SELECT
TBL.DELETE_FLG,
TBL.CONTENA_KEIKA_DATE,
TBL.CONTENA_KEIKA_BACK_COLOR,
TBL.CONTENA_KEIKA_BIKOU,
TBL.UPDATE_USER,
TBL.UPDATE_DATE,
TBL.UPDATE_PC,
TBL.CREATE_USER,
TBL.CREATE_DATE,
TBL.CREATE_PC,
TBL.TIME_STAMP
FROM 
dbo.M_CONTENA_KEIKA_DATE TBL
/*BEGIN*/WHERE
/*IF !data.CONTENA_KEIKA_DATE.IsNull*/TBL.CONTENA_KEIKA_DATE = /*data.CONTENA_KEIKA_DATE*/ /*END*/
/*IF !data.CONTENA_KEIKA_BACK_COLOR.IsNull*/AND TBL.CONTENA_KEIKA_BACK_COLOR= /*data.CONTENA_KEIKA_BACK_COLOR*/ /*END*/
/*IF data.CONTENA_KEIKA_BIKOU != null*/AND TBL.CONTENA_KEIKA_BIKOU LIKE '%' +  /*data.CONTENA_KEIKA_BIKOU*/ + '%'/*END*/
/*IF data.CREATE_USER != null*/AND TBL.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, TBL.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
/*IF data.UPDATE_USER != null*/AND TBL.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, TBL.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*IF !deletechuFlg*/AND TBL.DELETE_FLG = /*deletechuFlg*/0/*END*/
/*END*/
/*END*/
ORDER BY TBL.CONTENA_KEIKA_DATE