SELECT COUNT(SYSTEM_ID)
FROM
T_KEIRYOU_ENTRY
WHERE DELETE_FLG = 0
AND TAIRYUU_KBN = /*tairyuKbn*/
/*IF honjitsuKbn == 1*/AND CONVERT(DATETIME, CONVERT(nvarchar, DENPYOU_DATE, 111), 120) = CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)/*END*/
/*IF inoutKbn != 0*/AND KIHON_KEIRYOU = /*inoutKbn*//*END*/
/*IF kyotenCd != nulll*/AND KYOTEN_CD = /*kyotenCd*//*END*/