SELECT T.RAKURAKU_CUSTOMER_CD
FROM 
(SELECT RAKURAKU_CUSTOMER_CD FROM M_TORIHIKISAKI_SEIKYUU
 UNION
 SELECT RAKURAKU_CUSTOMER_CD FROM M_GYOUSHA
 UNION
 SELECT RAKURAKU_CUSTOMER_CD FROM M_GENBA) AS T
WHERE ISNUMERIC(T.RAKURAKU_CUSTOMER_CD) = 1