SELECT ISNULL(MIN(T.TORIHIKISAKI_CD),1) TORIHIKISAKI_CD
FROM (
		SELECT (TORIHIKISAKI_CD+1) TORIHIKISAKI_CD FROM M_TORIHIKISAKI WHERE ISNUMERIC(TORIHIKISAKI_CD)=1 
		UNION 
		SELECT (NYUUKINSAKI_CD+1) TORIHIKISAKI_CD FROM M_NYUUKINSAKI WHERE ISNUMERIC(NYUUKINSAKI_CD)=1
		UNION 
		SELECT (SYUKKINSAKI_CD+1) TORIHIKISAKI_CD FROM M_SYUKKINSAKI WHERE ISNUMERIC(SYUKKINSAKI_CD)=1
	) T
WHERE NOT EXISTS (
        SELECT TMP.TORIHIKISAKI_CD
		FROM (
			SELECT (CONVERT(INT, TORIHIKISAKI_CD+0)) TORIHIKISAKI_CD 
			FROM M_TORIHIKISAKI 
			WHERE ISNUMERIC(TORIHIKISAKI_CD)=1
			UNION
			SELECT (CONVERT(INT, NYUUKINSAKI_CD+0)) TORIHIKISAKI_CD 
			FROM M_NYUUKINSAKI 
			WHERE ISNUMERIC(NYUUKINSAKI_CD)=1
			UNION
			SELECT (CONVERT(INT, SYUKKINSAKI_CD+0)) TORIHIKISAKI_CD 
			FROM M_SYUKKINSAKI 
			WHERE ISNUMERIC(SYUKKINSAKI_CD)=1
		) TMP
		WHERE TMP.TORIHIKISAKI_CD = T.TORIHIKISAKI_CD
	)