SELECT
    M_TORIHIKISAKI.TORIHIKISAKI_CD AS TORIHIKISAKI_CD
   ,M_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU AS TORIHIKISAKI_NAME
   ,'' AS GYOUSHA_CD
   ,'' AS GENBA_CD
FROM M_TORIHIKISAKI
WHERE 
  /*IF selectType == 1*/
  M_TORIHIKISAKI.TORIHIKISAKI_CD = /*torihikisaki*/
  -- ELSE
  ISNULL(REPLACE(REPLACE(REPLACE(M_TORIHIKISAKI.TORIHIKISAKI_TEL, '-', ''), ')', ''), '(', ''), '') LIKE '%' + /*tel*/ + '%'
  /*END*/
ORDER BY  TORIHIKISAKI_CD  ASC
