SELECT DISTINCT N'引合現場マスタ' AS NAME FROM M_HIKIAI_GENBA WHERE HIKIAI_GYOUSHA_USE_FLG = 'False' AND GYOUSHA_CD = /*GYOUSHA_CD*/'' AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'基本品名単価マスタ' AS NAME FROM M_KIHON_HINMEI_TANKA WHERE (UNPAN_GYOUSHA_CD = /*GYOUSHA_CD*/'' OR NIOROSHI_GYOUSHA_CD = /*GYOUSHA_CD*/'') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'個別品名単価マスタ' AS NAME FROM M_KOBETSU_HINMEI_TANKA WHERE (GYOUSHA_CD = /*GYOUSHA_CD*/'' OR UNPAN_GYOUSHA_CD = /*GYOUSHA_CD*/'' OR NIOROSHI_GYOUSHA_CD = /*GYOUSHA_CD*/'') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'個別品名マスタ' AS NAME FROM M_KOBETSU_HINMEI WHERE GYOUSHA_CD = /*GYOUSHA_CD*/''  AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'車輌マスタ' AS NAME FROM M_SHARYOU WHERE GYOUSHA_CD = /*GYOUSHA_CD*/'' AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'運賃単価マスタ' AS NAME FROM M_UNCHIN_TANKA WHERE UNPAN_GYOUSHA_CD = /*GYOUSHA_CD*/'' AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'事業者マスタ' AS NAME FROM M_DENSHI_JIGYOUSHA WHERE GYOUSHA_CD = /*GYOUSHA_CD*/''
UNION
SELECT DISTINCT N'事業場マスタ' AS NAME FROM M_DENSHI_JIGYOUJOU WHERE GYOUSHA_CD = /*GYOUSHA_CD*/''
UNION
SELECT DISTINCT N'地域別許可番号マスタ' AS NAME FROM M_CHIIKIBETSU_KYOKA WHERE GYOUSHA_CD = /*GYOUSHA_CD*/'' AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'システム設定' AS NAME FROM M_SYS_INFO WHERE UKETSUKE_UPN_GYOUSHA_CD_DEFALUT = /*GYOUSHA_CD*/'' AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'現場マスタ' AS NAME
FROM M_GENBA
WHERE DELETE_FLG = 'False'
AND ((GYOUSHA_CD = /*GYOUSHA_CD*/'')
OR((MANI_HENSOUSAKI_GYOUSHA_CD_A = /*GYOUSHA_CD*/'')
OR (MANI_HENSOUSAKI_GYOUSHA_CD_B1 = /*GYOUSHA_CD*/'')
OR (MANI_HENSOUSAKI_GYOUSHA_CD_B2 = /*GYOUSHA_CD*/'')
OR (MANI_HENSOUSAKI_GYOUSHA_CD_B4 = /*GYOUSHA_CD*/'')
OR (MANI_HENSOUSAKI_GYOUSHA_CD_B6 = /*GYOUSHA_CD*/'')
OR (MANI_HENSOUSAKI_GYOUSHA_CD_C1 = /*GYOUSHA_CD*/'')
OR (MANI_HENSOUSAKI_GYOUSHA_CD_C2 = /*GYOUSHA_CD*/'')
OR (MANI_HENSOUSAKI_GYOUSHA_CD_D = /*GYOUSHA_CD*/'')
OR (MANI_HENSOUSAKI_GYOUSHA_CD_E = /*GYOUSHA_CD*/'')))
GROUP BY GYOUSHA_CD, GENBA_CD