SELECT 
    GEN.GENBA_CD AS GENBA_CD
    ,ISNULL(GEN.GENBA_NAME1,N'') AS GENBA_NAME1
    ,ISNULL(GEN.GENBA_ADDRESS1,N'') AS GENBA_ADDRESS1
    ,ISNULL(GEN.GENBA_NAME2,N'') AS GENBA_NAME2
    ,ISNULL(GEN.GENBA_ADDRESS2,N'') AS GENBA_ADDRESS2
    ,GEN.JISHA_KBN AS JISHA_KBN
FROM 
    dbo.M_GENBA GEN
WHERE GEN.GYOUSHA_CD = /*data.GYOUSHA_CD*/'000001'
  AND GEN.DELETE_FLG = 0
ORDER BY GEN.GENBA_CD
