SELECT 
    ITA.ITAKU_KEIYAKU_NO AS ITAKU_NO
    ,CAST(ITA.ITAKU_KEIYAKU_SHURUI AS VARCHAR(1)) AS ITAKU_SHURUI
    ,ITA.YUUKOU_BEGIN AS YUUKOU_BEGIN
    ,ITA.YUUKOU_END AS YUUKOU_END
    ,CAST(ITAKU_KEIYAKU_STATUS AS VARCHAR(1)) AS ITAKU_STATUS
	,ITA.SYSTEM_ID AS SYSTEM_ID
FROM 
    dbo.M_GYOUSHA GYO
    LEFT JOIN dbo.M_ITAKU_KEIYAKU_KIHON ITA ON ITA.HAISHUTSU_JIGYOUSHA_CD = GYO.GYOUSHA_CD
/*BEGIN*/WHERE
 /*IF data.HAISHUTSU_JIGYOUSHA_CD != null*/GYO.GYOUSHA_CD LIKE '%' + /*data.HAISHUTSU_JIGYOUSHA_CD*/'000001' + '%'/*END*/
 AND GYO.HAISHUTSU_NIZUMI_GYOUSHA_KBN = 1
 AND ITA.DELETE_FLG = 0
/*END*/
ORDER BY ITA.ITAKU_KEIYAKU_NO
