SELECT
    GURUPU.GURUPU_CD,
	GURUPU.GURUPU_NAME
FROM
    dbo.M_GURUPU_NYURYOKU GURUPU
/*BEGIN*/WHERE
    /*IF data.GURUPU_NAME != null*/GURUPU.GURUPU_NAME LIKE '%' +  /*data.GURUPU_NAME*/ + '%'/*END*/
/*END*/
AND  GURUPU.DELETE_FLG = 0
ORDER BY GURUPU.GURUPU_CD