SELECT DISTINCT N'引合業者マスタ' AS NAME FROM M_HIKIAI_GYOUSHA WHERE HIKIAI_TORIHIKISAKI_USE_FLG = 'True' AND TORIHIKISAKI_CD = /*TORIHIKISAKI_CD*/'' AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'引合現場マスタ' AS NAME FROM M_HIKiAI_GENBA WHERE HIKIAI_TORIHIKISAKI_USE_FLG = 'True' AND TORIHIKISAKI_CD = /*TORIHIKISAKI_CD*/'' AND DELETE_FLG = 'False'
