SELECT
    TORI.TORIHIKISAKI_CD,
    TORI.DELETE_FLG
FROM
    dbo.M_HIKIAI_TORIHIKISAKI TORI
/*BEGIN*/WHERE
 /*IF data.TORIHIKISAKI_CD != null*/
 TORI.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/'000001'
 /*END*/
/*END*/
ORDER BY TORI.TORIHIKISAKI_CD
