SELECT ISNULL(MIN(N.TORIHIKISAKI_CD),1) TORIHIKISAKI_CD
FROM (
		SELECT (TORIHIKISAKI_CD+1) TORIHIKISAKI_CD FROM M_HIKIAI_TORIHIKISAKI WHERE ISNUMERIC(TORIHIKISAKI_CD)=1 
	) N
WHERE N.TORIHIKISAKI_CD NOT IN (
		SELECT (TORIHIKISAKI_CD+0) TORIHIKISAKI_CD FROM M_HIKIAI_TORIHIKISAKI WHERE ISNUMERIC(TORIHIKISAKI_CD)=1
	)