SELECT 
    ISNULL(GYO.TEKIYOU_BEGIN,'1753/01/01') AS TEKIYOU_BEGIN
FROM 
    dbo.M_HIKIAI_GYOUSHA GYO
WHERE GYO.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/'000001'
  AND GYO.DELETE_FLG = 0
  AND HIKIAI_TORIHIKISAKI_USE_FLG = 1
UNION ALL
SELECT 
    ISNULL(GEN.TEKIYOU_BEGIN,'1753/01/01') AS TEKIYOU_BEGIN
FROM
    dbo.M_HIKIAI_GENBA GEN
WHERE GEN.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/'000001'
  AND GEN.DELETE_FLG = 0
  AND HIKIAI_TORIHIKISAKI_USE_FLG = 1
ORDER BY TEKIYOU_BEGIN
