SELECT HAIKI_SHURUI_CD,
       HAIKI_SHURUI_NAME,
       M_HOUKOKUSHO_BUNRUI.HOUKOKUSHO_BUNRUI_CD,
	   M_HOUKOKUSHO_BUNRUI.HOUKOKUSHO_BUNRUI_NAME
  FROM M_DENSHI_HAIKI_SHURUI (NOLOCK)
  LEFT JOIN M_HOUKOKUSHO_BUNRUI
      ON M_DENSHI_HAIKI_SHURUI.HOUKOKUSHO_BUNRUI_CD = M_HOUKOKUSHO_BUNRUI.HOUKOKUSHO_BUNRUI_CD