SELECT 
    KI.*
FROM 
    dbo.M_ITAKU_KEIYAKU_OBOE KI
/*BEGIN*/WHERE
 /*IF data.ITAKU_KEIYAKU_NO != null*/
 KI.ITAKU_KEIYAKU_NO = /*data.ITAKU_KEIYAKU_NO*/
 /*END*/
/*END*/
ORDER BY KI.ITAKU_KEIYAKU_NO
