SELECT M_OUTPUT_PATTERN_HIMO.SYSTEM_ID
     , M_OUTPUT_PATTERN_HIMO.SEQ
     , M_OUTPUT_PATTERN_HIMO.OUTPUT_KBN
     , M_OUTPUT_PATTERN_HIMO.PATTERN_NAME
     , M_OUTPUT_PATTERN_COLUMN_HIMO.DETAIL_SYSTEM_ID
     , M_OUTPUT_PATTERN_COLUMN_HIMO.KINOU_NO
     , M_OUTPUT_PATTERN_COLUMN_HIMO.KINOU_NAME
     , M_OUTPUT_PATTERN_COLUMN_HIMO.TABLE_NAME
     , M_OUTPUT_PATTERN_COLUMN_HIMO.KOUMOKU_RONRI_NAME
     , M_OUTPUT_PATTERN_COLUMN_HIMO.KOUMOKU_BUTSURI_NAME
     , M_OUTPUT_PATTERN_COLUMN_HIMO.SORT_NO
     , M_OUTPUT_PATTERN_COLUMN_HIMO.PRIORITY_NO
     , ISNULL(S_OUTPUT_COLUMN_SELECT.HISSU_KBN,'False') AS HISSU_KBN
     , CAST(M_OUTPUT_PATTERN_HIMO.TIME_STAMP AS int ) AS TIME_STAMP_MOP
     , M_OUTPUT_PATTERN_COLUMN_HIMO.TIME_STAMP AS TIME_STAMP_MOPC
FROM M_OUTPUT_PATTERN_HIMO WITH(NOLOCK)
INNER JOIN (
    SELECT SYSTEM_ID
         , MAX(SEQ) AS SEQ 
      FROM M_OUTPUT_PATTERN_HIMO WITH(NOLOCK) 
     WHERE DELETE_FLG = /*data.DELETE_FLG*/
    /*IF data.SYSTEM_ID != null && data.SYSTEM_ID != ''*/ AND SYSTEM_ID = /*data.SYSTEM_ID*//*END*/
    /*IF data.SEQ != null && data.SEQ != ''*/ AND SEQ = /*data.SEQ*//*END*/
     GROUP BY SYSTEM_ID
 )  AS MOP
    ON M_OUTPUT_PATTERN_HIMO.SYSTEM_ID = MOP.SYSTEM_ID AND M_OUTPUT_PATTERN_HIMO.SEQ = MOP.SEQ
  LEFT OUTER JOIN M_OUTPUT_PATTERN_COLUMN_HIMO WITH(NOLOCK)
    ON M_OUTPUT_PATTERN_HIMO.SYSTEM_ID = M_OUTPUT_PATTERN_COLUMN_HIMO.SYSTEM_ID AND M_OUTPUT_PATTERN_HIMO.SEQ = M_OUTPUT_PATTERN_COLUMN_HIMO.SEQ
  LEFT OUTER JOIN S_OUTPUT_COLUMN_SELECT WITH(NOLOCK)
    ON S_OUTPUT_COLUMN_SELECT.TABLE_NAME = M_OUTPUT_PATTERN_COLUMN_HIMO.TABLE_NAME
   AND S_OUTPUT_COLUMN_SELECT.KOUMOKU_BUTSURI_NAME = M_OUTPUT_PATTERN_COLUMN_HIMO.KOUMOKU_BUTSURI_NAME
   AND (CASE WHEN M_OUTPUT_PATTERN_COLUMN_HIMO.KINOU_NO = 1 THEN 9100
              WHEN M_OUTPUT_PATTERN_COLUMN_HIMO.KINOU_NO = 2 THEN 9140
              WHEN M_OUTPUT_PATTERN_COLUMN_HIMO.KINOU_NO = 3 THEN 9001
              WHEN M_OUTPUT_PATTERN_COLUMN_HIMO.KINOU_NO = 4 THEN 9002
              WHEN M_OUTPUT_PATTERN_COLUMN_HIMO.KINOU_NO = 5 THEN 9003
              WHEN M_OUTPUT_PATTERN_COLUMN_HIMO.KINOU_NO = 6 THEN 9080
              WHEN M_OUTPUT_PATTERN_COLUMN_HIMO.KINOU_NO = 7 THEN 9081
              WHEN M_OUTPUT_PATTERN_COLUMN_HIMO.KINOU_NO = 8 THEN 9090
              WHEN M_OUTPUT_PATTERN_COLUMN_HIMO.KINOU_NO = 9 THEN 9160
              WHEN M_OUTPUT_PATTERN_COLUMN_HIMO.KINOU_NO = 10 THEN 9170
        END) = S_OUTPUT_COLUMN_SELECT.DENSHU_KBN_CD
 WHERE M_OUTPUT_PATTERN_HIMO.DELETE_FLG = /*data.DELETE_FLG*/
/*IF data.SYSTEM_ID != null && data.SYSTEM_ID != ''*/ AND M_OUTPUT_PATTERN_HIMO.SYSTEM_ID = /*data.SYSTEM_ID*//*END*/
/*IF data.SEQ != null && data.SEQ != ''*/ AND M_OUTPUT_PATTERN_HIMO.SEQ = /*data.SEQ*//*END*/
AND S_OUTPUT_COLUMN_SELECT.DENSHU_KBN_CD IN ('9100','9140','9001','9002','9003','9080','9081','9090','9160','9170')

