SELECT S_OUTPUT_COLUMN_SELECT.DENSHU_KBN_CD
     , S_OUTPUT_COLUMN_SELECT.OUTPUT_KBN
     , S_OUTPUT_COLUMN_SELECT.KOUMOKU_ID
     , S_OUTPUT_COLUMN_SELECT.DISP_KOUMOKU_NAME
     , S_OUTPUT_COLUMN_SELECT.HISSU_KBN
     , S_OUTPUT_COLUMN_SELECT.TABLE_NAME
     , S_OUTPUT_COLUMN_SELECT.KOUMOKU_BUTSURI_NAME
  FROM S_OUTPUT_COLUMN_SELECT WITH (NOLOCK)
  WHERE NOT EXISTS(
    SELECT SYSTEM_ID, SEQ
      FROM M_OUTPUT_PATTERN_HIMO WITH(NOLOCK)
    INNER JOIN (
        SELECT SYSTEM_ID
             , MAX(SEQ) AS SEQ 
          FROM M_OUTPUT_PATTERN_HIMO WITH(NOLOCK) 
         WHERE DELETE_FLG = /*data.DELETE_FLG*/
        /*IF data.SYSTEM_ID != null && data.SYSTEM_ID != ''*/ AND SYSTEM_ID = /*data.SYSTEM_ID*//*END*/
        /*IF data.SEQ != null && data.SEQ != ''*/ AND SEQ = /*data.SEQ*//*END*/
         GROUP BY SYSTEM_ID
     ) AS MOP
        ON M_OUTPUT_PATTERN_HIMO.SYSTEM_ID = MOP.SYSTEM_ID AND M_OUTPUT_PATTERN_HIMO.SEQ = MOP.SEQ
      LEFT OUTER JOIN M_OUTPUT_PATTERN_COLUMN_HIMO WITH(NOLOCK)
        ON M_OUTPUT_PATTERN_HIMO.SYSTEM_ID = M_OUTPUT_PATTERN_COLUMN_HIMO.SYSTEM_ID 
       AND M_OUTPUT_PATTERN_HIMO.SEQ = M_OUTPUT_PATTERN_COLUMN_HIMO.SEQ
    WHERE M_OUTPUT_PATTERN_HIMO.DELETE_FLG = /*data.DELETE_FLG*/
    /*IF data.SYSTEM_ID != null && data.SYSTEM_ID != ''*/ AND M_OUTPUT_PATTERN_HIMO.SYSTEM_ID = /*data.SYSTEM_ID*//*END*/
    /*IF data.SEQ != null && data.SEQ != ''*/ AND M_OUTPUT_PATTERN_HIMO.SEQ = /*data.SEQ*//*END*/
      AND S_OUTPUT_COLUMN_SELECT.TABLE_NAME = M_OUTPUT_PATTERN_COLUMN_HIMO.TABLE_NAME
      AND S_OUTPUT_COLUMN_SELECT.KOUMOKU_BUTSURI_NAME = M_OUTPUT_PATTERN_COLUMN_HIMO.KOUMOKU_BUTSURI_NAME
)
/*IF data.DENSHU_KBN_CD != null && data.DENSHU_KBN_CD != ''*/ AND S_OUTPUT_COLUMN_SELECT.DENSHU_KBN_CD = /*data.DENSHU_KBN_CD*//*END*/
/*IF data.OUTPUT_KBN != null && data.OUTPUT_KBN != ''*/ AND S_OUTPUT_COLUMN_SELECT.OUTPUT_KBN = /*data.OUTPUT_KBN*//*END*/
/*IF data.KOUMOKU_ID != null && data.KOUMOKU_ID != ''*/ AND S_OUTPUT_COLUMN_SELECT.KOUMOKU_ID = /*data.KOUMOKU_ID*//*END*/