SELECT
  TOC.KANRI_ID 
FROM
  DT_MF_TOC AS TOC 
  INNER JOIN DT_R18 
    ON TOC.KANRI_ID = DT_R18.KANRI_ID 
    AND TOC.LATEST_SEQ = DT_R18.SEQ 
    AND DT_R18.MANIFEST_ID IS NOT NULL 
    AND DT_R18.MANIFEST_ID <> '' 
    AND ( 
      DT_R18.FIRST_MANIFEST_FLAG IS NULL 
      or DT_R18.FIRST_MANIFEST_FLAG = ''
    ) 
  INNER JOIN (
        SELECT
            EX.SYSTEM_ID AS EX_SYS_ID
            ,EX.SEQ AS EX_SEQ
            ,EX.HST_GYOUSHA_CD
            ,EX.HST_GENBA_CD
            ,EX.SBN_GYOUSHA_CD
            ,EX.KANRI_ID AS EX_KANRI_ID
            ,EX.GENNYOU_SUU EX_GENNYOU_SUU
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN convert(int,MIX.TIME_STAMP) ELSE convert(int,EX.TIME_STAMP) END) AS CONNECT_TIME_STAMP
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.DETAIL_SYSTEM_ID ELSE EX.SYSTEM_ID END) AS CONNECT_SYSTEM_ID
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.SEQ ELSE EX.SEQ END) AS CONNECT_SEQ
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.MANIFEST_ID ELSE EX.MANIFEST_ID END) AS CONNECT_MANIFEST_ID
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.HAIKI_DAI_CODE + MIX.HAIKI_CHU_CODE + MIX.HAIKI_SHO_CODE
                ELSE R18.HAIKI_DAI_CODE + R18.HAIKI_CHU_CODE + R18.HAIKI_SHO_CODE END) AS CONNECT_HAIKI_SHURUI_CD
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.HAIKI_NAME_CD ELSE EX.HAIKI_NAME_CD END) AS CONNECT_HAIKI_NAME_CD
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN M_DENSHI_HAIKI_SHURUI_MIX.HOUKOKUSHO_BUNRUI_CD ELSE M_DENSHI_HAIKI_SHURUI_R18.HOUKOKUSHO_BUNRUI_CD END) AS CONNECT_HOUKOKUSHO_BUNRUI_CD
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.SBN_HOUHOU_CD ELSE R18.SBN_WAY_CODE END) AS CONNECT_SBN_HOUHOU_CD
            ,MIX.*
        FROM DT_R18_EX AS EX
        INNER JOIN (
                SELECT DT_R18.* FROM DT_R18
                INNER JOIN DT_MF_TOC ON
                    ((DT_R18.KANRI_ID = DT_MF_TOC.KANRI_ID) AND (DT_R18.SEQ = DT_MF_TOC.LATEST_SEQ))
            ) AS R18
                ON EX.KANRI_ID = R18.KANRI_ID
        LEFT JOIN (
                SELECT
                    M_DENSHI_HAIKI_SHURUI.HAIKI_SHURUI_NAME
                    ,M_HAIKI_NAME.HAIKI_NAME
                    ,M_HOUKOKUSHO_BUNRUI.HOUKOKUSHO_BUNRUI_NAME_RYAKU
                    ,M_HOUKOKUSHO_BUNRUI.HOUKOKUSHO_BUNRUI_CD
                    ,M_UNIT.UNIT_NAME_RYAKU
                    ,M_SHOBUN_HOUHOU.SHOBUN_HOUHOU_NAME_RYAKU
                    ,DT_R18_MIX.*
                FROM DT_R18_MIX
                LEFT JOIN (SELECT * FROM M_DENSHI_HAIKI_SHURUI WHERE DELETE_FLG = 0) AS M_DENSHI_HAIKI_SHURUI
                    ON (DT_R18_MIX.HAIKI_DAI_CODE + DT_R18_MIX.HAIKI_CHU_CODE + DT_R18_MIX.HAIKI_SHO_CODE) = M_DENSHI_HAIKI_SHURUI.HAIKI_SHURUI_CD
                LEFT JOIN (SELECT * FROM M_HAIKI_NAME WHERE DELETE_FLG = 0) AS M_HAIKI_NAME
                    ON DT_R18_MIX.HAIKI_NAME_CD = M_HAIKI_NAME.HAIKI_NAME_CD
                LEFT JOIN (SELECT * FROM M_HOUKOKUSHO_BUNRUI WHERE DELETE_FLG = 0) AS M_HOUKOKUSHO_BUNRUI
                    ON M_DENSHI_HAIKI_SHURUI.HOUKOKUSHO_BUNRUI_CD = M_HOUKOKUSHO_BUNRUI.HOUKOKUSHO_BUNRUI_CD
                LEFT JOIN (SELECT * FROM M_UNIT WHERE DELETE_FLG = 0) AS M_UNIT
                    ON DT_R18_MIX.HAIKI_UNIT_CD = M_UNIT.UNIT_CD
                LEFT JOIN (SELECT * FROM M_SHOBUN_HOUHOU WHERE DELETE_FLG = 0) AS M_SHOBUN_HOUHOU
                    ON DT_R18_MIX.SBN_HOUHOU_CD = M_SHOBUN_HOUHOU.SHOBUN_HOUHOU_CD
                WHERE ((DT_R18_MIX.DELETE_FLG = 0) AND (DT_R18_MIX.SBN_ENDREP_KBN = 1))
            ) AS MIX
                ON EX.SYSTEM_ID = MIX.SYSTEM_ID
        LEFT JOIN (SELECT * FROM M_DENSHI_HAIKI_SHURUI WHERE DELETE_FLG = 0) AS M_DENSHI_HAIKI_SHURUI_MIX
            ON (MIX.HAIKI_DAI_CODE + MIX.HAIKI_CHU_CODE + MIX.HAIKI_SHO_CODE) = M_DENSHI_HAIKI_SHURUI_MIX.HAIKI_SHURUI_CD
        LEFT JOIN (SELECT * FROM M_DENSHI_HAIKI_SHURUI WHERE DELETE_FLG = 0) AS M_DENSHI_HAIKI_SHURUI_R18
            ON (R18.HAIKI_DAI_CODE + R18.HAIKI_CHU_CODE + R18.HAIKI_SHO_CODE) = M_DENSHI_HAIKI_SHURUI_R18.HAIKI_SHURUI_CD
        WHERE EX.DELETE_FLG = 0
    ) AS R18EX
        ON R18EX.EX_KANRI_ID = DT_R18.KANRI_ID
  LEFT JOIN T_MANIFEST_RELATION AS TMR
    ON R18EX.SYSTEM_ID = TMR.FIRST_SYSTEM_ID
    AND TMR.FIRST_HAIKI_KBN_CD = 4
    AND TMR.DELETE_FLG = 0 
 INNER JOIN DT_R19_EX AS MAXR19EX 
    ON R18EX.EX_SYS_ID = MAXR19EX.SYSTEM_ID
   AND R18EX.EX_SEQ = MAXR19EX.SEQ
 INNER JOIN DT_R19 AS MAXR19 
    ON MAXR19EX.KANRI_ID = MAXR19.KANRI_ID 
   AND MAXR19EX.UPN_ROUTE_NO = MAXR19.UPN_ROUTE_NO 
 INNER JOIN (SELECT DT_R19.KANRI_ID 
                   , DT_R19.SEQ 
                   , MAX(DT_R19.UPN_ROUTE_NO) AS UPN_ROUTE_NO 
                FROM DT_MF_TOC 
               INNER JOIN DT_R19 
                  ON DT_MF_TOC.KANRI_ID = DT_R19.KANRI_ID
                 AND DT_MF_TOC.LATEST_SEQ = DT_R19.SEQ
                 WHERE DT_R19.UPN_END_DATE IS NOT NULL
                GROUP BY DT_R19.KANRI_ID 
                    , DT_R19.SEQ 
             ) AS SEARCHR19 
    ON MAXR19.KANRI_ID = SEARCHR19.KANRI_ID 
   AND MAXR19.SEQ = SEARCHR19.SEQ 
   AND MAXR19.UPN_ROUTE_NO = SEARCHR19.UPN_ROUTE_NO
 INNER JOIN DT_R19_EX AS MINR19EX 
    ON R18EX.EX_SYS_ID = MINR19EX.SYSTEM_ID 
   AND R18EX.EX_SEQ = MINR19EX.SEQ 
   AND MINR19EX.UPN_ROUTE_NO = 1
   AND MINR19EX.DELETE_FLG = 0
 INNER JOIN DT_R19 AS MINR19 
    ON MINR19EX.KANRI_ID = MINR19.KANRI_ID 
   AND TOC.LATEST_SEQ = MINR19.SEQ
   AND MINR19EX.UPN_ROUTE_NO =  MINR19.UPN_ROUTE_NO 
  LEFT OUTER JOIN M_GENBA MGB_SHOBUN 
    ON MGB_SHOBUN.GYOUSHA_CD = MAXR19EX.UPNSAKI_GYOUSHA_CD 
    AND MGB_SHOBUN.GENBA_CD = MAXR19EX.UPNSAKI_GENBA_CD 
    AND MGB_SHOBUN.DELETE_FLG = 0 
WHERE
  TOC.KANRI_ID = /*kanriId*/'0' 
  AND TMR.FIRST_SYSTEM_ID IS NULL 
  AND DT_R18.SBN_END_DATE IS NOT NULL 
  AND DT_R18.SBN_ENDREP_FLAG = 1 
  AND DT_R18.SBN_ENDREP_KBN = 1 
  AND TOC.STATUS_FLAG = 4 
  AND MGB_SHOBUN.JISHA_KBN = 1
