SELECT
  TME.SYSTEM_ID 
FROM
  T_MANIFEST_ENTRY AS TME 
  INNER JOIN T_MANIFEST_DETAIL AS TMD 
    ON TME.SYSTEM_ID = TMD.SYSTEM_ID 
    AND TME.SEQ = TMD.SEQ 
  INNER JOIN T_MANIFEST_UPN AS MAX_TMU 
    ON TME.SYSTEM_ID = MAX_TMU.SYSTEM_ID 
    AND TME.SEQ = MAX_TMU.SEQ 
  INNER JOIN (SELECT T_MANIFEST_ENTRY.SYSTEM_ID 
           , T_MANIFEST_ENTRY.SEQ 
           , MAX(T_MANIFEST_UPN.UPN_ROUTE_NO) AS UPN_ROUTE_NO
        FROM T_MANIFEST_ENTRY 
       INNER JOIN T_MANIFEST_UPN 
          ON T_MANIFEST_ENTRY.SYSTEM_ID = T_MANIFEST_UPN.SYSTEM_ID 
         AND T_MANIFEST_ENTRY.SEQ = T_MANIFEST_UPN.SEQ 
       WHERE T_MANIFEST_ENTRY.DELETE_FLG = 'false' 
         AND 
         (
         ((T_MANIFEST_ENTRY.HAIKI_KBN_CD = '1' OR T_MANIFEST_ENTRY.HAIKI_KBN_CD = '2') AND T_MANIFEST_UPN.UPN_END_DATE IS NOT NULL)
         OR (T_MANIFEST_ENTRY.HAIKI_KBN_CD = '3' AND T_MANIFEST_UPN.UPN_SAKI_KBN IS NOT NULL)
         )
       GROUP BY T_MANIFEST_ENTRY.SYSTEM_ID 
           , T_MANIFEST_ENTRY.SEQ 
      ) AS TMU_SEARCH
    ON MAX_TMU.SYSTEM_ID = TMU_SEARCH.SYSTEM_ID 
   AND MAX_TMU.SEQ = TMU_SEARCH.SEQ 
   AND MAX_TMU.UPN_ROUTE_NO = TMU_SEARCH.UPN_ROUTE_NO
  LEFT OUTER JOIN M_GENBA MGB_SHOBUN 
    ON MGB_SHOBUN.GYOUSHA_CD = TME.SBN_GYOUSHA_CD 
    AND MGB_SHOBUN.GENBA_CD = MAX_TMU.UPN_SAKI_GENBA_CD 
    AND MGB_SHOBUN.DELETE_FLG = 0 
  LEFT OUTER JOIN M_GENBA MGB_TSUMIKAE 
    ON MGB_TSUMIKAE.GYOUSHA_CD = MAX_TMU.UPN_SAKI_GYOUSHA_CD 
    AND MGB_TSUMIKAE.GENBA_CD = MAX_TMU.UPN_SAKI_GENBA_CD 
    AND MGB_TSUMIKAE.DELETE_FLG = 0 
WHERE
  TME.DELETE_FLG = 'false' 
  AND TME.FIRST_MANIFEST_KBN = 'false' 
  AND TME.MANIFEST_ID IS NOT NULL 
  AND TME.MANIFEST_ID != '' 
  AND TMD.LAST_SBN_END_DATE IS NULL 
  AND TMD.SBN_END_DATE IS NOT NULL 
  AND ( 
    ( 
      ( 
        TME.HAIKI_KBN_CD = '1' 
        OR TME.HAIKI_KBN_CD = '2'
      ) 
      AND MGB_SHOBUN.JISHA_KBN = 1
    ) 
    OR ( 
      TME.HAIKI_KBN_CD = '3' 
      AND MGB_TSUMIKAE.JISHA_KBN = 1 
      AND MGB_TSUMIKAE.SHOBUN_NIOROSHI_GENBA_KBN = 1
    )
  ) 
   AND TME.SYSTEM_ID = /*systemId*/0