SELECT TME.HST_GYOUSHA_CD
       ,HST_GENBA_CD
       ,CONVERT(INT,TME.TIME_STAMP) AS TME_TIME_STAMP
       ,TMD.*
FROM T_MANIFEST_ENTRY TME
INNER JOIN T_MANIFEST_DETAIL TMD
ON TME.SYSTEM_ID = TMD.SYSTEM_ID
AND TME.SEQ = TMD.SEQ
WHERE TME.DELETE_FLG  = 0
  AND TME.MANIFEST_ID = /*data.MANIFEST_ID*/0
  AND TME.HAIKI_KBN_CD = /*data.HAIKI_KBN_CD*/0
  AND TME.FIRST_MANIFEST_KBN = /*data.FIRST_MANIFEST_KBN*/0
  AND TMD.HAIKI_SHURUI_CD = /*HAIKI_SHURUI_CD*/0
  AND ISNULL(TMD.HAIKI_NAME_CD,'') = /*HAIKI_NAME_CD*/0