SELECT TME.*
FROM T_MANIFEST_ENTRY TME
INNER JOIN T_MANIFEST_RELATION RE
ON TME.SYSTEM_ID = RE.NEXT_SYSTEM_ID
AND TME.HAIKI_KBN_CD = RE.NEXT_HAIKI_KBN_CD
WHERE TME.DELETE_FLG  = 0
  AND RE.DELETE_FLG  = 0
  AND TME.MANIFEST_ID = /*data.MANIFEST_ID*/
  AND TME.HAIKI_KBN_CD = /*data.HAIKI_KBN_CD*/