SELECT TME.*
FROM T_MANIFEST_ENTRY TME
INNER JOIN T_MANIFEST_DETAIL TMD
ON TME.SYSTEM_ID = TMD.SYSTEM_ID
AND TME.SEQ = TMD.SEQ
INNER JOIN T_MANIFEST_RELATION RE
ON TMD.DETAIL_SYSTEM_ID = RE.FIRST_SYSTEM_ID
AND TME.HAIKI_KBN_CD = RE.FIRST_HAIKI_KBN_CD
WHERE TME.DELETE_FLG  = 0
  AND RE.DELETE_FLG  = 0
  AND TME.MANIFEST_ID = /*data.MANIFEST_ID*/
  AND TME.HAIKI_KBN_CD = /*data.HAIKI_KBN_CD*/
  /*IF detailSystemId != ''*/  AND TMD.DETAIL_SYSTEM_ID = /*detailSystemId*/0 /*END*/