----二次マニフェストのデータを取得
SELECT
  R18_EX.SYSTEM_ID AS SYSTEM_ID
  ,R18_EX.SEQ AS SEQ
  ,MAX(R13_EX.LAST_SBN_GYOUSHA_CD) AS LAST_SBN_GYOUSHA_CD
  ,MAX(R13_EX.LAST_SBN_GENBA_CD) AS LAST_SBN_GENBA_CD
  ,MAX(R18.LAST_SBN_END_DATE) AS LAST_SBN_END_DATE
  ,COUNT(R18_EX.SYSTEM_ID) AS LINE_COUNT

FROM DT_MF_TOC AS MF_TOC 
  INNER JOIN DT_R18 AS R18 
  ON MF_TOC.KANRI_ID = R18.KANRI_ID
  AND MF_TOC.LATEST_SEQ = R18.SEQ
  LEFT JOIN DT_R18_EX AS R18_EX
  ON R18.KANRI_ID = R18_EX.KANRI_ID
  AND R18_EX.DELETE_FLG = 0
  LEFT JOIN DT_R13_EX AS R13_EX
  ON R18_EX.SYSTEM_ID = R13_EX.SYSTEM_ID
  AND R18_EX.SEQ = R13_EX.SEQ
  AND R18_EX.KANRI_ID = R13_EX.KANRI_ID
  LEFT JOIN M_GYOUSHA AS HST_GYOUSHA ON R18_EX.HST_GYOUSHA_CD = HST_GYOUSHA.GYOUSHA_CD

WHERE R18_EX.DELETE_FLG = 0
  /*IF data.SECOND_KANRI_ID != null*/
    AND MF_TOC.KANRI_ID = /*data.SECOND_KANRI_ID*/
  /*END*/
  AND (R18.FIRST_MANIFEST_FLAG IS NOT NULL AND HST_GYOUSHA.JISHA_KBN = 1)

GROUP BY
  R18_EX.SYSTEM_ID
  ,R18_EX.SEQ

ORDER BY 
  SEQ DESC