SELECT 
TMKK.SYSTEM_ID
,TMKK.SEQ
,TMKK.REC_NO
,TMKK.NISUGATA_CD
,TMKK.NISUGATA_NAME
,TMKK.PRT_FLG
 FROM T_MANIFEST_KP_NISUGATA TMKK
WHERE TMKK.SYSTEM_ID = /*data.SYSTEM_ID*/ AND TMKK.SEQ =  /*data.SEQ*/