//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorihikisakiIchiran.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KYOTEN_CD_TEXT {
            get {
                return ((string)(this["KYOTEN_CD_TEXT"]));
            }
            set {
                this["KYOTEN_CD_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ICHIRAN_ALERT_KENSUU {
            get {
                return ((string)(this["ICHIRAN_ALERT_KENSUU"]));
            }
            set {
                this["ICHIRAN_ALERT_KENSUU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TORIHIKISAKI_FURIGANA_TEXT {
            get {
                return ((string)(this["TORIHIKISAKI_FURIGANA_TEXT"]));
            }
            set {
                this["TORIHIKISAKI_FURIGANA_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TORIHIKISAKI_NAME1_TEXT {
            get {
                return ((string)(this["TORIHIKISAKI_NAME1_TEXT"]));
            }
            set {
                this["TORIHIKISAKI_NAME1_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TORIHIKISAKI_NAME2_TEXT {
            get {
                return ((string)(this["TORIHIKISAKI_NAME2_TEXT"]));
            }
            set {
                this["TORIHIKISAKI_NAME2_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TORIHIKISAKI_NAME_RYAKU_TEXT {
            get {
                return ((string)(this["TORIHIKISAKI_NAME_RYAKU_TEXT"]));
            }
            set {
                this["TORIHIKISAKI_NAME_RYAKU_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TORIHIKISAKI_TODOUFUKEN_CD_TEXT {
            get {
                return ((string)(this["TORIHIKISAKI_TODOUFUKEN_CD_TEXT"]));
            }
            set {
                this["TORIHIKISAKI_TODOUFUKEN_CD_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TORIHIKISAKI_ADDRESS_TEXT {
            get {
                return ((string)(this["TORIHIKISAKI_ADDRESS_TEXT"]));
            }
            set {
                this["TORIHIKISAKI_ADDRESS_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime TEKIYOU_BEGIN_VALUE {
            get {
                return ((global::System.DateTime)(this["TEKIYOU_BEGIN_VALUE"]));
            }
            set {
                this["TEKIYOU_BEGIN_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime TEKIYOU_END_VALUE {
            get {
                return ((global::System.DateTime)(this["TEKIYOU_END_VALUE"]));
            }
            set {
                this["TEKIYOU_END_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ICHIRAN_HYOUJI_JOUKEN_TEKIYOU {
            get {
                return ((bool)(this["ICHIRAN_HYOUJI_JOUKEN_TEKIYOU"]));
            }
            set {
                this["ICHIRAN_HYOUJI_JOUKEN_TEKIYOU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ICHIRAN_HYOUJI_JOUKEN_DELETED {
            get {
                return ((bool)(this["ICHIRAN_HYOUJI_JOUKEN_DELETED"]));
            }
            set {
                this["ICHIRAN_HYOUJI_JOUKEN_DELETED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ICHIRAN_HYOUJI_JOUKEN_TEKIYOUGAI {
            get {
                return ((bool)(this["ICHIRAN_HYOUJI_JOUKEN_TEKIYOUGAI"]));
            }
            set {
                this["ICHIRAN_HYOUJI_JOUKEN_TEKIYOUGAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TORIHIKISAKI_CD_TEXT {
            get {
                return ((string)(this["TORIHIKISAKI_CD_TEXT"]));
            }
            set {
                this["TORIHIKISAKI_CD_TEXT"] = value;
            }
        }
    }
}
