SELECT MCN.COURSE_NAME_CD, MCN.COURSE_NAME_RYAKU, MCN.KYOTEN_CD, KT.KYOTEN_NAME
FROM M_COURSE_NAME MCN
LEFT JOIN M_KYOTEN KT
ON KT.KYOTEN_CD = MCN.KYOTEN_CD
WHERE 1 = 1
AND MCN.DELETE_FLG = 0
/*IF !data.MONDAY.IsNull && data.MONDAY.IsTrue */ AND MCN.MONDAY = '1'/*END*/
/*IF !data.TUESDAY.IsNull && data.TUESDAY.IsTrue */ AND MCN.TUESDAY = '1'/*END*/
/*IF !data.WEDNESDAY.IsNull && data.WEDNESDAY.IsTrue */ AND MCN.WEDNESDAY = '1'/*END*/
/*IF !data.THURSDAY.IsNull && data.THURSDAY.IsTrue */ AND MCN.THURSDAY = '1'/*END*/
/*IF !data.FRIDAY.IsNull && data.FRIDAY.IsTrue */ AND MCN.FRIDAY = '1'/*END*/
/*IF !data.SATURDAY.IsNull && data.SATURDAY.IsTrue */ AND MCN.SATURDAY = '1'/*END*/
/*IF !data.SUNDAY.IsNull && data.SUNDAY.IsTrue */ AND MCN.SUNDAY = '1'/*END*/
ORDER BY
MCN.COURSE_NAME_CD, MCN.COURSE_NAME_RYAKU