SELECT MC.COURSE_NAME_CD AS DETAIL_COURSE_NAME_CD,
    MCN.COURSE_NAME_RYAKU AS DETAIL_COURSE_NAME,
    convert(varchar,MC.DAY_CD) AS DETAIL_DAY_CD,
    CASE MC.DAY_CD
      WHEN 1 THEN '月'
      WHEN 2 THEN '火'
      WHEN 3 THEN '水'
      WHEN 4 THEN '木'
      WHEN 5 THEN '金'
      WHEN 6 THEN '土'
      WHEN 7 THEN '日'
      ELSE ''
      END AS DETAIL_DAY_NAME,
    MCD.ROUND_NO AS DETAIL_ROUND_NO,
    MCD.GYOUSHA_CD AS DETAIL_GYOUSHA_CD,
    MGY.GYOUSHA_NAME_RYAKU AS DETAIL_GYOUSHA_NAME,
    MCD.GENBA_CD AS DETAIL_GENBA_CD,
    MGE.GENBA_NAME_RYAKU AS DETAIL_GENBA_NAME,
    convert(varchar,MCDI.INPUT_KBN) AS DETAIL_INPUT_KBN,
    CASE MCDI.INPUT_KBN
      WHEN 1 THEN '直接入力'
      WHEN 2 THEN '組込'
      ELSE ''
      END AS DETAIL_INPUT_KBN_NM,
    MCDI.NIOROSHI_NO AS DETAIL_NIOROSHI_NO,
    MCDI.HINMEI_CD AS DETAIL_HINMEI_CD,
    H.HINMEI_NAME_RYAKU AS DETAIL_HINMEI_NAME,
    MCDI.DENPYOU_KBN_CD AS DETAIL_DENPYOU_KBN_CD,
    DK.DENPYOU_KBN_NAME_RYAKU AS DETAIL_DENPYOU_KBN_NAME,
    convert(varchar,MCDI.UNIT_CD) AS DETAIL_UNIT_CD,
    U.UNIT_NAME_RYAKU AS DETAIL_UNIT_NAME,
    MCDI.KANSANCHI AS DETAIL_KANSANCHI,
    MCDI.KANSAN_UNIT_CD AS DETAIL_KANSAN_UNIT_CD,
    KU.UNIT_NAME_RYAKU AS DETAIL_KANSAN_UNIT_NAME,
    ISNULL(MCDI.KANSAN_UNIT_MOBILE_OUTPUT_FLG,'false') AS DETAIL_YOU_KINYU,
    ISNULL(MCDI.ANBUN_FLG,'false') AS DETAIL_ANBUN_FLG,
    convert(varchar,MCDI.KEIYAKU_KBN) AS DETAIL_KEIYAKU_KBN,
    CASE MCDI.KEIYAKU_KBN
      WHEN 1 THEN '定期'
      WHEN 2 THEN '単価'
      WHEN 3 THEN '回収のみ'
      ELSE ''
      END AS DETAIL_KEIYAKU_KBN_NM,
    convert(varchar,MCDI.KEIJYOU_KBN) AS DETAIL_KEIJYOU_KBN,
    CASE MCDI.KEIJYOU_KBN
      WHEN 1 THEN '伝票'
      WHEN 2 THEN '合算'
      ELSE ''
      END AS DETAIL_KEIJYOU_KBN_NM,
    MCDI.TEKIYOU_BEGIN AS DETAIL_TEKIYOU_BEGIN,
    MCDI.TEKIYOU_END AS DETAIL_TEKIYOU_END
FROM M_COURSE MC
LEFT JOIN M_COURSE_DETAIL MCD ON MC.DAY_CD = MCD.DAY_CD AND MC.COURSE_NAME_CD = MCD.COURSE_NAME_CD
LEFT JOIN M_COURSE_DETAIL_ITEMS MCDI ON MCD.DAY_CD = MCDI.DAY_CD AND MCD.COURSE_NAME_CD = MCDI.COURSE_NAME_CD AND MCD.REC_ID = MCDI.REC_ID
LEFT JOIN M_COURSE_NAME MCN ON MC.COURSE_NAME_CD = MCN.COURSE_NAME_CD
LEFT JOIN M_GYOUSHA MGY ON MGY.GYOUSHA_CD = MCD.GYOUSHA_CD
LEFT JOIN M_GENBA MGE ON MGE.GYOUSHA_CD = MCD.GYOUSHA_CD AND MGE.GENBA_CD = MCD.GENBA_CD
LEFT JOIN M_HINMEI H ON H.HINMEI_CD = MCDI.HINMEI_CD
LEFT JOIN M_UNIT U ON U.UNIT_CD = MCDI.UNIT_CD
LEFT JOIN M_UNIT KU ON KU.UNIT_CD = MCDI.KANSAN_UNIT_CD
LEFT JOIN M_DENPYOU_KBN DK ON DK.DENPYOU_KBN_CD = MCDI.DENPYOU_KBN_CD
WHERE 1 = 1
/*IF data.DAY_CD != null && data.DAY_CD != '' && data.DAY_CD != '8' */ AND MC.DAY_CD = /*data.DAY_CD*/'1'/*END*/
/*IF data.COURSE_NAME_CD != null && data.COURSE_NAME_CD != ''*/AND MC.COURSE_NAME_CD = /*data.COURSE_NAME_CD*/'000001'/*END*/
/*IF data.GYOUSHA_CD != null && data.GYOUSHA_CD != ''*/AND MCD.GYOUSHA_CD = /*data.GYOUSHA_CD*/'000001'/*END*/
/*IF data.GENBA_CD != null && data.GENBA_CD != ''*/AND MCD.GENBA_CD = /*data.GENBA_CD*/'000001'/*END*/
/*IF data.HINMEI_CD != null && data.HINMEI_CD != ''*/AND MCDI.HINMEI_CD = /*data.HINMEI_CD*/'000001'/*END*/
ORDER BY
MC.COURSE_NAME_CD,
MC.DAY_CD,
MCD.ROUND_NO,
MCD.GYOUSHA_CD,
MCD.GENBA_CD,
MCDI.INPUT_KBN,
MCDI.NIOROSHI_NO,
MCDI.HINMEI_CD,
MCDI.DENPYOU_KBN_CD,
MCDI.UNIT_CD,
MCDI.KANSAN_UNIT_CD,
MCDI.KEIYAKU_KBN,
MCDI.KEIJYOU_KBN,
MCDI.TEKIYOU_BEGIN,
MCDI.TEKIYOU_END