//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shougun.Core.Scale.KeiryouNyuuryoku.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DenpyouCtrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DenpyouCtrl"]));
            }
            set {
                this["DenpyouCtrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DetailCtrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DetailCtrl"]));
            }
            set {
                this["DetailCtrl"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>HINMEI_CD:品名CD:True:1</string>
  <string>HINMEI_NAME:品名:True:2</string>
  <string>KEIRYOU_TIME:計量時間:True:4</string>
  <string>STACK_JYUURYOU:総重量:True:5</string>
  <string>EMPTY_JYUURYOU:空車重量:True:6</string>
  <string>CHOUSEI_JYUURYOU:調整(Kg):True:7</string>
  <string>CHOUSEI_PERCENT:調整(%):True8</string>
  <string>YOUKI_CD:容器CD:True:9</string>
  <string>YOUKI_SUURYOU:容器数量:True:10</string>
  <string>YOUKI_JYUURYOU:容器重量:True:11</string>
  <string>SUURYOU:数量:True:12</string>
  <string>UNIT_CD:単位CD:True:13</string>
  <string>TANKA:単価:True:14</string>
  <string>KINGAKU:金額:True:15</string>
  <string>MEISAI_BIKOU:明細備考:True:16</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ApDetailCtrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ApDetailCtrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>KYOTEN_CD:拠点CD:True:0</string>\r\n  <string>NYUURYOKU_TANTOUSHA_CD:入力担当者:Tru" +
            "e:11</string>\r\n  <string>ENTRY_NUMBER:計量番号:True:12</string>\r\n  <string>RENBAN:年連" +
            "番/日連番:True:13</string>\r\n  <string>DENPYOU_DATE:伝票日付:True:14</string>\r\n  <string>" +
            "SHARYOU_CD:車輌CD:True:15</string>\r\n  <string>SHARYOU_NAME_RYAKU:車輌名:True:16</stri" +
            "ng>\r\n  <string>GYOUSHA_CD:業者CD:True:17</string>\r\n  <string>GYOUSHA_NAME_RYAKU:業者" +
            "名:True:18</string>\r\n  <string>GENBA_CD:現場CD:True:19</string>\r\n  <string>GENBA_NA" +
            "ME_RYAKU:現場名:True:20</string>\r\n  <string>UNPAN_GYOUSHA_CD:運搬業者CD:True:21</string" +
            ">\r\n  <string>UNPAN_GYOUSHA_NAME:運搬業者名:True:22</string>\r\n  <string>SHASHU_CD:車種CD" +
            ":True:23</string>\r\n  <string>UNTENSHA_CD:運転者CD:True:24</string>\r\n  <string>DENPY" +
            "OU_BIKOU:伝票備考:True:25</string>\r\n  <string>TAIRYUU_BIKOU:滞留備考:True:26</string>\r\n " +
            " <string>STACK_JYUURYOU:総重量:False:27</string>\r\n  <string>EMPTY_JYUURYOU:空車重量:Fal" +
            "se:28</string>\r\n  <string>EMPTY_KEIRYOU_TIME:総重量計量時間:True:29</string>\r\n  <string" +
            ">STACK_KEIRYOU_TIME:空車重量計量時間:True:30</string>\r\n  <string>HAIKI_KBN_CD:廃棄物区分CD:Tr" +
            "ue:42</string>\r\n  <string>HST_GYOUSHA_CD:排出事業者CD:True:43</string>\r\n  <string>HST" +
            "_GYOUSHA_NAME:排出事業者名:True:44</string>\r\n  <string>HST_GENBA_CD:排出事業場CD:True:45</s" +
            "tring>\r\n  <string>HST_GENBA_NAME:排出事業場名:True:46</string>\r\n  <string>SBN_GYOUSHA_" +
            "CD:処分業者CD:True:47</string>\r\n  <string>SBN_GYOUSHA_NAME:処分業者名:True:48</string>\r\n " +
            " <string>SBN_GENBA_CD:処分事業場CD:True:49</string>\r\n  <string>SBN_GENBA_NAME:処分事業場名:" +
            "True:50</string>\r\n  <string>LAST_SBN_GYOUSHA_CD:最終処分業者CD:True:51</string>\r\n  <st" +
            "ring>LAST_SBN_GYOUSHA_NAME:最終処分業者名:True:52</string>\r\n  <string>LAST_SBN_GENBA_CD" +
            ":最終処分場CD:True:53</string>\r\n  <string>LAST_SBN_GENBA_NAME:最終処分場名:True:54</string>" +
            "\r\n  <string>EIGYOU_TANTOUSHA_CD:営業担当者CD:True:61</string>\r\n  <string>NIZUMI_GYOUS" +
            "HA_CD:荷積業者CD:True:62</string>\r\n  <string>NIZUMI_GYOUSHA_NAME:荷積業者名:True:63</stri" +
            "ng>\r\n  <string>NIZUMI_GENBA_CD:荷積現場CD:True:64</string>\r\n  <string>NIZUMI_GENBA_N" +
            "AME:荷積現場名:True:65</string>\r\n  <string>NIOROSHI_GYOUSHA_CD:荷降業者CD:True:66</string" +
            ">\r\n  <string>NIOROSHI_GYOUSHA_NAME:荷降業者名:True:67</string>\r\n  <string>NIOROSHI_GE" +
            "NBA_CD:荷降現場CD:True:68</string>\r\n  <string>NIOROSHI_GENBA_NAME:荷降現場名:True:69</str" +
            "ing>\r\n  <string>DAIKAN_KBN:台貫:True:70</string>\r\n  <string>KEITAI_KBN_CD:形態区分CD:T" +
            "rue:71</string>\r\n  <string>MANIFEST_SHURUI_CD:マニ種類CD:True:72</string>\r\n  <string" +
            ">MANIFEST_TEHAI_CD:マニ手配CD:True:73</string>\r\n  <string>TORIHIKISAKI_CD:取引先CD:True" +
            ":81</string>\r\n  <string>TORIHIKISAKI_NAME_RYAKU:取引先名:True:82</string>\r\n  <string" +
            ">URIAGE_TORIHIKI_KBN_CD:売上取引区分CD:True:83</string>\r\n  <string>URIAGE_ZEI_KEISAN_K" +
            "BN_CD:売上税計算区分CD:True:84</string>\r\n  <string>URIAGE_ZEI_KBN_CD:売上税区分CD:True:85</s" +
            "tring>\r\n  <string>SHIHARAI_TORIHIKI_KBN_CD:支払取引区分CD:True:86</string>\r\n  <string>" +
            "SHIHARAI_ZEI_KEISAN_KBN_CD:支払税計算区分CD:True:87</string>\r\n  <string>SHIHARAI_ZEI_KB" +
            "N_CD:支払税区分CD:True:88</string>\r\n  <string>CASHEIR_RENDOU_KBN_CD:キャッシャー連動区分:True:8" +
            "9</string>\r\n  <string>RECEIPT_KBN_CD:領収書区分:True:90</string>\r\n  <string>RECEIPT_K" +
            "EISHOU_1:領収書敬称1:True:91</string>\r\n  <string>RECEIPT_KEISHOU_2:領収書敬称2:True:92</st" +
            "ring>\r\n  <string>RECEIPT_TADASHIGAKI:領収書但し書き:True:93</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ApDenpyouCtrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ApDenpyouCtrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tadasigaki {
            get {
                return ((string)(this["tadasigaki"]));
            }
            set {
                this["tadasigaki"] = value;
            }
        }
    }
}
