WITH MANI AS
(
SELECT TME.SYSTEM_ID,
       TME.SEQ,
       TMD.DETAIL_SYSTEM_ID,
       NULL AS KANRI_ID,
       NULL AS DEN_SEQ,
       TME.MANIFEST_ID,
       TME.KOUFU_DATE,
       TME.FIRST_MANIFEST_KBN,
       TME.HAIKI_KBN_CD,
       MHS.HOUKOKUSHO_BUNRUI_CD,
       TMD.HAIKI_SHURUI_CD,
       MHS.HAIKI_SHURUI_NAME,
       TME.HST_GYOUSHA_CD,
       TME.HST_GENBA_CD,
       TMD.KANSAN_SUU,
       TMD.SBN_HOUHOU_CD,
       UPN.UPN_SAKI_GYOUSHA_CD AS SBN_GYOUSHA_CD,
       UPN.UPN_SAKI_GENBA_CD AS SBN_GENBA_CD,
       NULL AS UPN_JYUTAKUSHA_CD,
       --TME.SBN_GYOUSHA_CD AS HIKIWATASHISAKI_CD,
       --TMD.KANSAN_SUU AS HIKIWATASHI_RYOU,
       UPN.UPN_GYOUSHA_CD AS UPN1_JYUTAKUSHA_CD,
       NULL AS UPN2_JYUTAKUSHA_CD,
       NULL AS UPN3_JYUTAKUSHA_CD,
       TME.TMH_GYOUSHA_CD AS TMH1_GYOUSHA_CD,
       TME.TMH_GENBA_CD AS TMH1_GENBA_CD,
       NULL AS TMH2_GYOUSHA_CD,
       NULL AS TMH2_GENBA_CD
FROM T_MANIFEST_ENTRY TME
LEFT JOIN T_MANIFEST_UPN UPN
       ON TME.SYSTEM_ID    = UPN.SYSTEM_ID
      AND TME.SEQ          = UPN.SEQ
LEFT JOIN T_MANIFEST_DETAIL TMD
       ON TME.SYSTEM_ID = TMD.SYSTEM_ID
      AND TME.SEQ       = TMD.SEQ
LEFT JOIN M_HAIKI_SHURUI MHS
       ON TME.HAIKI_KBN_CD    = MHS.HAIKI_KBN_CD
      AND TMD.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
WHERE TME.DELETE_FLG  = 0
   AND TME.HAIKI_KBN_CD = 1
   AND 
   /*IF data.HAIKIBUTU_KBN == 1*/
   TMD.HAIKI_SHURUI_CD BETWEEN '0000' AND '6999'
   /*END*/
   /*IF data.HAIKIBUTU_KBN == 2*/
   TMD.HAIKI_SHURUI_CD BETWEEN '7000' AND '9999'
   /*END*/
   AND UPN.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
   AND UPN.UPN_END_DATE >= /*data.DATE_FROM*/''
   AND UPN.UPN_END_DATE  <= /*data.DATE_TO*/''
   
UNION ALL

SELECT TME.SYSTEM_ID,
       TME.SEQ,
       TMD.DETAIL_SYSTEM_ID,
       NULL AS KANRI_ID,
       NULL AS DEN_SEQ,
       TME.MANIFEST_ID,
       TME.KOUFU_DATE,
       TME.FIRST_MANIFEST_KBN,
       TME.HAIKI_KBN_CD,
       MHS.HOUKOKUSHO_BUNRUI_CD,
       TMD.HAIKI_SHURUI_CD,
       MHS.HAIKI_SHURUI_NAME,
       TME.HST_GYOUSHA_CD,
	   TME.HST_GENBA_CD,
	   TMD.KANSAN_SUU,
       TMD.SBN_HOUHOU_CD,
       UPN1.UPN_SAKI_GYOUSHA_CD AS SBN_GYOUSHA_CD,
       UPN1.UPN_SAKI_GENBA_CD AS SBN_GENBA_CD,
       NULL AS UPN_JYUTAKUSHA_CD,
              
       UPN1.UPN_GYOUSHA_CD AS UPN1_JYUTAKUSHA_CD,
       UPN2.UPN_GYOUSHA_CD AS UPN2_JYUTAKUSHA_CD,
       NULL AS UPN3_JYUTAKUSHA_CD,
       TME.TMH_GYOUSHA_CD AS TMH1_GYOUSHA_CD,
       TME.TMH_GENBA_CD AS TMH1_GENBA_CD,
       NULL AS TMH2_GYOUSHA_CD,
       NULL AS TMH2_GENBA_CD
       --UPN1.UPN_SAKI_GYOUSHA_CD AS HIKIWATASHISAKI_CD,
       --TMD.KANSAN_SUU AS HIKIWATASHI_RYOU--,
FROM T_MANIFEST_ENTRY TME
LEFT JOIN T_MANIFEST_UPN UPN1
       ON TME.SYSTEM_ID    = UPN1.SYSTEM_ID
       AND TME.SEQ         = UPN1.SEQ
       AND UPN1.UPN_ROUTE_NO = 1
LEFT JOIN M_GYOUSHA UPN1_GYOUSHA
       ON UPN1_GYOUSHA.GYOUSHA_CD = UPN1.UPN_SAKI_GYOUSHA_CD
LEFT JOIN T_MANIFEST_UPN UPN2
       ON TME.SYSTEM_ID    = UPN2.SYSTEM_ID
       AND TME.SEQ         = UPN2.SEQ
       AND UPN2.UPN_ROUTE_NO = 2
LEFT JOIN M_GYOUSHA UPN2_GYOUSHA
       ON UPN2_GYOUSHA.GYOUSHA_CD = UPN2.UPN_SAKI_GYOUSHA_CD
LEFT JOIN T_MANIFEST_DETAIL TMD
       ON TME.SYSTEM_ID = TMD.SYSTEM_ID
       AND TME.SEQ       = TMD.SEQ
LEFT JOIN M_HAIKI_SHURUI MHS
       ON TME.HAIKI_KBN_CD    = MHS.HAIKI_KBN_CD
       AND TMD.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
WHERE TME.DELETE_FLG  = 0
   AND TME.HAIKI_KBN_CD = 2
   AND 
   /*IF data.HAIKIBUTU_KBN == 1*/
   TMD.HAIKI_SHURUI_CD BETWEEN '0000' AND '2099'
   /*END*/
   /*IF data.HAIKIBUTU_KBN == 2*/
   TMD.HAIKI_SHURUI_CD BETWEEN '2100' AND '9999'
   /*END*/
   AND ((UPN1.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
      AND UPN1.UPN_END_DATE >= /*data.DATE_FROM*/''
      AND UPN1.UPN_END_DATE  <= /*data.DATE_TO*/'')
     OR (UPN2.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
      AND UPN2.UPN_END_DATE >= /*data.DATE_FROM*/''
      AND UPN2.UPN_END_DATE  <= /*data.DATE_TO*/''))
      
UNION ALL
   
SELECT distinct TME.SYSTEM_ID,
       TME.SEQ,
       TMD.DETAIL_SYSTEM_ID,
       NULL AS KANRI_ID,
       NULL AS DEN_SEQ,
       TME.MANIFEST_ID,
       TME.KOUFU_DATE,
       TME.FIRST_MANIFEST_KBN,
       TME.HAIKI_KBN_CD,
       MHS.HOUKOKUSHO_BUNRUI_CD,
       TMD.HAIKI_SHURUI_CD,
       MHS.HAIKI_SHURUI_NAME, 
       TME.HST_GYOUSHA_CD,
	   TME.HST_GENBA_CD,
	   TMD.KANSAN_SUU,
       TMD.SBN_HOUHOU_CD,
       UPN.UPN_SAKI_GYOUSHA_CD AS SBN_GYOUSHA_CD,
       UPN.UPN_SAKI_GENBA_CD AS SBN_GENBA_CD,
       UPN.UPN_GYOUSHA_CD,
       --UPN.UPN_SAKI_GYOUSHA_CD AS HIKIWATASHISAKI_CD,
       --TMD.KANSAN_SUU AS HIKIWATASHI_RYOU
       CASE WHEN UPN.UPN_ROUTE_NO >= 1
       THEN UPN1.UPN_GYOUSHA_CD 
       ELSE NULL END AS UPN1_JYUTAKUSHA_CD,
       CASE WHEN UPN.UPN_ROUTE_NO >= 2
       THEN UPN2.UPN_GYOUSHA_CD 
       ELSE NULL END AS UPN2_JYUTAKUSHA_CD,
       CASE WHEN UPN.UPN_ROUTE_NO >= 3
       THEN UPN3.UPN_GYOUSHA_CD 
       ELSE NULL END AS UPN3_JYUTAKUSHA_CD,
       CASE 
       WHEN UPN1.UPN_SAKI_KBN = 2 AND UPN.UPN_ROUTE_NO > 1
       THEN 
       UPN1.UPN_SAKI_GYOUSHA_CD 
       ELSE
       NULL END AS TMH1_GYOUSHA_CD,
       
       CASE 
       WHEN UPN1.UPN_SAKI_KBN = 2 AND UPN.UPN_ROUTE_NO > 1
       THEN
       UPN1.UPN_SAKI_GENBA_CD 
       ELSE
       NULL END AS TMH1_GENBA_CD,
       
       CASE 
       WHEN UPN2.UPN_SAKI_KBN = 2 AND UPN.UPN_ROUTE_NO > 2
       THEN 
       UPN2.UPN_SAKI_GYOUSHA_CD 
       ELSE
       NULL END AS TMH2_GYOUSHA_CD,
       
       CASE 
       WHEN UPN2.UPN_SAKI_KBN = 2 AND UPN.UPN_ROUTE_NO > 2
       THEN
       UPN2.UPN_SAKI_GENBA_CD 
       ELSE
       NULL END AS TMH2_GENBA_CD
FROM T_MANIFEST_ENTRY TME
LEFT JOIN T_MANIFEST_UPN UPN
       ON TME.SYSTEM_ID    = UPN.SYSTEM_ID
       AND TME.SEQ         = UPN.SEQ
       AND UPN.UPN_ROUTE_NO = (SELECT MIN(UPN_ROUTE_NO) FROM T_MANIFEST_UPN WHERE TME.SYSTEM_ID = T_MANIFEST_UPN.SYSTEM_ID AND TME.SEQ = T_MANIFEST_UPN.SEQ  AND T_MANIFEST_UPN.UPN_SAKI_KBN = 1) 
LEFT JOIN T_MANIFEST_UPN UPN1
       ON TME.SYSTEM_ID    = UPN1.SYSTEM_ID
       AND TME.SEQ         = UPN1.SEQ
       AND UPN1.UPN_ROUTE_NO = 1
LEFT JOIN T_MANIFEST_UPN UPN2
       ON TME.SYSTEM_ID    = UPN2.SYSTEM_ID
       AND TME.SEQ         = UPN2.SEQ
       AND UPN2.UPN_ROUTE_NO = 2
LEFT JOIN T_MANIFEST_UPN UPN3
       ON TME.SYSTEM_ID    = UPN3.SYSTEM_ID
       AND TME.SEQ         = UPN3.SEQ
       AND UPN3.UPN_ROUTE_NO = 3      
LEFT JOIN T_MANIFEST_DETAIL TMD
       ON TME.SYSTEM_ID = TMD.SYSTEM_ID
       AND TME.SEQ       = TMD.SEQ
LEFT JOIN M_HAIKI_SHURUI MHS
       ON TME.HAIKI_KBN_CD    = MHS.HAIKI_KBN_CD
       AND TMD.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
WHERE TME.DELETE_FLG  = 0
   AND TME.HAIKI_KBN_CD = 3
   AND 
   /*IF data.HAIKIBUTU_KBN == 1*/
   TMD.HAIKI_SHURUI_CD BETWEEN '0000' AND '6999'
   /*END*/
   /*IF data.HAIKIBUTU_KBN == 2*/
   TMD.HAIKI_SHURUI_CD BETWEEN '7000' AND '9999'
   /*END*/
   AND ((UPN1.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
      AND UPN1.UPN_END_DATE >= /*data.DATE_FROM*/''
      AND UPN1.UPN_END_DATE  <= /*data.DATE_TO*/''
      AND UPN1.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO)
     OR (UPN2.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
      AND UPN2.UPN_END_DATE >= /*data.DATE_FROM*/''
      AND UPN2.UPN_END_DATE  <= /*data.DATE_TO*/''
      AND UPN2.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO)
     OR (UPN3.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
      AND UPN3.UPN_END_DATE >= /*data.DATE_FROM*/''
      AND UPN3.UPN_END_DATE  <= /*data.DATE_TO*/''
      AND UPN3.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO))
      
/*IF data.DENSHI_MANIFEST_KBN == 1*/
UNION ALL
SELECT distinct R18.SYSTEM_ID,
           R18.SEQ,
           R18.DETAIL_SYSTEM_ID,
           DMT.KANRI_ID,
           R18.DEN_SEQ,
           R18.MANIFEST_ID,
           R18.HIKIWATASHI_DATE AS KOUFU_DATE,
           CASE
           WHEN (ISNULL(R18.FIRST_MANIFEST_FLAG,'') = '' OR ISNULL(HST_GYOUSHA.JISHA_KBN, 0) = 0) AND R18.MANIFEST_KBN = 2
           THEN '0'
		   WHEN (ISNULL(R18.FIRST_MANIFEST_FLAG,'') <> '' AND ISNULL(HST_GYOUSHA.JISHA_KBN, 0) = 1) AND R18.MANIFEST_KBN = 2
           THEN '1'
            END                    AS FIRST_MANIFEST_KBN,
           CAST('4' AS SMALLINT ) AS HAIKI_KBN_CD,
           MDHS.HOUKOKUSHO_BUNRUI_CD,
           R18.HAIKI_DAI_CODE + R18.HAIKI_CHU_CODE + R18.HAIKI_SHO_CODE AS HAIKI_SHURUI_CD,
           R18.HAIKI_SHURUI_NAME,
           R18.HST_GYOUSHA_CD,
           R18.HST_GENBA_CD,
           R18.KANSAN_SUU,
           R18.SBN_HOUHOU_CD,        
           UPN_EX.UPNSAKI_GYOUSHA_CD AS SBN_GYOUSHA_CD,
           UPN_EX.UPNSAKI_GENBA_CD AS SBN_GENBA_CD,
           UPN_EX.UPN_GYOUSHA_CD AS UPN_JYUTAKUSHA_CD,
           --UPN_EX.UPNSAKI_GYOUSHA_CD AS HIKIWATASHISAKI_CD, 
		   CASE
		   WHEN UPN.UPN_ROUTE_NO >= 1
		   THEN
		   UPN_EX1.UPN_GYOUSHA_CD
		   ELSE NULL
		   END AS UPN1_JYUTAKUSHA_CD,
		   CASE
		   WHEN UPN.UPN_ROUTE_NO >= 2
		   THEN
		   UPN_EX2.UPN_GYOUSHA_CD
		   ELSE NULL
		   END AS UPN2_JYUTAKUSHA_CD,
		   CASE
		   WHEN UPN.UPN_ROUTE_NO >= 3
		   THEN
		   UPN_EX3.UPN_GYOUSHA_CD 
		   ELSE NULL 
		   END AS UPN3_JYUTAKUSHA_CD,
		   CASE 
		   WHEN UPN1.UPNSAKI_JOU_KBN = 1 AND UPN.UPN_ROUTE_NO > 1
		   THEN 
		   UPN_EX1.UPNSAKI_GYOUSHA_CD 
		   ELSE
		   NULL END AS TMH1_GYOUSHA_CD,
	       
		   CASE 
		   WHEN UPN1.UPNSAKI_JOU_KBN = 1 AND UPN.UPN_ROUTE_NO > 1
		   THEN
		   UPN_EX1.UPNSAKI_GENBA_CD 
		   ELSE
		   NULL END AS TMH1_GENBA_CD,
	       
		   CASE 
		   WHEN UPN2.UPNSAKI_JOU_KBN = 1 AND UPN.UPN_ROUTE_NO > 2
		   THEN 
		   UPN_EX2.UPNSAKI_GYOUSHA_CD  
		   ELSE
		   NULL END AS TMH2_GYOUSHA_CD,
	       
		   CASE 
		   WHEN UPN2.UPNSAKI_JOU_KBN = 2 AND UPN.UPN_ROUTE_NO > 2
		   THEN
		   UPN_EX2.UPNSAKI_GENBA_CD 
		   ELSE
		   NULL END AS TMH2_GENBA_CD
FROM DT_MF_TOC DMT
INNER JOIN (
        SELECT
            R18.KANRI_ID
            ,R18.SEQ AS DEN_SEQ
            ,R18.MANIFEST_ID
            ,R18.HIKIWATASHI_DATE
            ,R18.FIRST_MANIFEST_FLAG
            ,R18.MANIFEST_KBN
            ,EX.SYSTEM_ID
            ,EX.SEQ
            ,EX.HST_GYOUSHA_CD
            ,EX.HST_GENBA_CD
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.DETAIL_SYSTEM_ID ELSE EX.SYSTEM_ID END) AS DETAIL_SYSTEM_ID
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.SBN_HOUHOU_CD ELSE EX.SBN_HOUHOU_CD END) AS SBN_HOUHOU_CD
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.KANSAN_SUU ELSE EX.KANSAN_SUU END) AS KANSAN_SUU
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.HAIKI_DAI_CODE ELSE R18.HAIKI_DAI_CODE END) AS HAIKI_DAI_CODE
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.HAIKI_CHU_CODE ELSE R18.HAIKI_CHU_CODE END) AS HAIKI_CHU_CODE
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.HAIKI_SHO_CODE ELSE R18.HAIKI_SHO_CODE END) AS HAIKI_SHO_CODE
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX_HAIKI_SHURUI.HAIKI_SHURUI_NAME ELSE R18.HAIKI_SHURUI END) AS HAIKI_SHURUI_NAME
        FROM DT_R18 AS R18
        LEFT JOIN DT_R18_EX AS EX
        ON R18.KANRI_ID = EX.KANRI_ID AND EX.DELETE_FLG = 0
        LEFT JOIN DT_R18_MIX AS MIX
        ON EX.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0
        LEFT JOIN M_DENSHI_HAIKI_SHURUI AS MIX_HAIKI_SHURUI
        ON (MIX.HAIKI_DAI_CODE + MIX.HAIKI_CHU_CODE + MIX.HAIKI_SHO_CODE) = MIX_HAIKI_SHURUI.HAIKI_SHURUI_CD
    ) AS R18
    ON DMT.KANRI_ID = R18.KANRI_ID AND DMT.LATEST_SEQ = R18.DEN_SEQ
 LEFT JOIN M_GYOUSHA AS HST_GYOUSHA
        ON R18.HST_GYOUSHA_CD = HST_GYOUSHA.GYOUSHA_CD
 LEFT JOIN DT_R19 UPN
        ON R18.KANRI_ID        = UPN.KANRI_ID
       AND R18.DEN_SEQ             = UPN.SEQ
       AND UPN.UPNSAKI_JOU_KBN IN (2,3,4)       
 LEFT JOIN DT_R19_EX UPN_EX
        ON UPN.KANRI_ID     = UPN_EX.KANRI_ID
       AND R18.SYSTEM_ID  = UPN_EX.SYSTEM_ID
       AND R18.SEQ        = UPN_EX.SEQ
       AND UPN.UPN_ROUTE_NO = UPN_EX.UPN_ROUTE_NO
 LEFT JOIN M_DENSHI_HAIKI_SHURUI MDHS
        ON R18.HAIKI_DAI_CODE + R18.HAIKI_CHU_CODE + R18.HAIKI_SHO_CODE = MDHS.HAIKI_SHURUI_CD
 
 LEFT JOIN DT_R19 UPN1
        ON R18.KANRI_ID         = UPN1.KANRI_ID
       AND R18.DEN_SEQ              = UPN1.SEQ
	   AND UPN1.UPN_ROUTE_NO    = 1

 LEFT JOIN DT_R19_EX UPN_EX1
        ON UPN1.KANRI_ID     = UPN_EX1.KANRI_ID
       AND R18.SYSTEM_ID            = UPN_EX1.SYSTEM_ID
       AND R18.SEQ                  = UPN_EX1.SEQ
       AND UPN1.UPN_ROUTE_NO = UPN_EX1.UPN_ROUTE_NO
       
 LEFT JOIN DT_R19 UPN2
        ON R18.KANRI_ID         = UPN2.KANRI_ID
       AND R18.DEN_SEQ              = UPN2.SEQ
	   AND UPN2.UPN_ROUTE_NO    = 2
 LEFT JOIN DT_R19_EX UPN_EX2
        ON UPN2.KANRI_ID     = UPN_EX2.KANRI_ID
       AND R18.SYSTEM_ID   = UPN_EX2.SYSTEM_ID
       AND R18.SEQ         = UPN_EX2.SEQ
       AND UPN2.UPN_ROUTE_NO = UPN_EX2.UPN_ROUTE_NO
       
 LEFT JOIN DT_R19 UPN3
        ON R18.KANRI_ID         = UPN3.KANRI_ID
       AND R18.DEN_SEQ              = UPN3.SEQ
	   AND UPN3.UPN_ROUTE_NO    = 3
 LEFT JOIN DT_R19_EX UPN_EX3
        ON UPN3.KANRI_ID     = UPN_EX3.KANRI_ID
       AND R18.SYSTEM_ID   = UPN_EX3.SYSTEM_ID
       AND R18.SEQ         = UPN_EX3.SEQ
       AND UPN3.UPN_ROUTE_NO = UPN_EX3.UPN_ROUTE_NO
       
 LEFT JOIN DT_R19 UPN4
        ON R18.KANRI_ID         = UPN4.KANRI_ID
       AND R18.DEN_SEQ              = UPN4.SEQ
	   AND UPN4.UPN_ROUTE_NO    = 4
 LEFT JOIN DT_R19_EX UPN_EX4
        ON UPN4.KANRI_ID     = UPN_EX4.KANRI_ID
       AND R18.SYSTEM_ID   = UPN_EX4.SYSTEM_ID
       AND R18.SEQ         = UPN_EX4.SEQ
       AND UPN4.UPN_ROUTE_NO = UPN_EX4.UPN_ROUTE_NO
       
 LEFT JOIN DT_R19 UPN5
        ON R18.KANRI_ID         = UPN5.KANRI_ID
       AND R18.DEN_SEQ              = UPN5.SEQ
	   AND UPN5.UPN_ROUTE_NO    = 5
 LEFT JOIN DT_R19_EX UPN_EX5
        ON UPN5.KANRI_ID     = UPN_EX5.KANRI_ID
       AND R18.SYSTEM_ID   = UPN_EX5.SYSTEM_ID
       AND R18.SEQ         = UPN_EX5.SEQ
       AND UPN5.UPN_ROUTE_NO = UPN_EX5.UPN_ROUTE_NO
 WHERE (DMT.KIND = 4 OR DMT.KIND = 5 OR DMT.KIND IS NULL)
       AND (DMT.STATUS_FLAG = 3 OR DMT.STATUS_FLAG = 4)
       AND 
   /*IF data.HAIKIBUTU_KBN == 1*/
   (R18.HAIKI_DAI_CODE + R18.HAIKI_CHU_CODE + R18.HAIKI_SHO_CODE) BETWEEN '0000' AND '6999'
   /*END*/
   /*IF data.HAIKIBUTU_KBN == 2*/
   (R18.HAIKI_DAI_CODE + R18.HAIKI_CHU_CODE + R18.HAIKI_SHO_CODE) BETWEEN '7000' AND '9999'
   /*END*/
   AND ((UPN_EX1.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
        AND ISDATE(UPN1.UPN_END_DATE) = 1
        AND CONVERT(DATETIME, UPN1.UPN_END_DATE) >= /*data.DATE_FROM*/''
        AND CONVERT(DATETIME, UPN1.UPN_END_DATE)  <= /*data.DATE_TO*/''
        AND UPN1.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO)
      OR
        (UPN_EX2.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
		AND ISDATE(UPN2.UPN_END_DATE) = 1
        AND CONVERT(DATETIME, UPN2.UPN_END_DATE) >= /*data.DATE_FROM*/''
        AND CONVERT(DATETIME, UPN2.UPN_END_DATE)  <= /*data.DATE_TO*/''
        AND UPN2.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO)
      OR
        (UPN_EX3.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
		AND ISDATE(UPN3.UPN_END_DATE) = 1
        AND CONVERT(DATETIME, UPN3.UPN_END_DATE) >= /*data.DATE_FROM*/''
        AND CONVERT(DATETIME, UPN3.UPN_END_DATE)  <= /*data.DATE_TO*/''
        AND UPN3.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO)
      OR
        (UPN_EX4.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
		AND ISDATE(UPN4.UPN_END_DATE) = 1
        AND CONVERT(DATETIME, UPN4.UPN_END_DATE) >= /*data.DATE_FROM*/''
        AND CONVERT(DATETIME, UPN4.UPN_END_DATE)  <= /*data.DATE_TO*/''
        AND UPN4.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO)
      OR
        (UPN_EX5.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
		AND ISDATE(UPN5.UPN_END_DATE) = 1
        AND CONVERT(DATETIME, UPN5.UPN_END_DATE) >= /*data.DATE_FROM*/''
        AND CONVERT(DATETIME, UPN5.UPN_END_DATE)  <= /*data.DATE_TO*/''
        AND UPN5.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO)
      )
/*END*/
),
SEARCH_DATA AS (
SELECT
       MANI.SYSTEM_ID
      ,MANI.SEQ
      ,MANI.DETAIL_SYSTEM_ID
      ,MANI.KANRI_ID
      ,MANI.DEN_SEQ
      ,MANI.HAIKI_KBN_CD
      ,MANI.HAIKI_SHURUI_CD
      ,MCB.HOUKOKU_BUNRUI_CD
      ,MCB.HOUKOKU_BUNRUI_NAME
      ,MCB.HOUKOKUSHO_BUNRUI_CD
      ,CASE MCB.SEKIMEN_KBN
                    WHEN 0 THEN '×'
                    WHEN 1 THEN '〇'
                    ELSE NULL
                END AS SEKIMEN_KBN
      ,CASE MCB.TOKUTEI_YUUGAI_KBN
                    WHEN 0 THEN '×'
                    WHEN 1 THEN '〇'
                    ELSE NULL
                END AS TOKUTEI_YUUGAI_KBN
      ,MANI.KANSAN_SUU
      ,MU.UNIT_NAME
      --排出事業者
      ,HST_GYOUSHA.GYOUSHA_CD AS HST_GYOUSHA_CD
      ,HST_GYOUSHA.GYOUSHA_NAME1 + HST_GYOUSHA.GYOUSHA_NAME2 AS HST_GYOUSHA_NAME
      ,CASE /*data.JUSHO_CHUSHUTU_JOKEN*/0
       WHEN 1
       THEN HST_GYOUSHA_MT.TODOUFUKEN_NAME + HST_GYOUSHA.GYOUSHA_ADDRESS1 + HST_GYOUSHA.GYOUSHA_ADDRESS2
       WHEN 2
       THEN HST_GYOUSHA.GYOUSHA_ADDRESS1 + HST_GYOUSHA.GYOUSHA_ADDRESS2
       WHEN 3
       THEN HST_GYOUSHA_MT.TODOUFUKEN_NAME + HST_GYOUSHA.GYOUSHA_ADDRESS1
       END AS HST_GYOUSHA_ADDRESS
      ,HST_GYOUSHA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD AS HST_GYOUSHA_CHIIKI_CD
      ,HST_GYOUSHA_MC.CHIIKI_NAME AS HST_GYOUSHA_CHIIKI_NAME
      ,FOR_GYOUSHU_HST.HOUKOKU_GYOUSHU_CD AS HST_GYOUSHA_GYOUSHU_CD
      ,FOR_GYOUSHU_HST.HOUKOKU_GYOUSHU_NAME AS HST_GYOUSHA_GYOUSHU_NAME  
      --排出事業場
      ,HST_GENBA.GENBA_CD AS HST_GENBA_CD
      ,HST_GENBA.GENBA_NAME1 + HST_GENBA.GENBA_NAME2 AS HST_GENBA_NAME
      ,CASE /*data.JUSHO_CHUSHUTU_JOKEN*/0
       WHEN 1
       THEN HST_GENBA_MT.TODOUFUKEN_NAME + HST_GENBA.GENBA_ADDRESS1 + HST_GENBA.GENBA_ADDRESS2
       WHEN 2
       THEN HST_GENBA.GENBA_ADDRESS1 + HST_GENBA.GENBA_ADDRESS2
       WHEN 3
       THEN HST_GENBA_MT.TODOUFUKEN_NAME + HST_GENBA.GENBA_ADDRESS1
       END AS HST_GENBA_ADDRESS
      ,HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD AS HST_GENBA_CHIIKI_CD
      ,HST_GENBA_MC.CHIIKI_NAME AS HST_GENBA_CHIIKI_NAME
      ,FOR_GYOUSHU_HST_GENBA.HOUKOKU_GYOUSHU_CD AS HST_GENBA_GYOUSHU_CD
      ,FOR_GYOUSHU_HST_GENBA.HOUKOKU_GYOUSHU_NAME AS HST_GENBA_GYOUSHU_NAME
       --運搬受託者1
      ,MANI.UPN1_JYUTAKUSHA_CD AS UPN_GYOUSHA_CD1
      ,UPN_GYOUSHA1.GYOUSHA_NAME1 + UPN_GYOUSHA1.GYOUSHA_NAME2 AS UPN_GYOUSHA_NAME1
      ,CASE /*data.JUSHO_CHUSHUTU_JOKEN*/0
       WHEN 1
       THEN UPN_GYOUSHA_MT1.TODOUFUKEN_NAME + UPN_GYOUSHA1.GYOUSHA_ADDRESS1 + UPN_GYOUSHA1.GYOUSHA_ADDRESS2
       WHEN 2 
       THEN UPN_GYOUSHA1.GYOUSHA_ADDRESS1 + UPN_GYOUSHA1.GYOUSHA_ADDRESS2
       WHEN 3
       THEN UPN_GYOUSHA_MT1.TODOUFUKEN_NAME + UPN_GYOUSHA1.GYOUSHA_ADDRESS1
       END AS UPN_GYOUSHA_ADDRESS1
      ,UPN_GYOUSHA1.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD AS UPN_GYOUSHA_CHIIKI_CD1
      ,UPN_GYOUSHA_MC1.CHIIKI_NAME AS UPN_GYOUSHA_CHIIKI_NAME1
      ,UPN_GYOUSHA_GYOUSHU1.HOUKOKU_GYOUSHU_CD AS UPN_GYOUSHA_GYOUSHU_CD1
      ,UPN_GYOUSHA_GYOUSHU1.HOUKOKU_GYOUSHU_NAME AS UPN_GYOUSHA_GYOUSHU_NAME1
      ,CASE /*data.HAIKIBUTU_KBN*/0
         WHEN 1 THEN UPN_GYOUSHA_MCK1.FUTSUU_KYOKA_NO
         WHEN 2 THEN UPN_GYOUSHA_MCK1.TOKUBETSU_KYOKA_NO
       END AS UPN_GYOUSHA_KYOKA1
       --運搬受託者2
      ,MANI.UPN2_JYUTAKUSHA_CD AS UPN_GYOUSHA_CD2
      ,UPN_GYOUSHA2.GYOUSHA_NAME1 + UPN_GYOUSHA2.GYOUSHA_NAME2 AS UPN_GYOUSHA_NAME2
      ,CASE /*data.JUSHO_CHUSHUTU_JOKEN*/0
       WHEN 1
       THEN UPN_GYOUSHA_MT2.TODOUFUKEN_NAME + UPN_GYOUSHA2.GYOUSHA_ADDRESS1 + UPN_GYOUSHA2.GYOUSHA_ADDRESS2
       WHEN 2 
       THEN UPN_GYOUSHA2.GYOUSHA_ADDRESS1 + UPN_GYOUSHA2.GYOUSHA_ADDRESS2
       WHEN 3
       THEN UPN_GYOUSHA_MT2.TODOUFUKEN_NAME + UPN_GYOUSHA2.GYOUSHA_ADDRESS1
       END AS UPN_GYOUSHA_ADDRESS2
      ,UPN_GYOUSHA2.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD AS UPN_GYOUSHA_CHIIKI_CD2
      ,UPN_GYOUSHA_MC2.CHIIKI_NAME AS UPN_GYOUSHA_CHIIKI_NAME2
      ,UPN_GYOUSHA_GYOUSHU2.HOUKOKU_GYOUSHU_CD AS UPN_GYOUSHA_GYOUSHU_CD2
      ,UPN_GYOUSHA_GYOUSHU2.HOUKOKU_GYOUSHU_NAME AS UPN_GYOUSHA_GYOUSHU_NAME2
      ,CASE /*data.HAIKIBUTU_KBN*/0
         WHEN 1 THEN UPN_GYOUSHA_MCK2.FUTSUU_KYOKA_NO
         WHEN 2 THEN UPN_GYOUSHA_MCK2.TOKUBETSU_KYOKA_NO
       END AS UPN_GYOUSHA_KYOKA2
       --運搬受託者3
      ,MANI.UPN3_JYUTAKUSHA_CD AS UPN_GYOUSHA_CD3
      ,UPN_GYOUSHA3.GYOUSHA_NAME1 + UPN_GYOUSHA3.GYOUSHA_NAME2 AS UPN_GYOUSHA_NAME3
      ,CASE /*data.JUSHO_CHUSHUTU_JOKEN*/0
       WHEN 1
       THEN UPN_GYOUSHA_MT3.TODOUFUKEN_NAME + UPN_GYOUSHA3.GYOUSHA_ADDRESS1 + UPN_GYOUSHA3.GYOUSHA_ADDRESS2
       WHEN 2 
       THEN UPN_GYOUSHA3.GYOUSHA_ADDRESS1 + UPN_GYOUSHA3.GYOUSHA_ADDRESS2
       WHEN 3
       THEN UPN_GYOUSHA_MT3.TODOUFUKEN_NAME + UPN_GYOUSHA3.GYOUSHA_ADDRESS1
       END AS UPN_GYOUSHA_ADDRESS3
      ,UPN_GYOUSHA3.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD AS UPN_GYOUSHA_CHIIKI_CD3
      ,UPN_GYOUSHA_MC3.CHIIKI_NAME AS UPN_GYOUSHA_CHIIKI_NAME3
      ,UPN_GYOUSHA_GYOUSHU3.HOUKOKU_GYOUSHU_CD AS UPN_GYOUSHA_GYOUSHU_CD3
      ,UPN_GYOUSHA_GYOUSHU3.HOUKOKU_GYOUSHU_NAME AS UPN_GYOUSHA_GYOUSHU_NAME3
      ,CASE /*data.HAIKIBUTU_KBN*/0
         WHEN 1 THEN UPN_GYOUSHA_MCK3.FUTSUU_KYOKA_NO
         WHEN 2 THEN UPN_GYOUSHA_MCK3.TOKUBETSU_KYOKA_NO
       END AS UPN_GYOUSHA_KYOKA3
       --積替保管1
      ,MANI.TMH1_GYOUSHA_CD AS UPN_SAKI_GENBA_CD1
      ,UPN_SAKI_GENBA1.GENBA_NAME1 + UPN_SAKI_GENBA1.GENBA_NAME2 AS UPN_GENBA_NAME1
      ,CASE /*data.JUSHO_CHUSHUTU_JOKEN*/0
       WHEN 1
       THEN UPN_SAKI_GENBA_MT1.TODOUFUKEN_NAME + UPN_SAKI_GENBA1.GENBA_ADDRESS1 + UPN_SAKI_GENBA1.GENBA_ADDRESS2
       WHEN 2 
       THEN UPN_SAKI_GENBA1.GENBA_ADDRESS1 + UPN_SAKI_GENBA1.GENBA_ADDRESS2
       WHEN 3
       THEN UPN_SAKI_GENBA_MT1.TODOUFUKEN_NAME + UPN_SAKI_GENBA1.GENBA_ADDRESS1
       END AS UPN_GENBA_ADDRESS1
      ,UPN_SAKI_GENBA1.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD AS UPN_GENBA_CHIIKI_CD1
      ,UPN_SAKI_GENBA_MC1.CHIIKI_NAME AS UPN_GENBA_CHIIKI_NAME1
      ,UPN_SAKI_GYOUSHA_GYOUSHU1.HOUKOKU_GYOUSHU_CD AS UPN_GENBA_GYOUSHU_CD1
      ,UPN_SAKI_GYOUSHA_GYOUSHU1.HOUKOKU_GYOUSHU_NAME AS UPN_GENBA_GYOUSHU_NAME1
       --積替保管2
      ,MANI.TMH2_GYOUSHA_CD AS UPN_SAKI_GENBA_CD2
      ,UPN_SAKI_GENBA2.GENBA_NAME1 + UPN_SAKI_GENBA2.GENBA_NAME2 AS UPN_GENBA_NAME2
      ,CASE /*data.JUSHO_CHUSHUTU_JOKEN*/0
       WHEN 1
       THEN UPN_SAKI_GENBA_MT2.TODOUFUKEN_NAME + UPN_SAKI_GENBA2.GENBA_ADDRESS1 + UPN_SAKI_GENBA2.GENBA_ADDRESS2
       WHEN 2 
       THEN UPN_SAKI_GENBA2.GENBA_ADDRESS1 + UPN_SAKI_GENBA2.GENBA_ADDRESS2
       WHEN 3
       THEN UPN_SAKI_GENBA_MT2.TODOUFUKEN_NAME + UPN_SAKI_GENBA2.GENBA_ADDRESS1
       END AS UPN_GENBA_ADDRESS2
      ,UPN_SAKI_GENBA2.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD AS UPN_GENBA_CHIIKI_CD2
      ,UPN_SAKI_GENBA_MC2.CHIIKI_NAME AS UPN_GENBA_CHIIKI_NAME2
      ,UPN_SAKI_GYOUSHA_GYOUSHU2.HOUKOKU_GYOUSHU_CD AS UPN_GENBA_GYOUSHU_CD2
      ,UPN_SAKI_GYOUSHA_GYOUSHU2.HOUKOKU_GYOUSHU_NAME AS UPN_GENBA_GYOUSHU_NAME2
      ,CASE MANI.FIRST_MANIFEST_KBN
        -- 1次マニフェストの場合は、中間処分場の許可番号を表示
        WHEN 0 THEN
            CASE /*data.HAIKIBUTU_KBN*/0
                WHEN 1 THEN SBN_GENBA_MCK.FUTSUU_KYOKA_NO
                WHEN 2 THEN SBN_GENBA_MCK.TOKUBETSU_KYOKA_NO
            END
        -- 2次マニフェストの場合は、最終処分場の許可番号を表示
        WHEN 1 THEN
            CASE /*data.HAIKIBUTU_KBN*/0
                WHEN 1 THEN LAST_SBN_GENBA_MCK.FUTSUU_KYOKA_NO
                WHEN 2 THEN LAST_SBN_GENBA_MCK.TOKUBETSU_KYOKA_NO
            END
       END AS SBN_KYOKA
      ,MANI.SBN_GYOUSHA_CD
      ,SBN_GYOUSHA.GYOUSHA_NAME1 + SBN_GYOUSHA.GYOUSHA_NAME2 AS SBN_GYOUSHA_NAME
      ,CASE /*data.JUSHO_CHUSHUTU_JOKEN*/0
       WHEN 1
       THEN SBN_GYOUSHA_MT.TODOUFUKEN_NAME + SBN_GYOUSHA.GYOUSHA_ADDRESS1 + SBN_GYOUSHA.GYOUSHA_ADDRESS2
       WHEN 2
       THEN SBN_GYOUSHA.GYOUSHA_ADDRESS1 + SBN_GYOUSHA.GYOUSHA_ADDRESS2
       WHEN 3
       THEN SBN_GYOUSHA_MT.TODOUFUKEN_NAME + SBN_GYOUSHA.GYOUSHA_ADDRESS1
       END AS SBN_GYOUSHA_ADDRESS
      ,SBN_GYOUSHA.CHIIKI_CD AS SBN_GYOUSHA_CHIIKI_CD
      ,SBN_GYOUSHA_MC.CHIIKI_NAME AS SBN_GYOUSHA_CHIIKI_NAME
      ,SBN_GYOUSHA_GYOUSHU.HOUKOKU_GYOUSHU_CD AS SBN_GYOUSHA_GYOUSHU_CD
      ,SBN_GYOUSHA_GYOUSHU.HOUKOKU_GYOUSHU_NAME AS SBN_GYOUSHA_GYOUSHU_NAME
      --処分事業場
      ,MANI.SBN_GENBA_CD
      ,SBN_GENBA.GENBA_NAME1 + SBN_GENBA.GENBA_NAME2 AS SBN_GENBA_NAME
      ,CASE /*data.JUSHO_CHUSHUTU_JOKEN*/0
       WHEN 1
       THEN SBN_GENBA_MT.TODOUFUKEN_NAME + SBN_GENBA.GENBA_ADDRESS1 + SBN_GENBA.GENBA_ADDRESS2
       WHEN 2
       THEN SBN_GENBA.GENBA_ADDRESS1 + SBN_GENBA.GENBA_ADDRESS2
       WHEN 3
       THEN SBN_GENBA_MT.TODOUFUKEN_NAME + SBN_GENBA.GENBA_ADDRESS1
       END AS SBN_GENBA_ADDRESS
      ,SBN_GENBA.CHIIKI_CD AS SBN_GENBA_CHIIKI_CD
      ,SBN_GENBA_MC.CHIIKI_NAME AS SBN_GENBA_CHIIKI_NAME
      ,SBN_GENBA_GYOUSHU.HOUKOKU_GYOUSHU_CD AS SBN_GENBA_GYOUSHU_CD
      ,SBN_GENBA_GYOUSHU.HOUKOKU_GYOUSHU_NAME AS SBN_GENBA_GYOUSHU_NAME
      --処分方法
      ,MCS.HOUKOKU_SHOBUN_HOUHOU_CD AS SBN_HOUHOU_CD
      ,MCS.HOUKOKU_SHOBUN_HOUHOU_NAME AS SBN_HOUHOU_NAME
      --一次・二次共通
      ,MANI.MANIFEST_ID
      ,MANI.KOUFU_DATE
      ,CASE MANI.FIRST_MANIFEST_KBN
         WHEN 'FALSE' THEN '一次'
         WHEN 'TRUE' THEN '二次'
       END AS MANIFEST_KBN
 FROM MANI

    -- システム設定単位の取得
LEFT JOIN M_SYS_INFO
        ON M_SYS_INFO.SYS_ID = 0
LEFT JOIN M_UNIT MU
       ON MU.UNIT_CD = M_SYS_INFO.MANI_KANSAN_KIHON_UNIT_CD
    -- 排出事業者情報の取得
LEFT JOIN M_GYOUSHA HST_GYOUSHA
       ON MANI.HST_GYOUSHA_CD = HST_GYOUSHA.GYOUSHA_CD
LEFT JOIN M_CHIIKI HST_GYOUSHA_MC
       ON HST_GYOUSHA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = HST_GYOUSHA_MC.CHIIKI_CD
LEFT JOIN M_TODOUFUKEN HST_GYOUSHA_MT
       ON HST_GYOUSHA.GYOUSHA_TODOUFUKEN_CD = HST_GYOUSHA_MT.TODOUFUKEN_CD
LEFT JOIN M_CHIIKIBETSU_GYOUSHU FOR_GYOUSHU_HST 
       ON FOR_GYOUSHU_HST.GYOUSHU_CD = HST_GYOUSHA.GYOUSHU_CD 
	  AND FOR_GYOUSHU_HST.CHIIKI_CD = HST_GYOUSHA.CHIIKI_CD

    -- 排出事業場情報の取得
LEFT JOIN M_GENBA HST_GENBA    
       ON MANI.HST_GYOUSHA_CD = HST_GENBA.GYOUSHA_CD
      AND MANI.HST_GENBA_CD = HST_GENBA.GENBA_CD
LEFT JOIN M_CHIIKI HST_GENBA_MC
       ON HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = HST_GENBA_MC.CHIIKI_CD
LEFT JOIN M_TODOUFUKEN HST_GENBA_MT
       ON HST_GENBA.GENBA_TODOUFUKEN_CD = HST_GENBA_MT.TODOUFUKEN_CD
    -- 運搬品目情報の取得
 --LEFT JOIN M_HAIKI_SHURUI MHS
 --       ON MANI.HAIKI_KBN_CD    = MHS.HAIKI_KBN_CD
 --      AND MANI.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
 LEFT JOIN M_CHIIKIBETSU_BUNRUI MCB
        ON MANI.HOUKOKUSHO_BUNRUI_CD = MCB.HOUKOKUSHO_BUNRUI_CD
       AND MCB.CHIIKI_CD = /*data.TEISHUTUSAKI_CD*/''

LEFT JOIN M_CHIIKIBETSU_GYOUSHU FOR_GYOUSHU_HST_GENBA 
       ON FOR_GYOUSHU_HST_GENBA.GYOUSHU_CD = HST_GENBA.GYOUSHU_CD 
	  AND FOR_GYOUSHU_HST_GENBA.CHIIKI_CD = HST_GENBA.CHIIKI_CD

    -- 運搬受託者1情報の取得
 LEFT JOIN M_GYOUSHA UPN_GYOUSHA1
        ON UPN_GYOUSHA1.GYOUSHA_CD = MANI.UPN1_JYUTAKUSHA_CD
 LEFT JOIN M_TODOUFUKEN UPN_GYOUSHA_MT1
        ON UPN_GYOUSHA_MT1.TODOUFUKEN_CD = UPN_GYOUSHA1.GYOUSHA_TODOUFUKEN_CD
 LEFT JOIN M_CHIIKI UPN_GYOUSHA_MC1
        ON UPN_GYOUSHA_MC1.CHIIKI_CD = UPN_GYOUSHA1.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD
 LEFT JOIN M_CHIIKIBETSU_GYOUSHU UPN_GYOUSHA_GYOUSHU1
        ON UPN_GYOUSHA_GYOUSHU1.GYOUSHU_CD = UPN_GYOUSHA1.GYOUSHU_CD AND UPN_GYOUSHA_GYOUSHU1.CHIIKI_CD = UPN_GYOUSHA1.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD
 LEFT JOIN M_CHIIKIBETSU_KYOKA UPN_GYOUSHA_MCK1
        ON UPN_GYOUSHA_MCK1.GYOUSHA_CD = MANI.UPN1_JYUTAKUSHA_CD
       AND UPN_GYOUSHA_MCK1.GENBA_CD = ''
       AND UPN_GYOUSHA_MCK1.CHIIKI_CD = UPN_GYOUSHA1.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD
       AND UPN_GYOUSHA_MCK1.KYOKA_KBN = 1

    -- 運搬受託者2情報の取得
 LEFT JOIN M_GYOUSHA UPN_GYOUSHA2
        ON UPN_GYOUSHA2.GYOUSHA_CD = MANI.UPN2_JYUTAKUSHA_CD
 LEFT JOIN M_TODOUFUKEN UPN_GYOUSHA_MT2
        ON UPN_GYOUSHA_MT2.TODOUFUKEN_CD = UPN_GYOUSHA2.GYOUSHA_TODOUFUKEN_CD
 LEFT JOIN M_CHIIKI UPN_GYOUSHA_MC2
        ON UPN_GYOUSHA_MC2.CHIIKI_CD = UPN_GYOUSHA2.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD
 LEFT JOIN M_CHIIKIBETSU_GYOUSHU UPN_GYOUSHA_GYOUSHU2
        ON UPN_GYOUSHA_GYOUSHU2.GYOUSHU_CD = UPN_GYOUSHA2.GYOUSHU_CD AND UPN_GYOUSHA_GYOUSHU2.CHIIKI_CD = UPN_GYOUSHA2.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD
 LEFT JOIN M_CHIIKIBETSU_KYOKA UPN_GYOUSHA_MCK2
        ON UPN_GYOUSHA_MCK2.GYOUSHA_CD = MANI.UPN2_JYUTAKUSHA_CD
       AND UPN_GYOUSHA_MCK2.GENBA_CD = ''
       AND UPN_GYOUSHA_MCK2.CHIIKI_CD = UPN_GYOUSHA2.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD
       AND UPN_GYOUSHA_MCK2.KYOKA_KBN = 1

    -- 運搬受託者3情報の取得
 LEFT JOIN M_GYOUSHA UPN_GYOUSHA3
        ON UPN_GYOUSHA3.GYOUSHA_CD = MANI.UPN3_JYUTAKUSHA_CD
 LEFT JOIN M_TODOUFUKEN UPN_GYOUSHA_MT3
        ON UPN_GYOUSHA_MT3.TODOUFUKEN_CD = UPN_GYOUSHA3.GYOUSHA_TODOUFUKEN_CD
 LEFT JOIN M_CHIIKI UPN_GYOUSHA_MC3
        ON UPN_GYOUSHA_MC3.CHIIKI_CD = UPN_GYOUSHA3.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD
 LEFT JOIN M_CHIIKIBETSU_GYOUSHU UPN_GYOUSHA_GYOUSHU3
        ON UPN_GYOUSHA_GYOUSHU3.GYOUSHU_CD = UPN_GYOUSHA3.GYOUSHU_CD AND UPN_GYOUSHA_GYOUSHU3.CHIIKI_CD = UPN_GYOUSHA3.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD
 LEFT JOIN M_CHIIKIBETSU_KYOKA UPN_GYOUSHA_MCK3
        ON UPN_GYOUSHA_MCK3.GYOUSHA_CD = MANI.UPN3_JYUTAKUSHA_CD
       AND UPN_GYOUSHA_MCK3.GENBA_CD = ''
       AND UPN_GYOUSHA_MCK3.CHIIKI_CD = UPN_GYOUSHA3.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD
       AND UPN_GYOUSHA_MCK3.KYOKA_KBN = 1

    -- 積替保管1情報の取得
 LEFT JOIN M_GENBA UPN_SAKI_GENBA1
        ON UPN_SAKI_GENBA1.GYOUSHA_CD = MANI.TMH1_GYOUSHA_CD
       AND UPN_SAKI_GENBA1.GENBA_CD = MANI.TMH1_GENBA_CD
 LEFT JOIN M_TODOUFUKEN UPN_SAKI_GENBA_MT1
        ON UPN_SAKI_GENBA_MT1.TODOUFUKEN_CD = UPN_SAKI_GENBA1.GENBA_TODOUFUKEN_CD
 LEFT JOIN M_CHIIKI UPN_SAKI_GENBA_MC1
        ON UPN_SAKI_GENBA_MC1.CHIIKI_CD = UPN_SAKI_GENBA1.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD
 LEFT JOIN M_CHIIKIBETSU_GYOUSHU UPN_SAKI_GYOUSHA_GYOUSHU1
        ON UPN_SAKI_GYOUSHA_GYOUSHU1.GYOUSHU_CD = UPN_SAKI_GENBA1.GYOUSHU_CD AND UPN_SAKI_GYOUSHA_GYOUSHU1.CHIIKI_CD = UPN_SAKI_GENBA1.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD

    -- 積替保管2情報の取得
 LEFT JOIN M_GENBA UPN_SAKI_GENBA2
        ON UPN_SAKI_GENBA2.GYOUSHA_CD = MANI.TMH2_GYOUSHA_CD
       AND UPN_SAKI_GENBA2.GENBA_CD = MANI.TMH2_GENBA_CD
 LEFT JOIN M_TODOUFUKEN UPN_SAKI_GENBA_MT2
        ON UPN_SAKI_GENBA_MT2.TODOUFUKEN_CD = UPN_SAKI_GENBA2.GENBA_TODOUFUKEN_CD
 LEFT JOIN M_CHIIKI UPN_SAKI_GENBA_MC2
        ON UPN_SAKI_GENBA_MC2.CHIIKI_CD = UPN_SAKI_GENBA2.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD
 LEFT JOIN M_CHIIKIBETSU_GYOUSHU UPN_SAKI_GYOUSHA_GYOUSHU2
        ON UPN_SAKI_GYOUSHA_GYOUSHU2.GYOUSHU_CD = UPN_SAKI_GENBA2.GYOUSHU_CD AND UPN_SAKI_GYOUSHA_GYOUSHU2.CHIIKI_CD = UPN_SAKI_GENBA2.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD
        
    -- 処分受託者情報の取得
 LEFT JOIN M_GYOUSHA SBN_GYOUSHA
        ON SBN_GYOUSHA.GYOUSHA_CD = MANI.SBN_GYOUSHA_CD
 LEFT JOIN M_TODOUFUKEN SBN_GYOUSHA_MT
        ON SBN_GYOUSHA_MT.TODOUFUKEN_CD = SBN_GYOUSHA.GYOUSHA_TODOUFUKEN_CD
 LEFT JOIN M_CHIIKI SBN_GYOUSHA_MC
        ON SBN_GYOUSHA_MC.CHIIKI_CD = SBN_GYOUSHA.CHIIKI_CD
 LEFT JOIN M_CHIIKIBETSU_GYOUSHU SBN_GYOUSHA_GYOUSHU
        ON SBN_GYOUSHA_GYOUSHU.GYOUSHU_CD = SBN_GYOUSHA.GYOUSHU_CD AND SBN_GYOUSHA_GYOUSHU.CHIIKI_CD = SBN_GYOUSHA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD

    -- 処分事業場情報の取得
 LEFT JOIN M_GENBA SBN_GENBA
        ON SBN_GENBA.GYOUSHA_CD = MANI.SBN_GYOUSHA_CD
       AND SBN_GENBA.GENBA_CD = MANI.SBN_GENBA_CD
 LEFT JOIN M_TODOUFUKEN SBN_GENBA_MT
        ON SBN_GENBA_MT.TODOUFUKEN_CD = SBN_GENBA.GENBA_TODOUFUKEN_CD
 LEFT JOIN M_CHIIKI SBN_GENBA_MC
        ON SBN_GENBA_MC.CHIIKI_CD = SBN_GENBA.CHIIKI_CD
 LEFT JOIN M_CHIIKIBETSU_GYOUSHU SBN_GENBA_GYOUSHU
        ON SBN_GENBA_GYOUSHU.GYOUSHU_CD = SBN_GENBA.GYOUSHU_CD AND SBN_GENBA_GYOUSHU.CHIIKI_CD = SBN_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD
 LEFT JOIN M_CHIIKIBETSU_KYOKA SBN_GENBA_MCK
        ON SBN_GENBA_MCK.GYOUSHA_CD = MANI.SBN_GYOUSHA_CD
       AND SBN_GENBA_MCK.GENBA_CD = MANI.SBN_GENBA_CD
       AND SBN_GENBA_MCK.CHIIKI_CD = SBN_GENBA.CHIIKI_CD
       AND SBN_GENBA_MCK.KYOKA_KBN = 2
 LEFT JOIN M_CHIIKIBETSU_KYOKA LAST_SBN_GENBA_MCK
        ON LAST_SBN_GENBA_MCK.GYOUSHA_CD = MANI.SBN_GYOUSHA_CD
       AND LAST_SBN_GENBA_MCK.GENBA_CD = MANI.SBN_GENBA_CD
       AND LAST_SBN_GENBA_MCK.CHIIKI_CD = SBN_GENBA.CHIIKI_CD
       AND LAST_SBN_GENBA_MCK.KYOKA_KBN = 3

    -- 処分方法情報の取得
 LEFT JOIN M_CHIIKIBETSU_SHOBUN MCS
        ON MCS.SHOBUN_HOUHOU_CD = MANI.SBN_HOUHOU_CD
       AND MCS.CHIIKI_CD = /*data.TEISHUTUSAKI_CD*/''
 LEFT JOIN M_CHIIKI TSS_MC
        ON TSS_MC.CHIIKI_CD = /*data.TEISHUTUSAKI_CD*/''
)   
SELECT
           HOUKOKU_BUNRUI_CD                          AS 運搬品目CD
          ,HOUKOKU_BUNRUI_NAME                        AS 運搬品目
          ,HOUKOKUSHO_BUNRUI_CD
          ,HAIKI_KBN_CD 
          ,HAIKI_SHURUI_CD
          ,SEKIMEN_KBN                                AS 石綿
          ,TOKUTEI_YUUGAI_KBN                         AS 特定有害
          ,ISNULL(KANSAN_SUU,0)                       AS 運搬委託量
          ,UNIT_NAME                                  AS 単位1
          ,HST_GYOUSHA_CD                             AS 排出事業者CD
          ,HST_GYOUSHA_NAME                           AS 排出事業者名
          ,HST_GYOUSHA_ADDRESS                        AS 排出事業者住所
          ,HST_GYOUSHA_CHIIKI_CD                      AS 排出事業者地域CD
          ,HST_GYOUSHA_CHIIKI_NAME                    AS 排出事業者地域名
          ,HST_GYOUSHA_GYOUSHU_CD                     AS 排出事業者業種CD
          ,HST_GYOUSHA_GYOUSHU_NAME                   AS 排出事業者業種名
          ,HST_GENBA_CD                               AS 排出事業場CD
          ,HST_GENBA_NAME                             AS 排出事業場名
          ,HST_GENBA_ADDRESS                          AS 排出事業場住所
          ,HST_GENBA_CHIIKI_CD                        AS 排出事業場地域CD
          ,HST_GENBA_CHIIKI_NAME                      AS 排出事業場地域名
          ,HST_GENBA_GYOUSHU_CD                       AS 排出事業場業種CD
          ,HST_GENBA_GYOUSHU_NAME                     AS 排出事業場業種名
          ,HST_GENBA_CHIIKI_CD                        AS 排出事業場地域CD
          ,UPN_GYOUSHA_CD1                            AS 運搬受託者CD1
          ,UPN_GYOUSHA_NAME1                          AS 運搬受託者名1
          ,UPN_GYOUSHA_ADDRESS1                       AS 運搬受託者住所1
          ,UPN_GYOUSHA_CHIIKI_CD1                     AS 運搬受託者地域CD1
          ,UPN_GYOUSHA_CHIIKI_NAME1                   AS 運搬受託者地域名1
          ,UPN_GYOUSHA_GYOUSHU_CD1                    AS 運搬受託者業種CD1
          ,UPN_GYOUSHA_GYOUSHU_NAME1                  AS 運搬受託者業種名1
          ,UPN_GYOUSHA_KYOKA1                         AS 運搬受託者許可番号1
          ,UPN_GYOUSHA_CD2                            AS 運搬受託者CD2
          ,UPN_GYOUSHA_NAME2                          AS 運搬受託者名2
          ,UPN_GYOUSHA_ADDRESS2                       AS 運搬受託者住所2
          ,UPN_GYOUSHA_CHIIKI_CD2                     AS 運搬受託者地域CD2
          ,UPN_GYOUSHA_CHIIKI_NAME2                   AS 運搬受託者地域名2
          ,UPN_GYOUSHA_GYOUSHU_CD2                    AS 運搬受託者業種CD2
          ,UPN_GYOUSHA_GYOUSHU_NAME2                  AS 運搬受託者業種名2
          ,UPN_GYOUSHA_KYOKA2                         AS 運搬受託者許可番号2
          ,UPN_GYOUSHA_CD3                            AS 運搬受託者CD3
          ,UPN_GYOUSHA_NAME3                          AS 運搬受託者名3
          ,UPN_GYOUSHA_ADDRESS3                       AS 運搬受託者住所3
          ,UPN_GYOUSHA_CHIIKI_CD3                     AS 運搬受託者地域CD3
          ,UPN_GYOUSHA_CHIIKI_NAME3                   AS 運搬受託者地域名3
          ,UPN_GYOUSHA_GYOUSHU_CD3                    AS 運搬受託者業種CD3
          ,UPN_GYOUSHA_GYOUSHU_NAME3                  AS 運搬受託者業種名3
          ,UPN_GYOUSHA_KYOKA3                         AS 運搬受託者許可番号3
          ,UPN_SAKI_GENBA_CD1                         AS 積替保管場所CD1
          ,UPN_GENBA_NAME1                            AS 積替保管場所名1
          ,UPN_GENBA_ADDRESS1                         AS 積替保管場所住所1
          ,UPN_GENBA_CHIIKI_CD1                       AS 積替保管場所地域CD1
          ,UPN_GENBA_CHIIKI_NAME1                     AS 積替保管場所地域名1
          ,UPN_GENBA_GYOUSHU_CD1                      AS 積替保管場所業種CD1
          ,UPN_GENBA_GYOUSHU_NAME1                    AS 積替保管場所業種名1
          ,UPN_SAKI_GENBA_CD2                         AS 積替保管場所CD2
          ,UPN_GENBA_NAME2                            AS 積替保管場所名2
          ,UPN_GENBA_ADDRESS2                         AS 積替保管場所住所2
          ,UPN_GENBA_CHIIKI_CD2                       AS 積替保管場所地域CD2
          ,UPN_GENBA_CHIIKI_NAME2                     AS 積替保管場所地域名2
          ,UPN_GENBA_GYOUSHU_CD2                      AS 積替保管場所業種CD2
          ,UPN_GENBA_GYOUSHU_NAME2                    AS 積替保管場所業種名2
          ,SBN_KYOKA                                  AS 処分許可番号
          ,SBN_GYOUSHA_CD                             AS 処分受託者CD
          ,SBN_GYOUSHA_NAME                           AS 処分受託者名
          ,SBN_GYOUSHA_ADDRESS                        AS 処分受託者住所
          ,SBN_GYOUSHA_CHIIKI_CD                      AS 処分受託者地域CD
          ,SBN_GYOUSHA_CHIIKI_NAME                    AS 処分受託者地域名
          ,SBN_GYOUSHA_GYOUSHU_CD                     AS 処分受託者業種CD
          ,SBN_GYOUSHA_GYOUSHU_NAME                   AS 処分受託者業種名
          ,SBN_GENBA_CD                               AS 処分事業場CD
          ,SBN_GENBA_NAME                             AS 処分事業場名
          ,SBN_GENBA_ADDRESS                          AS 処分事業場住所
          ,SBN_GENBA_CHIIKI_CD                        AS 処分事業場地域CD
          ,SBN_GENBA_CHIIKI_NAME                      AS 処分事業場地域名
          ,SBN_GENBA_GYOUSHU_CD                       AS 処分事業場業種CD
          ,SBN_GENBA_GYOUSHU_NAME                     AS 処分事業場業種名
          ,ISNULL(KANSAN_SUU,0)                       AS 処分量
          ,UNIT_NAME                                  AS 単位3
          ,SBN_HOUHOU_CD                              AS 処分方法CD
          ,SBN_HOUHOU_NAME                            AS 処分方法
/*IF data.CSV_SHUKEI_KBN ==2*/
          ,MANIFEST_ID                                AS 交付番号
          ,KOUFU_DATE                                 AS 交付年月日
          ,MANIFEST_KBN                               AS マニフェスト区分
/*END*/
     FROM SEARCH_DATA
    WHERE 1 = 1