   SELECT TJHE.TEISHUTSU_NAME,
          HG.GYOUSHA_NAME1 + HG.GYOUSHA_NAME2 AS NAME_1,
          HG.GYOUSHA_DAIHYOU AS NAME_2,
          HG.GYOUSHA_TEL
     FROM T_JISSEKI_HOUKOKU_ENTRY TJHE
LEFT JOIN T_JISSEKI_HOUKOKU_UPN_DETAIL TJHUD
       ON TJHE.SYSTEM_ID = TJHUD.SYSTEM_ID
      AND TJHE.SEQ = TJHUD.SEQ
LEFT JOIN M_GYOUSHA HG
       ON TJHE.HOUKOKU_GYOUSHA_CD = HG.GYOUSHA_CD
LEFT JOIN M_CHIIKIBETSU_KYOKA HCK
       ON HCK.CHIIKI_CD = TJHE.TEISHUTSU_CHIIKI_CD
      AND HCK.KYOKA_KBN = TJHE.TOKUBETSU_KANRI_KBN
    WHERE TJHE.SYSTEM_ID = /*data.SYSTEM_ID*/''
      AND TJHE.SEQ       = /*data.SEQ*/''
      AND TJHE.DELETE_FLG = 0