SELECT            
T_TEIKI_JISSEKI_ENTRY.DENPYOU_DATE, 
T_TEIKI_JISSEKI_DETAIL.GYOUSHA_CD,
T_TEIKI_JISSEKI_DETAIL.GENBA_CD,
T_TEIKI_JISSEKI_DETAIL.UNIT_CD, 
M_HINMEI.HINMEI_NAME, 
M_UNIT.UNIT_NAME, 
T_TEIKI_JISSEKI_DETAIL.TSUKIGIME_KBN, SUM(T_TEIKI_JISSEKI_DETAIL.SUURYOU) AS Expr1
FROM             
T_TEIKI_JISSEKI_ENTRY INNER JOIN
T_TEIKI_JISSEKI_DETAIL ON T_TEIKI_JISSEKI_ENTRY.SYSTEM_ID = T_TEIKI_JISSEKI_DETAIL.SYSTEM_ID AND T_TEIKI_JISSEKI_ENTRY.SEQ = T_TEIKI_JISSEKI_DETAIL.SEQ INNER JOIN
M_UNIT ON T_TEIKI_JISSEKI_DETAIL.UNIT_CD = M_UNIT.UNIT_CD INNER JOIN
M_HINMEI ON T_TEIKI_JISSEKI_DETAIL.HINMEI_CD = M_HINMEI.HINMEI_CD

GROUP BY      

T_TEIKI_JISSEKI_DETAIL.GYOUSHA_CD, T_TEIKI_JISSEKI_DETAIL.GENBA_CD, T_TEIKI_JISSEKI_DETAIL.UNIT_CD, T_TEIKI_JISSEKI_ENTRY.DENPYOU_DATE, 
M_HINMEI.HINMEI_NAME, M_UNIT.UNIT_NAME, T_TEIKI_JISSEKI_DETAIL.TSUKIGIME_KBN
ORDER BY       T_TEIKI_JISSEKI_DETAIL.GYOUSHA_CD DESC, T_TEIKI_JISSEKI_DETAIL.GENBA_CD DESC, T_TEIKI_JISSEKI_DETAIL.UNIT_CD DESC