SELECT
      --実績報告書データ
       TJHE.HOUKOKU_SHOSHIKI
      --,CASE WHEN TJHE.HOUKOKU_SHOSHIKI = 1 THEN '標準様式1-1号(普通産廃)'
      --      WHEN TJHE.HOUKOKU_SHOSHIKI = 2 THEN '標準様式1-2号(特管)'
      --      WHEN TJHE.HOUKOKU_SHOSHIKI = 3 THEN '標準様式1-3号(普通産廃集計表)'
      --      WHEN TJHE.HOUKOKU_SHOSHIKI = 4 THEN '標準様式1-4号(特管集計表)'
      --      ELSE NULL END AS HOUKOKU_SHOSHIKI_NAME
	  ,'標準様式1-1/1-2号' AS HOUKOKU_SHOSHIKI_NAME
      ,TJHE.HOUKOKU_YEAR
      ,TJHE.TEISHUTSU_CHIIKI_CD
      ,TJHE.GYOUSHA_KBN
      ,CASE WHEN TJHE.GYOUSHA_KBN = 1 THEN '中間処理'
            WHEN TJHE.GYOUSHA_KBN = 2 THEN '最終処分'
            WHEN TJHE.GYOUSHA_KBN = 3 THEN '収集運搬'
            ELSE NULL END AS GYOUSHA_KBN_NAME
      ,TJHE.UPDATE_DATE
      ,TJHE.TOKUBETSU_KANRI_KBN
      ,CASE WHEN TJHE.TOKUBETSU_KANRI_KBN = 1 THEN '産業廃棄物'
            WHEN TJHE.TOKUBETSU_KANRI_KBN = 2 THEN '特別管理産業廃棄物'
            ELSE NULL END AS TOKUBETSU_KANRI_SYURUI
      ,TJHE.KEN_KBN
      ,CASE WHEN TJHE.KEN_KBN = 1 THEN '県内'
            WHEN TJHE.KEN_KBN = 2 THEN '県外'
            WHEN TJHE.KEN_KBN = 3 THEN '全て'
            ELSE NULL END AS KEN_KBN_NAME
      ,TJHE.HOZON_NAME
      ,TJHE.TEISHUTSU_NAME
      ,MC.CHIIKI_NAME
      ,MC.GOV_OR_MAY_NAME
      --実績報告書　処分実績明細データ
      ,TJHSD.HOUKOKUSHO_BUNRUI_CD
      ,TJHSD.HOUKOKUSHO_BUNRUI_NAME
	  ,TJHSD.JYUTAKU_KBN
      ,TJHSD.JYUTAKU_RYOU
	  ,TJHSD.SHOBUN_HOUHOU_NAME
	  ,TJHSD.SBN_RYOU
	  ,TJHSD.SBN_AFTER_RYOU
      ,TJHSD.ITAKU_RYOU
      ,TJHSD.SYSTEM_ID
      ,TJHSD.SEQ
      ,TJHSD.DETAIL_SYSTEM_ID
      -- 帳票用データ
      ,TJHE.HOUKOKU_GYOUSHA_CD
      ,TJHE.HOUKOKU_GENBA_CD
      ,TJHE.HOUKOKU_TANTO_NAME
      ,TJHE.HOUKOKU_TITLE1
      ,TJHE.HOUKOKU_TITLE2
      ,TJHE.HST_GYOUSHA_NAME_DISP_KBN
      ,TJHSD.HST_GYOUSHA_CD
	  ,TJHSD.HST_GYOUSHA_NAME
	  ,TJHSD.HST_GYOUSHA_ADDRESS
      ,TJHSD.HST_GENBA_CD
	  ,TJHSD.HST_GENBA_NAME
	  ,TJHSD.HST_GENBA_ADDRESS
      ,TJHSD.HST_GENBA_CHIIKI_CD
      ,TJHSD.HST_KEN_KBN
      ,TJHSD.HST_JOU_TODOUFUKEN_CD
	  ,TJHSD.SBN_GYOUSHA_CD
	  ,TJHSD.SBN_GYOUSHA_NAME
	  ,TJHSD.SBN_GYOUSHA_ADDRESS
      ,TJHSD.SBN_GENBA_CD
	  ,TJHSD.SBN_GENBA_NAME
	  ,TJHSD.SBN_GENBA_ADDRESS
      ,TJHSD.SBN_GENBA_CHIIKI_CD
      ,TJHSD.ITAKU_KBN
	  ,TJHSD.ITAKUSAKI_KYOKA_NO
	  ,TJHSD.ITAKUSAKI_NAME
	  ,TJHSD.ITAKUSAKI_ADDRESS
  FROM T_JISSEKI_HOUKOKU_ENTRY AS TJHE
  LEFT JOIN T_JISSEKI_HOUKOKU_SBN_DETAIL AS TJHSD
         ON TJHE.SYSTEM_ID = TJHSD.SYSTEM_ID
        AND TJHE.SEQ = TJHSD.SEQ
  LEFT JOIN M_CHIIKI MC ON MC.CHIIKI_CD = TJHE.TEISHUTSU_CHIIKI_CD
 WHERE
       TJHE.SYSTEM_ID = /*systemid*/0
   AND TJHE.DELETE_FLG = 0
ORDER BY TJHSD.HST_KEN_KBN
       , TJHSD.HST_GENBA_CHIIKI_CD
	   , TJHSD.HOUKOKUSHO_BUNRUI_CD
	   , TJHSD.HST_JOU_TODOUFUKEN_CD
	   , TJHSD.HST_GYOUSHA_CD
	   , TJHSD.HST_GENBA_CD
	   , TJHSD.SHOBUN_HOUHOU_CD
	   , TJHSD.SBN_GYOUSHA_CD
	   , TJHSD.SBN_GENBA_CD
	   , TJHSD.SBN_GENBA_CHIIKI_CD
	   , TJHSD.ITAKUSAKI_CD
	   , TJHSD.ITAKU_GENBA_CD
	   , TJHSD.ITAKUSAKI_CHIIKI_CD