SELECT * FROM dbo.M_NISUGATA
WHERE 
/*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
 DELETE_FLG = 0
-- ELSE
 1 = 1
/*END*/
/*IF data.NISUGATA_CD != null*/AND NISUGATA_CD = /*data.NISUGATA_CD*//*END*/
/*IF data.NISUGATA_NAME != null*/AND NISUGATA_NAME = /*data.NISUGATA_NAME*//*END*/
/*IF data.NISUGATA_NAME_RYAKU != null*/AND NISUGATA_NAME_RYAKU = /*data.NISUGATA_NAME_RYAKU*//*END*/
/*IF data.NISUGATA_BIKOU != null*/AND NISUGATA_BIKOU = /*data.NISUGATA_BIKOU*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
/*IF !data.DENSHI_USE_KBN.IsNull*/AND DENSHI_USE_KBN = /*data.DENSHI_USE_KBN*//*END*/
/*IF !data.KAMI_USE_KBN.IsNull*/AND KAMI_USE_KBN = /*data.KAMI_USE_KBN*//*END*/