SELECT
	'受入' AS DENPYOU_SHURUI
	,UKEIRE_NUMBER AS DENPYOU_NUMBER
FROM
	T_UKEIRE_ENTRY
WHERE
	DELETE_FLG = 0
	/*IF FROM_DATE != null && FROM_DATE != ''*/
	AND CONVERT(DateTime,/*FROM_DATE*/'2015/1/1', 111) <= DENPYOU_DATE/*END*/
	AND DENPYOU_DATE <= CONVERT(DateTime,/*TO_DATE*/'2015/1/31', 111)
	AND (KAKUTEI_KBN = 2 OR TAIRYUU_KBN = 1)

UNION ALL

SELECT
	'出荷' AS DENPYOU_SHURUI
	,SHUKKA_NUMBER AS DENPYOU_NUMBER
FROM
	T_SHUKKA_ENTRY
WHERE
	DELETE_FLG = 0
	/*IF FROM_DATE != null && FROM_DATE != ''*/
	AND CONVERT(DateTime,/*FROM_DATE*/'2015/1/1', 111) <= DENPYOU_DATE/*END*/
	AND DENPYOU_DATE <= CONVERT(DateTime,/*TO_DATE*/'2015/1/31', 111)
	AND (KAKUTEI_KBN = 2 OR TAIRYUU_KBN = 1)

UNION ALL

-- 要検収だが未検収の検収データ
SELECT
	'出荷' AS DENPYOU_SHURUI
	,SHUKKA.SHUKKA_NUMBER AS DENPYOU_NUMBER
FROM
	T_SHUKKA_ENTRY AS SHUKKA
LEFT JOIN T_KENSHU_DETAIL AS KENSHU
	ON SHUKKA.SYSTEM_ID = KENSHU.SYSTEM_ID
	AND SHUKKA.SEQ = KENSHU.SEQ
WHERE
	DELETE_FLG = 0
	AND KENSHU.SYSTEM_ID IS NULL
	AND SHUKKA.KENSHU_MUST_KBN = 1
	AND SHUKKA.KAKUTEI_KBN = 1
	AND SHUKKA.TAIRYUU_KBN = 0
	/*IF FROM_DATE != null && FROM_DATE != ''*/
	AND CONVERT(DateTime,/*FROM_DATE*/'2015/1/1', 111) <= SHUKKA.DENPYOU_DATE/*END*/
	AND SHUKKA.DENPYOU_DATE <= CONVERT(DateTime,/*TO_DATE*/'2015/1/31', 111)

UNION ALL

SELECT
	'売上/支払' AS DENPYOU_SHURUI
	,UR_SH_NUMBER AS DENPYOU_NUMBER
FROM
	T_UR_SH_ENTRY
WHERE
	DELETE_FLG = 0
	/*IF FROM_DATE != null && FROM_DATE != ''*/
	AND CONVERT(DateTime,/*FROM_DATE*/'2015/1/1', 111) <= DENPYOU_DATE/*END*/
	AND DENPYOU_DATE <= CONVERT(DateTime,/*TO_DATE*/'2015/1/31', 111)
	AND KAKUTEI_KBN = 2