SELECT 
    UNT.SHAIN_CD,
    ISNULL(SHA.SHAIN_NAME,N'') AS SHAIN_NAME,
    ISNULL(SHA.SHAIN_FURIGANA,N'') AS SHAIN_FURIGANA,
    UNT.UNTENSHA_BIKOU,
	SHA.TEKIYOU_BEGIN,
	SHA.TEKIYOU_END,
	UNT.CREATE_USER,
	UNT.CREATE_DATE,
	UNT.UPDATE_USER,
	UNT.UPDATE_DATE
FROM 
    dbo.M_UNTENSHA UNT
		LEFT JOIN dbo.M_SHAIN SHA ON UNT.SHAIN_CD = SHA.SHAIN_CD
/*BEGIN*/WHERE
	/*IF data.SHAIN_CD != null*/ UNT.SHAIN_CD LIKE '%' +  /*data.SHAIN_CD*/ + '%'/*END*/
	/*IF data.UNTENSHA_BIKOU != null*/AND UNT.UNTENSHA_BIKOU LIKE '%' +  /*data.UNTENSHA_BIKOU*/ + '%'/*END*/
	/*IF data.SEARCH_TEKIYOU_BEGIN != null*/AND CONVERT(nvarchar, SHA.TEKIYOU_BEGIN, 120) LIKE '%' +  /*data.SEARCH_TEKIYOU_BEGIN*/ + '%'/*END*/
	/*IF data.SEARCH_TEKIYOU_END != null*/AND CONVERT(nvarchar, SHA.TEKIYOU_END, 120) LIKE '%' +  /*data.SEARCH_TEKIYOU_END*/ + '%'/*END*/
	/*IF data.UPDATE_USER != null*/AND UNT.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
	/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, UNT.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
	/*IF data.CREATE_USER != null*/AND UNT.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
	/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, UNT.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
/*END*/
ORDER BY 
	UNT.SHAIN_CD
