SELECT 
    KYO.*
    ,ISNULL(CHI.CHIIKI_NAME_RYAKU, N'') AS CHIIKI_NAME_RYAKU
FROM 
    M_CHIIKIBETSU_KYOKA KYO
	LEFT JOIN M_CHIIKI       CHI ON KYO.CHIIKI_CD = CHI.CHIIKI_CD
WHERE /*IF data.GYOUSHA_CD != null*/KYO.GYOUSHA_CD = /*data.GYOUSHA_CD*/''
-- ELSE KYO.GYOUSHA_CD = ''
/*END*/
  /*IF data.GENBA_CD != null*/AND KYO.GENBA_CD = /*data.GENBA_CD*/''
-- ELSE AND KYO.GENBA_CD = ''
/*END*/
 /*IF data.KYOKA_KBN != null*/AND KYO.KYOKA_KBN = /*data.KYOKA_KBN*/0/*END*/
ORDER BY KYO.KYOKA_KBN, KYO.GYOUSHA_CD, KYO.GENBA_CD, KYO.CHIIKI_CD
