SELECT
    MEI.*
	,HOU.HOUKOKUSHO_BUNRUI_NAME_RYAKU AS HOUKOKUSHO_BUNRUI_NAME_RYAKU
FROM 
    dbo.M_CHIIKIBETSU_KYOKA_MEIGARA MEI
	LEFT JOIN M_HOUKOKUSHO_BUNRUI HOU ON MEI.HOUKOKUSHO_BUNRUI_CD = HOU.HOUKOKUSHO_BUNRUI_CD
WHERE /*IF data.GYOUSHA_CD != null*/MEI.GYOUSHA_CD = /*data.GYOUSHA_CD*/
-- ELSE MEI.GYOUSHA_CD = ''
/*END*/
  /*IF data.GENBA_CD != null*/AND MEI.GENBA_CD = /*data.GENBA_CD*/
-- ELSE AND MEI.GENBA_CD = ''
/*END*/
/*IF !data.KYOKA_KBN.IsNull*/AND MEI.KYOKA_KBN = /*data.KYOKA_KBN.Value*//*END*/
/*IF data.CHIIKI_CD != null*/AND MEI.CHIIKI_CD = /*data.CHIIKI_CD*//*END*/
/*IF !data.TOKUBETSU_KANRI_KBN.IsNull*/ AND MEI.TOKUBETSU_KANRI_KBN = /*data.TOKUBETSU_KANRI_KBN*//*END*/
/*IF data.HOUKOKUSHO_BUNRUI_CD != null*/AND MEI.HOUKOKUSHO_BUNRUI_CD = /*data.HOUKOKUSHO_BUNRUI_CD*//*END*/
/*IF data.CREATE_USER != null*/AND MEI.CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND MEI.CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND MEI.CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND MEI.UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND MEI.UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND MEI.UPDATE_PC = /*data.UPDATE_PC*//*END*/
ORDER BY MEI.KYOKA_KBN, MEI.GYOUSHA_CD, MEI.GENBA_CD, MEI.CHIIKI_CD, MEI.TOKUBETSU_KANRI_KBN, MEI.HOUKOKUSHO_BUNRUI_CD
