SELECT 
    KYO.*
    ,ISNULL(CHI.CHIIKI_NAME_RYAKU, N'') AS CHIIKI_NAME_RYAKU
FROM 
    M_CHIIKIBETSU_KYOKA KYO
	LEFT JOIN M_CHIIKI  CHI ON KYO.CHIIKI_CD = CHI.CHIIKI_CD
WHERE /*IF data.GYOUSHA_CD != null*/KYO.GYOUSHA_CD = /*data.GYOUSHA_CD*/''
-- ELSE KYO.GYOUSHA_CD = ''
/*END*/
  /*IF data.GENBA_CD != null*/AND KYO.GENBA_CD = /*data.GENBA_CD*/''
-- ELSE AND KYO.GENBA_CD = ''
/*END*/
  /*IF data.KYOKA_KBN != null*/AND KYO.KYOKA_KBN = /*data.KYOKA_KBN*/0/*END*/
  /*IF data.CHIIKI_CD != null*/AND KYO.CHIIKI_CD LIKE '%' +  /*data.CHIIKI_CD*/ + '%'/*END*/
  /*IF data.FUTSUU_KYOKA_NO != null*/AND KYO.FUTSUU_KYOKA_NO LIKE '%' +  /*data.FUTSUU_KYOKA_NO*/ + '%'/*END*/
  /*IF data.SEARCH_FUTSUU_KYOKA_BEGIN != null*/ AND CONVERT(nvarchar, KYO.FUTSUU_KYOKA_BEGIN, 120) LIKE '%' +  /*data.SEARCH_FUTSUU_KYOKA_BEGIN*/ + '%'/*END*/
  /*IF data.SEARCH_FUTSUU_KYOKA_END != null*/ AND CONVERT(nvarchar, KYO.FUTSUU_KYOKA_END, 120) LIKE '%' +  /*data.SEARCH_FUTSUU_KYOKA_END*/ + '%'/*END*/
  /*IF data.FUTSUU_KYOKA_FILE_PATH != null*/AND KYO.FUTSUU_KYOKA_FILE_PATH LIKE '%' +  /*data.FUTSUU_KYOKA_FILE_PATH*/ + '%'/*END*/
  /*IF data.TOKUBETSU_KYOKA_NO != null*/AND KYO.TOKUBETSU_KYOKA_NO LIKE '%' +  /*data.TOKUBETSU_KYOKA_NO*/ + '%'/*END*/
  /*IF data.SEARCH_TOKUBETSU_KYOKA_BEGIN != null*/ AND CONVERT(nvarchar, KYO.TOKUBETSU_KYOKA_BEGIN, 120) LIKE '%' +  /*data.SEARCH_TOKUBETSU_KYOKA_BEGIN*/ + '%'/*END*/
  /*IF data.SEARCH_TOKUBETSU_KYOKA_END != null*/ AND CONVERT(nvarchar, KYO.TOKUBETSU_KYOKA_END, 120) LIKE '%' +  /*data.SEARCH_TOKUBETSU_KYOKA_END*/ + '%'/*END*/
  /*IF data.TOKUBETSU_KYOKA_FILE_PATH != null*/AND KYO.TOKUBETSU_KYOKA_FILE_PATH LIKE '%' +  /*data.TOKUBETSU_KYOKA_FILE_PATH*/ + '%'/*END*/
  /*IF data.CHIIKIBETSU_KYOKA_BIKOU != null*/AND KYO.CHIIKIBETSU_KYOKA_BIKOU LIKE '%' +  /*data.CHIIKIBETSU_KYOKA_BIKOU*/ + '%'/*END*/
  /*IF data.CREATE_USER != null*/AND KYO.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
  /*IF data.UPDATE_USER != null*/AND KYO.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
  /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, KYO.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
  /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, KYO.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
  /*IF !deletechuFlg*/AND KYO.DELETE_FLG = /*deletechuFlg*/0/*END*/
ORDER BY KYO.KYOKA_KBN, KYO.GYOUSHA_CD, KYO.GENBA_CD, KYO.CHIIKI_CD
