SELECT 
    GENNYOURITSU.*
    ,ISNULL(HOUKOKUSHO.HOUKOKUSHO_BUNRUI_NAME_RYAKU,N'') AS HOUKOKUSHO_BUNRUI_NAME_RYAKU
    ,ISNULL(HAIKI.HAIKI_NAME_RYAKU,N'') AS HAIKI_NAME_RYAKU
    ,ISNULL(SHOBUN.SHOBUN_HOUHOU_NAME_RYAKU,N'') AS SHOBUN_HOUHOU_NAME_RYAKU
    ,GENNYOURITSU.HOUKOKUSHO_BUNRUI_CD AS UK_HOUKOKUSHO_BUNRUI_CD
    ,GENNYOURITSU.HAIKI_NAME_CD AS UK_HAIKI_NAME_CD
    ,GENNYOURITSU.SHOBUN_HOUHOU_CD AS UK_SHOBUN_HOUHOU_CD
FROM 
	dbo.M_HAIKI_NAME HAIKI
	INNER JOIN dbo.M_GENNYOURITSU GENNYOURITSU ON HAIKI.HAIKI_NAME_CD = GENNYOURITSU.HAIKI_NAME_CD
	LEFT JOIN dbo.M_HOUKOKUSHO_BUNRUI HOUKOKUSHO ON GENNYOURITSU.HOUKOKUSHO_BUNRUI_CD = HOUKOKUSHO.HOUKOKUSHO_BUNRUI_CD
	LEFT JOIN dbo.M_SHOBUN_HOUHOU SHOBUN ON GENNYOURITSU.SHOBUN_HOUHOU_CD = SHOBUN.SHOBUN_HOUHOU_CD
/*BEGIN*/WHERE
 /*IF data.HAIKI_NAME_CD != null*/HAIKI.HAIKI_NAME_CD LIKE '%' + /*data.HAIKI_NAME_CD*/'000001' + '%'/*END*/
 /*IF data.HAIKI_NAME_RYAKU != null*/AND HAIKI.HAIKI_NAME_RYAKU LIKE '%' +  /*data.HAIKI_NAME_RYAKU*/ + '%'/*END*/
 /*IF !deletechuFlg*/AND GENNYOURITSU.DELETE_FLG = /*deletechuFlg*/0/*END*/
/*END*/
ORDER BY GENNYOURITSU.HOUKOKUSHO_BUNRUI_CD, GENNYOURITSU.HAIKI_NAME_CD, GENNYOURITSU.SHOBUN_HOUHOU_CD
