
SELECT 
    GENNYOURITSU.*
    ,ISNULL(HOUKOKUSHO.HOUKOKUSHO_BUNRUI_NAME_RYAKU,N'') AS HOUKOKUSHO_BUNRUI_NAME_RYAKU
    ,ISNULL(HAIKI.HAIKI_NAME_RYAKU,N'') AS HAIKI_NAME_RYAKU
    ,ISNULL(SHOBUN.SHOBUN_HOUHOU_NAME_RYAKU,N'') AS SHOBUN_HOUHOU_NAME_RYAKU
    ,GENNYOURITSU.HOUKOKUSHO_BUNRUI_CD AS UK_HOUKOKUSHO_BUNRUI_CD
    ,GENNYOURITSU.HAIKI_NAME_CD AS UK_HAIKI_NAME_CD
    ,GENNYOURITSU.SHOBUN_HOUHOU_CD AS UK_SHOBUN_HOUHOU_CD
FROM 
    dbo.M_SHOBUN_HOUHOU SHOBUN
    INNER JOIN dbo.M_GENNYOURITSU GENNYOURITSU ON SHOBUN.SHOBUN_HOUHOU_CD = GENNYOURITSU.SHOBUN_HOUHOU_CD
    LEFT JOIN dbo.M_HOUKOKUSHO_BUNRUI HOUKOKUSHO ON GENNYOURITSU.HOUKOKUSHO_BUNRUI_CD = HOUKOKUSHO.HOUKOKUSHO_BUNRUI_CD
    LEFT JOIN dbo.M_HAIKI_NAME HAIKI ON GENNYOURITSU.HAIKI_NAME_CD = HAIKI.HAIKI_NAME_CD
/*BEGIN*/WHERE
 /*IF data.SHOBUN_HOUHOU_CD != null*/SHOBUN.SHOBUN_HOUHOU_CD LIKE '%' + /*data.SHOBUN_HOUHOU_CD*/'001' + '%'/*END*/
 /*IF data.SHOBUN_HOUHOU_NAME_RYAKU != null*/AND SHOBUN.SHOBUN_HOUHOU_NAME_RYAKU LIKE '%' +  /*data.SHOBUN_HOUHOU_NAME_RYAKU*/ + '%'/*END*/
 /*IF !deletechuFlg*/AND GENNYOURITSU.DELETE_FLG = /*deletechuFlg*/0/*END*/
/*END*/
ORDER BY GENNYOURITSU.HOUKOKUSHO_BUNRUI_CD, GENNYOURITSU.HAIKI_NAME_CD, GENNYOURITSU.SHOBUN_HOUHOU_CD
