UPDATE M_GENNYOURITSU SET
	HOUKOKUSHO_BUNRUI_CD = /*data.HOUKOKUSHO_BUNRUI_CD*/'',
	HAIKI_NAME_CD = /*data.HAIKI_NAME_CD*/'',
	SHOBUN_HOUHOU_CD = /*data.SHOBUN_HOUHOU_CD*/0,
	GENNYOURITSU = /*data.GENNYOURITSU*/'',
	GENNYOURITSU_BIKOU = /*data.GENNYOURITSU_BIKOU*/0,
	UPDATE_USER = /*data.UPDATE_USER*/'',
	UPDATE_DATE = CONVERT(DATETIME, /*data.UPDATE_DATE*/null, 120),
	UPDATE_PC = /*data.UPDATE_PC*/'',
	DELETE_FLG = /*data.DELETE_FLG*/0
WHERE HOUKOKUSHO_BUNRUI_CD = /*updateKey.HOUKOKUSHO_BUNRUI_CD*/''
  AND HAIKI_NAME_CD = /*updateKey.HAIKI_NAME_CD*/''
  AND SHOBUN_HOUHOU_CD = /*updateKey.SHOBUN_HOUHOU_CD*/0
