SELECT ISNULL(MIN(PO.POINT_ID),1) POINT_ID
FROM 
	(
		SELECT (CONVERT(INT, POINT_ID) + 1) POINT_ID FROM M_GENBA_DIGI WHERE ISNUMERIC(POINT_ID)=1 
	) PO
WHERE PO.POINT_ID NOT IN (
		SELECT (CONVERT(INT, POINT_ID) + 0) POINT_ID FROM M_GENBA_DIGI WHERE ISNUMERIC(POINT_ID)=1
	)