SELECT 
    KEI.*
	,BU.DENSHU_KBN_NAME_RYAKU
    ,ISNULL(BU.DENSHU_KBN_NAME_RYAKU,N'') AS DENSHU_KBN_NAME_RYAKU
FROM 
    dbo.M_KEITAI_KBN KEI
    LEFT JOIN dbo.M_DENSHU_KBN BU ON BU.DENSHU_KBN_CD = KEI.DENSHU_KBN_CD
ORDER BY KEI.KEITAI_KBN_CD
