//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shougun.Core.Carriage.Unchinichiran.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_KYOTEN_CD {
            get {
                return ((string)(this["SET_KYOTEN_CD"]));
            }
            set {
                this["SET_KYOTEN_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HIDUKE_TO {
            get {
                return ((string)(this["SET_HIDUKE_TO"]));
            }
            set {
                this["SET_HIDUKE_TO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HIDUKE_FROM {
            get {
                return ((string)(this["SET_HIDUKE_FROM"]));
            }
            set {
                this["SET_HIDUKE_FROM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HIDUKESENTAKU {
            get {
                return ((string)(this["SET_HIDUKESENTAKU"]));
            }
            set {
                this["SET_HIDUKESENTAKU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_TORIHIKISAKI {
            get {
                return ((string)(this["SET_TORIHIKISAKI"]));
            }
            set {
                this["SET_TORIHIKISAKI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_GYOUSYA {
            get {
                return ((string)(this["SET_GYOUSYA"]));
            }
            set {
                this["SET_GYOUSYA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_GENNBA {
            get {
                return ((string)(this["SET_GENNBA"]));
            }
            set {
                this["SET_GENNBA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_UNBANGYOUSYA {
            get {
                return ((string)(this["SET_UNBANGYOUSYA"]));
            }
            set {
                this["SET_UNBANGYOUSYA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_NIOTOSUGYOUSYA {
            get {
                return ((string)(this["SET_NIOTOSUGYOUSYA"]));
            }
            set {
                this["SET_NIOTOSUGYOUSYA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_NIOTOSUBA {
            get {
                return ((string)(this["SET_NIOTOSUBA"]));
            }
            set {
                this["SET_NIOTOSUBA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_DENPYO_KIND_CD {
            get {
                return ((string)(this["SET_DENPYO_KIND_CD"]));
            }
            set {
                this["SET_DENPYO_KIND_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_DENPYO_KBN_CD {
            get {
                return ((string)(this["SET_DENPYO_KBN_CD"]));
            }
            set {
                this["SET_DENPYO_KBN_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_KENSHU_MUST_KBN {
            get {
                return ((string)(this["SET_KENSHU_MUST_KBN"]));
            }
            set {
                this["SET_KENSHU_MUST_KBN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_KENSHU_JYOUKYOU {
            get {
                return ((string)(this["SET_KENSHU_JYOUKYOU"]));
            }
            set {
                this["SET_KENSHU_JYOUKYOU"] = value;
            }
        }
    }
}
