SELECT TDS.KANSANCHI, TDS.KANSAN_UNIT_CD FROM T_TEIKI_HAISHA_ENTRY AS TE
INNER JOIN (
	SELECT TD.GYOUSHA_CD, TD.GENBA_CD, TS.* FROM T_TEIKI_HAISHA_DETAIL AS TD
	INNER JOIN T_TEIKI_HAISHA_SHOUSAI AS TS ON (
	(TD.SYSTEM_ID = TS.SYSTEM_ID) AND
	(TD.SEQ = TS.SEQ) AND
	(TD.DETAIL_SYSTEM_ID = TS.DETAIL_SYSTEM_ID))
) AS TDS ON (
(TE.SYSTEM_ID = TDS.SYSTEM_ID) AND
(TE.SEQ = TDS.SEQ))
WHERE (TE.DELETE_FLG = 0)
	  /*IF data.HAISHA_DENPYOU_NO != null*/AND (TE.TEIKI_HAISHA_NUMBER = /*data.HAISHA_DENPYOU_NO*/)/*END*/
	  /*IF data.GYOUSHA_CD != null*/AND (TDS.GYOUSHA_CD = /*data.GYOUSHA_CD*/)/*END*/
	  /*IF data.GENBA_CD != null*/AND (TDS.GENBA_CD = /*data.GENBA_CD*/)/*END*/
	  /*IF data.HINMEI_CD != null*/AND (TDS.HINMEI_CD = /*data.HINMEI_CD*/)/*END*/
	  /*IF !data.UNIT_CD.IsNull*/AND (TDS.UNIT_CD = /*data.UNIT_CD.Value*/)/*END*/
	  /*IF !data.DENPYOU_KBN_CD.IsNull*/AND (TDS.DENPYOU_KBN_CD = /*data.DENPYOU_KBN_CD.Value*/)/*END*/
