SELECT DISTINCT N'現場マスタ' AS NAME FROM M_GENBA WHERE SHIKUCHOUSON_CD IN /*SHIKUCHOUSON_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'引合現場マスタ' AS NAME FROM M_HIKIAI_GENBA WHERE SHIKUCHOUSON_CD IN /*SHIKUCHOUSON_CD*/('') AND DELETE_FLG = 'False'