//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItakuKeiyakuHoshu.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ItakuKeiyakuHoshu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUNRUI_1 {
            get {
                return ResourceManager.GetString("BUNRUI_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUNRUI_2 {
            get {
                return ResourceManager.GetString("BUNRUI_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最終処分先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUNRUI_3 {
            get {
                return ResourceManager.GetString("BUNRUI_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再中間処理先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUNRUI_4 {
            get {
                return ResourceManager.GetString("BUNRUI_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPLETE {
            get {
                return ResourceManager.GetString("COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が{1}より前の日付になっています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DATE_ERR_FMT1 {
            get {
                return ResourceManager.GetString("DATE_ERR_FMT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が{1}より後の日付になっています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DATE_ERR_FMT2 {
            get {
                return ResourceManager.GetString("DATE_ERR_FMT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除が に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string END_KUBUN_1 {
            get {
                return ResourceManager.GetString("END_KUBUN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string END_KUBUN_2 {
            get {
                return ResourceManager.GetString("END_KUBUN_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最終 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string END_KUBUN_3 {
            get {
                return ResourceManager.GetString("END_KUBUN_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_TITLE {
            get {
                return ResourceManager.GetString("ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   業者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GYOUSHA {
            get {
                return ResourceManager.GetString("GYOUSHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   排出事業場 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HAISHUTSU_JIGYOUJOU {
            get {
                return ResourceManager.GetString("HAISHUTSU_JIGYOUJOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   排出事業場CD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HAISHUTSU_JIGYOUJOU_CD {
            get {
                return ResourceManager.GetString("HAISHUTSU_JIGYOUJOU_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   排出事業者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HAISHUTSU_JIGYOUSHA {
            get {
                return ResourceManager.GetString("HAISHUTSU_JIGYOUSHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   報告書分類 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HOUKOKUSHO_BUNRUI {
            get {
                return ResourceManager.GetString("HOUKOKUSHO_BUNRUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   収集運搬契約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ITAKU_KEIYAKU_SHURUI_1 {
            get {
                return ResourceManager.GetString("ITAKU_KEIYAKU_SHURUI_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処分契約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ITAKU_KEIYAKU_SHURUI_2 {
            get {
                return ResourceManager.GetString("ITAKU_KEIYAKU_SHURUI_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   収集運搬/処分契約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ITAKU_KEIYAKU_SHURUI_3 {
            get {
                return ResourceManager.GetString("ITAKU_KEIYAKU_SHURUI_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ITAKU_KEIYAKU_STATUS_1 {
            get {
                return ResourceManager.GetString("ITAKU_KEIYAKU_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ITAKU_KEIYAKU_STATUS_2 {
            get {
                return ResourceManager.GetString("ITAKU_KEIYAKU_STATUS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返送 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ITAKU_KEIYAKU_STATUS_3 {
            get {
                return ResourceManager.GetString("ITAKU_KEIYAKU_STATUS_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保管 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ITAKU_KEIYAKU_STATUS_4 {
            get {
                return ResourceManager.GetString("ITAKU_KEIYAKU_STATUS_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解約済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ITAKU_KEIYAKU_STATUS_5 {
            get {
                return ResourceManager.GetString("ITAKU_KEIYAKU_STATUS_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KEIYAKUSHO_CREATE_DATE {
            get {
                return ResourceManager.GetString("KEIYAKUSHO_CREATE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保管日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KEIYAKUSHO_END_DATE {
            get {
                return ResourceManager.GetString("KEIYAKUSHO_END_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返送日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KEIYAKUSHO_RETURN_DATE {
            get {
                return ResourceManager.GetString("KEIYAKUSHO_RETURN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送付日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KEIYAKUSHO_SEND_DATE {
            get {
                return ResourceManager.GetString("KEIYAKUSHO_SEND_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   許 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KONGOU_1 {
            get {
                return ResourceManager.GetString("KONGOU_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   否 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KONGOU_2 {
            get {
                return ResourceManager.GetString("KONGOU_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動更新終了日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KOUSHIN_END_DATE {
            get {
                return ResourceManager.GetString("KOUSHIN_END_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   普通産廃運搬 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KYOKA_KBN_1 {
            get {
                return ResourceManager.GetString("KYOKA_KBN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   特別産廃運搬 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KYOKA_KBN_2 {
            get {
                return ResourceManager.GetString("KYOKA_KBN_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   普通中間処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KYOKA_KBN_3 {
            get {
                return ResourceManager.GetString("KYOKA_KBN_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   特別中間処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KYOKA_KBN_4 {
            get {
                return ResourceManager.GetString("KYOKA_KBN_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   普通最終処分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KYOKA_KBN_5 {
            get {
                return ResourceManager.GetString("KYOKA_KBN_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   特別最終処分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KYOKA_KBN_6 {
            get {
                return ResourceManager.GetString("KYOKA_KBN_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最後の伝票です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LAST_DETAIL {
            get {
                return ResourceManager.GetString("LAST_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最終処分場 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LAST_SHOBUN_JIGYOUJOU {
            get {
                return ResourceManager.GetString("LAST_SHOBUN_JIGYOUJOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現場 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_GENBA {
            get {
                return ResourceManager.GetString("M_GENBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単位 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_UNIT {
            get {
                return ResourceManager.GetString("M_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当データがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOTING_DATE {
            get {
                return ResourceManager.GetString("NOTING_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録が に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処分業者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SHOBUN_GYOUSHA {
            get {
                return ResourceManager.GetString("SHOBUN_GYOUSHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処分方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SHOBUN_HOUHOU {
            get {
                return ResourceManager.GetString("SHOBUN_HOUHOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処分事業場 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SHOBUN_JIGYOUJOU {
            get {
                return ResourceManager.GetString("SHOBUN_JIGYOUJOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   許 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SHUSENBETU_1 {
            get {
                return ResourceManager.GetString("SHUSENBETU_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   否 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SHUSENBETU_2 {
            get {
                return ResourceManager.GetString("SHUSENBETU_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYSTEM_ID {
            get {
                return ResourceManager.GetString("SYSTEM_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   （建廃） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TITLE_KENPAI {
            get {
                return ResourceManager.GetString("TITLE_KENPAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   （産廃） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TITLE_SANPAI {
            get {
                return ResourceManager.GetString("TITLE_SANPAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   積替・保管施設 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UNPAN_END_1 {
            get {
                return ResourceManager.GetString("UNPAN_END_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処分施設 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UNPAN_END_2 {
            get {
                return ResourceManager.GetString("UNPAN_END_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   排出場所 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UNPAN_FROM_1 {
            get {
                return ResourceManager.GetString("UNPAN_FROM_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   積替・保管施設 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UNPAN_FROM_2 {
            get {
                return ResourceManager.GetString("UNPAN_FROM_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運搬業者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UNPAN_GYOUSHA {
            get {
                return ResourceManager.GetString("UNPAN_GYOUSHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効期限開始日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YUUKOU_BEGIN {
            get {
                return ResourceManager.GetString("YUUKOU_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効期限終了日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YUUKOU_END {
            get {
                return ResourceManager.GetString("YUUKOU_END", resourceCulture);
            }
        }
    }
}
