SELECT ISNULL(MIN(N.NYUUKINSAKI_CD),1) NYUUKINSAKI_CD
FROM (
		SELECT (NYUUKINSAKI_CD+1) NYUUKINSAKI_CD FROM M_NYUUKINSAKI WHERE ISNUMERIC(NYUUKINSAKI_CD)=1 
		UNION 
		SELECT (TORIHIKISAKI_CD+1) NYUUKINSAKI_CD FROM M_TORIHIKISAKI WHERE ISNUMERIC(TORIHIKISAKI_CD)=1
	) N
WHERE N.NYUUKINSAKI_CD NOT IN (
		SELECT (NYUUKINSAKI_CD+0) NYUUKINSAKI_CD FROM M_NYUUKINSAKI WHERE ISNUMERIC(NYUUKINSAKI_CD)=1
		UNION
		SELECT (TORIHIKISAKI_CD+0) NYUUKINSAKI_CD FROM M_TORIHIKISAKI WHERE ISNUMERIC(TORIHIKISAKI_CD)=1
	)