select 
ROW_NUMBER() OVER (ORDER BY SORT_SEIKYUU_DATE) AS ROW_NUMBER
,inview.GYOUSHA_CD 
,inview.GYOUSHA_NAME_RYAKU
,inview.GENBA_CD
,inview.GENBA_NAME_RYAKU
,inview.SEIKYUU_DATE
,inview.SEIKYUUGAKU AS SEIKYUUGAKU
,inview.KESHIKOMIGAKU AS KeshikomiGaku
,inview.KESHIKOMIGAKU_TOTAL AS KESHIKOMIGAKU_TOTAL
,inview.MIKESHIKOMIGAKU AS MiKeshikomiGaku
,inview.SEIKYUU_NUMBER
,inview.KAGAMI_NUMBER
,inview.SYSTEM_ID
,inview.KESHIKOMI_SEQ
,inview.NYUUKIN_NUMBER
,inview.KESHIKOMI_BIKOU
 FROM
 (
 SELECT
    TNK.SYSTEM_ID AS SYSTEM_ID,
	TNK.KESHIKOMI_SEQ AS KESHIKOMI_SEQ,
	NULL AS GYOUSHA_CD,
	NULL AS GYOUSHA_NAME_RYAKU,
	NULL AS GENBA_CD,
	NULL AS GENBA_NAME_RYAKU,
	'開始残高' AS SEIKYUU_DATE,
	'1753-01-01 00:00:00.000' AS SORT_SEIKYUU_DATE,
	ISNULL(MTS.KAISHI_URIKAKE_ZANDAKA,0) AS SEIKYUUGAKU,
	TNK.KESHIKOMI_GAKU AS KESHIKOMIGAKU,
	ISNULL(TNK2.KESHIKOMI_GAKU_TOTAL,0) AS KESHIKOMIGAKU_TOTAL,
	ISNULL(MTS.KAISHI_URIKAKE_ZANDAKA,0) - ISNULL(TNK2.KESHIKOMI_GAKU_TOTAL, 0) AS MIKESHIKOMIGAKU,
	0 AS SEIKYUU_NUMBER,
	0 AS KAGAMI_NUMBER,
	TNK.NYUUKIN_NUMBER AS NYUUKIN_NUMBER,
	TNK.KESHIKOMI_BIKOU AS KESHIKOMI_BIKOU
FROM
    M_TORIHIKISAKI_SEIKYUU MTS
LEFT JOIN T_NYUUKIN_KESHIKOMI TNK 
       ON MTS.TORIHIKISAKI_CD = TNK.TORIHIKISAKI_CD
	  AND TNK.SEIKYUU_NUMBER = 0
	  AND TNK.KAGAMI_NUMBER = 0
	  AND TNK.DELETE_FLG = 0
	  AND TNK.NYUUKIN_NUMBER = /*nyuukinNumber*/
LEFT JOIN (SELECT
              T_NYUUKIN_KESHIKOMI.SEIKYUU_NUMBER,
			  T_NYUUKIN_KESHIKOMI.KAGAMI_NUMBER,
			  T_NYUUKIN_KESHIKOMI.TORIHIKISAKI_CD,
			  SUM(T_NYUUKIN_KESHIKOMI.KESHIKOMI_GAKU) AS KESHIKOMI_GAKU_TOTAL
			FROM T_NYUUKIN_KESHIKOMI T_NYUUKIN_KESHIKOMI
			WHERE T_NYUUKIN_KESHIKOMI.DELETE_FLG = 0
			GROUP BY T_NYUUKIN_KESHIKOMI.SEIKYUU_NUMBER,
			         T_NYUUKIN_KESHIKOMI.KAGAMI_NUMBER,
			         T_NYUUKIN_KESHIKOMI.TORIHIKISAKI_CD) TNK2
	  ON TNK2.SEIKYUU_NUMBER = 0
	  AND TNK2.KAGAMI_NUMBER = 0
	  AND MTS.TORIHIKISAKI_CD = TNK2.TORIHIKISAKI_CD
	WHERE
	MTS.TORIHIKISAKI_CD = /*torihikisakiCd*/
UNION
SELECT
    TNK.SYSTEM_ID AS SYSTEM_ID,
	TNK.KESHIKOMI_SEQ AS KESHIKOMI_SEQ,
	TSDK.GYOUSHA_CD AS GYOUSHA_CD,
	MGYOUSHA.GYOUSHA_NAME_RYAKU AS GYOUSHA_NAME_RYAKU,
	TSDK.GENBA_CD AS GENBA_CD,
	MGENBA.GENBA_NAME_RYAKU AS GENBA_NAME_RYAKU,
	CONVERT(varchar(10), TSD.SEIKYUU_DATE, 111) AS SEIKYUU_DATE,
	TSD.SEIKYUU_DATE AS SORT_SEIKYUU_DATE,
	ISNULL(TSDK.KONKAI_URIAGE_GAKU,0)
	+ ISNULL(TSDK.KONKAI_SEI_UTIZEI_GAKU,0)
	+ ISNULL(TSDK.KONKAI_SEI_SOTOZEI_GAKU ,0)
	+ ISNULL(TSDK.KONKAI_DEN_UTIZEI_GAKU,0)
	+ ISNULL(TSDK.KONKAI_DEN_SOTOZEI_GAKU,0)
	+ ISNULL(TSDK.KONKAI_MEI_UTIZEI_GAKU,0)
	+ ISNULL(TSDK.KONKAI_MEI_SOTOZEI_GAKU,0) AS SEIKYUUGAKU,
	TNK.KESHIKOMI_GAKU AS KESHIKOMIGAKU,
	ISNULL(TNK2.KESHIKOMI_GAKU_TOTAL, 0) AS KESHIKOMIGAKU_TOTAL,
	ISNULL(TSDK.KONKAI_URIAGE_GAKU,0)
	+ ISNULL(TSDK.KONKAI_SEI_UTIZEI_GAKU,0)
	+ ISNULL(TSDK.KONKAI_SEI_SOTOZEI_GAKU ,0)
	+ ISNULL(TSDK.KONKAI_DEN_UTIZEI_GAKU,0)
	+ ISNULL(TSDK.KONKAI_DEN_SOTOZEI_GAKU,0)
	+ ISNULL(TSDK.KONKAI_MEI_UTIZEI_GAKU,0)
	+ ISNULL(TSDK.KONKAI_MEI_SOTOZEI_GAKU,0)
	- ISNULL(TNK2.KESHIKOMI_GAKU_TOTAL, 0) AS MIKESHIKOMIGAKU,
	TSD.SEIKYUU_NUMBER AS SEIKYUU_NUMBER,
	TSDK.KAGAMI_NUMBER AS KAGAMI_NUMBER,
	TNK.NYUUKIN_NUMBER AS NYUUKIN_NUMBER,
	TNK.KESHIKOMI_BIKOU AS KESHIKOMI_BIKOU
FROM
	T_SEIKYUU_DENPYOU TSD
LEFT JOIN T_SEIKYUU_DENPYOU_KAGAMI TSDK 
       ON TSDK.SEIKYUU_NUMBER = TSD.SEIKYUU_NUMBER 
	   AND TSDK.DELETE_FLG = 0
LEFT JOIN T_NYUUKIN_KESHIKOMI TNK
       ON TNK.SEIKYUU_NUMBER = TSDK.SEIKYUU_NUMBER
	   AND TNK.KAGAMI_NUMBER = TSDK.KAGAMI_NUMBER
	   AND TNK.DELETE_FLG = 0
	   AND TNK.NYUUKIN_NUMBER = /*nyuukinNumber*/
LEFT JOIN M_GYOUSHA MGYOUSHA
       ON MGYOUSHA.GYOUSHA_CD = TSDK.GYOUSHA_CD
LEFT JOIN M_GENBA MGENBA 
       ON MGENBA.GYOUSHA_CD = TSDK.GYOUSHA_CD
	   AND MGENBA.GENBA_CD = TSDK.GENBA_CD
LEFT JOIN (SELECT
              T_NYUUKIN_KESHIKOMI.SEIKYUU_NUMBER,
			  T_NYUUKIN_KESHIKOMI.KAGAMI_NUMBER,
			  SUM(T_NYUUKIN_KESHIKOMI.KESHIKOMI_GAKU) AS KESHIKOMI_GAKU_TOTAL
			FROM T_NYUUKIN_KESHIKOMI T_NYUUKIN_KESHIKOMI
			WHERE T_NYUUKIN_KESHIKOMI.DELETE_FLG = 0
			GROUP BY T_NYUUKIN_KESHIKOMI.SEIKYUU_NUMBER,
			         T_NYUUKIN_KESHIKOMI.KAGAMI_NUMBER
		   ) TNK2
	   ON TNK2.SEIKYUU_NUMBER = TSDK.SEIKYUU_NUMBER
	  AND TNK2.KAGAMI_NUMBER = TSDK.KAGAMI_NUMBER
WHERE
	TSD.TORIHIKISAKI_CD = /*torihikisakiCd*/
	AND TSD.SEIKYUU_DATE <= /*denpyouDate*/
	AND TSD.DELETE_FLG = 0
) inview
WHERE inview.MIKESHIKOMIGAKU <> 0 
OR inview.NYUUKIN_NUMBER = /*nyuukinNumber*/
order by ROW_NUMBER, GYOUSHA_CD, GENBA_CD
