SELECT MHS.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_CD
     , MHB.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_NAME
     , CONVERT(VARCHAR(10), TME2.KOUFU_DATE, 111) AS ITAKU_NENGAPPI 
     , TME2.HAIKI_KBN_CD
     , CASE 
           WHEN TME2.HAIKI_KBN_CD = '1' THEN '産廃(直行)' 
           WHEN TME2.HAIKI_KBN_CD = '2' THEN '建廃' 
           WHEN TME2.HAIKI_KBN_CD = '3' THEN '産廃(積替)' 
           ELSE '' 
       END AS HAIKIBUTU_KBN 
     , CASE WHEN MAX_ROUTE_GENBA.GYOUSHA_CD = TMD2.LAST_SBN_GYOUSHA_CD AND MAX_ROUTE_GENBA.GENBA_CD = TMD2.LAST_SBN_GENBA_CD
            THEN
                CASE
                    WHEN ( TME2.HAIKI_KBN_CD = '1' OR TME2.HAIKI_KBN_CD = '3' OR TME2.HAIKI_KBN_CD = '4') AND TMD2.HAIKI_SHURUI_CD < '7000' THEN MCK_SAISHU.FUTSUU_KYOKA_NO 
                    WHEN ( TME2.HAIKI_KBN_CD = '1' OR TME2.HAIKI_KBN_CD = '3' OR TME2.HAIKI_KBN_CD = '4') AND TMD2.HAIKI_SHURUI_CD >= '7000' THEN MCK_SAISHU.TOKUBETSU_KYOKA_NO 
                    WHEN TME2.HAIKI_KBN_CD = '2' AND TMD2.HAIKI_SHURUI_CD < '2100' THEN MCK_SAISHU.FUTSUU_KYOKA_NO 
                    WHEN TME2.HAIKI_KBN_CD = '2' AND TMD2.HAIKI_SHURUI_CD >= '2100' THEN MCK_SAISHU.TOKUBETSU_KYOKA_NO 
                    ELSE ' ' 
                END
            ELSE
                CASE
                    WHEN ( TME2.HAIKI_KBN_CD = '1' OR TME2.HAIKI_KBN_CD = '3' OR TME2.HAIKI_KBN_CD = '4') AND TMD2.HAIKI_SHURUI_CD < '7000' THEN MCK.FUTSUU_KYOKA_NO 
                    WHEN ( TME2.HAIKI_KBN_CD = '1' OR TME2.HAIKI_KBN_CD = '3' OR TME2.HAIKI_KBN_CD = '4') AND TMD2.HAIKI_SHURUI_CD >= '7000' THEN MCK.TOKUBETSU_KYOKA_NO 
                    WHEN TME2.HAIKI_KBN_CD = '2' AND TMD2.HAIKI_SHURUI_CD < '2100' THEN MCK.FUTSUU_KYOKA_NO 
                    WHEN TME2.HAIKI_KBN_CD = '2' AND TMD2.HAIKI_SHURUI_CD >= '2100' THEN MCK.TOKUBETSU_KYOKA_NO 
                    ELSE ' ' 
                END
       END AS KYOKANO
     , TME2.SBN_JYUTAKUSHA_CD AS JUTAKUSHA_GYOUSHA_CD
     , TMU2_1.UPN_SAKI_GENBA_CD AS JUTAKUSHA_GENBA_CD
     , TME2.SBN_GYOUSHA_NAME AS JUTAKUSHAMEI
     , TME2.SBN_GYOUSHA_ADDRESS AS JUTAKUSHA_ADDRESS
     , CONVERT(VARCHAR(10), TME2.KOUFU_DATE, 111) AS KOUFU_NENGAPPI2 
     , TME2.MANIFEST_ID AS KOUFUNO2 
     , FIRST_MANIFEST.KOUFUSHAMEI AS KOUFUSHAMEI 
     , FIRST_MANIFEST.KOUFU_NENGAPPI AS KOUFU_NENGAPPI 
     , FIRST_MANIFEST.KOUFUNO AS KOUFUNO 
     , MSH.SHOBUN_HOUHOU_NAME_RYAKU AS ITAKUNAIYOU 
     , ISNULL(FIRST_MANIFEST.GENNYOU_SUU, 0) AS ITAKURYO 
     , MU.UNIT_NAME_RYAKU AS ITAKURYO_TANI 
     , TME2.SBN_GYOUSHA_NAME AS JUTAKUSHAMEI_GOUKEI_NAME
     , MU.UNIT_NAME_RYAKU AS JUTAKUSHA_GOUKEI_ITAKURYOU_TANI 
     , MHS.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_GOUKEI_CD 
     , MHB.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_GOUKEI_NAME 
     , MU.UNIT_NAME_RYAKU AS HAIKI_SHURUI_GOUKEI_ITAKURYOU_TANI 
     , MU.UNIT_NAME_RYAKU AS SOUGOUKEI_ITAKURYOU_TANI 

  FROM T_MANIFEST_ENTRY AS TME2 
 INNER JOIN T_MANIFEST_UPN AS TMU2 
    ON TME2.SYSTEM_ID = TMU2.SYSTEM_ID 
   AND TME2.SEQ = TMU2.SEQ 
 INNER JOIN ( 
      SELECT TME_SANPAI.SYSTEM_ID 
           , TME_SANPAI.SEQ 
           , MIN(TMU_SANPAI.UPN_ROUTE_NO) AS UPN_ROUTE_NO 
        FROM T_MANIFEST_ENTRY    AS TME_SANPAI 
       INNER JOIN T_MANIFEST_UPN AS TMU_SANPAI 
          ON TME_SANPAI.SYSTEM_ID = TMU_SANPAI.SYSTEM_ID 
         AND TME_SANPAI.SEQ       = TMU_SANPAI.SEQ 
       WHERE TME_SANPAI.DELETE_FLG = 'false' 
         AND TME_SANPAI.HAIKI_KBN_CD IN (1,3) 
         AND TMU_SANPAI.UPN_SAKI_KBN = 1 
       GROUP BY TME_SANPAI.SYSTEM_ID 
           , TME_SANPAI.SEQ 
       UNION 
      SELECT TME_KENPAI.SYSTEM_ID 
           , TME_KENPAI.SEQ 
           , MIN(TMU_KENPAI.UPN_ROUTE_NO) AS UPN_ROUTE_NO 
        FROM T_MANIFEST_ENTRY    AS TME_KENPAI 
       INNER JOIN T_MANIFEST_UPN AS TMU_KENPAI 
          ON TME_KENPAI.SYSTEM_ID = TMU_KENPAI.SYSTEM_ID 
         AND TME_KENPAI.SEQ       = TMU_KENPAI.SEQ 
       WHERE TME_KENPAI.DELETE_FLG = 'false' 
         AND TME_KENPAI.HAIKI_KBN_CD = 2 
       GROUP BY TME_KENPAI.SYSTEM_ID 
           , TME_KENPAI.SEQ 
     ) AS TMU_MAX_ROUTE 
    ON TMU2.SYSTEM_ID = TMU_MAX_ROUTE.SYSTEM_ID 
   AND TMU2.SEQ = TMU_MAX_ROUTE.SEQ 
   AND TMU2.UPN_ROUTE_NO = TMU_MAX_ROUTE.UPN_ROUTE_NO 
 LEFT JOIN M_GENBA AS MAX_ROUTE_GENBA
    ON TMU2.UPN_SAKI_GYOUSHA_CD = MAX_ROUTE_GENBA.GYOUSHA_CD
   AND TMU2.UPN_SAKI_GENBA_CD = MAX_ROUTE_GENBA.GENBA_CD
   AND MAX_ROUTE_GENBA.SHOBUN_NIOROSHI_GENBA_KBN = 'true'
 INNER JOIN T_MANIFEST_UPN AS TMU2_1 
    ON TME2.SYSTEM_ID = TMU2_1.SYSTEM_ID 
   AND TME2.SEQ = TMU2_1.SEQ 
   AND TMU2_1.UPN_ROUTE_NO = 1 
 INNER JOIN T_MANIFEST_DETAIL AS TMD2 
    ON TME2.SYSTEM_ID = TMD2.SYSTEM_ID 
   AND TME2.SEQ = TMD2.SEQ 
 INNER JOIN M_SYS_INFO 
    ON SYS_ID = '0' 
 INNER JOIN M_GYOUSHA AS MG_HST 
    ON TME2.HST_GYOUSHA_CD = MG_HST.GYOUSHA_CD 
   AND MG_HST.JISHA_KBN = 'true' 
   AND MG_HST.HAISHUTSU_NIZUMI_GYOUSHA_KBN = 'true' 
 INNER JOIN M_GYOUSHA AS MG_LAST_SBN 
    ON TMD2.LAST_SBN_GYOUSHA_CD = MG_LAST_SBN.GYOUSHA_CD 
   AND MG_LAST_SBN.JISHA_KBN = 'false' 
   AND MG_LAST_SBN.SHOBUN_NIOROSHI_GYOUSHA_KBN = 'true' 
 INNER JOIN M_GENBA AS MGEN_LAST_SBN 
    ON TMD2.LAST_SBN_GYOUSHA_CD = MGEN_LAST_SBN.GYOUSHA_CD 
   AND TMD2.LAST_SBN_GENBA_CD = MGEN_LAST_SBN.GENBA_CD 
   AND MGEN_LAST_SBN.SAISHUU_SHOBUNJOU_KBN = 'true' 
--// 20140619 syunrei EV004818_最終処分委託帳簿の条件変更 start
 --INNER JOIN T_MANIFEST_RELATION AS TMR 
  LEFT OUTER JOIN T_MANIFEST_RELATION AS TMR 
 --// 20140619 syunrei EV004818_最終処分委託帳簿の条件変更 end
 --2016.12.07 chinkeigen 廃棄物帳簿 中間処理処分帳簿 #101097 start
    --ON TME2.SYSTEM_ID = TMR.NEXT_SYSTEM_ID 
	ON TMD2.DETAIL_SYSTEM_ID = TMR.NEXT_SYSTEM_ID 
 --2016.12.07  chinkeigen 廃棄物帳簿 中間処理処分帳簿 #101097 end
    AND TMR.NEXT_HAIKI_KBN_CD <> 4
   AND TMR.DELETE_FLG = 'false' 

 INNER JOIN (
      SELECT TMD1.DETAIL_SYSTEM_ID AS FIRST_SYSTEM_ID 
           , TME1.HAIKI_KBN_CD AS FIRST_HAIKI_KBN_CD
           , TME1.MANIFEST_ID AS KOUFUNO 
           , TME1.HST_GYOUSHA_NAME AS KOUFUSHAMEI 
           , CONVERT(VARCHAR(10), TME1.KOUFU_DATE, 111) AS KOUFU_NENGAPPI 
		   , TMD1.GENNYOU_SUU
        FROM T_MANIFEST_ENTRY AS TME1 
       INNER JOIN T_MANIFEST_DETAIL AS TMD1 
          ON TME1.SYSTEM_ID = TMD1.SYSTEM_ID 
         AND TME1.SEQ = TMD1.SEQ 
       WHERE TME1.DELETE_FLG = 'false' 
         AND ISNULL(TMD1.LAST_SBN_END_DATE, '') <> ''
         AND ISNULL(TMD1.LAST_SBN_GYOUSHA_CD, '') <> ''
         AND ISNULL(TMD1.LAST_SBN_GENBA_CD, '') <> ''
       UNION 
      SELECT DR18EX1.SYSTEM_ID AS FIRST_SYSTEM_ID 
           , 4 AS FIRST_HAIKI_KBN_CD
           , DR181.MANIFEST_ID AS KOUFUNO 
           , DR181.HST_SHA_NAME AS KOUFUSHAMEI 
           , CASE WHEN ISDATE(DR181.HIKIWATASHI_DATE) > 0 THEN CONVERT(VARCHAR(10), CONVERT(DATETIME, DR181.HIKIWATASHI_DATE), 111) 
                  ELSE NULL 
             END AS KOUFU_NENGAPPI 
		   , DR18EX1.GENNYOU_SUU
        FROM (
                SELECT 
                       (CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN DT_R18_MIX.DETAIL_SYSTEM_ID ELSE DT_R18_EX.SYSTEM_ID END) AS SYSTEM_ID
                    ,DT_R18_EX.KANRI_ID
					, (CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN DT_R18_MIX.GENNYOU_SUU ELSE DT_R18_EX.GENNYOU_SUU END) AS GENNYOU_SUU
                FROM DT_R18_EX
                LEFT JOIN (SELECT * FROM DT_R18_MIX WHERE DELETE_FLG = 0) AS DT_R18_MIX ON
                DT_R18_EX.SYSTEM_ID = DT_R18_MIX.SYSTEM_ID
                WHERE DT_R18_EX.DELETE_FLG = 0
            ) AS DR18EX1 
       INNER JOIN DT_MF_TOC AS DMT1 
          ON DR18EX1.KANRI_ID = DMT1.KANRI_ID 
       INNER JOIN DT_R18 AS DR181 
          ON DMT1.KANRI_ID = DR181.KANRI_ID 
         AND DMT1.LATEST_SEQ = DR181.SEQ 
       WHERE DR181.LAST_SBN_ENDREP_FLAG = 1
     ) AS FIRST_MANIFEST
    ON TMR.FIRST_SYSTEM_ID = FIRST_MANIFEST.FIRST_SYSTEM_ID 
    AND FIRST_MANIFEST.FIRST_HAIKI_KBN_CD = TMR.FIRST_HAIKI_KBN_CD
  LEFT OUTER JOIN M_SHOBUN_HOUHOU AS MSH 
    ON TMD2.SBN_HOUHOU_CD = MSH.SHOBUN_HOUHOU_CD 
  LEFT OUTER JOIN M_HAIKI_SHURUI AS MHS 
    ON TME2.HAIKI_KBN_CD = MHS.HAIKI_KBN_CD 
   AND TMD2.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
  LEFT OUTER JOIN M_HOUKOKUSHO_BUNRUI AS MHB 
    ON MHS.HOUKOKUSHO_BUNRUI_CD = MHB.HOUKOKUSHO_BUNRUI_CD
  LEFT OUTER JOIN M_CHIIKIBETSU_KYOKA AS MCK 
    ON MAX_ROUTE_GENBA.GYOUSHA_CD = MCK.GYOUSHA_CD
   AND MAX_ROUTE_GENBA.GENBA_CD = MCK.GENBA_CD
   AND MAX_ROUTE_GENBA.CHIIKI_CD = MCK.CHIIKI_CD
   AND MCK.KYOKA_KBN = '2' 
  LEFT OUTER JOIN M_CHIIKIBETSU_KYOKA AS MCK_SAISHU 
    ON MAX_ROUTE_GENBA.GYOUSHA_CD = MCK_SAISHU.GYOUSHA_CD
   AND MAX_ROUTE_GENBA.GENBA_CD = MCK_SAISHU.GENBA_CD
   AND MAX_ROUTE_GENBA.CHIIKI_CD = MCK_SAISHU.CHIIKI_CD
   AND MCK_SAISHU.KYOKA_KBN = '3' 
  LEFT OUTER JOIN M_UNIT AS MU 
    ON M_SYS_INFO.MANI_KANSAN_KIHON_UNIT_CD = MU.UNIT_CD 
 --// 20140619 syunrei EV004818_最終処分委託帳簿の条件変更 start
 INNER JOIN M_GYOUSHA AS GS_NAME
    ON TME2.SBN_JYUTAKUSHA_CD = GS_NAME.GYOUSHA_CD 
   --AND GS_NAME.DELETE_FLG = 'false'
   
 INNER JOIN M_GENBA AS GB_NAME
    ON TME2.SBN_JYUTAKUSHA_CD = GB_NAME.GYOUSHA_CD 
   AND TMU2_1.UPN_SAKI_GENBA_CD = GB_NAME.GENBA_CD 
   --AND GB_NAME.DELETE_FLG = 'false' 
 --// 20140619 syunrei EV004818_最終処分委託帳簿の条件変更 end
 WHERE TME2.DELETE_FLG = 'false' 
   AND ISNULL(TMD2.LAST_SBN_END_DATE, '') <> ''
   AND ISNULL(TMD2.LAST_SBN_GYOUSHA_CD, '') <> ''
   AND ISNULL(TMD2.LAST_SBN_GENBA_CD, '') <> ''
 --// 20140619 syunrei EV004818_最終処分委託帳簿の条件変更 start
   --AND TME2.FIRST_MANIFEST_KBN = 'true' 
 --// 20140619 syunrei EV004818_最終処分委託帳簿の条件変更 end
/*IF dto.HAIKIBUTSU_KBN.Count != 0 */
    AND TME2.HAIKI_KBN_CD IN /*dto.HAIKIBUTSU_KBN*/(1,2)
/*END*/
/*IF dto.HIDUKESYURUI == '1'*/ 
   AND TME2.KOUFU_DATE >= /*dto.DATE_FROM*/ 
   AND TME2.KOUFU_DATE <= /*dto.DATE_TO*/ 
/*END*/ 
/*IF dto.HIDUKESYURUI == '2'*/
   AND TMU2.UPN_END_DATE >= /*dto.DATE_FROM*/ 
   AND TMU2.UPN_END_DATE <= /*dto.DATE_TO*/ 
/*END*/ 
/*IF dto.HIDUKESYURUI == '3'*/ 
   AND TMD2.LAST_SBN_END_DATE >= /*dto.DATE_FROM*/ 
   AND TMD2.LAST_SBN_END_DATE <= /*dto.DATE_TO*/ 
/*END*/ 
/*IF dto.KYOTEN_CD != null && dto.KYOTEN_CD != '' */ 
   AND TME2.KYOTEN_CD = /*dto.KYOTEN_CD*/ 
/*END*/ 
/*IF dto.SBN_GYOUSHA_CD != null && dto.SBN_GYOUSHA_CD != '' */ 
   AND TME2.HST_GYOUSHA_CD = /*dto.SBN_GYOUSHA_CD*/ 
/*END*/ 
/*IF dto.SBN_GENBA_CD != null && dto.SBN_GENBA_CD != '' */
   AND TME2.HST_GENBA_CD >= /*dto.SBN_GENBA_CD*/ 
/*END*/ 
/*IF dto.SBN_GENBA_CD_TO != null && dto.SBN_GENBA_CD_TO != '' */
   AND TME2.HST_GENBA_CD <= /*dto.SBN_GENBA_CD_TO*/ 
/*END*/ 

 ORDER BY MHS.HOUKOKUSHO_BUNRUI_CD 
     , TME2.SBN_JYUTAKUSHA_CD 
     , TMU2_1.UPN_SAKI_GENBA_CD
     , KOUFU_NENGAPPI2 
     , TME2.MANIFEST_ID 
