SELECT MHS.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_CD
     , MHB.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_NAME
     , CONVERT(VARCHAR(10), TMU2.UPN_END_DATE, 111) AS UNPAN_NENGAPPI 
     , CONVERT(VARCHAR(10), TME2.KOUFU_DATE, 111) AS KOUFU_NENGAPPI 
     , TME2.HAIKI_KBN_CD
     , CASE 
           WHEN TME2.HAIKI_KBN_CD = '1' THEN 'ŽY”p(’¼s)' 
           WHEN TME2.HAIKI_KBN_CD = '2' THEN 'Œš”p' 
           WHEN TME2.HAIKI_KBN_CD = '3' THEN 'ŽY”p(Ï‘Ö)' 
           ELSE '' 
       END AS HAIKIBUTU_KBN 
     , TME2.HST_GYOUSHA_NAME AS KOUFUSHAMEI 
     , TME2.MANIFEST_ID AS KOUFUNO 
     , TME2.HST_GENBA_NAME AS UKEIRESAKI 
     , ISNULL(TMD2.KANSAN_SUU, 0) AS UKEIRERYO 
     , MU.UNIT_NAME_RYAKU AS UKEIRERYO_TANI 
     , TMU2.UPN_SAKI_GENBA_NAME AS UNPANSAKI 
     , ISNULL(TMD2.KANSAN_SUU, 0) AS UNPANRYO 
     , MU.UNIT_NAME_RYAKU AS UNPANRYO_TANI 
     , CASE WHEN TME2.HAIKI_KBN_CD = '1'                             THEN TME2.TMH_GENBA_NAME 
            WHEN TME2.HAIKI_KBN_CD = '2'                             THEN TME2.TMH_GENBA_NAME 
            WHEN TME2.HAIKI_KBN_CD = '3' AND TMU2.UPN_SAKI_KBN = '2' THEN TMU2.UPN_SAKI_GENBA_NAME 
            ELSE ' ' 
       END AS TUMIKAEHOKAN 
-- 2014.08.14 #1134 MIYA MOD START
--     , TMU2.UPN_HOUHOU_CD AS UNPAN_HOUHOU_CD 
     , ISNULL(TMU2.UPN_HOUHOU_CD,'') AS UNPAN_HOUHOU_CD
-- 2014.08.14 #1134 MIYA MOD END
     , MUH.UNPAN_HOUHOU_NAME_RYAKU AS UNPAN_HOUHOU_NAME 
     , CASE WHEN TME2.HAIKI_KBN_CD = '1' AND ISNULL(TME2.TMH_GENBA_NAME,'') != ''                                  THEN ISNULL(TMD2.KANSAN_SUU,0) 
            WHEN TME2.HAIKI_KBN_CD = '2' AND ISNULL(TME2.TMH_GENBA_NAME,'') != ''                                  THEN ISNULL(TMD2.KANSAN_SUU,0) 
            WHEN TME2.HAIKI_KBN_CD = '3' AND ISNULL(TMU2.UPN_SAKI_GENBA_NAME,'') != '' AND TMU2.UPN_SAKI_KBN = '2' THEN ISNULL(TMD2.KANSAN_SUU,0) 
            ELSE 0 
       END AS HANSHUTURYO 
     , CASE WHEN TME2.HAIKI_KBN_CD = '1'                             THEN MU.UNIT_NAME_RYAKU 
            WHEN TME2.HAIKI_KBN_CD = '2'                             THEN MU.UNIT_NAME_RYAKU 
            WHEN TME2.HAIKI_KBN_CD = '3' THEN MU.UNIT_NAME_RYAKU 
            ELSE ' ' 
       END AS HANSHUTURYO_TANI 
     , TMU2.UPN_SAKI_GENBA_NAME AS UNPANSAKI_GOUKEI_NAME
     , MU.UNIT_NAME_RYAKU AS UNPANSAKI_GOUKEI_SUURYO_TANI 
     , TME2.HST_GENBA_NAME AS UKEIRESAKI_GOUKEI_NAME
     , MU.UNIT_NAME_RYAKU AS UKEIRESAKI_GOUKEI_SUURYO_TANI 
     , TMU2.UPN_HOUHOU_CD AS UNPAN_HOUHOU_GOUKEI_CD 
     , MUH.UNPAN_HOUHOU_NAME_RYAKU AS UNPAN_HOUHOU_GOUKEI_NAME 
     , MU.UNIT_NAME_RYAKU AS UNPAN_HOUHOU_GOUKEI_SUURYO_TANI 
     , MU.UNIT_NAME_RYAKU AS HAIKI_GOUKEI_SUURYO_TANI 
     , MU.UNIT_NAME_RYAKU AS UKEIRERYO_SOUGOUKEI_TANI
     , MU.UNIT_NAME_RYAKU AS UNPANRYO_SOUGOUKEI_TANI
     , MU.UNIT_NAME_RYAKU AS HANSHUTURYO_SOUGOUKEI_TANI

  FROM T_MANIFEST_ENTRY AS TME2 
 INNER JOIN T_MANIFEST_UPN AS TMU2 
    ON TME2.SYSTEM_ID = TMU2.SYSTEM_ID 
   AND TME2.SEQ = TMU2.SEQ 
 INNER JOIN T_MANIFEST_DETAIL AS TMD2 
    ON TME2.SYSTEM_ID = TMD2.SYSTEM_ID 
   AND TME2.SEQ = TMD2.SEQ 
 INNER JOIN M_GYOUSHA AS MG_UPN 
    ON TMU2.UPN_GYOUSHA_CD = MG_UPN.GYOUSHA_CD 
   AND MG_UPN.JISHA_KBN = 'true' 
   AND MG_UPN.UNPAN_JUTAKUSHA_KAISHA_KBN = 'true' 
 INNER JOIN M_SYS_INFO 
    ON SYS_ID = '0' 
  LEFT OUTER JOIN M_UNPAN_HOUHOU AS MUH 
    ON TMU2.UPN_HOUHOU_CD = MUH.UNPAN_HOUHOU_CD 
  LEFT OUTER JOIN M_HAIKI_SHURUI AS MHS 
    ON TME2.HAIKI_KBN_CD = MHS.HAIKI_KBN_CD 
   AND TMD2.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
  LEFT OUTER JOIN M_HOUKOKUSHO_BUNRUI AS MHB 
    ON MHS.HOUKOKUSHO_BUNRUI_CD = MHB.HOUKOKUSHO_BUNRUI_CD
  LEFT OUTER JOIN M_UNIT AS MU 
    ON M_SYS_INFO.MANI_KANSAN_KIHON_UNIT_CD = MU.UNIT_CD 

 WHERE TME2.DELETE_FLG = 'false' 
   AND TME2.FIRST_MANIFEST_KBN = 'true' 
/*IF dto.HAIKIBUTSU_KBN.Count != 0 */
    AND TME2.HAIKI_KBN_CD IN /*dto.HAIKIBUTSU_KBN*/(1,2,3)
/*END*/
/*IF dto.HIDUKESYURUI == '1'*/ 
   AND TME2.KOUFU_DATE >= /*dto.DATE_FROM*/'2013/04/01' 
   AND TME2.KOUFU_DATE <= /*dto.DATE_TO*/'2014/03/31' 
/*END*/ 
/*IF dto.HIDUKESYURUI == '2'*/ 
   AND TMU2.UPN_END_DATE >= /*dto.DATE_FROM*/'2013/04/01' 
   AND TMU2.UPN_END_DATE <= /*dto.DATE_TO*/'2014/03/31' 
/*END*/ 
/*IF dto.HIDUKESYURUI == '3'*/ 
   AND TMD2.SBN_END_DATE >= /*dto.DATE_FROM*/'2013/04/01' 
   AND TMD2.SBN_END_DATE <= /*dto.DATE_TO*/'2014/03/31' 
/*END*/ 
/*IF dto.KYOTEN_CD != null && dto.KYOTEN_CD != '' */ 
   AND TME2.KYOTEN_CD = /*dto.KYOTEN_CD*/'00' 
/*END*/ 
/*IF dto.SBN_GYOUSHA_CD != null && dto.SBN_GYOUSHA_CD != '' */ 
   AND TMU2.UPN_GYOUSHA_CD = /*dto.SBN_GYOUSHA_CD*/'000300' 
/*END*/ 

 ORDER BY MHS.HOUKOKUSHO_BUNRUI_CD 
-- 2014.08.14 #1134 MIYA MOD START
--     , TMU2.UPN_HOUHOU_CD 
     , ISNULL(TMU2.UPN_HOUHOU_CD,'') 
-- 2014.08.14 #1134 MIYA MOD END
     , TME2.SBN_GYOUSHA_CD 
     , TMU2.UPN_SAKI_GENBA_NAME 
     , TME2.KOUFU_DATE 
     , TME2.HAIKI_KBN_CD 
     , TME2.MANIFEST_ID 
     , TMU2.UPN_ROUTE_NO 
     , TMD2.DETAIL_SYSTEM_ID 
