SELECT MHS.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_CD
     , MHB.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_NAME
     , CONVERT(VARCHAR(10), TME2.KOUFU_DATE, 111) AS ITAKU_NENGAPPI 
     , CASE WHEN TMU2.UPN_ROUTE_NO = 1
           THEN
                CASE
                    WHEN ( TME2.HAIKI_KBN_CD = '1' OR TME2.HAIKI_KBN_CD = '3' OR TME2.HAIKI_KBN_CD = '4') AND TMD2.HAIKI_SHURUI_CD < '7000' THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(MCK_MOTO_HST_CK.FUTSUU_KYOKA_NO, '') = '' THEN MCK_MOTO_HST.FUTSUU_KYOKA_NO
                            ELSE MCK_MOTO_HST_CK.FUTSUU_KYOKA_NO
                        END
                    WHEN ( TME2.HAIKI_KBN_CD = '1' OR TME2.HAIKI_KBN_CD = '3' OR TME2.HAIKI_KBN_CD = '4') AND TMD2.HAIKI_SHURUI_CD >= '7000' THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(MCK_MOTO_HST_CK.TOKUBETSU_KYOKA_NO, '') = '' THEN MCK_MOTO_HST.TOKUBETSU_KYOKA_NO
                            ELSE MCK_MOTO_HST_CK.TOKUBETSU_KYOKA_NO
                        END
                    WHEN TME2.HAIKI_KBN_CD = '2' AND TMD2.HAIKI_SHURUI_CD < '2100' THEN 
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(MCK_MOTO_HST_CK.FUTSUU_KYOKA_NO, '') = '' THEN MCK_MOTO_HST.FUTSUU_KYOKA_NO
                            ELSE MCK_MOTO_HST_CK.FUTSUU_KYOKA_NO
                        END
                    WHEN TME2.HAIKI_KBN_CD = '2' AND TMD2.HAIKI_SHURUI_CD >= '2100' THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(MCK_MOTO_HST_CK.TOKUBETSU_KYOKA_NO, '') = '' THEN MCK_MOTO_HST.TOKUBETSU_KYOKA_NO
                            ELSE MCK_MOTO_HST_CK.TOKUBETSU_KYOKA_NO
                        END
                ELSE ' ' 
                END
           ELSE
                CASE
                    WHEN ( TME2.HAIKI_KBN_CD = '1' OR TME2.HAIKI_KBN_CD = '3' OR TME2.HAIKI_KBN_CD = '4') AND TMD2.HAIKI_SHURUI_CD < '7000' THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(MCK_MOTO_CK.FUTSUU_KYOKA_NO, '') = '' THEN MCK_MOTO.FUTSUU_KYOKA_NO
                            ELSE MCK_MOTO_CK.FUTSUU_KYOKA_NO
                        END
                    WHEN ( TME2.HAIKI_KBN_CD = '1' OR TME2.HAIKI_KBN_CD = '3' OR TME2.HAIKI_KBN_CD = '4') AND TMD2.HAIKI_SHURUI_CD >= '7000' THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(MCK_MOTO_CK.TOKUBETSU_KYOKA_NO, '') = '' THEN MCK_MOTO.TOKUBETSU_KYOKA_NO
                            ELSE MCK_MOTO_CK.TOKUBETSU_KYOKA_NO
                        END
                    WHEN TME2.HAIKI_KBN_CD = '2' AND TMD2.HAIKI_SHURUI_CD < '2100' THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(MCK_MOTO_CK.FUTSUU_KYOKA_NO, '') = '' THEN MCK_MOTO.FUTSUU_KYOKA_NO
                            ELSE MCK_MOTO_CK.FUTSUU_KYOKA_NO
                        END
                    WHEN TME2.HAIKI_KBN_CD = '2' AND TMD2.HAIKI_SHURUI_CD >= '2100' THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(MCK_MOTO_CK.TOKUBETSU_KYOKA_NO, '') = '' THEN MCK_MOTO.TOKUBETSU_KYOKA_NO
                            ELSE MCK_MOTO_CK.TOKUBETSU_KYOKA_NO
                        END
                ELSE ' ' 
                END
       END AS KYOKANO 
     ,  CASE WHEN ( TME2.HAIKI_KBN_CD = '1' OR TME2.HAIKI_KBN_CD = '3' OR TME2.HAIKI_KBN_CD = '4') AND TMD2.HAIKI_SHURUI_CD < '7000' THEN
                --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                CASE WHEN ISNULL(MCK_SAKI_CK.FUTSUU_KYOKA_NO, '') = '' THEN MCK_SAKI.FUTSUU_KYOKA_NO
                    ELSE MCK_SAKI_CK.FUTSUU_KYOKA_NO
                END
             WHEN ( TME2.HAIKI_KBN_CD = '1' OR TME2.HAIKI_KBN_CD = '3' OR TME2.HAIKI_KBN_CD = '4') AND TMD2.HAIKI_SHURUI_CD >= '7000' THEN
                --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                CASE WHEN ISNULL(MCK_SAKI_CK.TOKUBETSU_KYOKA_NO, '') = '' THEN MCK_SAKI.TOKUBETSU_KYOKA_NO
                    ELSE MCK_SAKI_CK.TOKUBETSU_KYOKA_NO
                END
             WHEN TME2.HAIKI_KBN_CD = '2' AND TMD2.HAIKI_SHURUI_CD < '2100' THEN
                --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                CASE WHEN ISNULL(MCK_SAKI_CK.FUTSUU_KYOKA_NO, '') = '' THEN MCK_SAKI.FUTSUU_KYOKA_NO
                    ELSE MCK_SAKI_CK.FUTSUU_KYOKA_NO
                END
             WHEN TME2.HAIKI_KBN_CD = '2' AND TMD2.HAIKI_SHURUI_CD >= '2100' THEN
                --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                CASE WHEN ISNULL(MCK_SAKI_CK.TOKUBETSU_KYOKA_NO, '') = '' THEN MCK_SAKI.TOKUBETSU_KYOKA_NO
                    ELSE MCK_SAKI_CK.TOKUBETSU_KYOKA_NO
                END
             ELSE ' ' 
       END AS UPNSAKI_KYOKANO
     , TMU2.UPN_GYOUSHA_NAME AS JUTAKUSHA 
     , CONVERT(VARCHAR(10), TME2.KOUFU_DATE, 111) AS KOUFU_NENGAPPI 
     , TME2.HAIKI_KBN_CD
     , CASE 
           WHEN TME2.HAIKI_KBN_CD = '1' THEN '産廃(直行)' 
           WHEN TME2.HAIKI_KBN_CD = '2' THEN '建廃' 
           WHEN TME2.HAIKI_KBN_CD = '3' THEN '産廃(積替)' 
           ELSE '' 
       END AS HAIKIBUTU_KBN 
     , TME2.MANIFEST_ID AS KOUFUNO 
     , TMU2.UPN_GYOUSHA_ADDRESS AS JUTAKUSHA_ADDRESS 
     , TMU2.UPN_SAKI_GENBA_NAME AS UNPANSAKI 
     , SUM(ISNULL( TMD2.KANSAN_SUU, 0)) AS ITAKURYO 
     , MU.UNIT_NAME_RYAKU AS ITAKURYO_TANI 
     , TMU2.UPN_SAKI_GENBA_NAME AS UNPANSAKI_GOUKEI_NAME
     , MU.UNIT_NAME_RYAKU AS UNPANSAKI_GOUKEI_TANI 
     , MHS.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_GOUKEI_CD 
     , MHB.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_GOUKEI_NAME 
     , MU.UNIT_NAME_RYAKU AS HAIKI_SHURUI_GOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS ITAKURYO_SOUGOUKEI_TANI 

  FROM T_MANIFEST_ENTRY AS TME2 
 INNER JOIN T_MANIFEST_UPN AS TMU2 
    ON TME2.SYSTEM_ID = TMU2.SYSTEM_ID 
   AND TME2.SEQ = TMU2.SEQ 
 LEFT JOIN T_MANIFEST_UPN AS TMU2_PREV
    ON TMU2.SYSTEM_ID = TMU2_PREV.SYSTEM_ID
   AND TMU2.SEQ = TMU2_PREV.SEQ
   AND  TMU2_PREV.UPN_ROUTE_NO = (TMU2.UPN_ROUTE_NO - 1)
 INNER JOIN T_MANIFEST_DETAIL AS TMD2 
    ON TME2.SYSTEM_ID = TMD2.SYSTEM_ID 
   AND TME2.SEQ = TMD2.SEQ 
 INNER JOIN M_SYS_INFO 
    ON SYS_ID = '0' 
 INNER JOIN M_GYOUSHA AS MG_HST 
    ON TME2.HST_GYOUSHA_CD = MG_HST.GYOUSHA_CD 
   AND MG_HST.JISHA_KBN = 'true' 
   AND MG_HST.HAISHUTSU_NIZUMI_GYOUSHA_KBN = 'true' 
 INNER JOIN M_GYOUSHA AS MG_UPN 
    ON TMU2.UPN_GYOUSHA_CD = MG_UPN.GYOUSHA_CD 
   AND MG_UPN.JISHA_KBN = 'false' 
   AND MG_UPN.UNPAN_JUTAKUSHA_KAISHA_KBN = 'true' 
  LEFT OUTER JOIN M_HAIKI_SHURUI AS MHS 
    ON TME2.HAIKI_KBN_CD = MHS.HAIKI_KBN_CD 
   AND TMD2.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
  LEFT OUTER JOIN M_HOUKOKUSHO_BUNRUI AS MHB 
    ON MHS.HOUKOKUSHO_BUNRUI_CD = MHB.HOUKOKUSHO_BUNRUI_CD
  LEFT OUTER JOIN M_GENBA AS MGEN_CHIIKI 
    ON TME2.HST_GYOUSHA_CD = MGEN_CHIIKI.GYOUSHA_CD 
   AND TME2.HST_GENBA_CD = MGEN_CHIIKI.GENBA_CD
  LEFT OUTER JOIN M_UNIT AS MU 
    ON M_SYS_INFO.MANI_KANSAN_KIHON_UNIT_CD = MU.UNIT_CD 
  LEFT JOIN M_GENBA AS GENBA_UPNSAKI 
    ON TMU2.UPN_SAKI_GYOUSHA_CD = GENBA_UPNSAKI.GYOUSHA_CD 
    AND TMU2.UPN_SAKI_GENBA_CD = GENBA_UPNSAKI.GENBA_CD 
  LEFT JOIN M_GENBA AS GENBA_UPNSAKI_PREV 
    ON TMU2_PREV.UPN_SAKI_GYOUSHA_CD = GENBA_UPNSAKI_PREV.GYOUSHA_CD 
    AND TMU2_PREV.UPN_SAKI_GENBA_CD = GENBA_UPNSAKI_PREV.GENBA_CD 
   -- 4種類の許可番号情報を取得(運搬元 or 運搬先 * 特定の区間 or その他の区間 => 全4種類)
   -- どれを表示するかはSELECT句で制御
  LEFT OUTER JOIN M_CHIIKIBETSU_KYOKA AS MCK_MOTO_HST 
    ON TMU2.UPN_GYOUSHA_CD = MCK_MOTO_HST.GYOUSHA_CD 
   AND MGEN_CHIIKI.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = MCK_MOTO_HST.CHIIKI_CD 
   AND MCK_MOTO_HST.KYOKA_KBN = '1'
  LEFT OUTER JOIN M_CHIIKIBETSU_KYOKA AS MCK_MOTO_HST_CK 
    ON TMU2.UPN_GYOUSHA_CD = MCK_MOTO_HST_CK.GYOUSHA_CD 
   AND MGEN_CHIIKI.CHIIKI_CD = MCK_MOTO_HST_CK.CHIIKI_CD 
   AND MCK_MOTO_HST_CK.KYOKA_KBN = '1'
  LEFT OUTER JOIN M_CHIIKIBETSU_KYOKA AS MCK_MOTO
    ON TMU2.UPN_GYOUSHA_CD = MCK_MOTO.GYOUSHA_CD
   AND GENBA_UPNSAKI_PREV.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = MCK_MOTO.CHIIKI_CD
   AND MCK_MOTO.KYOKA_KBN = '1'
  LEFT OUTER JOIN M_CHIIKIBETSU_KYOKA AS MCK_MOTO_CK
    ON TMU2.UPN_GYOUSHA_CD = MCK_MOTO_CK.GYOUSHA_CD
   AND GENBA_UPNSAKI_PREV.CHIIKI_CD = MCK_MOTO_CK.CHIIKI_CD
   AND MCK_MOTO_CK.KYOKA_KBN = '1'
  LEFT OUTER JOIN M_CHIIKIBETSU_KYOKA AS MCK_SAKI
    ON TMU2.UPN_GYOUSHA_CD = MCK_SAKI.GYOUSHA_CD
   AND GENBA_UPNSAKI.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = MCK_SAKI.CHIIKI_CD
   AND MCK_SAKI.KYOKA_KBN = '1'
  LEFT OUTER JOIN M_CHIIKIBETSU_KYOKA AS MCK_SAKI_CK
    ON TMU2.UPN_GYOUSHA_CD = MCK_SAKI_CK.GYOUSHA_CD
   AND GENBA_UPNSAKI.CHIIKI_CD = MCK_SAKI_CK.CHIIKI_CD
   AND MCK_SAKI_CK.KYOKA_KBN = '1'

 WHERE TME2.DELETE_FLG = 'false' 
/*IF dto.HAIKIBUTSU_KBN.Count != 0 */
    AND TME2.HAIKI_KBN_CD IN /*dto.HAIKIBUTSU_KBN*/(1,2)
/*END*/
/*IF dto.HIDUKESYURUI == '1'*/ 
   AND TME2.KOUFU_DATE >= /*dto.DATE_FROM*/'2013/04/01' 
   AND TME2.KOUFU_DATE <= /*dto.DATE_TO*/'2014/03/31' 
/*END*/ 
/*IF dto.HIDUKESYURUI == '2'*/ 
   AND TMU2.UPN_END_DATE >= /*dto.DATE_FROM*/'2013/04/01' 
   AND TMU2.UPN_END_DATE <= /*dto.DATE_TO*/'2014/03/31' 
/*END*/ 
/*IF dto.HIDUKESYURUI == '3'*/ 
   AND TMD2.SBN_END_DATE >= /*dto.DATE_FROM*/'2013/04/01' 
   AND TMD2.SBN_END_DATE <= /*dto.DATE_TO*/'2014/03/31' 
/*END*/ 
/*IF dto.KYOTEN_CD != null && dto.KYOTEN_CD != '' */ 
   AND TME2.KYOTEN_CD = /*dto.KYOTEN_CD*/'00' 
/*END*/ 
/*IF dto.SBN_GYOUSHA_CD != null && dto.SBN_GYOUSHA_CD != '' */ 
   AND TME2.HST_GYOUSHA_CD = /*dto.SBN_GYOUSHA_CD*/'000000' 
/*END*/ 
/*IF dto.SBN_GENBA_CD != null && dto.SBN_GENBA_CD != '' */ 
   AND TME2.HST_GENBA_CD >= /*dto.SBN_GENBA_CD*/'000000' 
/*END*/ 
/*IF dto.SBN_GENBA_CD_TO != null && dto.SBN_GENBA_CD_TO != '' */ 
   AND TME2.HST_GENBA_CD <= /*dto.SBN_GENBA_CD_TO*/'000000' 
/*END*/ 

 GROUP BY MHS.HOUKOKUSHO_BUNRUI_CD
     , MHB.HOUKOKUSHO_BUNRUI_NAME
     , TMU2.UPN_GYOUSHA_NAME
     , TME2.KOUFU_DATE
     , TME2.MANIFEST_ID
     , TMU2.UPN_GYOUSHA_ADDRESS
     , TMU2.UPN_SAKI_GENBA_NAME
     , TME2.HAIKI_KBN_CD
     , TMD2.HAIKI_SHURUI_CD
     , TMD2.SBN_END_DATE
     , MCK_MOTO_HST.FUTSUU_KYOKA_NO
     , MCK_MOTO_HST.TOKUBETSU_KYOKA_NO
     , MCK_MOTO_HST_CK.FUTSUU_KYOKA_NO
     , MCK_MOTO_HST_CK.TOKUBETSU_KYOKA_NO
     , MCK_MOTO.FUTSUU_KYOKA_NO
     , MCK_MOTO.TOKUBETSU_KYOKA_NO
     , MCK_MOTO_CK.FUTSUU_KYOKA_NO
     , MCK_MOTO_CK.TOKUBETSU_KYOKA_NO
     , MCK_SAKI.FUTSUU_KYOKA_NO
     , MCK_SAKI.TOKUBETSU_KYOKA_NO
     , MCK_SAKI_CK.FUTSUU_KYOKA_NO
     , MCK_SAKI_CK.TOKUBETSU_KYOKA_NO
     , MU.UNIT_NAME_RYAKU
     , TMU2.UPN_ROUTE_NO

 ORDER BY MHS.HOUKOKUSHO_BUNRUI_CD
     , TMU2.UPN_SAKI_GENBA_NAME
     , TMD2.SBN_END_DATE
