SELECT MHS.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_CD
     , MHB.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_NAME
     , CONVERT(VARCHAR(10), TMD1.SBN_END_DATE, 111) AS SHOBUN_NENGAPPI 
     , CONVERT(VARCHAR(10), TME1.KOUFU_DATE, 111) AS KOUFU_NENGAPPI 
     , TME1.HAIKI_KBN_CD
     , CASE 
           WHEN TME1.HAIKI_KBN_CD = '1' THEN 'ŽY”p(’¼s)' 
           WHEN TME1.HAIKI_KBN_CD = '2' THEN 'Œš”p' 
           WHEN TME1.HAIKI_KBN_CD = '3' THEN 'ŽY”p(Ï‘Ö)' 
           ELSE '' 
       END AS HAIKIBUTU_KBN 
     , TME1.HST_GYOUSHA_NAME AS KOUFUSHAMEI 
     , TME1.SBN_GYOUSHA_NAME AS UKEIRESAKI 
     , SUM(ISNULL(TMD1.KANSAN_SUU,0)) AS UKEIRERYO 
     , MU.UNIT_NAME_RYAKU AS UKEIRERYO_TANI 
     , '' AS KOUFUNO2 
     , TME1.MANIFEST_ID AS KOUFUNO 
     , MSH.SHOBUN_HOUHOU_NAME_RYAKU AS SHOBUN_HOUHOU_NAME 
     , SUM(ISNULL(TMD1.KANSAN_SUU,0)) AS SHOBUNRYO 
     , MU.UNIT_NAME_RYAKU AS SHOBUNRYO_TANI 
     , '' AS MOCHIDASHISAKI 
     , CAST(0 AS MONEY) AS MOCHIDASHIRYO 
     , MU.UNIT_NAME_RYAKU AS MOCHIDASHIRYO_TANI 
     , TME1.SBN_GYOUSHA_NAME AS UKEIRESAKI_GOUKEI_NAME 
     , MU.UNIT_NAME_RYAKU AS UKEIRESAKI_GOUKEI_TANI 
     , MSH.SHOBUN_HOUHOU_NAME_RYAKU AS SHOBUN_HOUHOU_GOUKEI_NAME 
     , MU.UNIT_NAME_RYAKU AS SHOBUN_HOUHOU_GOUKEI_TANI 
     , '' AS MOCHIDASHISAKI_GOUKEI_NAME 
     , MU.UNIT_NAME_RYAKU AS MOCHIDASHISAKI_GOUKEI_TANI 
     , MHS.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_GOUKEI_CD 
     , MHB.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_GOUKEI_NAME 
     , MU.UNIT_NAME_RYAKU AS HAIKI_SHURUI_GOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS UKEIRESAKI_SOUGOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS SHOBUN_HOUHOU_SOUGOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS MOCHIDASHISAKI_SOUGOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS HAIKI_SHURUI_SOUGOUKEI_TANI 

  FROM T_MANIFEST_ENTRY AS TME1 
 INNER JOIN T_MANIFEST_UPN AS TMU1 
    ON TME1.SYSTEM_ID = TMU1.SYSTEM_ID 
   AND TME1.SEQ = TMU1.SEQ 
 INNER JOIN ( 
      SELECT TME_SANPAI.SYSTEM_ID 
           , TME_SANPAI.SEQ 
           , MIN(TMU_SANPAI.UPN_ROUTE_NO) AS UPN_ROUTE_NO 
        FROM T_MANIFEST_ENTRY    AS TME_SANPAI 
       INNER JOIN T_MANIFEST_UPN AS TMU_SANPAI 
          ON TME_SANPAI.SYSTEM_ID = TMU_SANPAI.SYSTEM_ID 
         AND TME_SANPAI.SEQ       = TMU_SANPAI.SEQ 
       WHERE TME_SANPAI.DELETE_FLG = 'false' 
         AND TME_SANPAI.HAIKI_KBN_CD IN (1,3) 
         AND TMU_SANPAI.UPN_SAKI_KBN = 1 
       GROUP BY TME_SANPAI.SYSTEM_ID 
           , TME_SANPAI.SEQ 
       UNION 
      SELECT TME_KENPAI.SYSTEM_ID 
           , TME_KENPAI.SEQ 
           , MIN(TMU_KENPAI.UPN_ROUTE_NO) AS UPN_ROUTE_NO 
        FROM T_MANIFEST_ENTRY    AS TME_KENPAI 
       INNER JOIN T_MANIFEST_UPN AS TMU_KENPAI 
          ON TME_KENPAI.SYSTEM_ID = TMU_KENPAI.SYSTEM_ID 
         AND TME_KENPAI.SEQ       = TMU_KENPAI.SEQ 
       WHERE TME_KENPAI.DELETE_FLG = 'false' 
         AND TME_KENPAI.HAIKI_KBN_CD = 2 
       GROUP BY TME_KENPAI.SYSTEM_ID 
           , TME_KENPAI.SEQ 
     ) AS TMU_MAX_ROUTE 
    ON TMU1.SYSTEM_ID = TMU_MAX_ROUTE.SYSTEM_ID 
   AND TMU1.SEQ = TMU_MAX_ROUTE.SEQ 
   AND TMU1.UPN_ROUTE_NO = TMU_MAX_ROUTE.UPN_ROUTE_NO 
 INNER JOIN T_MANIFEST_DETAIL AS TMD1 
    ON TME1.SYSTEM_ID = TMD1.SYSTEM_ID 
   AND TME1.SEQ = TMD1.SEQ
 INNER JOIN M_GYOUSHA AS MG_SBN 
    ON TME1.SBN_GYOUSHA_CD = MG_SBN.GYOUSHA_CD 
   AND MG_SBN.JISHA_KBN = 'true'
   AND MG_SBN.SHOBUN_NIOROSHI_GYOUSHA_KBN = 'true'
 INNER JOIN M_SYS_INFO 
    ON SYS_ID = '0'
  LEFT OUTER JOIN M_HAIKI_SHURUI AS MHS 
    ON TME1.HAIKI_KBN_CD = MHS.HAIKI_KBN_CD 
   AND TMD1.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
  LEFT OUTER JOIN M_HOUKOKUSHO_BUNRUI AS MHB 
    ON MHS.HOUKOKUSHO_BUNRUI_CD = MHB.HOUKOKUSHO_BUNRUI_CD
  LEFT OUTER JOIN M_SHOBUN_HOUHOU AS MSH 
    ON TMD1.SBN_HOUHOU_CD = MSH.SHOBUN_HOUHOU_CD
  LEFT OUTER JOIN M_GENNYOURITSU AS MGENYO 
    ON MHS.HOUKOKUSHO_BUNRUI_CD = MGENYO.HOUKOKUSHO_BUNRUI_CD 
   AND TMD1.HAIKI_NAME_CD = MGENYO.HAIKI_NAME_CD
   AND TMD1.SBN_HOUHOU_CD = MGENYO.SHOBUN_HOUHOU_CD
  LEFT OUTER JOIN M_UNIT AS MU 
    ON M_SYS_INFO.MANI_KANSAN_KIHON_UNIT_CD = MU.UNIT_CD

 WHERE TME1.DELETE_FLG = 'false'
   AND TME1.FIRST_MANIFEST_KBN = 'false'
   AND ISDATE(TMD1.SBN_END_DATE) > 0
   AND (TMD1.LAST_SBN_END_DATE IS NOT NULL
     OR TMD1.LAST_SBN_GYOUSHA_CD IS NOT NULL
     OR TMD1.LAST_SBN_GENBA_CD IS NOT NULL
       )
   AND NOT EXISTS ( 
      SELECT * 
        FROM T_MANIFEST_RELATION AS TMR 
       WHERE TMD1.DETAIL_SYSTEM_ID = TMR.FIRST_SYSTEM_ID
       AND TMR.FIRST_HAIKI_KBN_CD <> 4
         AND TMR.DELETE_FLG = 'false' 
   )
/*IF dto.HAIKIBUTSU_KBN.Count != 0 */
    AND TME1.HAIKI_KBN_CD IN /*dto.HAIKIBUTSU_KBN*/(1,2)
/*END*/
/*IF dto.HIDUKESYURUI == '1'*/
    AND TME1.KOUFU_DATE >= /*dto.DATE_FROM*/
    AND TME1.KOUFU_DATE <= /*dto.DATE_TO*/
/*END*/
/*IF dto.HIDUKESYURUI == '2'*/
    AND TMU1.UPN_END_DATE >= /*dto.DATE_FROM*/
    AND TMU1.UPN_END_DATE <= /*dto.DATE_TO*/
/*END*/
/*IF dto.HIDUKESYURUI == '3'*/
    AND TMD1.SBN_END_DATE >= /*dto.DATE_FROM*/
    AND TMD1.SBN_END_DATE <= /*dto.DATE_TO*/
/*END*/
/*IF dto.KYOTEN_CD != null && dto.KYOTEN_CD != '' */
    AND TME1.KYOTEN_CD = /*dto.KYOTEN_CD*/
/*END*/
/*IF dto.SBN_GYOUSHA_CD != null && dto.SBN_GYOUSHA_CD != '' */
    AND TME1.SBN_GYOUSHA_CD = /*dto.SBN_GYOUSHA_CD*/
/*END*/    
/*IF dto.SBN_GENBA_CD != null && dto.SBN_GENBA_CD != '' */
    AND TMU1.UPN_SAKI_GENBA_CD >= /*dto.SBN_GENBA_CD*/
/*END*/
/*IF dto.SBN_GENBA_CD_TO != null && dto.SBN_GENBA_CD_TO != '' */
    AND TMU1.UPN_SAKI_GENBA_CD <= /*dto.SBN_GENBA_CD_TO*/
/*END*/

 GROUP BY MHS.HOUKOKUSHO_BUNRUI_CD 
     , MHB.HOUKOKUSHO_BUNRUI_NAME
     , TMD1.SBN_END_DATE 
     , TME1.HAIKI_KBN_CD 
     , TME1.KOUFU_DATE 
     , TME1.HST_GYOUSHA_NAME 
     , TME1.SBN_GYOUSHA_NAME 
     , TME1.MANIFEST_ID 
     , MSH.SHOBUN_HOUHOU_NAME_RYAKU 
     , MGENYO.GENNYOURITSU 
     , MU.UNIT_NAME_RYAKU 

 ORDER BY MHS.HOUKOKUSHO_BUNRUI_CD 
     , TME1.SBN_GYOUSHA_NAME 
     , MSH.SHOBUN_HOUHOU_NAME_RYAKU 
     , TMD1.SBN_END_DATE
