SELECT 
       CASE WHEN MDHS_MIX.HAIKI_SHURUI_CD IS NOT NULL
            THEN MDHS_MIX.HOUKOKUSHO_BUNRUI_CD
            ELSE MDHS.HOUKOKUSHO_BUNRUI_CD
       END AS HAIKI_SHURUI_CD 
     , CASE WHEN MHB_MIX.HOUKOKUSHO_BUNRUI_CD IS NOT NULL
            THEN MHB_MIX.HOUKOKUSHO_BUNRUI_NAME
            ELSE MHB.HOUKOKUSHO_BUNRUI_NAME
       END AS HAIKI_SHURUI_NAME
     , CASE WHEN ISDATE(DR182.SBN_END_DATE) > 0 THEN CONVERT(VARCHAR(10), CONVERT(DATETIME, DR182.SBN_END_DATE), 111) 
            ELSE NULL 
       END AS SHOBUN_NENGAPPI 
     , CASE WHEN ISDATE(DR182.HIKIWATASHI_DATE) > 0 THEN CONVERT(VARCHAR(10), CONVERT(DATETIME, DR182.HIKIWATASHI_DATE), 111) 
            ELSE NULL 
       END AS KOUFU_NENGAPPI 
     , CONVERT(smallint, 4) AS HAIKI_KBN_CD
     , '電子' AS HAIKIBUTU_KBN 
     , DR182.HST_SHA_NAME AS KOUFUSHAMEI 
     , DR182.SBN_SHA_NAME AS UKEIRESAKI 
     , ISNULL(DR18EX2.KANSAN_SUU, 0) AS UKEIRERYO 
     , MU.UNIT_NAME_RYAKU AS UKEIRERYO_TANI 
     , DR182.MANIFEST_ID AS KOUFUNO 
     , MSH.SHOBUN_HOUHOU_NAME_RYAKU AS SHOBUN_HOUHOU_NAME 
     , ISNULL(DR18EX2.KANSAN_SUU, 0) AS SHOBUNRYO 
     , MU.UNIT_NAME_RYAKU AS SHOBUNRYO_TANI 
     , DR182.SBN_SHA_NAME AS UKEIRESAKI_GOUKEI_NAME
     , MU.UNIT_NAME_RYAKU AS UKEIRESAKI_GOUKEI_TANI 
     , MSH.SHOBUN_HOUHOU_NAME_RYAKU AS SHOBUN_HOUHOU_GOUKEI_NAME
     , MU.UNIT_NAME_RYAKU AS SHOBUN_HOUHOU_GOUKEI_TANI 
     , CASE WHEN MDHS_MIX.HAIKI_SHURUI_CD IS NOT NULL
            THEN MDHS_MIX.HOUKOKUSHO_BUNRUI_CD
            ELSE MDHS.HOUKOKUSHO_BUNRUI_CD
       END AS HAIKI_SHURUI_GOUKEI_CD 
     , CASE WHEN MHB_MIX.HOUKOKUSHO_BUNRUI_CD IS NOT NULL
            THEN MHB_MIX.HOUKOKUSHO_BUNRUI_NAME
            ELSE MHB.HOUKOKUSHO_BUNRUI_NAME
       END AS HAIKI_SHURUI_GOUKEI_NAME 
     , MU.UNIT_NAME_RYAKU AS HAIKI_SHURUI_GOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS UKEIRERYOU_SOUGOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS SHOBUNRYOU_SOUGOUKEI_TANI 

  FROM DT_MF_TOC AS DMT
 INNER JOIN DT_R18 AS DR182 
    ON DMT.KANRI_ID = DR182.KANRI_ID 
   AND DMT.LATEST_SEQ = DR182.SEQ 
 INNER JOIN DT_R19 AS DR192 
    ON DR182.KANRI_ID = DR192.KANRI_ID 
   AND DR182.SEQ = DR192.SEQ 
   AND DR182.UPN_ROUTE_CNT = DR192.UPN_ROUTE_NO 
 LEFT JOIN DT_R13 AS DR132 
    ON DR182.KANRI_ID = DR132.KANRI_ID 
   AND DR182.SEQ = DR132.SEQ 
   AND DR182.LAST_SBN_CNT = DR132.REC_SEQ 
 INNER JOIN (
        SELECT 
            (CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN DT_R18_MIX.DETAIL_SYSTEM_ID ELSE DT_R18_EX.SYSTEM_ID END) AS SYSTEM_ID
            ,DT_R18_EX.KANRI_ID
            ,(CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN DT_R18_MIX.KANSAN_SUU ELSE DT_R18_EX.KANSAN_SUU END) AS KANSAN_SUU
            ,(CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN DT_R18_MIX.SBN_HOUHOU_CD ELSE DT_R18_EX.SBN_HOUHOU_CD END) AS SBN_HOUHOU_CD
            ,(CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN DT_R18_MIX.HAIKI_NAME_CD ELSE DT_R18_EX.HAIKI_NAME_CD END) AS HAIKI_NAME_CD
            ,(CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN DT_R18_MIX.HAIKI_DAI_CODE ELSE '' END) AS HAIKI_DAI_CODE
            ,(CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN DT_R18_MIX.HAIKI_CHU_CODE ELSE '' END) AS HAIKI_CHU_CODE
            ,(CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN DT_R18_MIX.HAIKI_SHO_CODE ELSE '' END) AS HAIKI_SHO_CODE
            ,(CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN DT_R18_MIX.SBN_ENDREP_KBN ELSE r18.SBN_ENDREP_KBN END) AS SBN_ENDREP_KBN
			,(CASE WHEN r18.SBN_ENDREP_KBN = 1 THEN DT_R18_EX.SBN_GYOUSHA_CD ELSE MD_SBN.GYOUSHA_CD END ) AS SBN_GYOUSHA_CD_M
			,(CASE WHEN r18.SBN_ENDREP_KBN = 1 THEN DT_R18_EX.SBN_GENBA_CD ELSE MD_SBN.GENBA_CD END ) AS SBN_GENBA_CD_M
            ,(CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN CONVERT(nvarchar,DT_R18_MIX.LAST_SBN_END_DATE,112) ELSE r18.LAST_SBN_END_DATE END) AS LAST_SBN_END_DATE_M
            ,DT_R18_EX.SBN_GYOUSHA_CD
            ,DT_R18_EX.SBN_GENBA_CD
            ,DT_R18_EX.HST_GYOUSHA_CD
            ,DT_R18_EX.DELETE_FLG
        FROM DT_R18_EX
		INNER JOIN DT_MF_TOC toc ON DT_R18_EX.KANRI_ID = toc.KANRI_ID
		INNER JOIN DT_R18 r18 ON toc.KANRI_ID = r18.KANRI_ID AND toc.LATEST_SEQ = r18.SEQ
        LEFT JOIN (SELECT * FROM DT_R18_MIX WHERE DELETE_FLG = 0) AS DT_R18_MIX ON
        DT_R18_EX.SYSTEM_ID = DT_R18_MIX.SYSTEM_ID
		LEFT JOIN DT_R13 r13 on r18.KANRI_ID = r13.KANRI_ID AND r18.SEQ = r13.SEQ AND r18.LAST_SBN_CNT = r13.REC_SEQ 
		LEFT JOIN M_DENSHI_JIGYOUJOU AS MD_SBN
			ON r13.LAST_SBN_JOU_NAME = MD_SBN.JIGYOUJOU_NAME
				AND (ISNULL(r13.LAST_SBN_JOU_ADDRESS1, '') + ISNULL(r13.LAST_SBN_JOU_ADDRESS2, '') + ISNULL(r13.LAST_SBN_JOU_ADDRESS3, '') + ISNULL(r13.LAST_SBN_JOU_ADDRESS4, ''))
				= (ISNULL(MD_SBN.JIGYOUJOU_ADDRESS1, '') + ISNULL(MD_SBN.JIGYOUJOU_ADDRESS2, '') + ISNULL(MD_SBN.JIGYOUJOU_ADDRESS3, '') + ISNULL(MD_SBN.JIGYOUJOU_ADDRESS4, ''))
				AND MD_SBN.JIGYOUJOU_KBN = 3
        WHERE DT_R18_EX.DELETE_FLG = 0
    ) AS DR18EX2
    ON DR182.KANRI_ID = DR18EX2.KANRI_ID 
   AND DR18EX2.DELETE_FLG = 'false' 
 INNER JOIN DT_R19_EX AS DR19EX2 
    ON DR192.KANRI_ID = DR19EX2.KANRI_ID 
   AND DR192.UPN_ROUTE_NO = DR19EX2.UPN_ROUTE_NO 
   AND DR19EX2.DELETE_FLG = 'false' 
 LEFT JOIN DT_R13_EX AS DR13EX2 
    ON DR132.KANRI_ID = DR13EX2.KANRI_ID 
   AND DR132.REC_SEQ = DR13EX2.REC_SEQ 
   AND DR13EX2.DELETE_FLG = 'false' 
 LEFT JOIN M_GYOUSHA AS MG_SBN 
    ON DR13EX2.LAST_SBN_GYOUSHA_CD = MG_SBN.GYOUSHA_CD 
   AND MG_SBN.JISHA_KBN = 'true' 
   AND MG_SBN.SHOBUN_NIOROSHI_GYOUSHA_KBN = 'true' 
 LEFT JOIN M_GENBA AS MGEN_LAST_SBN 
    ON DR13EX2.LAST_SBN_GYOUSHA_CD = MGEN_LAST_SBN.GYOUSHA_CD 
   AND DR13EX2.LAST_SBN_GENBA_CD = MGEN_LAST_SBN.GENBA_CD 
   AND MGEN_LAST_SBN.SAISHUU_SHOBUNJOU_KBN = 'true' 
 INNER JOIN M_SYS_INFO 
    ON SYS_ID = '0' 
/*IF dto.HIDUKESYURUI == '2'*/
 LEFT JOIN (
			SELECT R19M.KANRI_ID, R19M.SEQ, R19M.UPN_ROUTE_NO, MAX(Other_KUKAN.UPN_ROUTE_NO) AS 表示日付区間
			FROM DT_MF_TOC 
			INNER JOIN DT_R19 AS R19M ON DT_MF_TOC.KANRI_ID = R19M.KANRI_ID AND DT_MF_TOC.LATEST_SEQ = R19M.SEQ
			LEFT JOIN (
					SELECT R18.KANRI_ID, R18.SEQ, UPN_ROUTE_NO 
					FROM DT_MF_TOC toc
					LEFT JOIN DT_R18 R18 on toc.KANRI_ID = R18.KANRI_ID AND toc.LATEST_SEQ = R18.SEQ
					LEFT JOIN DT_R19 R19 on R18.KANRI_ID = R19.KANRI_ID AND R18.SEQ = R19.SEQ AND R18.HST_SHA_EDI_MEMBER_ID != R19.UPN_SHA_EDI_MEMBER_ID
                    UNION 
					SELECT R18.KANRI_ID, R18.SEQ, 0 AS UPN_ROUTE_NO 
					FROM DT_MF_TOC toc
					LEFT JOIN DT_R18 R18 on toc.KANRI_ID = R18.KANRI_ID AND toc.LATEST_SEQ = R18.SEQ
			) AS Other_KUKAN
			ON R19M.KANRI_ID = Other_KUKAN.KANRI_ID AND R19M.SEQ = Other_KUKAN.SEQ AND R19M.UPN_ROUTE_NO >= Other_KUKAN.UPN_ROUTE_NO
			GROUP BY R19M.KANRI_ID, R19M.SEQ, R19M.UPN_ROUTE_NO
 ) Other_KUKAN_F
 ON DR192.KANRI_ID = Other_KUKAN_F.KANRI_ID AND DR192.SEQ = Other_KUKAN_F.SEQ AND DR192.UPN_ROUTE_NO = Other_KUKAN_F.UPN_ROUTE_NO
 LEFT JOIN (
			SELECT R19U.KANRI_ID, R19U.SEQ, R19U.UPN_ROUTE_NO, R19U.UPN_END_DATE
			FROM DT_MF_TOC toc INNER JOIN DT_R19 R19U ON toc.KANRI_ID = R19U.KANRI_ID AND toc.LATEST_SEQ = R19U.SEQ
			UNION 
			SELECT R18U.KANRI_ID, R18U.SEQ, 0 AS UPN_ROUTE_NO, R18U.HIKIWATASHI_DATE AS UPN_END_DATE
			FROM DT_MF_TOC toc INNER JOIN DT_R18 R18U ON toc.KANRI_ID = R18U.KANRI_ID AND toc.LATEST_SEQ = R18U.SEQ
 ) ROUTE_DATA 
 ON Other_KUKAN_F.KANRI_ID = ROUTE_DATA.KANRI_ID and Other_KUKAN_F.SEQ = ROUTE_DATA.SEQ and Other_KUKAN_F.表示日付区間 = ROUTE_DATA.UPN_ROUTE_NO
 /*END*/
  LEFT JOIN M_DENSHI_HAIKI_SHURUI AS MDHS 
    ON DR182.HAIKI_DAI_CODE = SUBSTRING(MDHS.HAIKI_SHURUI_CD,1,2) 
   AND DR182.HAIKI_CHU_CODE = SUBSTRING(MDHS.HAIKI_SHURUI_CD,3,1) 
   AND DR182.HAIKI_SHO_CODE = SUBSTRING(MDHS.HAIKI_SHURUI_CD,4,1) 
  LEFT OUTER JOIN M_DENSHI_HAIKI_SHURUI AS MDHS_MIX 
    ON DR18EX2.HAIKI_DAI_CODE = SUBSTRING(MDHS_MIX.HAIKI_SHURUI_CD,1,2) 
   AND DR18EX2.HAIKI_CHU_CODE = SUBSTRING(MDHS_MIX.HAIKI_SHURUI_CD,3,1) 
   AND DR18EX2.HAIKI_SHO_CODE = SUBSTRING(MDHS_MIX.HAIKI_SHURUI_CD,4,1) 
  LEFT OUTER JOIN M_HOUKOKUSHO_BUNRUI AS MHB 
    ON MDHS.HOUKOKUSHO_BUNRUI_CD = MHB.HOUKOKUSHO_BUNRUI_CD
  LEFT OUTER JOIN M_HOUKOKUSHO_BUNRUI AS MHB_MIX 
    ON MDHS_MIX.HOUKOKUSHO_BUNRUI_CD = MHB_MIX.HOUKOKUSHO_BUNRUI_CD
  LEFT JOIN M_SHOBUN_HOUHOU AS MSH 
    ON DR18EX2.SBN_HOUHOU_CD = MSH.SHOBUN_HOUHOU_CD 
   AND MSH.DENSHI_USE_KBN = 'true' 
  LEFT JOIN M_UNIT AS MU 
    ON M_SYS_INFO.MANI_KANSAN_KIHON_UNIT_CD = MU.UNIT_CD 
  LEFT JOIN M_GYOUSHA AS HST_GYOUSHA
    ON DR18EX2.HST_GYOUSHA_CD = HST_GYOUSHA.GYOUSHA_CD
 WHERE 
   (((DR182.FIRST_MANIFEST_FLAG <> '' AND DR182.FIRST_MANIFEST_FLAG IS NOT NULL) AND ISNULL(HST_GYOUSHA.JISHA_KBN, 0) = 1)
OR(
    ISNULL(DR18EX2.SBN_ENDREP_KBN, 0) = 2
AND (
    ISNULL(DR18EX2.SBN_HOUHOU_CD, 0) = 300
    OR  ISNULL(DR18EX2.SBN_HOUHOU_CD, 0) = 301
    OR  ISNULL(DR18EX2.SBN_HOUHOU_CD, 0) = 302
    OR  ISNULL(DR18EX2.SBN_HOUHOU_CD, 0) = 303
    OR  ISNULL(DR18EX2.SBN_HOUHOU_CD, 0) = 304
    OR  ISNULL(DR18EX2.SBN_HOUHOU_CD, 0) = 310
    )))
/*IF dto.HIDUKESYURUI == '1'*/
   AND DR182.HIKIWATASHI_DATE IS NOT NULL 
   AND DR182.HIKIWATASHI_DATE <> '' 
   AND DR182.HIKIWATASHI_DATE <> '0'
   AND CONVERT(DATETIME,DR182.HIKIWATASHI_DATE) >= /*dto.DATE_FROM*/
   AND CONVERT(DATETIME,DR182.HIKIWATASHI_DATE) <= /*dto.DATE_TO*/
/*END*/
/*IF dto.HIDUKESYURUI == '2'*/
   AND ROUTE_DATA.UPN_END_DATE IS NOT NULL 
   AND ROUTE_DATA.UPN_END_DATE <> '' 
   AND ROUTE_DATA.UPN_END_DATE <> '0'
   AND CONVERT(DATETIME,ROUTE_DATA.UPN_END_DATE) >= /*dto.DATE_FROM*/
   AND CONVERT(DATETIME,ROUTE_DATA.UPN_END_DATE) <= /*dto.DATE_TO*/    
/*END*/
/*IF dto.HIDUKESYURUI == '3'*/
   AND DR18EX2.LAST_SBN_END_DATE_M IS NOT NULL 
   AND DR18EX2.LAST_SBN_END_DATE_M <> '' 
   AND DR18EX2.LAST_SBN_END_DATE_M <> '0'
   AND CONVERT(DATETIME,DR18EX2.LAST_SBN_END_DATE_M) >= /*dto.DATE_FROM*/
   AND CONVERT(DATETIME,DR18EX2.LAST_SBN_END_DATE_M) <= /*dto.DATE_TO*/    
/*END*/
/*IF dto.SBN_GYOUSHA_CD != null && dto.SBN_GYOUSHA_CD != '' */
   AND DR18EX2.SBN_GYOUSHA_CD_M = /*dto.SBN_GYOUSHA_CD*/
/*END*/
/*IF dto.SBN_GENBA_CD != null && dto.SBN_GENBA_CD != '' */
   AND DR18EX2.SBN_GENBA_CD_M >= /*dto.SBN_GENBA_CD*/
/*END*/
/*IF dto.SBN_GENBA_CD_TO != null && dto.SBN_GENBA_CD_TO != '' */
   AND DR18EX2.SBN_GENBA_CD_M <= /*dto.SBN_GENBA_CD_TO*/
/*END*/

 ORDER BY MDHS.HOUKOKUSHO_BUNRUI_CD 
     , DR182.SBN_SHA_NAME 
     , MSH.SHOBUN_HOUHOU_NAME_RYAKU 
     , DR182.SBN_END_DATE
