SELECT 
     CASE WHEN MDHS_MIX.HAIKI_SHURUI_CD IS NOT NULL
            THEN MDHS_MIX.HOUKOKUSHO_BUNRUI_CD
            ELSE MDHS.HOUKOKUSHO_BUNRUI_CD
     END AS HAIKI_SHURUI_CD 
     , CASE WHEN MHB_MIX.HOUKOKUSHO_BUNRUI_CD IS NOT NULL
            THEN MHB_MIX.HOUKOKUSHO_BUNRUI_NAME
            ELSE MHB.HOUKOKUSHO_BUNRUI_NAME
       END AS HAIKI_SHURUI_NAME
     , CASE WHEN ISDATE(ROUTE_DATA.UPN_END_DATE) > 0 THEN CONVERT(VARCHAR(10), CONVERT(DATETIME, ROUTE_DATA.UPN_END_DATE), 111) 
            ELSE NULL 
       END AS UNPAN_NENGAPPI 
     , CASE WHEN ISDATE(DR182.HIKIWATASHI_DATE) > 0 THEN CONVERT(VARCHAR(10), CONVERT(DATETIME, DR182.HIKIWATASHI_DATE), 111) 
            ELSE NULL 
       END AS KOUFU_NENGAPPI 
     , CONVERT(smallint, 4) AS HAIKI_KBN_CD
     , '電子' AS HAIKIBUTU_KBN 
     , DR182.HST_SHA_NAME AS KOUFUSHAMEI 
     , DR182.MANIFEST_ID AS KOUFUNO 
     , DR182.HST_JOU_NAME AS UKEIRESAKI 
     , ISNULL(DR18EX2.KANSAN_SUU, 0) AS UKEIRERYO 
     , MU.UNIT_NAME_RYAKU AS UKEIRERYO_TANI 
     , DR192.UPNSAKI_JOU_NAME AS UNPANSAKI 
     , ISNULL(DR18EX2.KANSAN_SUU, 0) AS UNPANRYO 
     , MU.UNIT_NAME_RYAKU AS UNPANRYO_TANI 
     , CASE WHEN DR182.UPN_ROUTE_CNT > DR192.UPN_ROUTE_NO THEN DR192.UPNSAKI_JOU_NAME 
            ELSE '' 
       END AS TUMIKAEHOKAN 
     , ISNULL(DR192.UPN_WAY_CODE,'') AS UNPAN_HOUHOU_CD 
     , MUH.UNPAN_HOUHOU_NAME_RYAKU AS UNPAN_HOUHOU_NAME 
     , CASE WHEN DR182.UPN_ROUTE_CNT > DR192.UPN_ROUTE_NO AND ISNULL(DR192.UPNSAKI_JOU_NAME,'') != '' THEN ISNULL(DR18EX2.KANSAN_SUU,0) 
            ELSE 0 
       END AS HANSHUTURYO 
     , MU.UNIT_NAME_RYAKU AS HANSHUTURYO_TANI 
     , DR192.UPNSAKI_JOU_NAME AS UNPANSAKI_GOUKEI_NAME
     , MU.UNIT_NAME_RYAKU AS UNPANSAKI_GOUKEI_SUURYO_TANI 
     , DR182.HST_JOU_NAME AS UKEIRESAKI_GOUKEI_NAME
     , MU.UNIT_NAME_RYAKU AS UKEIRESAKI_GOUKEI_SUURYO_TANI 
     , DR192.UPN_WAY_CODE AS UNPAN_HOUHOU_GOUKEI_CD 
     , MUH.UNPAN_HOUHOU_NAME_RYAKU AS UNPAN_HOUHOU_GOUKEI_NAME 
     , MU.UNIT_NAME_RYAKU AS UNPAN_HOUHOU_GOUKEI_SUURYO_TANI 
     , MU.UNIT_NAME_RYAKU AS HAIKI_GOUKEI_SUURYO_TANI 
     , MU.UNIT_NAME_RYAKU AS UKEIRERYO_SOUGOUKEI_TANI
     , MU.UNIT_NAME_RYAKU AS UNPANRYO_SOUGOUKEI_TANI
     , MU.UNIT_NAME_RYAKU AS HANSHUTURYO_SOUGOUKEI_TANI

  FROM DT_MF_TOC AS DMT2 
 INNER JOIN DT_R18 AS DR182 
    ON DMT2.KANRI_ID = DR182.KANRI_ID 
   AND DMT2.LATEST_SEQ = DR182.SEQ 
 INNER JOIN DT_R19 AS DR192 
    ON DR182.KANRI_ID = DR192.KANRI_ID 
   AND DR182.SEQ = DR192.SEQ 
 INNER JOIN (
        SELECT
            DT_R18_EX.KANRI_ID
            ,(CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN DT_R18_MIX.KANSAN_SUU ELSE DT_R18_EX.KANSAN_SUU END) AS KANSAN_SUU
            ,(CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN DT_R18_MIX.HAIKI_DAI_CODE ELSE '' END) AS HAIKI_DAI_CODE
            ,(CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN DT_R18_MIX.HAIKI_CHU_CODE ELSE '' END) AS HAIKI_CHU_CODE
            ,(CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN DT_R18_MIX.HAIKI_SHO_CODE ELSE '' END) AS HAIKI_SHO_CODE
            ,DT_R18_EX.HST_GYOUSHA_CD
        FROM DT_R18_EX
        LEFT JOIN (SELECT * FROM DT_R18_MIX WHERE DELETE_FLG = 0) AS DT_R18_MIX ON
        DT_R18_EX.SYSTEM_ID = DT_R18_MIX.SYSTEM_ID
        WHERE DT_R18_EX.DELETE_FLG = 0
    ) AS DR18EX2
    ON DR182.KANRI_ID = DR18EX2.KANRI_ID 
 INNER JOIN DT_R19_EX AS DR19EX2 
    ON DR192.KANRI_ID = DR19EX2.KANRI_ID 
   AND DR192.UPN_ROUTE_NO = DR19EX2.UPN_ROUTE_NO 
   AND DR19EX2.DELETE_FLG = 'false' 

 LEFT JOIN (
			SELECT R19M.KANRI_ID, R19M.SEQ, R19M.UPN_ROUTE_NO, MAX(Other_KUKAN.UPN_ROUTE_NO) AS 表示日付区間
			FROM DT_MF_TOC 
			INNER JOIN DT_R19 AS R19M ON DT_MF_TOC.KANRI_ID = R19M.KANRI_ID AND DT_MF_TOC.LATEST_SEQ = R19M.SEQ
			LEFT JOIN (
					SELECT R18.KANRI_ID, R18.SEQ, UPN_ROUTE_NO 
					FROM DT_MF_TOC toc
					LEFT JOIN DT_R18 R18 on toc.KANRI_ID = R18.KANRI_ID AND toc.LATEST_SEQ = R18.SEQ
					LEFT JOIN DT_R19 R19 on R18.KANRI_ID = R19.KANRI_ID AND R18.SEQ = R19.SEQ AND R18.HST_SHA_EDI_MEMBER_ID != R19.UPN_SHA_EDI_MEMBER_ID
                    UNION 
					SELECT R18.KANRI_ID, R18.SEQ, 0 AS UPN_ROUTE_NO 
					FROM DT_MF_TOC toc
					LEFT JOIN DT_R18 R18 on toc.KANRI_ID = R18.KANRI_ID AND toc.LATEST_SEQ = R18.SEQ
			) AS Other_KUKAN
			ON R19M.KANRI_ID = Other_KUKAN.KANRI_ID AND R19M.SEQ = Other_KUKAN.SEQ AND R19M.UPN_ROUTE_NO >= Other_KUKAN.UPN_ROUTE_NO
			GROUP BY R19M.KANRI_ID, R19M.SEQ, R19M.UPN_ROUTE_NO
 ) Other_KUKAN_F
 ON DR192.KANRI_ID = Other_KUKAN_F.KANRI_ID AND DR192.SEQ = Other_KUKAN_F.SEQ AND DR192.UPN_ROUTE_NO = Other_KUKAN_F.UPN_ROUTE_NO
 LEFT JOIN (
			SELECT R19U.KANRI_ID, R19U.SEQ, R19U.UPN_ROUTE_NO, R19U.UPN_END_DATE
			FROM DT_MF_TOC toc INNER JOIN DT_R19 R19U ON toc.KANRI_ID = R19U.KANRI_ID AND toc.LATEST_SEQ = R19U.SEQ
			WHERE toc.STATUS_FLAG = '4'
			UNION 
			SELECT R18U.KANRI_ID, R18U.SEQ, 0 AS UPN_ROUTE_NO, R18U.HIKIWATASHI_DATE AS UPN_END_DATE
			FROM DT_MF_TOC toc INNER JOIN DT_R18 R18U ON toc.KANRI_ID = R18U.KANRI_ID AND toc.LATEST_SEQ = R18U.SEQ
			WHERE toc.STATUS_FLAG = '4'
 ) ROUTE_DATA 
 ON Other_KUKAN_F.KANRI_ID = ROUTE_DATA.KANRI_ID and Other_KUKAN_F.SEQ = ROUTE_DATA.SEQ and Other_KUKAN_F.表示日付区間 = ROUTE_DATA.UPN_ROUTE_NO


 INNER JOIN M_SYS_INFO 
    ON SYS_ID = '0' 
 INNER JOIN M_GYOUSHA AS MG_UPN 
    ON DR19EX2.UPN_GYOUSHA_CD = MG_UPN.GYOUSHA_CD 
   AND MG_UPN.JISHA_KBN = 'true' 
   AND MG_UPN.UNPAN_JUTAKUSHA_KAISHA_KBN = 'true' 
  LEFT OUTER JOIN M_DENSHI_HAIKI_SHURUI AS MDHS 
    ON DR182.HAIKI_DAI_CODE = SUBSTRING(MDHS.HAIKI_SHURUI_CD,1,2) 
   AND DR182.HAIKI_CHU_CODE = SUBSTRING(MDHS.HAIKI_SHURUI_CD,3,1) 
   AND DR182.HAIKI_SHO_CODE = SUBSTRING(MDHS.HAIKI_SHURUI_CD,4,1) 
  LEFT OUTER JOIN M_DENSHI_HAIKI_SHURUI AS MDHS_MIX 
    ON DR18EX2.HAIKI_DAI_CODE = SUBSTRING(MDHS_MIX.HAIKI_SHURUI_CD,1,2) 
   AND DR18EX2.HAIKI_CHU_CODE = SUBSTRING(MDHS_MIX.HAIKI_SHURUI_CD,3,1) 
   AND DR18EX2.HAIKI_SHO_CODE = SUBSTRING(MDHS_MIX.HAIKI_SHURUI_CD,4,1) 
  LEFT OUTER JOIN M_HOUKOKUSHO_BUNRUI AS MHB 
    ON MDHS.HOUKOKUSHO_BUNRUI_CD = MHB.HOUKOKUSHO_BUNRUI_CD
  LEFT OUTER JOIN M_HOUKOKUSHO_BUNRUI AS MHB_MIX 
    ON MDHS_MIX.HOUKOKUSHO_BUNRUI_CD = MHB_MIX.HOUKOKUSHO_BUNRUI_CD
  LEFT OUTER JOIN M_UNPAN_HOUHOU AS MUH 
    ON DR192.UPN_WAY_CODE = MUH.UNPAN_HOUHOU_CD 
  LEFT OUTER JOIN M_UNIT AS MU 
    ON M_SYS_INFO.MANI_KANSAN_KIHON_UNIT_CD = MU.UNIT_CD 
  LEFT JOIN M_GYOUSHA AS HST_GYOUSHA
    ON DR18EX2.HST_GYOUSHA_CD = HST_GYOUSHA.GYOUSHA_CD

 WHERE DMT2.STATUS_FLAG = 4  
 AND ( (DR182.FIRST_MANIFEST_FLAG <> '' OR DR182.FIRST_MANIFEST_FLAG IS NOT NULL) AND ISNULL(HST_GYOUSHA.JISHA_KBN, 0) = 1 ) 
/*IF dto.HIDUKESYURUI == '1'*/ 
   AND DR182.HIKIWATASHI_DATE IS NOT NULL 
   AND DR182.HIKIWATASHI_DATE <> '' 
   AND DR182.HIKIWATASHI_DATE <> '0' 
   AND CONVERT(DATETIME,DR182.HIKIWATASHI_DATE) >= /*dto.DATE_FROM*/ 
   AND CONVERT(DATETIME,DR182.HIKIWATASHI_DATE) <= /*dto.DATE_TO*/ 
/*END*/ 
/*IF dto.HIDUKESYURUI == '2'*/ 
   AND ROUTE_DATA.UPN_END_DATE IS NOT NULL 
   AND ROUTE_DATA.UPN_END_DATE <> '' 
   AND ROUTE_DATA.UPN_END_DATE <> '0' 
   AND CONVERT(DATETIME,ROUTE_DATA.UPN_END_DATE) >= /*dto.DATE_FROM*/ 
   AND CONVERT(DATETIME,ROUTE_DATA.UPN_END_DATE) <= /*dto.DATE_TO*/ 
/*END*/ 
/*IF dto.HIDUKESYURUI == '3'*/ 
   AND DR182.SBN_END_DATE IS NOT NULL 
   AND DR182.SBN_END_DATE <> '' 
   AND DR182.SBN_END_DATE <> '0' 
   AND CONVERT(DATETIME,DR182.SBN_END_DATE) >= /*dto.DATE_FROM*/ 
   AND CONVERT(DATETIME,DR182.SBN_END_DATE) <= /*dto.DATE_TO*/ 
/*END*/ 
/*IF dto.SBN_GYOUSHA_CD != null && dto.SBN_GYOUSHA_CD != '' */ 
   AND DR19EX2.UPN_GYOUSHA_CD = /*dto.SBN_GYOUSHA_CD*/ 
/*END*/ 

 ORDER BY MDHS.HOUKOKUSHO_BUNRUI_CD 
     , DR192.UPN_WAY_CODE 
     , DR182.SBN_SHA_NAME 
     , DR192.UPNSAKI_JOU_NAME 
     , DR182.MANIFEST_ID 
     , DR192.UPN_ROUTE_NO 