SELECT  HAIKI_SHURUI_CD
     ,  HAIKI_SHURUI_NAME
     ,  SHOBUN_NENGAPPI 
     ,  KOUFU_NENGAPPI 
     ,  HAIKI_KBN_CD
     ,  HAIKIBUTU_KBN 
     ,  KOUFUSHAMEI 
     ,  UKEIRESAKI 
     ,  UKEIRERYO 
     ,  UKEIRERYO_TANI 
     ,  KOUFUNO2 
     ,  KOUFUNO 
     ,  SHOBUN_HOUHOU_NAME 
     ,  SHOBUNRYO 
     ,  SHOBUNRYO_TANI 
     ,  MOCHIDASHISAKI 
     ,  ROUND(MOCHIDASHIRYO, /*dto.MANIFEST_SUURYOU_FORMAT*/, 1) AS MOCHIDASHIRYO
     ,  MOCHIDASHIRYO_TANI 
     ,  UKEIRESAKI_GOUKEI_NAME 
     ,  UKEIRESAKI_GOUKEI_TANI 
     ,  SHOBUN_HOUHOU_GOUKEI_NAME 
     ,  SHOBUN_HOUHOU_GOUKEI_TANI 
     ,  MOCHIDASHISAKI_GOUKEI_NAME 
     ,  MOCHIDASHISAKI_GOUKEI_TANI 
     ,  HAIKI_SHURUI_GOUKEI_CD 
     ,  HAIKI_SHURUI_GOUKEI_NAME 
     ,  HAIKI_SHURUI_GOUKEI_TANI 
     ,  UKEIRESAKI_SOUGOUKEI_TANI 
     ,  SHOBUN_HOUHOU_SOUGOUKEI_TANI 
     ,  MOCHIDASHISAKI_SOUGOUKEI_TANI 
     ,  HAIKI_SHURUI_SOUGOUKEI_TANI 
FROM (
SELECT MHS.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_CD
     , MHB.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_NAME
     , CONVERT(VARCHAR(10), TMD1.SBN_END_DATE, 111) AS SHOBUN_NENGAPPI 
     , CONVERT(VARCHAR(10), TME1.KOUFU_DATE, 111) AS KOUFU_NENGAPPI 
     , TME1.HAIKI_KBN_CD
     , CASE 
           WHEN TME1.HAIKI_KBN_CD = '1' THEN 'éYîp(íºçs)' 
           WHEN TME1.HAIKI_KBN_CD = '2' THEN 'åöîp' 
           WHEN TME1.HAIKI_KBN_CD = '3' THEN 'éYîp(êœë÷)' 
           ELSE '' 
       END AS HAIKIBUTU_KBN
     , TME1.HST_GYOUSHA_NAME AS KOUFUSHAMEI 
     , TME1.SBN_GYOUSHA_NAME AS UKEIRESAKI 
     , SUM(ISNULL(TMD1.KANSAN_SUU,0)) AS UKEIRERYO 
     , MU.UNIT_NAME_RYAKU AS UKEIRERYO_TANI 
     , NEXT_MANIFEST.MANIFEST_ID AS KOUFUNO2 
     , TME1.MANIFEST_ID AS KOUFUNO 
     , MSH.SHOBUN_HOUHOU_NAME_RYAKU AS SHOBUN_HOUHOU_NAME 
     , SUM(ISNULL(TMD1.KANSAN_SUU,0)) AS SHOBUNRYO 
     , MU.UNIT_NAME_RYAKU AS SHOBUNRYO_TANI 
     , NEXT_MANIFEST.GENBA_NAME1 + NEXT_MANIFEST.GENBA_NAME2 AS MOCHIDASHISAKI 
	 , SUM(ISNULL(TMD1.GENNYOU_SUU,0)) AS MOCHIDASHIRYO 
     , MU.UNIT_NAME_RYAKU AS MOCHIDASHIRYO_TANI 
     , TME1.SBN_GYOUSHA_NAME AS UKEIRESAKI_GOUKEI_NAME
     , MU.UNIT_NAME_RYAKU AS UKEIRESAKI_GOUKEI_TANI 
     , MSH.SHOBUN_HOUHOU_NAME_RYAKU AS SHOBUN_HOUHOU_GOUKEI_NAME
     , MU.UNIT_NAME_RYAKU AS SHOBUN_HOUHOU_GOUKEI_TANI 
     , NEXT_MANIFEST.GENBA_NAME_RYAKU AS MOCHIDASHISAKI_GOUKEI_NAME
     , MU.UNIT_NAME_RYAKU AS MOCHIDASHISAKI_GOUKEI_TANI 
     , MHS.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_GOUKEI_CD 
     , MHB.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_GOUKEI_NAME 
     , MU.UNIT_NAME_RYAKU AS HAIKI_SHURUI_GOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS UKEIRESAKI_SOUGOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS SHOBUN_HOUHOU_SOUGOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS MOCHIDASHISAKI_SOUGOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS HAIKI_SHURUI_SOUGOUKEI_TANI 

  FROM T_MANIFEST_ENTRY AS TME1 
 INNER JOIN T_MANIFEST_UPN AS TMU1 
    ON TME1.SYSTEM_ID = TMU1.SYSTEM_ID 
   AND TME1.SEQ = TMU1.SEQ 
 INNER JOIN ( 
      SELECT TME_SANPAI.SYSTEM_ID 
           , TME_SANPAI.SEQ 
           , MIN(TMU_SANPAI.UPN_ROUTE_NO) AS UPN_ROUTE_NO 
        FROM T_MANIFEST_ENTRY    AS TME_SANPAI 
       INNER JOIN T_MANIFEST_UPN AS TMU_SANPAI 
          ON TME_SANPAI.SYSTEM_ID = TMU_SANPAI.SYSTEM_ID 
         AND TME_SANPAI.SEQ       = TMU_SANPAI.SEQ 
       WHERE TME_SANPAI.DELETE_FLG = 'false' 
         AND TME_SANPAI.HAIKI_KBN_CD IN (1,3) 
         AND TMU_SANPAI.UPN_SAKI_KBN = 1 
       GROUP BY TME_SANPAI.SYSTEM_ID 
           , TME_SANPAI.SEQ 
       UNION 
      SELECT TME_KENPAI.SYSTEM_ID 
           , TME_KENPAI.SEQ 
           , MIN(TMU_KENPAI.UPN_ROUTE_NO) AS UPN_ROUTE_NO 
        FROM T_MANIFEST_ENTRY    AS TME_KENPAI 
       INNER JOIN T_MANIFEST_UPN AS TMU_KENPAI 
          ON TME_KENPAI.SYSTEM_ID = TMU_KENPAI.SYSTEM_ID 
         AND TME_KENPAI.SEQ       = TMU_KENPAI.SEQ 
       WHERE TME_KENPAI.DELETE_FLG = 'false' 
         AND TME_KENPAI.HAIKI_KBN_CD = 2 
       GROUP BY TME_KENPAI.SYSTEM_ID 
           , TME_KENPAI.SEQ 
     ) AS TMU_MAX_ROUTE 
    ON TMU1.SYSTEM_ID = TMU_MAX_ROUTE.SYSTEM_ID 
   AND TMU1.SEQ = TMU_MAX_ROUTE.SEQ 
   AND TMU1.UPN_ROUTE_NO = TMU_MAX_ROUTE.UPN_ROUTE_NO 
 INNER JOIN T_MANIFEST_DETAIL AS TMD1 
    ON TME1.SYSTEM_ID = TMD1.SYSTEM_ID 
   AND TME1.SEQ = TMD1.SEQ
 INNER JOIN M_GYOUSHA AS MG1_SBN 
    ON TME1.SBN_GYOUSHA_CD = MG1_SBN.GYOUSHA_CD 
   AND MG1_SBN.JISHA_KBN = 'true'
   AND MG1_SBN.SHOBUN_NIOROSHI_GYOUSHA_KBN = 'true'
 INNER JOIN M_SYS_INFO 
    ON SYS_ID = '0'
 LEFT JOIN T_MANIFEST_RELATION AS TMR 
    ON TMD1.DETAIL_SYSTEM_ID = TMR.FIRST_SYSTEM_ID 
    AND TMR.FIRST_HAIKI_KBN_CD <> 4
   AND TMR.DELETE_FLG = 'false' 
 LEFT JOIN (
      SELECT TMD2.DETAIL_SYSTEM_ID AS NEXT_SYSTEM_ID 
           , TME2.SEQ AS NEXT_SEQ
           , TME2.MANIFEST_ID 
           , MGEN2_UPN.GENBA_NAME_RYAKU 
		   , TMU2.UPN_SAKI_GENBA_NAME AS GENBA_NAME1
           , '' AS GENBA_NAME2
		   , TME2.HAIKI_KBN_CD
        FROM T_MANIFEST_ENTRY AS TME2 
       INNER JOIN T_MANIFEST_DETAIL AS TMD2
          ON TME2.SYSTEM_ID = TMD2.SYSTEM_ID
         AND TME2.SEQ = TMD2.SEQ
       INNER JOIN T_MANIFEST_UPN AS TMU2 
          ON TME2.SYSTEM_ID = TMU2.SYSTEM_ID 
         AND TME2.SEQ = TMU2.SEQ 
       INNER JOIN ( 
            SELECT TME_SANPAI.SYSTEM_ID 
                 , TME_SANPAI.SEQ 
                 , MIN(TMU_SANPAI.UPN_ROUTE_NO) AS UPN_ROUTE_NO 
              FROM T_MANIFEST_ENTRY    AS TME_SANPAI 
             INNER JOIN T_MANIFEST_UPN AS TMU_SANPAI 
                ON TME_SANPAI.SYSTEM_ID = TMU_SANPAI.SYSTEM_ID 
               AND TME_SANPAI.SEQ       = TMU_SANPAI.SEQ 
             WHERE TME_SANPAI.DELETE_FLG = 'false' 
               AND TME_SANPAI.HAIKI_KBN_CD IN (1,3) 
               AND TMU_SANPAI.UPN_SAKI_KBN = 1 
             GROUP BY TME_SANPAI.SYSTEM_ID 
                 , TME_SANPAI.SEQ 
             UNION 
            SELECT TME_KENPAI.SYSTEM_ID 
                 , TME_KENPAI.SEQ 
                 , MIN(TMU_KENPAI.UPN_ROUTE_NO) AS UPN_ROUTE_NO 
              FROM T_MANIFEST_ENTRY    AS TME_KENPAI 
             INNER JOIN T_MANIFEST_UPN AS TMU_KENPAI 
                ON TME_KENPAI.SYSTEM_ID = TMU_KENPAI.SYSTEM_ID 
               AND TME_KENPAI.SEQ       = TMU_KENPAI.SEQ 
             WHERE TME_KENPAI.DELETE_FLG = 'false' 
               AND TME_KENPAI.HAIKI_KBN_CD = 2 
             GROUP BY TME_KENPAI.SYSTEM_ID 
                 , TME_KENPAI.SEQ 
           ) AS TMU_MAX_ROUTE 
          ON TMU2.SYSTEM_ID = TMU_MAX_ROUTE.SYSTEM_ID 
         AND TMU2.SEQ = TMU_MAX_ROUTE.SEQ 
         AND TMU2.UPN_ROUTE_NO = TMU_MAX_ROUTE.UPN_ROUTE_NO 
        LEFT OUTER JOIN M_GENBA AS MGEN2_UPN 
          ON TMU2.UPN_SAKI_GYOUSHA_CD = MGEN2_UPN.GYOUSHA_CD
         AND TMU2.UPN_SAKI_GENBA_CD = MGEN2_UPN.GENBA_CD
       WHERE TME2.DELETE_FLG = 'false' 
       UNION 
      SELECT DR18EX2.SYSTEM_ID AS NEXT_SYSTEM_ID 
           , DR18EX2.SEQ AS NEXT_SEQ
           , DR18EX2.MANIFEST_ID 
           , MGEN2_UPN.GENBA_NAME_RYAKU 
		   , R19_2.UPNSAKI_JOU_NAME AS GENBA_NAME1
		   , '' AS GENBA_NAME2
           , CONVERT(smallint, 4) AS HAIKI_KBN_CD
        FROM DT_R18_EX AS DR18EX2 
       INNER JOIN DT_MF_TOC AS DMT2 
          ON DR18EX2.KANRI_ID = DMT2.KANRI_ID 
       INNER JOIN DT_R18 AS DR182 
          ON DMT2.KANRI_ID = DR182.KANRI_ID 
         AND DMT2.LATEST_SEQ = DR182.SEQ 
       INNER JOIN DT_R19_EX AS DR19EX2 
          ON DR18EX2.SYSTEM_ID = DR19EX2.SYSTEM_ID 
         AND DR18EX2.SEQ = DR19EX2.SEQ 
         AND DR182.UPN_ROUTE_CNT = DR19EX2.UPN_ROUTE_NO 
       INNER JOIN DT_R19 AS R19_2
          ON R19_2.KANRI_ID = DMT2.KANRI_ID
         AND R19_2.SEQ = DMT2.LATEST_SEQ
         AND R19_2.UPN_ROUTE_NO = DR182.UPN_ROUTE_CNT
        LEFT OUTER JOIN M_GENBA AS MGEN2_UPN 
          ON DR19EX2.UPNSAKI_GYOUSHA_CD = MGEN2_UPN.GYOUSHA_CD
         AND DR19EX2.UPNSAKI_GENBA_CD = MGEN2_UPN.GENBA_CD
       WHERE DR18EX2.DELETE_FLG = 'false' 
        ) AS NEXT_MANIFEST 
    ON ((TMR.NEXT_SYSTEM_ID = NEXT_MANIFEST.NEXT_SYSTEM_ID)
    AND (TMR.NEXT_HAIKI_KBN_CD = NEXT_MANIFEST.HAIKI_KBN_CD))
  LEFT OUTER JOIN T_MANIFEST_DETAIL AS TMD2 
    ON NEXT_MANIFEST.NEXT_SYSTEM_ID = TMD2.SYSTEM_ID 
   AND NEXT_MANIFEST.NEXT_SEQ = TMD2.SEQ
   AND TMD1.DETAIL_SYSTEM_ID = TMD2.DETAIL_SYSTEM_ID
  LEFT OUTER JOIN M_HAIKI_SHURUI AS MHS 
    ON TME1.HAIKI_KBN_CD = MHS.HAIKI_KBN_CD 
   AND TMD1.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD 
  LEFT OUTER JOIN M_HOUKOKUSHO_BUNRUI AS MHB 
    ON MHS.HOUKOKUSHO_BUNRUI_CD = MHB.HOUKOKUSHO_BUNRUI_CD
  LEFT OUTER JOIN M_SHOBUN_HOUHOU AS MSH 
    ON TMD1.SBN_HOUHOU_CD = MSH.SHOBUN_HOUHOU_CD
  LEFT OUTER JOIN M_GENNYOURITSU AS MGENYO 
    ON MHS.HOUKOKUSHO_BUNRUI_CD = MGENYO.HOUKOKUSHO_BUNRUI_CD 
   AND TMD1.HAIKI_NAME_CD = MGENYO.HAIKI_NAME_CD
   AND TMD1.SBN_HOUHOU_CD = MGENYO.SHOBUN_HOUHOU_CD
  LEFT OUTER JOIN M_UNIT AS MU 
    ON M_SYS_INFO.MANI_KANSAN_KIHON_UNIT_CD = MU.UNIT_CD

 WHERE TME1.DELETE_FLG = 'false'
   AND TME1.FIRST_MANIFEST_KBN = 'false' 
   AND ISDATE(TMD1.SBN_END_DATE) > 0
   AND (
           (
               (
               TMD1.LAST_SBN_END_DATE IS NULL
               AND TMD1.LAST_SBN_GYOUSHA_CD IS NULL
               AND TMD1.LAST_SBN_GENBA_CD IS NULL
               )
           AND NOT EXISTS
               ( 
               SELECT * 
               FROM T_MANIFEST_RELATION AS TMR 
               WHERE TMD1.DETAIL_SYSTEM_ID = TMR.FIRST_SYSTEM_ID
                   AND TMR.FIRST_HAIKI_KBN_CD <> 4
                   AND TMR.DELETE_FLG = 'false' 
               )
           )
       OR 
       EXISTS
           ( 
           SELECT * 
           FROM T_MANIFEST_RELATION AS TMR 
           WHERE TMD1.DETAIL_SYSTEM_ID = TMR.FIRST_SYSTEM_ID
               AND TMR.FIRST_HAIKI_KBN_CD <> 4
               AND TMR.DELETE_FLG = 'false' 
           )
       )
/*IF dto.HAIKIBUTSU_KBN.Count != 0 */
    AND TME1.HAIKI_KBN_CD IN /*dto.HAIKIBUTSU_KBN*/(1,2)
/*END*/
/*IF dto.HIDUKESYURUI == '1'*/
    AND TME1.KOUFU_DATE >= /*dto.DATE_FROM*/
    AND TME1.KOUFU_DATE <= /*dto.DATE_TO*/
/*END*/
/*IF dto.HIDUKESYURUI == '2'*/
    AND TMU1.UPN_END_DATE >= /*dto.DATE_FROM*/
    AND TMU1.UPN_END_DATE <= /*dto.DATE_TO*/
/*END*/
/*IF dto.HIDUKESYURUI == '3'*/
    AND TMD1.SBN_END_DATE >= /*dto.DATE_FROM*/
    AND TMD1.SBN_END_DATE <= /*dto.DATE_TO*/
/*END*/
/*IF dto.KYOTEN_CD != null && dto.KYOTEN_CD != '' */
    AND TME1.KYOTEN_CD = /*dto.KYOTEN_CD*/
/*END*/
/*IF dto.SBN_GYOUSHA_CD != null && dto.SBN_GYOUSHA_CD != '' */
    AND TME1.SBN_GYOUSHA_CD = /*dto.SBN_GYOUSHA_CD*/
/*END*/    
/*IF dto.SBN_GENBA_CD != null && dto.SBN_GENBA_CD != '' */
    AND TMU1.UPN_SAKI_GENBA_CD >= /*dto.SBN_GENBA_CD*/
/*END*/
/*IF dto.SBN_GENBA_CD_TO != null && dto.SBN_GENBA_CD_TO != '' */
    AND TMU1.UPN_SAKI_GENBA_CD <= /*dto.SBN_GENBA_CD_TO*/
/*END*/

GROUP BY MHS.HOUKOKUSHO_BUNRUI_CD 
    , MHB.HOUKOKUSHO_BUNRUI_NAME
    , TMD1.SBN_END_DATE 
    , TMD2.SBN_END_DATE 
    , TME1.HAIKI_KBN_CD 
    , TME1.KOUFU_DATE 
    , TME1.HST_GYOUSHA_NAME 
    , TME1.SBN_GYOUSHA_NAME 
    , NEXT_MANIFEST.MANIFEST_ID
    , TME1.MANIFEST_ID
    , MSH.SHOBUN_HOUHOU_NAME_RYAKU 
    , NEXT_MANIFEST.GENBA_NAME_RYAKU 
	, NEXT_MANIFEST.GENBA_NAME1
    , NEXT_MANIFEST.GENBA_NAME2
    , MGENYO.GENNYOURITSU 
    , MU.UNIT_NAME_RYAKU
) AS X 
ORDER BY HAIKI_SHURUI_CD 
    , UKEIRESAKI 
    , SHOBUN_HOUHOU_NAME 
    , MOCHIDASHISAKI
    , SHOBUN_NENGAPPI
