SELECT MHS.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_CD
     , MHB.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_NAME
     , CONVERT(VARCHAR(10), TMD2.SBN_END_DATE, 111) AS SHOBUN_NENGAPPI 
     , CONVERT(VARCHAR(10), TME2.KOUFU_DATE, 111) AS KOUFU_NENGAPPI 
     , TME2.HAIKI_KBN_CD
     , CASE 
           WHEN TME2.HAIKI_KBN_CD = '1' THEN 'ŽY”p(’¼s)' 
           WHEN TME2.HAIKI_KBN_CD = '2' THEN 'Œš”p' 
           WHEN TME2.HAIKI_KBN_CD = '3' THEN 'ŽY”p(Ï‘Ö)' 
           ELSE '' 
       END AS HAIKIBUTU_KBN 
     , TME2.HST_GYOUSHA_NAME AS KOUFUSHAMEI 
     , TME2.SBN_GYOUSHA_NAME AS UKEIRESAKI 
     , SUM(ISNULL(TMD2.KANSAN_SUU, 0)) AS UKEIRERYO 
     , MU.UNIT_NAME_RYAKU AS UKEIRERYO_TANI 
     , TME2.MANIFEST_ID AS KOUFUNO 
     , MSH.SHOBUN_HOUHOU_NAME_RYAKU AS SHOBUN_HOUHOU_NAME 
     , SUM(ISNULL(TMD2.KANSAN_SUU, 0)) AS SHOBUNRYO 
     , MU.UNIT_NAME_RYAKU AS SHOBUNRYO_TANI 
     , TME2.SBN_GYOUSHA_NAME AS UKEIRESAKI_GOUKEI_NAME
     , MU.UNIT_NAME_RYAKU AS UKEIRESAKI_GOUKEI_TANI 
     , MSH.SHOBUN_HOUHOU_NAME_RYAKU AS SHOBUN_HOUHOU_GOUKEI_NAME
     , MU.UNIT_NAME_RYAKU AS SHOBUN_HOUHOU_GOUKEI_TANI 
     , MHS.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_GOUKEI_CD 
     , MHB.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_GOUKEI_NAME 
     , MU.UNIT_NAME_RYAKU AS HAIKI_SHURUI_GOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS UKEIRERYOU_SOUGOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS SHOBUNRYOU_SOUGOUKEI_TANI 

  FROM T_MANIFEST_ENTRY AS TME2
 INNER JOIN T_MANIFEST_UPN AS TMU2 
    ON TME2.SYSTEM_ID = TMU2.SYSTEM_ID 
   AND TME2.SEQ = TMU2.SEQ 
 INNER JOIN ( 
      SELECT TME_SANPAI.SYSTEM_ID 
           , TME_SANPAI.SEQ 
           , MIN(TMU_SANPAI.UPN_ROUTE_NO) AS UPN_ROUTE_NO 
        FROM T_MANIFEST_ENTRY    AS TME_SANPAI 
       INNER JOIN T_MANIFEST_UPN AS TMU_SANPAI 
          ON TME_SANPAI.SYSTEM_ID = TMU_SANPAI.SYSTEM_ID 
         AND TME_SANPAI.SEQ       = TMU_SANPAI.SEQ 
       WHERE TME_SANPAI.DELETE_FLG = 'false' 
         AND TME_SANPAI.HAIKI_KBN_CD IN (1,3) 
         AND TMU_SANPAI.UPN_SAKI_KBN = 1 
       GROUP BY TME_SANPAI.SYSTEM_ID 
           , TME_SANPAI.SEQ 
       UNION 
      SELECT TME_KENPAI.SYSTEM_ID 
           , TME_KENPAI.SEQ 
           , MIN(TMU_KENPAI.UPN_ROUTE_NO) AS UPN_ROUTE_NO 
        FROM T_MANIFEST_ENTRY    AS TME_KENPAI 
       INNER JOIN T_MANIFEST_UPN AS TMU_KENPAI 
          ON TME_KENPAI.SYSTEM_ID = TMU_KENPAI.SYSTEM_ID 
         AND TME_KENPAI.SEQ       = TMU_KENPAI.SEQ 
       WHERE TME_KENPAI.DELETE_FLG = 'false' 
         AND TME_KENPAI.HAIKI_KBN_CD = 2 
       GROUP BY TME_KENPAI.SYSTEM_ID 
           , TME_KENPAI.SEQ 
     ) AS TMU_MAX_ROUTE 
    ON TMU2.SYSTEM_ID = TMU_MAX_ROUTE.SYSTEM_ID 
   AND TMU2.SEQ = TMU_MAX_ROUTE.SEQ 
   AND TMU2.UPN_ROUTE_NO = TMU_MAX_ROUTE.UPN_ROUTE_NO 
 INNER JOIN T_MANIFEST_DETAIL AS TMD2 
    ON TME2.SYSTEM_ID = TMD2.SYSTEM_ID 
   AND TME2.SEQ = TMD2.SEQ 
  INNER JOIN M_GYOUSHA AS MG_LAST_SBN 
    ON TMD2.LAST_SBN_GYOUSHA_CD = MG_LAST_SBN.GYOUSHA_CD 
   AND MG_LAST_SBN.JISHA_KBN = 'true' 
   AND MG_LAST_SBN.SHOBUN_NIOROSHI_GYOUSHA_KBN = 'true' 
  INNER JOIN M_GENBA AS MGEN_LAST_SBN 
    ON TMD2.LAST_SBN_GYOUSHA_CD = MGEN_LAST_SBN.GYOUSHA_CD 
   AND TMD2.LAST_SBN_GENBA_CD = MGEN_LAST_SBN.GENBA_CD 
   AND MGEN_LAST_SBN.SAISHUU_SHOBUNJOU_KBN = 'true' 
 INNER JOIN M_SYS_INFO 
    ON SYS_ID = '0' 
  LEFT OUTER JOIN M_HAIKI_SHURUI AS MHS 
    ON TME2.HAIKI_KBN_CD = MHS.HAIKI_KBN_CD 
   AND TMD2.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
  LEFT OUTER JOIN M_HOUKOKUSHO_BUNRUI AS MHB 
    ON MHS.HOUKOKUSHO_BUNRUI_CD = MHB.HOUKOKUSHO_BUNRUI_CD
  LEFT OUTER JOIN M_SHOBUN_HOUHOU AS MSH 
    ON TMD2.SBN_HOUHOU_CD = MSH.SHOBUN_HOUHOU_CD 
  LEFT OUTER JOIN M_UNIT AS MU 
    ON M_SYS_INFO.MANI_KANSAN_KIHON_UNIT_CD = MU.UNIT_CD 

 WHERE TME2.DELETE_FLG = 'false'
   AND TME2.FIRST_MANIFEST_KBN = 'true' 
/*IF dto.HAIKIBUTSU_KBN.Count != 0 */
    AND TME2.HAIKI_KBN_CD IN /*dto.HAIKIBUTSU_KBN*/(1,2)
/*END*/
/*IF dto.HIDUKESYURUI == '1'*/
   AND TME2.KOUFU_DATE >= /*dto.DATE_FROM*/
   AND TME2.KOUFU_DATE <= /*dto.DATE_TO*/
/*END*/
/*IF dto.HIDUKESYURUI == '2'*/
   AND TMU2.UPN_END_DATE >= /*dto.DATE_FROM*/
   AND TMU2.UPN_END_DATE <= /*dto.DATE_TO*/    
/*END*/
/*IF dto.HIDUKESYURUI == '3'*/ 
   AND TMD2.LAST_SBN_END_DATE >= /*dto.DATE_FROM*/ 
   AND TMD2.LAST_SBN_END_DATE <= /*dto.DATE_TO*/ 
/*END*/    
/*IF dto.KYOTEN_CD != null && dto.KYOTEN_CD != '' */
   AND TME2.KYOTEN_CD = /*dto.KYOTEN_CD*/
/*END*/
/*IF dto.SBN_GYOUSHA_CD != null && dto.SBN_GYOUSHA_CD != '' */
   AND TMD2.LAST_SBN_GYOUSHA_CD = /*dto.SBN_GYOUSHA_CD*/
/*END*/        
/*IF dto.SBN_GENBA_CD != null && dto.SBN_GENBA_CD != '' */
   AND TMD2.LAST_SBN_GENBA_CD >= /*dto.SBN_GENBA_CD*/
/*END*/
/*IF dto.SBN_GENBA_CD_TO != null && dto.SBN_GENBA_CD_TO != '' */
   AND TMD2.LAST_SBN_GENBA_CD <= /*dto.SBN_GENBA_CD_TO*/
/*END*/

 GROUP BY MHS.HOUKOKUSHO_BUNRUI_CD 
     , MHB.HOUKOKUSHO_BUNRUI_NAME
     , TMD2.SBN_END_DATE 
     , TME2.HAIKI_KBN_CD
     , TME2.KOUFU_DATE 
     , TME2.HST_GYOUSHA_NAME 
     , TME2.SBN_GYOUSHA_NAME 
     , TME2.MANIFEST_ID 
     , MSH.SHOBUN_HOUHOU_NAME_RYAKU 
     , MU.UNIT_NAME_RYAKU 

 ORDER BY MHS.HOUKOKUSHO_BUNRUI_CD 
     , TME2.SBN_GYOUSHA_NAME 
     , MSH.SHOBUN_HOUHOU_NAME_RYAKU 
     , TMD2.SBN_END_DATE
