SELECT MHS.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_CD
     , MHB.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_NAME
     , CONVERT(VARCHAR(10), TMU1.UPN_END_DATE, 111) AS ITAKU_NENGAPPI 
     , CONVERT(VARCHAR(10), TME1.KOUFU_DATE, 111) AS KOUFU_NENGAPPI 
     , TME1.HAIKI_KBN_CD
     , CASE 
           WHEN TME1.HAIKI_KBN_CD = '1' THEN 'éYîp(íºçs)' 
           WHEN TME1.HAIKI_KBN_CD = '2' THEN 'åöîp' 
           WHEN TME1.HAIKI_KBN_CD = '3' THEN 'éYîp(êœë÷)' 
           ELSE '' 
       END AS HAIKIBUTU_KBN 
     , TME1.HST_GYOUSHA_NAME AS KOUFUSHAMEI 
     , TME1.MANIFEST_ID AS KOUFUNO 
     , TME1.HST_GENBA_NAME AS UKEIRESAKI 
     , ISNULL(TMD1.KANSAN_SUU, 0) AS UKEIRERYO 
     , MU.UNIT_NAME_RYAKU AS UKEIRERYO_TANI 
     --, TMU1.UPN_SAKI_GENBA_NAME AS UNPANSAKI 
	 ,CASE 
          WHEN TME1.HAIKI_KBN_CD = '2' THEN 
			  CASE --â^î¿ãÊä‘2Ç™Ç»Ç¢èÍçá
				  WHEN (SELECT ISNULL(UPN_TEMP_1.UPN_GYOUSHA_CD,'') FROM T_MANIFEST_UPN UPN_TEMP_1 WHERE UPN_TEMP_1.SYSTEM_ID = TME1.SYSTEM_ID AND UPN_TEMP_1.SEQ = TME1.SEQ AND UPN_TEMP_1.UPN_ROUTE_NO = 2) = '' 
				      THEN TMU1.UPN_SAKI_GENBA_NAME
				  ELSE --â^î¿ãÊä‘2Ç™Ç†ÇÈèÍçá
					  CASE --ãÊä‘2
						  WHEN TMU1.UPN_ROUTE_NO = 2
							  THEN TMU1.UPN_SAKI_GENBA_NAME 
						  ELSE
							  CASE 
							      WHEN (ISNULL(TME1.TMH_GYOUSHA_CD,'')) = ''
								      THEN TMU1.UPN_SAKI_GENBA_NAME
								  ELSE TME1.TMH_GENBA_NAME
						      END 
					  END
			  END
          ELSE TMU1.UPN_SAKI_GENBA_NAME 
      END AS UNPANSAKI

     , ISNULL(TMD1.KANSAN_SUU, 0) AS UNPANRYO 
     , MU.UNIT_NAME_RYAKU AS UNPANRYO_TANI 
     , CASE 
           WHEN TME1.HAIKI_KBN_CD = '1' THEN TME1.TMH_GENBA_NAME 
           WHEN TME1.HAIKI_KBN_CD = '2' THEN TME1.TMH_GENBA_NAME 
		   WHEN TME1.HAIKI_KBN_CD = '3' THEN TMU2.UPN_SAKI_GENBA_NAME
           ELSE '' 
       END AS TUMIKAEHOKAN 
-- 2014.08.12 #1134 MIYA MOD START
--     , TMU1.UPN_HOUHOU_CD AS UNPAN_HOUHOU_CD
     , ISNULL(TMU1.UPN_HOUHOU_CD,'') AS UNPAN_HOUHOU_CD 
-- 2014.08.12 #1134 MIYA MOD END
     , MUH.UNPAN_HOUHOU_NAME_RYAKU AS UNPAN_HOUHOU_NAME 
     , CASE 
           WHEN TME1.HAIKI_KBN_CD = '1' AND TME1.TMH_GENBA_NAME IS NOT NULL AND TME1.TMH_GENBA_NAME <> '' THEN ISNULL(TMD1.KANSAN_SUU,0) 
           WHEN TME1.HAIKI_KBN_CD = '2' AND TME1.TMH_GENBA_NAME IS NOT NULL AND TME1.TMH_GENBA_NAME <> '' THEN ISNULL(TMD1.KANSAN_SUU,0) 
           WHEN TME1.HAIKI_KBN_CD = '3' AND TMU2.UPN_SAKI_GENBA_NAME IS NOT NULL THEN ISNULL(TMD1.KANSAN_SUU,0) 
           ELSE 0 
       END AS HANSHUTURYO 
     , CASE 
           WHEN TME1.HAIKI_KBN_CD = '1'                             THEN MU.UNIT_NAME_RYAKU 
           WHEN TME1.HAIKI_KBN_CD = '2'                             THEN MU.UNIT_NAME_RYAKU 
           WHEN TME1.HAIKI_KBN_CD = '3'								THEN MU.UNIT_NAME_RYAKU
           ELSE '' 
       END AS HANSHUTURYO_TANI 
     --, TMU1.UPN_SAKI_GENBA_NAME AS UNPANSAKI_GOUKEI_NAME 
	 ,CASE 
          WHEN TME1.HAIKI_KBN_CD = '2' THEN 
			  CASE --â^î¿ãÊä‘2Ç™Ç»Ç¢èÍçá
				  WHEN (SELECT ISNULL(UPN_TEMP_1.UPN_GYOUSHA_CD,'') FROM T_MANIFEST_UPN UPN_TEMP_1 WHERE UPN_TEMP_1.SYSTEM_ID = TME1.SYSTEM_ID AND UPN_TEMP_1.SEQ = TME1.SEQ AND UPN_TEMP_1.UPN_ROUTE_NO = 2) = '' 
				      THEN TMU1.UPN_SAKI_GENBA_NAME
				  ELSE --â^î¿ãÊä‘2Ç™Ç†ÇÈèÍçá
					  CASE --ãÊä‘2
						  WHEN TMU1.UPN_ROUTE_NO = 2
							  THEN TMU1.UPN_SAKI_GENBA_NAME 
						  ELSE
							  CASE 
							      WHEN (ISNULL(TME1.TMH_GYOUSHA_CD,'')) = ''
								      THEN TMU1.UPN_SAKI_GENBA_NAME
								  ELSE TME1.TMH_GENBA_NAME
						      END 
					  END
			  END
          ELSE TMU1.UPN_SAKI_GENBA_NAME 
      END AS UNPANSAKI_GOUKEI_NAME
     , TME1.HST_GENBA_NAME AS UKEIRESAKI_GOUKEI_NAME 
     , MU.UNIT_NAME_RYAKU AS UNPANSAKI_GOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS UKEIRESAKI_GOUKEI_TANI 
     , TMU1.UPN_HOUHOU_CD AS UNPAN_HOUHOU_GOUKEI_CD 
     , MUH.UNPAN_HOUHOU_NAME_RYAKU AS UNPAN_HOUHOU_GOUKEI_NAME 
     , MU.UNIT_NAME_RYAKU AS UNPAN_HOUHOU_GOUKEI_TANI 
     , MHS.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_GOUKEI_CD 
     , MHB.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_GOUKEI_NAME 
     , MU.UNIT_NAME_RYAKU AS HAIKI_SHURUI_GOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS UKEIRERYO_SOUGOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS UNPANRYO_SOUGOUKEI_TANI 
     , MU.UNIT_NAME_RYAKU AS HANSHUTURYO_SOUGOUKEI_TANI 
     
  FROM T_MANIFEST_ENTRY AS TME1 
 INNER JOIN T_MANIFEST_UPN AS TMU1 
    ON TME1.SYSTEM_ID = TMU1.SYSTEM_ID 
   AND TME1.SEQ = TMU1.SEQ 
 -- ëOãÊä‘ÇÃÉfÅ[É^
 LEFT JOIN  T_MANIFEST_UPN AS TMU2
    ON TME1.SYSTEM_ID = TMU2.SYSTEM_ID 
   AND TME1.SEQ = TMU2.SEQ	
   AND TMU2.UPN_SAKI_KBN = '2'
   AND TMU2.UPN_ROUTE_NO = (TMU1.UPN_ROUTE_NO - 1)
 INNER JOIN T_MANIFEST_DETAIL AS TMD1 
    ON TME1.SYSTEM_ID = TMD1.SYSTEM_ID 
   AND TME1.SEQ = TMD1.SEQ 
 INNER JOIN M_SYS_INFO 
    ON SYS_ID = '0' 
 INNER JOIN M_GYOUSHA AS MG_UPN 
    ON TMU1.UPN_GYOUSHA_CD = MG_UPN.GYOUSHA_CD 
   AND MG_UPN.JISHA_KBN = 'true' 
   AND MG_UPN.UNPAN_JUTAKUSHA_KAISHA_KBN = 'true' 

 INNER JOIN M_GENBA 
    ON M_GENBA.GYOUSHA_CD = TME1.HST_GYOUSHA_CD
   AND M_GENBA.GENBA_CD   = TME1.HST_GENBA_CD
   AND M_GENBA.JISHA_KBN = 'false' 

  LEFT OUTER JOIN M_UNPAN_HOUHOU AS MUH 
    ON TMU1.UPN_HOUHOU_CD = MUH.UNPAN_HOUHOU_CD 
  LEFT OUTER JOIN M_HAIKI_SHURUI AS MHS 
    ON TME1.HAIKI_KBN_CD = MHS.HAIKI_KBN_CD 
   AND TMD1.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
  LEFT OUTER JOIN M_HOUKOKUSHO_BUNRUI AS MHB 
    ON MHS.HOUKOKUSHO_BUNRUI_CD = MHB.HOUKOKUSHO_BUNRUI_CD
  LEFT OUTER JOIN M_UNIT AS MU 
    ON M_SYS_INFO.MANI_KANSAN_KIHON_UNIT_CD = MU.UNIT_CD 

 WHERE TME1.DELETE_FLG = 'false' 
   AND TMU1.UPN_END_DATE IS NOT NULL
/*IF dto.HAIKIBUTSU_KBN.Count != 0 */
    AND TME1.HAIKI_KBN_CD IN /*dto.HAIKIBUTSU_KBN*/(1,2)
/*END*/
/*IF dto.HIDUKESYURUI == '1'*/ 
   AND TME1.KOUFU_DATE >= /*dto.DATE_FROM*/'2013-01-01' 
   AND TME1.KOUFU_DATE <= /*dto.DATE_TO*/'2023-01-01' 
/*END*/ 
/*IF dto.HIDUKESYURUI == '2'*/ 
   AND TMU1.UPN_END_DATE >= /*dto.DATE_FROM*/'2013-01-01' 
   AND TMU1.UPN_END_DATE <= /*dto.DATE_TO*/'2023-01-01' 
/*END*/ 
/*IF dto.HIDUKESYURUI == '3'*/ 
   AND TMD1.SBN_END_DATE >= /*dto.DATE_FROM*/'2013-01-01' 
   AND TMD1.SBN_END_DATE <= /*dto.DATE_TO*/'2023-01-01' 
/*END*/ 
/*IF dto.KYOTEN_CD != null && dto.KYOTEN_CD != '' */ 
   AND TME1.KYOTEN_CD = /*dto.KYOTEN_CD*/'00' 
/*END*/ 
/*IF dto.SBN_GYOUSHA_CD != null && dto.SBN_GYOUSHA_CD != '' */ 
   AND TMU1.UPN_GYOUSHA_CD = /*dto.SBN_GYOUSHA_CD*/'000000' 
/*END*/ 

 ORDER BY MHS.HOUKOKUSHO_BUNRUI_CD 
-- 2014.08.12 #1134 MIYA MOD START
--     , TMU1.UPN_HOUHOU_CD 
     , ISNULL(TMU1.UPN_HOUHOU_CD,'')
-- 2014.08.12 #1134 MIYA MOD END
     , TME1.SBN_GYOUSHA_CD 
     , TMU1.UPN_SAKI_GENBA_NAME 
     , TME1.KOUFU_DATE 
     , TME1.HAIKI_KBN_CD 
     , TME1.MANIFEST_ID 
     , TMU1.UPN_ROUTE_NO 
     , TMD1.DETAIL_SYSTEM_ID  
