SELECT 
       MDHS.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_CD
     , MHB.HOUKOKUSHO_BUNRUI_NAME_RYAKU AS HAIKI_SHURUI_NAME
     , CASE WHEN ISDATE(DR182.HIKIWATASHI_DATE) > 0 THEN CONVERT(VARCHAR(10), CONVERT(DATETIME, DR182.HIKIWATASHI_DATE), 111) 
            ELSE NULL 
       END AS ITAKU_NENGAPPI 
     , CONVERT(smallint, 4) AS HAIKI_KBN_CD
     , '電子' AS HAIKIBUTU_KBN 
     , CASE WHEN ISNULL(DR132.LAST_SBN_JOU_NAME, '') = ISNULL(DR192.UPNSAKI_JOU_NAME, '')
                 AND ( ( ISNULL(DR132.LAST_SBN_JOU_ADDRESS1, '') + ISNULL(DR132.LAST_SBN_JOU_ADDRESS2, '') + ISNULL(DR132.LAST_SBN_JOU_ADDRESS3, '') + ISNULL(DR132.LAST_SBN_JOU_ADDRESS4, '') )
                        = ( ISNULL(DR192.UPNSAKI_JOU_ADDRESS1, '') + ISNULL(DR192.UPNSAKI_JOU_ADDRESS2, '') + ISNULL(DR192.UPNSAKI_JOU_ADDRESS3, '') + ISNULL(DR192.UPNSAKI_JOU_ADDRESS4, '') ) )
            THEN
                CASE WHEN ( DR182.HAIKI_DAI_CODE + DR182.HAIKI_CHU_CODE + DR182.HAIKI_SHO_CODE ) < '7000' THEN MCK_SAISHU.FUTSUU_KYOKA_NO 
                    WHEN ( DR182.HAIKI_DAI_CODE + DR182.HAIKI_CHU_CODE + DR182.HAIKI_SHO_CODE ) >= '7000' THEN MCK_SAISHU.TOKUBETSU_KYOKA_NO 
                    ELSE ' ' 
                END
            ELSE
                CASE WHEN ( DR182.HAIKI_DAI_CODE + DR182.HAIKI_CHU_CODE + DR182.HAIKI_SHO_CODE ) < '7000' THEN MCK.FUTSUU_KYOKA_NO 
                    WHEN ( DR182.HAIKI_DAI_CODE + DR182.HAIKI_CHU_CODE + DR182.HAIKI_SHO_CODE ) >= '7000' THEN MCK.TOKUBETSU_KYOKA_NO 
                    ELSE ' ' 
                END
       END AS KYOKANO 
    , DR19EX2.UPNSAKI_GYOUSHA_CD AS JUTAKUSHA_GYOUSHA_CD
    , DR19EX2.UPNSAKI_GENBA_CD AS JUTAKUSHA_GENBA_CD
     , DR192.UPNSAKI_JOU_NAME AS JUTAKUSHAMEI
     , ISNULL(DR192.UPNSAKI_JOU_ADDRESS1, '') + ISNULL(DR192.UPNSAKI_JOU_ADDRESS2, '') + ISNULL(DR192.UPNSAKI_JOU_ADDRESS3, '') + ISNULL(DR192.UPNSAKI_JOU_ADDRESS4, '') AS JUTAKUSHA_ADDRESS
     , CASE WHEN ISDATE(DR182.HIKIWATASHI_DATE) > 0 THEN CONVERT(VARCHAR(10), CONVERT(DATETIME, DR182.HIKIWATASHI_DATE), 111) 
            ELSE NULL 
       END AS KOUFU_NENGAPPI2 
     , DR182.MANIFEST_ID AS KOUFUNO2 
     , FIRST_MANIFEST.KOUFUSHAMEI AS KOUFUSHAMEI 
     , FIRST_MANIFEST.KOUFU_NENGAPPI AS KOUFU_NENGAPPI 
     , FIRST_MANIFEST.KOUFUNO AS KOUFUNO 
     , MSH.SHOBUN_HOUHOU_NAME_RYAKU AS ITAKUNAIYOU 
     , ISNULL(FIRST_MANIFEST.GENNYOU_SUU, 0) AS ITAKURYO 
     , MU.UNIT_NAME_RYAKU AS ITAKURYO_TANI 
     , DR192.UPNSAKI_JOU_NAME AS JUTAKUSHAMEI_GOUKEI_NAME
     , MU.UNIT_NAME_RYAKU AS JUTAKUSHA_GOUKEI_ITAKURYOU_TANI 
     , MDHS.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_GOUKEI_CD 
     , MHB.HOUKOKUSHO_BUNRUI_NAME_RYAKU AS HAIKI_SHURUI_GOUKEI_NAME 
     , MU.UNIT_NAME_RYAKU AS HAIKI_SHURUI_GOUKEI_ITAKURYOU_TANI 
     , MU.UNIT_NAME_RYAKU AS SOUGOUKEI_ITAKURYOU_TANI 

  FROM DT_MF_TOC AS DMT2 
 INNER JOIN DT_R18 AS DR182 
    ON DMT2.KANRI_ID = DR182.KANRI_ID 
   AND DMT2.LATEST_SEQ = DR182.SEQ 
 INNER JOIN DT_R19 AS DR192 
    ON DR182.KANRI_ID = DR192.KANRI_ID 
   AND DR182.SEQ = DR192.SEQ 
   AND DR182.UPN_ROUTE_CNT = DR192.UPN_ROUTE_NO 
 INNER JOIN DT_R19 AS DR192_1 
    ON DR182.KANRI_ID = DR192_1.KANRI_ID 
   AND DR182.SEQ = DR192_1.SEQ 
   AND DR192_1.UPN_ROUTE_NO = '1' 
 INNER JOIN DT_R13 AS DR132 
    ON DR182.KANRI_ID = DR132.KANRI_ID 
   AND DR182.SEQ = DR132.SEQ 
   AND DR182.LAST_SBN_CNT = DR132.REC_SEQ 
 INNER JOIN DT_R18_EX AS DR18EX2 
    ON DR182.KANRI_ID = DR18EX2.KANRI_ID 
   AND DR18EX2.DELETE_FLG = 'false' 
 INNER JOIN DT_R19_EX AS DR19EX2 
    ON DR192.KANRI_ID = DR19EX2.KANRI_ID 
   AND DR192.UPN_ROUTE_NO = DR19EX2.UPN_ROUTE_NO 
   AND DR19EX2.DELETE_FLG = 'false' 
 LEFT JOIN DT_R13_EX AS DR13EX2 
    ON DR132.KANRI_ID = DR13EX2.KANRI_ID 
   AND DR132.REC_SEQ = DR13EX2.REC_SEQ 
   AND DR13EX2.DELETE_FLG = 'false' 
 INNER JOIN M_SYS_INFO 
    ON SYS_ID = '0' 
 INNER JOIN M_GYOUSHA AS MG_HST 
    ON DR18EX2.HST_GYOUSHA_CD = MG_HST.GYOUSHA_CD 
   AND MG_HST.JISHA_KBN = 'true' 
   AND MG_HST.HAISHUTSU_NIZUMI_GYOUSHA_KBN = 'true' 
 LEFT JOIN M_GYOUSHA AS MG_LAST_SBN 
    ON DR13EX2.LAST_SBN_GYOUSHA_CD = MG_LAST_SBN.GYOUSHA_CD 
   AND MG_LAST_SBN.JISHA_KBN = 'false' 
   AND MG_LAST_SBN.SHOBUN_NIOROSHI_GYOUSHA_KBN = 'true' 
--// 20140619 syunrei EV004818_最終処分委託帳簿の条件変更 start
 --INNER JOIN T_MANIFEST_RELATION AS TMR 
 LEFT OUTER JOIN T_MANIFEST_RELATION AS TMR 
--// 20140619 syunrei EV004818_最終処分委託帳簿の条件変更 end 
    ON DR18EX2.SYSTEM_ID = TMR.NEXT_SYSTEM_ID 
   AND TMR.NEXT_HAIKI_KBN_CD = '4' 
   AND TMR.DELETE_FLG = 'false' 
 INNER JOIN (
      SELECT TMD1.DETAIL_SYSTEM_ID AS FIRST_SYSTEM_ID 
           , TME1.HAIKI_KBN_CD AS FIRST_HAIKI_KBN_CD
           , TME1.MANIFEST_ID AS KOUFUNO 
           , TME1.HST_GYOUSHA_NAME AS KOUFUSHAMEI 
           , CONVERT(VARCHAR(10), TME1.KOUFU_DATE, 111) AS KOUFU_NENGAPPI 
		   , TMD1.GENNYOU_SUU
        FROM T_MANIFEST_ENTRY AS TME1 
       INNER JOIN T_MANIFEST_DETAIL AS TMD1 
          ON TME1.SYSTEM_ID = TMD1.SYSTEM_ID 
         AND TME1.SEQ = TMD1.SEQ 
       WHERE TME1.DELETE_FLG = 'false' 
	     --#143033対応時、出力条件を削除（過去チケットではペンディング状態）…再度修正する可能性あり
         --AND ISNULL(TMD1.LAST_SBN_END_DATE, '') <> ''
         --AND ISNULL(TMD1.LAST_SBN_GYOUSHA_CD, '') <> ''
         --AND ISNULL(TMD1.LAST_SBN_GENBA_CD, '') <> ''
       UNION 
      SELECT DR18EX1.SYSTEM_ID AS FIRST_SYSTEM_ID 
           , 4 AS FIRST_HAIKI_KBN_CD
           , DR181.MANIFEST_ID AS KOUFUNO 
           , DR181.HST_SHA_NAME AS KOUFUSHAMEI 
           , CASE WHEN ISDATE(DR181.HIKIWATASHI_DATE) > 0 THEN CONVERT(VARCHAR(10), CONVERT(DATETIME, DR181.HIKIWATASHI_DATE), 111) 
                  ELSE NULL 
             END AS KOUFU_NENGAPPI 
		   , DR18EX1.GENNYOU_SUU
        FROM (
                SELECT 
                       (CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN DT_R18_MIX.DETAIL_SYSTEM_ID ELSE DT_R18_EX.SYSTEM_ID END) AS SYSTEM_ID
                    ,DT_R18_EX.KANRI_ID
					, (CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN DT_R18_MIX.GENNYOU_SUU ELSE DT_R18_EX.GENNYOU_SUU END) AS GENNYOU_SUU
                FROM DT_R18_EX
                LEFT JOIN (SELECT * FROM DT_R18_MIX WHERE DELETE_FLG = 0) AS DT_R18_MIX ON
                DT_R18_EX.SYSTEM_ID = DT_R18_MIX.SYSTEM_ID
                WHERE DT_R18_EX.DELETE_FLG = 0
            ) AS DR18EX1 
       INNER JOIN DT_MF_TOC AS DMT1 
          ON DR18EX1.KANRI_ID = DMT1.KANRI_ID 
       INNER JOIN DT_R18 AS DR181 
          ON DMT1.KANRI_ID = DR181.KANRI_ID 
         AND DMT1.LATEST_SEQ = DR181.SEQ 
       --#143033対応時、出力条件を削除
       --WHERE DR181.LAST_SBN_ENDREP_FLAG = 1
     ) AS FIRST_MANIFEST
    ON TMR.FIRST_SYSTEM_ID = FIRST_MANIFEST.FIRST_SYSTEM_ID 
    AND FIRST_MANIFEST.FIRST_HAIKI_KBN_CD = TMR.FIRST_HAIKI_KBN_CD
/*IF dto.HIDUKESYURUI == '2'*/
LEFT JOIN (
			SELECT R19M.KANRI_ID, R19M.SEQ, R19M.UPN_ROUTE_NO, MAX(Other_KUKAN.UPN_ROUTE_NO) AS 表示日付区間
			FROM DT_MF_TOC 
			INNER JOIN DT_R19 AS R19M ON DT_MF_TOC.KANRI_ID = R19M.KANRI_ID AND DT_MF_TOC.LATEST_SEQ = R19M.SEQ
			LEFT JOIN (
					SELECT R18.KANRI_ID, R18.SEQ, UPN_ROUTE_NO 
					FROM DT_MF_TOC toc
					LEFT JOIN DT_R18 R18 on toc.KANRI_ID = R18.KANRI_ID AND toc.LATEST_SEQ = R18.SEQ
					LEFT JOIN DT_R19 R19 on R18.KANRI_ID = R19.KANRI_ID AND R18.SEQ = R19.SEQ AND R18.HST_SHA_EDI_MEMBER_ID != R19.UPN_SHA_EDI_MEMBER_ID
                    UNION 
					SELECT R18.KANRI_ID, R18.SEQ, 0 AS UPN_ROUTE_NO 
					FROM DT_MF_TOC toc
					LEFT JOIN DT_R18 R18 on toc.KANRI_ID = R18.KANRI_ID AND toc.LATEST_SEQ = R18.SEQ
			) AS Other_KUKAN
			ON R19M.KANRI_ID = Other_KUKAN.KANRI_ID AND R19M.SEQ = Other_KUKAN.SEQ AND R19M.UPN_ROUTE_NO >= Other_KUKAN.UPN_ROUTE_NO
			GROUP BY R19M.KANRI_ID, R19M.SEQ, R19M.UPN_ROUTE_NO
 ) Other_KUKAN_F
 ON DR192.KANRI_ID = Other_KUKAN_F.KANRI_ID AND DR192.SEQ = Other_KUKAN_F.SEQ AND DR192.UPN_ROUTE_NO = Other_KUKAN_F.UPN_ROUTE_NO
 LEFT JOIN (
			SELECT R19U.KANRI_ID, R19U.SEQ, R19U.UPN_ROUTE_NO, R19U.UPN_END_DATE
			FROM DT_MF_TOC toc INNER JOIN DT_R19 R19U ON toc.KANRI_ID = R19U.KANRI_ID AND toc.LATEST_SEQ = R19U.SEQ
			UNION 
			SELECT R18U.KANRI_ID, R18U.SEQ, 0 AS UPN_ROUTE_NO, R18U.HIKIWATASHI_DATE AS UPN_END_DATE
			FROM DT_MF_TOC toc INNER JOIN DT_R18 R18U ON toc.KANRI_ID = R18U.KANRI_ID AND toc.LATEST_SEQ = R18U.SEQ
 ) ROUTE_DATA 
 ON Other_KUKAN_F.KANRI_ID = ROUTE_DATA.KANRI_ID and Other_KUKAN_F.SEQ = ROUTE_DATA.SEQ and Other_KUKAN_F.表示日付区間 = ROUTE_DATA.UPN_ROUTE_NO
/*END*/ 
  LEFT OUTER JOIN M_SHOBUN_HOUHOU AS MSH 
    ON DR18EX2.SBN_HOUHOU_CD = MSH.SHOBUN_HOUHOU_CD 
  LEFT OUTER JOIN M_DENSHI_HAIKI_SHURUI AS MDHS 
    ON DR182.HAIKI_DAI_CODE = SUBSTRING(MDHS.HAIKI_SHURUI_CD,1,2) 
   AND DR182.HAIKI_CHU_CODE = SUBSTRING(MDHS.HAIKI_SHURUI_CD,3,1) 
   AND DR182.HAIKI_SHO_CODE = SUBSTRING(MDHS.HAIKI_SHURUI_CD,4,1) 
  LEFT OUTER JOIN M_HOUKOKUSHO_BUNRUI AS MHB 
    ON MDHS.HOUKOKUSHO_BUNRUI_CD = MHB.HOUKOKUSHO_BUNRUI_CD
  LEFT JOIN M_GENBA AS GENBA_UPNSAKI
    ON DR19EX2.UPNSAKI_GYOUSHA_CD = GENBA_UPNSAKI.GYOUSHA_CD 
   AND DR19EX2.UPNSAKI_GENBA_CD = GENBA_UPNSAKI.GENBA_CD 
  LEFT OUTER JOIN M_CHIIKIBETSU_KYOKA AS MCK 
    ON GENBA_UPNSAKI.GYOUSHA_CD = MCK.GYOUSHA_CD 
   AND GENBA_UPNSAKI.GENBA_CD = MCK.GENBA_CD 
   AND GENBA_UPNSAKI.CHIIKI_CD = MCK.CHIIKI_CD 
   AND MCK.KYOKA_KBN = '2' 
  LEFT OUTER JOIN M_CHIIKIBETSU_KYOKA AS MCK_SAISHU 
    ON GENBA_UPNSAKI.GYOUSHA_CD = MCK_SAISHU.GYOUSHA_CD 
   AND GENBA_UPNSAKI.GENBA_CD = MCK_SAISHU.GENBA_CD 
   AND GENBA_UPNSAKI.CHIIKI_CD = MCK_SAISHU.CHIIKI_CD 
   AND MCK_SAISHU.KYOKA_KBN = '3' 
  LEFT OUTER JOIN M_UNIT AS MU 
    ON M_SYS_INFO.MANI_KANSAN_KIHON_UNIT_CD = MU.UNIT_CD 
	 --// 20140619 syunrei EV004818_最終処分委託帳簿の条件変更 start
 
 INNER JOIN M_GYOUSHA AS GS_NAME
    ON DR18EX2.SBN_GYOUSHA_CD = GS_NAME.GYOUSHA_CD 
 INNER JOIN M_GENBA AS GB_NAME
    ON DR18EX2.SBN_GYOUSHA_CD = GB_NAME.GYOUSHA_CD 
   AND DR18EX2.SBN_GENBA_CD = GB_NAME.GENBA_CD 
 --// 20140619 syunrei EV004818_最終処分委託帳簿の条件変更 end
 WHERE 
 --// 20140619 syunrei EV004818_最終処分委託帳簿の条件変更 start
 --( DR182.FIRST_MANIFEST_FLAG <> '' OR DR182.FIRST_MANIFEST_FLAG IS NOT NULL ) 
  DMT2.STATUS_FLAG = 4 
 --// 20140619 syunrei EV004818_最終処分委託帳簿の条件変更 end

/*IF dto.HIDUKESYURUI == '1'*/ 
   AND DR182.HIKIWATASHI_DATE IS NOT NULL 
   AND DR182.HIKIWATASHI_DATE <> '' 
   AND DR182.HIKIWATASHI_DATE <> '0' 
   AND CONVERT(DATETIME,DR182.HIKIWATASHI_DATE) >= /*dto.DATE_FROM*/ 
   AND CONVERT(DATETIME,DR182.HIKIWATASHI_DATE) <= /*dto.DATE_TO*/ 
/*END*/ 
/*IF dto.HIDUKESYURUI == '2'*/ 
   AND ROUTE_DATA.UPN_END_DATE IS NOT NULL 
   AND ROUTE_DATA.UPN_END_DATE <> '' 
   AND ROUTE_DATA.UPN_END_DATE <> '0' 
   AND CONVERT(DATETIME,ROUTE_DATA.UPN_END_DATE) >= /*dto.DATE_FROM*/ 
   AND CONVERT(DATETIME,ROUTE_DATA.UPN_END_DATE) <= /*dto.DATE_TO*/ 
/*END*/ 
/*IF dto.HIDUKESYURUI == '3'*/ 
   AND DR182.SBN_END_DATE IS NOT NULL 
   AND DR182.SBN_END_DATE <> '' 
   AND DR182.SBN_END_DATE <> '0' 
   AND CONVERT(DATETIME,DR182.SBN_END_DATE) >= /*dto.DATE_FROM*/ 
   AND CONVERT(DATETIME,DR182.SBN_END_DATE) <= /*dto.DATE_TO*/ 
/*END*/ 
/*IF dto.SBN_GYOUSHA_CD != null && dto.SBN_GYOUSHA_CD != '' */ 
   AND DR18EX2.HST_GYOUSHA_CD = /*dto.SBN_GYOUSHA_CD*/ 
/*END*/ 
/*IF dto.SBN_GENBA_CD != null && dto.SBN_GENBA_CD != '' */
   AND DR18EX2.HST_GENBA_CD >= /*dto.SBN_GENBA_CD*/ 
/*END*/ 
/*IF dto.SBN_GENBA_CD_TO != null && dto.SBN_GENBA_CD_TO != '' */
   AND DR18EX2.HST_GENBA_CD <= /*dto.SBN_GENBA_CD_TO*/ 
/*END*/ 

ORDER BY MDHS.HOUKOKUSHO_BUNRUI_CD 
    , DR19EX2.UPNSAKI_GYOUSHA_CD
    , DR19EX2.UPNSAKI_GENBA_CD
    , KOUFU_NENGAPPI2 
    , DR182.MANIFEST_ID 
