SELECT
M_CONTENA.*,
M_CONTENA_SHURUI.CONTENA_SHURUI_NAME_RYAKU,
M_GENBA.GENBA_NAME_RYAKU,
M_GYOUSHA.GYOUSHA_NAME_RYAKU
FROM
M_CONTENA INNER JOIN M_CONTENA_SHURUI ON 
M_CONTENA.CONTENA_SHURUI_CD = M_CONTENA_SHURUI.CONTENA_SHURUI_CD
LEFT JOIN M_GENBA ON 
M_CONTENA.GENBA_CD = M_GENBA.GENBA_CD 
AND M_CONTENA.GYOUSHA_CD = M_GENBA.GYOUSHA_CD 
LEFT JOIN M_GYOUSHA 
ON M_CONTENA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD

WHERE
1=1
 /*IF data.GYOUSHA_CD != null*/ AND M_CONTENA.GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/
 /*IF data.GENBA_CD != null*/ AND M_CONTENA.GENBA_CD = /*data.GENBA_CD*//*END*/
 /*IF data.CONTENA_CD != null*/ AND M_CONTENA.CONTENA_CD = /*data.CONTENA_CD*//*END*/
 /*IF data.CONTENA_SHURUI_CD != null*/ AND M_CONTENA.CONTENA_SHURUI_CD = /*data.CONTENA_SHURUI_CD*//*END*/
