SELECT
M_GYOUSHA.GYOUSHA_CD,
M_GYOUSHA.GYOUSHA_NAME_RYAKU,
M_GENBA.GENBA_CD,
M_GENBA.GENBA_NAME_RYAKU
FROM
M_GYOUSHA INNER JOIN M_GENBA ON 
M_GYOUSHA.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
WHERE
1=1
 /*IF data.GYOUSHA_CD != ''*/ AND M_GYOUSHA.GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/
 /*IF data.GENBA_CD != ''*/ AND M_GENBA.GENBA_CD = /*data.GENBA_CD*//*END*/