SELECT 
    HAI.*
FROM 
    dbo.M_DENSHI_HAIKI_SHURUI_SAIBUNRUI HAI
WHERE HAI.EDI_MEMBER_ID = /*data.EDI_MEMBER_ID*/'0000001'
  AND HAI.HAIKI_SHURUI_CD = /*data.HAIKI_SHURUI_CD*/'0001'
  AND HAI.HAIKI_SHURUI_SAIBUNRUI_CD = /*data.HAIKI_SHURUI_SAIBUNRUI_CD*/'001'
ORDER BY HAI.EDI_MEMBER_ID, HAI.HAIKI_SHURUI_CD, HAI.HAIKI_SHURUI_SAIBUNRUI_CD
