SELECT 
MCN.DELETE_FLG,
MCN.COURSE_NAME_CD,
MCN.COURSE_NAME,
MCN.COURSE_NAME_RYAKU,
MCN.COURSE_NAME_FURIGANA,
MCN.KYOTEN_CD,
MKT.KYOTEN_NAME_RYAKU,
MCN.MONDAY,
MCN.TUESDAY,
MCN.WEDNESDAY,
MCN.THURSDAY,
MCN.FRIDAY,
MCN.SATURDAY,
MCN.SUNDAY,
MCN.COURSE_NAME_BIKOU,
MCN.CREATE_USER,
MCN.CREATE_DATE,
MCN.CREATE_PC,
MCN.UPDATE_USER,
MCN.UPDATE_DATE,
MCN.UPDATE_PC,
MCN.TIME_STAMP
FROM 
M_COURSE_NAME MCN 
LEFT JOIN M_KYOTEN MKT
ON MCN.KYOTEN_CD = MKT.KYOTEN_CD
/*BEGIN*/WHERE
/*IF !data.DELETE_FLG.IsNull*/
AND MCN.DELETE_FLG = /*data.DELETE_FLG*/
/*END*/
/*IF data.COURSE_NAME_CD != null && data.COURSE_NAME_CD != ''*/
AND MCN.COURSE_NAME_CD LIKE '%' + /*data.COURSE_NAME_CD*/ + '%'
/*END*/
/*IF data.COURSE_NAME != null && data.COURSE_NAME != ''*/
AND MCN.COURSE_NAME LIKE '%' +  /*data.COURSE_NAME*/ + '%'
/*END*/
/*IF data.COURSE_NAME_RYAKU != null && data.COURSE_NAME_RYAKU != ''*/
AND MCN.COURSE_NAME_RYAKU LIKE '%' +  /*data.COURSE_NAME_RYAKU*/ + '%'
/*END*/
/*IF data.COURSE_NAME_FURIGANA != null && data.COURSE_NAME_FURIGANA != ''*/
AND MCN.COURSE_NAME_FURIGANA LIKE '%' +  /*data.COURSE_NAME_FURIGANA*/ + '%'
/*END*/
/*IF data.KYOTEN_CD != null && data.KYOTEN_CD != ''*/
AND MCN.KYOTEN_CD LIKE '%' +  /*data.KYOTEN_CD*/ + '%'
/*END*/
/*IF data.KYOTEN_NAME_RYAKU != null && data.KYOTEN_NAME_RYAKU != ''*/
AND MKT.KYOTEN_NAME_RYAKU LIKE '%' +  /*data.KYOTEN_NAME_RYAKU*/ + '%'
/*END*/
/*IF !data.MONDAY.IsNull*/
AND MCN.MONDAY = /*data.MONDAY*/
/*END*/
/*IF !data.TUESDAY.IsNull*/
AND MCN.TUESDAY = /*data.TUESDAY*/
/*END*/
/*IF !data.WEDNESDAY.IsNull*/
AND MCN.WEDNESDAY = /*data.WEDNESDAY*/
/*END*/
/*IF !data.THURSDAY.IsNull*/
AND MCN.THURSDAY = /*data.THURSDAY*/
/*END*/
/*IF !data.FRIDAY.IsNull*/
AND MCN.FRIDAY = /*data.FRIDAY*/
/*END*/
/*IF !data.SATURDAY.IsNull*/
AND MCN.SATURDAY = /*data.SATURDAY*/
/*END*/
/*IF !data.SUNDAY.IsNull*/
AND MCN.SUNDAY = /*data.SUNDAY*/
/*END*/
/*IF data.COURSE_NAME_BIKOU != null && data.COURSE_NAME_BIKOU != ''*/
AND MCN.COURSE_NAME_BIKOU LIKE '%' +  /*data.COURSE_NAME_BIKOU*/ + '%'
/*END*/
/*IF data.CREATE_USER != null && data.CREATE_USER != ''*/
AND MCN.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'
/*END*/
/*IF data.CREATE_DATE != null && data.CREATE_DATE != ''*/
AND CONVERT(nvarchar, MCN.CREATE_DATE, 120) LIKE '%' +  /*data.CREATE_DATE*/ + '%'
/*END*/
/*IF data.UPDATE_USER != null && data.UPDATE_USER != ''*/
AND MCN.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'
/*END*/
/*IF data.UPDATE_DATE != null && data.UPDATE_DATE != ''*/
AND CONVERT(nvarchar, MCN.UPDATE_DATE, 120) LIKE '%' +  /*data.UPDATE_DATE*/ + '%'
/*END*/
/*IF !deletechuFlg*/AND MCN.DELETE_FLG = /*deletechuFlg*/0/*END*/
/*END*/
ORDER BY MCN.COURSE_NAME_CD
