SELECT *
  FROM M_CHIIKIBETSU_GYOUSHU
 WHERE CHIIKI_CD = /*CHIIKI_CD*/''
   AND GYOUSHU_CD = (SELECT GYOUSHU_CD FROM M_GYOUSHA WHERE GYOUSHA_CD = /*GYOUSHA_CD*/'')
   AND CONVERT(DATE, ISNULL(TEKIYOU_BEGIN, DATEADD(day,-1,GETDATE()))) <= CONVERT(DATE, GETDATE()) and CONVERT(DATE, GETDATE()) <= CONVERT(DATE, ISNULL(TEKIYOU_END, DATEADD(day,1,GETDATE())))
   AND DELETE_FLG = 0