WITH MANI AS 
(SELECT TME.SYSTEM_ID,
       TME.SEQ,
       TMD.DETAIL_SYSTEM_ID,
       NULL AS KANRI_ID,
       NULL AS DEN_SEQ,
       TME.MANIFEST_ID,
	   TME.FIRST_MANIFEST_KBN,
       TME.HAIKI_KBN_CD,
       MHS.HOUKOKUSHO_BUNRUI_CD,
       TMD.HAIKI_SHURUI_CD,
       MHS.HAIKI_SHURUI_NAME,
       TME.HST_GYOUSHA_CD,
       TME.HST_GENBA_CD,
       TMD.KANSAN_SUU AS JYUTAKU_RYOU,
       TMD.SBN_HOUHOU_CD,
       1 AS LAST_UPN_ROUTE_FLAG,
       UPN.UPN_SAKI_GYOUSHA_CD AS SBN_GYOUSHA_CD,
       UPN.UPN_SAKI_GENBA_CD AS SBN_GENBA_CD,
       /*IF data.TUMIKAE_HOKAN_KBN == 1*/
       UPN.UPN_SAKI_GYOUSHA_CD,
       UPN.UPN_SAKI_GENBA_CD,
       /*END*/
       NULL AS UPN_ROUTE_NO,
       NULL AS UPN_JYUTAKUSHA_CD,
       TMD.KANSAN_SUU AS UPN_RYOU,
       UPN.UPN_SAKI_GYOUSHA_CD AS HIKIWATASHISAKI_CD,
       TMD.KANSAN_SUU AS HIKIWATASHI_RYOU
FROM T_MANIFEST_ENTRY TME
LEFT JOIN T_MANIFEST_UPN UPN
       ON TME.SYSTEM_ID    = UPN.SYSTEM_ID
      AND TME.SEQ          = UPN.SEQ
LEFT JOIN T_MANIFEST_DETAIL TMD
       ON TME.SYSTEM_ID = TMD.SYSTEM_ID
      AND TME.SEQ       = TMD.SEQ
LEFT JOIN M_HAIKI_SHURUI MHS
       ON TME.HAIKI_KBN_CD    = MHS.HAIKI_KBN_CD
      AND TMD.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
--LEFT JOIN M_GENBA HWS_GENBA
       --ON UPN.UPN_SAKI_GYOUSHA_CD = HWS_GENBA.GYOUSHA_CD
      --AND UPN.UPN_SAKI_GENBA_CD   = HWS_GENBA.GENBA_CD
--LEFT JOIN M_CHIIKI HSW_MC
       --ON HSW_MC.CHIIKI_CD = HWS_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD
WHERE TME.DELETE_FLG  = 0
   AND TME.HAIKI_KBN_CD = 1
   AND 
   /*IF data.HAIKIBUTU_KBN == 1*/
   TMD.HAIKI_SHURUI_CD BETWEEN '0000' AND '6999'
   /*END*/
   /*IF data.HAIKIBUTU_KBN == 2*/
   TMD.HAIKI_SHURUI_CD BETWEEN '7000' AND '9999'
   /*END*/
   AND UPN.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
   AND UPN.UPN_END_DATE >= /*data.DATE_FROM*/''
   AND UPN.UPN_END_DATE  <= /*data.DATE_TO*/''
   
UNION ALL

SELECT TME.SYSTEM_ID,
       TME.SEQ,
       TMD.DETAIL_SYSTEM_ID,
       NULL AS KANRI_ID,
       NULL AS DEN_SEQ,
       TME.MANIFEST_ID,
	   TME.FIRST_MANIFEST_KBN,
       TME.HAIKI_KBN_CD,
       MHS.HOUKOKUSHO_BUNRUI_CD,
       TMD.HAIKI_SHURUI_CD,
       MHS.HAIKI_SHURUI_NAME,
       TME.HST_GYOUSHA_CD,
	   TME.HST_GENBA_CD,
	   TMD.KANSAN_SUU AS JYUTAKU_RYOU,
       TMD.SBN_HOUHOU_CD,
/*IF data.TUMIKAE_HOKAN_KBN == 1*/
       1 AS LAST_UPN_ROUTE_FLAG,
        CASE WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = 1
            THEN UPN1.UPN_SAKI_GYOUSHA_CD
        WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = 2
            THEN UPN2.UPN_SAKI_GYOUSHA_CD
        END AS SBN_GYOUSHA_CD,
        CASE WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = 1
            THEN UPN1.UPN_SAKI_GENBA_CD
        WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = 2
            THEN UPN2.UPN_SAKI_GENBA_CD
        END AS SBN_GENBA_CD,

        CASE WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = 1
            THEN UPN1.UPN_SAKI_GYOUSHA_CD
        WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = 2
            THEN CASE WHEN UPN2_UPN_GYOUSHA.JISHA_KBN = 1
                THEN UPN2.UPN_SAKI_GYOUSHA_CD
            WHEN UPN1_UPN_GYOUSHA.JISHA_KBN = 1
                THEN TME.TMH_GYOUSHA_CD
            END
        END AS UPN_SAKI_GYOUSHA_CD,

        CASE WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = 1
            THEN UPN1.UPN_SAKI_GENBA_CD
        WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = 2
            THEN CASE WHEN UPN2_UPN_GYOUSHA.JISHA_KBN = 1
                THEN UPN2.UPN_SAKI_GENBA_CD
            WHEN UPN1_UPN_GYOUSHA.JISHA_KBN = 1
                THEN TME.TMH_GENBA_CD
            END 
        END AS UPN_SAKI_GENBA_CD,
/*END*/
/*IF data.TUMIKAE_HOKAN_KBN == 2*/
       CASE UPN_ALL_ROUTE.UPN_ROUTE_NO
            WHEN 2 THEN 1
            ELSE 0 END AS LAST_UPN_ROUTE_FLAG,
	   CASE WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = 1
	        THEN TME.TMH_GYOUSHA_CD
			WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = 2
			THEN UPN2.UPN_SAKI_GYOUSHA_CD
		END AS SBN_GYOUSHA_CD,

		CASE WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = 1
	        THEN TME.TMH_GENBA_CD
			WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = 2
			THEN UPN2.UPN_SAKI_GENBA_CD
		END AS SBN_GENBA_CD,
/*END*/
       --UPN.UPN_END_DATE,
/*IF data.TUMIKAE_HOKAN_KBN == 1*/
       NULL AS UPN_ROUTE_NO,
       NULL AS UPN_JYUTAKUSHA_CD,
/*END*/
/*IF data.TUMIKAE_HOKAN_KBN == 2*/
      UPN_ALL_ROUTE.UPN_ROUTE_NO AS UPN_ROUTE_NO,
	  UPN_ALL_ROUTE.UPN_GYOUSHA_CD AS UPN_JYUTAKUSHA_CD,
/*END*/
       TMD.KANSAN_SUU AS UPN_RYOU,
/*IF data.TUMIKAE_HOKAN_KBN == 1*/
       UPN1.UPN_SAKI_GYOUSHA_CD AS HIKIWATASHISAKI_CD,
/*END*/
/*IF data.TUMIKAE_HOKAN_KBN == 2*/
	   CASE WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = 1
	        THEN UPN2.UPN_GYOUSHA_CD
			WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = 2
			THEN UPN2.UPN_SAKI_GYOUSHA_CD
       END AS HIKIWATASHISAKI_CD,
/*END*/
       TMD.KANSAN_SUU AS HIKIWATASHI_RYOU--,
       --HWS_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD AS CHIIKI_CD3,
       --HSW_MC.TODOUFUKEN_CD AS TODOUFUKEN_CD2
FROM T_MANIFEST_ENTRY TME
LEFT JOIN T_MANIFEST_UPN UPN1
       ON TME.SYSTEM_ID    = UPN1.SYSTEM_ID
       AND TME.SEQ         = UPN1.SEQ
       AND UPN1.UPN_ROUTE_NO = 1
LEFT JOIN M_GYOUSHA UPN1_GYOUSHA
       ON UPN1_GYOUSHA.GYOUSHA_CD = UPN1.UPN_SAKI_GYOUSHA_CD
LEFT JOIN T_MANIFEST_UPN UPN2
       ON TME.SYSTEM_ID    = UPN2.SYSTEM_ID
       AND TME.SEQ         = UPN2.SEQ
       AND UPN2.UPN_ROUTE_NO = 2
/*IF data.TUMIKAE_HOKAN_KBN == 1*/
LEFT JOIN M_GYOUSHA UPN1_UPN_GYOUSHA
       ON UPN1_UPN_GYOUSHA.GYOUSHA_CD = UPN1.UPN_GYOUSHA_CD
LEFT JOIN M_GYOUSHA UPN2_UPN_GYOUSHA
       ON UPN2_UPN_GYOUSHA.GYOUSHA_CD = UPN2.UPN_GYOUSHA_CD
LEFT JOIN (
       SELECT
           SYSTEM_ID,
           SEQ,
           MAX(UPN_ROUTE_NO) AS UPN_ROUTE_NO
       FROM
           T_MANIFEST_UPN
       WHERE
           ISNULL(UPN_GYOUSHA_CD, '') != ''
       GROUP BY
           SYSTEM_ID, SEQ
    ) AS UPN_ALL_ROUTE
        ON TME.SYSTEM_ID    = UPN_ALL_ROUTE.SYSTEM_ID
        AND TME.SEQ          = UPN_ALL_ROUTE.SEQ
/*END*/
/*IF data.TUMIKAE_HOKAN_KBN == 2*/       
LEFT JOIN T_MANIFEST_UPN UPN_ALL_ROUTE
       ON TME.SYSTEM_ID    = UPN_ALL_ROUTE.SYSTEM_ID
       AND TME.SEQ          = UPN_ALL_ROUTE.SEQ
/*END*/ 
LEFT JOIN M_GYOUSHA UPN2_GYOUSHA
       ON UPN2_GYOUSHA.GYOUSHA_CD = UPN2.UPN_SAKI_GYOUSHA_CD
LEFT JOIN T_MANIFEST_DETAIL TMD
       ON TME.SYSTEM_ID = TMD.SYSTEM_ID
       AND TME.SEQ       = TMD.SEQ
LEFT JOIN M_HAIKI_SHURUI MHS
       ON TME.HAIKI_KBN_CD    = MHS.HAIKI_KBN_CD
       AND TMD.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
WHERE TME.DELETE_FLG  = 0
   AND TME.HAIKI_KBN_CD = 2
   AND 
   /*IF data.HAIKIBUTU_KBN == 1*/
   TMD.HAIKI_SHURUI_CD BETWEEN '0000' AND '2099'
   /*END*/
   /*IF data.HAIKIBUTU_KBN == 2*/
   TMD.HAIKI_SHURUI_CD BETWEEN '2100' AND '9999'
   /*END*/
   AND ((UPN1.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
      AND UPN1.UPN_END_DATE >= /*data.DATE_FROM*/''
      AND UPN1.UPN_END_DATE  <= /*data.DATE_TO*/'')
     OR (UPN2.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
      AND UPN2.UPN_END_DATE >= /*data.DATE_FROM*/''
      AND UPN2.UPN_END_DATE  <= /*data.DATE_TO*/''))
      
UNION ALL
   
SELECT distinct TME.SYSTEM_ID,
       TME.SEQ,
       TMD.DETAIL_SYSTEM_ID,
       NULL AS KANRI_ID,
       NULL AS DEN_SEQ,
       TME.MANIFEST_ID,
	   TME.FIRST_MANIFEST_KBN,
       TME.HAIKI_KBN_CD,
       MHS.HOUKOKUSHO_BUNRUI_CD,
       TMD.HAIKI_SHURUI_CD,
       MHS.HAIKI_SHURUI_NAME, 
       TME.HST_GYOUSHA_CD,
	   TME.HST_GENBA_CD,
	   TMD.KANSAN_SUU AS JYUTAKU_RYOU,
       TMD.SBN_HOUHOU_CD,
/*IF data.TUMIKAE_HOKAN_KBN == 1*/
       1 AS LAST_UPN_ROUTE_FLAG,
       UPN.UPN_SAKI_GYOUSHA_CD AS SBN_GYOUSHA_CD,
       UPN.UPN_SAKI_GENBA_CD AS SBN_GENBA_CD,

       CASE WHEN ISNULL(UPN3_UPN_GYOUSHA.JISHA_KBN, 0) = 1
         THEN UPN3.UPN_SAKI_GYOUSHA_CD
       WHEN ISNULL(UPN2_UPN_GYOUSHA.JISHA_KBN, 0) = 1
         THEN UPN2.UPN_SAKI_GYOUSHA_CD
       WHEN ISNULL(UPN1_UPN_GYOUSHA.JISHA_KBN, 0) = 1
         THEN UPN1.UPN_SAKI_GYOUSHA_CD
       END AS UPN_SAKI_GYOUSHA_CD,

       CASE WHEN ISNULL(UPN3_UPN_GYOUSHA.JISHA_KBN, 0) = 1
         THEN UPN3.UPN_SAKI_GENBA_CD
       WHEN ISNULL(UPN2_UPN_GYOUSHA.JISHA_KBN, 0) = 1
         THEN UPN2.UPN_SAKI_GENBA_CD
       WHEN ISNULL(UPN1_UPN_GYOUSHA.JISHA_KBN, 0) = 1
         THEN UPN1.UPN_SAKI_GENBA_CD
       END AS UPN_SAKI_GENBA_CD,

       UPN.UPN_ROUTE_NO,
       UPN.UPN_GYOUSHA_CD AS UPN_JYUTAKUSHA_CD,
/*END*/
/*IF data.TUMIKAE_HOKAN_KBN == 2*/
       CASE WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = UPN.UPN_ROUTE_NO THEN 1
            ELSE 0 END AS LAST_UPN_ROUTE_FLAG,
       UPN_ALL_ROUTE.UPN_SAKI_GYOUSHA_CD AS SBN_GYOUSHA_CD,
       UPN_ALL_ROUTE.UPN_SAKI_GENBA_CD AS SBN_GENBA_CD,
       UPN_ALL_ROUTE.UPN_ROUTE_NO,
       UPN_ALL_ROUTE.UPN_GYOUSHA_CD,    
/*END*/
       TMD.KANSAN_SUU AS UPN_RYOU,
/*IF data.TUMIKAE_HOKAN_KBN == 1*/
       UPN.UPN_SAKI_GYOUSHA_CD AS HIKIWATASHISAKI_CD,
/*END*/
/*IF data.TUMIKAE_HOKAN_KBN == 2*/
       CASE 
		 WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = UPN.UPN_ROUTE_NO
		   THEN UPN.UPN_SAKI_GYOUSHA_CD
	     WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO < UPN.UPN_ROUTE_NO
		 THEN
		   CASE 
		     WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = 1
			 THEN UPN2.UPN_GYOUSHA_CD 
			 WHEN UPN_ALL_ROUTE.UPN_ROUTE_NO = 2
			 THEN UPN3.UPN_GYOUSHA_CD
		   END
	   END AS HIKIWATASHISAKI_CD,
/*END*/
       TMD.KANSAN_SUU AS HIKIWATASHI_RYOU
FROM T_MANIFEST_ENTRY TME
LEFT JOIN T_MANIFEST_UPN UPN
       ON TME.SYSTEM_ID    = UPN.SYSTEM_ID
       AND TME.SEQ         = UPN.SEQ
       AND UPN.UPN_ROUTE_NO = (SELECT MIN(UPN_ROUTE_NO) FROM T_MANIFEST_UPN WHERE TME.SYSTEM_ID = T_MANIFEST_UPN.SYSTEM_ID AND TME.SEQ = T_MANIFEST_UPN.SEQ  AND T_MANIFEST_UPN.UPN_SAKI_KBN = 1) 
LEFT JOIN T_MANIFEST_UPN UPN1
       ON TME.SYSTEM_ID    = UPN1.SYSTEM_ID
       AND TME.SEQ         = UPN1.SEQ
       AND UPN1.UPN_ROUTE_NO = 1
LEFT JOIN T_MANIFEST_UPN UPN2
       ON TME.SYSTEM_ID    = UPN2.SYSTEM_ID
       AND TME.SEQ         = UPN2.SEQ
       AND UPN2.UPN_ROUTE_NO = 2
LEFT JOIN T_MANIFEST_UPN UPN3
       ON TME.SYSTEM_ID    = UPN3.SYSTEM_ID
       AND TME.SEQ         = UPN3.SEQ
       AND UPN3.UPN_ROUTE_NO = 3
/*IF data.TUMIKAE_HOKAN_KBN == 1*/
LEFT JOIN M_GYOUSHA UPN1_UPN_GYOUSHA
       ON UPN1_UPN_GYOUSHA.GYOUSHA_CD = UPN1.UPN_GYOUSHA_CD
LEFT JOIN M_GYOUSHA UPN2_UPN_GYOUSHA
       ON UPN2_UPN_GYOUSHA.GYOUSHA_CD = UPN2.UPN_GYOUSHA_CD
LEFT JOIN M_GYOUSHA UPN3_UPN_GYOUSHA
       ON UPN3_UPN_GYOUSHA.GYOUSHA_CD = UPN3.UPN_GYOUSHA_CD
/*END*/
/*IF data.TUMIKAE_HOKAN_KBN == 2*/       
LEFT JOIN T_MANIFEST_UPN UPN_ALL_ROUTE
       ON TME.SYSTEM_ID    = UPN_ALL_ROUTE.SYSTEM_ID
       AND TME.SEQ          = UPN_ALL_ROUTE.SEQ
	   AND UPN_ALL_ROUTE.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO 
/*END*/       
LEFT JOIN T_MANIFEST_DETAIL TMD
       ON TME.SYSTEM_ID = TMD.SYSTEM_ID
       AND TME.SEQ       = TMD.SEQ
LEFT JOIN M_HAIKI_SHURUI MHS
       ON TME.HAIKI_KBN_CD    = MHS.HAIKI_KBN_CD
       AND TMD.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
WHERE TME.DELETE_FLG  = 0
   AND TME.HAIKI_KBN_CD = 3
   AND 
   /*IF data.HAIKIBUTU_KBN == 1*/
   TMD.HAIKI_SHURUI_CD BETWEEN '0000' AND '6999'
   /*END*/
   /*IF data.HAIKIBUTU_KBN == 2*/
   TMD.HAIKI_SHURUI_CD BETWEEN '7000' AND '9999'
   /*END*/
   AND ((UPN1.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
      AND UPN1.UPN_END_DATE >= /*data.DATE_FROM*/''
      AND UPN1.UPN_END_DATE  <= /*data.DATE_TO*/''
      AND UPN1.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO)
     OR (UPN2.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
      AND UPN2.UPN_END_DATE >= /*data.DATE_FROM*/''
      AND UPN2.UPN_END_DATE  <= /*data.DATE_TO*/''
      AND UPN2.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO)
     OR (UPN3.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
      AND UPN3.UPN_END_DATE >= /*data.DATE_FROM*/''
      AND UPN3.UPN_END_DATE  <= /*data.DATE_TO*/''
      AND UPN3.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO))
      
/*IF data.DENSHI_MANIFEST_KBN == 1*/
UNION ALL
SELECT distinct R18.SYSTEM_ID,
           R18.SEQ,
           R18.DETAIL_SYSTEM_ID,
           DMT.KANRI_ID,
           R18.DEN_SEQ,
           R18.MANIFEST_ID,
           R18.FIRST_MANIFEST_KBN,
           CAST('4' AS SMALLINT ) AS HAIKI_KBN_CD,
           MDHS.HOUKOKUSHO_BUNRUI_CD,
           R18.HAIKI_DAI_CODE + R18.HAIKI_CHU_CODE + R18.HAIKI_SHO_CODE AS HAIKI_SHURUI_CD,
           R18.HAIKI_SHURUI_NAME,
           R18.HST_GYOUSHA_CD,
           R18.HST_GENBA_CD,
           R18.KANSAN_SUU AS JYUTAKU_RYOU,
           R18.SBN_HOUHOU_CD,
/*IF data.TUMIKAE_HOKAN_KBN == 1*/           
           1 AS LAST_UPN_ROUTE_FLAG,
           UPN_EX.UPNSAKI_GYOUSHA_CD AS SBN_GYOUSHA_CD,
           UPN_EX.UPNSAKI_GENBA_CD AS SBN_GENBA_CD,
           UPN_EX.UPNSAKI_GYOUSHA_CD AS UPN_SAKI_GYOUSHA_CD,
           UPN_EX.UPNSAKI_GENBA_CD AS UPN_SAKI_GENBA_CD,
           UPN_EX.UPN_ROUTE_NO,
           UPN_EX.UPN_GYOUSHA_CD AS UPN_JYUTAKUSHA_CD,
/*END*/
/*IF data.TUMIKAE_HOKAN_KBN == 2*/    
           CASE WHEN UPN_ALL_ROUTE_EX.UPN_ROUTE_NO = UPN_EX.UPN_ROUTE_NO THEN 1
                ELSE 0 END AS LAST_UPN_ROUTE_FLAG,
           UPN_ALL_ROUTE_EX.UPNSAKI_GYOUSHA_CD AS SBN_GYOUSHA_CD,
           UPN_ALL_ROUTE_EX.UPNSAKI_GENBA_CD AS SBN_GENBA_CD,
           UPN_ALL_ROUTE_EX.UPN_ROUTE_NO,
           UPN_ALL_ROUTE_EX.UPN_GYOUSHA_CD AS UPN_JYUTAKUSHA_CD,
/*END*/
           R18.KANSAN_SUU AS UPN_RYOU,
/*IF data.TUMIKAE_HOKAN_KBN == 2*/
           CASE WHEN UPN_ALL_ROUTE_EX.UPN_ROUTE_NO = UPN_EX.UPN_ROUTE_NO
		        THEN UPN_EX.UPNSAKI_GYOUSHA_CD
		        WHEN UPN_ALL_ROUTE_EX.UPN_ROUTE_NO < UPN_EX.UPN_ROUTE_NO
				THEN
				    CASE 
						WHEN UPN_ALL_ROUTE_EX.UPN_ROUTE_NO = 1
						THEN UPN_EX2.UPN_GYOUSHA_CD 
						WHEN UPN_ALL_ROUTE_EX.UPN_ROUTE_NO = 2
						THEN UPN_EX3.UPN_GYOUSHA_CD 
						WHEN UPN_ALL_ROUTE_EX.UPN_ROUTE_NO = 3
						THEN UPN_EX4.UPN_GYOUSHA_CD 
						WHEN UPN_ALL_ROUTE_EX.UPN_ROUTE_NO = 4
						THEN UPN_EX5.UPN_GYOUSHA_CD
					END
			    END AS HIKIWATASHISAKI_CD,
/*END*/
/*IF data.TUMIKAE_HOKAN_KBN == 1*/
           UPN_EX.UPNSAKI_GYOUSHA_CD AS HIKIWATASHISAKI_CD,
/*END*/
           R18.KANSAN_SUU AS HIKIWATASHI_RYOU
FROM DT_MF_TOC DMT
INNER JOIN (
        SELECT
            R18.KANRI_ID
            ,R18.SEQ AS DEN_SEQ
            ,R18.MANIFEST_ID
			,R18.HIKIWATASHI_DATE
			,R18.HST_SHA_EDI_MEMBER_ID
            ,EX.SYSTEM_ID
            ,EX.SEQ
            ,EX.HST_GYOUSHA_CD
            ,EX.HST_GENBA_CD
             --中間処理産業廃棄物管理方法フラグがブランクでなく存在し、排出が自社の場合は2次マニとして扱う
            ,CASE
               WHEN (R18.FIRST_MANIFEST_FLAG IS NOT NULL OR R18.FIRST_MANIFEST_FLAG != '') AND ISNULL(HST_GYOUSHA.JISHA_KBN, 0) = 1 THEN 1
               ELSE 0
             END AS FIRST_MANIFEST_KBN
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.DETAIL_SYSTEM_ID ELSE EX.SYSTEM_ID END) AS DETAIL_SYSTEM_ID
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.SBN_HOUHOU_CD ELSE EX.SBN_HOUHOU_CD END) AS SBN_HOUHOU_CD
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.KANSAN_SUU ELSE EX.KANSAN_SUU END) AS KANSAN_SUU
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.HAIKI_DAI_CODE ELSE R18.HAIKI_DAI_CODE END) AS HAIKI_DAI_CODE
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.HAIKI_CHU_CODE ELSE R18.HAIKI_CHU_CODE END) AS HAIKI_CHU_CODE
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.HAIKI_SHO_CODE ELSE R18.HAIKI_SHO_CODE END) AS HAIKI_SHO_CODE
            ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX_HAIKI_SHURUI.HAIKI_SHURUI_NAME ELSE R18.HAIKI_SHURUI END) AS HAIKI_SHURUI_NAME
        FROM DT_R18 AS R18
        LEFT JOIN DT_R18_EX AS EX
        ON R18.KANRI_ID = EX.KANRI_ID AND EX.DELETE_FLG = 0
        LEFT JOIN DT_R18_MIX AS MIX
        ON EX.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0
        LEFT JOIN M_DENSHI_HAIKI_SHURUI AS MIX_HAIKI_SHURUI
        ON (MIX.HAIKI_DAI_CODE + MIX.HAIKI_CHU_CODE + MIX.HAIKI_SHO_CODE) = MIX_HAIKI_SHURUI.HAIKI_SHURUI_CD
		LEFT JOIN M_GYOUSHA AS HST_GYOUSHA
		ON EX.HST_GYOUSHA_CD = HST_GYOUSHA.GYOUSHA_CD
    ) R18
    ON DMT.KANRI_ID = R18.KANRI_ID AND DMT.LATEST_SEQ = R18.DEN_SEQ
 LEFT JOIN DT_R19 UPN
        ON R18.KANRI_ID        = UPN.KANRI_ID
       AND R18.DEN_SEQ             = UPN.SEQ
       AND UPN.UPNSAKI_JOU_KBN IN (2,3,4)       
 LEFT JOIN DT_R19_EX UPN_EX
        ON UPN.KANRI_ID     = UPN_EX.KANRI_ID
       AND R18.SYSTEM_ID  = UPN_EX.SYSTEM_ID
       AND R18.SEQ        = UPN_EX.SEQ
       AND UPN.UPN_ROUTE_NO = UPN_EX.UPN_ROUTE_NO
 /*IF data.TUMIKAE_HOKAN_KBN == 2*/
 LEFT JOIN DT_R19 UPN_ALL_ROUTE
        ON R18.KANRI_ID               = UPN_ALL_ROUTE.KANRI_ID
       AND R18.DEN_SEQ                    = UPN_ALL_ROUTE.SEQ
	   AND UPN_ALL_ROUTE.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO
 LEFT JOIN DT_R19_EX UPN_ALL_ROUTE_EX
        ON UPN_ALL_ROUTE.KANRI_ID     = UPN_ALL_ROUTE_EX.KANRI_ID
       AND R18.SYSTEM_ID            = UPN_ALL_ROUTE_EX.SYSTEM_ID
       AND R18.SEQ                  = UPN_ALL_ROUTE_EX.SEQ
       AND UPN_ALL_ROUTE.UPN_ROUTE_NO = UPN_ALL_ROUTE_EX.UPN_ROUTE_NO
 /*END*/
 LEFT JOIN M_DENSHI_HAIKI_SHURUI MDHS
        ON R18.HAIKI_DAI_CODE + R18.HAIKI_CHU_CODE + R18.HAIKI_SHO_CODE = MDHS.HAIKI_SHURUI_CD
 
 LEFT JOIN DT_R19 UPN1
        ON R18.KANRI_ID         = UPN1.KANRI_ID
       AND R18.DEN_SEQ              = UPN1.SEQ
	   AND UPN1.UPN_ROUTE_NO    = 1
LEFT JOIN (SELECT DT_R18.KANRI_ID, DT_R18.SEQ, DT_R19.UPN_ROUTE_NO, DT_R19.UPN_END_DATE AS ENDDAY 
		FROM DT_MF_TOC toc INNER JOIN DT_R18 ON toc.KANRI_ID = DT_R18.KANRI_ID AND toc.LATEST_SEQ = DT_R18.SEQ
		LEFT JOIN DT_R19 on DT_R18.KANRI_ID = DT_R19.KANRI_ID AND DT_R18.SEQ = DT_R19.SEQ WHERE UPN_ROUTE_NO = 1 AND DT_R18.HST_SHA_EDI_MEMBER_ID != DT_R19.UPN_SHA_EDI_MEMBER_ID) UPN11
        ON UPN1.KANRI_ID         = UPN11.KANRI_ID
       AND UPN1.SEQ              = UPN11.SEQ
       
 LEFT JOIN DT_R19_EX UPN_EX1
        ON UPN1.KANRI_ID     = UPN_EX1.KANRI_ID
       AND R18.SYSTEM_ID            = UPN_EX1.SYSTEM_ID
       AND R18.SEQ                  = UPN_EX1.SEQ
       AND UPN1.UPN_ROUTE_NO = UPN_EX1.UPN_ROUTE_NO
       
 LEFT JOIN DT_R19 UPN2
        ON R18.KANRI_ID         = UPN2.KANRI_ID
       AND R18.DEN_SEQ              = UPN2.SEQ
	   AND UPN2.UPN_ROUTE_NO    = 2
 LEFT JOIN (SELECT DT_R18.KANRI_ID, DT_R18.SEQ, MAX(UPN_ROUTE_NO) AS ROUTENO 
			FROM DT_MF_TOC toc INNER JOIN DT_R18 ON toc.KANRI_ID = DT_R18.KANRI_ID AND toc.LATEST_SEQ = DT_R18.SEQ
			LEFT JOIN DT_R19 ON DT_R18.KANRI_ID  = DT_R19.KANRI_ID AND DT_R18.SEQ = DT_R19.SEQ
			WHERE DT_R19.UPN_ROUTE_NO <= 2 AND DT_R18.HST_SHA_EDI_MEMBER_ID != DT_R19.UPN_SHA_EDI_MEMBER_ID GROUP BY DT_R18.KANRI_ID,DT_R18.SEQ) UPN12
        ON UPN2.KANRI_ID         = UPN12.KANRI_ID
       AND UPN2.SEQ              = UPN12.SEQ
 LEFT JOIN (SELECT KANRI_ID, SEQ, UPN_ROUTE_NO, UPN_END_DATE AS ENDDAY FROM DT_R19) UPN22
		 ON UPN12.KANRI_ID  = UPN22.KANRI_ID AND UPN12.SEQ = UPN22.SEQ AND UPN12.ROUTENO = UPN22.UPN_ROUTE_NO
		AND ((UPN22.KANRI_ID IS NULL
			AND ISDATE(R18.HIKIWATASHI_DATE) = 1
			AND R18.HIKIWATASHI_DATE >= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_FROM*/''), 112)
			AND R18.HIKIWATASHI_DATE <= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_TO*/''), 112))
		OR   (UPN22.KANRI_ID IS NOT NULL
			AND ISDATE(UPN22.ENDDAY) = 1
			AND UPN22.ENDDAY >= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_FROM*/''), 112)
			AND UPN22.ENDDAY <= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_TO*/''), 112)
			AND UPN22.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO))
 LEFT JOIN DT_R19_EX UPN_EX2
        ON UPN2.KANRI_ID     = UPN_EX2.KANRI_ID
       AND R18.SYSTEM_ID   = UPN_EX2.SYSTEM_ID
       AND R18.SEQ         = UPN_EX2.SEQ
       AND UPN2.UPN_ROUTE_NO = UPN_EX2.UPN_ROUTE_NO
	   AND UPN_EX2.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''

 LEFT JOIN DT_R19 UPN3
        ON R18.KANRI_ID         = UPN3.KANRI_ID
       AND R18.DEN_SEQ              = UPN3.SEQ
	   AND UPN3.UPN_ROUTE_NO    = 3
LEFT JOIN (SELECT DT_R18.KANRI_ID, DT_R18.SEQ, MAX(UPN_ROUTE_NO) AS ROUTENO 
			FROM DT_MF_TOC toc INNER JOIN DT_R18 ON toc.KANRI_ID = DT_R18.KANRI_ID AND toc.LATEST_SEQ = DT_R18.SEQ
			LEFT JOIN DT_R19 ON DT_R18.KANRI_ID  = DT_R19.KANRI_ID AND DT_R18.SEQ = DT_R19.SEQ
			WHERE DT_R19.UPN_ROUTE_NO <= 3 AND DT_R18.HST_SHA_EDI_MEMBER_ID != DT_R19.UPN_SHA_EDI_MEMBER_ID GROUP BY DT_R18.KANRI_ID,DT_R18.SEQ) UPN13
        ON UPN3.KANRI_ID         = UPN13.KANRI_ID
       AND UPN3.SEQ              = UPN13.SEQ
 LEFT JOIN (SELECT KANRI_ID,SEQ, UPN_ROUTE_NO, UPN_END_DATE AS ENDDAY FROM DT_R19) UPN33
		 ON UPN13.KANRI_ID  = UPN33.KANRI_ID AND UPN13.SEQ = UPN33.SEQ AND UPN13.ROUTENO = UPN33.UPN_ROUTE_NO
		AND ((UPN33.KANRI_ID IS NULL
			AND ISDATE(R18.HIKIWATASHI_DATE) = 1
			AND R18.HIKIWATASHI_DATE >= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_FROM*/''), 112)
			AND R18.HIKIWATASHI_DATE <= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_TO*/''), 112))
		OR   (UPN33.KANRI_ID IS NOT NULL
			AND ISDATE(UPN33.ENDDAY) = 1
			AND UPN33.ENDDAY >= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_FROM*/''), 112)
			AND UPN33.ENDDAY <= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_TO*/''), 112)
			AND UPN33.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO))
 LEFT JOIN DT_R19_EX UPN_EX3
        ON UPN3.KANRI_ID     = UPN_EX3.KANRI_ID
       AND R18.SYSTEM_ID   = UPN_EX3.SYSTEM_ID
       AND R18.SEQ         = UPN_EX3.SEQ
       AND UPN3.UPN_ROUTE_NO = UPN_EX3.UPN_ROUTE_NO
	   AND UPN_EX3.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''

 LEFT JOIN DT_R19 UPN4
        ON R18.KANRI_ID         = UPN4.KANRI_ID
       AND R18.DEN_SEQ              = UPN4.SEQ
	   AND UPN4.UPN_ROUTE_NO    = 4
LEFT JOIN (SELECT DT_R18.KANRI_ID, DT_R18.SEQ, MAX(UPN_ROUTE_NO) AS ROUTENO 
			FROM DT_MF_TOC toc INNER JOIN DT_R18 ON toc.KANRI_ID = DT_R18.KANRI_ID AND toc.LATEST_SEQ = DT_R18.SEQ
			LEFT JOIN DT_R19 ON DT_R18.KANRI_ID  = DT_R19.KANRI_ID AND DT_R18.SEQ = DT_R19.SEQ
			WHERE DT_R19.UPN_ROUTE_NO <= 4 AND DT_R18.HST_SHA_EDI_MEMBER_ID != DT_R19.UPN_SHA_EDI_MEMBER_ID GROUP BY DT_R18.KANRI_ID,DT_R18.SEQ) UPN14
        ON UPN4.KANRI_ID         = UPN14.KANRI_ID
       AND UPN4.SEQ              = UPN14.SEQ
 LEFT JOIN (SELECT KANRI_ID, SEQ, UPN_ROUTE_NO, UPN_END_DATE AS ENDDAY FROM DT_R19) UPN44
		 ON UPN14.KANRI_ID  = UPN44.KANRI_ID AND UPN14.SEQ = UPN44.SEQ AND UPN14.ROUTENO = UPN44.UPN_ROUTE_NO
		AND ((UPN44.KANRI_ID IS NULL
			AND ISDATE(R18.HIKIWATASHI_DATE) = 1
			AND R18.HIKIWATASHI_DATE >= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_FROM*/''), 112)
			AND R18.HIKIWATASHI_DATE <= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_TO*/''), 112))
		OR   (UPN44.KANRI_ID IS NOT NULL
			AND ISDATE(UPN44.ENDDAY) = 1
			AND UPN44.ENDDAY >= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_FROM*/''), 112)
			AND UPN44.ENDDAY <= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_TO*/''), 112)
			AND UPN44.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO))
 LEFT JOIN DT_R19_EX UPN_EX4
        ON UPN4.KANRI_ID     = UPN_EX4.KANRI_ID
       AND R18.SYSTEM_ID   = UPN_EX4.SYSTEM_ID
       AND R18.SEQ         = UPN_EX4.SEQ
       AND UPN4.UPN_ROUTE_NO = UPN_EX4.UPN_ROUTE_NO
	   AND UPN_EX4.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''

 LEFT JOIN DT_R19 UPN5
        ON R18.KANRI_ID         = UPN5.KANRI_ID
       AND R18.DEN_SEQ              = UPN5.SEQ
	   AND UPN5.UPN_ROUTE_NO    = 5
LEFT JOIN (SELECT DT_R18.KANRI_ID, DT_R18.SEQ, MAX(UPN_ROUTE_NO) AS ROUTENO 
			FROM DT_MF_TOC toc INNER JOIN DT_R18 ON toc.KANRI_ID = DT_R18.KANRI_ID AND toc.LATEST_SEQ = DT_R18.SEQ
			LEFT JOIN DT_R19 ON DT_R18.KANRI_ID  = DT_R19.KANRI_ID AND DT_R18.SEQ = DT_R19.SEQ
			WHERE DT_R19.UPN_ROUTE_NO <= 5 AND DT_R18.HST_SHA_EDI_MEMBER_ID != DT_R19.UPN_SHA_EDI_MEMBER_ID GROUP BY DT_R18.KANRI_ID,DT_R18.SEQ) UPN15
        ON UPN5.KANRI_ID         = UPN15.KANRI_ID
       AND UPN5.SEQ              = UPN15.SEQ
 LEFT JOIN (SELECT KANRI_ID, SEQ, UPN_ROUTE_NO, UPN_END_DATE AS ENDDAY FROM DT_R19) UPN55
		 ON UPN15.KANRI_ID  = UPN55.KANRI_ID AND UPN15.SEQ = UPN55.SEQ AND UPN15.ROUTENO = UPN55.UPN_ROUTE_NO
		AND ((UPN55.KANRI_ID IS NULL
			AND ISDATE(R18.HIKIWATASHI_DATE) = 1
			AND R18.HIKIWATASHI_DATE >= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_FROM*/''), 112)
			AND R18.HIKIWATASHI_DATE <=CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_TO*/''), 112))
		OR   (UPN55.KANRI_ID IS NOT NULL
			AND ISDATE(UPN55.ENDDAY) = 1
			AND UPN55.ENDDAY >= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_FROM*/''), 112)
			AND UPN55.ENDDAY <= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_TO*/''), 112)
			AND UPN55.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO))
 LEFT JOIN DT_R19_EX UPN_EX5
        ON UPN5.KANRI_ID     = UPN_EX5.KANRI_ID
       AND R18.SYSTEM_ID   = UPN_EX5.SYSTEM_ID
       AND R18.SEQ         = UPN_EX5.SEQ
       AND UPN5.UPN_ROUTE_NO = UPN_EX5.UPN_ROUTE_NO
	   AND UPN_EX5.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
 WHERE (DMT.KIND = 4 OR DMT.KIND = 5 OR DMT.KIND IS NULL)
       AND DMT.STATUS_FLAG = 4
       AND 
   /*IF data.HAIKIBUTU_KBN == 1*/
   (R18.HAIKI_DAI_CODE + R18.HAIKI_CHU_CODE + R18.HAIKI_SHO_CODE) BETWEEN '0000' AND '6999'
   /*END*/
   /*IF data.HAIKIBUTU_KBN == 2*/
   (R18.HAIKI_DAI_CODE + R18.HAIKI_CHU_CODE + R18.HAIKI_SHO_CODE) BETWEEN '7000' AND '9999'
   /*END*/
   AND ((UPN_EX1.UPN_GYOUSHA_CD = /*data.HOUKOKU_JIGYOUSHA_CD*/''
		AND ((UPN11.KANRI_ID IS NULL
	        AND ISDATE(R18.HIKIWATASHI_DATE) = 1
		    AND R18.HIKIWATASHI_DATE >= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_FROM*/''), 112)
			AND R18.HIKIWATASHI_DATE  <= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_TO*/''), 112))
		OR (UPN11.KANRI_ID IS NOT NULL
			AND ISDATE(UPN11.ENDDAY) = 1
	        AND UPN11.ENDDAY >= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_FROM*/''), 112)
		    AND UPN11.ENDDAY  <= CONVERT(NVARCHAR, CONVERT(DATETIME, /*data.DATE_TO*/''), 112)
			AND UPN11.UPN_ROUTE_NO <= UPN.UPN_ROUTE_NO))
		)
      )
/*END*/
),
SEARCH_DATA AS (
SELECT 
      MANI.SYSTEM_ID,
      MANI.SEQ,
      MANI.DETAIL_SYSTEM_ID,
      MANI.KANRI_ID,
      MANI.DEN_SEQ,
      MANI.MANIFEST_ID,
      MANI.HAIKI_KBN_CD,
      MCB.HOUKOKU_BUNRUI_CD AS HOUKOKUSHO_BUNRUI_CD,
      MCB.HOUKOKU_BUNRUI_NAME AS HOUKOKUSHO_BUNRUI_NAME,
      MANI.HAIKI_SHURUI_CD,
      MANI.HAIKI_SHURUI_NAME,
      NULL AS SEKIMEN_KBN,
      NULL AS TOKUTEI_YUUGAI_KBN,
      NULL AS SAIITAKU_KYOKA_NO,
      MANI.HST_GYOUSHA_CD,
      HST_GYOUSHA.GYOUSHA_NAME1 + HST_GYOUSHA.GYOUSHA_NAME2 AS HST_GYOUSHA_NAME,
      CASE /*data.JUSHO_CHUSHUTU_JOKEN*/0
      WHEN 1
      THEN HST_GYOUSHA_MT.TODOUFUKEN_NAME + HST_GYOUSHA.GYOUSHA_ADDRESS1 + HST_GYOUSHA.GYOUSHA_ADDRESS2
      WHEN 2
      THEN HST_GYOUSHA.GYOUSHA_ADDRESS1 + HST_GYOUSHA.GYOUSHA_ADDRESS2
      WHEN 3
      THEN HST_GYOUSHA_MT.TODOUFUKEN_NAME + HST_GYOUSHA.GYOUSHA_ADDRESS1
      END AS HST_GYOUSHA_ADDRESS,
      NULL AS HST_GYOUSHA_GYOUSHU_CD,
      MANI.HST_GENBA_CD,
      HST_GENBA.GENBA_NAME1 + HST_GENBA.GENBA_NAME2 AS HST_GENBA_NAME,
      CASE /*data.JUSHO_CHUSHUTU_JOKEN*/0
      WHEN 1
      THEN HST_GENBA_MT.TODOUFUKEN_NAME + HST_GENBA.GENBA_ADDRESS1 + HST_GENBA.GENBA_ADDRESS2
      WHEN 2
      THEN HST_GENBA.GENBA_ADDRESS1 + HST_GENBA.GENBA_ADDRESS2
      WHEN 3
      THEN HST_GENBA_MT.TODOUFUKEN_NAME + HST_GENBA.GENBA_ADDRESS1
      END AS HST_GENBA_ADDRESS,
      NULL AS HST_GENBA_GYOUSHU_CD,
      HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD AS HST_GENBA_CHIIKI_CD,
      MANI.JYUTAKU_RYOU,
      NULL AS JYUTAKU_KBN,
      MU.UNIT_NAME AS JYUTAKU_UNIT_NAME,
      MCS.HOUKOKU_SHOBUN_HOUHOU_CD AS SHOBUN_HOUHOU_CD,
      MCS.HOUKOKU_SHOBUN_HOUHOU_NAME AS SHOBUN_HOUHOU_NAME,
      NULL AS SHOBUN_MOKUTEKI_CD,
      NULL AS SHOBUN_MOKUTEKI_NAME,
      MANI.SBN_GYOUSHA_CD AS SBN_GYOUSHA_CD,
      SBN_GYOUSHA.GYOUSHA_NAME1 + SBN_GYOUSHA.GYOUSHA_NAME2 AS SBN_GYOUSHA_NAME,
      CASE /*data.JUSHO_CHUSHUTU_JOKEN*/0
      WHEN 1
      THEN SBN_GYOUSHA_MT.TODOUFUKEN_NAME + SBN_GYOUSHA.GYOUSHA_ADDRESS1 + SBN_GYOUSHA.GYOUSHA_ADDRESS2
      WHEN 2
      THEN SBN_GYOUSHA.GYOUSHA_ADDRESS1 + SBN_GYOUSHA.GYOUSHA_ADDRESS2
      WHEN 3
      THEN SBN_GYOUSHA_MT.TODOUFUKEN_NAME + SBN_GYOUSHA.GYOUSHA_ADDRESS1
      END AS SBN_GYOUSHA_ADDRESS,
      MANI.SBN_GENBA_CD,
      SBN_GENBA.GENBA_NAME1 + SBN_GENBA.GENBA_NAME2 AS SBN_GENBA_NAME,
      CASE /*data.JUSHO_CHUSHUTU_JOKEN*/0
      WHEN 1
      THEN SBN_GENBA_MT.TODOUFUKEN_NAME + SBN_GENBA.GENBA_ADDRESS1 + SBN_GENBA.GENBA_ADDRESS2
      WHEN 2
      THEN SBN_GENBA.GENBA_ADDRESS1 + SBN_GENBA.GENBA_ADDRESS2
      WHEN 3
      THEN SBN_GENBA_MT.TODOUFUKEN_NAME + SBN_GENBA.GENBA_ADDRESS1
      END AS SBN_GENBA_ADDRESS,
      SBN_GENBA.CHIIKI_CD AS SBN_GENBA_CHIIKI_CD,
      MANI.UPN_RYOU,
      MANI.UPN_ROUTE_NO,
      CASE
      WHEN (/*data.UNPAN_SAIITAKU_JOKEN*/0 = 2 AND HWS_GYOUSHA.JISHA_KBN = 1) OR MANI.HIKIWATASHISAKI_CD IS NULL
      THEN NULL
      ELSE MANI.HIKIWATASHISAKI_CD
      END AS HIKIWATASHISAKI_CD,
      CASE
      WHEN (/*data.UNPAN_SAIITAKU_JOKEN*/0 = 2 AND HWS_GYOUSHA.JISHA_KBN = 1) OR MANI.HIKIWATASHISAKI_CD IS NULL
      THEN NULL
      ELSE HWS_GYOUSHA.GYOUSHA_NAME1 + HWS_GYOUSHA.GYOUSHA_NAME2
      END AS HIKIWATASHISAKI_NAME,
      CASE
      WHEN (/*data.UNPAN_SAIITAKU_JOKEN*/0 = 2 AND HWS_GYOUSHA.JISHA_KBN = 1) OR MANI.HIKIWATASHISAKI_CD IS NULL
      THEN NULL
      ELSE 
        CASE /*data.JUSHO_CHUSHUTU_JOKEN*/0
        WHEN 1
        THEN HWS_GYOUSHA_MT.TODOUFUKEN_NAME + HWS_GYOUSHA.GYOUSHA_ADDRESS1 + HWS_GYOUSHA.GYOUSHA_ADDRESS2
        WHEN 2
        THEN HWS_GYOUSHA.GYOUSHA_ADDRESS1 + HWS_GYOUSHA.GYOUSHA_ADDRESS2
        WHEN 3
        THEN HWS_GYOUSHA_MT.TODOUFUKEN_NAME + HWS_GYOUSHA.GYOUSHA_ADDRESS1
        END
      END AS HIKIWATASHISAKI_ADDRESS,
      HWS_GYOUSHA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD AS HIKIWATASHISAKI_CHIIKI_CD,
      CASE MANI.LAST_UPN_ROUTE_FLAG
         WHEN 0 THEN --引渡先（運搬）の許可番号
            CASE
               WHEN (/*data.UNPAN_SAIITAKU_JOKEN*/0 = 2 AND HWS_GYOUSHA.JISHA_KBN = 1) OR (/*data.TASHA_ITAKU_KYOKA_NO*/0 = 2 AND HWS_GYOUSHA.JISHA_KBN = 0) OR MANI.HIKIWATASHISAKI_CD IS NULL THEN NULL
               ELSE
                  CASE /*data.HAIKIBUTU_KBN*/0
                     WHEN 1 THEN MCK.FUTSUU_KYOKA_NO
                     WHEN 2 THEN MCK.TOKUBETSU_KYOKA_NO
                  END
            END
         WHEN 1 THEN --引渡先（処分）の許可番号
            CASE MANI.FIRST_MANIFEST_KBN
               -- 1次マニフェストの場合は、中間処分場の許可番号を表示
               WHEN 0 THEN
                  CASE /*data.HAIKIBUTU_KBN*/0
                     WHEN 1 THEN MCK_SBN.FUTSUU_KYOKA_NO
                     WHEN 2 THEN MCK_SBN.TOKUBETSU_KYOKA_NO
                  END
               -- 2次マニフェストの場合は、最終処分場の許可番号を表示
			   WHEN 1 THEN
                  CASE /*data.HAIKIBUTU_KBN*/0
                     WHEN 1 THEN MCK_LAST_SBN.FUTSUU_KYOKA_NO
                     WHEN 2 THEN MCK_LAST_SBN.TOKUBETSU_KYOKA_NO
                  END
			   ELSE NULL
            END
         ELSE ''
      END AS HIKIWATASHISAKI_KYOKA_NO,
	  CASE
	  WHEN (/*data.UNPAN_SAIITAKU_JOKEN*/0 = 2 AND HWS_GYOUSHA.JISHA_KBN = 1) OR MANI.HIKIWATASHISAKI_CD IS NULL
           THEN NULL
           ELSE
           MANI.HIKIWATASHI_RYOU
           END AS HIKIWATASHI_RYOU,
	  CASE
           WHEN (/*data.UNPAN_SAIITAKU_JOKEN*/0 = 2 AND HWS_GYOUSHA.JISHA_KBN = 1) OR MANI.HIKIWATASHISAKI_CD IS NULL
           THEN NULL
           ELSE
           '(再)'
           END AS HIKIWATASHI_KBN,
      HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD AS CHIIKI_CD2,
      HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD AS TODOUFUKEN_CD,
      SBN_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD AS CHIIKI_CD3,
      SBN_MC.CHIIKI_CD AS TODOUFUKEN_CD2,
      /*IF data.TUMIKAE_HOKAN_KBN == 2*/
	  CASE
      WHEN (HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = /*data.TEISHUTUSAKI_CD*/'') AND (/*data.TEISHUTUSAKI_CD*/'' = SBN_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD)
	  THEN 1
	  WHEN (HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = /*data.TEISHUTUSAKI_CD*/'') AND (/*data.TEISHUTUSAKI_CD*/'' != SBN_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD)
	  THEN 2
	  WHEN (HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD != /*data.TEISHUTUSAKI_CD*/'') AND (/*data.TEISHUTUSAKI_CD*/'' = SBN_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD)
	  THEN 3	  
	  WHEN (HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD != /*data.TEISHUTUSAKI_CD*/'') AND (/*data.TEISHUTUSAKI_CD*/'' != SBN_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD)
	  THEN 4
	  END AS HST_KEN_KBN,
      /*END*/
      /*IF data.TUMIKAE_HOKAN_KBN == 1*/
      CASE WHEN MANI.HAIKI_KBN_CD = 2 OR MANI.HAIKI_KBN_CD = 3
          THEN CASE
              WHEN (HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = /*data.TEISHUTUSAKI_CD*/'') AND (/*data.TEISHUTUSAKI_CD*/'' = UPN_SAKI_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD)
	          THEN 1
	          WHEN (HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = /*data.TEISHUTUSAKI_CD*/'') AND (/*data.TEISHUTUSAKI_CD*/'' != UPN_SAKI_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD)
	          THEN 2
	          WHEN (HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD != /*data.TEISHUTUSAKI_CD*/'') AND (/*data.TEISHUTUSAKI_CD*/'' = UPN_SAKI_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD)
	          THEN 3	  
	          WHEN (HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD != /*data.TEISHUTUSAKI_CD*/'') AND (/*data.TEISHUTUSAKI_CD*/'' != UPN_SAKI_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD)
	          THEN 4
          END
	          ELSE CASE
              WHEN (HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = /*data.TEISHUTUSAKI_CD*/'') AND (/*data.TEISHUTUSAKI_CD*/'' = SBN_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD)
	          THEN 1
	          WHEN (HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = /*data.TEISHUTUSAKI_CD*/'') AND (/*data.TEISHUTUSAKI_CD*/'' != SBN_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD)
	          THEN 2
	          WHEN (HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD != /*data.TEISHUTUSAKI_CD*/'') AND (/*data.TEISHUTUSAKI_CD*/'' = SBN_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD)
	          THEN 3	  
	          WHEN (HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD != /*data.TEISHUTUSAKI_CD*/'') AND (/*data.TEISHUTUSAKI_CD*/'' != SBN_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD)
	          THEN 4
	      END
      END AS HST_KEN_KBN,
      /*END*/
      MANI.UPN_JYUTAKUSHA_CD,
	  JYUTAKU_GYOUSHA.JISHA_KBN AS JYUTAKU_JISHA_KBN,
	  HST_GENBA.JISHA_KBN AS HST_GENBA_JISHA_KBN
FROM
      MANI 
LEFT JOIN M_CHIIKIBETSU_BUNRUI MCB
       ON MANI.HOUKOKUSHO_BUNRUI_CD = MCB.HOUKOKUSHO_BUNRUI_CD
       AND MCB.CHIIKI_CD = /*data.TEISHUTUSAKI_CD*/''
LEFT JOIN M_GYOUSHA HST_GYOUSHA
       ON HST_GYOUSHA.GYOUSHA_CD = MANI.HST_GYOUSHA_CD
LEFT JOIN M_TODOUFUKEN HST_GYOUSHA_MT
       ON HST_GYOUSHA_MT.TODOUFUKEN_CD = HST_GYOUSHA.GYOUSHA_TODOUFUKEN_CD
LEFT JOIN M_GENBA HST_GENBA
       ON HST_GENBA.GYOUSHA_CD = MANI.HST_GYOUSHA_CD
      AND HST_GENBA.GENBA_CD = MANI.HST_GENBA_CD 
LEFT JOIN M_TODOUFUKEN HST_GENBA_MT
       ON HST_GENBA_MT.TODOUFUKEN_CD = HST_GENBA.GENBA_TODOUFUKEN_CD
LEFT JOIN M_SYS_INFO
        ON M_SYS_INFO.SYS_ID = 0
LEFT JOIN M_UNIT MU
       ON MU.UNIT_CD = M_SYS_INFO.MANI_KANSAN_KIHON_UNIT_CD
LEFT JOIN M_CHIIKIBETSU_SHOBUN MCS
       ON MCS.SHOBUN_HOUHOU_CD = MANI.SBN_HOUHOU_CD
	  AND MCS.CHIIKI_CD = /*data.TEISHUTUSAKI_CD*/''
LEFT JOIN M_GYOUSHA SBN_GYOUSHA
       ON SBN_GYOUSHA.GYOUSHA_CD = MANI.SBN_GYOUSHA_CD
LEFT JOIN M_TODOUFUKEN SBN_GYOUSHA_MT
       ON SBN_GYOUSHA_MT.TODOUFUKEN_CD = SBN_GYOUSHA.GYOUSHA_TODOUFUKEN_CD
LEFT JOIN M_GENBA SBN_GENBA
       ON SBN_GENBA.GYOUSHA_CD = MANI.SBN_GYOUSHA_CD
      AND SBN_GENBA.GENBA_CD = MANI.SBN_GENBA_CD 
LEFT JOIN M_TODOUFUKEN SBN_GENBA_MT
       ON SBN_GENBA_MT.TODOUFUKEN_CD = SBN_GENBA.GENBA_TODOUFUKEN_CD
/*IF data.TUMIKAE_HOKAN_KBN == 1*/
LEFT JOIN M_GENBA UPN_SAKI_GENBA
       ON UPN_SAKI_GENBA.GYOUSHA_CD = MANI.UPN_SAKI_GYOUSHA_CD
       AND UPN_SAKI_GENBA.GENBA_CD = MANI.UPN_SAKI_GENBA_CD
/*END*/
LEFT JOIN M_GYOUSHA HWS_GYOUSHA
       ON HWS_GYOUSHA.GYOUSHA_CD = MANI.HIKIWATASHISAKI_CD
LEFT JOIN M_TODOUFUKEN HWS_GYOUSHA_MT
       ON HWS_GYOUSHA_MT.TODOUFUKEN_CD = HWS_GYOUSHA.GYOUSHA_TODOUFUKEN_CD
LEFT JOIN M_CHIIKIBETSU_KYOKA MCK
       ON MCK.GYOUSHA_CD = MANI.HIKIWATASHISAKI_CD
      AND MCK.CHIIKI_CD = HWS_GYOUSHA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD
      AND MCK.GENBA_CD = ''
      AND MCK.KYOKA_KBN = 1
LEFT JOIN M_CHIIKIBETSU_KYOKA MCK_SBN
       ON MCK_SBN.GYOUSHA_CD = MANI.SBN_GYOUSHA_CD
      AND MCK_SBN.GENBA_CD = MANI.SBN_GENBA_CD
      AND MCK_SBN.CHIIKI_CD = SBN_GENBA.CHIIKI_CD
      AND MCK_SBN.KYOKA_KBN = 2
LEFT JOIN M_CHIIKIBETSU_KYOKA MCK_LAST_SBN
       ON MCK_LAST_SBN.GYOUSHA_CD = MANI.SBN_GYOUSHA_CD
      AND MCK_LAST_SBN.GENBA_CD = MANI.SBN_GENBA_CD
      AND MCK_LAST_SBN.CHIIKI_CD = SBN_GENBA.CHIIKI_CD
      AND MCK_LAST_SBN.KYOKA_KBN = 3
LEFT JOIN M_CHIIKI TSS_MC
       ON TSS_MC.CHIIKI_CD = /*data.TEISHUTUSAKI_CD*/''
LEFT JOIN M_CHIIKI HST_MC
       ON HST_MC.CHIIKI_CD = HST_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD
LEFT JOIN M_CHIIKI SBN_MC
       ON SBN_MC.CHIIKI_CD = SBN_GENBA.CHIIKI_CD
LEFT JOIN M_GYOUSHA JYUTAKU_GYOUSHA
       ON JYUTAKU_GYOUSHA.GYOUSHA_CD = CONVERT(NVARCHAR, MANI.UPN_JYUTAKUSHA_CD) 
)
SELECT SYSTEM_ID,
       SEQ,
       DETAIL_SYSTEM_ID,
       KANRI_ID,
       DEN_SEQ,
       MANIFEST_ID,
       HAIKI_KBN_CD,
       HOUKOKUSHO_BUNRUI_CD,
       HOUKOKUSHO_BUNRUI_NAME,
       HAIKI_SHURUI_CD,
       HAIKI_SHURUI_NAME,
       SEKIMEN_KBN,
       TOKUTEI_YUUGAI_KBN,
       SAIITAKU_KYOKA_NO,
       HST_GYOUSHA_CD,
       HST_GYOUSHA_NAME,
       HST_GYOUSHA_ADDRESS,
       HST_GYOUSHA_GYOUSHU_CD,
       HST_GENBA_CD,
       HST_GENBA_NAME,
       HST_GENBA_ADDRESS,
       HST_GENBA_GYOUSHU_CD,
       HST_GENBA_CHIIKI_CD,
       JYUTAKU_RYOU,
       JYUTAKU_KBN,
       JYUTAKU_UNIT_NAME,
       SHOBUN_HOUHOU_CD,
       SHOBUN_HOUHOU_NAME,
       SHOBUN_MOKUTEKI_CD,
       SHOBUN_MOKUTEKI_NAME,
       SBN_GYOUSHA_CD,
       SBN_GYOUSHA_NAME,
       SBN_GYOUSHA_ADDRESS,
       SBN_GENBA_CD,
       SBN_GENBA_NAME,
       SBN_GENBA_ADDRESS,
       SBN_GENBA_CHIIKI_CD,
       UPN_RYOU,
	   UPN_ROUTE_NO,
	   HIKIWATASHISAKI_CD,
	   HIKIWATASHISAKI_NAME,
	   HIKIWATASHISAKI_ADDRESS,
	   HIKIWATASHISAKI_CHIIKI_CD,
	   HIKIWATASHISAKI_KYOKA_NO,
	   HIKIWATASHI_RYOU,
       HIKIWATASHI_KBN,
	   CONVERT(VARCHAR, CHIIKI_CD2) AS CHIIKI_CD2,
       CONVERT(VARCHAR, TODOUFUKEN_CD) AS TODOUFUKEN_CD,
       CONVERT(VARCHAR, CHIIKI_CD3) AS CHIIKI_CD3,
       CONVERT(VARCHAR, TODOUFUKEN_CD2) AS TODOUFUKEN_CD2,
       CONVERT(VARCHAR, HST_KEN_KBN) AS HST_KEN_KBN,
	   UPN_JYUTAKUSHA_CD,
	   JYUTAKU_JISHA_KBN,
	   HST_GENBA_JISHA_KBN
FROM SEARCH_DATA
WHERE 1 = 1
AND HST_KEN_KBN IS NOT NULL
/*IF data.CHUSHUTU_JOKEN_KBN_ARRAY.Length > 0*/
   /*IF data.TUMIKAE_HOKAN_KBN == 2*/
       AND ((SEARCH_DATA.HAIKI_KBN_CD IN (1) AND SEARCH_DATA.HST_KEN_KBN IN /*data.CHUSHUTU_JOKEN_KBN_ARRAY*/(1,2,3,4)) 
	       OR SEARCH_DATA.HAIKI_KBN_CD IN (2,3,4))
   /*END*/
   /*IF data.TUMIKAE_HOKAN_KBN == 1*/
      AND SEARCH_DATA.HST_KEN_KBN IN /*data.CHUSHUTU_JOKEN_KBN_ARRAY*/(1,2,3,4)
   /*END*/
/*END*/
/*IF data.JISHA_KBN == 2*/
    AND HST_GENBA_JISHA_KBN != 1
/*END*/
ORDER BY SYSTEM_ID, SEQ, DETAIL_SYSTEM_ID, KANRI_ID, DEN_SEQ, UPN_ROUTE_NO
         




       