
SELECT ISNULL(M_GYOUSHA.GYOUSHA_CD,'') AS GYOUSHA_CD
     , M_GYOUSHA.GYOUSHA_NAME_RYAKU AS GYOUSHA_NAME_RYAKU

  FROM M_GYOUSHA 

 WHERE M_GYOUSHA.GYOUSHAKBN_MANI = 'true'
   AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 'true'
/*IF data.GYOUSHA_CD != null && data.GYOUSHA_CD != ''*/ AND M_GYOUSHA.GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/