
SELECT ISNULL(M_TORIHIKISAKI.TORIHIKISAKI_CD,'') AS TORIHIKISAKI_CD
     , M_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU AS TORIHIKISAKI_NAME_RYAKU

  FROM M_TORIHIKISAKI 

 WHERE M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 'true'
/*IF data.TORIHIKISAKI_CD != null && data.TORIHIKISAKI_CD != ''*/ AND M_TORIHIKISAKI.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*//*END*/