SELECT --20250318
	GURUPU.*
FROM
	dbo.M_GURUPU_NYURYOKU GURUPU
WHERE
	GURUPU.DENPYOU_KBN_CD =/*data.DENPYOU_KBN_CD*/1
	AND GURUPU.DELETE_FLG = 0
ORDER BY GURUPU.DENPYOU_KBN_CD, GURUPU.GURUPU_CD

--SELECT 
--    GURUPU.*
--FROM 
--    dbo.M_GURUPU_NYURYOKU GURUPU
--/*BEGIN*/WHERE
-- /*IF !data.GURUPU_CD.IsNull */GURUPU.GURUPU_CD =/*data.GURUPU_CD*/0/*END*/
-- /*IF data.GURUPU_NAME != null*/AND GURUPU.GURUPU_NAME LIKE '%' +  /*data.GURUPU_NAME*/ + '%'/*END*/
-- /*IF data.UPDATE_USER != null*/AND UNIT.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
-- /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, UNIT.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
-- /*IF data.CREATE_USER != null*/AND UNIT.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
-- /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, UNIT.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
--/*END*/
--ORDER BY GURUPU.GURUPU_CD