SELECT 
  MUT.*
 ,MUT.UNPAN_GYOUSHA_CD AS UK_UNPAN_GYOUSHA_CD
 ,MUT.UNCHIN_HINMEI_CD AS UK_UNCHIN_HINMEI_CD
 ,MUT.UNIT_CD AS UK_UNIT_CD
 ,MUT.SHASHU_CD AS UK_SHASHU_CD
FROM 
 dbo.M_UNCHIN_TANKA MUT
WHERE
1 = 1
 /*IF data.UNPAN_GYOUSHA_CD != null*/AND MUT.UNPAN_GYOUSHA_CD = /*data.UNPAN_GYOUSHA_CD*/''/*END*/
ORDER BY MUT.UNCHIN_HINMEI_CD
