SELECT 
    UNCHIN_HINMEI_CD,UNCHIN_HINMEI_NAME
FROM 
    dbo.M_UNCHIN_HINMEI
WHERE
 DELETE_FLG = 0
AND UNCHIN_HINMEI_CD = /*data.UNCHIN_HINMEI_CD*/''
GROUP BY UNCHIN_HINMEI_CD, UNCHIN_HINMEI_NAME
ORDER BY UNCHIN_HINMEI_CD, UNCHIN_HINMEI_NAME
