SELECT
	MGE.GYOUSHA_CD,
	MGY.GYOUSHA_NAME_RYAKU,
	MGE.GENBA_CD,
	MGE.GENBA_NAME_RYAKU,
	MGE.MANI_HENSOUSAKI_USE_A,
	MGE.MANI_HENSOUSAKI_USE_B1,
	MGE.MANI_HENSOUSAKI_USE_B2,
	MGE.MANI_HENSOUSAKI_USE_B4,
	MGE.MANI_HENSOUSAKI_USE_B6,
	MGE.MANI_HENSOUSAKI_USE_C1,
	MGE.MANI_HENSOUSAKI_USE_C2,
	MGE.MANI_HENSOUSAKI_USE_D,
	MGE.MANI_HENSOUSAKI_USE_E
FROM
	M_GYOUSHA AS MGY 
	LEFT JOIN M_GENBA AS MGE ON MGY.GYOUSHA_CD = MGE.GYOUSHA_CD
WHERE
/*IF gyoshaCd != "" && genbaCd != ""*/
	MGE.GYOUSHA_CD = /*gyoshaCd*/
	AND MGE.GENBA_CD = /*genbaCd*/
	/*IF joken == 2*/AND MGE.MANI_HENSOUSAKI_KBN = 1/*END*/
/*END*/