SELECT 
M_HAIKI_SHURUI.HAIKI_KBN_CD, 
M_HAIKI_KBN.HAIKI_KBN_NAME_RYAKU, 
M_HAIKI_SHURUI.HAIKI_SHURUI_CD, 
M_HAIKI_SHURUI.HAIKI_SHURUI_NAME_RYAKU
FROM M_HAIKI_SHURUI 
LEFT JOIN M_HAIKI_KBN ON M_HAIKI_SHURUI.HAIKI_KBN_CD = M_HAIKI_KBN.HAIKI_KBN_CD 
AND M_HAIKI_KBN.DELETE_FLG = 0
/*$whereSql*/ 
