SELECT
	MASTER_GENBA.M_GYOUSHA_CD,
	MASTER_GENBA.M_GYOUSHA_NAME1,
	MASTER_GENBA.M_GYOUSHA_RYAKU,
	MASTER_GENBA.M_GYOUSHA_FURIGANA,
	MASTER_GENBA.M_GENBA_CD,
	MASTER_GENBA.M_GENBA_NAME1,
	MASTER_GENBA.M_GENBA_NAME_RYAKU,
	MASTER_GENBA.M_GENBA_FURIGANA,
	MASTER_GENBA.M_GENBA_POST,
	MASTER_TODOUFUKEN.M_TODOUFUKEN_NAME_RYAKU,
	MASTER_GENBA.M_GENBA_ADDRESS1,
	MASTER_GENBA.M_GENBA_ADDRESS2,
	MASTER_GENBA.M_GENBA_TEL,
	MASTER_GENBA.M_BIKOU1,
	MASTER_GENBA.M_BIKOU2,
	MASTER_GENBA.M_BIKOU3,
	MASTER_GENBA.M_BIKOU4
FROM
	 (
		SELECT 
			M_GYOUSHA.GYOUSHA_CD AS M_GYOUSHA_CD,
			M_GYOUSHA.GYOUSHA_NAME1 AS M_GYOUSHA_NAME1,
			M_GYOUSHA.GYOUSHA_NAME_RYAKU AS M_GYOUSHA_RYAKU,
			M_GYOUSHA.GYOUSHA_FURIGANA AS M_GYOUSHA_FURIGANA,
			M_GENBA.GENBA_CD AS M_GENBA_CD,
			M_GENBA.GENBA_NAME1 AS M_GENBA_NAME1,
			M_GENBA.GENBA_NAME_RYAKU AS M_GENBA_NAME_RYAKU,
			M_GENBA.GENBA_FURIGANA AS M_GENBA_FURIGANA,
			M_GENBA.GENBA_POST AS M_GENBA_POST,
			M_GENBA.GENBA_TODOUFUKEN_CD AS M_GENBA_TODOUFUKEN_CD,
			M_GENBA.GENBA_ADDRESS1 AS M_GENBA_ADDRESS1,
			M_GENBA.GENBA_ADDRESS2 AS M_GENBA_ADDRESS2,
			M_GENBA.GENBA_TEL AS M_GENBA_TEL,
			M_GENBA.BIKOU1 AS M_BIKOU1,
			M_GENBA.BIKOU2 AS M_BIKOU2,
			M_GENBA.BIKOU3 AS M_BIKOU3,
			M_GENBA.BIKOU4 AS M_BIKOU4
		FROM
			M_GENBA,M_GYOUSHA
		WHERE
			M_GENBA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
			AND (M_GENBA.SHOBUN_NIOROSHI_GENBA_KBN <> 0 OR M_GENBA.SAISHUU_SHOBUNJOU_KBN <> 0)
			AND M_GENBA.DELETE_FLG = 0
	) MASTER_GENBA LEFT JOIN
	(
		SELECT 
			TODOUFUKEN_NAME_RYAKU AS M_TODOUFUKEN_NAME_RYAKU,
			TODOUFUKEN_CD AS M_TODOUFUKEN_CD
		FROM M_TODOUFUKEN
	) MASTER_TODOUFUKEN
	
	ON MASTER_GENBA.M_GENBA_TODOUFUKEN_CD = MASTER_TODOUFUKEN.M_TODOUFUKEN_CD
	ORDER BY MASTER_GENBA.M_GYOUSHA_CD
