SELECT 
M_KYOTEN.KYOTEN_CD,
M_KYOTEN.KYOTEN_NAME,
M_KYOTEN.KYOTEN_POST,
M_TODOUFUKEN.TODOUFUKEN_NAME_RYAKU,
M_KYOTEN.KYOTEN_ADDRESS1,
M_KYOTEN.KYOTEN_ADDRESS2,
M_KYOTEN.KYOTEN_TEL
FROM
M_KYOTEN
LEFT JOIN (
	SELECT * FROM M_TODOUFUKEN
) AS M_TODOUFUKEN
ON
M_KYOTEN.KYOTEN_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD
WHERE M_KYOTEN.DELETE_FLG = 0
