SELECT
	RESULT_HAIHSHA.M_TEIKI_HAISHA_NUMBER,
	RESULT_HAIHSHA.M_COURSE_NAME_CD,
	RESULT_HAIHSHA.M_COURSE_NAME,
	RESULT_HAIHSHA.M_UNPAN_GYOUSHA_CD,
	RESULT_HAIHSHA.M_ROW_NUMBER,
	RESULT_HAIHSHA.M_GYOUSHA_CD,
	RESULT_HAIHSHA.M_GENBA_CD,
	RESULT_HAIHSHA.M_HINMEI_CD,
	RESULT_HAIHSHA.M_UNIT_CD,
	RESULT_HAIHSHA.M_SAGYOU_DATE,
	RESULT_HAIHSHA.M_UNTENSHA_CD,
	RESULT_HAIHSHA.M_SHARYOU_CD,
	RESULT_HAIHSHA.M_NIOROSHI_NUMBER,
	T_TEIKI_HAISHA_NIOROSHI.NIOROSHI_NUMBER,
	T_TEIKI_HAISHA_NIOROSHI.NIOROSHI_GYOUSHA_CD,
	T_TEIKI_HAISHA_NIOROSHI.NIOROSHI_GENBA_CD,
	RESULT_HAIHSHA.M_KANSAN_UNIT_CD
FROM
	(
		SELECT 
			T_TEIKI_HAISHA_ENTRY.TEIKI_HAISHA_NUMBER AS M_TEIKI_HAISHA_NUMBER,
			T_TEIKI_HAISHA_ENTRY.COURSE_NAME_CD AS M_COURSE_NAME_CD,
			M_COURSE_NAME.COURSE_NAME AS M_COURSE_NAME,
			T_TEIKI_HAISHA_ENTRY.UNPAN_GYOUSHA_CD AS M_UNPAN_GYOUSHA_CD,
			T_TEIKI_HAISHA_DETAIL.ROW_NUMBER AS M_ROW_NUMBER,
			T_TEIKI_HAISHA_DETAIL.GYOUSHA_CD AS M_GYOUSHA_CD,
			T_TEIKI_HAISHA_DETAIL.GENBA_CD AS M_GENBA_CD,
			T_TEIKI_HAISHA_SHOUSAI.HINMEI_CD AS M_HINMEI_CD,
			T_TEIKI_HAISHA_SHOUSAI.UNIT_CD AS M_UNIT_CD,
			T_TEIKI_HAISHA_ENTRY.SAGYOU_DATE AS M_SAGYOU_DATE,
			T_TEIKI_HAISHA_ENTRY.UNTENSHA_CD AS M_UNTENSHA_CD,
			T_TEIKI_HAISHA_ENTRY.SHARYOU_CD AS M_SHARYOU_CD,
			T_TEIKI_HAISHA_SHOUSAI.NIOROSHI_NUMBER AS M_NIOROSHI_NUMBER,
			T_TEIKI_HAISHA_ENTRY.SYSTEM_ID AS M_SYSTEM_ID,
			T_TEIKI_HAISHA_ENTRY.SEQ AS M_SEQ,
			(CASE T_TEIKI_HAISHA_SHOUSAI.KANSAN_UNIT_MOBILE_OUTPUT_FLG
			   WHEN 1 THEN T_TEIKI_HAISHA_SHOUSAI.KANSAN_UNIT_CD
			   ELSE NULL END) AS M_KANSAN_UNIT_CD
		FROM 
			T_TEIKI_HAISHA_ENTRY,M_COURSE_NAME,T_TEIKI_HAISHA_DETAIL,T_TEIKI_HAISHA_SHOUSAI
		WHERE
			M_COURSE_NAME.COURSE_NAME_CD = T_TEIKI_HAISHA_ENTRY.COURSE_NAME_CD
			
			AND T_TEIKI_HAISHA_ENTRY.DELETE_FLG = 0
			
			AND T_TEIKI_HAISHA_DETAIL.SYSTEM_ID = T_TEIKI_HAISHA_SHOUSAI.SYSTEM_ID
			AND T_TEIKI_HAISHA_DETAIL.SEQ = T_TEIKI_HAISHA_SHOUSAI.SEQ
			AND T_TEIKI_HAISHA_DETAIL.DETAIL_SYSTEM_ID = T_TEIKI_HAISHA_SHOUSAI.DETAIL_SYSTEM_ID
			AND T_TEIKI_HAISHA_DETAIL.TEIKI_HAISHA_NUMBER = T_TEIKI_HAISHA_SHOUSAI.TEIKI_HAISHA_NUMBER
			
			AND T_TEIKI_HAISHA_ENTRY.SYSTEM_ID = T_TEIKI_HAISHA_SHOUSAI.SYSTEM_ID
			AND T_TEIKI_HAISHA_ENTRY.SEQ = T_TEIKI_HAISHA_SHOUSAI.SEQ
			AND T_TEIKI_HAISHA_ENTRY.TEIKI_HAISHA_NUMBER = T_TEIKI_HAISHA_SHOUSAI.TEIKI_HAISHA_NUMBER

			AND T_TEIKI_HAISHA_ENTRY.SYSTEM_ID = T_TEIKI_HAISHA_DETAIL.SYSTEM_ID
			AND T_TEIKI_HAISHA_ENTRY.SEQ = T_TEIKI_HAISHA_DETAIL.SEQ
			AND T_TEIKI_HAISHA_ENTRY.TEIKI_HAISHA_NUMBER = T_TEIKI_HAISHA_DETAIL.TEIKI_HAISHA_NUMBER

			/*IF !data.KYOTEN_CD_TEIKI.IsNull*/ 
			AND T_TEIKI_HAISHA_ENTRY.KYOTEN_CD = /*data.KYOTEN_CD_TEIKI.Value*/
			/*END*/

			/*IF data.SAGYOU_DATE_TEIKI_FROM != null*/
			AND CONVERT(DATETIME, CONVERT(nvarchar, /*data.SAGYOU_DATE_TEIKI_FROM*/ , 111), 111) <= CONVERT(DATETIME, T_TEIKI_HAISHA_ENTRY.SAGYOU_DATE , 111)
			/*END*/
				
			/*IF data.SAGYOU_DATE_TEIKI_TO != null*/
			AND CONVERT(DATETIME, T_TEIKI_HAISHA_ENTRY.SAGYOU_DATE, 111) <= CONVERT(DATETIME, CONVERT(nvarchar, /*data.SAGYOU_DATE_TEIKI_TO*/ , 111), 111)
			/*END*/
	) RESULT_HAIHSHA LEFT JOIN T_TEIKI_HAISHA_NIOROSHI
		ON RESULT_HAIHSHA.M_SYSTEM_ID = T_TEIKI_HAISHA_NIOROSHI.SYSTEM_ID
		AND RESULT_HAIHSHA.M_SEQ = T_TEIKI_HAISHA_NIOROSHI.SEQ
		AND RESULT_HAIHSHA.M_NIOROSHI_NUMBER = T_TEIKI_HAISHA_NIOROSHI.NIOROSHI_NUMBER
	  LEFT JOIN (SELECT * FROM T_TEIKI_JISSEKI_ENTRY WHERE DELETE_FLG = 0) AS T_TEIKI_JISSEKI_ENTRY
	  ON RESULT_HAIHSHA.M_TEIKI_HAISHA_NUMBER = T_TEIKI_JISSEKI_ENTRY.TEIKI_HAISHA_NUMBER
	  WHERE T_TEIKI_JISSEKI_ENTRY.SYSTEM_ID IS NULL
	ORDER BY RESULT_HAIHSHA.M_TEIKI_HAISHA_NUMBER,RESULT_HAIHSHA.M_UNTENSHA_CD,RESULT_HAIHSHA.M_ROW_NUMBER,RESULT_HAIHSHA.M_GENBA_CD,RESULT_HAIHSHA.M_HINMEI_CD
