SELECT 
	T_UKETSUKE_SS_ENTRY.UKETSUKE_NUMBER,
	T_UKETSUKE_SS_ENTRY.GYOUSHA_CD,
	T_UKETSUKE_SS_ENTRY.GENBA_CD,
	T_UKETSUKE_SS_DETAIL.HINMEI_CD,
	T_UKETSUKE_SS_DETAIL.UNIT_CD,
	T_UKETSUKE_SS_ENTRY.UNTENSHA_CD,
	CASE 
		WHEN T_UKETSUKE_SS_ENTRY.SAGYOU_DATE IS NULL 
		THEN GETDATE()+1
		ELSE T_UKETSUKE_SS_ENTRY.SAGYOU_DATE END AS SAGYOU_DATE,
	T_UKETSUKE_SS_ENTRY.UNPAN_GYOUSHA_CD,
	T_UKETSUKE_SS_ENTRY.SHARYOU_CD,
	T_UKETSUKE_SS_ENTRY.SYSTEM_ID,
	T_UKETSUKE_SS_ENTRY.SEQ,
	T_UKETSUKE_SS_ENTRY.NIOROSHI_GYOUSHA_CD,
	T_UKETSUKE_SS_ENTRY.NIOROSHI_GENBA_CD,
	T_UKETSUKE_SS_ENTRY.GENCHAKU_TIME_NAME,
	T_UKETSUKE_SS_ENTRY.GENCHAKU_TIME,
	T_UKETSUKE_SS_ENTRY.NIOROSHI_DATE,
	T_UKETSUKE_SS_ENTRY.UNTENSHA_SIJIJIKOU1,
	T_UKETSUKE_SS_ENTRY.UNTENSHA_SIJIJIKOU2,
	T_UKETSUKE_SS_ENTRY.UNTENSHA_SIJIJIKOU3
FROM 
	T_UKETSUKE_SS_ENTRY,T_UKETSUKE_SS_DETAIL
WHERE
	T_UKETSUKE_SS_ENTRY.SYSTEM_ID = T_UKETSUKE_SS_DETAIL.SYSTEM_ID
	AND T_UKETSUKE_SS_ENTRY.SEQ = T_UKETSUKE_SS_DETAIL.SEQ
	AND T_UKETSUKE_SS_ENTRY.UKETSUKE_NUMBER = T_UKETSUKE_SS_DETAIL.UKETSUKE_NUMBER
	AND T_UKETSUKE_SS_ENTRY.DELETE_FLG = 0
	AND ( HAISHA_SHURUI_CD = 1 OR HAISHA_SHURUI_CD = 3)
	AND T_UKETSUKE_SS_ENTRY.COURSE_NAME_CD IS NULL
	/*IF !data.HAISHA_JOKYO_CD_SPOT_SS.IsNull*/ 
	AND T_UKETSUKE_SS_ENTRY.HAISHA_JOKYO_CD = /*data.HAISHA_JOKYO_CD_SPOT_SS.Value*/
	/*END*/
	/*IF !data.KYOTEN_CD_SPOT_SS.IsNull*/ 
	AND T_UKETSUKE_SS_ENTRY.KYOTEN_CD = /*data.KYOTEN_CD_SPOT_SS.Value*/
	/*END*/
	/*IF data.SAGYOU_DATE_SPOT_SS_FROM != null && data.SAGYOU_DATE_SPOT_SS_TO != null*/
	AND
	(
		(
			CONVERT(DATETIME, CONVERT(nvarchar, /*data.SAGYOU_DATE_SPOT_SS_FROM*/ , 111), 111) <= CONVERT(DATETIME, T_UKETSUKE_SS_ENTRY.SAGYOU_DATE , 111)
			AND
			CONVERT(DATETIME, T_UKETSUKE_SS_ENTRY.SAGYOU_DATE, 111) <= CONVERT(DATETIME, CONVERT(nvarchar, /*data.SAGYOU_DATE_SPOT_SS_TO*/ , 111), 111)
			/*END*/
		)
		OR
		(
			(
				CONVERT(DATETIME, CONVERT(nvarchar, /*data.SAGYOU_DATE_SPOT_SS_FROM*/ , 111), 111) <= CONVERT(DATETIME, T_UKETSUKE_SS_ENTRY.SAGYOU_DATE_BEGIN , 111)
				AND
				CONVERT(DATETIME, T_UKETSUKE_SS_ENTRY.SAGYOU_DATE_BEGIN , 111) <= CONVERT(DATETIME, CONVERT(nvarchar, /*data.SAGYOU_DATE_SPOT_SS_TO*/ , 111), 111)
			)
			OR 
			(
				CONVERT(DATETIME, CONVERT(nvarchar, /*data.SAGYOU_DATE_SPOT_SS_FROM*/ , 111), 111) <= CONVERT(DATETIME, T_UKETSUKE_SS_ENTRY.SAGYOU_DATE_END , 111)
				AND
				CONVERT(DATETIME, T_UKETSUKE_SS_ENTRY.SAGYOU_DATE_END , 111) <= CONVERT(DATETIME, CONVERT(nvarchar, /*data.SAGYOU_DATE_SPOT_SS_TO*/ , 111), 111)
			)
		)
		OR
		(
			CONVERT(DATETIME, T_UKETSUKE_SS_ENTRY.SAGYOU_DATE_BEGIN , 111)  <= CONVERT(DATETIME, CONVERT(nvarchar, /*data.SAGYOU_DATE_SPOT_SS_FROM*/ , 111), 111)
			AND
			CONVERT(DATETIME, CONVERT(nvarchar, /*data.SAGYOU_DATE_SPOT_SS_END*/ , 111), 111)  <= CONVERT(DATETIME, T_UKETSUKE_SS_ENTRY.SAGYOU_DATE_END , 111)
		)
	)
	/*END*/
ORDER BY     T_UKETSUKE_SS_ENTRY.SAGYOU_DATE, T_UKETSUKE_SS_ENTRY.UKETSUKE_NUMBER, T_UKETSUKE_SS_ENTRY.UNTENSHA_CD, T_UKETSUKE_SS_DETAIL.ROW_NO
