SELECT 
	0 AS TAISHO
	,DEL.ROW_NUMBER
	,0 AS NIOROSHI
	,NULL AS UKETSUKE_NUMBER	--スポット用のため未使用
	,NULL AS GENCHAKU_TIME_NAME	--スポット用のため未使用
	,NULL AS GENCHAKU_TIME		--スポット用のため未使用
	,ENT.TEIKI_HAISHA_NUMBER
	,DEL.GYOUSHA_CD
	,GYO.GYOUSHA_NAME_RYAKU
	,DEL.GENBA_CD
	,GEN.GENBA_NAME_RYAKU
	,GEN.GENBA_ADDRESS1 AS GENBA_ADDRESS
	,ENT.SHASHU_CD
	,ENT.SHARYOU_CD
	,ENT.UNTENSHA_CD
	,ENT.UNPAN_GYOUSHA_CD
	,ENT.SAGYOU_DATE AS DELIVERY_DATE
	,ENT.SYSTEM_ID AS REF_SYSTEM_ID
	,DEL.DETAIL_SYSTEM_ID AS REF_DETAIL_SYSTEM_ID
	,3 AS DENPYOU_ATTR
	,MGD.POINT_ID
	,CASE ISNULL(MDOG.GYOUSHA_CD, '')
	WHEN '' THEN '未連携'
	ELSE '済'
	END AS RENKEI_JYOUKYOU
	,MDSS.DIGI_SHASHU_CD
	,MDSR.DIGI_SHARYOU_CD
	,ENT.COURSE_NAME_CD
	,MCS.COURSE_NAME
	,0 AS NIZUMI_NIOROSHI_FLG

FROM T_TEIKI_HAISHA_ENTRY AS ENT
LEFT JOIN T_TEIKI_HAISHA_DETAIL AS DEL ON ENT.SYSTEM_ID = DEL.SYSTEM_ID AND ENT.SEQ = DEL.SEQ
LEFT JOIN M_GYOUSHA AS GYO ON DEL.GYOUSHA_CD = GYO.GYOUSHA_CD
LEFT JOIN M_GENBA AS GEN ON DEL.GYOUSHA_CD = GEN.GYOUSHA_CD AND DEL.GENBA_CD = GEN.GENBA_CD
LEFT JOIN M_COURSE_NAME MCS ON ENT.COURSE_NAME_CD = MCS.COURSE_NAME_CD
LEFT JOIN M_DIGI_OUTPUT_GENBA AS MDOG ON DEL.GYOUSHA_CD = MDOG.GYOUSHA_CD AND DEL.GENBA_CD = MDOG.GENBA_CD AND MDOG.JYOGAI_FLG = 0	--PointID確認用
LEFT JOIN M_GENBA_DIGI MGD ON DEL.GYOUSHA_CD = MGD.GYOUSHA_CD AND DEL.GENBA_CD = MGD.GENBA_CD	--PointID確認用
LEFT JOIN M_DIGI_OUTPUT_SHASHU MDSS ON ENT.SHASHU_CD = MDSS.SHASHU_CD	--車輌確認用
LEFT JOIN M_DIGI_OUTPUT_SHARYOU MDSR ON ENT.UNPAN_GYOUSHA_CD = MDSR.GYOUSHA_CD AND ENT.SHARYOU_CD = MDSR.SHARYOU_CD	--車輌確認用

WHERE 
	ENT.DELETE_FLG = 0 
	AND (ENT.SHARYOU_CD IS NOT NULL AND ENT.SHARYOU_CD != '')
	AND CONVERT(DATETIME, CONVERT(nvarchar, ENT.SAGYOU_DATE, 111), 120) >= /*searchData.SAGYOU_DATE_FROM*/
	AND CONVERT(DATETIME, CONVERT(nvarchar, ENT.SAGYOU_DATE, 111), 120) <= /*searchData.SAGYOU_DATE_TO*/
	AND NOT EXISTS (SELECT * FROM T_LOGI_DELIVERY_DETAIL WHERE DENPYOU_ATTR = 3 AND DELETE_FLG = 0 AND REF_SYSTEM_ID = ENT.SYSTEM_ID)
	--画面上の条件
	/*IF searchData.GYOUSHA_CD != null && searchData.GYOUSHA_CD != ''*/ AND DEL.GYOUSHA_CD = /*searchData.GYOUSHA_CD*/ /*END*/
	/*IF searchData.GENBA_CD != null && searchData.GENBA_CD != ''*/ AND DEL.GENBA_CD = /*searchData.GENBA_CD*/ /*END*/
	/*IF selectData.SHASHU_CD != null && selectData.SHASHU_CD != ''*/ AND ENT.SHASHU_CD = /*selectData.SHASHU_CD*/ /*END*/
	/*IF selectData.SHARYOU_CD != null && selectData.SHARYOU_CD != ''*/ AND ENT.SHARYOU_CD = /*selectData.SHARYOU_CD*/ /*END*/
	/*IF selectData.UNTENSHA_CD != null && selectData.UNTENSHA_CD != ''*/ AND ENT.UNTENSHA_CD = /*selectData.UNTENSHA_CD*/ /*END*/
	/*IF selectData.UNPAN_GYOUSHA_CD != null && selectData.UNPAN_GYOUSHA_CD != ''*/ AND ENT.UNPAN_GYOUSHA_CD = /*selectData.UNPAN_GYOUSHA_CD*/ /*END*/
	/*IF selectData.COURSE_NAME_CD != null && selectData.COURSE_NAME_CD != ''*/ AND ENT.COURSE_NAME_CD = /*selectData.COURSE_NAME_CD*/ /*END*/
	/*IF selectData.TEIKI_HAISHA_NUMBER != null && selectData.TEIKI_HAISHA_NUMBER != ''*/ AND ENT.TEIKI_HAISHA_NUMBER = /*selectData.TEIKI_HAISHA_NUMBER*/ /*END*/

ORDER BY DEL.ROW_NUMBER