SELECT DISTINCT
	0 AS KUMIKOMI
	,ENT.TEIKI_HAISHA_NUMBER
	,ENT.COURSE_NAME_CD
	,MCN.COURSE_NAME
	,ENT.SHASHU_CD
	,M_SHASHU.SHASHU_NAME_RYAKU
	,ENT.SHARYOU_CD
	,M_SHARYOU.SHARYOU_NAME_RYAKU
	,ENT.UNTENSHA_CD
	,M_SHAIN.SHAIN_NAME_RYAKU AS UNTENSHA_NAME_RYAKU
	,ENT.UNPAN_GYOUSHA_CD
	,M_GYOUSHA.GYOUSHA_NAME_RYAKU AS UNPAN_GYOUSHA_NAME_RYAKU
FROM
	T_TEIKI_HAISHA_ENTRY ENT
	LEFT JOIN T_TEIKI_HAISHA_DETAIL DEL ON ENT.SYSTEM_ID = DEL.SYSTEM_ID AND ENT.SEQ = DEL.SEQ
	LEFT JOIN M_SHASHU ON ENT.SHASHU_CD = M_SHASHU.SHASHU_CD
	LEFT JOIN M_SHARYOU ON ENT.UNPAN_GYOUSHA_CD = M_SHARYOU.GYOUSHA_CD AND ENT.SHARYOU_CD = M_SHARYOU.SHARYOU_CD
	INNER JOIN M_DIGI_OUTPUT_SHARYOU MDSR ON ENT.UNPAN_GYOUSHA_CD = MDSR.GYOUSHA_CD AND ENT.SHARYOU_CD = MDSR.SHARYOU_CD
	LEFT JOIN M_SHAIN ON ENT.UNTENSHA_CD = M_SHAIN.SHAIN_CD
	INNER JOIN M_DIGI_OUTPUT_SHAIN MDSH ON ENT.UNTENSHA_CD = MDSH.SHAIN_CD
	LEFT JOIN M_GYOUSHA ON ENT.UNPAN_GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
	LEFT JOIN M_COURSE_NAME MCN ON ENT.COURSE_NAME_CD = MCN.COURSE_NAME_CD
WHERE
	ENT.DELETE_FLG = 0
	AND (ENT.SHASHU_CD IS NOT NULL AND ENT.SHASHU_CD != '')
	AND (ENT.SHARYOU_CD IS NOT NULL AND ENT.SHARYOU_CD != '')
	AND (ENT.SAGYOU_DATE IS NOT NULL AND ENT.SAGYOU_DATE != '')
	AND (ENT.UNPAN_GYOUSHA_CD IS NOT NULL AND ENT.UNPAN_GYOUSHA_CD != '')
	AND (MDSR.OUTPUT_DATE IS NOT NULL)
	AND (MDSH.OUTPUT_DATE IS NOT NULL)
	AND CONVERT(DATETIME, CONVERT(nvarchar, ENT.SAGYOU_DATE, 111), 120) >= /*data.SAGYOU_DATE_FROM*/
	AND CONVERT(DATETIME, CONVERT(nvarchar, ENT.SAGYOU_DATE, 111), 120) <= /*data.SAGYOU_DATE_TO*/
	AND NOT EXISTS (SELECT * FROM T_LOGI_DELIVERY_DETAIL WHERE DENPYOU_ATTR = 3 AND DELETE_FLG = 0 AND REF_SYSTEM_ID = ENT.SYSTEM_ID)
	--画面上の条件
	/*IF data.GYOUSHA_CD != null && data.GYOUSHA_CD != ''*/ AND DEL.GYOUSHA_CD = /*data.GYOUSHA_CD*/ /*END*/
	/*IF data.GENBA_CD != null && data.GENBA_CD != ''*/ AND DEL.GENBA_CD = /*data.GENBA_CD*/ /*END*/
	/*IF data.UNPAN_GYOUSHA_CD != null && data.UNPAN_GYOUSHA_CD != ''*/ AND ENT.UNPAN_GYOUSHA_CD = /*data.UNPAN_GYOUSHA_CD*/ /*END*/
	/*IF data.SHARYOU_CD != null && data.SHARYOU_CD != ''*/ AND ENT.SHARYOU_CD = /*data.SHARYOU_CD*/ /*END*/
	/*IF data.SHASHU_CD != null && data.SHASHU_CD != ''*/ AND ENT.SHASHU_CD = /*data.SHASHU_CD*/ /*END*/
	/*IF data.UNTENSHA_CD != null && data.UNTENSHA_CD != ''*/ AND ENT.UNTENSHA_CD = /*data.UNTENSHA_CD*/ /*END*/
