SELECT DISTINCT
	1 AS TAISHO
	,DEL.DELIVERY_ORDER AS ROW_NUMBER
	,DEL.NOT_URIAGE_KBN AS NIOROSHI
	,CASE DEL.DENPYOU_ATTR
		WHEN 1 THEN DEL.REF_DENPYOU_NO
		WHEN 2 THEN DEL.REF_DENPYOU_NO
		ELSE NULL
		END AS UKETSUKE_NUMBER
	,CASE DEL.DENPYOU_ATTR
		WHEN 1 THEN SS.GENCHAKU_TIME_NAME
		WHEN 2 THEN SK.GENCHAKU_TIME_NAME
		ELSE NULL
		END AS GENCHAKU_TIME_NAME
	,CASE DEL.DENPYOU_ATTR
		WHEN 1 THEN SS.GENCHAKU_TIME
		WHEN 2 THEN SK.GENCHAKU_TIME
		ELSE NULL
		END AS GENCHAKU_TIME
	,CASE DEL.DENPYOU_ATTR
		WHEN 3 THEN DEL.REF_DENPYOU_NO
		ELSE NULL
		END AS TEIKI_HAISHA_NUMBER
	,DEL.GYOUSHA_CD
	,DEL.GYOUSHA_NAME AS GYOUSHA_NAME_RYAKU
	,DEL.GENBA_CD
	,DEL.GENBA_NAME AS GENBA_NAME_RYAKU
	,GEN.GENBA_ADDRESS1 AS GENBA_ADDRESS
	,ENT.SHASHU_CD
	,ENT.SHARYOU_CD
	,ENT.UNTENSHA_CD
	,ENT.UPN_GYOUSHA_CD AS UNPAN_GYOUSHA_CD
	,ENT.DELIVERY_DATE
	,ENT.SYSTEM_ID
	,DEL.DETAIL_SYSTEM_ID
	,DEL.REF_SYSTEM_ID
	,DEL.REF_DETAIL_SYSTEM_ID
	,DEL.DENPYOU_ATTR
	,ENT.HAISHA_KBN
	,ENT.DELIVERY_NO
	,ENT.DELIVERY_NAME
	,TLS.LINK_STATUS
	-- コースCD、名称取得
	,CASE DEL.DENPYOU_ATTR
		WHEN 3 THEN THE.COURSE_NAME_CD
		ELSE NULL
		END AS COURSE_NAME_CD
	,CASE DEL.DENPYOU_ATTR
		WHEN 3 THEN MCS.COURSE_NAME
		ELSE NULL
		END AS COURSE_NAME
	,MGD.POINT_ID
	,CASE ISNULL(MGD.POINT_ID, '') WHEN '' THEN '未連携' ELSE '済' END AS RENKEI_JYOUKYOU
	,MDSS.DIGI_SHASHU_CD
	,MDSR.DIGI_SHARYOU_CD
	,DEL.NIZUMI_NIOROSHI_FLG
FROM T_LOGI_DELIVERY AS ENT
LEFT JOIN T_LOGI_DELIVERY_DETAIL AS DEL ON ENT.SYSTEM_ID = DEL.SYSTEM_ID
LEFT JOIN T_LOGI_LINK_STATUS AS TLS ON ENT.SYSTEM_ID = TLS.SYSTEM_ID
LEFT JOIN (SELECT * FROM T_UKETSUKE_SS_ENTRY WHERE DELETE_FLG = 0) AS SS ON DEL.REF_SYSTEM_ID = SS.SYSTEM_ID
LEFT JOIN (SELECT * FROM T_UKETSUKE_SK_ENTRY WHERE DELETE_FLG = 0) AS SK ON DEL.REF_SYSTEM_ID = SK.SYSTEM_ID
LEFT JOIN (SELECT * FROM T_TEIKI_HAISHA_ENTRY WHERE DELETE_FLG = 0) AS THE ON DEL.REF_SYSTEM_ID = THE.SYSTEM_ID
LEFT JOIN M_COURSE_NAME AS MCS ON THE.COURSE_NAME_CD = MCS.COURSE_NAME_CD
LEFT JOIN M_GYOUSHA AS GYO ON DEL.GYOUSHA_CD = GYO.GYOUSHA_CD
LEFT JOIN M_GENBA AS GEN ON DEL.GYOUSHA_CD = GEN.GYOUSHA_CD AND DEL.GENBA_CD = GEN.GENBA_CD
LEFT JOIN M_GENBA_DIGI AS MGD ON DEL.GYOUSHA_CD = MGD.GYOUSHA_CD AND DEL.GENBA_CD = MGD.GENBA_CD
LEFT JOIN M_DIGI_OUTPUT_SHASHU MDSS ON ENT.SHASHU_CD = MDSS.SHASHU_CD
LEFT JOIN M_DIGI_OUTPUT_SHARYOU MDSR ON ENT.UPN_GYOUSHA_CD = MDSR.GYOUSHA_CD AND ENT.SHARYOU_CD = MDSR.SHARYOU_CD
WHERE 
	ENT.DELETE_FLG = 0
	AND ENT.SYSTEM_ID = /*systemId*/
