SELECT
  TZUD.DENSHU_KBN_CD,
  TZUD.SYSTEM_ID,
  TZUD.DETAIL_SYSTEM_ID,
  TZUD.SEQ,
  TZUD.ROW_NO,
  TZUD.GYOUSHA_CD,
  TZUD.GENBA_CD,
  TZUD.ZAIKO_HINMEI_CD,
  TZUD.ZAIKO_RITSU,
  TZUD.JYUURYOU,
  TZUD.TANKA,
  TZUD.KINGAKU,
  TZUD.TIME_STAMP,
  TZUD.DELETE_FLG
FROM
  T_ZAIKO_UKEIRE_DETAIL AS TZUD
WHERE
  TZUD.SYSTEM_ID = /*data.SYSTEM_ID*/'' AND
  TZUD.DETAIL_SYSTEM_ID = /*data.DETAIL_SYSTEM_ID*/'' AND
  TZUD.SEQ = /*data.SEQ*/'' AND
  TZUD.DELETE_FLG = 0
ORDER BY
  TZUD.ROW_NO