SELECT
	S_HAIKI.*
    ,ISNULL(K_HAIKI.HAIKI_KBN_NAME,N'') AS HAIKI_KBN_NAME
	,ISNULL(HOUKOKU.HOUKOKUSHO_BUNRUI_NAME_RYAKU,N'') AS HOUKOKUSHO_BUNRUI_NAME_RYAKU
FROM
	dbo.M_HOUKOKUSHO_BUNRUI HOUKOKU
	INNER JOIN dbo.M_HAIKI_SHURUI S_HAIKI ON HOUKOKU.HOUKOKUSHO_BUNRUI_CD = S_HAIKI.HOUKOKUSHO_BUNRUI_CD
	LEFT JOIN dbo.M_HAIKI_KBN K_HAIKI ON S_HAIKI.HAIKI_KBN_CD = K_HAIKI.HAIKI_KBN_CD
/*BEGIN*/WHERE
/*IF !data_S.HAIKI_KBN_CD.IsNull*/ S_HAIKI.HAIKI_KBN_CD = /*data_S.HAIKI_KBN_CD.Value*/1/*END*/
/*IF data_B.HOUKOKUSHO_BUNRUI_CD != null*/ AND HOUKOKU.HOUKOKUSHO_BUNRUI_CD LIKE '%' +  /*data_B.HOUKOKUSHO_BUNRUI_CD*/ + '%'/*END*/
/*IF data_B.HOUKOKUSHO_BUNRUI_NAME_RYAKU != null*/AND HOUKOKU.HOUKOKUSHO_BUNRUI_NAME_RYAKU LIKE '%' +  /*data_B.HOUKOKUSHO_BUNRUI_NAME_RYAKU*/ + '%'/*END*/
/*END*/
 ORDER BY S_HAIKI.HAIKI_KBN_CD, S_HAIKI.HAIKI_SHURUI_CD
