SELECT
    MTS.TORIHIKISAKI_CD AS TORIHIKISAKI_CD,
    MT.TORIHIKISAKI_NAME_RYAKU AS TORIHIKISAKI_NAME_RYAKU,
    MT.EIGYOU_TANTOU_CD AS EIGYOUSHA_CD,
    MS.SHAIN_NAME_RYAKU AS SHAIN_NAME_RYAKU,
    '' AS NYUUKIN_YOTEI_BI,
    MTS.KAISHI_URIKAKE_ZANDAKA AS SEIKYUU_GAKU,
    ISNULL(TNK.KESHIKOMI_GAKU, 0) AS NYUUKIN_GAKU,
    MTS.KAISHI_URIKAKE_ZANDAKA - ISNULL(TNK.KESHIKOMI_GAKU, 0) AS MINYUUKIN_GAKU,
    MTS.SHIMEBI1 AS SHIMEBI,
    '開始残高' AS SEIKYUU_DATE,
    MTS.KAISHUU_HOUHOU AS KAISHUU_HOUHOU,
    MNK.NYUUSHUKKIN_KBN_NAME_RYAKU AS NYUUSHUKKIN_KBN_NAME_RYAKU,
    ISNULL(TNK.SEIKYUU_NUMBER, 0) AS SEIKYUU_NUMBER,
    MT.TORIHIKISAKI_FURIGANA AS TORIHIKISAKI_FURIGANA,
    MS.SHAIN_FURIGANA AS SHAIN_FURIGANA
FROM M_TORIHIKISAKI_SEIKYUU AS MTS
LEFT JOIN (
    SELECT
        TORIHIKISAKI_CD,
        SEIKYUU_NUMBER,
        SUM(KESHIKOMI_GAKU) AS KESHIKOMI_GAKU
    FROM T_NYUUKIN_KESHIKOMI
    WHERE SEIKYUU_NUMBER = 0 AND DELETE_FLG = 0
    GROUP BY TORIHIKISAKI_CD, SEIKYUU_NUMBER
) AS TNK
    ON MTS.TORIHIKISAKI_CD = TNK.TORIHIKISAKI_CD AND TNK.SEIKYUU_NUMBER = 0
LEFT JOIN M_TORIHIKISAKI AS MT
    ON MT.TORIHIKISAKI_CD = MTS.TORIHIKISAKI_CD
LEFT JOIN M_SHAIN AS MS
    ON MS.SHAIN_CD = MT.EIGYOU_TANTOU_CD
LEFT JOIN M_NYUUSHUKKIN_KBN AS MNK
    ON MNK.NYUUSHUKKIN_KBN_CD = MTS.KAISHUU_HOUHOU
WHERE MTS.KAISHI_URIKAKE_ZANDAKA - ISNULL(TNK.KESHIKOMI_GAKU, 0) <> 0
/*IF dto.KyotenCd != null && dto.KyotenCd != 99*/AND MT.TORIHIKISAKI_KYOTEN_CD = /*dto.KyotenCd*/99/*END*/
/*IF dto.EigyoushaCdFrom != null && dto.EigyoushaCdFrom != ''*/AND MT.EIGYOU_TANTOU_CD >= /*dto.EigyoushaCdFrom*/''/*END*/
/*IF dto.EigyoushaCdTo != null && dto.EigyoushaCdTo != ''*/AND MT.EIGYOU_TANTOU_CD <= /*dto.EigyoushaCdTo*/''/*END*/
/*IF dto.TorihikisakiCdFrom != null && dto.TorihikisakiCdFrom != ''*/AND MTS.TORIHIKISAKI_CD >= /*dto.TorihikisakiCdFrom*/''/*END*/
/*IF dto.TorihikisakiCdTo != null && dto.TorihikisakiCdTo != ''*/AND MTS.TORIHIKISAKI_CD <= /*dto.TorihikisakiCdTo*/''/*END*/

UNION ALL

SELECT
    TSD.TORIHIKISAKI_CD,
    MT.TORIHIKISAKI_NAME_RYAKU,
    MT.EIGYOU_TANTOU_CD AS EIGYOUSHA_CD,
    MS.SHAIN_NAME_RYAKU,
    CONVERT(varchar, TSD.NYUUKIN_YOTEI_BI, 111) AS NYUUKIN_YOTEI_BI,
    ISNULL(TSD.KONKAI_URIAGE_GAKU, 0) + ISNULL(TSD.KONKAI_SEI_UTIZEI_GAKU, 0) + ISNULL(TSD.KONKAI_SEI_SOTOZEI_GAKU, 0) + ISNULL(TSD.KONKAI_DEN_UTIZEI_GAKU, 0) + ISNULL(TSD.KONKAI_DEN_SOTOZEI_GAKU, 0) + ISNULL(TSD.KONKAI_MEI_UTIZEI_GAKU, 0) + ISNULL(TSD.KONKAI_MEI_SOTOZEI_GAKU, 0) AS SEIKYUU_GAKU,
    ISNULL(TNK.NYUUKIN_GAKU, 0) AS NYUUKIN_GAKU,
    (ISNULL(TSD.KONKAI_URIAGE_GAKU, 0) + ISNULL(TSD.KONKAI_SEI_UTIZEI_GAKU, 0) + ISNULL(TSD.KONKAI_SEI_SOTOZEI_GAKU, 0) + ISNULL(TSD.KONKAI_DEN_UTIZEI_GAKU, 0) + ISNULL(TSD.KONKAI_DEN_SOTOZEI_GAKU, 0) + ISNULL(TSD.KONKAI_MEI_UTIZEI_GAKU, 0) + ISNULL(TSD.KONKAI_MEI_SOTOZEI_GAKU, 0)) - ISNULL(TNK.NYUUKIN_GAKU, 0) AS MINYUUKIN_GAKU,
    TSD.SHIMEBI,
    CONVERT(varchar, TSD.SEIKYUU_DATE, 111) AS SEIKYUU_DATE,
    MTS.KAISHUU_HOUHOU,
    MNK.NYUUSHUKKIN_KBN_NAME_RYAKU,
    TSD.SEIKYUU_NUMBER AS SEIKYUU_NUMBER,
    MT.TORIHIKISAKI_FURIGANA AS TORIHIKISAKI_FURIGANA,
    MS.SHAIN_FURIGANA AS SHAIN_FURIGANA
FROM T_SEIKYUU_DENPYOU AS TSD
LEFT JOIN (SELECT
    TNK.SEIKYUU_NUMBER,
    SUM(TNK.KESHIKOMI_GAKU) AS NYUUKIN_GAKU
FROM T_NYUUKIN_KESHIKOMI AS TNK
WHERE TNK.DELETE_FLG = 0
GROUP BY TNK.SEIKYUU_NUMBER) TNK
    ON TSD.SEIKYUU_NUMBER = TNK.SEIKYUU_NUMBER
JOIN M_TORIHIKISAKI AS MT
    ON MT.TORIHIKISAKI_CD = TSD.TORIHIKISAKI_CD
JOIN M_TORIHIKISAKI_SEIKYUU AS MTS
    ON MTS.TORIHIKISAKI_CD = MT.TORIHIKISAKI_CD
LEFT JOIN M_SHAIN AS MS
    ON MS.SHAIN_CD = MT.EIGYOU_TANTOU_CD
LEFT JOIN M_NYUUSHUKKIN_KBN AS MNK
    ON MNK.NYUUSHUKKIN_KBN_CD = MTS.KAISHUU_HOUHOU
WHERE TSD.DELETE_FLG = 0
/*IF dto.KyotenCd != null && dto.KyotenCd != 99*/AND TSD.KYOTEN_CD = /*dto.KyotenCd*/99/*END*/
/*IF dto.EigyoushaCdFrom != null && dto.EigyoushaCdFrom != ''*/AND MT.EIGYOU_TANTOU_CD >= /*dto.EigyoushaCdFrom*/''/*END*/
/*IF dto.EigyoushaCdTo != null && dto.EigyoushaCdTo != ''*/AND MT.EIGYOU_TANTOU_CD <= /*dto.EigyoushaCdTo*/''/*END*/
/*IF dto.TorihikisakiCdFrom != null && dto.TorihikisakiCdFrom != ''*/AND TSD.TORIHIKISAKI_CD >= /*dto.TorihikisakiCdFrom*/''/*END*/
/*IF dto.TorihikisakiCdTo != null && dto.TorihikisakiCdTo != ''*/AND TSD.TORIHIKISAKI_CD <= /*dto.TorihikisakiCdTo*/''/*END*/
AND (ISNULL(TSD.KONKAI_URIAGE_GAKU, 0) + ISNULL(TSD.KONKAI_SEI_UTIZEI_GAKU, 0) + ISNULL(TSD.KONKAI_SEI_SOTOZEI_GAKU, 0) + ISNULL(TSD.KONKAI_DEN_UTIZEI_GAKU, 0) + ISNULL(TSD.KONKAI_DEN_SOTOZEI_GAKU, 0) + ISNULL(TSD.KONKAI_MEI_UTIZEI_GAKU, 0) + ISNULL(TSD.KONKAI_MEI_SOTOZEI_GAKU, 0)) - ISNULL(TNK.NYUUKIN_GAKU, 0) <> 0
AND CONVERT(varchar, TSD.NYUUKIN_YOTEI_BI, 111) <= CONVERT(varchar, GETDATE(), 111)

/*IF dto.Sort1 == 1 && dto.Sort2 == 1*/
ORDER BY EIGYOUSHA_CD, TORIHIKISAKI_CD, SEIKYUU_NUMBER
/*END*/
/*IF dto.Sort1 == 1 && dto.Sort2 == 2*/
ORDER BY SHAIN_FURIGANA, EIGYOUSHA_CD, TORIHIKISAKI_CD, SEIKYUU_NUMBER
/*END*/
/*IF dto.Sort1 == 2 && dto.Sort2 == 1*/
ORDER BY TORIHIKISAKI_CD, EIGYOUSHA_CD, SEIKYUU_NUMBER
/*END*/
/*IF dto.Sort1 == 2 && dto.Sort2 == 2*/
ORDER BY TORIHIKISAKI_FURIGANA, TORIHIKISAKI_CD, EIGYOUSHA_CD, SEIKYUU_NUMBER
/*END*/