//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shougun.Core.SalesPayment.SyukkaNyuuryoku2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DenpyouCtrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DenpyouCtrl"]));
            }
            set {
                this["DenpyouCtrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DetailCtrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DetailCtrl"]));
            }
            set {
                this["DetailCtrl"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>KYOTEN_CD:拠点CD:True:0</string>
  <string>UKETSUKE_NUMBER:受付番号:True:1</string>
  <string>KEIRYOU_NUMBER:計量番号:True:2</string>
  <string>NYUURYOKU_TANTOUSHA_CD:入力担当者:True:3</string>
  <string>ENTRY_NUMBER:出荷番号:True:4</string>
  <string>RENBAN:年連番/日連番:True:5</string>
  <string>KAKUTEI_KBN:確定区分:True:6</string>
  <string>DENPYOU_DATE:伝票日付:True:7</string>
  <string>UNPAN_GYOUSHA_CD:運搬業者CD:True:8</string>
  <string>UNPAN_GYOUSHA_NAME:運搬業者名:True:9</string>
  <string>SHARYOU_CD:車輌CD:True:10</string>
  <string>SHARYOU_NAME_RYAKU:車輌名:True:11</string>
  <string>NINZUU_CNT:人数:True:12</string>
  <string>GYOUSHA_CD:業者CD:True:13</string>
  <string>GYOUSHA_NAME_RYAKU:業者名:True:14</string>
  <string>GENBA_CD:現場CD:True:15</string>
  <string>GENBA_NAME_RYAKU:現場名:True:16</string>
  <string>TORIHIKISAKI_CD:取引先CD:True:17</string>
  <string>TORIHIKISAKI_NAME_RYAKU:取引先名:True:18</string>
  <string>KEITAI_KBN_CD:形態区分CD:True:19</string>
  <string>DENPYOU_BIKOU:伝票備考:True:20</string>
  <string>TAIRYUU_BIKOU:滞留備考:True:21</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ApDenpyouCtrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ApDenpyouCtrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>STACK_JYUURYOU:総重量:True:0</string>
  <string>EMPTY_JYUURYOU:空車重量:True:1</string>
  <string>WARIFURI_JYUURYOU:割振(Kg):True:2</string>
  <string>WARIFURI_PERCENT:割振(%):True:3</string>
  <string>CHOUSEI_JYUURYOU:調整(Kg):True:4</string>
  <string>CHOUSEI_PERCENT:調整(%):True:5</string>
  <string>YOUKI_CD:容器:True:6</string>
  <string>YOUKI_SUURYOU:容器数量:True:7</string>
  <string>YOUKI_JYUURYOU:容器重量:True:8</string>
  <string>HINMEI_CD:品名CD:True:9</string>
  <string>HINMEI_NAME:品名:True:10</string>
  <string>SUURYOU:数量:True:11</string>
  <string>UNIT_CD:単位CD:True:12</string>
  <string>TANKA:単価:True:13</string>
  <string>KINGAKU:金額:True:14</string>
  <string>NISUGATA_SUURYOU:荷姿数量:True:15</string>
  <string>NISUGATA_UNIT_CD:荷姿単位CD:True:16</string>
  <string>ZAIKO_HINMEI_CD:在庫品名CD:True:17</string>
  <string>MEISAI_BIKOU:明細備考:True:18</string>
  <string>MANIFEST_ID:ﾏﾆﾌｪｽﾄ番号:True:19</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ApDetailCtrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ApDetailCtrl"]));
            }
        }
    }
}
