SELECT DISTINCT N'車輌マスタ' AS NAME, SHASYU_CD FROM M_SHARYOU WHERE SHASYU_CD IN /*SHASHU_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'運賃単価マスタ' AS NAME, SHASHU_CD AS SHASHU_CD  FROM M_UNCHIN_TANKA WHERE SHASHU_CD IN /*SHASHU_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'コースマスタ' AS NAME, SHASHU_CD FROM M_COURSE WHERE SHASHU_CD IN /*SHASHU_CD*/('') AND DELETE_FLG = 'False'
