SELECT
    T_UNCHIN_ENTRY.KYOTEN_CD,
    (SELECT KYOTEN_NAME_RYAKU FROM M_KYOTEN WHERE M_KYOTEN.KYOTEN_CD = T_UNCHIN_ENTRY.KYOTEN_CD) AS KYOTEN_NAME,
    T_UNCHIN_ENTRY.NIOROSHI_GYOUSHA_CD,
    -- 20150525 欠落した形態区分追加(運賃不具合一覧162) Start
    T_UNCHIN_ENTRY.KEITAI_KBN_CD,
    (SELECT KEITAI_KBN_NAME_RYAKU FROM M_KEITAI_KBN WHERE M_KEITAI_KBN.KEITAI_KBN_CD = T_UNCHIN_ENTRY.KEITAI_KBN_CD) AS KEITAI_KBN_NAME,
    -- 20150525 欠落した形態区分追加(運賃不具合一覧162) End
    (SELECT GYOUSHA_NAME_RYAKU FROM M_GYOUSHA WHERE M_GYOUSHA.GYOUSHA_CD = T_UNCHIN_ENTRY.NIOROSHI_GYOUSHA_CD) AS NIOROSHI_GYOUSHA_NAME,
    T_UNCHIN_ENTRY.NIOROSHI_GENBA_CD,
    (SELECT GENBA_NAME_RYAKU FROM M_GENBA WHERE M_GENBA.GYOUSHA_CD = T_UNCHIN_ENTRY.NIOROSHI_GYOUSHA_CD AND M_GENBA.GENBA_CD = T_UNCHIN_ENTRY.NIOROSHI_GENBA_CD) AS NIOROSHI_GENBA_NAME,
    -- 20150525 欠落した荷積業者現場追加(運賃不具合一覧158) Start
    T_UNCHIN_ENTRY.NIZUMI_GYOUSHA_CD,
    (SELECT GYOUSHA_NAME_RYAKU FROM M_GYOUSHA WHERE M_GYOUSHA.GYOUSHA_CD = T_UNCHIN_ENTRY.NIZUMI_GYOUSHA_CD) AS NIZUMI_GYOUSHA_NAME,
    T_UNCHIN_ENTRY.NIZUMI_GENBA_CD,
    (SELECT GENBA_NAME_RYAKU FROM M_GENBA WHERE M_GENBA.GYOUSHA_CD = T_UNCHIN_ENTRY.NIZUMI_GYOUSHA_CD AND M_GENBA.GENBA_CD = T_UNCHIN_ENTRY.NIZUMI_GENBA_CD) AS NIZUMI_GENBA_NAME,
    -- 20150525 欠落した荷積業者現場追加(運賃不具合一覧158) End
    T_UNCHIN_ENTRY.SHARYOU_CD,
    (SELECT SHARYOU_NAME_RYAKU FROM M_SHARYOU WHERE M_SHARYOU.GYOUSHA_CD = T_UNCHIN_ENTRY.UNPAN_GYOUSHA_CD AND M_SHARYOU.SHARYOU_CD = T_UNCHIN_ENTRY.SHARYOU_CD) AS SHARYOU_NAME,
    T_UNCHIN_ENTRY.SHASHU_CD,
    (SELECT SHASHU_NAME_RYAKU FROM M_SHASHU WHERE SHASHU_CD = T_UNCHIN_ENTRY.SHASHU_CD) AS SHASHU_NAME,
    T_UNCHIN_ENTRY.UNPAN_GYOUSHA_CD,
    (SELECT GYOUSHA_NAME_RYAKU FROM M_GYOUSHA WHERE M_GYOUSHA.GYOUSHA_CD = T_UNCHIN_ENTRY.UNPAN_GYOUSHA_CD) AS UNPAN_GYOUSHA_NAME,
    T_UNCHIN_ENTRY.UNTENSHA_CD,
    (SELECT SHAIN_NAME_RYAKU FROM M_SHAIN WHERE M_SHAIN.SHAIN_CD = T_UNCHIN_ENTRY.UNTENSHA_CD) AS UNTENSHA_NAME,
    T_UNCHIN_DETAIL.UNCHIN_HINMEI_CD AS HINMEI_CD,
    -- 20150525 品名を運賃品名に変更(運賃不具合一覧156) Start
    --(SELECT HINMEI_NAME_RYAKU FROM M_HINMEI WHERE M_HINMEI.HINMEI_CD = T_UNCHIN_DETAIL.UNCHIN_HINMEI_CD) AS HINMEI_NAME,
    (SELECT UNCHIN_HINMEI_NAME FROM M_UNCHIN_HINMEI WHERE M_UNCHIN_HINMEI.UNCHIN_HINMEI_CD = T_UNCHIN_DETAIL.UNCHIN_HINMEI_CD) AS HINMEI_NAME,
    -- 20150525 品名を運賃品名に変更(運賃不具合一覧156) End
    T_UNCHIN_DETAIL.UNIT_CD,
    (SELECT UNIT_NAME_RYAKU FROM M_UNIT WHERE M_UNIT.UNIT_CD = T_UNCHIN_DETAIL.UNIT_CD) AS UNIT_NAME,
    T_UNCHIN_DETAIL.NET_JYUURYOU,
    T_UNCHIN_DETAIL.SUURYOU,
    T_UNCHIN_DETAIL.KINGAKU
FROM T_UNCHIN_ENTRY
    JOIN T_UNCHIN_DETAIL
        ON T_UNCHIN_ENTRY.SYSTEM_ID = T_UNCHIN_DETAIL.SYSTEM_ID
            AND T_UNCHIN_ENTRY.SEQ = T_UNCHIN_DETAIL.SEQ
    LEFT JOIN M_HINMEI
    ON T_UNCHIN_DETAIL.UNCHIN_HINMEI_CD = M_HINMEI.HINMEI_CD
    LEFT JOIN (SELECT
                   DENPYOU.SEIKYUU_NUMBER,
                   DETAIL.DENPYOU_SYSTEM_ID,
                   DETAIL.DENPYOU_SEQ,
                   DETAIL.DETAIL_SYSTEM_ID,
                   DETAIL.DENPYOU_NUMBER
               FROM T_SEIKYUU_DENPYOU AS DENPYOU
               JOIN T_SEIKYUU_DENPYOU_KAGAMI AS KAGAMI
                   ON DENPYOU.SEIKYUU_NUMBER = KAGAMI.SEIKYUU_NUMBER
               JOIN T_SEIKYUU_DETAIL AS DETAIL
                   ON KAGAMI.SEIKYUU_NUMBER = DETAIL.SEIKYUU_NUMBER
                   AND KAGAMI.KAGAMI_NUMBER = DETAIL.KAGAMI_NUMBER
               WHERE DETAIL.DENPYOU_SHURUI_CD = 1
               AND DENPYOU.DELETE_FLG = 0) AS SEIKYUU
        ON SEIKYUU.DENPYOU_SYSTEM_ID = T_UNCHIN_DETAIL.SYSTEM_ID
            AND SEIKYUU.DENPYOU_SEQ = T_UNCHIN_DETAIL.SEQ
            AND SEIKYUU.DETAIL_SYSTEM_ID = T_UNCHIN_DETAIL.DETAIL_SYSTEM_ID
WHERE T_UNCHIN_ENTRY.DELETE_FLG = 0
/*IF dto.DenpyouShurui != 6 */
/*IF dto.DenpyouShurui == 4 */
 AND T_UNCHIN_ENTRY.DENSHU_KBN_CD =170
/*END*/
/*IF dto.DenpyouShurui == 5 */
 AND T_UNCHIN_ENTRY.DENSHU_KBN_CD =160
/*END*/
/*IF dto.DenpyouShurui != 4 && dto.DenpyouShurui != 5*/
 AND T_UNCHIN_ENTRY.DENSHU_KBN_CD =/*dto.DenpyouShurui*/''
/*END*/
/*END*/
/*IF dto.DateShurui == 1*/
  AND T_UNCHIN_ENTRY.DENPYOU_DATE >= /*dto.DateFrom*/''
  AND T_UNCHIN_ENTRY.DENPYOU_DATE <= /*dto.DateTo*/''
/*END*/
/*IF dto.DateShurui == 2*/
  AND CONVERT(date, T_UNCHIN_ENTRY.UPDATE_DATE, 111) >= /*dto.DateFrom*/''
  AND CONVERT(date, T_UNCHIN_ENTRY.UPDATE_DATE, 111) <= /*dto.DateTo*/''
/*END*/
/*IF dto.KyotenCd != 99*/
  AND T_UNCHIN_ENTRY.KYOTEN_CD = /*dto.KyotenCd*/0
/*END*/

/*IF dto.NioroshiGyoushaCdFrom != null && dto.NioroshiGyoushaCdFrom != ''*/
  AND T_UNCHIN_ENTRY.NIOROSHI_GYOUSHA_CD >= /*dto.NioroshiGyoushaCdFrom*/''
/*END*/
/*IF dto.NioroshiGyoushaCdTo != null && dto.NioroshiGyoushaCdTo != ''*/
  AND T_UNCHIN_ENTRY.NIOROSHI_GYOUSHA_CD <= /*dto.NioroshiGyoushaCdTo*/''
/*END*/

/*IF dto.NioroshiGenbaCdFrom != null && dto.NioroshiGenbaCdFrom != ''*/
  AND T_UNCHIN_ENTRY.NIOROSHI_GENBA_CD >= /*dto.NioroshiGenbaCdFrom*/''
/*END*/
/*IF dto.NioroshiGenbaCdTo != null && dto.NioroshiGenbaCdTo != ''*/
  AND T_UNCHIN_ENTRY.NIOROSHI_GENBA_CD <= /*dto.NioroshiGenbaCdTo*/''
/*END*/

-- 20150525 欠落した荷積業者現場追加(運賃不具合一覧158) Start
/*IF dto.NizumiGyoushaCdFrom != null && dto.NizumiGyoushaCdFrom != ''*/
  AND T_UNCHIN_ENTRY.NIZUMI_GYOUSHA_CD >= /*dto.NizumiGyoushaCdFrom*/''
/*END*/
/*IF dto.NizumiGyoushaCdTo != null && dto.NizumiGyoushaCdTo != ''*/
  AND T_UNCHIN_ENTRY.NIZUMI_GYOUSHA_CD <= /*dto.NizumiGyoushaCdTo*/''
/*END*/

/*IF dto.NizumiGenbaCdFrom != null && dto.NizumiGenbaCdFrom != ''*/
  AND T_UNCHIN_ENTRY.NIZUMI_GENBA_CD >= /*dto.NizumiGenbaCdFrom*/''
/*END*/
/*IF dto.NizumiGenbaCdTo != null && dto.NizumiGenbaCdTo != ''*/
  AND T_UNCHIN_ENTRY.NIZUMI_GENBA_CD <= /*dto.NizumiGenbaCdTo*/''
/*END*/
-- 20150525 欠落した荷積業者現場追加(運賃不具合一覧158) Start

/*IF dto.UnpanGyoushaCdFrom != null && dto.UnpanGyoushaCdFrom != ''*/
  AND T_UNCHIN_ENTRY.UNPAN_GYOUSHA_CD >= /*dto.UnpanGyoushaCdFrom*/''
/*END*/
/*IF dto.UnpanGyoushaCdTo != null && dto.UnpanGyoushaCdTo != ''*/
  AND T_UNCHIN_ENTRY.UNPAN_GYOUSHA_CD <= /*dto.UnpanGyoushaCdTo*/''
/*END*/

/*IF dto.ShashuCdFrom != null && dto.ShashuCdFrom != ''*/
  AND T_UNCHIN_ENTRY.SHASHU_CD >= /*dto.ShashuCdFrom*/''
/*END*/
/*IF dto.ShashuCdTo != null && dto.ShashuCdTo != ''*/
  AND T_UNCHIN_ENTRY.SHASHU_CD <= /*dto.ShashuCdTo*/''
/*END*/

/*IF dto.SharyouCdFrom != null && dto.SharyouCdFrom != ''*/
  AND T_UNCHIN_ENTRY.SHARYOU_CD >= /*dto.SharyouCdFrom*/''
/*END*/
/*IF dto.SharyouCdTo != null && dto.SharyouCdTo != ''*/
  AND T_UNCHIN_ENTRY.SHARYOU_CD <= /*dto.SharyouCdTo*/''
/*END*/

/*IF dto.KeitaiKbnCdFrom != null && dto.KeitaiKbnCdFrom != ''*/
  AND T_UNCHIN_ENTRY.KEITAI_KBN_CD = /*dto.KeitaiKbnCdFrom*/''
/*END*/
