SELECT DISTINCT N'取引先マスタ' AS NAME  FROM M_TORIHIKISAKI WHERE SHUUKEI_ITEM_CD IN /*SHUUKEI_KOUMOKU_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'引合取引先マスタ' AS NAME  FROM M_HIKIAI_TORIHIKISAKI WHERE SHUUKEI_ITEM_CD IN /*SHUUKEI_KOUMOKU_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'業者マスタ' AS NAME  FROM M_GYOUSHA WHERE SHUUKEI_ITEM_CD IN /*SHUUKEI_KOUMOKU_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'引合業者マスタ' AS NAME  FROM M_HIKIAI_GYOUSHA WHERE SHUUKEI_ITEM_CD IN /*SHUUKEI_KOUMOKU_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'現場マスタ' AS NAME  FROM M_GENBA WHERE SHUUKEI_ITEM_CD IN /*SHUUKEI_KOUMOKU_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'引合現場マスタ' AS NAME  FROM M_HIKIAI_GENBA WHERE SHUUKEI_ITEM_CD IN /*SHUUKEI_KOUMOKU_CD*/('') AND DELETE_FLG = 'False'
