SELECT 
    SHUKEI.*
    ,ISNULL(SHUKEI.SHUUKEI_KOUMOKU_NAME_RYAKU,N'') AS SHUUKEI_KOUMOKU_NAME_RYAKU
FROM 
    dbo.M_SHUUKEI_KOUMOKU SHUKEI
	
/*BEGIN*/WHERE
 /*IF data.SHUUKEI_KOUMOKU_CD != null*/ SHUKEI.SHUUKEI_KOUMOKU_CD LIKE '%' + /*data.SHUUKEI_KOUMOKU_CD*/ + '%'/*END*/
 /*IF data.SHUUKEI_KOUMOKU_NAME != null*/AND SHUKEI.SHUUKEI_KOUMOKU_NAME LIKE '%' +  /*data.SHUUKEI_KOUMOKU_NAME*/ + '%'/*END*/
 /*IF data.SHUUKEI_KOUMOKU_NAME_RYAKU != null*/AND SHUKEI.SHUUKEI_KOUMOKU_NAME_RYAKU LIKE '%' +  /*data.SHUUKEI_KOUMOKU_NAME_RYAKU*/ + '%'/*END*/
 /*IF data.SHUUKEI_KOUMOKU_FURIGANA != null*/AND SHUKEI.SHUUKEI_KOUMOKU_FURIGANA LIKE '%' +  /*data.SHUUKEI_KOUMOKU_FURIGANA*/ + '%'/*END*/
 /*IF data.SHUUKEI_KOUMOKU_BIKOU != null*/AND SHUKEI.SHUUKEI_KOUMOKU_BIKOU LIKE '%' +  /*data.SHUUKEI_KOUMOKU_BIKOU*/ + '%'/*END*/
 /*IF data.CREATE_USER != null*/AND SHUKEI.CREATE_USER LIKE '%' + /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, SHUKEI.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null*/AND SHUKEI.UPDATE_USER LIKE '%' + /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, SHUKEI.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
 /*IF !deletechuFlg*/AND SHUKEI.DELETE_FLG = /*deletechuFlg*/0/*END*/
/*END*/
ORDER BY SHUKEI.SHUUKEI_KOUMOKU_CD
