SELECT M_HAIKI_SHURUI.HAIKI_SHURUI_CD, M_HAIKI_SHURUI.HAIKI_SHURUI_NAME_RYAKU, M_HAIKI_KBN.HAIKI_KBN_CD, M_HAIKI_KBN.HAIKI_KBN_NAME_RYAKU 
FROM dbo.M_HAIKI_SHURUI AS M_HAIKI_SHURUI 
LEFT JOIN dbo.M_HAIKI_KBN AS M_HAIKI_KBN ON M_HAIKI_SHURUI.HAIKI_KBN_CD = M_HAIKI_KBN.HAIKI_KBN_CD 
AND M_HAIKI_KBN.DELETE_FLG = 0
WHERE 
 M_HAIKI_SHURUI.DELETE_FLG = 0