SELECT 
	MWCH.CLOSED_DATE,
	MWCH.BIKOU,
	MWCH.TIME_STAMP
FROM 
	M_WORK_CLOSED_HANNYUUSAKI MWCH
where
	MWCH.GYOUSHA_CD = /*data.gyoushaCd*/
	AND MWCH.GENBA_CD = /*data.genbaCd*/
	AND CONVERT(CHAR(7), MWCH.CLOSED_DATE, 111) = /*data.searchDate*/