SELECT 
	M_GYOUSHA.GYOUSHA_CD
	,M_GYOUSHA.GYOUSHA_NAME_RYAKU
	,M_GENBA.GENBA_CD
	,M_GENBA.GENBA_NAME_RYAKU
FROM
	M_GYOUSHA
	,M_GENBA 
WHERE
	M_GYOUSHA.GYOUSHA_CD = M_GENBA.GYOUSHA_CD 
	AND M_GYOUSHA.DELETE_FLG = 'False'
	AND M_GENBA.DELETE_FLG = 'False'
	AND (M_GYOUSHA.SHOBUN_NIOROSHI_GYOUSHA_KBN = 'True')
	AND (M_GENBA.SHOBUN_NIOROSHI_GENBA_KBN = 'True'
		OR M_GENBA.SAISHUU_SHOBUNJOU_KBN = 'True')
	/*IF data.GYOUSHA_CD != null*/AND M_GYOUSHA.GYOUSHA_CD LIKE '%' + /*data.GYOUSHA_CD*/ + '%'/*END*/
    /*IF data.GYOUSHA_NAME_RYAKU != null*/AND M_GYOUSHA.GYOUSHA_NAME_RYAKU LIKE '%' + /*data.GYOUSHA_NAME_RYAKU*/ + '%'/*END*/
    /*IF data.GENBA_CD != null*/AND M_GENBA.GENBA_CD LIKE '%' + /*data.GENBA_CD*/ + '%'/*END*/
    /*IF data.GENBA_NAME_RYAKU != null*/AND M_GENBA.GENBA_NAME_RYAKU LIKE '%' + /*data.GENBA_NAME_RYAKU*/ + '%'/*END*/
ORDER BY 
    M_GYOUSHA.GYOUSHA_CD
	,M_GENBA.GENBA_CD