SELECT NIO.*,ENT.SAGYOU_DATE
FROM T_TEIKI_HAISHA_NIOROSHI NIO
LEFT JOIN T_TEIKI_HAISHA_ENTRY ENT
ON NIO.SYSTEM_ID = ENT.SYSTEM_ID
AND NIO.SEQ = ENT.SEQ
WHERE
	NIOROSHI_GYOUSHA_CD = /*data.NIOROSHI_GYOUSHA_CD*/
	AND NIOROSHI_GENBA_CD = /*data.NIOROSHI_GENBA_CD*/
	AND CONVERT(CHAR(7), SAGYOU_DATE, 120) = CONVERT(CHAR(7), /*data.SAGYOU_DATE*/, 120)
	AND DELETE_FLG = 0