SELECT 	*
FROM T_UKETSUKE_SS_ENTRY
where
	NIOROSHI_GYOUSHA_CD = /*data.NIOROSHI_GYOUSHA_CD*/
	AND NIOROSHI_GENBA_CD = /*data.NIOROSHI_GENBA_CD*/
	AND CONVERT(CHAR(7), SAGYOU_DATE, 120) = CONVERT(CHAR(7), /*data.SAGYOU_DATE*/, 120)
	AND DELETE_FLG = 0