SELECT
DATA.*
FROM
(
SELECT 
SS.SAGYOU_DATE,
SUBSTRING(CONVERT(nvarchar, SS.GENCHAKU_TIME, 108), 1, 5) AS GENCHAKU_TIME,
(CASE /*data.SEND_JOKYO*/
    WHEN 1 THEN '未'
    ELSE '済'
    END)AS SEND_JOKYO,
SS.HAISHA_JOKYO_NAME,
'収集' AS DENPYOU_SHURUI,
SS.UKETSUKE_NUMBER AS DENPYOU_NUMBER,
SS.GYOUSHA_CD,
SS.GYOUSHA_NAME,
SS.GENBA_CD,
SS.GENBA_NAME,
SMS.RECEIVER_NAME,
SMS.MOBILE_PHONE_NUMBER,
SMS.MESSAGE_ID,
SMS.ERROR_CODE,
SMS.ERROR_DETAIL,
SMS.SEND_DATE_R,
SMS.SEND_USER,
SMS.SYSTEM_ID
FROM T_UKETSUKE_SS_ENTRY SS
LEFT OUTER JOIN T_SMS SMS
ON SS.UKETSUKE_NUMBER = SMS.DENPYOU_NUMBER
INNER JOIN M_GENBA GE
ON SS.GYOUSHA_CD = GE.GYOUSHA_CD
AND SS.GENBA_CD = GE.GENBA_CD
WHERE 1 = 1
/*IF data.KYOTEN_CD != null && data.KYOTEN_CD != ''*/AND SS.KYOTEN_CD = /*data.KYOTEN_CD*//*END*/
/*IF data.SAGYOU_DATE_FROM != null && data.SAGYOU_DATE_FROM != ''*/AND CONVERT(DATETIME, CONVERT(nvarchar, SS.SAGYOU_DATE, 111), 120) >= CONVERT(DATETIME, CONVERT(nvarchar, /*data.SAGYOU_DATE_FROM*/'', 111), 120)/*END*/
/*IF data.SAGYOU_DATE_TO != null && data.SAGYOU_DATE_TO != ''*/AND CONVERT(DATETIME, CONVERT(nvarchar, SS.SAGYOU_DATE, 111), 120) <= CONVERT(DATETIME, CONVERT(nvarchar, /*data.SAGYOU_DATE_TO*/'', 111), 120)/*END*/
/*IF data.HAISHA_JOKYO != null && data.HAISHA_JOKYO != '' && data.HAISHA_JOKYO != '6'*/AND SS.HAISHA_JOKYO_CD LIKE '%' + /*data.HAISHA_JOKYO*/ + '%'/*END*/
/*IF data.HAISHA_JOKYO != null && data.HAISHA_JOKYO != '' && data.HAISHA_JOKYO == '6'*/AND (SS.HAISHA_JOKYO_CD = '1' OR SS.HAISHA_JOKYO_CD = '2')/*END*/
/*IF data.GYOUSHA_CD != null && data.GYOUSHA_CD != ''*/AND SS.GYOUSHA_CD LIKE '%' + /*data.GYOUSHA_CD*/ + '%'/*END*/
/*IF data.GENBA_CD != null && data.GENBA_CD != ''*/AND SS.GENBA_CD LIKE '%' + /*data.GENBA_CD*/ + '%'/*END*/
/*IF data.UNPAN_GYOUSHA_CD != null && data.UNPAN_GYOUSHA_CD != ''*/AND SS.UNPAN_GYOUSHA_CD LIKE '%' + /*data.UNPAN_GYOUSHA_CD*/ + '%'/*END*/
AND SS.DELETE_FLG = 0
AND GE.SMS_USE = '1'
/*IF data.SEND_JOKYO == 1*/AND SMS.SEND_DATE_R IS NULL/*END*/
/*IF data.SEND_JOKYO == 2*/AND SMS.SEND_DATE_R IS NOT NULL AND SMS.ERROR_CODE IS NULL/*END*/
/*IF data.SEND_JOKYO == 3*/AND SMS.SEND_DATE_R IS NOT NULL AND SMS.ERROR_CODE IS NOT NULL/*END*/

UNION ALL (
SELECT 
SK.SAGYOU_DATE,
SUBSTRING(CONVERT(nvarchar, SK.GENCHAKU_TIME, 108), 1, 5) AS GENCHAKU_TIME,
(CASE /*data.SEND_JOKYO*/
    WHEN 1 THEN '未'
    ELSE '済'
    END)AS SEND_JOKYO,
SK.HAISHA_JOKYO_NAME,
'出荷' AS DENPYOU_SHURUI,
SK.UKETSUKE_NUMBER AS DENPYOU_NUMBER,
SK.GYOUSHA_CD,
SK.GYOUSHA_NAME,
SK.GENBA_CD,
SK.GENBA_NAME,
SMS.RECEIVER_NAME,
SMS.MOBILE_PHONE_NUMBER,
SMS.MESSAGE_ID,
SMS.ERROR_CODE,
SMS.ERROR_DETAIL,
SMS.SEND_DATE_R,
SMS.SEND_USER,
SMS.SYSTEM_ID
FROM T_UKETSUKE_SK_ENTRY SK
LEFT OUTER JOIN T_SMS SMS
ON SK.UKETSUKE_NUMBER = SMS.DENPYOU_NUMBER
INNER JOIN M_GENBA GE
ON SK.GYOUSHA_CD = GE.GYOUSHA_CD
AND SK.GENBA_CD = GE.GENBA_CD
WHERE 1 = 1
/*IF data.KYOTEN_CD != null && data.KYOTEN_CD != ''*/AND SK.KYOTEN_CD = /*data.KYOTEN_CD*//*END*/
/*IF data.SAGYOU_DATE_FROM != null && data.SAGYOU_DATE_FROM != ''*/AND CONVERT(DATETIME, CONVERT(nvarchar, SK.SAGYOU_DATE, 111), 120) >= CONVERT(DATETIME, CONVERT(nvarchar, /*data.SAGYOU_DATE_FROM*/'', 111), 120)/*END*/
/*IF data.SAGYOU_DATE_TO != null && data.SAGYOU_DATE_TO != ''*/AND CONVERT(DATETIME, CONVERT(nvarchar, SK.SAGYOU_DATE, 111), 120) <= CONVERT(DATETIME, CONVERT(nvarchar, /*data.SAGYOU_DATE_TO*/'', 111), 120)/*END*/
/*IF data.HAISHA_JOKYO != null && data.HAISHA_JOKYO != '' && data.HAISHA_JOKYO != '6'*/AND SK.HAISHA_JOKYO_CD LIKE '%' + /*data.HAISHA_JOKYO*/ + '%'/*END*/
/*IF data.HAISHA_JOKYO != null && data.HAISHA_JOKYO != '' && data.HAISHA_JOKYO == '6'*/AND (SK.HAISHA_JOKYO_CD = '1' OR SK.HAISHA_JOKYO_CD = '2')/*END*/
/*IF data.GYOUSHA_CD != null && data.GYOUSHA_CD != ''*/AND SK.GYOUSHA_CD LIKE '%' + /*data.GYOUSHA_CD*/ + '%'/*END*/
/*IF data.GENBA_CD != null && data.GENBA_CD != ''*/AND SK.GENBA_CD LIKE '%' + /*data.GENBA_CD*/ + '%'/*END*/
/*IF data.UNPAN_GYOUSHA_CD != null && data.UNPAN_GYOUSHA_CD != ''*/AND SK.UNPAN_GYOUSHA_CD LIKE '%' + /*data.UNPAN_GYOUSHA_CD*/ + '%'/*END*/
AND SK.DELETE_FLG = 0
AND GE.SMS_USE = '1'
/*IF data.SEND_JOKYO == 1*/AND SMS.SEND_DATE_R IS NULL/*END*/
/*IF data.SEND_JOKYO == 2*/AND SMS.SEND_DATE_R IS NOT NULL AND SMS.ERROR_CODE IS NULL/*END*/
/*IF data.SEND_JOKYO == 3*/AND SMS.SEND_DATE_R IS NOT NULL AND SMS.ERROR_CODE IS NOT NULL/*END*/
)
)AS DATA
ORDER BY SAGYOU_DATE,
GENCHAKU_TIME,
DENPYOU_SHURUI,
DENPYOU_NUMBER,
MOBILE_PHONE_NUMBER