SELECT DISTINCT N'マニフェスト換算マスタ' AS NAME FROM M_MANIFEST_KANSAN WHERE NISUGATA_CD IN /*NISUGATA_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'品名入力' AS NAME FROM M_HINMEI WHERE NISUGATA_CD IN /*NISUGATA_CD*/('') AND DELETE_FLG = 'False'