SELECT
    /*IF data.GENBASHUKEI_KBN == '1'*/M_CHIIKI.CHIIKI_CD + T_SUII.HST_GYOUSHA_CD AS HST_GYOUSHAGENBA,/*END*/
	/*IF data.GENBASHUKEI_KBN == '2'*/HST_GYOUSHA_CD + T_SUII.HST_GENBA_CD AS HST_GYOUSHAGENBA,/*END*/
    '4' AS CHOKKOU_ROUTE_NO,
    T_SUII.SYSTEM_ID,
    CONVERT(SMALLINT, '4') AS HAIKI_KBN_CD,
    1 AS HOUKOKUSHOBUNRUISORTKEY,
    M_CHIIKI.GOV_OR_MAY_NAME,
    M_CHIIKI.CHIIKI_NAME_RYAKU,
    M_GSH_TODOUFUKEN.TODOUFUKEN_NAME,
    REPLACE(M_GSH.GYOUSHA_ADDRESS1,',','，') AS GYOUSHA_ADDRESS1,
    REPLACE(M_GSH.GYOUSHA_ADDRESS2,',','，') AS GYOUSHA_ADDRESS2,
    M_GSH.GYOUSHA_NAME1,
    M_GSH.GYOUSHA_NAME2,
    M_GSH.JISHA_KBN,
    M_GSH.GYOUSHA_DAIHYOU AS DAIHYOUSHA,
    M_GSH.GYOUSHA_TEL,
    /*data.TITLE1*/ AS TITLE1,
    /*data.TITLE2*/ AS TITLE2,
    M_GNB.GENBA_NAME1 + M_GNB.GENBA_NAME2 AS JGB_NAME,
    REPLACE(M_GNB.GENBA_ADDRESS1 + M_GNB.GENBA_ADDRESS2,',','，') AS JGB_ADDRESS,
    TODOUFUKEN_JGB.TODOUFUKEN_NAME AS JGB_TODOUFUKEN_NAME,
    M_GSH.GYOUSHU_CD AS GYOUSHA_GYOUSHU_CD,
    M_GNB.GYOUSHU_CD AS GENBA_GYOUSHU_CD,
    (SELECT TOP 1 GYOUSHU_NAME FROM M_GYOUSHU AS M1  WHERE M1.GYOUSHU_CD = M_GSH.GYOUSHU_CD) AS GYOUSHA_GYOUSHU_NM,
    (SELECT TOP 1 GYOUSHU_NAME FROM M_GYOUSHU AS M2  WHERE M2.GYOUSHU_CD = M_GNB.GYOUSHU_CD) AS GENBA_GYOUSHU_NM,
    '' AS GYOUSHU_CD,
    '' AS GYOUSHU_NAME,
    M_GNB.GENBA_TEL,
    HAIKI_SHURUI_CD,
    HAIKI_SHURUI_NAME AS HAIKI_SHURUI_NAME_RYAKU,
    Sum(KANSAN_SUU) AS HAISHU_RYOU,
    0 AS COUFUMAISUU,
	CASE
		WHEN T_SUII.UPN_ROUTE_NO = 1 THEN
			--1区間目の許可番号は、排出事業場の地域に対しての運搬許可番号を参照
			CASE
				WHEN T_SUII.SANPAI_KBN = 1 THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                             ELSE UPN_KYOKA.FUTSUU_KYOKA_NO
                        END
				WHEN T_SUII.SANPAI_KBN = 2 THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                             ELSE UPN_KYOKA.TOKUBETSU_KYOKA_NO
                        END
				ELSE
                    --普通許可番号があれば普通許可番号、なければ特管許可番号
                    CASE
                        WHEN ISNULL(UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                        WHEN ISNULL(UPN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN UPN_KYOKA.FUTSUU_KYOKA_NO
                        WHEN ISNULL(UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                        ELSE UPN_KYOKA.TOKUBETSU_KYOKA_NO
                    END
				END
		ELSE
			--2区間目以降の許可番号は、前区間の運搬先の事業場の地域に対しての運搬許可番号を参照
			CASE
				WHEN T_SUII.SANPAI_KBN = 1 THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(MAE_UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN MAE_UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                             ELSE MAE_UPN_KYOKA.FUTSUU_KYOKA_NO
                        END
				WHEN T_SUII.SANPAI_KBN = 2 THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(MAE_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN MAE_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                             ELSE MAE_UPN_KYOKA.TOKUBETSU_KYOKA_NO
                        END
				ELSE
                    --普通許可番号があれば普通許可番号、なければ特管許可番号
                    CASE
                        WHEN ISNULL(MAE_UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN MAE_UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                        WHEN ISNULL(MAE_UPN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN MAE_UPN_KYOKA.FUTSUU_KYOKA_NO
                        WHEN ISNULL(MAE_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN MAE_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                        ELSE MAE_UPN_KYOKA.TOKUBETSU_KYOKA_NO
                    END
				END
	END AS UPN_FUTSUU_KYOKA_NO,
    T_SUII.UPN_ROUTE_NO,
    GYOUSHA_UPN.GYOUSHA_CD AS UPN_GYOUSHA_CD,
    GYOUSHA_UPN.GYOUSHA_NAME1 + GYOUSHA_UPN.GYOUSHA_NAME2 AS UPN_GYOUSHA_NAME,
	GYOUSHA_UPN.JISHA_KBN AS UPN_JISHA_KBN,
    GENBA_UPN_SAKI.GYOUSHA_CD AS UPN_SAKI_GYOUSHA_CD,
    GENBA_UPN_SAKI.GENBA_CD AS UPN_SAKI_GENBA_CD,
    REPLACE(ISNULL(UPN_GENBA_TODOUFUKEN.TODOUFUKEN_NAME + GENBA_UPN_SAKI.GENBA_ADDRESS1 + GENBA_UPN_SAKI.GENBA_ADDRESS2, ''),',','，') AS UPN_SAKI_GENBA_ADDRESS,
	/*IF data.GYOUSHASET_KBN2 == '2' || data.GYOUSHASET_KBN2 == '4'*/ --[提出業者設定-2] = 2.運搬/排出事業者, 4.全て
	CASE
		WHEN T_SUII.FIRST_MANIFEST_KBN = 0 THEN
			CASE
				WHEN T_SUII.SANPAI_KBN = 1 THEN SBN_KYOKA.FUTSUU_KYOKA_NO
				WHEN T_SUII.SANPAI_KBN = 2 THEN SBN_KYOKA.TOKUBETSU_KYOKA_NO
				ELSE
					CASE
						WHEN ISNULL(SBN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN SBN_KYOKA.FUTSUU_KYOKA_NO
						ELSE SBN_KYOKA.TOKUBETSU_KYOKA_NO
					END
			END
		WHEN T_SUII.FIRST_MANIFEST_KBN = 1 THEN
			CASE
				WHEN T_SUII.SANPAI_KBN = 1 THEN LAST_SBN_KYOKA.FUTSUU_KYOKA_NO
				WHEN T_SUII.SANPAI_KBN = 2 THEN LAST_SBN_KYOKA.TOKUBETSU_KYOKA_NO
				ELSE
					CASE
						WHEN ISNULL(LAST_SBN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN LAST_SBN_KYOKA.FUTSUU_KYOKA_NO
						ELSE LAST_SBN_KYOKA.TOKUBETSU_KYOKA_NO
					END
			END
    END AS SBN_FUTSUU_KYOKA_NO,
    GENBA_SBN.GYOUSHA_CD AS SBN_GYOUSHA_CD,
    ISNULL(GYOUSHA_SBN.GYOUSHA_NAME1, '') + ISNULL(GYOUSHA_SBN.GYOUSHA_NAME2, '') AS  SBN_GYOUSHA_NAME,
    GENBA_SBN.GENBA_CD AS SBN_GENBA_CD,
	REPLACE(ISNULL(SBN_GENBA_TODOUFUKEN.TODOUFUKEN_NAME + GENBA_SBN.GENBA_ADDRESS1 + GENBA_SBN.GENBA_ADDRESS2, ''),',','，') AS  SBN_GENBA_ADDRESS,
	GENBA_SBN.JISHA_KBN AS SBN_GENBA_JISHA_KBN
	/*END*/
	/*IF data.GYOUSHASET_KBN2 == '1' || data.GYOUSHASET_KBN2 == '3'*/ --[提出業者設定-2] = 1.収集運搬/自社, 3.収集運搬/他社
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN ''		--処分受託者欄に処分受託者を表示していい区間ではない(後区間にて表示される)
		ELSE
			CASE
				WHEN T_SUII.FIRST_MANIFEST_KBN = 0 THEN
					CASE
						WHEN T_SUII.SANPAI_KBN = 1 THEN SHOBUN_INFO.FUTSUU_KYOKA_NO
						WHEN T_SUII.SANPAI_KBN = 2 THEN SHOBUN_INFO.TOKUBETSU_KYOKA_NO
						ELSE
							CASE
								WHEN ISNULL(SHOBUN_INFO.FUTSUU_KYOKA_NO, '') != '' THEN SHOBUN_INFO.FUTSUU_KYOKA_NO
								ELSE SHOBUN_INFO.TOKUBETSU_KYOKA_NO
							END
					END
				WHEN T_SUII.FIRST_MANIFEST_KBN = 1 THEN
					CASE
						WHEN T_SUII.SANPAI_KBN = 1 THEN SHOBUN_INFO.LAST_FUTSUU_KYOKA_NO
						WHEN T_SUII.SANPAI_KBN = 2 THEN SHOBUN_INFO.LAST_TOKUBETSU_KYOKA_NO
						ELSE
							CASE
								WHEN ISNULL(SHOBUN_INFO.LAST_FUTSUU_KYOKA_NO, '') != '' THEN SHOBUN_INFO.LAST_FUTSUU_KYOKA_NO
								ELSE SHOBUN_INFO.LAST_TOKUBETSU_KYOKA_NO
							END
					END
			END
		END AS SBN_FUTSUU_KYOKA_NO,
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN ''
		ELSE SHOBUN_INFO.GYOUSHA_CD
        END AS SBN_GYOUSHA_CD,
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN ''
		ELSE SHOBUN_INFO.GYOUSHA_NAME1 + SHOBUN_INFO.GYOUSHA_NAME2
		END AS SBN_GYOUSHA_NAME,
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN ''
		ELSE SHOBUN_INFO.GENBA_CD
        END AS SBN_GENBA_CD,
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN ''
		ELSE REPLACE(SHOBUN_INFO.TODOUFUKEN_NAME + SHOBUN_INFO.GENBA_ADDRESS1 + SHOBUN_INFO.GENBA_ADDRESS2,',','，')
        END AS SBN_GENBA_ADDRESS,
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN 0
		ELSE SHOBUN_INFO.JISHA_KBN
        END AS SBN_GENBA_JISHA_KBN
	/*END*/
FROM
(
SELECT
    TME.SYSTEM_ID, 
    TME.SEQ,
    TME.HST_GYOUSHA_CD AS HST_GYOUSHA_CD,
    TME.HST_GENBA_CD AS HST_GENBA_CD,
	CASE
		--中間処理産業廃棄物管理方法フラグがブランクでなく存在し、排出が自社の場合は2次マニとして扱う
		WHEN (R18.FIRST_MANIFEST_FLAG IS NOT NULL OR R18.FIRST_MANIFEST_FLAG != '') AND ISNULL(HST_GYOUSHA.JISHA_KBN, 0) = 1 THEN 1
		ELSE 0
	END AS FIRST_MANIFEST_KBN,
    CASE
        WHEN R18.UPN_ROUTE_CNT = R19EX.UPN_ROUTE_NO THEN TME.SBN_GYOUSHA_CD
        ELSE ''
    END AS SBN_GYOUSHA_CD,
    CASE
        WHEN R18.UPN_ROUTE_CNT = R19EX.UPN_ROUTE_NO THEN TME.SBN_GENBA_CD
        ELSE ''
    END AS SBN_GENBA_CD,
	/*IF data.KONGOU_KBN == '1'*/--■混合出力有 #13266
	M_HOKOKU_BRI.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_CD,	
    CASE
		WHEN 
			(SELECT COUNT(*) FROM DT_R18_MIX AS MIX WHERE TME.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0) = 1 THEN 
				(SELECT M_HOUKOKUSHO_BUN_MIX.HOUKOKUSHO_BUNRUI_NAME
				FROM M_HOUKOKUSHO_BUNRUI AS M_HOUKOKUSHO_BUN_MIX
				-- 一次マニ電子(混廃)
				LEFT JOIN DT_R18_MIX AS MIX
					ON TME.SYSTEM_ID = MIX.SYSTEM_ID
					AND MIX.DELETE_FLG = 0
				--電子廃棄物種類マスタ
				LEFT JOIN
							M_DENSHI_HAIKI_SHURUI AS M_DENSHI_HAIKI_SHU
					ON       MIX.HAIKI_DAI_CODE + MIX.HAIKI_CHU_CODE + MIX.HAIKI_SHO_CODE = M_DENSHI_HAIKI_SHU.HAIKI_SHURUI_CD
				--報告書分類
				WHERE  M_DENSHI_HAIKI_SHU.HOUKOKUSHO_BUNRUI_CD = M_HOUKOKUSHO_BUN_MIX.HOUKOKUSHO_BUNRUI_CD)
		WHEN 
			(SELECT COUNT(*) FROM DT_R18_MIX AS MIX WHERE TME.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0) > 1 THEN
				CASE
					WHEN (SELECT COUNT(*) FROM
							(SELECT M_HOUKOKUSHO_BUN_MIX.HOUKOKUSHO_BUNRUI_CD
								FROM M_HOUKOKUSHO_BUNRUI AS M_HOUKOKUSHO_BUN_MIX
									-- 一次マニ電子(混廃)
									LEFT JOIN DT_R18_MIX AS MIX	ON TME.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0
									--電子廃棄物種類マスタ
									LEFT JOIN M_DENSHI_HAIKI_SHURUI AS M_DENSHI_HAIKI_SHU ON MIX.HAIKI_DAI_CODE + MIX.HAIKI_CHU_CODE + MIX.HAIKI_SHO_CODE = M_DENSHI_HAIKI_SHU.HAIKI_SHURUI_CD
								--報告書分類
								WHERE
									M_DENSHI_HAIKI_SHU.HOUKOKUSHO_BUNRUI_CD = M_HOUKOKUSHO_BUN_MIX.HOUKOKUSHO_BUNRUI_CD
								GROUP BY
									M_HOUKOKUSHO_BUN_MIX.HOUKOKUSHO_BUNRUI_CD
						) AS BUNRUI_COUNT) > 1 THEN '混合廃棄物'
					ELSE M_HOKOKU_BRI.HOUKOKUSHO_BUNRUI_NAME
					END
		ELSE M_HOKOKU_BRI.HOUKOKUSHO_BUNRUI_NAME
	END AS HAIKI_SHURUI_NAME,
	CASE
		WHEN
			--MIXの廃棄物種類の範囲で分岐
			(SELECT COUNT(*) FROM DT_R18_MIX AS MIX WHERE TME.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0) = 1 THEN
				CASE
					WHEN M_HIK_SRI.HAIKI_SHURUI_CD < '7000' THEN 1
					ELSE 2
				END
		WHEN
			--含まれている廃棄物のカウントで分岐
			(SELECT COUNT(*) FROM DT_R18_MIX AS MIX WHERE TME.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0) > 1 THEN
				CASE
					WHEN (SELECT SUM(CASE WHEN LEFT(MIX.HAIKI_SHURUI_CD, 4) < '7000' THEN 0 ELSE 1 END) FROM DT_R18_MIX AS MIX WHERE TME.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0) = 0 THEN 1	--普通
					WHEN (SELECT SUM(CASE WHEN LEFT(MIX.HAIKI_SHURUI_CD, 4) < '7000' THEN 0 ELSE 1 END) FROM DT_R18_MIX AS MIX WHERE TME.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0) = (SELECT COUNT(*) FROM DT_R18_MIX AS MIX WHERE TME.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0) THEN 2	--特管
					ELSE 3
				END
		ELSE
			CASE
				WHEN M_HIK_SRI.HAIKI_SHURUI_CD < '7000' THEN 1
				ELSE 2
			END
	END AS SANPAI_KBN,
	/*END*/
	/*IF data.KONGOU_KBN == '2'*/--■混合出力無
	CASE 
		WHEN (SELECT COUNT(*) FROM DT_R18_MIX AS MIX WHERE TME.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0) > 0 
			THEN M_HOUKOKUSHO_BUN_MIX.HOUKOKUSHO_BUNRUI_CD
		ELSE M_HOKOKU_BRI.HOUKOKUSHO_BUNRUI_CD
	END AS HAIKI_SHURUI_CD,
	CASE 
		WHEN (SELECT COUNT(*) FROM DT_R18_MIX AS MIX WHERE TME.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0) > 0 
			THEN M_HOUKOKUSHO_BUN_MIX.HOUKOKUSHO_BUNRUI_NAME
		ELSE M_HOKOKU_BRI.HOUKOKUSHO_BUNRUI_NAME
	END AS HAIKI_SHURUI_NAME,
	CASE
		WHEN (SELECT COUNT(*) FROM DT_R18_MIX AS MIX WHERE TME.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0) > 0
			THEN
				CASE
					WHEN M_DENSHI_HAIKI_SHU.HAIKI_SHURUI_CD < '7000' THEN 1
					ELSE 2
				END
		ELSE
			CASE
				WHEN M_HIK_SRI.HAIKI_SHURUI_CD < '7000' THEN 1
				ELSE 2
			END
	END AS SANPAI_KBN,
	/*END*/
    R19EX.UPN_ROUTE_NO,
    R19EX.UPN_GYOUSHA_CD,
    R19EX.UPNSAKI_GYOUSHA_CD,
    R19EX.UPNSAKI_GENBA_CD AS UPN_SAKI_GENBA_CD,
	/*IF data.KONGOU_KBN == '1'*/--■混合出力有 #12923
	CASE
		WHEN (SELECT COUNT(*) FROM DT_R18_MIX AS MIX WHERE TME.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0) = 1 THEN 
			 ISNULL((SELECT MIX.KANSAN_SUU FROM DT_R18_MIX AS MIX WHERE TME.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0),0)
		ELSE ISNULL(SUM(CONVERT(money,TME.KANSAN_SUU)),0)
	END AS KANSAN_SUU,
	/*END*/
	/*IF data.KONGOU_KBN == '2'*/--■混合出力無
	CASE
		WHEN (SELECT COUNT(*) FROM DT_R18_MIX AS MIX WHERE TME.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0) >0 THEN 
			 ISNULL(SUM(CONVERT(money,MIX.KANSAN_SUU)),0)
		ELSE ISNULL(SUM(CONVERT(money,TME.KANSAN_SUU)),0)
    END AS KANSAN_SUU,
	/*END*/
    R18.HIKIWATASHI_DATE AS KOUFU_DATE  
FROM DT_MF_TOC AS TOC
--R18 マニフェスト情報
INNER JOIN
          DT_R18 AS R18
  ON         TOC.KANRI_ID        = R18.KANRI_ID
  AND        TOC.LATEST_SEQ      = R18.SEQ

--電子マニフェスト基本拡張
INNER JOIN
          DT_R18_EX AS TME
  ON         R18.KANRI_ID = TME.KANRI_ID
  AND        TME.DELETE_FLG = 0
--排出事業者
LEFT JOIN
	M_GYOUSHA HST_GYOUSHA ON TME.HST_GYOUSHA_CD = HST_GYOUSHA.GYOUSHA_CD
/*IF data.KONGOU_KBN == '2'*/--■混合出力無
-- 一次マニ電子(混廃)
LEFT JOIN DT_R18_MIX AS MIX
	ON TME.SYSTEM_ID = MIX.SYSTEM_ID
	AND MIX.DELETE_FLG = 0
--電子廃棄物種類マスタ
LEFT JOIN
			M_DENSHI_HAIKI_SHURUI AS M_DENSHI_HAIKI_SHU
	ON       MIX.HAIKI_DAI_CODE + MIX.HAIKI_CHU_CODE + MIX.HAIKI_SHO_CODE = M_DENSHI_HAIKI_SHU.HAIKI_SHURUI_CD

--報告書分類
LEFT JOIN
	M_HOUKOKUSHO_BUNRUI AS M_HOUKOKUSHO_BUN_MIX
ON  M_DENSHI_HAIKI_SHU.HOUKOKUSHO_BUNRUI_CD = M_HOUKOKUSHO_BUN_MIX.HOUKOKUSHO_BUNRUI_CD
/*END*/
--電子マニフェスト収集運搬拡張
INNER JOIN
        (
          SELECT SYSTEM_ID, SEQ,UPN_ROUTE_NO
          FROM   DT_R19_EX
          WHERE  DELETE_FLG = 0
          AND ((UPN_GYOUSHA_CD <> '' AND UPN_GYOUSHA_CD IS NOT NULL) OR (UPNSAKI_GENBA_CD <> '' AND UPNSAKI_GENBA_CD IS NOT NULL)) --運搬受託者 処分受託者
          GROUP BY SYSTEM_ID, SEQ,UPN_ROUTE_NO
           ) AS R19EX2
          ON 1 = 1
--電子マニフェスト収集運搬拡張
INNER JOIN
          DT_R19_EX AS R19EX
  ON         TME.SYSTEM_ID = R19EX.SYSTEM_ID
  AND        TME.SEQ       = R19EX.SEQ
  AND        R19EX2.SYSTEM_ID = R19EX.SYSTEM_ID
  AND        R19EX2.SEQ       = R19EX.SEQ
  AND        R19EX.UPN_ROUTE_NO = R19EX2.UPN_ROUTE_NO
  AND        R19EX.DELETE_FLG = 0

--電子廃棄物種類マスタ
INNER JOIN
          M_DENSHI_HAIKI_SHURUI AS M_HIK_SRI
  ON       R18.HAIKI_DAI_CODE + R18.HAIKI_CHU_CODE + R18.HAIKI_SHO_CODE = M_HIK_SRI.HAIKI_SHURUI_CD

--報告書分類
INNER JOIN
    M_HOUKOKUSHO_BUNRUI AS M_HOKOKU_BRI
ON  M_HIK_SRI.HOUKOKUSHO_BUNRUI_CD = M_HOKOKU_BRI.HOUKOKUSHO_BUNRUI_CD

WHERE
    TOC.STATUS_FLAG = 4

GROUP BY
    TME.SYSTEM_ID,
    TME.SEQ,
    TME.HST_GYOUSHA_CD,
	HST_GYOUSHA.JISHA_KBN,
    TME.HST_GENBA_CD,
    TME.SBN_GYOUSHA_CD,
    TME.SBN_GENBA_CD,
	R18.FIRST_MANIFEST_FLAG,
    R18.HIKIWATASHI_DATE,
    R18.HAIKI_DAI_CODE + R18.HAIKI_CHU_CODE + R18.HAIKI_SHO_CODE,
	R18.UPN_ROUTE_CNT,
    R19EX.UPN_ROUTE_NO,
    R19EX.UPN_GYOUSHA_CD,
    R19EX.UPNSAKI_GYOUSHA_CD,
    R19EX.UPNSAKI_GENBA_CD,
	/*IF data.KONGOU_KBN == '2'*/--■混合出力無
	M_HOUKOKUSHO_BUN_MIX.HOUKOKUSHO_BUNRUI_CD,
	M_HOUKOKUSHO_BUN_MIX.HOUKOKUSHO_BUNRUI_NAME,
	M_DENSHI_HAIKI_SHU.HAIKI_SHURUI_CD,
	/*END*/
	M_HIK_SRI.HAIKI_SHURUI_CD,
    M_HOKOKU_BRI.HOUKOKUSHO_BUNRUI_CD,
    M_HOKOKU_BRI.HOUKOKUSHO_BUNRUI_NAME

) T_SUII

--前区間の収集運搬拡張を結合
LEFT JOIN
	DT_R19_EX MAE_T_SUII ON T_SUII.SYSTEM_ID = MAE_T_SUII.SYSTEM_ID AND T_SUII.SEQ = MAE_T_SUII.SEQ AND T_SUII.UPN_ROUTE_NO = MAE_T_SUII.UPN_ROUTE_NO + 1 AND MAE_T_SUII.DELETE_FLG = 0 
/*IF data.GYOUSHASET_KBN2 == '1' || data.GYOUSHASET_KBN2 == '3'*/ --[提出業者設定-2] = 1.収集運搬/自社, 3.収集運搬/他社
--最終区間、処分情報を別途作成して結合
LEFT JOIN
(
	--処分情報を表示していい区間かどうか。全ての最終区間 or 自社のみの最終区間 or 他社のみの最終区間
	SELECT
		MAX(R19.UPN_ROUTE_NO) MAX_UPN_ROUTE_NO,
		R19EX.SYSTEM_ID,
		R19EX.SEQ
	FROM
		DT_MF_TOC TOC
		INNER JOIN DT_R18 R18 ON TOC.KANRI_ID = R18.KANRI_ID AND TOC.LATEST_SEQ = R18.SEQ AND (R18.HIKIWATASHI_DATE >= /*data.KOUFU_DATE_FROM*/ AND R18.HIKIWATASHI_DATE <= /*data.KOUFU_DATE_TO*/)
		INNER JOIN DT_R19 R19 ON TOC.KANRI_ID = R19.KANRI_ID AND TOC.LATEST_SEQ = R19.SEQ
		INNER JOIN DT_R18_EX R18EX ON R18.KANRI_ID = R18EX.KANRI_ID AND R18EX.DELETE_FLG = 0
		INNER JOIN DT_R19_EX R19EX ON R18EX.SYSTEM_ID = R19EX.SYSTEM_ID AND R18EX.SEQ = R19EX.SEQ AND R19.UPN_ROUTE_NO = R19EX.UPN_ROUTE_NO
		INNER JOIN M_GYOUSHA ON R19EX.UPN_GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
		/*IF data.GYOUSHASET_KBN2 == '1'*/ AND M_GYOUSHA.JISHA_KBN <> 0/*END*/
		/*IF data.GYOUSHASET_KBN2 == '3'*/ AND M_GYOUSHA.JISHA_KBN = 0/*END*/
	GROUP BY
		R19EX.SYSTEM_ID,
		R19EX.SEQ
) AS SBN_DISP_ROUTE_NO ON T_SUII.SYSTEM_ID = SBN_DISP_ROUTE_NO.SYSTEM_ID AND T_SUII.SEQ = SBN_DISP_ROUTE_NO.SEQ AND T_SUII.UPN_ROUTE_NO = SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO
LEFT JOIN
(
	--2.処分業者情報を取得
	SELECT
		R19EX.SYSTEM_ID,
		R19EX.SEQ,
		R19EX.UPNSAKI_GYOUSHA_CD AS GYOUSHA_CD,
		M_GYOUSHA.GYOUSHA_NAME1,
		M_GYOUSHA.GYOUSHA_NAME2,
		R19EX.UPNSAKI_GENBA_CD AS GENBA_CD,
		M_TODOUFUKEN.TODOUFUKEN_NAME,
		M_GENBA.GENBA_ADDRESS1,
		M_GENBA.GENBA_ADDRESS2,
		M_GENBA.JISHA_KBN,
		KYOKA.FUTSUU_KYOKA_NO,
		KYOKA.TOKUBETSU_KYOKA_NO,
		LAST_KYOKA.FUTSUU_KYOKA_NO AS LAST_FUTSUU_KYOKA_NO,
		LAST_KYOKA.TOKUBETSU_KYOKA_NO AS LAST_TOKUBETSU_KYOKA_NO
	FROM
		DT_MF_TOC TOC
		INNER JOIN DT_R18 R18 ON TOC.KANRI_ID = R18.KANRI_ID AND TOC.LATEST_SEQ = R18.SEQ
		INNER JOIN DT_R19 R19 ON R18.KANRI_ID = R19.KANRI_ID AND R18.SEQ = R19.SEQ AND R18.UPN_ROUTE_CNT = R19.UPN_ROUTE_NO
		INNER JOIN DT_R18_EX R18EX ON R18.KANRI_ID = R18EX.KANRI_ID AND R18EX.DELETE_FLG = 0
		INNER JOIN DT_R19_EX R19EX ON R18EX.SYSTEM_ID = R19EX.SYSTEM_ID AND R18EX.SEQ = R19EX.SEQ AND R18.UPN_ROUTE_CNT = R19EX.UPN_ROUTE_NO
		LEFT JOIN M_GYOUSHA ON R19EX.UPNSAKI_GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
		LEFT JOIN M_GENBA ON R19EX.UPNSAKI_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND R19EX.UPNSAKI_GENBA_CD = M_GENBA.GENBA_CD
		LEFT JOIN M_TODOUFUKEN ON M_GENBA.GENBA_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD
		LEFT JOIN (
					SELECT
						M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
						M_CHIIKIBETSU_KYOKA.GENBA_CD,
						M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
						M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
						M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
						M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
					FROM
						M_CHIIKIBETSU_KYOKA
					WHERE
						M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 2
		) AS KYOKA ON (R19EX.UPNSAKI_GYOUSHA_CD = KYOKA.GYOUSHA_CD AND R19EX.UPNSAKI_GENBA_CD = KYOKA.GENBA_CD AND M_GENBA.CHIIKI_CD = KYOKA.CHIIKI_CD AND KYOKA.KYOKA_KBN = 2)
		LEFT JOIN (
					SELECT
						M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
						M_CHIIKIBETSU_KYOKA.GENBA_CD,
						M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
						M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
						M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
						M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
					FROM
						M_CHIIKIBETSU_KYOKA
					WHERE
						M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 3
		) AS LAST_KYOKA ON (R19EX.UPNSAKI_GYOUSHA_CD = LAST_KYOKA.GYOUSHA_CD AND R19EX.UPNSAKI_GENBA_CD = LAST_KYOKA.GENBA_CD AND M_GENBA.CHIIKI_CD = LAST_KYOKA.CHIIKI_CD AND LAST_KYOKA.KYOKA_KBN = 3)
	GROUP BY
		R19EX.SYSTEM_ID,
		R19EX.SEQ,
		R19EX.UPNSAKI_GYOUSHA_CD,
		M_GYOUSHA.GYOUSHA_NAME1,
		M_GYOUSHA.GYOUSHA_NAME2,
		R19EX.UPNSAKI_GENBA_CD,
		M_TODOUFUKEN.TODOUFUKEN_NAME,
		M_GENBA.GENBA_ADDRESS1,
		M_GENBA.GENBA_ADDRESS2,
		M_GENBA.JISHA_KBN,
		KYOKA.FUTSUU_KYOKA_NO,
		KYOKA.TOKUBETSU_KYOKA_NO,
		LAST_KYOKA.FUTSUU_KYOKA_NO,
		LAST_KYOKA.TOKUBETSU_KYOKA_NO
) AS SHOBUN_INFO ON T_SUII.SYSTEM_ID = SHOBUN_INFO.SYSTEM_ID AND T_SUII.SEQ = SHOBUN_INFO.SEQ
/*END*/

--業者マスタ JOIN
LEFT JOIN
          M_GYOUSHA AS M_GSH  
  ON        T_SUII.HST_GYOUSHA_CD = M_GSH.GYOUSHA_CD
--現場マスタ JOIN
LEFT JOIN M_GENBA AS M_GNB ON (T_SUII.HST_GYOUSHA_CD = M_GNB.GYOUSHA_CD AND T_SUII.HST_GENBA_CD = M_GNB.GENBA_CD)

LEFT JOIN M_TODOUFUKEN AS TODOUFUKEN_JGB ON (M_GNB.GENBA_TODOUFUKEN_CD = TODOUFUKEN_JGB.TODOUFUKEN_CD)
LEFT JOIN M_TODOUFUKEN AS M_GSH_TODOUFUKEN ON ( M_GSH.GYOUSHA_TODOUFUKEN_CD = M_GSH_TODOUFUKEN.TODOUFUKEN_CD )
LEFT JOIN M_GYOUSHA AS GYOUSHA_UPN ON (T_SUII.UPN_GYOUSHA_CD = GYOUSHA_UPN.GYOUSHA_CD)
LEFT JOIN M_GENBA AS GENBA_UPN_SAKI ON ( T_SUII.UPNSAKI_GYOUSHA_CD = GENBA_UPN_SAKI.GYOUSHA_CD AND T_SUII.UPN_SAKI_GENBA_CD = GENBA_UPN_SAKI.GENBA_CD)
LEFT JOIN M_TODOUFUKEN AS UPN_GENBA_TODOUFUKEN ON ( GENBA_UPN_SAKI.GENBA_TODOUFUKEN_CD = UPN_GENBA_TODOUFUKEN.TODOUFUKEN_CD )
LEFT JOIN M_GENBA AS MAE_GENBA_UPN_SAKI ON ( MAE_T_SUII.UPNSAKI_GYOUSHA_CD = MAE_GENBA_UPN_SAKI.GYOUSHA_CD AND MAE_T_SUII.UPNSAKI_GENBA_CD = MAE_GENBA_UPN_SAKI.GENBA_CD)
LEFT JOIN M_GYOUSHA AS GYOUSHA_SBN ON (T_SUII.SBN_GYOUSHA_CD = GYOUSHA_SBN.GYOUSHA_CD)
LEFT JOIN M_GENBA AS GENBA_SBN ON (T_SUII.SBN_GYOUSHA_CD = GENBA_SBN.GYOUSHA_CD AND T_SUII.SBN_GENBA_CD = GENBA_SBN.GENBA_CD)
LEFT JOIN M_TODOUFUKEN AS SBN_GENBA_TODOUFUKEN ON ( GENBA_SBN.GENBA_TODOUFUKEN_CD = SBN_GENBA_TODOUFUKEN.TODOUFUKEN_CD )
LEFT JOIN (
    SELECT
        M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
        M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
        M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
        M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
        M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
    FROM
        M_CHIIKIBETSU_KYOKA
    WHERE
        M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS UPN_KYOKA ON (T_SUII.UPN_GYOUSHA_CD = UPN_KYOKA.GYOUSHA_CD AND M_GNB.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = UPN_KYOKA.CHIIKI_CD AND UPN_KYOKA.KYOKA_KBN = 1)
LEFT JOIN (
    --地域に対しての許可番号。政令指定都市＞都道府県の順に許可番号を適用するため、運搬報告書提出先の地域、地域に対しての許可番号を取得する
    SELECT
        M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
        M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
        M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
        M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
        M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
    FROM
        M_CHIIKIBETSU_KYOKA
    WHERE
        M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS UPN_KYOKA_CK ON (T_SUII.UPN_GYOUSHA_CD = UPN_KYOKA_CK.GYOUSHA_CD AND M_GNB.CHIIKI_CD = UPN_KYOKA_CK.CHIIKI_CD AND UPN_KYOKA_CK.KYOKA_KBN = 1)
LEFT JOIN (
    SELECT
        M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
        M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
        M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
        M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
        M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
    FROM
        M_CHIIKIBETSU_KYOKA
    WHERE
        M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS MAE_UPN_KYOKA ON (T_SUII.UPN_GYOUSHA_CD = MAE_UPN_KYOKA.GYOUSHA_CD AND MAE_GENBA_UPN_SAKI.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = MAE_UPN_KYOKA.CHIIKI_CD AND MAE_UPN_KYOKA.KYOKA_KBN = 1)
LEFT JOIN (
    --地域に対しての許可番号。政令指定都市＞都道府県の順に許可番号を適用するため、運搬報告書提出先の地域、地域に対しての許可番号を取得する
    SELECT
        M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
        M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
        M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
        M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
        M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
    FROM
        M_CHIIKIBETSU_KYOKA
    WHERE
        M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS MAE_UPN_KYOKA_CK ON (T_SUII.UPN_GYOUSHA_CD = MAE_UPN_KYOKA_CK.GYOUSHA_CD AND MAE_GENBA_UPN_SAKI.CHIIKI_CD = MAE_UPN_KYOKA_CK.CHIIKI_CD AND MAE_UPN_KYOKA_CK.KYOKA_KBN = 1)
LEFT JOIN (
    SELECT
        M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
        M_CHIIKIBETSU_KYOKA.GENBA_CD,
        M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
        M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
        M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
        M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
    FROM
        M_CHIIKIBETSU_KYOKA
    WHERE
        M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 2
) AS SBN_KYOKA ON (T_SUII.SBN_GYOUSHA_CD = SBN_KYOKA.GYOUSHA_CD AND T_SUII.SBN_GENBA_CD = SBN_KYOKA.GENBA_CD AND GENBA_SBN.CHIIKI_CD = SBN_KYOKA.CHIIKI_CD AND SBN_KYOKA.KYOKA_KBN = 2)
LEFT JOIN (
    SELECT
        M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
        M_CHIIKIBETSU_KYOKA.GENBA_CD,
        M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
        M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
        M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
        M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
    FROM
        M_CHIIKIBETSU_KYOKA
    WHERE
        M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 3
) AS LAST_SBN_KYOKA ON (T_SUII.SBN_GYOUSHA_CD = LAST_SBN_KYOKA.GYOUSHA_CD AND T_SUII.SBN_GENBA_CD = LAST_SBN_KYOKA.GENBA_CD AND GENBA_SBN.CHIIKI_CD = LAST_SBN_KYOKA.CHIIKI_CD AND LAST_SBN_KYOKA.KYOKA_KBN = 3)
LEFT JOIN M_CHIIKI  ON (M_GNB.CHIIKI_CD = M_CHIIKI.CHIIKI_CD)
WHERE  ((T_SUII.KOUFU_DATE) >= /*data.KOUFU_DATE_FROM*/ AND (T_SUII.KOUFU_DATE) <= /*data.KOUFU_DATE_TO*/)  
/*IF data.GYOUSHU != null && data.GYOUSHU != ''*/
	AND (M_GNB.GYOUSHU_CD = /*data.GYOUSHU*/ OR (M_GSH.GYOUSHU_CD = /*data.GYOUSHU*/ AND (M_GNB.GYOUSHU_CD = '' OR M_GNB.GYOUSHU_CD IS NULL)))
/*END*/

/*IF data.GYOUSHASET_KBN1 == '1'*/ --if --[提出業者設定-1] = 1.個別(提出業者:FROMのみ)
    /*IF data.GENBASHUKEI_KBN == '2'*/ --現場一括集計:1する2:しない
   AND T_SUII.HST_GENBA_CD >=/*data.GENBA_CD_FROM*/ AND T_SUII.HST_GENBA_CD <=/*data.GENBA_CD_TO*/
   /*END*/  
    /*IF data.TEISHUTUSAKI_KBN == '1'*/ --if --[提出先] = 1.全体(都道府県政令の指定検索しない)                             
                /*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社
                                AND ((T_SUII.HST_GYOUSHA_CD)= /*data.GYOUSHA_CD_FROM*/ AND (T_SUII.HST_GENBA_CD)<> '') AND GYOUSHA_UPN.JISHA_KBN <> 0     
                /*END*/ 
                /*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者  
                                AND ((T_SUII.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (T_SUII.HST_GENBA_CD)<> '') AND (T_SUII.HST_GYOUSHA_CD = T_SUII.UPN_GYOUSHA_CD)
                /*END*/ 
                /*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社           
                                AND ((T_SUII.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND T_SUII.HST_GENBA_CD <> '') AND (GYOUSHA_UPN.JISHA_KBN = 0 OR GYOUSHA_UPN.JISHA_KBN is NULL) AND (T_SUII.HST_GYOUSHA_CD <> T_SUII.UPN_GYOUSHA_CD OR T_SUII.UPN_GYOUSHA_CD is NULL)     
                /*END*/                         
                /*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て    
                                AND ((T_SUII.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (T_SUII.HST_GENBA_CD)<> '')
                /*END*/ 
     /*END*/    
     /*IF data.TEISHUTUSAKI_KBN == '2'*/ -- else if --[提出先] = 2.個別(都道府県政令の指定検索する)                               
                /*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社            
                                AND ((T_SUII.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (T_SUII.HST_GENBA_CD)<> '') AND GYOUSHA_UPN.JISHA_KBN <> 0 AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/   
                /*END*/
                /*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者          
                                AND ((T_SUII.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (T_SUII.HST_GENBA_CD)<> '') AND (T_SUII.HST_GYOUSHA_CD = T_SUII.UPN_GYOUSHA_CD) AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/
                /*END*/
                /*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社       
                                AND ((T_SUII.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (T_SUII.HST_GENBA_CD)<> '') AND (GYOUSHA_UPN.JISHA_KBN = 0 OR GYOUSHA_UPN.JISHA_KBN is NULL) AND (T_SUII.HST_GYOUSHA_CD <> T_SUII.UPN_GYOUSHA_CD OR T_SUII.UPN_GYOUSHA_CD is NULL)        
                                AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/      
                /*END*/
                /*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て        
                                AND T_SUII.HST_GYOUSHA_CD =/*data.GYOUSHA_CD_FROM*/ AND T_SUII.HST_GENBA_CD <> '' AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/    
                /*END*/
    /*END*/

/*END*/ 
/*IF data.GYOUSHASET_KBN1 == '2'*/--else if--[提出業者設定-1] = 2.全体(提出業者:FROM/TO)                                        
        /*IF data.TEISHUTUSAKI_KBN == '1'*/ --if --[提出先] = 1.全体(都道府県政令の指定検索しない)                             
                /*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社    
                                AND ((((T_SUII.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/ ) AND ((T_SUII.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (T_SUII.HST_GENBA_CD) <> '')       
                                AND GYOUSHA_UPN.JISHA_KBN <> 0    
                /*END*/ 
                /*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者  
                                AND ((((T_SUII.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((T_SUII.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (T_SUII.HST_GENBA_CD) <>  '')       
                                AND (T_SUII.HST_GYOUSHA_CD = T_SUII.UPN_GYOUSHA_CD)
                /*END*/ 
                /*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社   
                                AND ((((HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((T_SUII.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/ )) AND (T_SUII.HST_GENBA_CD) <> '')      
                                AND ((GYOUSHA_UPN.JISHA_KBN = 0) OR ((GYOUSHA_UPN.JISHA_KBN)is NULL)) AND ((T_SUII.HST_GYOUSHA_CD <> T_SUII.UPN_GYOUSHA_CD) OR ((T_SUII.UPN_GYOUSHA_CD)is NULL))        
                                        
                /*END*/ 
                /*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て    
                                AND ((((T_SUII.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((T_SUII.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (T_SUII.HST_GENBA_CD) <> '')
                /*END*/
        /*END*/ 
        /*IF data.TEISHUTUSAKI_KBN == '2'*/ --else if--[提出先] = 2.個別(都道府県政令の指定検索する)                              
                /*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社            
                                AND ((((T_SUII.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/ ) AND ((T_SUII.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (T_SUII.HST_GENBA_CD) <> '')       
                                AND GYOUSHA_UPN.JISHA_KBN <> 0 AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/ 
                /*END*/ 
                /*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者  
                                AND ((((T_SUII.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((T_SUII.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (T_SUII.HST_GENBA_CD) <>  '')       
                                AND (T_SUII.HST_GYOUSHA_CD = T_SUII.UPN_GYOUSHA_CD) AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/  
                /*END*/ 
                /*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社           
                                AND ((((T_SUII.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((T_SUII.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/ )) AND (T_SUII.HST_GENBA_CD) <> '')       
                                AND ((GYOUSHA_UPN.JISHA_KBN = 0) OR ((GYOUSHA_UPN.JISHA_KBN)is NULL)) AND ((T_SUII.HST_GYOUSHA_CD <> T_SUII.UPN_GYOUSHA_CD) OR ((T_SUII.UPN_GYOUSHA_CD)is NULL))        
                                AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/      
                /*END*/ 
                /*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て            
                                AND ((((T_SUII.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((T_SUII.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (T_SUII.HST_GENBA_CD) <> '')        
                                AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/  
                /*END*/
        /*END*/
/*END*/

GROUP BY 
    /*IF data.GENBASHUKEI_KBN == '1'*/M_CHIIKI.CHIIKI_CD,/*END*/
    T_SUII.HST_GYOUSHA_CD,
	/*IF data.GENBASHUKEI_KBN == '2'*/T_SUII.HST_GENBA_CD,/*END*/
    T_SUII.SYSTEM_ID,
	T_SUII.FIRST_MANIFEST_KBN,
    M_CHIIKI.GOV_OR_MAY_NAME,
    M_CHIIKI.CHIIKI_NAME_RYAKU,
    M_GSH_TODOUFUKEN.TODOUFUKEN_NAME,
    M_GSH.JISHA_KBN,
    M_GSH.GYOUSHA_ADDRESS1,
    M_GSH.GYOUSHA_ADDRESS2,
    M_GSH.GYOUSHA_NAME1,
    M_GSH.GYOUSHA_NAME2,
    M_GSH.GYOUSHA_DAIHYOU,
    M_GSH.GYOUSHA_TEL,
    M_GSH.GYOUSHU_CD,
    M_GNB.GENBA_TEL,
    M_GNB.GENBA_NAME1 + M_GNB.GENBA_NAME2,
    M_GNB.GENBA_ADDRESS1 + M_GNB.GENBA_ADDRESS2,
    TODOUFUKEN_JGB.TODOUFUKEN_NAME,
    M_GNB.GYOUSHU_CD,
    HAIKI_SHURUI_CD,
    HAIKI_SHURUI_NAME,
    KOUFU_DATE,
	T_SUII.SANPAI_KBN,
    UPN_KYOKA.FUTSUU_KYOKA_NO,
    UPN_KYOKA.TOKUBETSU_KYOKA_NO,
    MAE_UPN_KYOKA.FUTSUU_KYOKA_NO,
    MAE_UPN_KYOKA.TOKUBETSU_KYOKA_NO,
    UPN_KYOKA_CK.FUTSUU_KYOKA_NO,
    UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO,
    MAE_UPN_KYOKA_CK.FUTSUU_KYOKA_NO,
    MAE_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO,
    T_SUII.UPN_ROUTE_NO,
    GYOUSHA_UPN.GYOUSHA_CD,
    GYOUSHA_UPN.GYOUSHA_NAME1 + GYOUSHA_UPN.GYOUSHA_NAME2,
	GYOUSHA_UPN.JISHA_KBN,
	GENBA_UPN_SAKI.GYOUSHA_CD,
    GENBA_UPN_SAKI.GENBA_CD,
    UPN_GENBA_TODOUFUKEN.TODOUFUKEN_NAME + GENBA_UPN_SAKI.GENBA_ADDRESS1 + GENBA_UPN_SAKI.GENBA_ADDRESS2
	/*IF data.GYOUSHASET_KBN2 == '2' || data.GYOUSHASET_KBN2 == '4'*/ --[提出業者設定-2] = 2.運搬/排出事業者, 4.全て
    ,SBN_KYOKA.FUTSUU_KYOKA_NO,
    SBN_KYOKA.TOKUBETSU_KYOKA_NO,
    LAST_SBN_KYOKA.FUTSUU_KYOKA_NO,
    LAST_SBN_KYOKA.TOKUBETSU_KYOKA_NO,
	GENBA_SBN.GYOUSHA_CD,
    GENBA_SBN.GENBA_CD,
	GYOUSHA_SBN.GYOUSHA_NAME1,
	GYOUSHA_SBN.GYOUSHA_NAME2,
	GENBA_SBN.JISHA_KBN,
    SBN_GENBA_TODOUFUKEN.TODOUFUKEN_NAME + GENBA_SBN.GENBA_ADDRESS1 + GENBA_SBN.GENBA_ADDRESS2
	/*END*/
	/*IF data.GYOUSHASET_KBN2 == '1' || data.GYOUSHASET_KBN2 == '3'*/ --[提出業者設定-2] = 1.収集運搬/自社, 3.収集運搬/他社
	,SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO,
	SHOBUN_INFO.FUTSUU_KYOKA_NO,
	SHOBUN_INFO.TOKUBETSU_KYOKA_NO,
	SHOBUN_INFO.LAST_FUTSUU_KYOKA_NO,
	SHOBUN_INFO.LAST_TOKUBETSU_KYOKA_NO,
	SHOBUN_INFO.GYOUSHA_CD,
	SHOBUN_INFO.GYOUSHA_NAME1,
	SHOBUN_INFO.GYOUSHA_NAME2,
	SHOBUN_INFO.GENBA_CD,
	SHOBUN_INFO.TODOUFUKEN_NAME,
	SHOBUN_INFO.GENBA_ADDRESS1,
	SHOBUN_INFO.GENBA_ADDRESS2,
	SHOBUN_INFO.JISHA_KBN
	/*END*/

ORDER BY
    HST_GYOUSHAGENBA,
    T_SUII.SYSTEM_ID,
    HAIKI_SHURUI_CD,
    HAIKI_SHURUI_NAME_RYAKU,
    UPN_ROUTE_NO,
    UPN_GYOUSHA_NAME,
    UPN_SAKI_GENBA_ADDRESS
