SELECT TOP 1
	GYOUSHA_CD AS CD,
	GYOUSHA_NAME_RYAKU AS NAME
FROM
	dbo.M_GYOUSHA
WHERE
	1 = 1
	AND GYOUSHAKBN_MANI = 1
	AND HAISHUTSU_NIZUMI_GYOUSHA_KBN = 1
	/*IF data.GYOUSHA_CD_FROM != null && data.GYOUSHA_CD_FROM != ''*/ AND M_GYOUSHA.GYOUSHA_CD = /*data.GYOUSHA_CD_FROM*//*END*/
ORDER BY
	GYOUSHA_CD DESC