SELECT
    HST_GYOUSHAGENBA,
    CHOKKOU_ROUTE_NO,
    SYSTEM_ID,
    HAIKI_KBN_CD,
    HOUKOKUSHOBUNRUISORTKEY,
    GOV_OR_MAY_NAME,
    CHIIKI_NAME_RYAKU,
    TODOUFUKEN_NAME,
	REPLACE(X.GYOUSHA_ADDRESS1,',','，') AS GYOUSHA_ADDRESS1,
    REPLACE(X.GYOUSHA_ADDRESS2,',','，') AS GYOUSHA_ADDRESS2,
	REPLACE(X.GYOUSHA_NAME1,',','，') AS GYOUSHA_NAME1,
	REPLACE(X.GYOUSHA_NAME2,',','，') AS GYOUSHA_NAME2,
    JISHA_KBN,
    DAIHYOUSHA,
    GYOUSHA_TEL,
    TITLE1,
    TITLE2,
	REPLACE(X.JGB_NAME,',','，') AS JGB_NAME,
    REPLACE(X.JGB_ADDRESS,',','，') AS JGB_ADDRESS,
    JGB_TODOUFUKEN_NAME,
    GYOUSHA_GYOUSHU_CD,
    GENBA_GYOUSHU_CD,
    GYOUSHA_GYOUSHU_NM,
    GENBA_GYOUSHU_NM,
    GYOUSHU_CD,
    GYOUSHU_NAME,
    GENBA_TEL,
    HAIKI_SHURUI_CD,
    HAIKI_SHURUI_NAME_RYAKU,
    HAISHU_RYOU,
    COUFUMAISUU,
    UPN_ROUTE_NO,
    UPN_FUTSUU_KYOKA_NO,
    UPN_GYOUSHA_CD,
    REPLACE(X.UPN_GYOUSHA_NAME,',','，') AS UPN_GYOUSHA_NAME,
	UPN_JISHA_KBN,
	UPN_SAKI_GYOUSHA_CD,
    UPN_SAKI_GENBA_CD,
    REPLACE(X.UPN_SAKI_GENBA_ADDRESS,',','，') AS UPN_SAKI_GENBA_ADDRESS,
    SBN_FUTSUU_KYOKA_NO,
    SBN_GYOUSHA_CD,
    REPLACE(X.SBN_GYOUSHA_NAME,',','，') AS SBN_GYOUSHA_NAME,
    SBN_GENBA_CD,
    REPLACE(X.SBN_GENBA_ADDRESS,',','，') AS SBN_GENBA_ADDRESS,
	SBN_GENBA_JISHA_KBN

FROM
(

--積替有の直行と建廃以外 = 積替無の直行と積替
--直行　排出事業場->(運搬業者)->処分事業場
--積替　排出事業場->(運搬業者)->処分事業場
--積替　排出事業場->(運搬業者)->積替保管場->(運搬業者)->処分事業場
--積替　排出事業場->(運搬業者)->積替保管場->(運搬業者)->積替保管場->(運搬業者)->処分事業場
SELECT
	/*IF data.GENBASHUKEI_KBN == '1'*/M_CHIIKI.CHIIKI_CD + TME.HST_GYOUSHA_CD AS HST_GYOUSHAGENBA,/*END*/
	/*IF data.GENBASHUKEI_KBN == '2'*/TME.HST_GYOUSHA_CD+TME.HST_GENBA_CD AS HST_GYOUSHAGENBA,/*END*/
    '0' AS CHOKKOU_ROUTE_NO,
    TME.SYSTEM_ID,
    TME.HAIKI_KBN_CD,
    TMD.HOUKOKUSHOBUNRUISORTKEY,
    M_CHIIKI.GOV_OR_MAY_NAME,
    M_CHIIKI.CHIIKI_NAME_RYAKU,
    GYOUSHA_TODOUFUKEN.TODOUFUKEN_NAME,
    M_GYOUSHA.GYOUSHA_ADDRESS1,
    M_GYOUSHA.GYOUSHA_ADDRESS2,
    M_GYOUSHA.GYOUSHA_NAME1,
    M_GYOUSHA.GYOUSHA_NAME2,
    M_GYOUSHA.JISHA_KBN,
    M_GYOUSHA.GYOUSHA_DAIHYOU AS DAIHYOUSHA,
    M_GYOUSHA.GYOUSHA_TEL,
    /*data.TITLE1*/ AS TITLE1,
    /*data.TITLE2*/ AS TITLE2,
    GENBA_JGB.GENBA_NAME1 + GENBA_JGB.GENBA_NAME2 AS JGB_NAME,
    GENBA_JGB.GENBA_ADDRESS1 + GENBA_JGB.GENBA_ADDRESS2 AS JGB_ADDRESS,
    TODOUFUKEN_JGB.TODOUFUKEN_NAME AS JGB_TODOUFUKEN_NAME,
    M_GYOUSHA.GYOUSHU_CD AS GYOUSHA_GYOUSHU_CD,
    GENBA_JGB.GYOUSHU_CD AS GENBA_GYOUSHU_CD,
    (SELECT TOP 1 GYOUSHU_NAME FROM M_GYOUSHU AS M1  WHERE M1.GYOUSHU_CD = M_GYOUSHA.GYOUSHU_CD) AS GYOUSHA_GYOUSHU_NM,
    (SELECT TOP 1 GYOUSHU_NAME FROM M_GYOUSHU AS M2  WHERE M2.GYOUSHU_CD = GENBA_JGB.GYOUSHU_CD) AS GENBA_GYOUSHU_NM,
    '' AS GYOUSHU_CD,
    '' AS GYOUSHU_NAME,
    GENBA_JGB.GENBA_TEL,
    TMD.HAIKI_SHURUI_CD,
    TMD.HAIKI_SHURUI_NAME_RYAKU,
    CASE
        WHEN Sum(CONVERT(money,TMD.KANSAN_SUU)) IS NOT NULL THEN Sum(CONVERT(money,TMD.KANSAN_SUU))
        ELSE 0
    END AS HAISHU_RYOU,
    0 AS COUFUMAISUU,
	CASE
		WHEN TMPT_UPN.UPN_ROUTE_NO = 1 THEN
			--1区間目の許可番号は、排出事業場の地域に対しての運搬許可番号を参照
			CASE
				WHEN TMD.SANPAI_KBN = 1 THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                             ELSE UPN_KYOKA.FUTSUU_KYOKA_NO
                        END
				WHEN TMD.SANPAI_KBN = 2 THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                             ELSE UPN_KYOKA.TOKUBETSU_KYOKA_NO
                        END
				ELSE
                    --普通許可番号があれば普通許可番号、なければ特管許可番号
                    CASE
                        WHEN ISNULL(UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                        WHEN ISNULL(UPN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN UPN_KYOKA.FUTSUU_KYOKA_NO
                        WHEN ISNULL(UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                        ELSE UPN_KYOKA.TOKUBETSU_KYOKA_NO
                    END
			END
		ELSE
			--2区間目以降の許可番号は、前区間の運搬先（積替保管施設）の事業場の地域に対しての運搬許可番号を参照
			CASE
				WHEN TMD.SANPAI_KBN = 1 THEN
                    --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                    CASE WHEN ISNULL(MAE_UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN MAE_UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                         ELSE MAE_UPN_KYOKA.FUTSUU_KYOKA_NO
                    END
				WHEN TMD.SANPAI_KBN = 2 THEN
                    --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                    CASE WHEN ISNULL(MAE_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN MAE_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                         ELSE MAE_UPN_KYOKA.TOKUBETSU_KYOKA_NO
                    END
				ELSE
                    --普通許可番号があれば普通許可番号、なければ特管許可番号
                    CASE
                        WHEN ISNULL(MAE_UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN MAE_UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                        WHEN ISNULL(MAE_UPN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN MAE_UPN_KYOKA.FUTSUU_KYOKA_NO
                        WHEN ISNULL(MAE_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN MAE_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                        ELSE MAE_UPN_KYOKA.TOKUBETSU_KYOKA_NO
                    END
			END
	END AS UPN_FUTSUU_KYOKA_NO,
    TMPT_UPN.UPN_ROUTE_NO,
    TMPT_UPN.UPN_GYOUSHA_CD,
    ISNULL(GENBA_UPN.GYOUSHA_NAME1 + GENBA_UPN.GYOUSHA_NAME2, '') AS UPN_GYOUSHA_NAME,
	ISNULL(GENBA_UPN.JISHA_KBN, 0) AS UPN_JISHA_KBN,
    ISNULL(TMPT_UPN.UPN_SAKI_GYOUSHA_CD, '') AS UPN_SAKI_GYOUSHA_CD,
    ISNULL(TMPT_UPN.UPN_SAKI_GENBA_CD, '') AS UPN_SAKI_GENBA_CD,
    ISNULL(UPN_GENBA_TODOUFUKEN.TODOUFUKEN_NAME + UPN_GENBA.GENBA_ADDRESS1 + UPN_GENBA.GENBA_ADDRESS2, '') AS UPN_SAKI_GENBA_ADDRESS,
	/*IF data.GYOUSHASET_KBN2 == '2' || data.GYOUSHASET_KBN2 == '4'*/ --[提出業者設定-2] = 2.運搬/排出事業者, 4.全て
	 --[提出業者設定-2] = 2.運搬/排出事業者, 4.全て
	CASE
		WHEN TME.HAIKI_KBN_CD = 1 THEN	--直行の時
			CASE
				WHEN TME.FIRST_MANIFEST_KBN = 0 THEN
					CASE
						WHEN TMD.SANPAI_KBN = 1 THEN SBN_KYOKA.FUTSUU_KYOKA_NO
						WHEN TMD.SANPAI_KBN = 2 THEN SBN_KYOKA.TOKUBETSU_KYOKA_NO
						ELSE
							CASE
								WHEN ISNULL(SBN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN SBN_KYOKA.FUTSUU_KYOKA_NO
								ELSE SBN_KYOKA.TOKUBETSU_KYOKA_NO
							END
					END
				WHEN TME.FIRST_MANIFEST_KBN = 1 THEN
					CASE
						WHEN TMD.SANPAI_KBN = 1 THEN LAST_SBN_KYOKA.FUTSUU_KYOKA_NO
						WHEN TMD.SANPAI_KBN = 2 THEN LAST_SBN_KYOKA.TOKUBETSU_KYOKA_NO
						ELSE
							CASE
								WHEN ISNULL(LAST_SBN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN LAST_SBN_KYOKA.FUTSUU_KYOKA_NO
								ELSE LAST_SBN_KYOKA.TOKUBETSU_KYOKA_NO
							END
					END
			END
		WHEN TME.HAIKI_KBN_CD = 3 THEN	--積替の時
			CASE
				WHEN TMPT_UPN.UPN_SAKI_KBN = 1 THEN		--処分施設
					CASE
						WHEN TME.FIRST_MANIFEST_KBN = 0 THEN
							CASE
								WHEN TMD.SANPAI_KBN = 1 THEN SBN_KYOKA.FUTSUU_KYOKA_NO
								WHEN TMD.SANPAI_KBN = 2 THEN SBN_KYOKA.TOKUBETSU_KYOKA_NO
								ELSE
									CASE
										WHEN ISNULL(SBN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN SBN_KYOKA.FUTSUU_KYOKA_NO
										ELSE SBN_KYOKA.TOKUBETSU_KYOKA_NO
									END
							END
						WHEN TME.FIRST_MANIFEST_KBN = 1 THEN
							CASE
								WHEN TMD.SANPAI_KBN = 1 THEN LAST_SBN_KYOKA.FUTSUU_KYOKA_NO
								WHEN TMD.SANPAI_KBN = 2 THEN LAST_SBN_KYOKA.TOKUBETSU_KYOKA_NO
								ELSE
									CASE
										WHEN ISNULL(LAST_SBN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN LAST_SBN_KYOKA.FUTSUU_KYOKA_NO
										ELSE LAST_SBN_KYOKA.TOKUBETSU_KYOKA_NO
									END
							END
					END
				ELSE ''
			END
	END	AS SBN_FUTSUU_KYOKA_NO,
    CASE
		WHEN TME.HAIKI_KBN_CD = 1 THEN TME.SBN_GYOUSHA_CD		--直行の時
		WHEN HAIKI_KBN_CD = 3 THEN		--積替の時
			CASE
				WHEN TMPT_UPN.UPN_SAKI_KBN = 1 THEN TME.SBN_GYOUSHA_CD		--処分施設
				ELSE ''		--積替保管,または設定なし
			END
	END AS SBN_GYOUSHA_CD,
    CASE
		WHEN TME.HAIKI_KBN_CD = 1 THEN TME_SBN_GYOUSHA.GYOUSHA_NAME1 + TME_SBN_GYOUSHA.GYOUSHA_NAME2		--直行の時
		WHEN HAIKI_KBN_CD = 3 THEN		--積替の時
			CASE WHEN TMPT_UPN.UPN_SAKI_KBN = 1 THEN TME_SBN_GYOUSHA.GYOUSHA_NAME1 + TME_SBN_GYOUSHA.GYOUSHA_NAME2		--処分施設
				ELSE ''		--積替保管,または設定なし
			END
	END AS SBN_GYOUSHA_NAME,
    CASE
		WHEN TME.HAIKI_KBN_CD = 1 THEN TMPT_UPN.UPN_SAKI_GENBA_CD		--直行の時
		WHEN HAIKI_KBN_CD = 3 THEN		--積替の時
			CASE
				WHEN TMPT_UPN.UPN_SAKI_KBN = 1 THEN TMPT_UPN.UPN_SAKI_GENBA_CD		--処分施設
				ELSE ''		--積替保管,または設定なし
			END
	END AS SBN_GENBA_CD,
    CASE
		WHEN TME.HAIKI_KBN_CD = 1 THEN UPN_GENBA_TODOUFUKEN.TODOUFUKEN_NAME + UPN_GENBA.GENBA_ADDRESS1 + UPN_GENBA.GENBA_ADDRESS2		--直行の時
		WHEN HAIKI_KBN_CD = 3 THEN		--積替の時
			CASE
				WHEN TMPT_UPN.UPN_SAKI_KBN = 1 THEN UPN_GENBA_TODOUFUKEN.TODOUFUKEN_NAME + UPN_GENBA.GENBA_ADDRESS1 + UPN_GENBA.GENBA_ADDRESS2		--処分施設
				ELSE ''		--積替保管,または設定なし
			END
	END AS SBN_GENBA_ADDRESS,
    CASE
		WHEN TME.HAIKI_KBN_CD = 1 THEN UPN_GENBA.JISHA_KBN		--直行の時
		WHEN HAIKI_KBN_CD = 3 THEN		--積替の時
			CASE
				WHEN TMPT_UPN.UPN_SAKI_KBN = 1 THEN UPN_GENBA.JISHA_KBN		--処分施設
				ELSE 0		--積替保管,または設定なし
			END
	END AS SBN_GENBA_JISHA_KBN
	/*END*/
	/*IF data.GYOUSHASET_KBN2 == '1' || data.GYOUSHASET_KBN2 == '3'*/ --[提出業者設定-2] = 1.収集運搬/自社, 3.収集運搬/他社
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN ''		--処分受託者欄に処分受託者を表示していい区間ではない(後区間にて表示される)
		ELSE
			CASE
				WHEN TME.FIRST_MANIFEST_KBN = 0 THEN
					CASE
						WHEN TMD.SANPAI_KBN = 1 THEN SHOBUN_INFO.FUTSUU_KYOKA_NO
						WHEN TMD.SANPAI_KBN = 2 THEN SHOBUN_INFO.TOKUBETSU_KYOKA_NO
						ELSE
							CASE
								WHEN ISNULL(SHOBUN_INFO.FUTSUU_KYOKA_NO, '') != '' THEN SHOBUN_INFO.FUTSUU_KYOKA_NO
								ELSE SHOBUN_INFO.TOKUBETSU_KYOKA_NO
							END
					END
				WHEN TME.FIRST_MANIFEST_KBN = 1 THEN
					CASE
						WHEN TMD.SANPAI_KBN = 1 THEN SHOBUN_INFO.LAST_FUTSUU_KYOKA_NO
						WHEN TMD.SANPAI_KBN = 2 THEN SHOBUN_INFO.LAST_TOKUBETSU_KYOKA_NO
						ELSE
							CASE
								WHEN ISNULL(SHOBUN_INFO.LAST_FUTSUU_KYOKA_NO, '') != '' THEN SHOBUN_INFO.LAST_FUTSUU_KYOKA_NO
								ELSE SHOBUN_INFO.LAST_TOKUBETSU_KYOKA_NO
							END
					END
			END
		END AS SBN_FUTSUU_KYOKA_NO,
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN ''
		ELSE SHOBUN_INFO.GYOUSHA_CD
        END AS SBN_GYOUSHA_CD,
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN ''
		ELSE SHOBUN_INFO.GYOUSHA_NAME1 + SHOBUN_INFO.GYOUSHA_NAME2
		END AS SBN_GYOUSHA_NAME,
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN ''
		ELSE SHOBUN_INFO.GENBA_CD
        END AS SBN_GENBA_CD,
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN ''
		ELSE SHOBUN_INFO.TODOUFUKEN_NAME + SHOBUN_INFO.GENBA_ADDRESS1 + SHOBUN_INFO.GENBA_ADDRESS2
        END AS SBN_GENBA_ADDRESS,
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN 0
		ELSE SHOBUN_INFO.JISHA_KBN
        END AS SBN_GENBA_JISHA_KBN
	/*END*/
FROM T_MANIFEST_ENTRY AS TME
INNER JOIN T_MANIFEST_UPN AS TMPT_UPN ON (TME.SYSTEM_ID = TMPT_UPN.SYSTEM_ID AND TME.SEQ = TMPT_UPN.SEQ AND ((TMPT_UPN.UPN_GYOUSHA_CD <> '' AND TMPT_UPN.UPN_GYOUSHA_CD IS NOT NULL) OR (TMPT_UPN.UPN_SAKI_GENBA_CD <> '' AND TMPT_UPN.UPN_SAKI_GENBA_CD IS NOT NULL)))
LEFT JOIN T_MANIFEST_UPN AS MAE_UPN ON (TMPT_UPN.SYSTEM_ID = MAE_UPN.SYSTEM_ID AND TMPT_UPN.SEQ = MAE_UPN.SEQ AND TMPT_UPN.UPN_ROUTE_NO = MAE_UPN.UPN_ROUTE_NO + 1)
/*IF data.KONGOU_KBN == '1'*/--■混合出力有
LEFT JOIN
    (SELECT 
        TME1.SYSTEM_ID,
        TME1.SEQ,
        CASE
            WHEN Sum(CONVERT(money,TMD1.KANSAN_SUU)) IS NOT NULL THEN Sum(CONVERT(money,TMD1.KANSAN_SUU))
            ELSE 0
        END AS KANSAN_SUU,
        CASE
            WHEN COUNT(DISTINCT HOUKOKU.HOUKOKUSHO_BUNRUI_CD) > 1 THEN 2
            ELSE 1
        END AS HOUKOKUSHOBUNRUISORTKEY,
        CASE
            WHEN COUNT(DISTINCT HOUKOKU.HOUKOKUSHO_BUNRUI_CD) > 1 THEN ''
            ELSE MAX(HOUKOKU.HOUKOKUSHO_BUNRUI_CD)
        END AS HAIKI_SHURUI_CD,
        CASE
            WHEN COUNT(DISTINCT HOUKOKU.HOUKOKUSHO_BUNRUI_CD) > 1 THEN '混合廃棄物'
            ELSE MAX(HOUKOKU.HOUKOKUSHO_BUNRUI_NAME)
        END AS HAIKI_SHURUI_NAME_RYAKU,
        CASE
			WHEN SUM(CASE WHEN ISNULL(HAIKI.HAIKI_SHURUI_CD, '') < '7000' THEN 0 ELSE 1 END) = 0 THEN 1	--普通産廃のみ
			WHEN SUM(CASE WHEN ISNULL(HAIKI.HAIKI_SHURUI_CD, '') < '7000' THEN 0 ELSE 1 END) = COUNT(HAIKI.HAIKI_SHURUI_CD) THEN 2	--特管産廃のみ
			ELSE 3 --混在
		END AS SANPAI_KBN
     FROM T_MANIFEST_ENTRY AS TME1
     LEFT JOIN T_MANIFEST_DETAIL AS TMD1 ON (TME1.SYSTEM_ID = TMD1.SYSTEM_ID AND TME1.SEQ = TMD1.SEQ)
     LEFT JOIN M_HAIKI_SHURUI AS HAIKI ON (TME1.HAIKI_KBN_CD = HAIKI.HAIKI_KBN_CD AND TMD1.HAIKI_SHURUI_CD = HAIKI.HAIKI_SHURUI_CD)
     LEFT JOIN M_HOUKOKUSHO_BUNRUI AS HOUKOKU ON  HAIKI.HOUKOKUSHO_BUNRUI_CD = HOUKOKU.HOUKOKUSHO_BUNRUI_CD
     WHERE   TME1.DELETE_FLG = 0
          AND ((TME1.KOUFU_DATE) >= /*data.KOUFU_DATE_FROM*/ AND (TME1.KOUFU_DATE) <= /*data.KOUFU_DATE_TO*/)
     GROUP BY TME1.SYSTEM_ID,TME1.SEQ ) AS TMD ON (TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ)
/*END*/
/*IF data.KONGOU_KBN == '2'*/--■混合出力無
LEFT JOIN 
    (SELECT
        TME1.SYSTEM_ID,
        TME1.SEQ,
        CASE
            WHEN Sum(CONVERT(money,TMD1.KANSAN_SUU)) IS NOT NULL THEN Sum(CONVERT(money,TMD1.KANSAN_SUU))
            ELSE 0
        END AS KANSAN_SUU,
        1 AS HOUKOKUSHOBUNRUISORTKEY,
        HOUKOKU.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_CD,
        HOUKOKU.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_NAME_RYAKU,
        CASE
			WHEN SUM(CASE WHEN ISNULL(HAIKI.HAIKI_SHURUI_CD, '') < '7000' THEN 0 ELSE 1 END) = 0 THEN 1	--普通産廃のみ
			WHEN SUM(CASE WHEN ISNULL(HAIKI.HAIKI_SHURUI_CD, '') < '7000' THEN 0 ELSE 1 END) = COUNT(HAIKI.HAIKI_SHURUI_CD) THEN 2	--特管産廃のみ
			ELSE 3 --混在
		END AS SANPAI_KBN
    FROM T_MANIFEST_ENTRY AS TME1
    LEFT JOIN T_MANIFEST_DETAIL AS TMD1 ON (TME1.SYSTEM_ID = TMD1.SYSTEM_ID AND TME1.SEQ = TMD1.SEQ)
    LEFT JOIN M_HAIKI_SHURUI AS HAIKI ON (TME1.HAIKI_KBN_CD = HAIKI.HAIKI_KBN_CD AND TMD1.HAIKI_SHURUI_CD = HAIKI.HAIKI_SHURUI_CD)
    LEFT JOIN M_HOUKOKUSHO_BUNRUI AS HOUKOKU ON  HAIKI.HOUKOKUSHO_BUNRUI_CD = HOUKOKU.HOUKOKUSHO_BUNRUI_CD
    WHERE TME1.DELETE_FLG = 0
		AND ((TME1.KOUFU_DATE) >= /*data.KOUFU_DATE_FROM*/ AND (TME1.KOUFU_DATE) <= /*data.KOUFU_DATE_TO*/)
    GROUP BY TME1.SYSTEM_ID,TME1.SEQ,HOUKOKU.HOUKOKUSHO_BUNRUI_CD,HOUKOKU.HOUKOKUSHO_BUNRUI_NAME) AS TMD ON (TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ)
/*END*/
LEFT JOIN M_GYOUSHA AS GENBA_UPN ON (TMPT_UPN.UPN_GYOUSHA_CD = GENBA_UPN.GYOUSHA_CD)
LEFT JOIN M_GENBA AS GENBA_SBN ON (TME.SBN_GYOUSHA_CD = GENBA_SBN.GYOUSHA_CD AND TMPT_UPN.UPN_SAKI_GENBA_CD = GENBA_SBN.GENBA_CD)
LEFT JOIN M_GENBA AS GENBA_CHK ON (TME.HST_GYOUSHA_CD = GENBA_CHK.GYOUSHA_CD AND TME.HST_GENBA_CD = GENBA_CHK.GENBA_CD)
LEFT JOIN M_CHIIKI  ON (GENBA_CHK.CHIIKI_CD = M_CHIIKI.CHIIKI_CD)
LEFT JOIN M_GYOUSHA ON (TME.HST_GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD)
LEFT JOIN M_TODOUFUKEN AS GYOUSHA_TODOUFUKEN ON (M_GYOUSHA.GYOUSHA_TODOUFUKEN_CD = GYOUSHA_TODOUFUKEN.TODOUFUKEN_CD)
LEFT JOIN M_GENBA AS GENBA_JGB ON (TME.HST_GYOUSHA_CD = GENBA_JGB.GYOUSHA_CD AND TME.HST_GENBA_CD = GENBA_JGB.GENBA_CD)
LEFT JOIN M_TODOUFUKEN AS TODOUFUKEN_JGB ON (GENBA_JGB.GENBA_TODOUFUKEN_CD = TODOUFUKEN_JGB.TODOUFUKEN_CD)
LEFT JOIN M_GENBA AS UPN_GENBA ON ( TMPT_UPN.UPN_SAKI_GYOUSHA_CD = UPN_GENBA.GYOUSHA_CD AND TMPT_UPN.UPN_SAKI_GENBA_CD = UPN_GENBA.GENBA_CD)
LEFT JOIN M_TODOUFUKEN AS UPN_GENBA_TODOUFUKEN ON ( UPN_GENBA.GENBA_TODOUFUKEN_CD = UPN_GENBA_TODOUFUKEN.TODOUFUKEN_CD )
LEFT JOIN M_GENBA AS MAE_UPN_GENBA ON (MAE_UPN.UPN_SAKI_GYOUSHA_CD = MAE_UPN_GENBA.GYOUSHA_CD AND MAE_UPN.UPN_SAKI_GENBA_CD = MAE_UPN_GENBA.GENBA_CD)
LEFT JOIN M_GYOUSHA AS TME_SBN_GYOUSHA ON ( TME.SBN_GYOUSHA_CD = TME_SBN_GYOUSHA.GYOUSHA_CD)
LEFT JOIN (
			--1区間目の許可番号は、排出事業場の地域に対しての運搬許可番号を参照
			--許可番号の対応品目はコンプライアンス上で必要なものなので、報告書ではそこまで判断しない。
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS UPN_KYOKA ON (TMPT_UPN.UPN_GYOUSHA_CD = UPN_KYOKA.GYOUSHA_CD AND GENBA_JGB.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = UPN_KYOKA.CHIIKI_CD AND UPN_KYOKA.KYOKA_KBN = 1)
LEFT JOIN (
            --地域に対しての許可番号。政令指定都市＞都道府県の順に許可番号を適用するため、運搬報告書提出先の地域、地域に対しての許可番号を取得する
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS UPN_KYOKA_CK ON (TMPT_UPN.UPN_GYOUSHA_CD = UPN_KYOKA_CK.GYOUSHA_CD AND GENBA_JGB.CHIIKI_CD = UPN_KYOKA_CK.CHIIKI_CD AND UPN_KYOKA_CK.KYOKA_KBN = 1)
LEFT JOIN (
			--2区間目以降の許可番号は、前区間の運搬先（積替保管施設）の事業場の地域に対しての運搬許可番号を参照
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS MAE_UPN_KYOKA ON (TMPT_UPN.UPN_GYOUSHA_CD = MAE_UPN_KYOKA.GYOUSHA_CD AND MAE_UPN_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = MAE_UPN_KYOKA.CHIIKI_CD AND MAE_UPN_KYOKA.KYOKA_KBN = 1)
LEFT JOIN (
            --地域に対しての許可番号。政令指定都市＞都道府県の順に許可番号を適用するため、運搬報告書提出先の地域、地域に対しての許可番号を取得する
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS MAE_UPN_KYOKA_CK ON (TMPT_UPN.UPN_GYOUSHA_CD = MAE_UPN_KYOKA_CK.GYOUSHA_CD AND MAE_UPN_GENBA.CHIIKI_CD = MAE_UPN_KYOKA_CK.CHIIKI_CD AND MAE_UPN_KYOKA_CK.KYOKA_KBN = 1)
LEFT JOIN (
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.GENBA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 2
) AS SBN_KYOKA ON (TME.SBN_GYOUSHA_CD = SBN_KYOKA.GYOUSHA_CD AND TMPT_UPN.UPN_SAKI_GENBA_CD = SBN_KYOKA.GENBA_CD AND GENBA_SBN.CHIIKI_CD = SBN_KYOKA.CHIIKI_CD AND SBN_KYOKA.KYOKA_KBN = 2)
LEFT JOIN (
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.GENBA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 3
) AS LAST_SBN_KYOKA ON (TME.SBN_GYOUSHA_CD = LAST_SBN_KYOKA.GYOUSHA_CD AND TMPT_UPN.UPN_SAKI_GENBA_CD = LAST_SBN_KYOKA.GENBA_CD AND GENBA_SBN.CHIIKI_CD = LAST_SBN_KYOKA.CHIIKI_CD AND LAST_SBN_KYOKA.KYOKA_KBN = 3)
/*IF data.GYOUSHASET_KBN2 == '1' || data.GYOUSHASET_KBN2 == '3'*/ --[提出業者設定-2] = 1.収集運搬/自社, 3.収集運搬/他社
LEFT JOIN
(
	SELECT
		MAX(T_MANIFEST_UPN.UPN_ROUTE_NO) MAX_UPN_ROUTE_NO,
		T_MANIFEST_UPN.SYSTEM_ID,
		T_MANIFEST_UPN.SEQ
	FROM
		T_MANIFEST_UPN
		INNER JOIN T_MANIFEST_ENTRY ON T_MANIFEST_ENTRY.SYSTEM_ID = T_MANIFEST_UPN.SYSTEM_ID AND T_MANIFEST_ENTRY.SEQ = T_MANIFEST_UPN.SEQ AND T_MANIFEST_ENTRY.DELETE_FLG = 0 AND (T_MANIFEST_ENTRY.KOUFU_DATE >= /*data.KOUFU_DATE_FROM*/ AND T_MANIFEST_ENTRY.KOUFU_DATE <= /*data.KOUFU_DATE_TO*/)
		INNER JOIN M_GYOUSHA ON T_MANIFEST_UPN.UPN_GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
		/*IF data.GYOUSHASET_KBN2 == '1'*/ AND M_GYOUSHA.JISHA_KBN <> 0/*END*/
		/*IF data.GYOUSHASET_KBN2 == '3'*/ AND M_GYOUSHA.JISHA_KBN = 0/*END*/
	GROUP BY
		T_MANIFEST_UPN.SYSTEM_ID,
		T_MANIFEST_UPN.SEQ
) AS SBN_DISP_ROUTE_NO ON TMPT_UPN.SYSTEM_ID = SBN_DISP_ROUTE_NO.SYSTEM_ID AND TMPT_UPN.SEQ = SBN_DISP_ROUTE_NO.SEQ AND TMPT_UPN.UPN_ROUTE_NO = SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO
LEFT JOIN
(
	SELECT
		T_MANIFEST_UPN.SYSTEM_ID,
		T_MANIFEST_UPN.SEQ,
		T_MANIFEST_UPN.UPN_SAKI_GYOUSHA_CD AS GYOUSHA_CD,
		M_GYOUSHA.GYOUSHA_NAME1,
		M_GYOUSHA.GYOUSHA_NAME2,
		T_MANIFEST_UPN.UPN_SAKI_GENBA_CD AS GENBA_CD,
		M_TODOUFUKEN.TODOUFUKEN_NAME,
		M_GENBA.GENBA_ADDRESS1,
		M_GENBA.GENBA_ADDRESS2,
		M_GENBA.JISHA_KBN,
		KYOKA.FUTSUU_KYOKA_NO,
		KYOKA.TOKUBETSU_KYOKA_NO,
		LAST_KYOKA.FUTSUU_KYOKA_NO AS LAST_FUTSUU_KYOKA_NO,
		LAST_KYOKA.TOKUBETSU_KYOKA_NO AS LAST_TOKUBETSU_KYOKA_NO
	FROM
		T_MANIFEST_UPN
		INNER JOIN T_MANIFEST_ENTRY ON T_MANIFEST_ENTRY.SYSTEM_ID = T_MANIFEST_UPN.SYSTEM_ID AND T_MANIFEST_ENTRY.SEQ = T_MANIFEST_UPN.SEQ AND T_MANIFEST_ENTRY.DELETE_FLG = 0 AND T_MANIFEST_ENTRY.DELETE_FLG = 0 AND (T_MANIFEST_ENTRY.KOUFU_DATE >= /*data.KOUFU_DATE_FROM*/ AND T_MANIFEST_ENTRY.KOUFU_DATE <= /*data.KOUFU_DATE_TO*/)
		INNER JOIN
		(
		SELECT
			MAX(T_MANIFEST_UPN.UPN_ROUTE_NO) MAX_UPN_ROUTE_NO,
			T_MANIFEST_UPN.SYSTEM_ID,
			T_MANIFEST_UPN.SEQ
		FROM
			T_MANIFEST_UPN
			INNER JOIN T_MANIFEST_ENTRY ON T_MANIFEST_ENTRY.SYSTEM_ID = T_MANIFEST_UPN.SYSTEM_ID AND T_MANIFEST_ENTRY.SEQ = T_MANIFEST_UPN.SEQ AND T_MANIFEST_ENTRY.DELETE_FLG = 0 AND T_MANIFEST_ENTRY.DELETE_FLG = 0 AND (T_MANIFEST_ENTRY.KOUFU_DATE >= /*data.KOUFU_DATE_FROM*/ AND T_MANIFEST_ENTRY.KOUFU_DATE <= /*data.KOUFU_DATE_TO*/)
			INNER JOIN M_GYOUSHA ON T_MANIFEST_UPN.UPN_GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
		GROUP BY
			T_MANIFEST_UPN.SYSTEM_ID,
			T_MANIFEST_UPN.SEQ
		) AS T_MANIFEST_LAST_UPN ON T_MANIFEST_UPN.SYSTEM_ID = T_MANIFEST_LAST_UPN.SYSTEM_ID AND T_MANIFEST_UPN.SEQ = T_MANIFEST_LAST_UPN.SEQ AND T_MANIFEST_UPN.UPN_ROUTE_NO = T_MANIFEST_LAST_UPN.MAX_UPN_ROUTE_NO
		LEFT JOIN M_GYOUSHA ON T_MANIFEST_UPN.UPN_SAKI_GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
		LEFT JOIN M_GENBA ON T_MANIFEST_UPN.UPN_SAKI_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND T_MANIFEST_UPN.UPN_SAKI_GENBA_CD = M_GENBA.GENBA_CD
		LEFT JOIN M_TODOUFUKEN ON M_GENBA.GENBA_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD
		LEFT JOIN (
					SELECT
						M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
						M_CHIIKIBETSU_KYOKA.GENBA_CD,
						M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
						M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
						M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
						M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
					FROM
						M_CHIIKIBETSU_KYOKA
					WHERE
						M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 2
		) AS KYOKA ON (T_MANIFEST_UPN.UPN_SAKI_GYOUSHA_CD = KYOKA.GYOUSHA_CD AND T_MANIFEST_UPN.UPN_SAKI_GENBA_CD = KYOKA.GENBA_CD AND M_GENBA.CHIIKI_CD = KYOKA.CHIIKI_CD AND KYOKA.KYOKA_KBN = 2)
		LEFT JOIN (
					SELECT
						M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
						M_CHIIKIBETSU_KYOKA.GENBA_CD,
						M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
						M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
						M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
						M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
					FROM
						M_CHIIKIBETSU_KYOKA
					WHERE
						M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 3
		) AS LAST_KYOKA ON (T_MANIFEST_UPN.UPN_SAKI_GYOUSHA_CD = LAST_KYOKA.GYOUSHA_CD AND T_MANIFEST_UPN.UPN_SAKI_GENBA_CD = LAST_KYOKA.GENBA_CD AND M_GENBA.CHIIKI_CD = LAST_KYOKA.CHIIKI_CD AND LAST_KYOKA.KYOKA_KBN = 3)
	GROUP BY
		T_MANIFEST_UPN.SYSTEM_ID,
		T_MANIFEST_UPN.SEQ,
		T_MANIFEST_UPN.UPN_SAKI_GYOUSHA_CD,
		M_GYOUSHA.GYOUSHA_NAME1,
		M_GYOUSHA.GYOUSHA_NAME2,
		T_MANIFEST_UPN.UPN_SAKI_GENBA_CD,
		M_TODOUFUKEN.TODOUFUKEN_NAME,
		M_GENBA.GENBA_ADDRESS1,
		M_GENBA.GENBA_ADDRESS2,
		M_GENBA.JISHA_KBN,
		KYOKA.FUTSUU_KYOKA_NO,
		KYOKA.TOKUBETSU_KYOKA_NO,
		LAST_KYOKA.FUTSUU_KYOKA_NO,
		LAST_KYOKA.TOKUBETSU_KYOKA_NO
) AS SHOBUN_INFO ON TME.SYSTEM_ID = SHOBUN_INFO.SYSTEM_ID AND TME.SEQ = SHOBUN_INFO.SEQ
/*END*/

WHERE TME.DELETE_FLG = 0 AND ((TME.KOUFU_DATE) >= /*data.KOUFU_DATE_FROM*/ AND (TME.KOUFU_DATE) <= /*data.KOUFU_DATE_TO*/)
    AND (TME.HAIKI_KBN_CD = 3 OR (TME.HAIKI_KBN_CD = 1 AND (TME.TMH_GYOUSHA_CD = '' OR TME.TMH_GYOUSHA_CD IS NULL)))
/*IF data.GYOUSHU != null && data.GYOUSHU != ''*/
	AND (GENBA_JGB.GYOUSHU_CD = /*data.GYOUSHU*/ OR (M_GYOUSHA.GYOUSHU_CD = /*data.GYOUSHU*/ AND (GENBA_JGB.GYOUSHU_CD = '' OR GENBA_JGB.GYOUSHU_CD IS NULL)))
/*END*/

/*IF data.GYOUSHASET_KBN1 == '1'*/ --if --[提出業者設定-1] = 1.個別(提出業者:FROMのみ)	
 /*IF data.GENBASHUKEI_KBN == '2'*/--現場一括集計:1する,2:しない
   AND(TME.HST_GENBA_CD >=/*data.GENBA_CD_FROM*/ AND TME.HST_GENBA_CD <=/*data.GENBA_CD_TO*/ )
   /*END*/	
    /*IF data.TEISHUTUSAKI_KBN == '1'*/ --if --[提出先] = 1.全体(都道府県政令の指定検索しない)
				/*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社
								AND ((TME.HST_GYOUSHA_CD)= /*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND GENBA_UPN.JISHA_KBN <> 0
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者	
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND (TME.HST_GYOUSHA_CD = TMPT_UPN.UPN_GYOUSHA_CD)
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社			
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND TME.HST_GENBA_CD <> '') AND (GENBA_UPN.JISHA_KBN = 0 OR GENBA_UPN.JISHA_KBN is NULL) AND (TME.HST_GYOUSHA_CD <> TMPT_UPN.UPN_GYOUSHA_CD OR TMPT_UPN.UPN_GYOUSHA_CD is NULL)		
				/*END*/							
				/*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て	
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '')
				/*END*/	
	 /*END*/	
	 /*IF data.TEISHUTUSAKI_KBN == '2'*/ --	else if --[提出先] = 2.個別(都道府県政令の指定検索する)								
				/*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社			
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND GENBA_UPN.JISHA_KBN <> 0 AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/
				/*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者			
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND (TME.HST_GYOUSHA_CD = TMPT_UPN.UPN_GYOUSHA_CD) AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/
				/*END*/
				/*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社		
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND (GENBA_UPN.JISHA_KBN = 0 OR GENBA_UPN.JISHA_KBN is NULL) AND (TME.HST_GYOUSHA_CD <> TMPT_UPN.UPN_GYOUSHA_CD OR TMPT_UPN.UPN_GYOUSHA_CD is NULL)		
								AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/		
				/*END*/
				/*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て		
								AND TME.HST_GYOUSHA_CD =/*data.GYOUSHA_CD_FROM*/ AND TME.HST_GENBA_CD <> '' AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/
	/*END*/
/*END*/	
/*IF data.GYOUSHASET_KBN1 == '2'*/--else if--[提出業者設定-1] = 2.全体(提出業者:FROM/TO)										
		/*IF data.TEISHUTUSAKI_KBN == '1'*/ --if --[提出先] = 1.全体(都道府県政令の指定検索しない)								
				/*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/ ) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <> '')		
								AND GENBA_UPN.JISHA_KBN <> 0	
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <>  '')		
								AND (TME.HST_GYOUSHA_CD = TMPT_UPN.UPN_GYOUSHA_CD)
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/ )) AND (TME.HST_GENBA_CD) <> '')		
								AND ((GENBA_UPN.JISHA_KBN = 0) OR ((GENBA_UPN.JISHA_KBN)is NULL)) AND ((TME.HST_GYOUSHA_CD <> TMPT_UPN.UPN_GYOUSHA_CD) OR ((TMPT_UPN.UPN_GYOUSHA_CD)is NULL))		
										
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <> '')
				/*END*/
		/*END*/	
		/*IF data.TEISHUTUSAKI_KBN == '2'*/ --else if--[提出先] = 2.個別(都道府県政令の指定検索する)								
				/*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社			
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/ ) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <> '')		
								AND GENBA_UPN.JISHA_KBN <> 0 AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <>  '')		
								AND (TME.HST_GYOUSHA_CD = TMPT_UPN.UPN_GYOUSHA_CD) AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社			
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/ )) AND (TME.HST_GENBA_CD) <> '')		
								AND ((GENBA_UPN.JISHA_KBN = 0) OR ((GENBA_UPN.JISHA_KBN)is NULL)) AND ((TME.HST_GYOUSHA_CD <> TMPT_UPN.UPN_GYOUSHA_CD) OR ((TMPT_UPN.UPN_GYOUSHA_CD)is NULL))		
								AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/		
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て			
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <> '')		
								AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/		
		/*END*/
/*END*/
GROUP BY
    /*IF data.GENBASHUKEI_KBN == '1'*/M_CHIIKI.CHIIKI_CD,/*END*/
    TME.HST_GYOUSHA_CD,
	/*IF data.GENBASHUKEI_KBN == '2'*/TME.HST_GENBA_CD,/*END*/
    TME.SYSTEM_ID,
    TME.HAIKI_KBN_CD,
	TME.FIRST_MANIFEST_KBN,
    TMD.HOUKOKUSHOBUNRUISORTKEY,
    M_CHIIKI.GOV_OR_MAY_NAME,
    M_CHIIKI.CHIIKI_NAME_RYAKU,
    GYOUSHA_TODOUFUKEN.TODOUFUKEN_NAME,
    M_GYOUSHA.GYOUSHA_ADDRESS1,
    M_GYOUSHA.GYOUSHA_ADDRESS2,
    M_GYOUSHA.GYOUSHA_NAME1,
    M_GYOUSHA.GYOUSHA_NAME2,
    M_GYOUSHA.JISHA_KBN,
    M_GYOUSHA.GYOUSHA_DAIHYOU,
    M_GYOUSHA.GYOUSHA_TEL,
    GENBA_JGB.GENBA_NAME1,
    GENBA_JGB.GENBA_NAME2,
    GENBA_JGB.GENBA_ADDRESS1,
    GENBA_JGB.GENBA_ADDRESS2,
    TODOUFUKEN_JGB.TODOUFUKEN_NAME,
    M_GYOUSHA.GYOUSHU_CD,
    GENBA_JGB.GYOUSHU_CD,
    GENBA_JGB.GENBA_TEL,
    TMD.HAIKI_SHURUI_CD,
    TMD.HAIKI_SHURUI_NAME_RYAKU,
	TMD.SANPAI_KBN,
    UPN_KYOKA.FUTSUU_KYOKA_NO,
    UPN_KYOKA.TOKUBETSU_KYOKA_NO,
    UPN_KYOKA_CK.FUTSUU_KYOKA_NO,
    UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO,
    MAE_UPN_KYOKA.FUTSUU_KYOKA_NO,
    MAE_UPN_KYOKA.TOKUBETSU_KYOKA_NO,
    MAE_UPN_KYOKA_CK.FUTSUU_KYOKA_NO,
    MAE_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO,
    TMPT_UPN.UPN_ROUTE_NO,
    TMPT_UPN.UPN_GYOUSHA_CD,
    GENBA_UPN.GYOUSHA_NAME1,
    GENBA_UPN.GYOUSHA_NAME2,
	GENBA_UPN.JISHA_KBN,
    TMPT_UPN.UPN_GYOUSHA_NAME,
    TMPT_UPN.UPN_SAKI_GYOUSHA_CD,
    TMPT_UPN.UPN_SAKI_GENBA_CD,
    UPN_GENBA_TODOUFUKEN.TODOUFUKEN_NAME,
    UPN_GENBA.GENBA_ADDRESS1,
    UPN_GENBA.GENBA_ADDRESS2,
	UPN_GENBA.JISHA_KBN,
    TMPT_UPN.UPN_SAKI_GENBA_ADDRESS,
	/*IF data.GYOUSHASET_KBN2 == '2' || data.GYOUSHASET_KBN2 == '4'*/ --[提出業者設定-2] = 2.運搬/排出事業者, 4.全て
	TMPT_UPN.UPN_SAKI_KBN,
	/*END*/
    SBN_KYOKA.FUTSUU_KYOKA_NO,
    SBN_KYOKA.TOKUBETSU_KYOKA_NO,
    LAST_SBN_KYOKA.FUTSUU_KYOKA_NO,
    LAST_SBN_KYOKA.TOKUBETSU_KYOKA_NO,
    TME.SBN_GYOUSHA_CD,
    TME_SBN_GYOUSHA.GYOUSHA_NAME1,
    TME_SBN_GYOUSHA.GYOUSHA_NAME2
	/*IF data.GYOUSHASET_KBN2 == '1' || data.GYOUSHASET_KBN2 == '3'*/ --[提出業者設定-2] = 1.収集運搬/自社 ,3.収集運搬/他社
	,SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO,
	SHOBUN_INFO.FUTSUU_KYOKA_NO,
	SHOBUN_INFO.TOKUBETSU_KYOKA_NO,
	SHOBUN_INFO.LAST_FUTSUU_KYOKA_NO,
	SHOBUN_INFO.LAST_TOKUBETSU_KYOKA_NO,
	SHOBUN_INFO.GYOUSHA_CD,
	SHOBUN_INFO.GYOUSHA_NAME1,
	SHOBUN_INFO.GYOUSHA_NAME2,
	SHOBUN_INFO.GENBA_CD,
	SHOBUN_INFO.TODOUFUKEN_NAME,
	SHOBUN_INFO.GENBA_ADDRESS1,
	SHOBUN_INFO.GENBA_ADDRESS2,
	SHOBUN_INFO.JISHA_KBN
	/*END*/

UNION

--直行 積替①
--直行　排出事業場->(運搬業者)->積替保管場
SELECT
    /*IF data.GENBASHUKEI_KBN == '1'*/M_CHIIKI.CHIIKI_CD + TME.HST_GYOUSHA_CD AS HST_GYOUSHAGENBA,/*END*/
    /*IF data.GENBASHUKEI_KBN == '2'*/TME.HST_GYOUSHA_CD+TME.HST_GENBA_CD AS HST_GYOUSHAGENBA,/*END*/
    '1' AS CHOKKOU_ROUTE_NO,
    TME.SYSTEM_ID,
    TME.HAIKI_KBN_CD,
    TMD.HOUKOKUSHOBUNRUISORTKEY,
    M_CHIIKI.GOV_OR_MAY_NAME,
    M_CHIIKI.CHIIKI_NAME_RYAKU,
    GYOUSHA_TODOUFUKEN.TODOUFUKEN_NAME,
    M_GYOUSHA.GYOUSHA_ADDRESS1,
    M_GYOUSHA.GYOUSHA_ADDRESS2,
    M_GYOUSHA.GYOUSHA_NAME1,
    M_GYOUSHA.GYOUSHA_NAME2,
    M_GYOUSHA.JISHA_KBN,
    M_GYOUSHA.GYOUSHA_DAIHYOU AS DAIHYOUSHA,
    M_GYOUSHA.GYOUSHA_TEL,
    /*data.TITLE1*/ AS TITLE1,
    /*data.TITLE2*/ AS TITLE2,
    GENBA_JGB.GENBA_NAME1 + GENBA_JGB.GENBA_NAME2 AS JGB_NAME,
    GENBA_JGB.GENBA_ADDRESS1 + GENBA_JGB.GENBA_ADDRESS2 AS JGB_ADDRESS,
    TODOUFUKEN_JGB.TODOUFUKEN_NAME AS JGB_TODOUFUKEN_NAME,
    M_GYOUSHA.GYOUSHU_CD AS GYOUSHA_GYOUSHU_CD,
    GENBA_JGB.GYOUSHU_CD AS GENBA_GYOUSHU_CD,
    (SELECT TOP 1 GYOUSHU_NAME FROM M_GYOUSHU AS M1  WHERE M1.GYOUSHU_CD = M_GYOUSHA.GYOUSHU_CD) AS GYOUSHA_GYOUSHU_NM,
    (SELECT TOP 1 GYOUSHU_NAME FROM M_GYOUSHU AS M2  WHERE M2.GYOUSHU_CD = GENBA_JGB.GYOUSHU_CD) AS GENBA_GYOUSHU_NM,
    '' AS GYOUSHU_CD,
    '' AS GYOUSHU_NAME,
    GENBA_JGB.GENBA_TEL,
    TMD.HAIKI_SHURUI_CD,
    TMD.HAIKI_SHURUI_NAME_RYAKU,
    CASE
        WHEN Sum(CONVERT(money,TMD.KANSAN_SUU)) IS NOT NULL THEN Sum(CONVERT(money,TMD.KANSAN_SUU))
        ELSE 0
    END AS HAISHU_RYOU,
    0 AS COUFUMAISUU,
    CASE
		WHEN TMD.SANPAI_KBN = 1 THEN
            --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
            CASE WHEN ISNULL(UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                 ELSE UPN_KYOKA.FUTSUU_KYOKA_NO
            END
		WHEN TMD.SANPAI_KBN = 2 THEN
            --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
            CASE WHEN ISNULL(UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                ELSE UPN_KYOKA.TOKUBETSU_KYOKA_NO
            END
        ELSE
            --普通許可番号があれば普通許可番号、なければ特管許可番号
            CASE
                WHEN ISNULL(UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                WHEN ISNULL(UPN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN UPN_KYOKA.FUTSUU_KYOKA_NO
                WHEN ISNULL(UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                ELSE UPN_KYOKA.TOKUBETSU_KYOKA_NO
            END
    END AS UPN_FUTSUU_KYOKA_NO,
    TMPT_UPN.UPN_ROUTE_NO,
    TMPT_UPN.UPN_GYOUSHA_CD,
    ISNULL(GENBA_UPN.GYOUSHA_NAME1 + GENBA_UPN.GYOUSHA_NAME2, '') AS UPN_GYOUSHA_NAME,
	ISNULL(GENBA_UPN.JISHA_KBN, 0) AS UPN_JISHA_KBN,
    ISNULL(TME.TMH_GYOUSHA_CD, '') AS UPN_SAKI_GYOUSHA_CD,
    ISNULL(TME.TMH_GENBA_CD, '') AS UPN_SAKI_GENBA_CD,
    ISNULL(TME_GENBA_TODOUFUKEN.TODOUFUKEN_NAME + TME_GENBA.GENBA_ADDRESS1 + TME_GENBA.GENBA_ADDRESS2, '') AS UPN_SAKI_GENBA_ADDRESS,
    '' AS SBN_FUTSUU_KYOKA_NO,
    '' AS SBN_GYOUSHA_CD,
    '' AS SBN_GYOUSHA_NAME,
    '' AS SBN_GENBA_CD,
    '' AS SBN_GENBA_ADDRESS,
	0 AS SBN_GENBA_JISHA_KBN
FROM T_MANIFEST_ENTRY AS TME
INNER JOIN T_MANIFEST_UPN AS TMPT_UPN ON (TME.SYSTEM_ID = TMPT_UPN.SYSTEM_ID AND TME.SEQ = TMPT_UPN.SEQ AND ((TMPT_UPN.UPN_GYOUSHA_CD <> '' AND TMPT_UPN.UPN_GYOUSHA_CD IS NOT NULL) OR (TMPT_UPN.UPN_SAKI_GENBA_CD <> '' AND TMPT_UPN.UPN_SAKI_GENBA_CD IS NOT NULL)))
/*IF data.KONGOU_KBN == '1'*/--■混合出力有
LEFT JOIN
    (SELECT 
        TME1.SYSTEM_ID,
        TME1.SEQ,
        CASE
            WHEN Sum(CONVERT(money,TMD1.KANSAN_SUU)) IS NOT NULL THEN Sum(CONVERT(money,TMD1.KANSAN_SUU))
            ELSE 0
        END AS KANSAN_SUU,
        CASE
            WHEN COUNT(DISTINCT HOUKOKU.HOUKOKUSHO_BUNRUI_CD) > 1 THEN 2
            ELSE 1
        END AS HOUKOKUSHOBUNRUISORTKEY,
        CASE
            WHEN COUNT(DISTINCT HOUKOKU.HOUKOKUSHO_BUNRUI_CD) > 1 THEN ''
            ELSE MAX(HOUKOKU.HOUKOKUSHO_BUNRUI_CD)
        END AS HAIKI_SHURUI_CD,
        CASE
            WHEN COUNT(DISTINCT HOUKOKU.HOUKOKUSHO_BUNRUI_CD) > 1 THEN '混合廃棄物'
            ELSE MAX(HOUKOKU.HOUKOKUSHO_BUNRUI_NAME)
        END AS HAIKI_SHURUI_NAME_RYAKU,
        CASE
			WHEN SUM(CASE WHEN ISNULL(HAIKI.HAIKI_SHURUI_CD, '') < '7000' THEN 0 ELSE 1 END) = 0 THEN 1	--普通産廃のみ
			WHEN SUM(CASE WHEN ISNULL(HAIKI.HAIKI_SHURUI_CD, '') < '7000' THEN 0 ELSE 1 END) = COUNT(HAIKI.HAIKI_SHURUI_CD) THEN 2	--特管産廃のみ
			ELSE 3 --混在
		END AS SANPAI_KBN
     FROM T_MANIFEST_ENTRY AS TME1
     LEFT JOIN T_MANIFEST_DETAIL AS TMD1 ON (TME1.SYSTEM_ID = TMD1.SYSTEM_ID AND TME1.SEQ = TMD1.SEQ)
     LEFT JOIN M_HAIKI_SHURUI AS HAIKI ON (TME1.HAIKI_KBN_CD = HAIKI.HAIKI_KBN_CD AND TMD1.HAIKI_SHURUI_CD = HAIKI.HAIKI_SHURUI_CD)
     LEFT JOIN M_HOUKOKUSHO_BUNRUI AS HOUKOKU ON  HAIKI.HOUKOKUSHO_BUNRUI_CD = HOUKOKU.HOUKOKUSHO_BUNRUI_CD
     WHERE   TME1.DELETE_FLG = 0
          AND ((TME1.KOUFU_DATE) >= /*data.KOUFU_DATE_FROM*/ AND (TME1.KOUFU_DATE) <= /*data.KOUFU_DATE_TO*/)
     GROUP BY TME1.SYSTEM_ID,TME1.SEQ ) AS TMD ON (TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ)
/*END*/
/*IF data.KONGOU_KBN == '2'*/--■混合出力無
LEFT JOIN 
    (SELECT
        TME1.SYSTEM_ID,
        TME1.SEQ,
        CASE
            WHEN Sum(CONVERT(money,TMD1.KANSAN_SUU)) IS NOT NULL THEN Sum(CONVERT(money,TMD1.KANSAN_SUU))
            ELSE 0
        END AS KANSAN_SUU,
        1 AS HOUKOKUSHOBUNRUISORTKEY,
        HOUKOKU.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_CD,
        HOUKOKU.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_NAME_RYAKU,
        CASE
			WHEN SUM(CASE WHEN ISNULL(HAIKI.HAIKI_SHURUI_CD, '') < '7000' THEN 0 ELSE 1 END) = 0 THEN 1	--普通産廃のみ
			WHEN SUM(CASE WHEN ISNULL(HAIKI.HAIKI_SHURUI_CD, '') < '7000' THEN 0 ELSE 1 END) = COUNT(HAIKI.HAIKI_SHURUI_CD) THEN 2	--特管産廃のみ
			ELSE 3 --混在
		END AS SANPAI_KBN
    FROM T_MANIFEST_ENTRY AS TME1
    LEFT JOIN T_MANIFEST_DETAIL AS TMD1 ON (TME1.SYSTEM_ID = TMD1.SYSTEM_ID AND TME1.SEQ = TMD1.SEQ)
    LEFT JOIN M_HAIKI_SHURUI AS HAIKI ON (TME1.HAIKI_KBN_CD = HAIKI.HAIKI_KBN_CD AND TMD1.HAIKI_SHURUI_CD = HAIKI.HAIKI_SHURUI_CD)
    LEFT JOIN M_HOUKOKUSHO_BUNRUI AS HOUKOKU ON  HAIKI.HOUKOKUSHO_BUNRUI_CD = HOUKOKU.HOUKOKUSHO_BUNRUI_CD
    WHERE TME1.DELETE_FLG = 0
		AND ((TME1.KOUFU_DATE) >= /*data.KOUFU_DATE_FROM*/ AND (TME1.KOUFU_DATE) <= /*data.KOUFU_DATE_TO*/)
    GROUP BY TME1.SYSTEM_ID,TME1.SEQ,HOUKOKU.HOUKOKUSHO_BUNRUI_CD,HOUKOKU.HOUKOKUSHO_BUNRUI_NAME) AS TMD ON (TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ)
/*END*/
LEFT JOIN M_GYOUSHA AS GENBA_UPN ON (TMPT_UPN.UPN_GYOUSHA_CD = GENBA_UPN.GYOUSHA_CD)
LEFT JOIN M_GENBA AS GENBA_SBN ON (TME.SBN_GYOUSHA_CD = GENBA_SBN.GYOUSHA_CD AND TMPT_UPN.UPN_SAKI_GENBA_CD = GENBA_SBN.GENBA_CD)
LEFT JOIN M_GENBA AS GENBA_CHK ON (TME.HST_GYOUSHA_CD = GENBA_CHK.GYOUSHA_CD AND TME.HST_GENBA_CD = GENBA_CHK.GENBA_CD)
LEFT JOIN M_CHIIKI  ON (GENBA_CHK.CHIIKI_CD = M_CHIIKI.CHIIKI_CD)
LEFT JOIN M_GYOUSHA ON (TME.HST_GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD)
LEFT JOIN M_TODOUFUKEN AS GYOUSHA_TODOUFUKEN ON (M_GYOUSHA.GYOUSHA_TODOUFUKEN_CD = GYOUSHA_TODOUFUKEN.TODOUFUKEN_CD)
LEFT JOIN M_GENBA AS GENBA_JGB ON (TME.HST_GYOUSHA_CD = GENBA_JGB.GYOUSHA_CD AND TME.HST_GENBA_CD = GENBA_JGB.GENBA_CD)
LEFT JOIN M_TODOUFUKEN AS TODOUFUKEN_JGB ON (GENBA_JGB.GENBA_TODOUFUKEN_CD = TODOUFUKEN_JGB.TODOUFUKEN_CD)
LEFT JOIN M_GENBA AS TME_GENBA ON  (TME.TMH_GYOUSHA_CD = TME_GENBA.GYOUSHA_CD AND TME.TMH_GENBA_CD = TME_GENBA.GENBA_CD)
LEFT JOIN M_TODOUFUKEN AS TME_GENBA_TODOUFUKEN ON  (TME_GENBA.GENBA_TODOUFUKEN_CD = TME_GENBA_TODOUFUKEN.TODOUFUKEN_CD)
LEFT JOIN M_GYOUSHA AS TME_SBN_GYOUSHA ON (TME.SBN_GYOUSHA_CD = TME_SBN_GYOUSHA.GYOUSHA_CD)
LEFT JOIN (
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS UPN_KYOKA ON (TMPT_UPN.UPN_GYOUSHA_CD = UPN_KYOKA.GYOUSHA_CD AND GENBA_JGB.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = UPN_KYOKA.CHIIKI_CD AND UPN_KYOKA.KYOKA_KBN = 1)
LEFT JOIN (
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS UPN_KYOKA_CK ON (TMPT_UPN.UPN_GYOUSHA_CD = UPN_KYOKA_CK.GYOUSHA_CD AND GENBA_JGB.CHIIKI_CD = UPN_KYOKA_CK.CHIIKI_CD AND UPN_KYOKA_CK.KYOKA_KBN = 1)
WHERE TME.DELETE_FLG = 0 AND ((TME.KOUFU_DATE) >= /*data.KOUFU_DATE_FROM*/ AND (TME.KOUFU_DATE) <= /*data.KOUFU_DATE_TO*/)
    AND TME.HAIKI_KBN_CD = 1 AND (TME.TMH_GYOUSHA_CD <> '' AND TME.TMH_GYOUSHA_CD IS NOT NULL)
/*IF data.GYOUSHU != null && data.GYOUSHU != ''*/
	AND (GENBA_JGB.GYOUSHU_CD = /*data.GYOUSHU*/ OR (M_GYOUSHA.GYOUSHU_CD = /*data.GYOUSHU*/ AND (GENBA_JGB.GYOUSHU_CD = '' OR GENBA_JGB.GYOUSHU_CD IS NULL)))
/*END*/

/*IF data.GYOUSHASET_KBN1 == '1'*/ --if --[提出業者設定-1] = 1.個別(提出業者:FROMのみ)	
 /*IF data.GENBASHUKEI_KBN == '2'*/--現場一括集計:1する,2:しない
   AND(TME.HST_GENBA_CD >=/*data.GENBA_CD_FROM*/ AND TME.HST_GENBA_CD <=/*data.GENBA_CD_TO*/ )
   /*END*/	
    /*IF data.TEISHUTUSAKI_KBN == '1'*/ --if --[提出先] = 1.全体(都道府県政令の指定検索しない)
				/*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社
								AND ((TME.HST_GYOUSHA_CD)= /*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND GENBA_UPN.JISHA_KBN <> 0
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者	
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND (TME.HST_GYOUSHA_CD = TMPT_UPN.UPN_GYOUSHA_CD)
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社			
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND TME.HST_GENBA_CD <> '') AND (GENBA_UPN.JISHA_KBN = 0 OR GENBA_UPN.JISHA_KBN is NULL) AND (TME.HST_GYOUSHA_CD <> TMPT_UPN.UPN_GYOUSHA_CD OR TMPT_UPN.UPN_GYOUSHA_CD is NULL)		
				/*END*/							
				/*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て	
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '')
				/*END*/	
	 /*END*/	
	 /*IF data.TEISHUTUSAKI_KBN == '2'*/ --	else if --[提出先] = 2.個別(都道府県政令の指定検索する)								
				/*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社			
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND GENBA_UPN.JISHA_KBN <> 0 AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/
				/*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者			
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND (TME.HST_GYOUSHA_CD = TMPT_UPN.UPN_GYOUSHA_CD) AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/
				/*END*/
				/*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社		
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND (GENBA_UPN.JISHA_KBN = 0 OR GENBA_UPN.JISHA_KBN is NULL) AND (TME.HST_GYOUSHA_CD <> TMPT_UPN.UPN_GYOUSHA_CD OR TMPT_UPN.UPN_GYOUSHA_CD is NULL)		
								AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/		
				/*END*/
				/*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て		
								AND TME.HST_GYOUSHA_CD =/*data.GYOUSHA_CD_FROM*/ AND TME.HST_GENBA_CD <> '' AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/
	/*END*/
/*END*/	
/*IF data.GYOUSHASET_KBN1 == '2'*/--else if--[提出業者設定-1] = 2.全体(提出業者:FROM/TO)										
		/*IF data.TEISHUTUSAKI_KBN == '1'*/ --if --[提出先] = 1.全体(都道府県政令の指定検索しない)								
				/*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/ ) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <> '')		
								AND GENBA_UPN.JISHA_KBN <> 0	
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <>  '')		
								AND (TME.HST_GYOUSHA_CD = TMPT_UPN.UPN_GYOUSHA_CD)
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/ )) AND (TME.HST_GENBA_CD) <> '')		
								AND ((GENBA_UPN.JISHA_KBN = 0) OR ((GENBA_UPN.JISHA_KBN)is NULL)) AND ((TME.HST_GYOUSHA_CD <> TMPT_UPN.UPN_GYOUSHA_CD) OR ((TMPT_UPN.UPN_GYOUSHA_CD)is NULL))		
										
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <> '')
				/*END*/
		/*END*/	
		/*IF data.TEISHUTUSAKI_KBN == '2'*/ --else if--[提出先] = 2.個別(都道府県政令の指定検索する)								
				/*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社			
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/ ) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <> '')		
								AND GENBA_UPN.JISHA_KBN <> 0 AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <>  '')		
								AND (TME.HST_GYOUSHA_CD = TMPT_UPN.UPN_GYOUSHA_CD) AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社			
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/ )) AND (TME.HST_GENBA_CD) <> '')		
								AND ((GENBA_UPN.JISHA_KBN = 0) OR ((GENBA_UPN.JISHA_KBN)is NULL)) AND ((TME.HST_GYOUSHA_CD <> TMPT_UPN.UPN_GYOUSHA_CD) OR ((TMPT_UPN.UPN_GYOUSHA_CD)is NULL))		
								AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/		
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て			
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <> '')		
								AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/		
		/*END*/
/*END*/
GROUP BY
    /*IF data.GENBASHUKEI_KBN == '1'*/M_CHIIKI.CHIIKI_CD,/*END*/
    TME.HST_GYOUSHA_CD,
	/*IF data.GENBASHUKEI_KBN == '2'*/TME.HST_GENBA_CD,/*END*/
    TME.SYSTEM_ID,
    TME.HAIKI_KBN_CD,
	TME.FIRST_MANIFEST_KBN,
    TMD.HOUKOKUSHOBUNRUISORTKEY,
    M_CHIIKI.GOV_OR_MAY_NAME,
    M_CHIIKI.CHIIKI_NAME_RYAKU,
    GYOUSHA_TODOUFUKEN.TODOUFUKEN_NAME,
    M_GYOUSHA.GYOUSHA_ADDRESS1,
    M_GYOUSHA.GYOUSHA_ADDRESS2,
    M_GYOUSHA.GYOUSHA_NAME1,
    M_GYOUSHA.GYOUSHA_NAME2,
    M_GYOUSHA.JISHA_KBN,
    M_GYOUSHA.GYOUSHA_DAIHYOU,
    M_GYOUSHA.GYOUSHA_TEL,
    GENBA_JGB.GENBA_NAME1,
    GENBA_JGB.GENBA_NAME2,
    GENBA_JGB.GENBA_ADDRESS1,
    GENBA_JGB.GENBA_ADDRESS2,
    TODOUFUKEN_JGB.TODOUFUKEN_NAME,
    M_GYOUSHA.GYOUSHU_CD,
    GENBA_JGB.GYOUSHU_CD,
    GENBA_JGB.GENBA_TEL,
    TMD.HAIKI_SHURUI_CD,
    TMD.HAIKI_SHURUI_NAME_RYAKU,
	TMD.SANPAI_KBN,
    UPN_KYOKA.FUTSUU_KYOKA_NO,
    UPN_KYOKA.TOKUBETSU_KYOKA_NO,
    UPN_KYOKA_CK.FUTSUU_KYOKA_NO,
    UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO,
    TMPT_UPN.UPN_ROUTE_NO,
    TMPT_UPN.UPN_GYOUSHA_CD,
    GENBA_UPN.GYOUSHA_NAME1,
    GENBA_UPN.GYOUSHA_NAME2,
	GENBA_UPN.JISHA_KBN,
    TMPT_UPN.UPN_GYOUSHA_NAME,
    TME.TMH_GYOUSHA_CD,
    TME.TMH_GENBA_CD,
    TME_GENBA_TODOUFUKEN.TODOUFUKEN_NAME,
    TME_GENBA.GENBA_ADDRESS1,
    TME_GENBA.GENBA_ADDRESS2

UNION

--直行 積替②
--直行　(排出事業場->(運搬業者)->)積替保管場->(運搬業者)->処分事業場
SELECT
    /*IF data.GENBASHUKEI_KBN == '1'*/M_CHIIKI.CHIIKI_CD + TME.HST_GYOUSHA_CD AS HST_GYOUSHAGENBA,/*END*/
	/*IF data.GENBASHUKEI_KBN == '2'*/TME.HST_GYOUSHA_CD+TME.HST_GENBA_CD AS HST_GYOUSHAGENBA,/*END*/
    '2' AS CHOKKOU_ROUTE_NO,
    TME.SYSTEM_ID,
    TME.HAIKI_KBN_CD,
    TMD.HOUKOKUSHOBUNRUISORTKEY,
    M_CHIIKI.GOV_OR_MAY_NAME,
    M_CHIIKI.CHIIKI_NAME_RYAKU,
    GYOUSHA_TODOUFUKEN.TODOUFUKEN_NAME,
    M_GYOUSHA.GYOUSHA_ADDRESS1,
    M_GYOUSHA.GYOUSHA_ADDRESS2,
    M_GYOUSHA.GYOUSHA_NAME1,
    M_GYOUSHA.GYOUSHA_NAME2,
    M_GYOUSHA.JISHA_KBN,
    M_GYOUSHA.GYOUSHA_DAIHYOU AS DAIHYOUSHA,
    M_GYOUSHA.GYOUSHA_TEL,
    /*data.TITLE1*/ AS TITLE1,
    /*data.TITLE2*/ AS TITLE2,
    GENBA_JGB.GENBA_NAME1 + GENBA_JGB.GENBA_NAME2 AS JGB_NAME,
    GENBA_JGB.GENBA_ADDRESS1 + GENBA_JGB.GENBA_ADDRESS2 AS JGB_ADDRESS,
    TODOUFUKEN_JGB.TODOUFUKEN_NAME AS JGB_TODOUFUKEN_NAME,
    M_GYOUSHA.GYOUSHU_CD AS GYOUSHA_GYOUSHU_CD,
    GENBA_JGB.GYOUSHU_CD AS GENBA_GYOUSHU_CD,
    (SELECT TOP 1 GYOUSHU_NAME FROM M_GYOUSHU AS M1  WHERE M1.GYOUSHU_CD = M_GYOUSHA.GYOUSHU_CD) AS GYOUSHA_GYOUSHU_NM,
    (SELECT TOP 1 GYOUSHU_NAME FROM M_GYOUSHU AS M2  WHERE M2.GYOUSHU_CD = GENBA_JGB.GYOUSHU_CD) AS GENBA_GYOUSHU_NM,
    '' AS GYOUSHU_CD,
    '' AS GYOUSHU_NAME,
    GENBA_JGB.GENBA_TEL,
    TMD.HAIKI_SHURUI_CD,
    TMD.HAIKI_SHURUI_NAME_RYAKU,
    '' AS HAISHU_RYOU,
    0 AS COUFUMAISUU,
	CASE
		WHEN (TME.TMH_GENBA_CD = '' OR TME.TMH_GENBA_CD IS NULL) THEN
			CASE
				WHEN TMD.SANPAI_KBN = 1 THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                             ELSE UPN_KYOKA.FUTSUU_KYOKA_NO
                        END
				WHEN TMD.SANPAI_KBN = 2 THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                             ELSE UPN_KYOKA.TOKUBETSU_KYOKA_NO
                        END
				ELSE
                    --普通許可番号があれば普通許可番号、なければ特管許可番号
                    CASE
                        WHEN ISNULL(UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                        WHEN ISNULL(UPN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN UPN_KYOKA.FUTSUU_KYOKA_NO
                        WHEN ISNULL(UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                        ELSE UPN_KYOKA.TOKUBETSU_KYOKA_NO
                    END
			END
		ELSE
		    CASE
				WHEN TMD.SANPAI_KBN = 1 THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(TM_UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN TM_UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                             ELSE TM_UPN_KYOKA.FUTSUU_KYOKA_NO
                        END
				WHEN TMD.SANPAI_KBN = 2 THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(TM_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN TM_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                             ELSE TM_UPN_KYOKA.TOKUBETSU_KYOKA_NO
                        END
				ELSE
                    --普通許可番号があれば普通許可番号、なければ特管許可番号
                    CASE
                        WHEN ISNULL(TM_UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN TM_UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                        WHEN ISNULL(TM_UPN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN TM_UPN_KYOKA.FUTSUU_KYOKA_NO
                        WHEN ISNULL(TM_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN TM_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                        ELSE TM_UPN_KYOKA.TOKUBETSU_KYOKA_NO
                    END
			END
	END AS UPN_FUTSUU_KYOKA_NO,
    TMPT_UPN.UPN_ROUTE_NO,
    TMPT_UPN.UPN_GYOUSHA_CD,
    ISNULL(GENBA_UPN.GYOUSHA_NAME1 + GENBA_UPN.GYOUSHA_NAME2, '') AS UPN_GYOUSHA_NAME,
	ISNULL(GENBA_UPN.JISHA_KBN, 0) AS UPN_JISHA_KBN,
    ISNULL(TMPT_UPN.UPN_SAKI_GYOUSHA_CD, '') AS UPN_SAKI_GYOUSHA_CD,
    ISNULL(TMPT_UPN.UPN_SAKI_GENBA_CD, '') AS UPN_SAKI_GENBA_CD,
    ISNULL(UPN_GENBA_TODOUFUKEN.TODOUFUKEN_NAME + UPN_GENBA.GENBA_ADDRESS1 + UPN_GENBA.GENBA_ADDRESS2, '') AS UPN_SAKI_GENBA_ADDRESS,
    CASE
		WHEN TME.FIRST_MANIFEST_KBN = 0 THEN
			CASE
				WHEN TMD.SANPAI_KBN = 1 THEN SBN_KYOKA.FUTSUU_KYOKA_NO
				WHEN TMD.SANPAI_KBN = 2 THEN SBN_KYOKA.TOKUBETSU_KYOKA_NO
				ELSE
					CASE
						WHEN ISNULL(SBN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN SBN_KYOKA.FUTSUU_KYOKA_NO
						ELSE SBN_KYOKA.TOKUBETSU_KYOKA_NO
					END
			END
		WHEN TME.FIRST_MANIFEST_KBN = 1 THEN
			CASE
				WHEN TMD.SANPAI_KBN = 1 THEN LAST_SBN_KYOKA.FUTSUU_KYOKA_NO
				WHEN TMD.SANPAI_KBN = 2 THEN LAST_SBN_KYOKA.TOKUBETSU_KYOKA_NO
				ELSE
					CASE
						WHEN ISNULL(LAST_SBN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN LAST_SBN_KYOKA.FUTSUU_KYOKA_NO
						ELSE LAST_SBN_KYOKA.TOKUBETSU_KYOKA_NO
					END
			END
    END AS SBN_FUTSUU_KYOKA_NO,
    TME.SBN_GYOUSHA_CD,
    TME_SBN_GYOUSHA.GYOUSHA_NAME1 + TME_SBN_GYOUSHA.GYOUSHA_NAME2 AS SBN_GYOUSHA_NAME,
    TMPT_UPN.UPN_SAKI_GENBA_CD AS SBN_GENBA_CD,
    UPN_GENBA_TODOUFUKEN.TODOUFUKEN_NAME + UPN_GENBA.GENBA_ADDRESS1 + UPN_GENBA.GENBA_ADDRESS2 AS SBN_GENBA_ADDRESS,
	UPN_GENBA.JISHA_KBN AS SBN_GENBA_JISHA_KBN
FROM T_MANIFEST_ENTRY AS TME
INNER JOIN T_MANIFEST_UPN AS TMPT_UPN ON (TME.SYSTEM_ID = TMPT_UPN.SYSTEM_ID AND TME.SEQ = TMPT_UPN.SEQ AND ((TMPT_UPN.UPN_GYOUSHA_CD <> '' AND TMPT_UPN.UPN_GYOUSHA_CD IS NOT NULL) OR (TMPT_UPN.UPN_SAKI_GENBA_CD <> '' AND TMPT_UPN.UPN_SAKI_GENBA_CD IS NOT NULL)))
/*IF data.KONGOU_KBN == '1'*/--■混合出力有
LEFT JOIN
    (SELECT 
        TME1.SYSTEM_ID,
        TME1.SEQ,
        CASE
            WHEN Sum(CONVERT(money,TMD1.KANSAN_SUU)) IS NOT NULL THEN Sum(CONVERT(money,TMD1.KANSAN_SUU))
            ELSE 0
        END AS KANSAN_SUU,
        CASE
            WHEN COUNT(DISTINCT HOUKOKU.HOUKOKUSHO_BUNRUI_CD) > 1 THEN 2
            ELSE 1
        END AS HOUKOKUSHOBUNRUISORTKEY,
        CASE
            WHEN COUNT(DISTINCT HOUKOKU.HOUKOKUSHO_BUNRUI_CD) > 1 THEN ''
            ELSE MAX(HOUKOKU.HOUKOKUSHO_BUNRUI_CD)
        END AS HAIKI_SHURUI_CD,
        CASE
            WHEN COUNT(DISTINCT HOUKOKU.HOUKOKUSHO_BUNRUI_CD) > 1 THEN '混合廃棄物'
            ELSE MAX(HOUKOKU.HOUKOKUSHO_BUNRUI_NAME)
        END AS HAIKI_SHURUI_NAME_RYAKU,
        CASE
			WHEN SUM(CASE WHEN ISNULL(HAIKI.HAIKI_SHURUI_CD, '') < '7000' THEN 0 ELSE 1 END) = 0 THEN 1	--普通産廃のみ
			WHEN SUM(CASE WHEN ISNULL(HAIKI.HAIKI_SHURUI_CD, '') < '7000' THEN 0 ELSE 1 END) = COUNT(HAIKI.HAIKI_SHURUI_CD) THEN 2	--特管産廃のみ
			ELSE 3 --混在
		END AS SANPAI_KBN
     FROM T_MANIFEST_ENTRY AS TME1
     LEFT JOIN T_MANIFEST_DETAIL AS TMD1 ON (TME1.SYSTEM_ID = TMD1.SYSTEM_ID AND TME1.SEQ = TMD1.SEQ)
     LEFT JOIN M_HAIKI_SHURUI AS HAIKI ON (TME1.HAIKI_KBN_CD = HAIKI.HAIKI_KBN_CD AND TMD1.HAIKI_SHURUI_CD = HAIKI.HAIKI_SHURUI_CD)
     LEFT JOIN M_HOUKOKUSHO_BUNRUI AS HOUKOKU ON  HAIKI.HOUKOKUSHO_BUNRUI_CD = HOUKOKU.HOUKOKUSHO_BUNRUI_CD
     WHERE   TME1.DELETE_FLG = 0
          AND ((TME1.KOUFU_DATE) >= /*data.KOUFU_DATE_FROM*/ AND (TME1.KOUFU_DATE) <= /*data.KOUFU_DATE_TO*/)
     GROUP BY TME1.SYSTEM_ID,TME1.SEQ ) AS TMD ON (TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ)
/*END*/
/*IF data.KONGOU_KBN == '2'*/--■混合出力無
LEFT JOIN 
    (SELECT
        TME1.SYSTEM_ID,
        TME1.SEQ,
        CASE
            WHEN Sum(CONVERT(money,TMD1.KANSAN_SUU)) IS NOT NULL THEN Sum(CONVERT(money,TMD1.KANSAN_SUU))
            ELSE 0
        END AS KANSAN_SUU,
        1 AS HOUKOKUSHOBUNRUISORTKEY,
        HOUKOKU.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_CD,
        HOUKOKU.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_NAME_RYAKU,
        CASE
			WHEN SUM(CASE WHEN ISNULL(HAIKI.HAIKI_SHURUI_CD, '') < '7000' THEN 0 ELSE 1 END) = 0 THEN 1	--普通産廃のみ
			WHEN SUM(CASE WHEN ISNULL(HAIKI.HAIKI_SHURUI_CD, '') < '7000' THEN 0 ELSE 1 END) = COUNT(HAIKI.HAIKI_SHURUI_CD) THEN 2	--特管産廃のみ
			ELSE 3 --混在
		END AS SANPAI_KBN
    FROM T_MANIFEST_ENTRY AS TME1
    LEFT JOIN T_MANIFEST_DETAIL AS TMD1 ON (TME1.SYSTEM_ID = TMD1.SYSTEM_ID AND TME1.SEQ = TMD1.SEQ)
    LEFT JOIN M_HAIKI_SHURUI AS HAIKI ON (TME1.HAIKI_KBN_CD = HAIKI.HAIKI_KBN_CD AND TMD1.HAIKI_SHURUI_CD = HAIKI.HAIKI_SHURUI_CD)
    LEFT JOIN M_HOUKOKUSHO_BUNRUI AS HOUKOKU ON  HAIKI.HOUKOKUSHO_BUNRUI_CD = HOUKOKU.HOUKOKUSHO_BUNRUI_CD
    WHERE TME1.DELETE_FLG = 0
		AND ((TME1.KOUFU_DATE) >= /*data.KOUFU_DATE_FROM*/ AND (TME1.KOUFU_DATE) <= /*data.KOUFU_DATE_TO*/)
    GROUP BY TME1.SYSTEM_ID,TME1.SEQ,HOUKOKU.HOUKOKUSHO_BUNRUI_CD,HOUKOKU.HOUKOKUSHO_BUNRUI_NAME) AS TMD ON (TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ)
/*END*/
LEFT JOIN M_GYOUSHA AS GENBA_UPN ON (TMPT_UPN.UPN_GYOUSHA_CD = GENBA_UPN.GYOUSHA_CD)
LEFT JOIN M_GENBA AS GENBA_SBN ON (TME.SBN_GYOUSHA_CD = GENBA_SBN.GYOUSHA_CD AND TMPT_UPN.UPN_SAKI_GENBA_CD = GENBA_SBN.GENBA_CD)
LEFT JOIN M_GENBA AS GENBA_CHK ON (TME.HST_GYOUSHA_CD = GENBA_CHK.GYOUSHA_CD AND TME.HST_GENBA_CD = GENBA_CHK.GENBA_CD)
LEFT JOIN M_CHIIKI  ON (GENBA_CHK.CHIIKI_CD = M_CHIIKI.CHIIKI_CD)
LEFT JOIN M_GYOUSHA ON (TME.HST_GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD)
LEFT JOIN M_TODOUFUKEN AS GYOUSHA_TODOUFUKEN ON (M_GYOUSHA.GYOUSHA_TODOUFUKEN_CD = GYOUSHA_TODOUFUKEN.TODOUFUKEN_CD)
LEFT JOIN M_GENBA AS GENBA_JGB ON (TME.HST_GYOUSHA_CD = GENBA_JGB.GYOUSHA_CD AND TME.HST_GENBA_CD = GENBA_JGB.GENBA_CD)
LEFT JOIN M_TODOUFUKEN AS TODOUFUKEN_JGB ON (GENBA_JGB.GENBA_TODOUFUKEN_CD = TODOUFUKEN_JGB.TODOUFUKEN_CD)
LEFT JOIN M_GENBA AS UPN_GENBA ON  (TMPT_UPN.UPN_SAKI_GYOUSHA_CD = UPN_GENBA.GYOUSHA_CD AND TMPT_UPN.UPN_SAKI_GENBA_CD = UPN_GENBA.GENBA_CD)
LEFT JOIN M_TODOUFUKEN AS UPN_GENBA_TODOUFUKEN ON  (UPN_GENBA.GENBA_TODOUFUKEN_CD = UPN_GENBA_TODOUFUKEN.TODOUFUKEN_CD)
LEFT JOIN M_GENBA AS TME_GENBA ON (TME.TMH_GYOUSHA_CD = TME_GENBA.GYOUSHA_CD AND TME.TMH_GENBA_CD = TME_GENBA.GENBA_CD)
LEFT JOIN M_GYOUSHA AS TME_SBN_GYOUSHA ON  (TME.SBN_GYOUSHA_CD = TME_SBN_GYOUSHA.GYOUSHA_CD)
LEFT JOIN (
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS UPN_KYOKA ON (TMPT_UPN.UPN_GYOUSHA_CD = UPN_KYOKA.GYOUSHA_CD AND GENBA_JGB.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = UPN_KYOKA.CHIIKI_CD AND UPN_KYOKA.KYOKA_KBN = 1)
LEFT JOIN (
            --地域に対しての許可番号。政令指定都市＞都道府県の順に許可番号を適用するため、運搬報告書提出先の地域、地域に対しての許可番号を取得する
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS UPN_KYOKA_CK ON (TMPT_UPN.UPN_GYOUSHA_CD = UPN_KYOKA_CK.GYOUSHA_CD AND GENBA_JGB.CHIIKI_CD = UPN_KYOKA_CK.CHIIKI_CD AND UPN_KYOKA_CK.KYOKA_KBN = 1)
LEFT JOIN (
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS TM_UPN_KYOKA ON (TMPT_UPN.UPN_GYOUSHA_CD = TM_UPN_KYOKA.GYOUSHA_CD AND TME_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = TM_UPN_KYOKA.CHIIKI_CD AND TM_UPN_KYOKA.KYOKA_KBN = 1)
LEFT JOIN (
            --地域に対しての許可番号。政令指定都市＞都道府県の順に許可番号を適用するため、運搬報告書提出先の地域、地域に対しての許可番号を取得する
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS TM_UPN_KYOKA_CK ON (TMPT_UPN.UPN_GYOUSHA_CD = TM_UPN_KYOKA_CK.GYOUSHA_CD AND TME_GENBA.CHIIKI_CD = TM_UPN_KYOKA_CK.CHIIKI_CD AND TM_UPN_KYOKA_CK.KYOKA_KBN = 1)
LEFT JOIN (
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.GENBA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 2
) AS SBN_KYOKA ON (TME.SBN_GYOUSHA_CD = SBN_KYOKA.GYOUSHA_CD AND TMPT_UPN.UPN_SAKI_GENBA_CD = SBN_KYOKA.GENBA_CD AND GENBA_SBN.CHIIKI_CD = SBN_KYOKA.CHIIKI_CD AND SBN_KYOKA.KYOKA_KBN = 2)
LEFT JOIN (
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.GENBA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 3
) AS LAST_SBN_KYOKA ON (TME.SBN_GYOUSHA_CD = LAST_SBN_KYOKA.GYOUSHA_CD AND TMPT_UPN.UPN_SAKI_GENBA_CD = LAST_SBN_KYOKA.GENBA_CD AND GENBA_SBN.CHIIKI_CD = LAST_SBN_KYOKA.CHIIKI_CD AND LAST_SBN_KYOKA.KYOKA_KBN = 3)

WHERE TME.DELETE_FLG = 0 AND ((TME.KOUFU_DATE) >= /*data.KOUFU_DATE_FROM*/ AND (TME.KOUFU_DATE) <= /*data.KOUFU_DATE_TO*/)
      AND TME.HAIKI_KBN_CD = 1 AND (TME.TMH_GYOUSHA_CD <> '' AND TME.TMH_GYOUSHA_CD IS NOT NULL)
/*IF data.GYOUSHU != null && data.GYOUSHU != ''*/
	AND (GENBA_JGB.GYOUSHU_CD = /*data.GYOUSHU*/ OR (M_GYOUSHA.GYOUSHU_CD = /*data.GYOUSHU*/ AND (GENBA_JGB.GYOUSHU_CD = '' OR GENBA_JGB.GYOUSHU_CD IS NULL)))
/*END*/

/*IF data.GYOUSHASET_KBN1 == '1'*/ --if --[提出業者設定-1] = 1.個別(提出業者:FROMのみ)	
 /*IF data.GENBASHUKEI_KBN == '2'*/--現場一括集計:1する,2:しない
   AND(TME.HST_GENBA_CD >=/*data.GENBA_CD_FROM*/ AND TME.HST_GENBA_CD <=/*data.GENBA_CD_TO*/ )
   /*END*/	
    /*IF data.TEISHUTUSAKI_KBN == '1'*/ --if --[提出先] = 1.全体(都道府県政令の指定検索しない)
				/*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社
								AND ((TME.HST_GYOUSHA_CD)= /*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND GENBA_UPN.JISHA_KBN <> 0
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者	
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND (TME.HST_GYOUSHA_CD = TMPT_UPN.UPN_GYOUSHA_CD)
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社			
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND TME.HST_GENBA_CD <> '') AND (GENBA_UPN.JISHA_KBN = 0 OR GENBA_UPN.JISHA_KBN is NULL) AND (TME.HST_GYOUSHA_CD <> TMPT_UPN.UPN_GYOUSHA_CD OR TMPT_UPN.UPN_GYOUSHA_CD is NULL)		
				/*END*/							
				/*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て	
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '')
				/*END*/	
	 /*END*/	
	 /*IF data.TEISHUTUSAKI_KBN == '2'*/ --	else if --[提出先] = 2.個別(都道府県政令の指定検索する)								
				/*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社			
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND GENBA_UPN.JISHA_KBN <> 0 AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/
				/*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者			
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND (TME.HST_GYOUSHA_CD = TMPT_UPN.UPN_GYOUSHA_CD) AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/
				/*END*/
				/*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社		
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND (GENBA_UPN.JISHA_KBN = 0 OR GENBA_UPN.JISHA_KBN is NULL) AND (TME.HST_GYOUSHA_CD <> TMPT_UPN.UPN_GYOUSHA_CD OR TMPT_UPN.UPN_GYOUSHA_CD is NULL)		
								AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/		
				/*END*/
				/*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て		
								AND TME.HST_GYOUSHA_CD =/*data.GYOUSHA_CD_FROM*/ AND TME.HST_GENBA_CD <> '' AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/
	/*END*/
/*END*/	
/*IF data.GYOUSHASET_KBN1 == '2'*/--else if--[提出業者設定-1] = 2.全体(提出業者:FROM/TO)										
		/*IF data.TEISHUTUSAKI_KBN == '1'*/ --if --[提出先] = 1.全体(都道府県政令の指定検索しない)								
				/*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/ ) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <> '')		
								AND GENBA_UPN.JISHA_KBN <> 0	
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <>  '')		
								AND (TME.HST_GYOUSHA_CD = TMPT_UPN.UPN_GYOUSHA_CD)
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/ )) AND (TME.HST_GENBA_CD) <> '')		
								AND ((GENBA_UPN.JISHA_KBN = 0) OR ((GENBA_UPN.JISHA_KBN)is NULL)) AND ((TME.HST_GYOUSHA_CD <> TMPT_UPN.UPN_GYOUSHA_CD) OR ((TMPT_UPN.UPN_GYOUSHA_CD)is NULL))		
										
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <> '')
				/*END*/
		/*END*/	
		/*IF data.TEISHUTUSAKI_KBN == '2'*/ --else if--[提出先] = 2.個別(都道府県政令の指定検索する)								
				/*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社			
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/ ) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <> '')		
								AND GENBA_UPN.JISHA_KBN <> 0 AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <>  '')		
								AND (TME.HST_GYOUSHA_CD = TMPT_UPN.UPN_GYOUSHA_CD) AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社			
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/ )) AND (TME.HST_GENBA_CD) <> '')		
								AND ((GENBA_UPN.JISHA_KBN = 0) OR ((GENBA_UPN.JISHA_KBN)is NULL)) AND ((TME.HST_GYOUSHA_CD <> TMPT_UPN.UPN_GYOUSHA_CD) OR ((TMPT_UPN.UPN_GYOUSHA_CD)is NULL))		
								AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/		
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て			
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <> '')		
								AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/		
		/*END*/
/*END*/
GROUP BY
    /*IF data.GENBASHUKEI_KBN == '1'*/M_CHIIKI.CHIIKI_CD,/*END*/
    TME.HST_GYOUSHA_CD,
	/*IF data.GENBASHUKEI_KBN == '2'*/TME.HST_GENBA_CD,/*END*/
    TME.SYSTEM_ID,
    TME.HAIKI_KBN_CD,
	TME.FIRST_MANIFEST_KBN,
    TMD.HOUKOKUSHOBUNRUISORTKEY,
    M_CHIIKI.GOV_OR_MAY_NAME,
    M_CHIIKI.CHIIKI_NAME_RYAKU,
    GYOUSHA_TODOUFUKEN.TODOUFUKEN_NAME,
    M_GYOUSHA.GYOUSHA_ADDRESS1,
    M_GYOUSHA.GYOUSHA_ADDRESS2,
    M_GYOUSHA.GYOUSHA_NAME1,
    M_GYOUSHA.GYOUSHA_NAME2,
    M_GYOUSHA.JISHA_KBN,
    M_GYOUSHA.GYOUSHA_DAIHYOU,
    M_GYOUSHA.GYOUSHA_TEL,
    GENBA_JGB.GENBA_NAME1,
    GENBA_JGB.GENBA_NAME2,
    GENBA_JGB.GENBA_ADDRESS1,
    GENBA_JGB.GENBA_ADDRESS2,
    TODOUFUKEN_JGB.TODOUFUKEN_NAME,
    M_GYOUSHA.GYOUSHU_CD,
    GENBA_JGB.GYOUSHU_CD,
    GENBA_JGB.GENBA_TEL,
    TMD.HAIKI_SHURUI_CD,
    TMD.HAIKI_SHURUI_NAME_RYAKU,
	TMD.SANPAI_KBN,
    UPN_KYOKA.FUTSUU_KYOKA_NO,
    UPN_KYOKA.TOKUBETSU_KYOKA_NO,
	TM_UPN_KYOKA.FUTSUU_KYOKA_NO,
	TM_UPN_KYOKA.TOKUBETSU_KYOKA_NO,
    UPN_KYOKA_CK.FUTSUU_KYOKA_NO,
    UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO,
	TM_UPN_KYOKA_CK.FUTSUU_KYOKA_NO,
	TM_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO,
    TMPT_UPN.UPN_ROUTE_NO,
    TMPT_UPN.UPN_GYOUSHA_CD,
    GENBA_UPN.GYOUSHA_NAME1,
    GENBA_UPN.GYOUSHA_NAME2,
	GENBA_UPN.JISHA_KBN,
    TMPT_UPN.UPN_SAKI_GYOUSHA_CD,
    TMPT_UPN.UPN_SAKI_GENBA_CD,
    UPN_GENBA_TODOUFUKEN.TODOUFUKEN_NAME,
    UPN_GENBA.GENBA_ADDRESS1,
    UPN_GENBA.GENBA_ADDRESS2,
	UPN_GENBA.JISHA_KBN,
    TME.TMH_GYOUSHA_CD,
    TME.TMH_GENBA_CD,
    TME.SBN_GYOUSHA_CD,
    TME_SBN_GYOUSHA.GYOUSHA_NAME1,
    TME_SBN_GYOUSHA.GYOUSHA_NAME2,
    SBN_KYOKA.FUTSUU_KYOKA_NO,
    SBN_KYOKA.TOKUBETSU_KYOKA_NO,
    LAST_SBN_KYOKA.FUTSUU_KYOKA_NO,
    LAST_SBN_KYOKA.TOKUBETSU_KYOKA_NO,
    TME.SBN_GYOUSHA_NAME

UNION

--建廃のみ
--建廃　排出事業場->(運搬業者)->処分事業場
--建廃　排出事業場->(運搬業者)->積替保管場->(運搬業者)->処分事業場
SELECT
    /*IF data.GENBASHUKEI_KBN == '1'*/M_CHIIKI.CHIIKI_CD + TME.HST_GYOUSHA_CD AS HST_GYOUSHAGENBA,/*END*/
	/*IF data.GENBASHUKEI_KBN == '2'*/TME.HST_GYOUSHA_CD+TME.HST_GENBA_CD AS HST_GYOUSHAGENBA,/*END*/
    '3' AS CHOKKOU_ROUTE_NO,
    TME.SYSTEM_ID,
    TME.HAIKI_KBN_CD,
    TMD.HOUKOKUSHOBUNRUISORTKEY,
    M_CHIIKI.GOV_OR_MAY_NAME,
    M_CHIIKI.CHIIKI_NAME_RYAKU,
    GYOUSHA_TODOUFUKEN.TODOUFUKEN_NAME,
    M_GYOUSHA.GYOUSHA_ADDRESS1,
    M_GYOUSHA.GYOUSHA_ADDRESS2,
    M_GYOUSHA.GYOUSHA_NAME1,
    M_GYOUSHA.GYOUSHA_NAME2,
    M_GYOUSHA.JISHA_KBN,
    M_GYOUSHA.GYOUSHA_DAIHYOU AS DAIHYOUSHA,
    M_GYOUSHA.GYOUSHA_TEL,
    /*data.TITLE1*/ AS TITLE1,
    /*data.TITLE2*/ AS TITLE2,
    GENBA_JGB.GENBA_NAME1 + GENBA_JGB.GENBA_NAME2 AS JGB_NAME,
    GENBA_JGB.GENBA_ADDRESS1 + GENBA_JGB.GENBA_ADDRESS2 AS JGB_ADDRESS,
    TODOUFUKEN_JGB.TODOUFUKEN_NAME AS JGB_TODOUFUKEN_NAME,
    M_GYOUSHA.GYOUSHU_CD AS GYOUSHA_GYOUSHU_CD,
    GENBA_JGB.GYOUSHU_CD AS GENBA_GYOUSHU_CD,
    (SELECT TOP 1 GYOUSHU_NAME FROM M_GYOUSHU AS M1  WHERE M1.GYOUSHU_CD = M_GYOUSHA.GYOUSHU_CD) AS GYOUSHA_GYOUSHU_NM,
    (SELECT TOP 1 GYOUSHU_NAME FROM M_GYOUSHU AS M2  WHERE M2.GYOUSHU_CD = GENBA_JGB.GYOUSHU_CD) AS GENBA_GYOUSHU_NM,
    '' AS GYOUSHU_CD,
    '' AS GYOUSHU_NAME,
    GENBA_JGB.GENBA_TEL,
    TMD.HAIKI_SHURUI_CD,
    TMD.HAIKI_SHURUI_NAME_RYAKU,
    CASE
        WHEN Sum(CONVERT(money,TMD.KANSAN_SUU)) IS NOT NULL THEN Sum(CONVERT(money,TMD.KANSAN_SUU))
        ELSE 0
    END AS HAISHU_RYOU,
    0 AS COUFUMAISUU,

	CASE
		WHEN TMPT_UPN.UPN_ROUTE_NO = 1 THEN	
			--1区間目の許可番号は、排出事業場の地域に対しての運搬許可番号を参照
			CASE
				WHEN TMD.SANPAI_KBN = 1 THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                             ELSE UPN_KYOKA.FUTSUU_KYOKA_NO
                        END
				WHEN TMD.SANPAI_KBN = 2 THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                             ELSE UPN_KYOKA.TOKUBETSU_KYOKA_NO
                        END
				ELSE
                    --普通許可番号があれば普通許可番号、なければ特管許可番号
                    CASE
                        WHEN ISNULL(UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                        WHEN ISNULL(UPN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN UPN_KYOKA.FUTSUU_KYOKA_NO
                        WHEN ISNULL(UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                        ELSE UPN_KYOKA.TOKUBETSU_KYOKA_NO
                    END
			END
		ELSE
			--2区間目の許可番号は、積替保管施設の事業場の地域に対しての運搬許可番号を参照
			CASE
				WHEN TMD.SANPAI_KBN = 1 THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(TM_UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN TM_UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                             ELSE TM_UPN_KYOKA.FUTSUU_KYOKA_NO
                        END
				WHEN TMD.SANPAI_KBN = 2 THEN
                        --地域の許可番号がなければ運搬報告書提出先地域の許可番号を表示する
                        CASE WHEN ISNULL(TM_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN TM_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                             ELSE TM_UPN_KYOKA.TOKUBETSU_KYOKA_NO
                        END
				ELSE
                    --普通許可番号があれば普通許可番号、なければ特管許可番号
                    CASE
                        WHEN ISNULL(TM_UPN_KYOKA_CK.FUTSUU_KYOKA_NO, '') != '' THEN TM_UPN_KYOKA_CK.FUTSUU_KYOKA_NO
                        WHEN ISNULL(TM_UPN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN TM_UPN_KYOKA.FUTSUU_KYOKA_NO
                        WHEN ISNULL(TM_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO, '') != '' THEN TM_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO
                        ELSE TM_UPN_KYOKA.TOKUBETSU_KYOKA_NO
                    END
			END
	END AS UPN_FUTSUU_KYOKA_NO,			
    TMPT_UPN.UPN_ROUTE_NO,
    TMPT_UPN.UPN_GYOUSHA_CD,
    ISNULL(GENBA_UPN.GYOUSHA_NAME1 + GENBA_UPN.GYOUSHA_NAME2, '') AS UPN_GYOUSHA_NAME,
	ISNULL(GENBA_UPN.JISHA_KBN, 0) AS UPN_JISHA_KBN,
    ISNULL(
        CASE
            WHEN (TME.TMH_GENBA_CD <> '' AND TME.TMH_GENBA_CD IS NOT NULL) AND TMPT_UPN.UPN_ROUTE_NO = 1 THEN TME.TMH_GYOUSHA_CD
            ELSE TMPT_UPN.UPN_SAKI_GYOUSHA_CD
        END,
        ''
    ) AS UPN_SAKI_GYOUSHA_CD,
    ISNULL(
        CASE
            WHEN (TME.TMH_GENBA_CD <> '' AND TME.TMH_GENBA_CD IS NOT NULL) AND TMPT_UPN.UPN_ROUTE_NO = 1 THEN TME.TMH_GENBA_CD
            ELSE TMPT_UPN.UPN_SAKI_GENBA_CD
        END,
        ''
    ) AS UPN_SAKI_GENBA_CD,
    ISNULL(
        CASE
            WHEN (TME.TMH_GENBA_CD <> '' AND TME.TMH_GENBA_CD IS NOT NULL) AND TMPT_UPN.UPN_ROUTE_NO = 1 THEN TME_GENBA_TODOUFUKEN.TODOUFUKEN_NAME + TME_GENBA.GENBA_ADDRESS1 + TME_GENBA.GENBA_ADDRESS2
            ELSE UPN_GENBA_TODOUFUKEN.TODOUFUKEN_NAME + UPN_GENBA.GENBA_ADDRESS1 + UPN_GENBA.GENBA_ADDRESS2
        END,
        ''
    ) AS UPN_SAKI_GENBA_ADDRESS,
	/*IF data.GYOUSHASET_KBN2 == '2' || data.GYOUSHASET_KBN2 == '4'*/ --[提出業者設定-2] = 2.運搬/排出事業者, 4.全て
	CASE
		WHEN TME.FIRST_MANIFEST_KBN = 0 THEN
			CASE
				WHEN (TME.TMH_GENBA_CD <> '' AND TME.TMH_GENBA_CD IS NOT NULL) AND TMPT_UPN.UPN_ROUTE_NO = 1 THEN ''
				WHEN TMD.SANPAI_KBN = 1 THEN SBN_KYOKA.FUTSUU_KYOKA_NO
				WHEN TMD.SANPAI_KBN = 2 THEN SBN_KYOKA.TOKUBETSU_KYOKA_NO
				ELSE
					CASE
						WHEN ISNULL(SBN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN SBN_KYOKA.FUTSUU_KYOKA_NO
						ELSE SBN_KYOKA.TOKUBETSU_KYOKA_NO
					END
			END
		WHEN TME.FIRST_MANIFEST_KBN = 1 THEN
			CASE
				WHEN (TME.TMH_GENBA_CD <> '' AND TME.TMH_GENBA_CD IS NOT NULL) AND TMPT_UPN.UPN_ROUTE_NO = 1 THEN ''
				WHEN TMD.SANPAI_KBN = 1 THEN LAST_SBN_KYOKA.FUTSUU_KYOKA_NO
				WHEN TMD.SANPAI_KBN = 2 THEN LAST_SBN_KYOKA.TOKUBETSU_KYOKA_NO
				ELSE
					CASE
						WHEN ISNULL(LAST_SBN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN LAST_SBN_KYOKA.FUTSUU_KYOKA_NO
						ELSE LAST_SBN_KYOKA.TOKUBETSU_KYOKA_NO
					END
			END
	END AS SBN_FUTSUU_KYOKA_NO,
    ISNULL(
        CASE
            WHEN(
                TME.TMH_GENBA_CD <> ''
            AND TME.TMH_GENBA_CD IS NOT NULL
            )
        AND TMPT_UPN.UPN_ROUTE_NO = 1 THEN ''
            ELSE TME.SBN_GYOUSHA_CD
        END,
        ''
    ) AS SBN_GYOUSHA_CD,
    ISNULL(
        CASE
            WHEN(
                TME.TMH_GENBA_CD <> ''
            AND TME.TMH_GENBA_CD IS NOT NULL
            )
        AND TMPT_UPN.UPN_ROUTE_NO = 1 THEN ''
            ELSE TME_SBN_GYOUSHA.GYOUSHA_NAME1 + TME_SBN_GYOUSHA.GYOUSHA_NAME2
        END,
        ''
    ) AS SBN_GYOUSHA_NAME,
    ISNULL(
        CASE
            WHEN(
                TME.TMH_GENBA_CD <> ''
            AND TME.TMH_GENBA_CD IS NOT NULL
            )
        AND TMPT_UPN.UPN_ROUTE_NO = 1 THEN ''
            ELSE TMPT_UPN.UPN_SAKI_GENBA_CD
        END,
        ''
    ) AS SBN_GENBA_CD,
    ISNULL(
        CASE
            WHEN(
                TME.TMH_GENBA_CD <> ''
            AND TME.TMH_GENBA_CD IS NOT NULL
            )
        AND TMPT_UPN.UPN_ROUTE_NO = 1 THEN ''
            ELSE UPN_GENBA_TODOUFUKEN.TODOUFUKEN_NAME + UPN_GENBA.GENBA_ADDRESS1 + UPN_GENBA.GENBA_ADDRESS2
        END,
        ''
    ) AS SBN_GENBA_ADDRESS,
    ISNULL(
        CASE
            WHEN(TME.TMH_GENBA_CD <> '' AND TME.TMH_GENBA_CD IS NOT NULL) AND TMPT_UPN.UPN_ROUTE_NO = 1 THEN 0
            ELSE UPN_GENBA.JISHA_KBN
        END,
        0
    ) AS SBN_GENBA_JISHA_KBN
	/*END*/
	/*IF data.GYOUSHASET_KBN2 == '1' || data.GYOUSHASET_KBN2 == '3'*/ --[提出業者設定-2] = 1.収集運搬/自社, 3.収集運搬/他社
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN ''		--処分受託者欄に処分受託者を表示していい区間ではない(後区間にて表示される)
		ELSE
			CASE
				WHEN TME.FIRST_MANIFEST_KBN = 0 THEN
					CASE
						WHEN TMD.SANPAI_KBN = 1 THEN SBN_KYOKA.FUTSUU_KYOKA_NO
						WHEN TMD.SANPAI_KBN = 2 THEN SBN_KYOKA.TOKUBETSU_KYOKA_NO
						ELSE
							CASE
								WHEN ISNULL(SBN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN SBN_KYOKA.FUTSUU_KYOKA_NO
								ELSE SBN_KYOKA.TOKUBETSU_KYOKA_NO
							END
					END
				WHEN TME.FIRST_MANIFEST_KBN = 1 THEN
					CASE
						WHEN TMD.SANPAI_KBN = 1 THEN LAST_SBN_KYOKA.FUTSUU_KYOKA_NO
						WHEN TMD.SANPAI_KBN = 2 THEN LAST_SBN_KYOKA.TOKUBETSU_KYOKA_NO
						ELSE
							CASE
								WHEN ISNULL(LAST_SBN_KYOKA.FUTSUU_KYOKA_NO, '') != '' THEN LAST_SBN_KYOKA.FUTSUU_KYOKA_NO
								ELSE LAST_SBN_KYOKA.TOKUBETSU_KYOKA_NO
							END
					END
			END
		END AS SBN_FUTSUU_KYOKA_NO,
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN ''
		ELSE TME.SBN_GYOUSHA_CD
        END AS SBN_GYOUSHA_CD,
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN ''
		ELSE TME_SBN_GYOUSHA.GYOUSHA_NAME1 + TME_SBN_GYOUSHA.GYOUSHA_NAME2
		END AS SBN_GYOUSHA_NAME,
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN ''
		ELSE TMPT_UPN.UPN_SAKI_GENBA_CD
        END AS SBN_GENBA_CD,
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN ''
		ELSE UPN_GENBA_TODOUFUKEN.TODOUFUKEN_NAME + UPN_GENBA.GENBA_ADDRESS1 + UPN_GENBA.GENBA_ADDRESS2
        END AS SBN_GENBA_ADDRESS,
	CASE WHEN SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO IS NULL THEN ''
		ELSE UPN_GENBA.JISHA_KBN
        END AS SBN_GENBA_JISHA_KBN
	/*END*/
FROM T_MANIFEST_ENTRY AS TME
INNER JOIN T_MANIFEST_UPN AS TMPT_UPN ON (TME.SYSTEM_ID = TMPT_UPN.SYSTEM_ID AND TME.SEQ = TMPT_UPN.SEQ AND (TMPT_UPN.UPN_GYOUSHA_CD <> '' AND TMPT_UPN.UPN_GYOUSHA_CD IS NOT NULL))
/*IF data.KONGOU_KBN == '1'*/--■混合出力有
LEFT JOIN
    (SELECT 
        TME1.SYSTEM_ID,
        TME1.SEQ,
        CASE
            WHEN Sum(CONVERT(money,TMD1.KANSAN_SUU)) IS NOT NULL THEN Sum(CONVERT(money,TMD1.KANSAN_SUU))
            ELSE 0
        END AS KANSAN_SUU,
        CASE
            WHEN COUNT(DISTINCT HOUKOKU.HOUKOKUSHO_BUNRUI_CD) > 1 THEN 2
            ELSE 1
        END AS HOUKOKUSHOBUNRUISORTKEY,
        CASE
            WHEN COUNT(DISTINCT HOUKOKU.HOUKOKUSHO_BUNRUI_CD) > 1 THEN ''
            ELSE MAX(HOUKOKU.HOUKOKUSHO_BUNRUI_CD)
        END AS HAIKI_SHURUI_CD,
        CASE
            WHEN COUNT(DISTINCT HOUKOKU.HOUKOKUSHO_BUNRUI_CD) > 1 THEN '混合廃棄物'
            ELSE MAX(HOUKOKU.HOUKOKUSHO_BUNRUI_NAME)
        END AS HAIKI_SHURUI_NAME_RYAKU,
        CASE
			WHEN SUM(CASE WHEN ISNULL(HAIKI.HAIKI_SHURUI_CD, '') < '2100' THEN 0 ELSE 1 END) = 0 THEN 1	--普通
			WHEN SUM(CASE WHEN ISNULL(HAIKI.HAIKI_SHURUI_CD, '') < '2100' THEN 0 ELSE 1 END) = COUNT(HAIKI.HAIKI_SHURUI_CD) THEN 2	--特管
			ELSE 3 --混在
		END AS SANPAI_KBN
     FROM T_MANIFEST_ENTRY AS TME1
     LEFT JOIN T_MANIFEST_DETAIL AS TMD1 ON (TME1.SYSTEM_ID = TMD1.SYSTEM_ID AND TME1.SEQ = TMD1.SEQ)
     LEFT JOIN M_HAIKI_SHURUI AS HAIKI ON (TME1.HAIKI_KBN_CD = HAIKI.HAIKI_KBN_CD AND TMD1.HAIKI_SHURUI_CD = HAIKI.HAIKI_SHURUI_CD)
     LEFT JOIN M_HOUKOKUSHO_BUNRUI AS HOUKOKU ON  HAIKI.HOUKOKUSHO_BUNRUI_CD = HOUKOKU.HOUKOKUSHO_BUNRUI_CD
     WHERE   TME1.DELETE_FLG = 0
          AND ((TME1.KOUFU_DATE) >= /*data.KOUFU_DATE_FROM*/ AND (TME1.KOUFU_DATE) <= /*data.KOUFU_DATE_TO*/)
     GROUP BY TME1.SYSTEM_ID,TME1.SEQ ) AS TMD ON (TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ)
/*END*/
/*IF data.KONGOU_KBN == '2'*/--■混合出力無
LEFT JOIN 
    (SELECT
        TME1.SYSTEM_ID,
        TME1.SEQ,
        CASE
            WHEN Sum(CONVERT(money,TMD1.KANSAN_SUU)) IS NOT NULL THEN Sum(CONVERT(money,TMD1.KANSAN_SUU))
            ELSE 0
        END AS KANSAN_SUU,
        1 AS HOUKOKUSHOBUNRUISORTKEY,
        HOUKOKU.HOUKOKUSHO_BUNRUI_CD AS HAIKI_SHURUI_CD,
        HOUKOKU.HOUKOKUSHO_BUNRUI_NAME AS HAIKI_SHURUI_NAME_RYAKU,
        CASE
			WHEN SUM(CASE WHEN ISNULL(HAIKI.HAIKI_SHURUI_CD, '') < '2100' THEN 0 ELSE 1 END) = 0 THEN 1	--普通
			WHEN SUM(CASE WHEN ISNULL(HAIKI.HAIKI_SHURUI_CD, '') < '2100' THEN 0 ELSE 1 END) = COUNT(HAIKI.HAIKI_SHURUI_CD) THEN 2	--特管
			ELSE 3 --混在
		END AS SANPAI_KBN
    FROM T_MANIFEST_ENTRY AS TME1
    LEFT JOIN T_MANIFEST_DETAIL AS TMD1 ON (TME1.SYSTEM_ID = TMD1.SYSTEM_ID AND TME1.SEQ = TMD1.SEQ)
    LEFT JOIN M_HAIKI_SHURUI AS HAIKI ON (TME1.HAIKI_KBN_CD = HAIKI.HAIKI_KBN_CD AND TMD1.HAIKI_SHURUI_CD = HAIKI.HAIKI_SHURUI_CD)
    LEFT JOIN M_HOUKOKUSHO_BUNRUI AS HOUKOKU ON  HAIKI.HOUKOKUSHO_BUNRUI_CD = HOUKOKU.HOUKOKUSHO_BUNRUI_CD
    WHERE TME1.DELETE_FLG = 0
		AND ((TME1.KOUFU_DATE) >= /*data.KOUFU_DATE_FROM*/ AND (TME1.KOUFU_DATE) <= /*data.KOUFU_DATE_TO*/)
    GROUP BY TME1.SYSTEM_ID,TME1.SEQ,HOUKOKU.HOUKOKUSHO_BUNRUI_CD,HOUKOKU.HOUKOKUSHO_BUNRUI_NAME) AS TMD ON (TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ)
/*END*/
LEFT JOIN M_GYOUSHA AS GENBA_UPN ON (TMPT_UPN.UPN_GYOUSHA_CD = GENBA_UPN.GYOUSHA_CD)
LEFT JOIN M_GENBA AS GENBA_SBN ON (TME.SBN_GYOUSHA_CD = GENBA_SBN.GYOUSHA_CD AND TMPT_UPN.UPN_SAKI_GENBA_CD = GENBA_SBN.GENBA_CD)
LEFT JOIN M_GENBA AS GENBA_CHK ON (TME.HST_GYOUSHA_CD = GENBA_CHK.GYOUSHA_CD AND TME.HST_GENBA_CD = GENBA_CHK.GENBA_CD)
LEFT JOIN M_CHIIKI  ON (GENBA_CHK.CHIIKI_CD = M_CHIIKI.CHIIKI_CD)
LEFT JOIN M_GYOUSHA ON (TME.HST_GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD)
LEFT JOIN M_TODOUFUKEN AS GYOUSHA_TODOUFUKEN ON (M_GYOUSHA.GYOUSHA_TODOUFUKEN_CD = GYOUSHA_TODOUFUKEN.TODOUFUKEN_CD)
LEFT JOIN M_GENBA AS GENBA_JGB ON (TME.HST_GYOUSHA_CD = GENBA_JGB.GYOUSHA_CD AND TME.HST_GENBA_CD = GENBA_JGB.GENBA_CD)
LEFT JOIN M_TODOUFUKEN AS TODOUFUKEN_JGB ON (GENBA_JGB.GENBA_TODOUFUKEN_CD = TODOUFUKEN_JGB.TODOUFUKEN_CD)
LEFT JOIN M_GENBA AS UPN_GENBA ON  (TMPT_UPN.UPN_SAKI_GYOUSHA_CD = UPN_GENBA.GYOUSHA_CD AND TMPT_UPN.UPN_SAKI_GENBA_CD = UPN_GENBA.GENBA_CD)
LEFT JOIN M_TODOUFUKEN AS UPN_GENBA_TODOUFUKEN ON  (UPN_GENBA.GENBA_TODOUFUKEN_CD = UPN_GENBA_TODOUFUKEN.TODOUFUKEN_CD)
LEFT JOIN M_GENBA AS TME_GENBA ON  (TME.TMH_GYOUSHA_CD = TME_GENBA.GYOUSHA_CD AND TME.TMH_GENBA_CD = TME_GENBA.GENBA_CD)
LEFT JOIN M_TODOUFUKEN AS TME_GENBA_TODOUFUKEN ON  (TME_GENBA.GENBA_TODOUFUKEN_CD = TME_GENBA_TODOUFUKEN.TODOUFUKEN_CD)
LEFT JOIN M_GYOUSHA AS TME_SBN_GYOUSHA ON  (TME.SBN_GYOUSHA_CD = TME_SBN_GYOUSHA.GYOUSHA_CD)
LEFT JOIN (
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS UPN_KYOKA ON (TMPT_UPN.UPN_GYOUSHA_CD = UPN_KYOKA.GYOUSHA_CD AND GENBA_JGB.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = UPN_KYOKA.CHIIKI_CD AND UPN_KYOKA.KYOKA_KBN = 1 AND UPN_KYOKA.KYOKA_KBN = 1)
LEFT JOIN (
            --地域に対しての許可番号。政令指定都市＞都道府県の順に許可番号を適用するため、運搬報告書提出先の地域、地域に対しての許可番号を取得する
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS UPN_KYOKA_CK ON (TMPT_UPN.UPN_GYOUSHA_CD = UPN_KYOKA_CK.GYOUSHA_CD AND GENBA_JGB.CHIIKI_CD = UPN_KYOKA_CK.CHIIKI_CD AND UPN_KYOKA_CK.KYOKA_KBN = 1)
LEFT JOIN (
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS TM_UPN_KYOKA ON (TMPT_UPN.UPN_GYOUSHA_CD = TM_UPN_KYOKA.GYOUSHA_CD AND TME_GENBA.UPN_HOUKOKUSHO_TEISHUTSU_CHIIKI_CD = TM_UPN_KYOKA.CHIIKI_CD AND TM_UPN_KYOKA.KYOKA_KBN = 1)
LEFT JOIN (
            --地域に対しての許可番号。政令指定都市＞都道府県の順に許可番号を適用するため、運搬報告書提出先の地域、地域に対しての許可番号を取得する
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 1
) AS TM_UPN_KYOKA_CK ON (TMPT_UPN.UPN_GYOUSHA_CD = TM_UPN_KYOKA_CK.GYOUSHA_CD AND TME_GENBA.CHIIKI_CD = TM_UPN_KYOKA_CK.CHIIKI_CD AND TM_UPN_KYOKA_CK.KYOKA_KBN = 1)
LEFT JOIN (
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.GENBA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 2
) AS SBN_KYOKA ON (TME.SBN_GYOUSHA_CD = SBN_KYOKA.GYOUSHA_CD AND TMPT_UPN.UPN_SAKI_GENBA_CD = SBN_KYOKA.GENBA_CD AND GENBA_SBN.CHIIKI_CD = SBN_KYOKA.CHIIKI_CD AND SBN_KYOKA.KYOKA_KBN = 2)
LEFT JOIN (
            SELECT
                M_CHIIKIBETSU_KYOKA.GYOUSHA_CD,
                M_CHIIKIBETSU_KYOKA.GENBA_CD,
                M_CHIIKIBETSU_KYOKA.CHIIKI_CD,
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN,
                M_CHIIKIBETSU_KYOKA.FUTSUU_KYOKA_NO,
                M_CHIIKIBETSU_KYOKA.TOKUBETSU_KYOKA_NO
            FROM
                M_CHIIKIBETSU_KYOKA
            WHERE
                M_CHIIKIBETSU_KYOKA.KYOKA_KBN = 3
) AS LAST_SBN_KYOKA ON (TME.SBN_GYOUSHA_CD = LAST_SBN_KYOKA.GYOUSHA_CD AND TMPT_UPN.UPN_SAKI_GENBA_CD = LAST_SBN_KYOKA.GENBA_CD AND GENBA_SBN.CHIIKI_CD = LAST_SBN_KYOKA.CHIIKI_CD AND LAST_SBN_KYOKA.KYOKA_KBN = 3)
/*IF data.GYOUSHASET_KBN2 == '1' || data.GYOUSHASET_KBN2 == '3'*/ --[提出業者設定-2] = 1.収集運搬/自社, 3.収集運搬/他社
LEFT JOIN
(
	SELECT
		MAX(T_MANIFEST_UPN.UPN_ROUTE_NO) MAX_UPN_ROUTE_NO,
		T_MANIFEST_UPN.SYSTEM_ID,
		T_MANIFEST_UPN.SEQ
	FROM
		T_MANIFEST_UPN
		INNER JOIN T_MANIFEST_ENTRY ON T_MANIFEST_ENTRY.SYSTEM_ID = T_MANIFEST_UPN.SYSTEM_ID AND T_MANIFEST_ENTRY.SEQ = T_MANIFEST_UPN.SEQ AND T_MANIFEST_ENTRY.DELETE_FLG = 0
		INNER JOIN M_GYOUSHA ON T_MANIFEST_UPN.UPN_GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
	WHERE
		/*IF data.GYOUSHASET_KBN2 == '1'*/M_GYOUSHA.JISHA_KBN <> 0/*END*/
		/*IF data.GYOUSHASET_KBN2 == '3'*/M_GYOUSHA.JISHA_KBN = 0/*END*/
	GROUP BY
		T_MANIFEST_UPN.SYSTEM_ID,
		T_MANIFEST_UPN.SEQ

) AS SBN_DISP_ROUTE_NO ON TMPT_UPN.SYSTEM_ID = SBN_DISP_ROUTE_NO.SYSTEM_ID AND TMPT_UPN.SEQ = SBN_DISP_ROUTE_NO.SEQ AND TMPT_UPN.UPN_ROUTE_NO = SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO
/*END*/
WHERE TME.DELETE_FLG = 0 AND ((TME.KOUFU_DATE) >= /*data.KOUFU_DATE_FROM*/ AND (TME.KOUFU_DATE) <= /*data.KOUFU_DATE_TO*/)
      AND TME.HAIKI_KBN_CD = 2
/*IF data.GYOUSHU != null && data.GYOUSHU != ''*/
	AND (GENBA_JGB.GYOUSHU_CD = /*data.GYOUSHU*/ OR (M_GYOUSHA.GYOUSHU_CD = /*data.GYOUSHU*/ AND (GENBA_JGB.GYOUSHU_CD = '' OR GENBA_JGB.GYOUSHU_CD IS NULL)))
/*END*/

/*IF data.GYOUSHASET_KBN1 == '1'*/ --if --[提出業者設定-1] = 1.個別(提出業者:FROMのみ)	
 /*IF data.GENBASHUKEI_KBN == '2'*/--現場一括集計:1する,2:しない
   AND(TME.HST_GENBA_CD >=/*data.GENBA_CD_FROM*/ AND TME.HST_GENBA_CD <=/*data.GENBA_CD_TO*/ )
   /*END*/	
    /*IF data.TEISHUTUSAKI_KBN == '1'*/ --if --[提出先] = 1.全体(都道府県政令の指定検索しない)
				/*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社
								AND ((TME.HST_GYOUSHA_CD)= /*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND GENBA_UPN.JISHA_KBN <> 0
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者	
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND (TME.HST_GYOUSHA_CD = TMPT_UPN.UPN_GYOUSHA_CD)
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社			
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND TME.HST_GENBA_CD <> '') AND (GENBA_UPN.JISHA_KBN = 0 OR GENBA_UPN.JISHA_KBN is NULL) AND (TME.HST_GYOUSHA_CD <> TMPT_UPN.UPN_GYOUSHA_CD OR TMPT_UPN.UPN_GYOUSHA_CD is NULL)		
				/*END*/							
				/*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て	
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '')
				/*END*/	
	 /*END*/	
	 /*IF data.TEISHUTUSAKI_KBN == '2'*/ --	else if --[提出先] = 2.個別(都道府県政令の指定検索する)								
				/*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社			
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND GENBA_UPN.JISHA_KBN <> 0 AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/
				/*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者			
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND (TME.HST_GYOUSHA_CD = TMPT_UPN.UPN_GYOUSHA_CD) AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/
				/*END*/
				/*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社		
								AND ((TME.HST_GYOUSHA_CD)=/*data.GYOUSHA_CD_FROM*/ AND (TME.HST_GENBA_CD)<> '') AND (GENBA_UPN.JISHA_KBN = 0 OR GENBA_UPN.JISHA_KBN is NULL) AND (TME.HST_GYOUSHA_CD <> TMPT_UPN.UPN_GYOUSHA_CD OR TMPT_UPN.UPN_GYOUSHA_CD is NULL)		
								AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/		
				/*END*/
				/*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て		
								AND TME.HST_GYOUSHA_CD =/*data.GYOUSHA_CD_FROM*/ AND TME.HST_GENBA_CD <> '' AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/
	/*END*/
/*END*/	
/*IF data.GYOUSHASET_KBN1 == '2'*/--else if--[提出業者設定-1] = 2.全体(提出業者:FROM/TO)										
		/*IF data.TEISHUTUSAKI_KBN == '1'*/ --if --[提出先] = 1.全体(都道府県政令の指定検索しない)								
				/*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/ ) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <> '')		
								AND GENBA_UPN.JISHA_KBN <> 0	
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <>  '')		
								AND (TME.HST_GYOUSHA_CD = TMPT_UPN.UPN_GYOUSHA_CD)
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/ )) AND (TME.HST_GENBA_CD) <> '')		
								AND ((GENBA_UPN.JISHA_KBN = 0) OR ((GENBA_UPN.JISHA_KBN)is NULL)) AND ((TME.HST_GYOUSHA_CD <> TMPT_UPN.UPN_GYOUSHA_CD) OR ((TMPT_UPN.UPN_GYOUSHA_CD)is NULL))		
										
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <> '')
				/*END*/
		/*END*/	
		/*IF data.TEISHUTUSAKI_KBN == '2'*/ --else if--[提出先] = 2.個別(都道府県政令の指定検索する)								
				/*IF data.GYOUSHASET_KBN2 == '1'*/ --if --[提出業者設定-2] = 1.収集運搬/自社			
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/ ) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <> '')		
								AND GENBA_UPN.JISHA_KBN <> 0 AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '2'*/ --else if --[提出業者設定-2] = 2.運搬/排出事業者	
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <>  '')		
								AND (TME.HST_GYOUSHA_CD = TMPT_UPN.UPN_GYOUSHA_CD) AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '3'*/ --else if --[提出業者設定-2] = 3.収集運搬/他社			
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/ )) AND (TME.HST_GENBA_CD) <> '')		
								AND ((GENBA_UPN.JISHA_KBN = 0) OR ((GENBA_UPN.JISHA_KBN)is NULL)) AND ((TME.HST_GYOUSHA_CD <> TMPT_UPN.UPN_GYOUSHA_CD) OR ((TMPT_UPN.UPN_GYOUSHA_CD)is NULL))		
								AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/		
				/*END*/	
				/*IF data.GYOUSHASET_KBN2 == '4'*/ --else if --[提出業者設定-2] = 4.全て			
								AND ((((TME.HST_GYOUSHA_CD) >=/*data.GYOUSHA_CD_FROM*/) AND ((TME.HST_GYOUSHA_CD) <= /*data.GYOUSHA_CD_TO*/)) AND (TME.HST_GENBA_CD) <> '')		
								AND M_CHIIKI.CHIIKI_CD =/*data.CHIIKI_CD*/	
				/*END*/		
		/*END*/
/*END*/
GROUP BY
    /*IF data.GENBASHUKEI_KBN == '1'*/M_CHIIKI.CHIIKI_CD,/*END*/
    TME.HST_GYOUSHA_CD,
	/*IF data.GENBASHUKEI_KBN == '2'*/TME.HST_GENBA_CD,/*END*/
    TME.SYSTEM_ID,
    TME.HAIKI_KBN_CD,
	TME.FIRST_MANIFEST_KBN,
    TMD.HOUKOKUSHOBUNRUISORTKEY,
    M_CHIIKI.GOV_OR_MAY_NAME,
    M_CHIIKI.CHIIKI_NAME_RYAKU,
    GYOUSHA_TODOUFUKEN.TODOUFUKEN_NAME,
    M_GYOUSHA.GYOUSHA_ADDRESS1,
    M_GYOUSHA.GYOUSHA_ADDRESS2,
    M_GYOUSHA.GYOUSHA_NAME1,
    M_GYOUSHA.GYOUSHA_NAME2,
    M_GYOUSHA.JISHA_KBN,
    M_GYOUSHA.GYOUSHA_DAIHYOU,
    M_GYOUSHA.GYOUSHA_TEL,
    GENBA_JGB.GENBA_NAME1,
    GENBA_JGB.GENBA_NAME2,
    GENBA_JGB.GENBA_ADDRESS1,
    GENBA_JGB.GENBA_ADDRESS2,
    TODOUFUKEN_JGB.TODOUFUKEN_NAME,
    M_GYOUSHA.GYOUSHU_CD,
    GENBA_JGB.GYOUSHU_CD,
    GENBA_JGB.GENBA_TEL,
    TMD.HAIKI_SHURUI_CD,
    TMD.HAIKI_SHURUI_NAME_RYAKU,
	TMD.SANPAI_KBN,
    UPN_KYOKA.FUTSUU_KYOKA_NO,
    UPN_KYOKA.TOKUBETSU_KYOKA_NO,
    TM_UPN_KYOKA.FUTSUU_KYOKA_NO,
    TM_UPN_KYOKA.TOKUBETSU_KYOKA_NO,
    UPN_KYOKA_CK.FUTSUU_KYOKA_NO,
    UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO,
    TM_UPN_KYOKA_CK.FUTSUU_KYOKA_NO,
    TM_UPN_KYOKA_CK.TOKUBETSU_KYOKA_NO,
    TMPT_UPN.UPN_ROUTE_NO,
    TMPT_UPN.UPN_GYOUSHA_CD,
    GENBA_UPN.GYOUSHA_NAME1,
    GENBA_UPN.GYOUSHA_NAME2,
	GENBA_UPN.JISHA_KBN,
    TMPT_UPN.UPN_SAKI_GYOUSHA_CD,
    TMPT_UPN.UPN_SAKI_GENBA_CD,
    UPN_GENBA_TODOUFUKEN.TODOUFUKEN_NAME,
    UPN_GENBA.GENBA_ADDRESS1,
    UPN_GENBA.GENBA_ADDRESS2,
	UPN_GENBA.JISHA_KBN,
    SBN_KYOKA.FUTSUU_KYOKA_NO,
    SBN_KYOKA.TOKUBETSU_KYOKA_NO,
    LAST_SBN_KYOKA.FUTSUU_KYOKA_NO,
    LAST_SBN_KYOKA.TOKUBETSU_KYOKA_NO,
    TME.SBN_GYOUSHA_CD,
    TME_SBN_GYOUSHA.GYOUSHA_NAME1,
    TME_SBN_GYOUSHA.GYOUSHA_NAME2,
    TME.TMH_GYOUSHA_CD,
    TME.TMH_GENBA_CD,
    TME_GENBA_TODOUFUKEN.TODOUFUKEN_NAME,
    TME_GENBA.GENBA_ADDRESS1,
    TME_GENBA.GENBA_ADDRESS2
	/*IF data.GYOUSHASET_KBN2 == '1' || data.GYOUSHASET_KBN2 == '3'*/ --[提出業者設定-2] = 1.収集運搬/自社 ,3.収集運搬/他社
	,SBN_DISP_ROUTE_NO.MAX_UPN_ROUTE_NO
	/*END*/
) AS X
ORDER BY
    HST_GYOUSHAGENBA,
    CHOKKOU_ROUTE_NO,
    SYSTEM_ID,
    HAIKI_SHURUI_CD,
    HAIKI_SHURUI_NAME_RYAKU,
    UPN_ROUTE_NO,
    UPN_GYOUSHA_NAME,
    UPN_SAKI_GENBA_ADDRESS
