   SELECT M_KOBETSU_HINMEI.*,
          M_HINMEI.HINMEI_NAME_RYAKU
     FROM M_KOBETSU_HINMEI
LEFT JOIN M_HINMEI
       ON M_HINMEI.HINMEI_CD = M_KOBETSU_HINMEI.HINMEI_CD
    WHERE M_KOBETSU_HINMEI.GYOUSHA_CD = /*data.GYOUSHA_CD*/''
      AND M_KOBETSU_HINMEI.GENBA_CD = /*data.GENBA_CD*/''
      /*IF !deletechuFlg*/AND M_KOBETSU_HINMEI.DELETE_FLG = 0/*END*/
 ORDER BY M_KOBETSU_HINMEI.GYOUSHA_CD,
          M_KOBETSU_HINMEI.GENBA_CD,
          M_KOBETSU_HINMEI.HINMEI_CD

