SELECT
	T0.SHORI,
	T0.DENPYOU_DATE,
	T0.KEIRYOU_NUMBER,
	T0.DATE_NUMBER,
	T0.YEAR_NUMBER,
	T0.GYOUSHA_CD,
	T0.GYOUSHA_NAME,
	T0.GENBA_CD,
	T0.GENBA_NAME,
	T0.UNPAN_GYOUSHA_CD,
	T0.UNPAN_GYOUSHA_NAME,
	T0.SHARYOU_NAME,
	T0.SHASHU_NAME,
	T0.UNTENSHA_NAME,
	T0.NIOROSHI_GYOUSHA_CD,
	T0.NIOROSHI_GYOUSHA_NAME,
	T0.NIOROSHI_GENBA_CD,
	T0.NIOROSHI_GENBA_NAME,
	T0.TORIHIKISAKI_CD,
	T0.TORIHIKISAKI_NAME,
	T0.SYSTEM_ID,
	T0.SEQ,
	T0.UPDATE_USER,
	T0.UPDATE_DATE,
	T0.CREATE_USER,
	T0.CREATE_DATE
FROM
(
SELECT
	case 
	when T1.SEQ = 1 then '新規' 
	when T1.SEQ <> 1 and T1.SEQ <> TX.SEQ then '修正'
	when T1.SEQ <> 1 and T1.SEQ = TX.SEQ and T1.DELETE_FLG = 0 then '修正'
	when T1.SEQ <> 1 and T1.SEQ = TX.SEQ and T1.DELETE_FLG <> 0 then '削除'
	else ''
	end as SHORI,
	CONVERT(varchar,CONVERT(varchar,T1.DENPYOU_DATE,111) + '(' + LEFT(DATENAME(weekday, T1.DENPYOU_DATE),1) + ')') AS DENPYOU_DATE,
	T1.KEIRYOU_NUMBER AS KEIRYOU_NUMBER,
	T1.DATE_NUMBER AS DATE_NUMBER,
	T1.YEAR_NUMBER AS YEAR_NUMBER,
	T1.GYOUSHA_CD AS GYOUSHA_CD,
	T1.GYOUSHA_NAME AS GYOUSHA_NAME,
	T1.GENBA_CD AS GENBA_CD,
	T1.GENBA_NAME AS GENBA_NAME,
	T1.UNPAN_GYOUSHA_CD AS UNPAN_GYOUSHA_CD,
	T1.UNPAN_GYOUSHA_NAME AS UNPAN_GYOUSHA_NAME,
	T1.SHARYOU_NAME AS SHARYOU_NAME,
	T1.SHASHU_NAME AS SHASHU_NAME,
	T1.UNTENSHA_NAME AS UNTENSHA_NAME,
	T1.NIOROSHI_GYOUSHA_CD AS NIOROSHI_GYOUSHA_CD,
	T1.NIOROSHI_GYOUSHA_NAME AS NIOROSHI_GYOUSHA_NAME,
	T1.NIOROSHI_GENBA_CD AS NIOROSHI_GENBA_CD,
	T1.NIOROSHI_GENBA_NAME AS NIOROSHI_GENBA_NAME,
	T1.TORIHIKISAKI_CD AS TORIHIKISAKI_CD,
	T1.TORIHIKISAKI_NAME AS TORIHIKISAKI_NAME,
	T1.SYSTEM_ID AS SYSTEM_ID,
	T1.SEQ AS SEQ,
	T1.UPDATE_USER AS UPDATE_USER,
	T1.UPDATE_DATE,
	T1.CREATE_USER AS CREATE_USER,
	T1.CREATE_DATE

FROM dbo.T_KEIRYOU_ENTRY AS T1 ,(SELECT MAX(SEQ) AS SEQ,SYSTEM_ID FROM T_KEIRYOU_ENTRY   group by SYSTEM_ID) AS TX

WHERE 
T1.DELETE_FLG = T1.DELETE_FLG
/*IF !kyotenCD.IsNull && ''!=kyotenCD*/AND T1.KYOTEN_CD = /*kyotenCD*/0 /*END*/
/*IF !updateFrom.IsNull && ''!=updateFrom*/AND CONVERT(date, T1.UPDATE_DATE) >= CONVERT(date, /*updateFrom*/0) /*END*/
/*IF !updateTo.IsNull && ''!=updateTo*/AND CONVERT(date, T1.UPDATE_DATE) <= CONVERT(date, /*updateTo*/0) /*END*/
AND T1.SEQ = T1.SEQ  AND T1.SYSTEM_ID = TX.SYSTEM_ID
) AS T0
WHERE 
T0.SEQ = T0.SEQ
/*IF !appendWhere.IsNull && ''!=appendWhere*//*$appendWhere*//*END*/

ORDER BY SYSTEM_ID desc, SEQ asc