SELECT 
	T0.SHORI,
	T0.DENPYOU_DATE,
	T0.DENPYOU_NUMBER,
	T0.UKEIRE_TORIHIKISAKI_CD,
	T0.SHUKKA_TORIHIKISAKI_CD,
	T0.UKEIRE_TORIHIKISAKI_NAME,
	T0.SHUKKA_TORIHIKISAKI_NAME,
	T0.UKEIRE_GYOUSHA_CD,
	T0.SHUKKA_GYOUSHA_CD,
	T0.UKEIRE_GYOUSHA_NAME,
	T0.SHUKKA_GYOUSHA_NAME,
	T0.UKEIRE_GENBA_CD,
	T0.SHUKKA_GENBA_CD,
	T0.UKEIRE_GENBA_NAME,
	T0.SHUKKA_GENBA_NAME,
	T0.UNPAN_GYOUSHA_CD,
	T0.UNPAN_GYOUSHA_NAME,
	T0.SHARYOU,
	T0.SHASHU,
	T0.UNTENSHA,
	T0.KOUSHIN_SHA,
	T0.KOUSHIN_BI,
	T0.SAKUSEI_SHA,
	T0.SAKUSEI_BI,
	T0.SYSTEM_ID,
	T0.UKEIRE_SYSTEM_ID,
	T0.SHUKKA_SYSTEM_ID,
	T0.SEQ,
	T0.UKEIRE_SEQ,
	T0.SHUKKA_SEQ
FROM
(
	SELECT
		ISNULL(URIAGE.UKEIRE_SYSTEM_ID, SHIHARAI.SHUKKA_SYSTEM_ID) AS SYSTEM_ID,
		ISNULL(URIAGE.UKEIRE_SEQ, SHIHARAI.SHUKKA_SEQ) AS SEQ,
		ISNULL(URIAGE.UKEIRE_SHORI, SHIHARAI.SHUKKA_SHORI) AS SHORI,
		ISNULL(URIAGE.UKEIRE_DENPYOU_NUMBER, SHIHARAI.SHUKKA_DENPYOU_NUMBER) AS DENPYOU_NUMBER,
		ISNULL(URIAGE.UKEIRE_DENPYOU_DATE, SHIHARAI.SHUKKA_DENPYOU_DATE) AS DENPYOU_DATE,
		ISNULL(URIAGE.UKEIRE_UNPAN_GYOUSHA_CD, SHIHARAI.SHUKKA_UNPAN_GYOUSHA_CD) AS UNPAN_GYOUSHA_CD,
		ISNULL(URIAGE.UKEIRE_UNPAN_GYOUSHA_NAME, SHIHARAI.SHUKKA_UNPAN_GYOUSHA_NAME) AS UNPAN_GYOUSHA_NAME,
		ISNULL(URIAGE.UKEIRE_SHASHU, SHIHARAI.SHUKKA_SHASHU) AS SHASHU,
		ISNULL(URIAGE.UKEIRE_SHARYOU, SHIHARAI.SHUKKA_SHARYOU) AS SHARYOU,
		ISNULL(URIAGE.UKEIRE_UNTENSHA, SHIHARAI.SHUKKA_UNTENSHA) AS UNTENSHA,
		* ,
		ISNULL(URIAGE.UKEIRE_UPDATE_USER, SHIHARAI.SHUKKA_UPDATE_USER) AS KOUSHIN_SHA,
		ISNULL(URIAGE.UKEIRE_UPDATE_DATE, SHIHARAI.SHUKKA_UPDATE_DATE) AS KOUSHIN_BI,
		ISNULL(URIAGE.UKEIRE_CREATE_USER, SHIHARAI.SHUKKA_CREATE_USER) AS SAKUSEI_SHA,
		ISNULL(URIAGE.UKEIRE_CREATE_DATE, SHIHARAI.SHUKKA_CREATE_DATE) AS SAKUSEI_BI
	FROM
	--------------URIAGE START----------------------
		(SELECT
			CASE 
				WHEN T1.SEQ = 1 THEN '新規' 
				WHEN T1.SEQ <> 1 and T1.SEQ <> TX.SEQ THEN '修正'
				WHEN T1.SEQ <> 1 and T1.SEQ = TX.SEQ and T1.DELETE_FLG = 0 THEN '修正'
				WHEN T1.SEQ <> 1 and T1.SEQ = TX.SEQ and T1.DELETE_FLG <> 0 THEN '削除'
				ELSE ''
			END AS UKEIRE_SHORI,
			T1.SYSTEM_ID AS UKEIRE_SYSTEM_ID,
			T1.SEQ AS UKEIRE_SEQ,
			T1.UR_SH_NUMBER AS UKEIRE_DENPYOU_NUMBER,
			T1.DENPYOU_DATE AS UKEIRE_DENPYOU_DATE,
			T1.UNPAN_GYOUSHA_CD AS UKEIRE_UNPAN_GYOUSHA_CD,
			T1.UNPAN_GYOUSHA_NAME AS UKEIRE_UNPAN_GYOUSHA_NAME,
			T1.SHASHU_NAME AS UKEIRE_SHASHU,
			T1.SHARYOU_NAME AS UKEIRE_SHARYOU,
			T1.UNTENSHA_NAME AS UKEIRE_UNTENSHA,
			'受入' AS UKEIRE_KUBUN,
			T1.TORIHIKISAKI_CD AS UKEIRE_TORIHIKISAKI_CD,
			T1.TORIHIKISAKI_NAME AS UKEIRE_TORIHIKISAKI_NAME,
			T1.GYOUSHA_CD AS UKEIRE_GYOUSHA_CD,
			T1.GYOUSHA_NAME AS UKEIRE_GYOUSHA_NAME,
			T1.GENBA_CD AS UKEIRE_GENBA_CD,
			T1.GENBA_NAME AS UKEIRE_GENBA_NAME,
			T1.UPDATE_USER AS UKEIRE_UPDATE_USER,
			T1.UPDATE_DATE AS UKEIRE_UPDATE_DATE,
			T1.CREATE_USER AS UKEIRE_CREATE_USER,
			T1.CREATE_DATE AS UKEIRE_CREATE_DATE
		FROM dbo.T_UR_SH_ENTRY AS T1 ,(SELECT MAX(SEQ) AS SEQ,SYSTEM_ID FROM T_UR_SH_ENTRY   group by SYSTEM_ID) AS TX

		WHERE 
		T1.DELETE_FLG = T1.DELETE_FLG AND T1.DAINOU_FLG = 1 AND T1.SHIHARAI_DATE IS NOT NULL AND T1.SHIHARAI_DATE <> ''
		/*IF !kyotenCD.IsNull && ''!=kyotenCD*/AND T1.KYOTEN_CD = /*kyotenCD*/0 /*END*/
		/*IF !updateFrom.IsNull && ''!=updateFrom*/AND CONVERT(date, T1.UPDATE_DATE) >= CONVERT(date, /*updateFrom*/0) /*END*/
		/*IF !updateTo.IsNull && ''!=updateTo*/AND CONVERT(date, T1.UPDATE_DATE) <= CONVERT(date, /*updateTo*/0) /*END*/
		AND T1.SEQ = T1.SEQ  AND T1.SYSTEM_ID = TX.SYSTEM_ID) AS URIAGE
		--------------URIAGE END----------------------
			FULL OUTER JOIN
			--------------SHIHARAI START------------------
			(SELECT			
				CASE 
					WHEN T1.SEQ = 1 THEN '新規' 
					WHEN T1.SEQ <> 1 and T1.SEQ <> TX.SEQ THEN '修正'
					WHEN T1.SEQ <> 1 and T1.SEQ = TX.SEQ and T1.DELETE_FLG = 0 THEN '修正'
					WHEN T1.SEQ <> 1 and T1.SEQ = TX.SEQ and T1.DELETE_FLG <> 0 THEN '削除'
					ELSE ''
				END AS SHUKKA_SHORI,
				T1.SYSTEM_ID AS SHUKKA_SYSTEM_ID,
				T1.SEQ AS SHUKKA_SEQ,
				T1.UR_SH_NUMBER AS SHUKKA_DENPYOU_NUMBER,
				T1.DENPYOU_DATE AS SHUKKA_DENPYOU_DATE,
				T1.UNPAN_GYOUSHA_CD AS SHUKKA_UNPAN_GYOUSHA_CD,
				T1.UNPAN_GYOUSHA_NAME AS SHUKKA_UNPAN_GYOUSHA_NAME,
				T1.SHASHU_NAME AS SHUKKA_SHASHU,
				T1.SHARYOU_NAME AS SHUKKA_SHARYOU,
				T1.UNTENSHA_NAME AS SHUKKA_UNTENSHA,
				'出荷' AS SHUKKA_KUBUN,
				T1.TORIHIKISAKI_CD AS SHUKKA_TORIHIKISAKI_CD,
				T1.TORIHIKISAKI_NAME AS SHUKKA_TORIHIKISAKI_NAME,
				T1.GYOUSHA_CD AS SHUKKA_GYOUSHA_CD,
				T1.GYOUSHA_NAME AS SHUKKA_GYOUSHA_NAME,
				T1.GENBA_CD AS SHUKKA_GENBA_CD,
				T1.GENBA_NAME AS SHUKKA_GENBA_NAME,
				T1.UPDATE_USER AS SHUKKA_UPDATE_USER,
				T1.UPDATE_DATE AS SHUKKA_UPDATE_DATE,
				T1.CREATE_USER AS SHUKKA_CREATE_USER,
				T1.CREATE_DATE AS SHUKKA_CREATE_DATE
			FROM dbo.T_UR_SH_ENTRY AS T1 ,(SELECT MAX(SEQ) AS SEQ,SYSTEM_ID FROM T_UR_SH_ENTRY   group by SYSTEM_ID) AS TX

			WHERE 
			T1.DELETE_FLG = T1.DELETE_FLG AND T1.DAINOU_FLG = 1 AND T1.URIAGE_DATE IS NOT NULL AND T1.URIAGE_DATE <> ''
			/*IF !kyotenCD.IsNull && ''!=kyotenCD*/AND T1.KYOTEN_CD = /*kyotenCD*/0 /*END*/
			/*IF !updateFrom.IsNull && ''!=updateFrom*/AND CONVERT(date, T1.UPDATE_DATE) >= CONVERT(date, /*updateFrom*/0) /*END*/
			/*IF !updateTo.IsNull && ''!=updateTo*/AND CONVERT(date, T1.UPDATE_DATE) <= CONVERT(date, /*updateTo*/0) /*END*/
			AND T1.SEQ = T1.SEQ  AND T1.SYSTEM_ID = TX.SYSTEM_ID) AS SHIHARAI 
			--------------SHIHARAI END--------------------
		ON URIAGE.UKEIRE_DENPYOU_NUMBER = SHIHARAI.SHUKKA_DENPYOU_NUMBER AND URIAGE.UKEIRE_SEQ = SHIHARAI.SHUKKA_SEQ
) AS T0
WHERE 
T0.SEQ = T0.SEQ
/*IF !appendWhere.IsNull && ''!=appendWhere*//*$appendWhere*//*END*/

ORDER BY SYSTEM_ID DESC, SEQ ASC
