SELECT
	T0.SHORI,
	T0.UKETSUKE_KBN,
	T0.SAGYOU_DATE,
	T0.UKETSUKE_DATE,
	T0.UKETSUKE_NUMBER,
	T0.TORIHIKISAKI_CD,
	T0.TORIHIKISAKI_NAME,
	T0.GYOUSHA_CD,
	T0.GYOUSHA_NAME,
	T0.GENBA_CD,
	T0.GENBA_NAME,
	T0.UNPAN_GYOUSHA_CD,
	T0.UNPAN_GYOUSHA_NAME,
	T0.SHASHU_NAME,
	T0.SHARYOU_NAME,
	T0.UNTENSHA_NAME,
	T0.GOUKEI_KINGAKU_TOTAL,
	T0.GENCHAKU_TIME,
	T0.UKETSUKE_TIME,
	T0.KINGAKU_TOTAL,
	T0.SHOUHIZEI_TOTAL,
	T0.SYSTEM_ID,
	T0.SEQ,
	T0.UPDATE_USER,
	T0.UPDATE_DATE,
	T0.UPDATE_DATE_SORT,
	T0.CREATE_USER,
	T0.CREATE_DATE

FROM
(
SELECT 
	case 
	when T1.SEQ = 1 then '新規' 
	when T1.SEQ <> 1 and T1.SEQ <> TX.SEQ then '修正'
	when T1.SEQ <> 1 and T1.SEQ = TX.SEQ and T1.DELETE_FLG = 0 then '修正'
	when T1.SEQ <> 1 and T1.SEQ = TX.SEQ and T1.DELETE_FLG <> 0 then '削除'
	else ''
	end as SHORI,
	'収集' AS UKETSUKE_KBN,
	CONVERT(varchar,CONVERT(varchar,T1.SAGYOU_DATE,111) + '(' + LEFT(DATENAME(weekday, T1.SAGYOU_DATE),1) + ')') AS SAGYOU_DATE,
	T1.GENCHAKU_TIME AS GENCHAKU_TIME,
	CONVERT(varchar,CONVERT(varchar,T1.UKETSUKE_DATE,111) + '(' + LEFT(DATENAME(weekday, T1.UKETSUKE_DATE),1) + ')') AS UKETSUKE_DATE,
	RIGHT(CONVERT(varchar, DATEPART(hh, T1.UKETSUKE_DATE)), 2) + ':' + RIGHT('0' + CONVERT(varchar, DATEPART(n, T1.UKETSUKE_DATE)), 2) AS UKETSUKE_TIME,
	T1.UKETSUKE_NUMBER AS UKETSUKE_NUMBER,
	T1.GYOUSHA_CD AS GYOUSHA_CD,
	T1.GYOUSHA_NAME AS GYOUSHA_NAME,
	T1.GENBA_CD AS GENBA_CD,
	T1.GENBA_NAME AS GENBA_NAME,
	T1.UNPAN_GYOUSHA_CD AS UNPAN_GYOUSHA_CD,
	T1.UNPAN_GYOUSHA_NAME AS UNPAN_GYOUSHA_NAME,
	T1.SHARYOU_NAME AS SHARYOU_NAME,
	T1.SHASHU_NAME AS SHASHU_NAME,
	T1.UNTENSHA_NAME AS UNTENSHA_NAME,
	T1.TORIHIKISAKI_CD AS TORIHIKISAKI_CD,
	T1.TORIHIKISAKI_NAME AS TORIHIKISAKI_NAME,
	T1.KINGAKU_TOTAL AS KINGAKU_TOTAL,
	T1.SHOUHIZEI_TOTAL AS SHOUHIZEI_TOTAL,
	T1.GOUKEI_KINGAKU_TOTAL AS GOUKEI_KINGAKU_TOTAL,
	T1.SYSTEM_ID AS SYSTEM_ID,
	T1.SEQ AS SEQ,
	T1.UPDATE_USER AS UPDATE_USER,
	T1.UPDATE_DATE,
	T1.UPDATE_DATE AS UPDATE_DATE_SORT,
	T1.CREATE_USER AS CREATE_USER,
	T1.CREATE_DATE


FROM dbo.T_UKETSUKE_SS_ENTRY AS T1 ,(SELECT MAX(SEQ) AS SEQ,SYSTEM_ID FROM T_UKETSUKE_SS_ENTRY   group by SYSTEM_ID) AS TX

WHERE 
T1.DELETE_FLG = T1.DELETE_FLG
/*IF !kyotenCD.IsNull && ''!=kyotenCD*/AND T1.KYOTEN_CD = /*kyotenCD*/0 /*END*/
/*IF !updateFrom.IsNull && ''!=updateFrom*/AND CONVERT(date, T1.UPDATE_DATE) >= CONVERT(date, /*updateFrom*/0) /*END*/
/*IF !updateTo.IsNull && ''!=updateTo*/AND CONVERT(date, T1.UPDATE_DATE) <= CONVERT(date, /*updateTo*/0) /*END*/
AND T1.SEQ = T1.SEQ  AND T1.SYSTEM_ID = TX.SYSTEM_ID

--ORDER BY T1.UPDATE_DATE desc

UNION 
SELECT 
	case 
	when T2.SEQ = 1 then '新規' 
	when T2.SEQ <> 1 and T2.SEQ <> TX.SEQ then '修正'
	when T2.SEQ <> 1 and T2.SEQ = TX.SEQ and T2.DELETE_FLG = 0 then '修正'
	when T2.SEQ <> 1 and T2.SEQ = TX.SEQ and T2.DELETE_FLG <> 0 then '削除'
	else ''
	end as SHORI,
	'出荷' AS UKETSUKE_KBN,
	CONVERT(varchar,CONVERT(varchar,T2.SAGYOU_DATE,111) + '(' + LEFT(DATENAME(weekday, T2.SAGYOU_DATE),1) + ')') AS SAGYOU_DATE,
	T2.GENCHAKU_TIME AS GENCHAKU_TIME,
	CONVERT(varchar,CONVERT(varchar,T2.UKETSUKE_DATE,111) + '(' + LEFT(DATENAME(weekday, T2.UKETSUKE_DATE),1) + ')') AS UKETSUKE_DATE,
	RIGHT(CONVERT(varchar, DATEPART(hh, T2.UKETSUKE_DATE)), 2) + ':' + RIGHT('0' + CONVERT(varchar, DATEPART(n, T2.UKETSUKE_DATE)), 2) AS UKETSUKE_TIME,
	T2.UKETSUKE_NUMBER AS UKETSUKE_NUMBER,
	T2.GYOUSHA_CD AS GYOUSHA_CD,
	T2.GYOUSHA_NAME AS GYOUSHA_NAME,
	T2.GENBA_CD AS GENBA_CD,
	T2.GENBA_NAME AS GENBA_NAME,
	T2.UNPAN_GYOUSHA_CD AS UNPAN_GYOUSHA_CD,
	T2.UNPAN_GYOUSHA_NAME AS UNPAN_GYOUSHA_NAME,
	T2.SHARYOU_NAME AS SHARYOU_NAME,
	T2.SHASHU_NAME AS SHASHU_NAME,
	T2.UNTENSHA_NAME AS UNTENSHA_NAME,
	T2.TORIHIKISAKI_CD AS TORIHIKISAKI_CD,
	T2.TORIHIKISAKI_NAME AS TORIHIKISAKI_NAME,
	T2.KINGAKU_TOTAL AS KINGAKU_TOTAL,
	T2.SHOUHIZEI_TOTAL AS SHOUHIZEI_TOTAL,
	T2.GOUKEI_KINGAKU_TOTAL AS GOUKEI_KINGAKU_TOTAL,
	T2.SYSTEM_ID AS SYSTEM_ID,
	T2.SEQ AS SEQ,
	T2.UPDATE_USER AS UPDATE_USER,
	T2.UPDATE_DATE,
	T2.UPDATE_DATE AS UPDATE_DATE_SORT,
	T2.CREATE_USER AS CREATE_USER,
	T2.CREATE_DATE


FROM dbo.T_UKETSUKE_SK_ENTRY AS T2,(SELECT MAX(SEQ) AS SEQ,SYSTEM_ID FROM T_UKETSUKE_SK_ENTRY   group by SYSTEM_ID) AS TX

WHERE 
T2.DELETE_FLG = T2.DELETE_FLG
/*IF !kyotenCD.IsNull && ''!=kyotenCD*/AND T2.KYOTEN_CD = /*kyotenCD*/0 /*END*/
/*IF !updateFrom.IsNull && ''!=updateFrom*/AND CONVERT(date, T2.UPDATE_DATE) >= CONVERT(date, /*updateFrom*/0) /*END*/
/*IF !updateTo.IsNull && ''!=updateTo*/AND CONVERT(date, T2.UPDATE_DATE) <= CONVERT(date, /*updateTo*/0) /*END*/
AND T2.SEQ = T2.SEQ  AND T2.SYSTEM_ID = TX.SYSTEM_ID

UNION 
SELECT 
	case 
	when T3.SEQ = 1 then '新規' 
	when T3.SEQ <> 1 and T3.SEQ <> TX.SEQ then '修正'
	when T3.SEQ <> 1 and T3.SEQ = TX.SEQ and T3.DELETE_FLG = 0 then '修正'
	when T3.SEQ <> 1 and T3.SEQ = TX.SEQ and T3.DELETE_FLG <> 0 then '削除'
	else ''
	end as SHORI,
	'持込' AS UKETSUKE_KBN,
	CONVERT(varchar,CONVERT(varchar,T3.SAGYOU_DATE,111) + '(' + LEFT(DATENAME(weekday, T3.SAGYOU_DATE),1) + ')') AS SAGYOU_DATE,
	T3.GENCHAKU_TIME AS GENCHAKU_TIME,
	CONVERT(varchar,CONVERT(varchar,T3.UKETSUKE_DATE,111) + '(' + LEFT(DATENAME(weekday, T3.UKETSUKE_DATE),1) + ')') AS UKETSUKE_DATE,
	RIGHT(CONVERT(varchar, DATEPART(hh, T3.UKETSUKE_DATE)), 2) + ':' + RIGHT('0' + CONVERT(varchar, DATEPART(n, T3.UKETSUKE_DATE)), 2) AS UKETSUKE_TIME,
	T3.UKETSUKE_NUMBER AS UKETSUKE_NUMBER,
	T3.GYOUSHA_CD AS GYOUSHA_CD,
	T3.GYOUSHA_NAME AS GYOUSHA_NAME,
	T3.GENBA_CD AS GENBA_CD,
	T3.GENBA_NAME AS GENBA_NAME,
	T3.UNPAN_GYOUSHA_CD AS UNPAN_GYOUSHA_CD,
	T3.UNPAN_GYOUSHA_NAME AS UNPAN_GYOUSHA_NAME,
	T3.SHARYOU_NAME AS SHARYOU_NAME,
	T3.SHASHU_NAME AS SHASHU_NAME,
	'' AS UNTENSHA_NAME,
	T3.TORIHIKISAKI_CD AS TORIHIKISAKI_CD,
	T3.TORIHIKISAKI_NAME AS TORIHIKISAKI_NAME,
	T3.KINGAKU_TOTAL AS KINGAKU_TOTAL,
	T3.SHOUHIZEI_TOTAL AS SHOUHIZEI_TOTAL,
	T3.GOUKEI_KINGAKU_TOTAL AS GOUKEI_KINGAKU_TOTAL,
	T3.SYSTEM_ID AS SYSTEM_ID,
	T3.SEQ AS SEQ,
	T3.UPDATE_USER AS UPDATE_USER,
	T3.UPDATE_DATE,
	T3.UPDATE_DATE AS UPDATE_DATE_SORT,
	T3.CREATE_USER AS CREATE_USER,
	T3.CREATE_DATE


FROM dbo.T_UKETSUKE_MK_ENTRY AS T3 ,(SELECT MAX(SEQ) AS SEQ,SYSTEM_ID FROM T_UKETSUKE_MK_ENTRY   group by SYSTEM_ID) AS TX

WHERE 
T3.DELETE_FLG = T3.DELETE_FLG
/*IF !kyotenCD.IsNull && ''!=kyotenCD*/AND T3.KYOTEN_CD = /*kyotenCD*/0 /*END*/
/*IF !updateFrom.IsNull && ''!=updateFrom*/AND CONVERT(date, T3.UPDATE_DATE) >= CONVERT(date, /*updateFrom*/0) /*END*/
/*IF !updateTo.IsNull && ''!=updateTo*/AND CONVERT(date, T3.UPDATE_DATE) <= CONVERT(date, /*updateTo*/0) /*END*/
AND T3.SEQ = T3.SEQ  AND T3.SYSTEM_ID = TX.SYSTEM_ID
) AS T0
where 
T0.SEQ = T0.SEQ
/*IF !appendWhere.IsNull && ''!=appendWhere*//*$appendWhere*//*END*/
ORDER BY SYSTEM_ID desc, SEQ asc