SELECT 
    CHI.*
    ,ISNULL(SHO.SHOBUN_HOUHOU_NAME_RYAKU,N'') AS SHOBUN_HOUHOU_NAME_RYAKU
FROM 
    dbo.M_CHIIKIBETSU_SHISETSU CHI
	LEFT JOIN dbo.M_SHOBUN_HOUHOU SHO ON SHO.SHOBUN_HOUHOU_CD = CHI.SHOBUN_HOUHOU_CD
WHERE CHI.CHIIKI_CD = /*data.CHIIKI_CD*/'000001'
  /*IF data.SHOBUN_HOUHOU_CD != null*/AND CHI.SHOBUN_HOUHOU_CD LIKE '%' +  /*data.SHOBUN_HOUHOU_CD*/ + '%'/*END*/
  /*IF data.HOUKOKU_SHISETSU_CD != null*/AND CHI.HOUKOKU_SHISETSU_CD LIKE '%' +  /*data.HOUKOKU_SHISETSU_CD*/ + '%'/*END*/
  /*IF data.HOUKOKU_SHISETSU_NAME != null*/AND CHI.HOUKOKU_SHISETSU_NAME LIKE '%' +  /*data.HOUKOKU_SHISETSU_NAME*/ + '%'/*END*/
  /*IF data.CHIIKIBETSU_SHISETSU_BIKOU != null*/AND CHI.CHIIKIBETSU_SHISETSU_BIKOU LIKE '%' +  /*data.CHIIKIBETSU_SHISETSU_BIKOU*/ + '%'/*END*/
  /*IF data.UPDATE_USER != null*/AND CHI.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
  /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, CHI.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
  /*IF data.CREATE_USER != null*/AND CHI.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
  /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, CHI.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
  /*IF !deletechuFlg*/AND CHI.DELETE_FLG = /*deletechuFlg*/0/*END*/
ORDER BY CHI.CHIIKI_CD, CHI.SHOBUN_HOUHOU_CD
