SELECT
    TSD.TORIHIKISAKI_CD
FROM T_SEIKYUU_DETAIL AS TSD
JOIN T_NYUUKIN_ENTRY AS TNE
ON TSD.DENPYOU_SYSTEM_ID = TNE.SYSTEM_ID 
AND TSD.DENPYOU_SEQ = TNE.SEQ
AND TNE.NYUUKIN_NUMBER = /*nyuukinNumber*/
AND TNE.DELETE_FLG = 0
WHERE TSD.DELETE_FLG = 0
AND TSD.DENPYOU_SHURUI_CD = 10