SELECT NYUUKIN_NUMBER
FROM T_NYUUKIN_ENTRY
WHERE NYUUKIN_NUMBER = (
SELECT MAX(NYUUKIN_NUMBER) 
FROM T_NYUUKIN_ENTRY 
WHERE DELETE_FLG = 0 
 /*IF kyotenCd != ''*/AND (KYOTEN_CD = /*kyotenCd*/ OR /*kyotenCd*/ = 99)/*END*/
AND TOK_INPUT_KBN = 0/*IF nyuukinNumber != ''*/ 
AND NYUUKIN_NUMBER < /*nyuukinNumber*/0/*END*/)
AND DELETE_FLG = 0