SELECT 
    NK.*
FROM 
    dbo.M_NYUUSHUKKIN_KBN NK
/*BEGIN*/WHERE
 /*IF !data.NYUUSHUKKIN_KBN_CD.IsNull*/ NK.NYUUSHUKKIN_KBN_CD = + /*data.NYUUSHUKKIN_KBN_CD*/'01'/*END*/
 /*IF data.NYUUSHUKKIN_KBN_NAME != null*/AND NK.NYUUSHUKKIN_KBN_NAME LIKE '%' + /*data.NYUUSHUKKIN_KBN_NAME*/ + '%'/*END*/
 /*IF data.NYUUSHUKKIN_KBN_BIKOU != null*/AND NK.NYUUSHUKKIN_KBN_BIKOU LIKE '%' + /*data.NYUUSHUKKIN_KBN_BIKOU*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null*/AND NK.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, NK.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
 /*IF data.CREATE_USER != null*/AND NK.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, NK.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
/*END*/
ORDER BY NK.NYUUSHUKKIN_KBN_CD
