SELECT *
FROM T_UKETSUKE_SK_ENTRY
where
	(UNTENSHA_CD = /*data.UNTENSHA_CD*/
	OR HOJOIN_CD = /*data.UNTENSHA_CD*/)
	AND CONVERT(CHAR(7), SAGYOU_DATE, 120) = CONVERT(CHAR(7), /*data.SAGYOU_DATE*/, 120)
	AND DELETE_FLG = 0