SELECT
 MT.TORIHIKISAKI_CD,
 MTS.SHIMEBI1 
FROM
 M_TORIHIKISAKI AS MT
JOIN
 M_TORIHIKISAKI_SEIKYUU AS MTS
ON
 MT.TORIHIKISAKI_CD = MTS.TORIHIKISAKI_CD
WHERE
 MT.TORIHIKISAKI_CD = /*torihikisakiCd*/'000001'
AND MTS.SHIMEBI1 = /*shimebi*/10