UPDATE M_DENSHI_JIGYOUSHA SET
	GYOUSHA_CD = /*data.GYOUSHA_CD*/'000001',
	UPDATE_USER = /*data.UPDATE_USER*/'',
	UPDATE_DATE = /*data.UPDATE_DATE*/'',
	UPDATE_PC = /*data.UPDATE_PC*/''
 WHERE EDI_MEMBER_ID = /*data.EDI_MEMBER_ID*/'0000001'