SELECT 
M_HIKIAI_GYOUSHA.TORIHIKISAKI_CD, 
/* 20140722 ria EV005369 引合現場入力の業者検索ポップアップに取引先名が表示されていないものがある start*/
CASE M_HIKIAI_GYOUSHA.HIKIAI_TORIHIKISAKI_USE_FLG 
WHEN '0' THEN M_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU 
ELSE M_HIKIAI_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU 
END AS TORIHIKISAKI_NAME_RYAKU, 
/* 20140722 ria EV005369 引合現場入力の業者検索ポップアップに取引先名が表示されていないものがある end*/
M_HIKIAI_GYOUSHA.GYOUSHA_CD, 
M_HIKIAI_GYOUSHA.GYOUSHA_NAME_RYAKU, 
M_HIKIAI_GYOUSHA.GYOUSHA_FURIGANA,
M_HIKIAI_GYOUSHA.GYOUSHA_POST,  
M_TODOUFUKEN.TODOUFUKEN_NAME_RYAKU, 
M_HIKIAI_GYOUSHA.GYOUSHA_ADDRESS1, 
M_HIKIAI_GYOUSHA.GYOUSHA_TEL, 
M_HIKIAI_GYOUSHA.HIKIAI_TORIHIKISAKI_USE_FLG AS TORIHIKISAKI_HIKIAI_FLG, 
CONVERT(bit, '1') AS GYOUSHA_HIKIAI_FLG, 
M_HIKIAI_GYOUSHA.SHOKUCHI_KBN AS GYOUSHA_SHOKUCHI_KBN 
FROM M_HIKIAI_GYOUSHA 
/* 20140722 ria EV005369 引合現場入力の業者検索ポップアップに取引先名が表示されていないものがある start*/
LEFT JOIN M_HIKIAI_TORIHIKISAKI ON M_HIKIAI_GYOUSHA.TORIHIKISAKI_CD = M_HIKIAI_TORIHIKISAKI.TORIHIKISAKI_CD AND M_HIKIAI_GYOUSHA.HIKIAI_TORIHIKISAKI_USE_FLG = 1
LEFT JOIN M_TORIHIKISAKI ON M_HIKIAI_GYOUSHA.TORIHIKISAKI_CD = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_HIKIAI_GYOUSHA.HIKIAI_TORIHIKISAKI_USE_FLG = 0
/* 20140722 ria EV005369 引合現場入力の業者検索ポップアップに取引先名が表示されていないものがある end*/
LEFT JOIN M_TODOUFUKEN ON M_HIKIAI_GYOUSHA.GYOUSHA_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD 
AND M_TODOUFUKEN.DELETE_FLG = 0 