SELECT 
	 M_ZAIKO_HINMEI.ZAIKO_HINMEI_CD
	,M_ZAIKO_HINMEI.ZAIKO_HINMEI_RYAKU
	,M_ZAIKO_HIRITSU.ZAIKO_HIRITSU
	,M_ZAIKO_HINMEI.ZAIKO_BASE_TANKA
 FROM M_ZAIKO_HIRITSU
  INNER JOIN M_ZAIKO_HINMEI
     ON M_ZAIKO_HINMEI.ZAIKO_HINMEI_CD = M_ZAIKO_HIRITSU.ZAIKO_HINMEI_CD
    AND (M_ZAIKO_HINMEI.TEKIYOU_BEGIN <= GETDATE()
      OR M_ZAIKO_HINMEI.TEKIYOU_BEGIN IS NULL)
	AND (M_ZAIKO_HINMEI.TEKIYOU_END >= GETDATE()
      OR M_ZAIKO_HINMEI.TEKIYOU_END IS NULL)
    AND M_ZAIKO_HINMEI.DELETE_FLG = 0
 WHERE M_ZAIKO_HIRITSU.DENSHU_KBN_CD = /*data.DENSHU_KBN_CD*/
	AND M_ZAIKO_HIRITSU.HINMEI_CD = /*data.HINMEI_CD*/
	AND (M_ZAIKO_HIRITSU.TEKIYOU_BEGIN <= GETDATE()
      OR M_ZAIKO_HIRITSU.TEKIYOU_BEGIN IS NULL)
	AND (M_ZAIKO_HIRITSU.TEKIYOU_END >= GETDATE()
      OR M_ZAIKO_HIRITSU.TEKIYOU_END IS NULL)
    AND M_ZAIKO_HIRITSU.DELETE_FLG = 0
