SELECT	DISTINCT
		  T_HIRITU.ZAIKO_HINMEI_CD
		, T_HIRITU.ZAIKO_HIRITSU
		, T_HINMEI.ZAIKO_HINMEI_RYAKU
		, T_HINMEI.ZAIKO_UNIT_CD
		, T_UNIT.UNIT_NAME_RYAKU
FROM
		M_ZAIKO_HIRITSU	T_HIRITU
LEFT OUTER JOIN 
		M_ZAIKO_HINMEI	T_HINMEI
ON		T_HIRITU.ZAIKO_HINMEI_CD = T_HINMEI.ZAIKO_HINMEI_CD
LEFT OUTER JOIN
		M_UNIT			T_UNIT
ON		T_HINMEI.ZAIKO_UNIT_CD = T_UNIT.UNIT_CD

WHERE	T_HIRITU.HINMEI_CD = /*data.HinmeiCd*/
AND		T_HIRITU.ZAIKO_HINMEI_CD = /*data.ZaikoHinmeiCd*/
AND		T_HINMEI.DELETE_FLG = 0
AND		T_HIRITU.DELETE_FLG = 0

