SELECT 
MMT.DELETE_FLG,
MMT.MANIFEST_TEHAI_CD,
MMT.MANIFEST_TEHAI_NAME,
MMT.MANIFEST_TEHAI_NAME_RYAKU,
MMT.MANIFEST_TEHAI_BIKOU,
MMT.UPDATE_USER,
MMT.UPDATE_DATE,
MMT.CREATE_USER,
MMT.CREATE_DATE,
MMT.UPDATE_PC,
MMT.CREATE_PC,
MMT.TIME_STAMP
FROM 
dbo.M_MANIFEST_TEHAI MMT
/*BEGIN*/WHERE
/*IF !data.MANIFEST_TEHAI_CD.IsNull*/CAST(MMT.MANIFEST_TEHAI_CD AS varchar(5)) LIKE '%' + CAST(/*data.MANIFEST_TEHAI_CD*/0 AS varchar(5)) + '%'/*END*/
/*IF data.MANIFEST_TEHAI_NAME != null*/AND MMT.MANIFEST_TEHAI_NAME LIKE '%' +  /*data.MANIFEST_TEHAI_NAME*/ + '%'/*END*/
/*IF data.MANIFEST_TEHAI_NAME_RYAKU != null*/AND MMT.MANIFEST_TEHAI_NAME_RYAKU LIKE '%' +  /*data.MANIFEST_TEHAI_NAME_RYAKU*/ + '%'/*END*/
/*IF data.MANIFEST_TEHAI_BIKOU != null*/AND MMT.MANIFEST_TEHAI_BIKOU LIKE '%' +  /*data.MANIFEST_TEHAI_BIKOU*/ + '%'/*END*/
/*IF data.CREATE_USER != null*/AND MMT.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, MMT.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
/*IF data.UPDATE_USER != null*/AND MMT.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, MMT.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*IF !deletechuFlg*/AND MMT.DELETE_FLG = 0/*END*/
/*END*/
ORDER BY MMT.MANIFEST_TEHAI_CD
