//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shougun.Core.Master.KobetsuHimeiTankaUpdate.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TORIHIKISAKI_CD_TEXT
        {
            get
            {
                return ((string)(this["TORIHIKISAKI_CD_TEXT"]));
            }
            set
            {
                this["TORIHIKISAKI_CD_TEXT"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GYOUSHA_CD_TEXT
        {
            get
            {
                return ((string)(this["GYOUSHA_CD_TEXT"]));
            }
            set
            {
                this["GYOUSHA_CD_TEXT"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_CD_TEXT
        {
            get
            {
                return ((string)(this["GENBA_CD_TEXT"]));
            }
            set
            {
                this["GENBA_CD_TEXT"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TORIHIKISAKI_NAME_RYAKU_TEXT
        {
            get
            {
                return ((string)(this["TORIHIKISAKI_NAME_RYAKU_TEXT"]));
            }
            set
            {
                this["TORIHIKISAKI_NAME_RYAKU_TEXT"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GYOUSHA_NAME_RYAKU_TEXT
        {
            get
            {
                return ((string)(this["GYOUSHA_NAME_RYAKU_TEXT"]));
            }
            set
            {
                this["GYOUSHA_NAME_RYAKU_TEXT"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_NAME_RYAKU_TEXT
        {
            get
            {
                return ((string)(this["GENBA_NAME_RYAKU_TEXT"]));
            }
            set
            {
                this["GENBA_NAME_RYAKU_TEXT"] = value;
            }
        }
    }
}
