SELECT
ALLT.KOUFU_DATE
, ALLT.MANI_HENSOUSAKI_CD_NAME
, ALLT.MANI_HENSOUSAKI
--, ALLT.HST_GYOUSHA_CD
--, ALLT.HST_GENBA_CD
--, ALLT.HAIKI_KBN_CD
, SUM(ALLT.M_SEND_A)  AS   M_SEND_A
, SUM(ALLT.M_SEND_B1) AS M_SEND_B1
, SUM(ALLT. M_SEND_B2) AS M_SEND_B2
, SUM(ALLT. M_SEND_B4) AS M_SEND_B4
, SUM(ALLT. M_SEND_B6) AS M_SEND_B6
, SUM(ALLT.M_SEND_C1) AS M_SEND_C1
,SUM(ALLT. M_SEND_C2) AS M_SEND_C2
, SUM(ALLT.M_SEND_D) AS M_SEND_D
, SUM(ALLT.M_SEND_E) AS M_SEND_E
FROM
(
SELECT
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
,CONVERT(CHAR (10), SUMNUY.SEND_A, 111) AS KOUFU_DATE
, COUNT(SUMNUY.SEND_A) AS M_SEND_A
, 0 AS M_SEND_B1
, 0 AS M_SEND_B2
, 0 AS M_SEND_B4
, 0 AS M_SEND_B6
, 0 AS M_SEND_C1
, 0 AS M_SEND_C2
, 0 AS M_SEND_D
, 0 AS M_SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'') + ' ' + ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END AS MANI_HENSOUSAKI_CD_NAME
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI
FROM
(
SELECT
TME.HST_GYOUSHA_CD
, TME.HST_GENBA_CD
, TME.HAIKI_KBN_CD
, TMR.SEND_A
, TMR.SEND_B1
, TMR.SEND_B2
, TMR.SEND_B4
, TMR.SEND_B6
, TMR.SEND_C1
, TMR.SEND_C2
, TMR.SEND_D
, TMR.SEND_E
, TME.KYOTEN_CD
FROM
T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID
WHERE 	TME.DELETE_FLG = 0 AND TMR.DELETE_FLG = 0 AND TME.FIRST_MANIFEST_KBN=0
) SUMNUY
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1 )
ON SUMNUY.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND SUMNUY.HST_GENBA_CD = M_GENBA.GENBA_CD	

WHERE
SUMNUY.SEND_A IS NOT NULL
AND  2=2
/*IF data.TORIHIKISAKI_CD_FROM != null && data.TORIHIKISAKI_CD_FROM != '' && data.TORIHIKISAKI_CD_TO != null && data.TORIHIKISAKI_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A >= /*data.TORIHIKISAKI_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A <= /*data.TORIHIKISAKI_CD_TO*/
/*END*/

/*IF data.GYOUSHA_CD_FROM != null && data.GYOUSHA_CD_FROM != '' && data.GYOUSHA_CD_TO != null && data.GYOUSHA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A >= /*data.GYOUSHA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A <= /*data.GYOUSHA_CD_TO*/
/*END*/

/*IF data.GENBA_CD_FROM != null && data.GENBA_CD_FROM != '' && data.GENBA_CD_TO != null && data.GENBA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A >= /*data.GENBA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A <= /*data.GENBA_CD_TO*/
/*END*/

/*IF data.KYOTEN_CD != null && data.KYOTEN_CD != ''*/
AND SUMNUY.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/

GROUP BY
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
, CONVERT(CHAR (10), SUMNUY.SEND_A, 111)
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'') END
END

/*IF data.INSATU_KBN == '1'*/
UNION ALL

SELECT
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
,CONVERT(CHAR (10), SUMNUY.SEND_B1, 111) AS KOUFU_DATE
, 0 AS M_SEND_A
, COUNT(SUMNUY.SEND_B1) AS M_SEND_B1
, 0 AS M_SEND_B2
, 0 AS M_SEND_B4
, 0 AS M_SEND_B6
, 0 AS M_SEND_C1
, 0 AS M_SEND_C2
, 0 AS M_SEND_D
, 0 AS M_SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'') + ' ' + ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END AS MANI_HENSOUSAKI_CD_NAME
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI

FROM
(
SELECT
TME.HST_GYOUSHA_CD
, TME.HST_GENBA_CD
, TME.HAIKI_KBN_CD
, TMR.SEND_A
, TMR.SEND_B1
, TMR.SEND_B2
, TMR.SEND_B4
, TMR.SEND_B6
, TMR.SEND_C1
, TMR.SEND_C2
, TMR.SEND_D
, TMR.SEND_E
, TME.KYOTEN_CD
FROM
T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0
WHERE 	TME.DELETE_FLG = 0 AND TMR.DELETE_FLG = 0 AND TME.FIRST_MANIFEST_KBN=0
) SUMNUY
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1 )
ON SUMNUY.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND SUMNUY.HST_GENBA_CD = M_GENBA.GENBA_CD	

WHERE
SUMNUY.SEND_B1 IS NOT NULL
AND  2=2
/*IF data.TORIHIKISAKI_CD_FROM != null && data.TORIHIKISAKI_CD_FROM != '' && data.TORIHIKISAKI_CD_TO != null && data.TORIHIKISAKI_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 >= /*data.TORIHIKISAKI_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 <= /*data.TORIHIKISAKI_CD_TO*/
/*END*/

/*IF data.GYOUSHA_CD_FROM != null && data.GYOUSHA_CD_FROM != '' && data.GYOUSHA_CD_TO != null && data.GYOUSHA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 >= /*data.GYOUSHA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 <= /*data.GYOUSHA_CD_TO*/
/*END*/

/*IF data.GENBA_CD_FROM != null && data.GENBA_CD_FROM != '' && data.GENBA_CD_TO != null && data.GENBA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 >= /*data.GENBA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 <= /*data.GENBA_CD_TO*/
/*END*/

/*IF data.KYOTEN_CD != null && data.KYOTEN_CD != ''*/
AND SUMNUY.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/

GROUP BY
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
, CONVERT(CHAR (10), SUMNUY.SEND_B1, 111)
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'') END
END
/*END*/

UNION ALL

SELECT
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
,CONVERT(CHAR (10), SUMNUY.SEND_B2, 111) AS KOUFU_DATE
, 0 AS M_SEND_A
,0 AS M_SEND_B1
,  COUNT(SUMNUY.SEND_B2) AS M_SEND_B2
, 0 AS M_SEND_B4
, 0 AS M_SEND_B6
, 0 AS M_SEND_C1
, 0 AS M_SEND_C2
, 0 AS M_SEND_D
, 0 AS M_SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'') + ' ' + ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END AS MANI_HENSOUSAKI_CD_NAME
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI

FROM
(
SELECT
TME.HST_GYOUSHA_CD
, TME.HST_GENBA_CD
, TME.HAIKI_KBN_CD
, TMR.SEND_A
, TMR.SEND_B1
, TMR.SEND_B2
, TMR.SEND_B4
, TMR.SEND_B6
, TMR.SEND_C1
, TMR.SEND_C2
, TMR.SEND_D
, TMR.SEND_E
, TME.KYOTEN_CD
FROM
T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0
WHERE 	TME.DELETE_FLG = 0 AND TMR.DELETE_FLG = 0 AND TME.FIRST_MANIFEST_KBN=0
) SUMNUY
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1)
ON SUMNUY.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND SUMNUY.HST_GENBA_CD = M_GENBA.GENBA_CD	

WHERE
SUMNUY.SEND_B2 IS NOT NULL
AND  2=2
/*IF data.TORIHIKISAKI_CD_FROM != null && data.TORIHIKISAKI_CD_FROM != '' && data.TORIHIKISAKI_CD_TO != null && data.TORIHIKISAKI_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 >= /*data.TORIHIKISAKI_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 <= /*data.TORIHIKISAKI_CD_TO*/
/*END*/

/*IF data.GYOUSHA_CD_FROM != null && data.GYOUSHA_CD_FROM != '' && data.GYOUSHA_CD_TO != null && data.GYOUSHA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 >= /*data.GYOUSHA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 <= /*data.GYOUSHA_CD_TO*/
/*END*/

/*IF data.GENBA_CD_FROM != null && data.GENBA_CD_FROM != '' && data.GENBA_CD_TO != null && data.GENBA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 >= /*data.GENBA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 <= /*data.GENBA_CD_TO*/
/*END*/

/*IF data.KYOTEN_CD != null && data.KYOTEN_CD != ''*/
AND SUMNUY.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/

GROUP BY
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
, CONVERT(CHAR (10), SUMNUY.SEND_B2, 111)
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'') END
END
/*IF data.INSATU_KBN == '2'*/

UNION ALL

SELECT
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
,CONVERT(CHAR (10), SUMNUY.SEND_B4, 111) AS KOUFU_DATE
, 0 AS M_SEND_A
,0 AS M_SEND_B1
,0 AS M_SEND_B2
, COUNT(SUMNUY.SEND_B4) AS M_SEND_B4
, 0 AS M_SEND_B6
, 0 AS M_SEND_C1
, 0 AS M_SEND_C2
, 0 AS M_SEND_D
, 0 AS M_SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'') + ' ' + ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END AS MANI_HENSOUSAKI_CD_NAME
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI

FROM
(
SELECT
TME.HST_GYOUSHA_CD
, TME.HST_GENBA_CD
, TME.HAIKI_KBN_CD
, TMR.SEND_A
, TMR.SEND_B1
, TMR.SEND_B2
, TMR.SEND_B4
, TMR.SEND_B6
, TMR.SEND_C1
, TMR.SEND_C2
, TMR.SEND_D
, TMR.SEND_E
, TME.KYOTEN_CD
FROM
T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0
WHERE 	TME.DELETE_FLG = 0 AND TMR.DELETE_FLG = 0 AND TME.FIRST_MANIFEST_KBN=0
) SUMNUY
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1)
ON SUMNUY.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND SUMNUY.HST_GENBA_CD = M_GENBA.GENBA_CD	

WHERE
SUMNUY.SEND_B4 IS NOT NULL
AND  2=2
/*IF data.TORIHIKISAKI_CD_FROM != null && data.TORIHIKISAKI_CD_FROM != '' && data.TORIHIKISAKI_CD_TO != null && data.TORIHIKISAKI_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 >= /*data.TORIHIKISAKI_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 <= /*data.TORIHIKISAKI_CD_TO*/
/*END*/

/*IF data.GYOUSHA_CD_FROM != null && data.GYOUSHA_CD_FROM != '' && data.GYOUSHA_CD_TO != null && data.GYOUSHA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 >= /*data.GYOUSHA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 <= /*data.GYOUSHA_CD_TO*/
/*END*/

/*IF data.GENBA_CD_FROM != null && data.GENBA_CD_FROM != '' && data.GENBA_CD_TO != null && data.GENBA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 >= /*data.GENBA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 <= /*data.GENBA_CD_TO*/
/*END*/

/*IF data.KYOTEN_CD != null && data.KYOTEN_CD != ''*/
AND SUMNUY.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/

GROUP BY
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
, CONVERT(CHAR (10), SUMNUY.SEND_B4, 111)
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'') END
END

UNION ALL

SELECT
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
,CONVERT(CHAR (10), SUMNUY.SEND_B6, 111) AS KOUFU_DATE
, 0 AS M_SEND_A
,0 AS M_SEND_B1
,0 AS M_SEND_B2
, 0 AS M_SEND_B4
, COUNT(SUMNUY.SEND_B6) AS M_SEND_B6
, 0 AS M_SEND_C1
, 0 AS M_SEND_C2
, 0 AS M_SEND_D
, 0 AS M_SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'') + ' ' + ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END AS MANI_HENSOUSAKI_CD_NAME
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI

FROM
(
SELECT
TME.HST_GYOUSHA_CD
, TME.HST_GENBA_CD
, TME.HAIKI_KBN_CD
, TMR.SEND_A
, TMR.SEND_B1
, TMR.SEND_B2
, TMR.SEND_B4
, TMR.SEND_B6
, TMR.SEND_C1
, TMR.SEND_C2
, TMR.SEND_D
, TMR.SEND_E
, TME.KYOTEN_CD
FROM
T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0
WHERE 	TME.DELETE_FLG = 0 AND TMR.DELETE_FLG = 0 AND TME.FIRST_MANIFEST_KBN=0
) SUMNUY
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1)
ON SUMNUY.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND SUMNUY.HST_GENBA_CD = M_GENBA.GENBA_CD	

WHERE
SUMNUY.SEND_B6 IS NOT NULL
AND  2=2

/*IF data.TORIHIKISAKI_CD_FROM != null && data.TORIHIKISAKI_CD_FROM != '' && data.TORIHIKISAKI_CD_TO != null && data.TORIHIKISAKI_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 >= /*data.TORIHIKISAKI_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 <= /*data.TORIHIKISAKI_CD_TO*/
/*END*/

/*IF data.GYOUSHA_CD_FROM != null && data.GYOUSHA_CD_FROM != '' && data.GYOUSHA_CD_TO != null && data.GYOUSHA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 >= /*data.GYOUSHA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 <= /*data.GYOUSHA_CD_TO*/
/*END*/

/*IF data.GENBA_CD_FROM != null && data.GENBA_CD_FROM != '' && data.GENBA_CD_TO != null && data.GENBA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 >= /*data.GENBA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 <= /*data.GENBA_CD_TO*/
/*END*/

/*IF data.KYOTEN_CD != null && data.KYOTEN_CD != ''*/
AND SUMNUY.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/

GROUP BY
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
, CONVERT(CHAR (10), SUMNUY.SEND_B6, 111)
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'') END
END
/*END*/

UNION ALL

SELECT
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
,CONVERT(CHAR (10), SUMNUY.SEND_C1, 111) AS KOUFU_DATE
, 0 AS M_SEND_A
,0 AS M_SEND_B1
,0 AS M_SEND_B2
, 0 AS M_SEND_B4
, 0 AS M_SEND_B6
, COUNT(SUMNUY.SEND_C1) AS M_SEND_C1
, 0 AS M_SEND_C2
, 0 AS M_SEND_D
, 0 AS M_SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'') + ' ' + ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END AS MANI_HENSOUSAKI_CD_NAME
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI

FROM
(
SELECT
TME.HST_GYOUSHA_CD
, TME.HST_GENBA_CD
, TME.HAIKI_KBN_CD
, TMR.SEND_A
, TMR.SEND_B1
, TMR.SEND_B2
, TMR.SEND_B4
, TMR.SEND_B6
, TMR.SEND_C1
, TMR.SEND_C2
, TMR.SEND_D
, TMR.SEND_E
, TME.KYOTEN_CD
FROM
T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0
WHERE 	TME.DELETE_FLG = 0 AND TMR.DELETE_FLG = 0 AND TME.FIRST_MANIFEST_KBN=0
) SUMNUY
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1)
ON SUMNUY.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND SUMNUY.HST_GENBA_CD = M_GENBA.GENBA_CD	

WHERE
SUMNUY.SEND_C1 IS NOT NULL
AND  2=2

/*IF data.TORIHIKISAKI_CD_FROM != null && data.TORIHIKISAKI_CD_FROM != '' && data.TORIHIKISAKI_CD_TO != null && data.TORIHIKISAKI_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 >= /*data.TORIHIKISAKI_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 <= /*data.TORIHIKISAKI_CD_TO*/
/*END*/

/*IF data.GYOUSHA_CD_FROM != null && data.GYOUSHA_CD_FROM != '' && data.GYOUSHA_CD_TO != null && data.GYOUSHA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 >= /*data.GYOUSHA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 <= /*data.GYOUSHA_CD_TO*/
/*END*/

/*IF data.GENBA_CD_FROM != null && data.GENBA_CD_FROM != '' && data.GENBA_CD_TO != null && data.GENBA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 >= /*data.GENBA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 <= /*data.GENBA_CD_TO*/
/*END*/

/*IF data.KYOTEN_CD != null && data.KYOTEN_CD != ''*/
AND SUMNUY.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/

GROUP BY
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
, CONVERT(CHAR (10), SUMNUY.SEND_C1, 111)
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'') END
END

UNION ALL

SELECT
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
,CONVERT(CHAR (10), SUMNUY.SEND_C2, 111) AS KOUFU_DATE
, 0 AS M_SEND_A
,0 AS M_SEND_B1
,0 AS M_SEND_B2
, 0 AS M_SEND_B4
, 0 AS M_SEND_B6
,0 AS M_SEND_C1
, COUNT(SUMNUY.SEND_C2) AS M_SEND_C2
, 0 AS M_SEND_D
, 0 AS M_SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'') + ' ' + ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END AS MANI_HENSOUSAKI_CD_NAME
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI

FROM
(
SELECT
TME.HST_GYOUSHA_CD
, TME.HST_GENBA_CD
, TME.HAIKI_KBN_CD
, TMR.SEND_A
, TMR.SEND_B1
, TMR.SEND_B2
, TMR.SEND_B4
, TMR.SEND_B6
, TMR.SEND_C1
, TMR.SEND_C2
, TMR.SEND_D
, TMR.SEND_E
, TME.KYOTEN_CD
FROM
T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0
WHERE 	TME.DELETE_FLG = 0 AND TMR.DELETE_FLG = 0 AND TME.FIRST_MANIFEST_KBN=0
) SUMNUY
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1)
ON SUMNUY.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND SUMNUY.HST_GENBA_CD = M_GENBA.GENBA_CD	

WHERE
SUMNUY.SEND_C2 IS NOT NULL
AND  2=2

/*IF data.TORIHIKISAKI_CD_FROM != null && data.TORIHIKISAKI_CD_FROM != '' && data.TORIHIKISAKI_CD_TO != null && data.TORIHIKISAKI_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 >= /*data.TORIHIKISAKI_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 <= /*data.TORIHIKISAKI_CD_TO*/
/*END*/

/*IF data.GYOUSHA_CD_FROM != null && data.GYOUSHA_CD_FROM != '' && data.GYOUSHA_CD_TO != null && data.GYOUSHA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 >= /*data.GYOUSHA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 <= /*data.GYOUSHA_CD_TO*/
/*END*/

/*IF data.GENBA_CD_FROM != null && data.GENBA_CD_FROM != '' && data.GENBA_CD_TO != null && data.GENBA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 >= /*data.GENBA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 <= /*data.GENBA_CD_TO*/
/*END*/

/*IF data.KYOTEN_CD != null && data.KYOTEN_CD != ''*/
AND SUMNUY.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/

GROUP BY
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
, CONVERT(CHAR (10), SUMNUY.SEND_C2, 111)
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'') END
END

UNION ALL

SELECT
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
,CONVERT(CHAR (10), SUMNUY.SEND_D, 111) AS KOUFU_DATE
, 0 AS M_SEND_A
,0 AS M_SEND_B1
,0 AS M_SEND_B2
, 0 AS M_SEND_B4
, 0 AS M_SEND_B6
,0 AS M_SEND_C1
, 0 AS M_SEND_C2
, COUNT(SUMNUY.SEND_D) AS M_SEND_D
, 0 AS M_SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'') + ' ' + ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END AS MANI_HENSOUSAKI_CD_NAME
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI

FROM
(
SELECT
TME.HST_GYOUSHA_CD
, TME.HST_GENBA_CD
, TME.HAIKI_KBN_CD
, TMR.SEND_A
, TMR.SEND_B1
, TMR.SEND_B2
, TMR.SEND_B4
, TMR.SEND_B6
, TMR.SEND_C1
, TMR.SEND_C2
, TMR.SEND_D
, TMR.SEND_E
, TME.KYOTEN_CD
FROM
T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0
WHERE 	TME.DELETE_FLG = 0 AND TMR.DELETE_FLG = 0 AND TME.FIRST_MANIFEST_KBN=0
) SUMNUY
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1)
ON SUMNUY.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND SUMNUY.HST_GENBA_CD = M_GENBA.GENBA_CD	

WHERE
SUMNUY.SEND_D IS NOT NULL
AND  2=2

/*IF data.TORIHIKISAKI_CD_FROM != null && data.TORIHIKISAKI_CD_FROM != '' && data.TORIHIKISAKI_CD_TO != null && data.TORIHIKISAKI_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D >= /*data.TORIHIKISAKI_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D <= /*data.TORIHIKISAKI_CD_TO*/
/*END*/

/*IF data.GYOUSHA_CD_FROM != null && data.GYOUSHA_CD_FROM != '' && data.GYOUSHA_CD_TO != null && data.GYOUSHA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D >= /*data.GYOUSHA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D <= /*data.GYOUSHA_CD_TO*/
/*END*/

/*IF data.GENBA_CD_FROM != null && data.GENBA_CD_FROM != '' && data.GENBA_CD_TO != null && data.GENBA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D >= /*data.GENBA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D <= /*data.GENBA_CD_TO*/
/*END*/

/*IF data.KYOTEN_CD != null && data.KYOTEN_CD != ''*/
AND SUMNUY.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/

GROUP BY
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
, CONVERT(CHAR (10), SUMNUY.SEND_D, 111)
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'') END
END


UNION ALL

SELECT
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
,CONVERT(CHAR (10), SUMNUY.SEND_E, 111) AS KOUFU_DATE
, 0 AS M_SEND_A
,0 AS M_SEND_B1
,0 AS M_SEND_B2
, 0 AS M_SEND_B4
, 0 AS M_SEND_B6
,0 AS M_SEND_C1
, 0 AS M_SEND_C2
, 0 AS M_SEND_D
, COUNT(SUMNUY.SEND_E) AS M_SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'') + ' ' + ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END AS MANI_HENSOUSAKI_CD_NAME
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI

FROM
(
SELECT
TME.HST_GYOUSHA_CD
, TME.HST_GENBA_CD
, TME.HAIKI_KBN_CD
, TMR.SEND_A
, TMR.SEND_B1
, TMR.SEND_B2
, TMR.SEND_B4
, TMR.SEND_B6
, TMR.SEND_C1
, TMR.SEND_C2
, TMR.SEND_D
, TMR.SEND_E
, TME.KYOTEN_CD
FROM
T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0
WHERE 	TME.DELETE_FLG = 0 AND TMR.DELETE_FLG = 0 AND TME.FIRST_MANIFEST_KBN=0
) SUMNUY
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1)
ON SUMNUY.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND SUMNUY.HST_GENBA_CD = M_GENBA.GENBA_CD	

WHERE
SUMNUY.SEND_E IS NOT NULL
AND  2=2

/*IF data.TORIHIKISAKI_CD_FROM != null && data.TORIHIKISAKI_CD_FROM != '' && data.TORIHIKISAKI_CD_TO != null && data.TORIHIKISAKI_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E >= /*data.TORIHIKISAKI_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E <= /*data.TORIHIKISAKI_CD_TO*/
/*END*/

/*IF data.GYOUSHA_CD_FROM != null && data.GYOUSHA_CD_FROM != '' && data.GYOUSHA_CD_TO != null && data.GYOUSHA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E >= /*data.GYOUSHA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E <= /*data.GYOUSHA_CD_TO*/
/*END*/

/*IF data.GENBA_CD_FROM != null && data.GENBA_CD_FROM != '' && data.GENBA_CD_TO != null && data.GENBA_CD_TO != ''*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E >= /*data.GENBA_CD_FROM*/
AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E <= /*data.GENBA_CD_TO*/
/*END*/

/*IF data.KYOTEN_CD != null && data.KYOTEN_CD != ''*/
AND SUMNUY.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/

GROUP BY
SUMNUY.HST_GYOUSHA_CD
, SUMNUY.HST_GENBA_CD
, SUMNUY.HAIKI_KBN_CD
, CONVERT(CHAR (10), SUMNUY.SEND_E, 111)
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E <> '' THEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E+',返送先現場'
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E <> '' THEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E+',返送先業者'
WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E <> '' THEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E+',返送先取引先'
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'')
END
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'')
ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2,'') END
END

)
AS ALLT
WHERE (1=1)
/*IF data.RET_DATE_FROM != null && data.RET_DATE_FROM != '' && data.RET_DATE_TO != null && data.RET_DATE_TO != ''*/
AND ( ALLT.KOUFU_DATE >= /*data.RET_DATE_FROM*/ AND ALLT.KOUFU_DATE <= /*data.RET_DATE_TO*/)
/*END*/
/*IF data.HST_GYOUSHA_CD_FROM != null && data.HST_GYOUSHA_CD_FROM != '' && data.HST_GYOUSHA_CD_TO != null && data.HST_GYOUSHA_CD_TO != ''*/
AND ALLT.HST_GYOUSHA_CD >= /*data.HST_GYOUSHA_CD_FROM*/
AND ALLT.HST_GYOUSHA_CD <= /*data.HST_GYOUSHA_CD_TO*/
/*END*/

/*IF data.HST_GENBA_CD_FROM != null && data.HST_GENBA_CD_FROM != '' && data.HST_GENBA_CD_TO != null && data.HST_GENBA_CD_TO != ''*/
AND ALLT.HST_GENBA_CD >= /*data.HST_GENBA_CD_FROM*/
AND ALLT.HST_GENBA_CD <= /*data.HST_GENBA_CD_TO*/
/*END*/

/*IF data.INSATU_KBN == '1'*/AND  ( ALLT.HAIKI_KBN_CD = 1 OR ALLT.HAIKI_KBN_CD = 2)/*END*/                 -- ※印刷区分		印刷区分 = 1の場合	マニフェスト.廃棄物区分CD IN 1 OR 2
/*IF data.INSATU_KBN == '2'*/AND  ALLT.HAIKI_KBN_CD = 3 /*END*/                                           -- ※印刷区分		印刷区分 = 2の場合	マニフェスト.廃棄物区分CD 3

GROUP BY
ALLT.KOUFU_DATE
--, ALLT.HST_GYOUSHA_CD
--, ALLT.HST_GENBA_CD
--, ALLT.HAIKI_KBN_CD
, ALLT.MANI_HENSOUSAKI_CD_NAME
, ALLT.MANI_HENSOUSAKI
