SELECT DISTINCT
SUMMEY.SYSTEM_ID
,SUMMEY.SEQ
,(CONVERT(nvarchar,SUMMEY.KOUFU_DATE,111)) AS KOUFU_DATE
,SUMMEY.MANIFEST_ID
,SUMMEY.HST_GYOUSHA_CD
,(SELECT TOP 1 GYOUSHA_NAME_RYAKU FROM M_GYOUSHA AS MG1  WHERE MG1.GYOUSHA_CD = SUMMEY.HST_GYOUSHA_CD) HST_GYOUSHA_NAME_RYAKU
,(SELECT TOP 1 GYOUSHA_NAME1 FROM M_GYOUSHA AS MG2  WHERE MG2.GYOUSHA_CD = SUMMEY.HST_GYOUSHA_CD) HST_GYOUSHA_NAME1
,(SELECT TOP 1 GYOUSHA_NAME2 FROM M_GYOUSHA AS MG3  WHERE MG3.GYOUSHA_CD = SUMMEY.HST_GYOUSHA_CD) HST_GYOUSHA_NAME2
,SUMMEY.HST_GENBA_CD
,SUMMEY.HST_GENBA_NAME_RYAKU
,SUMMEY.HST_GENBA_NAME1
,SUMMEY.HST_GENBA_NAME2
,SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD
,SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD
,SUMMEY.MANI_HENSOUSAKI_GENBA_CD
,(SELECT TOP 1 TORIHIKISAKI_NAME_RYAKU FROM M_TORIHIKISAKI   WHERE M_TORIHIKISAKI.TORIHIKISAKI_CD = SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD) MANI_HENSOUSAKI_TORIHIKISAKI_NAME_RYAKU
,(SELECT TOP 1 GYOUSHA_NAME_RYAKU FROM M_GYOUSHA AS MG1  WHERE MG1.GYOUSHA_CD = SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD) MANI_HENSOUSAKI_GYOUSHA_NAME_RYAKU
,(SELECT TOP 1 GENBA_NAME_RYAKU FROM M_GENBA AS M2  WHERE M2.GYOUSHA_CD = SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD AND M2.GENBA_CD = SUMMEY.MANI_HENSOUSAKI_GENBA_CD) MANI_HENSOUSAKI_GENBA_NAME_RYAKU
,CASE
WHEN SUMMEY.MANI_HENSOUSAKI_GENBA_CD IS NOT NULL AND SUMMEY.MANI_HENSOUSAKI_GENBA_CD <>''  THEN '3'
WHEN SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD IS NOT NULL  AND SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD <>'' THEN '2'
WHEN SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD IS NOT NULL AND SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD <>''  THEN '1'
ELSE '3'
END AS MANI_HENSOUSAKI_NAME_KBN  -- 1:取引先,2:業者,3:現場
,CASE
WHEN SUMMEY.MANI_HENSOUSAKI_GENBA_CD IS NOT NULL AND SUMMEY.MANI_HENSOUSAKI_GENBA_CD <>'' THEN SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD+SUMMEY.MANI_HENSOUSAKI_GENBA_CD+SUMMEY.MANI_HENSOUSAKI_NAME1
WHEN SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD IS NOT NULL  AND SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD <>'' THEN SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD+SUMMEY.MANI_HENSOUSAKI_NAME1
WHEN SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD IS NOT NULL AND SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD <>''  THEN SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD+SUMMEY.MANI_HENSOUSAKI_NAME1
ELSE SUMMEY.MANI_HENSOUSAKI_NAME1
END AS MANI_HENSOUSAKI_NAME
,CASE
WHEN SUMMEY.MANI_HENSOUSAKI_GENBA_CD IS NOT NULL AND SUMMEY.MANI_HENSOUSAKI_GENBA_CD <>'' THEN SUMMEY.MANI_HENSOUSAKI_GENBA_CD+SUMMEY.MANI_HENSOUSAKI_NAME1_REPORT
WHEN SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD IS NOT NULL  AND SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD <>'' THEN SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD+SUMMEY.MANI_HENSOUSAKI_NAME1_REPORT
WHEN SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD IS NOT NULL AND SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD <>''  THEN SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD+SUMMEY.MANI_HENSOUSAKI_NAME1_REPORT
ELSE SUMMEY.MANI_HENSOUSAKI_NAME1_REPORT
END AS MANI_HENSOUSAKI_NAME_REPORT
--,SUMMEY.MANI_HENSOUSAKI_NAME AS MANI_HENSOUSAKI_NAME
,CASE
WHEN SUMMEY.MANI_HENSOUSAKI_GENBA_CD IS NOT NULL AND SUMMEY.MANI_HENSOUSAKI_GENBA_CD <>'' THEN 'AAAAAAAAAAAA'+SUMMEY.MANI_HENSOUSAKI_GENBA_CD
WHEN SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD IS NOT NULL AND SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD <>'' THEN 'AAAAAA'+SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD
WHEN SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD	IS NOT NULL AND SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD <>'' THEN SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD
ELSE 'AAAAAAAAAAAAAAAAAA'
END AS MANI_HENSOUSAKI_SORT
,SUMMEY.HAIKI_KBN_CD
,'' AS HAIKI_SHURUI_NAME
,SUMMEY.SEND_A
,SUMMEY.SEND_B1
,SUMMEY.SEND_B2
,SUMMEY.SEND_B4
,SUMMEY.SEND_B6
,SUMMEY.SEND_C1
,SUMMEY.SEND_C2
,SUMMEY.SEND_D
,SUMMEY.SEND_E
,SUMMEY.MANI_HENSOUSAKI_POST
,SUMMEY.MANI_HENSOUSAKI_ADDRESS1
,SUMMEY.MANI_HENSOUSAKI_ADDRESS2
,SUMMEY.MANI_HENSOUSAKI_NAME1
,SUMMEY.MANI_HENSOUSAKI_NAME1_REPORT
,SUMMEY.MANI_HENSOUSAKI_KEISHOU1
,SUMMEY.MANI_HENSOUSAKI_NAME2
,SUMMEY.MANI_HENSOUSAKI_KEISHOU2
,SUMMEY.MANI_HENSOUSAKI_BUSHO
,SUMMEY.MANI_HENSOUSAKI_TANTOU
FROM
(
-- （A票返送先）
SELECT
TME.SYSTEM_ID
,TME.SEQ
,TME.KOUFU_DATE
,TME.DELETE_FLG
,TME.KOUFU_KBN
,TME.MANIFEST_ID
,TME.HST_GYOUSHA_CD
,TME.HST_GENBA_CD
,M_GENBA.GENBA_NAME_RYAKU AS  HST_GENBA_NAME_RYAKU
,M_GENBA.GENBA_NAME1 AS  HST_GENBA_NAME1
,M_GENBA.GENBA_NAME2 AS  HST_GENBA_NAME2
,M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A	AS MANI_HENSOUSAKI_TORIHIKISAKI_CD
,M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A AS MANI_HENSOUSAKI_GYOUSHA_CD
,M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A   AS MANI_HENSOUSAKI_GENBA_CD
--,'A票'  MANI_HENSOUSAKI_NAME
,TME.HAIKI_KBN_CD
,CASE WHEN M_GENBA.MANI_HENSOUSAKI_USE_A = 2 THEN '-' ELSE (CONVERT(nvarchar,TMR.SEND_A,111)) END AS SEND_A
,'' AS SEND_B1
,'' AS SEND_B2
,'' AS SEND_B4
,'' AS SEND_B6
,'' AS SEND_C1
,'' AS SEND_C2
,'' AS SEND_D
,'' AS SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A <> '' THEN M_GENBA2.MANI_HENSOUSAKI_POST
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_POST
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_POST ELSE M_GENBA.MANI_HENSOUSAKI_POST END
END AS MANI_HENSOUSAKI_POST
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS1 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS1 END
END AS MANI_HENSOUSAKI_ADDRESS1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS2 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS2 END
END AS MANI_HENSOUSAKI_ADDRESS2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'') ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI_NAME1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1 ELSE M_GENBA.MANI_HENSOUSAKI_NAME1 END
END AS MANI_HENSOUSAKI_NAME1_REPORT
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU1 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU1 END
END AS MANI_HENSOUSAKI_KEISHOU1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2 ELSE M_GENBA.MANI_HENSOUSAKI_NAME2 END
END AS MANI_HENSOUSAKI_NAME2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU2 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU2 END 
END AS MANI_HENSOUSAKI_KEISHOU2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A <> '' THEN M_GENBA2.MANI_HENSOUSAKI_BUSHO
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_BUSHO
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_BUSHO ELSE M_GENBA.MANI_HENSOUSAKI_BUSHO END 
END AS MANI_HENSOUSAKI_BUSHO
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A <> '' THEN M_GENBA2.MANI_HENSOUSAKI_TANTOU
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_TANTOU
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_TANTOU ELSE M_GENBA.MANI_HENSOUSAKI_TANTOU END 
END AS MANI_HENSOUSAKI_TANTOU,
TME.KYOTEN_CD


FROM	T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_A = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_A = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_A = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1 )
ON TME.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND TME.HST_GENBA_CD = M_GENBA.GENBA_CD	
--LEFT JOIN T_MANIFEST_DETAIL AS TMD ON TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0

WHERE
TMR.SEND_A IS NOT NULL
AND TME.FIRST_MANIFEST_KBN=0

/*IF data.INSATU_KBN == '1'*/
UNION

-- （B1票返送先）
SELECT
TME.SYSTEM_ID
,TME.SEQ
,TME.KOUFU_DATE
,TME.DELETE_FLG
,TME.KOUFU_KBN
,TME.MANIFEST_ID
,TME.HST_GYOUSHA_CD
,TME.HST_GENBA_CD
,M_GENBA.GENBA_NAME_RYAKU AS  HST_GENBA_NAME_RYAKU
,M_GENBA.GENBA_NAME1 AS  HST_GENBA_NAME1
,M_GENBA.GENBA_NAME2 AS  HST_GENBA_NAME2
,M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1	AS MANI_HENSOUSAKI_TORIHIKISAKI_CD
,M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 AS MANI_HENSOUSAKI_GYOUSHA_CD
,M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1   AS MANI_HENSOUSAKI_GENBA_CD
--,'B1票'  MANI_HENSOUSAKI_NAME
,TME.HAIKI_KBN_CD
,'' AS SEND_A
,CASE WHEN M_GENBA.MANI_HENSOUSAKI_USE_B1 = 2 THEN '-' ELSE (CONVERT(nvarchar,TMR.SEND_B1,111)) END AS SEND_B1
,'' AS SEND_B2
,'' AS SEND_B4
,'' AS SEND_B6
,'' AS SEND_C1
,'' AS SEND_C2
,'' AS SEND_D
,'' AS SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_POST
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_POST
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_POST ELSE M_GENBA.MANI_HENSOUSAKI_POST END
END AS MANI_HENSOUSAKI_POST
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS1 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS1 END
END AS MANI_HENSOUSAKI_ADDRESS1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS2 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS2 END
END AS MANI_HENSOUSAKI_ADDRESS2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'') ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI_NAME1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1 ELSE M_GENBA.MANI_HENSOUSAKI_NAME1 END
END AS MANI_HENSOUSAKI_NAME1_REPORT
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU1 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU1 END
END AS MANI_HENSOUSAKI_KEISHOU1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2 ELSE M_GENBA.MANI_HENSOUSAKI_NAME2 END
END AS MANI_HENSOUSAKI_NAME2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU2 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU2 END 
END AS MANI_HENSOUSAKI_KEISHOU2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_BUSHO
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_BUSHO
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_BUSHO ELSE M_GENBA.MANI_HENSOUSAKI_BUSHO END 
END AS MANI_HENSOUSAKI_BUSHO
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_TANTOU
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_TANTOU
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_TANTOU ELSE M_GENBA.MANI_HENSOUSAKI_TANTOU END 
END AS MANI_HENSOUSAKI_TANTOU,
TME.KYOTEN_CD

FROM	T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B1 = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B1 = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1 )
ON TME.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND TME.HST_GENBA_CD = M_GENBA.GENBA_CD	
--LEFT JOIN T_MANIFEST_DETAIL AS TMD ON TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0

WHERE
TMR.SEND_B1 IS NOT NULL
AND TME.FIRST_MANIFEST_KBN=0

/*END*/

UNION
-- （B2票返送先）
SELECT
TME.SYSTEM_ID
,TME.SEQ
,TME.KOUFU_DATE
,TME.DELETE_FLG
,TME.KOUFU_KBN
,TME.MANIFEST_ID
,TME.HST_GYOUSHA_CD
,TME.HST_GENBA_CD
,M_GENBA.GENBA_NAME_RYAKU AS  HST_GENBA_NAME_RYAKU
,M_GENBA.GENBA_NAME1 AS  HST_GENBA_NAME1
,M_GENBA.GENBA_NAME2 AS  HST_GENBA_NAME2
,M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2	AS MANI_HENSOUSAKI_TORIHIKISAKI_CD
,M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 AS MANI_HENSOUSAKI_GYOUSHA_CD
,M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2   AS MANI_HENSOUSAKI_GENBA_CD
--,'B2票'  MANI_HENSOUSAKI_NAME
,TME.HAIKI_KBN_CD
,'' AS SEND_A
,'' AS SEND_B1
,CASE WHEN M_GENBA.MANI_HENSOUSAKI_USE_B2 = 2 THEN '-' ELSE (CONVERT(nvarchar,TMR.SEND_B2,111)) END AS SEND_B2
,'' AS SEND_B4
,'' AS SEND_B6
,'' AS SEND_C1
,'' AS SEND_C2
,'' AS SEND_D
,'' AS SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_POST
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_POST
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_POST ELSE M_GENBA.MANI_HENSOUSAKI_POST END
END AS MANI_HENSOUSAKI_POST
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS1 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS1 END
END AS MANI_HENSOUSAKI_ADDRESS1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS2 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS2 END
END AS MANI_HENSOUSAKI_ADDRESS2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'') ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI_NAME1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1 ELSE M_GENBA.MANI_HENSOUSAKI_NAME1 END
END AS MANI_HENSOUSAKI_NAME1_REPORT
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU1 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU1 END
END AS MANI_HENSOUSAKI_KEISHOU1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2 ELSE M_GENBA.MANI_HENSOUSAKI_NAME2 END
END AS MANI_HENSOUSAKI_NAME2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU2 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU2 END 
END AS MANI_HENSOUSAKI_KEISHOU2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_BUSHO
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_BUSHO
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_BUSHO ELSE M_GENBA.MANI_HENSOUSAKI_BUSHO END 
END AS MANI_HENSOUSAKI_BUSHO
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_TANTOU
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_TANTOU
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_TANTOU ELSE M_GENBA.MANI_HENSOUSAKI_TANTOU END 
END AS MANI_HENSOUSAKI_TANTOU,
TME.KYOTEN_CD


FROM	T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B2 = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B2 = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1 )
ON TME.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND TME.HST_GENBA_CD = M_GENBA.GENBA_CD	
--LEFT JOIN T_MANIFEST_DETAIL AS TMD ON TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0

WHERE
TMR.SEND_B2 IS NOT NULL
AND TME.FIRST_MANIFEST_KBN=0

/*IF data.INSATU_KBN == '2'*/
UNION
-- （B4票返送先）
SELECT
TME.SYSTEM_ID
,TME.SEQ
,TME.KOUFU_DATE
,TME.DELETE_FLG
,TME.KOUFU_KBN
,TME.MANIFEST_ID
,TME.HST_GYOUSHA_CD
,TME.HST_GENBA_CD
,M_GENBA.GENBA_NAME_RYAKU AS  HST_GENBA_NAME_RYAKU
,M_GENBA.GENBA_NAME1 AS  HST_GENBA_NAME1
,M_GENBA.GENBA_NAME2 AS  HST_GENBA_NAME2
,M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4	AS MANI_HENSOUSAKI_TORIHIKISAKI_CD
,M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 AS MANI_HENSOUSAKI_GYOUSHA_CD
,M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4   AS MANI_HENSOUSAKI_GENBA_CD
--,'B4票'  MANI_HENSOUSAKI_NAME
,TME.HAIKI_KBN_CD
,'' AS SEND_A
,'' AS SEND_B1
,'' AS SEND_B2
,CASE WHEN M_GENBA.MANI_HENSOUSAKI_USE_B4 = 2 THEN '-' ELSE (CONVERT(nvarchar,TMR.SEND_B4,111)) END AS SEND_B4
,'' AS SEND_B6
,'' AS SEND_C1
,'' AS SEND_C2
,'' AS SEND_D
,'' AS SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_POST
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_POST
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_POST ELSE M_GENBA.MANI_HENSOUSAKI_POST END
END AS MANI_HENSOUSAKI_POST
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS1 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS1 END
END AS MANI_HENSOUSAKI_ADDRESS1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS2 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS2 END
END AS MANI_HENSOUSAKI_ADDRESS2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'') ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI_NAME1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1 ELSE M_GENBA.MANI_HENSOUSAKI_NAME1 END
END AS MANI_HENSOUSAKI_NAME1_REPORT
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU1 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU1 END
END AS MANI_HENSOUSAKI_KEISHOU1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2 ELSE M_GENBA.MANI_HENSOUSAKI_NAME2 END
END AS MANI_HENSOUSAKI_NAME2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU2 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU2 END 
END AS MANI_HENSOUSAKI_KEISHOU2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_BUSHO
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_BUSHO
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_BUSHO ELSE M_GENBA.MANI_HENSOUSAKI_BUSHO END 
END AS MANI_HENSOUSAKI_BUSHO
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_TANTOU
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_TANTOU
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_TANTOU ELSE M_GENBA.MANI_HENSOUSAKI_TANTOU END 
END AS MANI_HENSOUSAKI_TANTOU,
TME.KYOTEN_CD


FROM	T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B4 = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B4 = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1 )
ON TME.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND TME.HST_GENBA_CD = M_GENBA.GENBA_CD	
--LEFT JOIN T_MANIFEST_DETAIL AS TMD ON TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0
WHERE
TMR.SEND_B4 IS NOT NULL
AND TME.FIRST_MANIFEST_KBN=0

UNION
-- （B6票返送先）
SELECT
TME.SYSTEM_ID
,TME.SEQ
,TME.KOUFU_DATE
,TME.DELETE_FLG
,TME.KOUFU_KBN
,TME.MANIFEST_ID
,TME.HST_GYOUSHA_CD
,TME.HST_GENBA_CD
,M_GENBA.GENBA_NAME_RYAKU AS  HST_GENBA_NAME_RYAKU
,M_GENBA.GENBA_NAME1 AS  HST_GENBA_NAME1
,M_GENBA.GENBA_NAME2 AS  HST_GENBA_NAME2
,M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6	AS MANI_HENSOUSAKI_TORIHIKISAKI_CD
,M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 AS MANI_HENSOUSAKI_GYOUSHA_CD
,M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6   AS MANI_HENSOUSAKI_GENBA_CD
--,'B6票'  MANI_HENSOUSAKI_NAME
,TME.HAIKI_KBN_CD
,'' AS SEND_A
,'' AS SEND_B1
,'' AS SEND_B2
,'' AS SEND_B4
,CASE WHEN M_GENBA.MANI_HENSOUSAKI_USE_B6 = 2 THEN '-' ELSE (CONVERT(nvarchar,TMR.SEND_B6,111)) END AS SEND_B6
,'' AS SEND_C1
,'' AS SEND_C2
,'' AS SEND_D
,'' AS SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_POST
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_POST
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_POST ELSE M_GENBA.MANI_HENSOUSAKI_POST END
END AS MANI_HENSOUSAKI_POST
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS1 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS1 END
END AS MANI_HENSOUSAKI_ADDRESS1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS2 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS2 END
END AS MANI_HENSOUSAKI_ADDRESS2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'') ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI_NAME1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1 ELSE M_GENBA.MANI_HENSOUSAKI_NAME1 END
END AS MANI_HENSOUSAKI_NAME1_REPORT
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU1 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU1 END
END AS MANI_HENSOUSAKI_KEISHOU1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2 ELSE M_GENBA.MANI_HENSOUSAKI_NAME2 END
END AS MANI_HENSOUSAKI_NAME2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU2 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU2 END 
END AS MANI_HENSOUSAKI_KEISHOU2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_BUSHO
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_BUSHO
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_BUSHO ELSE M_GENBA.MANI_HENSOUSAKI_BUSHO END 
END AS MANI_HENSOUSAKI_BUSHO
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_TANTOU
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_TANTOU
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_TANTOU ELSE M_GENBA.MANI_HENSOUSAKI_TANTOU END 
END AS MANI_HENSOUSAKI_TANTOU,
TME.KYOTEN_CD


FROM	T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_B6 = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_B6 = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1 )
ON TME.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND TME.HST_GENBA_CD = M_GENBA.GENBA_CD	
--LEFT JOIN T_MANIFEST_DETAIL AS TMD ON TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0
WHERE
TMR.SEND_B6 IS NOT NULL
AND TME.FIRST_MANIFEST_KBN=0

/*END*/
UNION
-- （C1票返送先）
SELECT
TME.SYSTEM_ID
,TME.SEQ
,TME.KOUFU_DATE
,TME.DELETE_FLG
,TME.KOUFU_KBN
,TME.MANIFEST_ID
,TME.HST_GYOUSHA_CD
,TME.HST_GENBA_CD
,M_GENBA.GENBA_NAME_RYAKU AS  HST_GENBA_NAME_RYAKU
,M_GENBA.GENBA_NAME1 AS  HST_GENBA_NAME1
,M_GENBA.GENBA_NAME2 AS  HST_GENBA_NAME2
,M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1	AS MANI_HENSOUSAKI_TORIHIKISAKI_CD
,M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 AS MANI_HENSOUSAKI_GYOUSHA_CD
,M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1   AS MANI_HENSOUSAKI_GENBA_CD
--,'C1票'  MANI_HENSOUSAKI_NAME
,TME.HAIKI_KBN_CD
,'' AS SEND_A
,'' AS SEND_B1
,'' AS SEND_B2
,'' AS SEND_B4
,'' AS SEND_B6
,CASE WHEN M_GENBA.MANI_HENSOUSAKI_USE_C1 = 2 THEN '-' ELSE (CONVERT(nvarchar,TMR.SEND_C1,111)) END AS SEND_C1
,'' AS SEND_C2
,'' AS SEND_D
,'' AS SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_POST
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_POST
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_POST ELSE M_GENBA.MANI_HENSOUSAKI_POST END
END AS MANI_HENSOUSAKI_POST
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS1 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS1 END
END AS MANI_HENSOUSAKI_ADDRESS1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS2 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS2 END
END AS MANI_HENSOUSAKI_ADDRESS2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'') ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI_NAME1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1 ELSE M_GENBA.MANI_HENSOUSAKI_NAME1 END
END AS MANI_HENSOUSAKI_NAME1_REPORT
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU1 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU1 END
END AS MANI_HENSOUSAKI_KEISHOU1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2 ELSE M_GENBA.MANI_HENSOUSAKI_NAME2 END
END AS MANI_HENSOUSAKI_NAME2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU2 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU2 END 
END AS MANI_HENSOUSAKI_KEISHOU2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_BUSHO
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_BUSHO
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_BUSHO ELSE M_GENBA.MANI_HENSOUSAKI_BUSHO END 
END AS MANI_HENSOUSAKI_BUSHO
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_TANTOU
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_TANTOU
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_TANTOU ELSE M_GENBA.MANI_HENSOUSAKI_TANTOU END 
END AS MANI_HENSOUSAKI_TANTOU,
TME.KYOTEN_CD


FROM	T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C1 = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C1 = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1 )
ON TME.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND TME.HST_GENBA_CD = M_GENBA.GENBA_CD	
--LEFT JOIN T_MANIFEST_DETAIL AS TMD ON TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0
WHERE
TMR.SEND_C1 IS NOT NULL
AND TME.FIRST_MANIFEST_KBN=0

UNION
-- （C2票返送先）
SELECT
TME.SYSTEM_ID
,TME.SEQ
,TME.KOUFU_DATE
,TME.DELETE_FLG
,TME.KOUFU_KBN
,TME.MANIFEST_ID
,TME.HST_GYOUSHA_CD
,TME.HST_GENBA_CD
,M_GENBA.GENBA_NAME_RYAKU AS  HST_GENBA_NAME_RYAKU
,M_GENBA.GENBA_NAME1 AS  HST_GENBA_NAME1
,M_GENBA.GENBA_NAME2 AS  HST_GENBA_NAME2
,M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2	AS MANI_HENSOUSAKI_TORIHIKISAKI_CD
,M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 AS MANI_HENSOUSAKI_GYOUSHA_CD
,M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2   AS MANI_HENSOUSAKI_GENBA_CD
--,'C2票'  MANI_HENSOUSAKI_NAME
,TME.HAIKI_KBN_CD
,'' AS SEND_A
,'' AS SEND_B1
,'' AS SEND_B2
,'' AS SEND_B4
,'' AS SEND_B6
,'' AS SEND_C1
,CASE WHEN M_GENBA.MANI_HENSOUSAKI_USE_C2 = 2 THEN '-' ELSE (CONVERT(nvarchar,TMR.SEND_C2,111)) END AS SEND_C2
,'' AS SEND_D
,'' AS SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_POST
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_POST
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_POST ELSE M_GENBA.MANI_HENSOUSAKI_POST END
END AS MANI_HENSOUSAKI_POST
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS1 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS1 END
END AS MANI_HENSOUSAKI_ADDRESS1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS2 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS2 END
END AS MANI_HENSOUSAKI_ADDRESS2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'') ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI_NAME1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1 ELSE M_GENBA.MANI_HENSOUSAKI_NAME1 END
END AS MANI_HENSOUSAKI_NAME1_REPORT
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU1 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU1 END
END AS MANI_HENSOUSAKI_KEISHOU1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2 ELSE M_GENBA.MANI_HENSOUSAKI_NAME2 END
END AS MANI_HENSOUSAKI_NAME2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU2 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU2 END 
END AS MANI_HENSOUSAKI_KEISHOU2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_BUSHO
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_BUSHO
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_BUSHO ELSE M_GENBA.MANI_HENSOUSAKI_BUSHO END 
END AS MANI_HENSOUSAKI_BUSHO
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 <> '' THEN M_GENBA2.MANI_HENSOUSAKI_TANTOU
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_TANTOU
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_TANTOU ELSE M_GENBA.MANI_HENSOUSAKI_TANTOU END 
END AS MANI_HENSOUSAKI_TANTOU,
TME.KYOTEN_CD


FROM	T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_C2 = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_C2 = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1 )
ON TME.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND TME.HST_GENBA_CD = M_GENBA.GENBA_CD	
--LEFT JOIN T_MANIFEST_DETAIL AS TMD ON TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0
WHERE
TMR.SEND_C2 IS NOT NULL
AND TME.FIRST_MANIFEST_KBN=0

UNION
-- （D票返送先）
SELECT
TME.SYSTEM_ID
,TME.SEQ
,TME.KOUFU_DATE
,TME.DELETE_FLG
,TME.KOUFU_KBN
,TME.MANIFEST_ID
,TME.HST_GYOUSHA_CD
,TME.HST_GENBA_CD
,M_GENBA.GENBA_NAME_RYAKU AS  HST_GENBA_NAME_RYAKU
,M_GENBA.GENBA_NAME1 AS  HST_GENBA_NAME1
,M_GENBA.GENBA_NAME2 AS  HST_GENBA_NAME2
,M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D	AS MANI_HENSOUSAKI_TORIHIKISAKI_CD
,M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D AS MANI_HENSOUSAKI_GYOUSHA_CD
,M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D   AS MANI_HENSOUSAKI_GENBA_CD
--,'D票'  MANI_HENSOUSAKI_NAME
,TME.HAIKI_KBN_CD
,'' AS SEND_A
,'' AS SEND_B1
,'' AS SEND_B2
,'' AS SEND_B4
,'' AS SEND_B6
,'' AS SEND_C1
,'' AS SEND_C2
,CASE WHEN M_GENBA.MANI_HENSOUSAKI_USE_D = 2 THEN '-' ELSE (CONVERT(nvarchar,TMR.SEND_D,111)) END AS SEND_D
,'' AS SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D <> '' THEN M_GENBA2.MANI_HENSOUSAKI_POST
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_POST
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_POST ELSE M_GENBA.MANI_HENSOUSAKI_POST END
END AS MANI_HENSOUSAKI_POST
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS1 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS1 END
END AS MANI_HENSOUSAKI_ADDRESS1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS2 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS2 END
END AS MANI_HENSOUSAKI_ADDRESS2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'') ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI_NAME1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1 ELSE M_GENBA.MANI_HENSOUSAKI_NAME1 END
END AS MANI_HENSOUSAKI_NAME1_REPORT
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU1 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU1 END
END AS MANI_HENSOUSAKI_KEISHOU1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2 ELSE M_GENBA.MANI_HENSOUSAKI_NAME2 END
END AS MANI_HENSOUSAKI_NAME2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU2 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU2 END 
END AS MANI_HENSOUSAKI_KEISHOU2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D <> '' THEN M_GENBA2.MANI_HENSOUSAKI_BUSHO
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_BUSHO
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_BUSHO ELSE M_GENBA.MANI_HENSOUSAKI_BUSHO END 
END AS MANI_HENSOUSAKI_BUSHO
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D <> '' THEN M_GENBA2.MANI_HENSOUSAKI_TANTOU
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_TANTOU
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_TANTOU ELSE M_GENBA.MANI_HENSOUSAKI_TANTOU END 
END AS MANI_HENSOUSAKI_TANTOU,
TME.KYOTEN_CD


FROM	T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_D = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_D = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_D = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1 )
ON TME.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND TME.HST_GENBA_CD = M_GENBA.GENBA_CD	
--LEFT JOIN T_MANIFEST_DETAIL AS TMD ON TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0
WHERE
TMR.SEND_D IS NOT NULL
AND TME.FIRST_MANIFEST_KBN=0

UNION
-- （E票返送先）
SELECT
TME.SYSTEM_ID
,TME.SEQ
,TME.KOUFU_DATE
,TME.DELETE_FLG
,TME.KOUFU_KBN
,TME.MANIFEST_ID
,TME.HST_GYOUSHA_CD
,TME.HST_GENBA_CD
,M_GENBA.GENBA_NAME_RYAKU AS  HST_GENBA_NAME_RYAKU
,M_GENBA.GENBA_NAME1 AS  HST_GENBA_NAME1
,M_GENBA.GENBA_NAME2 AS  HST_GENBA_NAME2
,M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E	AS MANI_HENSOUSAKI_TORIHIKISAKI_CD
,M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E AS MANI_HENSOUSAKI_GYOUSHA_CD
,M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E   AS MANI_HENSOUSAKI_GENBA_CD
--,'E票'  MANI_HENSOUSAKI_NAME
,TME.HAIKI_KBN_CD
,'' AS SEND_A
,'' AS SEND_B1
,'' AS SEND_B2
,'' AS SEND_B4
,'' AS SEND_B6
,'' AS SEND_C1
,'' AS SEND_C2
,'' AS SEND_D
,CASE WHEN M_GENBA.MANI_HENSOUSAKI_USE_E = 2 THEN '-' ELSE (CONVERT(nvarchar,TMR.SEND_E,111)) END AS SEND_E
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E <> '' THEN M_GENBA2.MANI_HENSOUSAKI_POST
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_POST
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_POST ELSE M_GENBA.MANI_HENSOUSAKI_POST END
END AS MANI_HENSOUSAKI_POST
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS1 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS1 END
END AS MANI_HENSOUSAKI_ADDRESS1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E <> '' THEN M_GENBA2.MANI_HENSOUSAKI_ADDRESS2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_ADDRESS2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_ADDRESS2 ELSE M_GENBA.MANI_HENSOUSAKI_ADDRESS2 END
END AS MANI_HENSOUSAKI_ADDRESS2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E <> '' THEN ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GENBA2.MANI_HENSOUSAKI_NAME2,'')
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E <> '' THEN ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_GYOUSHA.MANI_HENSOUSAKI_NAME2,'')
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E <> '' THEN ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1,'')+' '+ISNULL(M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2,'') ELSE ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME1, '')+' '+ISNULL(M_GENBA.MANI_HENSOUSAKI_NAME2, '') END
END AS MANI_HENSOUSAKI_NAME1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME1 ELSE M_GENBA.MANI_HENSOUSAKI_NAME1 END
END AS MANI_HENSOUSAKI_NAME1_REPORT
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU1
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU1
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU1 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU1 END
END AS MANI_HENSOUSAKI_KEISHOU1
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E <> '' THEN M_GENBA2.MANI_HENSOUSAKI_NAME2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_NAME2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_NAME2 ELSE M_GENBA.MANI_HENSOUSAKI_NAME2 END
END AS MANI_HENSOUSAKI_NAME2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E <> '' THEN M_GENBA2.MANI_HENSOUSAKI_KEISHOU2
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_KEISHOU2
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_KEISHOU2 ELSE M_GENBA.MANI_HENSOUSAKI_KEISHOU2 END 
END AS MANI_HENSOUSAKI_KEISHOU2
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E <> '' THEN M_GENBA2.MANI_HENSOUSAKI_BUSHO
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_BUSHO
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_BUSHO ELSE M_GENBA.MANI_HENSOUSAKI_BUSHO END 
END AS MANI_HENSOUSAKI_BUSHO
,CASE
WHEN M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E <> '' THEN M_GENBA2.MANI_HENSOUSAKI_TANTOU
WHEN M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E <> '' THEN M_GYOUSHA.MANI_HENSOUSAKI_TANTOU
ELSE CASE WHEN M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E IS NOT NULL AND M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E <> '' THEN M_TORIHIKISAKI.MANI_HENSOUSAKI_TANTOU ELSE M_GENBA.MANI_HENSOUSAKI_TANTOU END 
END AS MANI_HENSOUSAKI_TANTOU,
TME.KYOTEN_CD


FROM	T_MANIFEST_ENTRY AS TME 	-- マニフェスト
LEFT JOIN (M_GENBA AS M_GENBA -- 現場マスタ
LEFT JOIN  M_TORIHIKISAKI ON M_GENBA.MANI_HENSOUSAKI_TORIHIKISAKI_CD_E = M_TORIHIKISAKI.TORIHIKISAKI_CD AND M_TORIHIKISAKI.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GYOUSHA ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.MANI_HENSOUSAKI_KBN = 1
LEFT JOIN  M_GENBA AS M_GENBA2 ON M_GENBA.MANI_HENSOUSAKI_GYOUSHA_CD_E = M_GENBA2.GYOUSHA_CD AND M_GENBA.MANI_HENSOUSAKI_GENBA_CD_E = M_GENBA2.GENBA_CD
AND M_GENBA2.MANI_HENSOUSAKI_KBN = 1 )
ON TME.HST_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND TME.HST_GENBA_CD = M_GENBA.GENBA_CD	
--LEFT JOIN T_MANIFEST_DETAIL AS TMD ON TME.SYSTEM_ID = TMD.SYSTEM_ID AND TME.SEQ = TMD.SEQ
LEFT JOIN T_MANIFEST_RET_DATE AS TMR ON TME.SYSTEM_ID = TMR.SYSTEM_ID AND TMR.DELETE_FLG = 0
WHERE
TMR.SEND_E IS NOT NULL
AND TME.FIRST_MANIFEST_KBN=0

) AS SUMMEY

WHERE 	SUMMEY.DELETE_FLG = 0
AND (CASE
WHEN SUMMEY.MANI_HENSOUSAKI_GENBA_CD IS NOT NULL AND SUMMEY.MANI_HENSOUSAKI_GENBA_CD <>'' THEN SUMMEY.MANI_HENSOUSAKI_GENBA_CD+SUMMEY.MANI_HENSOUSAKI_NAME1
WHEN SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD IS NOT NULL  AND SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD <>'' THEN SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD+SUMMEY.MANI_HENSOUSAKI_NAME1
WHEN SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD IS NOT NULL AND SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD <>''  THEN SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD+SUMMEY.MANI_HENSOUSAKI_NAME1
ELSE SUMMEY.MANI_HENSOUSAKI_NAME1
END ) IS NOT NULL
/*IF data.RET_DATE_FROM != null && data.RET_DATE_FROM != '' && data.RET_DATE_TO != null && data.RET_DATE_TO != ''*/AND
(
(CONVERT(nvarchar,SUMMEY.SEND_A,111) >= /*data.RET_DATE_FROM*/ AND CONVERT(nvarchar,SUMMEY.SEND_A,111) <= /*data.RET_DATE_TO*/)
OR (CONVERT(nvarchar,SUMMEY.SEND_B1,111) >= /*data.RET_DATE_FROM*/ AND CONVERT(nvarchar,SUMMEY.SEND_B1,111) <= /*data.RET_DATE_TO*/)
OR (CONVERT(nvarchar,SUMMEY.SEND_B2,111) >= /*data.RET_DATE_FROM*/ AND CONVERT(nvarchar,SUMMEY.SEND_B2,111) <= /*data.RET_DATE_TO*/)
OR (CONVERT(nvarchar,SUMMEY.SEND_B4,111) >= /*data.RET_DATE_FROM*/ AND CONVERT(nvarchar,SUMMEY.SEND_B4,111) <= /*data.RET_DATE_TO*/)
OR (CONVERT(nvarchar,SUMMEY.SEND_B6,111) >= /*data.RET_DATE_FROM*/ AND CONVERT(nvarchar,SUMMEY.SEND_B6,111) <= /*data.RET_DATE_TO*/)
OR (CONVERT(nvarchar,SUMMEY.SEND_C1,111) >= /*data.RET_DATE_FROM*/ AND CONVERT(nvarchar,SUMMEY.SEND_C1,111) <= /*data.RET_DATE_TO*/)
OR (CONVERT(nvarchar,SUMMEY.SEND_C2,111) >= /*data.RET_DATE_FROM*/ AND CONVERT(nvarchar,SUMMEY.SEND_C2,111) <= /*data.RET_DATE_TO*/)
OR (CONVERT(nvarchar,SUMMEY.SEND_D,111) >= /*data.RET_DATE_FROM*/ AND CONVERT(nvarchar,SUMMEY.SEND_D,111) <= /*data.RET_DATE_TO*/)
OR (CONVERT(nvarchar,SUMMEY.SEND_E,111) >= /*data.RET_DATE_FROM*/ AND CONVERT(nvarchar,SUMMEY.SEND_E,111) <= /*data.RET_DATE_TO*/)
)
/*END*/
/*IF data.HST_GYOUSHA_CD_FROM != null && data.HST_GYOUSHA_CD_FROM != '' && data.HST_GYOUSHA_CD_TO != null && data.HST_GYOUSHA_CD_TO != ''*/
AND SUMMEY.HST_GYOUSHA_CD >= /*data.HST_GYOUSHA_CD_FROM*/
AND SUMMEY.HST_GYOUSHA_CD <= /*data.HST_GYOUSHA_CD_TO*/
/*END*/

/*IF data.HST_GENBA_CD_FROM != null && data.HST_GENBA_CD_FROM != '' && data.HST_GENBA_CD_TO != null && data.HST_GENBA_CD_TO != ''*/
AND SUMMEY.HST_GENBA_CD >= /*data.HST_GENBA_CD_FROM*/
AND SUMMEY.HST_GENBA_CD <= /*data.HST_GENBA_CD_TO*/
/*END*/
/*IF data.TORIHIKISAKI_CD_FROM != null && data.TORIHIKISAKI_CD_FROM != '' && data.TORIHIKISAKI_CD_TO != null && data.TORIHIKISAKI_CD_TO != ''*/
AND SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD >= /*data.TORIHIKISAKI_CD_FROM*/
AND SUMMEY.MANI_HENSOUSAKI_TORIHIKISAKI_CD <= /*data.TORIHIKISAKI_CD_TO*/
/*END*/

/*IF data.GYOUSHA_CD_FROM != null && data.GYOUSHA_CD_FROM != '' && data.GYOUSHA_CD_TO != null && data.GYOUSHA_CD_TO != ''*/
AND SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD >= /*data.GYOUSHA_CD_FROM*/
AND SUMMEY.MANI_HENSOUSAKI_GYOUSHA_CD <= /*data.GYOUSHA_CD_TO*/
/*END*/

/*IF data.GENBA_CD_FROM != null && data.GENBA_CD_FROM != '' && data.GENBA_CD_TO != null && data.GENBA_CD_TO != ''*/
AND SUMMEY.MANI_HENSOUSAKI_GENBA_CD >= /*data.GENBA_CD_FROM*/
AND SUMMEY.MANI_HENSOUSAKI_GENBA_CD <= /*data.GENBA_CD_TO*/
/*END*/

/*IF data.KYOTEN_CD != null && data.KYOTEN_CD != ''*/
AND SUMMEY.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/

/*IF data.INSATU_KBN == '1'*/AND  ( SUMMEY.HAIKI_KBN_CD = 1 OR SUMMEY.HAIKI_KBN_CD = 2)/*END*/                 -- ※印刷区分		印刷区分 = 1の場合	マニフェスト.廃棄物区分CD IN 1 OR 2
/*IF data.INSATU_KBN == '2'*/AND  SUMMEY.HAIKI_KBN_CD = 3 /*END*/                                           -- ※印刷区分		印刷区分 = 2の場合	マニフェスト.廃棄物区分CD 3
