SELECT 
    MNS.*
FROM 
    dbo.M_MANIFEST_SHURUI MNS
/*BEGIN*/WHERE
/*IF !data.MANIFEST_SHURUI_CD.IsNull */CAST(MNS.MANIFEST_SHURUI_CD AS varchar(5)) LIKE '%' + CAST(/*data.MANIFEST_SHURUI_CD*/0 AS varchar(5)) + '%'/*END*/
 /*IF data.MANIFEST_SHURUI_NAME != null*/AND MNS.MANIFEST_SHURUI_NAME LIKE '%' +  /*data.MANIFEST_SHURUI_NAME*/ + '%'/*END*/
 /*IF data.MANIFEST_SHURUI_NAME_RYAKU != null*/AND MNS.MANIFEST_SHURUI_NAME_RYAKU LIKE '%' +  /*data.MANIFEST_SHURUI_NAME_RYAKU*/ + '%'/*END*/
 /*IF data.MANIFEST_SHURUI_FURIGANA != null*/AND MNS.MANIFEST_SHURUI_FURIGANA LIKE '%' +  /*data.MANIFEST_SHURUI_FURIGANA*/ + '%'/*END*/
 /*IF data.MANIFEST_SHURUI_BIKOU != null*/AND MNS.MANIFEST_SHURUI_BIKOU LIKE '%' +  /*data.MANIFEST_SHURUI_BIKOU*/ + '%'/*END*/
 /*IF data.CREATE_USER != null*/AND MNS.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, MNS.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null*/AND MNS.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, MNS.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
 /*IF !deletechuFlg*/AND MNS.DELETE_FLG = 0/*END*/
/*END*/
ORDER BY MNS.MANIFEST_SHURUI_CD
