SELECT
 MAIN.SYS_ID,
    SUB.TORIHIKISAKI_CD, 
    SUB.TORIHIKISAKI_NAME_RYAKU,
    SUB.GYOUSHA_CD, 
    SUB.GYOUSHA_NAME_RYAKU,
    SUB.GENBA_CD, 
    SUB.GENBA_NAME_RYAKU, 
    SUB.HINMEI_CD, 
    --SUB.HINMEI_NAME_RYAKU,
    SUB.DENSHU_KBN_CD,
	MAIN.DENPYOU_KBN_CD,
    SUB.UNIT_CD, 
    SUB.UNIT_NAME_RYAKU,
    SUB.UNPAN_GYOUSHA_CD, 
    SUB.UNPAN_GYOUSHA_NAME_RYAKU,
    SUB.NIOROSHI_GYOUSHA_CD, 
    SUB.NIOROSHI_GYOUSHA_NAME_RYAKU, 
    SUB.NIOROSHI_GENBA_CD, 
    SUB.NIOROSHI_GENBA_NAME_RYAKU,
    SUB.TEKIYOU_BEGIN,
    MAIN.TANKA,
    MAIN.TEKIYOU_END,
    MAIN.TIME_STAMP,
    MH.HINMEI_NAME_RYAKU,
    MH.BUNRUI_CD,
    MB.BUNRUI_NAME_RYAKU,
    MH.SHURUI_CD,
    MS.SHURUI_NAME_RYAKU,
    MAIN.BIKOU

FROM
 M_KOBETSU_HINMEI_TANKA AS MAIN
 INNER JOIN (
   SELECT 
   TOP (100) PERCENT
    A.TORIHIKISAKI_CD, 
    MT.TORIHIKISAKI_NAME_RYAKU,
    A.GYOUSHA_CD, 
    MG.GYOUSHA_NAME_RYAKU,
    A.GENBA_CD, 
    M_GENBA.GENBA_NAME_RYAKU, 
    A.HINMEI_CD, 
    --B.HINMEI_NAME_RYAKU,
    A.DENSHU_KBN_CD,
	--A.DENPYOU_KBN_CD,
    A.UNIT_CD, 
    MU.UNIT_NAME_RYAKU,
    A.UNPAN_GYOUSHA_CD, 
    M_UNPAN_GYOUSHA.GYOUSHA_NAME_RYAKU AS UNPAN_GYOUSHA_NAME_RYAKU,
    A.NIOROSHI_GYOUSHA_CD, 
    M_NIOROSHI_GYOUSHA.GYOUSHA_NAME_RYAKU AS NIOROSHI_GYOUSHA_NAME_RYAKU, 
    A.NIOROSHI_GENBA_CD, 
    M_NIOROSHI_GENBA.GENBA_NAME_RYAKU AS NIOROSHI_GENBA_NAME_RYAKU,
    MAX(A.TEKIYOU_BEGIN) AS TEKIYOU_BEGIN
   -- A.TANKA,
   -- A.TEKIYOU_END
   FROM M_KOBETSU_HINMEI_TANKA AS A 
   LEFT JOIN M_TORIHIKISAKI  MT
       ON A.TORIHIKISAKI_CD = MT.TORIHIKISAKI_CD 
   LEFT JOIN M_GYOUSHA MG
       ON A.GYOUSHA_CD = MG.GYOUSHA_CD
   LEFT JOIN M_GENBA 
       ON  A.GENBA_CD = M_GENBA.GENBA_CD
--       AND A.TORIHIKISAKI_CD = M_GENBA.TORIHIKISAKI_CD
       AND A.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
--   LEFT JOIN M_HINMEI AS B 
--       ON A.HINMEI_CD = B.HINMEI_CD 
--/*IF shuruiCD != null && shuruiCD != ''*/AND B.SHURUI_CD =  /*shuruiCD*/ /*END*/
--/*IF bunruiCD != null && bunruiCD != ''*/AND B.BUNRUI_CD = /*bunruiCD*/ /*END*/
   LEFT JOIN M_UNIT MU
       ON A.UNIT_CD = MU.UNIT_CD
   LEFT JOIN M_GYOUSHA AS M_UNPAN_GYOUSHA 
       ON A.UNPAN_GYOUSHA_CD = M_UNPAN_GYOUSHA.GYOUSHA_CD 
 --      AND A.TORIHIKISAKI_CD = M_UNPAN_GYOUSHA.TORIHIKISAKI_CD 
       AND M_UNPAN_GYOUSHA.UNPAN_JUTAKUSHA_KAISHA_KBN = 1 
   LEFT JOIN M_GYOUSHA AS M_NIOROSHI_GYOUSHA 
       ON A.NIOROSHI_GYOUSHA_CD = M_NIOROSHI_GYOUSHA.GYOUSHA_CD 
--       AND A.TORIHIKISAKI_CD = M_NIOROSHI_GYOUSHA.TORIHIKISAKI_CD 
       AND M_NIOROSHI_GYOUSHA.SHOBUN_NIOROSHI_GYOUSHA_KBN = 1
   LEFT JOIN M_GENBA AS M_NIOROSHI_GENBA 
       ON A.NIOROSHI_GENBA_CD = M_NIOROSHI_GENBA.GENBA_CD 
 --      AND A.TORIHIKISAKI_CD = M_NIOROSHI_GENBA.TORIHIKISAKI_CD 
       AND A.NIOROSHI_GYOUSHA_CD = M_NIOROSHI_GENBA.GYOUSHA_CD 
       AND M_NIOROSHI_GENBA.SHOBUN_NIOROSHI_GENBA_KBN = 1 
   GROUP BY
    A.TORIHIKISAKI_CD, 
    MT.TORIHIKISAKI_NAME_RYAKU,
    A.GYOUSHA_CD, 
    MG.GYOUSHA_NAME_RYAKU,
    A.GENBA_CD, 
    M_GENBA.GENBA_NAME_RYAKU, 
    A.HINMEI_CD, 
    --B.HINMEI_NAME_RYAKU,
    A.DENSHU_KBN_CD, 
	--A.DENPYOU_KBN_CD,
    A.UNIT_CD, 
    MU.UNIT_NAME_RYAKU,
    A.UNPAN_GYOUSHA_CD, 
    M_UNPAN_GYOUSHA.GYOUSHA_NAME_RYAKU,
    A.NIOROSHI_GYOUSHA_CD, 
    M_NIOROSHI_GYOUSHA.GYOUSHA_NAME_RYAKU,
    A.NIOROSHI_GENBA_CD, 
    M_NIOROSHI_GENBA.GENBA_NAME_RYAKU
   -- A.TANKA, 
    --B.HINMEI_NAME_RYAKU 
   -- A.TEKIYOU_END
   ORDER BY 
    A.TORIHIKISAKI_CD, 
    A.GYOUSHA_CD, 
    A.GENBA_CD, 
    A.HINMEI_CD, 
    A.DENSHU_KBN_CD, 
    A.UNIT_CD, 
    A.UNPAN_GYOUSHA_CD, 
    A.NIOROSHI_GYOUSHA_CD, 
    A.NIOROSHI_GENBA_CD
  ) AS SUB
  ON 
    ISNULL(MAIN.TORIHIKISAKI_CD,'') = ISNULL(SUB.TORIHIKISAKI_CD,'')
  AND
    ISNULL(MAIN.GYOUSHA_CD,'') = ISNULL(SUB.GYOUSHA_CD,'')
  AND
    ISNULL(MAIN.GENBA_CD,'') = ISNULL(SUB.GENBA_CD,'')
  AND
    ISNULL(MAIN.HINMEI_CD,'') = ISNULL(SUB.HINMEI_CD,'')
  AND
    ISNULL(MAIN.DENSHU_KBN_CD,'') = ISNULL(SUB.DENSHU_KBN_CD,'')
  --AND
  --  ISNULL(MAIN.DENPYOU_KBN_CD,'') = ISNULL(SUB.DENPYOU_KBN_CD,'')
  AND
    ISNULL(MAIN.UNIT_CD,'') = ISNULL(SUB.UNIT_CD,'')
  AND
    ISNULL(MAIN.UNPAN_GYOUSHA_CD,'') = ISNULL(SUB.UNPAN_GYOUSHA_CD,'')
  AND
    ISNULL(MAIN.NIOROSHI_GYOUSHA_CD,'') = ISNULL(SUB.NIOROSHI_GYOUSHA_CD,'')
  AND
    ISNULL(MAIN.NIOROSHI_GENBA_CD,'') = ISNULL(SUB.NIOROSHI_GENBA_CD,'')
  AND
    ISNULL(MAIN.TEKIYOU_BEGIN,'') = ISNULL(SUB.TEKIYOU_BEGIN,'')
 LEFT JOIN M_HINMEI AS MH 
       ON ISNULL(MAIN.HINMEI_CD,'') = ISNULL(MH.HINMEI_CD,'') 
 LEFT JOIN M_SHURUI AS MS
       ON ISNULL(MH.SHURUI_CD,'') = ISNULL(MS.SHURUI_CD,'')
 LEFT JOIN M_BUNRUI AS MB
       ON ISNULL(MH.BUNRUI_CD,'') = ISNULL(MB.BUNRUI_CD,'')
/*BEGIN*/WHERE
/*IF data.TORIHIKISAKI_CD!= null*/MAIN.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/ /*END*/
/*IF data.GYOUSHA_CD != null*/AND MAIN.GYOUSHA_CD  = /*data.GYOUSHA_CD*/ /*END*/
/*IF data.GENBA_CD != null*/AND MAIN.GENBA_CD = /*data.GENBA_CD*/ /*END*/
/*IF !data.DENSHU_KBN_CD.IsNull*/AND MAIN.DENSHU_KBN_CD= /*data.DENSHU_KBN_CD*/ /*END*/
/*IF !data.DENPYOU_KBN_CD.IsNull*/AND MAIN.DENPYOU_KBN_CD= /*data.DENPYOU_KBN_CD*/ /*END*/
/*IF !data.UNIT_CD.IsNull*/AND MAIN.UNIT_CD = /*data.UNIT_CD*/ /*END*/
/*IF data.UNPAN_GYOUSHA_CD != null*/AND MAIN.UNPAN_GYOUSHA_CD = /*data.UNPAN_GYOUSHA_CD*/ /*END*/
/*IF data.NIOROSHI_GYOUSHA_CD != null*/ AND MAIN.NIOROSHI_GYOUSHA_CD = /*data.NIOROSHI_GYOUSHA_CD*/ /*END*/
/*IF data.NIOROSHI_GENBA_CD != null*/AND MAIN.NIOROSHI_GENBA_CD= /*data.NIOROSHI_GENBA_CD*/ /*END*/
/*IF data.HINMEI_CD != null*/AND MH.HINMEI_CD = /*data.HINMEI_CD*/ /*END*/
/*IF shuruiCD != null && shuruiCD != ''*/AND MS.SHURUI_CD = /*shuruiCD*/ /*END*/
/*IF bunruiCD != null && bunruiCD != ''*/AND MB.BUNRUI_CD = /*bunruiCD*/ /*END*/
AND MAIN.DELETE_FLG = 0
/*END*/

