SELECT 
 MT.TORIHIKISAKI_CD AS TORIHIKISAKI_CD,
 M_KYOTEN.KYOTEN_NAME_RYAKU AS KYOTEN_NAME_RYAKU
FROM M_TORIHIKISAKI AS MT
INNER JOIN M_KYOTEN 
    ON MT.TORIHIKISAKI_KYOTEN_CD = M_KYOTEN.KYOTEN_CD
WHERE
1=1
/*BEGIN*/
/*IF data.TORIHIKISAKI_CD != null*/AND MT.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/ /*END*/
/*END*/
AND MT.DELETE_FLG = 0
ORDER BY MT.TORIHIKISAKI_CD