SELECT
       HOUKOKU_SHOBUN_HOUHOU_CD,
       HOUKOKU_SHOBUN_HOUHOU_NAME
  FROM M_CHIIKIBETSU_SHOBUN
 WHERE CHIIKI_CD = /*data.CHIIKI_CD*/0
   AND SHOBUN_HOUHOU_CD = /*data.SHOBUN_HOUHOU_CD*/0
   AND DELETE_FLG = 0