SELECT * FROM M_KOBETSU_HINMEI
INNER JOIN M_HINMEI ON M_KOBETSU_HINMEI.HINMEI_CD = M_HINMEI.HINMEI_CD
WHERE M_KOBETSU_HINMEI.GYOUSHA_CD = /*data.GYOUSHA_CD*/''
  AND M_KOBETSU_HINMEI.GENBA_CD =  /*data.GENBA_CD*/''
  AND M_KOBETSU_HINMEI.HINMEI_CD = /*data.HINMEI_CD*/''
  AND M_KOBETSU_HINMEI.DELETE_FLG = 0
  AND M_HINMEI.DELETE_FLG = 0
  AND (M_HINMEI.DENSHU_KBN_CD = /*hinmei.DENPYOU_KBN_CD.Value*/1 OR M_HINMEI.DENSHU_KBN_CD = 9)