SELECT 
    YUUGAI.*
FROM 
    dbo.M_DENSHI_YUUGAI_BUSSHITSU YUUGAI
/*BEGIN*/WHERE
 /*IF data.YUUGAI_BUSSHITSU_CD != null*/
 YUUGAI.YUUGAI_BUSSHITSU_CD LIKE '%' + /*data.YUUGAI_BUSSHITSU_CD*/'01' + '%'
 /*END*/
 /*IF data.YUUGAI_BUSSHITSU_NAME != null*/AND YUUGAI.YUUGAI_BUSSHITSU_NAME LIKE '%' +  /*data.YUUGAI_BUSSHITSU_NAME*/ + '%'/*END*/
 /*IF data.CREATE_USER != null*/AND YUUGAI.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, YUUGAI.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null*/AND YUUGAI.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, YUUGAI.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
 /*IF !deletechuFlg*/AND YUUGAI.DELETE_FLG = /*deletechuFlg*/0/*END*/
/*END*/
ORDER BY YUUGAI.YUUGAI_BUSSHITSU_CD
