SELECT
S.SHARYOU_CD AS 車輌CD,
S.SHARYOU_NAME_RYAKU AS 車輌名,
X.SHASHU_CD AS 車種CD,
X.SHASHU_NAME_RYAKU AS 車種名,
S.GYOUSHA_CD AS 業者CD,
G.GYOUSHA_NAME_RYAKU AS 業者名,
S.KUUSHA_JYURYO AS 空車重量,
U.SHAIN_CD AS 運転者CD,
U.SHAIN_NAME_RYAKU AS 運転者名
FROM
M_SHARYOU S
LEFT OUTER JOIN M_GYOUSHA G  ON S.GYOUSHA_CD = G.GYOUSHA_CD
LEFT OUTER JOIN M_SHASHU X  ON S.SHASYU_CD = X.SHASHU_CD AND X.DELETE_FLG <> 1
LEFT OUTER JOIN M_SHAIN U ON S.SHAIN_CD = U.SHAIN_CD AND U.UNTEN_KBN = 1 AND U.DELETE_FLG <> 1
/*BEGIN*/WHERE 
/*IF data.DELETE_FLG.IsFalse */ 
  S.DELETE_FLG <> '1' /*END*/
/*IF data.GYOUSHA_TEKIYOU_FLG.IsFalse */ 
  AND G.DELETE_FLG <> '1' /*END*/
/*IF data.GYOUSHA_TEKIYOU_FLG.IsTrue */ 
/*IF data.TEKIYOU_DATE != null && data.TEKIYOU_DATE !='' */ 
  AND (((G.TEKIYOU_BEGIN <= CONVERT(DATETIME, /*data.TEKIYOU_DATE*/, 120) AND CONVERT(DATETIME, /*data.TEKIYOU_DATE*/, 120) <= G.TEKIYOU_END) OR (G.TEKIYOU_BEGIN <= CONVERT(DATETIME, /*data.TEKIYOU_DATE*/, 120) AND G.TEKIYOU_END IS NULL) OR (G.TEKIYOU_BEGIN IS NULL AND CONVERT(DATETIME, /*data.TEKIYOU_DATE*/, 120) <= G.TEKIYOU_END) OR (G.TEKIYOU_BEGIN IS NULL AND G.TEKIYOU_END IS NULL)) AND G.DELETE_FLG <> 1) /*END*/
/*IF data.TEKIYOU_DATE == null || data.TEKIYOU_DATE =='' */ 
  AND (((G.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) AND CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= G.TEKIYOU_END) OR (G.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) AND G.TEKIYOU_END IS NULL) OR (G.TEKIYOU_BEGIN IS NULL AND CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= G.TEKIYOU_END) OR (G.TEKIYOU_BEGIN IS NULL AND G.TEKIYOU_END IS NULL)) AND G.DELETE_FLG <> 1) /*END*/
/*END*/
/*IF data.GYOUSHA_CD != null && data.GYOUSHA_CD != '' && data.GYOUSHA_CD != '自社'*/
 AND S.GYOUSHA_CD = /*data.GYOUSHA_CD*/ /*END*/
/*IF data.GYOUSHA_CD != null && data.GYOUSHA_CD == '自社'*/
 AND S.GYOUSHA_CD = '' /*END*/
 /*IF (data.KENCONDITION_VALUE == null || data.KENCONDITION_VALUE == '') && (data.SHARYOU_CD != null && data.SHARYOU_CD != '')*/
	AND S.SHARYOU_CD LIKE '%' + /*data.SHARYOU_CD*/ + '%' /*END*/
 /*IF data.SHASYU_CD != null && data.SHASYU_CD != ''*/
 AND S.SHASYU_CD LIKE '%' + /*data.SHASYU_CD*/ + '%' /*END*/
 /*IF data.SHAIN_CD != null && data.SHAIN_CD != ''*/
 AND S.SHAIN_CD LIKE '%' + /*data.SHAIN_CD*/ + '%' /*END*/
 /*  20140620 ria EV004826 車輌選択画面に検索条件が無い為、車輌の検索ができない start*/
/*IF data.KENCONDITION_VALUE != null && data.KENCONDITION_VALUE != ''*/
    /*IF data.KENCONDITION_ITEM == '1'*/
       AND S.SHARYOU_CD LIKE '%' + /*data.KENCONDITION_VALUE*/0 + '%'
    /*END*/
    /*IF data.KENCONDITION_ITEM == '2'*/
       AND S.SHARYOU_NAME_RYAKU LIKE '%' + /*data.KENCONDITION_VALUE*/ + '%'
    /*END*/
    /*IF data.KENCONDITION_ITEM == '3'*/
       AND S.GYOUSHA_CD LIKE '%' + /*data.KENCONDITION_VALUE*/0 + '%'
    /*END*/
    /*IF data.KENCONDITION_ITEM == '4'*/
       AND G.GYOUSHA_NAME_RYAKU LIKE '%' + /*data.KENCONDITION_VALUE*/ + '%'
    /*END*/
    /*IF data.KENCONDITION_ITEM == '5'*/
       AND (S.SHARYOU_CD LIKE '%' + /*data.KENCONDITION_VALUE*/ + '%' 
            OR  S.SHARYOU_NAME_RYAKU LIKE '%' + /*data.KENCONDITION_VALUE*/ + '%'
            OR  S.GYOUSHA_CD  LIKE '%' + /*data.KENCONDITION_VALUE*/ + '%'
           OR G.GYOUSHA_NAME_RYAKU LIKE '%' + /*data.KENCONDITION_VALUE*/ + '%')
    /*END*/
/*END*/
/* 20140620 ria EV004826 車輌選択画面に検索条件が無い為、車輌の検索ができない end*/
 /*IF data.CLOSED_DATE != null && data.CLOSED_DATE != ''*/
 AND NOT EXISTS( SELECT 1 FROM M_WORK_CLOSED_SHARYOU T2 
                 WHERE S.GYOUSHA_CD = T2.GYOUSHA_CD
                   AND S.SHARYOU_CD = T2.SHARYOU_CD
				   AND CONVERT(CHAR(10), T2.CLOSED_DATE, 111) = CONVERT(CHAR(10), /*data.CLOSED_DATE*/, 111)
				   AND S.DELETE_FLG = 0 AND T2.DELETE_FLG = 0)
 /*END*/
/*IF data.GYOUSHAKBN == 1*/
AND G.GYOUSHAKBN_UKEIRE = 1
/*END*/
/*IF data.GYOUSHAKBN == 2*/
AND G.GYOUSHAKBN_SHUKKA = 1
/*END*/
/*IF data.GYOUSHAKBN == 3*/
AND G.GYOUSHAKBN_UKEIRE = 1
AND G.GYOUSHAKBN_SHUKKA = 1
/*END*/
/*IF data.UNPAN_JUTAKUSHA_KAISHA_KBN.IsTrue */ 
AND G.UNPAN_JUTAKUSHA_KAISHA_KBN = 1
/*END*/
/*IF data.GYOUSHAKBN_MANI.IsTrue */ 
AND G.GYOUSHAKBN_MANI = 1
/*END*/
/*END*/
ORDER BY S.SHARYOU_CD, X.SHASHU_CD, S.GYOUSHA_CD