SELECT  T_USSD.*
		, M_DENPYOU_KBN.DENPYOU_KBN_NAME_RYAKU
		, M_UNIT.UNIT_NAME_RYAKU
FROM    T_UKETSUKE_SS_DETAIL AS T_USSD LEFT OUTER JOIN
        M_UNIT ON T_USSD.UNIT_CD = M_UNIT.UNIT_CD LEFT OUTER JOIN
        M_DENPYOU_KBN ON T_USSD.DENPYOU_KBN_CD = M_DENPYOU_KBN.DENPYOU_KBN_CD AND M_DENPYOU_KBN.DELETE_FLG = 0
WHERE	T_USSD.SYSTEM_ID = /*data.SYSTEM_ID*/
AND		T_USSD.SEQ = /*data.SEQ*/
ORDER BY T_USSD.ROW_NO