SELECT M_DENSHU_KBN.DENSHU_KBN_CD, M_DENSHU_KBN.DENSHU_KBN_NAME_RYAKU FROM dbo.M_DENSHU_KBN AS M_DENSHU_KBN
WHERE 
DELETE_FLG = 0
/*IF !data.DENSHU_KBN_CD.IsNull*/AND DENSHU_KBN_CD = /*data.DENSHU_KBN_CD.Value*//*END*/
/*IF data.DENSHU_KBN_NAME != null*/AND DENSHU_KBN_NAME = /*data.DENSHU_KBN_NAME*//*END*/
/*IF data.DENSHU_KBN_NAME_RYAKU != null*/AND DENSHU_KBN_NAME_RYAKU = /*data.DENSHU_KBN_NAME_RYAKU*//*END*/
/*IF data.DENSHU_KBN_BIKOU != null*/AND DENSHU_KBN_BIKOU = /*data.DENSHU_KBN_BIKOU*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
