SELECT  										
	M_OUTPUT_PATTERN_COLUMN.TABLE_NAME,									
	M_OUTPUT_PATTERN_COLUMN.KOUMOKU_RONRI_NAME,									
	M_OUTPUT_PATTERN_COLUMN.KOUMOKU_BUTSURI_NAME,									
	M_OUTPUT_PATTERN_COLUMN.SORT_NO,									
	M_OUTPUT_PATTERN_COLUMN.PRIORITY_NO									
FROM										
	M_OUTPUT_PATTERN_KOBETSU,									
	M_OUTPUT_PATTERN,									
	M_OUTPUT_PATTERN_COLUMN									
WHERE										
	M_OUTPUT_PATTERN_KOBETSU.SHAIN_CD = '123456'                            AND									
	M_OUTPUT_PATTERN_KOBETSU.DELETE_FLG = 0                                 AND									
	M_OUTPUT_PATTERN.DELETE_FLG = 0                                         AND									
	M_OUTPUT_PATTERN_KOBETSU.SYSTEM_ID = M_OUTPUT_PATTERN.SYSTEM_ID         AND									
	M_OUTPUT_PATTERN_KOBETSU.SEQ = M_OUTPUT_PATTERN.SEQ						AND		
	M_OUTPUT_PATTERN_KOBETSU.SYSTEM_ID = M_OUTPUT_PATTERN_COLUMN.SYSTEM_ID	AND
	M_OUTPUT_PATTERN_KOBETSU.SEQ = M_OUTPUT_PATTERN_COLUMN.SEQ									
ORDER BY										
	M_OUTPUT_PATTERN_COLUMN.SYSTEM_ID									
