SELECT DISTINCT N'地域別分類マスタ' AS NAME FROM M_CHIIKIBETSU_BUNRUI WHERE HOUKOKUSHO_BUNRUI_CD IN /*HOUKOKUSHO_BUNRUI_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'地域別許可名マスタ' AS NAME FROM M_CHIIKIBETSU_KYOKA_MEIGARA WHERE HOUKOKUSHO_BUNRUI_CD IN /*HOUKOKUSHO_BUNRUI_CD*/('')
UNION
SELECT DISTINCT N'電子廃棄種類マスタ' AS NAME FROM M_DENSHI_HAIKI_SHURUI WHERE HOUKOKUSHO_BUNRUI_CD IN /*HOUKOKUSHO_BUNRUI_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'減容率マスタ' AS NAME FROM M_GENNYOURITSU WHERE HOUKOKUSHO_BUNRUI_CD IN /*HOUKOKUSHO_BUNRUI_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'廃棄種類マスタ' AS NAME FROM M_HAIKI_SHURUI WHERE HOUKOKUSHO_BUNRUI_CD IN /*HOUKOKUSHO_BUNRUI_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'品名マスタ' AS NAME FROM M_HINMEI WHERE HOUKOKUSHO_BUNRUI_CD IN /*HOUKOKUSHO_BUNRUI_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'マニフェスト換算値マスタ' AS NAME FROM M_MANIFEST_KANSAN WHERE HOUKOKUSHO_BUNRUI_CD IN /*HOUKOKUSHO_BUNRUI_CD*/('') AND DELETE_FLG = 'False'
