SELECT GTH.*
		,ISNULL(H1.HINMEI_NAME_RYAKU,N'') AS HINMEI_NAME_RYAKU
		,ISNULL(H2.HINMEI_NAME_RYAKU,N'') AS TSUKI_HINMEI_NAME_RYAKU
		,ISNULL(U1.UNIT_NAME_RYAKU,N'') AS UNIT_NAME_RYAKU
		,ISNULL(U2.UNIT_NAME_RYAKU,N'') AS KANSAN_UNIT_NAME_RYAKU
--		,ISNULL(Y.YOUKI_NAME_RYAKU,N'') AS YOUKI_NAME_RYAKU
		,ISNULL(D.DENPYOU_KBN_NAME_RYAKU,N'') AS DENPYOU_KBN_NAME_RYAKU
		,CONVERT(nvarchar, N'') KEIYAKU_KBN_NAME
		,CONVERT(nvarchar, N'') KEIJYOU_KBN_NAME
  FROM M_HIKIAI_GENBA_TEIKI_HINMEI GTH
	LEFT JOIN M_HINMEI H1 ON H1.HINMEI_CD = GTH.HINMEI_CD
	LEFT JOIN M_HINMEI H2 ON H2.HINMEI_CD = GTH.TSUKI_HINMEI_CD
	LEFT JOIN M_UNIT U1 ON U1.UNIT_CD = GTH.UNIT_CD
	LEFT JOIN M_UNIT U2 ON U2.UNIT_CD = GTH.KANSAN_UNIT_CD
--	LEFT JOIN M_YOUKI Y ON Y.YOUKI_CD = GTH.YOUKI_CD
	LEFT JOIN M_DENPYOU_KBN D ON D.DENPYOU_KBN_CD = GTH.DENPYOU_KBN_CD
 WHERE GTH.HIKIAI_GYOUSHA_USE_FLG = /*data.HIKIAI_GYOUSHA_USE_FLG*/''
   AND GTH.GYOUSHA_CD = /*data.GYOUSHA_CD*/''
   AND GTH.GENBA_CD = /*data.GENBA_CD*/''
 ORDER BY GTH.ROW_NO ASC