SELECT GTH.*
		,ISNULL(H.HINMEI_NAME_RYAKU,N'') AS HINMEI_NAME_RYAKU
		,ISNULL(U.UNIT_NAME_RYAKU,N'') AS UNIT_NAME_RYAKU
		,ISNULL(D.DENPYOU_KBN_NAME_RYAKU,N'') AS DENPYOU_KBN_NAME_RYAKU
  FROM M_HIKIAI_GENBA_TSUKI_HINMEI GTH
	LEFT JOIN M_HINMEI H ON H.HINMEI_CD = GTH.HINMEI_CD
	LEFT JOIN M_UNIT U ON U.UNIT_CD = GTH.UNIT_CD
	LEFT JOIN M_DENPYOU_KBN D ON D.DENPYOU_KBN_CD = GTH.DENPYOU_KBN_CD
 WHERE GTH.HIKIAI_GYOUSHA_USE_FLG = /*data.HIKIAI_GYOUSHA_USE_FLG*/''
   AND GTH.GYOUSHA_CD = /*data.GYOUSHA_CD*/''
   AND GTH.GENBA_CD = /*data.GENBA_CD*/''
 ORDER BY GTH.ROW_NO ASC