SELECT 
 M_DENSHI_JIGYOUJOU.EDI_MEMBER_ID, 
 M_DENSHI_JIGYOUSHA.JIGYOUSHA_NAME, 

 M_DENSHI_JIGYOUJOU.JIGYOUJOU_CD , 
 M_DENSHI_JIGYOUJOU.JIGYOUJOU_NAME , 
 M_DENSHI_JIGYOUJOU.JIGYOUJOU_POST , 
 M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS1 TODOFUKEN_NAME, 
 ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS2,N'') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS3, N'') JIGYOUJOU_ADDRESS, 
 M_DENSHI_JIGYOUJOU.JIGYOUJOU_TEL , 

 M_DENSHI_JIGYOUSHA.JIGYOUSHA_POST , 
 M_DENSHI_JIGYOUSHA.JIGYOUSHA_TEL , 
 M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS1 , 
 M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS2 , 
 M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS3 , 
 M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS4 ,

 M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS1 , 
 M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS2 , 
 M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS3 , 
 M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS4 
 
 FROM M_DENSHI_JIGYOUJOU
 LEFT JOIN M_DENSHI_JIGYOUSHA ON M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID = M_DENSHI_JIGYOUJOU.EDI_MEMBER_ID
 LEFT JOIN M_GYOUSHA ON M_DENSHI_JIGYOUJOU.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
 LEFT JOIN M_GENBA ON M_DENSHI_JIGYOUJOU.GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND M_DENSHI_JIGYOUJOU.GENBA_CD = M_GENBA.GENBA_CD 
