SELECT
    DISTINCT M_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU, 
    M_GENBA.GYOUSHA_CD, 
    M_GYOUSHA.GYOUSHA_NAME_RYAKU, 
    M_GENBA.GENBA_CD, 
    M_GENBA.GENBA_NAME_RYAKU, 
    M_TODOUFUKEN2.TODOUFUKEN_NAME_RYAKU, 
    M_GENBA.GENBA_ADDRESS1, 
    M_GENBA.GENBA_FURIGANA, 
    M_GENBA.GENBA_POST, 
    M_GENBA.GENBA_TEL, 
    M_GENBA.GENBA_NAME1, 
    M_GENBA.GENBA_NAME2, 
    M_GENBA.GENBA_ADDRESS2, 
    M_GYOUSHA.GYOUSHA_NAME1, 
    M_GYOUSHA.GYOUSHA_NAME2, 
    M_GYOUSHA.GYOUSHA_ADDRESS1, 
    M_GYOUSHA.GYOUSHA_ADDRESS2, 
    M_GYOUSHA.TORIHIKISAKI_CD, 
    M_TORIHIKISAKI.TORIHIKISAKI_NAME2, 
    M_TORIHIKISAKI.TORIHIKISAKI_ADDRESS1, 
    M_TORIHIKISAKI.TORIHIKISAKI_ADDRESS2, 
    M_TODOUFUKEN.TODOUFUKEN_NAME_RYAKU GYOUSHA_TODOUFUKEN_NAME_RYAKU, 
    M_TODOUFUKEN2.TODOUFUKEN_NAME_RYAKU GENBA_TODOUFUKEN_NAME_RYAKU 
FROM
    M_GENBA
    LEFT JOIN
        M_GYOUSHA ON
        M_GENBA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
    LEFT JOIN
        M_TODOUFUKEN ON
        M_GYOUSHA.GYOUSHA_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD AND
        M_TODOUFUKEN.DELETE_FLG = 0
    LEFT JOIN
        M_TODOUFUKEN M_TODOUFUKEN2 ON
        M_GENBA.GENBA_TODOUFUKEN_CD = M_TODOUFUKEN2.TODOUFUKEN_CD AND
        M_TODOUFUKEN2.DELETE_FLG = 0
    LEFT JOIN
        M_TORIHIKISAKI ON
        M_TORIHIKISAKI.TORIHIKISAKI_CD = M_GYOUSHA.TORIHIKISAKI_CD