SELECT 
 M_HIKIAI_GENBA.GYOUSHA_CD, 
 CASE M_HIKIAI_GENBA.HIKIAI_GYOUSHA_USE_FLG 
 WHEN '0' THEN M_GYOUSHA.GYOUSHA_NAME_RYAKU 
 ELSE M_HIKIAI_GYOUSHA.GYOUSHA_NAME_RYAKU 
 END AS GYOUSHA_NAME_RYAKU, 
 M_HIKIAI_GENBA.GENBA_CD, 
 M_HIKIAI_GENBA.GENBA_NAME_RYAKU, 
 M_HIKIAI_GENBA.GENBA_FURIGANA, 
 M_HIKIAI_GENBA.GENBA_POST, 
 M_TODOUFUKEN.TODOUFUKEN_NAME_RYAKU, 
 M_HIKIAI_GENBA.GENBA_ADDRESS1, 
 M_HIKIAI_GENBA.GENBA_TEL, 
 M_HIKIAI_GENBA.HIKIAI_GYOUSHA_USE_FLG AS GYOUSHA_HIKIAI_FLG, 
'1' AS GENBA_HIKIAI_FLG, 
 M_TODOUFUKEN.TODOUFUKEN_NAME_RYAKU AS GYOUSHA_TODOUFUKEN_NAME_RYAKU, 
 M_TODOUFUKEN2.TODOUFUKEN_NAME_RYAKU AS GENBA_TODOUFUKEN_NAME_RYAKU 

 FROM M_HIKIAI_GENBA 

 LEFT JOIN M_GYOUSHA ON M_HIKIAI_GENBA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD 

 LEFT JOIN M_HIKIAI_GYOUSHA ON M_HIKIAI_GENBA.GYOUSHA_CD = M_HIKIAI_GYOUSHA.GYOUSHA_CD 

 LEFT JOIN M_TODOUFUKEN ON M_HIKIAI_GYOUSHA.GYOUSHA_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD 
 AND M_TODOUFUKEN.DELETE_FLG = 0 

 LEFT JOIN M_TODOUFUKEN M_TODOUFUKEN2 ON M_HIKIAI_GENBA.GENBA_TODOUFUKEN_CD = M_TODOUFUKEN2.TODOUFUKEN_CD 
 AND M_TODOUFUKEN2.DELETE_FLG = 0 

 LEFT JOIN M_HIKIAI_TORIHIKISAKI ON  M_HIKIAI_TORIHIKISAKI.TORIHIKISAKI_CD = M_HIKIAI_GYOUSHA.TORIHIKISAKI_CD 

 LEFT JOIN M_DENSHI_JIGYOUJOU ON M_DENSHI_JIGYOUJOU.GYOUSHA_CD = M_HIKIAI_GENBA.GYOUSHA_CD AND M_DENSHI_JIGYOUJOU.GENBA_CD = M_HIKIAI_GENBA.GENBA_CD
 LEFT JOIN M_DENSHI_JIGYOUSHA ON M_DENSHI_JIGYOUSHA.GYOUSHA_CD = M_HIKIAI_GYOUSHA.GYOUSHA_CD AND M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID = M_DENSHI_JIGYOUJOU.EDI_MEMBER_ID 
