SELECT M_HIKIAI_GYOUSHA.GYOUSHA_CD, M_HIKIAI_GYOUSHA.GYOUSHA_NAME_RYAKU FROM dbo.M_HIKIAI_GYOUSHA AS M_HIKIAI_GYOUSHA
WHERE 
/*IF data.ISNOT_NEED_DELETE_FLG.IsTrue*/
1 = 1
-- ELSE
((TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= TEKIYOU_END) or (TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and TEKIYOU_END IS NULL) or (TEKIYOU_BEGIN IS NULL and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= TEKIYOU_END) or (TEKIYOU_BEGIN IS NULL and TEKIYOU_END IS NULL))
AND DELETE_FLG = 0
/*END*/
/*IF data.GYOUSHA_CD != null*/AND GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/
/*IF !data.TORIHIKISAKI_UMU_KBN.IsNull*/AND TORIHIKISAKI_UMU_KBN = /*data.TORIHIKISAKI_UMU_KBN.Value*//*END*/
/*IF !data.GYOUSHAKBN_MITSUMORI.IsNull*/ AND GYOUSHAKBN_MITSUMORI = /*data.GYOUSHAKBN_MITSUMORI*//*END*/
/*IF !data.GYOUSHAKBN_SHUKKA.IsNull*/ AND GYOUSHAKBN_SHUKKA = /*data.GYOUSHAKBN_SHUKKA*//*END*/
/*IF !data.GYOUSHAKBN_MANI.IsNull*/ AND GYOUSHAKBN_MANI = /*data.GYOUSHAKBN_MANI*//*END*/
/*IF data.TORIHIKISAKI_CD != null*/AND TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*//*END*/
/*IF !data.KYOTEN_CD.IsNull*/AND KYOTEN_CD = /*data.KYOTEN_CD.Value*//*END*/
/*IF data.GYOUSHA_NAME1 != null*/AND GYOUSHA_NAME1 = /*data.GYOUSHA_NAME1*//*END*/
/*IF data.GYOUSHA_NAME2 != null*/AND GYOUSHA_NAME2 = /*data.GYOUSHA_NAME2*//*END*/
/*IF data.GYOUSHA_NAME_RYAKU != null*/AND GYOUSHA_NAME_RYAKU = /*data.GYOUSHA_NAME_RYAKU*//*END*/
/*IF data.GYOUSHA_FURIGANA != null*/AND GYOUSHA_FURIGANA = /*data.GYOUSHA_FURIGANA*//*END*/
/*IF data.GYOUSHA_TEL != null*/AND GYOUSHA_TEL = /*data.GYOUSHA_TEL*//*END*/
/*IF data.GYOUSHA_FAX != null*/AND GYOUSHA_FAX = /*data.GYOUSHA_FAX*//*END*/
/*IF data.GYOUSHA_KEITAI_TEL != null*/AND GYOUSHA_KEITAI_TEL = /*data.GYOUSHA_KEITAI_TEL*//*END*/
/*IF data.GYOUSHA_KEISHOU1 != null*/AND GYOUSHA_KEISHOU1 = /*data.GYOUSHA_KEISHOU1*//*END*/
/*IF data.GYOUSHA_KEISHOU2 != null*/AND GYOUSHA_KEISHOU2 = /*data.GYOUSHA_KEISHOU2*//*END*/
/*IF data.EIGYOU_TANTOU_BUSHO_CD != null*/AND EIGYOU_TANTOU_BUSHO_CD = /*data.EIGYOU_TANTOU_BUSHO_CD*//*END*/
/*IF data.EIGYOU_TANTOU_CD != null*/AND EIGYOU_TANTOU_CD = /*data.EIGYOU_TANTOU_CD*//*END*/
/*IF data.GYOUSHA_POST != null*/AND GYOUSHA_POST = /*data.GYOUSHA_POST*//*END*/
/*IF !data.GYOUSHA_TODOUFUKEN_CD.IsNull*/AND GYOUSHA_TODOUFUKEN_CD = /*data.GYOUSHA_TODOUFUKEN_CD.Value*//*END*/
/*IF data.GYOUSHA_ADDRESS1 != null*/AND GYOUSHA_ADDRESS1 = /*data.GYOUSHA_ADDRESS1*//*END*/
/*IF data.GYOUSHA_ADDRESS2 != null*/AND GYOUSHA_ADDRESS2 = /*data.GYOUSHA_ADDRESS2*//*END*/
/*IF !data.TORIHIKI_JOUKYOU.IsNull*/AND TORIHIKI_JOUKYOU = /*data.TORIHIKI_JOUKYOU.Value*//*END*/
/*IF data.CHUUSHI_RIYUU1 != null*/AND CHUUSHI_RIYUU1 = /*data.CHUUSHI_RIYUU1*//*END*/
/*IF data.CHUUSHI_RIYUU2 != null*/AND CHUUSHI_RIYUU2 = /*data.CHUUSHI_RIYUU2*//*END*/
/*IF data.BUSHO != null*/AND BUSHO = /*data.BUSHO*//*END*/
/*IF data.TANTOUSHA != null*/AND TANTOUSHA = /*data.TANTOUSHA*//*END*/
/*IF data.SHUUKEI_ITEM_CD != null*/AND SHUUKEI_ITEM_CD = /*data.SHUUKEI_ITEM_CD*//*END*/
/*IF data.GYOUSHU_CD != null*/AND GYOUSHU_CD = /*data.GYOUSHU_CD*//*END*/
/*IF data.CHIIKI_CD != null*/AND CHIIKI_CD = /*data.CHIIKI_CD*//*END*/
/*IF data.BIKOU1 != null*/AND BIKOU1 = /*data.BIKOU1*//*END*/
/*IF data.BIKOU2 != null*/AND BIKOU2 = /*data.BIKOU2*//*END*/
/*IF data.BIKOU3 != null*/AND BIKOU3 = /*data.BIKOU3*//*END*/
/*IF data.BIKOU4 != null*/AND BIKOU4 = /*data.BIKOU4*//*END*/
/*IF data.SEIKYUU_SOUFU_NAME1 != null*/AND SEIKYUU_SOUFU_NAME1 = /*data.SEIKYUU_SOUFU_NAME1*//*END*/
/*IF data.SEIKYUU_SOUFU_NAME2 != null*/AND SEIKYUU_SOUFU_NAME2 = /*data.SEIKYUU_SOUFU_NAME2*//*END*/
/*IF data.SEIKYUU_SOUFU_KEISHOU1 != null*/AND SEIKYUU_SOUFU_KEISHOU1 = /*data.SEIKYUU_SOUFU_KEISHOU1*//*END*/
/*IF data.SEIKYUU_SOUFU_KEISHOU2 != null*/AND SEIKYUU_SOUFU_KEISHOU2 = /*data.SEIKYUU_SOUFU_KEISHOU2*//*END*/
/*IF data.SEIKYUU_SOUFU_POST != null*/AND SEIKYUU_SOUFU_POST = /*data.SEIKYUU_SOUFU_POST*//*END*/
/*IF data.SEIKYUU_SOUFU_ADDRESS1 != null*/AND SEIKYUU_SOUFU_ADDRESS1 = /*data.SEIKYUU_SOUFU_ADDRESS1*//*END*/
/*IF data.SEIKYUU_SOUFU_ADDRESS2 != null*/AND SEIKYUU_SOUFU_ADDRESS2 = /*data.SEIKYUU_SOUFU_ADDRESS2*//*END*/
/*IF data.SEIKYUU_SOUFU_BUSHO != null*/AND SEIKYUU_SOUFU_BUSHO = /*data.SEIKYUU_SOUFU_BUSHO*//*END*/
/*IF data.SEIKYUU_SOUFU_TANTOU != null*/AND SEIKYUU_SOUFU_TANTOU = /*data.SEIKYUU_SOUFU_TANTOU*//*END*/
/*IF data.SEIKYUU_SOUFU_TEL != null*/AND SEIKYUU_SOUFU_TEL = /*data.SEIKYUU_SOUFU_TEL*//*END*/
/*IF data.SEIKYUU_SOUFU_FAX != null*/AND SEIKYUU_SOUFU_FAX = /*data.SEIKYUU_SOUFU_FAX*//*END*/
/*IF data.SEIKYUU_TANTOU != null*/AND SEIKYUU_TANTOU = /*data.SEIKYUU_TANTOU*//*END*/
/*IF !data.SEIKYUU_DAIHYOU_PRINT_KBN.IsNull*/AND SEIKYUU_DAIHYOU_PRINT_KBN = /*data.SEIKYUU_DAIHYOU_PRINT_KBN.Value*//*END*/
/*IF data.SHIHARAI_SOUFU_NAME1 != null*/AND SHIHARAI_SOUFU_NAME1 = /*data.SHIHARAI_SOUFU_NAME1*//*END*/
/*IF data.SHIHARAI_SOUFU_NAME2 != null*/AND SHIHARAI_SOUFU_NAME2 = /*data.SHIHARAI_SOUFU_NAME2*//*END*/
/*IF data.SHIHARAI_SOUFU_KEISHOU1 != null*/AND SHIHARAI_SOUFU_KEISHOU1 = /*data.SHIHARAI_SOUFU_KEISHOU1*//*END*/
/*IF data.SHIHARAI_SOUFU_KEISHOU2 != null*/AND SHIHARAI_SOUFU_KEISHOU2 = /*data.SHIHARAI_SOUFU_KEISHOU2*//*END*/
/*IF data.SHIHARAI_SOUFU_POST != null*/AND SHIHARAI_SOUFU_POST = /*data.SHIHARAI_SOUFU_POST*//*END*/
/*IF data.SHIHARAI_SOUFU_ADDRESS1 != null*/AND SHIHARAI_SOUFU_ADDRESS1 = /*data.SHIHARAI_SOUFU_ADDRESS1*//*END*/
/*IF data.SHIHARAI_SOUFU_ADDRESS2 != null*/AND SHIHARAI_SOUFU_ADDRESS2 = /*data.SHIHARAI_SOUFU_ADDRESS2*//*END*/
/*IF data.SHIHARAI_SOUFU_BUSHO != null*/AND SHIHARAI_SOUFU_BUSHO = /*data.SHIHARAI_SOUFU_BUSHO*//*END*/
/*IF data.SHIHARAI_SOUFU_TANTOU != null*/AND SHIHARAI_SOUFU_TANTOU = /*data.SHIHARAI_SOUFU_TANTOU*//*END*/
/*IF data.SHIHARAI_SOUFU_TEL != null*/AND SHIHARAI_SOUFU_TEL = /*data.SHIHARAI_SOUFU_TEL*//*END*/
/*IF data.SHIHARAI_SOUFU_FAX != null*/AND SHIHARAI_SOUFU_FAX = /*data.SHIHARAI_SOUFU_FAX*//*END*/
/*IF !data.JISHA_KBN.IsNull*/ AND JISHA_KBN = /*data.JISHA_KBN*//*END*/
/*IF !data.HAISHUTSU_NIZUMI_GYOUSHA_KBN.IsNull*/ AND HAISHUTSU_NIZUMI_GYOUSHA_KBN = /*data.HAISHUTSU_NIZUMI_GYOUSHA_KBN*//*END*/
/*IF !data.UNPAN_JUTAKUSHA_KAISHA_KBN.IsNull*/ AND UNPAN_JUTAKUSHA_KAISHA_KBN = /*data.UNPAN_JUTAKUSHA_KAISHA_KBN*//*END*/
/*IF !data.SHOBUN_NIOROSHI_GYOUSHA_KBN.IsNull*/ AND SHOBUN_NIOROSHI_GYOUSHA_KBN = /*data.SHOBUN_NIOROSHI_GYOUSHA_KBN*//*END*/
/*IF !data.MANI_HENSOUSAKI_KBN.IsNull*/ AND MANI_HENSOUSAKI_KBN = /*data.MANI_HENSOUSAKI_KBN*//*END*/
/*IF !data.SHOKUCHI_KBN.IsNull*/ AND SHOKUCHI_KBN = /*data.SHOKUCHI_KBN*//*END*/
/*IF !data.TEKIYOU_BEGIN.IsNull*/AND TEKIYOU_BEGIN = /*data.TEKIYOU_BEGIN.Value*//*END*/
/*IF !data.TEKIYOU_END.IsNull*/AND TEKIYOU_END = /*data.TEKIYOU_END.Value*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
/*IF !data.HAISHUTSU_NIZUMI_GYOUSHA_KBN.IsNull*/ AND HAISHUTSU_NIZUMI_GYOUSHA_KBN = /*data.HAISHUTSU_NIZUMI_GYOUSHA_KBN*//*END*/
/*IF !data.UNPAN_JUTAKUSHA_KAISHA_KBN.IsNull*/ AND UNPAN_JUTAKUSHA_KAISHA_KBN = /*data.UNPAN_JUTAKUSHA_KAISHA_KBN*//*END*/
/*IF !data.SHOBUN_NIOROSHI_GYOUSHA_KBN.IsNull*/ AND SHOBUN_NIOROSHI_GYOUSHA_KBN = /*data.SHOBUN_NIOROSHI_GYOUSHA_KBN*//*END*/