SELECT
	MCN.NIOROSHI_NO AS NIOROSHI_NUMBER
	,MCN.NIOROSHI_GYOUSHA_CD
	,MGY.GYOUSHA_NAME_RYAKU AS NIOROSHI_GYOUSHA_NAME_RYAKU
	,MCN.NIOROSHI_GENBA_CD
	,MGB.GENBA_NAME_RYAKU AS NIOROSHI_GENBA_NAME_RYAKU
FROM M_COURSE_NIOROSHI MCN
	LEFT JOIN M_GYOUSHA MGY
		ON MGY.GYOUSHA_CD = MCN.NIOROSHI_GYOUSHA_CD
	LEFT JOIN M_GENBA MGB
		ON MGB.GYOUSHA_CD = MCN.NIOROSHI_GYOUSHA_CD
        AND MGB.GENBA_CD = MCN.NIOROSHI_GENBA_CD
WHERE 
	MCN.COURSE_NAME_CD = /*data.CourseNameCd*/
	/*IF data.DayCd != null && data.DayCd !='' */ AND MCN.DAY_CD = /*data.DayCd*/ /*END*/
ORDER BY
	MCN.NIOROSHI_NO