SELECT 
MC.SHASHU_CD,
MSH.SHASHU_NAME_RYAKU,
MC.SHARYOU_CD,
MSY.SHARYOU_NAME_RYAKU,
MC.UNTENSHA_CD,
MSA.SHAIN_NAME_RYAKU,
MC.UNPAN_GYOUSHA_CD,
MGY.GYOUSHA_NAME_RYAKU,
MC.SHUPPATSU_GYOUSHA_CD,
MGY_SHU.GYOUSHA_NAME_RYAKU AS SHUPPATSU_GYOUSHA_NAME,
MC.SHUPPATSU_GENBA_CD,
MGE_SHU.GENBA_NAME_RYAKU AS SHUPPATSU_GENBA_NAME,
MC.SAGYOU_BEGIN_HOUR,
MC.SAGYOU_BEGIN_MINUTE,
MC.SAGYOU_END_HOUR,
MC.SAGYOU_END_MINUTE
FROM M_COURSE MC
LEFT JOIN M_SHASHU MSH ON MC.SHASHU_CD = MSH.SHASHU_CD
LEFT JOIN M_SHARYOU MSY ON ((MC.SHARYOU_CD = MSY.SHARYOU_CD) AND (MC.UNPAN_GYOUSHA_CD = MSY.GYOUSHA_CD))
LEFT JOIN M_SHAIN  MSA ON MC.UNTENSHA_CD = MSA.SHAIN_CD
LEFT JOIN M_GYOUSHA MGY ON MC.UNPAN_GYOUSHA_CD = MGY.GYOUSHA_CD
LEFT JOIN M_GYOUSHA MGY_SHU ON MC.SHUPPATSU_GYOUSHA_CD = MGY_SHU.GYOUSHA_CD
LEFT JOIN M_GENBA MGE_SHU ON MC.SHUPPATSU_GYOUSHA_CD = MGE_SHU.GYOUSHA_CD AND MC.SHUPPATSU_GENBA_CD = MGE_SHU.GENBA_CD
WHERE 
MC.DELETE_FLG = 0
/*IF data.DayCd != null && data.DayCd !='' */ AND MC.DAY_CD = /*data.DayCd*/ /*END*/
AND MC.COURSE_NAME_CD = /*data.CourseNameCd*/