SELECT 
	TTHE.*
	,MK.KYOTEN_NAME_RYAKU
	,MCN.COURSE_NAME_RYAKU
	,MSHARYOU.SHARYOU_NAME_RYAKU
	,MSHASHU.SHASHU_NAME_RYAKU
	,UNTENSHA.SHAIN_NAME_RYAKU AS UNTENSHA_NAME
	,HOJOIN.SHAIN_NAME_RYAKU AS HOJOIN_NAME
	,UNPAN_GYOUSHA.GYOUSHA_NAME_RYAKU AS UNPAN_GYOUSHA_NAME
	,SHUPPATSU_GYOUSHA.GYOUSHA_NAME_RYAKU AS SHUPPATSU_GYOUSHA_NAME
	,SHUPPATSU_GENBA.GENBA_NAME_RYAKU AS SHUPPATSU_GENBA_NAME
FROM
	T_TEIKI_HAISHA_ENTRY TTHE
	LEFT JOIN M_KYOTEN MK
		ON TTHE.KYOTEN_CD = MK.KYOTEN_CD
	LEFT JOIN M_COURSE_NAME MCN
		ON TTHE.COURSE_NAME_CD = MCN.COURSE_NAME_CD
	LEFT JOIN M_SHARYOU MSHARYOU
		ON MSHARYOU.GYOUSHA_CD = TTHE.UNPAN_GYOUSHA_CD
		AND TTHE.SHARYOU_CD = MSHARYOU.SHARYOU_CD
	LEFT JOIN M_SHASHU MSHASHU
		ON TTHE.SHASHU_CD = MSHASHU.SHASHU_CD
	LEFT JOIN M_SHAIN UNTENSHA
		ON TTHE.UNTENSHA_CD = UNTENSHA.SHAIN_CD
	LEFT JOIN M_GYOUSHA UNPAN_GYOUSHA
		ON TTHE.UNPAN_GYOUSHA_CD = UNPAN_GYOUSHA.GYOUSHA_CD
	LEFT JOIN M_SHAIN HOJOIN
		ON TTHE.HOJOIN_CD = HOJOIN.SHAIN_CD
	LEFT JOIN M_GYOUSHA SHUPPATSU_GYOUSHA
		ON TTHE.SHUPPATSU_GYOUSHA_CD = SHUPPATSU_GYOUSHA.GYOUSHA_CD
	LEFT JOIN M_GENBA SHUPPATSU_GENBA
		ON TTHE.SHUPPATSU_GYOUSHA_CD = SHUPPATSU_GENBA.GYOUSHA_CD AND TTHE.SHUPPATSU_GENBA_CD = SHUPPATSU_GENBA.GENBA_CD
WHERE
	TTHE.TEIKI_HAISHA_NUMBER = /*data.TeikiHaishaNumber*/
	AND TTHE.DELETE_FLG = 0