SELECT DISTINCT
      RT.HAISHA_DENPYOU_NO
     ,SHOS.NIOROSHI_NUMBER
     ,HN.HANYU_SEQ_NO
FROM 
     T_MOBISYO_RT RT
     LEFT JOIN T_MOBISYO_RT_DTL DTL ON RT.SEQ_NO = DTL.SEQ_NO AND DTL.DELETE_FLG = 0
     LEFT JOIN T_MOBISYO_RT_HANNYUU HN ON DTL.HANYU_SEQ_NO = HN.HANYU_SEQ_NO AND HN.DELETE_FLG = 0
     LEFT JOIN T_TEIKI_HAISHA_ENTRY ENT ON RT.HAISHA_DENPYOU_NO = ENT.TEIKI_HAISHA_NUMBER AND ENT.DELETE_FLG = 0
     LEFT JOIN T_TEIKI_HAISHA_DETAIL DET ON ENT.SYSTEM_ID = DET.SYSTEM_ID AND ENT.SEQ = DET.SEQ AND RT.HAISHA_ROW_NUMBER = DET.ROW_NUMBER
	 LEFT JOIN T_TEIKI_HAISHA_SHOUSAI SHOS ON SHOS.SYSTEM_ID = DET.SYSTEM_ID AND SHOS.SEQ = DET.SEQ AND SHOS.DETAIL_SYSTEM_ID = DET.DETAIL_SYSTEM_ID
WHERE 
     RT.DELETE_FLG = 0
     AND RT.HAISHA_KBN = 0
     AND SHOS.NIOROSHI_NUMBER IS NOT NULL
	 AND HN.HANYU_SEQ_NO IS NOT NULL
     AND RT.HAISHA_DENPYOU_NO = /*TEIKI_HAISHA_NUMBER*/