SELECT 
	TTHS.DETAIL_SYSTEM_ID AS REC_ID
	,TTHS.ROW_NUMBER AS REC_SEQ
	,TTHS.HINMEI_CD
	,MH.HINMEI_NAME_RYAKU
	,TTHS.UNIT_CD
	,MU.UNIT_NAME_RYAKU
	,TTHS.KANSANCHI
	,TTHS.KANSAN_UNIT_CD

	,TTHS.KEIYAKU_KBN                   --契約区分
	,TTHS.KEIJYOU_KBN                   --計上区分
	,TTHS.DENPYOU_KBN_CD                --伝票区分CD
	,TTHS.KANSAN_UNIT_MOBILE_OUTPUT_FLG --換算後単位モバイル出力フラグ
	,TTHS.INPUT_KBN
	,TTHS.NIOROSHI_NUMBER
	,TTHS.ANBUN_FLG
FROM
	T_TEIKI_HAISHA_SHOUSAI TTHS
	LEFT JOIN M_HINMEI MH
		ON TTHS.HINMEI_CD = MH.HINMEI_CD
	LEFT JOIN M_UNIT MU
		ON TTHS.UNIT_CD = MU.UNIT_CD
WHERE
	TTHS.SYSTEM_ID = /*data.SystemId*/
	AND TTHS.SEQ = /*data.Seq*/
	AND TTHS.DETAIL_SYSTEM_ID = /*data.DetailSystemId*/
ORDER BY
	TTHS.ROW_NUMBER