SELECT 
ENT.TEIKI_HAISHA_NUMBER 
FROM 
T_TEIKI_HAISHA_ENTRY ENT
LEFT JOIN T_TEIKI_HAISHA_DETAIL DET ON ENT.SYSTEM_ID = DET.SYSTEM_ID AND ENT.SEQ = DET.SEQ
LEFT JOIN M_GYOUSHA ON DET.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD 
WHERE 
ENT.TEIKI_HAISHA_NUMBER = /*TEIKI_HAISHA_NUMBER*/ 
AND ENT.DELETE_FLG = 0
AND M_GYOUSHA.TORIHIKISAKI_UMU_KBN = 2