SELECT * FROM M_CONTENA
 where DELETE_FLG = 0
 /*IF data.CONTENA_SHURUI_CD != null*/ AND CONTENA_SHURUI_CD = /*data.CONTENA_SHURUI_CD*//*END*/
 /*IF data.CONTENA_CD != null*/ AND CONTENA_CD = /*data.CONTENA_CD*//*END*/
