 SELECT TB1.DAISUU_CNT
  FROM T_CONTENA_RESERVE AS TB1 INNER JOIN
      (SELECT MAX(SYSTEM_ID) AS SYSTEM_ID
         FROM T_CONTENA_RESERVE
	WHERE DELETE_FLG = 0
	/*IF data.CONTENA_SET_KBN != null*/ AND CONTENA_SET_KBN = /*data.CONTENA_SET_KBN*//*END*/
	/*IF data.CONTENA_SHURUI_CD != null*/ AND CONTENA_SHURUI_CD = /*data.CONTENA_SHURUI_CD*//*END*/
	/*IF data.CONTENA_CD != null*/ AND CONTENA_CD = /*data.CONTENA_CD*//*END*/
	   ) AS TB2
	   ON   TB1.SYSTEM_ID = TB2.SYSTEM_ID