 SELECT TB1.HINMEI_CD
  FROM M_COURSE_DETAIL_ITEMS AS TB1 INNER JOIN
      (SELECT MAX(TIME_STAMP) AS TIME_STAMP
         FROM M_COURSE_DETAIL_ITEMS
        WHERE
        /*IF data.COURSE_NAME_CD != 0*/COURSE_NAME_CD = /*data.COURSE_NAME_CD*//*END*/
	   ) AS TB2
	   ON   TB1.TIME_STAMP = TB2.TIME_STAMP