SELECT 
 ENTRY.TEIKI_HAISHA_NUMBER
,DETAIL.ROW_NUMBER AS DETAIL_ROW_NUMBER
,DETAIL.GYOUSHA_CD
,DETAIL.GENBA_CD
,SHOUSAI.ROW_NUMBER AS SHOUSAI_ROW_NUMBER
,SHOUSAI.HINMEI_CD
FROM T_TEIKI_HAISHA_ENTRY AS ENTRY
INNER JOIN T_TEIKI_HAISHA_DETAIL AS DETAIL
ON ENTRY.SYSTEM_ID = DETAIL.SYSTEM_ID AND ENTRY.SEQ = DETAIL.SEQ
INNER JOIN T_TEIKI_HAISHA_SHOUSAI AS SHOUSAI
ON DETAIL.SYSTEM_ID = SHOUSAI.SYSTEM_ID AND DETAIL.SEQ = SHOUSAI.SEQ AND DETAIL.DETAIL_SYSTEM_ID = SHOUSAI.DETAIL_SYSTEM_ID
WHERE ENTRY.DELETE_FLG = 0
AND ENTRY.TEIKI_HAISHA_NUMBER = /*haishaNum*/
ORDER BY DETAIL_ROW_NUMBER, SHOUSAI.HINMEI_CD
