SELECT M_SHARYOU.SHARYOU_NAME_RYAKU, M_SHASHU.SHASHU_CD, M_SHASHU.SHASHU_NAME_RYAKU
FROM M_SHARYOU
INNER JOIN M_SHASHU ON M_SHARYOU.SHASYU_CD = M_SHASHU.SHASHU_CD
WHERE M_SHARYOU.GYOUSHA_CD = /*gyoushaCD*/ AND M_SHARYOU.SHARYOU_CD = /*sharyouCD*/
