SELECT M_GYOUSHU.GYOUSHU_CD, M_GYOUSHU.GYOUSHU_NAME_RYAKU FROM dbo.M_GYOUSHU AS M_GYOUSHU
WHERE DELETE_FLG = 0
/*IF data.GYOUSHU_CD != null*/AND GYOUSHU_CD = /*data.GYOUSHU_CD*//*END*/
/*IF data.GYOUSHU_NAME != null*/AND GYOUSHU_NAME = /*data.GYOUSHU_NAME*//*END*/
/*IF data.GYOUSHU_NAME_RYAKU != null*/AND GYOUSHU_NAME_RYAKU = /*data.GYOUSHU_NAME_RYAKU*//*END*/
/*IF data.GYOUSHU_FURIGANA != null*/AND GYOUSHU_FURIGANA = /*data.GYOUSHU_FURIGANA*//*END*/
/*IF data.GYOUSHU_BIKOU != null*/AND GYOUSHU_BIKOU = /*data.GYOUSHU_BIKOU*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
