select 
* 
from 
T_UKETSUKE_SLIP SLIP2, 
(select MAX(UKETSUKE_NO) as UKETSUKE_NO from T_UKETSUKE_SLIP where T_UKETSUKE_SLIP.UKETSUKE_NO < /*data.UKETSUKE_NO*/ 
AND T_UKETSUKE_SLIP.SLIP_GROUP_NO = /*data.SLIP_GROUP_NO*/) SLIP1 
where 
SLIP2.UKETSUKE_NO = SLIP1.UKETSUKE_NO