select 
* 
from 
T_UKETSUKE_SLIP SLIP2, 
(select MIN(UKETSUKE_NO) as UKETSUKE_NO from T_UKETSUKE_SLIP where T_UKETSUKE_SLIP.SLIP_GROUP_NO = /*groupNo*/) SLIP1 
where 
SLIP2.UKETSUKE_NO = SLIP1.UKETSUKE_NO