SELECT 
	DETAIL.SEIKYUU_NUMBER
FROM  
	T_SEIKYUU_DETAIL DETAIL,
	T_SEIKYUU_DENPYOU DENPYOU,
	T_NYUUKIN_ENTRY NYUUKIN
/*BEGIN*/
WHERE 
/*IF !deletechuFlg*/
	DETAIL.DENPYOU_SHURUI_CD = 10 AND
	DETAIL.DENPYOU_SYSTEM_ID = NYUUKIN.SYSTEM_ID AND
	DETAIL.DENPYOU_SEQ = NYUUKIN.SEQ AND
	DETAIL.DELETE_FLG = 0 AND
	DETAIL.SEIKYUU_NUMBER = DENPYOU.SEIKYUU_NUMBER AND
	DENPYOU.DELETE_FLG = 0 
/*END*/
	/*IF data.Nyukin_number != null && data.Nyukin_number != ''*/
	AND NYUUKIN.NYUUKIN_NUMBER = /*data.Nyukin_number*/ /*END*/
/*END*/