SELECT M_GYOUSHA.GYOUSHA_CD
     , M_GYOUSHA.GYOUSHA_NAME_RYAKU
     , M_GYOUSHA.GYOUSHA_POST
     , M_GYOUSHA.GYOUSHA_TEL
     , M_GYOUSHA.GYOUSHA_ADDRESS1
     , M_GYOUSHA.GYOUSHA_ADDRESS2
     , M_GYOUSHA.BIKOU1
	 , M_GYOUSHA.BIKOU2
	 , M_GYOUSHA.GYOUSHA_LATITUDE
	 , M_GYOUSHA.GYOUSHA_LONGITUDE
	 , M_TODOUFUKEN.TODOUFUKEN_NAME
  FROM M_GYOUSHA
 LEFT JOIN M_TODOUFUKEN ON M_GYOUSHA.GYOUSHA_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD
 WHERE M_GYOUSHA.DELETE_FLG = 'false'
/*IF data.GYOUSHA_CD != null && data.GYOUSHA_CD != ''*/ AND M_GYOUSHA.GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/