SELECT M_GYOUSHA.GYOUSHA_CD
     , M_GYOUSHA.GYOUSHA_NAME_RYAKU
     , M_GENBA.GENBA_CD
     , M_GENBA.GENBA_NAME_RYAKU
     , M_GENBA.GENBA_POST
     , M_GENBA.GENBA_TEL
     , M_GENBA.GENBA_ADDRESS1
     , M_GENBA.GENBA_ADDRESS2
     , M_GENBA.BIKOU1
	 , M_GENBA.BIKOU2
	 , M_GENBA.GENBA_LATITUDE
	 , M_GENBA.GENBA_LONGITUDE
	 , M_TODOUFUKEN.TODOUFUKEN_NAME
  FROM M_GYOUSHA
 INNER JOIN M_GENBA ON M_GYOUSHA.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
 LEFT JOIN M_TODOUFUKEN ON M_GENBA.GENBA_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD
 WHERE M_GYOUSHA.DELETE_FLG = 'false'
/*IF data.GYOUSHA_CD != null && data.GYOUSHA_CD != ''*/ AND M_GYOUSHA.GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/
   AND M_GENBA.DELETE_FLG = 'false'
/*IF data.GENBA_CD != null && data.GENBA_CD != ''*/ AND M_GENBA.GENBA_CD = /*data.GENBA_CD*//*END*/