SELECT
	MCDI.DAY_CD,
	MCDI.COURSE_NAME_CD,
	MCDI.REC_ID,
	MAX(MCDI.REC_SEQ) AS MAX_REC_SEQ

FROM
	M_COURSE_DETAIL_ITEMS AS MCDI 

/*BEGIN*/WHERE
/*IF !data_M_COURSE_DETAIL_ITEMS.DAY_CD.IsNull*/MCDI.DAY_CD = /*data_M_COURSE_DETAIL_ITEMS.DAY_CD*/1/*END*/
/*IF data_M_COURSE_DETAIL_ITEMS.COURSE_NAME_CD != null*/AND MCDI.COURSE_NAME_CD = /*data_M_COURSE_DETAIL_ITEMS.COURSE_NAME_CD*/'abc'/*END*/
/*IF !data_M_COURSE_DETAIL_ITEMS.REC_ID.IsNull*/AND MCDI.REC_ID = /*data_M_COURSE_DETAIL_ITEMS.REC_ID*/1/*END*/
/*END*/

GROUP BY 
	MCDI.DAY_CD,
	MCDI.COURSE_NAME_CD,
	MCDI.REC_ID