SELECT MCDI.*
FROM M_COURSE_DETAIL_ITEMS AS MCDI
/*BEGIN*/WHERE
/*IF !data.DAY_CD.IsNull*/MCDI.DAY_CD = /*data.DAY_CD*/1/*END*/
/*IF data.COURSE_NAME_CD != null*/AND MCDI.COURSE_NAME_CD = /*data.COURSE_NAME_CD*/'abc'/*END*/
/*END*/
ORDER BY 
	MCDI.REC_ID,
	MCDI.REC_SEQ