SELECT

	MCN.NIOROSHI_NO,
	MCN.NIOROSHI_GYOUSHA_CD,
		M_GYOUSHA.GYOUSHA_NAME_RYAKU,
	MCN.NIOROSHI_GENBA_CD,
		M_GENBA.GENBA_NAME_RYAKU, 
	
	MCN.DAY_CD,
	MCN.COURSE_NAME_CD,

	MCN.TIME_STAMP

FROM

	M_COURSE_NIOROSHI AS MCN 
	
	LEFT OUTER JOIN

		M_GYOUSHA 
			ON 
				MCN.NIOROSHI_GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
--/*IF !data_M_GYOUSHA.KYOTEN_CD.IsNull*/AND M_GYOUSHA.KYOTEN_CD = /*data_M_GYOUSHA.KYOTEN_CD*/1/*END*/
--				AND ( M_GYOUSHA.UNPAN_JUTAKUSHA_KBN = 1 OR M_GYOUSHA.NIOROSHI_GHOUSHA_KBN = 1 )
	
	LEFT OUTER JOIN
	
		M_GENBA
			ON
				MCN.NIOROSHI_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND MCN.NIOROSHI_GENBA_CD = M_GENBA.GENBA_CD
--/*IF !data_M_GENBA.KYOTEN_CD.IsNull*/AND M_GENBA.KYOTEN_CD = /*data_M_GENBA.KYOTEN_CD*/1/*END*/
--				AND ( M_GENBA.SHOBUN_JIGYOUJOU_KBN = 1 OR M_GENBA.SAISHUU_SHOBUNJOU_KBN = 1 OR M_GENBA.NIOROSHI_GENBA_KBN = 1 )

/*BEGIN*/WHERE
/*IF !data_M_COURSE_NIOROSHI.DAY_CD.IsNull*/MCN.DAY_CD = /*data_M_COURSE_NIOROSHI.DAY_CD*/1/*END*/
/*IF data_M_COURSE_NIOROSHI.COURSE_NAME_CD != null*/AND MCN.COURSE_NAME_CD = /*data_M_COURSE_NIOROSHI.COURSE_NAME_CD*/'abc'/*END*/
/*END*/

ORDER BY 
	MCN.NIOROSHI_NO