SELECT MCN.*
FROM M_COURSE_NIOROSHI AS MCN
/*BEGIN*/WHERE
/*IF !data.DAY_CD.IsNull*/MCN.DAY_CD = /*data.DAY_CD*/1/*END*/
/*IF data.COURSE_NAME_CD != null*/AND MCN.COURSE_NAME_CD = /*data.COURSE_NAME_CD*/'abc'/*END*/
/*END*/
ORDER BY 
	MCN.DAY_CD,
	MCN.COURSE_NAME_CD