SELECT
	MCD.DAY_CD,
	MCD.COURSE_NAME_CD,
	MAX(MCD.ROW_NO) AS MAX_ROW_NO

FROM
	M_COURSE_DETAIL AS MCD 

WHERE
	--DELETE_FLG = 0
/*IF !data_M_COURSE_DETAIL.DAY_CD.IsNull*/MCD.DAY_CD = /*data_M_COURSE_DETAIL.DAY_CD*/1/*END*/
/*IF data_M_COURSE_DETAIL.COURSE_NAME_CD != null*/AND MCD.COURSE_NAME_CD = /*data_M_COURSE_DETAIL.COURSE_NAME_CD*/'abc'/*END*/

GROUP BY 
	MCD.DAY_CD,
	MCD.COURSE_NAME_CD