SELECT
	MC.*,
	M_SHASHU.SHASHU_NAME_RYAKU AS SHASHU_NAME,
	M_SHARYOU.SHARYOU_NAME_RYAKU AS SHARYOU_NAME,
	M_SHAIN.SHAIN_NAME_RYAKU AS UNTENSHA_NAME,
	M_GYOUSHA.GYOUSHA_NAME_RYAKU AS UNPAN_GYOUSHA_NAME,
	M_COURSE_NAME.COURSE_NAME,
	SGYO.GYOUSHA_NAME_RYAKU AS SHUPPATSU_GYOUSHA_NAME,
	SGEN.GENBA_NAME_RYAKU AS SHUPPATSU_GENBA_NAME,
    'False' AS NewFlag
FROM              
	M_COURSE AS MC 
LEFT OUTER JOIN M_COURSE_NAME ON MC.COURSE_NAME_CD = M_COURSE_NAME.COURSE_NAME_CD
/*IF !data_M_COURSE_NAME.KYOTEN_CD.IsNull*/AND M_COURSE_NAME.KYOTEN_CD = /*data_M_COURSE_NAME.KYOTEN_CD*/1/*END*/
LEFT JOIN M_SHASHU ON MC.SHASHU_CD = M_SHASHU.SHASHU_CD
LEFT JOIN M_SHARYOU ON ((MC.SHARYOU_CD = M_SHARYOU.SHARYOU_CD) AND (MC.UNPAN_GYOUSHA_CD = M_SHARYOU.GYOUSHA_CD))
LEFT JOIN M_SHAIN ON MC.UNTENSHA_CD = M_SHAIN.SHAIN_CD
LEFT JOIN M_GYOUSHA ON MC.UNPAN_GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
LEFT JOIN M_GYOUSHA SGYO ON MC.SHUPPATSU_GYOUSHA_CD = SGYO.GYOUSHA_CD
LEFT JOIN M_GENBA SGEN ON MC.SHUPPATSU_GYOUSHA_CD = SGEN.GYOUSHA_CD AND MC.SHUPPATSU_GENBA_CD = SGEN.GENBA_CD
/*BEGIN*/
WHERE
/*IF !data_M_COURSE.DAY_CD.IsNull*/MC.DAY_CD = /*data_M_COURSE.DAY_CD*/1/*END*/
/*IF data_M_COURSE.COURSE_NAME_CD != null*/AND MC.COURSE_NAME_CD = /*data_M_COURSE.COURSE_NAME_CD*/'abc'/*END*/
/*END*/