SELECT
    MCD.ROW_NO,
    MCD.ROW_NO as ROW_NO2,
    MCD.ROUND_NO,
    MCD.GYOUSHA_CD,
    M_GYOUSHA.GYOUSHA_NAME_RYAKU,
    MCD.GENBA_CD,
    M_GENBA.GENBA_NAME_RYAKU,
    'è⁄ç◊' as DETAIL_BUTTON,
    '' as KAISYUUHIN_NAME,
    MCD.BIKOU,
    MCD.DAY_CD,
    MCD.COURSE_NAME_CD,
    MCD.REC_ID,
    ISNULL(LEFT(CONVERT(varchar, MCD.KIBOU_TIME, 114), 5),'') AS KIBOU_TIME,
    MCD.SAGYOU_TIME_MINUTE,
    MCD.TIME_STAMP,
    'False' AS NewFlag
FROM
    M_COURSE_DETAIL AS MCD
    LEFT OUTER JOIN
        M_GYOUSHA
    ON  MCD.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
    LEFT OUTER JOIN
        M_GENBA
    ON  MCD.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
    AND MCD.GENBA_CD = M_GENBA.GENBA_CD
/*BEGIN*/
WHERE
    /*IF !data_M_COURSE_DETAIL.DAY_CD.IsNull*/
    MCD.DAY_CD = /*data_M_COURSE_DETAIL.DAY_CD*/1
    /*END*/
    /*IF data_M_COURSE_DETAIL.COURSE_NAME_CD != null*/
AND MCD.COURSE_NAME_CD = /*data_M_COURSE_DETAIL.COURSE_NAME_CD*/'abc'
    /*END*/
    /*IF data_M_COURSE_DETAIL.GYOUSHA_CD != null*/
AND MCD.GYOUSHA_CD = /*data_M_COURSE_DETAIL.GYOUSHA_CD*/'abc'
    /*END*/
    /*IF data_M_COURSE_DETAIL.GENBA_CD != null*/
AND MCD.GENBA_CD = /*data_M_COURSE_DETAIL.GENBA_CD*/'abc'
    /*END*/
    /*IF !data_M_COURSE_DETAIL.ROUND_NO.IsNull*/
AND MCD.ROUND_NO = /*data_M_COURSE_DETAIL.ROUND_NO*/1
    /*END*/
/*END*/
ORDER BY
    MCD.ROW_NO