
SELECT
	
	COURSE_NAME_CD,
	COURSE_NAME,
	--COURSE_NAME_RYAKU,
	KYOTEN_CD,
	MONDAY,
	TUESDAY,
	WEDNESDAY,
	THURSDAY,
	FRIDAY,
	SATURDAY,
	SUNDAY

FROM

	M_COURSE_NAME

WHERE
	M_COURSE_NAME.DELETE_FLG = 0

/*IF !data.KYOTEN_CD.IsNull*/AND(KYOTEN_CD = 99 OR KYOTEN_CD = /*data.KYOTEN_CD*/1)/*END*/
/*IF monday*/AND MONDAY = 1/*END*/
/*IF tuesday*/AND TUESDAY = 1/*END*/
/*IF wednesday*/AND WEDNESDAY = 1/*END*/
/*IF thursday*/AND THURSDAY = 1/*END*/
/*IF friday*/AND FRIDAY = 1/*END*/
/*IF saturday*/AND SATURDAY = 1/*END*/
/*IF sunday*/AND SUNDAY = 1/*END*/
