SELECT
	MCD.DAY_CD,
	MCD.COURSE_NAME_CD,
	MAX(MCD.REC_ID) AS MAX_REC_ID

FROM
	M_COURSE_DETAIL AS MCD 

WHERE
	--DELETE_FLG = 0
/*IF !data_M_COURSE_DETAIL.DAY_CD.IsNull*/MCD.DAY_CD = /*data_M_COURSE_DETAIL.DAY_CD*/1/*END*/
/*IF data_M_COURSE_DETAIL.COURSE_NAME_CD != null*/AND MCD.COURSE_NAME_CD = /*data_M_COURSE_DETAIL.COURSE_NAME_CD*/'abc'/*END*/

/*IF data_M_COURSE_DETAIL.GYOUSHA_CD != null*/AND MCD.GYOUSHA_CD = /*data_M_COURSE_DETAIL.GYOUSHA_CD*/'abc'/*END*/
/*IF data_M_COURSE_DETAIL.GENBA_CD != null*/AND MCD.GENBA_CD = /*data_M_COURSE_DETAIL.GENBA_CD*/'abc'/*END*/
/*IF !data_M_COURSE_DETAIL.ROUND_NO.IsNull*/AND MCD.ROUND_NO = /*data_M_COURSE_DETAIL.ROUND_NO*/1/*END*/

GROUP BY 
	MCD.DAY_CD,
	MCD.COURSE_NAME_CD