SELECT
	
	MCDI.DAY_CD,
	MCDI.COURSE_NAME_CD,
	MCDI.REC_ID,
	MCDI.REC_SEQ,
	MCDI.HINMEI_CD,
	MCDI.UNIT_CD,
	MCDI.KANSANCHI,
	MCDI.KANSAN_UNIT_CD,
	MCDI.KEIYAKU_KBN,
	MCDI.KEIJYOU_KBN,
	MCDI.TIME_STAMP,
	M_HINMEI.HINMEI_NAME_RYAKU,
	M_UNIT.UNIT_NAME_RYAKU AS UNIT_NAME,    
    MCDI.DENPYOU_KBN_CD,
    MCDI.KANSAN_UNIT_MOBILE_OUTPUT_FLG,
	0 as DELETE_FLG,
	MCDI.INPUT_KBN,
	MCDI.NIOROSHI_NO AS NIOROSHI_NUMBER,
	MCDI.ANBUN_FLG,
	MCDI.TEKIYOU_BEGIN,
	MCDI.TEKIYOU_END,
	MG.TEKIYOU_BEGIN AS GENBA_TEKIYOU_BEGIN,
	MG.TEKIYOU_END AS GENBA_TEKIYOU_END
FROM
	M_COURSE_DETAIL_ITEMS AS MCDI
	
	LEFT OUTER JOIN
		M_HINMEI
			ON 
				MCDI.HINMEI_CD = M_HINMEI.HINMEI_CD 

	LEFT OUTER JOIN
		M_UNIT
			ON 
				MCDI.UNIT_CD = M_UNIT.UNIT_CD 
LEFT JOIN M_COURSE_DETAIL MCD
ON MCD.DAY_CD = MCDI.DAY_CD
AND MCD.COURSE_NAME_CD = MCDI.COURSE_NAME_CD
AND MCD.REC_ID = MCDI.REC_ID
LEFT JOIN M_GENBA MG
ON MCD.GYOUSHA_CD = MG.GYOUSHA_CD
AND MCD.GENBA_CD = MG.GENBA_CD
/*IF ichiranFlag*/
	LEFT JOIN M_GENBA_TEIKI_HINMEI GTH
	ON MG.GYOUSHA_CD = GTH.GYOUSHA_CD
	AND MG.GENBA_CD = GTH.GENBA_CD
	AND MCDI.HINMEI_CD = GTH.HINMEI_CD
	AND MCDI.UNIT_CD = GTH.UNIT_CD
	/*END*/	

/*BEGIN*/WHERE
/*IF !data_M_COURSE_DETAIL_ITEMS.DAY_CD.IsNull*/MCDI.DAY_CD = /*data_M_COURSE_DETAIL_ITEMS.DAY_CD*/1/*END*/
/*IF data_M_COURSE_DETAIL_ITEMS.COURSE_NAME_CD != null*/AND MCDI.COURSE_NAME_CD = /*data_M_COURSE_DETAIL_ITEMS.COURSE_NAME_CD*/'abc'/*END*/
/*IF !data_M_COURSE_DETAIL_ITEMS.REC_ID.IsNull*/AND MCDI.REC_ID = /*data_M_COURSE_DETAIL_ITEMS.REC_ID*/1/*END*/
/*IF ichiranFlag && !dayCd.IsNull && dayCd == '1' */ AND GTH.MONDAY = '1'/*END*/
	/*IF ichiranFlag && !dayCd.IsNull && dayCd == '2' */ AND GTH.TUESDAY = '1'/*END*/
	/*IF ichiranFlag && !dayCd.IsNull && dayCd == '3' */ AND GTH.WEDNESDAY = '1'/*END*/
	/*IF ichiranFlag && !dayCd.IsNull && dayCd == '4' */ AND GTH.THURSDAY = '1'/*END*/
	/*IF ichiranFlag && !dayCd.IsNull && dayCd == '5' */ AND GTH.FRIDAY = '1'/*END*/
	/*IF ichiranFlag && !dayCd.IsNull && dayCd == '6' */ AND GTH.SATURDAY = '1'/*END*/
	/*IF ichiranFlag && !dayCd.IsNull && dayCd == '7' */ AND GTH.SUNDAY = '1'/*END*/
/*END*/

ORDER BY 
	--MCDI.DAY_CD,
	--MCDI.COURSE_NAME_CD,
	MCDI.REC_ID,
	MCDI.REC_SEQ