SELECT

	0 as KUMIKOMI,
	MGTH.GYOUSHA_CD,
	M_GYOUSHA.GYOUSHA_NAME_RYAKU,
	MGTH.GENBA_CD,
	M_GENBA.GENBA_NAME_RYAKU, 
	M_GENBA.SHIKUCHOUSON_CD,
	M_SHIKUCHOUSON.SHIKUCHOUSON_NAME_RYAKU,
	MGTH.HINMEI_CD,
	M_HINMEI.HINMEI_NAME_RYAKU,
	CONVERT(numeric(7,3), MGTH.KANSANCHI) AS KANSANCHI,
	MGTH.KANSAN_UNIT_CD,
	M_KANSANMAE_UNIT.UNIT_NAME_RYAKU AS KANSANMAE_UNIT_NAME,
	MGTH.MONDAY,
	MGTH.TUESDAY,
	MGTH.WEDNESDAY,
	MGTH.THURSDAY,
	MGTH.FRIDAY,
	MGTH.SATURDAY,
	MGTH.SUNDAY,
	MGTH.ROW_NO,
	MGTH.UNIT_CD,
	M_UNIT.UNIT_NAME_RYAKU AS UNIT_NAME,
	MGTH.DENPYOU_KBN_CD,
	MGTH.KEIJYOU_KBN,
	MGTH.KANSAN_UNIT_MOBILE_OUTPUT_FLG,
	MGTH.ANBUN_FLG,
	MGTH.KEIYAKU_KBN,
	M_GENBA.TEKIYOU_BEGIN,
	M_GENBA.TEKIYOU_END,
	0 as isShow
FROM
	M_GENBA_TEIKI_HINMEI AS MGTH
	
	INNER JOIN
		M_GYOUSHA 
			ON 
				MGTH.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
				AND ( M_GYOUSHA.HAISHUTSU_NIZUMI_GYOUSHA_KBN = 1 OR M_GYOUSHA.UNPAN_JUTAKUSHA_KAISHA_KBN = 1)
				AND M_GYOUSHA.DELETE_FLG = 0
				
	INNER JOIN
		M_GENBA
			ON
				MGTH.GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND MGTH.GENBA_CD = M_GENBA.GENBA_CD
				AND (M_GENBA.HAISHUTSU_NIZUMI_GENBA_KBN = 1 OR M_GENBA.TSUMIKAEHOKAN_KBN = 1)
				AND M_GENBA.DELETE_FLG = 0
	LEFT OUTER JOIN
		M_HINMEI
			ON
				MGTH.HINMEI_CD = M_HINMEI.HINMEI_CD
				AND M_HINMEI.DELETE_FLG = 0

	LEFT OUTER JOIN
		M_UNIT AS M_KANSANMAE_UNIT
			ON
				MGTH.KANSAN_UNIT_CD = M_KANSANMAE_UNIT.UNIT_CD
				AND M_KANSANMAE_UNIT.DELETE_FLG = 0

	LEFT OUTER JOIN
		M_UNIT
			ON
				MGTH.UNIT_CD = M_UNIT.UNIT_CD
				AND M_UNIT.DELETE_FLG = 0

	LEFT OUTER JOIN
		M_SHIKUCHOUSON
			ON
			 	M_GENBA.SHIKUCHOUSON_CD = M_SHIKUCHOUSON.SHIKUCHOUSON_CD
			 	AND M_SHIKUCHOUSON.DELETE_FLG = 0
WHERE
1 = 1
/*IF shikuChousonCd != ''*/AND M_GENBA.SHIKUCHOUSON_CD = /*shikuChousonCd*/'000'/*END*/
/*IF data_M_GENBA_TEIKI_HINMEI.GYOUSHA_CD != null*/AND MGTH.GYOUSHA_CD = /*data_M_GENBA_TEIKI_HINMEI.GYOUSHA_CD*/'000001'/*END*/
/*IF data_M_GENBA_TEIKI_HINMEI.GENBA_CD != null*/AND MGTH.GENBA_CD = /*data_M_GENBA_TEIKI_HINMEI.GENBA_CD*/'000001'/*END*/
/*IF data_M_GENBA_TEIKI_HINMEI.HINMEI_CD != null*/AND MGTH.HINMEI_CD = /*data_M_GENBA_TEIKI_HINMEI.HINMEI_CD*/'000001'/*END*/
/*IF dayCd != null && dayCd == '1' */AND MGTH.MONDAY = 1 /*END*/
/*IF dayCd != null && dayCd == '2' */AND MGTH.TUESDAY = 1 /*END*/
/*IF dayCd != null && dayCd == '3' */AND MGTH.WEDNESDAY = 1 /*END*/
/*IF dayCd != null && dayCd == '4' */AND MGTH.THURSDAY = 1 /*END*/
/*IF dayCd != null && dayCd == '5' */AND MGTH.FRIDAY = 1 /*END*/
/*IF dayCd != null && dayCd == '6' */AND MGTH.SATURDAY = 1 /*END*/
/*IF dayCd != null && dayCd == '7' */AND MGTH.SUNDAY = 1 /*END*/

ORDER BY
	MGTH.GYOUSHA_CD,
	MGTH.GENBA_CD,
	MGTH.HINMEI_CD