SELECT 
    HK.HAIKI_KBN_CD as HAIKI_KBN_CD
    ,HK.HAIKI_KBN_NAME_RYAKU as HAIKI_KBN_NAME_RYAKU
FROM 
    dbo.M_HAIKI_KBN HK
/*BEGIN*/WHERE 1=1 
 /*IF !data.HAIKI_KBN_CD.IsNull*/
 AND CAST(KONGOU.HAIKI_KBN_CD AS VARCHAR(2)) LIKE '%' + CAST(/*data.HAIKI_KBN_CD*/0 AS VARCHAR(2)) + '%'/*END*/
 /*END*/