-- このクエリを修正した場合は、 \01_共通\BusinessCommon\Sql\GetSyuuryouBiKeikokuData.sql も同様の修正を行うこと

--運搬
(SELECT
    TME.SYSTEM_ID,
    TME.SEQ,
    NULL AS DENMANI_KANRI_ID,
    NULL AS DENMANI_SEQ,
    NULL AS EDI_PASSWORD,
    NULL AS KIND,
    TME.HAIKI_KBN_CD,
    MHK.HAIKI_KBN_NAME_RYAKU AS '廃棄物区分',
    CASE WHEN TME.FIRST_MANIFEST_KBN = '0' THEN '一次'
    WHEN TME.FIRST_MANIFEST_KBN = '1' THEN '二次'
    END AS '一次二次',
    '運搬' AS '終了日警告区分',
    DATEDIFF(DAY, CONVERT(VARCHAR(10), (TME.KOUFU_DATE + /*data.sys_nitsusuu_upn*/0), 120), CONVERT(VARCHAR(10), GETDATE(), 120)) AS '経過日数',
    TME.MANIFEST_ID AS '交付番号',
    LTRIM(RTRIM(SUBSTRING(ISNULL(TME.HST_GYOUSHA_NAME, ''),1, 40)) + SUBSTRING(ISNULL(TME.HST_GYOUSHA_NAME, ''),41, 40)) AS '排出事業者名',
    LTRIM(RTRIM(SUBSTRING(ISNULL(TME.HST_GENBA_NAME, ''),1, 40)) + SUBSTRING(ISNULL(TME.HST_GENBA_NAME, ''),41, 40)) AS '排出事業場名',
    TMU.UPN_GYOUSHA_NAME AS '運搬受託者名',
    TME.SBN_GYOUSHA_NAME AS '処分受託者名',
    M_GNB.GENBA_NAME1 AS '最終処分場所名',
    MHS.HAIKI_SHURUI_NAME_RYAKU AS '廃棄物種類',
    ISNULL(TMAD.HAIKI_SUU,0) AS '数量',
    MU.UNIT_NAME AS '単位'
FROM T_MANIFEST_ENTRY AS TME
LEFT JOIN T_MANIFEST_DETAIL AS TMAD
    ON TME.SYSTEM_ID = TMAD.SYSTEM_ID
    AND TME.SEQ = TMAD.SEQ
    AND TME.DELETE_FLG = 0
LEFT JOIN T_MANIFEST_UPN AS TMU
    ON TME.SYSTEM_ID = TMU.SYSTEM_ID
    AND TME.SEQ = TMU.SEQ
    AND TME.DELETE_FLG = 0
LEFT JOIN M_HAIKI_SHURUI AS MHS
    ON TME.HAIKI_KBN_CD = MHS.HAIKI_KBN_CD
    AND TMAD.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
LEFT JOIN M_GENBA AS M_GNB
    ON TMAD.LAST_SBN_GYOUSHA_CD = M_GNB.GYOUSHA_CD
    AND TMAD.LAST_SBN_GENBA_CD = M_GNB.GENBA_CD
LEFT JOIN M_HAIKI_KBN AS MHK
    ON TME.HAIKI_KBN_CD=MHK.HAIKI_KBN_CD
LEFT JOIN M_UNIT AS MU
    ON TMAD.HAIKI_UNIT_CD=MU.UNIT_CD
WHERE
        TME.KOUFU_DATE + /*data.sys_nitsusuu_upn*/0 < CONVERT(DATETIME, CONVERT(NVARCHAR, GETDATE(), 111), 120)
    AND ISNULL(TMU.UPN_END_DATE, '') = ''
    AND TME.DELETE_FLG = 0
    AND /*data.sys_nitsusuu_upn*/0 > 0
    AND (TMU.UPN_GYOUSHA_CD IS NOT NULL AND TMU.UPN_GYOUSHA_CD <> '')
    AND (TMU.UPN_END_DATE IS NULL OR TMU.UPN_END_DATE = '')
    )
    
    UNION 
    
    --処分
    (
    SELECT
    TME.SYSTEM_ID,
    TME.SEQ,
    NULL AS DENMANI_KANRI_ID,
    NULL AS DENMANI_SEQ,
    NULL AS EDI_PASSWORD,
    NULL AS KIND,
    TME.HAIKI_KBN_CD,
    MHK.HAIKI_KBN_NAME_RYAKU AS '廃棄物区分',
    CASE WHEN TME.FIRST_MANIFEST_KBN = '0' THEN '一次'
    WHEN TME.FIRST_MANIFEST_KBN = '1' THEN '二次'
    END AS '一次二次',
    '中間処分' AS '終了日警告区分',
    DATEDIFF(DAY, CONVERT(VARCHAR(10), (TME.KOUFU_DATE + /*data.sys_nitsusuu_sbu*/0), 120), CONVERT(VARCHAR(10), GETDATE(), 120)) AS '経過日数',
    TME.MANIFEST_ID AS '交付番号',
    LTRIM(RTRIM(SUBSTRING(ISNULL(TME.HST_GYOUSHA_NAME, ''),1, 40)) + SUBSTRING(ISNULL(TME.HST_GYOUSHA_NAME, ''),41, 40)) AS '排出事業者名',
    LTRIM(RTRIM(SUBSTRING(ISNULL(TME.HST_GENBA_NAME, ''),1, 40)) + SUBSTRING(ISNULL(TME.HST_GENBA_NAME, ''),41, 40)) AS '排出事業場名',
    TMU.UPN_GYOUSHA_NAME AS '運搬受託者名',
    TME.SBN_GYOUSHA_NAME AS '処分受託者名',
    M_GNB.GENBA_NAME1 AS '最終処分場所名',
    MHS.HAIKI_SHURUI_NAME_RYAKU AS '廃棄物種類',
    ISNULL(TMAD.HAIKI_SUU,0) AS '数量',
    MU.UNIT_NAME AS '単位'
FROM T_MANIFEST_ENTRY AS TME
LEFT JOIN T_MANIFEST_DETAIL AS TMAD
    ON TME.SYSTEM_ID = TMAD.SYSTEM_ID
    AND TME.SEQ = TMAD.SEQ
    AND TME.DELETE_FLG = 0
        LEFT JOIN
            (
                SELECT
                    T_MANIFEST_UPN.SYSTEM_ID,
                    T_MANIFEST_UPN.SEQ,
                    T_MANIFEST_UPN.UPN_GYOUSHA_NAME
                FROM
                    T_MANIFEST_UPN JOIN
                    (
                        SELECT
                            SYSTEM_ID,
                            SEQ,
                            MAX (UPN_ROUTE_NO) AS UPN_ROUTE_NO
                        FROM
                            T_MANIFEST_UPN
                        WHERE
                            T_MANIFEST_UPN.UPN_GYOUSHA_CD IS NOT NULL AND T_MANIFEST_UPN.UPN_GYOUSHA_CD <> ''
                        GROUP BY
                            SYSTEM_ID,
                            SEQ
                    ) AS T_MANIFEST_UPN_MAX
                ON  T_MANIFEST_UPN.SYSTEM_ID = T_MANIFEST_UPN_MAX.SYSTEM_ID
                AND T_MANIFEST_UPN.SEQ = T_MANIFEST_UPN_MAX.SEQ
                AND T_MANIFEST_UPN.UPN_ROUTE_NO = T_MANIFEST_UPN_MAX.UPN_ROUTE_NO
            ) AS TMU
        ON  TME.SYSTEM_ID = TMU.SYSTEM_ID
        AND TME.SEQ = TMU.SEQ
LEFT JOIN M_HAIKI_SHURUI AS MHS
    ON TME.HAIKI_KBN_CD = MHS.HAIKI_KBN_CD
    AND TMAD.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
LEFT JOIN M_GENBA AS M_GNB
    ON TMAD.LAST_SBN_GYOUSHA_CD = M_GNB.GYOUSHA_CD
    AND TMAD.LAST_SBN_GENBA_CD = M_GNB.GENBA_CD
    LEFT JOIN M_HAIKI_KBN AS MHK
    ON TME.HAIKI_KBN_CD=MHK.HAIKI_KBN_CD
    LEFT JOIN M_UNIT AS MU
    ON TMAD.HAIKI_UNIT_CD=MU.UNIT_CD
    WHERE
     TME.KOUFU_DATE + /*data.sys_nitsusuu_sbu*/0 < CONVERT(DATETIME, CONVERT(NVARCHAR, GETDATE(), 111), 120)
    AND ISNULL(TMAD.SBN_END_DATE,'') = ''
    AND TME.DELETE_FLG = 0
    AND /*data.sys_nitsusuu_sbu*/0 > 0
    AND (((TME.HAIKI_KBN_CD = 1 OR TME.HAIKI_KBN_CD = 3) AND TMAD.HAIKI_SHURUI_CD < '7000') OR (TME.HAIKI_KBN_CD = 2 AND TMAD.HAIKI_SHURUI_CD < '2100'))
    )
    
        UNION 
    
    --特管処分
    (
    SELECT
    TME.SYSTEM_ID,
    TME.SEQ,
    NULL AS DENMANI_KANRI_ID,
    NULL AS DENMANI_SEQ,
    NULL AS EDI_PASSWORD,
    NULL AS KIND,
    TME.HAIKI_KBN_CD,
    MHK.HAIKI_KBN_NAME_RYAKU AS '廃棄物区分',
    CASE WHEN TME.FIRST_MANIFEST_KBN = '0' THEN '一次'
    WHEN TME.FIRST_MANIFEST_KBN = '1' THEN '二次'
    END AS '一次二次',
    '特管処分' AS '終了日警告区分',
    DATEDIFF(DAY, CONVERT(VARCHAR(10), (TME.KOUFU_DATE + /*data.sys_nitsusuu_tk_sbu*/0), 120), CONVERT(VARCHAR(10), GETDATE(), 120)) AS '経過日数',
    TME.MANIFEST_ID AS '交付番号',
    LTRIM(RTRIM(SUBSTRING(ISNULL(TME.HST_GYOUSHA_NAME, ''),1, 40)) + SUBSTRING(ISNULL(TME.HST_GYOUSHA_NAME, ''),41, 40)) AS '排出事業者名',
    LTRIM(RTRIM(SUBSTRING(ISNULL(TME.HST_GENBA_NAME, ''),1, 40)) + SUBSTRING(ISNULL(TME.HST_GENBA_NAME, ''),41, 40)) AS '排出事業場名',
    TMU.UPN_GYOUSHA_NAME AS '運搬受託者名',
    TME.SBN_GYOUSHA_NAME AS '処分受託者名',
    M_GNB.GENBA_NAME1 AS '最終処分場所名',
    MHS.HAIKI_SHURUI_NAME_RYAKU AS '廃棄物種類',
    ISNULL(TMAD.HAIKI_SUU,0) AS '数量',
    MU.UNIT_NAME AS '単位'
FROM T_MANIFEST_ENTRY AS TME
LEFT JOIN T_MANIFEST_DETAIL AS TMAD
    ON TME.SYSTEM_ID = TMAD.SYSTEM_ID
    AND TME.SEQ = TMAD.SEQ
    AND TME.DELETE_FLG = 0
        LEFT JOIN
            (
                SELECT
                    T_MANIFEST_UPN.SYSTEM_ID,
                    T_MANIFEST_UPN.SEQ,
                    T_MANIFEST_UPN.UPN_GYOUSHA_NAME
                FROM
                    T_MANIFEST_UPN JOIN
                    (
                        SELECT
                            SYSTEM_ID,
                            SEQ,
                            MAX (UPN_ROUTE_NO) AS UPN_ROUTE_NO
                        FROM
                            T_MANIFEST_UPN
                        WHERE
                            T_MANIFEST_UPN.UPN_GYOUSHA_CD IS NOT NULL AND T_MANIFEST_UPN.UPN_GYOUSHA_CD <> ''
                        GROUP BY
                            SYSTEM_ID,
                            SEQ
                    ) AS T_MANIFEST_UPN_MAX
                ON  T_MANIFEST_UPN.SYSTEM_ID = T_MANIFEST_UPN_MAX.SYSTEM_ID
                AND T_MANIFEST_UPN.SEQ = T_MANIFEST_UPN_MAX.SEQ
                AND T_MANIFEST_UPN.UPN_ROUTE_NO = T_MANIFEST_UPN_MAX.UPN_ROUTE_NO
            ) AS TMU
        ON  TME.SYSTEM_ID = TMU.SYSTEM_ID
        AND TME.SEQ = TMU.SEQ
LEFT JOIN M_HAIKI_SHURUI AS MHS
    ON TME.HAIKI_KBN_CD = MHS.HAIKI_KBN_CD
    AND TMAD.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
LEFT JOIN M_GENBA AS M_GNB
    ON TMAD.LAST_SBN_GYOUSHA_CD = M_GNB.GYOUSHA_CD
    AND TMAD.LAST_SBN_GENBA_CD = M_GNB.GENBA_CD
LEFT JOIN M_HAIKI_KBN AS MHK
    ON TME.HAIKI_KBN_CD=MHK.HAIKI_KBN_CD
    LEFT JOIN M_UNIT AS MU
    ON TMAD.HAIKI_UNIT_CD=MU.UNIT_CD
    WHERE
     TME.KOUFU_DATE + /*data.sys_nitsusuu_tk_sbu*/0  < CONVERT(DATETIME, CONVERT(NVARCHAR, GETDATE(), 111), 120)
    AND ISNULL(TMAD.SBN_END_DATE,'') = ''
    AND TME.DELETE_FLG = 0
    AND /*data.sys_nitsusuu_tk_sbu*/0 > 0
    AND (((TME.HAIKI_KBN_CD = 1 OR TME.HAIKI_KBN_CD = 3) AND TMAD.HAIKI_SHURUI_CD >= '7000') OR (TME.HAIKI_KBN_CD = 2 AND TMAD.HAIKI_SHURUI_CD >= '2100'))
    )
        UNION 
        --最終処分
    (
    SELECT
    TME.SYSTEM_ID,
    TME.SEQ,
    NULL AS DENMANI_KANRI_ID,
    NULL AS DENMANI_SEQ,
    NULL AS EDI_PASSWORD,
    NULL AS KIND,
    TME.HAIKI_KBN_CD,
    MHK.HAIKI_KBN_NAME_RYAKU AS '廃棄物区分',
    CASE WHEN TME.FIRST_MANIFEST_KBN = '0' THEN '一次'
    WHEN TME.FIRST_MANIFEST_KBN = '1' THEN '二次'
    END AS '一次二次',
    '最終処分' AS '終了日警告区分',
    DATEDIFF(DAY, CONVERT(VARCHAR(10), (TME.KOUFU_DATE + /*data.sys_nitsusuu_last_sbu*/0), 120), CONVERT(VARCHAR(10), GETDATE(), 120)) AS '経過日数',
    TME.MANIFEST_ID AS '交付番号',
    LTRIM(RTRIM(SUBSTRING(ISNULL(TME.HST_GYOUSHA_NAME, ''),1, 40)) + SUBSTRING(ISNULL(TME.HST_GYOUSHA_NAME, ''),41, 40)) AS '排出事業者名',
    LTRIM(RTRIM(SUBSTRING(ISNULL(TME.HST_GENBA_NAME, ''),1, 40)) + SUBSTRING(ISNULL(TME.HST_GENBA_NAME, ''),41, 40)) AS '排出事業場名',
    TMU.UPN_GYOUSHA_NAME AS '運搬受託者名',
    TME.SBN_GYOUSHA_NAME AS '処分受託者名',
    M_GNB.GENBA_NAME1 AS '最終処分場所名',
    MHS.HAIKI_SHURUI_NAME_RYAKU AS '廃棄物種類',
    ISNULL(TMAD.HAIKI_SUU,0) AS '数量',
    MU.UNIT_NAME AS '単位'
FROM T_MANIFEST_ENTRY AS TME
LEFT JOIN T_MANIFEST_DETAIL AS TMAD
    ON TME.SYSTEM_ID = TMAD.SYSTEM_ID
    AND TME.SEQ = TMAD.SEQ
    AND TME.DELETE_FLG = 0
        LEFT JOIN
            (
                SELECT
                    T_MANIFEST_UPN.SYSTEM_ID,
                    T_MANIFEST_UPN.SEQ,
                    T_MANIFEST_UPN.UPN_GYOUSHA_NAME
                FROM
                    T_MANIFEST_UPN JOIN
                    (
                        SELECT
                            SYSTEM_ID,
                            SEQ,
                            MAX (UPN_ROUTE_NO) AS UPN_ROUTE_NO
                        FROM
                            T_MANIFEST_UPN
                        WHERE
                            T_MANIFEST_UPN.UPN_GYOUSHA_CD IS NOT NULL AND T_MANIFEST_UPN.UPN_GYOUSHA_CD <> ''
                        GROUP BY
                            SYSTEM_ID,
                            SEQ
                    ) AS T_MANIFEST_UPN_MAX
                ON  T_MANIFEST_UPN.SYSTEM_ID = T_MANIFEST_UPN_MAX.SYSTEM_ID
                AND T_MANIFEST_UPN.SEQ = T_MANIFEST_UPN_MAX.SEQ
                AND T_MANIFEST_UPN.UPN_ROUTE_NO = T_MANIFEST_UPN_MAX.UPN_ROUTE_NO
            ) AS TMU
        ON  TME.SYSTEM_ID = TMU.SYSTEM_ID
        AND TME.SEQ = TMU.SEQ
LEFT JOIN M_HAIKI_SHURUI AS MHS
    ON TME.HAIKI_KBN_CD = MHS.HAIKI_KBN_CD
    AND TMAD.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
LEFT JOIN M_GENBA AS M_GNB
    ON TMAD.LAST_SBN_GYOUSHA_CD = M_GNB.GYOUSHA_CD
    AND TMAD.LAST_SBN_GENBA_CD = M_GNB.GENBA_CD
LEFT JOIN M_HAIKI_KBN AS MHK
    ON TME.HAIKI_KBN_CD=MHK.HAIKI_KBN_CD
    LEFT JOIN M_UNIT AS MU
    ON TMAD.HAIKI_UNIT_CD=MU.UNIT_CD
    WHERE
         TME.KOUFU_DATE + /*data.sys_nitsusuu_last_sbu*/0  < CONVERT(DATETIME, CONVERT(NVARCHAR, GETDATE(), 111), 120)
    AND ISNULL(TMAD.LAST_SBN_END_DATE,'') = ''
    AND TME.DELETE_FLG = 0    
    AND /*data.sys_nitsusuu_last_sbu*/0 > 0
    )

-- 電子マニフェスト（運搬）
UNION
(
    SELECT
        DT_R18_EX.SYSTEM_ID,
        DT_R18_EX.SEQ,
        DT_R18.KANRI_ID AS DENMANI_KANRI_ID,
        DT_R18.SEQ AS DENMANI_SEQ,
        MS_JWNET_MEMBER.EDI_PASSWORD,
        DT_MF_TOC.KIND,
        4 AS HAIKI_KBN_CD,
        '電子' AS '廃棄物区分',
        CASE WHEN DT_R18.FIRST_MANIFEST_FLAG IS NULL OR DT_R18.FIRST_MANIFEST_FLAG = '' OR ISNULL(HST_JIGYOUSHA.JISHA_KBN, 0) = 0 THEN '一次'
                ELSE '二次'
        END AS '一次二次',
        '運搬' AS '終了日警告区分',
        ISNULL(DATEDIFF(DAY, DATEADD(DAY, /*data.sys_nitsusuu_upn*/1, DT_R18.HIKIWATASHI_DATE), GETDATE() ), 0) AS '経過日数',
        ISNULL(DT_R18.MANIFEST_ID, '') AS '交付番号',
        CASE
            WHEN HST_JIGYOUSHA.GYOUSHA_NAME_RYAKU IS NOT NULL THEN HST_JIGYOUSHA.GYOUSHA_NAME_RYAKU
            ELSE DT_R18.HST_SHA_NAME
        END AS '排出事業者名',
        CASE
            WHEN HST_JIGYOUJOU.GENBA_NAME_RYAKU IS NOT NULL THEN HST_JIGYOUJOU.GENBA_NAME_RYAKU
            ELSE DT_R18.HST_JOU_NAME
        END AS '排出事業場名',
        CASE
            WHEN UPN_JIGYOUSHA.GYOUSHA_NAME_RYAKU IS NOT NULL THEN UPN_JIGYOUSHA.GYOUSHA_NAME_RYAKU
            ELSE DT_R19.UPN_SHA_NAME
        END AS '運搬受託者名',
        CASE
            WHEN SBN_JIGYOUSHA.GYOUSHA_NAME_RYAKU IS NOT NULL THEN SBN_JIGYOUSHA.GYOUSHA_NAME_RYAKU
            ELSE DT_R18.SBN_SHA_NAME
        END AS '処分受託者名',
        CASE
            WHEN LAST_SBN_JIGYOUJOU.GENBA_NAME_RYAKU IS NOT NULL THEN LAST_SBN_JIGYOUJOU.GENBA_NAME_RYAKU
            ELSE DT_R13.LAST_SBN_JOU_NAME
        END AS '最終処分場所名',
        M_DENSHI_HAIKI_SHURUI.HAIKI_SHURUI_NAME AS '廃棄物種類',
        ISNULL(DT_R18.HAIKI_SUU, 0) AS '数量',
        ISNULL(M_UNIT.UNIT_NAME_RYAKU, '') AS '単位'
    FROM DT_R18
        JOIN DT_MF_TOC
            ON DT_R18.KANRI_ID = DT_MF_TOC.KANRI_ID
            AND DT_R18.SEQ = DT_MF_TOC.LATEST_SEQ
        JOIN DT_R18_EX
            ON DT_R18.KANRI_ID = DT_R18_EX.KANRI_ID
           AND DT_R18_EX.DELETE_FLG = 0
        JOIN DT_R19
            ON DT_R18.KANRI_ID = DT_R19.KANRI_ID
           AND DT_R18.SEQ = DT_R19.SEQ
        LEFT JOIN (
            SELECT
                M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID,
                M_GYOUSHA.GYOUSHA_CD,
                M_GYOUSHA.GYOUSHA_NAME_RYAKU,
                M_GYOUSHA.JISHA_KBN
            FROM M_DENSHI_JIGYOUSHA
                JOIN M_GYOUSHA
                    ON M_DENSHI_JIGYOUSHA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
        ) AS HST_JIGYOUSHA
            ON HST_JIGYOUSHA.EDI_MEMBER_ID = DT_R18.HST_SHA_EDI_MEMBER_ID
        LEFT JOIN (
            SELECT
                M_GENBA.GENBA_CD,
                M_GENBA.GENBA_NAME_RYAKU,
                M_DENSHI_JIGYOUJOU.JIGYOUJOU_NAME,
                (ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS1, 0) + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS2, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS3, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS4, '')) AS JIGYOUJOU_ADDRESS
            FROM M_DENSHI_JIGYOUJOU
                JOIN M_GENBA
                    ON M_DENSHI_JIGYOUJOU.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
                   AND M_DENSHI_JIGYOUJOU.GENBA_CD = M_GENBA.GENBA_CD
        ) AS HST_JIGYOUJOU
            ON HST_JIGYOUJOU.JIGYOUJOU_NAME = DT_R18.HST_JOU_NAME
           AND HST_JIGYOUJOU.JIGYOUJOU_ADDRESS = (ISNULL(DT_R18.HST_JOU_ADDRESS1, '') + ISNULL(DT_R18.HST_JOU_ADDRESS2, '') + ISNULL(DT_R18.HST_JOU_ADDRESS3, '') + ISNULL(DT_R18.HST_JOU_ADDRESS4, ''))
        JOIN (
            SELECT
                M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID,
                M_GYOUSHA.GYOUSHA_CD,
                M_GYOUSHA.GYOUSHA_NAME_RYAKU
            FROM M_DENSHI_JIGYOUSHA
                JOIN M_GYOUSHA
                    ON M_DENSHI_JIGYOUSHA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
                   --AND M_GYOUSHA.JISHA_KBN = 1
        ) AS UPN_JIGYOUSHA
            ON UPN_JIGYOUSHA.EDI_MEMBER_ID = DT_R19.UPN_SHA_EDI_MEMBER_ID
        LEFT JOIN (
            SELECT
                M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID,
                M_GYOUSHA.GYOUSHA_CD,
                M_GYOUSHA.GYOUSHA_NAME_RYAKU
            FROM M_DENSHI_JIGYOUSHA
                JOIN M_GYOUSHA
                    ON M_DENSHI_JIGYOUSHA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
        ) AS SBN_JIGYOUSHA
            ON SBN_JIGYOUSHA.EDI_MEMBER_ID = DT_R18.SBN_SHA_MEMBER_ID
        LEFT JOIN (
            SELECT
                R13_1.KANRI_ID,
                R13_1.SEQ,
                R13_1.LAST_SBN_END_DATE,
                R13_1.LAST_SBN_JOU_NAME,
                R13_1.LAST_SBN_JOU_ADDRESS1,
                R13_1.LAST_SBN_JOU_ADDRESS2,
                R13_1.LAST_SBN_JOU_ADDRESS3,
                R13_1.LAST_SBN_JOU_ADDRESS4,
                R13_2.CNT
            FROM DT_R13 AS R13_1
                JOIN (
                    SELECT
                         KANRI_ID,
                         SEQ,
                         COUNT(KANRI_ID) AS CNT
                    FROM DT_R13
                    GROUP BY KANRI_ID, SEQ
                ) AS R13_2
                    ON R13_1.KANRI_ID = R13_2.KANRI_ID
                   AND R13_1.SEQ = R13_2.SEQ
            WHERE R13_1.REC_SEQ = 1
        ) AS DT_R13
            ON DT_R18.KANRI_ID = DT_R13.KANRI_ID
           AND DT_R18.SEQ = DT_R13.SEQ
        LEFT JOIN (
            SELECT
                M_GENBA.GYOUSHA_CD,
                M_GENBA.GENBA_CD,
                M_GENBA.GENBA_NAME_RYAKU,
                M_DENSHI_JIGYOUJOU.JIGYOUJOU_NAME,
                (ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS1, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS2, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS3, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS4, '')) AS JIGYOUJOU_ADDRESS
            FROM M_DENSHI_JIGYOUJOU
                JOIN M_GENBA
                    ON M_DENSHI_JIGYOUJOU.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
                   AND M_DENSHI_JIGYOUJOU.GENBA_CD = M_GENBA.GENBA_CD
        ) AS LAST_SBN_JIGYOUJOU
            ON LAST_SBN_JIGYOUJOU.JIGYOUJOU_NAME = DT_R13.LAST_SBN_JOU_NAME
           AND LAST_SBN_JIGYOUJOU.JIGYOUJOU_ADDRESS = (ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS1, '') + ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS2, '') + ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS3, '') + ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS4, ''))
        LEFT JOIN M_DENSHI_HAIKI_SHURUI
            ON (DT_R18.HAIKI_DAI_CODE + DT_R18.HAIKI_CHU_CODE + DT_R18.HAIKI_SHO_CODE) = M_DENSHI_HAIKI_SHURUI.HAIKI_SHURUI_CD
        LEFT JOIN M_UNIT
            ON DT_R18.HAIKI_UNIT_CODE = M_UNIT.UNIT_CD
        LEFT JOIN MS_JWNET_MEMBER
            ON DT_R18.HST_SHA_EDI_MEMBER_ID = MS_JWNET_MEMBER.EDI_MEMBER_ID
    WHERE
        ISNULL(DT_R19.UPN_END_DATE, '') = ''
    AND DT_MF_TOC.STATUS_FLAG = 4
    AND DT_R19.UPN_SHA_EDI_MEMBER_ID <> '0000000'	--報告不要の除外
	AND DT_R18.HST_SHA_EDI_MEMBER_ID <> DT_R19.UPN_SHA_EDI_MEMBER_ID	--自己運搬の除外
    AND CONVERT(varchar, DATEADD(DAY, /*data.sys_nitsusuu_upn*/1, CONVERT(date, DT_R18.HIKIWATASHI_DATE)), 112) < CONVERT(varchar, GETDATE(), 112)
    AND /*data.sys_nitsusuu_upn*/1 > 0
)

-- 電子マニフェスト（処分）
UNION
(
    SELECT
        DT_R18_EX.SYSTEM_ID,
        DT_R18_EX.SEQ,
        DT_R18.KANRI_ID AS DENMANI_KANRI_ID,
        DT_R18.SEQ AS DENMANI_SEQ,
        MS_JWNET_MEMBER.EDI_PASSWORD,
        DT_MF_TOC.KIND,
        4 AS HAIKI_KBN_CD,
        '電子' AS '廃棄物区分',
        CASE WHEN DT_R18.FIRST_MANIFEST_FLAG IS NULL OR DT_R18.FIRST_MANIFEST_FLAG = '' OR ISNULL(HST_JIGYOUSHA.JISHA_KBN, 0) = 0 THEN '一次'
                ELSE '二次'
        END AS '一次二次',
        '中間処分' AS '終了日警告区分',
        ISNULL(DATEDIFF(DAY, DATEADD(DAY, /*data.sys_nitsusuu_sbu*/1, DT_R18.HIKIWATASHI_DATE), GETDATE() ), 0) AS '経過日数',
        ISNULL(DT_R18.MANIFEST_ID, '') AS '交付番号',
        CASE
            WHEN HST_JIGYOUSHA.GYOUSHA_NAME_RYAKU IS NOT NULL THEN HST_JIGYOUSHA.GYOUSHA_NAME_RYAKU
            ELSE DT_R18.HST_SHA_NAME
        END AS '排出事業者名',
        CASE
            WHEN HST_JIGYOUJOU.GENBA_NAME_RYAKU IS NOT NULL THEN HST_JIGYOUJOU.GENBA_NAME_RYAKU
            ELSE DT_R18.HST_JOU_NAME
        END AS '排出事業場名',
        CASE
            WHEN UPN_JIGYOUSHA.GYOUSHA_NAME_RYAKU IS NOT NULL THEN UPN_JIGYOUSHA.GYOUSHA_NAME_RYAKU
            ELSE DT_R19.UPN_SHA_NAME
        END AS '運搬受託者名',
        CASE
            WHEN SBN_JIGYOUSHA.GYOUSHA_NAME_RYAKU IS NOT NULL THEN SBN_JIGYOUSHA.GYOUSHA_NAME_RYAKU
            ELSE DT_R18.SBN_SHA_NAME
        END AS '処分受託者名',
        CASE
            WHEN LAST_SBN_JIGYOUJOU.GENBA_NAME_RYAKU IS NOT NULL THEN LAST_SBN_JIGYOUJOU.GENBA_NAME_RYAKU
            ELSE DT_R13.LAST_SBN_JOU_NAME
        END AS '最終処分場所名',
        M_DENSHI_HAIKI_SHURUI.HAIKI_SHURUI_NAME AS '廃棄物種類',
        ISNULL(DT_R18.HAIKI_SUU, 0) AS '数量',
        ISNULL(M_UNIT.UNIT_NAME_RYAKU, '') AS '単位'
    FROM DT_R18
        JOIN DT_MF_TOC
            ON DT_R18.KANRI_ID = DT_MF_TOC.KANRI_ID
            AND DT_R18.SEQ = DT_MF_TOC.LATEST_SEQ
        JOIN DT_R18_EX
            ON DT_R18.KANRI_ID = DT_R18_EX.KANRI_ID
           AND DT_R18_EX.DELETE_FLG = 0
        JOIN (SELECT
                  DT_R19.KANRI_ID, DT_R19.SEQ, DT_R19.UPN_SHA_NAME, DT_R19.UPN_SHA_EDI_MEMBER_ID
              FROM
                  DT_R19
                  JOIN (SELECT KANRI_ID, SEQ, MAX(UPN_ROUTE_NO) AS UPN_ROUTE_NO FROM DT_R19 GROUP BY KANRI_ID, SEQ) AS DT_R19_MAX
                      ON DT_R19.KANRI_ID = DT_R19_MAX.KANRI_ID AND DT_R19.SEQ = DT_R19_MAX.SEQ AND DT_R19.UPN_ROUTE_NO = DT_R19_MAX.UPN_ROUTE_NO) AS DT_R19
            ON DT_R18.KANRI_ID = DT_R19.KANRI_ID
           AND DT_R18.SEQ = DT_R19.SEQ
        LEFT JOIN (
            SELECT
                M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID,
                M_GYOUSHA.GYOUSHA_CD,
                M_GYOUSHA.GYOUSHA_NAME_RYAKU,
                M_GYOUSHA.JISHA_KBN
            FROM M_DENSHI_JIGYOUSHA
                JOIN M_GYOUSHA
                    ON M_DENSHI_JIGYOUSHA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
        ) AS HST_JIGYOUSHA
            ON HST_JIGYOUSHA.EDI_MEMBER_ID = DT_R18.HST_SHA_EDI_MEMBER_ID
        LEFT JOIN (
            SELECT
                M_GENBA.GENBA_CD,
                M_GENBA.GENBA_NAME_RYAKU,
                M_DENSHI_JIGYOUJOU.JIGYOUJOU_NAME,
                (ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS1, 0) + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS2, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS3, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS4, '')) AS JIGYOUJOU_ADDRESS
            FROM M_DENSHI_JIGYOUJOU
                JOIN M_GENBA
                    ON M_DENSHI_JIGYOUJOU.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
                   AND M_DENSHI_JIGYOUJOU.GENBA_CD = M_GENBA.GENBA_CD
        ) AS HST_JIGYOUJOU
            ON HST_JIGYOUJOU.JIGYOUJOU_NAME = DT_R18.HST_JOU_NAME
           AND HST_JIGYOUJOU.JIGYOUJOU_ADDRESS = (ISNULL(DT_R18.HST_JOU_ADDRESS1, '') + ISNULL(DT_R18.HST_JOU_ADDRESS2, '') + ISNULL(DT_R18.HST_JOU_ADDRESS3, '') + ISNULL(DT_R18.HST_JOU_ADDRESS4, ''))
        JOIN (
            SELECT
                M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID,
                M_GYOUSHA.GYOUSHA_CD,
                M_GYOUSHA.GYOUSHA_NAME_RYAKU
            FROM M_DENSHI_JIGYOUSHA
                JOIN M_GYOUSHA
                    ON M_DENSHI_JIGYOUSHA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
        ) AS UPN_JIGYOUSHA
            ON UPN_JIGYOUSHA.EDI_MEMBER_ID = DT_R19.UPN_SHA_EDI_MEMBER_ID
        LEFT JOIN (
            SELECT
                M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID,
                M_GYOUSHA.GYOUSHA_CD,
                M_GYOUSHA.GYOUSHA_NAME_RYAKU
            FROM M_DENSHI_JIGYOUSHA
                JOIN M_GYOUSHA
                    ON M_DENSHI_JIGYOUSHA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
                   --AND M_GYOUSHA.JISHA_KBN = 1
        ) AS SBN_JIGYOUSHA
            ON SBN_JIGYOUSHA.EDI_MEMBER_ID = DT_R18.SBN_SHA_MEMBER_ID
        LEFT JOIN (
            SELECT
                R13_1.KANRI_ID,
                R13_1.SEQ,
                R13_1.LAST_SBN_END_DATE,
                R13_1.LAST_SBN_JOU_NAME,
                R13_1.LAST_SBN_JOU_ADDRESS1,
                R13_1.LAST_SBN_JOU_ADDRESS2,
                R13_1.LAST_SBN_JOU_ADDRESS3,
                R13_1.LAST_SBN_JOU_ADDRESS4,
                R13_2.CNT
            FROM DT_R13 AS R13_1
                JOIN (
                    SELECT
                         KANRI_ID,
                         SEQ,
                         COUNT(KANRI_ID) AS CNT
                    FROM DT_R13
                    GROUP BY KANRI_ID, SEQ
                ) AS R13_2
                    ON R13_1.KANRI_ID = R13_2.KANRI_ID
                   AND R13_1.SEQ = R13_2.SEQ
            WHERE R13_1.REC_SEQ = 1
        ) AS DT_R13
            ON DT_R18.KANRI_ID = DT_R13.KANRI_ID
           AND DT_R18.SEQ = DT_R13.SEQ
        LEFT JOIN (
            SELECT
                M_GENBA.GYOUSHA_CD,
                M_GENBA.GENBA_CD,
                M_GENBA.GENBA_NAME_RYAKU,
                M_DENSHI_JIGYOUJOU.JIGYOUJOU_NAME,
                (ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS1, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS2, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS3, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS4, '')) AS JIGYOUJOU_ADDRESS
            FROM M_DENSHI_JIGYOUJOU
                JOIN M_GENBA
                    ON M_DENSHI_JIGYOUJOU.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
                   AND M_DENSHI_JIGYOUJOU.GENBA_CD = M_GENBA.GENBA_CD
        ) AS LAST_SBN_JIGYOUJOU
            ON LAST_SBN_JIGYOUJOU.JIGYOUJOU_NAME = DT_R13.LAST_SBN_JOU_NAME
           AND LAST_SBN_JIGYOUJOU.JIGYOUJOU_ADDRESS = (ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS1, '') + ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS2, '') + ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS3, '') + ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS4, ''))
        LEFT JOIN M_DENSHI_HAIKI_SHURUI
            ON (DT_R18.HAIKI_DAI_CODE + DT_R18.HAIKI_CHU_CODE + DT_R18.HAIKI_SHO_CODE) = M_DENSHI_HAIKI_SHURUI.HAIKI_SHURUI_CD
        LEFT JOIN M_UNIT
            ON DT_R18.HAIKI_UNIT_CODE = M_UNIT.UNIT_CD
        LEFT JOIN MS_JWNET_MEMBER
            ON DT_R18.HST_SHA_EDI_MEMBER_ID = MS_JWNET_MEMBER.EDI_MEMBER_ID
    WHERE
        ISNULL(DT_R18.SBN_END_DATE, '') = ''
    AND DT_MF_TOC.STATUS_FLAG = 4
    AND (DT_R18.HAIKI_DAI_CODE < '70' OR DT_R18.HAIKI_DAI_CODE > '89')
    AND DT_R18.SBN_SHA_MEMBER_ID <> '0000000'	--報告不要の除外
	AND DT_R18.HST_SHA_EDI_MEMBER_ID <> DT_R18.SBN_SHA_MEMBER_ID	--自己処分の除外
    AND CONVERT(varchar, DATEADD(DAY, /*data.sys_nitsusuu_sbu*/1, CONVERT(date, DT_R18.HIKIWATASHI_DATE)), 112) < CONVERT(varchar, GETDATE(), 112)
    AND /*data.sys_nitsusuu_sbu*/1 > 0
)

-- 電子マニフェスト（特管処分）
UNION
(
    SELECT
        DT_R18_EX.SYSTEM_ID,
        DT_R18_EX.SEQ,
        DT_R18.KANRI_ID AS DENMANI_KANRI_ID,
        DT_R18.SEQ AS DENMANI_SEQ,
        MS_JWNET_MEMBER.EDI_PASSWORD,
        DT_MF_TOC.KIND,
        4 AS HAIKI_KBN_CD,
        '電子' AS '廃棄物区分',
        CASE WHEN DT_R18.FIRST_MANIFEST_FLAG IS NULL OR DT_R18.FIRST_MANIFEST_FLAG = '' OR ISNULL(HST_JIGYOUSHA.JISHA_KBN, 0) = 0 THEN '一次'
                ELSE '二次'
        END AS '一次二次',
        '特管処分' AS '終了日警告区分',
        ISNULL(DATEDIFF(DAY, DATEADD(DAY, /*data.sys_nitsusuu_tk_sbu*/1, DT_R18.HIKIWATASHI_DATE), GETDATE() ), 0) AS '経過日数',
        ISNULL(DT_R18.MANIFEST_ID, '') AS '交付番号',
        CASE
            WHEN HST_JIGYOUSHA.GYOUSHA_NAME_RYAKU IS NOT NULL THEN HST_JIGYOUSHA.GYOUSHA_NAME_RYAKU
            ELSE DT_R18.HST_SHA_NAME
        END AS '排出事業者名',
        CASE
            WHEN HST_JIGYOUJOU.GENBA_NAME_RYAKU IS NOT NULL THEN HST_JIGYOUJOU.GENBA_NAME_RYAKU
            ELSE DT_R18.HST_JOU_NAME
        END AS '排出事業場名',
        CASE
            WHEN UPN_JIGYOUSHA.GYOUSHA_NAME_RYAKU IS NOT NULL THEN UPN_JIGYOUSHA.GYOUSHA_NAME_RYAKU
            ELSE DT_R19.UPN_SHA_NAME
        END AS '運搬受託者名',
        CASE
            WHEN SBN_JIGYOUSHA.GYOUSHA_NAME_RYAKU IS NOT NULL THEN SBN_JIGYOUSHA.GYOUSHA_NAME_RYAKU
            ELSE DT_R18.SBN_SHA_NAME
        END AS '処分受託者名',
        CASE
            WHEN LAST_SBN_JIGYOUJOU.GENBA_NAME_RYAKU IS NOT NULL THEN LAST_SBN_JIGYOUJOU.GENBA_NAME_RYAKU
            ELSE DT_R13.LAST_SBN_JOU_NAME
        END AS '最終処分場所名',
        M_DENSHI_HAIKI_SHURUI.HAIKI_SHURUI_NAME AS '廃棄物種類',
        ISNULL(DT_R18.HAIKI_SUU, 0) AS '数量',
        ISNULL(M_UNIT.UNIT_NAME_RYAKU, '') AS '単位'
    FROM DT_R18
        JOIN DT_MF_TOC
            ON DT_R18.KANRI_ID = DT_MF_TOC.KANRI_ID
            AND DT_R18.SEQ = DT_MF_TOC.LATEST_SEQ
        JOIN DT_R18_EX
            ON DT_R18.KANRI_ID = DT_R18_EX.KANRI_ID
           AND DT_R18_EX.DELETE_FLG = 0
        JOIN (SELECT
                  DT_R19.KANRI_ID, DT_R19.SEQ, DT_R19.UPN_SHA_NAME, DT_R19.UPN_SHA_EDI_MEMBER_ID
              FROM
                  DT_R19
                  JOIN (SELECT KANRI_ID, SEQ, MAX(UPN_ROUTE_NO) AS UPN_ROUTE_NO FROM DT_R19 GROUP BY KANRI_ID, SEQ) AS DT_R19_MAX
                      ON DT_R19.KANRI_ID = DT_R19_MAX.KANRI_ID AND DT_R19.SEQ = DT_R19_MAX.SEQ AND DT_R19.UPN_ROUTE_NO = DT_R19_MAX.UPN_ROUTE_NO) AS DT_R19
            ON DT_R18.KANRI_ID = DT_R19.KANRI_ID
           AND DT_R18.SEQ = DT_R19.SEQ
        LEFT JOIN (
            SELECT
                M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID,
                M_GYOUSHA.GYOUSHA_CD,
                M_GYOUSHA.GYOUSHA_NAME_RYAKU,
                M_GYOUSHA.JISHA_KBN
            FROM M_DENSHI_JIGYOUSHA
                JOIN M_GYOUSHA
                    ON M_DENSHI_JIGYOUSHA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
        ) AS HST_JIGYOUSHA
            ON HST_JIGYOUSHA.EDI_MEMBER_ID = DT_R18.HST_SHA_EDI_MEMBER_ID
        LEFT JOIN (
            SELECT
                M_GENBA.GENBA_CD,
                M_GENBA.GENBA_NAME_RYAKU,
                M_DENSHI_JIGYOUJOU.JIGYOUJOU_NAME,
                (ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS1, 0) + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS2, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS3, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS4, '')) AS JIGYOUJOU_ADDRESS
            FROM M_DENSHI_JIGYOUJOU
                JOIN M_GENBA
                    ON M_DENSHI_JIGYOUJOU.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
                   AND M_DENSHI_JIGYOUJOU.GENBA_CD = M_GENBA.GENBA_CD
        ) AS HST_JIGYOUJOU
            ON HST_JIGYOUJOU.JIGYOUJOU_NAME = DT_R18.HST_JOU_NAME
           AND HST_JIGYOUJOU.JIGYOUJOU_ADDRESS = (ISNULL(DT_R18.HST_JOU_ADDRESS1, '') + ISNULL(DT_R18.HST_JOU_ADDRESS2, '') + ISNULL(DT_R18.HST_JOU_ADDRESS3, '') + ISNULL(DT_R18.HST_JOU_ADDRESS4, ''))
        JOIN (
            SELECT
                M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID,
                M_GYOUSHA.GYOUSHA_CD,
                M_GYOUSHA.GYOUSHA_NAME_RYAKU
            FROM M_DENSHI_JIGYOUSHA
                JOIN M_GYOUSHA
                    ON M_DENSHI_JIGYOUSHA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
        ) AS UPN_JIGYOUSHA
            ON UPN_JIGYOUSHA.EDI_MEMBER_ID = DT_R19.UPN_SHA_EDI_MEMBER_ID
        LEFT JOIN (
            SELECT
                M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID,
                M_GYOUSHA.GYOUSHA_CD,
                M_GYOUSHA.GYOUSHA_NAME_RYAKU
            FROM M_DENSHI_JIGYOUSHA
                JOIN M_GYOUSHA
                    ON M_DENSHI_JIGYOUSHA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
                   --AND M_GYOUSHA.JISHA_KBN = 1
        ) AS SBN_JIGYOUSHA
            ON SBN_JIGYOUSHA.EDI_MEMBER_ID = DT_R18.SBN_SHA_MEMBER_ID
        LEFT JOIN (
            SELECT
                R13_1.KANRI_ID,
                R13_1.SEQ,
                R13_1.LAST_SBN_END_DATE,
                R13_1.LAST_SBN_JOU_NAME,
                R13_1.LAST_SBN_JOU_ADDRESS1,
                R13_1.LAST_SBN_JOU_ADDRESS2,
                R13_1.LAST_SBN_JOU_ADDRESS3,
                R13_1.LAST_SBN_JOU_ADDRESS4,
                R13_2.CNT
            FROM DT_R13 AS R13_1
                JOIN (
                    SELECT
                         KANRI_ID,
                         SEQ,
                         COUNT(KANRI_ID) AS CNT
                    FROM DT_R13
                    GROUP BY KANRI_ID, SEQ
                ) AS R13_2
                    ON R13_1.KANRI_ID = R13_2.KANRI_ID
                   AND R13_1.SEQ = R13_2.SEQ
            WHERE R13_1.REC_SEQ = 1
        ) AS DT_R13
            ON DT_R18.KANRI_ID = DT_R13.KANRI_ID
           AND DT_R18.SEQ = DT_R13.SEQ
        LEFT JOIN (
            SELECT
                M_GENBA.GYOUSHA_CD,
                M_GENBA.GENBA_CD,
                M_GENBA.GENBA_NAME_RYAKU,
                M_DENSHI_JIGYOUJOU.JIGYOUJOU_NAME,
                (ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS1, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS2, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS3, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS4, '')) AS JIGYOUJOU_ADDRESS
            FROM M_DENSHI_JIGYOUJOU
                JOIN M_GENBA
                    ON M_DENSHI_JIGYOUJOU.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
                   AND M_DENSHI_JIGYOUJOU.GENBA_CD = M_GENBA.GENBA_CD
        ) AS LAST_SBN_JIGYOUJOU
            ON LAST_SBN_JIGYOUJOU.JIGYOUJOU_NAME = DT_R13.LAST_SBN_JOU_NAME
           AND LAST_SBN_JIGYOUJOU.JIGYOUJOU_ADDRESS = (ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS1, '') + ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS2, '') + ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS3, '') + ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS4, ''))
        LEFT JOIN M_DENSHI_HAIKI_SHURUI
            ON (DT_R18.HAIKI_DAI_CODE + DT_R18.HAIKI_CHU_CODE + DT_R18.HAIKI_SHO_CODE) = M_DENSHI_HAIKI_SHURUI.HAIKI_SHURUI_CD
        LEFT JOIN M_UNIT
            ON DT_R18.HAIKI_UNIT_CODE = M_UNIT.UNIT_CD
        LEFT JOIN MS_JWNET_MEMBER
            ON DT_R18.HST_SHA_EDI_MEMBER_ID = MS_JWNET_MEMBER.EDI_MEMBER_ID
    WHERE
        DT_R18.HAIKI_DAI_CODE >= '70' AND DT_R18.HAIKI_DAI_CODE <= '89'
    AND DT_MF_TOC.STATUS_FLAG = 4
    AND DT_R18.SBN_SHA_MEMBER_ID <> '0000000'	--報告不要の除外
	AND DT_R18.HST_SHA_EDI_MEMBER_ID <> DT_R18.SBN_SHA_MEMBER_ID	--自己処分の除外
    AND ISNULL(DT_R18.SBN_END_DATE, '') = ''
    AND CONVERT(varchar, DATEADD(DAY, /*data.sys_nitsusuu_tk_sbu*/1, CONVERT(date, DT_R18.HIKIWATASHI_DATE)), 112) < CONVERT(varchar, GETDATE(), 112)
    AND /*data.sys_nitsusuu_tk_sbu*/1 > 0
)

-- 電子マニフェスト（最終処分）
UNION
(
    SELECT
        DT_R18_EX.SYSTEM_ID,
        DT_R18_EX.SEQ,
        DT_R18.KANRI_ID AS DENMANI_KANRI_ID,
        DT_R18.SEQ AS DENMANI_SEQ,
        MS_JWNET_MEMBER.EDI_PASSWORD,
        DT_MF_TOC.KIND,
        4 AS HAIKI_KBN_CD,
        '電子' AS '廃棄物区分',
        CASE WHEN DT_R18.FIRST_MANIFEST_FLAG IS NULL OR DT_R18.FIRST_MANIFEST_FLAG = '' OR ISNULL(HST_JIGYOUSHA.JISHA_KBN, 0) = 0 THEN '一次'
                ELSE '二次'
        END AS '一次二次',
        '最終処分' AS '終了日警告区分',
        ISNULL(DATEDIFF(DAY, DATEADD(DAY, /*data.sys_nitsusuu_last_sbu*/1, DT_R18.HIKIWATASHI_DATE), GETDATE()), 0) AS '経過日数',
        ISNULL(DT_R18.MANIFEST_ID, '') AS '交付番号',
        CASE
            WHEN HST_JIGYOUSHA.GYOUSHA_NAME_RYAKU IS NOT NULL THEN HST_JIGYOUSHA.GYOUSHA_NAME_RYAKU
            ELSE DT_R18.HST_SHA_NAME
        END AS '排出事業者名',
        CASE
            WHEN HST_JIGYOUJOU.GENBA_NAME_RYAKU IS NOT NULL THEN HST_JIGYOUJOU.GENBA_NAME_RYAKU
            ELSE DT_R18.HST_JOU_NAME
        END AS '排出事業場名',
        CASE
            WHEN UPN_JIGYOUSHA.GYOUSHA_NAME_RYAKU IS NOT NULL THEN UPN_JIGYOUSHA.GYOUSHA_NAME_RYAKU
            ELSE DT_R19.UPN_SHA_NAME
        END AS '運搬受託者名',
        CASE
            WHEN SBN_JIGYOUSHA.GYOUSHA_NAME_RYAKU IS NOT NULL THEN SBN_JIGYOUSHA.GYOUSHA_NAME_RYAKU
            ELSE DT_R18.SBN_SHA_NAME
        END AS '処分受託者名',
        CASE
            WHEN LAST_SBN_JIGYOUJOU.GENBA_NAME_RYAKU IS NOT NULL THEN LAST_SBN_JIGYOUJOU.GENBA_NAME_RYAKU
            ELSE DT_R13.LAST_SBN_JOU_NAME
        END AS '最終処分場所名',
        M_DENSHI_HAIKI_SHURUI.HAIKI_SHURUI_NAME AS '廃棄物種類',
        ISNULL(DT_R18.HAIKI_SUU, 0) AS '数量',
        ISNULL(M_UNIT.UNIT_NAME_RYAKU, '') AS '単位'
    FROM DT_R18
        JOIN DT_MF_TOC
            ON DT_R18.KANRI_ID = DT_MF_TOC.KANRI_ID
            AND DT_R18.SEQ = DT_MF_TOC.LATEST_SEQ
        JOIN DT_R18_EX
            ON DT_R18.KANRI_ID = DT_R18_EX.KANRI_ID
           AND DT_R18_EX.DELETE_FLG = 0
        JOIN (SELECT
                  DT_R19.KANRI_ID, DT_R19.SEQ, DT_R19.UPN_SHA_NAME, DT_R19.UPN_SHA_EDI_MEMBER_ID
              FROM
                  DT_R19
                  JOIN (SELECT KANRI_ID, SEQ, MAX(UPN_ROUTE_NO) AS UPN_ROUTE_NO FROM DT_R19 GROUP BY KANRI_ID, SEQ) AS DT_R19_MAX
                      ON DT_R19.KANRI_ID = DT_R19_MAX.KANRI_ID AND DT_R19.SEQ = DT_R19_MAX.SEQ AND DT_R19.UPN_ROUTE_NO = DT_R19_MAX.UPN_ROUTE_NO) AS DT_R19
            ON DT_R18.KANRI_ID = DT_R19.KANRI_ID
           AND DT_R18.SEQ = DT_R19.SEQ
        LEFT JOIN (
            SELECT
                M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID,
                M_GYOUSHA.GYOUSHA_CD,
                M_GYOUSHA.GYOUSHA_NAME_RYAKU,
                M_GYOUSHA.JISHA_KBN
            FROM M_DENSHI_JIGYOUSHA
                JOIN M_GYOUSHA
                    ON M_DENSHI_JIGYOUSHA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
        ) AS HST_JIGYOUSHA
            ON HST_JIGYOUSHA.EDI_MEMBER_ID = DT_R18.HST_SHA_EDI_MEMBER_ID
        LEFT JOIN (
            SELECT
                M_GENBA.GENBA_CD,
                M_GENBA.GENBA_NAME_RYAKU,
                M_DENSHI_JIGYOUJOU.JIGYOUJOU_NAME,
                (ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS1, 0) + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS2, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS3, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS4, '')) AS JIGYOUJOU_ADDRESS
            FROM M_DENSHI_JIGYOUJOU
                JOIN M_GENBA
                    ON M_DENSHI_JIGYOUJOU.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
                   AND M_DENSHI_JIGYOUJOU.GENBA_CD = M_GENBA.GENBA_CD
        ) AS HST_JIGYOUJOU
            ON HST_JIGYOUJOU.JIGYOUJOU_NAME = DT_R18.HST_JOU_NAME
           AND HST_JIGYOUJOU.JIGYOUJOU_ADDRESS = (ISNULL(DT_R18.HST_JOU_ADDRESS1, '') + ISNULL(DT_R18.HST_JOU_ADDRESS2, '') + ISNULL(DT_R18.HST_JOU_ADDRESS3, '') + ISNULL(DT_R18.HST_JOU_ADDRESS4, ''))
        JOIN (
            SELECT
                M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID,
                M_GYOUSHA.GYOUSHA_CD,
                M_GYOUSHA.GYOUSHA_NAME_RYAKU
            FROM M_DENSHI_JIGYOUSHA
                JOIN M_GYOUSHA
                    ON M_DENSHI_JIGYOUSHA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
        ) AS UPN_JIGYOUSHA
            ON UPN_JIGYOUSHA.EDI_MEMBER_ID = DT_R19.UPN_SHA_EDI_MEMBER_ID
        LEFT JOIN (
            SELECT
                M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID,
                M_GYOUSHA.GYOUSHA_CD,
                M_GYOUSHA.GYOUSHA_NAME_RYAKU
            FROM M_DENSHI_JIGYOUSHA
                JOIN M_GYOUSHA
                    ON M_DENSHI_JIGYOUSHA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
        ) AS SBN_JIGYOUSHA
            ON SBN_JIGYOUSHA.EDI_MEMBER_ID = DT_R18.SBN_SHA_MEMBER_ID
        LEFT JOIN (
            SELECT
                R13_1.KANRI_ID,
                R13_1.SEQ,
                R13_1.LAST_SBN_END_DATE,
                R13_1.LAST_SBN_JOU_NAME,
                R13_1.LAST_SBN_JOU_ADDRESS1,
                R13_1.LAST_SBN_JOU_ADDRESS2,
                R13_1.LAST_SBN_JOU_ADDRESS3,
                R13_1.LAST_SBN_JOU_ADDRESS4,
                R13_2.CNT
            FROM DT_R13 AS R13_1
                JOIN (
                    SELECT
                         KANRI_ID,
                         SEQ,
                         COUNT(KANRI_ID) AS CNT
                    FROM DT_R13
                    GROUP BY KANRI_ID, SEQ
                ) AS R13_2
                    ON R13_1.KANRI_ID = R13_2.KANRI_ID
                   AND R13_1.SEQ = R13_2.SEQ
            WHERE R13_1.REC_SEQ = 1
        ) AS DT_R13
            ON DT_R18.KANRI_ID = DT_R13.KANRI_ID
           AND DT_R18.SEQ = DT_R13.SEQ
        LEFT JOIN (
            SELECT
                M_GENBA.GYOUSHA_CD,
                M_GENBA.GENBA_CD,
                M_GENBA.GENBA_NAME_RYAKU,
                M_DENSHI_JIGYOUJOU.JIGYOUJOU_NAME,
                (ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS1, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS2, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS3, '') + ISNULL(M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS4, '')) AS JIGYOUJOU_ADDRESS
            FROM M_DENSHI_JIGYOUJOU
                JOIN M_GENBA
                    ON M_DENSHI_JIGYOUJOU.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
                   AND M_DENSHI_JIGYOUJOU.GENBA_CD = M_GENBA.GENBA_CD
        ) AS LAST_SBN_JIGYOUJOU
            ON LAST_SBN_JIGYOUJOU.JIGYOUJOU_NAME = DT_R13.LAST_SBN_JOU_NAME
           AND LAST_SBN_JIGYOUJOU.JIGYOUJOU_ADDRESS = (ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS1, '') + ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS2, '') + ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS3, '') + ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS4, ''))
        LEFT JOIN M_DENSHI_HAIKI_SHURUI
            ON (DT_R18.HAIKI_DAI_CODE + DT_R18.HAIKI_CHU_CODE + DT_R18.HAIKI_SHO_CODE) = M_DENSHI_HAIKI_SHURUI.HAIKI_SHURUI_CD
        LEFT JOIN M_UNIT
            ON DT_R18.HAIKI_UNIT_CODE = M_UNIT.UNIT_CD
        LEFT JOIN MS_JWNET_MEMBER
            ON DT_R18.HST_SHA_EDI_MEMBER_ID = MS_JWNET_MEMBER.EDI_MEMBER_ID
    WHERE
        ISNULL(DT_R18.LAST_SBN_END_DATE, '') = ''
    AND DT_MF_TOC.STATUS_FLAG = 4
    AND DT_R18.SBN_SHA_MEMBER_ID <> '0000000'	--報告不要の除外
	AND DT_R18.HST_SHA_EDI_MEMBER_ID <> DT_R18.SBN_SHA_MEMBER_ID	--自己処分の除外
    AND CONVERT(varchar, DATEADD(DAY, /*data.sys_nitsusuu_last_sbu*/1, CONVERT(date, DT_R18.HIKIWATASHI_DATE)), 112) < CONVERT(varchar, GETDATE(), 112)
    AND /*data.sys_nitsusuu_last_sbu*/1 > 0
)

ORDER BY 
    'HAIKI_KBN_CD' ASC,'一次二次' ASC,'終了日警告区分' ASC,'経過日数' ASC