SELECT 
	 MSYS.MANIFEST_UNPAN_DAYS,
	 MSYS.MANIFEST_SBN_DAYS,
	 MSYS.MANIFEST_TOK_SBN_DAYS,
	 MSYS.MANIFEST_LAST_SBN_DAYS 
FROM M_SYS_INFO MSYS
WHERE 
	'0'= /*data.SYSTEM_ID*/0 
  AND ISNULL(MSYS.DELETE_FLG,0)=0