SELECT DISTINCT 
T_TEIKI_JISSEKI_DETAIL.GYOUSHA_CD,
M_GYOUSHA.GYOUSHA_NAME_RYAKU,  
T_TEIKI_JISSEKI_DETAIL.GENBA_CD, 
M_GENBA.GENBA_NAME_RYAKU,
T_TEIKI_JISSEKI_ENTRY.DENPYOU_DATE
FROM
T_TEIKI_JISSEKI_ENTRY INNER JOIN T_TEIKI_JISSEKI_DETAIL ON 
T_TEIKI_JISSEKI_ENTRY.SYSTEM_ID = T_TEIKI_JISSEKI_DETAIL.SYSTEM_ID
LEFT OUTER JOIN M_GENBA ON 
T_TEIKI_JISSEKI_DETAIL.GENBA_CD = M_GENBA.GENBA_CD AND 
T_TEIKI_JISSEKI_DETAIL.GYOUSHA_CD = M_GENBA.GYOUSHA_CD 
LEFT OUTER JOIN M_GYOUSHA ON 
T_TEIKI_JISSEKI_DETAIL.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD 
CROSS JOIN T_TEIKI_JISSEKI_ENTRY AS T_TEIKI_JISSEKI_ENTRY_1
WHERE
T_TEIKI_JISSEKI_DETAIL.GYOUSHA_CD IS NOT NULL AND
T_TEIKI_JISSEKI_DETAIL.GENBA_CD IS NOT NULL AND 
M_GYOUSHA.GYOUSHA_NAME_RYAKU IS NOT NULL AND 
M_GENBA.GENBA_NAME_RYAKU IS NOT NULL AND
T_TEIKI_JISSEKI_ENTRY.DENPYOU_DATE IS NOT NULL
/*IF data.YEAR != null*/AND CONVERT(CHAR(4),T_TEIKI_JISSEKI_ENTRY.DENPYOU_DATE,111) = /*data.YEAR*//*END*/
/*IF data.DENPYOU_DATE_FROM != null*/AND CONVERT(varchar,T_TEIKI_JISSEKI_ENTRY.DENPYOU_DATE,111) >= CONVERT(varchar,/*data.DENPYOU_DATE_FROM*/,111)/*END*/
/*IF data.dtp_KikanTO != null*/AND CONVERT(varchar,T_TEIKI_JISSEKI_ENTRY.DENPYOU_DATE,111) <= CONVERT(varchar,/*data.dtp_KikanTO*/,111)/*END*/
/*IF data.GYOUSHA_CD_FROM != null*/AND M_GYOUSHA.GYOUSHA_CD >= /*data.GYOUSHA_CD_FROM*//*END*/
/*IF data.GYOUSHA_CD_TO != null*/AND M_GYOUSHA.GYOUSHA_CD <= /*data.GYOUSHA_CD_TO*//*END*/
/*IF data.GENBA_CD_FROM != null*/AND M_GENBA.GENBA_CD >= /*data.GENBA_CD_FROM*//*END*/
/*IF data.GENBA_CD_TO != null*/AND M_GENBA.GENBA_CD <= /*data.GENBA_CD_TO*//*END*/