SELECT
YEAR(T_TEIKI_JISSEKI_ENTRY.DENPYOU_DATE) AS YEAR, 
T_TEIKI_JISSEKI_ENTRY.DENPYOU_DATE,
T_TEIKI_JISSEKI_DETAIL.GYOUSHA_CD, 
T_TEIKI_JISSEKI_DETAIL.GENBA_CD, 
T_TEIKI_JISSEKI_DETAIL.UNIT_CD, 
T_TEIKI_JISSEKI_DETAIL.HINMEI_CD,
M_HINMEI.HINMEI_NAME, 
M_UNIT.UNIT_NAME, 
T_TEIKI_JISSEKI_DETAIL.TSUKIGIME_KBN, 
SUM(T_TEIKI_JISSEKI_DETAIL.SUURYOU) AS Expr1,
M_GENBA.GENBA_NAME_RYAKU,
M_GYOUSHA.GYOUSHA_NAME_RYAKU

FROM
T_TEIKI_JISSEKI_ENTRY INNER JOIN T_TEIKI_JISSEKI_DETAIL ON 
T_TEIKI_JISSEKI_ENTRY.SYSTEM_ID = T_TEIKI_JISSEKI_DETAIL.SYSTEM_ID AND 
T_TEIKI_JISSEKI_ENTRY.SEQ = T_TEIKI_JISSEKI_DETAIL.SEQ 
INNER JOIN M_UNIT ON 
T_TEIKI_JISSEKI_DETAIL.UNIT_CD = M_UNIT.UNIT_CD 
INNER JOIN M_HINMEI ON 
T_TEIKI_JISSEKI_DETAIL.HINMEI_CD = M_HINMEI.HINMEI_CD
LEFT JOIN M_GENBA ON 
T_TEIKI_JISSEKI_DETAIL.GENBA_CD = M_GENBA.GENBA_CD AND 
T_TEIKI_JISSEKI_DETAIL.GYOUSHA_CD = M_GENBA.GYOUSHA_CD 
LEFT JOIN M_GYOUSHA ON 
T_TEIKI_JISSEKI_DETAIL.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD

WHERE 
T_TEIKI_JISSEKI_ENTRY.DELETE_FLG = 0 AND
M_UNIT.DELETE_FLG = 0 AND
M_HINMEI.DELETE_FLG = 0 AND 
T_TEIKI_JISSEKI_ENTRY.DENPYOU_DATE IS NOT NULL
/*IF data.YEAR != null*/AND CONVERT(CHAR(4),T_TEIKI_JISSEKI_ENTRY.DENPYOU_DATE,111) = /*data.YEAR*//*END*/
/*IF data.GYOUSHA_CD_FROM != null*/AND T_TEIKI_JISSEKI_DETAIL.GYOUSHA_CD >= /*data.GYOUSHA_CD_FROM*//*END*/
/*IF data.GYOUSHA_CD_TO != null*/AND T_TEIKI_JISSEKI_DETAIL.GYOUSHA_CD <= /*data.GYOUSHA_CD_TO*//*END*/
/*IF data.GENBA_CD_FROM != null*/AND T_TEIKI_JISSEKI_DETAIL.GENBA_CD >= /*data.GENBA_CD_FROM*//*END*/
/*IF data.GENBA_CD_TO != null*/AND T_TEIKI_JISSEKI_DETAIL.GENBA_CD <= /*data.GENBA_CD_TO*//*END*/

GROUP BY
YEAR(T_TEIKI_JISSEKI_ENTRY.DENPYOU_DATE), 
T_TEIKI_JISSEKI_ENTRY.DENPYOU_DATE,
T_TEIKI_JISSEKI_DETAIL.GYOUSHA_CD, 
T_TEIKI_JISSEKI_DETAIL.GENBA_CD, 
T_TEIKI_JISSEKI_DETAIL.UNIT_CD, 
M_HINMEI.HINMEI_NAME, 
M_UNIT.UNIT_NAME, 
T_TEIKI_JISSEKI_DETAIL.TSUKIGIME_KBN,
T_TEIKI_JISSEKI_DETAIL.HINMEI_CD,
M_GENBA.GENBA_NAME_RYAKU,
M_GYOUSHA.GYOUSHA_NAME_RYAKU
ORDER BY
YEAR(T_TEIKI_JISSEKI_ENTRY.DENPYOU_DATE),
T_TEIKI_JISSEKI_DETAIL.GYOUSHA_CD, 
T_TEIKI_JISSEKI_DETAIL.GENBA_CD, 
T_TEIKI_JISSEKI_DETAIL.UNIT_CD,
T_TEIKI_JISSEKI_DETAIL.HINMEI_CD
