SELECT 
DELETE_FLG,
DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD,
DENSHI_KEIYAKU_SHANAI_KEIRO_NAME,
DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_FURIGANA,
CREATE_USER,
CREATE_DATE,
CREATE_PC,
UPDATE_USER,
UPDATE_DATE,
UPDATE_PC,
TIME_STAMP
FROM 
M_DENSHI_KEIYAKU_SHANAI_KEIRO_NAME 
/*BEGIN*/WHERE
/*IF !data.DELETE_FLG.IsNull*/
AND DELETE_FLG = /*data.DELETE_FLG*/
/*END*/
/*IF !data.DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD.IsNull*/
AND CAST(DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD AS varchar(2)) LIKE '%' + CAST(/*data.DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD*/0 AS varchar(2)) + '%'
/*END*/
/*IF data.DENSHI_KEIYAKU_SHANAI_KEIRO_NAME != null && data.DENSHI_KEIYAKU_SHANAI_KEIRO_NAME != ''*/
AND DENSHI_KEIYAKU_SHANAI_KEIRO_NAME LIKE '%' + /*data.DENSHI_KEIYAKU_SHANAI_KEIRO_NAME*/ + '%'
/*END*/
/*IF data.DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_FURIGANA != null && data.DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_FURIGANA != ''*/
AND DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_FURIGANA LIKE '%' +  /*data.DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_FURIGANA*/ + '%'
/*END*/
/*IF data.CREATE_USER != null && data.CREATE_USER != ''*/
AND CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'
/*END*/
/*IF data.SEARCH_CREATE_DATE != null && data.SEARCH_CREATE_DATE != ''*/
AND CONVERT(nvarchar, CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'
/*END*/
/*IF data.UPDATE_USER != null && data.UPDATE_USER != ''*/
AND UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'
/*END*/
/*IF data.SEARCH_UPDATE_DATE != null && data.SEARCH_UPDATE_DATE != ''*/
AND CONVERT(nvarchar, UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'
/*END*/
/*IF !deletechuFlg*/AND DELETE_FLG = 0/*END*/
/*END*/
ORDER BY DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD
