SELECT 
  ISNULL(M_SHARYOU.SHARYOU_CD, '') SHARYOU_CD
, M_SHARYOU.SHARYOU_NAME_RYAKU
, ISNULL(M_SHARYOU.SHASYU_CD, '') SHASYU_CD
, M_SHASHU.SHASHU_NAME_RYAKU
, CASE WHEN M_WORK_CLOSED_UNTENSHA.SHAIN_CD IS NULL
    THEN ISNULL(M_SHARYOU.SHAIN_CD, '')
    ELSE ''
END AS SHAIN_CD
, CASE WHEN M_WORK_CLOSED_UNTENSHA.SHAIN_CD IS NULL
    THEN M_SHAIN.SHAIN_NAME_RYAKU
    ELSE ''
END AS SHAIN_NAME_RYAKU
, ISNULL(M_SHARYOU.GYOUSHA_CD, '') GYOUSHA_CD
, M_GYOUSHA.GYOUSHA_NAME_RYAKU
, ISNULL(CONVERT(int, M_SHARYOU.SAIDAI_WAKU_SUU), 30) SAIDAI_WAKU_SUU
, CAST(CASE WHEN M_WORK_CLOSED_SHARYOU.CLOSED_DATE IS NULL THEN 0 ELSE 1 END AS bit) WORK_CLOSED_SHARYOU
/*IF data.HaisyaKubun != null && !data.HaisyaKubun*/
    , CAST(CASE WHEN M_WORK_CLOSED_UNTENSHA.CLOSED_DATE IS NULL THEN 0 ELSE 1 END AS bit) WORK_CLOSED_UNTENSHA
    -- ELSE , CAST(0 AS bit) AS WORK_CLOSED_UNTENSHA
/*END*/
FROM 
  (SELECT * FROM M_SHARYOU 
  WHERE M_SHARYOU.GYOUSHA_CD IS NOT NULL
  AND HAISHA_WARIATE = 1) M_SHARYOU
LEFT JOIN (SELECT * FROM M_SHAIN 
  WHERE  M_SHAIN.UNTEN_KBN = 1
  ) M_SHAIN  
ON M_SHAIN.SHAIN_CD = M_SHARYOU.SHAIN_CD 
LEFT JOIN (SELECT * FROM M_SHASHU) M_SHASHU
ON M_SHARYOU.SHASYU_CD = M_SHASHU.SHASHU_CD
LEFT JOIN (SELECT * FROM M_WORK_CLOSED_SHARYOU WHERE
(CLOSED_DATE IS NULL OR CLOSED_DATE = /*data.SagyouDate*/)) M_WORK_CLOSED_SHARYOU
ON M_SHARYOU.SHARYOU_CD = M_WORK_CLOSED_SHARYOU.SHARYOU_CD
AND M_SHARYOU.GYOUSHA_CD = M_WORK_CLOSED_SHARYOU.GYOUSHA_CD
LEFT JOIN (SELECT * FROM M_WORK_CLOSED_UNTENSHA WHERE 
(CLOSED_DATE IS NULL OR CLOSED_DATE = /*data.SagyouDate*/)) M_WORK_CLOSED_UNTENSHA
ON M_SHARYOU.SHAIN_CD = M_WORK_CLOSED_UNTENSHA.SHAIN_CD
LEFT JOIN M_GYOUSHA
ON M_GYOUSHA.GYOUSHA_CD = M_SHARYOU.GYOUSHA_CD
WHERE
    M_WORK_CLOSED_SHARYOU.SHARYOU_CD IS NULL
    /*IF data.HaisyaKubun != null && !data.HaisyaKubun*/
        -- é≤ÅFé‘éÌÅ^é‘óºÇÃèÍçá
        --   ãxìÆìoò^(â^ì]é“)Ç≥ÇÍÇƒÇ¢ÇÈèÍçáÇÕçsÇÃï\é¶ÇÕÇ∑ÇÈÇ™ÅAâ^ì]é“ÇÉuÉâÉìÉNÇ≈ï\é¶
        -- é≤ÅFâ^ì]é“ÇÃèÍçá
        --   ãxìÆìoò^(â^ì]é“)Ç≥ÇÍÇƒÇ¢ÇÈèÍçáÇÕîÒï\é¶
        AND M_WORK_CLOSED_UNTENSHA.SHAIN_CD IS NULL
    /*END*/
ORDER BY M_SHARYOU.SHAIN_CD, M_SHARYOU.SHASYU_CD, M_SHARYOU.SHARYOU_CD