SELECT M_SHARYOU.GYOUSHA_CD
, M_SHARYOU.SHARYOU_CD
, M_SHARYOU.SHARYOU_NAME_RYAKU
, M_SHARYOU.SHASYU_CD
, M_SHASHU.SHASHU_NAME_RYAKU
, M_SHARYOU.GYOUSHA_CD
, M_GYOUSHA.GYOUSHA_NAME_RYAKU
, ISNULL(CONVERT(int, M_SHARYOU.SAIDAI_WAKU_SUU), 30) SAIDAI_WAKU_SUU
, CAST(CASE WHEN M_WORK_CLOSED_SHARYOU.CLOSED_DATE IS NULL THEN 0 ELSE 1 END AS bit) WORK_CLOSED_SHARYOU
FROM (SELECT * FROM M_SHARYOU WHERE DELETE_FLG = 0 AND SHARYOU_CD = /*data.SharyouCd*/
/*IF data.ShashuCd != null*/AND SHASYU_CD = /*data.ShashuCd*//*END*/
/*IF data.GyoushaCd != null*/AND GYOUSHA_CD = /*data.GyoushaCd*//*END*/
) M_SHARYOU
LEFT JOIN (SELECT * FROM M_WORK_CLOSED_SHARYOU WHERE DELETE_FLG = 0
AND (CLOSED_DATE IS NULL OR CLOSED_DATE = /*data.SagyouDate*/)) M_WORK_CLOSED_SHARYOU
ON M_SHARYOU.SHARYOU_CD = M_WORK_CLOSED_SHARYOU.SHARYOU_CD
AND M_SHARYOU.GYOUSHA_CD = M_WORK_CLOSED_SHARYOU.GYOUSHA_CD
LEFT JOIN (SELECT * FROM M_SHASHU WHERE DELETE_FLG = 0) M_SHASHU
ON M_SHARYOU.SHASYU_CD = M_SHASHU.SHASHU_CD 
LEFT JOIN (SELECT * FROM M_GYOUSHA WHERE DELETE_FLG = 0) M_GYOUSHA 
ON M_SHARYOU.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
