SELECT M_WORK_CLOSED_UNTENSHA.BIKOU
, CAST(CASE WHEN M_WORK_CLOSED_UNTENSHA.CLOSED_DATE IS NULL THEN 0 ELSE 1 END AS bit) WORK_CLOSED_UNTENSHA
, UNTEN_KBN
, SHAIN_NAME_RYAKU
FROM (SELECT * FROM M_SHAIN WHERE DELETE_FLG = 0 AND SHAIN_CD = /*data.ShainCd*/) M_SHAIN
LEFT JOIN (SELECT * FROM M_WORK_CLOSED_UNTENSHA WHERE DELETE_FLG = 0
AND (CLOSED_DATE IS NULL OR CLOSED_DATE = /*data.SagyouDate*/)) M_WORK_CLOSED_UNTENSHA
ON M_SHAIN.SHAIN_CD = M_WORK_CLOSED_UNTENSHA.SHAIN_CD