SELECT GTH.*
		,ISNULL(H1.HINMEI_NAME_RYAKU,N'') AS HINMEI_NAME
		,ISNULL(H2.HINMEI_NAME_RYAKU,N'') AS TSUKI_HINMEI_NAME
		,ISNULL(U1.UNIT_NAME_RYAKU,N'') AS UNIT_NAME_RYAKU
		,ISNULL(U2.UNIT_NAME_RYAKU,N'') AS KANSAN_UNIT_NAME_RYAKU
		,ISNULL(D.DENPYOU_KBN_NAME_RYAKU,N'') AS DENPYOU_KBN_NAME_RYAKU
		,(CASE WHEN GTH.KEIYAKU_KBN = 1 THEN '定期' WHEN GTH.KEIYAKU_KBN = 2 THEN '単価' WHEN GTH.KEIYAKU_KBN = 3 THEN '回収のみ' ELSE '' END) AS KEIYAKU_KBN_NAME
		,(CASE WHEN GTH.KEIJYOU_KBN = 1 THEN '伝票' WHEN GTH.KEIJYOU_KBN = 2 THEN '合算' ELSE '' END) AS KEIJYOU_KBN_NAME
		,GEN.SHIKUCHOUSON_CD
		,GEN.SHIKUCHOUSON_NAME_RYAKU
  FROM M_GENBA_TEIKI_HINMEI GTH
	LEFT JOIN M_GENBA_TSUKI_HINMEI TSUKI 
	ON GTH.GYOUSHA_CD = TSUKI.GYOUSHA_CD
	AND GTH.GENBA_CD = TSUKI.GENBA_CD
	AND GTH.TSUKI_HINMEI_CD = TSUKI.HINMEI_CD
	LEFT JOIN M_HINMEI H1 ON H1.HINMEI_CD = GTH.HINMEI_CD
	LEFT JOIN M_HINMEI H2 ON H2.HINMEI_CD = GTH.TSUKI_HINMEI_CD
	LEFT JOIN M_UNIT U1 ON U1.UNIT_CD = GTH.UNIT_CD
	LEFT JOIN M_UNIT U2 ON U2.UNIT_CD = GTH.KANSAN_UNIT_CD
	LEFT JOIN M_DENPYOU_KBN D ON D.DENPYOU_KBN_CD = GTH.DENPYOU_KBN_CD
	LEFT JOIN (
		SELECT M_GENBA.GYOUSHA_CD, M_GENBA.GENBA_CD, M_GENBA.SHIKUCHOUSON_CD, M_SHIKUCHOUSON.SHIKUCHOUSON_NAME_RYAKU
		FROM M_GENBA
		INNER JOIN M_SHIKUCHOUSON ON M_GENBA.SHIKUCHOUSON_CD = M_SHIKUCHOUSON.SHIKUCHOUSON_CD
	) AS GEN ON (GTH.GYOUSHA_CD = GEN.GYOUSHA_CD) AND (GTH.GENBA_CD = GEN.GENBA_CD)
 WHERE GTH.GYOUSHA_CD = /*gyoushaCD*/''
   AND GTH.GENBA_CD = /*genbaCD*/''
 ORDER BY GTH.ROW_NO ASC