SELECT
	DISTINCT 
	T1.ITAKU_KEIYAKU_NO  ,
	ITAKU_KEIYAKU_SHURUI =
	CASE 
      WHEN T1.ITAKU_KEIYAKU_SHURUI = 1 THEN '収集・運搬委託契約' 
      WHEN T1.ITAKU_KEIYAKU_SHURUI = 2 THEN '処分委託契約'  
	  WHEN T1.ITAKU_KEIYAKU_SHURUI = 3 THEN '収集・運搬/処分委託契約' 
	END ,

	T1.YUUKOU_BEGIN AS YUUKOU_BEGIN,
	'～' AS YUUKOU_RENKETSU,
	T1.YUUKOU_END AS YUUKOU_END,
	ITAKU_KEIYAKU_STATUS =
	CASE 
      WHEN T1.ITAKU_KEIYAKU_STATUS = 1 THEN '作成'  
      WHEN T1.ITAKU_KEIYAKU_STATUS = 2 THEN '送付' 
	  WHEN T1.ITAKU_KEIYAKU_STATUS = 3 THEN '返送' 
	  WHEN T1.ITAKU_KEIYAKU_STATUS = 4 THEN '保管' 
	  WHEN T1.ITAKU_KEIYAKU_STATUS = 5 THEN '解約済' 
	END ,
	T1.SYSTEM_ID AS SYSTEM_ID
FROM
	((
		SELECT
			T2.SYSTEM_ID,
			T2.ITAKU_KEIYAKU_NO,
			T2.ITAKU_KEIYAKU_SHURUI,
			T2.YUUKOU_BEGIN,
			T2.YUUKOU_END,
			CASE WHEN T2.YUUKOU_END IS NOT NULL AND ISNULL(T2.KOUSHIN_SHUBETSU, 0) = 2 AND CONVERT(date, T2.YUUKOU_END) < CONVERT(date, GETDATE())
				THEN '5'
				ELSE
					CASE WHEN T2.KOUSHIN_END_DATE IS NOT NULL AND ISNULL(T2.KOUSHIN_SHUBETSU, 0) = 1 AND CONVERT(date, T2.KOUSHIN_END_DATE) < CONVERT(date, GETDATE())
					THEN '5'
					ELSE
						CASE WHEN T2.KEIYAKUSHO_END_DATE IS NOT NULL
						THEN '4'
						ELSE
							CASE WHEN T2.KEIYAKUSHO_RETURN_DATE IS NOT NULL
							THEN '3'
							ELSE
								CASE WHEN T2.KEIYAKUSHO_SEND_DATE IS NOT NULL
								THEN '2'
								ELSE
									CASE WHEN T2.KEIYAKUSHO_CREATE_DATE IS NOT NULL
									THEN '1'
									ELSE ''
								END
							END
						END
					END
				END
			END AS 'ITAKU_KEIYAKU_STATUS'
		FROM
			M_ITAKU_KEIYAKU_KIHON T2
		WHERE
			1 = 1
			/*IF null != gyoushaCd && ''!=gyoushaCd*/AND T2.HAISHUTSU_JIGYOUSHA_CD = /*gyoushaCd*/0 /*END*/
			/*IF null != genbaCd && ''!=genbaCd*/AND T2.HAISHUTSU_JIGYOUJOU_CD = /*genbaCd*/0 /*END*/
	)
	UNION ALL
	(
		SELECT
			T4.SYSTEM_ID,
			T4.ITAKU_KEIYAKU_NO,
			T4.ITAKU_KEIYAKU_SHURUI,
			T4.YUUKOU_BEGIN,
			T4.YUUKOU_END,
			CASE WHEN T4.YUUKOU_END IS NOT NULL AND ISNULL(T4.KOUSHIN_SHUBETSU, 0) = 2 AND CONVERT(date, T4.YUUKOU_END) < CONVERT(date, GETDATE())
				THEN '5'
				ELSE
					CASE WHEN T4.KOUSHIN_END_DATE IS NOT NULL AND ISNULL(T4.KOUSHIN_SHUBETSU, 0) = 1 AND CONVERT(date, T4.KOUSHIN_END_DATE) < CONVERT(date, GETDATE())
					THEN '5'
					ELSE
						CASE WHEN T4.KEIYAKUSHO_END_DATE IS NOT NULL
						THEN '4'
						ELSE
							CASE WHEN T4.KEIYAKUSHO_RETURN_DATE IS NOT NULL
							THEN '3'
							ELSE
								CASE WHEN T4.KEIYAKUSHO_SEND_DATE IS NOT NULL
								THEN '2'
								ELSE
									CASE WHEN T4.KEIYAKUSHO_CREATE_DATE IS NOT NULL
									THEN '1'
									ELSE ''
								END
							END
						END
					END
				END
			END AS 'ITAKU_KEIYAKU_STATUS'
		FROM
			M_ITAKU_KEIYAKU_KIHON_HST_GENBA T3
				LEFT JOIN M_ITAKU_KEIYAKU_KIHON T4 ON T4.SYSTEM_ID = T3.SYSTEM_ID
		WHERE
			1 = 1
			/*IF null != gyoushaCd && ''!=gyoushaCd*/AND T3.HAISHUTSU_JIGYOUSHA_CD = /*gyoushaCd*/0 /*END*/
			/*IF null != genbaCd && ''!=genbaCd*/AND T3.HAISHUTSU_JIGYOUJOU_CD = /*genbaCd*/0 /*END*/
	)) T1
ORDER BY T1.ITAKU_KEIYAKU_NO