SELECT 
	T1.HINMEI_CD AS HINMEI_CD,
	T2.HINMEI_NAME AS HINMEI_NAME,
	T2.HINMEI_NAME_RYAKU AS HINMEI_NAME_RYAKU,
	--T1.DENSHU_KBN_CD AS DENSHU_KBN_CD,
	T3.DENSHU_KBN_NAME AS DENSHU_KBN_NAME,
	--T1.UNIT_CD AS UNIT_CD,
	T7.UNIT_NAME AS UNIT_NAME,
	T1.UNPAN_GYOUSHA_CD AS UNPAN_GYOUSHA_CD,
	T4.GYOUSHA_NAME1 AS UNPAN_GYOUSHA_NAME,
	T1.NIOROSHI_GYOUSHA_CD AS NIOROSHI_GYOUSHA_CD,
	T5.GYOUSHA_NAME1 AS NIOROSHI_GYOUSHA_NAME,
	T1.NIOROSHI_GENBA_CD AS NIOROSHI_GENBA_CD,
	T6.GENBA_NAME1 AS NIOROSHI_GENBA_NAME,
	T1.TANKA AS TANKA,
	T1.BIKOU AS BIKOU,
	T1.TEKIYOU_BEGIN AS TEKIYOU_BEGIN,
	T1.TEKIYOU_END AS TEKIYOU_END,
	T1.UPDATE_USER AS UPDATE_USER,
	T1.UPDATE_DATE AS UPDATE_DATE,
	T1.CREATE_USER AS CREATE_USER,
	T1.CREATE_DATE AS CREATE_DATE

FROM dbo.M_KOBETSU_HINMEI_TANKA AS T1 
LEFT JOIN dbo.M_HINMEI AS T2 ON T1.HINMEI_CD = T2.HINMEI_CD 
LEFT JOIN dbo.M_DENSHU_KBN AS T3 ON T1.DENSHU_KBN_CD = T3.DENSHU_KBN_CD 
LEFT JOIN dbo.M_GYOUSHA AS T4 ON T1.UNPAN_GYOUSHA_CD = T4.GYOUSHA_CD 
LEFT JOIN dbo.M_GYOUSHA AS T5 ON T1.NIOROSHI_GYOUSHA_CD = T5.GYOUSHA_CD 
LEFT JOIN dbo.M_GENBA AS T6 ON T1.NIOROSHI_GENBA_CD = T6.GENBA_CD AND T1.NIOROSHI_GYOUSHA_CD =T6.GYOUSHA_CD 
LEFT JOIN dbo.M_UNIT AS T7 ON T1.UNIT_CD = T7.UNIT_CD 

WHERE 
1=1
AND T1.DELETE_FLG = 0
/*IF null != data.TORIHIKISAKI_CD && ''!=data.TORIHIKISAKI_CD*/AND T1.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/0 /*END*/
/*IF null != data.GYOUSHA_CD && ''!=data.GYOUSHA_CD*/AND T1.GYOUSHA_CD = /*data.GYOUSHA_CD*/0 /*END*/
/*IF null != data.GENBA_CD  && ''!=data.GENBA_CD*/AND T1.GENBA_CD = /*data.GENBA_CD*/0 /*END*/
/*IF null != denpyouKbnCd  && ''!=denpyouKbnCd*/AND T1.DENPYOU_KBN_CD = /*denpyouKbnCd*/0 /*END*/
ORDER BY T1.HINMEI_CD