SELECT 
	T1.TORIHIKISAKI_POST AS TORIHIKISAKI_POST,
	T1.TORIHIKISAKI_TODOUFUKEN_CD AS TODOUFUKEN_CD,
	T2.TODOUFUKEN_NAME AS TODOUFUKEN_NAME,
	T1.TORIHIKISAKI_ADDRESS1 AS TORIHIKISAKI_ADDRESS1,
	T1.TORIHIKISAKI_ADDRESS2 AS TORIHIKISAKI_ADDRESS2,
	T1.BUSHO AS BUSHO,
	T1.TANTOUSHA AS TANTOUSHA,
	T1.SHUUKEI_ITEM_CD AS SHUUKEI_ITEM_CD,
	T4.SHUUKEI_KOUMOKU_NAME AS SHUUKEI_ITEM_NAME,
	T4.SHUUKEI_KOUMOKU_NAME_RYAKU AS SHUUKEI_ITEM_NAME_RYAKU,
	T1.GYOUSHU_CD AS GYOUSHU_CD,
	T3.GYOUSHU_NAME AS GYOUSHU_NAME,
	T3.GYOUSHU_NAME_RYAKU AS GYOUSHU_NAME_RYAKU,
	T1.DAIHYOU_PRINT_KBN AS DAIHYOU_PRINT_KBN,
	T1.BIKOU1 AS BIKOU1,
	T1.BIKOU2 AS BIKOU2,
	T1.BIKOU3 AS BIKOU3,
	T1.BIKOU4 AS BIKOU4,
	T1.SHOKUCHI_KBN AS SHOKUCHI_KBN,
	T1.MANI_HENSOUSAKI_KBN AS MANI_HENSOUSAKI_KBN,
	T1.MANI_HENSOUSAKI_NAME1 AS MANI_HENSOUSAKI_NAME1,
	T1.MANI_HENSOUSAKI_KEISHOU1 AS MANI_HENSOUSAKI_KEISHOU1,
	T1.MANI_HENSOUSAKI_NAME2 AS MANI_HENSOUSAKI_NAME2,
	T1.MANI_HENSOUSAKI_KEISHOU2 AS MANI_HENSOUSAKI_KEISHOU2,
	T1.MANI_HENSOUSAKI_POST AS MANI_HENSOUSAKI_POST,
	T1.MANI_HENSOUSAKI_ADDRESS1 AS MANI_HENSOUSAKI_ADDRESS1,
	T1.MANI_HENSOUSAKI_ADDRESS2 AS MANI_HENSOUSAKI_ADDRESS2,
	T1.MANI_HENSOUSAKI_BUSHO AS MANI_HENSOUSAKI_BUSHO,
	T1.MANI_HENSOUSAKI_TANTOU AS MANI_HENSOUSAKI_TANTOU,
	T1.MANI_HENSOUSAKI_THIS_ADDRESS_KBN AS MANI_HENSOUSAKI_THIS_ADDRESS_KBN


FROM dbo.M_TORIHIKISAKI AS T1 
LEFT JOIN dbo.M_TODOUFUKEN AS T2 ON T1.TORIHIKISAKI_TODOUFUKEN_CD = T2.TODOUFUKEN_CD 
LEFT JOIN dbo.M_GYOUSHU AS T3 ON T1.GYOUSHU_CD = T3.GYOUSHU_CD 
LEFT JOIN dbo.M_SHUUKEI_KOUMOKU AS T4 ON T1.SHUUKEI_ITEM_CD = T4.SHUUKEI_KOUMOKU_CD 

WHERE 
 T1.TORIHIKISAKI_CD = /*torihikisakiCd*/