SELECT 
	T1.NYUUSHUKKIN_KBN_CD AS NYUUSHUKKIN_KBN_CD,
	T2.NYUUSHUKKIN_KBN_NAME_RYAKU AS NYUUSHUKKIN_KBN_NAME_RYAKU,
	T1.KINGAKU AS KINGAKU,
	T1.MEISAI_BIKOU AS MEISAI_BIKOU


FROM dbo.T_NYUUKIN_DETAIL AS T1 
LEFT JOIN dbo.M_NYUUSHUKKIN_KBN AS T2 ON T1.NYUUSHUKKIN_KBN_CD = T2.NYUUSHUKKIN_KBN_CD 


WHERE 
 T1.SYSTEM_ID = /*systemId*/0 /*END*/
AND T1.SEQ = /*seq*/0 /*END*/

ORDER BY T1.ROW_NUMBER