SELECT TOP(100)
	CONVERT(varchar(100), T1.DENPYOU_DATE, 111) AS DENPYOU_DATE,
    CONVERT(varchar(100), T1.KENSHU_DATE, 111) AS KENSHU_DATE,
    T2.HINMEI_CD AS SHUKKA_DETAIL_HINMEI_CD,
    T2.HINMEI_NAME AS SHUKKA_DETAIL_HINMEI_NAME,
    CASE T2.DENPYOU_KBN_CD WHEN 1 THEN '売上' WHEN 2 THEN '支払' ELSE '' END AS SHUKKA_DETAIL_DENPYOU_KBN_NAME,
    ISNULL(T2.NET_JYUURYOU, 0) AS SHUKKA_DETAIL_NET_JYUURYOU,
    ISNULL(T2.SUURYOU, 0) AS SHUKKA_DETAIL_SUURYOU,
    T3.UNIT_NAME_RYAKU AS SHUKKA_DETAIL_UNIT_NAME,
    T2.ROW_NO AS ROW_NO,
    T4.HINMEI_CD AS KENSYU_DETAIL_HINMEI_CD,
	T4.HINMEI_NAME  KENSYU_DETAIL_HINMEI_NAME,
    CASE T4.DENPYOU_KBN_CD WHEN 1 THEN '売上' WHEN 2 THEN '支払' ELSE '' END AS KENSYU_DETAIL_DENPYOU_KBN_NAME,
	ISNULL(T4.KENSHU_NET, 0) AS KENSHU_NET_JYUURYOU,
	ISNULL(T4.SUURYOU, 0) AS KENSYU_DETAIL_SUURYOU,
    T5.UNIT_NAME_RYAKU AS KENSYU_DETAIL_UNIT_NAME,
    T4.BUBIKI AS KENSYU_DETAIL_BUBIKI,
    T4.TANKA AS KENSYU_DETAIL_TANKA,
	ISNULL(T4.KINGAKU, 0) + ISNULL(T4.HINMEI_KINGAKU, 0) AS KENSYU_DETAIL_KINGAKU,
	T1.SYSTEM_ID AS SYSTEM_ID,
	T1.SEQ AS SEQ
	

FROM dbo.T_SHUKKA_ENTRY AS T1 

LEFT JOIN dbo.T_SHUKKA_DETAIL AS T2 ON T1.SYSTEM_ID = T2.SYSTEM_ID AND T1.SEQ = T2.SEQ
LEFT JOIN dbo.M_UNIT AS T3 ON T2.UNIT_CD = T3.UNIT_CD 
INNER JOIN dbo.T_KENSHU_DETAIL T4 ON T2.SYSTEM_ID = T4.SYSTEM_ID AND T2.SEQ = T4.SEQ AND T2.DETAIL_SYSTEM_ID = T4.DETAIL_SYSTEM_ID
LEFT JOIN dbo.M_UNIT AS T5 ON T4.UNIT_CD = T5.UNIT_CD 

WHERE 
T1.SYSTEM_ID = /*systemId*/0 /*END*/
AND T1.SEQ = /*seq*/0 /*END*/

ORDER BY T2.ROW_NO