SELECT 
	TOP(100)
    '0' AS JYOUKYOU_SEISAN,
	T1.DENPYOU_DATE AS DENPYOU_DATE,
	T1.SHUKKIN_NUMBER AS SHUKKIN_NUMBER_DISP,
	T1.TORIHIKISAKI_CD AS TORIHIKISAKI_CD,
	T2.TORIHIKISAKI_NAME_RYAKU AS TORIHIKISAKI_NAME_RYAKU,
	T1.DENPYOU_BIKOU,
	T1.SYSTEM_ID AS SYSTEM_ID,
	T1.SEQ AS SEQ,
	T1.SHUKKIN_NUMBER AS SHUKKIN_NUMBER
	

FROM dbo.T_SHUKKIN_ENTRY AS T1 

	LEFT JOIN dbo.M_TORIHIKISAKI AS T2 ON T1.TORIHIKISAKI_CD = T2.TORIHIKISAKI_CD 
	JOIN (SELECT MAX(SEQ) AS SEQ,SYSTEM_ID FROM T_SHUKKIN_ENTRY   group by SYSTEM_ID) AS TX ON T1.SEQ = TX.SEQ  AND T1.SYSTEM_ID = TX.SYSTEM_ID
 
WHERE 
1=1
/*IF !torihikisakiCd.IsNull && ''!=torihikisakiCd*/AND T1.TORIHIKISAKI_CD = /*torihikisakiCd*/0 /*END*/
/*IF !kyotenCd.IsNull && ''!=kyotenCd && '99'!=kyotenCd*/AND T1.KYOTEN_CD = /*kyotenCd*//*END*/
/*IF !fromDate.IsNull && ''!=fromDate*/AND CONVERT(varchar(10), T1.DENPYOU_DATE, 120) >= /*fromDate*//*END*/
/*IF !toDate.IsNull && ''!=toDate*/AND CONVERT(varchar(10), T1.DENPYOU_DATE, 120) <= /*toDate*//*END*/
AND T1.DELETE_FLG = 0

ORDER BY T1.DENPYOU_DATE desc, T1.SYSTEM_ID asc