SELECT 
    '0' AS JYOUKYOU,
	T1.SYSTEM_ID AS SYSTEM_ID,
	T1.SEQ AS SEQ,
	T1.DETAIL_SYSTEM_ID AS DETAIL_SYSTEM_ID,
	T1.UR_SH_NUMBER AS UR_SH_NUMBER,
	T1.URIAGESHIHARAI_DATE AS URIAGESHIHARAI_DATE,
	T1.HINMEI_CD AS HINMEI_CD,
	T1.HINMEI_NAME AS HINMEI_NAME,
	T2.DENPYOU_KBN_NAME_RYAKU AS DENPYOU_KBN_NAME_RYAKU,
	T1.SUURYOU AS SUURYOU,
	--T1.UNIT_CD AS UNIT_CD,
	T3.UNIT_NAME_RYAKU AS UNIT_NAME_RYAKU,
	T1.TANKA AS TANKA,
	CASE WHEN T1.KINGAKU <> 0 THEN T1.KINGAKU ELSE T1.HINMEI_KINGAKU END AS KINGAKU,
	--T1.NISUGATA_SUURYOU AS NISUGATA_SUURYOU,
	--T4.UNIT_NAME_RYAKU AS NISUGATA_NAME_RYAKU,
	T1.MEISAI_BIKOU AS MEISAI_BIKOU

		

FROM dbo.T_UR_SH_DETAIL AS T1 
LEFT JOIN dbo.M_DENPYOU_KBN AS T2 ON T1.DENPYOU_KBN_CD = T2.DENPYOU_KBN_CD 
LEFT JOIN dbo.M_UNIT AS T3 ON T1.UNIT_CD = T3.UNIT_CD 
LEFT JOIN dbo.M_UNIT AS T4 ON T1.NISUGATA_UNIT_CD = T4.UNIT_CD 

WHERE 
 T1.SYSTEM_ID = /*systemId*/0 /*END*/
AND T1.SEQ = /*seq*/0 /*END*/
ORDER BY T1.ROW_NO

