SELECT 
	T1.HINMEI_CD AS HINMEI_CD,
	T1.HINMEI_NAME AS HINMEI_NAME,
	T2.DENPYOU_KBN_NAME_RYAKU AS DENPYOU_KBN_NAME_RYAKU,
	T1.SUURYOU AS SUURYOU,
	T3.UNIT_NAME_RYAKU AS UNIT_NAME_RYAKU,
	T1.TANKA AS TANKA,
	(ISNULL(T1.KINGAKU, 0) + ISNULL(T1.HINMEI_KINGAKU, 0)) AS KINGAKU,
	(T1.TAX_SOTO+T1.TAX_UCHI +T1.HINMEI_TAX_SOTO +T1.HINMEI_TAX_UCHI) AS ZEI,
	T1.MEISAI_BIKOU AS MEISAI_BIKOU
	

FROM dbo.T_UKETSUKE_SS_DETAIL AS T1 
LEFT JOIN dbo.M_DENPYOU_KBN AS T2 ON T1.DENPYOU_KBN_CD = T2.DENPYOU_KBN_CD 
LEFT JOIN dbo.M_UNIT AS T3 ON T1.UNIT_CD = T3.UNIT_CD 


WHERE 
 T1.SYSTEM_ID = /*systemId*/0 /*END*/
AND T1.SEQ = /*seq*/0 /*END*/

ORDER BY T1.ROW_NO

