SELECT *
FROM
(
SELECT
	'0' AS JYOUKYOU_SEIKYUU,
	'0' AS JYOUKYOU_SEISAN,
	'0' AS JYOUKYOU_SALES_ZAIKO,
	ISNULL(URIAGE.UKEIRE_DENPYOU_NUMBER, SHIHARAI.SHUKKA_DENPYOU_NUMBER) AS DENPYOU_NUMBER,
	ISNULL(URIAGE.UKEIRE_DENPYOU_DATE, SHIHARAI.SHUKKA_DENPYOU_DATE) AS DENPYOU_DATE,
	ISNULL(URIAGE.UKEIRE_UNPAN_GYOUSHA_CD, SHIHARAI.SHUKKA_UNPAN_GYOUSHA_CD) AS UNPAN_GYOUSHA_CD,
	ISNULL(URIAGE.UKEIRE_UNPAN_GYOUSHA_NAME, SHIHARAI.SHUKKA_UNPAN_GYOUSHA_NAME) AS UNPAN_GYOUSHA_NAME,
	ISNULL(URIAGE.UKEIRE_SHASHU, SHIHARAI.SHUKKA_SHASHU) AS SHASHU,
	ISNULL(URIAGE.UKEIRE_SHARYOU, SHIHARAI.SHUKKA_SHARYOU) AS SHARYOU,
	ISNULL(URIAGE.UKEIRE_UNTENSHA, SHIHARAI.SHUKKA_UNTENSHA) AS UNTENSHA,
	* ,	
	ISNULL(URIAGE.UKEIRE_DENPYOU_BIKOU, SHIHARAI.SHUKKA_DENPYOU_BIKOU) AS DENPYOU_BIKOU
FROM
--------------URIAGE START----------------------
	(SELECT
		T1.SYSTEM_ID AS UKEIRE_SYSTEM_ID,
		T1.SEQ AS UKEIRE_SEQ,
		T1.UR_SH_NUMBER AS UKEIRE_DENPYOU_NUMBER,
		T1.DENPYOU_DATE AS UKEIRE_DENPYOU_DATE,
		T1.UNPAN_GYOUSHA_CD AS UKEIRE_UNPAN_GYOUSHA_CD,
		T1.UNPAN_GYOUSHA_NAME AS UKEIRE_UNPAN_GYOUSHA_NAME,
		T1.SHASHU_NAME AS UKEIRE_SHASHU,
		T1.SHARYOU_NAME AS UKEIRE_SHARYOU,
		T1.UNTENSHA_NAME AS UKEIRE_UNTENSHA,
		'受入' AS UKEIRE_KUBUN,
		T1.KYOTEN_CD AS UKEIRE_KYOTEN_CD,
		T1.TORIHIKISAKI_CD AS UKEIRE_TORIHIKISAKI_CD,
		T1.TORIHIKISAKI_NAME AS UKEIRE_TORIHIKISAKI_NAME,
		T1.GYOUSHA_CD AS UKEIRE_GYOUSHA_CD,
		T1.GYOUSHA_NAME AS UKEIRE_GYOUSHA_NAME,
		T1.GENBA_CD AS UKEIRE_GENBA_CD,
		T1.GENBA_NAME AS UKEIRE_GENBA_NAME,
		T1.DENPYOU_BIKOU AS UKEIRE_DENPYOU_BIKOU	
	FROM dbo.T_UR_SH_ENTRY AS T1 ,(SELECT MAX(SEQ) AS SEQ,SYSTEM_ID FROM T_UR_SH_ENTRY   group by SYSTEM_ID) AS TX

	WHERE 
	 T1.DAINOU_FLG = 1 AND T1.SHIHARAI_DATE IS NOT NULL AND T1.SHIHARAI_DATE <> ''
	AND T1.SEQ = TX.SEQ  AND T1.SYSTEM_ID = TX.SYSTEM_ID
	AND T1.DELETE_FLG = 0) AS URIAGE
	--------------URIAGE END----------------------
		FULL OUTER JOIN
		--------------SHIHARAI START------------------
		(SELECT
			T1.SYSTEM_ID AS SHUKKA_SYSTEM_ID,
			T1.SEQ AS SHUKKA_SEQ,
			T1.UR_SH_NUMBER AS SHUKKA_DENPYOU_NUMBER,
			T1.DENPYOU_DATE AS SHUKKA_DENPYOU_DATE,
			T1.UNPAN_GYOUSHA_CD AS SHUKKA_UNPAN_GYOUSHA_CD,
			T1.UNPAN_GYOUSHA_NAME AS SHUKKA_UNPAN_GYOUSHA_NAME,
			T1.SHASHU_NAME AS SHUKKA_SHASHU,
			T1.SHARYOU_NAME AS SHUKKA_SHARYOU,
			T1.UNTENSHA_NAME AS SHUKKA_UNTENSHA,
			'出荷' AS SHUKKA_KUBUN,
			T1.KYOTEN_CD AS SHUKKA_KYOTEN_CD,
			T1.TORIHIKISAKI_CD AS SHUKKA_TORIHIKISAKI_CD,
			T1.TORIHIKISAKI_NAME AS SHUKKA_TORIHIKISAKI_NAME,
			T1.GYOUSHA_CD AS SHUKKA_GYOUSHA_CD,
			T1.GYOUSHA_NAME AS SHUKKA_GYOUSHA_NAME,
			T1.GENBA_CD AS SHUKKA_GENBA_CD,
			T1.GENBA_NAME AS SHUKKA_GENBA_NAME,
			T1.DENPYOU_BIKOU AS SHUKKA_DENPYOU_BIKOU
		FROM dbo.T_UR_SH_ENTRY AS T1 ,(SELECT MAX(SEQ) AS SEQ,SYSTEM_ID FROM T_UR_SH_ENTRY   group by SYSTEM_ID) AS TX

		WHERE 
		 T1.DAINOU_FLG = 1 AND T1.URIAGE_DATE IS NOT NULL AND T1.URIAGE_DATE <> ''
		AND T1.SEQ = TX.SEQ  AND T1.SYSTEM_ID = TX.SYSTEM_ID
		AND T1.DELETE_FLG = 0) AS SHIHARAI 
		--------------SHIHARAI END--------------------
	ON URIAGE.UKEIRE_DENPYOU_NUMBER = SHIHARAI.SHUKKA_DENPYOU_NUMBER
	) AS T0
WHERE 1=1
		/*IF !torihikisakiCd.IsNull && ''!=torihikisakiCd*/AND (UKEIRE_TORIHIKISAKI_CD = /*torihikisakiCd*/0 OR SHUKKA_TORIHIKISAKI_CD = /*torihikisakiCd*/0)/*END*/
		/*IF !gyoushaCd.IsNull && ''!=gyoushaCd*/AND (UKEIRE_GYOUSHA_CD = /*gyoushaCd*/0 OR SHUKKA_GYOUSHA_CD = /*gyoushaCd*/0)/*END*/
		/*IF !genbaCd.IsNull && ''!=genbaCd*/AND (UKEIRE_GENBA_CD = /*genbaCd*/0 OR SHUKKA_GENBA_CD = /*genbaCd*/0)/*END*/
		/*IF !kyotenCd.IsNull && ''!=kyotenCd && '99'!=kyotenCd*/AND (UKEIRE_KYOTEN_CD = /*kyotenCd*/0 OR SHUKKA_KYOTEN_CD = /*kyotenCd*/0)/*END*/
		AND((1=1
		/*IF !fromDate.IsNull && ''!=fromDate*/AND CONVERT(varchar(10), UKEIRE_DENPYOU_DATE, 120) >= /*fromDate*//*END*/
		/*IF !toDate.IsNull && ''!=toDate*/AND CONVERT(varchar(10), SHUKKA_DENPYOU_DATE, 120) <= /*toDate*//*END*/)
		OR (1=1
		/*IF !fromDate.IsNull && ''!=fromDate*/AND CONVERT(varchar(10), UKEIRE_DENPYOU_DATE, 120) >= /*fromDate*//*END*/
		/*IF !toDate.IsNull && ''!=toDate*/AND CONVERT(varchar(10), SHUKKA_DENPYOU_DATE, 120) <= /*toDate*//*END*/)
		)
		
ORDER BY T0.UKEIRE_DENPYOU_NUMBER DESC, T0.UKEIRE_SYSTEM_ID ASC