SELECT DISTINCT N'減容率マスタ' AS NAME FROM M_GENNYOURITSU WHERE SHOBUN_HOUHOU_CD IN /*SHOBUN_HOUHOU_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'地域別施設マスタ' AS NAME FROM M_CHIIKIBETSU_SHISETSU WHERE SHOBUN_HOUHOU_CD IN /*SHOBUN_HOUHOU_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'地域別処分マスタ' AS NAME FROM M_CHIIKIBETSU_SHOBUN WHERE SHOBUN_HOUHOU_CD IN /*SHOBUN_HOUHOU_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'品名入力' AS NAME FROM M_HINMEI WHERE SHOBUN_HOHO_CD IN /*SHOBUN_HOUHOU_CD*/('') AND DELETE_FLG = 'False'