SELECT DISTINCT
	   USSE.SYSTEM_ID AS SYSTEM_ID
	  ,USSE.SEQ AS SEQ
	  ,MOBISYO.CREATE_DATE AS CREATE_DATE
	  ,MOBISYO.CREATE_PC AS CREATE_PC
	  ,MOBISYO.CREATE_USER AS CREATE_USER
	  ,MOBISYO.TIME_STAMP AS TIME_STAMP
	  ,MOBISYO.SEQ_NO AS SEQ_NO
FROM T_UKETSUKE_SS_ENTRY USSE
LEFT JOIN
	(SELECT MR.SEQ_NO 
		   ,MR.HAISHA_DENPYOU_NO
		   ,MR.CREATE_DATE
		   ,MR.CREATE_PC
		   ,MR.CREATE_USER
		   ,MR.TIME_STAMP
	 FROM T_MOBISYO_RT MR
	 INNER JOIN T_MOBISYO_RT_CONTENA MRC
	 ON MR.SEQ_NO = MRC.SEQ_NO
	) AS MOBISYO
 ON USSE.UKETSUKE_NUMBER = MOBISYO.HAISHA_DENPYOU_NO
 WHERE /*IF data.SYSTEM_ID != null && dataz.SYSTEM_ID != ''*/ USSE.SYSTEM_ID = /*data.SYSTEM_ID*//*END*/
	   /*IF data.SEQ != null && dataz.SEQ != ''*/AND USSE.SEQ = /*data.SEQ*//*END*/
