SELECT DETAIL.* FROM(
SELECT
	 RT_MIKAISHU.MIKAISHU_CNT
	 ,T_MOBISYO_RT.HAISHA_KBN
     ,T_MOBISYO_RT.GENBA_NO
     ,CASE
		WHEN T_MOBISYO_RT.GENBA_STTS = 0 AND T_MOBISYO_RT.GENBA_JISSEKI_JYOGAIFLG = 0 THEN '未回収'
		WHEN T_MOBISYO_RT.GENBA_JISSEKI_JYOGAIFLG = 1 THEN '回収無'
		WHEN (T_MOBISYO_RT.GENBA_STTS = 1 or T_MOBISYO_RT.GENBA_STTS = 2) AND T_MOBISYO_RT.GENBA_JISSEKI_JYOGAIFLG = 0 THEN '回収済'
		ELSE ''
		END AS KAISHU_JOKYO
	 ,T_MOBISYO_RT.HAISHA_SAGYOU_DATE
	 ,T_MOBISYO_RT.HAISHA_DENPYOU_NO
	 ,T_MOBISYO_RT.HAISHA_COURSE_NAME_CD
	 ,T_MOBISYO_RT.HAISHA_COURSE_NAME
	 ,T_MOBISYO_RT.SHASHU_NAME
	 ,T_MOBISYO_RT.SHARYOU_NAME
	 ,T_MOBISYO_RT.UNTENSHA_NAME

FROM
     T_MOBISYO_RT
	 LEFT JOIN M_GYOUSHA ON T_MOBISYO_RT.GENBA_JISSEKI_GYOUSHACD = M_GYOUSHA.GYOUSHA_CD 
	 LEFT JOIN M_GENBA ON T_MOBISYO_RT.GENBA_JISSEKI_GYOUSHACD = M_GENBA.GYOUSHA_CD AND T_MOBISYO_RT.GENBA_JISSEKI_GENBACD = M_GENBA.GENBA_CD 
	 LEFT JOIN (
		SELECT
			T_MOBISYO_RT.HAISHA_DENPYOU_NO
			,T_MOBISYO_RT.HAISHA_KBN
			,COUNT(DTL_MIKAISHU.SEQ_NO) AS MIKAISHU_CNT
		FROM
			T_MOBISYO_RT
			LEFT JOIN T_MOBISYO_RT_DTL DTL_MIKAISHU ON T_MOBISYO_RT.SEQ_NO = DTL_MIKAISHU.SEQ_NO AND DTL_MIKAISHU.JISSEKI_REGIST_FLG = 0
		WHERE
			T_MOBISYO_RT.DELETE_FLG = 0
			AND T_MOBISYO_RT.GENBA_JISSEKI_JYOGAIFLG = 0
			AND T_MOBISYO_RT.HAISHA_KBN = 0
			AND T_MOBISYO_RT.GENBA_STTS = 0
			AND T_MOBISYO_RT.HAISHA_SAGYOU_DATE >= /*data.SAGYOU_DATE_FROM*/  AND T_MOBISYO_RT.HAISHA_SAGYOU_DATE <= /*data.SAGYOU_DATE_TO*/
		GROUP BY
			T_MOBISYO_RT.HAISHA_DENPYOU_NO
			,T_MOBISYO_RT.HAISHA_KBN
			) AS RT_MIKAISHU ON T_MOBISYO_RT.HAISHA_DENPYOU_NO = RT_MIKAISHU.HAISHA_DENPYOU_NO AND T_MOBISYO_RT.HAISHA_KBN = RT_MIKAISHU.HAISHA_KBN

WHERE
	 T_MOBISYO_RT.DELETE_FLG = 0
	 AND T_MOBISYO_RT.HAISHA_KBN = 0
	 AND T_MOBISYO_RT.JISSEKI_REGIST_FLG = 0
	 AND T_MOBISYO_RT.HAISHA_SAGYOU_DATE >= /*data.SAGYOU_DATE_FROM*/ AND T_MOBISYO_RT.HAISHA_SAGYOU_DATE <= /*data.SAGYOU_DATE_TO*/
	 /*IF data.SHASHU_CD != null && data.SHASHU_CD != ''*/ AND T_MOBISYO_RT.SHASHU_CD = /*data.SHASHU_CD*/ /*END*/
	 /*IF data.SHARYOU_CD != null && data.SHARYOU_CD != ''*/ AND T_MOBISYO_RT.SHARYOU_CD = /*data.SHARYOU_CD*/ /*END*/
	 /*IF data.UNTENSHA_CD != null && data.UNTENSHA_CD != ''*/ AND T_MOBISYO_RT.UNTENSHA_CD = /*data.UNTENSHA_CD*/ /*END*/
	 /*IF data.UNPAN_GYOUSHA_CD != null && data.UNPAN_GYOUSHA_CD != ''*/ AND T_MOBISYO_RT.GENBA_JISSEKI_UPNGYOSHACD = /*data.UNPAN_GYOUSHA_CD*/ /*END*/
) DETAIL
WHERE 1 = 1
	 /*IF data.KAISYUU_JYOUKYOU == '1'*/
	 AND NOT EXISTS 
	 (
		SELECT * FROM T_MOBISYO_RT
		WHERE HAISHA_DENPYOU_NO = DETAIL.HAISHA_DENPYOU_NO
		  AND HAISHA_KBN = DETAIL.HAISHA_KBN
		  AND GENBA_STTS = 0
		  AND GENBA_JISSEKI_JYOGAIFLG = 0
	 )
	 /*END*/
	  /*IF data.KAISYUU_JYOUKYOU == '2'*/
	 AND EXISTS 
	 (
		SELECT * FROM T_MOBISYO_RT
		WHERE HAISHA_DENPYOU_NO = DETAIL.HAISHA_DENPYOU_NO
		  AND HAISHA_KBN = DETAIL.HAISHA_KBN
		  AND GENBA_STTS = 0
		  AND GENBA_JISSEKI_JYOGAIFLG = 0
	 )
	 /*END*/
ORDER BY
     DETAIL.HAISHA_DENPYOU_NO
    ,DETAIL.HAISHA_SAGYOU_DATE
