SELECT
	DETAIL.MIKAISHU_CNT
	,DETAIL.KAISHU_JOKYO
	,DETAIL.HAISHA_SAGYOU_DATE
	,DETAIL.HAISHA_DENPYOU_NO
	,DETAIL.HAISHA_COURSE_NAME_CD
	,DETAIL.HAISHA_COURSE_NAME
	,DETAIL.SHASHU_NAME
	,DETAIL.SHARYOU_NAME
	,DETAIL.UNTENSHA_NAME
	,THD.ROW_NUMBER as DETAIL_NO
	,THD.ROW_NUMBER as JYUNBAN
	,THD.ROUND_NO as ROUND_NO
	,THD.GYOUSHA_CD as GYOUSHA_CD
	,MGYO.GYOUSHA_NAME_RYAKU as	GYOUSHA_NAME
	,THD.GENBA_CD as GENBA_CD
	,MGEN.GENBA_NAME_RYAKU as GENBA_NAME
	,DETAIL.HINMEI_CD as HINMEI_CD
	,MH.HINMEI_NAME_RYAKU as HINMEI_NAME
	,DETAIL.SUURYOU as SUURYOU
	,MU.UNIT_NAME_RYAKU as UNIT_NAME
FROM(
SELECT
	 RT_MIKAISHU.MIKAISHU_CNT
	 ,T_MOBISYO_RT.HAISHA_KBN
	 ,T_MOBISYO_RT.SEQ_NO
	 ,T_MOBISYO_RT.HAISHA_ROW_NUMBER
     ,T_MOBISYO_RT.GENBA_NO
     ,CASE
		WHEN T_MOBISYO_RT.GENBA_STTS = 0 AND T_MOBISYO_RT.GENBA_JISSEKI_JYOGAIFLG = 0 THEN '未回収'
		WHEN T_MOBISYO_RT.GENBA_JISSEKI_JYOGAIFLG = 1 THEN '回収無'
		WHEN (T_MOBISYO_RT.GENBA_STTS = 1 or T_MOBISYO_RT.GENBA_STTS = 2) AND T_MOBISYO_RT.GENBA_JISSEKI_JYOGAIFLG = 0 THEN '回収済'
		ELSE ''
		END AS KAISHU_JOKYO
	 ,T_MOBISYO_RT.HAISHA_SAGYOU_DATE
	 ,T_MOBISYO_RT.HAISHA_DENPYOU_NO
	 ,T_MOBISYO_RT.HAISHA_COURSE_NAME_CD
	 ,T_MOBISYO_RT.HAISHA_COURSE_NAME
	 ,T_MOBISYO_RT.SHASHU_NAME
	 ,T_MOBISYO_RT.SHARYOU_NAME
	 ,T_MOBISYO_RT.UNTENSHA_NAME
	 ,T_MOBISYO_RT_DTL.GENBA_DETAIL_HINMEICD as HINMEI_CD
	 ,T_MOBISYO_RT_DTL.GENBA_DETAIL_SUURYO1 as SUURYOU
	 ,T_MOBISYO_RT_DTL.GENBA_DETAIL_UNIT_CD1 as UNIT_CD
	 ,T_MOBISYO_RT_DTL.EDABAN

FROM
     T_MOBISYO_RT
	 LEFT JOIN M_GYOUSHA ON T_MOBISYO_RT.GENBA_JISSEKI_GYOUSHACD = M_GYOUSHA.GYOUSHA_CD 
	 LEFT JOIN M_GENBA ON T_MOBISYO_RT.GENBA_JISSEKI_GYOUSHACD = M_GENBA.GYOUSHA_CD AND T_MOBISYO_RT.GENBA_JISSEKI_GENBACD = M_GENBA.GENBA_CD 
	 LEFT JOIN T_MOBISYO_RT_DTL 
	        ON T_MOBISYO_RT.SEQ_NO = T_MOBISYO_RT_DTL.SEQ_NO
		   AND T_MOBISYO_RT_DTL.GENBA_DETAIL_HINMEICD is not NULL
	 LEFT JOIN (
		SELECT
			T_MOBISYO_RT.HAISHA_DENPYOU_NO
			,T_MOBISYO_RT.HAISHA_KBN
			,COUNT(DTL_MIKAISHU.SEQ_NO) AS MIKAISHU_CNT
		FROM
			T_MOBISYO_RT
			LEFT JOIN T_MOBISYO_RT_DTL DTL_MIKAISHU ON T_MOBISYO_RT.SEQ_NO = DTL_MIKAISHU.SEQ_NO AND DTL_MIKAISHU.JISSEKI_REGIST_FLG = 0
		WHERE
			T_MOBISYO_RT.DELETE_FLG = 0
			AND T_MOBISYO_RT.GENBA_JISSEKI_JYOGAIFLG = 0
			AND T_MOBISYO_RT.HAISHA_KBN = 0
			AND T_MOBISYO_RT.GENBA_STTS = 0
			AND T_MOBISYO_RT.HAISHA_SAGYOU_DATE >= /*data.SAGYOU_DATE_FROM*/  AND T_MOBISYO_RT.HAISHA_SAGYOU_DATE <= /*data.SAGYOU_DATE_TO*/
		GROUP BY
			T_MOBISYO_RT.HAISHA_DENPYOU_NO
			,T_MOBISYO_RT.HAISHA_KBN
			) AS RT_MIKAISHU ON T_MOBISYO_RT.HAISHA_DENPYOU_NO = RT_MIKAISHU.HAISHA_DENPYOU_NO AND T_MOBISYO_RT.HAISHA_KBN = RT_MIKAISHU.HAISHA_KBN

WHERE
	 T_MOBISYO_RT.DELETE_FLG = 0
	 AND T_MOBISYO_RT.HAISHA_KBN = 0
	 AND T_MOBISYO_RT.JISSEKI_REGIST_FLG = 0
	 AND T_MOBISYO_RT.HAISHA_SAGYOU_DATE >= /*data.SAGYOU_DATE_FROM*/ AND T_MOBISYO_RT.HAISHA_SAGYOU_DATE <= /*data.SAGYOU_DATE_TO*/
	 /*IF data.SHASHU_CD != null && data.SHASHU_CD != ''*/ AND T_MOBISYO_RT.SHASHU_CD = /*data.SHASHU_CD*/ /*END*/
	 /*IF data.SHARYOU_CD != null && data.SHARYOU_CD != ''*/ AND T_MOBISYO_RT.SHARYOU_CD = /*data.SHARYOU_CD*/ /*END*/
	 /*IF data.UNTENSHA_CD != null && data.UNTENSHA_CD != ''*/ AND T_MOBISYO_RT.UNTENSHA_CD = /*data.UNTENSHA_CD*/ /*END*/
	 /*IF data.UNPAN_GYOUSHA_CD != null && data.UNPAN_GYOUSHA_CD != ''*/ AND T_MOBISYO_RT.GENBA_JISSEKI_UPNGYOSHACD = /*data.UNPAN_GYOUSHA_CD*/ /*END*/

) DETAIL
LEFT JOIN T_TEIKI_HAISHA_DETAIL THD
       ON DETAIL.HAISHA_DENPYOU_NO = THD.TEIKI_HAISHA_NUMBER
	  AND DETAIL.HAISHA_ROW_NUMBER = THD.ROW_NUMBER
INNER JOIN T_TEIKI_HAISHA_ENTRY THE
       ON THE.SYSTEM_ID = THD.SYSTEM_ID
	  AND THE.SEQ = THD.SEQ
	  AND THE.DELETE_FLG = 0
LEFT JOIN M_GYOUSHA MGYO
	   ON THD.GYOUSHA_CD = MGYO.GYOUSHA_CD
LEFT JOIN M_GENBA MGEN
	   ON THD.GYOUSHA_CD = MGEN.GYOUSHA_CD
	  AND THD.GENBA_CD = MGEN.GENBA_CD
LEFT JOIN M_HINMEI MH
       ON DETAIL.HINMEI_CD = MH.HINMEI_CD
LEFT JOIN M_UNIT MU
       ON DETAIL.UNIT_CD = MU.UNIT_CD

WHERE 1 = 1
	 /*IF data.KAISYUU_JYOUKYOU == '1'*/
	 AND NOT EXISTS 
	 (
		SELECT * FROM T_MOBISYO_RT
		WHERE HAISHA_DENPYOU_NO = DETAIL.HAISHA_DENPYOU_NO
		  AND HAISHA_KBN = DETAIL.HAISHA_KBN
		  AND GENBA_STTS = 0
		  AND GENBA_JISSEKI_JYOGAIFLG = 0
	 )
	 /*END*/
	  /*IF data.KAISYUU_JYOUKYOU == '2'*/
	 AND EXISTS 
	 (
		SELECT * FROM T_MOBISYO_RT
		WHERE HAISHA_DENPYOU_NO = DETAIL.HAISHA_DENPYOU_NO
		  AND HAISHA_KBN = DETAIL.HAISHA_KBN
		  AND GENBA_STTS = 0
		  AND GENBA_JISSEKI_JYOGAIFLG = 0
	 )
	 /*END*/
ORDER BY
     DETAIL.HAISHA_DENPYOU_NO
    ,DETAIL.HAISHA_SAGYOU_DATE
	,THD.ROW_NUMBER
	,DETAIL.EDABAN
