SELECT
	DETAIL.SEQ_NO
	,DETAIL.KAISHU_JOKYO
	,DETAIL.HAISHA_SAGYOU_DATE
	,DETAIL.HAISHA_DENPYOU_NO
	,DETAIL.GENBA_JISSEKI_GYOUSHACD
	,DETAIL.GYOUSHA_NAME
	,DETAIL.GENBA_JISSEKI_GENBACD
	,DETAIL.GENBA_NAME
	,DETAIL.SHARYOU_NAME
	,DETAIL.UNTENSHA_NAME
	,DETAIL.UKETSUKE_KBN
	,MDTL.EDABAN as DETAIL_NO
	,MDTL.GENBA_DETAIL_HINMEICD as HINMEI_CD
	,MH.HINMEI_NAME_RYAKU as HINMEI_NAME
	,MDTL.GENBA_DETAIL_SUURYO1 as SUURYOU
	,MU.UNIT_NAME_RYAKU as UNIT_NAME
FROM(
SELECT 
     CASE
		WHEN T_MOBISYO_RT.GENBA_STTS = 0 AND T_MOBISYO_RT.GENBA_JISSEKI_JYOGAIFLG = 0 THEN '未回収'
		WHEN T_MOBISYO_RT.GENBA_JISSEKI_JYOGAIFLG = 1 THEN '回収無'
		WHEN (T_MOBISYO_RT.GENBA_STTS = 1 or T_MOBISYO_RT.GENBA_STTS = 2) AND T_MOBISYO_RT.GENBA_JISSEKI_JYOGAIFLG = 0 THEN '回収済'
		ELSE ''
		END AS KAISHU_JOKYO

	 ,M_GYOUSHA.GYOUSHA_NAME_RYAKU AS GYOUSHA_NAME
	 ,M_GENBA.GENBA_NAME_RYAKU AS GENBA_NAME
	 ,T_MOBISYO_RT.*
FROM
     T_MOBISYO_RT
     LEFT JOIN M_GYOUSHA ON T_MOBISYO_RT.GENBA_JISSEKI_GYOUSHACD = M_GYOUSHA.GYOUSHA_CD 
	 LEFT JOIN M_GENBA ON T_MOBISYO_RT.GENBA_JISSEKI_GYOUSHACD = M_GENBA.GYOUSHA_CD AND T_MOBISYO_RT.GENBA_JISSEKI_GENBACD = M_GENBA.GENBA_CD
WHERE
	 T_MOBISYO_RT.DELETE_FLG = 0
	 AND T_MOBISYO_RT.HAISHA_KBN = 1
	 AND T_MOBISYO_RT.JISSEKI_REGIST_FLG = 0
	 AND T_MOBISYO_RT.HAISHA_SAGYOU_DATE >= /*data.SAGYOU_DATE_FROM*/ AND T_MOBISYO_RT.HAISHA_SAGYOU_DATE <= /*data.SAGYOU_DATE_TO*/
	 /*IF data.GYOUSHA_CD != null && data.GYOUSHA_CD != ''*/AND T_MOBISYO_RT.GENBA_JISSEKI_GYOUSHACD = /*data.GYOUSHA_CD*//*END*/
	 /*IF data.GENBA_CD != null && data.GENBA_CD != ''*/AND T_MOBISYO_RT.GENBA_JISSEKI_GENBACD = /*data.GENBA_CD*//*END*/
	 /*IF data.SHASHU_CD != null && data.SHASHU_CD != ''*/ AND T_MOBISYO_RT.SHASHU_CD = /*data.SHASHU_CD*/ /*END*/
	 /*IF data.SHARYOU_CD != null && data.SHARYOU_CD != ''*/ AND T_MOBISYO_RT.SHARYOU_CD = /*data.SHARYOU_CD*/ /*END*/
	 /*IF data.UNTENSHA_CD != null && data.UNTENSHA_CD != ''*/ AND T_MOBISYO_RT.UNTENSHA_CD = /*data.UNTENSHA_CD*/ /*END*/
	 /*IF data.UNPAN_GYOUSHA_CD != null && data.UNPAN_GYOUSHA_CD != ''*/ AND T_MOBISYO_RT.GENBA_JISSEKI_UPNGYOSHACD = /*data.UNPAN_GYOUSHA_CD*/ /*END*/
) DETAIL
LEFT JOIN T_MOBISYO_RT_DTL MDTL
       ON MDTL.SEQ_NO = DETAIL.SEQ_NO
LEFT JOIN M_HINMEI MH
       ON MDTL.GENBA_DETAIL_HINMEICD = MH.HINMEI_CD
LEFT JOIN M_UNIT MU
       ON MDTL.GENBA_DETAIL_UNIT_CD1 = MU.UNIT_CD 
WHERE 1 = 1
	 /*IF data.KAISYUU_JYOUKYOU == '1'*/
	 AND KAISHU_JOKYO = '回収済' 
	 /*END*/
	  /*IF data.KAISYUU_JYOUKYOU == '2'*/
	 AND KAISHU_JOKYO = '未回収' 
	 /*END*/
ORDER BY
     DETAIL.HAISHA_DENPYOU_NO
    ,DETAIL.HAISHA_SAGYOU_DATE
    ,DETAIL.UNTENSHA_CD
    ,DETAIL.SHARYOU_CD