SELECT
	MR.SEQ_NO as seqNo,
	MR.SHIJI_FLG as shijiFg,
	MR.HAISHA_KBN as haishaKbn,
	CONVERT(VARCHAR(100),MR.HAISHA_SAGYOU_DATE,111) as sagyoDate,
	GENBA.GYOUSHA_CD as gyoshaCd,
	GENBA.GENBA_CD as genbaCd,
	GYOUSHA.GYOUSHA_NAME_RYAKU as gyoshaNm,
	GENBA.GENBA_NAME_RYAKU as genbaNm,
	MR.HAISHA_COURSE_NAME_CD as courseNameCd,
	MR.GENBA_STTS as genbaSTTS,
	MR.GENBA_JISSEKI_JYOGAIFLG as jyogaiFlg
FROM T_MOBISYO_RT MR
INNER JOIN M_GYOUSHA GYOUSHA
ON MR.GENBA_JISSEKI_GYOUSHACD = GYOUSHA.GYOUSHA_CD
INNER JOIN M_GENBA GENBA
ON MR.GENBA_JISSEKI_GYOUSHACD = GENBA.GYOUSHA_CD
AND MR.GENBA_JISSEKI_GENBACD = GENBA.GENBA_CD
WHERE
	CAST(MR.HAISHA_SAGYOU_DATE AS DATE) = CAST(/*sagyouDate*/ AS DATE)
AND MR.UNTENSHA_CD = /*untenshaCd*/

/*IF sharyouCd != null && sharyouCd != ''*/
AND MR.SHARYOU_CD = /*sharyouCd*/
/*END*/
/*IF sharyouCd != null && sharyouCd != ''*/
AND MR.GENBA_JISSEKI_UPNGYOSHACD = /*gyoushaCd*/
/*END*/

AND MR.JISSEKI_REGIST_FLG = 0
AND MR.DELETE_FLG = 0
ORDER BY MR.SHIJI_FLG ASC, MR.SEQ_NO DESC

