SELECT
	MR.*
FROM T_MOBISYO_RT MR
INNER JOIN M_GYOUSHA GYOUSHA
ON MR.GENBA_JISSEKI_GYOUSHACD = GYOUSHA.GYOUSHA_CD
INNER JOIN M_GENBA GENBA
ON MR.GENBA_JISSEKI_GYOUSHACD = GENBA.GYOUSHA_CD
AND MR.GENBA_JISSEKI_GENBACD = GENBA.GENBA_CD
LEFT JOIN M_TODOUFUKEN TODOUFUKEN 
ON TODOUFUKEN.TODOUFUKEN_CD = GENBA.GENBA_TODOUFUKEN_CD
WHERE
/*IF courseNameCd == null || courseNameCd == ''*/
	MR.HAISHA_KBN = 1
/*END*/
/*IF courseNameCd != null && courseNameCd != ''*/
	MR.HAISHA_COURSE_NAME_CD = /*courseNameCd*/
	AND MR.HAISHA_KBN = 0
/*END*/
	AND MR.JISSEKI_REGIST_FLG = 0
	AND CAST(MR.HAISHA_SAGYOU_DATE AS DATE) = CAST(/*sagyouDate*/ AS DATE)
	AND MR.UNTENSHA_CD = /*untenshaCd*/

/*IF sharyouCd != null && sharyouCd != ''*/
	AND MR.SHARYOU_CD = /*sharyouCd*/
/*END*/

	AND MR.DELETE_FLG = 0
/*IF joken == '0' */
	AND MR.GENBA_STTS = 0
	AND MR.GENBA_JISSEKI_JYOGAIFLG = 0
/*END*/
/*IF joken == '1' */
	AND MR.GENBA_STTS IN(1, 2)
	AND MR.GENBA_JISSEKI_JYOGAIFLG = 0
/*END*/
/*IF joken == '2' */
	AND MR.GENBA_JISSEKI_JYOGAIFLG = 1
/*END*/


