SELECT TS.DENPYOU_KBN_CD, TS.KEIYAKU_KBN, TS.KEIJYOU_KBN, TS.INPUT_KBN, TS.ANBUN_FLG FROM T_TEIKI_HAISHA_ENTRY AS TE
INNER JOIN T_TEIKI_HAISHA_DETAIL AS TD ON TE.SYSTEM_ID = TD.SYSTEM_ID AND TE.SEQ = TD.SEQ
INNER JOIN T_TEIKI_HAISHA_SHOUSAI AS TS ON TD.SYSTEM_ID = TS.SYSTEM_ID AND TD.SEQ = TS.SEQ AND TD.DETAIL_SYSTEM_ID = TS.DETAIL_SYSTEM_ID
WHERE (TE.DELETE_FLG = 0)
/*IF data.HAISHA_DENPYOU_NO != 0*/ AND (TE.TEIKI_HAISHA_NUMBER = /*data.HAISHA_DENPYOU_NO*/) /*END*/
/*IF !data.ROUND_NO.IsNull*/ AND (TD.ROUND_NO = /*data.ROUND_NO.Value*/) /*END*/
/*IF data.GYOUSHA_CD != null*/ AND (TD.GYOUSHA_CD = /*data.GYOUSHA_CD*/) /*END*/
/*IF data.GENBA_CD != null*/ AND (TD.GENBA_CD = /*data.GENBA_CD*/) /*END*/
/*IF data.HINMEI_CD != null*/ AND (TS.HINMEI_CD = /*data.HINMEI_CD*/) /*END*/
/*IF !data.ROW_NO.IsNull*/ AND (TD.ROW_NUMBER = /*data.ROW_NO.Value*/) /*END*/
/*IF !data.UNIT_CD.IsNull*/ AND (TS.UNIT_CD = /*data.UNIT_CD.Value*/) /*END*/
