SELECT
     ROW_NUMBER()OVER(ORDER BY ENT.SAGYOU_DATE,ENT.TEIKI_HAISHA_NUMBER,DET.ROW_NUMBER) ROW_NO
     ,ENT.SHASHU_CD
     ,M_SHASHU.SHASHU_NAME_RYAKU AS SHASHU_NAME
     ,ENT.SHARYOU_CD
     ,M_SHARYOU.SHARYOU_NAME_RYAKU AS SHARYOU_NAME
     ,M_SHAIN.SHAIN_NAME_RYAKU AS UNTENSHA_NAME
     ,ENT.UNTENSHA_CD
     ,ENT.SAGYOU_DATE AS HAISHA_SAGYOU_DATE
     ,ENT.TEIKI_HAISHA_NUMBER AS HAISHA_DENPYOU_NO
     ,ENT.COURSE_NAME_CD AS HAISHA_COURSE_NAME_CD
     ,M_COURSE_NAME.COURSE_NAME_RYAKU AS HAISHA_COURSE_NAME
     ,DET.GYOUSHA_CD AS GENBA_JISSEKI_GYOUSHACD
     ,M_GYOUSHA.GYOUSHA_NAME_RYAKU AS GYOUSHA_NAME
     ,DET.GENBA_CD AS GENBA_JISSEKI_GENBACD
     ,M_GENBA.GENBA_NAME_RYAKU AS GENBA_NAME
     ,ENT.UNPAN_GYOUSHA_CD AS GENBA_JISSEKI_UPNGYOSHACD
     ,DET.ROW_NUMBER AS HAISHA_ROW_NUMBER
     ,SHOS.HINMEI_CD AS GENBA_DETAIL_HINMEICD
     ,M_HINMEI.HINMEI_NAME_RYAKU AS HINMEI_NAME
     ,SHOS.UNIT_CD AS GENBA_DETAIL_UNIT_CD1
     ,SHOS.KANSAN_UNIT_CD AS GENBA_DETAIL_UNIT_CD2
     ,ENT.SYSTEM_ID
     ,ENT.SEQ
	 ,SHOS.NIOROSHI_NUMBER
FROM
	T_TEIKI_HAISHA_ENTRY ENT
	LEFT JOIN T_TEIKI_HAISHA_DETAIL DET ON ENT.SYSTEM_ID = DET.SYSTEM_ID AND ENT.SEQ = DET.SEQ
	LEFT JOIN T_TEIKI_HAISHA_SHOUSAI SHOS ON SHOS.SYSTEM_ID = DET.SYSTEM_ID AND SHOS.SEQ = DET.SEQ AND SHOS.DETAIL_SYSTEM_ID = DET.DETAIL_SYSTEM_ID
	LEFT JOIN (
		SELECT
			HAISHA_DENPYOU_NO
			,HAISHA_ROW_NUMBER
		FROM
			T_MOBISYO_RT
		WHERE
			DELETE_FLG = 0
			AND HAISHA_KBN = 0
		GROUP BY
			HAISHA_DENPYOU_NO
			,HAISHA_ROW_NUMBER
		) REGISTED ON DET.TEIKI_HAISHA_NUMBER = REGISTED.HAISHA_DENPYOU_NO
				AND DET.ROW_NUMBER = REGISTED.HAISHA_ROW_NUMBER
	LEFT JOIN M_SHASHU ON M_SHASHU.SHASHU_CD = ENT.SHASHU_CD
	LEFT JOIN M_SHARYOU ON ENT.UNPAN_GYOUSHA_CD = M_SHARYOU.GYOUSHA_CD AND ENT.SHARYOU_CD = M_SHARYOU.SHARYOU_CD
	LEFT JOIN M_SHAIN ON ENT.UNTENSHA_CD = M_SHAIN.SHAIN_CD
	LEFT JOIN M_COURSE_NAME ON M_COURSE_NAME.COURSE_NAME_CD = ENT.COURSE_NAME_CD
	LEFT JOIN M_HINMEI ON M_HINMEI.HINMEI_CD = SHOS.HINMEI_CD
	LEFT JOIN M_GYOUSHA ON DET.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD 
	LEFT JOIN M_GENBA ON DET.GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND DET.GENBA_CD = M_GENBA.GENBA_CD 
WHERE
	ENT.DELETE_FLG = 0
	AND (ENT.UNTENSHA_CD IS NOT NULL AND ENT.UNTENSHA_CD != '')
	AND (ENT.SHARYOU_CD IS NOT NULL AND ENT.SHARYOU_CD != '')
	AND REGISTED.HAISHA_DENPYOU_NO IS NULL
	AND ENT.TEIKI_HAISHA_NUMBER = /*TEIKI_HAISHA_NUMBER*/ 
ORDER BY
	ENT.SAGYOU_DATE
	,ENT.TEIKI_HAISHA_NUMBER
	,DET.ROW_NUMBER
    ,SHOS.HINMEI_CD
	,SHOS.UNIT_CD