SELECT 
    NIOROSHI_GYOUSHA_CD AS HANNYUU_GYOUSHACD
    ,NIOROSHI_GENBA_CD AS HANNYUU_GENBACD
FROM
    T_TEIKI_HAISHA_NIOROSHI
WHERE 
    SYSTEM_ID = /*SYSTEM_ID*/
    AND SEQ = /*SEQ*/
    AND NIOROSHI_NUMBER = /*NIOROSHI_NUMBER*/