//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KobetsuHinmeiTankaIchiran.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KYOTEN_CD_TEXT {
            get {
                return ((string)(this["KYOTEN_CD_TEXT"]));
            }
            set {
                this["KYOTEN_CD_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ICHIRAN_ALERT_KENSUU {
            get {
                return ((string)(this["ICHIRAN_ALERT_KENSUU"]));
            }
            set {
                this["ICHIRAN_ALERT_KENSUU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TORIHIKISAKI_NAME_RYAKU_TEXT {
            get {
                return ((string)(this["TORIHIKISAKI_NAME_RYAKU_TEXT"]));
            }
            set {
                this["TORIHIKISAKI_NAME_RYAKU_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GYOUSHA_NAME_RYAKU_TEXT {
            get {
                return ((string)(this["GYOUSHA_NAME_RYAKU_TEXT"]));
            }
            set {
                this["GYOUSHA_NAME_RYAKU_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_FURIGANA_TEXT {
            get {
                return ((string)(this["GENBA_FURIGANA_TEXT"]));
            }
            set {
                this["GENBA_FURIGANA_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_NAME1_TEXT {
            get {
                return ((string)(this["GENBA_NAME1_TEXT"]));
            }
            set {
                this["GENBA_NAME1_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_NAME2_TEXT {
            get {
                return ((string)(this["GENBA_NAME2_TEXT"]));
            }
            set {
                this["GENBA_NAME2_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_NAME_RYAKU_TEXT {
            get {
                return ((string)(this["GENBA_NAME_RYAKU_TEXT"]));
            }
            set {
                this["GENBA_NAME_RYAKU_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_TODOUFUKEN_CD_TEXT {
            get {
                return ((string)(this["GENBA_TODOUFUKEN_CD_TEXT"]));
            }
            set {
                this["GENBA_TODOUFUKEN_CD_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_ADDRESS_TEXT {
            get {
                return ((string)(this["GENBA_ADDRESS_TEXT"]));
            }
            set {
                this["GENBA_ADDRESS_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime TEKIYOU_BEGIN_VALUE {
            get {
                return ((global::System.DateTime)(this["TEKIYOU_BEGIN_VALUE"]));
            }
            set {
                this["TEKIYOU_BEGIN_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime TEKIYOU_END_VALUE {
            get {
                return ((global::System.DateTime)(this["TEKIYOU_END_VALUE"]));
            }
            set {
                this["TEKIYOU_END_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ICHIRAN_HYOUJI_JOUKEN_TEKIYOU {
            get {
                return ((bool)(this["ICHIRAN_HYOUJI_JOUKEN_TEKIYOU"]));
            }
            set {
                this["ICHIRAN_HYOUJI_JOUKEN_TEKIYOU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ICHIRAN_HYOUJI_JOUKEN_DELETED {
            get {
                return ((bool)(this["ICHIRAN_HYOUJI_JOUKEN_DELETED"]));
            }
            set {
                this["ICHIRAN_HYOUJI_JOUKEN_DELETED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ICHIRAN_HYOUJI_JOUKEN_TEKIYOUGAI {
            get {
                return ((bool)(this["ICHIRAN_HYOUJI_JOUKEN_TEKIYOUGAI"]));
            }
            set {
                this["ICHIRAN_HYOUJI_JOUKEN_TEKIYOUGAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TORIHIKISAKI_CD_TEXT {
            get {
                return ((string)(this["TORIHIKISAKI_CD_TEXT"]));
            }
            set {
                this["TORIHIKISAKI_CD_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GYOUSHA_CD_TEXT {
            get {
                return ((string)(this["GYOUSHA_CD_TEXT"]));
            }
            set {
                this["GYOUSHA_CD_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_CD_TEXT {
            get {
                return ((string)(this["GENBA_CD_TEXT"]));
            }
            set {
                this["GENBA_CD_TEXT"] = value;
            }
        }
    }
}
