SELECT
    DISTINCT TJD.SYSTEM_ID,
    TJD.SEQ,
    TJE.SAGYOU_DATE
FROM
    T_TEIKI_JISSEKI_ENTRY AS TJE
    LEFT JOIN
        T_TEIKI_JISSEKI_DETAIL AS TJD
    ON  TJE.SYSTEM_ID = TJD.SYSTEM_ID
    AND TJE.SEQ = TJD.SEQ
    AND TJD.KAKUTEI_FLG = 1
    AND TJE.DELETE_FLG = 0
    INNER JOIN
        M_GENBA AS MG
    ON  MG.GYOUSHA_CD = TJD.GYOUSHA_CD
    AND MG.GENBA_CD = TJD.GENBA_CD
WHERE
    CONVERT(nvarchar, TJE.SAGYOU_DATE, 112) >= CONVERT(nvarchar, /*data.KIKAN_DATE_FROM*/null, 112)
AND CONVERT(nvarchar, TJE.SAGYOU_DATE, 112) <= CONVERT(nvarchar, /*data.KIKAN_DATE_TO*/null, 112)
AND MG.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/''