SELECT DISTINCT N'取引先マスタ' AS NAME FROM M_TORIHIKISAKI AS T
 LEFT JOIN M_TORIHIKISAKI_SEIKYUU AS TSE ON T.TORIHIKISAKI_CD = TSE.TORIHIKISAKI_CD AND T.DELETE_FLG = 'False'
 WHERE TSE.NYUUKINSAKI_CD = /*data.NYUUKINSAKI_CD*/''
UNION
SELECT DISTINCT N'引合取引先マスタ' AS NAME FROM M_HIKIAI_TORIHIKISAKI AS T
 LEFT JOIN M_HIKIAI_TORIHIKISAKI_SEIKYUU AS TSE ON T.TORIHIKISAKI_CD = TSE.TORIHIKISAKI_CD AND T.DELETE_FLG = 'False'
 WHERE TSE.NYUUKINSAKI_CD = /*data.NYUUKINSAKI_CD*/''
