SELECT 
    FURI.*
FROM 
    dbo.M_NYUUKINSAKI_FURIKOMI FURI
/*BEGIN*/WHERE
 /*IF data.NYUUKINSAKI_CD != null*/
 FURI.NYUUKINSAKI_CD = /*data.NYUUKINSAKI_CD*/'000001'
 /*END*/
/*END*/
ORDER BY FURI.FURIKOMI_SEQ
