SELECT
	TORIKYUU.NYUUKINSAKI_CD,
	TORISAKI.*
FROM
	M_TORIHIKISAKI TORISAKI
JOIN
	M_TORIHIKISAKI_SEIKYUU TORIKYUU
ON TORISAKI.TORIHIKISAKI_CD = TORIKYUU.TORIHIKISAKI_CD
/*BEGIN*/WHERE
 /*IF data.NYUUKINSAKI_CD != null*/
 TORIKYUU.NYUUKINSAKI_CD = /*data.NYUUKINSAKI_CD*/'000001'
 /*END*/
 AND TORISAKI.DELETE_FLG = 0
/*END*/
ORDER BY TORISAKI.TORIHIKISAKI_CD
