SELECT
    HAIKIS.HAIKI_KBN_CD as HAIKI_KBN_CD
    ,HAIKIS.HAIKI_SHURUI_CD as HAIKI_SHURUI_CD
    ,HAIKIS.HAIKI_SHURUI_NAME_RYAKU as HAIKI_SHURUI_NAME_RYAKU
FROM
    dbo.M_HAIKI_SHURUI HAIKIS
/*BEGIN*/WHERE
 /*IF data.HAIKI_SHURUI_CD != null*/ HAIKIS.HAIKI_SHURUI_CD LIKE '%' +  /*data.HAIKI_SHURUI_CD*/'0001' + '%'/*END*/
 /*IF data.HAIKI_SHURUI_NAME_RYAKU != null*/AND HAIKIS.HAIKI_SHURUI_NAME_RYAKU LIKE '%' +  /*data.HAIKI_SHURUI_NAME_RYAKU*/ + '%'/*END*/
/*END*/
