SELECT
    KON.*,
/*IF data.HAIKI_KBN_CD.Value != 4*/
    HAIKI.HAIKI_SHURUI_NAME_RYAKU HAIKI_SHURUI_NAME_RYAKU,
/*END*/
/*IF data.HAIKI_KBN_CD.Value == 4*/
    HAIKI.HAIKI_SHURUI_NAME HAIKI_SHURUI_NAME_RYAKU,
/*END*/
    KON.HAIKI_KBN_CD AS UK_HAIKI_KBN_CD,
    KON.KONGOU_SHURUI_CD AS UK_KONGOU_SHURUI_CD,
    KON.HAIKI_SHURUI_CD AS UK_HAIKI_SHURUI_CD
FROM
    dbo.M_KONGOU_HAIKIBUTSU KON
/*IF data.HAIKI_KBN_CD.Value != 4*/
    INNER JOIN dbo.M_HAIKI_SHURUI HAIKI ON KON.HAIKI_KBN_CD = HAIKI.HAIKI_KBN_CD AND KON.HAIKI_SHURUI_CD = HAIKI.HAIKI_SHURUI_CD
/*END*/
/*IF data.HAIKI_KBN_CD.Value == 4*/
    INNER JOIN dbo.M_DENSHI_HAIKI_SHURUI HAIKI ON KON.HAIKI_SHURUI_CD = (HAIKI.HAIKI_SHURUI_CD + '000')
/*END*/
/*BEGIN*/WHERE
 /*IF !data.HAIKI_KBN_CD.IsNull */KON.HAIKI_KBN_CD=/*data.HAIKI_KBN_CD.Value*/0/*END*/
 /*IF data.KONGOU_SHURUI_CD != null*/AND KON.KONGOU_SHURUI_CD LIKE '%' +  /*data.KONGOU_SHURUI_CD*/'01' + '%'/*END*/
 /*IF data.HAIKI_SHURUI_CD != null*/AND KON.HAIKI_SHURUI_CD LIKE '%' +  /*data.HAIKI_SHURUI_CD*/'0001' + '%'/*END*/
 /*IF data.HAIKI_SHURUI_NAME_RYAKU != null*/
 /*IF data.HAIKI_KBN_CD.Value != 4*/ AND HAIKI.HAIKI_SHURUI_NAME_RYAKU LIKE '%' +  /*data.HAIKI_SHURUI_NAME_RYAKU*/ + '%'/*END*/
 /*IF data.HAIKI_KBN_CD.Value == 4*/ AND HAIKI.HAIKI_SHURUI_NAME LIKE '%' +  /*data.HAIKI_SHURUI_NAME_RYAKU*/ + '%'/*END*/
 /*END*/
 /*IF !data.HAIKI_HIRITSU.IsNull*/AND KON.HAIKI_HIRITSU=/*data.HAIKI_HIRITSU.Value*/0/*END*/
 /*IF data.KONGOU_HAIKIBUTSU_BIKOU != null*/AND KON.KONGOU_HAIKIBUTSU_BIKOU LIKE '%' +  /*data.KONGOU_HAIKIBUTSU_BIKOU*/ + '%'/*END*/
 /*IF data.CREATE_USER != null*/AND KON.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, KON.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null*/AND KON.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, KON.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*END*/
ORDER BY KON.HAIKI_KBN_CD,KON.KONGOU_SHURUI_CD,KON.HAIKI_SHURUI_CD
