UPDATE M_KONGOU_HAIKIBUTSU SET
	KONGOU_SHURUI_CD = /*data.KONGOU_SHURUI_CD*/'',
	HAIKI_SHURUI_CD = /*data.HAIKI_SHURUI_CD*/'',
	HAIKI_HIRITSU = /*data.HAIKI_HIRITSU*/0,
	KONGOU_HAIKIBUTSU_BIKOU = /*data.KONGOU_HAIKIBUTSU_BIKOU*/'',
	UPDATE_USER = /*data.UPDATE_USER*/'',
	UPDATE_DATE = CONVERT(DATETIME, /*data.UPDATE_DATE*/null, 120),
	UPDATE_PC = /*data.UPDATE_PC*/'',
	DELETE_FLG = /*data.DELETE_FLG*/0
WHERE HAIKI_KBN_CD = /*updateKey.HAIKI_KBN_CD*/''
  AND KONGOU_SHURUI_CD = /*updateKey.KONGOU_SHURUI_CD*/''
  AND HAIKI_SHURUI_CD = /*updateKey.HAIKI_SHURUI_CD*/0
