SELECT 
    TAN.*
FROM 
    dbo.M_DENSHI_TANTOUSHA TAN
WHERE
	TAN.EDI_MEMBER_ID = /*data.EDI_MEMBER_ID*/'0000001'
AND TAN.TANTOUSHA_KBN = /*data.TANTOUSHA_KBN*/'0'
AND TAN.TANTOUSHA_CD = /*data.TANTOUSHA_CD*/'0000000001'
