SELECT
    MEISAI.KYOTEN_CD,
    MEISAI.KYOTEN_NAME_RYAKU,
    MEISAI.TORIHIKISAKI_CD,
    MEISAI.TORIHIKISAKI_NAME,
    MEISAI.GYOUSHA_CD,
    MEISAI.GYOUSHA_NAME,
    MEISAI.GENBA_CD,
    MEISAI.GENBA_NAME,
    MEISAI.DENPYOU_DATE,
	MEISAI.YM,
    MEISAI.DENPYOU_NUMBER,
	MEISAI.KEIRYOU_KBN,
	MEISAI.KEIRYOU_KBN_NAME,
	MEISAI.KEITAI_KBN_CD,
	MEISAI.KEITAI_KBN_NAME,
	MEISAI.UNPAN_GYOUSHA_CD,
    MEISAI.UNPAN_GYOUSHA_NAME,
	MEISAI.SHASHU_CD,
	MEISAI.SHASHU_NAME,
	MEISAI.SHARYOU_CD,
	MEISAI.SHARYOU_NAME,
	MEISAI.UNTENSHA_CD,
	MEISAI.UNTENSHA_NAME,
    MEISAI.ROW_NO,
	MEISAI.DENPYOU_KBN_CD,
    MEISAI.HINMEI_CD,
    MEISAI.HINMEI_NAME,
	MEISAI.SHURUI_CD,
	MEISAI.SHURUI_NAME,
	MEISAI.BUNRUI_CD,
	MEISAI.BUNRUI_NAME,
	MEISAI.STACK_JYUURYOU,
	MEISAI.EMPTY_JYUURYOU,
	MEISAI.SE_JYUURYOU,
	MEISAI.CHOUSEI_JYUURYOU,
    ISNULL(MEISAI.NET_JYUURYOU, 0) AS NET_JYUURYOU,
	MEISAI.SUURYOU,
	MEISAI.UNIT_CD,
	MEISAI.UNIT_NAME,
	MEISAI.KINGAKU,
	MEISAI.DETAIL_TAX AS TAX,
	MEISAI.SUM_KINGAKU,
    MEISAI.MEISAI_BIKOU,
	SUM(ISNULL(MEISAI.NET_JYUURYOU,0)) OVER (PARTITION BY MEISAI.DENPYOU_NUMBER) AS NET_JYUURYOU_DENPYOU,
	SUM(ISNULL(MEISAI.NET_JYUURYOU,0)) OVER (PARTITION BY MEISAI.TORIHIKISAKI_CD) AS NET_JYUURYOU_TORIHIKISAKI,
	SUM(ISNULL(MEISAI.NET_JYUURYOU,0)) OVER (PARTITION BY MEISAI.TORIHIKISAKI_CD, MEISAI.GYOUSHA_CD) AS NET_JYUURYOU_GYOUSHA,
	SUM(ISNULL(MEISAI.NET_JYUURYOU,0)) OVER (PARTITION BY MEISAI.TORIHIKISAKI_CD, MEISAI.GYOUSHA_CD,MEISAI.GENBA_CD) AS NET_JYUURYOU_GENBA,
	SUM(ISNULL(MEISAI.NET_JYUURYOU,0)) OVER (PARTITION BY MEISAI.DELETE_FLG) AS NET_JYUURYOU_TOTAL,
	SUM(ISNULL(MEISAI.KINGAKU,0)) OVER (PARTITION BY MEISAI.DENPYOU_NUMBER) AS KINGAKU_DENPYOU,
	SUM(ISNULL(MEISAI.KINGAKU,0)) OVER (PARTITION BY MEISAI.TORIHIKISAKI_CD) AS KINGAKU_TORIHIKISAKI,
	SUM(ISNULL(MEISAI.KINGAKU,0)) OVER (PARTITION BY MEISAI.TORIHIKISAKI_CD, MEISAI.GYOUSHA_CD) AS KINGAKU_GYOUSHA,
	SUM(ISNULL(MEISAI.KINGAKU,0)) OVER (PARTITION BY MEISAI.TORIHIKISAKI_CD, MEISAI.GYOUSHA_CD,MEISAI.GENBA_CD) AS KINGAKU_GENBA,
	SUM(ISNULL(MEISAI.KINGAKU,0)) OVER (PARTITION BY MEISAI.DELETE_FLG) AS KINGAKU_TOTAL,
	SUM(ISNULL(MEISAI.TAX,0)) OVER (PARTITION BY MEISAI.DENPYOU_NUMBER) AS TAX_DENPYOU,
	SUM(ISNULL(MEISAI.TAX,0)) OVER (PARTITION BY MEISAI.TORIHIKISAKI_CD) AS TAX_TORIHIKISAKI,
	SUM(ISNULL(MEISAI.TAX,0)) OVER (PARTITION BY MEISAI.TORIHIKISAKI_CD, MEISAI.GYOUSHA_CD) AS TAX_GYOUSHA,
	SUM(ISNULL(MEISAI.TAX,0)) OVER (PARTITION BY MEISAI.TORIHIKISAKI_CD, MEISAI.GYOUSHA_CD,MEISAI.GENBA_CD) AS TAX_GENBA,
	SUM(ISNULL(MEISAI.TAX,0)) OVER (PARTITION BY MEISAI.DELETE_FLG) AS TAX_TOTAL,
	SUM(ISNULL(MEISAI.SUM_KINGAKU_TOTAL,0)) OVER (PARTITION BY MEISAI.DENPYOU_NUMBER) AS SUM_KINGAKU_DENPYOU,
	SUM(ISNULL(MEISAI.SUM_KINGAKU_TOTAL,0)) OVER (PARTITION BY MEISAI.TORIHIKISAKI_CD) AS SUM_KINGAKU_TORIHIKISAKI,
	SUM(ISNULL(MEISAI.SUM_KINGAKU_TOTAL,0)) OVER (PARTITION BY MEISAI.TORIHIKISAKI_CD, MEISAI.GYOUSHA_CD) AS SUM_KINGAKU_GYOUSHA,
	SUM(ISNULL(MEISAI.SUM_KINGAKU_TOTAL,0)) OVER (PARTITION BY MEISAI.TORIHIKISAKI_CD, MEISAI.GYOUSHA_CD,MEISAI.GENBA_CD) AS SUM_KINGAKU_GENBA,
	SUM(ISNULL(MEISAI.SUM_KINGAKU_TOTAL,0)) OVER (PARTITION BY MEISAI.DELETE_FLG) AS SUM_KINGAKU_TOTAL,
	ISNULL(MEISAI.GYOUSHA_CD,'000000') + ISNULL(MEISAI.GENBA_CD,'000000') AS KEY_GENBA 
FROM (
    SELECT
        ENTRY.SYSTEM_ID,
        ENTRY.SEQ,
        ENTRY.TAIRYUU_KBN,
        ENTRY.KYOTEN_CD,
        M_KYOTEN.KYOTEN_NAME_RYAKU AS KYOTEN_NAME_RYAKU,
        ENTRY.KEIRYOU_NUMBER AS DENPYOU_NUMBER,
        ENTRY.DATE_NUMBER,
        ENTRY.YEAR_NUMBER,
        ENTRY.DENPYOU_DATE,
		YEAR(ENTRY.DENPYOU_DATE) * 100 + MONTH(ENTRY.DENPYOU_DATE) AS YM,
		ENTRY.KIHON_KEIRYOU AS KEIRYOU_KBN,
		CASE WHEN ENTRY.KIHON_KEIRYOU = 1 THEN '受入' 
		WHEN ENTRY.KIHON_KEIRYOU = 2 THEN '出荷' END AS KEIRYOU_KBN_NAME,
        ENTRY.TORIHIKISAKI_CD,
        ENTRY.TORIHIKISAKI_NAME,
        ENTRY.GYOUSHA_CD,
        ENTRY.GYOUSHA_NAME,
        ENTRY.GENBA_CD,
        ENTRY.GENBA_NAME,
        ENTRY.UNPAN_GYOUSHA_CD,
        ENTRY.UNPAN_GYOUSHA_NAME,
        ENTRY.KEITAI_KBN_CD,
		M_KEITAI_KBN.KEITAI_KBN_NAME_RYAKU AS KEITAI_KBN_NAME,
		ENTRY.SHASHU_CD,
		ENTRY.SHASHU_NAME,
		ENTRY.SHARYOU_CD,
		ENTRY.SHARYOU_NAME,
		ENTRY.UNTENSHA_CD,
		ENTRY.UNTENSHA_NAME,
        ENTRY.CREATE_USER,
        ENTRY.CREATE_DATE,
        ENTRY.UPDATE_DATE,
		ENTRY.DELETE_FLG,
        DETAIL.DETAIL_SYSTEM_ID,
        DETAIL.ROW_NO,
		DETAIL.DENPYOU_KBN_CD,
        DETAIL.HINMEI_CD,
        DETAIL.HINMEI_NAME,
		DETAIL.STACK_JYUURYOU,
		DETAIL.EMPTY_JYUURYOU,
		ISNULL(DETAIL.STACK_JYUURYOU,0) - ISNULL(DETAIL.EMPTY_JYUURYOU,0) AS SE_JYUURYOU,
		DETAIL.CHOUSEI_JYUURYOU,
        DETAIL.NET_JYUURYOU,
		DETAIL.SUURYOU,
		DETAIL.UNIT_CD,
		M_UNIT.UNIT_NAME_RYAKU AS UNIT_NAME,
		DETAIL.MEISAI_BIKOU,
		ISNULL(DETAIL.KINGAKU,0) + ISNULL(DETAIL.HINMEI_KINGAKU,0) - ISNULL(DETAIL.TAX_UCHI,0) - ISNULL(DETAIL.HINMEI_TAX_UCHI,0) AS KINGAKU,
		CASE WHEN DETAIL.DENPYOU_KBN_CD = 1 AND (ENTRY.URIAGE_ZEI_KEISAN_KBN_CD = 3 OR DETAIL.HINMEI_ZEI_KBN_CD IS NOT NULL)
		     THEN ISNULL(DETAIL.TAX_SOTO,0) + ISNULL(DETAIL.TAX_UCHI,0) + ISNULL(DETAIL.HINMEI_TAX_SOTO,0) + ISNULL(DETAIL.HINMEI_TAX_UCHI,0)
			 WHEN DETAIL.DENPYOU_KBN_CD = 2 AND (ENTRY.SHIHARAI_ZEI_KEISAN_KBN_CD = 3 OR DETAIL.HINMEI_ZEI_KBN_CD IS NOT NULL) 
			 THEN ISNULL(DETAIL.TAX_SOTO,0) + ISNULL(DETAIL.TAX_UCHI,0) + ISNULL(DETAIL.HINMEI_TAX_SOTO,0) + ISNULL(DETAIL.HINMEI_TAX_UCHI,0)
			 ELSE 0 END AS DETAIL_TAX,
		CASE WHEN DETAIL.DENPYOU_KBN_CD = 1 AND (ENTRY.URIAGE_ZEI_KEISAN_KBN_CD = 1 OR ENTRY.URIAGE_ZEI_KEISAN_KBN_CD = 3 OR DETAIL.HINMEI_ZEI_KBN_CD IS NOT NULL)
		     THEN ISNULL(DETAIL.TAX_SOTO,0) + ISNULL(DETAIL.TAX_UCHI,0) + ISNULL(DETAIL.HINMEI_TAX_SOTO,0) + ISNULL(DETAIL.HINMEI_TAX_UCHI,0)
		     WHEN DETAIL.DENPYOU_KBN_CD = 2 AND (ENTRY.SHIHARAI_ZEI_KEISAN_KBN_CD = 1 OR ENTRY.SHIHARAI_ZEI_KEISAN_KBN_CD = 3 OR DETAIL.HINMEI_ZEI_KBN_CD IS NOT NULL)
		     THEN ISNULL(DETAIL.TAX_SOTO,0) + ISNULL(DETAIL.TAX_UCHI,0) + ISNULL(DETAIL.HINMEI_TAX_SOTO,0) + ISNULL(DETAIL.HINMEI_TAX_UCHI,0)
			 ELSE 0 END AS TAX,
		CASE WHEN DETAIL.DENPYOU_KBN_CD = 1 AND (ENTRY.URIAGE_ZEI_KEISAN_KBN_CD = 3 OR DETAIL.HINMEI_ZEI_KBN_CD IS NOT NULL)
		     THEN ISNULL(DETAIL.KINGAKU,0) + ISNULL(DETAIL.HINMEI_KINGAKU,0) + ISNULL(DETAIL.TAX_SOTO,0) + ISNULL(DETAIL.HINMEI_TAX_SOTO,0)
			 WHEN DETAIL.DENPYOU_KBN_CD = 2 AND (ENTRY.SHIHARAI_ZEI_KEISAN_KBN_CD = 3 OR DETAIL.HINMEI_ZEI_KBN_CD IS NOT NULL) 
			 THEN ISNULL(DETAIL.KINGAKU,0) + ISNULL(DETAIL.HINMEI_KINGAKU,0) + ISNULL(DETAIL.TAX_SOTO,0) + ISNULL(DETAIL.HINMEI_TAX_SOTO,0)
			 ELSE ISNULL(DETAIL.KINGAKU,0) + ISNULL(DETAIL.HINMEI_KINGAKU,0) END AS SUM_KINGAKU,
		CASE WHEN DETAIL.DENPYOU_KBN_CD = 1 AND (ENTRY.URIAGE_ZEI_KEISAN_KBN_CD = 1 OR ENTRY.URIAGE_ZEI_KEISAN_KBN_CD = 3 OR DETAIL.HINMEI_ZEI_KBN_CD IS NOT NULL)
		     THEN ISNULL(DETAIL.KINGAKU,0) + ISNULL(DETAIL.HINMEI_KINGAKU,0) + ISNULL(DETAIL.TAX_SOTO,0) + ISNULL(DETAIL.HINMEI_TAX_SOTO,0)
			 WHEN DETAIL.DENPYOU_KBN_CD = 2 AND (ENTRY.SHIHARAI_ZEI_KEISAN_KBN_CD = 1 OR ENTRY.SHIHARAI_ZEI_KEISAN_KBN_CD = 3 OR DETAIL.HINMEI_ZEI_KBN_CD IS NOT NULL) 
			 THEN ISNULL(DETAIL.KINGAKU,0) + ISNULL(DETAIL.HINMEI_KINGAKU,0) + ISNULL(DETAIL.TAX_SOTO,0) + ISNULL(DETAIL.HINMEI_TAX_SOTO,0)
			 ELSE ISNULL(DETAIL.KINGAKU,0) + ISNULL(DETAIL.HINMEI_KINGAKU,0) END AS SUM_KINGAKU_TOTAL,
		M_HINMEI.SHURUI_CD,
		ISNULL(M_SHURUI.SHURUI_NAME_RYAKU,'') AS SHURUI_NAME,
		M_HINMEI.BUNRUI_CD,
		ISNULL(M_BUNRUI.BUNRUI_NAME_RYAKU,'') AS BUNRUI_NAME
    FROM T_KEIRYOU_ENTRY AS ENTRY
    INNER JOIN T_KEIRYOU_DETAIL AS DETAIL
        ON ENTRY.SYSTEM_ID = DETAIL.SYSTEM_ID
        AND ENTRY.SEQ = DETAIL.SEQ
        AND ENTRY.KEIRYOU_NUMBER = DETAIL.KEIRYOU_NUMBER
	LEFT JOIN M_HINMEI
	    ON M_HINMEI.HINMEI_CD = DETAIL.HINMEI_CD
	LEFT JOIN M_SHURUI
		ON M_SHURUI.SHURUI_CD = M_HINMEI.SHURUI_CD
	LEFT JOIN M_BUNRUI
		ON M_BUNRUI.BUNRUI_CD = M_HINMEI.BUNRUI_CD
	LEFT JOIN M_UNIT
		ON M_UNIT.UNIT_CD = DETAIL.UNIT_CD
	LEFT JOIN M_KYOTEN
	    ON M_KYOTEN.KYOTEN_CD = ENTRY.KYOTEN_CD
    AND M_KYOTEN.DELETE_FLG = 0
	LEFT JOIN M_KEITAI_KBN
	    ON M_KEITAI_KBN.KEITAI_KBN_CD = ENTRY.KEITAI_KBN_CD
    WHERE ENTRY.DELETE_FLG = 0
) AS MEISAI
WHERE
    MEISAI.TAIRYUU_KBN = 0 AND MEISAI.DELETE_FLG = 0
    -- 拠点
    /*IF dto.KyotenCd != null && dto.KyotenCd != 99 */AND MEISAI.KYOTEN_CD = /*dto.KyotenCd*/'99'/*END*/
	-- 伝票区分
    /*IF dto.DenpyouKbnCd != null*/AND MEISAI.DENPYOU_KBN_CD = /*dto.DenpyouKbnCd*/0 /*END*/
    -- 伝票日付
    /*IF dto.DateShuruiCd != null && dto.DateShuruiCd == 1*/AND CONVERT(VARCHAR, MEISAI.DENPYOU_DATE, 111) >= /*dto.DateFrom*/'2014/01/01' AND CONVERT(VARCHAR, MEISAI.DENPYOU_DATE, 111) <= /*dto.DateTo*/'2014/01/01'/*END*/
    -- 入力日付
    /*IF dto.DateShuruiCd != null && dto.DateShuruiCd == 2*/AND CONVERT(VARCHAR, MEISAI.UPDATE_DATE, 111) >= /*dto.DateFrom*/'2014/01/01' AND CONVERT(VARCHAR, MEISAI.UPDATE_DATE, 111) <= /*dto.DateTo*/'2014/01/01'/*END*/
    -- 計量区分
    /*IF dto.KeiryouKbn != null && dto.KeiryouKbn != 3*/AND MEISAI.KEIRYOU_KBN = /*dto.KeiryouKbn*/0 /*END*/
	-- 取引先
    /*IF dto.TorihikisakiCdFrom != null && dto.TorihikisakiCdFrom != ''*/AND MEISAI.TORIHIKISAKI_CD >= /*dto.TorihikisakiCdFrom*/'000000'/*END*/
    /*IF dto.TorihikisakiCdTo != null && dto.TorihikisakiCdTo != ''*/AND MEISAI.TORIHIKISAKI_CD <= /*dto.TorihikisakiCdTo*/'000000'/*END*/
    -- 業者
    /*IF dto.GyoushaCdFrom != null && dto.GyoushaCdFrom != ''*/AND MEISAI.GYOUSHA_CD >= /*dto.GyoushaCdFrom*/'000000'/*END*/
    /*IF dto.GyoushaCdTo != null && dto.GyoushaCdTo != ''*/AND MEISAI.GYOUSHA_CD <= /*dto.GyoushaCdTo*/'000000'/*END*/
    -- 現場
    /*IF dto.GenbaCdFrom != null && dto.GenbaCdFrom != ''*/AND MEISAI.GENBA_CD >= /*dto.GenbaCdFrom*/'000000'/*END*/
    /*IF dto.GenbaCdTo != null && dto.GenbaCdTo != ''*/AND MEISAI.GENBA_CD <= /*dto.GenbaCdTo*/'000000'/*END*/
	-- 運搬業者
	/*IF dto.UpnGyoushaCdFrom != null && dto.UpnGyoushaCdFrom != ''*/AND MEISAI.UNPAN_GYOUSHA_CD >= /*dto.UpnGyoushaCdFrom*/'000000'/*END*/
    /*IF dto.UpnGyoushaCdTo != null && dto.UpnGyoushaCdTo != ''*/AND MEISAI.UNPAN_GYOUSHA_CD <= /*dto.UpnGyoushaCdTo*/'000000'/*END*/
	-- 品名
	/*IF dto.HinmeiCdFrom != null && dto.HinmeiCdFrom != ''*/AND MEISAI.HINMEI_CD >= /*dto.HinmeiCdFrom*/'000000'/*END*/
    /*IF dto.HinmeiCdTo != null && dto.HinmeiCdTo != ''*/AND MEISAI.HINMEI_CD <= /*dto.HinmeiCdTo*/'000000'/*END*/
	-- 種類
	/*IF dto.ShuruiCdFrom != null && dto.ShuruiCdFrom != ''*/AND MEISAI.SHURUI_CD >= /*dto.ShuruiCdFrom*/'000000'/*END*/
    /*IF dto.ShuruiCdTo != null && dto.ShuruiCdTo != ''*/AND MEISAI.SHURUI_CD <= /*dto.ShuruiCdTo*/'000000'/*END*/
	-- 分類
	/*IF dto.BunruiCdFrom != null && dto.BunruiCdFrom != ''*/AND MEISAI.BUNRUI_CD >= /*dto.BunruiCdFrom*/'000000'/*END*/
    /*IF dto.BunruiCdTo != null && dto.BunruiCdTo != ''*/AND MEISAI.BUNRUI_CD <= /*dto.BunruiCdTo*/'000000'/*END*/
	-- 形態区分
	/*IF dto.KeitaiKbnCdFrom != null && dto.KeitaiKbnCdFrom != ''*/AND MEISAI.KEITAI_KBN_CD >= /*dto.KeitaiKbnCdFrom*/'000000'/*END*/
    /*IF dto.KeitaiKbnCdTo != null && dto.KeitaiKbnCdTo != ''*/AND MEISAI.KEITAI_KBN_CD <= /*dto.KeitaiKbnCdTo*/'000000'/*END*/
ORDER BY 
    /*IF dto.GroupTani == null || dto.GroupTani == ''*/ 
	MEISAI.DENPYOU_DATE,
	MEISAI.TORIHIKISAKI_CD,
    MEISAI.TORIHIKISAKI_NAME,
    MEISAI.GYOUSHA_CD,
    MEISAI.GYOUSHA_NAME,
    MEISAI.GENBA_CD,
    MEISAI.GENBA_NAME, 
	/*END*/
    /*IF dto.GroupTani == 1*/ 
	MEISAI.TORIHIKISAKI_CD, 
	MEISAI.YM,
    MEISAI.TORIHIKISAKI_NAME,
    MEISAI.GYOUSHA_CD,
    MEISAI.GYOUSHA_NAME,
    MEISAI.GENBA_CD,
    MEISAI.GENBA_NAME,
	MEISAI.DENPYOU_DATE, /*END*/
	/*IF dto.GroupTani == 2*/ 
	MEISAI.GYOUSHA_CD, 
	MEISAI.YM, 
	MEISAI.TORIHIKISAKI_CD,
    MEISAI.TORIHIKISAKI_NAME,
    MEISAI.GYOUSHA_NAME,
    MEISAI.GENBA_CD,
    MEISAI.GENBA_NAME, 
	MEISAI.DENPYOU_DATE, /*END*/
	/*IF dto.GroupTani == 3*/ 
	MEISAI.GYOUSHA_CD, 
	MEISAI.GENBA_CD, 
	MEISAI.YM, 
	MEISAI.TORIHIKISAKI_CD,
    MEISAI.TORIHIKISAKI_NAME,
    MEISAI.GYOUSHA_NAME,
    MEISAI.GENBA_NAME,
	MEISAI.DENPYOU_DATE,  
	/*END*/
	/*IF dto.GroupTani == 4*/ 
	MEISAI.HINMEI_CD, 
	MEISAI.YM, 
	MEISAI.TORIHIKISAKI_CD,
    MEISAI.TORIHIKISAKI_NAME,
    MEISAI.GYOUSHA_CD,
    MEISAI.GYOUSHA_NAME,
    MEISAI.GENBA_CD,
    MEISAI.GENBA_NAME, 
	MEISAI.DENPYOU_DATE, 
	/*END*/
	/*IF dto.GroupTani == 5*/ 
	MEISAI.BUNRUI_CD, 
	MEISAI.HINMEI_CD, 
	MEISAI.YM, 
	MEISAI.TORIHIKISAKI_CD,
    MEISAI.TORIHIKISAKI_NAME,
    MEISAI.GYOUSHA_CD,
    MEISAI.GYOUSHA_NAME,
    MEISAI.GENBA_CD,
    MEISAI.GENBA_NAME, 
	MEISAI.DENPYOU_DATE, 
	/*END*/
	/*IF dto.GroupTani == 6*/ 
	MEISAI.SHURUI_CD, 
	MEISAI.HINMEI_CD, 
	MEISAI.YM, 
	MEISAI.TORIHIKISAKI_CD,
    MEISAI.TORIHIKISAKI_NAME,
    MEISAI.GYOUSHA_CD,
    MEISAI.GYOUSHA_NAME,
    MEISAI.GENBA_CD,
    MEISAI.GENBA_NAME, 
	MEISAI.DENPYOU_DATE, 
	/*END*/
    MEISAI.KEIRYOU_KBN,
    MEISAI.DENPYOU_NUMBER,
    MEISAI.ROW_NO
   
