SELECT
SYSTEM_ID,
SEQ,
DENPYOU_NUMBER,
ROW_NO,
SHORI_KBN,
ITAKU_KEIYAKU_SYSTEM_ID,
ITAKU_KEIYAKU_NO,
GYOUSHA_CD,
GYOUSHA_NAME,
GYOUSHA_ADDRESS,
GENBA_CD,
GENBA_NAME,
GENBA_ADDRESS,
KOUSHIN_SHUBETSU,
ITAKU_KEIYAKU_SHURUI,
ITAKU_KEIYAKU_DATE_BEGIN,
ITAKU_KEIYAKU_DATE_END,
SHOBUN_PATTERN_SYSYTEM_ID,
SHOBUN_PATTERN_SEQ,
SHOBUN_PATTERN_NAME,
LAST_SHOBUN_PATTERN_SYSYTEM_ID ,
LAST_SHOBUN_PATTERN_SEQ,
LAST_SHOBUN_PATTERN_NAME,
TIME_STAMP
FROM
T_ITAKU_MEMO_IKKATSU_DETAIL 
/*BEGIN*/WHERE
/*IF data.DENPYOU_NUMBER != null*/
   DENPYOU_NUMBER = /*data.DENPYOU_NUMBER*/
/*END*/
 /*IF data.SYSTEM_ID != null*/
 AND SYSTEM_ID = /*data.SYSTEM_ID*/
 /*END*/
  /*IF data.SEQ != null*/
 AND SEQ = /*data.SEQ*/
 /*END*/
/*END*/
ORDER BY ITAKU_KEIYAKU_NO