SELECT MHGTH.*
        ,ISNULL(H1.HINMEI_NAME_RYAKU,N'') AS HINMEI_NAME_RYAKU
        ,ISNULL(H2.HINMEI_NAME_RYAKU,N'') AS TSUKI_HINMEI_NAME_RYAKU
        ,ISNULL(U1.UNIT_NAME_RYAKU,N'') AS UNIT_NAME_RYAKU
        ,ISNULL(U2.UNIT_NAME_RYAKU,N'') AS KANSAN_UNIT_NAME_RYAKU
        ,ISNULL(D.DENPYOU_KBN_NAME_RYAKU,N'') AS DENPYOU_KBN_NAME_RYAKU
        ,CONVERT(nvarchar, N'') KEIYAKU_KBN_NAME
        ,CONVERT(nvarchar, N'') KEIJYOU_KBN_NAME
  FROM M_HIKIAI_GENBA_TEIKI_HINMEI AS MHGTH
    LEFT JOIN M_HINMEI H1 ON H1.HINMEI_CD = MHGTH.HINMEI_CD
    LEFT JOIN M_HINMEI H2 ON H2.HINMEI_CD = MHGTH.TSUKI_HINMEI_CD
    LEFT JOIN M_UNIT U1 ON U1.UNIT_CD = MHGTH.UNIT_CD
    LEFT JOIN M_UNIT U2 ON U2.UNIT_CD = MHGTH.KANSAN_UNIT_CD
    LEFT JOIN M_DENPYOU_KBN D ON D.DENPYOU_KBN_CD = MHGTH.DENPYOU_KBN_CD
 WHERE MHGTH.GYOUSHA_CD = /*entity.GYOUSHA_CD*/''
   AND MHGTH.GENBA_CD = /*entity.GENBA_CD*/''
   AND MHGTH.HIKIAI_GYOUSHA_USE_FLG = /*entity.HIKIAI_GYOUSHA_USE_FLG*/0
 ORDER BY MHGTH.ROW_NO ASC