SELECT MHGTH.*
        ,ISNULL(H.HINMEI_NAME_RYAKU,N'') AS HINMEI_NAME_RYAKU
        ,ISNULL(U.UNIT_NAME_RYAKU,N'') AS UNIT_NAME_RYAKU
        ,ISNULL(D.DENPYOU_KBN_NAME_RYAKU,N'') AS DENPYOU_KBN_NAME_RYAKU
  FROM M_HIKIAI_GENBA_TSUKI_HINMEI AS MHGTH
    LEFT JOIN M_HINMEI H ON H.HINMEI_CD = MHGTH.HINMEI_CD
    LEFT JOIN M_UNIT U ON U.UNIT_CD = MHGTH.UNIT_CD
    LEFT JOIN M_DENPYOU_KBN D ON D.DENPYOU_KBN_CD = MHGTH.DENPYOU_KBN_CD
 WHERE MHGTH.GYOUSHA_CD = /*entity.GYOUSHA_CD*/''
   AND MHGTH.GENBA_CD = /*entity.GENBA_CD*/''
   AND MHGTH.HIKIAI_GYOUSHA_USE_FLG = /*entity.HIKIAI_GYOUSHA_USE_FLG*/0
 ORDER BY MHGTH.ROW_NO ASC