SELECT MKGTH.*
        ,ISNULL(H1.HINMEI_NAME_RYAKU,N'') AS HINMEI_NAME_RYAKU
        ,ISNULL(H2.HINMEI_NAME_RYAKU,N'') AS TSUKI_HINMEI_NAME_RYAKU
        ,ISNULL(U1.UNIT_NAME_RYAKU,N'') AS UNIT_NAME_RYAKU
        ,ISNULL(U2.UNIT_NAME_RYAKU,N'') AS KANSAN_UNIT_NAME_RYAKU
        ,ISNULL(D.DENPYOU_KBN_NAME_RYAKU,N'') AS DENPYOU_KBN_NAME_RYAKU
        ,CONVERT(nvarchar, N'') KEIYAKU_KBN_NAME
        ,CONVERT(nvarchar, N'') KEIJYOU_KBN_NAME
  FROM M_KARI_GENBA_TEIKI_HINMEI AS MKGTH
    LEFT JOIN M_HINMEI H1 ON H1.HINMEI_CD = MKGTH.HINMEI_CD
    LEFT JOIN M_HINMEI H2 ON H2.HINMEI_CD = MKGTH.TSUKI_HINMEI_CD
    LEFT JOIN M_UNIT U1 ON U1.UNIT_CD = MKGTH.UNIT_CD
    LEFT JOIN M_UNIT U2 ON U2.UNIT_CD = MKGTH.KANSAN_UNIT_CD
    LEFT JOIN M_DENPYOU_KBN D ON D.DENPYOU_KBN_CD = MKGTH.DENPYOU_KBN_CD
 WHERE MKGTH.GYOUSHA_CD = /*data.GYOUSHA_CD*/''
   AND MKGTH.GENBA_CD = /*data.GENBA_CD*/''
 ORDER BY MKGTH.ROW_NO ASC