SELECT MKGTH.*
        ,ISNULL(H.HINMEI_NAME_RYAKU,N'') AS HINMEI_NAME_RYAKU
        ,ISNULL(U.UNIT_NAME_RYAKU,N'') AS UNIT_NAME_RYAKU
        ,ISNULL(D.DENPYOU_KBN_NAME_RYAKU,N'') AS DENPYOU_KBN_NAME_RYAKU
  FROM M_KARI_GENBA_TSUKI_HINMEI AS MKGTH
    LEFT JOIN M_HINMEI H ON H.HINMEI_CD = MKGTH.HINMEI_CD
    LEFT JOIN M_UNIT U ON U.UNIT_CD = MKGTH.UNIT_CD
    LEFT JOIN M_DENPYOU_KBN D ON D.DENPYOU_KBN_CD = MKGTH.DENPYOU_KBN_CD
 WHERE MKGTH.GYOUSHA_CD = /*data.GYOUSHA_CD*/''
   AND MKGTH.GENBA_CD = /*data.GENBA_CD*/''
 ORDER BY MKGTH.ROW_NO ASC