SELECT 
	SMSR.DELETE_FLG,
	SMSR.MOBILE_PHONE_NUMBER,
	SMSR.RECEIVER_NAME,
	(CASE
    WHEN SMSR.RENKEI_FLG = 1 AND SMSR.DELETE_FLG = 0 THEN '連携済'
	WHEN SMSR.RENKEI_FLG = 0 AND SMSR.DELETE_FLG = 0 THEN '送信待'
    ELSE ''
    END) AS STATUS,
	SMSR.SYSTEM_ID,
	SMSR.RENKEI_FLG
FROM M_SMS_RECEIVER SMSR
	LEFT JOIN M_SMS_RECEIVER_LINK_GENBA SMSRG ON SMSR.SYSTEM_ID = SMSRG.SYSTEM_ID
	AND SMSR.MOBILE_PHONE_NUMBER = SMSRG.MOBILE_PHONE_NUMBER
WHERE SMSRG.GYOUSHA_CD = /*data.GYOUSHA_CD*/''
	AND SMSRG.GENBA_CD = /*data.GENBA_CD*/''
ORDER BY SMSR.SYSTEM_ID ASC