SELECT
    TDSE.*
FROM
    T_DENSHI_SHINSEI_ENTRY AS TDSE JOIN
    T_DENSHI_SHINSEI_STATUS AS TDSS
ON  TDSE.SYSTEM_ID = TDSS.SYSTEM_ID
AND TDSE.SEQ = TDSS.SEQ
AND TDSS.SHINSEI_STATUS_CD = 2
AND TDSS.DELETE_FLG = 0
WHERE
    TDSE.DELETE_FLG = 0
/*IF entity.HIKIAI_GYOUSHA_CD != null && entity.HIKIAI_GYOUSHA_CD != ''*/AND TDSE.HIKIAI_GYOUSHA_CD = /*entity.HIKIAI_GYOUSHA_CD*/'000000'/*END*/
/*IF entity.HIKIAI_GENBA_CD != null && entity.HIKIAI_GENBA_CD != ''*/AND TDSE.HIKIAI_GENBA_CD = /*entity.HIKIAI_GENBA_CD*/'000000'/*END*/
/*IF entity.GYOUSHA_CD != null && entity.GYOUSHA_CD != ''*/AND TDSE.GYOUSHA_CD = /*entity.GYOUSHA_CD*/'000000'/*END*/
/*IF entity.GENBA_CD != null && entity.GENBA_CD != ''*/AND TDSE.GENBA_CD = /*entity.GENBA_CD*/'000000'/*END*/
/*IF !entity.SYSTEM_ID.IsNull*/AND TDSE.SYSTEM_ID = /*entity.SYSTEM_ID*/'-1'/*END*/
/*IF !entity.SEQ.IsNull*/AND TDSE.SEQ = /*entity.SEQ*/'-1'/*END*/