SELECT CASE WHEN ISDATE(HIKIWATASHI_DATE) = 0 THEN NULL
            ELSE CONVERT(nvarchar,CONVERT(DATETIME, HIKIWATASHI_DATE),120) 
		END AS HIKIWATASHI_DATE,
		HAIKI_DAI_CODE,
		HAIKI_CHU_CODE,
		HAIKI_SHO_CODE,
		MANIFEST_KBN
FROM DT_R18
WHERE KANRI_ID = /*data.KANRI_ID*/
AND SEQ = /*data.SEQ*/