SELECT M_KEIRYOU_CHOUSEI.TORIHIKISAKI_CD, M_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU, M_KEIRYOU_CHOUSEI.GYOUSHA_CD, M_GYOUSHA.GYOUSHA_NAME_RYAKU, M_KEIRYOU_CHOUSEI.GENBA_CD, M_GENBA.GENBA_NAME_RYAKU, M_KEIRYOU_CHOUSEI.HINMEI_CD, M_HINMEI.HINMEI_NAME_RYAKU, M_KEIRYOU_CHOUSEI.UNIT_CD, M_UNIT.UNIT_NAME_RYAKU, M_KEIRYOU_CHOUSEI.CHOUSEICHI, M_KEIRYOU_CHOUSEI.CHOUSEIWARIAI 
FROM dbo.M_KEIRYOU_CHOUSEI AS M_KEIRYOU_CHOUSEI 
LEFT JOIN dbo.M_TORIHIKISAKI AS M_TORIHIKISAKI ON M_KEIRYOU_CHOUSEI.TORIHIKISAKI_CD = M_TORIHIKISAKI.TORIHIKISAKI_CD 
AND CONVERT(DATE, ISNULL(M_TORIHIKISAKI.TEKIYOU_BEGIN, DATEADD(day,-1,GETDATE()))) <= CONVERT(DATE, GETDATE()) and CONVERT(DATE, GETDATE()) <= CONVERT(DATE, ISNULL(M_TORIHIKISAKI.TEKIYOU_END, DATEADD(day,1,GETDATE())))
AND M_TORIHIKISAKI.DELETE_FLG = 0
LEFT JOIN dbo.M_GYOUSHA AS M_GYOUSHA ON M_KEIRYOU_CHOUSEI.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD 
AND CONVERT(DATE, ISNULL(M_GYOUSHA.TEKIYOU_BEGIN, DATEADD(day,-1,GETDATE()))) <= CONVERT(DATE, GETDATE()) and CONVERT(DATE, GETDATE()) <= CONVERT(DATE, ISNULL(M_GYOUSHA.TEKIYOU_END, DATEADD(day,1,GETDATE())))
AND M_GYOUSHA.DELETE_FLG = 0
LEFT JOIN dbo.M_GENBA AS M_GENBA ON M_KEIRYOU_CHOUSEI.GENBA_CD = M_GENBA.GENBA_CD AND M_KEIRYOU_CHOUSEI.GYOUSHA_CD = M_GENBA.GYOUSHA_CD 
AND CONVERT(DATE, ISNULL(M_GENBA.TEKIYOU_BEGIN, DATEADD(day,-1,GETDATE()))) <= CONVERT(DATE, GETDATE()) and CONVERT(DATE, GETDATE()) <= CONVERT(DATE, ISNULL(M_GENBA.TEKIYOU_END, DATEADD(day,1,GETDATE())))
AND M_GENBA.DELETE_FLG = 0
LEFT JOIN dbo.M_HINMEI AS M_HINMEI ON M_KEIRYOU_CHOUSEI.HINMEI_CD = M_HINMEI.HINMEI_CD 
AND M_HINMEI.DELETE_FLG = 0
LEFT JOIN dbo.M_UNIT AS M_UNIT ON M_KEIRYOU_CHOUSEI.UNIT_CD = M_UNIT.UNIT_CD 
AND M_UNIT.DELETE_FLG = 0
WHERE 
 M_KEIRYOU_CHOUSEI.DELETE_FLG = 0
/*IF data.TORIHIKISAKI_CD != null*/AND M_KEIRYOU_CHOUSEI.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*//*END*/
/*IF data.GYOUSHA_CD != null*/AND M_KEIRYOU_CHOUSEI.GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/
/*IF data.GENBA_CD != null*/AND M_KEIRYOU_CHOUSEI.GENBA_CD = /*data.GENBA_CD*//*END*/
/*IF data.HINMEI_CD != null*/AND M_KEIRYOU_CHOUSEI.HINMEI_CD = /*data.HINMEI_CD*//*END*/
/*IF !data.UNIT_CD.IsNull*/AND M_KEIRYOU_CHOUSEI.UNIT_CD = /*data.UNIT_CD.Value*//*END*/
/*IF !data.CHOUSEICHI.IsNull*/AND M_KEIRYOU_CHOUSEI.CHOUSEICHI = /*data.CHOUSEICHI.Value*//*END*/
/*IF !data.CHOUSEIWARIAI.IsNull*/AND M_KEIRYOU_CHOUSEI.CHOUSEIWARIAI = /*data.CHOUSEIWARIAI.Value*//*END*/
/*IF data.KEIRYOU_CHOUSEI_BIKOU != null*/AND M_KEIRYOU_CHOUSEI.KEIRYOU_CHOUSEI_BIKOU = /*data.KEIRYOU_CHOUSEI_BIKOU*//*END*/
/*IF data.CREATE_USER != null*/AND M_KEIRYOU_CHOUSEI.CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND M_KEIRYOU_CHOUSEI.CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND M_KEIRYOU_CHOUSEI.CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND M_KEIRYOU_CHOUSEI.UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND M_KEIRYOU_CHOUSEI.UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND M_KEIRYOU_CHOUSEI.UPDATE_PC = /*data.UPDATE_PC*//*END*/
