SELECT * FROM dbo.M_KEIRYOU_CHOUSEI
WHERE 
/*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
 DELETE_FLG = 0
-- ELSE
 1 = 1
/*END*/
/*IF data.TORIHIKISAKI_CD != null*/AND TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*//*END*/
/*IF data.GYOUSHA_CD != null*/AND GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/
/*IF data.GENBA_CD != null*/AND GENBA_CD = /*data.GENBA_CD*//*END*/
/*IF data.HINMEI_CD != null*/AND HINMEI_CD = /*data.HINMEI_CD*//*END*/
/*IF !data.UNIT_CD.IsNull*/AND UNIT_CD = /*data.UNIT_CD.Value*//*END*/
/*IF !data.CHOUSEICHI.IsNull*/AND CHOUSEICHI = /*data.CHOUSEICHI.Value*//*END*/
/*IF !data.CHOUSEIWARIAI.IsNull*/AND CHOUSEIWARIAI = /*data.CHOUSEIWARIAI.Value*//*END*/
/*IF data.KEIRYOU_CHOUSEI_BIKOU != null*/AND KEIRYOU_CHOUSEI_BIKOU = /*data.KEIRYOU_CHOUSEI_BIKOU*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
