SELECT
	KAGAMI.TORIHIKISAKI_CD					--支払先CD
	,TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU	--支払先名
	,KAGAMI.GYOUSHA_CD						--業者CD
	,GYOUSHA.GYOUSHA_NAME_RYAKU				--業者名略称
	,KAGAMI.GENBA_CD						--現場CD
	,GENBA.GENBA_NAME_RYAKU					--現場名略称
	,DENPYOU.SHIMEBI						--締日
	,KAGAMI.KONKAI_SHIHARAI_GAKU			--今回取引額(税抜）
	,(ISNULL(KAGAMI.KONKAI_SEI_UTIZEI_GAKU,0) 
		+ ISNULL(KAGAMI.KONKAI_SEI_SOTOZEI_GAKU,0)  
		+ ISNULL(KAGAMI.KONKAI_DEN_UTIZEI_GAKU,0)  
		+ ISNULL(KAGAMI.KONKAI_DEN_SOTOZEI_GAKU,0)  
		+ ISNULL(KAGAMI.KONKAI_MEI_UTIZEI_GAKU,0) 
		+ ISNULL(KAGAMI.KONKAI_MEI_SOTOZEI_GAKU,0)
	) AS SHOUHIZEI							--消費税
	,KAGAMI.KONKAI_SHIHARAI_GAKU
		+(ISNULL(KAGAMI.KONKAI_SEI_UTIZEI_GAKU,0) 
		+ ISNULL(KAGAMI.KONKAI_SEI_SOTOZEI_GAKU,0)  
		+ ISNULL(KAGAMI.KONKAI_DEN_UTIZEI_GAKU,0)  
		+ ISNULL(KAGAMI.KONKAI_DEN_SOTOZEI_GAKU,0)  
		+ ISNULL(KAGAMI.KONKAI_MEI_UTIZEI_GAKU,0) 
		+ ISNULL(KAGAMI.KONKAI_MEI_SOTOZEI_GAKU,0)
	) AS KONKAI_SEISAN_GAKU					--今回御請求額
	,DENPYOU.SHUKKIN_YOTEI_BI				--入金予定日
	,DENPYOU.SEISAN_DATE					--支払年月日
FROM 
	T_SEISAN_DENPYOU AS DENPYOU
		INNER JOIN T_SEISAN_DENPYOU_KAGAMI AS KAGAMI
			ON DENPYOU.SEISAN_NUMBER=KAGAMI.SEISAN_NUMBER
		INNER JOIN M_TORIHIKISAKI AS TORIHIKISAKI
			ON TORIHIKISAKI.TORIHIKISAKI_CD = KAGAMI.TORIHIKISAKI_CD 
		LEFT JOIN M_GYOUSHA AS GYOUSHA
			ON GYOUSHA.GYOUSHA_CD = KAGAMI.GYOUSHA_CD 
		LEFT JOIN M_GENBA AS GENBA
			ON GENBA.GYOUSHA_CD = KAGAMI.GYOUSHA_CD AND GENBA.GENBA_CD=KAGAMI.GENBA_CD
WHERE
	DENPYOU.DELETE_FLG = 0
	/*IF !data.HIDUKE_FROM.IsNull*/ AND DENPYOU.SEISAN_DATE >= /*data.HIDUKE_FROM*//*END*/
	/*IF !data.HIDUKE_TO.IsNull*/ AND DENPYOU.SEISAN_DATE <= /*data.HIDUKE_TO*//*END*/
	/*IF data.TORIHIKISAKI_CD_FROM != ''*/ AND DENPYOU.TORIHIKISAKI_CD >= /*data.TORIHIKISAKI_CD_FROM*//*END*/
	/*IF data.TORIHIKISAKI_CD_TO != ''*/ AND DENPYOU.TORIHIKISAKI_CD <= /*data.TORIHIKISAKI_CD_TO*//*END*/
  /*IF !data.KYOTEN_CD.IsNull*/ AND (DENPYOU.KYOTEN_CD = /*data.KYOTEN_CD*/ OR /*data.KYOTEN_CD*/ = 99) /*END*/
  /*IF !data.TORIHIKISAKI_SORT.IsNull && data.TORIHIKISAKI_SORT == '1'*/ ORDER BY TORIHIKISAKI.TORIHIKISAKI_FURIGANA, DENPYOU.TORIHIKISAKI_CD, DENPYOU.SEISAN_DATE ASC /*END*/
  /*IF !data.TORIHIKISAKI_SORT.IsNull && data.TORIHIKISAKI_SORT == '2'*/ ORDER BY DENPYOU.TORIHIKISAKI_CD ASC /*END*/