SELECT
    MIX.HAIKI_SHURUI_CD,
    HAIKI_SHURUI.HAIKI_SHURUI_NAME,
    SBN_HOUHOU.SHOBUN_HOUHOU_CD AS SBN_HOUHOU_CD,
    SBN_HOUHOU.SHOBUN_HOUHOU_NAME_RYAKU AS SBN_HOUHOU_NAME,
    MIX.WARIAI,
    MIX.KONGOU_SHURUI_CD,
    KONGOU_SHURUI.KONGOU_SHURUI_NAME_RYAKU,
    MIX.HAIKI_SUU,
    MIX.HAIKI_UNIT_CD,
    M_UNIT.UNIT_NAME_RYAKU AS HAIKI_UNIT_NAME,
    MIX.KANSAN_SUU,
    MIX.GENNYOU_SUU,
    MIX.HAIKI_NAME_CD,
	CASE WHEN DENSHI_HAIKI.HAIKI_NAME IS NULL THEN HAIKI.HAIKI_NAME_RYAKU ELSE DENSHI_HAIKI.HAIKI_NAME END AS HAIKI_NAME_NAME,
    MIX.SBN_ENDREP_KBN,
    CASE RELATION.NEXT_HAIKI_KBN_CD
    WHEN 1 THEN '産廃'
    WHEN 2 THEN '建廃'
    WHEN 3 THEN '積替'
    WHEN 4 THEN '電子'
    END AS MANI_SHURUI,
    CASE RELATION.NEXT_HAIKI_KBN_CD
    WHEN 4 THEN DT_MF_TOC.MANIFEST_ID
    ELSE NEXT_PAPER_MANI.MANIFEST_ID
    END AS NEXT_MANIFEST_ID,
    CASE WHEN MIX.SBN_ENDREP_KBN = 1
        THEN
            CASE RELATION.NEXT_HAIKI_KBN_CD
            WHEN 4 THEN (SELECT MAX(R13.LAST_SBN_END_DATE) FROM DT_MF_TOC TOC LEFT JOIN DT_R13 R13 ON TOC.KANRI_ID = R13.KANRI_ID AND TOC.LATEST_SEQ = R13.SEQ WHERE TOC.KANRI_ID = NEXT_ELEC_MANI_EX.KANRI_ID)
            ELSE NEXT_PAPER_MANI.LAST_SBN_END_DATE
        END
        ELSE MIX.LAST_SBN_END_DATE
    END AS LAST_SBN_END_DATE,
    MIX.DETAIL_SYSTEM_ID,
    MIX.SEQ
FROM
    -- 一次マニ電子(混廃)
    DT_R18_EX AS R18EX
    INNER JOIN DT_R18_MIX AS MIX
    ON R18EX.SYSTEM_ID = MIX.SYSTEM_ID
	INNER JOIN DT_MF_TOC TOC
	ON TOC.KANRI_ID = R18EX.KANRI_ID
	INNER JOIN DT_R18 R18
	ON TOC.KANRI_ID = R18.KANRI_ID AND TOC.LATEST_SEQ = R18.SEQ
    LEFT JOIN T_MANIFEST_RELATION AS RELATION
    ON RELATION.FIRST_SYSTEM_ID = MIX.DETAIL_SYSTEM_ID
    AND RELATION.FIRST_HAIKI_KBN_CD = 4
    AND RELATION.DELETE_FLG = 0

    -- 二次マニ(紙)
    LEFT JOIN (
	SELECT
      MENTRY.*, MDETAIL.DETAIL_SYSTEM_ID, MDETAIL.LAST_SBN_END_DATE
    FROM
        T_MANIFEST_ENTRY AS MENTRY
		INNER JOIN T_MANIFEST_DETAIL AS MDETAIL 
			ON MDETAIL.SYSTEM_ID = MENTRY.SYSTEM_ID
			AND MENTRY.SEQ = MDETAIL.SEQ
	) AS NEXT_PAPER_MANI
	
    ON RELATION.NEXT_SYSTEM_ID = NEXT_PAPER_MANI.DETAIL_SYSTEM_ID
    AND NEXT_PAPER_MANI.DELETE_FLG = 0

    -- 二次マニ(電子)
    LEFT JOIN DT_R18_EX AS NEXT_ELEC_MANI_EX
    ON RELATION.NEXT_SYSTEM_ID = NEXT_ELEC_MANI_EX.SYSTEM_ID
    AND NEXT_ELEC_MANI_EX.DELETE_FLG = 0
    LEFT JOIN DT_MF_TOC
    ON NEXT_ELEC_MANI_EX.KANRI_ID = DT_MF_TOC.KANRI_ID

    -- 名称系取得
    LEFT JOIN M_DENSHI_HAIKI_SHURUI AS HAIKI_SHURUI
    ON MIX.HAIKI_DAI_CODE + MIX.HAIKI_CHU_CODE + MIX.HAIKI_SHO_CODE = HAIKI_SHURUI.HAIKI_SHURUI_CD
    LEFT JOIN M_SHOBUN_HOUHOU AS SBN_HOUHOU
    ON RIGHT('000' + convert(varchar, MIX.SBN_HOUHOU_CD) ,3) = SBN_HOUHOU.SHOBUN_HOUHOU_CD
    AND SBN_HOUHOU.DELETE_FLG = 0
    LEFT JOIN M_UNIT
    ON MIX.HAIKI_UNIT_CD = M_UNIT.UNIT_CD
    AND M_UNIT.DELETE_FLG = 0
    LEFT JOIN M_HAIKI_NAME AS HAIKI
    ON MIX.HAIKI_NAME_CD = HAIKI.HAIKI_NAME_CD
    AND HAIKI.DELETE_FLG = 0
    LEFT JOIN M_DENSHI_HAIKI_NAME AS DENSHI_HAIKI
    ON R18.HST_SHA_EDI_MEMBER_ID = DENSHI_HAIKI.EDI_MEMBER_ID AND MIX.HAIKI_NAME_CD = DENSHI_HAIKI.HAIKI_NAME_CD
    AND DENSHI_HAIKI.DELETE_FLG = 0
    LEFT JOIN M_KONGOU_SHURUI AS KONGOU_SHURUI
    ON KONGOU_SHURUI.HAIKI_KBN_CD = 4 
    AND MIX.KONGOU_SHURUI_CD = KONGOU_SHURUI.KONGOU_SHURUI_CD

WHERE
    R18EX.DELETE_FLG = 0
    AND R18EX.SYSTEM_ID = /*data.SYSTEM_ID*/
    AND MIX.KANRI_ID = /*data.KANRI_ID*/
    /*IF !data.DETAIL_SYSTEM_ID.IsNull && data.DETAIL_SYSTEM_ID != ''*/AND MIX.DETAIL_SYSTEM_ID = /*data.DETAIL_SYSTEM_ID*//*END*/
    /*IF !data.SEQ.IsNull && data.SEQ != ''*/AND MIX.SEQ = /*data.SEQ*//*END*/
    AND MIX.DELETE_FLG = 0
ORDER BY
    MIX.ROW_NO