SELECT MSJS.EDI_PASSWORD
  FROM MS_JWNET_MEMBER MSJS
  INNER JOIN M_DENSHI_JIGYOUSHA MDJ 
   ON MSJS.EDI_MEMBER_ID = MDJ.EDI_MEMBER_ID
   AND MDJ.UPN_KBN = 'True'
 WHERE MSJS.EDI_MEMBER_ID = /*SAI_UPN_SHA_EDI_MEMBER_ID*/
