-- SousinnHoryuuPopup(最終処分仮登録画面)から一部拝借
SELECT COUNT(*) AS 'COUNT'
FROM ( 
    SELECT
        T_LAST_SBN_SUSPEND.SYSTEM_ID
    FROM
        T_LAST_SBN_SUSPEND WITH(NOLOCK) 
        INNER JOIN  T_MANIFEST_ENTRY WITH(NOLOCK)
            ON T_LAST_SBN_SUSPEND.SYSTEM_ID = T_MANIFEST_ENTRY.SYSTEM_ID
        INNER JOIN  T_MANIFEST_DETAIL WITH(NOLOCK)
            ON T_MANIFEST_ENTRY.SYSTEM_ID = T_MANIFEST_DETAIL.SYSTEM_ID
            AND T_MANIFEST_ENTRY.SEQ = T_MANIFEST_DETAIL.SEQ
        INNER JOIN  T_MANIFEST_RELATION WITH(NOLOCK)
            ON T_MANIFEST_DETAIL.SYSTEM_ID = T_MANIFEST_RELATION.NEXT_SYSTEM_ID
            AND T_MANIFEST_RELATION.NEXT_HAIKI_KBN_CD != 4
            AND T_MANIFEST_RELATION.FIRST_HAIKI_KBN_CD = 4  
        INNER JOIN (
            SELECT
                DT_R18_EX.KANRI_ID,
                CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
                    THEN DT_R18_MIX.DETAIL_SYSTEM_ID
                    ELSE DT_R18_EX.SYSTEM_ID
                END
                AS SYSTEM_ID,
                DT_R18_EX.DELETE_FLG
            FROM
                DT_R18_EX WITH(NOLOCK)
                LEFT JOIN DT_R18_MIX WITH(NOLOCK)
                    ON DT_R18_EX.SYSTEM_ID = DT_R18_MIX.SYSTEM_ID
                    AND DT_R18_MIX.DELETE_FLG = 0
                WHERE
                    DT_R18_EX.DELETE_FLG = 0
        ) AS DT_R18_EX
            ON T_MANIFEST_RELATION.FIRST_SYSTEM_ID = DT_R18_EX.SYSTEM_ID
        INNER JOIN  DT_MF_TOC WITH(NOLOCK)
            ON DT_R18_EX.KANRI_ID = DT_MF_TOC.KANRI_ID
        INNER JOIN  QUE_INFO WITH(NOLOCK)
            ON DT_MF_TOC.KANRI_ID = QUE_INFO.KANRI_ID
            AND DT_MF_TOC.LATEST_SEQ = QUE_INFO.SEQ
        INNER JOIN  M_HAIKI_SHURUI WITH(NOLOCK)
            ON T_MANIFEST_ENTRY.HAIKI_KBN_CD = M_HAIKI_SHURUI.HAIKI_KBN_CD
            AND T_MANIFEST_DETAIL.HAIKI_SHURUI_CD = M_HAIKI_SHURUI.HAIKI_SHURUI_CD
    WHERE
        T_LAST_SBN_SUSPEND.DELETE_FLG = 0
        AND T_MANIFEST_ENTRY.DELETE_FLG = 0
        AND T_MANIFEST_RELATION.DELETE_FLG = 0
        AND DT_R18_EX.KANRI_ID = /*kanriId*/
        AND DT_R18_EX.DELETE_FLG = 0
        AND QUE_INFO.STATUS_FLAG = 7
        AND QUE_INFO.FUNCTION_ID IN (2000,2100)

    UNION ALL
    SELECT DISTINCT
        T_LAST_SBN_SUSPEND.SYSTEM_ID
    FROM
        T_LAST_SBN_SUSPEND WITH(NOLOCK) 
        INNER JOIN  T_MANIFEST_RELATION WITH(NOLOCK)
            ON T_LAST_SBN_SUSPEND.SYSTEM_ID = T_MANIFEST_RELATION.NEXT_SYSTEM_ID
            AND T_MANIFEST_RELATION.NEXT_HAIKI_KBN_CD = 4  AND T_MANIFEST_RELATION.FIRST_HAIKI_KBN_CD = 4
        INNER JOIN  DT_R18_EX AS DT_R18_EX_NEXT WITH(NOLOCK)
            ON  T_MANIFEST_RELATION.NEXT_SYSTEM_ID = DT_R18_EX_NEXT.SYSTEM_ID
        INNER JOIN  DT_MF_TOC AS DT_MF_TOC_NEXT WITH(NOLOCK)
            ON  DT_R18_EX_NEXT.KANRI_ID = DT_MF_TOC_NEXT.KANRI_ID
        INNER JOIN  DT_R18 WITH(NOLOCK)
            ON  DT_R18_EX_NEXT.KANRI_ID = DT_R18.KANRI_ID
            AND DT_MF_TOC_NEXT.LATEST_SEQ = DT_R18.SEQ
        INNER JOIN  M_DENSHI_HAIKI_SHURUI WITH(NOLOCK)
            ON  DT_R18.HAIKI_DAI_CODE + DT_R18.HAIKI_CHU_CODE + DT_R18.HAIKI_SHO_CODE = M_DENSHI_HAIKI_SHURUI.HAIKI_SHURUI_CD
        INNER JOIN (
            SELECT
                DT_R18_EX.KANRI_ID,
                CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
                    THEN DT_R18_MIX.DETAIL_SYSTEM_ID
                    ELSE DT_R18_EX.SYSTEM_ID
                END
                AS SYSTEM_ID,
                DT_R18_EX.DELETE_FLG
            FROM
                DT_R18_EX WITH(NOLOCK)
                LEFT JOIN DT_R18_MIX WITH(NOLOCK)
                    ON DT_R18_EX.SYSTEM_ID = DT_R18_MIX.SYSTEM_ID
                    AND DT_R18_MIX.DELETE_FLG = 0
                WHERE
            DT_R18_EX.DELETE_FLG = 0
        ) AS DT_R18_EX_FIRST
            ON  T_MANIFEST_RELATION.FIRST_SYSTEM_ID = DT_R18_EX_FIRST.SYSTEM_ID
        INNER JOIN  DT_MF_TOC AS DT_MF_TOC_FIRST WITH(NOLOCK)
            ON  DT_R18_EX_FIRST.KANRI_ID = DT_MF_TOC_FIRST.KANRI_ID
        INNER JOIN  QUE_INFO WITH(NOLOCK)
            ON  DT_MF_TOC_FIRST.KANRI_ID = QUE_INFO.KANRI_ID
            AND DT_MF_TOC_FIRST.LATEST_SEQ = QUE_INFO.SEQ 
    WHERE
        T_LAST_SBN_SUSPEND.DELETE_FLG = 0
        AND T_MANIFEST_RELATION.DELETE_FLG = 0
        AND DT_R18_EX_FIRST.KANRI_ID = /*kanriId*/
        AND DT_R18_EX_FIRST.DELETE_FLG = 0
        AND DT_R18_EX_NEXT.DELETE_FLG = 0
        AND QUE_INFO.STATUS_FLAG = 7
        AND QUE_INFO.FUNCTION_ID IN (2000,2100)
) AS SUMMARY