SELECT
	*
FROM
(
	/*IF data.DENPYOU_SHURUI_SHUSHU*/
	--収集
	SELECT
		ET.TORIHIKISAKI_CD
		,ET.TORIHIKISAKI_NAME AS TORIHIKISAKI_NAME_RYAKU
		,ET.GYOUSHA_CD
		,ET.GYOUSHA_NAME AS GYOUSHA_NAME_RYAKU
		,ET.GENBA_CD
		,ET.GENBA_NAME AS GENBA_NAME_RYAKU
		,CONVERT(NVARCHAR,ET.SAGYOU_DATE,111) AS SAGYOU_DATE
		,CONVERT(NVARCHAR,ET.UKETSUKE_DATE,111) AS UKETSUKE_DATE
		,'収集' AS DENPYOU_SHURUI
		,ET.UKETSUKE_NUMBER
		,ET.SHASHU_CD
		,ET.SHASHU_NAME
		,ET.SHARYOU_CD
		,ET.SHARYOU_NAME
		,ET.UNPAN_GYOUSHA_CD
		,ET.UNPAN_GYOUSHA_NAME
		,ET.UNTENSHA_CD
		,ET.UNTENSHA_NAME
		,DT.ROW_NO
		,DT.UNIT_CD
		,DT.HINMEI_CD
		,DT.HINMEI_NAME
		,CASE DT.DENPYOU_KBN_CD
			WHEN 1 THEN '売上'
			WHEN 2 THEN '支払'
			ELSE ''
		END AS DENPYOU_KBN
		,DT.SUURYOU AS TMP_SUURYOU
		,DT.UNIT_NAME_RYAKU AS UNIT_NAME
		,DT.TANKA AS TMP_TANKA
		,REPLACE(CONVERT(varchar, DT.KINGAKU, 1), '.00', '') AS KINGAKU
		,(ISNULL(ET.TORIHIKISAKI_CD,'') + '_' + ISNULL(ET.GYOUSHA_CD,'') + '_' + ISNULL(ET.GENBA_CD,'')
			+ '_' + ISNULL(CONVERT(NVARCHAR,ET.SAGYOU_DATE,120),'') + '_' + ISNULL(CONVERT(NVARCHAR,ET.UKETSUKE_DATE,120),'')
			+ '_' + '収集'+ '_' + ISNULL(CONVERT(NVARCHAR,ET.UKETSUKE_NUMBER),'') + '_' + ISNULL(ET.SHASHU_CD,'')
			+ '_' + ISNULL(ET.SHARYOU_CD,'') + '_' + ISNULL(ET.UNPAN_GYOUSHA_CD,'') + '_' + ISNULL(ET.UNTENSHA_CD,'')
		) AS GROUP_1_KEY
	FROM
		T_UKETSUKE_SS_ENTRY ET
		LEFT JOIN (
			SELECT
				T_UKETSUKE_SS_DETAIL.*
				,M_UNIT.UNIT_NAME_RYAKU
			FROM
				T_UKETSUKE_SS_DETAIL
				LEFT JOIN M_UNIT ON T_UKETSUKE_SS_DETAIL.UNIT_CD = M_UNIT.UNIT_CD
		) DT
			ON ET.SYSTEM_ID = DT.SYSTEM_ID
			AND ET.SEQ = DT.SEQ
	WHERE
		DELETE_FLG = 0
		/*IF data.KYOTEN_CD != 99*/
		AND ET.KYOTEN_CD = /*data.KYOTEN_CD*/99
		/*END*/
		/*IF data.HIDUKE == 1 */
		AND ET.UKETSUKE_DATE >= CONVERT(DateTime,/*data.HIDUKE_RANGE_FROM*/'2015/01/01', 111)
		AND ET.UKETSUKE_DATE < CONVERT(DateTime,/*data.HIDUKE_RANGE_TO*/'2015/12/31', 111)
		/*END*/
		/*IF data.HIDUKE == 2 */
		AND ET.SAGYOU_DATE >= CONVERT(DateTime,/*data.HIDUKE_RANGE_FROM*/'2015/01/01', 111)
		AND ET.SAGYOU_DATE < CONVERT(DateTime,/*data.HIDUKE_RANGE_TO*/'2015/12/31', 111)
		/*END*/
		/*IF data.HIDUKE == 3 */
		AND ET.UPDATE_DATE >= CONVERT(DateTime,/*data.HIDUKE_RANGE_FROM*/'2015/01/01', 111)
		AND ET.UPDATE_DATE < CONVERT(DateTime,/*data.HIDUKE_RANGE_TO*/'2015/12/31', 111)
		/*END*/
		AND (
			/*IF data.HAISHA_JOUKYOU_JUCHU*/
			ET.HAISHA_JOKYO_CD = 1
			/*END*/
			/*IF data.HAISHA_JOUKYOU_HAISHA*/
			/*IF data.HAISHA_JOUKYOU_JUCHU*/
			OR 
			/*END*/
			ET.HAISHA_JOKYO_CD = 2
			/*END*/
			/*IF data.HAISHA_JOUKYOU_KEIJO*/
			/*IF data.HAISHA_JOUKYOU_JUCHU || data.HAISHA_JOUKYOU_HAISHA*/
			OR
			/*END*/
			ET.HAISHA_JOKYO_CD = 3
			/*END*/
			/*IF data.HAISHA_JOUKYOU_CANCEL*/
			/*IF data.HAISHA_JOUKYOU_JUCHU || data.HAISHA_JOUKYOU_HAISHA || data.HAISHA_JOUKYOU_KEIJO*/
			OR
			/*END*/
			ET.HAISHA_JOKYO_CD = 4
			/*END*/
			/*IF data.HAISHA_JOUKYOU_KAISHUNASHI*/
			/*IF data.HAISHA_JOUKYOU_JUCHU || data.HAISHA_JOUKYOU_HAISHA || data.HAISHA_JOUKYOU_KEIJO || data.HAISHA_JOUKYOU_CANCEL*/
			OR
			/*END*/
			ET.HAISHA_JOKYO_CD = 5
			/*END*/
		)
		/*IF data.TORIHIKISAKI_CD_FROM != ''*/
		AND ET.TORIHIKISAKI_CD >= /*data.TORIHIKISAKI_CD_FROM*/'000000'
		/*END*/
		/*IF data.TORIHIKISAKI_CD_TO != ''*/
		AND ET.TORIHIKISAKI_CD <= /*data.TORIHIKISAKI_CD_TO*/'ZZZZZZ'
		/*END*/
		/*IF data.GYOUSHA_CD_FROM != ''*/
		AND ET.GYOUSHA_CD >= /*data.GYOUSHA_CD_FROM*/'000000'
		/*END*/
		/*IF data.GYOUSHA_CD_TO != ''*/
		AND ET.GYOUSHA_CD <= /*data.GYOUSHA_CD_TO*/'ZZZZZZ'
		/*END*/
		/*IF data.GENBA_CD_FROM != ''*/
		AND ET.GENBA_CD >= /*data.GENBA_CD_FROM*/'000000'
		/*END*/
		/*IF data.GENBA_CD_TO != ''*/
		AND ET.GENBA_CD <= /*data.GENBA_CD_TO*/'ZZZZZZ'
		/*END*/
		/*IF data.UNPAN_GYOUSHA_CD_FROM != ''*/
		AND ET.UNPAN_GYOUSHA_CD >= /*data.UNPAN_GYOUSHA_CD_FROM*/'000000'
		/*END*/
		/*IF data.UNPAN_GYOUSHA_CD_TO != ''*/
		AND ET.UNPAN_GYOUSHA_CD <= /*data.UNPAN_GYOUSHA_CD_TO*/'ZZZZZZ'
		/*END*/
		/*IF data.SHASHU_CD_FROM != ''*/
		AND ET.SHASHU_CD >= /*data.SHASHU_CD_FROM*/'000'
		/*END*/
		/*IF data.SHASHU_CD_TO != ''*/
		AND ET.SHASHU_CD <= /*data.SHASHU_CD_TO*/'ZZZ'
		/*END*/
		/*IF data.SHARYOU_CD_FROM != ''*/
		AND ET.SHARYOU_CD >= /*data.SHARYOU_CD_FROM*/'000000'
		/*END*/
		/*IF data.SHARYOU_CD_TO != ''*/
		AND ET.SHARYOU_CD <= /*data.SHARYOU_CD_TO*/'ZZZZZZ'
		/*END*/
		/*IF data.UNTENSHA_CD_FROM != ''*/
		AND ET.UNTENSHA_CD >= /*data.UNTENSHA_CD_FROM*/'000000'
		/*END*/
		/*IF data.UNTENSHA_CD_TO != ''*/
		AND ET.UNTENSHA_CD <= /*data.UNTENSHA_CD_TO*/'ZZZZZZ'
		/*END*/
	/*END*/

	/*IF data.DENPYOU_SHURUI_SHUSHU && data.DENPYOU_SHURUI_SHUKKA*/
	UNION
	/*END*/
	
	/*IF data.DENPYOU_SHURUI_SHUKKA*/
	--出荷
	SELECT
		ET.TORIHIKISAKI_CD
		,ET.TORIHIKISAKI_NAME AS TORIHIKISAKI_NAME_RYAKU
		,ET.GYOUSHA_CD
		,ET.GYOUSHA_NAME AS GYOUSHA_NAME_RYAKU
		,ET.GENBA_CD
		,ET.GENBA_NAME AS GENBA_NAME_RYAKU
		,CONVERT(NVARCHAR,ET.SAGYOU_DATE,111) AS SAGYOU_DATE
		,CONVERT(NVARCHAR,ET.UKETSUKE_DATE,111) AS UKETSUKE_DATE
		,'出荷' AS DENPYOU_SHURUI
		,ET.UKETSUKE_NUMBER
		,ET.SHASHU_CD
		,ET.SHASHU_NAME
		,ET.SHARYOU_CD
		,ET.SHARYOU_NAME
		,ET.UNPAN_GYOUSHA_CD
		,ET.UNPAN_GYOUSHA_NAME
		,ET.UNTENSHA_CD
		,ET.UNTENSHA_NAME
		,DT.ROW_NO
		,DT.UNIT_CD
		,DT.HINMEI_CD
		,DT.HINMEI_NAME
		,CASE DT.DENPYOU_KBN_CD
			WHEN 1 THEN '売上'
			WHEN 2 THEN '支払'
			ELSE ''
		END AS DENPYOU_KBN
		,DT.SUURYOU AS TMP_SUURYOU
		,DT.UNIT_NAME_RYAKU AS UNIT_NAME
		,DT.TANKA AS TMP_TANKA
		,REPLACE(CONVERT(varchar, DT.KINGAKU, 1), '.00', '') AS KINGAKU
		,(ISNULL(ET.TORIHIKISAKI_CD,'') + '_' + ISNULL(ET.GYOUSHA_CD,'') + '_' + ISNULL(ET.GENBA_CD,'')
			+ '_' + ISNULL(CONVERT(NVARCHAR,ET.SAGYOU_DATE,120),'') + '_' + ISNULL(CONVERT(NVARCHAR,ET.UKETSUKE_DATE,120),'')
			+ '_' + '出荷'+ '_' + ISNULL(CONVERT(NVARCHAR,ET.UKETSUKE_NUMBER),'') + '_' + ISNULL(ET.SHASHU_CD,'')
			+ '_' + ISNULL(ET.SHARYOU_CD,'') + '_' + ISNULL(ET.UNPAN_GYOUSHA_CD,'') + '_' + ISNULL(ET.UNTENSHA_CD,'')
		) AS GROUP_1_KEY
	FROM
		T_UKETSUKE_SK_ENTRY ET
		LEFT JOIN (
			SELECT
				T_UKETSUKE_SK_DETAIL.*
				,M_UNIT.UNIT_NAME_RYAKU
			FROM
				T_UKETSUKE_SK_DETAIL
				LEFT JOIN M_UNIT ON T_UKETSUKE_SK_DETAIL.UNIT_CD = M_UNIT.UNIT_CD
		) DT
			ON ET.SYSTEM_ID = DT.SYSTEM_ID
			AND ET.SEQ = DT.SEQ
	WHERE
		DELETE_FLG = 0
		/*IF data.KYOTEN_CD != 99*/
		AND ET.KYOTEN_CD = /*data.KYOTEN_CD*/99
		/*END*/
		/*IF data.HIDUKE == 1 */
		AND ET.UKETSUKE_DATE >= CONVERT(DateTime,/*data.HIDUKE_RANGE_FROM*/'2015/01/01', 111)
		AND ET.UKETSUKE_DATE < CONVERT(DateTime,/*data.HIDUKE_RANGE_TO*/'2015/12/31', 111)
		/*END*/
		/*IF data.HIDUKE == 2 */
		AND ET.SAGYOU_DATE >= CONVERT(DateTime,/*data.HIDUKE_RANGE_FROM*/'2015/01/01', 111)
		AND ET.SAGYOU_DATE < CONVERT(DateTime,/*data.HIDUKE_RANGE_TO*/'2015/12/31', 111)
		/*END*/
		/*IF data.HIDUKE == 3 */
		AND ET.UPDATE_DATE >= CONVERT(DateTime,/*data.HIDUKE_RANGE_FROM*/'2015/01/01', 111)
		AND ET.UPDATE_DATE < CONVERT(DateTime,/*data.HIDUKE_RANGE_TO*/'2015/12/31', 111)
		/*END*/
		AND (
			/*IF data.HAISHA_JOUKYOU_JUCHU*/
			ET.HAISHA_JOKYO_CD = 1
			/*END*/
			/*IF data.HAISHA_JOUKYOU_HAISHA*/
			/*IF data.HAISHA_JOUKYOU_JUCHU*/
			OR 
			/*END*/
			ET.HAISHA_JOKYO_CD = 2
			/*END*/
			/*IF data.HAISHA_JOUKYOU_KEIJO*/
			/*IF data.HAISHA_JOUKYOU_JUCHU || data.HAISHA_JOUKYOU_HAISHA*/
			OR
			/*END*/
			ET.HAISHA_JOKYO_CD = 3
			/*END*/
			/*IF data.HAISHA_JOUKYOU_CANCEL*/
			/*IF data.HAISHA_JOUKYOU_JUCHU || data.HAISHA_JOUKYOU_HAISHA || data.HAISHA_JOUKYOU_KEIJO*/
			OR
			/*END*/
			ET.HAISHA_JOKYO_CD = 4
			/*END*/
			/*IF data.HAISHA_JOUKYOU_KAISHUNASHI*/
			/*IF data.HAISHA_JOUKYOU_JUCHU || data.HAISHA_JOUKYOU_HAISHA || data.HAISHA_JOUKYOU_KEIJO || data.HAISHA_JOUKYOU_CANCEL*/
			OR
			/*END*/
			ET.HAISHA_JOKYO_CD = 5
			/*END*/
		)
		/*IF data.TORIHIKISAKI_CD_FROM != ''*/
		AND ET.TORIHIKISAKI_CD >= /*data.TORIHIKISAKI_CD_FROM*/'000000'
		/*END*/
		/*IF data.TORIHIKISAKI_CD_TO != ''*/
		AND ET.TORIHIKISAKI_CD <= /*data.TORIHIKISAKI_CD_TO*/'ZZZZZZ'
		/*END*/
		/*IF data.GYOUSHA_CD_FROM != ''*/
		AND ET.GYOUSHA_CD >= /*data.GYOUSHA_CD_FROM*/'000000'
		/*END*/
		/*IF data.GYOUSHA_CD_TO != ''*/
		AND ET.GYOUSHA_CD <= /*data.GYOUSHA_CD_TO*/'ZZZZZZ'
		/*END*/
		/*IF data.GENBA_CD_FROM != ''*/
		AND ET.GENBA_CD >= /*data.GENBA_CD_FROM*/'000000'
		/*END*/
		/*IF data.GENBA_CD_TO != ''*/
		AND ET.GENBA_CD <= /*data.GENBA_CD_TO*/'ZZZZZZ'
		/*END*/
		/*IF data.UNPAN_GYOUSHA_CD_FROM != ''*/
		AND ET.UNPAN_GYOUSHA_CD >= /*data.UNPAN_GYOUSHA_CD_FROM*/'000000'
		/*END*/
		/*IF data.UNPAN_GYOUSHA_CD_TO != ''*/
		AND ET.UNPAN_GYOUSHA_CD <= /*data.UNPAN_GYOUSHA_CD_TO*/'ZZZZZZ'
		/*END*/
		/*IF data.SHASHU_CD_FROM != ''*/
		AND ET.SHASHU_CD >= /*data.SHASHU_CD_FROM*/'000'
		/*END*/
		/*IF data.SHASHU_CD_TO != ''*/
		AND ET.SHASHU_CD <= /*data.SHASHU_CD_TO*/'ZZZ'
		/*END*/
		/*IF data.SHARYOU_CD_FROM != ''*/
		AND ET.SHARYOU_CD >= /*data.SHARYOU_CD_FROM*/'000000'
		/*END*/
		/*IF data.SHARYOU_CD_TO != ''*/
		AND ET.SHARYOU_CD <= /*data.SHARYOU_CD_TO*/'ZZZZZZ'
		/*END*/
		/*IF data.UNTENSHA_CD_FROM != ''*/
		AND ET.UNTENSHA_CD >= /*data.UNTENSHA_CD_FROM*/'000000'
		/*END*/
		/*IF data.UNTENSHA_CD_TO != ''*/
		AND ET.UNTENSHA_CD <= /*data.UNTENSHA_CD_TO*/'ZZZZZZ'
		/*END*/
	/*END*/

	/*IF (data.DENPYOU_SHURUI_SHUSHU || data.DENPYOU_SHURUI_SHUKKA) && data.DENPYOU_SHURUI_MOCHIKOMI*/
	UNION
	/*END*/
	
	/*IF data.DENPYOU_SHURUI_MOCHIKOMI*/
	--持込
	SELECT
		ET.TORIHIKISAKI_CD
		,ET.TORIHIKISAKI_NAME AS TORIHIKISAKI_NAME_RYAKU
		,ET.GYOUSHA_CD
		,ET.GYOUSHA_NAME AS GYOUSHA_NAME_RYAKU
		,ET.GENBA_CD
		,ET.GENBA_NAME AS GENBA_NAME_RYAKU
		,CONVERT(NVARCHAR,ET.SAGYOU_DATE,111) AS SAGYOU_DATE
		,CONVERT(NVARCHAR,ET.UKETSUKE_DATE,111) AS UKETSUKE_DATE
		,'持込' AS DENPYOU_SHURUI
		,ET.UKETSUKE_NUMBER
		,ET.SHASHU_CD
		,ET.SHASHU_NAME
		,ET.SHARYOU_CD
		,ET.SHARYOU_NAME
		,ET.UNPAN_GYOUSHA_CD
		,ET.UNPAN_GYOUSHA_NAME
		,'' AS UNTENSHA_CD
		,'' AS UNTENSHA_NAME
		,DT.ROW_NO
		,DT.UNIT_CD
		,DT.HINMEI_CD
		,DT.HINMEI_NAME
		,CASE DT.DENPYOU_KBN_CD
			WHEN 1 THEN '売上'
			WHEN 2 THEN '支払'
			ELSE ''
		END AS DENPYOU_KBN
		,DT.SUURYOU AS TMP_SUURYOU
		,DT.UNIT_NAME_RYAKU AS UNIT_NAME
		,DT.TANKA AS TMP_TANKA
		,REPLACE(CONVERT(varchar, DT.KINGAKU, 1), '.00', '') AS KINGAKU
		,(ISNULL(ET.TORIHIKISAKI_CD,'') + '_' + ISNULL(ET.GYOUSHA_CD,'') + '_' + ISNULL(ET.GENBA_CD,'')
			+ '_' + ISNULL(CONVERT(NVARCHAR,ET.SAGYOU_DATE,120),'') + '_' + ISNULL(CONVERT(NVARCHAR,ET.UKETSUKE_DATE,120),'')
			+ '_' + '持込'+ '_' + ISNULL(CONVERT(NVARCHAR,ET.UKETSUKE_NUMBER),'') + '_' + ISNULL(ET.SHASHU_CD,'')
			+ '_' + ISNULL(ET.SHARYOU_CD,'') + '_' + ISNULL(ET.UNPAN_GYOUSHA_CD,'') + '_' + ''
		) AS GROUP_1_KEY
	FROM
		T_UKETSUKE_MK_ENTRY ET
		LEFT JOIN (
			SELECT
				T_UKETSUKE_MK_DETAIL.*
				,M_UNIT.UNIT_NAME_RYAKU
			FROM
				T_UKETSUKE_MK_DETAIL
				LEFT JOIN M_UNIT ON T_UKETSUKE_MK_DETAIL.UNIT_CD = M_UNIT.UNIT_CD
		) DT
			ON ET.SYSTEM_ID = DT.SYSTEM_ID
			AND ET.SEQ = DT.SEQ
	WHERE
		DELETE_FLG = 0
		/*IF data.KYOTEN_CD != 99*/
		AND ET.KYOTEN_CD = /*data.KYOTEN_CD*/99
		/*END*/
		/*IF data.HIDUKE == 1 */
		AND ET.UKETSUKE_DATE >= CONVERT(DateTime,/*data.HIDUKE_RANGE_FROM*/'2015/01/01', 111)
		AND ET.UKETSUKE_DATE < CONVERT(DateTime,/*data.HIDUKE_RANGE_TO*/'2015/12/31', 111)
		/*END*/
		/*IF data.HIDUKE == 2 */
		AND ET.SAGYOU_DATE >= CONVERT(DateTime,/*data.HIDUKE_RANGE_FROM*/'2015/01/01', 111)
		AND ET.SAGYOU_DATE < CONVERT(DateTime,/*data.HIDUKE_RANGE_TO*/'2015/12/31', 111)
		/*END*/
		/*IF data.HIDUKE == 3 */
		AND ET.UPDATE_DATE >= CONVERT(DateTime,/*data.HIDUKE_RANGE_FROM*/'2015/01/01', 111)
		AND ET.UPDATE_DATE < CONVERT(DateTime,/*data.HIDUKE_RANGE_TO*/'2015/12/31', 111)
		/*END*/
		/*IF data.TORIHIKISAKI_CD_FROM != ''*/
		AND ET.TORIHIKISAKI_CD >= /*data.TORIHIKISAKI_CD_FROM*/'000000'
		/*END*/
		/*IF data.TORIHIKISAKI_CD_TO != ''*/
		AND ET.TORIHIKISAKI_CD <= /*data.TORIHIKISAKI_CD_TO*/'ZZZZZZ'
		/*END*/
		/*IF data.GYOUSHA_CD_FROM != ''*/
		AND ET.GYOUSHA_CD >= /*data.GYOUSHA_CD_FROM*/'000000'
		/*END*/
		/*IF data.GYOUSHA_CD_TO != ''*/
		AND ET.GYOUSHA_CD <= /*data.GYOUSHA_CD_TO*/'ZZZZZZ'
		/*END*/
		/*IF data.GENBA_CD_FROM != ''*/
		AND ET.GENBA_CD >= /*data.GENBA_CD_FROM*/'000000'
		/*END*/
		/*IF data.GENBA_CD_TO != ''*/
		AND ET.GENBA_CD <= /*data.GENBA_CD_TO*/'ZZZZZZ'
		/*END*/
		/*IF data.UNPAN_GYOUSHA_CD_FROM != ''*/
		AND ET.UNPAN_GYOUSHA_CD >= /*data.UNPAN_GYOUSHA_CD_FROM*/'000000'
		/*END*/
		/*IF data.UNPAN_GYOUSHA_CD_TO != ''*/
		AND ET.UNPAN_GYOUSHA_CD <= /*data.UNPAN_GYOUSHA_CD_TO*/'ZZZZZZ'
		/*END*/
		/*IF data.SHASHU_CD_FROM != ''*/
		AND ET.SHASHU_CD >= /*data.SHASHU_CD_FROM*/'000'
		/*END*/
		/*IF data.SHASHU_CD_TO != ''*/
		AND ET.SHASHU_CD <= /*data.SHASHU_CD_TO*/'ZZZ'
		/*END*/
		/*IF data.SHARYOU_CD_FROM != ''*/
		AND ET.SHARYOU_CD >= /*data.SHARYOU_CD_FROM*/'000000'
		/*END*/
		/*IF data.SHARYOU_CD_TO != ''*/
		AND ET.SHARYOU_CD <= /*data.SHARYOU_CD_TO*/'ZZZZZZ'
		/*END*/
	/*END*/
) PRINT_DATA
ORDER BY
/*IF data.ORDER == 1*/
TORIHIKISAKI_CD,GYOUSHA_CD,GENBA_CD,SAGYOU_DATE,UKETSUKE_NUMBER,ROW_NO
/*END*/
/*IF data.ORDER == 2*/
GYOUSHA_CD,GENBA_CD,TORIHIKISAKI_CD,SAGYOU_DATE,UKETSUKE_NUMBER,ROW_NO
/*END*/
/*IF data.ORDER == 3*/
UNPAN_GYOUSHA_CD,SHARYOU_CD,SAGYOU_DATE,UKETSUKE_NUMBER,ROW_NO
/*END*/
/*IF data.ORDER == 4*/
UNTENSHA_CD,SAGYOU_DATE,UKETSUKE_NUMBER,ROW_NO
/*END*/
/*IF data.ORDER == 5*/
SAGYOU_DATE,UKETSUKE_NUMBER,ROW_NO
/*END*/
/*IF data.ORDER == 6*/
UKETSUKE_NUMBER,ROW_NO
/*END*/