//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KyokaShouIchiran.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
   
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KYOKA_KBN
        {
            get
            {
                return ((string)(this["KYOKA_KBN"]));
            }
            set
            {
                this["KYOKA_KBN"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FUTSU_KBN
        {
            get
            {
                return ((string)(this["FUTSU_KBN"]));
            }
            set
            {
                this["FUTSU_KBN"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KIKAN_KBN
        {
            get
            {
                return ((string)(this["KIKAN_KBN"]));
            }
            set
            {
                this["KIKAN_KBN"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HIDUKE_FROM
        {
            get
            {
                return ((string)(this["HIDUKE_FROM"]));
            }
            set
            {
                this["HIDUKE_FROM"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HIDUKE_TO
        {
            get
            {
                return ((string)(this["HIDUKE_TO"]));
            }
            set
            {
                this["HIDUKE_TO"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KYOKA_NO
        {
            get
            {
                return ((string)(this["KYOKA_NO"]));
            }
            set
            {
                this["KYOKA_NO"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GYOUSHA_CD
        {
            get
            {
                return ((string)(this["GYOUSHA_CD"]));
            }
            set
            {
                this["GYOUSHA_CD"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_CD
        {
            get
            {
                return ((string)(this["GENBA_CD"]));
            }
            set
            {
                this["GENBA_CD"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CHIIKI_CD
        {
            get
            {
                return ((string)(this["CHIIKI_CD"]));
            }
            set
            {
                this["CHIIKI_CD"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HOUKOKU_SHOU_BUNRUI_CD
        {
            get
            {
                return ((string)(this["HOUKOKU_SHOU_BUNRUI_CD"]));
            }
            set
            {
                this["HOUKOKU_SHOU_BUNRUI_CD"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string ICHIRAN_HYOUJI_JOUKEN_DELETED
        {
            get
            {
                return ((string)(this["ICHIRAN_HYOUJI_JOUKEN_DELETED"]));
            }
            set
            {
                this["ICHIRAN_HYOUJI_JOUKEN_DELETED"] = value;
            }
        }
    }
    
}
