SELECT
T1.HINMEI_CD,
T1.HINMEI_NAME,
T1.HINMEI_NAME_RYAKU,
T1.DENPYOU_KBN_CD,
T1.ZEI_KBN_CD,
T1.UNIT_CD,
T2.UNIT_NAME_RYAKU AS UNIT_NAME


FROM M_HINMEI AS T1
LEFT JOIN dbo.M_UNIT AS T2 ON T1.UNIT_CD = T2.UNIT_CD AND T2.DELETE_FLG = 0

WHERE
T1.DELETE_FLG = 0
AND T1.HINMEI_CD = /*hinmeiCD*/'0'
AND (T1.DENSHU_KBN_CD = 2  OR T1.DENSHU_KBN_CD = 9)
AND (T1.DENPYOU_KBN_CD = 1  OR T1.DENPYOU_KBN_CD = 9)
