SELECT MIN(T1.UR_SH_NUMBER)
  FROM T_UR_SH_ENTRY T1
  INNER JOIN T_UR_SH_DETAIL T2
    ON T2.SYSTEM_ID = T1.SYSTEM_ID
   AND T2.SEQ = T1.SEQ
 WHERE DELETE_FLG = 0
   AND DAINOU_FLG = 1
   AND KYOTEN_CD = /*data.KYOTEN_CD*/0