SELECT 
	T1.TORIHIKISAKI_CD AS TORIHIKISAKI_CD,
	T2.TORIHIKISAKI_NAME1 AS TORIHIKISAKI_NAME1,
	T2.TORIHIKISAKI_NAME_RYAKU AS TORIHIKISAKI_NAME_RYAKU,
	T2.TORIHIKISAKI_ADDRESS1 AS TORIHIKISAKI_ADDRESS1,
	T2.TORIHIKISAKI_ADDRESS2 AS TORIHIKISAKI_ADDRESS2,
	T2.TORIHIKISAKI_TEL AS TORIHIKISAKI_TEL,
	T2.TEKIYOU_BEGIN AS TORIHIKISAKI_TEKIYOU_BEGIN,
	T2.TEKIYOU_END AS TORIHIKISAKI_TEKIYOU_END,
	T1.GYOUSHA_CD AS GYOUSHA_CD,
	T1.GYOUSHA_NAME1 AS GYOUSHA_NAME1,
	T1.GYOUSHA_NAME_RYAKU AS GYOUSHA_NAME_RYAKU,
	T1.GYOUSHA_ADDRESS1 AS GYOUSHA_ADDRESS1,
	T1.GYOUSHA_ADDRESS2 AS GYOUSHA_ADDRESS2,
	T1.GYOUSHA_TEL AS GYOUSHA_TEL,
	T3.TODOUFUKEN_NAME_RYAKU AS GYOUSHA_TODOUFUKEN_NAME_RYAKU		
	

FROM dbo.M_GYOUSHA AS T1 
LEFT JOIN dbo.M_TORIHIKISAKI AS T2 ON T1.TORIHIKISAKI_CD = T2.TORIHIKISAKI_CD 
LEFT JOIN dbo.M_TODOUFUKEN AS T3 ON T1.GYOUSHA_TODOUFUKEN_CD = T3.TODOUFUKEN_CD

WHERE 
 T1.GYOUSHA_CD = /*gyoushaCd*/0
 AND T1.UNPAN_JUTAKUSHA_KAISHA_KBN = 1

