  SELECT 
     HINMEI.ZAIKO_HINMEI_CD
    ,HINMEI.ZAIKO_HINMEI_NAME_RYAKU AS ZAIKO_HINMEI_NAME
  FROM dbo.M_ZAIKO_HINMEI HINMEI
/*BEGIN*/ 
WHERE 
/*IF zaikoHinmei!= null*/HINMEI.ZAIKO_HINMEI_CD = /*zaikoHinmei*//*END*/
 AND  HINMEI.DELETE_FLG = 0 
/*END*/