  SELECT
     ZAIKO_HIRITSU
	,DELETE_FLG
	,ZAIKO_HINMEI_CD
    ,DENSHU_KBN_CD
    ,HINMEI_CD
  FROM dbo.M_ZAIKO_HIRITSU HIRITSU
/*BEGIN*/ 
  WHERE 
/*IF data.DENSHU_KBN_CD!= null*/HIRITSU.DENSHU_KBN_CD = /*data.DENSHU_KBN_CD*//*END*/
/*IF data.HINMEI_CD!= null*/AND HIRITSU.HINMEI_CD = /*data.HINMEI_CD*//*END*/
/*IF data.ZAIKO_HINMEI_CD!= null*/AND HIRITSU.ZAIKO_HINMEI_CD = /*data.ZAIKO_HINMEI_CD*//*END*/
AND HIRITSU.DELETE_FLG = 0
/*END*/