UPDATE M_ZAIKO_HIRITSU SET
	DENSHU_KBN_CD = /*data.DENSHU_KBN_CD*/0,
	HINMEI_CD = /*data.HINMEI_CD*/'',
	HINMEI_NAME = /*data.HINMEI_NAME*/'',
	ZAIKO_HINMEI_CD = /*data.ZAIKO_HINMEI_CD*/'',
	ZAIKO_HINMEI_NAME = /*data.ZAIKO_HINMEI_NAME*/'',
	UNIT_CD = /*data.UNIT_CD*/0,
	ZAIKO_HIRITSU = /*data.ZAIKO_HIRITSU*/0,
	BIKOU = /*data.BIKOU*/'',
	UPDATE_USER = /*data.UPDATE_USER*/'',
	UPDATE_DATE = CONVERT(DATETIME, /*data.UPDATE_DATE*/null, 120),
	UPDATE_PC = /*data.UPDATE_PC*/'',
	DELETE_FLG = /*data.DELETE_FLG*/0
WHERE DENSHU_KBN_CD = /*updateKey.DENSHU_KBN_CD*/0
  AND HINMEI_CD = /*updateKey.HINMEI_CD*/''
  AND ZAIKO_HINMEI_CD = /*updateKey.ZAIKO_HINMEI_CD*/''
