 SELECT
	MCDEI.ROUND_NO
	,MCDEI.GYOUSHA_CD
	,MCDEI.GYOUSHA_NAME_RYAKU
	,MCDEI.GENBA_CD
	,MCDEI.GENBA_NAME_RYAKU
	,MCDEI.HINMEI_CD
	,MCDEI.HINMEI_NAME_RYAKU
	,MCDEI.DENPYOU_KBN_CD
	,MCDEI.UNIT_CD
	,MCDEI.UNIT_NAME_RYAKU
	,MCDEI.KANSAN_UNIT_CD
	,MCDEI.UNITKANSAN_NAME
	,MCDEI.KEIYAKU_KBN
	,MCDEI.NIOROSHI_NO AS NIOROSHI_NUMBER_DETAIL
	,MCDEI.BIKOU AS HINMEI_BIKOU
	,MCDEI.KEIJYOU_KBN AS TSUKIGIME_KBN
	--,MCDEI.KANSANCHI
	,MCDEI.INPUT_KBN
	,MCDEI.ANBUN_FLG
	,MCDEI.ROW_NO AS [ROW_NUMBER] 
 FROM
	M_COURSE MC
		INNER JOIN (
			SELECT
				CDE.ROUND_NO
				,CDE.DAY_CD
				,CDE.COURSE_NAME_CD
				,CDE.REC_ID
				,CDE.ROW_NO
				,MCDI.NIOROSHI_NO
				,CDE.GYOUSHA_CD
				,GYO.GYOUSHA_NAME_RYAKU
				,CDE.GENBA_CD
				,GEN.GENBA_NAME_RYAKU
				,CDE.BIKOU
				,MCDI.HINMEI_CD
				,MCDI.HINMEI_NAME_RYAKU
				,MCDI.UNIT_CD
				,MCDI.UNIT_NAME_RYAKU
				--,MCDI.KANSANCHI
				,MCDI.KANSAN_UNIT_CD
				,MCDI.UNITKANSAN_NAME
				,MCDI.KEIYAKU_KBN
				,MCDI.DENPYOU_KBN_CD
				,MCDI.KEIJYOU_KBN
				,MCDI.INPUT_KBN
				,MCDI.ANBUN_FLG
			FROM
				M_COURSE_DETAIL CDE
					INNER JOIN M_GYOUSHA GYO ON GYO.GYOUSHA_CD = CDE.GYOUSHA_CD
					INNER JOIN M_GENBA GEN ON GEN.GYOUSHA_CD = CDE.GYOUSHA_CD AND GEN.GENBA_CD = CDE.GENBA_CD
					INNER JOIN (
						SELECT
							CDI.DAY_CD
							,CDI.COURSE_NAME_CD
							,CDI.REC_ID
							,CDI.HINMEI_CD
							,HIN.HINMEI_NAME_RYAKU
							,CDI.UNIT_CD
							,UNI.UNIT_NAME_RYAKU
							--,CDI.KANSANCHI
							,CASE CDI.KANSAN_UNIT_CD
								WHEN 0 THEN NULL
								ELSE CDI.KANSAN_UNIT_CD
								END
							 AS KANSAN_UNIT_CD
							,KANSAN_UNI.UNIT_NAME_RYAKU AS UNITKANSAN_NAME
							,CDI.KEIYAKU_KBN
							,CDI.DENPYOU_KBN_CD
							,CDI.KEIJYOU_KBN
							,CDI.NIOROSHI_NO
							,CDI.INPUT_KBN
							,CDI.ANBUN_FLG
						FROM
							M_COURSE_DETAIL_ITEMS CDI
								LEFT JOIN M_HINMEI HIN ON HIN.HINMEI_CD = CDI.HINMEI_CD
								LEFT JOIN M_UNIT UNI ON UNI.UNIT_CD = CDI.UNIT_CD
								LEFT JOIN M_UNIT KANSAN_UNI ON KANSAN_UNI.UNIT_CD = CDI.KANSAN_UNIT_CD
						WHERE
							((CDI.TEKIYOU_BEGIN <= /*data.tekiyouDate*/ AND /*data.tekiyouDate*/ <= CDI.TEKIYOU_END)
								OR (CDI.TEKIYOU_BEGIN <= /*data.tekiyouDate*/ AND CDI.TEKIYOU_END IS NULL))

					) MCDI ON CDE.DAY_CD = MCDI.DAY_CD AND CDE.COURSE_NAME_CD = MCDI.COURSE_NAME_CD AND CDE.REC_ID = MCDI.REC_ID
		) MCDEI ON MC.DAY_CD = MCDEI.DAY_CD AND MC.COURSE_NAME_CD = MCDEI.COURSE_NAME_CD
 WHERE
	MC.DELETE_FLG = 0
	/*IF data.dayCd != 0*/AND MC.DAY_CD = /*data.dayCd*//*END*/
	AND MC.COURSE_NAME_CD = /*data.courseNameCd*/
 ORDER BY ROW_NO