 SELECT
	MCN.NIOROSHI_NO AS NIOROSHI_NUMBER
	,MCN.NIOROSHI_GYOUSHA_CD AS NIOROSHI_GYOUSHA_CD
	,MCN.GYOUSHA_NAME_RYAKU AS NIOROSHI_GYOUSHA_NAME_RYAKU
	,MCN.NIOROSHI_GENBA_CD AS NIOROSHI_GENBA_CD
	,MCN.GENBA_NAME_RYAKU AS NIOROSHI_GENBA_NAME_RYAKU
 FROM
	M_COURSE MC
		INNER JOIN (
			SELECT
				CN.DAY_CD
				,CN.COURSE_NAME_CD
				,CN.NIOROSHI_NO
				,CN.NIOROSHI_GYOUSHA_CD
				,GYO.GYOUSHA_NAME_RYAKU
				,CN.NIOROSHI_GENBA_CD
				,GEN.GENBA_NAME_RYAKU
			FROM
				M_COURSE_NIOROSHI CN
					INNER JOIN M_GYOUSHA GYO ON GYO.GYOUSHA_CD = CN.NIOROSHI_GYOUSHA_CD
					INNER JOIN M_GENBA GEN ON GEN.GYOUSHA_CD = CN.NIOROSHI_GYOUSHA_CD AND GEN.GENBA_CD = CN.NIOROSHI_GENBA_CD
		) MCN ON MC.DAY_CD = MCN.DAY_CD AND MC.COURSE_NAME_CD = MCN.COURSE_NAME_CD
 WHERE
	MC.DELETE_FLG = 0
	/*IF data.dayCd != 0*/ AND MC.DAY_CD = /*data.dayCd*//*END*/
	AND MC.COURSE_NAME_CD = /*data.courseNameCd*/
 ORDER BY NIOROSHI_NUMBER