SELECT
TTHD.SYSTEM_ID
,TTHD.SEQ
,TTHD.DETAIL_SYSTEM_ID
,TTHD.TEIKI_JISSEKI_NUMBER
,TTHD.ROW_NUMBER
,TTHD.INPUT_KBN
,TTHD.ROUND_NO
,TTHD.GYOUSHA_CD
,TTHD.GENBA_CD
,TTHD.HINMEI_CD
,TTHD.SUURYOU AS SUURYOU
,TTHD.UNIT_CD
,TTHD.ANBUN_SUURYOU
,TTHD.NIOROSHI_NUMBER
,CAST(TTHD.SHUUSHUU_TIME as varchar) AS SHUUSHUU_TIME
,TTHD.KAISHUU_BIKOU
,TTHD.KANSAN_SUURYOU
,TTHD.KANSAN_UNIT_CD
,TTHD.HINMEI_BIKOU
,TTHD.TSUKIGIME_KBN
,TTHD.KEIYAKU_KBN
,TTHD.DENPYOU_KBN_CD
,TTHD.KAKUTEI_FLG
,M_GYOUSHA.GYOUSHA_NAME_RYAKU
,M_GENBA.GENBA_NAME_RYAKU
,M_HINMEI.HINMEI_NAME_RYAKU
,M_UNIT.UNIT_NAME_RYAKU
,UNITKANSAN.UNIT_NAME_RYAKU  AS UNITKANSAN_NAME
,TTHD.GYOUSHA_CD+TTHD.GENBA_CD AS GYOUSHAGENBA
, CASE WHEN TTHD.HINMEI_CD IS  NOT NULL AND  TTHD.UNIT_CD IS NOT NULL THEN TTHD.HINMEI_CD+CAST(TTHD.UNIT_CD as varchar)
	 ELSE '1' END AS HINMEIUNIT
, CASE WHEN TTHD.HINMEI_CD IS  NOT NULL AND  TTHD.KANSAN_UNIT_CD IS NOT NULL THEN TTHD.HINMEI_CD+CAST(TTHD.KANSAN_UNIT_CD as varchar)
	 ELSE '1' END AS HINMEIKANSANUNIT
,TTHD.KANSAN_UNIT_MOBILE_OUTPUT_FLG
,KANSAN.KANSANCHI
,TTHD.UR_SH_NUMBER AS UR_SH_NUMBER_NUMERIC
,TTHD.ANBUN_FLG
FROM
	T_TEIKI_JISSEKI_DETAIL TTHD
	INNER JOIN T_TEIKI_JISSEKI_ENTRY TTJE
	ON TTHD.SYSTEM_ID = TTJE.SYSTEM_ID
	AND TTHD.SEQ = TTJE.SEQ
	LEFT JOIN M_GYOUSHA
		ON TTHD.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
	LEFT JOIN M_GENBA
		ON TTHD.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
		AND TTHD.GENBA_CD = M_GENBA.GENBA_CD
	LEFT JOIN M_HINMEI
		ON TTHD.HINMEI_CD = M_HINMEI.HINMEI_CD
	LEFT JOIN M_UNIT
		ON TTHD.UNIT_CD = M_UNIT.UNIT_CD
	LEFT JOIN M_UNIT AS UNITKANSAN
		ON TTHD.KANSAN_UNIT_CD = UNITKANSAN.UNIT_CD
	LEFT JOIN T_UR_SH_ENTRY AS TUSE
		ON TTHD.UR_SH_NUMBER = TUSE.UR_SH_NUMBER
		AND TUSE.DELETE_FLG='0'
	LEFT JOIN M_GENBA_TEIKI_HINMEI AS KANSAN
	    ON TTHD.GYOUSHA_CD = KANSAN.GYOUSHA_CD
		AND TTHD.GENBA_CD = KANSAN.GENBA_CD
		AND TTHD.HINMEI_CD = KANSAN.HINMEI_CD
		AND TTHD.UNIT_CD = KANSAN.UNIT_CD
		AND TTHD.DENPYOU_KBN_CD = KANSAN.DENPYOU_KBN_CD
WHERE
	TTHD.SYSTEM_ID = /*data.SystemId*/
	AND TTHD.SEQ = /*data.Seq*/
ORDER BY
	TTHD.ROW_NUMBER
