SELECT 
	TTHE.SYSTEM_ID
,TTHE.SEQ
,TTHE.KYOTEN_CD
,TTHE.TEIKI_HAISHA_NUMBER
,TTHE.DAY_CD
,TTHE.DENPYOU_DATE
,TTHE.SAGYOU_DATE
,TTHE.SAGYOU_BEGIN_HOUR
,TTHE.SAGYOU_BEGIN_MINUTE
,TTHE.SAGYOU_END_HOUR
,TTHE.SAGYOU_END_MINUTE
,TTHE.COURSE_NAME_CD
,TTHE.SHARYOU_CD
,TTHE.SHASHU_CD
,TTHE.UNTENSHA_CD
,TTHE.UNPAN_GYOUSHA_CD
,TTHE.HOJOIN_CD
,'' CREATE_USER
,'' CREATE_DATE
,'' CREATE_PC
,'' UPDATE_USER
,'' UPDATE_DATE
,'' UPDATE_PC
,TTHE.DELETE_FLG
,TTHE.TIME_STAMP
	,MK.KYOTEN_NAME_RYAKU
	,MCN.COURSE_NAME_RYAKU
	,MSHARYOU.SHARYOU_NAME_RYAKU
	,MSHASHU.SHASHU_NAME_RYAKU
	,UNTENSHA.SHAIN_NAME_RYAKU AS UNTENSHA_NAME
	,HOJOIN.SHAIN_NAME_RYAKU AS HOJOIN_NAME
	,UNPAN_GYOUSHA.GYOUSHA_NAME_RYAKU AS UNPAN_GYOUSHA_NAME
	,'' AS TEIKI_JISSEKI_NUMBER
	,'' AS WEATHER
	,'' AS SHUKKO_METER
	,'' AS SHUKKO_HOUR
	,'' AS SHUKKO_MINUTE
	,'' AS KIKO_METER
	,'' AS KIKO_HOUR
	,'' AS KIKO_MINUTE
	,FURIKAE_HAISHA_KBN

FROM
	T_TEIKI_HAISHA_ENTRY TTHE
	LEFT JOIN M_KYOTEN MK
		ON TTHE.KYOTEN_CD = MK.KYOTEN_CD
	LEFT JOIN M_COURSE_NAME MCN
		ON TTHE.COURSE_NAME_CD = MCN.COURSE_NAME_CD
	LEFT JOIN M_SHARYOU MSHARYOU
		ON MSHARYOU.GYOUSHA_CD = TTHE.UNPAN_GYOUSHA_CD
		AND TTHE.SHARYOU_CD = MSHARYOU.SHARYOU_CD
	LEFT JOIN M_SHASHU MSHASHU
		ON TTHE.SHASHU_CD = MSHASHU.SHASHU_CD
	LEFT JOIN M_SHAIN UNTENSHA
		ON TTHE.UNTENSHA_CD = UNTENSHA.SHAIN_CD
	LEFT JOIN M_SHAIN HOJOIN
		ON TTHE.HOJOIN_CD = HOJOIN.SHAIN_CD
	LEFT JOIN M_GYOUSHA UNPAN_GYOUSHA
		ON TTHE.UNPAN_GYOUSHA_CD = UNPAN_GYOUSHA.GYOUSHA_CD
WHERE
	TTHE.TEIKI_HAISHA_NUMBER = /*data.TeikiHaishaNumber*/ 
	AND TTHE.DELETE_FLG = 0