SELECT 
 TTJE.SYSTEM_ID	
,TTJE.SEQ	
,TTJE.KYOTEN_CD	
,TTJE.TEIKI_HAISHA_NUMBER	
,TTJE.DENPYOU_DATE	
,TTJE.SAGYOU_DATE	
,TTHE.SAGYOU_BEGIN_HOUR	
,TTHE.SAGYOU_BEGIN_MINUTE	
,TTHE.SAGYOU_END_HOUR	
,TTHE.SAGYOU_END_MINUTE	
,TTJE.COURSE_NAME_CD	
,TTJE.SHARYOU_CD	
,TTJE.SHASHU_CD	
,TTJE.UNTENSHA_CD	
,TTJE.UNPAN_GYOUSHA_CD
,TTJE.HOJOIN_CD	
,'' CREATE_USER	
,'' CREATE_DATE	
,'' CREATE_PC	
,'' UPDATE_USER	
,'' UPDATE_DATE	
,'' UPDATE_PC	
,TTJE.DELETE_FLG	
,TTJE.TIME_STAMP
,MK.KYOTEN_NAME_RYAKU
,MCN.COURSE_NAME_RYAKU
,MSHARYOU.SHARYOU_NAME_RYAKU
,MSHASHU.SHASHU_NAME_RYAKU
,UNTENSHA.SHAIN_NAME_RYAKU AS UNTENSHA_NAME
,HOJOIN.SHAIN_NAME_RYAKU AS HOJOIN_NAME
,TTJE.TEIKI_JISSEKI_NUMBER AS TEIKI_JISSEKI_NUMBER
,UNPAN_GYOUSHA.GYOUSHA_NAME_RYAKU AS UNPAN_GYOUSHA_NAME
,'' AS WEATHER
,'' AS SHUKKO_METER
,'' AS SHUKKO_HOUR
,'' AS SHUKKO_MINUTE
,'' AS KIKO_METER
,'' AS KIKO_HOUR
,'' AS KIKO_MINUTE
FROM
	T_TEIKI_JISSEKI_ENTRY TTJE
	LEFT JOIN (SELECT * FROM T_TEIKI_HAISHA_ENTRY WHERE DELETE_FLG = 0) TTHE
		ON TTJE.TEIKI_HAISHA_NUMBER = TTHE.TEIKI_HAISHA_NUMBER
	LEFT JOIN M_KYOTEN MK
		ON TTJE.KYOTEN_CD = MK.KYOTEN_CD
	LEFT JOIN M_COURSE_NAME MCN
		ON TTJE.COURSE_NAME_CD = MCN.COURSE_NAME_CD
	LEFT JOIN M_SHARYOU MSHARYOU
		ON MSHARYOU.GYOUSHA_CD = TTJE.UNPAN_GYOUSHA_CD
		AND TTJE.SHARYOU_CD = MSHARYOU.SHARYOU_CD
	LEFT JOIN M_SHASHU MSHASHU
		ON TTJE.SHASHU_CD = MSHASHU.SHASHU_CD
	LEFT JOIN M_SHAIN UNTENSHA
		ON TTJE.UNTENSHA_CD = UNTENSHA.SHAIN_CD
	LEFT JOIN M_SHAIN HOJOIN
		ON TTJE.HOJOIN_CD = HOJOIN.SHAIN_CD
	LEFT JOIN M_GYOUSHA UNPAN_GYOUSHA
		ON TTJE.UNPAN_GYOUSHA_CD = UNPAN_GYOUSHA.GYOUSHA_CD
WHERE
	TTJE.TEIKI_HAISHA_NUMBER = /*data.TeikiHaishaNumber*/ 
	AND TTJE.DELETE_FLG = 0
