SELECT DISTINCT
	TTHD.SYSTEM_ID
	,TTHD.SEQ
	,'' DETAIL_SYSTEM_ID
	,TTHD.TEIKI_HAISHA_NUMBER
	,TTHD.ROW_NUMBER
	,TTHS.ROW_NUMBER
	,TTHS.INPUT_KBN
	,TTHS.NIOROSHI_NUMBER
	,TTHD.ROUND_NO
	,TTHD.GYOUSHA_CD
	,TTHD.GENBA_CD
	,M_GYOUSHA.GYOUSHA_NAME_RYAKU
	,M_GENBA.GENBA_NAME_RYAKU
	,'' AS TEIKI_JISSEKI_NUMBER
	,TTHS.HINMEI_CD
	,'' AS SUURYOU
	,TTHS.UNIT_CD
	,'' AS ANBUN_SUURYOU
	,'' AS SHUUSHUU_TIME
	,'' AS KAISHUU_BIKOU
	,'' AS HINMEI_BIKOU
	,'' AS KAKUTEI_FLG
	,TTHS.KEIJYOU_KBN AS TSUKIGIME_KBN
	,TTHS.KEIYAKU_KBN AS KEIYAKU_KBN
    ,TTHS.DENPYOU_KBN_CD AS DENPYOU_KBN_CD
	,TTHS.KANSANCHI
	,'' AS KANSAN_SUURYOU
	,TTHS.KANSAN_UNIT_CD
	,M_HINMEI.HINMEI_NAME_RYAKU
	,M_UNIT.UNIT_NAME_RYAKU
	,UNITKANSAN.UNIT_NAME_RYAKU  AS UNITKANSAN_NAME
	,TTHD.GYOUSHA_CD+TTHD.GENBA_CD AS GYOUSHAGENBA
 , CASE WHEN TTHS.HINMEI_CD IS  NOT NULL AND  TTHS.UNIT_CD IS NOT NULL THEN TTHS.HINMEI_CD+CAST(TTHS.UNIT_CD as varchar)
     ELSE '' END AS HINMEIUNIT
 , CASE WHEN TTHS.HINMEI_CD IS  NOT NULL AND  TTHS.KANSAN_UNIT_CD IS NOT NULL THEN TTHS.HINMEI_CD+CAST(TTHS.KANSAN_UNIT_CD as varchar)
	 ELSE '' END AS HINMEIKANSANUNIT
	,TTHS.KANSAN_UNIT_MOBILE_OUTPUT_FLG
	,null AS UR_SH_NUMBER_NUMERIC
	,TTHS.ANBUN_FLG
FROM
	T_TEIKI_HAISHA_DETAIL TTHD
	LEFT JOIN T_TEIKI_HAISHA_SHOUSAI TTHS
		ON TTHD.SYSTEM_ID = TTHS.SYSTEM_ID
		AND TTHD.SEQ = TTHS.SEQ
		AND TTHD.DETAIL_SYSTEM_ID = TTHS.DETAIL_SYSTEM_ID
		AND TTHD.TEIKI_HAISHA_NUMBER = TTHS.TEIKI_HAISHA_NUMBER
	LEFT JOIN M_GYOUSHA
		ON TTHD.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
	LEFT JOIN M_GENBA
		ON TTHD.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
		AND TTHD.GENBA_CD = M_GENBA.GENBA_CD
	LEFT JOIN M_HINMEI
		ON TTHS.HINMEI_CD = M_HINMEI.HINMEI_CD
	LEFT JOIN M_UNIT
		ON TTHS.UNIT_CD = M_UNIT.UNIT_CD
	LEFT JOIN M_UNIT AS UNITKANSAN
		ON TTHS.KANSAN_UNIT_CD = UNITKANSAN.UNIT_CD
WHERE
	TTHD.SYSTEM_ID = /*data.SystemId*/
	AND TTHD.SEQ = /*data.Seq*/
ORDER BY
    TTHD.ROW_NUMBER
	,TTHS.INPUT_KBN DESC
	,TTHS.HINMEI_CD
	,TTHS.UNIT_CD