SELECT 
	TEMP.DENPYOU_KBN_CD
	,TEMP.DENPYOU_KBN_COL
	,TEMP.KAKUTEI_KBN_COL
	,TEMP.DENPYOU_DATE_COL
	,TEMP.SHURUI_CD_COL
	,TEMP.SHURUI_NAME_COL
	,TEMP.HINMEI_CD_COL
	,TEMP.HINMEI_NAME_COL
	,TEMP.UNIT_CD_COL
	,TEMP.UNIT_NAME_COL
	,TEMP.TANKA_COL
FROM
	(SELECT
		DD.DENPYOU_KBN_CD
		,(CASE WHEN DD.DENPYOU_KBN_CD = 1 
			THEN '”„ã'
			ELSE 'Žx•¥'
		END) AS DENPYOU_KBN_COL
		,'' AS KAKUTEI_KBN_COL
		,EE.SAGYOU_DATE AS DENPYOU_DATE_COL
		,HM.SHURUI_CD AS SHURUI_CD_COL
		,MS.SHURUI_NAME AS SHURUI_NAME_COL
		,DD.HINMEI_CD AS HINMEI_CD_COL
		,HM.HINMEI_NAME_RYAKU AS HINMEI_NAME_COL
		,DD.UNIT_CD AS UNIT_CD_COL
		,MU.UNIT_NAME_RYAKU AS UNIT_NAME_COL
		,DD.TANKA AS TANKA_COL

	FROM T_UKETSUKE_MK_ENTRY AS EE
		LEFT JOIN T_UKETSUKE_MK_DETAIL AS DD ON EE.SYSTEM_ID = DD.SYSTEM_ID AND EE.SEQ = DD.SEQ
		LEFT JOIN M_HINMEI AS HM ON DD.HINMEI_CD = HM.HINMEI_CD
		LEFT JOIN M_UNIT AS MU ON DD.UNIT_CD = MU.UNIT_CD
		LEFT JOIN M_SHURUI AS MS ON HM.SHURUI_CD = MS.SHURUI_CD

	WHERE EE.DELETE_FLG = 0
	/*IF dto.KYOTEN_CD != null && dto.KYOTEN_CD != '' && dto.KYOTEN_CD != '99'*/
		AND EE.KYOTEN_CD = CONVERT(int, /*dto.KYOTEN_CD*/0)
	/*END*/
	/*IF dto.TORIHIKISAKI_CD != null && dto.TORIHIKISAKI_CD != ''*/
		AND EE.TORIHIKISAKI_CD = /*dto.TORIHIKISAKI_CD*/'000000'
	/*END*/
	/*IF dto.GYOUSHA_CD != null && dto.GYOUSHA_CD != ''*/
		AND EE.GYOUSHA_CD = /*dto.GYOUSHA_CD*/'000000'
	/*END*/
	/*IF dto.GENBA_CD != null && dto.GENBA_CD != ''*/
		AND EE.GENBA_CD = /*dto.GENBA_CD*/'000000'
	/*END*/
	/*IF dto.UNPAN_GYOUSHA_CD != null && dto.UNPAN_GYOUSHA_CD != ''*/
		AND EE.UNPAN_GYOUSHA_CD = /*dto.UNPAN_GYOUSHA_CD*/'000000'
	/*END*/
	/*IF dto.NIZUMI_GYOUSHA_CD != null && dto.NIZUMI_GYOUSHA_CD != ''*/
		AND EE.NIZUMI_GYOUSHA_CD = /*dto.NIZUMI_GYOUSHA_CD*/'000000'
	/*END*/
	/*IF dto.NIZUMI_GENBA_CD != null && dto.NIZUMI_GENBA_CD != ''*/
		AND EE.NIZUMI_GENBA_CD = /*dto.NIZUMI_GENBA_CD*/'000000'
	/*END*/
	/*IF dto.NIOROSHI_GYOUSHA_CD != null && dto.NIOROSHI_GYOUSHA_CD != ''*/
		AND EE.NIOROSHI_GYOUSHA_CD = /*dto.NIOROSHI_GYOUSHA_CD*/'000000'
	/*END*/
	/*IF dto.NIOROSHI_GENBA_CD != null && dto.NIOROSHI_GENBA_CD != ''*/
		AND EE.NIOROSHI_GENBA_CD = /*dto.NIOROSHI_GENBA_CD*/'000000'
	/*END*/
	/*IF !dto.HIDZUKE_FROM.IsNull*/
		AND EE.SAGYOU_DATE >= CONVERT(datetime, /*dto.HIDZUKE_FROM.Value*/'2020/01/01')
	/*END*/
	/*IF !dto.HIDZUKE_TO.IsNull*/
		AND EE.SAGYOU_DATE <= CONVERT(datetime, /*dto.HIDZUKE_TO.Value*/'2020/01/01')
	/*END*/
	/*IF dto.DENPYOU_KBN != null && dto.DENPYOU_KBN != ''*/
		/*IF dto.DENPYOU_KBN == '1'*/
			AND DD.DENPYOU_KBN_CD = 1
		/*END*/
		/*IF dto.DENPYOU_KBN == '2'*/
			AND DD.DENPYOU_KBN_CD = 2
		/*END*/
	/*END*/
	/*IF dto.HINMEI_CD != null && dto.HINMEI_CD != ''*/
		AND DD.HINMEI_CD = /*dto.HINMEI_CD*/'000000'
	/*END*/

	) AS TEMP
GROUP BY 
	TEMP.DENPYOU_KBN_CD
	,TEMP.DENPYOU_KBN_COL
	,TEMP.KAKUTEI_KBN_COL
	,TEMP.DENPYOU_DATE_COL
	,TEMP.SHURUI_CD_COL
	,TEMP.SHURUI_NAME_COL
	,TEMP.HINMEI_CD_COL
	,TEMP.HINMEI_NAME_COL
	,TEMP.UNIT_CD_COL
	,TEMP.UNIT_NAME_COL
	,TEMP.TANKA_COL
ORDER BY
	TEMP.DENPYOU_KBN_CD ASC
	,TEMP.DENPYOU_DATE_COL DESC
	,TEMP.HINMEI_CD_COL ASC
	,TEMP.HINMEI_NAME_COL ASC
	,TEMP.UNIT_CD_COL ASC