SELECT SYSTEM_ID
      ,SEQ
      ,KANRI_ID
      ,REC_SEQ
      ,MANIFEST_ID
      ,HST_GYOUSHA_CD
      ,HST_GENBA_CD
      ,HAIKI_SHURUI_CD
      ,CREATE_USER
      ,CREATE_DATE
      ,CREATE_PC
      ,UPDATE_USER
      ,UPDATE_DATE
      ,UPDATE_PC
      ,DELETE_FLG
      ,TIME_STAMP
FROM DT_R08_EX
WHERE SYSTEM_ID = /*data.SYSTEM_ID*/ 
AND SEQ <= /*data.SEQ*/ 
AND DELETE_FLG = 0
ORDER BY SYSTEM_ID, SEQ DESC, REC_SEQ