SELECT
  R18EX.SYSTEM_ID
 ,R18EX.SEQ
 ,R18EX.KANRI_ID
 ,R18EX.MANIFEST_ID
 ,R18EX.HST_GYOUSHA_CD
 ,R18EX.HST_GENBA_CD
 ,R18EX.SBN_GYOUSHA_CD
 ,R18EX.SBN_GENBA_CD
 ,R18EX.NO_REP_SBN_EDI_MEMBER_ID
 ,R18EX.SBN_HOUHOU_CD
 ,R18EX.HOUKOKU_TANTOUSHA_CD
 ,R18EX.SBN_TANTOUSHA_CD
 ,R18EX.UPN_TANTOUSHA_CD
 ,R18EX.SHARYOU_CD
 ,R18EX.KANSAN_SUU
 ,CREATE_DATA.CREATE_USER
 ,R18EX.CREATE_DATE
 ,R18EX.CREATE_PC
 ,R18EX.UPDATE_USER
 ,R18EX.UPDATE_DATE
 ,R18EX.UPDATE_PC
 ,R18EX.DELETE_FLG
 ,R18EX.TIME_STAMP
 ,R18EX.HAIKI_NAME_CD
 ,R18EX.GENNYOU_SUU
FROM 
  DT_R18_EX R18EX
 ,(
   SELECT
    R18EX.SYSTEM_ID
   ,R18EX.SEQ
   ,R18EX.KANRI_ID
   ,R18EX.CREATE_USER
   ,R18EX.CREATE_DATE
   ,R18EX.CREATE_PC
  FROM
   DT_R18_EX R18EX
   ,(SELECT
      SYSTEM_ID
     ,MIN(SEQ) MIN_SEQ
     FROM
      DT_R18_EX
     WHERE
      KANRI_ID = /*data.KANRI_ID*/
     GROUP BY 
      SYSTEM_ID
     ) SEQ_DATA
  WHERE
       R18EX.KANRI_ID = /*data.KANRI_ID*/
   AND R18EX.SYSTEM_ID = seq_data.SYSTEM_ID
   AND R18EX.SEQ = SEQ_DATA.MIN_SEQ
   ) CREATE_DATA
WHERE
     R18EX.KANRI_ID = /*data.KANRI_ID*/
 AND R18EX.SYSTEM_ID = CREATE_DATA.SYSTEM_ID
 AND R18EX.DELETE_FLG = 0
