SELECT MGYRSU.GENNYOURITSU 
		FROM M_GENNYOURITSU MGYRSU INNER JOIN M_DENSHI_HAIKI_SHURUI MDHS 
				ON MGYRSU.HOUKOKUSHO_BUNRUI_CD = MDHS.HOUKOKUSHO_BUNRUI_CD 
		WHERE MGYRSU.DELETE_FLG = 0 
		AND MDHS.HAIKI_SHURUI_CD = /*data.HAIKI_SHURUI_CD*//*END*/
		AND MGYRSU.HAIKI_NAME_CD = /*data.HAIKI_NAME_CD*//*END*/
		AND MGYRSU.SHOBUN_HOUHOU_CD = /*data.SHOBUN_HOUHOU_CD*//*END*/ 
