--最終処分終了報告
SELECT DISTINCT
    --管理番号
    DMT1.KANRI_ID,
    --最新SEQ
    DMT1.LATEST_SEQ,
    --R13 最終処分終了日・事業場情報.マニフェスト／予約番号
    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN DT_R13.MANIFEST_ID
        ELSE ME.MANIFEST_ID
    END AS MANIFEST_ID,
    --R13 最終処分終了日・事業場情報.最終処分事業場名称
    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN DT_R13.LAST_SBN_JOU_NAME
        ELSE M_GENBA.GENBA_NAME1
    END AS LAST_SBN_JOU_NAME,
    --R13 最終処分終了日・事業場情報.最終処分事業場所在地の郵便番号
    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN DT_R13.LAST_SBN_JOU_POST
        ELSE M_GENBA.GENBA_POST
    END AS LAST_SBN_JOU_POST,
    --R13 最終処分終了日・事業場情報.最終処分事業場所在地１
    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS1, '')
        ELSE ISNULL(M_TODOUFUKEN.TODOUFUKEN_NAME, '')
    END AS LAST_SBN_JOU_ADDRESS1,
    --R13 最終処分終了日・事業場情報.最終処分事業場所在地２
    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS2, '')
        ELSE ISNULL(M_GENBA.GENBA_ADDRESS1, '')
    END AS LAST_SBN_JOU_ADDRESS2,
    --R13 最終処分終了日・事業場情報.最終処分事業場所在地３
    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS3, '')
        ELSE ISNULL(M_GENBA.GENBA_ADDRESS2, '')
    END AS LAST_SBN_JOU_ADDRESS3,
    --R13 最終処分終了日・事業場情報.最終処分事業場所在地４
    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS4, '')
        ELSE ''
    END AS LAST_SBN_JOU_ADDRESS4,
    --R13 最終処分終了日・事業場情報.最終処分事業場電話番号
    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN DT_R13.LAST_SBN_JOU_TEL
        ELSE M_GENBA.GENBA_TEL
    END AS LAST_SBN_JOU_TEL,
    --R13 最終処分終了日・事業場情報.最終処分終了日
    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN CONVERT(VARCHAR, DT_R13.LAST_SBN_END_DATE, 112)
        ELSE CONVERT(VARCHAR, MD.LAST_SBN_END_DATE, 112)
    END AS LAST_SBN_END_DATE,
    -- 最終処分情報が重複除外されるのを防ぐ
    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN DT_R13.REC_SEQ
        ELSE MD.DETAIL_SYSTEM_ID
    END AS REC_SEQ,
    --システムID
    TMR2.NEXT_SYSTEM_ID AS SYSTEM_ID,
    --タイムスタンプ
    DMT1.UPDATE_TS,
    --状態フラグ
    DMT1.STATUS_FLAG,
    --状態詳細フラグ
    DMT1.STATUS_DETAIL,
    --修正/取消中SEQ
    DMT1.APPROVAL_SEQ

FROM
    --電子マニフェスト基本拡張
    DT_R18_EX
    --マニフェスト紐付　AS　マニフェスト紐付（１次）
    INNER JOIN T_MANIFEST_RELATION TMR1 ON TMR1.NEXT_SYSTEM_ID = DT_R18_EX.SYSTEM_ID AND TMR1.DELETE_FLG = 0
    --電子マニフェスト基本拡張（１次）
    INNER JOIN (
        SELECT
            DT_R18_EX.KANRI_ID,
            CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
                THEN DT_R18_MIX.DETAIL_SYSTEM_ID
                ELSE DT_R18_EX.SYSTEM_ID
            END
            AS SYSTEM_ID,
            CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
                THEN DT_R18_MIX.DELETE_FLG
                ELSE DT_R18_EX.DELETE_FLG
            END
            AS DELETE_FLG
        FROM
            DT_R18_EX
            LEFT JOIN DT_R18_MIX
            ON DT_R18_EX.SYSTEM_ID = DT_R18_MIX.SYSTEM_ID
            AND DT_R18_MIX.DELETE_FLG = 0
        WHERE
            DT_R18_EX.DELETE_FLG = 0
    ) AS R18_EX1 ON R18_EX1.SYSTEM_ID = TMR1.FIRST_SYSTEM_ID
                               AND TMR1.FIRST_HAIKI_KBN_CD = 4
                               AND R18_EX1.DELETE_FLG = 0
    --マニフェスト目次情報（１次）
    INNER JOIN DT_MF_TOC DMT1 ON DMT1.KANRI_ID = R18_EX1.KANRI_ID
	--
	INNER JOIN DT_R18 DT_R18_1 ON DT_R18_1.KANRI_ID = DMT1.KANRI_ID
	                          AND DT_R18_1.SEQ = DMT1.LATEST_SEQ

    -- 混廃振分データ取得(混廃じゃない場合はDT_R18_EXが一件取得される)
    LEFT JOIN
    (
        SELECT
            DT_R18_EX.KANRI_ID,
            CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
                THEN DT_R18_MIX.DETAIL_SYSTEM_ID
                ELSE DT_R18_EX.SYSTEM_ID
            END
            AS SYSTEM_ID,
            CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
                THEN DT_R18_MIX.SBN_ENDREP_KBN
                ELSE 1
            END
            AS SBN_ENDREP_KBN
        FROM
            DT_R18_EX
            LEFT JOIN DT_R18_MIX
            ON DT_R18_EX.SYSTEM_ID = DT_R18_MIX.SYSTEM_ID
            AND DT_R18_MIX.DELETE_FLG = 0
        WHERE
            DT_R18_EX.DELETE_FLG = 0
    )
    AS HURIWAKE_DATA
    ON DT_R18_1.KANRI_ID = HURIWAKE_DATA.KANRI_ID

    ----マニフェスト紐付　AS　マニフェスト紐付（２次）
    LEFT JOIN T_MANIFEST_RELATION TMR2 ON TMR2.FIRST_SYSTEM_ID = HURIWAKE_DATA.SYSTEM_ID
    AND TMR2.FIRST_HAIKI_KBN_CD = 4
    AND TMR2.DELETE_FLG = 0
    --電子マニフェスト基本拡張（２次）
    LEFT JOIN DT_R18_EX R18_EX2 ON R18_EX2.SYSTEM_ID = TMR2.NEXT_SYSTEM_ID
                               AND TMR2.NEXT_HAIKI_KBN_CD = 4
                               AND R18_EX2.DELETE_FLG = 0
    --マニフェスト目次情報（２次）
    LEFT JOIN DT_MF_TOC DMT2 ON DMT2.KANRI_ID = R18_EX2.KANRI_ID
    --マニフェスト情報
    LEFT JOIN DT_R18 DT_R18_2 ON DT_R18_2.KANRI_ID = DMT2.KANRI_ID
                              AND DT_R18_2.SEQ = DMT2.LATEST_SEQ
    --R13 最終処分終了日・事業場情報
    LEFT JOIN DT_R13 ON DT_R13.KANRI_ID = DT_R18_2.KANRI_ID
                     AND DT_R13.SEQ = DT_R18_2.SEQ
    --最終処分保留
    LEFT JOIN T_LAST_SBN_SUSPEND TLSS ON TLSS.SYSTEM_ID = TMR2.NEXT_SYSTEM_ID
                                     AND TLSS.DELETE_FLG = 0                             
    LEFT JOIN 
        (SELECT 
		     T_MANIFEST_ENTRY.*,
			 T_MANIFEST_DETAIL.DETAIL_SYSTEM_ID
	     FROM T_MANIFEST_ENTRY 
		 LEFT JOIN T_MANIFEST_DETAIL 
		        ON T_MANIFEST_DETAIL.SYSTEM_ID = T_MANIFEST_ENTRY.SYSTEM_ID
			   AND T_MANIFEST_DETAIL.SEQ = T_MANIFEST_ENTRY.SEQ) AS ME ON TMR2.NEXT_SYSTEM_ID = ME.DETAIL_SYSTEM_ID AND TMR2.NEXT_HAIKI_KBN_CD <> 4 AND ME.DELETE_FLG = 0
    LEFT JOIN T_MANIFEST_DETAIL AS MD ON ME.SYSTEM_ID = MD.SYSTEM_ID AND ME.SEQ = MD.SEQ
    LEFT JOIN M_GENBA ON MD.LAST_SBN_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND MD.LAST_SBN_GENBA_CD = M_GENBA.GENBA_CD AND M_GENBA.SAISHUU_SHOBUNJOU_KBN = 1
    LEFT JOIN M_TODOUFUKEN ON M_GENBA.GENBA_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD
WHERE DT_R18_EX.KANRI_ID = /*data.KANRI_ID*/
  AND DT_R18_EX.DELETE_FLG = 0
  AND (DT_R18_1.LAST_SBN_ENDREP_FLAG IS NULL OR DT_R18_1.LAST_SBN_ENDREP_FLAG = 0)
  AND HURIWAKE_DATA.SBN_ENDREP_KBN = 1
  AND TLSS.SYSTEM_ID IS NULL