SELECT KANRI_ID,QUE_SEQ,SEQ,REQUEST_CODE,EDI_RECORD_ID,FUNCTION_ID,UPN_ROUTE_NO,TUUCHI_ID,STATUS_FLAG,UPDATE_TS 
FROM QUE_INFO 
WHERE KANRI_ID = /*data.KANRI_ID*/ 
AND QUE_SEQ = (SELECT MAX(QUE_SEQ) FROM QUE_INFO WHERE KANRI_ID =/*data.KANRI_ID*/)
