SELECT
    REL.*
FROM
    (
        SELECT
            CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
            THEN DT_R18_MIX.DETAIL_SYSTEM_ID
            ELSE DT_R18_EX.SYSTEM_ID
            END AS SYSTEM_ID,
            DT_R18_EX.DELETE_FLG AS DELETE_FLG
        FROM
            DT_R18_EX
            LEFT JOIN DT_R18_MIX
            ON DT_R18_EX.SYSTEM_ID = DT_R18_MIX.SYSTEM_ID
            AND DT_R18_MIX.DELETE_FLG = 0
        WHERE
            DT_R18_EX.SYSTEM_ID = /*firstExSysId*/-1
    )AS EX
    INNER JOIN T_MANIFEST_RELATION AS REL
    ON EX.SYSTEM_ID = REL.FIRST_SYSTEM_ID AND REL.DELETE_FLG = 0 AND REL.FIRST_HAIKI_KBN_CD = 4
WHERE
    EX.DELETE_FLG = 0