SELECT 
    SHO.SHAIN_CD,
    SHO.SHOBUN_TANTOUSHA_BIKOU,
    SHO.CREATE_DATE,
    SHO.CREATE_USER,
    SHO.CREATE_PC,
    SHO.UPDATE_DATE,
    SHO.UPDATE_USER,
    SHO.UPDATE_PC,
    SHO.DELETE_FLG,
    SHO.TIME_STAMP,
	ISNULL(SHA.SHAIN_NAME, N'') AS SHAIN_NAME,
	ISNULL(SHA.SHAIN_FURIGANA, N'') AS SHAIN_FURIGANA,
	SHA.TEKIYOU_BEGIN,
	SHA.TEKIYOU_END
FROM 
    dbo.M_SHOBUN_TANTOUSHA SHO
    INNER JOIN dbo.M_SHAIN SHA ON SHA.SHAIN_CD = SHO.SHAIN_CD
/*BEGIN*/WHERE
 /*IF data.SHAIN_CD != null*/
 SHA.SHAIN_CD LIKE '%' + /*data.SHAIN_CD*/'000001' + '%'
 /*END*/
/*IF data.SHAIN_NAME != null*/AND SHA.SHAIN_NAME LIKE '%' +  /*data.SHAIN_NAME*/ + '%'/*END*/
/*IF data.SHAIN_FURIGANA != null*/AND SHA.SHAIN_FURIGANA LIKE '%' +  /*data.SHAIN_FURIGANA*/ + '%'/*END*/
/*IF data.CREATE_USER != null*/AND SHA.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, SHA.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
/*IF data.UPDATE_USER != null*/AND SHA.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, SHA.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*IF !deletechuFlg*/AND SHO.DELETE_FLG = /*deletechuFlg*/0/*END*/
/*END*/
ORDER BY SHO.SHAIN_CD
