SELECT * FROM dbo.M_DENSHI_KEIYAKU_SHANAI_KEIRO
WHERE 
/*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
 DELETE_FLG = 0
-- ELSE
 1 = 1
/*END*/
/*IF !data.DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD.IsNull*/AND DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = /*data.DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD.Value*//*END*/
/*IF !data.DENSHI_KEIYAKU_SHANAI_KEIRO_ROW_NO.IsNull*/AND DENSHI_KEIYAKU_SHANAI_KEIRO_ROW_NO = /*data.DENSHI_KEIYAKU_SHANAI_KEIRO_ROW_NO.Value*//*END*/
/*IF data.SHAIN_CD != null*/AND SHAIN_CD = /*data.SHAIN_CD*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
