SELECT M_BANK_SHITEN.BANK_CD
, M_BANK.BANK_NAME
, M_BANK.BANK_NAME_RYAKU
, M_BANK_SHITEN.BANK_SHITEN_CD
, M_BANK_SHITEN.BANK_SHITEN_NAME
, M_BANK_SHITEN.BANK_SHIETN_NAME_RYAKU
, M_BANK_SHITEN.KOUZA_SHURUI
, M_BANK_SHITEN.KOUZA_NO
, M_BANK_SHITEN.KOUZA_NAME
, M_BANK_SHITEN.BANK_SHIETN_NAME_RYAKU + ' / ' + M_BANK_SHITEN.KOUZA_NO + ' / ' + M_BANK_SHITEN.KOUZA_NAME AS BANK_SHITEN_INFO
FROM M_BANK
INNER JOIN M_BANK_SHITEN ON M_BANK.BANK_CD = M_BANK_SHITEN.BANK_CD
WHERE M_BANK.DELETE_FLG = 0
AND M_BANK_SHITEN.DELETE_FLG = 0
AND('' = /*data.BankCd*/ OR M_BANK_SHITEN.BANK_CD =  /*data.BankCd*/)
AND M_BANK_SHITEN.BANK_SHITEN_CD =  /*data.BankShitenCd*/
AND('' = /*data.KouzaShurui*/ OR M_BANK_SHITEN.KOUZA_SHURUI =  /*data.KouzaShurui*/)
AND('' = /*data.KouzaNo*/ OR M_BANK_SHITEN.KOUZA_NO =  /*data.KouzaNo*/)