SELECT
    MEISAI.DENPYOU_SHURUI_CD,
    MEISAI.DENPYOU_SHURUI,
    MEISAI.DENPYOU_KBN_CD,
    MEISAI.DENPYOU_KBN_NAME,
    MEISAI.KYOTEN_CD,
    MEISAI.KYOTEN_NAME_RYAKU,
    MEISAI.TORIHIKISAKI_CD,
    MEISAI.TORIHIKISAKI_NAME,
    MEISAI.GYOUSHA_CD,
    MEISAI.GYOUSHA_NAME,
    MEISAI.GENBA_CD,
    MEISAI.GENBA_NAME,
    MEISAI.UNPAN_GYOUSHA_CD,
    MEISAI.UNPAN_GYOUSHA_NAME,
    MEISAI.DENPYOU_DATE,
    MEISAI.URIAGE_DATE,
    MEISAI.SHIHARAI_DATE,
    CASE WHEN MEISAI.DENPYOU_KBN_CD = 1 THEN MEISAI.URIAGE_DATE
         WHEN MEISAI.DENPYOU_KBN_CD = 2 THEN MEISAI.SHIHARAI_DATE
    END URIAGE_SHIHARAI_DATE,
    MEISAI.DENPYOU_NUMBER,
    MEISAI.ROW_NO,
    MEISAI.URIAGE_TORIHIKI_KBN_CD,
    MEISAI.URIAGE_TORIHIKI_KBN,
    MEISAI.SHIHARAI_TORIHIKI_KBN_CD,
    MEISAI.SHIHARAI_TORIHIKI_KBN,
    CASE WHEN MEISAI.DENPYOU_KBN_CD = 1 THEN MEISAI.URIAGE_TORIHIKI_KBN_CD
         WHEN MEISAI.DENPYOU_KBN_CD = 2 THEN MEISAI.SHIHARAI_TORIHIKI_KBN_CD
    END TORIHIKI_KBN_CD,
    CASE WHEN MEISAI.DENPYOU_KBN_CD = 1 THEN MEISAI.URIAGE_TORIHIKI_KBN
         WHEN MEISAI.DENPYOU_KBN_CD = 2 THEN MEISAI.SHIHARAI_TORIHIKI_KBN
    END TORIHIKI_KBN,
    MEISAI.SEIKYU_SHIME,
    MEISAI.SEISAN_SHIME,
    CASE WHEN MEISAI.DENPYOU_KBN_CD = 1 THEN MEISAI.SEIKYU_SHIME
         WHEN MEISAI.DENPYOU_KBN_CD = 2 THEN MEISAI.SEISAN_SHIME
    END SHIME,
    MEISAI.DETAIL_KAKUTEI_KBN,
    MEISAI.KAKUTEI_KBN_NAME,
    MEISAI.HINMEI_CD,
    MEISAI.HINMEI_NAME,
    ISNULL(MEISAI.NET_JYUURYOU, 0) AS NET_JYUURYOU,
    ISNULL(MEISAI.SUURYOU, 0) AS SUURYOU,
    MEISAI.UNIT_CD,
    MEISAI.UNIT_NAME_RYAKU,
    MEISAI.TANKA,
    ISNULL(MEISAI.KINGAKU, 0) AS KINGAKU,
    ISNULL(MEISAI.HINMEI_KINGAKU, 0) AS HINMEI_KINGAKU,
    (ISNULL(MEISAI.KINGAKU, 0) + ISNULL(MEISAI.HINMEI_KINGAKU, 0)) AS SUM_KINGAKU,
    ISNULL(MEISAI.TAX_UCHI, 0) AS TAX_UCHI,
    ISNULL(MEISAI.HINMEI_TAX_UCHI, 0) AS HINMEI_TAX_UCHI,
    (ISNULL(MEISAI.KINGAKU, 0) + ISNULL(MEISAI.HINMEI_KINGAKU, 0)) - (ISNULL(MEISAI.TAX_UCHI, 0) + ISNULL(MEISAI.HINMEI_TAX_UCHI, 0)) AS ZEINUKI_KINGAKU,
    MEISAI.URIAGE_ZEI_KEISAN_KBN_CD,
    MEISAI.SHIHARAI_ZEI_KEISAN_KBN_CD,
    MEISAI.HINMEI_ZEI_KBN_CD,
    MEISAI.URIAGE_UCHIZEI,
    MEISAI.SHIHARAI_UCHIZEI,
    CASE WHEN MEISAI.DENPYOU_KBN_CD = 1 THEN MEISAI.URIAGE_UCHIZEI
         WHEN MEISAI.DENPYOU_KBN_CD = 2 THEN MEISAI.SHIHARAI_UCHIZEI
    END UCHIZEI
FROM (
    SELECT
        ENTRY.SYSTEM_ID,
        ENTRY.SEQ,
        ENTRY.TAIRYUU_KBN,
        ENTRY.KYOTEN_CD,
        (SELECT
             KYOTEN_NAME_RYAKU
         FROM
             M_KYOTEN
         WHERE
             KYOTEN_CD = ENTRY.KYOTEN_CD
             AND DELETE_FLG = 0)
         AS KYOTEN_NAME_RYAKU,
        ENTRY.UKEIRE_NUMBER AS DENPYOU_NUMBER,
        ENTRY.DATE_NUMBER,
        ENTRY.YEAR_NUMBER,
        ENTRY.KAKUTEI_KBN AS ENTRY_KAKUTEI_KBN,
        ENTRY.DENPYOU_DATE,
        ENTRY.URIAGE_DATE,
        ENTRY.SHIHARAI_DATE,
        ENTRY.TORIHIKISAKI_CD,
        ENTRY.TORIHIKISAKI_NAME,
        (SELECT
            TORIHIKISAKI_FURIGANA
         FROM
            M_TORIHIKISAKI
         WHERE
            TORIHIKISAKI_CD = ENTRY.TORIHIKISAKI_CD
             AND DELETE_FLG = 0)
         AS TORIHIKISAKI_FURIGANA,
        ENTRY.GYOUSHA_CD,
        ENTRY.GYOUSHA_NAME,
        (SELECT
            GYOUSHA_FURIGANA
         FROM
            M_GYOUSHA
         WHERE
            GYOUSHA_CD = ENTRY.GYOUSHA_CD
             AND DELETE_FLG = 0)
         AS GYOUSHA_FURIGANA,
        ENTRY.GENBA_CD,
        ENTRY.GENBA_NAME,
        NULL AS NIZUMI_GYOUSHA_CD,
        NULL AS NIZUMI_GYOUSHA_NAME,
        NULL AS NIZUMI_GENBA_CD,
        NULL AS NIZUMI_GENBA_NAME,
        ENTRY.NIOROSHI_GYOUSHA_CD,
        ENTRY.NIOROSHI_GYOUSHA_NAME,
        ENTRY.NIOROSHI_GENBA_CD,
        ENTRY.NIOROSHI_GENBA_NAME,
        ENTRY.EIGYOU_TANTOUSHA_CD,
        ENTRY.EIGYOU_TANTOUSHA_NAME,
        ENTRY.NYUURYOKU_TANTOUSHA_CD,
        ENTRY.NYUURYOKU_TANTOUSHA_NAME,
        ENTRY.SHARYOU_CD,
        ENTRY.SHARYOU_NAME,
        ENTRY.SHASHU_CD,
        ENTRY.SHASHU_NAME,
        ENTRY.UNPAN_GYOUSHA_CD,
        ENTRY.UNPAN_GYOUSHA_NAME,
        ENTRY.UNTENSHA_CD,
        ENTRY.UNTENSHA_NAME,
        ENTRY.NINZUU_CNT,
        ENTRY.KEITAI_KBN_CD,
        ENTRY.DAIKAN_KBN,
        ENTRY.CONTENA_SOUSA_CD,
        ENTRY.MANIFEST_SHURUI_CD,
        ENTRY.MANIFEST_TEHAI_CD,
        ENTRY.DENPYOU_BIKOU,
        ENTRY.TAIRYUU_BIKOU,
        ENTRY.UKETSUKE_NUMBER,
        ENTRY.KEIRYOU_NUMBER,
        ENTRY.RECEIPT_NUMBER,
        ENTRY.NET_TOTAL,
        ENTRY.URIAGE_SHOUHIZEI_RATE,
        ENTRY.URIAGE_KINGAKU_TOTAL,
        ENTRY.URIAGE_TAX_SOTO,
        ENTRY.URIAGE_TAX_UCHI,
        ENTRY.URIAGE_TAX_SOTO_TOTAL,
        ENTRY.URIAGE_TAX_UCHI_TOTAL,
        ENTRY.HINMEI_URIAGE_KINGAKU_TOTAL,
        ENTRY.HINMEI_URIAGE_TAX_SOTO_TOTAL,
        ENTRY.HINMEI_URIAGE_TAX_UCHI_TOTAL,
        ENTRY.SHIHARAI_SHOUHIZEI_RATE,
        ENTRY.SHIHARAI_KINGAKU_TOTAL,
        ENTRY.SHIHARAI_TAX_SOTO,
        ENTRY.SHIHARAI_TAX_UCHI,
        ENTRY.SHIHARAI_TAX_SOTO_TOTAL,
        ENTRY.SHIHARAI_TAX_UCHI_TOTAL,
        ENTRY.HINMEI_SHIHARAI_KINGAKU_TOTAL,
        ENTRY.HINMEI_SHIHARAI_TAX_SOTO_TOTAL,
        ENTRY.HINMEI_SHIHARAI_TAX_UCHI_TOTAL,
        ENTRY.URIAGE_ZEI_KEISAN_KBN_CD,
        ENTRY.URIAGE_ZEI_KBN_CD,
        ENTRY.URIAGE_TORIHIKI_KBN_CD,
        ENTRY.SHIHARAI_ZEI_KEISAN_KBN_CD,
        ENTRY.SHIHARAI_ZEI_KBN_CD,
        ENTRY.SHIHARAI_TORIHIKI_KBN_CD,
        NULL AS TSUKI_CREATE_KBN,
        NULL AS KENSHU_DATE,
        NULL AS SHUKKA_NET_TOTAL,
        NULL AS KENSHU_NET_TOTAL,
        NULL AS SABUN,
        NULL AS SHUKKA_KINGAKU_TOTAL,
        NULL AS KENSHU_KINGAKU_TOTAL,
        NULL AS SAGAKU,
        --ENTRY.CREATE_USER,
        ENTRY.CREATE_DATE,
        ENTRY.UPDATE_DATE,
        --ENTRY.CREATE_PC,
        --ENTRY.UPDATE_USER,
        --ENTRY.UPDATE_DATE,
        --ENTRY.UPDATE_PC,
        --ENTRY.DELETE_FLG,
        --ENTRY.TIME_STAMP,
        --DETAIL.SYSTEM_ID,
        --DETAIL.SEQ,
        DETAIL.DETAIL_SYSTEM_ID,
        --DETAIL.UKEIRE_NUMBER AS DENPYOU_NUMBER,
        DETAIL.ROW_NO,
        DETAIL.KAKUTEI_KBN AS DETAIL_KAKUTEI_KBN,
        DETAIL.URIAGESHIHARAI_DATE,
        DETAIL.STACK_JYUURYOU,
        DETAIL.EMPTY_JYUURYOU,
        DETAIL.WARIFURI_JYUURYOU,
        DETAIL.WARIFURI_PERCENT,
        DETAIL.CHOUSEI_JYUURYOU,
        DETAIL.CHOUSEI_PERCENT,
        DETAIL.YOUKI_CD,
        DETAIL.YOUKI_SUURYOU,
        DETAIL.YOUKI_JYUURYOU,
        DETAIL.DENPYOU_KBN_CD,
        DETAIL.HINMEI_CD,
        DETAIL.HINMEI_NAME,
        (SELECT
             SHURUI_CD
         FROM
             M_HINMEI
         WHERE
             HINMEI_CD = DETAIL.HINMEI_CD
		) AS SHURUI_CD,
        (SELECT
             BUNRUI_CD
         FROM
             M_HINMEI
         WHERE
             HINMEI_CD = DETAIL.HINMEI_CD
		) AS BUNRUI_CD,
        DETAIL.NET_JYUURYOU,
        DETAIL.SUURYOU,
        DETAIL.UNIT_CD,
        (SELECT
             UNIT_NAME_RYAKU
         FROM
             M_UNIT
         WHERE
             UNIT_CD = DETAIL.UNIT_CD
        ) AS UNIT_NAME_RYAKU,
        DETAIL.TANKA,
        DETAIL.KINGAKU,
        DETAIL.TAX_SOTO,
        DETAIL.TAX_UCHI,
        DETAIL.HINMEI_ZEI_KBN_CD,
        DETAIL.HINMEI_KINGAKU,
        DETAIL.HINMEI_TAX_SOTO,
        DETAIL.HINMEI_TAX_UCHI,
        DETAIL.MEISAI_BIKOU,
        DETAIL.NISUGATA_SUURYOU,
        DETAIL.NISUGATA_UNIT_CD,
        --DETAIL.TIME_STAMP,
        CASE
            WHEN DETAIL.DENPYOU_KBN_CD = 1 THEN '売上'
            WHEN DETAIL.DENPYOU_KBN_CD = 2 THEN '支払'
            ELSE NULL
        END DENPYOU_KBN_NAME,
        '1' AS DENPYOU_SHURUI_CD,
        '受入' AS DENPYOU_SHURUI,
        CASE
            WHEN ENTRY.URIAGE_TORIHIKI_KBN_CD = 1 THEN '現金'
            WHEN ENTRY.URIAGE_TORIHIKI_KBN_CD = 2 THEN '掛'
            ELSE NULL
        END URIAGE_TORIHIKI_KBN,
        CASE
            WHEN ENTRY.SHIHARAI_TORIHIKI_KBN_CD = 1 THEN '現金'
            WHEN ENTRY.SHIHARAI_TORIHIKI_KBN_CD = 2 THEN '掛'
            ELSE NULL
        END SHIHARAI_TORIHIKI_KBN,
        CASE
            WHEN DETAIL.DENPYOU_KBN_CD = 2 THEN NULL
            WHEN ENTRY.URIAGE_TORIHIKI_KBN_CD = 1 THEN '-'
            WHEN SEIKYUU.SEIKYUU_NUMBER IS NOT NULL THEN '済'
            ELSE '未'
        END SEIKYU_SHIME,
        CASE
            WHEN DETAIL.DENPYOU_KBN_CD = 1 THEN NULL
            WHEN ENTRY.SHIHARAI_TORIHIKI_KBN_CD = 1 THEN '-'
            WHEN SEISAN.SEISAN_NUMBER IS NOT NULL THEN '済'
            ELSE '未'
        END SEISAN_SHIME,
        CASE
            WHEN DETAIL.KAKUTEI_KBN = 1 THEN '確'
            WHEN DETAIL.KAKUTEI_KBN = 2 THEN '未'
            ELSE NULL
        END KAKUTEI_KBN_NAME,
        CASE
            WHEN ENTRY.URIAGE_ZEI_KBN_CD = 2 THEN '※'
            WHEN DETAIL.HINMEI_ZEI_KBN_CD = 2 THEN '※'
            ELSE NULL
        END URIAGE_UCHIZEI,
        CASE
            WHEN ENTRY.SHIHARAI_ZEI_KBN_CD = 2 THEN '※'
            WHEN DETAIL.HINMEI_ZEI_KBN_CD = 2 THEN '※'
            ELSE NULL
        END SHIHARAI_UCHIZEI
    FROM T_UKEIRE_ENTRY AS ENTRY
    JOIN T_UKEIRE_DETAIL AS DETAIL
        ON ENTRY.SYSTEM_ID = DETAIL.SYSTEM_ID
        AND ENTRY.SEQ = DETAIL.SEQ
        AND ENTRY.UKEIRE_NUMBER = DETAIL.UKEIRE_NUMBER
    LEFT JOIN (SELECT
        DENPYOU.SEIKYUU_NUMBER,
        DETAIL.DENPYOU_SYSTEM_ID,
        DETAIL.DENPYOU_SEQ,
        DETAIL.DETAIL_SYSTEM_ID,
        DETAIL.DENPYOU_NUMBER
    FROM T_SEIKYUU_DENPYOU AS DENPYOU
    JOIN T_SEIKYUU_DENPYOU_KAGAMI AS KAGAMI
        ON DENPYOU.SEIKYUU_NUMBER = KAGAMI.SEIKYUU_NUMBER
    JOIN T_SEIKYUU_DETAIL AS DETAIL
        ON KAGAMI.SEIKYUU_NUMBER = DETAIL.SEIKYUU_NUMBER
        AND KAGAMI.KAGAMI_NUMBER = DETAIL.KAGAMI_NUMBER
    WHERE DETAIL.DENPYOU_SHURUI_CD = 1
    AND DENPYOU.DELETE_FLG = 0) AS SEIKYUU
        ON SEIKYUU.DENPYOU_SYSTEM_ID = DETAIL.SYSTEM_ID
        AND SEIKYUU.DENPYOU_SEQ = DETAIL.SEQ
        AND SEIKYUU.DETAIL_SYSTEM_ID = DETAIL.DETAIL_SYSTEM_ID
        AND SEIKYUU.DENPYOU_NUMBER = DETAIL.UKEIRE_NUMBER
    LEFT JOIN (SELECT
        DENPYOU.SEISAN_NUMBER,
        DETAIL.DENPYOU_SYSTEM_ID,
        DETAIL.DENPYOU_SEQ,
        DETAIL.DETAIL_SYSTEM_ID,
        DETAIL.DENPYOU_NUMBER
    FROM T_SEISAN_DENPYOU AS DENPYOU
    JOIN T_SEISAN_DENPYOU_KAGAMI AS KAGAMI
        ON DENPYOU.SEISAN_NUMBER = KAGAMI.SEISAN_NUMBER
    JOIN T_SEISAN_DETAIL AS DETAIL
        ON KAGAMI.SEISAN_NUMBER = DETAIL.SEISAN_NUMBER
        AND KAGAMI.KAGAMI_NUMBER = DETAIL.KAGAMI_NUMBER
    WHERE DETAIL.DENPYOU_SHURUI_CD = 1
    AND DENPYOU.DELETE_FLG = 0) AS SEISAN
        ON SEISAN.DENPYOU_SYSTEM_ID = DETAIL.SYSTEM_ID
        AND SEISAN.DENPYOU_SEQ = DETAIL.SEQ
        AND SEISAN.DETAIL_SYSTEM_ID = DETAIL.DETAIL_SYSTEM_ID
        AND SEISAN.DENPYOU_NUMBER = DETAIL.UKEIRE_NUMBER
    WHERE ENTRY.DELETE_FLG = 0
    
    UNION ALL
    
    SELECT
        ENTRY.SYSTEM_ID,
        ENTRY.SEQ,
        ENTRY.TAIRYUU_KBN,
        ENTRY.KYOTEN_CD,
        (SELECT
             KYOTEN_NAME_RYAKU
         FROM
             M_KYOTEN
         WHERE
             KYOTEN_CD = ENTRY.KYOTEN_CD
             AND DELETE_FLG = 0)
         AS KYOTEN_NAME_RYAKU,
        ENTRY.SHUKKA_NUMBER AS DENPYOU_NUMBER,
        ENTRY.DATE_NUMBER,
        ENTRY.YEAR_NUMBER,
        ENTRY.KAKUTEI_KBN AS ENTRY_KAKUTEI_KBN,
        ENTRY.DENPYOU_DATE,
        ENTRY.URIAGE_DATE,
        ENTRY.SHIHARAI_DATE,
        ENTRY.TORIHIKISAKI_CD,
        ENTRY.TORIHIKISAKI_NAME,
        (SELECT
            TORIHIKISAKI_FURIGANA
         FROM
            M_TORIHIKISAKI
         WHERE
            TORIHIKISAKI_CD = ENTRY.TORIHIKISAKI_CD
             AND DELETE_FLG = 0)
         AS TORIHIKISAKI_FURIGANA,
        ENTRY.GYOUSHA_CD,
        ENTRY.GYOUSHA_NAME,
        (SELECT
            GYOUSHA_FURIGANA
         FROM
            M_GYOUSHA
         WHERE
            GYOUSHA_CD = ENTRY.GYOUSHA_CD
             AND DELETE_FLG = 0)
         AS GYOUSHA_FURIGANA,
        ENTRY.GENBA_CD,
        ENTRY.GENBA_NAME,
        ENTRY.NIZUMI_GYOUSHA_CD,
        ENTRY.NIZUMI_GYOUSHA_NAME,
        ENTRY.NIZUMI_GENBA_CD,
        ENTRY.NIZUMI_GENBA_NAME,
        NULL AS NIOROSHI_GYOUSHA_CD,
        NULL AS NIOROSHI_GYOUSHA_NAME,
        NULL AS NIOROSHI_GENBA_CD,
        NULL AS NIOROSHI_GENBA_NAME,
        ENTRY.EIGYOU_TANTOUSHA_CD,
        ENTRY.EIGYOU_TANTOUSHA_NAME,
        ENTRY.NYUURYOKU_TANTOUSHA_CD,
        ENTRY.NYUURYOKU_TANTOUSHA_NAME,
        ENTRY.SHARYOU_CD,
        ENTRY.SHARYOU_NAME,
        ENTRY.SHASHU_CD,
        ENTRY.SHASHU_NAME,
        ENTRY.UNPAN_GYOUSHA_CD,
        ENTRY.UNPAN_GYOUSHA_NAME,
        ENTRY.UNTENSHA_CD,
        ENTRY.UNTENSHA_NAME,
        ENTRY.NINZUU_CNT,
        ENTRY.KEITAI_KBN_CD,
        ENTRY.DAIKAN_KBN,
        ENTRY.CONTENA_SOUSA_CD,
        ENTRY.MANIFEST_SHURUI_CD,
        ENTRY.MANIFEST_TEHAI_CD,
        ENTRY.DENPYOU_BIKOU,
        ENTRY.TAIRYUU_BIKOU,
        ENTRY.UKETSUKE_NUMBER,
        ENTRY.KEIRYOU_NUMBER,
        ENTRY.RECEIPT_NUMBER,
        ENTRY.NET_TOTAL,
        ENTRY.URIAGE_SHOUHIZEI_RATE,
        ENTRY.URIAGE_AMOUNT_TOTAL AS URIAGE_KINGAKU_TOTAL,
        ENTRY.URIAGE_TAX_SOTO,
        ENTRY.URIAGE_TAX_UCHI,
        ENTRY.URIAGE_TAX_SOTO_TOTAL,
        ENTRY.URIAGE_TAX_UCHI_TOTAL,
        ENTRY.HINMEI_URIAGE_KINGAKU_TOTAL,
        ENTRY.HINMEI_URIAGE_TAX_SOTO_TOTAL,
        ENTRY.HINMEI_URIAGE_TAX_UCHI_TOTAL,
        ENTRY.SHIHARAI_SHOUHIZEI_RATE,
        ENTRY.SHIHARAI_AMOUNT_TOTAL AS SHIHARAI_KINGAKU_TOTAL,
        ENTRY.SHIHARAI_TAX_SOTO,
        ENTRY.SHIHARAI_TAX_UCHI,
        ENTRY.SHIHARAI_TAX_SOTO_TOTAL,
        ENTRY.SHIHARAI_TAX_UCHI_TOTAL,
        ENTRY.HINMEI_SHIHARAI_KINGAKU_TOTAL,
        ENTRY.HINMEI_SHIHARAI_TAX_SOTO_TOTAL,
        ENTRY.HINMEI_SHIHARAI_TAX_UCHI_TOTAL,
        ENTRY.URIAGE_ZEI_KEISAN_KBN_CD,
        ENTRY.URIAGE_ZEI_KBN_CD,
        ENTRY.URIAGE_TORIHIKI_KBN_CD,
        ENTRY.SHIHARAI_ZEI_KEISAN_KBN_CD,
        ENTRY.SHIHARAI_ZEI_KBN_CD,
        ENTRY.SHIHARAI_TORIHIKI_KBN_CD,
        NULL AS TSUKI_CREATE_KBN,
        ENTRY.KENSHU_DATE,
        ENTRY.SHUKKA_NET_TOTAL,
        ENTRY.KENSHU_NET_TOTAL,
        ENTRY.SABUN,
        ENTRY.SHUKKA_KINGAKU_TOTAL,
        ENTRY.KENSHU_KINGAKU_TOTAL,
        ENTRY.SAGAKU,
        --ENTRY.CREATE_USER,
        ENTRY.CREATE_DATE,
        ENTRY.UPDATE_DATE,
        --ENTRY.CREATE_PC,
        --ENTRY.UPDATE_USER,
        --ENTRY.UPDATE_DATE,
        --ENTRY.UPDATE_PC,
        --ENTRY.DELETE_FLG,
        --ENTRY.TIME_STAMP,
        --DETAIL.SYSTEM_ID,
        --DETAIL.SEQ,
        DETAIL.DETAIL_SYSTEM_ID,
        --DETAIL.SHUKKA_NUMBER AS DENPYOU_NUMBER,
        DETAIL.ROW_NO,
        DETAIL.KAKUTEI_KBN AS DETAIL_KAKUTEI_KBN,
        DETAIL.URIAGESHIHARAI_DATE,
        DETAIL.STACK_JYUURYOU,
        DETAIL.EMPTY_JYUURYOU,
        DETAIL.WARIFURI_JYUURYOU,
        DETAIL.WARIFURI_PERCENT,
        DETAIL.CHOUSEI_JYUURYOU,
        DETAIL.CHOUSEI_PERCENT,
        DETAIL.YOUKI_CD,
        DETAIL.YOUKI_SUURYOU,
        DETAIL.YOUKI_JYUURYOU,
        DETAIL.DENPYOU_KBN_CD,
        DETAIL.HINMEI_CD,
        DETAIL.HINMEI_NAME,
        (SELECT
             SHURUI_CD
         FROM
             M_HINMEI
         WHERE
             HINMEI_CD = DETAIL.HINMEI_CD
        ) AS SHURUI_CD,
        (SELECT
             BUNRUI_CD
         FROM
             M_HINMEI
         WHERE
             HINMEI_CD = DETAIL.HINMEI_CD
        ) AS BUNRUI_CD,
        DETAIL.NET_JYUURYOU,
        DETAIL.SUURYOU,
        DETAIL.UNIT_CD,
        (SELECT
             UNIT_NAME_RYAKU
         FROM
             M_UNIT
         WHERE
             UNIT_CD = DETAIL.UNIT_CD
        ) AS UNIT_NAME_RYAKU,
        DETAIL.TANKA,
        DETAIL.KINGAKU,
        DETAIL.TAX_SOTO,
        DETAIL.TAX_UCHI,
        DETAIL.HINMEI_ZEI_KBN_CD,
        DETAIL.HINMEI_KINGAKU,
        DETAIL.HINMEI_TAX_SOTO,
        DETAIL.HINMEI_TAX_UCHI,
        DETAIL.MEISAI_BIKOU,
        DETAIL.NISUGATA_SUURYOU,
        DETAIL.NISUGATA_UNIT_CD,
        --DETAIL.TIME_STAMP,
        CASE
            WHEN DETAIL.DENPYOU_KBN_CD = 1 THEN '売上'
            WHEN DETAIL.DENPYOU_KBN_CD = 2 THEN '支払'
            ELSE NULL
        END DENPYOU_KBN_NAME,
        '2' AS DENPYOU_SHURUI_CD,
        '出荷' AS DENPYOU_SHURUI,
        CASE
            WHEN ENTRY.URIAGE_TORIHIKI_KBN_CD = 1 THEN '現金'
            WHEN ENTRY.URIAGE_TORIHIKI_KBN_CD = 2 THEN '掛'
            ELSE NULL
        END URIAGE_TORIHIKI_KBN,
        CASE
            WHEN ENTRY.SHIHARAI_TORIHIKI_KBN_CD = 1 THEN '現金'
            WHEN ENTRY.SHIHARAI_TORIHIKI_KBN_CD = 2 THEN '掛'
            ELSE NULL
        END SHIHARAI_TORIHIKI_KBN,
        CASE
            WHEN DETAIL.DENPYOU_KBN_CD = 2 THEN NULL
            WHEN ENTRY.URIAGE_TORIHIKI_KBN_CD = 1 THEN '-'
            WHEN SEIKYUU.SEIKYUU_NUMBER IS NOT NULL THEN '済'
            ELSE '未'
        END SEIKYU_SHIME,
        CASE
            WHEN DETAIL.DENPYOU_KBN_CD = 1 THEN NULL
            WHEN ENTRY.SHIHARAI_TORIHIKI_KBN_CD = 1 THEN '-'
            WHEN SEISAN.SEISAN_NUMBER IS NOT NULL THEN '済'
            ELSE '未'
        END SEISAN_SHIME,
        CASE
            WHEN DETAIL.KAKUTEI_KBN = 1 THEN '確'
            WHEN DETAIL.KAKUTEI_KBN = 2 THEN '未'
            ELSE NULL
        END KAKUTEI_KBN_NAME,
        CASE
            WHEN ENTRY.URIAGE_ZEI_KBN_CD = 2 THEN '※'
            WHEN DETAIL.HINMEI_ZEI_KBN_CD = 2 THEN '※'
            ELSE NULL
        END URIAGE_UCHIZEI,
        CASE
            WHEN ENTRY.SHIHARAI_ZEI_KBN_CD = 2 THEN '※'
            WHEN DETAIL.HINMEI_ZEI_KBN_CD = 2 THEN '※'
            ELSE NULL
        END SHIHARAI_UCHIZEI
    FROM T_SHUKKA_ENTRY AS ENTRY
    JOIN T_SHUKKA_DETAIL AS DETAIL
        ON ENTRY.SYSTEM_ID = DETAIL.SYSTEM_ID
        AND ENTRY.SEQ = DETAIL.SEQ
        AND ENTRY.SHUKKA_NUMBER = DETAIL.SHUKKA_NUMBER
    LEFT JOIN (SELECT
        DENPYOU.SEIKYUU_NUMBER,
        DETAIL.DENPYOU_SYSTEM_ID,
        DETAIL.DENPYOU_SEQ,
        DETAIL.DETAIL_SYSTEM_ID,
        DETAIL.DENPYOU_NUMBER
    FROM T_SEIKYUU_DENPYOU AS DENPYOU
    JOIN T_SEIKYUU_DENPYOU_KAGAMI AS KAGAMI
        ON DENPYOU.SEIKYUU_NUMBER = KAGAMI.SEIKYUU_NUMBER
    JOIN T_SEIKYUU_DETAIL AS DETAIL
        ON KAGAMI.SEIKYUU_NUMBER = DETAIL.SEIKYUU_NUMBER
        AND KAGAMI.KAGAMI_NUMBER = DETAIL.KAGAMI_NUMBER
    WHERE DETAIL.DENPYOU_SHURUI_CD = 2
    AND DENPYOU.DELETE_FLG = 0) AS SEIKYUU
        ON SEIKYUU.DENPYOU_SYSTEM_ID = DETAIL.SYSTEM_ID
        AND SEIKYUU.DENPYOU_SEQ = DETAIL.SEQ
        AND SEIKYUU.DETAIL_SYSTEM_ID = DETAIL.DETAIL_SYSTEM_ID
        AND SEIKYUU.DENPYOU_NUMBER = DETAIL.SHUKKA_NUMBER
    LEFT JOIN (SELECT
        DENPYOU.SEISAN_NUMBER,
        DETAIL.DENPYOU_SYSTEM_ID,
        DETAIL.DENPYOU_SEQ,
        DETAIL.DETAIL_SYSTEM_ID,
        DETAIL.DENPYOU_NUMBER
    FROM T_SEISAN_DENPYOU AS DENPYOU
    JOIN T_SEISAN_DENPYOU_KAGAMI AS KAGAMI
        ON DENPYOU.SEISAN_NUMBER = KAGAMI.SEISAN_NUMBER
    JOIN T_SEISAN_DETAIL AS DETAIL
        ON KAGAMI.SEISAN_NUMBER = DETAIL.SEISAN_NUMBER
        AND KAGAMI.KAGAMI_NUMBER = DETAIL.KAGAMI_NUMBER
    WHERE DETAIL.DENPYOU_SHURUI_CD = 2
    AND DENPYOU.DELETE_FLG = 0) AS SEISAN
        ON SEISAN.DENPYOU_SYSTEM_ID = DETAIL.SYSTEM_ID
        AND SEISAN.DENPYOU_SEQ = DETAIL.SEQ
        AND SEISAN.DETAIL_SYSTEM_ID = DETAIL.DETAIL_SYSTEM_ID
        AND SEISAN.DENPYOU_NUMBER = DETAIL.SHUKKA_NUMBER
    WHERE ENTRY.DELETE_FLG = 0
    AND ( ENTRY.KENSHU_MUST_KBN = 0 OR ENTRY.KENSHU_MUST_KBN IS NULL)

    UNION ALL

    SELECT
        ENTRY.SYSTEM_ID,
        ENTRY.SEQ,
        ENTRY.TAIRYUU_KBN,
        ENTRY.KYOTEN_CD,
        (SELECT
             KYOTEN_NAME_RYAKU
         FROM
             M_KYOTEN
         WHERE
             KYOTEN_CD = ENTRY.KYOTEN_CD
             AND DELETE_FLG = 0)
         AS KYOTEN_NAME_RYAKU,
        ENTRY.SHUKKA_NUMBER AS DENPYOU_NUMBER,
        ENTRY.DATE_NUMBER,
        ENTRY.YEAR_NUMBER,
        ENTRY.KAKUTEI_KBN AS ENTRY_KAKUTEI_KBN,
        ENTRY.KENSHU_DATE AS DENPYOU_DATE,
        ENTRY.KENSHU_URIAGE_DATE AS URIAGE_DATE,
        ENTRY.KENSHU_SHIHARAI_DATE AS SHIHARAI_DATE,
        ENTRY.TORIHIKISAKI_CD,
        ENTRY.TORIHIKISAKI_NAME,
        (SELECT
            TORIHIKISAKI_FURIGANA
         FROM
            M_TORIHIKISAKI
         WHERE
            TORIHIKISAKI_CD = ENTRY.TORIHIKISAKI_CD
             AND DELETE_FLG = 0)
         AS TORIHIKISAKI_FURIGANA,
        ENTRY.GYOUSHA_CD,
        ENTRY.GYOUSHA_NAME,
        (SELECT
            GYOUSHA_FURIGANA
         FROM
            M_GYOUSHA
         WHERE
            GYOUSHA_CD = ENTRY.GYOUSHA_CD
             AND DELETE_FLG = 0)
         AS GYOUSHA_FURIGANA,
        ENTRY.GENBA_CD,
        ENTRY.GENBA_NAME,
        ENTRY.NIZUMI_GYOUSHA_CD,
        ENTRY.NIZUMI_GYOUSHA_NAME,
        ENTRY.NIZUMI_GENBA_CD,
        ENTRY.NIZUMI_GENBA_NAME,
        NULL AS NIOROSHI_GYOUSHA_CD,
        NULL AS NIOROSHI_GYOUSHA_NAME,
        NULL AS NIOROSHI_GENBA_CD,
        NULL AS NIOROSHI_GENBA_NAME,
        ENTRY.EIGYOU_TANTOUSHA_CD,
        ENTRY.EIGYOU_TANTOUSHA_NAME,
        ENTRY.NYUURYOKU_TANTOUSHA_CD,
        ENTRY.NYUURYOKU_TANTOUSHA_NAME,
        ENTRY.SHARYOU_CD,
        ENTRY.SHARYOU_NAME,
        ENTRY.SHASHU_CD,
        ENTRY.SHASHU_NAME,
        ENTRY.UNPAN_GYOUSHA_CD,
        ENTRY.UNPAN_GYOUSHA_NAME,
        ENTRY.UNTENSHA_CD,
        ENTRY.UNTENSHA_NAME,
        ENTRY.NINZUU_CNT,
        ENTRY.KEITAI_KBN_CD,
        ENTRY.DAIKAN_KBN,
        ENTRY.CONTENA_SOUSA_CD,
        ENTRY.MANIFEST_SHURUI_CD,
        ENTRY.MANIFEST_TEHAI_CD,
        ENTRY.DENPYOU_BIKOU,
        ENTRY.TAIRYUU_BIKOU,
        ENTRY.UKETSUKE_NUMBER,
        ENTRY.KEIRYOU_NUMBER,
        ENTRY.RECEIPT_NUMBER,
        ENTRY.KENSHU_NET_TOTAL AS NET_TOTAL,
        ENTRY.KENSHU_URIAGE_SHOUHIZEI_RATE AS URIAGE_SHOUHIZEI_RATE,
        ENTRY.KENSHU_URIAGE_AMOUNT_TOTAL AS URIAGE_KINGAKU_TOTAL,
        ENTRY.KENSHU_URIAGE_TAX_SOTO AS URIAGE_TAX_SOTO,
        ENTRY.KENSHU_URIAGE_TAX_UCHI AS URIAGE_TAX_UCHI,
        ENTRY.KENSHU_URIAGE_TAX_SOTO_TOTAL AS URIAGE_TAX_SOTO_TOTAL,
        ENTRY.KENSHU_URIAGE_TAX_UCHI_TOTAL AS URIAGE_TAX_UCHI_TOTAL,
        ENTRY.KENSHU_HINMEI_URIAGE_KINGAKU_TOTAL AS HINMEI_URIAGE_KINGAKU_TOTAL,
        ENTRY.KENSHU_HINMEI_URIAGE_TAX_SOTO_TOTAL AS HINMEI_URIAGE_TAX_SOTO_TOTAL,
        ENTRY.KENSHU_HINMEI_URIAGE_TAX_UCHI_TOTAL AS HINMEI_URIAGE_TAX_UCHI_TOTAL,
        ENTRY.KENSHU_SHIHARAI_SHOUHIZEI_RATE AS SHIHARAI_SHOUHIZEI_RATE,
        ENTRY.KENSHU_SHIHARAI_AMOUNT_TOTAL AS SHIHARAI_KINGAKU_TOTAL,
        ENTRY.KENSHU_SHIHARAI_TAX_SOTO AS SHIHARAI_TAX_SOTO,
        ENTRY.KENSHU_SHIHARAI_TAX_UCHI AS SHIHARAI_TAX_UCHI,
        ENTRY.KENSHU_SHIHARAI_TAX_SOTO_TOTAL AS SHIHARAI_TAX_SOTO_TOTAL,
        ENTRY.KENSHU_SHIHARAI_TAX_UCHI_TOTAL AS SHIHARAI_TAX_UCHI_TOTAL,
        ENTRY.KENSHU_HINMEI_SHIHARAI_KINGAKU_TOTAL AS HINMEI_SHIHARAI_KINGAKU_TOTAL,
        ENTRY.KENSHU_HINMEI_SHIHARAI_TAX_SOTO_TOTAL AS HINMEI_SHIHARAI_TAX_SOTO_TOTAL,
        ENTRY.KENSHU_HINMEI_SHIHARAI_TAX_UCHI_TOTAL AS HINMEI_SHIHARAI_TAX_UCHI_TOTAL,
        ENTRY.URIAGE_ZEI_KEISAN_KBN_CD,
        ENTRY.URIAGE_ZEI_KBN_CD,
        ENTRY.URIAGE_TORIHIKI_KBN_CD,
        ENTRY.SHIHARAI_ZEI_KEISAN_KBN_CD,
        ENTRY.SHIHARAI_ZEI_KBN_CD,
        ENTRY.SHIHARAI_TORIHIKI_KBN_CD,
        NULL AS TSUKI_CREATE_KBN,
        ENTRY.KENSHU_DATE,
        ENTRY.SHUKKA_NET_TOTAL,
        ENTRY.KENSHU_NET_TOTAL,
        ENTRY.SABUN,
        ENTRY.SHUKKA_KINGAKU_TOTAL,
        ENTRY.KENSHU_KINGAKU_TOTAL,
        ENTRY.SAGAKU,
        --ENTRY.CREATE_USER,
        ENTRY.CREATE_DATE,
        ENTRY.UPDATE_DATE,
        --ENTRY.CREATE_PC,
        --ENTRY.UPDATE_USER,
        --ENTRY.UPDATE_DATE,
        --ENTRY.UPDATE_PC,
        --ENTRY.DELETE_FLG,
        --ENTRY.TIME_STAMP,
        --DETAIL.SYSTEM_ID,
        --DETAIL.SEQ,
        DETAIL.DETAIL_SYSTEM_ID,
        --DETAIL.SHUKKA_NUMBER AS DENPYOU_NUMBER,
        DETAIL.KENSHU_ROW_NO AS ROW_NO,
        -- 検収明細に無いため親の確定区分を使用
        ENTRY.KAKUTEI_KBN AS DETAIL_KAKUTEI_KBN,
        NULL AS URIAGESHIHARAI_DATE,
        NULL AS STACK_JYUURYOU,
        NULL AS EMPTY_JYUURYOU,
        NULL AS WARIFURI_JYUURYOU,
        NULL AS WARIFURI_PERCENT,
        DETAIL.BUBIKI AS CHOUSEI_JYUURYOU,
        NULL AS CHOUSEI_PERCENT,
        NULL AS YOUKI_CD,
        NULL AS YOUKI_SUURYOU,
        NULL AS YOUKI_JYUURYOU,
        DETAIL.DENPYOU_KBN_CD,
        DETAIL.HINMEI_CD,
        DETAIL.HINMEI_NAME,
        (SELECT
             SHURUI_CD
         FROM
             M_HINMEI
         WHERE
             HINMEI_CD = DETAIL.HINMEI_CD
        ) AS SHURUI_CD,
        (SELECT
             BUNRUI_CD
         FROM
             M_HINMEI
         WHERE
             HINMEI_CD = DETAIL.HINMEI_CD
        ) AS BUNRUI_CD,
        DETAIL.NET_JYUURYOU,
        DETAIL.SUURYOU,
        DETAIL.UNIT_CD,
        (SELECT
             UNIT_NAME_RYAKU
         FROM
             M_UNIT
         WHERE
             UNIT_CD = DETAIL.UNIT_CD
        ) AS UNIT_NAME_RYAKU,
        DETAIL.TANKA,
        DETAIL.KINGAKU,
        DETAIL.TAX_SOTO,
        DETAIL.TAX_UCHI,
        DETAIL.HINMEI_ZEI_KBN_CD,
        DETAIL.HINMEI_KINGAKU,
        DETAIL.HINMEI_TAX_SOTO,
        DETAIL.HINMEI_TAX_UCHI,
        NULL AS MEISAI_BIKOU,
        NULL AS NISUGATA_SUURYOU,
        NULL AS NISUGATA_UNIT_CD,
        --DETAIL.TIME_STAMP,
        CASE
            WHEN DETAIL.DENPYOU_KBN_CD = 1 THEN '売上'
            WHEN DETAIL.DENPYOU_KBN_CD = 2 THEN '支払'
            ELSE NULL
        END DENPYOU_KBN_NAME,
        '2' AS DENPYOU_SHURUI_CD,
        '出荷' AS DENPYOU_SHURUI,
        CASE
            WHEN ENTRY.URIAGE_TORIHIKI_KBN_CD = 1 THEN '現金'
            WHEN ENTRY.URIAGE_TORIHIKI_KBN_CD = 2 THEN '掛'
            ELSE NULL
        END URIAGE_TORIHIKI_KBN,
        CASE
            WHEN ENTRY.SHIHARAI_TORIHIKI_KBN_CD = 1 THEN '現金'
            WHEN ENTRY.SHIHARAI_TORIHIKI_KBN_CD = 2 THEN '掛'
            ELSE NULL
        END SHIHARAI_TORIHIKI_KBN,
        CASE
            WHEN DETAIL.DENPYOU_KBN_CD = 2 THEN NULL
            WHEN ENTRY.URIAGE_TORIHIKI_KBN_CD = 1 THEN '-'
			WHEN EXISTS
				(
					SELECT * FROM 
						(
							SELECT
								DENPYOU.SEIKYUU_NUMBER,
								DETAIL.DENPYOU_SYSTEM_ID,
								DETAIL.DENPYOU_SEQ,
								DETAIL.DETAIL_SYSTEM_ID,
								DETAIL.DENPYOU_NUMBER
							FROM T_SEIKYUU_DENPYOU AS DENPYOU
							JOIN T_SEIKYUU_DENPYOU_KAGAMI AS KAGAMI
								ON DENPYOU.SEIKYUU_NUMBER = KAGAMI.SEIKYUU_NUMBER
							JOIN T_SEIKYUU_DETAIL AS DETAIL
								ON KAGAMI.SEIKYUU_NUMBER = DETAIL.SEIKYUU_NUMBER
								AND KAGAMI.KAGAMI_NUMBER = DETAIL.KAGAMI_NUMBER
							WHERE DETAIL.DENPYOU_SHURUI_CD = 2
								AND DENPYOU.DELETE_FLG = 0
						) AS SEIKYUU
					WHERE SEIKYUU.DENPYOU_SYSTEM_ID = DETAIL.SYSTEM_ID
					AND SEIKYUU.DENPYOU_SEQ = DETAIL.SEQ
					AND SEIKYUU.DETAIL_SYSTEM_ID = DETAIL.DETAIL_SYSTEM_ID
					AND SEIKYUU.DENPYOU_NUMBER = DETAIL.SHUKKA_NUMBER
				) THEN '済'
            ELSE '未'
        END SEIKYU_SHIME,
        CASE
            WHEN DETAIL.DENPYOU_KBN_CD = 1 THEN NULL
            WHEN ENTRY.SHIHARAI_TORIHIKI_KBN_CD = 1 THEN '-'
			WHEN EXISTS
				(
					SELECT * FROM 
						(
							SELECT
								DENPYOU.SEISAN_NUMBER,
								DETAIL.DENPYOU_SYSTEM_ID,
								DETAIL.DENPYOU_SEQ,
								DETAIL.DETAIL_SYSTEM_ID,
								DETAIL.DENPYOU_NUMBER
							FROM T_SEISAN_DENPYOU AS DENPYOU
							JOIN T_SEISAN_DENPYOU_KAGAMI AS KAGAMI
								ON DENPYOU.SEISAN_NUMBER = KAGAMI.SEISAN_NUMBER
							JOIN T_SEISAN_DETAIL AS DETAIL
								ON KAGAMI.SEISAN_NUMBER = DETAIL.SEISAN_NUMBER
								AND KAGAMI.KAGAMI_NUMBER = DETAIL.KAGAMI_NUMBER
							WHERE DETAIL.DENPYOU_SHURUI_CD = 2
								AND DENPYOU.DELETE_FLG = 0
						) AS SEISAN
					WHERE SEISAN.DENPYOU_SYSTEM_ID = DETAIL.SYSTEM_ID
					AND SEISAN.DENPYOU_SEQ = DETAIL.SEQ
					AND SEISAN.DETAIL_SYSTEM_ID = DETAIL.DETAIL_SYSTEM_ID
					AND SEISAN.DENPYOU_NUMBER = DETAIL.SHUKKA_NUMBER
				) THEN '済'
            ELSE '未'
		END SEISAN_SHIME,
        CASE
            WHEN ENTRY.KAKUTEI_KBN = 1 THEN '確'
            WHEN ENTRY.KAKUTEI_KBN = 2 THEN '未'
            ELSE NULL
        END KAKUTEI_KBN_NAME,
        CASE
            WHEN ENTRY.URIAGE_ZEI_KBN_CD = 2 THEN '※'
            WHEN DETAIL.HINMEI_ZEI_KBN_CD = 2 THEN '※'
            ELSE NULL
        END URIAGE_UCHIZEI,
        CASE
            WHEN ENTRY.SHIHARAI_ZEI_KBN_CD = 2 THEN '※'
            WHEN DETAIL.HINMEI_ZEI_KBN_CD = 2 THEN '※'
            ELSE NULL
        END SHIHARAI_UCHIZEI
    FROM T_SHUKKA_ENTRY AS ENTRY
    JOIN (SELECT
        KENSHU_DETAIL.SYSTEM_ID,
        KENSHU_DETAIL.SEQ,
        KENSHU_DETAIL.DETAIL_SYSTEM_ID,
        KENSHU_DETAIL.KENSHU_SYSTEM_ID,
        KENSHU_DETAIL.SHUKKA_NUMBER,
        KENSHU_DETAIL.ROW_NO,
        KENSHU_DETAIL.KENSHU_ROW_NO,
        KENSHU_DETAIL.DENPYOU_KBN_CD,
        KENSHU_DETAIL.HINMEI_CD,
        KENSHU_DETAIL.HINMEI_NAME,
        KENSHU_DETAIL.KENSHU_NET AS NET_JYUURYOU,
        KENSHU_DETAIL.BUBIKI,
        KENSHU_DETAIL.KENSHU_NET,
        KENSHU_DETAIL.SUURYOU,
        KENSHU_DETAIL.UNIT_CD,
        KENSHU_DETAIL.TANKA,
        KENSHU_DETAIL.KINGAKU,
        KENSHU_DETAIL.TAX_SOTO,
        KENSHU_DETAIL.TAX_UCHI,
        KENSHU_DETAIL.HINMEI_ZEI_KBN_CD,
        KENSHU_DETAIL.HINMEI_KINGAKU,
        KENSHU_DETAIL.HINMEI_TAX_SOTO,
        KENSHU_DETAIL.HINMEI_TAX_UCHI
    FROM
        T_SHUKKA_DETAIL SHUKKA_DETAIL
        INNER JOIN T_KENSHU_DETAIL KENSHU_DETAIL
            ON SHUKKA_DETAIL.SYSTEM_ID = KENSHU_DETAIL.SYSTEM_ID
            AND SHUKKA_DETAIL.SEQ = KENSHU_DETAIL.SEQ
            AND SHUKKA_DETAIL.DETAIL_SYSTEM_ID = KENSHU_DETAIL.DETAIL_SYSTEM_ID
    ) AS DETAIL
        ON ENTRY.SYSTEM_ID = DETAIL.SYSTEM_ID
        AND ENTRY.SEQ = DETAIL.SEQ
        AND ENTRY.SHUKKA_NUMBER = DETAIL.SHUKKA_NUMBER
    WHERE ENTRY.DELETE_FLG = 0
    AND ENTRY.KENSHU_MUST_KBN = 1
    AND ENTRY.KENSHU_DATE IS NOT NULL
    
    -- UNION ALL
    
    -- SELECT
    --     ENTRY.SYSTEM_ID,
    --     ENTRY.SEQ,
    --     NULL AS TAIRYUU_KBN,
    --     ENTRY.KYOTEN_CD,
    --     (SELECT
    --          KYOTEN_NAME_RYAKU
    --      FROM
    --          M_KYOTEN
    --      WHERE
    --          KYOTEN_CD = ENTRY.KYOTEN_CD
    --          AND DELETE_FLG = 0)
    --      AS KYOTEN_NAME_RYAKU,
    --     ENTRY.UR_SH_NUMBER AS DENPYOU_NUMBER,
    --     ENTRY.DATE_NUMBER,
    --     ENTRY.YEAR_NUMBER,
    --     ENTRY.KAKUTEI_KBN AS ENTRY_KAKUTEI_KBN,
    --     ENTRY.DENPYOU_DATE,
    --     ENTRY.URIAGE_DATE,
    --     ENTRY.SHIHARAI_DATE,
    --     ENTRY.TORIHIKISAKI_CD,
    --     ENTRY.TORIHIKISAKI_NAME,
    --     (SELECT
    --         TORIHIKISAKI_FURIGANA
    --      FROM
    --         M_TORIHIKISAKI
    --      WHERE
    --         TORIHIKISAKI_CD = ENTRY.TORIHIKISAKI_CD
    --          AND DELETE_FLG = 0)
    --      AS TORIHIKISAKI_FURIGANA,
    --     ENTRY.GYOUSHA_CD,
    --     ENTRY.GYOUSHA_NAME,
    --     (SELECT
    --         GYOUSHA_FURIGANA
    --      FROM
    --         M_GYOUSHA
    --      WHERE
    --         GYOUSHA_CD = ENTRY.GYOUSHA_CD
    --          AND DELETE_FLG = 0)
    --      AS GYOUSHA_FURIGANA,
    --     ENTRY.GENBA_CD,
    --     ENTRY.GENBA_NAME,
    --     ENTRY.NIZUMI_GYOUSHA_CD,
    --     ENTRY.NIZUMI_GYOUSHA_NAME,
    --     ENTRY.NIZUMI_GENBA_CD,
    --     ENTRY.NIZUMI_GENBA_NAME,
    --     ENTRY.NIOROSHI_GYOUSHA_CD,
    --     ENTRY.NIOROSHI_GYOUSHA_NAME,
    --     ENTRY.NIOROSHI_GENBA_CD,
    --     ENTRY.NIOROSHI_GENBA_NAME,
    --     ENTRY.EIGYOU_TANTOUSHA_CD,
    --     ENTRY.EIGYOU_TANTOUSHA_NAME,
    --     ENTRY.NYUURYOKU_TANTOUSHA_CD,
    --     ENTRY.NYUURYOKU_TANTOUSHA_NAME,
    --     ENTRY.SHARYOU_CD,
    --     ENTRY.SHARYOU_NAME,
    --     ENTRY.SHASHU_CD,
    --     ENTRY.SHASHU_NAME,
    --     ENTRY.UNPAN_GYOUSHA_CD,
    --     ENTRY.UNPAN_GYOUSHA_NAME,
    --     ENTRY.UNTENSHA_CD,
    --     ENTRY.UNTENSHA_NAME,
    --     ENTRY.NINZUU_CNT,
    --     ENTRY.KEITAI_KBN_CD,
    --     NULL AS DAIKAN_KBN,
    --     ENTRY.CONTENA_SOUSA_CD,
    --     ENTRY.MANIFEST_SHURUI_CD,
    --     ENTRY.MANIFEST_TEHAI_CD,
    --     ENTRY.DENPYOU_BIKOU,
    --     NULL AS TAIRYUU_BIKOU,
    --     ENTRY.UKETSUKE_NUMBER,
    --     NULL AS KEIRYOU_NUMBER,
    --     ENTRY.RECEIPT_NUMBER,
    --     NULL AS NET_TOTAL,
    --     ENTRY.URIAGE_SHOUHIZEI_RATE,
    --     ENTRY.URIAGE_AMOUNT_TOTAL AS URIAGE_KINGAKU_TOTAL,
    --     ENTRY.URIAGE_TAX_SOTO,
    --     ENTRY.URIAGE_TAX_UCHI,
    --     ENTRY.URIAGE_TAX_SOTO_TOTAL,
    --     ENTRY.URIAGE_TAX_UCHI_TOTAL,
    --     ENTRY.HINMEI_URIAGE_KINGAKU_TOTAL,
    --     ENTRY.HINMEI_URIAGE_TAX_SOTO_TOTAL,
    --     ENTRY.HINMEI_URIAGE_TAX_UCHI_TOTAL,
    --     ENTRY.SHIHARAI_SHOUHIZEI_RATE,
    --     ENTRY.SHIHARAI_AMOUNT_TOTAL AS SHIHARAI_KINGAKU_TOTAL,
    --     ENTRY.SHIHARAI_TAX_SOTO,
    --     ENTRY.SHIHARAI_TAX_UCHI,
    --     ENTRY.SHIHARAI_TAX_SOTO_TOTAL,
    --     ENTRY.SHIHARAI_TAX_UCHI_TOTAL,
    --     ENTRY.HINMEI_SHIHARAI_KINGAKU_TOTAL,
    --     ENTRY.HINMEI_SHIHARAI_TAX_SOTO_TOTAL,
    --     ENTRY.HINMEI_SHIHARAI_TAX_UCHI_TOTAL,
    --     ENTRY.URIAGE_ZEI_KEISAN_KBN_CD,
    --     ENTRY.URIAGE_ZEI_KBN_CD,
    --     ENTRY.URIAGE_TORIHIKI_KBN_CD,
    --     ENTRY.SHIHARAI_ZEI_KEISAN_KBN_CD,
    --     ENTRY.SHIHARAI_ZEI_KBN_CD,
    --     ENTRY.SHIHARAI_TORIHIKI_KBN_CD,
    --     ENTRY.TSUKI_CREATE_KBN,
    --     NULL AS KENSHU_DATE,
    --     NULL AS SHUKKA_NET_TOTAL,
    --     NULL AS KENSHU_NET_TOTAL,
    --     NULL AS SABUN,
    --     NULL AS SHUKKA_KINGAKU_TOTAL,
    --     NULL AS KENSHU_KINGAKU_TOTAL,
    --     NULL AS SAGAKU,
    --     --ENTRY.CREATE_USER,
    --     ENTRY.CREATE_DATE,
    --     --ENTRY.CREATE_PC,
    --     --ENTRY.UPDATE_USER,
    --     --ENTRY.UPDATE_DATE,
    --     --ENTRY.UPDATE_PC,
    --     --ENTRY.DELETE_FLG,
    --     --ENTRY.TIME_STAMP,
    --     --DETAIL.SYSTEM_ID,
    --     --DETAIL.SEQ,
    --     DETAIL.DETAIL_SYSTEM_ID,
    --     --DETAIL.UR_SH_NUMBER AS DENPYOU_NUMBER,
    --     DETAIL.ROW_NO,
    --     DETAIL.KAKUTEI_KBN AS DETAIL_KAKUTEI_KBN,
    --     DETAIL.URIAGESHIHARAI_DATE,
    --     NULL AS STACK_JYUURYOU,
    --     NULL AS EMPTY_JYUURYOU,
    --     NULL AS WARIFURI_JYUURYOU,
    --     NULL AS WARIFURI_PERCENT,
    --     NULL AS CHOUSEI_JYUURYOU,
    --     NULL AS CHOUSEI_PERCENT,
    --     NULL AS YOUKI_CD,
    --     NULL AS YOUKI_SUURYOU,
    --     NULL AS YOUKI_JYUURYOU,
    --     DETAIL.DENPYOU_KBN_CD,
    --     DETAIL.HINMEI_CD,
    --     DETAIL.HINMEI_NAME,
    --     (SELECT
    --          SHURUI_CD
    --      FROM
    --          M_HINMEI
    --      WHERE
    --          HINMEI_CD = DETAIL.HINMEI_CD
    --          AND DELETE_FLG = 0)
    --      AS SHURUI_CD,
    --     (SELECT
    --          BUNRUI_CD
    --      FROM
    --          M_HINMEI
    --      WHERE
    --          HINMEI_CD = DETAIL.HINMEI_CD
    --          AND DELETE_FLG = 0)
    --      AS BUNRUI_CD,
    --     NULL AS NET_JYUURYOU,
    --     DETAIL.SUURYOU,
    --     DETAIL.UNIT_CD,
    --     (SELECT
    --          UNIT_NAME_RYAKU
    --      FROM
    --          M_UNIT
    --      WHERE
    --          UNIT_CD = DETAIL.UNIT_CD
    --          AND DELETE_FLG = 0)
    --     AS UNIT_NAME_RYAKU,
    --     DETAIL.TANKA,
    --     DETAIL.KINGAKU,
    --     DETAIL.TAX_SOTO,
    --     DETAIL.TAX_UCHI,
    --     DETAIL.HINMEI_ZEI_KBN_CD,
    --     DETAIL.HINMEI_KINGAKU,
    --     DETAIL.HINMEI_TAX_SOTO,
    --     DETAIL.HINMEI_TAX_UCHI,
    --     DETAIL.MEISAI_BIKOU,
    --     DETAIL.NISUGATA_SUURYOU,
    --     DETAIL.NISUGATA_UNIT_CD,
    --     --DETAIL.TIME_STAMP,
    --     CASE
    --         WHEN DETAIL.DENPYOU_KBN_CD = 1 THEN '売上'
    --         WHEN DETAIL.DENPYOU_KBN_CD = 2 THEN '支払'
    --         ELSE NULL
    --     END DENPYOU_KBN_NAME,
    --     '3' AS DENPYOU_SHURUI_CD,
    --     '売支' AS DENPYOU_SHURUI,
    --     CASE
    --         WHEN ENTRY.URIAGE_TORIHIKI_KBN_CD = 1 THEN '現金'
    --         WHEN ENTRY.URIAGE_TORIHIKI_KBN_CD = 2 THEN '掛'
    --         ELSE NULL
    --     END URIAGE_TORIHIKI_KBN,
    --     CASE
    --         WHEN ENTRY.SHIHARAI_TORIHIKI_KBN_CD = 1 THEN '現金'
    --         WHEN ENTRY.SHIHARAI_TORIHIKI_KBN_CD = 2 THEN '掛'
    --         ELSE NULL
    --     END SHIHARAI_TORIHIKI_KBN,
    --     CASE
    --         WHEN DETAIL.DENPYOU_KBN_CD = 2 THEN NULL
    --         WHEN ENTRY.URIAGE_TORIHIKI_KBN_CD = 1 THEN '-'
    --         WHEN SEIKYUU.SEIKYUU_NUMBER IS NOT NULL THEN '済'
    --         ELSE '未'
    --     END SEIKYU_SHIME,
    --     CASE
    --         WHEN DETAIL.DENPYOU_KBN_CD = 1 THEN NULL
    --         WHEN ENTRY.SHIHARAI_TORIHIKI_KBN_CD = 1 THEN '-'
    --         WHEN SEISAN.SEISAN_NUMBER IS NOT NULL THEN '済'
    --         ELSE '未'
    --     END SEISAN_SHIME,
    --     CASE
    --         WHEN DETAIL.KAKUTEI_KBN = 1 THEN '確'
    --         WHEN DETAIL.KAKUTEI_KBN = 2 THEN '未'
    --         ELSE NULL
    --     END KAKUTEI_KBN_NAME,
    --     CASE
    --         WHEN ENTRY.URIAGE_ZEI_KBN_CD = 2 THEN '※'
    --         WHEN DETAIL.HINMEI_ZEI_KBN_CD = 2 THEN '※'
    --         ELSE NULL
    --     END URIAGE_UCHIZEI,
    --     CASE
    --         WHEN ENTRY.SHIHARAI_ZEI_KBN_CD = 2 THEN '※'
    --         WHEN DETAIL.HINMEI_ZEI_KBN_CD = 2 THEN '※'
    --         ELSE NULL
    --     END SHIHARAI_UCHIZEI
    -- FROM T_UR_SH_ENTRY AS ENTRY
    -- JOIN T_UR_SH_DETAIL AS DETAIL
    --     ON ENTRY.SYSTEM_ID = DETAIL.SYSTEM_ID
    --     AND ENTRY.SEQ = DETAIL.SEQ
    --     AND ENTRY.UR_SH_NUMBER = DETAIL.UR_SH_NUMBER
    -- LEFT JOIN (SELECT
    --     DENPYOU.SEIKYUU_NUMBER,
    --     DETAIL.DENPYOU_SYSTEM_ID,
    --     DETAIL.DENPYOU_SEQ,
    --     DETAIL.DETAIL_SYSTEM_ID,
    --     DETAIL.DENPYOU_NUMBER
    -- FROM T_SEIKYUU_DENPYOU AS DENPYOU
    -- JOIN T_SEIKYUU_DENPYOU_KAGAMI AS KAGAMI
    --     ON DENPYOU.SEIKYUU_NUMBER = KAGAMI.SEIKYUU_NUMBER
    -- JOIN T_SEIKYUU_DETAIL AS DETAIL
    --     ON KAGAMI.SEIKYUU_NUMBER = DETAIL.SEIKYUU_NUMBER
    --     AND KAGAMI.KAGAMI_NUMBER = DETAIL.KAGAMI_NUMBER
    -- WHERE DETAIL.DENPYOU_SHURUI_CD = 3
    -- AND DENPYOU.DELETE_FLG = 0) AS SEIKYUU
    --     ON SEIKYUU.DENPYOU_SYSTEM_ID = DETAIL.SYSTEM_ID
    --     AND SEIKYUU.DENPYOU_SEQ = DETAIL.SEQ
    --     AND SEIKYUU.DETAIL_SYSTEM_ID = DETAIL.DETAIL_SYSTEM_ID
    --     AND SEIKYUU.DENPYOU_NUMBER = DETAIL.UR_SH_NUMBER
    -- LEFT JOIN (SELECT
    --     DENPYOU.SEISAN_NUMBER,
    --     DETAIL.DENPYOU_SYSTEM_ID,
    --     DETAIL.DENPYOU_SEQ,
    --     DETAIL.DETAIL_SYSTEM_ID,
    --     DETAIL.DENPYOU_NUMBER
    -- FROM T_SEISAN_DENPYOU AS DENPYOU
    -- JOIN T_SEISAN_DENPYOU_KAGAMI AS KAGAMI
    --     ON DENPYOU.SEISAN_NUMBER = KAGAMI.SEISAN_NUMBER
    -- JOIN T_SEISAN_DETAIL AS DETAIL
    --     ON KAGAMI.SEISAN_NUMBER = DETAIL.SEISAN_NUMBER
    --     AND KAGAMI.KAGAMI_NUMBER = DETAIL.KAGAMI_NUMBER
    -- WHERE DETAIL.DENPYOU_SHURUI_CD = 3
    -- AND DENPYOU.DELETE_FLG = 0) AS SEISAN
    --     ON SEISAN.DENPYOU_SYSTEM_ID = DETAIL.SYSTEM_ID
    --     AND SEISAN.DENPYOU_SEQ = DETAIL.SEQ
    --     AND SEISAN.DETAIL_SYSTEM_ID = DETAIL.DETAIL_SYSTEM_ID
    --     AND SEISAN.DENPYOU_NUMBER = DETAIL.UR_SH_NUMBER
    -- WHERE ENTRY.DELETE_FLG = 0
) AS MEISAI
WHERE
    1 = 1
    -- 拠点
    /*IF dto.KyotenCd != null && dto.KyotenCd != 99 */AND MEISAI.KYOTEN_CD = /*dto.KyotenCd*/'99'/*END*/
    -- 入力担当者
    /*IF dto.NyuuryokuTantoushaCd != null && dto.NyuuryokuTantoushaCd != ''*/AND (MEISAI.NYUURYOKU_TANTOUSHA_CD = /*dto.NyuuryokuTantoushaCd*/'999999' OR MEISAI.NYUURYOKU_TANTOUSHA_CD IS NULL)/*END*/
    -- 伝票種類
    /*IF dto.DenpyouShuruiCd != '4'*/AND MEISAI.DENPYOU_SHURUI_CD = /*dto.DenpyouShuruiCd*/9/*END*/
    -- 伝票日付
    /*IF dto.DateShuruiCd != null && dto.DateShuruiCd == 1*/AND MEISAI.DENPYOU_DATE >= /*dto.DateFrom*/'2014/01/01' AND MEISAI.DENPYOU_DATE <= /*dto.DateTo*/'2014/01/01'/*END*/
    -- 入力日付
    /*IF dto.DateShuruiCd != null && dto.DateShuruiCd == 2*/AND CONVERT(date, MEISAI.UPDATE_DATE, 111) >= /*dto.DateFrom*/'2014/01/01' AND CONVERT(date, MEISAI.UPDATE_DATE, 111) <= /*dto.DateTo*/'2014/01/02'/*END*/
    -- 業者
    /*IF dto.GyoushaCdFrom != null && dto.GyoushaCdFrom != ''*/AND MEISAI.GYOUSHA_CD >= /*dto.GyoushaCdFrom*/'000000'/*END*/
    /*IF dto.GyoushaCdTo != null && dto.GyoushaCdTo != ''*/AND MEISAI.GYOUSHA_CD <= /*dto.GyoushaCdTo*/'000000'/*END*/
    -- 現場
    /*IF dto.GenbaCdFrom != null && dto.GenbaCdFrom != ''*/AND MEISAI.GENBA_CD >= /*dto.GenbaCdFrom*/'000000'/*END*/
    /*IF dto.GenbaCdTo != null && dto.GenbaCdTo != ''*/AND MEISAI.GENBA_CD <= /*dto.GenbaCdTo*/'000000'/*END*/
    -- 運搬業者
    /*IF dto.UnpanGyoushaCdFrom != null && dto.UnpanGyoushaCdFrom != ''*/AND MEISAI.UNPAN_GYOUSHA_CD >= /*dto.UnpanGyoushaCdFrom*/'000000'/*END*/
    /*IF dto.UnpanGyoushaCdTo != null && dto.UnpanGyoushaCdTo != ''*/AND MEISAI.UNPAN_GYOUSHA_CD <= /*dto.UnpanGyoushaCdTo*/'000000'/*END*/
    -- 形態区分
    /*IF dto.KeitaiKbnFrom != null && dto.KeitaiKbnFrom != ''*/AND MEISAI.KEITAI_KBN_CD >= /*dto.KeitaiKbnFrom*/0/*END*/
    /*IF dto.KeitaiKbnTo != null && dto.KeitaiKbnTo != ''*/AND MEISAI.KEITAI_KBN_CD <= /*dto.KeitaiKbnTo*/0/*END*/
    -- 品名
    /*IF dto.HinmeiCdFrom != null && dto.HinmeiCdFrom != ''*/AND MEISAI.HINMEI_CD >= /*dto.HinmeiCdFrom*/'000000'/*END*/
    /*IF dto.HinmeiCdTo != null && dto.HinmeiCdTo != ''*/AND MEISAI.HINMEI_CD <= /*dto.HinmeiCdTo*/'000000'/*END*/
    -- 種類
    /*IF dto.ShuruiCdFrom != null && dto.ShuruiCdFrom != ''*/AND MEISAI.SHURUI_CD >= /*dto.ShuruiCdFrom*/'000000'/*END*/
    /*IF dto.ShuruiCdTo != null && dto.ShuruiCdTo != ''*/AND MEISAI.SHURUI_CD <= /*dto.ShuruiCdTo*/'000000'/*END*/
    -- 分類
    /*IF dto.BunruiCdFrom != null && dto.BunruiCdFrom != ''*/AND MEISAI.BUNRUI_CD >= /*dto.BunruiCdFrom*/'000000'/*END*/
    /*IF dto.BunruiCdTo != null && dto.BunruiCdTo != ''*/AND MEISAI.BUNRUI_CD <= /*dto.BunruiCdTo*/'000000'/*END*/
    AND MEISAI.TAIRYUU_KBN = 0
ORDER BY
    -- 業者CD順
    /*IF dto.Order == 1*/
    MEISAI.GYOUSHA_CD,
    MEISAI.GYOUSHA_NAME,
    MEISAI.GENBA_CD,
    MEISAI.GENBA_NAME,
    MEISAI.UNPAN_GYOUSHA_CD,
    MEISAI.UNPAN_GYOUSHA_NAME,
    MEISAI.DENPYOU_DATE,
    MEISAI.DENPYOU_NUMBER,
    MEISAI.ROW_NO
    /*END*/
    -- 業者フリガナ順
    /*IF dto.Order == 2*/
    MEISAI.GYOUSHA_FURIGANA,
    MEISAI.GYOUSHA_CD,
    MEISAI.GYOUSHA_NAME,
    MEISAI.GENBA_CD,
    MEISAI.GENBA_NAME,
    MEISAI.UNPAN_GYOUSHA_CD,
    MEISAI.UNPAN_GYOUSHA_NAME,
    MEISAI.DENPYOU_DATE,
    MEISAI.DENPYOU_NUMBER,
    MEISAI.ROW_NO
    /*END*/
    -- 伝票日付順
    /*IF dto.Order == 3*/
    MEISAI.DENPYOU_DATE,
    MEISAI.DENPYOU_SHURUI,
    MEISAI.DENPYOU_NUMBER,
    MEISAI.ROW_NO,
    MEISAI.GYOUSHA_CD,
    MEISAI.GENBA_CD
    /*END*/
    -- 伝票種類順
    /*IF dto.Order == 4*/
    MEISAI.DENPYOU_SHURUI,
    MEISAI.DENPYOU_NUMBER,
    MEISAI.DENPYOU_DATE,
    MEISAI.ROW_NO,
    MEISAI.GYOUSHA_CD,
    MEISAI.GENBA_CD
    /*END*/
