SELECT * FROM dbo.M_SHIKUCHOUSON
WHERE 
/*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
 DELETE_FLG = 0
-- ELSE
 1 = 1
/*END*/
/*IF data.SHIKUCHOUSON_CD != null*/AND SHIKUCHOUSON_CD = /*data.SHIKUCHOUSON_CD*//*END*/
/*IF data.SHIKUCHOUSON_NAME != null*/AND SHIKUCHOUSON_NAME = /*data.SHIKUCHOUSON_NAME*//*END*/
/*IF data.SHIKUCHOUSON_NAME_RYAKU != null*/AND SHIKUCHOUSON_NAME_RYAKU = /*data.SHIKUCHOUSON_NAME_RYAKU*//*END*/
/*IF data.SHIKUCHOUSON_FURIGANA != null*/AND SHIKUCHOUSON_FURIGANA = /*data.SHIKUCHOUSON_FURIGANA*//*END*/
/*IF data.SHIKUCHOUSON_BIKOU != null*/AND SHIKUCHOUSON_BIKOU = /*data.SHIKUCHOUSON_BIKOU*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
