SELECT DISTINCT N'廃棄種類マスタ' AS NAME FROM M_HAIKI_SHURUI WHERE HAIKI_KBN_CD IN /*HAIKI_KBN_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'混合種類マスタ' AS NAME FROM M_KONGOU_SHURUI WHERE HAIKI_KBN_CD IN /*HAIKI_KBN_CD*/('') AND DELETE_FLG = 'False'
