SELECT GYOUSHA_CD,GENBA_CD,ZAIKO_HINMEI_CD, SUM(ZAIKO_RYOU) AS ZAIKO_RYOU FROM
(
    --受入量
    SELECT NIOROSHI_GYOUSHA_CD AS GYOUSHA_CD,NIOROSHI_GENBA_CD AS GENBA_CD,ZAIKO_HINMEI_CD,SUM(ZAIKO_RYOU) AS ZAIKO_RYOU FROM T_UKEIRE_ENTRY TUE
    INNER JOIN T_UKEIRE_DETAIL TUD 
    ON TUE.SYSTEM_ID = TUD.SYSTEM_ID
    AND TUE.SEQ = TUD.SEQ
    INNER JOIN T_ZAIKO_HINMEI_HURIWAKE MZH
    ON MZH.SYSTEM_ID = TUD.SYSTEM_ID
    AND MZH.SEQ = TUD.SEQ
    AND MZH.DETAIL_SYSTEM_ID = TUD.DETAIL_SYSTEM_ID
	AND MZH.DENSHU_KBN_CD = 1
    WHERE TUE.NIOROSHI_GYOUSHA_CD = /*gyoushaCd*/
    AND TUE.NIOROSHI_GENBA_CD = /*genbaCd*/
    AND MZH.ZAIKO_HINMEI_CD = /*zaikoHinmeiCd*/
    /*IF !dateFrom.IsNull*/
    AND TUE.DENPYOU_DATE >= /*dateFrom*/
    /*END*/
    AND TUE.DENPYOU_DATE <= /*dateTo*/
    AND TUE.DELETE_FLG = 0
	AND TUE.KAKUTEI_KBN = 1
	AND TUE.TAIRYUU_KBN = 0
    GROUP BY NIOROSHI_GYOUSHA_CD,NIOROSHI_GENBA_CD,ZAIKO_HINMEI_CD
    
    UNION 

    --出荷量
    SELECT NIZUMI_GYOUSHA_CD AS GYOUSHA_CD,NIZUMI_GENBA_CD AS GENBA_CD,ZAIKO_HINMEI_CD,SUM(ZAIKO_RYOU)*-1 AS ZAIKO_RYOU FROM T_SHUKKA_ENTRY TSE
    INNER JOIN T_SHUKKA_DETAIL TSD 
    ON TSE.SYSTEM_ID = TSD.SYSTEM_ID
    AND TSE.SEQ = TSD.SEQ
    INNER JOIN T_ZAIKO_HINMEI_HURIWAKE MZH
    ON MZH.SYSTEM_ID = TSD.SYSTEM_ID
    AND MZH.SEQ = TSD.SEQ
    AND MZH.DETAIL_SYSTEM_ID = TSD.DETAIL_SYSTEM_ID
	AND MZH.DENSHU_KBN_CD = 2
    WHERE TSE.NIZUMI_GYOUSHA_CD = /*gyoushaCd*/
    AND TSE.NIZUMI_GENBA_CD = /*genbaCd*/
    AND MZH.ZAIKO_HINMEI_CD = /*zaikoHinmeiCd*/
    /*IF !dateFrom.IsNull*/
    AND TSE.DENPYOU_DATE >= /*dateFrom*/
    /*END*/
    AND TSE.DENPYOU_DATE <= /*dateTo*/
    AND TSE.DELETE_FLG = 0
	AND TSE.KAKUTEI_KBN = 1
	AND TSE.TAIRYUU_KBN = 0
    GROUP BY NIZUMI_GYOUSHA_CD,NIZUMI_GENBA_CD,ZAIKO_HINMEI_CD
    
    UNION 

    --調整量
    SELECT GYOUSHA_CD,GENBA_CD,ZAIKO_HINMEI_CD,SUM(TYOUSEI_RYOU) AS ZAIKO_RYOU FROM T_ZAIKO_TYOUSEI_ENTRY TZTE
    INNER JOIN T_ZAIKO_TYOUSEI_DETAIL TZTD
    ON TZTE.SYSTEM_ID = TZTD.SYSTEM_ID
    AND TZTE.SEQ = TZTD.SEQ
    WHERE TZTE.GYOUSHA_CD = /*gyoushaCd*/
    AND TZTE.GENBA_CD = /*genbaCd*/
    AND TZTD.ZAIKO_HINMEI_CD = /*zaikoHinmeiCd*/
    /*IF !dateFrom.IsNull*/
    AND TZTE.TYOUSEI_DATE >= /*dateFrom*/
    /*END*/
    AND TZTE.TYOUSEI_DATE <= /*dateTo*/
    GROUP BY GYOUSHA_CD,GENBA_CD,ZAIKO_HINMEI_CD
    
    UNION 

    --移動量
    --該当現場から移動する移動量
    SELECT TZIE.GYOUSHA_CD,TZIE.GENBA_CD,TZIE.ZAIKO_HINMEI_CD,SUM(TZID.IDOU_RYOU)*-1 AS ZAIKO_RYOU  FROM T_ZAIKO_IDOU_ENTRY TZIE
    INNER JOIN T_ZAIKO_IDOU_DETAIL TZID
    ON TZIE.SYSTEM_ID = TZID.SYSTEM_ID
    AND TZIE.SEQ = TZID.SEQ
    WHERE TZIE.GYOUSHA_CD = /*gyoushaCd*/
    AND TZIE.GENBA_CD = /*genbaCd*/
    AND TZIE.ZAIKO_HINMEI_CD = /*zaikoHinmeiCd*/
    /*IF !dateFrom.IsNull*/
    AND TZIE.IDOU_DATE >= /*dateFrom*/
    /*END*/
    AND TZIE.IDOU_DATE <= /*dateTo*/
    GROUP BY TZIE.GYOUSHA_CD,TZIE.GENBA_CD,TZIE.ZAIKO_HINMEI_CD

    UNION 

    --該当現場に移動する移動量
    SELECT TZIE.GYOUSHA_CD,TZID.GENBA_CD,TZIE.ZAIKO_HINMEI_CD,SUM(TZID.IDOU_RYOU) AS ZAIKO_RYOU  FROM T_ZAIKO_IDOU_ENTRY TZIE
    INNER JOIN T_ZAIKO_IDOU_DETAIL TZID
    ON TZIE.SYSTEM_ID = TZID.SYSTEM_ID
    AND TZIE.SEQ = TZID.SEQ
    WHERE TZIE.GYOUSHA_CD = /*gyoushaCd*/
    AND TZID.GENBA_CD = /*genbaCd*/
    AND TZIE.ZAIKO_HINMEI_CD = /*zaikoHinmeiCd*/
    /*IF !dateFrom.IsNull*/
    AND TZIE.IDOU_DATE >= /*dateFrom*/
    /*END*/
    AND TZIE.IDOU_DATE <= /*dateTo*/
    GROUP BY TZIE.GYOUSHA_CD,TZID.GENBA_CD,TZIE.ZAIKO_HINMEI_CD
) AS A
WHERE A.GYOUSHA_CD = /*gyoushaCd*/
AND A.GENBA_CD = /*genbaCd*/
AND A.ZAIKO_HINMEI_CD = /*zaikoHinmeiCd*/
GROUP BY GYOUSHA_CD,GENBA_CD,ZAIKO_HINMEI_CD