SELECT
INFO.DELETE_FLG,
INFO.SHORUI_INFO_ID,
INFO.SHORUI_INFO_NAME,
INFO.UPDATE_USER,
INFO.UPDATE_DATE,
INFO.CREATE_USER,
INFO.CREATE_DATE,
INFO.CREATE_PC,
INFO.UPDATE_PC,
INFO.TIME_STAMP
FROM
dbo.M_DENSHI_KEIYAKU_SHORUI_INFO INFO
/*BEGIN*/WHERE
/*IF data.SHORUI_INFO_ID != null*/INFO.SHORUI_INFO_ID = /*data.SHORUI_INFO_ID*//*END*/
/*IF data.SHORUI_INFO_NAME != null*/AND INFO.SHORUI_INFO_NAME LIKE '%' +  /*data.SHORUI_INFO_NAME*/ + '%'/*END*/
/*IF data.CREATE_USER != null*/AND INFO.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, INFO.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
/*IF data.UPDATE_USER != null*/AND INFO.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, INFO.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*IF !deletechuFlg*/AND INFO.DELETE_FLG = /*deletechuFlg*/0/*END*/
/*END*/
ORDER BY 
LEN(INFO.SHORUI_INFO_ID),
INFO.SHORUI_INFO_ID
