SELECT
	TSD.TORIHIKISAKI_CD,
	MT.TORIHIKISAKI_NAME_RYAKU,
	MT.EIGYOU_TANTOU_CD AS EIGYOUSHA_CD,
	MS.SHAIN_NAME_RYAKU,
	CONVERT(varchar, TSD.NYUUKIN_YOTEI_BI, 111) AS NYUUKIN_YOTEI_BI,
	TSD.SEIKYUU_GAKU,
	ISNULL(TNK.KESHIKOMI_GAKU,0) AS KESHIKOMI_GAKU,
	/*IF dto.NyuukinKeshigomuJoukyou == 1*/
	(TSD.SEIKYUU_GAKU - ISNULL(TNK.KESHIKOMI_GAKU,0)) AS NYUUKIN_GAKU,
	--ELSE
	TSD.SEIKYUU_GAKU AS NYUUKIN_GAKU,
	/*END*/
	TSD.SHIMEBI,
	CONVERT(varchar, TSD.SEIKYUU_DATE, 111) AS SEIKYUU_DATE,
	MNK.NYUUSHUKKIN_KBN_NAME_RYAKU AS NYUUSHUKKIN_KBN_NAME_RYAKU
FROM (SELECT 
			TSD.KYOTEN_CD,
			TSD.SEIKYUU_NUMBER,
			TSD.TORIHIKISAKI_CD,
			TSD.SHIMEBI,
			TSD.SEIKYUU_DATE,
			TSD.NYUUKIN_YOTEI_BI,
			(ISNULL(TSD.KONKAI_URIAGE_GAKU, 0) 
			+ ISNULL(TSD.KONKAI_SEI_UTIZEI_GAKU, 0) 
			+ ISNULL(TSD.KONKAI_SEI_SOTOZEI_GAKU, 0) 
			+ ISNULL(TSD.KONKAI_DEN_UTIZEI_GAKU, 0) 
			+ ISNULL(TSD.KONKAI_DEN_SOTOZEI_GAKU, 0) 
			+ ISNULL(TSD.KONKAI_MEI_UTIZEI_GAKU, 0) 
			+ ISNULL(TSD.KONKAI_MEI_SOTOZEI_GAKU, 0)) AS SEIKYUU_GAKU,
			TSD.KONKAI_URIAGE_GAKU,
			TSD.DELETE_FLG
		FROM T_SEIKYUU_DENPYOU AS TSD
		WHERE TSD.DELETE_FLG = 0) AS TSD
LEFT JOIN (SELECT
				TNK.SEIKYUU_NUMBER,
				SUM(ISNULL(TNK.KESHIKOMI_GAKU,0)) AS KESHIKOMI_GAKU
			FROM T_NYUUKIN_KESHIKOMI AS TNK
			WHERE TNK.DELETE_FLG = 0
			GROUP BY TNK.SEIKYUU_NUMBER) TNK ON TSD.SEIKYUU_NUMBER = TNK.SEIKYUU_NUMBER
JOIN M_TORIHIKISAKI AS MT ON MT.TORIHIKISAKI_CD = TSD.TORIHIKISAKI_CD
LEFT JOIN M_TORIHIKISAKI_SEIKYUU AS MTS ON MT.TORIHIKISAKI_CD = MTS.TORIHIKISAKI_CD
LEFT JOIN M_NYUUSHUKKIN_KBN AS MNK ON MNK.NYUUSHUKKIN_KBN_CD = MTS.KAISHUU_HOUHOU
LEFT JOIN M_SHAIN AS MS ON MS.SHAIN_CD = MT.EIGYOU_TANTOU_CD
WHERE
TSD.DELETE_FLG = 0
/*IF dto.KyotenCd != null && dto.KyotenCd != 99*/AND TSD.KYOTEN_CD = /*dto.KyotenCd*/99/*END*/
/*IF dto.NyuukinYoteiDateFrom != null && dto.NyuukinYoteiDateFrom != ''*/AND CONVERT(varchar, TSD.NYUUKIN_YOTEI_BI, 111) >= /*dto.NyuukinYoteiDateFrom*/''/*END*/
/*IF dto.NyuukinYoteiDateTo != null && dto.NyuukinYoteiDateTo != ''*/AND CONVERT(varchar, TSD.NYUUKIN_YOTEI_BI, 111) <= /*dto.NyuukinYoteiDateTo*/''/*END*/
/*IF dto.SeikyuuDateFrom != null && dto.SeikyuuDateFrom != ''*/AND CONVERT(varchar, TSD.SEIKYUU_DATE, 111) >= /*dto.SeikyuuDateFrom*/''/*END*/
/*IF dto.SeikyuuDateTo != null && dto.SeikyuuDateTo != ''*/AND CONVERT(varchar, TSD.SEIKYUU_DATE, 111) <= /*dto.SeikyuuDateTo*/''/*END*/
/*IF dto.EigyoushaCdFrom != null && dto.EigyoushaCdFrom != ''*/AND MT.EIGYOU_TANTOU_CD >= /*dto.EigyoushaCdFrom*/''/*END*/
/*IF dto.EigyoushaCdTo != null && dto.EigyoushaCdTo != ''*/AND MT.EIGYOU_TANTOU_CD <= /*dto.EigyoushaCdTo*/''/*END*/
/*IF dto.TorihikisakiCdFrom != null && dto.TorihikisakiCdFrom != ''*/AND TSD.TORIHIKISAKI_CD >= /*dto.TorihikisakiCdFrom*/''/*END*/
/*IF dto.TorihikisakiCdTo != null && dto.TorihikisakiCdTo != ''*/AND TSD.TORIHIKISAKI_CD <= /*dto.TorihikisakiCdTo*/''/*END*/
AND TSD.KONKAI_URIAGE_GAKU > 0
/*IF dto.NyuukinKeshigomuJoukyou == 1*/
AND (TSD.SEIKYUU_GAKU - ISNULL(TNK.KESHIKOMI_GAKU,0)) <> 0
/*END*/
/*IF dto.Sort1 == 1 && dto.Sort2 == 1*/
ORDER BY MT.EIGYOU_TANTOU_CD, TSD.TORIHIKISAKI_CD, TSD.SEIKYUU_NUMBER
/*END*/
/*IF dto.Sort1 == 1 && dto.Sort2 == 2*/
ORDER BY MS.SHAIN_FURIGANA, MT.EIGYOU_TANTOU_CD, TSD.TORIHIKISAKI_CD, TSD.SEIKYUU_NUMBER
/*END*/
/*IF dto.Sort1 == 2 && dto.Sort2 == 1*/
ORDER BY TSD.TORIHIKISAKI_CD, MT.EIGYOU_TANTOU_CD, TSD.SEIKYUU_NUMBER
/*END*/
/*IF dto.Sort1 == 2 && dto.Sort2 == 2*/
ORDER BY MT.TORIHIKISAKI_FURIGANA, TSD.TORIHIKISAKI_CD, MT.EIGYOU_TANTOU_CD, TSD.SEIKYUU_NUMBER
/*END*/
/*IF dto.Sort1 == 3 && dto.IsGroupEigyousha*/
ORDER BY TSD.NYUUKIN_YOTEI_BI, MT.EIGYOU_TANTOU_CD, TSD.TORIHIKISAKI_CD, TSD.SEIKYUU_DATE, TSD.SEIKYUU_NUMBER
/*END*/
/*IF dto.Sort1 == 3 && dto.IsGroupEigyousha != true*/
ORDER BY TSD.NYUUKIN_YOTEI_BI, TSD.TORIHIKISAKI_CD, TSD.SEIKYUU_DATE, TSD.SEIKYUU_NUMBER
/*END*/