WITH UKEIRE AS
(
    SELECT DISTINCT
           T_UR_SH_ENTRY.UR_SH_NUMBER,
           T_UR_SH_ENTRY.KYOTEN_CD,
           T_UR_SH_ENTRY.DENPYOU_DATE,
           T_UR_SH_ENTRY.UNPAN_GYOUSHA_CD,
           T_UR_SH_ENTRY.UNPAN_GYOUSHA_NAME,
           T_UR_SH_ENTRY.SHASHU_CD,
           T_UR_SH_ENTRY.SHASHU_NAME,
           T_UR_SH_ENTRY.SHARYOU_CD,
           T_UR_SH_ENTRY.SHARYOU_NAME,
           T_UR_SH_ENTRY.UNTENSHA_CD,
           T_UR_SH_ENTRY.UNTENSHA_NAME,
           T_UR_SH_ENTRY.GYOUSHA_CD,
           T_UR_SH_ENTRY.GYOUSHA_NAME,
           T_UR_SH_ENTRY.GENBA_CD,
           T_UR_SH_ENTRY.GENBA_NAME
      FROM T_UR_SH_ENTRY
INNER JOIN T_UR_SH_DETAIL
        ON T_UR_SH_ENTRY.SYSTEM_ID = T_UR_SH_DETAIL.SYSTEM_ID
       AND T_UR_SH_ENTRY.SEQ = T_UR_SH_DETAIL.SEQ
     WHERE T_UR_SH_ENTRY.UR_SH_NUMBER = /*data.UR_SH_NUMBER.Value*/0
       AND T_UR_SH_ENTRY.DELETE_FLG = 0
       AND T_UR_SH_ENTRY.DAINOU_FLG = 1
       AND T_UR_SH_DETAIL.DENPYOU_KBN_CD = 2
),
SHUKKA AS
(
    SELECT DISTINCT
           T_UR_SH_ENTRY.UR_SH_NUMBER,
           T_UR_SH_ENTRY.KYOTEN_CD,
           T_UR_SH_ENTRY.DENPYOU_DATE,
           T_UR_SH_ENTRY.UNPAN_GYOUSHA_CD,
           T_UR_SH_ENTRY.UNPAN_GYOUSHA_NAME,
           T_UR_SH_ENTRY.SHASHU_CD,
           T_UR_SH_ENTRY.SHASHU_NAME,
           T_UR_SH_ENTRY.SHARYOU_CD,
           T_UR_SH_ENTRY.SHARYOU_NAME,
           T_UR_SH_ENTRY.UNTENSHA_CD,
           T_UR_SH_ENTRY.UNTENSHA_NAME,
           T_UR_SH_ENTRY.GYOUSHA_CD,
           T_UR_SH_ENTRY.GYOUSHA_NAME,
           T_UR_SH_ENTRY.GENBA_CD,
           T_UR_SH_ENTRY.GENBA_NAME
      FROM T_UR_SH_ENTRY
INNER JOIN T_UR_SH_DETAIL
        ON T_UR_SH_ENTRY.SYSTEM_ID = T_UR_SH_DETAIL.SYSTEM_ID
       AND T_UR_SH_ENTRY.SEQ = T_UR_SH_DETAIL.SEQ
     WHERE T_UR_SH_ENTRY.UR_SH_NUMBER = /*data.UR_SH_NUMBER.Value*/0
       AND T_UR_SH_ENTRY.DELETE_FLG = 0
       AND T_UR_SH_ENTRY.DAINOU_FLG = 1
       AND T_UR_SH_DETAIL.DENPYOU_KBN_CD = 1
)
    SELECT UKEIRE.KYOTEN_CD,
           UKEIRE.DENPYOU_DATE,
           UKEIRE.UNPAN_GYOUSHA_CD,
           UKEIRE.UNPAN_GYOUSHA_NAME,
           UKEIRE.SHASHU_CD,
           UKEIRE.SHASHU_NAME,
           UKEIRE.SHARYOU_CD,
           UKEIRE.SHARYOU_NAME,
           UKEIRE.UNTENSHA_CD,
           UKEIRE.UNTENSHA_NAME,
           UKEIRE.GYOUSHA_CD   AS NIZUMI_GYOUSHA_CD,
           UKEIRE.GYOUSHA_NAME AS NIZUMI_GYOUSHA_NAME,
           UKEIRE.GENBA_CD     AS NIZUMI_GENBA_CD,
           UKEIRE.GENBA_NAME   AS NIZUMI_GENBA_NAME,
           SHUKKA.GYOUSHA_CD   AS NIOROSHI_GYOUSHA_CD,
           SHUKKA.GYOUSHA_NAME AS NIOROSHI_GYOUSHA_NAME,
           SHUKKA.GENBA_CD     AS NIOROSHI_GENBA_CD,
           SHUKKA.GENBA_NAME   AS NIOROSHI_GENBA_NAME
      FROM UKEIRE
INNER JOIN SHUKKA
        ON UKEIRE.UR_SH_NUMBER = SHUKKA.UR_SH_NUMBER