SELECT
SHARYOU_CD,
SHARYOU_NAME_RYAKU
FROM
M_SHARYOU
WHERE
DELETE_FLG = 0
/*IF data.SHARYOU_CD!= null*/ AND SHARYOU_CD = /*data.SHARYOU_CD*//*END*/
/*IF data.GYOSHA_CD!= null*/ AND GYOSHA_CD = /*data.GYOSHA_CD*//*END*/