
SELECT  T_USSE.*
		, M_KYOTEN.KYOTEN_NAME_RYAKU
FROM	T_UNCHIN_ENTRY AS T_USSE LEFT OUTER JOIN
		M_KYOTEN ON T_USSE.KYOTEN_CD = M_KYOTEN.KYOTEN_CD AND M_KYOTEN.DELETE_FLG = 0
WHERE	T_USSE.DELETE_FLG = 0   

/*IF data.RENKEI_SYSTEM_ID!= null*/ AND RENKEI_SYSTEM_ID = /*data.RENKEI_SYSTEM_ID*//*END*/

/*IF data.RENKEI_DENSHU_KBN_CD!= null*/ AND RENKEI_DENSHU_KBN_CD = /*data.RENKEI_DENSHU_KBN_CD*//*END*/
