UPDATE dbo.T_UNCHIN_ENTRY 
SET 
UPDATE_USER=/*data.UPDATE_USER*/,
UPDATE_PC=/*data.UPDATE_PC*/,
UPDATE_DATE=/*data.UPDATE_DATE*/,
DELETE_FLG = /*data.DELETE_FLG*/
WHERE  
DENPYOU_NUMBER = /*data.DENPYOU_NUMBER*/ 
AND SYSTEM_ID = /*data.SYSTEM_ID*/
AND SEQ=/*data.SEQ*/
AND DELETE_FLG = 0
