SELECT * FROM dbo.S_NUMBER_RECEIPT
WHERE DELETE_FLG = 0
/*IF !data.NUMBERED_DAY.IsNull*/AND NUMBERED_DAY = /*data.NUMBERED_DAY.Value*//*END*/
/*IF !data.KYOTEN_CD.IsNull*/AND KYOTEN_CD = /*data.KYOTEN_CD.Value*//*END*/