//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DenManiHaikiShuruiHoshu.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConditionValue_Text {
            get {
                return ((string)(this["ConditionValue_Text"]));
            }
            set {
                this["ConditionValue_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ICHIRAN_HYOUJI_JOUKEN_TEKIYOU {
            get {
                return ((bool)(this["ICHIRAN_HYOUJI_JOUKEN_TEKIYOU"]));
            }
            set {
                this["ICHIRAN_HYOUJI_JOUKEN_TEKIYOU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ICHIRAN_HYOUJI_JOUKEN_DELETED {
            get {
                return ((bool)(this["ICHIRAN_HYOUJI_JOUKEN_DELETED"]));
            }
            set {
                this["ICHIRAN_HYOUJI_JOUKEN_DELETED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ICHIRAN_HYOUJI_JOUKEN_TEKIYOUGAI {
            get {
                return ((bool)(this["ICHIRAN_HYOUJI_JOUKEN_TEKIYOUGAI"]));
            }
            set {
                this["ICHIRAN_HYOUJI_JOUKEN_TEKIYOUGAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConditionValue_DBFieldsName {
            get {
                return ((string)(this["ConditionValue_DBFieldsName"]));
            }
            set {
                this["ConditionValue_DBFieldsName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConditionValue_ItemDefinedTypes {
            get {
                return ((string)(this["ConditionValue_ItemDefinedTypes"]));
            }
            set {
                this["ConditionValue_ItemDefinedTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConditionItem_Text {
            get {
                return ((string)(this["ConditionItem_Text"]));
            }
            set {
                this["ConditionItem_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SAIBUNRUI_ConditionValue_Text {
            get {
                return ((string)(this["SAIBUNRUI_ConditionValue_Text"]));
            }
            set {
                this["SAIBUNRUI_ConditionValue_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SAIBUNRUI_ICHIRAN_HYOUJI_JOUKEN_TEKIYOU {
            get {
                return ((bool)(this["SAIBUNRUI_ICHIRAN_HYOUJI_JOUKEN_TEKIYOU"]));
            }
            set {
                this["SAIBUNRUI_ICHIRAN_HYOUJI_JOUKEN_TEKIYOU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SAIBUNRUI_ICHIRAN_HYOUJI_JOUKEN_DELETED {
            get {
                return ((bool)(this["SAIBUNRUI_ICHIRAN_HYOUJI_JOUKEN_DELETED"]));
            }
            set {
                this["SAIBUNRUI_ICHIRAN_HYOUJI_JOUKEN_DELETED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SAIBUNRUI_ICHIRAN_HYOUJI_JOUKEN_TEKIYOUGAI {
            get {
                return ((bool)(this["SAIBUNRUI_ICHIRAN_HYOUJI_JOUKEN_TEKIYOUGAI"]));
            }
            set {
                this["SAIBUNRUI_ICHIRAN_HYOUJI_JOUKEN_TEKIYOUGAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SAIBUNRUI_ConditionValue_DBFieldsName {
            get {
                return ((string)(this["SAIBUNRUI_ConditionValue_DBFieldsName"]));
            }
            set {
                this["SAIBUNRUI_ConditionValue_DBFieldsName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SAIBUNRUI_ConditionValue_ItemDefinedTypes {
            get {
                return ((string)(this["SAIBUNRUI_ConditionValue_ItemDefinedTypes"]));
            }
            set {
                this["SAIBUNRUI_ConditionValue_ItemDefinedTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SAIBUNRUI_ConditionItem_Text {
            get {
                return ((string)(this["SAIBUNRUI_ConditionItem_Text"]));
            }
            set {
                this["SAIBUNRUI_ConditionItem_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SAIBUNRUI_EDI_MEMBER_ID_Text {
            get {
                return ((string)(this["SAIBUNRUI_EDI_MEMBER_ID_Text"]));
            }
            set {
                this["SAIBUNRUI_EDI_MEMBER_ID_Text"] = value;
            }
        }
    }
}
