SELECT
    TMLU.TORIHIKISAKI_CD,
    MT.TORIHIKISAKI_NAME_RYAKU AS TORIHIKISAKI_NAME,
    TMLU.PREVIOUS_MONTH_BALANCE AS KURIKOSHI_ZANDAKA,
    TMLU.NYUUKIN_KINGAKU AS NYUKINGAKU,
    TMLU.KINGAKU AS ZEINUKI_URIAGE,
    (TMLU.TAX + ISNULL (TMAU.ADJUST_TAX, 0)) AS SHOHIZEI,
    (TMLU.TOTAL_KINGAKU + ISNULL (TMAU.ADJUST_TAX, 0)) AS ZEIKOMI_URIAGE,
    ISNULL (TMAU.ZANDAKA, TMLU.ZANDAKA) AS SASHIHIKI_URIAGE_ZANDAKA,
    MTS.SHIMEBI1,
    MTS.SHIMEBI2,
    MTS.SHIMEBI3
FROM
    T_MONTHLY_LOCK_UR AS TMLU
    LEFT JOIN
        T_MONTHLY_ADJUST_UR AS TMAU
    ON  TMLU.TORIHIKISAKI_CD = TMAU.TORIHIKISAKI_CD
    AND TMLU.YEAR = TMAU.YEAR
    AND TMLU.MONTH = TMAU.MONTH
    AND TMLU.SEQ = TMAU.SEQ
    INNER JOIN
        M_TORIHIKISAKI AS MT
    ON  TMLU.TORIHIKISAKI_CD = MT.TORIHIKISAKI_CD
    LEFT JOIN
        M_TORIHIKISAKI_SEIKYUU AS MTS
    ON  TMLU.TORIHIKISAKI_CD = MTS.TORIHIKISAKI_CD
WHERE
    TMLU.DELETE_FLG = 0
AND (
        TMAU.DELETE_FLG = 0
    OR  TMAU.DELETE_FLG IS NULL
    )
AND TMLU.YEAR = /*year*/2014
AND TMLU.MONTH = /*month*/12
AND TMLU.TORIHIKISAKI_CD >= /*startCD*/'700001'
AND TMLU.TORIHIKISAKI_CD <= /*endCD*/'700001'
AND MTS.TORIHIKI_KBN_CD = 2
ORDER BY TMLU.TORIHIKISAKI_CD