SELECT MT.TORIHIKISAKI_CD,
 MT.TORIHIKISAKI_NAME_RYAKU,
 MTSE.TORIHIKI_KBN_CD,
 MTSE.SHIMEBI1,
 MTSE.SHIMEBI2,
 MTSE.SHIMEBI3,
 MTSE.KAISHI_URIKAKE_ZANDAKA,
 MTSE.SHOSHIKI_KBN,
 MTSE.TAX_HASUU_CD
FROM dbo.M_TORIHIKISAKI AS MT
 LEFT JOIN dbo.M_TORIHIKISAKI_SEIKYUU AS MTSE
ON MT.TORIHIKISAKI_CD = MTSE.TORIHIKISAKI_CD
WHERE 
MTSE.TORIHIKI_KBN_CD = 2
/*IF startCD != null*/AND MTSE.TORIHIKISAKI_CD >= /*startCD*//*END*/
/*IF endCD != null*/AND MTSE.TORIHIKISAKI_CD <= /*endCD*//*END*/
ORDER BY MT.TORIHIKISAKI_CD
