SELECT
	CK.FUTSUU_KYOKA_NO AS 'KYOKA_NO'
	,CK.FUTSUU_KYOKA_BEGIN AS 'KYOKA_BEGIN'
	,CK.FUTSUU_KYOKA_END AS 'KYOKA_END'
	,HS.HOUKOKUSHO_BUNRUI_NAME_RYAKU
	,CKM.TOKUBETSU_KANRI_KBN
FROM M_CHIIKIBETSU_KYOKA CK
LEFT JOIN M_CHIIKIBETSU_KYOKA_MEIGARA CKM ON CK.KYOKA_KBN = CKM.KYOKA_KBN AND CK.GYOUSHA_CD = CKM.GYOUSHA_CD AND CK.GENBA_CD = CKM.GENBA_CD AND CK.CHIIKI_CD = CKM.CHIIKI_CD
LEFT JOIN M_HOUKOKUSHO_BUNRUI HS ON CKM.HOUKOKUSHO_BUNRUI_CD = HS.HOUKOKUSHO_BUNRUI_CD
WHERE
	CK.DELETE_FLG = 0
/*IF !data.KYOKA_KBN.IsNull*/
AND CK.KYOKA_KBN = /*data.KYOKA_KBN*/1
/*END*/
/*IF data.GYOUSHA_CD != null*/
AND CK.GYOUSHA_CD = /*data.GYOUSHA_CD*/'000001'
/*END*/
/*IF data.GENBA_CD != null*/
AND CK.GENBA_CD = /*data.GENBA_CD*/'000001'
/*END*/
/*IF data.CHIIKI_CD != null*/
AND CK.CHIIKI_CD = /*data.CHIIKI_CD*/'000001'
/*END*/
AND	ISNULL(CK.FUTSUU_KYOKA_NO, '') <> ''
AND	CK.FUTSUU_KYOKA_BEGIN IS NOT NULL
AND	CKM.TOKUBETSU_KANRI_KBN = 0

UNION
SELECT
	CK.TOKUBETSU_KYOKA_NO AS 'KYOKA_NO'
	,CK.TOKUBETSU_KYOKA_BEGIN AS 'KYOKA_BEGIN'
	,CK.TOKUBETSU_KYOKA_END AS 'KYOKA_END'
	,HS.HOUKOKUSHO_BUNRUI_NAME_RYAKU
	,CKM.TOKUBETSU_KANRI_KBN
FROM M_CHIIKIBETSU_KYOKA CK
LEFT JOIN M_CHIIKIBETSU_KYOKA_MEIGARA CKM ON CK.KYOKA_KBN = CKM.KYOKA_KBN AND CK.GYOUSHA_CD = CKM.GYOUSHA_CD AND CK.GENBA_CD = CKM.GENBA_CD AND CK.CHIIKI_CD = CKM.CHIIKI_CD
LEFT JOIN M_HOUKOKUSHO_BUNRUI HS ON CKM.HOUKOKUSHO_BUNRUI_CD = HS.HOUKOKUSHO_BUNRUI_CD
WHERE
	CK.DELETE_FLG = 0
/*IF !data.KYOKA_KBN.IsNull*/
AND CK.KYOKA_KBN = /*data.KYOKA_KBN*/1
/*END*/
/*IF data.GYOUSHA_CD != null*/
AND CK.GYOUSHA_CD = /*data.GYOUSHA_CD*/'000001'
/*END*/
/*IF data.GENBA_CD != null*/
AND CK.GENBA_CD = /*data.GENBA_CD*/'000001'
/*END*/
/*IF data.CHIIKI_CD != null*/
AND CK.CHIIKI_CD = /*data.CHIIKI_CD*/'000001'
/*END*/
AND	ISNULL(CK.TOKUBETSU_KYOKA_NO, '') <> ''
AND	CK.TOKUBETSU_KYOKA_BEGIN IS NOT NULL
AND	CKM.TOKUBETSU_KANRI_KBN = 1

