SELECT 
    MIKT.*,
    U1.UNIT_NAME_RYAKU HOKAN_JOGEN_UNIT_NAME,
	MT.TODOUFUKEN_NAME_RYAKU AS TSUMIKAE_HOKANBA_TODOUFUKEN_NAME,
	CONVERT(nvarchar, '') UNPAN_FROM_NAME,
	CONVERT(nvarchar, '') UNPAN_TO_NAME,
	CONVERT(nvarchar, '') KONGOU_NAME,
	CONVERT(nvarchar, '') SHUSENBETU_NAME
FROM 
    dbo.M_ITAKU_KEIYAKU_TSUMIKAE MIKT
    LEFT JOIN dbo.M_UNIT U1 ON U1.UNIT_CD = MIKT.HOKAN_JOGEN_UNIT_CD
	LEFT JOIN M_GENBA MGENBA ON MGENBA.GENBA_CD = MIKT.TSUMIKAE_HOKANBA_CD AND MGENBA.GYOUSHA_CD = MIKT.UNPAN_GYOUSHA_CD
	LEFT JOIN M_TODOUFUKEN MT ON MT.TODOUFUKEN_CD = MGENBA.GENBA_TODOUFUKEN_CD
/*BEGIN*/WHERE
 /*IF data.SYSTEM_ID != null*/
 MIKT.SYSTEM_ID = /*data.SYSTEM_ID*/'000001'
 /*END*/
/*END*/
ORDER BY MIKT.SEQ
