SELECT 
    CONVERT(BIT, 0) AS KYOKA_LINK,
    UPN.*,
	GYO.GYOUSHA_NAME_RYAKU,
	GEN.GENBA_NAME_RYAKU,
	CHI.CHIIKI_NAME_RYAKU,
	CASE WHEN UPN.KYOKA_KBN = 1 THEN CONVERT(nvarchar(10), FUTSUU_KYOKA_END, 111)
	ELSE CASE WHEN UPN.KYOKA_KBN = 2 THEN CONVERT(nvarchar(10), TOKUBETSU_KYOKA_END, 111)
	END END AS KYOKA_END
FROM 
    dbo.M_ITAKU_UPN_KYOKASHO UPN
	LEFT JOIN M_GYOUSHA GYO ON GYO.GYOUSHA_CD = UPN.GYOUSHA_CD
	LEFT JOIN M_GENBA GEN ON GEN.GYOUSHA_CD = UPN.GYOUSHA_CD AND GEN.GENBA_CD = UPN.GENBA_CD
	LEFT JOIN M_CHIIKI CHI ON CHI.CHIIKI_CD = UPN.CHIIKI_CD
	LEFT JOIN M_CHIIKIBETSU_KYOKA CK
	ON CK.KYOKA_KBN = 1
	AND CK.GYOUSHA_CD = UPN.GYOUSHA_CD
	AND CK.GENBA_CD = UPN.GENBA_CD
	AND CK.CHIIKI_CD = UPN.CHIIKI_CD
WHERE 1 != 1
