SELECT 
    B1Y.*,
	HB.HOUKOKUSHO_BUNRUI_NAME_RYAKU
FROM 
    dbo.M_ITAKU_KEIYAKU_BETSU1_YOTEI B1Y
	LEFT JOIN dbo.M_HOUKOKUSHO_BUNRUI HB ON HB.HOUKOKUSHO_BUNRUI_CD = B1Y.HOUKOKUSHO_BUNRUI_CD
WHERE 1 != 1