SELECT 
    B3.*
	,U.UNIT_NAME_RYAKU HOKAN_JOGEN_UNIT_NAME
	,SH.SHOBUN_HOUHOU_NAME_RYAKU
	,CONVERT(nvarchar, '') UNPAN_FROM_NAME
	,CONVERT(nvarchar, '') UNPAN_END_NAME
	,CONVERT(nvarchar, '') KONGOU_NAME
	,CONVERT(nvarchar, '') SHUSENBETU_NAME
	,MT1.TODOUFUKEN_NAME_RYAKU AS SHOBUN_GYOUSHA_TODOUFUKEN_NAME
	,MT2.TODOUFUKEN_NAME_RYAKU AS SHOBUN_JIGYOUJOU_TODOUFUKEN_NAME
FROM 
    dbo.M_ITAKU_KEIYAKU_BETSU3 B3
	LEFT JOIN dbo.M_UNIT U ON U.UNIT_CD = B3.HOKAN_JOGEN_UNIT_CD
	LEFT JOIN dbo.M_SHOBUN_HOUHOU SH ON SH.SHOBUN_HOUHOU_CD = B3.SHOBUN_HOUHOU_CD
	LEFT JOIN M_GYOUSHA MGYOUSHA ON MGYOUSHA.GYOUSHA_CD = B3.SHOBUN_GYOUSHA_CD
	LEFT JOIN M_TODOUFUKEN MT1 ON MT1.TODOUFUKEN_CD = MGYOUSHA.GYOUSHA_TODOUFUKEN_CD
	LEFT JOIN M_GENBA MGENBA ON MGENBA.GENBA_CD = B3.SHOBUN_JIGYOUJOU_CD AND MGENBA.GYOUSHA_CD = B3.SHOBUN_GYOUSHA_CD
	LEFT JOIN M_TODOUFUKEN MT2 ON MT2.TODOUFUKEN_CD = MGENBA.GENBA_TODOUFUKEN_CD
WHERE 1 != 1