SELECT 
    MIKH.*,
	U1.UNIT_NAME_RYAKU UNPAN_YOTEI_SUU_UNIT_NAME,
	U2.UNIT_NAME_RYAKU SHOBUN_YOTEI_SUU_UNIT_NAME,
	SH.SHOBUN_HOUHOU_NAME_RYAKU,
	MT.TODOUFUKEN_NAME_RYAKU
FROM 
    dbo.M_ITAKU_KEIYAKU_HINMEI MIKH	
	LEFT JOIN dbo.M_UNIT U1 ON U1.UNIT_CD = MIKH.UNPAN_YOTEI_SUU_UNIT_CD
	LEFT JOIN dbo.M_UNIT U2 ON U2.UNIT_CD = MIKH.SHOBUN_YOTEI_SUU_UNIT_CD
	LEFT JOIN dbo.M_SHOBUN_HOUHOU SH ON SH.SHOBUN_HOUHOU_CD = MIKH.SHOBUN_HOUHOU_CD
	LEFT JOIN dbo.M_GENBA MG ON MG.GYOUSHA_CD = MIKH.SHOBUN_JUTAKUSHA_CD AND MG.GENBA_CD = MIKH.SHOBUN_JIGYOUJOU_CD
	LEFT JOIN dbo.M_TODOUFUKEN MT ON MG.GENBA_TODOUFUKEN_CD = MT.TODOUFUKEN_CD
/*BEGIN*/WHERE
 /*IF data.SYSTEM_ID != null*/
 MIKH.SYSTEM_ID = /*data.SYSTEM_ID*/'000001'
 /*END*/
/*END*/
ORDER BY MIKH.SEQ
