SELECT 
    B1Y.*,
	HB.HOUKOKUSHO_BUNRUI_NAME_RYAKU
FROM 
    dbo.M_ITAKU_KEIYAKU_BETSU1_YOTEI B1Y
	LEFT JOIN dbo.M_HOUKOKUSHO_BUNRUI HB ON HB.HOUKOKUSHO_BUNRUI_CD = B1Y.HOUKOKUSHO_BUNRUI_CD
/*BEGIN*/WHERE
 /*IF data.SYSTEM_ID != null*/
 B1Y.SYSTEM_ID = /*data.SYSTEM_ID*/'000001'
 /*END*/
/*END*/
ORDER BY B1Y.SEQ
