SELECT 
    B1H.*--,
	--HB.HOUKOKUSHO_BUNRUI_NAME_RYAKU,
	--SH.SHOBUN_HOUHOU_NAME_RYAKU
FROM 
    dbo.M_ITAKU_KEIYAKU_BETSU1_HST B1H
	--LEFT JOIN dbo.M_HOUKOKUSHO_BUNRUI HB ON HB.HOUKOKUSHO_BUNRUI_CD = B1H.HOUKOKUSHO_BUNRUI_CD
	--LEFT JOIN dbo.M_SHOBUN_HOUHOU SH ON SH.SHOBUN_HOUHOU_CD = B1H.SHOBUN_HOUHOU_CD
/*BEGIN*/WHERE
 /*IF data.SYSTEM_ID != null*/
 B1H.SYSTEM_ID = /*data.SYSTEM_ID*/'000001'
 /*END*/
/*END*/
ORDER BY B1H.SEQ
