SELECT 
    CONVERT(BIT, 0) AS KYOKA_LINK,
    SBN.*,
	GYO.GYOUSHA_NAME_RYAKU,
	GEN.GENBA_NAME_RYAKU,
	CHI.CHIIKI_NAME_RYAKU,
	CASE WHEN SBN.KYOKA_KBN = 3 or SBN.KYOKA_KBN = 5 THEN CONVERT(nvarchar(10), FUTSUU_KYOKA_END, 111)
	ELSE CASE WHEN SBN.KYOKA_KBN = 4 or SBN.KYOKA_KBN = 6 THEN CONVERT(nvarchar(10), TOKUBETSU_KYOKA_END, 111)
	END END AS KYOKA_END
FROM 
    dbo.M_ITAKU_SBN_KYOKASHO SBN
	LEFT JOIN M_GYOUSHA GYO ON GYO.GYOUSHA_CD = SBN.GYOUSHA_CD
	LEFT JOIN M_GENBA GEN ON GEN.GYOUSHA_CD = SBN.GYOUSHA_CD AND GEN.GENBA_CD = SBN.GENBA_CD
	LEFT JOIN M_CHIIKI CHI ON CHI.CHIIKI_CD = SBN.CHIIKI_CD
	LEFT JOIN M_CHIIKIBETSU_KYOKA CK
	ON ((CK.KYOKA_KBN = 2 AND (SBN.KYOKA_KBN = 3 OR SBN.KYOKA_KBN = 4))
	    OR (CK.KYOKA_KBN = 3 AND (SBN.KYOKA_KBN = 5 OR SBN.KYOKA_KBN = 6)))
	AND CK.GYOUSHA_CD = SBN.GYOUSHA_CD
	AND CK.GENBA_CD = SBN.GENBA_CD
	AND CK.CHIIKI_CD = SBN.CHIIKI_CD
WHERE 1 != 1
