SELECT 
    KHG.*,
	MT.TODOUFUKEN_NAME_RYAKU AS HAISHUTSU_JIGYOUJOU_TODOUFUKEN_NAME
FROM 
    dbo.M_ITAKU_KEIYAKU_KIHON_HST_GENBA KHG
	LEFT JOIN M_GENBA MGENBA ON MGENBA.GENBA_CD = KHG.HAISHUTSU_JIGYOUJOU_CD AND MGENBA.GYOUSHA_CD = KHG.HAISHUTSU_JIGYOUSHA_CD
	LEFT JOIN M_TODOUFUKEN MT ON MT.TODOUFUKEN_CD = MGENBA.GENBA_TODOUFUKEN_CD
/*BEGIN*/WHERE
 /*IF data.SYSTEM_ID != null*/
 KHG.SYSTEM_ID = /*data.SYSTEM_ID*/'000001'
 /*END*/
/*END*/
ORDER BY KHG.SEQ
