SELECT 
    B2.*,
	MT.TODOUFUKEN_NAME_RYAKU AS UNPAN_TODOUFUKEN_NAME
FROM 
    dbo.M_ITAKU_KEIYAKU_BETSU2 B2
	LEFT JOIN M_GYOUSHA MG ON MG.GYOUSHA_CD = B2.UNPAN_GYOUSHA_CD
	LEFT JOIN M_TODOUFUKEN MT ON MT.TODOUFUKEN_CD = MG.GYOUSHA_TODOUFUKEN_CD
/*BEGIN*/WHERE
 /*IF data.SYSTEM_ID != null*/
 B2.SYSTEM_ID = /*data.SYSTEM_ID*/'000001'
 /*END*/
/*END*/
ORDER BY B2.SEQ
