SELECT 
    SBNB.*
	,U.UNIT_NAME_RYAKU HOKAN_JOGEN_UNIT_NAME
	,SH.SHOBUN_HOUHOU_NAME_RYAKU
	,CONVERT(nvarchar, '') UNPAN_FROM_NAME
	,CONVERT(nvarchar, '') UNPAN_END_NAME
	,CONVERT(nvarchar, '') KONGOU_NAME
	,CONVERT(nvarchar, '') SHUSENBETU_NAME
	,CONVERT(nvarchar, '') BUNRUI_NANE
	,CONVERT(nvarchar, '') END_KUBUN_NAME
	,MT1.TODOUFUKEN_NAME_RYAKU AS GYOUSHA_TODOUFUKEN_NAME
	,MT2.TODOUFUKEN_NAME_RYAKU AS GENBA_TODOUFUKEN_NAME
FROM 
    dbo.M_SBNB_PATTERN SBNB
		LEFT JOIN M_UNIT U ON U.UNIT_CD = SBNB.HOKAN_JOGEN_UNIT_CD
		LEFT JOIN M_SHOBUN_HOUHOU SH ON SH.SHOBUN_HOUHOU_CD = SBNB.SHOBUN_HOUHOU_CD
		LEFT JOIN M_GYOUSHA MGYOUSHA ON MGYOUSHA.GYOUSHA_CD = SBNB.GYOUSHA_CD
		LEFT JOIN M_TODOUFUKEN MT1 ON MT1.TODOUFUKEN_CD = MGYOUSHA.GYOUSHA_TODOUFUKEN_CD
		LEFT JOIN M_GENBA MGENBA ON MGENBA.GENBA_CD = SBNB.GENBA_CD AND MGENBA.GYOUSHA_CD = SBNB.GYOUSHA_CD
		LEFT JOIN M_TODOUFUKEN MT2 ON MT2.TODOUFUKEN_CD = MGENBA.GENBA_TODOUFUKEN_CD
WHERE
	SBNB.LAST_SBN_KBN = /*data.LAST_SBN_KBN*/0
    AND SBNB.DELETE_FLG = 0
	/*IF !data.ITAKU_KEIYAKU_TYPE.IsNull*/AND SBNB.ITAKU_KEIYAKU_TYPE = /*data.ITAKU_KEIYAKU_TYPE*/0/*END*/
	/*IF !data.SYSTEM_ID.IsNull*/AND SBNB.SYSTEM_ID = /*data.SYSTEM_ID*/0/*END*/
	/*IF !data.SEQ.IsNull*/AND SBNB.SEQ = /*data.SEQ*/0/*END*/
	/*IF !data.ROW_NO.IsNull*/AND SBNB.ROW_NO = /*data.ROW_NO*/0/*END*/
	/*IF data.PATTERN_NAME != null*/AND SBNB.PATTERN_NAME = /*data.PATTERN_NAME*/''/*END*/
ORDER BY SBNB.SYSTEM_ID, SBNB.SEQ, SBNB.ROW_NO