SELECT 
    TB.DENPYOU_NUMBER as DENPYOU_NUMBER
    ,TB.MEMO_UPDATE_DATE as MEMO_UPDATE_DATE
	,TB.MEMO as MEMO
	,TB.UPD_SHOBUN_PATTERN_NAME as SHOBUN_PATTERN_NAME
	,TB.UPD_LAST_SHOBUN_PATTERN_NAME as LAST_SHOBUN_PATTERN_NAME
	,TB.UPD_SHOBUN_PATTERN_SYSTEM_ID as SHOBUN_PATTERN_SYSTEM_ID
	,TB.UPD_SHOBUN_PATTERN_SEQ as SHOBUN_PATTERN_SEQ
	,TB.UPD_LAST_SHOBUN_PATTERN_SYSTEM_ID as LAST_SHOBUN_PATTERN_SYSTEM_ID
	,TB.UPD_LAST_SHOBUN_PATTERN_SEQ as LAST_SHOBUN_PATTERN_SEQ
	,TB.SEQ as SEQ
	,TB.SYSTEM_ID as SYSTEM_ID
FROM 
    dbo.T_ITAKU_MEMO_IKKATSU_ENTRY TB
WHERE 
	TB.DELETE_FLG = 0
ORDER BY TB.DENPYOU_NUMBER
