SELECT 
M_GENBA.GYOUSHA_CD, 
M_GYOUSHA.GYOUSHA_NAME_RYAKU, 
M_GENBA.GENBA_CD, 
M_GENBA.GENBA_NAME_RYAKU, 
M_GENBA.GENBA_FURIGANA, 
M_TODOUFUKEN.TODOUFUKEN_NAME_RYAKU, 
M_GENBA.GENBA_ADDRESS1, 
M_GENBA.GENBA_TEL 
FROM M_GENBA 
LEFT JOIN M_GYOUSHA ON M_GENBA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD 
AND ((M_GYOUSHA.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= M_GYOUSHA.TEKIYOU_END) or (M_GYOUSHA.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and M_GYOUSHA.TEKIYOU_END IS NULL) or (M_GYOUSHA.TEKIYOU_BEGIN IS NULL and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= M_GYOUSHA.TEKIYOU_END) or (M_GYOUSHA.TEKIYOU_BEGIN IS NULL and M_GYOUSHA.TEKIYOU_END IS NULL))
AND M_GYOUSHA.DELETE_FLG = 0
LEFT JOIN M_TODOUFUKEN ON M_GENBA.GENBA_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD 
AND M_TODOUFUKEN.DELETE_FLG = 0
WHERE 
((M_GENBA.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= M_GENBA.TEKIYOU_END) or (M_GENBA.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and M_GENBA.TEKIYOU_END IS NULL) or (M_GENBA.TEKIYOU_BEGIN IS NULL and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= M_GENBA.TEKIYOU_END) or (M_GENBA.TEKIYOU_BEGIN IS NULL and M_GENBA.TEKIYOU_END IS NULL))
AND M_GENBA.DELETE_FLG = 0