SELECT 
M_HINMEI.HINMEI_CD, 
M_HINMEI.HINMEI_NAME_RYAKU, 
M_HINMEI.HINMEI_FURIGANA, 
M_SHURUI.SHURUI_CD, 
M_SHURUI.SHURUI_NAME_RYAKU 
FROM M_HINMEI 
LEFT JOIN M_SHURUI ON M_HINMEI.SHURUI_CD = M_SHURUI.SHURUI_CD 
AND M_SHURUI.DELETE_FLG = 0
WHERE 
 M_HINMEI.DELETE_FLG = 0