SELECT DISTINCT N'自社情報マスタ' AS NAME 
FROM M_CORP_INFO 
WHERE BANK_CD = /*BANK_CD*/ 
AND BANK_SHITEN_CD = /*BANK_SHITEN_CD*/ 
AND KOUZA_NO = /*BANK_KOUZA_NO*/ 
AND DELETE_FLG = 'False' 
UNION
SELECT DISTINCT N'取引先マスタ' AS NAME 
FROM M_TORIHIKISAKI AS MT
	LEFT JOIN M_TORIHIKISAKI_SEIKYUU AS MT_SEI
	ON MT.TORIHIKISAKI_CD = MT_SEI.TORIHIKISAKI_CD
	AND MT.DELETE_FLG = 'False'
WHERE 
	MT_SEI.FURIKOMI_BANK_CD = /*BANK_CD*/
	AND MT_SEI.FURIKOMI_BANK_SHITEN_CD = /*BANK_SHITEN_CD*/
	AND MT_SEI.KOUZA_NO = /*BANK_KOUZA_NO*/
UNION
SELECT DISTINCT N'引合取引先マスタ' AS NAME 
FROM M_HIKIAI_TORIHIKISAKI AS MHT
	LEFT JOIN M_HIKIAI_TORIHIKISAKI_SEIKYUU AS MHT_SEI
	ON MHT.TORIHIKISAKI_CD = MHT_SEI.TORIHIKISAKI_CD
	AND MHT.DELETE_FLG = 'False'
WHERE
	MHT_SEI.FURIKOMI_BANK_CD = /*BANK_CD*/
	AND MHT_SEI.FURIKOMI_BANK_SHITEN_CD = /*BANK_SHITEN_CD*/
	AND MHT_SEI.KOUZA_NO = /*BANK_KOUZA_NO*/