SELECT 
DSRN.DELETE_FLG,
DSRN.DENSHI_SHINSEI_ROUTE_CD,
DSRN.DENSHI_SHINSEI_ROUTE_NAME,
DSRN.DENSHI_SHINSEI_ROUTE_FURIGANA,
DSRN.CREATE_USER,
DSRN.CREATE_DATE,
DSRN.CREATE_PC,
DSRN.UPDATE_USER,
DSRN.UPDATE_DATE,
DSRN.UPDATE_PC,
DSRN.TIME_STAMP
FROM 
M_DENSHI_SHINSEI_ROUTE_NAME DSRN 
/*BEGIN*/WHERE
/*IF !data.DELETE_FLG.IsNull*/
AND DSRN.DELETE_FLG = /*data.DELETE_FLG*/
/*END*/
/*IF data.DENSHI_SHINSEI_ROUTE_CD != null && data.DENSHI_SHINSEI_ROUTE_CD != ''*/
AND DSRN.DENSHI_SHINSEI_ROUTE_CD LIKE '%' + /*data.DENSHI_SHINSEI_ROUTE_CD*/ + '%'
/*END*/
/*IF data.DENSHI_SHINSEI_ROUTE_NAME != null && data.DENSHI_SHINSEI_ROUTE_NAME != ''*/
AND DSRN.DENSHI_SHINSEI_ROUTE_NAME LIKE '%' + /*data.DENSHI_SHINSEI_ROUTE_NAME*/ + '%'
/*END*/
/*IF data.DENSHI_SHINSEI_ROUTE_FURIGANA != null && data.DENSHI_SHINSEI_ROUTE_FURIGANA != ''*/
AND DSRN.DENSHI_SHINSEI_ROUTE_FURIGANA LIKE '%' +  /*data.DENSHI_SHINSEI_ROUTE_FURIGANA*/ + '%'
/*END*/
/*IF data.CREATE_USER != null && data.CREATE_USER != ''*/
AND DSRN.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'
/*END*/
/*IF data.SEARCH_CREATE_DATE != null && data.SEARCH_CREATE_DATE != ''*/
AND CONVERT(nvarchar, DSRN.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'
/*END*/
/*IF data.UPDATE_USER != null && data.UPDATE_USER != ''*/
AND DSRN.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'
/*END*/
/*IF data.SEARCH_UPDATE_DATE != null && data.SEARCH_UPDATE_DATE != ''*/
AND CONVERT(nvarchar, DSRN.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'
/*END*/
/*IF !deletechuFlg*/AND DSRN.DELETE_FLG = 0/*END*/
/*END*/
ORDER BY DSRN.DENSHI_SHINSEI_ROUTE_CD
