SELECT
    TE.SHAIN_CD,
    TE.TEGATA_HOKANSHA_BIKOU,
    TE.CREATE_DATE,
    TE.CREATE_USER,
    TE.CREATE_PC,
    TE.UPDATE_DATE,
    TE.UPDATE_USER,
    TE.UPDATE_PC,
    TE.DELETE_FLG,
    TE.TIME_STAMP,
    ISNULL(SHA.SHAIN_NAME, N'') AS SHAIN_NAME,
    ISNULL(SHA.SHAIN_FURIGANA, N'') AS SHAIN_FURIGANA,
    SHA.TEKIYOU_BEGIN,
    SHA.TEKIYOU_END
FROM
    dbo.M_TEGATA_HOKANSHA TE
        LEFT JOIN dbo.M_SHAIN SHA ON TE.SHAIN_CD = SHA.SHAIN_CD
/*BEGIN*/WHERE
/*IF !deletechuFlg*/AND TE.DELETE_FLG = 0/*END*/
/*IF data.SHAIN_CD != null*/ AND TE.SHAIN_CD LIKE '%' +  /*data.SHAIN_CD*/'000001' + '%'/*END*/
/*IF data.TEGATA_HOKANSHA_BIKOU != null*/AND TE.TEGATA_HOKANSHA_BIKOU LIKE '%' +  /*data.TEGATA_HOKANSHA_BIKOU*/ + '%'/*END*/
/*IF data.CREATE_USER != null*/AND TE.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, TE.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
/*IF data.UPDATE_USER != null*/AND TE.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, TE.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*IF tekiyounaiFlg || deletechuFlg || tekiyougaiFlg*/AND (1 = 0/*END*/
/*IF tekiyounaiFlg*/OR (((SHA.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= SHA.TEKIYOU_END) or (SHA.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and SHA.TEKIYOU_END IS NULL) or (SHA.TEKIYOU_BEGIN IS NULL and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= SHA.TEKIYOU_END) or (SHA.TEKIYOU_BEGIN IS NULL and SHA.TEKIYOU_END IS NULL)) and TE.DELETE_FLG = 0)/*END*/
/*IF deletechuFlg*/OR TE.DELETE_FLG = /*deletechuFlg*/1/*END*/
/*IF tekiyougaiFlg*/OR ((SHA.TEKIYOU_BEGIN > CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) or CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) > SHA.TEKIYOU_END) and TE.DELETE_FLG = 0)/*END*/
/*IF tekiyounaiFlg || deletechuFlg || tekiyougaiFlg*/ )/*END*/
/*END*/
ORDER BY SHA.SHAIN_CD
