SELECT 
    TE.SHAIN_CD,
    TE.TEGATA_HOKANSHA_BIKOU,
    TE.CREATE_DATE,
    TE.CREATE_USER,
    TE.CREATE_PC,
    TE.UPDATE_DATE,
    TE.UPDATE_USER,
    TE.UPDATE_PC,
    TE.DELETE_FLG,
    TE.TIME_STAMP,
	ISNULL(SHA.SHAIN_NAME, N'') AS SHAIN_NAME,
	ISNULL(SHA.SHAIN_FURIGANA, N'') AS SHAIN_FURIGANA,
	SHA.TEKIYOU_BEGIN,
	SHA.TEKIYOU_END
FROM 
	dbo.M_TEGATA_HOKANSHA TE
		INNER JOIN dbo.M_SHAIN SHA ON SHA.SHAIN_CD = TE.SHAIN_CD
/*BEGIN*/WHERE
	/*IF data.SHAIN_CD != null*/ TE.SHAIN_CD LIKE '%' +  /*data.SHAIN_CD*/'000001' + '%'/*END*/
	/*IF data.SHAIN_NAME != null*/AND SHA.SHAIN_NAME LIKE '%' +  /*data.SHAIN_NAME*/ + '%'/*END*/
	/*IF data.SHAIN_FURIGANA != null*/AND SHA.SHAIN_FURIGANA LIKE '%' +  /*data.SHAIN_FURIGANA*/ + '%'/*END*/
 /*IF !deletechuFlg*/AND TE.DELETE_FLG = 0/*END*/
 /*IF tekiyounaiFlg || deletechuFlg || tekiyougaiFlg*/AND (1 = 0/*END*/
 /*IF tekiyounaiFlg*/OR (((SHA.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= SHA.TEKIYOU_END) or (SHA.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and SHA.TEKIYOU_END IS NULL) or (SHA.TEKIYOU_BEGIN IS NULL and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= SHA.TEKIYOU_END) or (SHA.TEKIYOU_BEGIN IS NULL and SHA.TEKIYOU_END IS NULL)) and TE.DELETE_FLG = 0)/*END*/
 /*IF deletechuFlg*/OR TE.DELETE_FLG = /*deletechuFlg*/1/*END*/
 /*IF tekiyougaiFlg*/OR ((SHA.TEKIYOU_BEGIN > CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) or CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) > SHA.TEKIYOU_END) and TE.DELETE_FLG = 0)/*END*/
 /*IF tekiyounaiFlg || deletechuFlg || tekiyougaiFlg*/ )/*END*/
/*END*/
ORDER BY TE.SHAIN_CD