SELECT 
  M_KAISHI_ZAIKO_INFO.DELETE_FLG
, M_KAISHI_ZAIKO_INFO.GYOUSHA_CD
, M_KAISHI_ZAIKO_INFO.GENBA_CD
, M_KAISHI_ZAIKO_INFO.ZAIKO_HINMEI_CD
, M_KAISHI_ZAIKO_INFO.ZAIKO_HINMEI_NAME_RYAKU
, M_KAISHI_ZAIKO_INFO.KAISHI_ZAIKO_RYOU
, M_KAISHI_ZAIKO_INFO.KAISHI_ZAIKO_KINGAKU
, M_KAISHI_ZAIKO_INFO.KAISHI_ZAIKO_TANKA
, M_KAISHI_ZAIKO_INFO.UPDATE_USER
, M_KAISHI_ZAIKO_INFO.UPDATE_DATE
, M_KAISHI_ZAIKO_INFO.CREATE_USER
, M_KAISHI_ZAIKO_INFO.CREATE_DATE
, M_KAISHI_ZAIKO_INFO.CREATE_PC
, M_KAISHI_ZAIKO_INFO.UPDATE_PC
, M_KAISHI_ZAIKO_INFO.TIME_STAMP
FROM dbo.M_KAISHI_ZAIKO_INFO
/*BEGIN*/ 
WHERE 
/*IF data.GYOUSHA_CD != null*/M_KAISHI_ZAIKO_INFO.GYOUSHA_CD = /*data.GYOUSHA_CD*/ /*END*/
/*IF data.GENBA_CD != null*/AND M_KAISHI_ZAIKO_INFO.GENBA_CD = /*data.GENBA_CD*/ /*END*/
/*IF data.ZAIKO_HINMEI_CD!= null*/AND M_KAISHI_ZAIKO_INFO.ZAIKO_HINMEI_CD LIKE '%' +/*data.ZAIKO_HINMEI_CD*/ + '%'/*END*/
/*IF data.ZAIKO_HINMEI_NAME_RYAKU!= null*/AND M_KAISHI_ZAIKO_INFO.ZAIKO_HINMEI_NAME_RYAKU LIKE '%' +/*data.ZAIKO_HINMEI_NAME_RYAKU*/ + '%'/*END*/
/*IF !data.KAISHI_ZAIKO_RYOU.IsNull*/AND CONVERT(nvarchar, M_KAISHI_ZAIKO_INFO.KAISHI_ZAIKO_RYOU, 111) LIKE '%' + CONVERT(nvarchar, /*data.KAISHI_ZAIKO_RYOU*/, 111) + '%'/*END*/
/*IF !data.KAISHI_ZAIKO_KINGAKU.IsNull*/AND CONVERT(nvarchar, M_KAISHI_ZAIKO_INFO.KAISHI_ZAIKO_KINGAKU, 111) LIKE '%' + CONVERT(nvarchar, /*data.KAISHI_ZAIKO_KINGAKU*/, 111) + '%'/*END*/
/*IF !data.KAISHI_ZAIKO_TANKA.IsNull*/AND CONVERT(nvarchar, M_KAISHI_ZAIKO_INFO.KAISHI_ZAIKO_TANKA, 111) LIKE '%' + CONVERT(nvarchar, /*data.KAISHI_ZAIKO_TANKA*/, 111) + '%'/*END*/
/*IF data.CREATE_USER != null*/AND M_KAISHI_ZAIKO_INFO.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, M_KAISHI_ZAIKO_INFO.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
/*IF data.UPDATE_USER != null*/AND M_KAISHI_ZAIKO_INFO.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, M_KAISHI_ZAIKO_INFO.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*IF !deletechuFlg*/AND M_KAISHI_ZAIKO_INFO.DELETE_FLG = 0/*END*/
/*END*/
ORDER BY M_KAISHI_ZAIKO_INFO.GYOUSHA_CD,M_KAISHI_ZAIKO_INFO.GENBA_CD,M_KAISHI_ZAIKO_INFO.ZAIKO_HINMEI_CD