//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shougun.Core.Master.DenManiKansanHoshu.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EDI_MEMBER_ID {
            get {
                return ((string)(this["EDI_MEMBER_ID"]));
            }
            set {
                this["EDI_MEMBER_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HAIKI_SHURUI_CD {
            get {
                return ((string)(this["HAIKI_SHURUI_CD"]));
            }
            set {
                this["HAIKI_SHURUI_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SEARCH_CONDITION_ITEM {
            get {
                return ((string)(this["SEARCH_CONDITION_ITEM"]));
            }
            set {
                this["SEARCH_CONDITION_ITEM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SEARCH_CONDITION_VALUE_TEXT {
            get {
                return ((string)(this["SEARCH_CONDITION_VALUE_TEXT"]));
            }
            set {
                this["SEARCH_CONDITION_VALUE_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SEARCH_CONDITION_VALUE_DBFIELDSNAME {
            get {
                return ((string)(this["SEARCH_CONDITION_VALUE_DBFIELDSNAME"]));
            }
            set {
                this["SEARCH_CONDITION_VALUE_DBFIELDSNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SHOW_CONDITION_DELETED {
            get {
                return ((bool)(this["SHOW_CONDITION_DELETED"]));
            }
            set {
                this["SHOW_CONDITION_DELETED"] = value;
            }
        }
    }
}
