SELECT
   TJHE.HOUKOKU_YEAR AS HOKOKU_NENDO
  ,TJHE.HOZON_NAME AS HOZON_NAME
  ,TJHE.HOUKOKU_SHOSHIKI AS HOUKOKU_SHOSHIKI
  --,CASE WHEN TJHE.REPORT_ID = 1 AND TJHE.HOUKOKU_SHOSHIKI = 1 THEN '様式1-1/1-2号'
  --      WHEN TJHE.REPORT_ID = 1 AND TJHE.HOUKOKU_SHOSHIKI = 2 THEN '様式1-2号'
  --      WHEN TJHE.REPORT_ID = 1 AND TJHE.HOUKOKU_SHOSHIKI = 3 THEN '様式1-3号'
  --      WHEN TJHE.REPORT_ID = 1 AND TJHE.HOUKOKU_SHOSHIKI = 4 THEN '様式1-4号'
		--WHEN TJHE.REPORT_ID = 3 AND TJHE.HOUKOKU_SHOSHIKI = 1 THEN '様式1-5/1-6号'
  --      WHEN TJHE.REPORT_ID = 3 AND TJHE.HOUKOKU_SHOSHIKI = 2 THEN '様式1-6号'
  --      WHEN TJHE.REPORT_ID = 3 AND TJHE.HOUKOKU_SHOSHIKI = 3 THEN '様式1-7号'
  --      WHEN TJHE.REPORT_ID = 3 AND TJHE.HOUKOKU_SHOSHIKI = 4 THEN '様式1-8号'
		--WHEN TJHE.REPORT_ID = 2 AND TJHE.HOUKOKU_SHOSHIKI = 1 THEN '様式1-9/1-10号'
  --      WHEN TJHE.REPORT_ID = 2 AND TJHE.HOUKOKU_SHOSHIKI = 2 THEN '様式1-10号'
		--ELSE NULL END AS HOUKOKU_SHOSHIKI_NAME
  ,CASE WHEN TJHE.REPORT_ID = 1 THEN '様式1-1/1-2号'
        WHEN TJHE.REPORT_ID = 3 THEN '様式1-5/1-6号'
		WHEN TJHE.REPORT_ID = 2 THEN '様式1-9/1-10号'
		ELSE NULL END AS HOUKOKU_SHOSHIKI_NAME
  ,TJHE.TEISHUTSU_CHIIKI_CD AS TEISHUTSU_CHIIKI_CD
  ,TJHE.TEISHUTSU_NAME AS TEISHUTSU_NAME
  ,MC.GOV_OR_MAY_NAME AS GOV_OR_MAY_NAME
  ,TJHE.TOKUBETSU_KANRI_KBN AS TOKUBETSU_KANRI_KBN
  ,CASE WHEN TJHE.TOKUBETSU_KANRI_KBN = 1 THEN '産業廃棄物'
        WHEN TJHE.TOKUBETSU_KANRI_KBN = 2 THEN '特別管理型'
		ELSE '特管区分なし' END AS TOKUBETSU_KANRI_SYURUI
  ,TJHE.GYOUSHA_KBN AS GYOUSHA_KBN
  ,CASE WHEN TJHE.GYOUSHA_KBN = 1 THEN '中間処理'
        WHEN TJHE.GYOUSHA_KBN = 2 THEN '最終処分'
        WHEN TJHE.GYOUSHA_KBN = 3 THEN '収集運搬'
		ELSE '自社業種区分なし' END AS GYOUSHA_KBN_NAME
  ,TJHE.KEN_KBN AS KEN_KBN
  ,CASE WHEN TJHE.REPORT_ID = 1 AND TJHE.KEN_KBN = 1 THEN '県内'
        WHEN TJHE.REPORT_ID = 1 AND TJHE.KEN_KBN = 2 THEN '県外'
		WHEN TJHE.REPORT_ID = 1 AND TJHE.KEN_KBN = 3 THEN '全て'
		WHEN TJHE.REPORT_ID = 3 AND TJHE.KEN_KBN = 1 THEN '内→外'
		WHEN TJHE.REPORT_ID = 3 AND TJHE.KEN_KBN = 10 THEN '内→内'
		WHEN TJHE.REPORT_ID = 3 AND TJHE.KEN_KBN = 11 THEN '内→外, 内→内'
		WHEN TJHE.REPORT_ID = 3 AND TJHE.KEN_KBN = 100 THEN '外→内'
		WHEN TJHE.REPORT_ID = 3 AND TJHE.KEN_KBN = 101 THEN '外→内, 内→外'
		WHEN TJHE.REPORT_ID = 3 AND TJHE.KEN_KBN = 110 THEN '外→内, 内→内'
		WHEN TJHE.REPORT_ID = 3 AND TJHE.KEN_KBN = 111 THEN '外→内, 内→内, 内→外'
		WHEN TJHE.REPORT_ID = 3 AND TJHE.KEN_KBN = 1000 THEN '外→外'
		WHEN TJHE.REPORT_ID = 3 AND TJHE.KEN_KBN = 1001 THEN '外→外, 内→外'
		WHEN TJHE.REPORT_ID = 3 AND TJHE.KEN_KBN = 1010 THEN '外→外, 内→内'
		WHEN TJHE.REPORT_ID = 3 AND TJHE.KEN_KBN = 1011 THEN '外→外, 内→内, 内→外'
		WHEN TJHE.REPORT_ID = 3 AND TJHE.KEN_KBN = 1100 THEN '外→外, 外→内'
		WHEN TJHE.REPORT_ID = 3 AND TJHE.KEN_KBN = 1110 THEN '外→外, 外→内, 内→内'
		WHEN TJHE.REPORT_ID = 3 AND TJHE.KEN_KBN = 1111 THEN '全て'
		--WHEN TJHE.REPORT_ID = 3 THEN '全て'
		ELSE NULL END AS KEN_KBN_NAME
  ,TJHE.CREATE_DATE AS CREATE_DATE
  ,TJHE.CREATE_USER AS CREATE_USER
  ,TJHE.SYSTEM_ID
  ,TJHE.SEQ
  ,TJHE.REPORT_ID AS REPORT_KBN
FROM
   T_JISSEKI_HOUKOKU_ENTRY TJHE
   LEFT JOIN M_CHIIKI MC ON  MC.CHIIKI_CD = TJHE.TEISHUTSU_CHIIKI_CD
WHERE
   TJHE.DELETE_FLG = 0
   AND TJHE.REPORT_ID = /*data.REPORT_KBN.Value*/
   /*IF data.YEAR_KBN.Value == 1*/
   AND  TJHE.HOUKOKU_YEAR = /*data.HOKOKU_NENDO*/
   /*END*/
   /*IF data.YEAR_KBN.Value == 2*/
   AND  TJHE.HOUKOKU_YEAR <= /*data.HOKOKU_NENDO*/
   /*END*/