SELECT 
MNOG.GYOUSHA_CD + MNOG.GENBA_CD AS VISIT_CODE
,CONVERT(CHAR(5), MCD.KIBOU_TIME,108) AS KIBOU_TIME
,ISNULL(MCD.SAGYOU_TIME_MINUTE, SI.NAVI_SAGYOU_TIME) AS SAGYOU_TIME_MINUTE
,LEFT(CONVERT(VARCHAR, CONVERT(VARCHAR, MC.SAGYOU_BEGIN_HOUR) + ':' + CONVERT(VARCHAR, MC.SAGYOU_BEGIN_MINUTE), 108), 5) AS SAGYOU_TIME_FROM
,LEFT(CONVERT(VARCHAR, CONVERT(VARCHAR, MC.SAGYOU_END_HOUR) + ':' + CONVERT(VARCHAR, MC.SAGYOU_END_MINUTE), 108), 5) AS SAGYOU_TIME_TO
,MCD.GYOUSHA_CD
,GYO.GYOUSHA_NAME_RYAKU
,MCD.GENBA_CD
,GEN.GENBA_NAME_RYAKU
,CASE WHEN 
CONVERT(DATETIME, LEFT(CONVERT(VARCHAR, CONVERT(VARCHAR, MC.SAGYOU_BEGIN_HOUR) + ':' + CONVERT(VARCHAR, MC.SAGYOU_BEGIN_MINUTE), 108), 5))>
CONVERT(DATETIME, LEFT(CONVERT(VARCHAR, CONVERT(VARCHAR, MC.SAGYOU_END_HOUR) + ':' + CONVERT(VARCHAR, MC.SAGYOU_END_MINUTE), 108), 5))
THEN -1
ELSE 0
END AS DATE_CHANGE_FLG
FROM M_COURSE MC
INNER JOIN M_COURSE_DETAIL MCD ON MC.DAY_CD = MCD.DAY_CD AND MC.COURSE_NAME_CD = MCD.COURSE_NAME_CD
LEFT JOIN M_NAVI_OUTPUT_GENBA MNOG ON MCD.GYOUSHA_CD = MNOG.GYOUSHA_CD AND MCD.GENBA_CD = MNOG.GENBA_CD AND MNOG.OUTPUT_DATE IS NOT NULL
LEFT JOIN M_GYOUSHA GYO ON MCD.GYOUSHA_CD = GYO.GYOUSHA_CD
LEFT JOIN M_GENBA GEN ON MCD.GYOUSHA_CD = GEN.GYOUSHA_CD AND MCD.GENBA_CD = GEN.GENBA_CD
LEFT JOIN M_SYS_INFO SI ON SI.SYS_ID = 0
WHERE MC.DELETE_FLG = 0
AND MC.DAY_CD = /*dayCd*/
AND MC.COURSE_NAME_CD = /*courseNameCd*/
ORDER BY MCD.ROW_NO