SELECT 
MNOG.GYOUSHA_CD + MNOG.GENBA_CD AS VISIT_CODE
,CONVERT(CHAR(5), DET.KIBOU_TIME,108) AS KIBOU_TIME
,ISNULL(DET.SAGYOU_TIME_MINUTE, SI.NAVI_SAGYOU_TIME) AS SAGYOU_TIME_MINUTE
,LEFT(CONVERT(VARCHAR, CONVERT(VARCHAR, ENT.SAGYOU_BEGIN_HOUR) + ':' + CONVERT(VARCHAR, ENT.SAGYOU_BEGIN_MINUTE), 108), 5) AS SAGYOU_TIME_FROM
,LEFT(CONVERT(VARCHAR, CONVERT(VARCHAR, ENT.SAGYOU_END_HOUR) + ':' + CONVERT(VARCHAR, ENT.SAGYOU_END_MINUTE), 108), 5) AS SAGYOU_TIME_TO
,DET.GYOUSHA_CD
,GYO.GYOUSHA_NAME_RYAKU
,DET.GENBA_CD
,GEN.GENBA_NAME_RYAKU
,CASE WHEN 
CONVERT(DATETIME, LEFT(CONVERT(VARCHAR, CONVERT(VARCHAR, ENT.SAGYOU_BEGIN_HOUR) + ':' + CONVERT(VARCHAR, ENT.SAGYOU_BEGIN_MINUTE), 108), 5))>
CONVERT(DATETIME, LEFT(CONVERT(VARCHAR, CONVERT(VARCHAR, ENT.SAGYOU_END_HOUR) + ':' + CONVERT(VARCHAR, ENT.SAGYOU_END_MINUTE), 108), 5))
THEN -1
ELSE 0
END AS DATE_CHANGE_FLG
FROM T_TEIKI_HAISHA_ENTRY ENT
INNER JOIN T_TEIKI_HAISHA_DETAIL DET ON ENT.SYSTEM_ID = DET.SYSTEM_ID AND ENT.SEQ = DET.SEQ
LEFT JOIN M_NAVI_OUTPUT_GENBA MNOG ON DET.GYOUSHA_CD = MNOG.GYOUSHA_CD AND DET.GENBA_CD = MNOG.GENBA_CD AND MNOG.OUTPUT_DATE IS NOT NULL
LEFT JOIN M_GYOUSHA GYO ON DET.GYOUSHA_CD = GYO.GYOUSHA_CD
LEFT JOIN M_GENBA GEN ON DET.GYOUSHA_CD = GEN.GYOUSHA_CD AND DET.GENBA_CD = GEN.GENBA_CD
LEFT JOIN M_SYS_INFO SI ON SI.SYS_ID = 0
WHERE ENT.DELETE_FLG = 0
AND ENT.SYSTEM_ID = /*system_id*/
AND ENT.SEQ = /*seq*/
ORDER BY DET.ROW_NUMBER