SELECT 
NYU.*,
	ISNULL(SHA.SHAIN_NAME, N'') AS SHAIN_NAME,
	ISNULL(SHA.SHAIN_FURIGANA, N'') AS SHAIN_FURIGANA,
	SHA.TEKIYOU_BEGIN,
	SHA.TEKIYOU_END
FROM 
    dbo.M_NYUURYOKU_TANTOUSHA NYU
		LEFT JOIN dbo.M_SHAIN SHA ON NYU.SHAIN_CD = SHA.SHAIN_CD
/*BEGIN*/WHERE
	/*IF data.SHAIN_CD != null*/ NYU.SHAIN_CD LIKE '%' +  /*data.SHAIN_CD*/ + '%'/*END*/
	/*IF data.NYUURYOKU_TANTOUSHA_BIKOU != null*/AND NYU.NYUURYOKU_TANTOUSHA_BIKOU LIKE '%' +  /*data.UNTENSHA_BIKOU*/ + '%'/*END*/
	/*IF data.SEARCH_TEKIYOU_BEGIN != null*/AND CONVERT(nvarchar, SHA.TEKIYOU_BEGIN, 120) LIKE '%' +  /*data.SEARCH_TEKIYOU_BEGIN*/ + '%'/*END*/
	/*IF data.SEARCH_TEKIYOU_END != null*/AND CONVERT(nvarchar, SHA.TEKIYOU_END, 120) LIKE '%' +  /*data.SEARCH_TEKIYOU_END*/ + '%'/*END*/
	/*IF data.UPDATE_USER != null*/AND NYU.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
	/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, NYU.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
	/*IF data.CREATE_USER != null*/AND NYU.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
	/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, NYU.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
/*END*/
ORDER BY NYU.SHAIN_CD