select	tse.SHUKKA_NUMBER,
DENPYOU_DATE,
KENSHU_DATE,
tse.TORIHIKISAKI_CD,
tse.TORIHIKISAKI_NAME,
tse.GYOUSHA_CD,
tse.GYOUSHA_NAME,
tse.GENBA_CD,
tse.GENBA_NAME,
tsd.HINMEI_CD SHUKKA_DETAIL_HINMEI_CD, 
tsd.HINMEI_NAME SHUKKA_DETAIL_HINMEI_NAME,
NET_JYUURYOU,
tsd.SUURYOU SHUKKA_DETAIL_SUURYOU,
(select top 1 UNIT_NAME_RYAKU from M_UNIT u where u.UNIT_CD = tsd.UNIT_CD) SHUKKA_DETAIL_UNIT_NAME_RYAKU,
tsd.TANKA SHUKKA_DETAIL_TANKA,
tsd.TANKA SHUKKA_DETAIL_KINGAKU,
tkd.HINMEI_CD KENSYU_DETAIL_HINMEI_CD,
tkd.HINMEI_NAME  KENSYU_DETAIL_HINMEI_NAME,
KENSHU_NET,
tkd.SUURYOU KENSYU_DETAIL_SUURYOU,
BUBIKI,
(select top 1 UNIT_NAME_RYAKU from M_UNIT u where u.UNIT_CD = tkd.UNIT_CD) KENSYU_DETAIL_UNIT_NAME_RYAKU,
tkd.TANKA KENSYU_DETAIL_TANKA,
tkd.KINGAKU KENSYU_DETAIL_KINGAKU
,tse.KYOTEN_CD
,mgb.KENSHU_YOUHI
,tsd.DETAIL_SYSTEM_ID
,tsd.SYSTEM_ID
,tsd.SEQ
,tse.NIZUMI_GYOUSHA_CD
,tse.NIZUMI_GENBA_CD
,tse.URIAGE_DATE
 from T_SHUKKA_DETAIL as tsd
 inner join T_SHUKKA_ENTRY as tse
	on tse.SYSTEM_ID = tsd.SYSTEM_ID
	and tse.SEQ = tsd.SEQ
left join T_KENSHU_DETAIL as  tkd
	on tkd.SYSTEM_ID = tsd.SYSTEM_ID
	and tkd.SEQ = tsd.SEQ
	and tkd.DETAIL_SYSTEM_ID = tsd.DETAIL_SYSTEM_ID

left join M_GENBA as mgb
	on mgb.GYOUSHA_CD = tse.GYOUSHA_CD
	and mgb.GENBA_CD = tse.GENBA_CD
where
	tse.DELETE_FLG = 0
	and mgb.DELETE_FLG = 0
	and DENPYOU_DATE >= /*data.Shukka_Entry_Denpyou_Date_Begin*/ and DENPYOU_DATE<= /*data.Shukka_Entry_Denpyou_Date_End*/
	and KENSHU_DATE >= /*data.Shukka_Entry_Kenshu_Date_Begin*/ and KENSHU_DATE<= /*data.Shukka_Entry_Kenshu_Date_End*/
	and tsd.DETAIL_SYSTEM_ID in ( select kd.DETAIL_SYSTEM_ID from dbo.T_KENSHU_DETAIL kd where kd.SYSTEM_ID = tsd.SYSTEM_ID
										and kd.SEQ = tsd.SEQ)
										
										

	
