SELECT 
    SHO.*
FROM 
    dbo.M_SHOBUN_MOKUTEKI SHO
/*BEGIN*/WHERE
 /*IF data.SHOBUN_MOKUTEKI_CD != null && data.SHOBUN_MOKUTEKI_CD !=''*/SHO.SHOBUN_MOKUTEKI_CD LIKE '%' + /*data.SHOBUN_MOKUTEKI_CD*/ + '%'/*END*/
 /*IF data.SHOBUN_MOKUTEKI_NAME != null && data.SHOBUN_MOKUTEKI_NAME !=''*/AND SHO.SHOBUN_MOKUTEKI_NAME LIKE '%' +  /*data.SHOBUN_MOKUTEKI_NAME*/ + '%'/*END*/
 /*IF data.SHOBUN_MOKUTEKI_NAME_RYAKU != null && data.SHOBUN_MOKUTEKI_NAME_RYAKU !=''*/AND SHO.SHOBUN_MOKUTEKI_NAME_RYAKU LIKE '%' +  /*data.SHOBUN_MOKUTEKI_NAME_RYAKU*/ + '%'/*END*/
 /*IF data.SHOBUN_MOKUTEKI_BIKOU != null && data.SHOBUN_MOKUTEKI_BIKOU !=''*/AND SHO.SHOBUN_MOKUTEKI_BIKOU LIKE '%' +  /*data.SHOBUN_MOKUTEKI_BIKOU*/ + '%'/*END*/
 /*IF data.CREATE_USER != null && data.CREATE_USER !=''*/AND SHO.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, SHO.CREATE_DATE, 120) LIKE '%' + /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null && data.UPDATE_USER !=''*/AND SHO.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, SHO.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
 /*IF !deletechuFlg*/AND SHO.DELETE_FLG = /*deletechuFlg*/0/*END*/
/*END*/
ORDER BY SHO.SHOBUN_MOKUTEKI_CD
