SELECT 
    SHO.*
FROM 
    dbo.M_SHOBUN_MOKUTEKI SHO
/*BEGIN*/WHERE
 /*IF data.SHOBUN_MOKUTEKI_CD != null*/SHO.SHOBUN_MOKUTEKI_CD LIKE '%' + /*data.SHOBUN_MOKUTEKI_CD*/ + '%'/*END*/
 /*IF data.SHOBUN_MOKUTEKI_NAME != null*/AND SHO.SHOBUN_MOKUTEKI_NAME LIKE '%' + /*data.SHOBUN_MOKUTEKI_NAME*/ + '%'/*END*/
 /*IF data.SHOBUN_MOKUTEKI_NAME_RYAKU != null*/AND SHO.SHOBUN_MOKUTEKI_NAME_RYAKU LIKE '%' + /*data.SHOBUN_MOKUTEKI_NAME_RYAKU*/ + '%'/*END*/
 /*IF data.SHOBUN_MOKUTEKI_BIKOU != null*/AND SHO.SHOBUN_MOKUTEKI_BIKOU LIKE '%' + /*data.SHOBUN_MOKUTEKI_BIKOU*/ + '%'/*END*/
 /*IF !data.TEKIYOU_BEGIN.IsNull*/ AND SHO.TEKIYOU_BEGIN LIKE '%' +  /*data.TEKIYOU_BEGIN.Value*/ + '%'/*END*/
 /*IF !data.TEKIYOU_END.IsNull*/AND SHO.TEKIYOU_END LIKE '%' +  /*data.TEKIYOU_END.Value*/ + '%'/*END*/
 /*IF data.CREATE_USER != null && data.CREATE_USER !=''*/AND SHO.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, SHO.CREATE_DATE, 120) LIKE '%' + /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null && data.UPDATE_USER !=''*/AND SHO.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, SHO.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*END*/
ORDER BY SHO.SHOBUN_MOKUTEKI_CD
