SELECT
    JBUN.*
FROM 
    dbo.M_JISSEKI_BUNRUI JBUN
/*BEGIN*/WHERE
 /*IF data.JISSEKI_BUNRUI_CD != null*/
 JBUN.JISSEKI_BUNRUI_CD LIKE '%' + /*data.JISSEKI_BUNRUI_CD*/'001' + '%'
 /*END*/
 /*IF data.JISSEKI_BUNRUI_NAME != null*/AND JBUN.JISSEKI_BUNRUI_NAME LIKE '%' +  /*data.JISSEKI_BUNRUI_NAME*/ + '%'/*END*/
 /*IF data.JISSEKI_BUNRUI_NAME_RYAKU != null*/AND JBUN.JISSEKI_BUNRUI_NAME_RYAKU LIKE '%' +  /*data.JISSEKI_BUNRUI_NAME_RYAKU*/ + '%'/*END*/
 /*IF data.JISSEKI_BUNRUI_FURIGANA != null*/AND JBUN.JISSEKI_BUNRUI_FURIGANA LIKE '%' +  /*data.JISSEKI_BUNRUI_FURIGANA*/ + '%'/*END*/
 /*IF data.JISSEKI_BUNRUI_BIKOU != null*/AND JBUN.JISSEKI_BUNRUI_BIKOU LIKE '%' +  /*data.JISSEKI_BUNRUI_BIKOU*/ + '%'/*END*/
 /*IF data.CREATE_USER != null*/AND JBUN.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, JBUN.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null*/AND JBUN.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, JBUN.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
 /*IF !deletechuFlg*/AND JBUN.DELETE_FLG = /*deletechuFlg*/0/*END*/
/*END*/
ORDER BY JBUN.JISSEKI_BUNRUI_CD
