SELECT 
    HYOU.*
FROM 
    dbo.M_GENBAMEMO_HYOUDAI HYOU
/*BEGIN*/WHERE
/*IF data.GENBAMEMO_HYOUDAI_CD != null && data.GENBAMEMO_HYOUDAI_CD != '' */ HYOU.GENBAMEMO_HYOUDAI_CD LIKE '%' + /*data.GENBAMEMO_HYOUDAI_CD*/ + '%'/*END*/
 /*IF data.GENBAMEMO_HYOUDAI_NAME != null && data.GENBAMEMO_HYOUDAI_NAME != ''*/AND HYOU.GENBAMEMO_HYOUDAI_NAME LIKE '%' +  /*data.GENBAMEMO_HYOUDAI_NAME*/ + '%'/*END*/
 /*IF data.CREATE_USER != null && data.CREATE_USER != ''*/AND HYOU.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, HYOU.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null && data.UPDATE_USER != ''*/AND HYOU.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, HYOU.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
 /*IF !deletechuFlg*/AND HYOU.DELETE_FLG = /*deletechuFlg*/0/*END*/
/*END*/
ORDER BY HYOU.GENBAMEMO_HYOUDAI_CD
