SELECT * FROM dbo.M_OUTPUT_PATTERN_INXS
WHERE 
1 = 1
/*IF !data.SYSTEM_ID.IsNull*/AND SYSTEM_ID = /*data.SYSTEM_ID.Value*//*END*/
/*IF !data.SEQ.IsNull*/AND SEQ = /*data.SEQ.Value*//*END*/
/*IF data.HYOUJUN_TEMPLATE_CD!=null*/AND HYOUJUN_TEMPLATE_CD = /*data.HYOUJUN_TEMPLATE_CD*//*END*/
ORDER BY SYSTEM_ID, SEQ