SELECT
TUE.RENKEI_DENSHU_KBN_CD
,MIN(M_DENSHU_KBN.DENSHU_KBN_NAME_RYAKU) AS DENSHU_KBN_NAME_RYAKU
,TUE.UNPAN_GYOUSHA_CD
,MIN(TUE.UNPAN_GYOUSHA_NAME) AS  UNPAN_GYOUSHA_NAME
,TUE.NIZUMI_GYOUSHA_CD
,MIN(TUE.NIZUMI_GYOUSHA_NAME) AS NIZUMI_GYOUSHA_NAME
,TUE.NIZUMI_GENBA_CD
,MIN(TUE.NIZUMI_GENBA_NAME) AS NIZUMI_GENBA_NAME
,TUE.NIOROSHI_GYOUSHA_CD
,MIN(TUE.NIOROSHI_GYOUSHA_NAME)  AS NIOROSHI_GYOUSHA_NAME
,TUE.NIOROSHI_GENBA_CD
,MIN(TUE.NIOROSHI_GENBA_NAME) AS NIOROSHI_GENBA_NAME
,TUE.SHARYOU_CD
,MIN(TUE.SHARYOU_NAME) AS SHARYOU_NAME
,TUE.SHASHU_CD
,MIN(TUE.SHASHU_NAME) AS SHASHU_NAME
,TUE.UNTENSHA_CD
,MIN(TUE.UNTENSHA_NAME) AS UNTENSHA_NAME
,TUD.HINMEI_CD
,MIN(TUD.HINMEI_NAME)  AS HINMEI_NAME
,SUM(isNull(TUD.NET_JYUURYOU,0)) AS NET_JYUURYOU
,SUM(isNull(TUD.SUURYOU,0)) AS SUURYOU
,TUD.UNIT_CD
,MIN(M_UNIT.UNIT_NAME_RYAKU) AS UNIT_NAME_RYAKU
,SUM(isNull(TUD.KINGAKU,0))  AS KINGAKU1
,SUM(isNull(TUD.HINMEI_KINGAKU,0)) AS HINMEI_KINGAKU
,SUM(isNull(TUD.TAX_SOTO,0)) AS TAX_SOTO
,SUM(isNull(TUD.HINMEI_TAX_SOTO,0)) AS HINMEI_TAX_SOTO
,SUM(isNull(TUD.KINGAKU,0) + isNull(TUD.HINMEI_KINGAKU,0)) AS TANKA
,SUM(isNull(TUD.TAX_SOTO,0) + isNull(TUD.HINMEI_TAX_SOTO,0)) AS TAX
,SUM(isNull(TUD.KINGAKU,0) + isNull(TUD.HINMEI_KINGAKU,0)+ isNull(TUD.TAX_SOTO,0) + isNull(TUD.HINMEI_TAX_SOTO,0)) AS KINGAKU
FROM
T_UNCHIN_ENTRY AS TUE
INNER JOIN 
T_UNCHIN_DETAIL AS TUD ON 
TUE.SYSTEM_ID = TUD.SYSTEM_ID AND 
TUE.SEQ = TUD.SEQ 
LEFT JOIN M_UNIT ON 
TUD.UNIT_CD = M_UNIT.UNIT_CD 
LEFT JOIN M_DENSHU_KBN ON 
TUE.RENKEI_DENSHU_KBN_CD = M_DENSHU_KBN.DENSHU_KBN_CD 
WHERE 
TUE.DELETE_FLG = 0 
AND TUE.DENPYOU_DATE IS NOT NULL
/*IF data.DENPYOU_DATE_FROM != null && data.DENPYOU_DATE_FROM != ''*/ AND CONVERT(nvarchar,TUE.DENPYOU_DATE,111) >= /*data.DENPYOU_DATE_FROM*//*END*/
/*IF data.DENPYOU_DATE_TO != null && data.DENPYOU_DATE_TO != ''*/ AND CONVERT(nvarchar,TUE.DENPYOU_DATE,111) <= /*data.DENPYOU_DATE_TO*//*END*/

/*IF data.KYOTEN_CD != null && data.KYOTEN_CD != ''*/AND TUE.KYOTEN_CD = /*data.KYOTEN_CD*//*END*/

/*IF data.UNPAN_GYOUSHA_CD_FROM != null && data.UNPAN_GYOUSHA_CD_FROM != ''*/AND TUE.UNPAN_GYOUSHA_CD >= /*data.UNPAN_GYOUSHA_CD_FROM*//*END*/
/*IF data.UNPAN_GYOUSHA_CD_TO != null && data.UNPAN_GYOUSHA_CD_TO != ''*/AND TUE.UNPAN_GYOUSHA_CD <= /*data.UNPAN_GYOUSHA_CD_TO*//*END*/

/*IF data.NIZUMI_GYOUSHA_CD_FROM != null && data.NIZUMI_GYOUSHA_CD_FROM != ''*/AND TUE.NIZUMI_GYOUSHA_CD >= /*data.NIZUMI_GYOUSHA_CD_FROM*//*END*/
/*IF data.NIZUMI_GYOUSHA_CD_TO != null && data.NIZUMI_GYOUSHA_CD_TO != ''*/AND TUE.NIZUMI_GYOUSHA_CD <= /*data.NIZUMI_GYOUSHA_CD_TO*//*END*/
/*IF data.NIZUMI_GENBA_CD_FROM != null && data.NIZUMI_GENBA_CD_FROM != ''*/AND TUE.NIZUMI_GENBA_CD >= /*data.NIZUMI_GENBA_CD_FROM*//*END*/
/*IF data.NIZUMI_GENBA_CD_TO != null && data.NIZUMI_GENBA_CD_TO != ''*/AND TUE.NIZUMI_GENBA_CD <= /*data.NIZUMI_GENBA_CD_TO*//*END*/

/*IF data.NIOROSHI_GYOUSHA_CD_FROM != null && data.NIOROSHI_GYOUSHA_CD_FROM != ''*/AND TUE.NIOROSHI_GYOUSHA_CD >= /*data.NIOROSHI_GYOUSHA_CD_FROM*//*END*/
/*IF data.NIOROSHI_GYOUSHA_CD_TO != null && data.NIOROSHI_GYOUSHA_CD_TO != ''*/AND TUE.NIOROSHI_GYOUSHA_CD <= /*data.NIOROSHI_GYOUSHA_CD_TO*//*END*/
/*IF data.NIOROSHI_GENBA_CD_FROM != null && data.NIOROSHI_GENBA_CD_FROM != ''*/AND TUE.NIOROSHI_GENBA_CD >= /*data.NIOROSHI_GENBA_CD_FROM*//*END*/
/*IF data.NIOROSHI_GENBA_CD_TO != null && data.NIOROSHI_GENBA_CD_TO != ''*/AND TUE.NIOROSHI_GENBA_CD <= /*data.NIOROSHI_GENBA_CD_TO*//*END*/

GROUP BY
TUE.UNPAN_GYOUSHA_CD
,TUE.NIZUMI_GYOUSHA_CD
,TUE.NIZUMI_GENBA_CD
,TUE.NIOROSHI_GYOUSHA_CD
,TUE.NIOROSHI_GENBA_CD
,TUE.RENKEI_DENSHU_KBN_CD
,TUE.SHASHU_CD
,TUE.SHARYOU_CD
,TUE.UNTENSHA_CD
,TUD.HINMEI_CD
,TUD.UNIT_CD
ORDER BY
TUE.UNPAN_GYOUSHA_CD
,TUE.NIZUMI_GYOUSHA_CD
,TUE.NIZUMI_GENBA_CD
,TUE.NIOROSHI_GYOUSHA_CD
,TUE.NIOROSHI_GENBA_CD
,TUE.RENKEI_DENSHU_KBN_CD
,TUE.SHASHU_CD
,TUE.SHARYOU_CD
,TUE.UNTENSHA_CD
,TUD.HINMEI_CD
,TUD.UNIT_CD
