SELECT DENSHU_KBN_CD
      ,DENSHU_KBN_NAME
      ,DENSHU_KBN_NAME_RYAKU
      ,DENSHU_KBN_BIKOU
      ,CREATE_USER
      ,CREATE_DATE
      ,CREATE_PC
      ,UPDATE_USER
      ,UPDATE_DATE
      ,UPDATE_PC
      ,DELETE_FLG
      ,TIME_STAMP
      ,HINMEI_USE_KBN
  FROM M_DENSHU_KBN MDK
WHERE MDK.DELETE_FLG = 0
AND MDK.DENSHU_KBN_CD =  /*data.RENKEI_DENSHU_KBN_CD*/0