SELECT
MG.GENNYOURITSU
FROM M_GENNYOURITSU MG 
left join M_HAIKI_SHURUI MHS ON (MHS.HAIKI_SHURUI_CD = 2 AND MG.HOUKOKUSHO_BUNRUI_CD = MHS.HOUKOKUSHO_BUNRUI_CD)
WHERE MG.DELETE_FLG = 0
AND MG.HAIKI_NAME_CD = /*data.HAIKI_NAME_CD*/
AND MG.SHOBUN_HOUHOU_CD = /*data.SHOBUN_HOUHOU_CD*/