   SELECT KEIRYOU_E.DENPYOU_DATE,
          KEIRYOU_E.TORIHIKISAKI_CD,
          KEIRYOU_E.TORIHIKISAKI_NAME,
          KEIRYOU_E.GYOUSHA_CD,
          KEIRYOU_E.GYOUSHA_NAME,
          KEIRYOU_E.GENBA_CD,
          KEIRYOU_E.GENBA_NAME,
          KEIRYOU_E.NIZUMI_GYOUSHA_CD,
          KEIRYOU_E.NIZUMI_GYOUSHA_NAME,
          KEIRYOU_E.NIZUMI_GENBA_CD,
          KEIRYOU_E.NIZUMI_GENBA_NAME,
          KEIRYOU_E.UNPAN_GYOUSHA_CD,
          KEIRYOU_E.UNPAN_GYOUSHA_NAME,
          KEIRYOU_E.NIOROSHI_GYOUSHA_CD,
          KEIRYOU_E.NIOROSHI_GYOUSHA_NAME,
          KEIRYOU_E.NIOROSHI_GENBA_CD,
          KEIRYOU_E.NIOROSHI_GENBA_NAME,
          HAIKI.HAIKI_SHURUI_CD,
          HAIKI.HAIKI_SHURUI_NAME_RYAKU,
          KEIRYOU_E.GYOUSHA_CD,
          KEIRYOU_E.GYOUSHA_NAME,
          KEIRYOU_E.SHASHU_CD,
          KEIRYOU_E.SHASHU_NAME,
          KEIRYOU_E.SHARYOU_CD,
          KEIRYOU_E.SHARYOU_NAME,
          KEIRYOU_E.UNTENSHA_CD,
          KEIRYOU_E.UNTENSHA_NAME,
          KEIRYOU_E.SYSTEM_ID,
          UJD.DETAIL_SYSTEM_ID AS DETAIL_SYSTEM_ID,
          KEIRYOU_E.MANIFEST_SHURUI_CD,
          KEIRYOU_E.HST_GYOUSHA_CD as HAISYUTU_GYOUSHA_CD,
          KEIRYOU_E.HST_GENBA_CD as HAISYUTU_GENBA_CD,
          KEIRYOU_E.SBN_GYOUSHA_CD as SYOBUN_GYOUSHA_CD,
          KEIRYOU_E.SBN_GENBA_CD as UNPAN_GENBA_CD,
          KEIRYOU_E.LAST_SBN_GYOUSHA_CD as LAST_SBN_GYOUSHA_CD,
          MG.GYOUSHA_NAME_RYAKU as LAST_SBN_GYOUSHA_NAME,
          KEIRYOU_E.LAST_SBN_GENBA_CD as LAST_SBN_GENBA_CD,
          MGA.GENBA_NAME_RYAKU as LAST_SBN_GENBA_NAME,
          KEIRYOU_E.KIHON_KEIRYOU,
		  ISNULL(KEIRYOU_E.NET_TOTAL,0) AS NET_TOTAL,
	      ISNULL(UJD.SUURYOU_WARIAI,0) AS SUURYOU_WARIAI,
		  M_UNIT.UNIT_NAME
     FROM (SELECT TOP 1
                  KEIRYOU_E.*, UJE.SEQ AS UJE_SEQ, UJD.DETAIL_SEQ AS UJD_DETAIL_SEQ, 3 AS UNIT_CD 
             FROM T_KEIRYOU_ENTRY  KEIRYOU_E
			 LEFT JOIN T_UKEIRE_JISSEKI_ENTRY UJE ON (KEIRYOU_E.SYSTEM_ID = UJE.DENPYOU_SYSTEM_ID AND UJE.DENPYOU_SHURUI = 1 AND UJE.DELETE_FLG = 0)
			 LEFT JOIN T_UKEIRE_JISSEKI_DETAIL UJD ON (UJE.DENPYOU_SHURUI = UJD.DENPYOU_SHURUI AND UJE.DENPYOU_SYSTEM_ID = UJD.DENPYOU_SYSTEM_ID AND UJE.SEQ = UJD.SEQ)
            WHERE KEIRYOU_E.KEIRYOU_NUMBER = /*data.RENKEI_NUMBER*/0
              AND KEIRYOU_E.DELETE_FLG     = 0
              /*IF data.RENKEI_ROW_NO != NULL*/
              AND UJD.DETAIL_SEQ        = /*data.RENKEI_ROW_NO*/0
              /*END*/) KEIRYOU_E
LEFT JOIN T_UKEIRE_JISSEKI_DETAIL UJD ON (KEIRYOU_E.SYSTEM_ID = UJD.DENPYOU_SYSTEM_ID AND KEIRYOU_E.UJE_SEQ = UJD.SEQ AND UJD.DENPYOU_SHURUI = 1)
LEFT JOIN M_HINMEI
       ON UJD.HINMEI_CD = M_HINMEI.HINMEI_CD
      AND M_HINMEI.DELETE_FLG = 0 
LEFT JOIN M_HAIKI_SHURUI HAIKI
       ON HAIKI.HAIKI_KBN_CD    = 2
      AND HAIKI.HAIKI_SHURUI_CD = M_HINMEI.KP_HAIKI_SHURUI_CD
      AND HAIKI.DELETE_FLG      = 0
LEFT JOIN M_GYOUSHA MG ON (MG.GYOUSHA_CD = KEIRYOU_E.LAST_SBN_GYOUSHA_CD)
LEFT JOIN M_GENBA MGA ON (MGA.GYOUSHA_CD = KEIRYOU_E.LAST_SBN_GYOUSHA_CD
                       AND MGA.GENBA_CD = KEIRYOU_E.LAST_SBN_GENBA_CD)
LEFT JOIN M_UNIT ON KEIRYOU_E.UNIT_CD = M_UNIT.UNIT_CD
    WHERE KEIRYOU_E.KEIRYOU_NUMBER = /*data.RENKEI_NUMBER*/0
      AND KEIRYOU_E.DELETE_FLG     = 0
     /*IF data.RENKEI_ROW_NO != NULL*/
      AND UJD.DETAIL_SEQ        = /*data.RENKEI_ROW_NO*/0
     /*END*/
/*IF (data.RENKEI_ROW_NO == NULL || data.RENKEI_ROW_NO == '') && data.CHK_MODE_KBN == 1 */
AND UJD.SUURYOU_WARIAI IS NOT NULL
/*END*/
