   SELECT KEIRYOU_E.DENPYOU_DATE,
          KEIRYOU_E.TORIHIKISAKI_CD,
          KEIRYOU_E.TORIHIKISAKI_NAME,
          KEIRYOU_E.GYOUSHA_CD,
          KEIRYOU_E.GYOUSHA_NAME,
          KEIRYOU_E.GENBA_CD,
          KEIRYOU_E.GENBA_NAME,
          KEIRYOU_E.NIZUMI_GYOUSHA_CD,
          KEIRYOU_E.NIZUMI_GYOUSHA_NAME,
          KEIRYOU_E.NIZUMI_GENBA_CD,
          KEIRYOU_E.NIZUMI_GENBA_NAME,
          KEIRYOU_E.UNPAN_GYOUSHA_CD,
          KEIRYOU_E.UNPAN_GYOUSHA_NAME,
          KEIRYOU_E.NIOROSHI_GYOUSHA_CD,
          KEIRYOU_E.NIOROSHI_GYOUSHA_NAME,
          KEIRYOU_E.NIOROSHI_GENBA_CD,
          KEIRYOU_E.NIOROSHI_GENBA_NAME,
          HAIKI.HAIKI_SHURUI_CD,
          HAIKI.HAIKI_SHURUI_NAME_RYAKU,
          KEIRYOU_E.GYOUSHA_CD,
          KEIRYOU_E.GYOUSHA_NAME,
          KEIRYOU_E.SHASHU_CD,
          KEIRYOU_E.SHASHU_NAME,
          KEIRYOU_E.SHARYOU_CD,
          KEIRYOU_E.SHARYOU_NAME,
          KEIRYOU_E.UNTENSHA_CD,
          KEIRYOU_E.UNTENSHA_NAME,
          KEIRYOU_E.SYSTEM_ID,
          KEIRYOU_D.DETAIL_SYSTEM_ID,
          KEIRYOU_E.MANIFEST_SHURUI_CD,
          KEIRYOU_E.HST_GYOUSHA_CD as HAISYUTU_GYOUSHA_CD,
          KEIRYOU_E.HST_GENBA_CD as HAISYUTU_GENBA_CD,
          KEIRYOU_E.SBN_GYOUSHA_CD as SYOBUN_GYOUSHA_CD,
          KEIRYOU_E.SBN_GENBA_CD as UNPAN_GENBA_CD,
          KEIRYOU_E.LAST_SBN_GYOUSHA_CD as LAST_SBN_GYOUSHA_CD,
          MG.GYOUSHA_NAME_RYAKU as LAST_SBN_GYOUSHA_NAME,
          KEIRYOU_E.LAST_SBN_GENBA_CD as LAST_SBN_GENBA_CD,
          MGA.GENBA_NAME_RYAKU as LAST_SBN_GENBA_NAME,
          KEIRYOU_E.KIHON_KEIRYOU
     FROM (SELECT TOP 1
                  KEIRYOU_E.*
             FROM T_KEIRYOU_ENTRY  KEIRYOU_E
        LEFT JOIN T_KEIRYOU_DETAIL KEIRYOU_D
               ON KEIRYOU_E.SYSTEM_ID = KEIRYOU_D.SYSTEM_ID
              AND KEIRYOU_E.SEQ       = KEIRYOU_D.SEQ
            WHERE KEIRYOU_E.KEIRYOU_NUMBER = /*data.RENKEI_NUMBER*/0
              AND KEIRYOU_E.DELETE_FLG     = 0
              /*IF data.RENKEI_ROW_NO != NULL*/
              AND KEIRYOU_D.ROW_NO        = /*data.RENKEI_ROW_NO*/0
              /*END*/) KEIRYOU_E
LEFT JOIN T_KEIRYOU_DETAIL KEIRYOU_D
       ON KEIRYOU_E.SYSTEM_ID = KEIRYOU_D.SYSTEM_ID
      AND KEIRYOU_E.SEQ       = KEIRYOU_D.SEQ
LEFT JOIN M_HINMEI
       ON KEIRYOU_D.HINMEI_CD = M_HINMEI.HINMEI_CD
      AND M_HINMEI.DELETE_FLG = 0 
LEFT JOIN M_HAIKI_SHURUI HAIKI
       ON HAIKI.HAIKI_KBN_CD    = 2
      AND HAIKI.HAIKI_SHURUI_CD = M_HINMEI.KP_HAIKI_SHURUI_CD
      AND HAIKI.DELETE_FLG      = 0
LEFT JOIN M_GYOUSHA MG ON (MG.GYOUSHA_CD = KEIRYOU_E.LAST_SBN_GYOUSHA_CD)
LEFT JOIN M_GENBA MGA ON (MGA.GYOUSHA_CD = KEIRYOU_E.LAST_SBN_GYOUSHA_CD
                       AND MGA.GENBA_CD = KEIRYOU_E.LAST_SBN_GENBA_CD)
    WHERE KEIRYOU_E.KEIRYOU_NUMBER = /*data.RENKEI_NUMBER*/0
      AND KEIRYOU_E.DELETE_FLG     = 0
     /*IF data.RENKEI_ROW_NO != NULL*/
      AND KEIRYOU_D.ROW_NO        = /*data.RENKEI_ROW_NO*/0
     /*END*/
