SELECT 
	MSI.MANIFEST_USE_A
	,MSI.MANIFEST_USE_B1
	,MSI.MANIFEST_USE_B2
	,MSI.MANIFEST_USE_C1
	,MSI.MANIFEST_USE_C2
	,MSI.MANIFEST_USE_D
	,MSI.MANIFEST_USE_E
	,MU.UNIT_NAME
	,MANIFEST_VALIDATION_CHECK
	,MANIFEST_RENKEI_KBN
FROM M_SYS_INFO MSI
left join M_UNIT MU ON (MU.UNIT_CD = MSI.MANI_KANSAN_KIHON_UNIT_CD)
WHERE ISNULL(MSI.DELETE_FLG,0) = 0
AND MSI.SYS_ID =  /*data.SYSTEM_ID*/ 