   SELECT UKEIRE_E.DENPYOU_DATE,
          UKEIRE_E.TORIHIKISAKI_CD,
          UKEIRE_E.TORIHIKISAKI_NAME,
          UKEIRE_E.GYOUSHA_CD,
          UKEIRE_E.GYOUSHA_NAME,
          UKEIRE_E.GENBA_CD,
          UKEIRE_E.GENBA_NAME,
          UKEIRE_E.UNPAN_GYOUSHA_CD,
          UKEIRE_E.UNPAN_GYOUSHA_NAME,
          UKEIRE_E.NIOROSHI_GYOUSHA_CD,
          UKEIRE_E.NIOROSHI_GYOUSHA_NAME,
          UKEIRE_E.NIOROSHI_GENBA_CD,
          UKEIRE_E.NIOROSHI_GENBA_NAME,
          HAIKI.HAIKI_SHURUI_CD,
          HAIKI.HAIKI_SHURUI_NAME_RYAKU,
          UKEIRE_E.SHASHU_CD,
          UKEIRE_E.SHASHU_NAME,
          UKEIRE_E.SHARYOU_CD,
          UKEIRE_E.SHARYOU_NAME,
          UKEIRE_E.UNTENSHA_CD,
          UKEIRE_E.UNTENSHA_NAME,
          UKEIRE_E.SYSTEM_ID,
          UKEIRE_D.DETAIL_SYSTEM_ID,
          UKEIRE_E.MANIFEST_SHURUI_CD
     FROM (SELECT TOP 1
                  UKEIRE_E.*
             FROM T_UKEIRE_ENTRY  UKEIRE_E
        LEFT JOIN T_UKEIRE_DETAIL UKEIRE_D
               ON UKEIRE_E.SYSTEM_ID = UKEIRE_D.SYSTEM_ID
              AND UKEIRE_E.SEQ       = UKEIRE_D.SEQ
            WHERE UKEIRE_E.UKEIRE_NUMBER = /*data.RENKEI_NUMBER*/0
              AND UKEIRE_E.DELETE_FLG    = 0
             /*IF data.RENKEI_ROW_NO != NULL*/
              AND UKEIRE_D.ROW_NO          = /*data.RENKEI_ROW_NO*/0
             /*END*/) UKEIRE_E
LEFT JOIN T_UKEIRE_DETAIL UKEIRE_D
       ON UKEIRE_E.SYSTEM_ID = UKEIRE_D.SYSTEM_ID
      AND UKEIRE_E.SEQ       = UKEIRE_D.SEQ
LEFT JOIN M_HINMEI
       ON UKEIRE_D.HINMEI_CD  = M_HINMEI.HINMEI_CD
LEFT JOIN M_HAIKI_SHURUI HAIKI
       ON HAIKI.HAIKI_KBN_CD    = 2
      AND HAIKI.HAIKI_SHURUI_CD = M_HINMEI.KP_HAIKI_SHURUI_CD
    WHERE UKEIRE_E.UKEIRE_NUMBER = /*data.RENKEI_NUMBER*/0
      AND UKEIRE_E.DELETE_FLG    = 0
     /*IF data.RENKEI_ROW_NO != NULL*/
      AND UKEIRE_D.ROW_NO        = /*data.RENKEI_ROW_NO*/0
     /*END*/