SELECT TUSKE.UKETSUKE_NUMBER,
TUSKD.ROW_NO
FROM T_UKETSUKE_SK_ENTRY TUSKE
left join T_UKETSUKE_SK_DETAIL TUSKD ON (TUSKE.SYSTEM_ID = TUSKD.SYSTEM_ID AND TUSKE.SEQ = TUSKD.SEQ
 AND TUSKD.DETAIL_SYSTEM_ID = /*data.RENKEI_MEISAI_SYSTEM_ID*/0)
WHERE TUSKE.DELETE_FLG = 0				
AND TUSKE.SYSTEM_ID = /*data.RENKEI_SYSTEM_ID*/0
	