SELECT TUMKE.UKETSUKE_NUMBER,
TUMKD.ROW_NO
FROM T_UKETSUKE_MK_ENTRY TUMKE 
left join T_UKETSUKE_MK_DETAIL TUMKD ON (TUMKE.SYSTEM_ID = TUMKD.SYSTEM_ID AND TUMKE.SEQ = TUMKD.SEQ
 AND TUMKD.DETAIL_SYSTEM_ID = /*data.RENKEI_MEISAI_SYSTEM_ID*/0)
WHERE  TUMKE.DELETE_FLG = 0
AND TUMKE.SYSTEM_ID = /*data.RENKEI_SYSTEM_ID*/0
	