    SELECT M_GYOUSHA.GYOUSHA_CD,
           M_GENBA.GENBA_CD,
           M_GENBA.GENBA_NAME1,
           M_GENBA.GENBA_NAME2,
           M_GENBA.GENBA_POST,
           M_GENBA.GENBA_TEL,
           M_GENBA.GENBA_ADDRESS1,
           M_GENBA.GENBA_ADDRESS2,
           M_GENBA.SHOBUNSAKI_NO,
           M_TODOUFUKEN.TODOUFUKEN_NAME
      FROM M_GYOUSHA
INNER JOIN M_GENBA
        ON M_GYOUSHA.GYOUSHA_CD    = M_GENBA.GYOUSHA_CD
        /*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
       AND M_GENBA.DELETE_FLG = 'false'
       /*END*/
      LEFT JOIN M_TODOUFUKEN 
        ON M_GENBA.GENBA_TODOUFUKEN_CD  = M_TODOUFUKEN.TODOUFUKEN_CD 
        /*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
       AND M_TODOUFUKEN.DELETE_FLG      = 'false'
       /*END*/
     WHERE
       /*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
       M_GYOUSHA.DELETE_FLG = 'false'
       -- ELSE
        1 = 1
       /*END*/
    /*IF data.GYOUSHA_CD != null && data.GYOUSHA_CD != ''*/ AND M_GYOUSHA.GYOUSHA_CD = /*data.GYOUSHA_CD*/'0'/*END*/
    /*IF data.GENBA_CD != null && data.GENBA_CD != ''*/ AND M_GENBA.GENBA_CD = /*data.GENBA_CD*/'0'/*END*/
    /*IF data.HAISHUTSU_NIZUMI_GYOUSHA_KBN != null && data.HAISHUTSU_NIZUMI_GYOUSHA_KBN != ''*/ AND M_GYOUSHA.HAISHUTSU_NIZUMI_GYOUSHA_KBN = /*data.HAISHUTSU_NIZUMI_GYOUSHA_KBN*/0/*END*/
    /*IF data.SHOBUN_NIOROSHI_GYOUSHA_KBN != null && data.SHOBUN_NIOROSHI_GYOUSHA_KBN != ''*/ AND M_GYOUSHA.SHOBUN_NIOROSHI_GYOUSHA_KBN = /*data.SHOBUN_NIOROSHI_GYOUSHA_KBN*/0/*END*/
    /*IF data.HAISHUTSU_NIZUMI_GENBA_KBN != null && data.HAISHUTSU_NIZUMI_GENBA_KBN != ''*/ AND M_GENBA.HAISHUTSU_NIZUMI_GENBA_KBN = /*data.HAISHUTSU_NIZUMI_GENBA_KBN*/0/*END*/
    /*IF data.SAISHUU_SHOBUNJOU_KBN != null && data.SAISHUU_SHOBUNJOU_KBN != ''*/ AND M_GENBA.SAISHUU_SHOBUNJOU_KBN = /*data.SAISHUU_SHOBUNJOU_KBN*/0/*END*/
    /*IF data.SHOBUN_NIOROSHI_GENBA_KBN != null && data.SHOBUN_NIOROSHI_GENBA_KBN != ''*/ AND M_GENBA.SHOBUN_NIOROSHI_GENBA_KBN = /*data.SHOBUN_NIOROSHI_GENBA_KBN*/0/*END*/
    /*IF data.TSUMIKAEHOKAN_KBN != null && data.TSUMIKAEHOKAN_KBN != ''*/ AND M_GENBA.TSUMIKAEHOKAN_KBN = /*data.TSUMIKAEHOKAN_KBN*/0/*END*/
