SELECT 
TMKN.SYSTEM_ID
,TMKN.SEQ
,TMKN.REC_NO
,TMKN.NISUGATA_CD
,TMKN.NISUGATA_NAME
,TMKN.PRT_FLG
 FROM T_MANIFEST_PT_KP_NISUGATA TMKN
WHERE TMKN.SYSTEM_ID = /*data.SYSTEM_ID*/ AND TMKN.SEQ =  /*data.SEQ*/