SELECT 
TMKSH.SYSTEM_ID
,TMKSH.SEQ
,TMKSH.REC_NO
,TMKSH.SHOBUN_HOUHOU_CD
,TMKSH.SHOBUN_HOUHOU_NAME
,TMKSH.PRT_FLG
FROM T_MANIFEST_PT_KP_SBN_HOUHOU TMKSH
WHERE TMKSH.SYSTEM_ID = /*data.SYSTEM_ID*/ AND TMKSH.SEQ =  /*data.SEQ*/