SELECT 
    CHJ.*
    ,ISNULL(CHI.CHIIKI_NAME_RYAKU,N'') AS CHIIKI_NAME_RYAKU
FROM 
    dbo.M_CHIIKIBETSU_JUUSHO CHJ
	LEFT JOIN dbo.M_CHIIKI CHI ON CHI.CHIIKI_CD = CHJ.CHANGE_CHIIKI_CD
WHERE CHJ.CHIIKI_CD = /*data.CHIIKI_CD*/'000001'
  /*IF data.CHANGE_CHIIKI_CD != null*/AND CHJ.CHANGE_CHIIKI_CD LIKE '%' +  /*data.CHANGE_CHIIKI_CD*/ + '%'/*END*/
  /*IF data.HOUKOKU_JUUSHO_CD != null*/AND CHJ.HOUKOKU_JUUSHO_CD LIKE '%' +  /*data.HOUKOKU_JUUSHO_CD*/ + '%'/*END*/
  /*IF data.HOUKOKU_JUUSHO_NAME != null*/AND CHJ.HOUKOKU_JUUSHO_NAME LIKE '%' +  /*data.HOUKOKU_JUUSHO_NAME*/ + '%'/*END*/
  /*IF data.CHIIKIBETSU_JUUSHO_BIKOU != null*/AND CHJ.CHIIKIBETSU_JUUSHO_BIKOU LIKE '%' +  /*data.CHIIKIBETSU_JUUSHO_BIKOU*/ + '%'/*END*/
  /*IF data.UPDATE_USER != null*/AND CHJ.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
  /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, CHJ.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
  /*IF data.CREATE_USER != null*/AND CHJ.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
  /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, CHJ.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
  /*IF !deletechuFlg*/AND CHJ.DELETE_FLG = /*deletechuFlg*/0/*END*/
ORDER BY CHJ.CHIIKI_CD, CHJ.CHANGE_CHIIKI_CD
