SELECT 
	JIGYOUJOU_CD,JIGYOUJOU_NAME
FROM  
	M_DENSHI_JIGYOUJOU
/*BEGIN*/
where 
/*IF !deletechuFlg*/ 
	(JIGYOUJOU_KBN = 2 or JIGYOUJOU_KBN = 3 )
/*END*/
/*IF data.JIGYOUSHA_CD != null && data.JIGYOUSHA_CD != ''*/
AND	EDI_MEMBER_ID = /*data.JIGYOUSHA_CD*//*END*/ 		
/*END*/
