//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shougun.Core.ExternalConnection.RakurakuMasutaIchiran.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KYOTEN_CD_TEXT {
            get {
                return ((string)(this["KYOTEN_CD_TEXT"]));
            }
            set {
                this["KYOTEN_CD_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ICHIRAN_ALERT_KENSUU {
            get {
                return ((string)(this["ICHIRAN_ALERT_KENSUU"]));
            }
            set {
                this["ICHIRAN_ALERT_KENSUU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TORIHIKISAKI_NAME_RYAKU_TEXT {
            get {
                return ((string)(this["TORIHIKISAKI_NAME_RYAKU_TEXT"]));
            }
            set {
                this["TORIHIKISAKI_NAME_RYAKU_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GYOUSHA_NAME_RYAKU_TEXT {
            get {
                return ((string)(this["GYOUSHA_NAME_RYAKU_TEXT"]));
            }
            set {
                this["GYOUSHA_NAME_RYAKU_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_FURIGANA_TEXT {
            get {
                return ((string)(this["GENBA_FURIGANA_TEXT"]));
            }
            set {
                this["GENBA_FURIGANA_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_NAME1_TEXT {
            get {
                return ((string)(this["GENBA_NAME1_TEXT"]));
            }
            set {
                this["GENBA_NAME1_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_NAME2_TEXT {
            get {
                return ((string)(this["GENBA_NAME2_TEXT"]));
            }
            set {
                this["GENBA_NAME2_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_NAME_RYAKU_TEXT {
            get {
                return ((string)(this["GENBA_NAME_RYAKU_TEXT"]));
            }
            set {
                this["GENBA_NAME_RYAKU_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_TODOUFUKEN_CD_TEXT {
            get {
                return ((string)(this["GENBA_TODOUFUKEN_CD_TEXT"]));
            }
            set {
                this["GENBA_TODOUFUKEN_CD_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_ADDRESS_TEXT {
            get {
                return ((string)(this["GENBA_ADDRESS_TEXT"]));
            }
            set {
                this["GENBA_ADDRESS_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime TEKIYOU_BEGIN_VALUE {
            get {
                return ((global::System.DateTime)(this["TEKIYOU_BEGIN_VALUE"]));
            }
            set {
                this["TEKIYOU_BEGIN_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime TEKIYOU_END_VALUE {
            get {
                return ((global::System.DateTime)(this["TEKIYOU_END_VALUE"]));
            }
            set {
                this["TEKIYOU_END_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ICHIRAN_HYOUJI_JOUKEN_TEKIYOU {
            get {
                return ((bool)(this["ICHIRAN_HYOUJI_JOUKEN_TEKIYOU"]));
            }
            set {
                this["ICHIRAN_HYOUJI_JOUKEN_TEKIYOU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ICHIRAN_HYOUJI_JOUKEN_DELETED {
            get {
                return ((bool)(this["ICHIRAN_HYOUJI_JOUKEN_DELETED"]));
            }
            set {
                this["ICHIRAN_HYOUJI_JOUKEN_DELETED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ICHIRAN_HYOUJI_JOUKEN_TEKIYOUGAI {
            get {
                return ((bool)(this["ICHIRAN_HYOUJI_JOUKEN_TEKIYOUGAI"]));
            }
            set {
                this["ICHIRAN_HYOUJI_JOUKEN_TEKIYOUGAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TORIHIKISAKI_CD_TEXT {
            get {
                return ((string)(this["TORIHIKISAKI_CD_TEXT"]));
            }
            set {
                this["TORIHIKISAKI_CD_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GYOUSHA_CD_TEXT {
            get {
                return ((string)(this["GYOUSHA_CD_TEXT"]));
            }
            set {
                this["GYOUSHA_CD_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_CD_TEXT {
            get {
                return ((string)(this["GENBA_CD_TEXT"]));
            }
            set {
                this["GENBA_CD_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CB_SHIMEBI {
            get {
                return ((string)(this["CB_SHIMEBI"]));
            }
            set {
                this["CB_SHIMEBI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RAKURAKU_CSV_KBN {
            get {
                return ((string)(this["RAKURAKU_CSV_KBN"]));
            }
            set {
                this["RAKURAKU_CSV_KBN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SEIKYUU_SHO_SHOSHIKI_1 {
            get {
                return ((string)(this["SEIKYUU_SHO_SHOSHIKI_1"]));
            }
            set {
                this["SEIKYUU_SHO_SHOSHIKI_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RAKURAKU_MEISAI_RENKEI {
            get {
                return ((string)(this["RAKURAKU_MEISAI_RENKEI"]));
            }
            set {
                this["RAKURAKU_MEISAI_RENKEI"] = value;
            }
        }
    }
}
