SELECT
    (CASE
        WHEN SMS.SYSTEM_ID IS NOT NULL THEN 'ëóêMçœ'
        ELSE 'ñ¢ëóêM'
        END)
FROM T_UKETSUKE_SS_ENTRY SS
LEFT JOIN T_SMS SMS
ON SS.UKETSUKE_NUMBER = SMS.DENPYOU_NUMBER
WHERE SS.UKETSUKE_NUMBER = /*uketsukeNumber*/