SELECT RT.HAISHA_SAGYOU_DATE
      ,RT.HAISHA_DENPYOU_NO
      ,RT.HAISHA_COURSE_NAME_CD
      ,RT.HAISHA_COURSE_NAME
      ,RT.GENBA_JISSEKI_UPNGYOSHACD
	  ,UNPAN.GYOUSHA_NAME_RYAKU AS GENBA_JISSEKI_UPNGYOSHA_NAME
      ,RT.SHASHU_CD
      ,RT.SHASHU_NAME
      ,RT.SHARYOU_CD
      ,RT.SHARYOU_NAME
      ,RT.UNTENSHA_CD
      ,RT.UNTENSHA_NAME
      ,ROW_NUMBER() OVER(ORDER BY RT.SEQ_NO, RT_DTL.EDABAN) AS kaishuuNo
      ,RT.GENBA_JISSEKI_GYOUSHACD
      ,GYO.GYOUSHA_NAME_RYAKU AS GENBA_JISSEKI_GYOUSHA_NM
      ,RT.GENBA_JISSEKI_GENBACD
      ,GEN.GENBA_NAME_RYAKU AS GENBA_JISSEKI_GENBA_NM
      ,RT_DTL.GENBA_DETAIL_HINMEICD
      ,HIN.HINMEI_NAME_RYAKU AS GENBA_DETAIL_HINMEI_NM
      ,RT_DTL.GENBA_DETAIL_SUURYO1
      ,RT_DTL.GENBA_DETAIL_UNIT_CD1
      ,UNI1.UNIT_NAME_RYAKU AS GENBA_DETAIL_UNIT_NM1
      ,RT_DTL.GENBA_DETAIL_SUURYO2
      ,RT_DTL.GENBA_DETAIL_UNIT_CD2
      ,UNI2.UNIT_NAME_RYAKU AS GENBA_DETAIL_UNIT_NM2
      ,RT_HAN_JISSEKI.HANNYUU_JISSEKI_GYOUSHACD
      ,HAN_GYO.GYOUSHA_NAME_RYAKU AS HANNYUU_JISSEKI_GYOUSHA_NM
      ,RT_HAN_JISSEKI.HANNYUU_JISSEKI_GENBACD
      ,HAN_GEN.GENBA_NAME_RYAKU AS HANNYUU_JISSEKI_GENBA_NM
      ,RT_HAN.HANNYUU_GYOUSHACD AS HANNYUU_JISSEKI_GYOUSHACD_YOTEI
      ,HAN_GYO_YOTEI.GYOUSHA_NAME_RYAKU AS HANNYUU_JISSEKI_GYOUSHA_NM_YOTEI
      ,RT_HAN.HANNYUU_GENBACD AS HANNYUU_JISSEKI_GENBACD_YOTEI
      ,HAN_GEN_YOTEI.GENBA_NAME_RYAKU AS HANNYUU_JISSEKI_GENBA_NM_YOTEI
	  ,RT.SEQ_NO
  FROM T_MOBISYO_RT RT
  LEFT JOIN T_MOBISYO_RT_DTL RT_DTL ON RT.SEQ_NO = RT_DTL.SEQ_NO
  LEFT JOIN M_GYOUSHA UNPAN ON RT.GENBA_JISSEKI_UPNGYOSHACD = UNPAN.GYOUSHA_CD
  LEFT JOIN M_GYOUSHA GYO ON RT.GENBA_JISSEKI_GYOUSHACD = GYO.GYOUSHA_CD
  LEFT JOIN M_GENBA GEN ON RT.GENBA_JISSEKI_GYOUSHACD = GEN.GYOUSHA_CD AND RT.GENBA_JISSEKI_GENBACD = GEN.GENBA_CD
  LEFT JOIN M_HINMEI HIN ON RT_DTL.GENBA_DETAIL_HINMEICD = HIN.HINMEI_CD
  LEFT JOIN M_UNIT UNI1 ON RT_DTL.GENBA_DETAIL_UNIT_CD1 = UNI1.UNIT_CD
  LEFT JOIN M_UNIT UNI2 ON RT_DTL.GENBA_DETAIL_UNIT_CD2 = UNI2.UNIT_CD
  LEFT JOIN T_MOBISYO_RT_HANNYUU RT_HAN ON RT_DTL.HANYU_SEQ_NO = RT_HAN.HANYU_SEQ_NO
  LEFT JOIN T_MOBISYO_RT_HANNYUU RT_HAN_JISSEKI ON RT_DTL.HANYU_JISSEKI_SEQ_NO = RT_HAN_JISSEKI.HANYU_SEQ_NO
  LEFT JOIN M_GYOUSHA HAN_GYO ON RT_HAN_JISSEKI.HANNYUU_JISSEKI_GYOUSHACD = HAN_GYO.GYOUSHA_CD
  LEFT JOIN M_GENBA HAN_GEN ON RT_HAN_JISSEKI.HANNYUU_JISSEKI_GYOUSHACD = HAN_GEN.GYOUSHA_CD AND RT_HAN_JISSEKI.HANNYUU_JISSEKI_GENBACD = HAN_GEN.GENBA_CD
  LEFT JOIN M_GYOUSHA HAN_GYO_YOTEI ON RT_HAN.HANNYUU_GYOUSHACD = HAN_GYO_YOTEI.GYOUSHA_CD
  LEFT JOIN M_GENBA HAN_GEN_YOTEI ON RT_HAN.HANNYUU_GYOUSHACD = HAN_GEN_YOTEI.GYOUSHA_CD AND RT_HAN.HANNYUU_GENBACD = HAN_GEN_YOTEI.GENBA_CD
 WHERE RT.GENBA_JISSEKI_JYOGAIFLG = 0
   AND RT.DELETE_FLG = 0
   AND (RT_DTL.DELETE_FLG IS NULL OR RT_DTL.DELETE_FLG = 0)
   AND (RT_HAN.DELETE_FLG IS NULL OR RT_DTL.DELETE_FLG = 0)
   --AND RT_HAN_JISSEKI.DELETE_FLG = 0
   AND RT.HAISHA_DENPYOU_NO = /*haishaDenpyouNo*/0
   AND RT.HAISHA_KBN = /*haishaKbn*/0
/*IF haishaKbn != null && haishaKbn.Value == 0*/
ORDER BY
  RT.SEQ_NO
/*END*/ 
 
