SELECT
    TSD.TORIHIKISAKI_CD
FROM T_SEISAN_DETAIL AS TSD
JOIN T_SHUKKIN_ENTRY AS TNE
ON TSD.DENPYOU_SYSTEM_ID = TNE.SYSTEM_ID 
AND TSD.DENPYOU_SEQ = TNE.SEQ
AND TNE.SHUKKIN_NUMBER = /*ShukkinNumber*/
AND TNE.DELETE_FLG = 0
WHERE TSD.DELETE_FLG = 0
AND TSD.DENPYOU_SHURUI_CD = 20