SELECT DISTINCT N'運賃単価マスタ' AS NAME FROM M_UNCHIN_TANKA WHERE UNIT_CD IN /*UNIT_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'運賃品名マスタ' AS NAME FROM M_UNCHIN_HINMEI WHERE UNIT_CD IN /*UNIT_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'基本品名単価マスタ' AS NAME FROM M_KIHON_HINMEI_TANKA WHERE UNIT_CD IN /*UNIT_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'個別品名単価マスタ' AS NAME FROM M_KOBETSU_HINMEI_TANKA WHERE UNIT_CD IN /*UNIT_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'品名マスタ' AS NAME FROM M_HINMEI WHERE UNIT_CD IN /*UNIT_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'マニフェスト換算マスタ' AS NAME FROM M_MANIFEST_KANSAN WHERE UNIT_CD IN /*UNIT_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'現場マスタ' AS NAME FROM M_GENBA AS G
 LEFT JOIN M_GENBA_TEIKI_HINMEI AS GTEIKI ON G.GYOUSHA_CD = GTEIKI.GYOUSHA_CD AND G.GENBA_CD = GTEIKI.GENBA_CD
 LEFT JOIN M_GENBA_TSUKI_HINMEI AS GTSUKI ON G.GYOUSHA_CD = GTSUKI.GYOUSHA_CD AND G.GENBA_CD = GTSUKI.GENBA_CD
 WHERE (GTEIKI.UNIT_CD IN /*UNIT_CD*/('') OR GTEIKI.KANSAN_UNIT_CD IN /*UNIT_CD*/('') OR GTSUKI.UNIT_CD IN /*UNIT_CD*/('')) AND G.DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'引合現場マスタ' AS NAME FROM M_HIKIAI_GENBA AS G
 LEFT JOIN M_HIKIAI_GENBA_TEIKI_HINMEI AS GTEIKI ON G.HIKIAI_GYOUSHA_USE_FLG = GTEIKI.HIKIAI_GYOUSHA_USE_FLG AND G.GYOUSHA_CD = GTEIKI.GYOUSHA_CD AND G.GENBA_CD = GTEIKI.GENBA_CD
 LEFT JOIN M_HIKIAI_GENBA_TSUKI_HINMEI AS GTSUKI ON G.HIKIAI_GYOUSHA_USE_FLG = GTSUKI.HIKIAI_GYOUSHA_USE_FLG AND G.GYOUSHA_CD = GTSUKI.GYOUSHA_CD AND G.GENBA_CD = GTSUKI.GENBA_CD
 WHERE (GTEIKI.UNIT_CD IN /*UNIT_CD*/('') OR GTEIKI.KANSAN_UNIT_CD IN /*UNIT_CD*/('') OR GTSUKI.UNIT_CD IN /*UNIT_CD*/('')) AND G.DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'コースマスタ' AS NAME FROM M_COURSE_DETAIL_ITEMS AS CDI
 INNER JOIN M_COURSE_NAME AS C ON CDI.COURSE_NAME_CD = C.COURSE_NAME_CD
 WHERE (CDI.UNIT_CD IN /*UNIT_CD*/('') OR CDI.KANSAN_UNIT_CD IN /*UNIT_CD*/('')) AND C.DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'システム設定マスタ' AS NAME FROM M_SYS_INFO WHERE (HINMEI_UNIT_CD IN /*UNIT_CD*/('') OR MANI_KANSAN_KIHON_UNIT_CD IN /*UNIT_CD*/('') OR MANI_KANSAN_UNIT_CD IN /*UNIT_CD*/('')) AND DELETE_FLG = 'False'
