SELECT DISTINCT
*
FROM
	M_HINMEI
LEFT JOIN M_SHURUI ON M_HINMEI.SHURUI_CD = M_SHURUI.SHURUI_CD
AND M_SHURUI.DELETE_FLG = 0
WHERE
	1 = 1
AND	M_HINMEI.HINMEI_CD = /*data.HINMEI_CD*/''
AND M_HINMEI.DELETE_FLG = 0
AND (
	M_HINMEI.DENSHU_KBN_CD = CONVERT (SMALLINT, '1')
	OR M_HINMEI.DENSHU_KBN_CD = CONVERT (SMALLINT, '9')
)
ORDER BY
	M_HINMEI.HINMEI_CD