select 
 M_SHAIN.SHAIN_CD as CD,
 M_SHAIN.SHAIN_NAME_RYAKU as NAME,
 M_BUSHO.BUSHO_CD as BUSHO_CD,
 M_BUSHO.BUSHO_NAME_RYAKU as BUSHO_NAME 
FROM M_SHAIN  
 inner Join M_BUSHO
on M_BUSHO.BUSHO_CD = M_SHAIN.BUSHO_CD
 /*$whereSql*/ and M_SHAIN.EIGYOU_TANTOU_KBN = 1