SELECT DISTINCT N'電子事業場マスタ' AS NAME FROM M_DENSHI_JIGYOUJOU WHERE EDI_MEMBER_ID = /*EDI_MEMBER_ID*/
UNION
SELECT DISTINCT N'電子担当者マスタ' AS NAME FROM M_DENSHI_TANTOUSHA WHERE EDI_MEMBER_ID = /*EDI_MEMBER_ID*/ AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'電子廃棄物種類細分類マスタ' AS NAME FROM M_DENSHI_HAIKI_SHURUI_SAIBUNRUI WHERE EDI_MEMBER_ID = /*EDI_MEMBER_ID*/ AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'電子廃棄物名称マスタ' AS NAME FROM M_DENSHI_HAIKI_NAME WHERE EDI_MEMBER_ID = /*EDI_MEMBER_ID*/ AND DELETE_FLG = 'False'