//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shougun.Core.Scale.Keiryou.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SW08RDS01\\SQLEXPRESS2008R2;Persist Security Info=True;User ID=sa;Pass" +
            "word=203388")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DenpyouCtrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DenpyouCtrl"]));
            }
            set {
                this["DenpyouCtrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DetailCtrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DetailCtrl"]));
            }
            set {
                this["DetailCtrl"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>KYOTEN_CD:拠点CD:True:0</string>\r\n  <string>KIHON_KEIRYOU:入出区分:True:1</strin" +
            "g>\r\n  <string>NYUURYOKU_TANTOUSHA_CD:入力担当者:True:4</string>\r\n  <string>KEIRYOU_NU" +
            "MBER:計量番号:True:6</string>\r\n  <string>RENBAN:年連番/日連番:True:9</string>\r\n  <string>U" +
            "KETSUKE_NUMBER:受付番号:True:10</string>\r\n  <string>DENPYOU_DATE:伝票日付:True:11</strin" +
            "g>\r\n  <string>UNPAN_GYOUSHA_CD:運搬業者CD:True:12</string>\r\n  <string>UNPAN_GYOUSHA_" +
            "NAME:運搬業者名:True:13</string>\r\n  <string>SHASHU_CD:車種CD:True:14</string>\r\n  <strin" +
            "g>SHARYOU_CD:車輌CD:True:16</string>\r\n  <string>SHARYOU_NAME_RYAKU:車輌名:True:17</st" +
            "ring>\r\n  <string>UNTENSHA_CD:運転者CD:True:19</string>\r\n  <string>NINZUU_CNT:人数:Tru" +
            "e:21</string>\r\n  <string>GYOUSHA_CD:業者CD:True:22</string>\r\n  <string>GYOUSHA_NAM" +
            "E_RYAKU:業者名:True:23</string>\r\n  <string>GENBA_CD:現場CD:True:24</string>\r\n  <strin" +
            "g>GENBA_NAME_RYAKU:現場名:True:25</string>\r\n  <string>TORIHIKISAKI_CD:取引先CD:True:26" +
            "</string>\r\n  <string>TORIHIKISAKI_NAME_RYAKU:取引先名:True:27</string>\r\n  <string>NI" +
            "ZUMI_GYOUSHA_CD:荷積業者CD:True:29</string>\r\n  <string>NIZUMI_GYOUSHA_NAME:荷積業者名:Tru" +
            "e:30</string>\r\n  <string>NIZUMI_GENBA_CD:荷積現場CD:True:31</string>\r\n  <string>NIZU" +
            "MI_GENBA_NAME:荷積現場名:True:32</string>\r\n  <string>NIOROSHI_GYOUSHA_CD:荷降業者CD:True:" +
            "33</string>\r\n  <string>NIOROSHI_GYOUSHA_NAME:荷降業者名:True:34</string>\r\n  <string>N" +
            "IOROSHI_GENBA_CD:荷降現場CD:True:35</string>\r\n  <string>NIOROSHI_GENBA_NAME:荷降現場名:Tr" +
            "ue:36</string>\r\n  <string>KEITAI_KBN_CD:形態区分CD:True:41</string>\r\n  <string>MANIF" +
            "EST_SHURUI_CD:マニ種類CD:True:44</string>\r\n  <string>MANIFEST_TEHAI_CD:マニ手配CD:True:4" +
            "6</string>\r\n  <string>EIGYOU_TANTOUSHA_CD:営業担当者:True:48</string>\r\n  <string>DENP" +
            "YOU_BIKOU:伝票備考:True:53</string>\r\n  <string>TAIRYUU_BIKOU:滞留備考:True:54</string>\r\n" +
            "</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ApDenpyouCtrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ApDenpyouCtrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>STACK_JYUURYOU:総重量:True:10</string>
  <string>EMPTY_JYUURYOU:空車重量:True:20</string>
  <string>WARIFURI_JYUURYOU:割振(Kg):True:30</string>
  <string>WARIFURI_PERCENT:割振(%):True:40</string>
  <string>CHOUSEI_JYUURYOU:調整(Kg):True:50</string>
  <string>CHOUSEI_PERCENT:調整(%):True:60</string>
  <string>YOUKI_CD:容器CD:True:70</string>
  <string>YOUKI_SUURYOU:容器数量:True:80</string>
  <string>YOUKI_JYUURYOU:容器重量:True:90</string>
  <string>HINMEI_CD:品名CD:True:100</string>
  <string>NISUGATA_SUURYOU:荷姿数量:True:150</string>
  <string>NISUGATA_UNIT_CD:荷姿単位CD:True:160</string>
  <string>MANIFEST_ID:ﾏﾆﾌｪｽﾄ番号:True:170</string>
  <string>MEISAI_BIKOU:明細備考:True:180</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ApDetailCtrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ApDetailCtrl"]));
            }
        }
    }
}
