SELECT
    ADJUST.TORIHIKISAKI_CD,
    ADJUST.SEQ,
    ADJUST.UPDATE_SEQ,
    ADJUST.CREATE_USER,
    ADJUST.CREATE_DATE,
    ADJUST.CREATE_PC,
    ADJUST.DELETE_FLG,
    ADJUST.TIME_STAMP
FROM
    T_MONTHLY_ADJUST_SH AS ADJUST
    INNER JOIN
        (
            SELECT
                ROW_NUMBER () OVER (PARTITION BY A.TORIHIKISAKI_CD, A.YEAR, A.MONTH, A.SEQ ORDER BY A.TORIHIKISAKI_CD, A.YEAR, A.MONTH, A.SEQ DESC, A.UPDATE_SEQ DESC) AS ROW,
                A.TORIHIKISAKI_CD,
                A.YEAR,
                A.MONTH,
                A.SEQ,
                A.UPDATE_SEQ
            FROM
                T_MONTHLY_ADJUST_SH AS A
                INNER JOIN
                    T_MONTHLY_LOCK_SH AS L
                ON  A.TORIHIKISAKI_CD = L.TORIHIKISAKI_CD
                AND A.YEAR = L.YEAR
                AND A.MONTH = L.MONTH
                AND A.SEQ = L.SEQ
            WHERE
                A.YEAR = /*year*/2015
            AND A.MONTH = /*month*/1
            AND L.DELETE_FLG = 0
        ) AS MAX_ADJUST
    ON  ADJUST.TORIHIKISAKI_CD = MAX_ADJUST.TORIHIKISAKI_CD
    AND ADJUST.YEAR = MAX_ADJUST.YEAR
    AND ADJUST.MONTH = MAX_ADJUST.MONTH
    AND ADJUST.SEQ = MAX_ADJUST.SEQ
    AND ADJUST.UPDATE_SEQ = MAX_ADJUST.UPDATE_SEQ
WHERE
    MAX_ADJUST.ROW = 1
