SELECT T_SEIKYUU_DENPYOU.SEIKYUU_NUMBER
FROM   T_SEIKYUU_DENPYOU
       LEFT JOIN T_SEIKYUU_DENPYOU_INXS
              ON T_SEIKYUU_DENPYOU_INXS.SEIKYUU_NUMBER = T_SEIKYUU_DENPYOU.SEIKYUU_NUMBER
       LEFT JOIN M_TORIHIKISAKI_SEIKYUU
              ON T_SEIKYUU_DENPYOU.TORIHIKISAKI_CD = M_TORIHIKISAKI_SEIKYUU.TORIHIKISAKI_CD
WHERE  T_SEIKYUU_DENPYOU.DELETE_FLG = 0
       AND M_TORIHIKISAKI_SEIKYUU.INXS_SEIKYUU_KBN = 1
       AND T_SEIKYUU_DENPYOU_INXS.UPLOAD_STATUS IN ( 2, 5 ) 
	   AND T_SEIKYUU_DENPYOU.SEIKYUU_NUMBER =  /*seikyuuNumber*/