SELECT
top 1 *
FROM
T_SEIKYUU_DENPYOU
WHERE
TORIHIKISAKI_CD =  /*seikyuCd*/
/*IF selectFlg */
AND SEIKYUU_DATE = CONVERT(DATETIME ,/*seikyuuDate*/,120)
/*END*/
/*IF !selectFlg */
AND SEIKYUU_DATE < CONVERT(DATETIME ,/*seikyuuDate*/,120)
/*END*/
AND DELETE_FLG = 0
ORDER BY
SEIKYUU_DATE DESC