SELECT
*
FROM
T_SHIME_SHORI_CHUU
WITH(TABLOCKX)
/*BEGIN*/WHERE
/*IF data.URIAGE_SHIHARAI_KBN != null*/
SHORI_KBN = /*data.URIAGE_SHIHARAI_KBN*//*END*/
/*IF data.TORIHIKISAKI_CD != null && data.TORIHIKISAKI_CD != ""*/
 AND TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*//*END*/
/*END*/