DELETE dbo.T_SHIME_SHORI_CHUU
WHERE 
1 = 1
/*IF !data.SHIME_JIKKOU_NO.IsNull*/AND SHIME_JIKKOU_NO = /*data.SHIME_JIKKOU_NO*//*END*/
/*IF data.TORIHIKISAKI_CD != null*/AND TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*//*END*/
/*IF !data.SHORI_KBN.IsNull*/AND SHORI_KBN = /*data.SHORI_KBN*//*END*/
/*IF !data.SHORI_DENPYOU_SHURUI.IsNull*/AND SHORI_DENPYOU_SHURUI = /*data.SHORI_DENPYOU_SHURUI*//*END*/
/*IF !data.KYOTEN_CD.IsNull*/AND KYOTEN_CD = /*data.KYOTEN_CD*//*END*/
/*IF !data.HIDUKE_HANI_BEGIN.IsNull*/AND HIDUKE_HANI_BEGIN = /*data.HIDUKE_HANI_BEGIN*//*END*/
/*IF data.SEARCH_HIDUKE_HANI_BEGIN != null*/AND SEARCH_HIDUKE_HANI_BEGIN = /*data.SEARCH_HIDUKE_HANI_BEGIN*//*END*/
/*IF !data.HIDUKE_HANI_END.IsNull*/AND HIDUKE_HANI_END = /*data.HIDUKE_HANI_END*//*END*/
/*IF data.SEARCH_HIDUKE_HANI_END != null*/AND SEARCH_HIDUKE_HANI_END = /*data.SEARCH_HIDUKE_HANI_END*//*END*/
/*IF data.CLIENT_COMPUTER_NAME != null*/AND CLIENT_COMPUTER_NAME = /*data.CLIENT_COMPUTER_NAME*//*END*/
/*IF data.CLIENT_USER_NAME != null*/AND CLIENT_USER_NAME = /*data.CLIENT_USER_NAME*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/