SELECT
	TE.NYUUKIN_NUMBER AS DENPYOU_NUMBER, 
	TE.DENPYOU_DATE, 
	'' AS URIAGE_ZEI_KEISAN_KBN_CD,
	NULL AS SEIKYU_SHIMEBI, 
	NULL AS GYOUSHA_NAME, 
	NULL AS GENBA_NAME, 
	(ISNULL(TE.NYUUKIN_AMOUNT_TOTAL, 0) + ISNULL(TE.CHOUSEI_AMOUNT_TOTAL, 0)) AS KINGAKU,
	0 AS HINMEI_SOTO_ZEI_COUNT,
	0 AS HINMEI_NASI_ZEI_COUNT,
	0 AS URIAGE_ZEI_KBN_CD
FROM
	T_NYUUKIN_ENTRY TE
WHERE
TE.DELETE_FLG = 0
/*IF data.KYOTEN_CD != 99*/
AND TE.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/ 		
/*IF data.SEIKYU_CD != null && data.SEIKYU_CD != ""*/
AND TE.TORIHIKISAKI_CD = /*data.SEIKYU_CD*/
/*END*/ 
/*IF data.SEIKYUSHIMEBI_FROM != null && data.SEIKYUSHIMEBI_FROM != ""*/
	AND CONVERT(DATETIME, TE.DENPYOU_DATE,111) >= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_FROM*/null,111)
/*END*/ 
/*IF data.SEIKYUSHIMEBI_TO != null && data.SEIKYUSHIMEBI_TO != ""*/
	AND CONVERT(DATETIME, TE.DENPYOU_DATE,111) <= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_TO*/,111)
/*END*/ 
AND (NOT EXISTS
	(
	SELECT 1
	FROM              
	    T_SEIKYUU_DETAIL SEID
	WHERE
	    TE.SYSTEM_ID = SEID.DENPYOU_SYSTEM_ID
	    AND TE.SEQ = SEID.DENPYOU_SEQ
	    AND SEID.DENPYOU_SHURUI_CD = 10
	    AND SEID.DELETE_FLG = 0
	)
	)

ORDER BY 
	TE.DENPYOU_DATE,
	TE.NYUUKIN_NUMBER
		