SELECT
    SHE.SHUKKA_NUMBER AS DENPYOU_NUMBER, 
    SHE.DENPYOU_DATE, 
	CASE WHEN SHE.KENSHU_MUST_KBN = 1
	THEN
		SHE.KENSHU_URIAGE_DATE
	ELSE
		SHE.URIAGE_DATE 
	END
	AS SEIKYU_SHIMEBI, 
	SHE.URIAGE_ZEI_KEISAN_KBN_CD,
    SHE.GYOUSHA_NAME,
    SHE.GENBA_NAME, 
    CASE WHEN SHE.KENSHU_MUST_KBN = 1
    THEN
		(ISNULL(SHE.KENSHU_URIAGE_AMOUNT_TOTAL, 0) + ISNULL(SHE.KENSHU_HINMEI_URIAGE_KINGAKU_TOTAL, 0))
    ELSE
		(ISNULL(SHE.URIAGE_AMOUNT_TOTAL, 0) + ISNULL(SHE.HINMEI_URIAGE_KINGAKU_TOTAL, 0))
    END
    AS KINGAKU,
	ISNULL(HIN_COUNT.HIN_SOTO,0) AS HINMEI_SOTO_ZEI_COUNT,
	ISNULL(HIN_COUNT.HIN_NASI,0) AS HINMEI_NASI_ZEI_COUNT,
	SHE.URIAGE_ZEI_KBN_CD
FROM
    T_SHUKKA_ENTRY AS SHE
	LEFT JOIN (
			SELECT 
				COUNT_TABLE.SYSTEM_ID, COUNT(COUNT_TABLE.SOTO) AS HIN_SOTO, COUNT(COUNT_TABLE.NASI) AS HIN_NASI
			FROM (
				SELECT
					SE.SYSTEM_ID , 
					CASE WHEN HINMEI_ZEI_KBN_CD = 1 THEN COUNT(HINMEI_ZEI_KBN_CD) END AS SOTO,
					CASE WHEN HINMEI_ZEI_KBN_CD is null THEN COUNT(HINMEI_ZEI_KBN_CD) END AS NASI
				FROM
					T_SHUKKA_ENTRY SE INNER JOIN T_SHUKKA_DETAIL SD
				ON SE.SYSTEM_ID = SD.SYSTEM_ID 
					AND SE.SEQ = SD.SEQ 
					/*IF data.KYOTEN_CD != 99*/AND SE.KYOTEN_CD = /*data.KYOTEN_CD*//*END*/ 		
					AND SE.URIAGE_TORIHIKI_KBN_CD = 2 
					AND SE.KAKUTEI_KBN = 1 
					AND SE.TAIRYUU_KBN = 0 
					AND SD.DENPYOU_KBN_CD = 1
					/*IF !deletechuFlg*/AND SE.DELETE_FLG = 0/*END*/
					/*IF data.SEIKYU_CD != null && data.SEIKYU_CD != ""*/AND SE.TORIHIKISAKI_CD = /*data.SEIKYU_CD*//*END*/ 
					/*IF data.SEIKYUSHIMEBI_FROM != null && data.SEIKYUSHIMEBI_FROM != ""*/
						AND CONVERT(DATETIME, SE.URIAGE_DATE,111) >= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_FROM*/null,111)
					/*END*/ 
					/*IF data.SEIKYUSHIMEBI_TO != null && data.SEIKYUSHIMEBI_TO != ""*/
						AND CONVERT(DATETIME, SE.URIAGE_DATE,111) <= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_TO*/,111)
					/*END*/ 
				WHERE (SE.KENSHU_MUST_KBN != 1 OR SE.KENSHU_MUST_KBN IS NULL)
					GROUP BY SE.SYSTEM_ID, HINMEI_ZEI_KBN_CD
				UNION ALL (
					SELECT
						SE.SYSTEM_ID , 
						CASE WHEN KD.HINMEI_ZEI_KBN_CD = 1 THEN COUNT(KD.HINMEI_ZEI_KBN_CD) END AS SOTO,
						CASE WHEN KD.HINMEI_ZEI_KBN_CD is null THEN COUNT(KD.HINMEI_ZEI_KBN_CD) END AS NASI
					FROM
						T_SHUKKA_ENTRY SE 
					INNER JOIN T_SHUKKA_DETAIL SD
						ON SE.SYSTEM_ID = SD.SYSTEM_ID 
						AND SE.SEQ = SD.SEQ 
						AND SE.URIAGE_TORIHIKI_KBN_CD = 2 
						AND SE.KAKUTEI_KBN = 1 
						AND SE.TAIRYUU_KBN = 0 
						AND SD.DENPYOU_KBN_CD = 1
						/*IF !deletechuFlg*/AND SE.DELETE_FLG = 0/*END*/
						/*IF data.SEIKYU_CD != null && data.SEIKYU_CD != ""*/AND SE.TORIHIKISAKI_CD = /*data.SEIKYU_CD*//*END*/ 
					LEFT JOIN T_KENSHU_DETAIL KD
					ON KD.SYSTEM_ID = SD.SYSTEM_ID 
						AND KD.SEQ = SD.SEQ 
						AND KD.DETAIL_SYSTEM_ID = SD.DETAIL_SYSTEM_ID
						AND KD.ROW_NO = SD.ROW_NO
						AND KD.DENPYOU_KBN_CD = 1
					WHERE SE.KENSHU_MUST_KBN = 1
						/*IF data.SEIKYUSHIMEBI_FROM != null && data.SEIKYUSHIMEBI_FROM != ""*/
							AND CONVERT(DATETIME, SE.KENSHU_URIAGE_DATE,111) >= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_FROM*/null,111)
						/*END*/ 
						/*IF data.SEIKYUSHIMEBI_TO != null && data.SEIKYUSHIMEBI_TO != ""*/
							AND CONVERT(DATETIME, SE.KENSHU_URIAGE_DATE,111) <= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_TO*/,111)
						/*END*/ 
						GROUP BY SE.SYSTEM_ID, KD.HINMEI_ZEI_KBN_CD
					)
				) AS COUNT_TABLE
			GROUP BY COUNT_TABLE.SYSTEM_ID
		) AS HIN_COUNT
	ON SHE.SYSTEM_ID = HIN_COUNT.SYSTEM_ID
WHERE
	(EXISTS
		(
		SELECT
			DISTINCT SE.SYSTEM_ID 
		FROM
			T_SHUKKA_ENTRY SE INNER JOIN T_SHUKKA_DETAIL SD
		ON SE.SYSTEM_ID = SD.SYSTEM_ID 
			AND SE.SEQ = SD.SEQ 
	        /*IF data.KYOTEN_CD != 99*/AND SE.KYOTEN_CD = /*data.KYOTEN_CD*//*END*/ 		
			AND SE.URIAGE_TORIHIKI_KBN_CD = 2 
			AND SE.KAKUTEI_KBN = 1 
			AND SE.TAIRYUU_KBN = 0 
			AND SD.DENPYOU_KBN_CD = 1
			/*IF !deletechuFlg*/AND SE.DELETE_FLG = 0/*END*/
			/*IF data.SEIKYU_CD != null && data.SEIKYU_CD != ""*/AND SE.TORIHIKISAKI_CD = /*data.SEIKYU_CD*//*END*/ 
			/*IF data.SEIKYUSHIMEBI_FROM != null && data.SEIKYUSHIMEBI_FROM != ""*/
				AND CONVERT(DATETIME, SE.URIAGE_DATE,111) >= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_FROM*/null,111)
			/*END*/ 
			/*IF data.SEIKYUSHIMEBI_TO != null && data.SEIKYUSHIMEBI_TO != ""*/
				AND CONVERT(DATETIME, SE.URIAGE_DATE,111) <= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_TO*/,111)
			/*END*/ 
		WHERE SHE.SYSTEM_ID = SE.SYSTEM_ID
			AND (SHE.KENSHU_MUST_KBN != 1 OR SHE.KENSHU_MUST_KBN IS NULL)
		UNION ALL (
			SELECT
				DISTINCT SE.SYSTEM_ID 
			FROM
				T_SHUKKA_ENTRY SE 
			INNER JOIN T_SHUKKA_DETAIL SD
				ON SE.SYSTEM_ID = SD.SYSTEM_ID 
				AND SE.SEQ = SD.SEQ 
				AND SE.URIAGE_TORIHIKI_KBN_CD = 2 
				AND SE.KAKUTEI_KBN = 1 
				AND SE.TAIRYUU_KBN = 0 
                AND SD.DENPYOU_KBN_CD = 1
				/*IF !deletechuFlg*/AND SE.DELETE_FLG = 0/*END*/
				/*IF data.SEIKYU_CD != null && data.SEIKYU_CD != ""*/AND SE.TORIHIKISAKI_CD = /*data.SEIKYU_CD*//*END*/ 
			LEFT JOIN T_KENSHU_DETAIL KD
			ON KD.SYSTEM_ID = SD.SYSTEM_ID 
				AND KD.SEQ = SD.SEQ 
				AND KD.DETAIL_SYSTEM_ID = SD.DETAIL_SYSTEM_ID
				AND KD.ROW_NO = SD.ROW_NO
				AND KD.DENPYOU_KBN_CD = 1
			WHERE SHE.SYSTEM_ID = SE.SYSTEM_ID
				AND SHE.KENSHU_MUST_KBN = 1
				/*IF data.SEIKYUSHIMEBI_FROM != null && data.SEIKYUSHIMEBI_FROM != ""*/
					AND CONVERT(DATETIME, SE.KENSHU_URIAGE_DATE,111) >= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_FROM*/null,111)
				/*END*/ 
				/*IF data.SEIKYUSHIMEBI_TO != null && data.SEIKYUSHIMEBI_TO != ""*/
					AND CONVERT(DATETIME, SE.KENSHU_URIAGE_DATE,111) <= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_TO*/,111)
				/*END*/ 
			)
		)
	)
	AND (NOT EXISTS
	    (
	    SELECT
	        SHE.SYSTEM_ID, SHE.SEQ
	    FROM              
	        T_SEIKYUU_DETAIL SEID
	    WHERE
	        SHE.SYSTEM_ID = SEID.DENPYOU_SYSTEM_ID
	        AND SHE.SEQ = SEID.DENPYOU_SEQ
	        AND SEID.DENPYOU_SHURUI_CD = '2'
	        AND SEID.DELETE_FLG = 0
	    )
		)
	/*IF !deletechuFlg*/AND SHE.DELETE_FLG = 0/*END*/
