SELECT
	UKE.UKEIRE_NUMBER AS DENPYOU_NUMBER, 
	UKE.DENPYOU_DATE, 
	UKE.URIAGE_ZEI_KEISAN_KBN_CD,
	UKE.URIAGE_DATE AS SEIKYU_SHIMEBI, 
	UKE.GYOUSHA_NAME, 
	UKE.GENBA_NAME, 
	(ISNULL(UKE.URIAGE_KINGAKU_TOTAL, 0) + ISNULL(UKE.HINMEI_URIAGE_KINGAKU_TOTAL, 0)) AS KINGAKU,
	ISNULL(HIN_COUNT.HIN_SOTO,0) AS HINMEI_SOTO_ZEI_COUNT,
	ISNULL(HIN_COUNT.HIN_NASI,0) AS HINMEI_NASI_ZEI_COUNT, 
	UKE.URIAGE_ZEI_KBN_CD
FROM
	T_UKEIRE_ENTRY UKE
	LEFT JOIN 
		(
			SELECT 
				COUNT_TABLE.SYSTEM_ID, COUNT(COUNT_TABLE.SOTO) AS HIN_SOTO, COUNT(COUNT_TABLE.NASI) AS HIN_NASI
			FROM (
				SELECT
					UE.SYSTEM_ID,
					CASE WHEN HINMEI_ZEI_KBN_CD = 1 THEN COUNT(HINMEI_ZEI_KBN_CD) END AS SOTO,
					CASE WHEN HINMEI_ZEI_KBN_CD is null THEN COUNT(HINMEI_ZEI_KBN_CD) END AS NASI
				FROM
					T_UKEIRE_ENTRY UE INNER JOIN T_UKEIRE_DETAIL UD
				ON UE.SYSTEM_ID = UD.SYSTEM_ID 
					AND UE.SEQ = UD.SEQ 
					/*IF data.KYOTEN_CD != 99*/AND UE.KYOTEN_CD = /*data.KYOTEN_CD*//*END*/ 		
					AND UE.URIAGE_TORIHIKI_KBN_CD = 2 
					AND UE.KAKUTEI_KBN = 1 
					AND UE.TAIRYUU_KBN = 0 
					AND UD.DENPYOU_KBN_CD = 1
					/*IF !deletechuFlg*/AND UE.DELETE_FLG = 0/*END*/
					/*IF data.SEIKYU_CD != null && data.SEIKYU_CD != ""*/AND UE.TORIHIKISAKI_CD = /*data.SEIKYU_CD*//*END*/ 
					/*IF data.SEIKYUSHIMEBI_FROM != null && data.SEIKYUSHIMEBI_FROM != ""*/ 
						AND CONVERT(DATETIME, UE.URIAGE_DATE,111) >= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_FROM*/null,111)
					/*END*/ 
					/*IF data.SEIKYUSHIMEBI_TO != null && data.SEIKYUSHIMEBI_TO != ""*/
						AND CONVERT(DATETIME, UE.URIAGE_DATE,111) <= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_TO*/,111)
					/*END*/ 
				GROUP BY UE.SYSTEM_ID,HINMEI_ZEI_KBN_CD
			) AS COUNT_TABLE
			GROUP BY COUNT_TABLE.SYSTEM_ID
		) AS HIN_COUNT
	ON UKE.SYSTEM_ID = HIN_COUNT.SYSTEM_ID
WHERE
	(EXISTS
		(
		SELECT
			DISTINCT UE.SYSTEM_ID
		FROM
			T_UKEIRE_ENTRY UE INNER JOIN T_UKEIRE_DETAIL UD
		ON UE.SYSTEM_ID = UD.SYSTEM_ID 
			AND UE.SEQ = UD.SEQ 
	        /*IF data.KYOTEN_CD != 99*/AND UE.KYOTEN_CD = /*data.KYOTEN_CD*//*END*/ 		
			AND UE.URIAGE_TORIHIKI_KBN_CD = 2 
			AND UE.KAKUTEI_KBN = 1 
			AND UE.TAIRYUU_KBN = 0 
			AND UD.DENPYOU_KBN_CD = 1
			/*IF !deletechuFlg*/AND UE.DELETE_FLG = 0/*END*/
			/*IF data.SEIKYU_CD != null && data.SEIKYU_CD != ""*/AND UE.TORIHIKISAKI_CD = /*data.SEIKYU_CD*//*END*/
			/*IF data.SEIKYUSHIMEBI_FROM != null && data.SEIKYUSHIMEBI_FROM != ""*/ 
			AND CONVERT(DATETIME, UE.URIAGE_DATE,111) >= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_FROM*/null,111)
			/*END*/ 
			/*IF data.SEIKYUSHIMEBI_TO != null && data.SEIKYUSHIMEBI_TO != ""*/
			AND CONVERT(DATETIME, UE.URIAGE_DATE,111) <= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_TO*/,111)
			/*END*/ 
		WHERE UKE.SYSTEM_ID = UE.SYSTEM_ID
	)
	)
	AND (NOT EXISTS
	    (
	    SELECT
	        UKE.SYSTEM_ID, UKE.SEQ
	    FROM              
	        T_SEIKYUU_DETAIL SEID
	    WHERE
	        UKE.SYSTEM_ID = SEID.DENPYOU_SYSTEM_ID
	        AND UKE.SEQ = SEID.DENPYOU_SEQ
	        AND SEID.DENPYOU_SHURUI_CD = '1'
	        AND SEID.DELETE_FLG = 0
	    )
		)
	/*IF !deletechuFlg*/AND UKE.DELETE_FLG = 0/*END*/
