SELECT
KAISHUU_MONTH,
KAISHUU_DAY,
ISNULL(KAISHUU_BETSU_KBN, 0) AS KAISHUU_BETSU_KBN,
ISNULL(KAISHUU_BETSU_NICHIGO, 0) AS KAISHUU_BETSU_NICHIGO
FROM
M_TORIHIKISAKI_SEIKYUU
/*BEGIN*/WHERE
/*IF data.TORIHIKISAKI_CD != null */
TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*//*END*/
/*END*/