SELECT
TORIHIKISAKI_CD,
TORIHIKISAKI_NAME_RYAKU
FROM
M_TORIHIKISAKI
/*BEGIN*/WHERE
/*IF data.TORIHIKISAKI_CD != null && data.TORIHIKISAKI_CD != ""*/
AND TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*//*END*/
/*END*/
ORDER BY TORIHIKISAKI_CD