SELECT
T_S.SYSTEM_ID,
T_S.SEQ,
T_S.SHUKKA_NUMBER AS DENPYONO,
T_S.DENPYOU_DATE,
T_S.URIAGE_DATE,
T_S.TORIHIKISAKI_CD,
T_S.GYOUSHA_CD,
T_S.GENBA_CD,
T_S.URIAGE_AMOUNT_TOTAL,
T_S.URIAGE_TAX_SOTO,
T_S.URIAGE_TAX_UCHI,
T_S.URIAGE_TAX_SOTO_TOTAL,
T_S.URIAGE_TAX_UCHI_TOTAL,
T_S.HINMEI_URIAGE_KINGAKU_TOTAL,
T_S.HINMEI_URIAGE_TAX_SOTO_TOTAL,
T_S.HINMEI_URIAGE_TAX_UCHI_TOTAL,
T_S.URIAGE_ZEI_KEISAN_KBN_CD,
T_S.URIAGE_ZEI_KBN_CD,
T_S.URIAGE_SHOUHIZEI_RATE,
T_S.SHARYOU_NAME,
--T_S_D.SYSTEM_ID,
--T_S_D.SEQ,
T_S_D.DETAIL_SYSTEM_ID,
T_S_D.SHUKKA_NUMBER,
T_S_D.DENPYOU_KBN_CD,
T_S_D.HINMEI_CD,
--T_S_D.HINMEI_NAME,
T_S_D.SUURYOU,
T_S_D.UNIT_CD,
T_S_D.KINGAKU,
T_S_D.TAX_SOTO,
T_S_D.TAX_UCHI,
T_S_D.HINMEI_KINGAKU,
T_S_D.HINMEI_TAX_SOTO,
T_S_D.HINMEI_TAX_UCHI,
T_S_D.HINMEI_ZEI_KBN_CD,
T_S_D.MEISAI_BIKOU,
T_S_D.TANKA,
T_S_D.ROW_NO,

M_GYOUSHA.SEIKYUU_DAIHYOU_PRINT_KBN AS GY_SEIKYUU_DAIHYOU_PRINT_KBN,
M_GYOUSHA.SEIKYUU_KYOTEN_PRINT_KBN AS GY_SEIKYUU_KYOTEN_PRINT_KBN,
M_GYOUSHA.SEIKYUU_KYOTEN_CD AS GY_SEIKYUU_KYOTEN_CD,
M_GYOUSHA.SEIKYUU_SOUFU_NAME1 AS GY_SEIKYUU_SOUFU_NAME1,
M_GYOUSHA.SEIKYUU_SOUFU_NAME2 AS GY_SEIKYUU_SOUFU_NAME2,
M_GYOUSHA.SEIKYUU_SOUFU_KEISHOU1 AS GY_SEIKYUU_SOUFU_KEISHOU1,
M_GYOUSHA.SEIKYUU_SOUFU_KEISHOU2 AS GY_SEIKYUU_SOUFU_KEISHOU2,
M_GYOUSHA.SEIKYUU_SOUFU_POST AS GY_SEIKYUU_SOUFU_POST,
M_GYOUSHA.SEIKYUU_SOUFU_ADDRESS1 AS GY_SEIKYUU_SOUFU_ADDRESS1,
M_GYOUSHA.SEIKYUU_SOUFU_ADDRESS2 AS GY_SEIKYUU_SOUFU_ADDRESS2,
M_GYOUSHA.SEIKYUU_SOUFU_BUSHO AS GY_SEIKYUU_SOUFU_BUSHO,
M_GYOUSHA.SEIKYUU_SOUFU_TANTOU AS GY_SEIKYUU_SOUFU_TANTOU,
M_GYOUSHA.SEIKYUU_SOUFU_TEL AS GY_SEIKYUU_SOUFU_TEL,
M_GYOUSHA.SEIKYUU_SOUFU_FAX AS GY_SEIKYUU_SOUFU_FAX,
M_GYOUSHA.SEIKYUU_TANTOU AS GY_SEIKYUU_TANTOU,
M_GYOUSHA.GYOUSHA_NAME1,
M_GYOUSHA.GYOUSHA_NAME2,

M_GYOUSHA_KYOTEN.KYOTEN_NAME AS GY_KYOTEN_NAME,
M_GYOUSHA_KYOTEN.KYOTEN_DAIHYOU AS GY_KYOTEN_DAIHYOU,
M_GYOUSHA_KYOTEN.KYOTEN_POST AS GY_KYOTEN_POST,
M_GYOUSHA_KYOTEN.KYOTEN_ADDRESS1 AS GY_KYOTEN_ADDRESS1,
M_GYOUSHA_KYOTEN.KYOTEN_ADDRESS2 AS GY_KYOTEN_ADDRESS2,
M_GYOUSHA_KYOTEN.KYOTEN_TEL AS GY_KYOTEN_TEL,
M_GYOUSHA_KYOTEN.KYOTEN_FAX AS GY_KYOTEN_FAX,

M_GENBA.GENBA_CD,
M_GENBA.SEIKYUU_DAIHYOU_PRINT_KBN AS GE_SEIKYUU_DAIHYOU_PRINT_KBN,
M_GENBA.SEIKYUU_KYOTEN_PRINT_KBN AS GE_SEIKYUU_KYOTEN_PRINT_KBN,
M_GENBA.SEIKYUU_KYOTEN_CD AS GE_SEIKYUU_KYOTEN_CD,
M_GENBA.SEIKYUU_SOUFU_NAME1 AS GE_SEIKYUU_SOUFU_NAME1,
M_GENBA.SEIKYUU_SOUFU_NAME2 AS GE_SEIKYUU_SOUFU_NAME2,
M_GENBA.SEIKYUU_SOUFU_KEISHOU1 AS GE_SEIKYUU_SOUFU_KEISHOU1,
M_GENBA.SEIKYUU_SOUFU_KEISHOU2 AS GE_SEIKYUU_SOUFU_KEISHOU2,
M_GENBA.SEIKYUU_SOUFU_POST AS GE_SEIKYUU_SOUFU_POST,
M_GENBA.SEIKYUU_SOUFU_ADDRESS1 AS GE_SEIKYUU_SOUFU_ADDRESS1,
M_GENBA.SEIKYUU_SOUFU_ADDRESS2 AS GE_SEIKYUU_SOUFU_ADDRESS2,
M_GENBA.SEIKYUU_SOUFU_BUSHO AS GE_SEIKYUU_SOUFU_BUSHO,
M_GENBA.SEIKYUU_SOUFU_TANTOU AS GE_SEIKYUU_SOUFU_TANTOU,
M_GENBA.SEIKYUU_SOUFU_TEL AS GE_SEIKYUU_SOUFU_TEL,
M_GENBA.SEIKYUU_SOUFU_FAX AS GE_SEIKYUU_SOUFU_FAX,
M_GENBA.SEIKYUU_TANTOU AS GE_SEIKYUU_TANTOU,
M_GENBA.GENBA_NAME1,
M_GENBA.GENBA_NAME2,

M_GENBA_KYOTEN.KYOTEN_NAME AS GE_KYOTEN_NAME,
M_GENBA_KYOTEN.KYOTEN_DAIHYOU AS GE_KYOTEN_DAIHYOU,
M_GENBA_KYOTEN.KYOTEN_POST AS GE_KYOTEN_POST,
M_GENBA_KYOTEN.KYOTEN_ADDRESS1 AS GE_KYOTEN_ADDRESS1,
M_GENBA_KYOTEN.KYOTEN_ADDRESS2 AS GE_KYOTEN_ADDRESS2,
M_GENBA_KYOTEN.KYOTEN_TEL AS GE_KYOTEN_TEL,
M_GENBA_KYOTEN.KYOTEN_FAX AS GE_KYOTEN_FAX,

M_UNIT.UNIT_NAME,

M_KYOTEN.KYOTEN_NAME,
M_KYOTEN.KYOTEN_DAIHYOU,
M_KYOTEN.KYOTEN_POST,
M_KYOTEN.KYOTEN_ADDRESS1,
M_KYOTEN.KYOTEN_ADDRESS2,
M_KYOTEN.KYOTEN_TEL,
M_KYOTEN.KYOTEN_FAX,

M_T.SEIKYUU_DAIHYOU_PRINT_KBN,
M_T.SEIKYUU_SOUFU_NAME1,
M_T.SEIKYUU_SOUFU_NAME2,
M_T.SEIKYUU_SOUFU_KEISHOU1,
M_T.SEIKYUU_SOUFU_KEISHOU2,
M_T.SEIKYUU_SOUFU_POST,
M_T.SEIKYUU_SOUFU_ADDRESS1,
M_T.SEIKYUU_SOUFU_ADDRESS2,
M_T.SEIKYUU_KYOTEN_PRINT_KBN,
M_T.SEIKYUU_KYOTEN_CD,
M_T.SEIKYUU_SOUFU_BUSHO,
M_T.SEIKYUU_SOUFU_TANTOU,
M_T.SEIKYUU_SOUFU_TEL,
M_T.SEIKYUU_SOUFU_FAX,
M_T.SEIKYUU_TANTOU,
M_T.SHOSHIKI_KBN,

M_TORIHIKISAKI_KYOTEN.KYOTEN_NAME AS TR_KYOTEN_NAME,
M_TORIHIKISAKI_KYOTEN.KYOTEN_DAIHYOU AS TR_KYOTEN_DAIHYOU,
M_TORIHIKISAKI_KYOTEN.KYOTEN_POST AS TR_KYOTEN_POST,
M_TORIHIKISAKI_KYOTEN.KYOTEN_ADDRESS1 AS TR_KYOTEN_ADDRESS1,
M_TORIHIKISAKI_KYOTEN.KYOTEN_ADDRESS2 AS TR_KYOTEN_ADDRESS2,
M_TORIHIKISAKI_KYOTEN.KYOTEN_TEL AS TR_KYOTEN_TEL,
M_TORIHIKISAKI_KYOTEN.KYOTEN_FAX AS TR_KYOTEN_FAX,

M_C.CORP_NAME,
M_C.CORP_DAIHYOU,

T_S_D.HINMEI_NAME,
'' as KENSHU_SYSTEM_ID

FROM
T_SHUKKA_ENTRY T_S
INNER JOIN T_SHUKKA_DETAIL T_S_D 
ON T_S.SYSTEM_ID = T_S_D.SYSTEM_ID 
AND T_S.SEQ = T_S_D.SEQ 
AND T_S_D.DENPYOU_KBN_CD = '1'
LEFT JOIN 
(
	SELECT 
		COUNT_TABLE.SYSTEM_ID, COUNT_TABLE.SEQ, COUNT(COUNT_TABLE.SOTO) AS HIN_SOTO, COUNT(COUNT_TABLE.NASI) AS HIN_NASI
		FROM (
			SELECT
				E.SYSTEM_ID, E.SEQ, 
				CASE WHEN HINMEI_ZEI_KBN_CD = 1 THEN COUNT(HINMEI_ZEI_KBN_CD) END AS SOTO,
				CASE WHEN HINMEI_ZEI_KBN_CD is null THEN COUNT(HINMEI_ZEI_KBN_CD) END AS NASI
			FROM
				T_SHUKKA_ENTRY E INNER JOIN T_SHUKKA_DETAIL D
			ON E.SYSTEM_ID = D.SYSTEM_ID 
				AND E.SEQ = D.SEQ 
				AND E.TORIHIKISAKI_CD = /*data.SEIKYU_CD*/
				/*IF data.SEIKYUSHIMEBI_FROM != "" && data.SEIKYUSHIMEBI_FROM != null*/
				AND CONVERT(DateTime,/*data.SEIKYUSHIMEBI_FROM*/nul, 111) <= E.URIAGE_DATE/*END*/
				AND E.URIAGE_DATE <= CONVERT(DateTime,/*data.SEIKYUSHIMEBI_TO*/null, 111)
				AND E.DELETE_FLG = '0'
				AND E.TAIRYUU_KBN = 0
				AND E.KAKUTEI_KBN = '1' 
				AND D.DENPYOU_KBN_CD = '1'
				AND E.URIAGE_TORIHIKI_KBN_CD = '2' 
				AND (E.KENSHU_MUST_KBN != 1 OR E.KENSHU_MUST_KBN IS NULL)
				/*IF data.KYOTEN_CD != 99 */
				AND E.KYOTEN_CD = /*data.KYOTEN_CD*/
				/*END*/
			GROUP BY E.SYSTEM_ID, E.SEQ, HINMEI_ZEI_KBN_CD
		) AS COUNT_TABLE
	GROUP BY COUNT_TABLE.SYSTEM_ID, COUNT_TABLE.SEQ
) HIN_COUNT
ON T_S.SYSTEM_ID = HIN_COUNT.SYSTEM_ID 
AND T_S.SEQ = HIN_COUNT.SEQ 
LEFT OUTER JOIN M_GYOUSHA
ON T_S.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD 
LEFT OUTER JOIN M_KYOTEN AS M_GYOUSHA_KYOTEN
ON ISNULL(M_GYOUSHA.SEIKYUU_KYOTEN_CD,'00') = M_GYOUSHA_KYOTEN.KYOTEN_CD
LEFT OUTER JOIN M_GENBA
ON T_S.GYOUSHA_CD = M_GENBA.GYOUSHA_CD 
AND T_S.GENBA_CD = M_GENBA.GENBA_CD
LEFT OUTER JOIN M_KYOTEN AS M_GENBA_KYOTEN
ON ISNULL(M_GENBA.SEIKYUU_KYOTEN_CD,'00') = M_GENBA_KYOTEN.KYOTEN_CD 
LEFT OUTER JOIN M_UNIT
ON T_S_D.UNIT_CD = M_UNIT.UNIT_CD 
LEFT OUTER JOIN M_KYOTEN
ON M_KYOTEN.KYOTEN_CD = T_S.KYOTEN_CD
LEFT JOIN M_TORIHIKISAKI_SEIKYUU M_T
ON M_T.TORIHIKISAKI_CD = /*data.SEIKYU_CD*/
LEFT OUTER JOIN M_KYOTEN AS M_TORIHIKISAKI_KYOTEN
ON ISNULL(M_T.SEIKYUU_KYOTEN_CD,'00') = M_TORIHIKISAKI_KYOTEN.KYOTEN_CD
LEFT JOIN M_CORP_INFO M_C
ON M_C.SYS_ID = 0
LEFT JOIN M_HINMEI
ON M_HINMEI.HINMEI_CD = T_S_D.HINMEI_CD

WHERE
T_S.TORIHIKISAKI_CD = /*data.SEIKYU_CD*//*END*/
/*IF data.SEIKYUSHIMEBI_FROM != "" && data.SEIKYUSHIMEBI_FROM != null*/
AND CONVERT(DateTime,/*data.SEIKYUSHIMEBI_FROM*/nul, 111) <= T_S.URIAGE_DATE/*END*/
AND T_S.URIAGE_DATE <= CONVERT(DateTime,/*data.SEIKYUSHIMEBI_TO*/null, 111)

AND T_S.DELETE_FLG = '0'
AND T_S.TAIRYUU_KBN = 0
AND T_S.KAKUTEI_KBN = '1' 
AND T_S.URIAGE_TORIHIKI_KBN_CD = '2' 
AND (T_S.KENSHU_MUST_KBN != 1 OR T_S.KENSHU_MUST_KBN IS NULL)
/*IF data.KYOTEN_CD != 99 */
AND T_S.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/
/*IF data.INVOICE_KBN == 2*/
AND (T_S.URIAGE_ZEI_KEISAN_KBN_CD = 2 
/*END*/
/*IF data.INVOICE_KBN == 2*/
OR (T_S.URIAGE_ZEI_KEISAN_KBN_CD = 3 AND (T_S.URIAGE_ZEI_KBN_CD != 1 OR (T_S.URIAGE_ZEI_KBN_CD = 1 AND HIN_COUNT.HIN_NASI = 0))))
/*END*/
/*IF data.INVOICE_KBN != 1*/
AND HIN_COUNT.HIN_SOTO = 0
/*END*/
AND (NOT EXISTS
    (SELECT T_S.SYSTEM_ID, T_S.SEQ
     FROM   T_SEIKYUU_DETAIL
     WHERE  (T_S.SYSTEM_ID = DENPYOU_SYSTEM_ID) 
	 AND (T_S.SEQ = DENPYOU_SEQ)
	 AND (DENPYOU_SHURUI_CD = '2')
	 AND (DELETE_FLG = 0)))

UNION ALL (
SELECT DISTINCT
T_S.SYSTEM_ID,
T_S.SEQ,
T_S.SHUKKA_NUMBER AS DENPYONO,
T_S.KENSHU_DATE AS DENPYOU_DATE,
T_S.KENSHU_URIAGE_DATE AS URIAGE_DATE,
T_S.TORIHIKISAKI_CD,
T_S.GYOUSHA_CD,
T_S.GENBA_CD,
T_S.KENSHU_URIAGE_AMOUNT_TOTAL AS URIAGE_AMOUNT_TOTAL,
T_S.KENSHU_URIAGE_TAX_SOTO AS URIAGE_TAX_SOTO,
T_S.KENSHU_URIAGE_TAX_UCHI AS URIAGE_TAX_UCHI,
T_S.KENSHU_URIAGE_TAX_SOTO_TOTAL AS URIAGE_TAX_SOTO_TOTAL,
T_S.KENSHU_URIAGE_TAX_UCHI_TOTAL AS URIAGE_TAX_UCHI_TOTAL,
T_S.KENSHU_HINMEI_URIAGE_KINGAKU_TOTAL AS HINMEI_URIAGE_KINGAKU_TOTAL,
T_S.KENSHU_HINMEI_URIAGE_TAX_SOTO_TOTAL AS HINMEI_URIAGE_TAX_SOTO_TOTAL,
T_S.KENSHU_HINMEI_URIAGE_TAX_UCHI_TOTAL AS HINMEI_URIAGE_TAX_UCHI_TOTAL,
T_S.URIAGE_ZEI_KEISAN_KBN_CD,
T_S.URIAGE_ZEI_KBN_CD,
ISNULL(T_S.KENSHU_URIAGE_SHOUHIZEI_RATE, 0) AS URIAGE_SHOUHIZEI_RATE,
T_S.SHARYOU_NAME,
T_S_D.DETAIL_SYSTEM_ID,
T_S_D.SHUKKA_NUMBER,
T_K_D.DENPYOU_KBN_CD,
T_K_D.HINMEI_CD,
T_K_D.SUURYOU,
T_K_D.UNIT_CD,
T_K_D.KINGAKU,
T_K_D.TAX_SOTO,
T_K_D.TAX_UCHI,
T_K_D.HINMEI_KINGAKU,
T_K_D.HINMEI_TAX_SOTO,
T_K_D.HINMEI_TAX_UCHI,
T_K_D.HINMEI_ZEI_KBN_CD,
T_S_D.MEISAI_BIKOU,
T_K_D.TANKA,
T_S_D.ROW_NO,

M_GYOUSHA.SEIKYUU_DAIHYOU_PRINT_KBN AS GY_SEIKYUU_DAIHYOU_PRINT_KBN,
M_GYOUSHA.SEIKYUU_KYOTEN_PRINT_KBN AS GY_SEIKYUU_KYOTEN_PRINT_KBN,
M_GYOUSHA.SEIKYUU_KYOTEN_CD AS GY_SEIKYUU_KYOTEN_CD,
M_GYOUSHA.SEIKYUU_SOUFU_NAME1 AS GY_SEIKYUU_SOUFU_NAME1,
M_GYOUSHA.SEIKYUU_SOUFU_NAME2 AS GY_SEIKYUU_SOUFU_NAME2,
M_GYOUSHA.SEIKYUU_SOUFU_KEISHOU1 AS GY_SEIKYUU_SOUFU_KEISHOU1,
M_GYOUSHA.SEIKYUU_SOUFU_KEISHOU2 AS GY_SEIKYUU_SOUFU_KEISHOU2,
M_GYOUSHA.SEIKYUU_SOUFU_POST AS GY_SEIKYUU_SOUFU_POST,
M_GYOUSHA.SEIKYUU_SOUFU_ADDRESS1 AS GY_SEIKYUU_SOUFU_ADDRESS1,
M_GYOUSHA.SEIKYUU_SOUFU_ADDRESS2 AS GY_SEIKYUU_SOUFU_ADDRESS2,
M_GYOUSHA.SEIKYUU_SOUFU_BUSHO AS GY_SEIKYUU_SOUFU_BUSHO,
M_GYOUSHA.SEIKYUU_SOUFU_TANTOU AS GY_SEIKYUU_SOUFU_TANTOU,
M_GYOUSHA.SEIKYUU_SOUFU_TEL AS GY_SEIKYUU_SOUFU_TEL,
M_GYOUSHA.SEIKYUU_SOUFU_FAX AS GY_SEIKYUU_SOUFU_FAX,
M_GYOUSHA.SEIKYUU_TANTOU AS GY_SEIKYUU_TANTOU,
M_GYOUSHA.GYOUSHA_NAME1,
M_GYOUSHA.GYOUSHA_NAME2,

M_GYOUSHA_KYOTEN.KYOTEN_NAME AS GY_KYOTEN_NAME,
M_GYOUSHA_KYOTEN.KYOTEN_DAIHYOU AS GY_KYOTEN_DAIHYOU,
M_GYOUSHA_KYOTEN.KYOTEN_POST AS GY_KYOTEN_POST,
M_GYOUSHA_KYOTEN.KYOTEN_ADDRESS1 AS GY_KYOTEN_ADDRESS1,
M_GYOUSHA_KYOTEN.KYOTEN_ADDRESS2 AS GY_KYOTEN_ADDRESS2,
M_GYOUSHA_KYOTEN.KYOTEN_TEL AS GY_KYOTEN_TEL,
M_GYOUSHA_KYOTEN.KYOTEN_FAX AS GY_KYOTEN_FAX,

M_GENBA.GENBA_CD,
M_GENBA.SEIKYUU_DAIHYOU_PRINT_KBN AS GE_SEIKYUU_DAIHYOU_PRINT_KBN,
M_GENBA.SEIKYUU_KYOTEN_PRINT_KBN AS GE_SEIKYUU_KYOTEN_PRINT_KBN,
M_GENBA.SEIKYUU_KYOTEN_CD AS GE_SEIKYUU_KYOTEN_CD,
M_GENBA.SEIKYUU_SOUFU_NAME1 AS GE_SEIKYUU_SOUFU_NAME1,
M_GENBA.SEIKYUU_SOUFU_NAME2 AS GE_SEIKYUU_SOUFU_NAME2,
M_GENBA.SEIKYUU_SOUFU_KEISHOU1 AS GE_SEIKYUU_SOUFU_KEISHOU1,
M_GENBA.SEIKYUU_SOUFU_KEISHOU2 AS GE_SEIKYUU_SOUFU_KEISHOU2,
M_GENBA.SEIKYUU_SOUFU_POST AS GE_SEIKYUU_SOUFU_POST,
M_GENBA.SEIKYUU_SOUFU_ADDRESS1 AS GE_SEIKYUU_SOUFU_ADDRESS1,
M_GENBA.SEIKYUU_SOUFU_ADDRESS2 AS GE_SEIKYUU_SOUFU_ADDRESS2,
M_GENBA.SEIKYUU_SOUFU_BUSHO AS GE_SEIKYUU_SOUFU_BUSHO,
M_GENBA.SEIKYUU_SOUFU_TANTOU AS GE_SEIKYUU_SOUFU_TANTOU,
M_GENBA.SEIKYUU_SOUFU_TEL AS GE_SEIKYUU_SOUFU_TEL,
M_GENBA.SEIKYUU_SOUFU_FAX AS GE_SEIKYUU_SOUFU_FAX,
M_GENBA.SEIKYUU_TANTOU AS GE_SEIKYUU_TANTOU,
M_GENBA.GENBA_NAME1,
M_GENBA.GENBA_NAME2,

M_GENBA_KYOTEN.KYOTEN_NAME AS GE_KYOTEN_NAME,
M_GENBA_KYOTEN.KYOTEN_DAIHYOU AS GE_KYOTEN_DAIHYOU,
M_GENBA_KYOTEN.KYOTEN_POST AS GE_KYOTEN_POST,
M_GENBA_KYOTEN.KYOTEN_ADDRESS1 AS GE_KYOTEN_ADDRESS1,
M_GENBA_KYOTEN.KYOTEN_ADDRESS2 AS GE_KYOTEN_ADDRESS2,
M_GENBA_KYOTEN.KYOTEN_TEL AS GE_KYOTEN_TEL,
M_GENBA_KYOTEN.KYOTEN_FAX AS GE_KYOTEN_FAX,

M_UNIT.UNIT_NAME,

M_KYOTEN.KYOTEN_NAME,
M_KYOTEN.KYOTEN_DAIHYOU,
M_KYOTEN.KYOTEN_POST,
M_KYOTEN.KYOTEN_ADDRESS1,
M_KYOTEN.KYOTEN_ADDRESS2,
M_KYOTEN.KYOTEN_TEL,
M_KYOTEN.KYOTEN_FAX,

M_T.SEIKYUU_DAIHYOU_PRINT_KBN,
M_T.SEIKYUU_SOUFU_NAME1,
M_T.SEIKYUU_SOUFU_NAME2,
M_T.SEIKYUU_SOUFU_KEISHOU1,
M_T.SEIKYUU_SOUFU_KEISHOU2,
M_T.SEIKYUU_SOUFU_POST,
M_T.SEIKYUU_SOUFU_ADDRESS1,
M_T.SEIKYUU_SOUFU_ADDRESS2,
M_T.SEIKYUU_KYOTEN_PRINT_KBN,
M_T.SEIKYUU_KYOTEN_CD,
M_T.SEIKYUU_SOUFU_BUSHO,
M_T.SEIKYUU_SOUFU_TANTOU,
M_T.SEIKYUU_SOUFU_TEL,
M_T.SEIKYUU_SOUFU_FAX,
M_T.SEIKYUU_TANTOU,
M_T.SHOSHIKI_KBN,

M_TORIHIKISAKI_KYOTEN.KYOTEN_NAME AS TR_KYOTEN_NAME,
M_TORIHIKISAKI_KYOTEN.KYOTEN_DAIHYOU AS TR_KYOTEN_DAIHYOU,
M_TORIHIKISAKI_KYOTEN.KYOTEN_POST AS TR_KYOTEN_POST,
M_TORIHIKISAKI_KYOTEN.KYOTEN_ADDRESS1 AS TR_KYOTEN_ADDRESS1,
M_TORIHIKISAKI_KYOTEN.KYOTEN_ADDRESS2 AS TR_KYOTEN_ADDRESS2,
M_TORIHIKISAKI_KYOTEN.KYOTEN_TEL AS TR_KYOTEN_TEL,
M_TORIHIKISAKI_KYOTEN.KYOTEN_FAX AS TR_KYOTEN_FAX,

M_C.CORP_NAME,
M_C.CORP_DAIHYOU,

T_K_D.HINMEI_NAME,
T_K_D.KENSHU_SYSTEM_ID

FROM
T_SHUKKA_ENTRY T_S
INNER JOIN T_SHUKKA_DETAIL T_S_D 
ON T_S.SYSTEM_ID = T_S_D.SYSTEM_ID 
AND T_S.SEQ = T_S_D.SEQ 
LEFT JOIN T_KENSHU_DETAIL T_K_D
ON T_S_D.SYSTEM_ID = T_K_D.SYSTEM_ID
AND T_S_D.SEQ = T_K_D.SEQ
AND T_S_D.DETAIL_SYSTEM_ID = T_K_D.DETAIL_SYSTEM_ID
AND T_S_D.ROW_NO = T_K_D.ROW_NO
LEFT JOIN 
(
	SELECT 
		COUNT_TABLE.SYSTEM_ID, COUNT_TABLE.SEQ, COUNT(COUNT_TABLE.SOTO) AS HIN_SOTO, COUNT(COUNT_TABLE.NASI) AS HIN_NASI
		FROM (
			SELECT
				E.SYSTEM_ID, E.SEQ, 
				CASE WHEN KD.HINMEI_ZEI_KBN_CD = 1 THEN COUNT(KD.HINMEI_ZEI_KBN_CD) END AS SOTO,
				CASE WHEN KD.HINMEI_ZEI_KBN_CD is null THEN COUNT(KD.HINMEI_ZEI_KBN_CD) END AS NASI
			FROM
				T_SHUKKA_ENTRY E 
			INNER JOIN T_SHUKKA_DETAIL D
				ON E.SYSTEM_ID = D.SYSTEM_ID AND E.SEQ = D.SEQ 
			LEFT JOIN T_KENSHU_DETAIL KD
				ON D.SYSTEM_ID = KD.SYSTEM_ID
				AND D.SEQ = KD.SEQ
				AND D.DETAIL_SYSTEM_ID = KD.DETAIL_SYSTEM_ID
				AND D.ROW_NO = KD.ROW_NO
				AND D.DENPYOU_KBN_CD = '1'
			WHERE
				E.TORIHIKISAKI_CD = /*data.SEIKYU_CD*//*END*/
				/*IF data.SEIKYUSHIMEBI_FROM != "" && data.SEIKYUSHIMEBI_FROM != null*/
				AND CONVERT(DateTime,/*data.SEIKYUSHIMEBI_FROM*/nul, 111) <= E.KENSHU_URIAGE_DATE/*END*/
				AND E.KENSHU_URIAGE_DATE <= CONVERT(DateTime,/*data.SEIKYUSHIMEBI_TO*/null, 111)
				AND E.DELETE_FLG = '0'
				AND E.TAIRYUU_KBN = 0
				AND E.KAKUTEI_KBN = '1' 
				AND E.URIAGE_TORIHIKI_KBN_CD = '2' 
				AND E.KENSHU_MUST_KBN = 1
				AND KD.DENPYOU_KBN_CD = 1
				/*IF data.KYOTEN_CD != 99 */
				AND E.KYOTEN_CD = /*data.KYOTEN_CD*/
				/*END*/
			GROUP BY E.SYSTEM_ID, E.SEQ, KD.HINMEI_ZEI_KBN_CD
		) AS COUNT_TABLE
	GROUP BY COUNT_TABLE.SYSTEM_ID, COUNT_TABLE.SEQ
) HIN_COUNT
ON T_S.SYSTEM_ID = HIN_COUNT.SYSTEM_ID 
AND T_S.SEQ = HIN_COUNT.SEQ 
LEFT OUTER JOIN M_GYOUSHA
ON T_S.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD 
LEFT OUTER JOIN M_KYOTEN AS M_GYOUSHA_KYOTEN
ON ISNULL(M_GYOUSHA.SEIKYUU_KYOTEN_CD,'00') = M_GYOUSHA_KYOTEN.KYOTEN_CD
LEFT OUTER JOIN M_GENBA
ON T_S.GYOUSHA_CD = M_GENBA.GYOUSHA_CD 
AND T_S.GENBA_CD = M_GENBA.GENBA_CD
LEFT OUTER JOIN M_KYOTEN AS M_GENBA_KYOTEN
ON ISNULL(M_GENBA.SEIKYUU_KYOTEN_CD,'00') = M_GENBA_KYOTEN.KYOTEN_CD 
LEFT OUTER JOIN M_UNIT
ON T_K_D.UNIT_CD = M_UNIT.UNIT_CD 
LEFT OUTER JOIN M_KYOTEN
ON M_KYOTEN.KYOTEN_CD = T_S.KYOTEN_CD
LEFT JOIN M_TORIHIKISAKI_SEIKYUU M_T
ON M_T.TORIHIKISAKI_CD = /*data.SEIKYU_CD*/
LEFT OUTER JOIN M_KYOTEN AS M_TORIHIKISAKI_KYOTEN
ON ISNULL(M_T.SEIKYUU_KYOTEN_CD,'00') = M_TORIHIKISAKI_KYOTEN.KYOTEN_CD
LEFT JOIN M_CORP_INFO M_C
ON M_C.SYS_ID = 0
LEFT JOIN M_HINMEI
ON M_HINMEI.HINMEI_CD = T_K_D.HINMEI_CD

WHERE
T_S.TORIHIKISAKI_CD = /*data.SEIKYU_CD*//*END*/
/*IF data.SEIKYUSHIMEBI_FROM != "" && data.SEIKYUSHIMEBI_FROM != null*/
AND CONVERT(DateTime,/*data.SEIKYUSHIMEBI_FROM*/nul, 111) <= T_S.KENSHU_URIAGE_DATE/*END*/
AND T_S.KENSHU_URIAGE_DATE <= CONVERT(DateTime,/*data.SEIKYUSHIMEBI_TO*/null, 111)

AND T_S.DELETE_FLG = '0'
AND T_S.TAIRYUU_KBN = 0
AND T_S.KAKUTEI_KBN = '1' 
AND T_S.URIAGE_TORIHIKI_KBN_CD = '2' 
AND T_S.KENSHU_MUST_KBN = 1
AND T_K_D.DENPYOU_KBN_CD = 1
/*IF data.KYOTEN_CD != 99 */
AND T_S.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/
/*IF data.INVOICE_KBN == 2*/
AND (T_S.URIAGE_ZEI_KEISAN_KBN_CD = 2 
/*END*/
/*IF data.INVOICE_KBN == 2*/
OR (T_S.URIAGE_ZEI_KEISAN_KBN_CD = 3 AND (T_S.URIAGE_ZEI_KBN_CD != 1 OR (T_S.URIAGE_ZEI_KBN_CD = 1 AND HIN_COUNT.HIN_NASI = 0))))
/*END*/
/*IF data.INVOICE_KBN != 1*/
AND HIN_COUNT.HIN_SOTO = 0
/*END*/
AND (NOT EXISTS
    (SELECT T_S.SYSTEM_ID, T_S.SEQ
     FROM   T_SEIKYUU_DETAIL
     WHERE  (T_S.SYSTEM_ID = DENPYOU_SYSTEM_ID) 
	 AND (T_S.SEQ = DENPYOU_SEQ)
	 AND (DENPYOU_SHURUI_CD = '2')
	 AND (DELETE_FLG = 0)))
)

ORDER BY T_S.GYOUSHA_CD,T_S.GENBA_CD ASC