SELECT
T_U.SYSTEM_ID,
T_U.SEQ,
T_U.UKEIRE_NUMBER AS DENPYONO,
T_U.DENPYOU_DATE,
T_U.URIAGE_DATE,
T_U.TORIHIKISAKI_CD,
T_U.GYOUSHA_CD,
T_U.GENBA_CD,
T_U.URIAGE_KINGAKU_TOTAL AS URIAGE_AMOUNT_TOTAL,
T_U.URIAGE_TAX_SOTO,
T_U.URIAGE_TAX_UCHI,
T_U.URIAGE_TAX_SOTO_TOTAL,
T_U.URIAGE_TAX_UCHI_TOTAL,
T_U.HINMEI_URIAGE_KINGAKU_TOTAL,
T_U.HINMEI_URIAGE_TAX_SOTO_TOTAL,
T_U.HINMEI_URIAGE_TAX_UCHI_TOTAL,
T_U.URIAGE_ZEI_KEISAN_KBN_CD,
T_U.URIAGE_ZEI_KBN_CD,
T_U.URIAGE_SHOUHIZEI_RATE,
T_U.SHARYOU_NAME,
--T_U_D.SYSTEM_ID,
--T_U_D.SEQ,
T_U_D.DETAIL_SYSTEM_ID,
T_U_D.UKEIRE_NUMBER,
T_U_D.DENPYOU_KBN_CD,
T_U_D.HINMEI_CD,
--T_U_D.HINMEI_NAME,
T_U_D.SUURYOU,
T_U_D.UNIT_CD,
T_U_D.KINGAKU,
T_U_D.TAX_SOTO,
T_U_D.TAX_UCHI,
T_U_D.HINMEI_KINGAKU,
T_U_D.HINMEI_TAX_SOTO,
T_U_D.HINMEI_TAX_UCHI,
T_U_D.HINMEI_ZEI_KBN_CD,
T_U_D.MEISAI_BIKOU,
T_U_D.TANKA,
T_U_D.ROW_NO,

M_GYOUSHA.SEIKYUU_DAIHYOU_PRINT_KBN AS GY_SEIKYUU_DAIHYOU_PRINT_KBN,
M_GYOUSHA.SEIKYUU_KYOTEN_PRINT_KBN AS GY_SEIKYUU_KYOTEN_PRINT_KBN,
M_GYOUSHA.SEIKYUU_KYOTEN_CD AS GY_SEIKYUU_KYOTEN_CD,
M_GYOUSHA.SEIKYUU_SOUFU_NAME1 AS GY_SEIKYUU_SOUFU_NAME1,
M_GYOUSHA.SEIKYUU_SOUFU_NAME2 AS GY_SEIKYUU_SOUFU_NAME2,
M_GYOUSHA.SEIKYUU_SOUFU_KEISHOU1 AS GY_SEIKYUU_SOUFU_KEISHOU1,
M_GYOUSHA.SEIKYUU_SOUFU_KEISHOU2 AS GY_SEIKYUU_SOUFU_KEISHOU2,
M_GYOUSHA.SEIKYUU_SOUFU_POST AS GY_SEIKYUU_SOUFU_POST,
M_GYOUSHA.SEIKYUU_SOUFU_ADDRESS1 AS GY_SEIKYUU_SOUFU_ADDRESS1,
M_GYOUSHA.SEIKYUU_SOUFU_ADDRESS2 AS GY_SEIKYUU_SOUFU_ADDRESS2,
M_GYOUSHA.SEIKYUU_SOUFU_BUSHO AS GY_SEIKYUU_SOUFU_BUSHO,
M_GYOUSHA.SEIKYUU_SOUFU_TANTOU AS GY_SEIKYUU_SOUFU_TANTOU,
M_GYOUSHA.SEIKYUU_SOUFU_TEL AS GY_SEIKYUU_SOUFU_TEL,
M_GYOUSHA.SEIKYUU_SOUFU_FAX AS GY_SEIKYUU_SOUFU_FAX,
M_GYOUSHA.SEIKYUU_TANTOU AS GY_SEIKYUU_TANTOU,
M_GYOUSHA.GYOUSHA_NAME1,
M_GYOUSHA.GYOUSHA_NAME2,

M_GYOUSHA_KYOTEN.KYOTEN_NAME AS GY_KYOTEN_NAME,
M_GYOUSHA_KYOTEN.KYOTEN_DAIHYOU AS GY_KYOTEN_DAIHYOU,
M_GYOUSHA_KYOTEN.KYOTEN_POST AS GY_KYOTEN_POST,
M_GYOUSHA_KYOTEN.KYOTEN_ADDRESS1 AS GY_KYOTEN_ADDRESS1,
M_GYOUSHA_KYOTEN.KYOTEN_ADDRESS2 AS GY_KYOTEN_ADDRESS2,
M_GYOUSHA_KYOTEN.KYOTEN_TEL AS GY_KYOTEN_TEL,
M_GYOUSHA_KYOTEN.KYOTEN_FAX AS GY_KYOTEN_FAX,

M_GENBA.GENBA_CD,
M_GENBA.SEIKYUU_DAIHYOU_PRINT_KBN AS GE_SEIKYUU_DAIHYOU_PRINT_KBN,
M_GENBA.SEIKYUU_KYOTEN_PRINT_KBN AS GE_SEIKYUU_KYOTEN_PRINT_KBN,
M_GENBA.SEIKYUU_KYOTEN_CD AS GE_SEIKYUU_KYOTEN_CD,
M_GENBA.SEIKYUU_SOUFU_NAME1 AS GE_SEIKYUU_SOUFU_NAME1,
M_GENBA.SEIKYUU_SOUFU_NAME2 AS GE_SEIKYUU_SOUFU_NAME2,
M_GENBA.SEIKYUU_SOUFU_KEISHOU1 AS GE_SEIKYUU_SOUFU_KEISHOU1,
M_GENBA.SEIKYUU_SOUFU_KEISHOU2 AS GE_SEIKYUU_SOUFU_KEISHOU2,
M_GENBA.SEIKYUU_SOUFU_POST AS GE_SEIKYUU_SOUFU_POST,
M_GENBA.SEIKYUU_SOUFU_ADDRESS1 AS GE_SEIKYUU_SOUFU_ADDRESS1,
M_GENBA.SEIKYUU_SOUFU_ADDRESS2 AS GE_SEIKYUU_SOUFU_ADDRESS2,
M_GENBA.SEIKYUU_SOUFU_BUSHO AS GE_SEIKYUU_SOUFU_BUSHO,
M_GENBA.SEIKYUU_SOUFU_TANTOU AS GE_SEIKYUU_SOUFU_TANTOU,
M_GENBA.SEIKYUU_SOUFU_TEL AS GE_SEIKYUU_SOUFU_TEL,
M_GENBA.SEIKYUU_SOUFU_FAX AS GE_SEIKYUU_SOUFU_FAX,
M_GENBA.SEIKYUU_TANTOU AS GE_SEIKYUU_TANTOU,
M_GENBA.GENBA_NAME1,
M_GENBA.GENBA_NAME2,

M_GENBA_KYOTEN.KYOTEN_NAME AS GE_KYOTEN_NAME,
M_GENBA_KYOTEN.KYOTEN_DAIHYOU AS GE_KYOTEN_DAIHYOU,
M_GENBA_KYOTEN.KYOTEN_POST AS GE_KYOTEN_POST,
M_GENBA_KYOTEN.KYOTEN_ADDRESS1 AS GE_KYOTEN_ADDRESS1,
M_GENBA_KYOTEN.KYOTEN_ADDRESS2 AS GE_KYOTEN_ADDRESS2,
M_GENBA_KYOTEN.KYOTEN_TEL AS GE_KYOTEN_TEL,
M_GENBA_KYOTEN.KYOTEN_FAX AS GE_KYOTEN_FAX,

M_UNIT.UNIT_NAME,

M_KYOTEN.KYOTEN_NAME,
M_KYOTEN.KYOTEN_DAIHYOU,
M_KYOTEN.KYOTEN_POST,
M_KYOTEN.KYOTEN_ADDRESS1,
M_KYOTEN.KYOTEN_ADDRESS2,
M_KYOTEN.KYOTEN_TEL,
M_KYOTEN.KYOTEN_FAX,

M_T.SEIKYUU_DAIHYOU_PRINT_KBN,
M_T.SEIKYUU_SOUFU_NAME1,
M_T.SEIKYUU_SOUFU_NAME2,
M_T.SEIKYUU_SOUFU_KEISHOU1,
M_T.SEIKYUU_SOUFU_KEISHOU2,
M_T.SEIKYUU_SOUFU_POST,
M_T.SEIKYUU_SOUFU_ADDRESS1,
M_T.SEIKYUU_SOUFU_ADDRESS2,
M_T.SEIKYUU_KYOTEN_PRINT_KBN,
M_T.SEIKYUU_KYOTEN_CD,
M_T.SEIKYUU_SOUFU_BUSHO,
M_T.SEIKYUU_SOUFU_TANTOU,
M_T.SEIKYUU_SOUFU_TEL,
M_T.SEIKYUU_SOUFU_FAX,
M_T.SEIKYUU_TANTOU,
M_T.SHOSHIKI_KBN,

M_TORIHIKISAKI_KYOTEN.KYOTEN_NAME AS TR_KYOTEN_NAME,
M_TORIHIKISAKI_KYOTEN.KYOTEN_DAIHYOU AS TR_KYOTEN_DAIHYOU,
M_TORIHIKISAKI_KYOTEN.KYOTEN_POST AS TR_KYOTEN_POST,
M_TORIHIKISAKI_KYOTEN.KYOTEN_ADDRESS1 AS TR_KYOTEN_ADDRESS1,
M_TORIHIKISAKI_KYOTEN.KYOTEN_ADDRESS2 AS TR_KYOTEN_ADDRESS2,
M_TORIHIKISAKI_KYOTEN.KYOTEN_TEL AS TR_KYOTEN_TEL,
M_TORIHIKISAKI_KYOTEN.KYOTEN_FAX AS TR_KYOTEN_FAX,

M_C.CORP_NAME,
M_C.CORP_DAIHYOU,

T_U_D.HINMEI_NAME

FROM
T_UKEIRE_ENTRY T_U 
INNER JOIN T_UKEIRE_DETAIL T_U_D 
ON T_U.SYSTEM_ID = T_U_D.SYSTEM_ID 
AND T_U.SEQ = T_U_D.SEQ 
AND T_U_D.DENPYOU_KBN_CD = '1'
LEFT JOIN 
(
	SELECT 
		COUNT_TABLE.SYSTEM_ID, COUNT_TABLE.SEQ, COUNT(COUNT_TABLE.SOTO) AS HIN_SOTO, COUNT(COUNT_TABLE.NASI) AS HIN_NASI
		FROM (
			SELECT
				E.SYSTEM_ID, E.SEQ, 
				CASE WHEN HINMEI_ZEI_KBN_CD = 1 THEN COUNT(HINMEI_ZEI_KBN_CD) END AS SOTO,
				CASE WHEN HINMEI_ZEI_KBN_CD is null THEN COUNT(HINMEI_ZEI_KBN_CD) END AS NASI
			FROM
				T_UKEIRE_ENTRY E INNER JOIN T_UKEIRE_DETAIL D
			ON E.SYSTEM_ID = D.SYSTEM_ID 
				AND E.SEQ = D.SEQ 
				AND E.TORIHIKISAKI_CD = /*data.SEIKYU_CD*/
				/*IF data.SEIKYUSHIMEBI_FROM != "" && data.SEIKYUSHIMEBI_FROM != null*/
				AND CONVERT(DateTime,/*data.SEIKYUSHIMEBI_FROM*/nul, 111) <= E.URIAGE_DATE/*END*/
				AND E.URIAGE_DATE <= CONVERT(DateTime,/*data.SEIKYUSHIMEBI_TO*/null, 111)
				AND E.DELETE_FLG = '0'
				AND E.TAIRYUU_KBN = 0
				AND E.KAKUTEI_KBN = '1' 
				AND D.DENPYOU_KBN_CD = '1'
				AND E.URIAGE_TORIHIKI_KBN_CD = '2' 
				/*IF data.KYOTEN_CD != 99*/
				AND E.KYOTEN_CD = /*data.KYOTEN_CD*/
				/*END*/
			GROUP BY E.SYSTEM_ID, E.SEQ, HINMEI_ZEI_KBN_CD
		) AS COUNT_TABLE
	GROUP BY COUNT_TABLE.SYSTEM_ID, COUNT_TABLE.SEQ
) HIN_COUNT
ON T_U.SYSTEM_ID = HIN_COUNT.SYSTEM_ID 
AND T_U.SEQ = HIN_COUNT.SEQ 
LEFT OUTER JOIN M_GYOUSHA
ON T_U.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD 
LEFT OUTER JOIN M_KYOTEN AS M_GYOUSHA_KYOTEN
ON ISNULL(M_GYOUSHA.SEIKYUU_KYOTEN_CD,'00') = M_GYOUSHA_KYOTEN.KYOTEN_CD
LEFT OUTER JOIN M_GENBA
ON T_U.GYOUSHA_CD = M_GENBA.GYOUSHA_CD 
AND T_U.GENBA_CD = M_GENBA.GENBA_CD
LEFT OUTER JOIN M_KYOTEN AS M_GENBA_KYOTEN
ON ISNULL(M_GENBA.SEIKYUU_KYOTEN_CD,'00') = M_GENBA_KYOTEN.KYOTEN_CD 
LEFT OUTER JOIN M_UNIT
ON T_U_D.UNIT_CD = M_UNIT.UNIT_CD
LEFT OUTER JOIN M_KYOTEN
ON M_KYOTEN.KYOTEN_CD = T_U.KYOTEN_CD
LEFT JOIN M_TORIHIKISAKI_SEIKYUU M_T
ON M_T.TORIHIKISAKI_CD = /*data.SEIKYU_CD*/
LEFT OUTER JOIN M_KYOTEN AS M_TORIHIKISAKI_KYOTEN
ON ISNULL(M_T.SEIKYUU_KYOTEN_CD,'00') = M_TORIHIKISAKI_KYOTEN.KYOTEN_CD
LEFT JOIN M_CORP_INFO M_C
ON M_C.SYS_ID = 0
LEFT JOIN M_HINMEI
ON M_HINMEI.HINMEI_CD = T_U_D.HINMEI_CD
WHERE
T_U.TORIHIKISAKI_CD = /*data.SEIKYU_CD*/
/*IF data.SEIKYUSHIMEBI_FROM != "" && data.SEIKYUSHIMEBI_FROM != null*/
AND CONVERT(DateTime,/*data.SEIKYUSHIMEBI_FROM*/nul, 111) <= T_U.URIAGE_DATE/*END*/
AND T_U.URIAGE_DATE <= CONVERT(DateTime,/*data.SEIKYUSHIMEBI_TO*/null, 111)

AND T_U.DELETE_FLG = '0'
AND T_U.TAIRYUU_KBN = 0
AND T_U.KAKUTEI_KBN = '1' 
AND T_U.URIAGE_TORIHIKI_KBN_CD = '2' 
/*IF data.KYOTEN_CD != 99*/
AND T_U.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/
/*IF data.INVOICE_KBN == 2*/
AND (T_U.URIAGE_ZEI_KEISAN_KBN_CD = 2 
/*END*/
/*IF data.INVOICE_KBN == 2*/
OR (T_U.URIAGE_ZEI_KEISAN_KBN_CD = 3 AND (T_U.URIAGE_ZEI_KBN_CD != 1 OR (T_U.URIAGE_ZEI_KBN_CD = 1 AND HIN_COUNT.HIN_NASI = 0))))
/*END*/
/*IF data.INVOICE_KBN != 1*/
AND HIN_COUNT.HIN_SOTO = 0
/*END*/
AND (NOT EXISTS
    (SELECT T_U.SYSTEM_ID, T_U.SEQ
     FROM   T_SEIKYUU_DETAIL
     WHERE  (T_U.SYSTEM_ID = DENPYOU_SYSTEM_ID) 
	 AND (T_U.SEQ = DENPYOU_SEQ)
	 AND (DENPYOU_SHURUI_CD = '1')
	 AND (DELETE_FLG = 0)))
ORDER BY T_U.GYOUSHA_CD,T_U.GENBA_CD ASC

