SELECT
KONKAI_SEIKYU_GAKU
FROM
T_SEIKYUU_DENPYOU
WHERE
DELETE_FLG = 0
AND
TORIHIKISAKI_CD = /*data.SEIKYU_CD*/
AND
CONVERT(DateTime, SEIKYUU_DATE, 111) <= CONVERT(DateTime, /*data.SEIKYUSHIMEBI_TO*/null, 111)
ORDER BY SEIKYUU_DATE DESC, SEIKYUU_NUMBER DESC