SELECT
M_T.TORIHIKISAKI_CD,
M_T.SHOSHIKI_KBN,
M_T.SHOSHIKI_MEISAI_KBN,
M_T.SHOSHIKI_GENBA_KBN,
M_T.SEIKYUU_KEITAI_KBN,
M_T.NYUUKIN_MEISAI_KBN,
M_T.YOUSHI_KBN,
M_T.SEIKYUU_SOUFU_NAME1,
M_T.SEIKYUU_SOUFU_NAME2,
M_T.SEIKYUU_SOUFU_KEISHOU1,
M_T.SEIKYUU_SOUFU_KEISHOU2,
M_T.SEIKYUU_SOUFU_POST,
M_T.SEIKYUU_SOUFU_ADDRESS1,
M_T.SEIKYUU_SOUFU_ADDRESS2,
M_T.SEIKYUU_DAIHYOU_PRINT_KBN,
M_T.SEIKYUU_KYOTEN_PRINT_KBN,
M_T.SEIKYUU_KYOTEN_CD,
M_T.SEIKYUU_SOUFU_BUSHO,
M_T.SEIKYUU_SOUFU_TANTOU,
M_T.SEIKYUU_SOUFU_TEL,
M_T.SEIKYUU_SOUFU_FAX,
M_T.FURIKOMI_BANK_CD,
M_T.FURIKOMI_BANK_SHITEN_CD,
M_T.KOUZA_SHURUI,
M_T.KOUZA_NO,
(SELECT
    KOUZA_NAME
FROM
    M_BANK_SHITEN AS M_BC
WHERE
    M_T.FURIKOMI_BANK_CD = M_BC.BANK_CD
AND M_T.FURIKOMI_BANK_SHITEN_CD = M_BC.BANK_SHITEN_CD
AND M_T.KOUZA_SHURUI = M_BC.KOUZA_SHURUI
AND M_T.KOUZA_NO = M_BC.KOUZA_NO) AS KOUZA_NAME,
M_T.KAISHI_URIKAKE_ZANDAKA,
M_T.TAX_HASUU_CD,
M_B.BANK_NAME,

M_B_S.BANK_SHITEN_NAME,

M_K.KYOTEN_NAME AS SEIKYUU_KYOTEN_NAME,
M_K.KYOTEN_DAIHYOU AS SEIKYUU_KYOTEN_DAIHYOU,
M_K.KYOTEN_POST AS SEIKYUU_KYOTEN_POST,
M_K.KYOTEN_ADDRESS1 AS SEIKYUU_KYOTEN_ADDRESS1,
M_K.KYOTEN_ADDRESS2 AS SEIKYUU_KYOTEN_ADDRESS2,
M_K.KYOTEN_TEL AS SEIKYUU_KYOTEN_TEL,
M_K.KYOTEN_FAX AS SEIKYUU_KYOTEN_FAX,

M_T.FURIKOMI_BANK_CD_2,
M_T.FURIKOMI_BANK_SHITEN_CD_2,
M_T.KOUZA_SHURUI_2,
M_T.KOUZA_NO_2,
(SELECT
    KOUZA_NAME
FROM
    M_BANK_SHITEN AS M_BC
WHERE
    M_T.FURIKOMI_BANK_CD_2 = M_BC.BANK_CD
AND M_T.FURIKOMI_BANK_SHITEN_CD_2 = M_BC.BANK_SHITEN_CD
AND M_T.KOUZA_SHURUI_2 = M_BC.KOUZA_SHURUI
AND M_T.KOUZA_NO_2 = M_BC.KOUZA_NO) AS KOUZA_NAME_2,
M_B2.BANK_NAME AS BANK_NAME_2,
M_B_S2.BANK_SHITEN_NAME AS BANK_SHITEN_NAME_2,

M_T.FURIKOMI_BANK_CD_3,
M_T.FURIKOMI_BANK_SHITEN_CD_3,
M_T.KOUZA_SHURUI_3,
M_T.KOUZA_NO_3,
(SELECT
    KOUZA_NAME
FROM
    M_BANK_SHITEN AS M_BC
WHERE
    M_T.FURIKOMI_BANK_CD_3 = M_BC.BANK_CD
AND M_T.FURIKOMI_BANK_SHITEN_CD_3 = M_BC.BANK_SHITEN_CD
AND M_T.KOUZA_SHURUI_3 = M_BC.KOUZA_SHURUI
AND M_T.KOUZA_NO_3 = M_BC.KOUZA_NO) AS KOUZA_NAME_3,
M_B3.BANK_NAME AS BANK_NAME_3,
M_B_S3.BANK_SHITEN_NAME AS BANK_SHITEN_NAME_3

FROM
M_TORIHIKISAKI_SEIKYUU M_T

LEFT OUTER JOIN M_BANK M_B
ON M_T.FURIKOMI_BANK_CD = M_B.BANK_CD

LEFT OUTER JOIN M_BANK_SHITEN M_B_S
ON M_T.FURIKOMI_BANK_CD = M_B_S.BANK_CD
AND M_T.FURIKOMI_BANK_SHITEN_CD = M_B_S.BANK_SHITEN_CD
AND M_T.KOUZA_SHURUI = M_B_S.KOUZA_SHURUI
AND M_T.KOUZA_NO = M_B_S.KOUZA_NO

LEFT OUTER JOIN M_KYOTEN M_K
ON ISNULL(M_T.SEIKYUU_KYOTEN_CD,'00') = M_K.KYOTEN_CD

LEFT OUTER JOIN M_BANK M_B2
ON M_T.FURIKOMI_BANK_CD_2 = M_B2.BANK_CD

LEFT OUTER JOIN M_BANK_SHITEN M_B_S2
ON M_T.FURIKOMI_BANK_CD_2 = M_B_S2.BANK_CD
AND M_T.FURIKOMI_BANK_SHITEN_CD_2 = M_B_S2.BANK_SHITEN_CD
AND M_T.KOUZA_SHURUI_2 = M_B_S2.KOUZA_SHURUI
AND M_T.KOUZA_NO_2 = M_B_S2.KOUZA_NO

LEFT OUTER JOIN M_BANK M_B3
ON M_T.FURIKOMI_BANK_CD_3 = M_B3.BANK_CD

LEFT OUTER JOIN M_BANK_SHITEN M_B_S3
ON M_T.FURIKOMI_BANK_CD_3 = M_B_S3.BANK_CD
AND M_T.FURIKOMI_BANK_SHITEN_CD_3 = M_B_S3.BANK_SHITEN_CD
AND M_T.KOUZA_SHURUI_3 = M_B_S3.KOUZA_SHURUI
AND M_T.KOUZA_NO_3 = M_B_S3.KOUZA_NO

WHERE
TORIHIKISAKI_CD = /*data.SEIKYU_CD*/
