UPDATE T_SEIKYUU_DENPYOU SET DELETE_FLG = /*deleteFlg*/ WHERE SEIKYUU_NUMBER = /*seikyuuNumber*/ 

UPDATE T_SEIKYUU_DENPYOU_KAGAMI SET DELETE_FLG = /*deleteFlg*/ WHERE SEIKYUU_NUMBER = /*seikyuuNumber*/ 

UPDATE T_SEIKYUU_DETAIL SET DELETE_FLG = /*deleteFlg*/ WHERE SEIKYUU_NUMBER = /*seikyuuNumber*/ 

UPDATE T_NYUUKIN_KESHIKOMI SET DELETE_FLG = /*deleteFlg*/ WHERE SEIKYUU_NUMBER = /*seikyuuNumber*/