SELECT MT.TORIHIKISAKI_CD,
 MT.TORIHIKISAKI_NAME_RYAKU,
 MTSE.TORIHIKI_KBN_CD,
 MTSE.KAISHI_URIKAKE_ZANDAKA,
 MTSE.SHOSHIKI_KBN,
 MTSE.TAX_HASUU_CD
FROM dbo.M_TORIHIKISAKI AS MT
 LEFT JOIN dbo.M_TORIHIKISAKI_SEIKYUU AS MTSE
ON MT.TORIHIKISAKI_CD = MTSE.TORIHIKISAKI_CD
WHERE 
MTSE.TORIHIKI_KBN_CD = 2
/*IF startCD != null && startCD != ''*/AND MTSE.TORIHIKISAKI_CD >= /*startCD*//*END*/
/*IF endCD != null && endCD != ''*/AND MTSE.TORIHIKISAKI_CD <= /*endCD*//*END*/
/*IF shimebi != null && shimebi != ''*/ 
 AND (MTSE.SHIMEBI1 = /*shimebi*/0
   OR MTSE.SHIMEBI2 = /*shimebi*/0
   OR MTSE.SHIMEBI3 = /*shimebi*/0) /*END*/
ORDER BY MT.TORIHIKISAKI_CD
