SELECT *
FROM dbo.M_TORIHIKISAKI AS MT
LEFT JOIN dbo.M_TORIHIKISAKI_SEIKYUU AS MTSE
ON MT.TORIHIKISAKI_CD = MTSE.TORIHIKISAKI_CD
WHERE 
1=1
/*IF !containsDeleteOutRange*/
AND ((TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= TEKIYOU_END) or (TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and TEKIYOU_END IS NULL) or (TEKIYOU_BEGIN IS NULL and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= TEKIYOU_END) or (TEKIYOU_BEGIN IS NULL and TEKIYOU_END IS NULL))
AND DELETE_FLG = 0 /*END*/
/*IF startCD != '' && startCD != null*/AND MT.TORIHIKISAKI_CD >= /*startCD*//*END*/
/*IF endCD != '' && endCD != null*/AND MT.TORIHIKISAKI_CD <= /*endCD*//*END*/
/*IF torihikiKBN == 2*/AND MTSE.TORIHIKI_KBN_CD = 1/*END*/
/*IF torihikiKBN == 1*/AND MTSE.TORIHIKI_KBN_CD = 2/*END*/
/*IF shimebi != '' && shimebi != null*/AND (MTSE.SHIMEBI1 = /*shimebi*/
OR MTSE.SHIMEBI2 = /*shimebi*/
OR MTSE.SHIMEBI3 = /*shimebi*/)/*END*/
ORDER BY MT.TORIHIKISAKI_CD
