SELECT
	 ISNULL(SEIDEN.KONKAI_SEIKYU_GAKU, 0) AS SEIKYUU_ZANDAKA,
	 SEIDEN.SEIKYUU_NUMBER,
	 SEIDEN.SEIKYUU_DATE AS EXEC_DATE
FROM
	T_SEIKYUU_DENPYOU AS SEIDEN
WHERE (SEIDEN.DELETE_FLG = 0) 
/*IF torihikisakiCD != null*/AND SEIDEN.TORIHIKISAKI_CD = /*torihikisakiCD*//*END*/
/*IF startDay != null*/AND CONVERT(DATETIME, CONVERT(nvarchar, SEIDEN.SEIKYUU_DATE, 111), 120) = (
	SELECT
		MAX(T_SEIKYUU_DENPYOU.SEIKYUU_DATE)
	FROM
		T_SEIKYUU_DENPYOU
	WHERE
		T_SEIKYUU_DENPYOU.DELETE_FLG = 0
		AND T_SEIKYUU_DENPYOU.SEIKYUU_DATE < /*startDay*/
		/*IF torihikisakiCD != null*/AND T_SEIKYUU_DENPYOU.TORIHIKISAKI_CD = /*torihikisakiCD*//*END*/)/*END*/
ORDER BY SEIDEN.SEIKYUU_NUMBER DESC

