SELECT
 *
FROM
(
SELECT   
    CONVERT(BIT, 0) AS CHECKBOX, 
    R18.MANIFEST_ID AS MANIFEST_ID,                      --マニフェスト番号
	CASE WHEN ISDATE(R18.HIKIWATASHI_DATE) = 0 THEN NULL ELSE CONVERT(DATETIME, R18.HIKIWATASHI_DATE) END AS HIKIWATASHI_DATE,            --引渡日
    R18.HST_SHA_NAME AS HST_GYOUSHA_NAME,                --排出事業者名
    R18.HST_JOU_NAME AS HST_GENBA_NAME,                  --排出事業場名
	R18.HAIKI_SHURUI AS HAIKI_SHURUI_NAME,               --廃棄物種類
    R18.HAIKI_NAME AS HAIKI_NAME,                        --廃棄物名称
	R18.HAIKI_SUU AS REPORT_SUU,                         --数量（明細）
	UNIT2.UNIT_NAME_RYAKU AS REPORT_UNIT_NAME,           --単位
	R19_EX.UPN_GYOUSHA_CD AS UPN_JYUTAKUSHA_CD,          --運搬受託者ＣＤ
	SHUSHU.UPN_SHA_NAME AS UPN_JYUTAKUSHA_NAME,          --運搬受託者名
	R18_EX.SBN_GYOUSHA_CD AS SBN_GYOUSHA_CD,             --処分事業者ＣＤ
	R18.SBN_SHA_NAME AS SBN_GYOUSHA_NAME,                --処分事業者名
	R18_EX.SBN_GENBA_CD AS SBN_GENBA_CD,                 --処分事業場ＣＤ
	SHUSHU.UPNSAKI_JOU_NAME AS SBN_GENBA_NAME,           --処分事業場名
	CASE WHEN TMD_2.DETAIL_SYSTEM_ID IS NOT NULL
    THEN TME_2.MANIFEST_ID
    ELSE R18EX_2.MANIFEST_ID
    END AS NEXT_MANIFEST_ID,                             --2次マニフェスト番号
	CASE WHEN TMD_2.DETAIL_SYSTEM_ID IS NOT NULL
    THEN TME_2.SBN_GYOUSHA_NAME
    ELSE R18_2.SBN_SHA_NAME
    END AS NEXT_SBN_GYOUSHA_NAME,                        --2次処分受託者名
	CASE WHEN TMD_2.DETAIL_SYSTEM_ID IS NOT NULL
    THEN TMU_2.UPN_SAKI_GENBA_NAME
    ELSE R19_2.UPNSAKI_JOU_NAME
    END AS NEXT_SBN_GENBA_NAME,                          --2次処分事業場名
	CASE WHEN TMD_2.DETAIL_SYSTEM_ID IS NOT NULL
    THEN TMD_2.LAST_SBN_END_DATE
    ELSE R13_2.LAST_SBN_END_DATE
    END AS LAST_SBN_END_DATE,                            --最終処分終了日
    MF_TOC.KANRI_ID AS KANRI_ID,
    MF_TOC.LATEST_SEQ AS LATEST_SEQ,
	R18_EX.SYSTEM_ID AS SYSTEM_ID
FROM
    DT_MF_TOC AS MF_TOC
    INNER JOIN DT_R18 AS R18
            ON MF_TOC.KANRI_ID = R18.KANRI_ID
           AND MF_TOC.LATEST_SEQ = R18.SEQ
	INNER JOIN DT_R18_EX AS R18_EX
	        ON R18.KANRI_ID = R18_EX.KANRI_ID
		   AND R18_EX.DELETE_FLG = 0
	LEFT JOIN
	(
		SELECT
			DT_R18_EX.KANRI_ID,
			CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
				THEN DT_R18_MIX.DETAIL_SYSTEM_ID
				ELSE DT_R18_EX.SYSTEM_ID
			END
			AS SYSTEM_ID,
			CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
				THEN DT_R18_MIX.SBN_ENDREP_KBN
				ELSE 1
			END
			AS SBN_ENDREP_KBN,
			CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
				THEN DT_R18_MIX.HAIKI_NAME_CD
				ELSE DT_R18_EX.HAIKI_NAME_CD
			END
			AS HAIKI_NAME_CD
		FROM
			DT_R18_EX
			LEFT JOIN DT_R18_MIX
			ON DT_R18_EX.SYSTEM_ID = DT_R18_MIX.SYSTEM_ID
			AND DT_R18_MIX.DELETE_FLG = 0
		WHERE
			DT_R18_EX.DELETE_FLG = 0
	)  AS MIX
	       ON R18.KANRI_ID = MIX.KANRI_ID
	INNER JOIN DT_R19 SHUSHU 
	        ON SHUSHU.KANRI_ID = R18.KANRI_ID 
		   AND SHUSHU.SEQ = R18.SEQ 
		   AND  SHUSHU.UPN_ROUTE_NO = (
		   SELECT MAX(UPN_ROUTE_NO) FROM DT_R19 
		   WHERE  DT_R19.KANRI_ID = R18.KANRI_ID AND DT_R19.SEQ = R18.SEQ)
	INNER JOIN MS_JWNET_MEMBER MEMBER ON R18.SBN_SHA_MEMBER_ID = MEMBER.EDI_MEMBER_ID
	LEFT JOIN DT_D10 UNPAN ON SHUSHU.KANRI_ID = UNPAN.KANRI_ID
	LEFT JOIN M_DENSHI_JIGYOUSHA DENSHI_JIGYOUSHA ON SHUSHU.UPN_SHA_EDI_MEMBER_ID = DENSHI_JIGYOUSHA.EDI_MEMBER_ID 
	LEFT JOIN  M_UNIT UNIT2 ON R18.HAIKI_UNIT_CODE = UNIT2.UNIT_CD
    LEFT JOIN DT_R19_EX AS R19_EX
        ON SHUSHU.KANRI_ID = R19_EX.KANRI_ID
        AND SHUSHU.UPN_ROUTE_NO = R19_EX.UPN_ROUTE_NO
        AND R19_EX.DELETE_FLG = 0
	LEFT JOIN T_MANIFEST_RELATION TMR --マニフェスト紐付（２次）
		ON TMR.FIRST_SYSTEM_ID = MIX.SYSTEM_ID
		AND TMR.FIRST_HAIKI_KBN_CD = 4
		AND TMR.DELETE_FLG = 0

	LEFT JOIN (
		SELECT
			SYSTEM_ID,
			DETAIL_SYSTEM_ID,
			MAX(SEQ) AS SEQ,
			LAST_SBN_END_DATE
		FROM T_MANIFEST_DETAIL TMP_TMD
		GROUP BY SYSTEM_ID,DETAIL_SYSTEM_ID,LAST_SBN_END_DATE
	) AS TMD_2  -- マニフェスト明細
	ON TMD_2.DETAIL_SYSTEM_ID = TMR.NEXT_SYSTEM_ID
	AND TMR.NEXT_HAIKI_KBN_CD <> 4

	LEFT JOIN  T_MANIFEST_ENTRY TME_2 -- マニフェスト
        ON TME_2.SYSTEM_ID = TMD_2.SYSTEM_ID
		AND TMD_2.SEQ = TME_2.SEQ
		AND TME_2.DELETE_FLG = 0

	--LEFT JOIN  T_MANIFEST_ENTRY TME_2 -- マニフェスト
 --       ON TME_2.SYSTEM_ID = TMR.NEXT_SYSTEM_ID
 --       AND TMR.NEXT_HAIKI_KBN_CD <> 4
	--	AND TME_2.DELETE_FLG = 0
	--LEFT JOIN  T_MANIFEST_DETAIL TMD_2 -- マニフェスト明細
 --       ON TMD_2.SYSTEM_ID = TME_2.SYSTEM_ID
 --       AND TMD_2.SEQ = TME_2.SEQ
	LEFT JOIN (SELECT TMU1.* FROM T_MANIFEST_ENTRY TME1 
	           INNER JOIN T_MANIFEST_UPN TMU1 
	              ON TMU1.SYSTEM_ID = TME1.SYSTEM_ID 
				  AND TMU1.SEQ = TME1.SEQ 
				  AND TMU1.UPN_ROUTE_NO = 1 
			   WHERE (TME1.HAIKI_KBN_CD = 1 OR TME1.HAIKI_KBN_CD =2) 
			      AND TME1.DELETE_FLG =0 
				  AND TME1.SEQ = (SELECT MAX(SEQ) FROM T_MANIFEST_ENTRY WHERE SYSTEM_ID = TME1.SYSTEM_ID)
	           UNION
	           SELECT TMU2.* FROM T_MANIFEST_ENTRY TME2 
			   INNER JOIN T_MANIFEST_UPN TMU2 
			      ON TMU2.SYSTEM_ID = TME2.SYSTEM_ID 
				 AND TMU2.SEQ = TME2.SEQ AND TME2.HAIKI_KBN_CD = 3  
				 AND TMU2.UPN_ROUTE_NO = (SELECT MIN(UPN_ROUTE_NO) FROM T_MANIFEST_UPN 
				                          WHERE TME2.SYSTEM_ID = SYSTEM_ID 
										    AND SEQ = TME2.SEQ 
											AND TME2.HAIKI_KBN_CD = 3 
											AND UPN_SAKI_KBN = 1) 
			     AND TME2.DELETE_FLG = 0) TMU_2 
		  ON TMU_2.SYSTEM_ID = TME_2.SYSTEM_ID 
		  AND TMU_2.SEQ = TME_2.SEQ
	LEFT JOIN DT_R18_EX AS R18EX_2 ON TMR.NEXT_SYSTEM_ID = R18EX_2.SYSTEM_ID AND TMR.NEXT_HAIKI_KBN_CD = 4 AND R18EX_2.DELETE_FLG = 0
    LEFT JOIN DT_MF_TOC AS TOC_2 ON R18EX_2.KANRI_ID = TOC_2.KANRI_ID
    LEFT JOIN DT_R18 AS R18_2 ON TOC_2.KANRI_ID = R18_2.KANRI_ID AND TOC_2.LATEST_SEQ = R18_2.SEQ
    LEFT JOIN DT_R13 AS R13_2 ON TOC_2.KANRI_ID = R13_2.KANRI_ID AND TOC_2.LATEST_SEQ = R13_2.SEQ
    LEFT JOIN DT_R13_EX AS R13_EX_2 ON R18EX_2.KANRI_ID = R13_EX_2.KANRI_ID AND R13_EX_2.DELETE_FLG = 0 AND R13_2.REC_SEQ = R13_EX_2.REC_SEQ
	LEFT JOIN DT_R19 R19_2 
	        ON R19_2.KANRI_ID = R18_2.KANRI_ID 
		   AND R19_2.SEQ = R18_2.SEQ 
		   AND  R19_2.UPN_ROUTE_NO = (
		   SELECT MAX(UPN_ROUTE_NO) FROM DT_R19 
		   WHERE  DT_R19.KANRI_ID = R18_2.KANRI_ID AND DT_R19.SEQ = R18_2.SEQ)
WHERE
    1=2
) SEARCH_DATA
WHERE NEXT_MANIFEST_ID IS NOT NULL