----マニフェスト紐付対象取得
SELECT * FROM (
SELECT DISTINCT
C.KANRI_ID AS KANRI_ID, --マニフェスト目次情報.管理番号	
C.LATEST_SEQ AS LATEST_SEQ,  --マニフェスト目次情報.最新SEQ
CASE WHEN G.MANIFEST_ID IS NOT NULL
    THEN G.MANIFEST_ID
    ELSE R18EX_2.MANIFEST_ID
END AS MANIFEST_ID, --マニフェスト.交付番号
CASE WHEN H.DETAIL_SYSTEM_ID IS NOT NULL
    THEN H.LAST_SBN_END_DATE
    ELSE R13_2.LAST_SBN_END_DATE
END AS LAST_SBN_END_DATE,--マニフェスト明細.最終処分終了日
CASE WHEN H.DETAIL_SYSTEM_ID IS NOT NULL
    THEN H.LAST_SBN_GENBA_CD
    ELSE R13_EX_2.LAST_SBN_GENBA_CD
END AS LAST_SBN_GENBA_CD, -- マニフェスト明細.最終処分終了場所
CASE WHEN H.DETAIL_SYSTEM_ID IS NOT NULL
    THEN M.GENBA_NAME1
    ELSE R13_2.LAST_SBN_JOU_NAME
END AS GENBA_NAME1,--現場マスタ.現場名1
CASE WHEN H.DETAIL_SYSTEM_ID IS NOT NULL
    THEN M.GENBA_POST
    ELSE R13_2.LAST_SBN_JOU_POST
END AS GENBA_POST,--現場マスタ.現場郵便番号
CASE WHEN H.DETAIL_SYSTEM_ID IS NOT NULL
    THEN M.GENBA_TEL
    ELSE R13_2.LAST_SBN_JOU_TEL
END AS GENBA_TEL,--現場マスタ.現場TEL
CASE WHEN H.DETAIL_SYSTEM_ID IS NOT NULL
    THEN N.TODOUFUKEN_NAME
    ELSE ''
END AS TODOUFUKEN_NAME,--都道府県マスタ.都道府県名
O.CHIIKI_NAME,--地域マスタ.地域名
P.SHIKUCHOUSON_NAME,--市区町村マスタ.市区町村名
CASE WHEN H.DETAIL_SYSTEM_ID IS NOT NULL
    THEN M.GENBA_ADDRESS1
    ELSE ISNULL(R13_2.LAST_SBN_JOU_ADDRESS1, '') + ISNULL(R13_2.LAST_SBN_JOU_ADDRESS2, '') + ISNULL(R13_2.LAST_SBN_JOU_ADDRESS3, '') + ISNULL(R13_2.LAST_SBN_JOU_ADDRESS4, '')
END AS GENBA_ADDRESS1,--現場マスタ.現場住所1
CASE WHEN H.DETAIL_SYSTEM_ID IS NOT NULL
    THEN M.GENBA_ADDRESS2
    ELSE ''
END AS GENBA_ADDRESS2,--現場マスタ.現場住所2
'' AS GENBA_ADDRESS3,
'' AS GENBA_ADDRESS4,
CASE WHEN G.SYSTEM_ID IS NOT NULL
    THEN G.SYSTEM_ID
    ELSE R18EX_2.SYSTEM_ID
END AS SYSTEM_ID,--マニフェスト．システムID
H.DETAIL_SYSTEM_ID, -- 明細システムID
R13_2.REC_SEQ, -- 電マニ.最終処分情報の行
C.UPDATE_TS, --タイムスタンプ
C.STATUS_FLAG, -- 状態フラグ
C.STATUS_DETAIL, -- 状態詳細フラグ
C.APPROVAL_SEQ, -- 修正/取消中SEQ
HURIWAKE_DATA.SBN_ENDREP_KBN, -- 処分終了報告区分
HAIKI_SHURUI.KONGOU_KBN -- 混合区分

FROM T_MANIFEST_RELATION A -- マニフェスト紐付
INNER JOIN (
    SELECT
        CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL
            THEN MIX.KANRI_ID
            ELSE EX.KANRI_ID
        END
        AS KANRI_ID,
        CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL
            THEN MIX.DETAIL_SYSTEM_ID
            ELSE EX.SYSTEM_ID
        END
        AS SYSTEM_ID,
        CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL
            THEN MIX.DELETE_FLG
            ELSE EX.DELETE_FLG
        END
        AS DELETE_FLG,
		EX.HAIKI_NAME_CD
    FROM
        DT_R18_EX AS EX
        LEFT JOIN DT_R18_MIX AS MIX
        ON EX.SYSTEM_ID = MIX.SYSTEM_ID
        AND MIX.DELETE_FLG = 0
    WHERE
        EX.DELETE_FLG = 0
) AS B --電子マニフェスト基本拡張
ON A.FIRST_SYSTEM_ID = B.SYSTEM_ID
INNER JOIN DT_MF_TOC C --マニフェスト目次情報
ON B.KANRI_ID = C.KANRI_ID
INNER JOIN DT_R18 R -- R18 マニフェスト情報
ON R.KANRI_ID = C.KANRI_ID
AND R.SEQ = C.LATEST_SEQ
AND R.SEQ = C.LATEST_SEQ
AND (R.LAST_SBN_ENDREP_FLAG = 0 OR R.LAST_SBN_ENDREP_FLAG IS NULL)

-- 混廃振分データ取得(混廃じゃない場合はDT_R18_EXが一件取得される)
LEFT JOIN
(
    SELECT
        DT_R18_EX.KANRI_ID,
        CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
            THEN DT_R18_MIX.DETAIL_SYSTEM_ID
            ELSE DT_R18_EX.SYSTEM_ID
        END
        AS SYSTEM_ID,
        CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
            THEN DT_R18_MIX.SBN_ENDREP_KBN
            ELSE 1
        END
        AS SBN_ENDREP_KBN
    FROM
        DT_R18_EX
        LEFT JOIN DT_R18_MIX
        ON DT_R18_EX.SYSTEM_ID = DT_R18_MIX.SYSTEM_ID
        AND DT_R18_MIX.DELETE_FLG = 0
    WHERE
        DT_R18_EX.DELETE_FLG = 0
)
AS HURIWAKE_DATA
ON C.KANRI_ID = HURIWAKE_DATA.KANRI_ID

INNER JOIN DT_R19 SHUSHU 
ON SHUSHU.KANRI_ID = R.KANRI_ID 
AND SHUSHU.SEQ = R.SEQ
AND  SHUSHU.UPN_ROUTE_NO = (
     SELECT MAX(UPN_ROUTE_NO) FROM DT_R19
	 WHERE  DT_R19.KANRI_ID = R.KANRI_ID AND DT_R19.SEQ = R.SEQ)

LEFT JOIN T_MANIFEST_RELATION F --マニフェスト紐付（２次）
ON F.FIRST_SYSTEM_ID = HURIWAKE_DATA.SYSTEM_ID
AND F.FIRST_HAIKI_KBN_CD = 4
AND F.DELETE_FLG = 0
LEFT JOIN  
        (SELECT 
             T_MANIFEST_ENTRY.*,
             T_MANIFEST_DETAIL.DETAIL_SYSTEM_ID
         FROM T_MANIFEST_ENTRY 
         LEFT JOIN T_MANIFEST_DETAIL 
                ON T_MANIFEST_DETAIL.SYSTEM_ID = T_MANIFEST_ENTRY.SYSTEM_ID
               AND T_MANIFEST_DETAIL.SEQ = T_MANIFEST_ENTRY.SEQ) G -- マニフェスト
ON G.DETAIL_SYSTEM_ID = F.NEXT_SYSTEM_ID
AND F.NEXT_HAIKI_KBN_CD <> 4
AND G.DELETE_FLG = 0
LEFT JOIN  T_MANIFEST_DETAIL H -- マニフェスト明細
ON H.SYSTEM_ID = G.SYSTEM_ID
AND H.SEQ = G.SEQ
AND H.DETAIL_SYSTEM_ID = G.DETAIL_SYSTEM_ID
LEFT JOIN T_LAST_SBN_SUSPEND  E --最終処分保留
ON F.NEXT_SYSTEM_ID = E.SYSTEM_ID
AND E.DELETE_FLG = 0
--現場マスタ
LEFT JOIN M_GENBA M
ON M.GYOUSHA_CD = H.LAST_SBN_GYOUSHA_CD
AND M.GENBA_CD = H.LAST_SBN_GENBA_CD
AND M.SAISHUU_SHOBUNJOU_KBN = 1
--都道府県マスタ
LEFT JOIN M_TODOUFUKEN N
ON N.TODOUFUKEN_CD = M.GENBA_TODOUFUKEN_CD
--地域マスタ
LEFT JOIN M_CHIIKI O
ON O.CHIIKI_CD = M.CHIIKI_CD
--市区町村マスタ
LEFT JOIN M_SHIKUCHOUSON P
ON P.SHIKUCHOUSON_CD = M.SHIKUCHOUSON_CD
-- 廃棄物種類(混合区分を取得する)
LEFT JOIN M_DENSHI_HAIKI_SHURUI AS HAIKI_SHURUI
ON R.HAIKI_DAI_CODE + R.HAIKI_CHU_CODE + R.HAIKI_SHO_CODE = HAIKI_SHURUI.HAIKI_SHURUI_CD
LEFT JOIN DT_R18_EX AS R18EX_2 ON F.NEXT_SYSTEM_ID = R18EX_2.SYSTEM_ID AND F.NEXT_HAIKI_KBN_CD = 4 AND R18EX_2.DELETE_FLG = 0
LEFT JOIN DT_MF_TOC AS TOC_2 ON R18EX_2.KANRI_ID = TOC_2.KANRI_ID
LEFT JOIN DT_R13 AS R13_2 ON TOC_2.KANRI_ID = R13_2.KANRI_ID AND TOC_2.LATEST_SEQ = R13_2.SEQ
LEFT JOIN DT_R13_EX AS R13_EX_2 ON R18EX_2.KANRI_ID = R13_EX_2.KANRI_ID AND R13_EX_2.DELETE_FLG = 0 AND R13_2.REC_SEQ = R13_EX_2.REC_SEQ

WHERE
A.DELETE_FLG = 0               --マニフェスト紐付.削除フラグ
AND A.FIRST_HAIKI_KBN_CD = 4       --マニフェスト紐付.一次廃棄物区分CD
AND B.DELETE_FLG = 0               --電子マニフェスト基本拡張.削除フラグ
AND E.SYSTEM_ID IS NULL            -- 最終処分保留.システムID
AND (G.DELETE_FLG = 0 OR G.DELETE_FLG IS NULL) --マニフェスト.削除フラグ
AND HURIWAKE_DATA.SBN_ENDREP_KBN = 1 -- 混合廃棄物.処分終了報告区分
/*IF data.HIKIWATASHI_DATE_FROM != null && data.HIKIWATASHI_DATE_FROM != ''*/
AND	R.HIKIWATASHI_DATE >= /*data.HIKIWATASHI_DATE_FROM*/
/*END*/ 
/*IF data.HIKIWATASHI_DATE_TO != null && data.HIKIWATASHI_DATE_TO != ''*/
AND	R.HIKIWATASHI_DATE <= /*data.HIKIWATASHI_DATE_TO*/
/*END*/
/*IF data.MANIFEST_ID_FROM != null && data.MANIFEST_ID_FROM != ''*/
AND	R.MANIFEST_ID >= /*data.MANIFEST_ID_FROM*/
/*END*/
/*IF data.MANIFEST_ID_TO != null && data.MANIFEST_ID_TO != ''*/
AND	R.MANIFEST_ID <= /*data.MANIFEST_ID_TO*/
/*END*/
/*IF data.HAIKI_SHURUI_CD != null && data.HAIKI_SHURUI_CD != ''*/
AND	R.HAIKI_DAI_CODE = /*data.HAIKI_DAI_CODE*/
AND	R.HAIKI_CHU_CODE = /*data.HAIKI_CHU_CODE*/
AND	R.HAIKI_SHO_CODE = /*data.HAIKI_SHO_CODE*/
/*END*/
/*IF data.HAIKI_NAME_CD != null && data.HAIKI_NAME_CD != ''*/
AND	B.HAIKI_NAME_CD = /*data.HAIKI_NAME_CD*/
/*END*/
/*IF data.HST_GYOUSHA_CD != null && data.HST_GYOUSHA_CD != ''*/
AND	R.HST_SHA_EDI_MEMBER_ID = /*data.HST_GYOUSHA_CD*/
/*END*/
/*IF data.HST_GENBA_CD != null && data.HST_GENBA_CD != ''*/
AND	EXISTS (SELECT * FROM DT_R18 DTR18,M_DENSHI_JIGYOUJOU
            WHERE  DTR18.KANRI_ID = R.KANRI_ID
			   AND DTR18.SEQ = R.SEQ
			   AND M_DENSHI_JIGYOUJOU.EDI_MEMBER_ID = /*data.HST_GYOUSHA_CD*/
			   AND M_DENSHI_JIGYOUJOU.JIGYOUJOU_CD = /*data.HST_GENBA_CD*/
			   AND DTR18.HST_JOU_NAME = M_DENSHI_JIGYOUJOU.JIGYOUJOU_NAME
			   AND (DTR18.HST_JOU_ADDRESS1 + DTR18.HST_JOU_ADDRESS2 + DTR18.HST_JOU_ADDRESS3 + DTR18.HST_JOU_ADDRESS4)
			   = (M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS1 + M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS2 + M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS3 + M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS4))
/*END*/
/*IF data.UPN_GYOUSHA_CD != null && data.UPN_GYOUSHA_CD != ''*/
AND	SHUSHU.UPN_SHA_EDI_MEMBER_ID = /*data.UPN_GYOUSHA_CD*/
/*END*/
/*IF data.UPN_GYOUSHA_CD != null && data.UPN_GYOUSHA_CD != ''*/
AND	SHUSHU.UPN_SHA_EDI_MEMBER_ID = /*data.UPN_GYOUSHA_CD*/
/*END*/
/*IF data.SBN_GYOUSHA_CD != null && data.SBN_GYOUSHA_CD != ''*/
AND	SHUSHU.UPNSAKI_EDI_MEMBER_ID = /*data.SBN_GYOUSHA_CD*/
/*END*/

AND NOT EXISTS(
SELECT
*
FROM
(
    SELECT
        DT_R18_EX.KANRI_ID,
        CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
            THEN DT_R18_MIX.DETAIL_SYSTEM_ID
            ELSE DT_R18_EX.SYSTEM_ID
        END
        AS SYSTEM_ID,
        CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
            THEN DT_R18_MIX.DELETE_FLG
            ELSE DT_R18_EX.DELETE_FLG
        END
        AS DELETE_FLG
    FROM
        DT_R18_EX
        LEFT JOIN DT_R18_MIX
            ON DT_R18_EX.SYSTEM_ID = DT_R18_MIX.SYSTEM_ID
            AND DT_R18_MIX.DELETE_FLG = 0
) AS I --電子マニフェスト基本拡張
INNER JOIN DT_MF_TOC J --マニフェスト目次情報
ON I.KANRI_ID = J.KANRI_ID
INNER JOIN DT_R18 K -- R18 マニフェスト情報
ON K.KANRI_ID = J.KANRI_ID
AND K.SEQ = J.LATEST_SEQ
INNER JOIN DT_D13 L -- R13 最終処分終了日・事業場情報
ON L.KANRI_ID = K.KANRI_ID
AND L.D13_SEQ = K.SEQ
WHERE
I.SYSTEM_ID = F.NEXT_SYSTEM_ID
AND F.NEXT_HAIKI_KBN_CD = 4
AND I.DELETE_FLG = 0
AND (K.LAST_SBN_ENDREP_FLAG = 0 OR K.LAST_SBN_ENDREP_FLAG IS NULL)
AND K.LAST_SBN_END_DATE IS NULL
AND L.LAST_SBN_JOU_NAME IS NULL
AND (L.LAST_SBN_JOU_ADDRESS1 IS NULL
OR L.LAST_SBN_JOU_ADDRESS2 IS NULL
OR L.LAST_SBN_JOU_ADDRESS3 IS NULL
OR L.LAST_SBN_JOU_ADDRESS4 IS NULL)
)
) A
WHERE A.LAST_SBN_END_DATE IS NOT NULL
  AND A.LAST_SBN_GENBA_CD IS NOT NULL

UNION ALL

SELECT * FROM (
----電子マニフェスト紐付対象取得
SELECT DISTINCT
    DMT1.KANRI_ID,                       --管理番号
    DMT1.LATEST_SEQ,                     --最新SEQ
    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN DT_R13.MANIFEST_ID
        ELSE ME.MANIFEST_ID
    END AS MANIFEST_ID,                  --R13 最終処分終了日・事業場情報.マニフェスト／予約番号
    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN CONVERT(VARCHAR, DT_R13.LAST_SBN_END_DATE, 112)
        ELSE CONVERT(VARCHAR, MD.LAST_SBN_END_DATE, 112)
    END AS LAST_SBN_END_DATE,            --R13 最終処分終了日・事業場情報.最終処分終了日

    '' AS LAST_SBN_GENBA_CD,

    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN DT_R13.LAST_SBN_JOU_NAME
        ELSE M_GENBA.GENBA_NAME1
    END AS GENBA_NAME1,                  --R13 最終処分終了日・事業場情報.最終処分事業場名称

    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN DT_R13.LAST_SBN_JOU_POST
        ELSE M_GENBA.GENBA_POST
    END AS GENBA_POST,                   --R13 最終処分終了日・事業場情報.最終処分事業場所在地の郵便番号
    
    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN DT_R13.LAST_SBN_JOU_TEL
        ELSE M_GENBA.GENBA_TEL
    END AS GENBA_TEL,                    --R13 最終処分終了日・事業場情報.最終処分事業場電話番号

    '' AS TODOUFUKEN_NAME,
    '' AS CHIIKI_NAME,
    '' AS SHIKUCHOUSON_NAME,

    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS1, '')
        ELSE ISNULL(M_TODOUFUKEN.TODOUFUKEN_NAME, '')
    END AS GENBA_ADDRESS1,               --R13 最終処分終了日・事業場情報.最終処分事業場所在地１

    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS2, '')
        ELSE ISNULL(M_GENBA.GENBA_ADDRESS1, '')
    END AS GENBA_ADDRESS2,               --R13 最終処分終了日・事業場情報.最終処分事業場所在地２
    
    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS3, '')
        ELSE ISNULL(M_GENBA.GENBA_ADDRESS2, '')
    END AS GENBA_ADDRESS3,               --R13 最終処分終了日・事業場情報.最終処分事業場所在地３

    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN ISNULL(DT_R13.LAST_SBN_JOU_ADDRESS4, '')
        ELSE ''
    END AS GENBA_ADDRESS4,               --R13 最終処分終了日・事業場情報.最終処分事業場所在地４

    --システムID
    TMR2.NEXT_SYSTEM_ID AS SYSTEM_ID,
    '' AS DETAIL_SYSTEM_ID,

    -- 最終処分情報が重複除外されるのを防ぐ
    CASE WHEN ISNULL(R18_EX2.SYSTEM_ID, '') <> ''
        THEN DT_R13.REC_SEQ
        ELSE MD.DETAIL_SYSTEM_ID
    END AS REC_SEQ,

    --タイムスタンプ
    DMT1.UPDATE_TS,
    --状態フラグ
    DMT1.STATUS_FLAG,
    --状態詳細フラグ
    DMT1.STATUS_DETAIL,
    --修正/取消中SEQ
    DMT1.APPROVAL_SEQ,

    HURIWAKE_DATA.SBN_ENDREP_KBN, -- 処分終了報告区分
    HAIKI_SHURUI.KONGOU_KBN -- 混合区分

FROM
    --電子マニフェスト基本拡張
    DT_R18_EX
    --マニフェスト紐付　AS　マニフェスト紐付（１次）
    INNER JOIN T_MANIFEST_RELATION TMR1 ON TMR1.NEXT_SYSTEM_ID = DT_R18_EX.SYSTEM_ID
    --電子マニフェスト基本拡張（１次）
    INNER JOIN (
        SELECT
            DT_R18_EX.KANRI_ID,
            CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
                THEN DT_R18_MIX.DETAIL_SYSTEM_ID
                ELSE DT_R18_EX.SYSTEM_ID
            END
            AS SYSTEM_ID,
            CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
                THEN DT_R18_MIX.DELETE_FLG
                ELSE DT_R18_EX.DELETE_FLG
            END
            AS DELETE_FLG
        FROM
            DT_R18_EX
            LEFT JOIN DT_R18_MIX
            ON DT_R18_EX.SYSTEM_ID = DT_R18_MIX.SYSTEM_ID
            AND DT_R18_MIX.DELETE_FLG = 0
        WHERE
            DT_R18_EX.DELETE_FLG = 0
    ) AS R18_EX1 ON R18_EX1.SYSTEM_ID = TMR1.FIRST_SYSTEM_ID
                               AND TMR1.FIRST_HAIKI_KBN_CD = 4
                               AND R18_EX1.DELETE_FLG = 0
    --マニフェスト目次情報（１次）
    INNER JOIN DT_MF_TOC DMT1 ON DMT1.KANRI_ID = R18_EX1.KANRI_ID
    INNER JOIN DT_R18 DT_R18_1 ON DT_R18_1.KANRI_ID = DMT1.KANRI_ID AND DT_R18_1.SEQ = DMT1.LATEST_SEQ

    -- 混廃振分データ取得(混廃じゃない場合はDT_R18_EXが一件取得される)
    LEFT JOIN
    (
        SELECT
            DT_R18_EX.KANRI_ID,
            CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
                THEN DT_R18_MIX.DETAIL_SYSTEM_ID
                ELSE DT_R18_EX.SYSTEM_ID
            END
            AS SYSTEM_ID,
            CASE WHEN DT_R18_MIX.DETAIL_SYSTEM_ID IS NOT NULL
                THEN DT_R18_MIX.SBN_ENDREP_KBN
                ELSE 1
            END
            AS SBN_ENDREP_KBN
        FROM
            DT_R18_EX
            LEFT JOIN DT_R18_MIX
            ON DT_R18_EX.SYSTEM_ID = DT_R18_MIX.SYSTEM_ID
            AND DT_R18_MIX.DELETE_FLG = 0
        WHERE
            DT_R18_EX.DELETE_FLG = 0
    )
    AS HURIWAKE_DATA
    ON DT_R18_1.KANRI_ID = HURIWAKE_DATA.KANRI_ID

    INNER JOIN DT_R19 SHUSHU 
    ON SHUSHU.KANRI_ID = DT_R18_1.KANRI_ID 
    AND SHUSHU.SEQ = DT_R18_1.SEQ
    AND SHUSHU.UPN_ROUTE_NO = (SELECT MAX(UPN_ROUTE_NO) FROM DT_R19 WHERE  DT_R19.KANRI_ID = DT_R18_1.KANRI_ID AND DT_R19.SEQ = DT_R18_1.SEQ)

    ----マニフェスト紐付　AS　マニフェスト紐付（２次）
    LEFT JOIN T_MANIFEST_RELATION TMR2 ON TMR2.FIRST_SYSTEM_ID = HURIWAKE_DATA.SYSTEM_ID
    AND TMR2.FIRST_HAIKI_KBN_CD = 4
    AND TMR2.DELETE_FLG = 0
    --電子マニフェスト基本拡張（２次）
    LEFT JOIN DT_R18_EX R18_EX2 ON R18_EX2.SYSTEM_ID = TMR2.NEXT_SYSTEM_ID
                               AND TMR2.NEXT_HAIKI_KBN_CD = 4
                               AND R18_EX2.DELETE_FLG = 0
    --マニフェスト目次情報（２次）
    LEFT JOIN DT_MF_TOC DMT2 ON DMT2.KANRI_ID = R18_EX2.KANRI_ID
    --マニフェスト情報
    LEFT JOIN DT_R18 DT_R18_2 ON DT_R18_2.KANRI_ID = DMT2.KANRI_ID
                              AND DT_R18_2.SEQ = DMT2.LATEST_SEQ
    --R13 最終処分終了日・事業場情報
    LEFT JOIN DT_R13 ON DT_R13.KANRI_ID = DT_R18_2.KANRI_ID
                     AND DT_R13.SEQ = DT_R18_2.SEQ
    --最終処分保留
    LEFT JOIN T_LAST_SBN_SUSPEND TLSS ON TLSS.SYSTEM_ID = TMR2.NEXT_SYSTEM_ID AND TLSS.DELETE_FLG = 0
    LEFT JOIN 
        (SELECT T_MANIFEST_ENTRY.*, T_MANIFEST_DETAIL.DETAIL_SYSTEM_ID
           FROM T_MANIFEST_ENTRY
           LEFT JOIN T_MANIFEST_DETAIL 
             ON T_MANIFEST_DETAIL.SYSTEM_ID = T_MANIFEST_ENTRY.SYSTEM_ID
            AND T_MANIFEST_DETAIL.SEQ = T_MANIFEST_ENTRY.SEQ) AS ME ON TMR2.NEXT_SYSTEM_ID = ME.DETAIL_SYSTEM_ID AND TMR2.NEXT_HAIKI_KBN_CD <> 4 AND ME.DELETE_FLG = 0
    LEFT JOIN T_MANIFEST_DETAIL AS MD ON ME.SYSTEM_ID = MD.SYSTEM_ID AND ME.SEQ = MD.SEQ
    LEFT JOIN M_GENBA ON MD.LAST_SBN_GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND MD.LAST_SBN_GENBA_CD = M_GENBA.GENBA_CD AND M_GENBA.SAISHUU_SHOBUNJOU_KBN = 1
    LEFT JOIN M_TODOUFUKEN ON M_GENBA.GENBA_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD
    -- 廃棄物種類(混合区分を取得する)
    LEFT JOIN M_DENSHI_HAIKI_SHURUI AS HAIKI_SHURUI ON DT_R18_1.HAIKI_DAI_CODE + DT_R18_1.HAIKI_CHU_CODE + DT_R18_1.HAIKI_SHO_CODE = HAIKI_SHURUI.HAIKI_SHURUI_CD
WHERE DT_R18_EX.DELETE_FLG = 0
  AND (DT_R18_1.LAST_SBN_ENDREP_FLAG IS NULL OR DT_R18_1.LAST_SBN_ENDREP_FLAG = 0)
  AND HURIWAKE_DATA.SBN_ENDREP_KBN = 1
  AND TLSS.SYSTEM_ID IS NULL

/*IF data.HIKIWATASHI_DATE_FROM != null && data.HIKIWATASHI_DATE_FROM != ''*/
AND	DT_R18_1.HIKIWATASHI_DATE >= /*data.HIKIWATASHI_DATE_FROM*/
/*END*/ 
/*IF data.HIKIWATASHI_DATE_TO != null && data.HIKIWATASHI_DATE_TO != ''*/
AND	DT_R18_1.HIKIWATASHI_DATE <= /*data.HIKIWATASHI_DATE_TO*/
/*END*/
/*IF data.MANIFEST_ID_FROM != null && data.MANIFEST_ID_FROM != ''*/
AND	DT_R18_1.MANIFEST_ID >= /*data.MANIFEST_ID_FROM*/
/*END*/
/*IF data.MANIFEST_ID_TO != null && data.MANIFEST_ID_TO != ''*/
AND	DT_R18_1.MANIFEST_ID <= /*data.MANIFEST_ID_TO*/
/*END*/
/*IF data.HAIKI_SHURUI_CD != null && data.HAIKI_SHURUI_CD != ''*/
AND	DT_R18_1.HAIKI_DAI_CODE = /*data.HAIKI_DAI_CODE*/
AND	DT_R18_1.HAIKI_CHU_CODE = /*data.HAIKI_CHU_CODE*/
AND	DT_R18_1.HAIKI_SHO_CODE = /*data.HAIKI_SHO_CODE*/
/*END*/
/*IF data.HAIKI_NAME_CD != null && data.HAIKI_NAME_CD != ''*/
AND	DT_R18_EX.HAIKI_NAME_CD = /*data.HAIKI_NAME_CD*/
/*END*/
/*IF data.HST_GYOUSHA_CD != null && data.HST_GYOUSHA_CD != ''*/
AND	DT_R18_1.HST_SHA_EDI_MEMBER_ID = /*data.HST_GYOUSHA_CD*/
/*END*/
/*IF data.HST_GENBA_CD != null && data.HST_GENBA_CD != ''*/
AND	EXISTS (SELECT * FROM DT_R18 DTR18,M_DENSHI_JIGYOUJOU
            WHERE  DTR18.KANRI_ID = DT_R18_1.KANRI_ID
			   AND DTR18.SEQ = DT_R18_1.SEQ
			   AND M_DENSHI_JIGYOUJOU.EDI_MEMBER_ID = /*data.HST_GYOUSHA_CD*/
			   AND M_DENSHI_JIGYOUJOU.JIGYOUJOU_CD = /*data.HST_GENBA_CD*/
			   AND DTR18.HST_JOU_NAME = M_DENSHI_JIGYOUJOU.JIGYOUJOU_NAME
			   AND (DTR18.HST_JOU_ADDRESS1 + DTR18.HST_JOU_ADDRESS2 + DTR18.HST_JOU_ADDRESS3 + DTR18.HST_JOU_ADDRESS4)
			   = (M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS1 + M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS2 + M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS3 + M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS4))
/*END*/
/*IF data.UPN_GYOUSHA_CD != null && data.UPN_GYOUSHA_CD != ''*/
AND	SHUSHU.UPN_SHA_EDI_MEMBER_ID = /*data.UPN_GYOUSHA_CD*/
/*END*/
/*IF data.UPN_GYOUSHA_CD != null && data.UPN_GYOUSHA_CD != ''*/
AND	SHUSHU.UPN_SHA_EDI_MEMBER_ID = /*data.UPN_GYOUSHA_CD*/
/*END*/
/*IF data.SBN_GYOUSHA_CD != null && data.SBN_GYOUSHA_CD != ''*/
AND	SHUSHU.UPNSAKI_EDI_MEMBER_ID = /*data.SBN_GYOUSHA_CD*/
/*END*/
) B
WHERE B.LAST_SBN_END_DATE IS NOT NULL
  AND B.GENBA_NAME1 IS NOT NULL
  AND (B.GENBA_ADDRESS1 != '' OR B.GENBA_ADDRESS2 != '' OR B.GENBA_ADDRESS3 != '' OR B.GENBA_ADDRESS4 != '')