SELECT
    MANI_MAIN.KANRI_ID AS KANRI_ID, --管理番号
    MANI_MAIN.LATEST_SEQ AS LATEST_SEQ,  --最新SEQ
    MANI_REL_OWN.NEXT_SYSTEM_ID AS SYSTEM_ID,
    MANI_MAIN.UPDATE_TS,
    MANI_MAIN.STATUS_FLAG, -- 状態フラグ
    MANI_MAIN.STATUS_DETAIL, -- 状態詳細フラグ
    MANI_MAIN.APPROVAL_SEQ -- 修正/取消中SEQ
FROM 
    (
        SELECT
            FIRST_SYSTEM_ID, NEXT_SYSTEM_ID
        FROM
            T_MANIFEST_RELATION 
        WHERE
            DELETE_FLG = 0
            AND FIRST_HAIKI_KBN_CD = 4
    ) MANI_REL_OWN --自身のマニフェスト紐付情報
INNER JOIN 
    (
        SELECT
            TOC.KANRI_ID,
            TOC.LATEST_SEQ,
            TOC.APPROVAL_SEQ,
            TOC.STATUS_FLAG,
            TOC.STATUS_DETAIL,
            TOC.UPDATE_TS,
            MANI.SYSTEM_ID
        FROM
            DT_MF_TOC TOC
            INNER JOIN DT_R18 R18 ON TOC.KANRI_ID = R18.KANRI_ID AND TOC.LATEST_SEQ = R18.SEQ
            LEFT JOIN DT_R18_EX R18E ON R18.KANRI_ID = R18E.KANRI_ID AND R18E.DELETE_FLG = 0
            LEFT JOIN DT_R18_MIX R18M ON R18E.SYSTEM_ID = R18M.SYSTEM_ID AND R18M.DELETE_FLG = 0
			LEFT JOIN (SELECT R18E.KANRI_ID
			                 ,CASE WHEN R18M.DETAIL_SYSTEM_ID IS NOT NULL THEN R18M.DETAIL_SYSTEM_ID ELSE R18E.SYSTEM_ID END SYSTEM_ID
					   FROM DT_R18_EX R18E
					   LEFT JOIN DT_R18_MIX R18M ON R18E.SYSTEM_ID = R18M.SYSTEM_ID AND R18M.DELETE_FLG = 0
					   WHERE R18E.DELETE_FLG = 0) MANI
				   ON R18.KANRI_ID = MANI.KANRI_ID
			INNER JOIN DT_R19 SHUSHU 
                    ON SHUSHU.KANRI_ID = R18.KANRI_ID 
                   AND SHUSHU.SEQ = R18.SEQ
                   AND SHUSHU.UPN_ROUTE_NO = (
                                            SELECT MAX(UPN_ROUTE_NO) FROM DT_R19
	                                        WHERE  DT_R19.KANRI_ID = R18.KANRI_ID AND DT_R19.SEQ = R18.SEQ)
        WHERE
            R18.LAST_SBN_ENDREP_FLAG = '1'
            AND TOC.STATUS_FLAG IN (3, 4)
			/*IF data.HIKIWATASHI_DATE_FROM != null && data.HIKIWATASHI_DATE_FROM != ''*/
			AND	R18.HIKIWATASHI_DATE >= /*data.HIKIWATASHI_DATE_FROM*/
			/*END*/ 
			/*IF data.HIKIWATASHI_DATE_TO != null && data.HIKIWATASHI_DATE_TO != ''*/
			AND	R18.HIKIWATASHI_DATE <= /*data.HIKIWATASHI_DATE_TO*/
			/*END*/
			/*IF data.MANIFEST_ID_FROM != null && data.MANIFEST_ID_FROM != ''*/
			AND	R18.MANIFEST_ID >= /*data.MANIFEST_ID_FROM*/
			/*END*/
			/*IF data.MANIFEST_ID_TO != null && data.MANIFEST_ID_TO != ''*/
			AND	R18.MANIFEST_ID <= /*data.MANIFEST_ID_TO*/
			/*END*/
			/*IF data.HAIKI_SHURUI_CD != null && data.HAIKI_SHURUI_CD != ''*/
			AND	R18.HAIKI_DAI_CODE = /*data.HAIKI_DAI_CODE*/
			AND	R18.HAIKI_CHU_CODE = /*data.HAIKI_CHU_CODE*/
			AND	R18.HAIKI_SHO_CODE = /*data.HAIKI_SHO_CODE*/
			/*END*/
			/*IF data.HAIKI_NAME_CD != null && data.HAIKI_NAME_CD != ''*/
			AND	R18E.HAIKI_NAME_CD = /*data.HAIKI_NAME_CD*/
			/*END*/
			/*IF data.HST_GYOUSHA_CD != null && data.HST_GYOUSHA_CD != ''*/
			AND	R18.HST_SHA_EDI_MEMBER_ID = /*data.HST_GYOUSHA_CD*/
			/*END*/
			/*IF data.HST_GENBA_CD != null && data.HST_GENBA_CD != ''*/
			AND	EXISTS (SELECT * FROM DT_R18 DTR18,M_DENSHI_JIGYOUJOU
						WHERE  DTR18.KANRI_ID = R18.KANRI_ID
						   AND DTR18.SEQ = R18.SEQ
						   AND M_DENSHI_JIGYOUJOU.EDI_MEMBER_ID = /*data.HST_GYOUSHA_CD*/
						   AND M_DENSHI_JIGYOUJOU.JIGYOUJOU_CD = /*data.HST_GENBA_CD*/
						   AND DTR18.HST_JOU_NAME = M_DENSHI_JIGYOUJOU.JIGYOUJOU_NAME
						   AND (DTR18.HST_JOU_ADDRESS1 + DTR18.HST_JOU_ADDRESS2 + DTR18.HST_JOU_ADDRESS3 + DTR18.HST_JOU_ADDRESS4)
						   = (M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS1 + M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS2 + M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS3 + M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS4))
			/*END*/
			/*IF data.UPN_GYOUSHA_CD != null && data.UPN_GYOUSHA_CD != ''*/
			AND	SHUSHU.UPN_SHA_EDI_MEMBER_ID = /*data.UPN_GYOUSHA_CD*/
			/*END*/
			/*IF data.UPN_GYOUSHA_CD != null && data.UPN_GYOUSHA_CD != ''*/
			AND	SHUSHU.UPN_SHA_EDI_MEMBER_ID = /*data.UPN_GYOUSHA_CD*/
			/*END*/
			/*IF data.SBN_GYOUSHA_CD != null && data.SBN_GYOUSHA_CD != ''*/
			AND	SHUSHU.UPNSAKI_EDI_MEMBER_ID = /*data.SBN_GYOUSHA_CD*/
			/*END*/
    ) MANI_MAIN -- R18 マニフェスト情報・目次情報
ON MANI_REL_OWN.FIRST_SYSTEM_ID = MANI_MAIN.SYSTEM_ID

INNER JOIN (SELECT FIRST_SYSTEM_ID, NEXT_HAIKI_KBN_CD, NEXT_SYSTEM_ID FROM T_MANIFEST_RELATION WHERE FIRST_HAIKI_KBN_CD = 4 AND DELETE_FLG = 0) MANI_FIRST --マニフェスト紐付（２次）
ON MANI_FIRST.FIRST_SYSTEM_ID = MANI_MAIN.SYSTEM_ID

LEFT JOIN (SELECT SYSTEM_ID FROM T_LAST_SBN_SUSPEND WHERE SYSTEM_ID IS NULL AND DELETE_FLG = 0) SBN_SUS --最終処分保留
ON MANI_FIRST.NEXT_SYSTEM_ID = SBN_SUS.SYSTEM_ID