SELECT 
  ISNULL(HAISHA.SHARYOU_CD, '') SHARYOU_CD
, M_SHARYOU.SHARYOU_NAME_RYAKU
, ISNULL(HAISHA.SHASHU_CD, '') SHASYU_CD
, M_SHASHU.SHASHU_NAME_RYAKU
, ISNULL(HAISHA.UNTENSHA_CD , '') SHAIN_CD
, M_SHAIN.SHAIN_NAME_RYAKU
, ISNULL(HAISHA.GYOUSHA_CD, '') GYOUSHA_CD
, M_GYOUSHA.GYOUSHA_NAME_RYAKU
, ISNULL(CONVERT(int, M_SHARYOU.SAIDAI_WAKU_SUU), 30) SAIDAI_WAKU_SUU
, CAST(CASE WHEN M_WORK_CLOSED_SHARYOU.CLOSED_DATE IS NULL THEN 0 ELSE 1 END AS bit) WORK_CLOSED_SHARYOU
, CAST(CASE WHEN M_WORK_CLOSED_UNTENSHA.CLOSED_DATE IS NULL THEN 0 ELSE 1 END AS bit) WORK_CLOSED_UNTENSHA
, HAISHA.KARADENPYOU_FLG_01
, HAISHA.KARADENPYOU_FLG_02
, HAISHA.KARADENPYOU_FLG_03
, HAISHA.KARADENPYOU_FLG_04
, HAISHA.KARADENPYOU_FLG_05
, HAISHA.KARADENPYOU_FLG_06
, HAISHA.KARADENPYOU_FLG_07
, HAISHA.KARADENPYOU_FLG_08
, HAISHA.KARADENPYOU_FLG_09
, HAISHA.KARADENPYOU_FLG_10
, HAISHA.KARADENPYOU_FLG_11
, HAISHA.KARADENPYOU_FLG_12
, HAISHA.KARADENPYOU_FLG_13
, HAISHA.KARADENPYOU_FLG_14
, HAISHA.KARADENPYOU_FLG_15
, HAISHA.KARADENPYOU_FLG_16
, HAISHA.KARADENPYOU_FLG_17
, HAISHA.KARADENPYOU_FLG_18
, HAISHA.KARADENPYOU_FLG_19
, HAISHA.KARADENPYOU_FLG_20
, HAISHA.KARADENPYOU_FLG_21
, HAISHA.KARADENPYOU_FLG_22
, HAISHA.KARADENPYOU_FLG_23
, HAISHA.KARADENPYOU_FLG_24
, HAISHA.KARADENPYOU_FLG_25
, HAISHA.KARADENPYOU_FLG_26
, HAISHA.KARADENPYOU_FLG_27
, HAISHA.KARADENPYOU_FLG_28
, HAISHA.KARADENPYOU_FLG_29
, HAISHA.KARADENPYOU_FLG_30
FROM T_HAISHA_WARIATE_DAY HAISHA 
LEFT JOIN  M_SHARYOU 
ON HAISHA.SHARYOU_CD = M_SHARYOU.SHARYOU_CD
AND HAISHA.GYOUSHA_CD = M_SHARYOU.GYOUSHA_CD
LEFT JOIN M_SHASHU
ON HAISHA.SHASHU_CD = M_SHASHU.SHASHU_CD
LEFT JOIN M_SHAIN  
ON M_SHAIN.SHAIN_CD = HAISHA.UNTENSHA_CD 
LEFT JOIN M_GYOUSHA
ON M_GYOUSHA.GYOUSHA_CD = HAISHA.GYOUSHA_CD
LEFT JOIN (SELECT * FROM M_WORK_CLOSED_SHARYOU WHERE DELETE_FLG = 0
AND (CLOSED_DATE IS NULL OR CLOSED_DATE = /*data.SagyouDate*/)) M_WORK_CLOSED_SHARYOU
ON HAISHA.SHARYOU_CD = M_WORK_CLOSED_SHARYOU.SHARYOU_CD
AND HAISHA.GYOUSHA_CD = M_WORK_CLOSED_SHARYOU.GYOUSHA_CD
LEFT JOIN (SELECT * FROM M_WORK_CLOSED_UNTENSHA WHERE DELETE_FLG = 0
AND (CLOSED_DATE IS NULL OR CLOSED_DATE = /*data.SagyouDate*/)) M_WORK_CLOSED_UNTENSHA
ON HAISHA.UNTENSHA_CD = M_WORK_CLOSED_UNTENSHA.SHAIN_CD
WHERE HAISHA.DELETE_FLG=0
AND HAISHA.SAGYOU_DATE = /*data.SagyouDate*/
ORDER BY HAISHA.ROW_NUM ASC








