SELECT M_CONTENA_SHURUI.CONTENA_SHURUI_CD, M_CONTENA_SHURUI.CONTENA_SHURUI_NAME, M_CONTENA.CONTENA_CD, M_CONTENA.CONTENA_NAME_RYAKU 
FROM dbo.M_CONTENA AS M_CONTENA 
LEFT JOIN dbo.M_CONTENA_SHURUI AS M_CONTENA_SHURUI ON M_CONTENA.CONTENA_SHURUI_CD = M_CONTENA_SHURUI.CONTENA_SHURUI_CD 
AND M_CONTENA_SHURUI.DELETE_FLG = 0
WHERE 
M_CONTENA.DELETE_FLG = 0
/*IF data.CONTENA_SHURUI_CD != null*/AND M_CONTENA.CONTENA_SHURUI_CD = /*data.CONTENA_SHURUI_CD*//*END*/
/*IF data.CONTENA_CD != null*/AND M_CONTENA.CONTENA_CD = /*data.CONTENA_CD*//*END*/
/*IF data.CONTENA_NAME != null*/AND M_CONTENA.CONTENA_NAME = /*data.CONTENA_NAME*//*END*/
/*IF data.CONTENA_NAME_RYAKU != null*/AND M_CONTENA.CONTENA_NAME_RYAKU = /*data.CONTENA_NAME_RYAKU*//*END*/
/*IF data.GYOUSHA_CD != null*/AND M_CONTENA.GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/
/*IF data.GENBA_CD != null*/AND M_CONTENA.GENBA_CD = /*data.GENBA_CD*//*END*/
/*IF !data.KYOTEN_CD.IsNull*/AND M_CONTENA.KYOTEN_CD = /*data.KYOTEN_CD.Value*//*END*/
/*IF data.SHARYOU_GYOUSHA_CD != null*/AND M_CONTENA.SHARYOU_GYOUSHA_CD = /*data.SHARYOU_GYOUSHA_CD*//*END*/
/*IF data.SHARYOU_CD != null*/AND M_CONTENA.SHARYOU_CD = /*data.SHARYOU_CD*//*END*/
/*IF !data.SECCHI_DATE.IsNull*/AND M_CONTENA.SECCHI_DATE = /*data.SECCHI_DATE.Value*//*END*/
/*IF !data.HIKIAGE_DATE.IsNull*/AND M_CONTENA.HIKIAGE_DATE = /*data.HIKIAGE_DATE.Value*//*END*/
/*IF !data.JOUKYOU_KBN.IsNull*/AND M_CONTENA.JOUKYOU_KBN = /*data.JOUKYOU_KBN.Value*//*END*/
/*IF !data.KOUNYUU_DATE.IsNull*/AND M_CONTENA.KOUNYUU_DATE = /*data.KOUNYUU_DATE.Value*//*END*/
/*IF !data.LAST_SHUUFUKU_DATE.IsNull*/AND M_CONTENA.LAST_SHUUFUKU_DATE = /*data.LAST_SHUUFUKU_DATE.Value*//*END*/
/*IF data.CONTENA_BIKOU != null*/AND M_CONTENA.CONTENA_BIKOU = /*data.CONTENA_BIKOU*//*END*/
/*IF data.CREATE_USER != null*/AND M_CONTENA.CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND M_CONTENA.CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND M_CONTENA.CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND M_CONTENA.UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND M_CONTENA.UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND M_CONTENA.UPDATE_PC = /*data.UPDATE_PC*//*END*/
