SELECT 
    BNK.BANK_CD,
    ISNULL(BNK.BANK_NAME,N'') AS BANK_NAME,
    ISNULL(BNK.BANK_NAME_RYAKU,N'') AS BANK_NAME_RYAKU,
    BNK.BANK_FURIGANA,
	BNK.RENKEI_CD,
    BNK.BANK_BIKOU,
	BNK.CREATE_USER,
	BNK.CREATE_DATE,
	BNK.UPDATE_USER,
	BNK.UPDATE_DATE,
	CAST(0 AS bit) AS DELETE_FLG
FROM 
    dbo.M_BANK BNK
/*BEGIN*/WHERE
	/*IF data.BANK_CD != null*/BNK.BANK_CD LIKE '%' + /*data.BANK_CD*/ + '%'/*END*/
	/*IF data.BANK_NAME != null*/AND BNK.BANK_NAME LIKE '%' +  /*data.BANK_NAME*/ + '%'/*END*/
    /*IF data.RENKEI_CD != null*/BNK.BANK_CD LIKE '%' + /*data.RENKEI_CD*/ + '%'/*END*/
/*END*/
ORDER BY 
	BNK.BANK_CD
