SELECT  T_UCME.SYSTEM_ID
       ,T_UCME.SEQ
       ,T_UCME.KYOTEN_CD
	   ,M_KYOTEN.KYOTEN_NAME_RYAKU
       ,T_UCME.UKETSUKE_NUMBER
       ,T_UCME.UKETSUKE_DATE
       ,T_UCME.TORIHIKISAKI_CD
       ,T_UCME.TORIHIKISAKI_NAME
       ,T_UCME.GYOUSHA_CD
       ,T_UCME.GYOUSHA_NAME
       ,T_UCME.GENBA_CD
       ,T_UCME.GENBA_NAME
       ,T_UCME.EIGYOU_TANTOUSHA_CD
       ,T_UCME.EIGYOU_TANTOUSHA_NAME
       ,T_UCME.TAIOU_END__DATE
       ,T_UCME.TITLE_NAME
       ,T_UCME.SENPOU_TOIAWASE_USER
       ,T_UCME.NAIYOU_1
       ,T_UCME.NAIYOU_2
       ,T_UCME.NAIYOU_3
       ,T_UCME.NAIYOU_4
       ,T_UCME.NAIYOU_5
       ,T_UCME.NAIYOU_6
       ,T_UCME.NAIYOU_7
       ,T_UCME.NAIYOU_8
       ,T_UCME.CREATE_USER
       ,T_UCME.CREATE_DATE
       ,T_UCME.CREATE_PC
       ,T_UCME.UPDATE_USER
       ,T_UCME.UPDATE_DATE
       ,T_UCME.UPDATE_PC
       ,T_UCME.DELETE_FLG
	   ,T_UCME.TIME_STAMP
FROM	T_UKETSUKE_CM_ENTRY AS T_UCME
LEFT JOIN M_KYOTEN
ON T_UCME.KYOTEN_CD = M_KYOTEN.KYOTEN_CD
WHERE	T_UCME.UKETSUKE_NUMBER = /*data.UketsukeNumber*/
AND		T_UCME.DELETE_FLG = 0