SELECT M_KONGOU_SHURUI.HAIKI_KBN_CD, M_HAIKI_KBN.HAIKI_KBN_NAME_RYAKU, M_KONGOU_SHURUI.KONGOU_SHURUI_CD, M_KONGOU_SHURUI.KONGOU_SHURUI_NAME_RYAKU 
FROM dbo.M_KONGOU_SHURUI AS M_KONGOU_SHURUI 
LEFT JOIN dbo.M_HAIKI_KBN AS M_HAIKI_KBN ON M_KONGOU_SHURUI.HAIKI_KBN_CD = M_HAIKI_KBN.HAIKI_KBN_CD 
AND M_HAIKI_KBN.DELETE_FLG = 0
WHERE M_KONGOU_SHURUI.DELETE_FLG = 0
/*IF !data.HAIKI_KBN_CD.IsNull*/AND M_KONGOU_SHURUI.HAIKI_KBN_CD = /*data.HAIKI_KBN_CD.Value*//*END*/
/*IF data.KONGOU_SHURUI_CD != null*/AND M_KONGOU_SHURUI.KONGOU_SHURUI_CD = /*data.KONGOU_SHURUI_CD*//*END*/
/*IF data.KONGOU_SHURUI_NAME != null*/AND M_KONGOU_SHURUI.KONGOU_SHURUI_NAME = /*data.KONGOU_SHURUI_NAME*//*END*/
/*IF data.KONGOU_SHURUI_NAME_RYAKU != null*/AND M_KONGOU_SHURUI.KONGOU_SHURUI_NAME_RYAKU = /*data.KONGOU_SHURUI_NAME_RYAKU*//*END*/
/*IF data.KONGOU_SHURUI_FURIGANA != null*/AND M_KONGOU_SHURUI.KONGOU_SHURUI_FURIGANA = /*data.KONGOU_SHURUI_FURIGANA*//*END*/
/*IF data.KONGOU_SHURUI_BIKOU != null*/AND M_KONGOU_SHURUI.KONGOU_SHURUI_BIKOU = /*data.KONGOU_SHURUI_BIKOU*//*END*/
/*IF data.CREATE_USER != null*/AND M_KONGOU_SHURUI.CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND M_KONGOU_SHURUI.CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND M_KONGOU_SHURUI.CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND M_KONGOU_SHURUI.UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND M_KONGOU_SHURUI.UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND M_KONGOU_SHURUI.UPDATE_PC = /*data.UPDATE_PC*//*END*/
