SELECT TBL.KANSANSHIKI,TBL.KANSANCHI
FROM (SELECT KANSANSHIKI,KANSANCHI 
		FROM M_MANIFEST_KANSAN MMK 
		INNER JOIN M_DENSHI_HAIKI_SHURUI MDHS 
				ON MMK.HOUKOKUSHO_BUNRUI_CD = MDHS.HOUKOKUSHO_BUNRUI_CD 
		INNER JOIN M_DENSHI_HAIKI_NAME MDHN 
				ON MMK.HAIKI_NAME_CD = MDHN.HAIKI_NAME_CD 
		WHERE  MDHS.HAIKI_SHURUI_CD = /*data.HAIKI_SHURUI_CD*/
		AND MDHN.EDI_MEMBER_ID = /*data.EDI_MEMBER_ID*/
		AND MDHN.HAIKI_NAME = /*data.HAIKI_NAME*/
		AND MMK.UNIT_CD = /*data.UNIT_CD*/
		AND MMK.NISUGATA_CD = /*data.NISUGATA_CD*/
		) TBL 