SELECT M_ZAIKO_HINMEI.ZAIKO_HINMEI_CD, M_ZAIKO_HINMEI.ZAIKO_HINMEI_NAME_RYAKU, M_ZAIKO_HINMEI.ZAIKO_TANKA FROM dbo.M_ZAIKO_HINMEI AS M_ZAIKO_HINMEI
WHERE 
DELETE_FLG = 0
/*IF data.ZAIKO_HINMEI_CD != null*/AND ZAIKO_HINMEI_CD = /*data.ZAIKO_HINMEI_CD*//*END*/
/*IF data.ZAIKO_HINMEI_NAME != null*/AND ZAIKO_HINMEI_NAME = /*data.ZAIKO_HINMEI_NAME*//*END*/
/*IF data.ZAIKO_HINMEI_NAME_RYAKU != null*/AND ZAIKO_HINMEI_NAME_RYAKU = /*data.ZAIKO_HINMEI_NAME_RYAKU*//*END*/
/*IF data.ZAIKO_HINMEI_FURIGANA != null*/AND ZAIKO_HINMEI_FURIGANA = /*data.ZAIKO_HINMEI_FURIGANA*//*END*/
/*IF !data.ZAIKO_TANKA.IsNull*/AND ZAIKO_TANKA = /*data.ZAIKO_TANKA.Value*//*END*/
/*IF data.BIKOU != null*/AND BIKOU = /*data.BIKOU.Value*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
