SELECT
    KEI.*
    ,ISNULL(TOR.TORIHIKISAKI_NAME_RYAKU,N'') AS TORIHIKISAKI_NAME_RYAKU
    ,ISNULL(GYO.GYOUSHA_NAME_RYAKU,N'') AS GYOUSHA_NAME_RYAKU
    ,ISNULL(GEN.GENBA_NAME_RYAKU,N'') AS GENBA_NAME_RYAKU
    ,ISNULL(HIN.HINMEI_NAME_RYAKU,N'') AS HINMEI_NAME_RYAKU
    ,ISNULL(UNI.UNIT_NAME_RYAKU,N'') AS UNIT_NAME_RYAKU
    ,ISNULL(SHURUI.SHURUI_CD,'') AS SHURUI_CD
    ,ISNULL(SHURUI.SHURUI_NAME_RYAKU,N'') AS SHURUI_NAME_RYAKU
FROM
    dbo.M_HINMEI HIN
    LEFT JOIN dbo.M_SHURUI SHURUI ON SHURUI.SHURUI_CD = HIN.SHURUI_CD
    LEFT JOIN dbo.M_KEIRYOU_CHOUSEI KEI ON KEI.HINMEI_CD = HIN.HINMEI_CD
    LEFT JOIN dbo.M_TORIHIKISAKI TOR ON TOR.TORIHIKISAKI_CD = KEI.TORIHIKISAKI_CD
    LEFT JOIN dbo.M_GYOUSHA GYO ON GYO.GYOUSHA_CD = KEI.GYOUSHA_CD
    LEFT JOIN dbo.M_GENBA GEN ON GEN.GENBA_CD = KEI.GENBA_CD
    LEFT JOIN dbo.M_UNIT UNI ON UNI.UNIT_CD = KEI.UNIT_CD
/*BEGIN*/WHERE
 /*IF data.HINMEI_CD != null*/HIN.HINMEI_CD LIKE '%' +  /*data.HINMEI_CD*/ + '%'/*END*/
 /*IF data.HINMEI_NAME_RYAKU != null*/AND HIN.HINMEI_NAME_RYAKU LIKE '%' +  /*data.HINMEI_NAME_RYAKU*/ + '%'/*END*/
 /*IF data.SHURUI_CD != null*/AND HIN.SHURUI_CD LIKE '%' +  /*data.SHURUI_CD*/ + '%'/*END*/
 /*IF !data.TEKIYOU_BEGIN.IsNull*/ AND HIN.TEKIYOU_BEGIN LIKE '%' +  /*data.TEKIYOU_BEGIN.Value*/ + '%'/*END*/
 /*IF !data.TEKIYOU_END.IsNull*/AND HIN.TEKIYOU_END LIKE '%' +  /*data.TEKIYOU_END.Value*/ + '%'/*END*/
 /*IF data.CREATE_USER != null && data.CREATE_USER != '' */AND HIN.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, HIN.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null && data.UPDATE_USER != '' */AND HIN.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, HIN.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
 /*IF !deletechuFlg*/AND HIN.DELETE_FLG = 0/*END*/
 /*IF tekiyounaiFlg || deletechuFlg || tekiyougaiFlg*/AND (1 = 0/*END*/
 /*IF tekiyounaiFlg*/OR (((HIN.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= HIN.TEKIYOU_END) or (HIN.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and HIN.TEKIYOU_END IS NULL) or (HIN.TEKIYOU_BEGIN IS NULL and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= HIN.TEKIYOU_END) or (HIN.TEKIYOU_BEGIN IS NULL and HIN.TEKIYOU_END IS NULL)) and HIN.DELETE_FLG = 0)/*END*/
 /*IF deletechuFlg*/OR HIN.DELETE_FLG = /*deletechuFlg*/0/*END*/
 /*IF tekiyougaiFlg*/OR ((HIN.TEKIYOU_BEGIN > CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) or CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) > HIN.TEKIYOU_END) and HIN.DELETE_FLG = 0)/*END*/
 /*IF tekiyounaiFlg || deletechuFlg || tekiyougaiFlg*/ )/*END*/
  AND HIN.SHURUI_CD = SHURUI.SHURUI_CD
/*END*/
ORDER BY HIN.HINMEI_CD
