SELECT
    KEI.*
    ,ISNULL(TOR.TORIHIKISAKI_NAME_RYAKU,N'') AS TORIHIKISAKI_NAME_RYAKU
    ,ISNULL(GYO.GYOUSHA_NAME_RYAKU,N'') AS GYOUSHA_NAME_RYAKU
    ,ISNULL(GEN.GENBA_NAME_RYAKU,N'') AS GENBA_NAME_RYAKU
    ,ISNULL(HIN.HINMEI_NAME_RYAKU,N'') AS HINMEI_NAME_RYAKU
    ,ISNULL(UNI.UNIT_NAME_RYAKU,N'') AS UNIT_NAME_RYAKU
    ,ISNULL(SHURUI.SHURUI_CD,'') AS SHURUI_CD
    ,ISNULL(SHURUI.SHURUI_NAME_RYAKU,N'') AS SHURUI_NAME_RYAKU
FROM
    dbo.M_SHURUI SHURUI
    LEFT JOIN dbo.M_HINMEI HIN ON HIN.SHURUI_CD = SHURUI.SHURUI_CD
    LEFT JOIN dbo.M_KEIRYOU_CHOUSEI KEI ON KEI.HINMEI_CD = HIN.HINMEI_CD
    LEFT JOIN dbo.M_TORIHIKISAKI TOR ON KEI.TORIHIKISAKI_CD = TOR.TORIHIKISAKI_CD
    LEFT JOIN dbo.M_GYOUSHA GYO ON KEI.GYOUSHA_CD = GYO.GYOUSHA_CD
    LEFT JOIN dbo.M_GENBA GEN ON KEI.GYOUSHA_CD = GEN.GYOUSHA_CD AND KEI.GENBA_CD = GEN.GENBA_CD
    LEFT JOIN dbo.M_UNIT UNI ON KEI.UNIT_CD = UNI.UNIT_CD
/*BEGIN*/WHERE
 /*IF data.SHURUI_NAME_RYAKU != null*/SHURUI.SHURUI_NAME_RYAKU LIKE '%' +  /*data.SHURUI_NAME_RYAKU*/ + '%'/*END*/
 /*IF data.SHURUI_CD != null*/AND SHURUI.SHURUI_CD LIKE '%' +  /*data.SHURUI_CD*/ + '%'/*END*/
 /*IF !data.TEKIYOU_BEGIN.IsNull*/ AND SHURUI.TEKIYOU_BEGIN LIKE '%' +  /*data.TEKIYOU_BEGIN.Value*/ + '%'/*END*/
 /*IF !data.TEKIYOU_END.IsNull*/AND SHURUI.TEKIYOU_END LIKE '%' +  /*data.TEKIYOU_END.Value*/ + '%'/*END*/
 /*IF data.CREATE_USER != null && data.CREATE_USER != '' */AND SHURUI.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, SHURUI.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null && data.UPDATE_USER != '' */AND SHURUI.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, SHURUI.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
 /*IF !deletechuFlg*/AND SHURUI.DELETE_FLG = 0/*END*/
 /*IF tekiyounaiFlg || deletechuFlg || tekiyougaiFlg*/AND (1 = 0/*END*/
 /*IF tekiyounaiFlg*/OR (((SHURUI.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= SHURUI.TEKIYOU_END) or (SHURUI.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and SHURUI.TEKIYOU_END IS NULL) or (SHURUI.TEKIYOU_BEGIN IS NULL and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= SHURUI.TEKIYOU_END) or (SHURUI.TEKIYOU_BEGIN IS NULL and SHURUI.TEKIYOU_END IS NULL)) and SHURUI.DELETE_FLG = 0)/*END*/
 /*IF deletechuFlg*/OR SHURUI.DELETE_FLG = /*deletechuFlg*/0/*END*/
 /*IF tekiyougaiFlg*/OR ((SHURUI.TEKIYOU_BEGIN > CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) or CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) > SHURUI.TEKIYOU_END) and SHURUI.DELETE_FLG = 0)/*END*/
 /*IF tekiyounaiFlg || deletechuFlg || tekiyougaiFlg*/ )/*END*/
/*END*/
ORDER BY SHURUI.SHURUI_CD
