SELECT 
    KEI.*
    ,ISNULL(TOR.TORIHIKISAKI_NAME_RYAKU,N'') AS TORIHIKISAKI_NAME_RYAKU
    ,ISNULL(GYO.GYOUSHA_NAME_RYAKU,N'') AS GYOUSHA_NAME_RYAKU
    ,ISNULL(GEN.GENBA_NAME_RYAKU,N'') AS GENBA_NAME_RYAKU
    ,ISNULL(HIN.HINMEI_NAME_RYAKU,N'') AS HINMEI_NAME_RYAKU
    ,ISNULL(UNI.UNIT_NAME_RYAKU,N'') AS UNIT_NAME_RYAKU
    ,ISNULL(SHU.SHURUI_NAME_RYAKU,N'') AS SHURUI_NAME_RYAKU
FROM 
    dbo.M_KEIRYOU_CHOUSEI KEI
	LEFT JOIN dbo.M_TORIHIKISAKI TOR ON KEI.TORIHIKISAKI_CD = TOR.TORIHIKISAKI_CD
	LEFT JOIN dbo.M_GYOUSHA GYO ON KEI.GYOUSHA_CD = GYO.GYOUSHA_CD
	LEFT JOIN dbo.M_GENBA GEN ON KEI.GYOUSHA_CD = GEN.GYOUSHA_CD AND KEI.GENBA_CD = GEN.GENBA_CD
	LEFT JOIN dbo.M_HINMEI HIN ON KEI.HINMEI_CD = HIN.HINMEI_CD
	LEFT JOIN dbo.M_UNIT UNI ON KEI.UNIT_CD = UNI.UNIT_CD
	LEFT JOIN dbo.M_SHURUI SHU ON SHU.SHURUI_CD = HIN.SHURUI_CD
/*BEGIN*/WHERE
 /*IF data.TORIHIKISAKI_CD != null && data.TORIHIKISAKI_CD != '' */ KEI.TORIHIKISAKI_CD LIKE '%' +  /*data.TORIHIKISAKI_CD*/ + '%'/*END*/
 /*IF data.GYOUSHA_CD != null && data.GYOUSHA_CD != '' */AND KEI.GYOUSHA_CD LIKE '%' +  /*data.GYOUSHA_CD*/ + '%'/*END*/
 /*IF data.GENBA_CD != null && data.GENBA_CD != '' */AND KEI.GENBA_CD LIKE '%' +  /*data.GENBA_CD*/ + '%'/*END*/
 /*IF data.HINMEI_CD != null && data.HINMEI_CD != '' */AND KEI.HINMEI_CD LIKE '%' +  /*data.HINMEI_CD*/ + '%'/*END*/
 /*IF !data.UNIT_CD.IsNull */AND KEI.UNIT_CD=/*data.UNIT_CD*/0/*END*/
 /*IF !data.CHOUSEICHI.IsNull*/AND KEI.CHOUSEICHI= /*data.CHOUSEICHI.Value*/0/*END*/ 
 /*IF !data.CHOUSEIWARIAI.IsNull*/AND KEI.CHOUSEIWARIAI= /*data.CHOUSEIWARIAI.Value*/0/*END*/ 
 /*IF data.KEIRYOU_CHOUSEI_BIKOU != null && data.KEIRYOU_CHOUSEI_BIKOU != '' */AND KEI.KEIRYOU_CHOUSEI_BIKOU LIKE '%' +  /*data.KEIRYOU_CHOUSEI_BIKOU*/ + '%'/*END*/
 /*IF !data.TEKIYOU_BEGIN.IsNull*/ AND KEI.TEKIYOU_BEGIN LIKE '%' +  /*data.TEKIYOU_BEGIN.Value*/ + '%'/*END*/
 /*IF !data.TEKIYOU_END.IsNull*/AND KEI.TEKIYOU_END LIKE '%' +  /*data.TEKIYOU_END.Value*/ + '%'/*END*/
 /*IF data.CREATE_USER != null && data.CREATE_USER != '' */AND KEI.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, KEI.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null && data.UPDATE_USER != '' */AND KEI.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, KEI.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*END*/
ORDER BY KEI.TORIHIKISAKI_CD