SELECT
    EIG.SHAIN_CD,
    EIG.EIGYOU_TANTOUSHA_BIKOU,
    EIG.CREATE_DATE,
    EIG.CREATE_USER,
    EIG.CREATE_PC,
    EIG.UPDATE_DATE,
    EIG.UPDATE_USER,
    EIG.UPDATE_PC,
    EIG.DELETE_FLG,
    EIG.TIME_STAMP,
    ISNULL(SHA.SHAIN_NAME, N'') AS SHAIN_NAME,
    ISNULL(SHA.SHAIN_FURIGANA, N'') AS SHAIN_FURIGANA
FROM
    dbo.M_EIGYOU_TANTOUSHA EIG
        LEFT JOIN dbo.M_SHAIN SHA ON EIG.SHAIN_CD = SHA.SHAIN_CD
/*BEGIN*/WHERE
 /*IF !deletechuFlg*/ EIG.DELETE_FLG = 0/*END*/
 /*IF data.SHAIN_CD != null*/ AND EIG.SHAIN_CD LIKE '%' +  /*data.SHAIN_CD*/ + '%'/*END*/
 /*IF data.SHAIN_NAME != null*/ AND SHA.SHAIN_NAME LIKE '%' +  /*data.SHAIN_NAME*/ + '%'/*END*/
 /*IF data.SHAIN_FURIGANA != null*/AND SHA.SHAIN_FURIGANA LIKE '%' +  /*data.SHAIN_FURIGANA*/ + '%'/*END*/
 /*IF data.EIGENSHA_BIKOU != null*/AND EIG.EIGENSHA_BIKOU LIKE '%' +  /*data.EIGENSHA_BIKOU*/ + '%'/*END*/
 /*IF data.CREATE_USER != null*/AND EIG.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, EIG.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null*/AND EIG.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, EIG.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
 /*IF !deletechuFlg*/OR EIG.DELETE_FLG = /*deletechuFlg*/0/*END*/
/*END*/
ORDER BY SHA.SHAIN_CD
