//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shougun.Core.Master.KaishiZaikoJouhouHoshu.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ICHIRAN_HYOUJI_JOUKEN_DELETED {
            get {
                return ((bool)(this["ICHIRAN_HYOUJI_JOUKEN_DELETED"]));
            }
            set {
                this["ICHIRAN_HYOUJI_JOUKEN_DELETED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_CD {
            get {
                return ((string)(this["GENBA_CD"]));
            }
            set {
                this["GENBA_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_NAME_RYAKU {
            get {
                return ((string)(this["GENBA_NAME_RYAKU"]));
            }
            set {
                this["GENBA_NAME_RYAKU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DENSHU_KBN_CD {
            get {
                return ((string)(this["DENSHU_KBN_CD"]));
            }
            set {
                this["DENSHU_KBN_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConditionValue_Text {
            get {
                return ((string)(this["ConditionValue_Text"]));
            }
            set {
                this["ConditionValue_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string ConditionValue_DBFieldsName {
            get {
                return ((string)(this["ConditionValue_DBFieldsName"]));
            }
            set {
                this["ConditionValue_DBFieldsName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConditionItem_Text {
            get {
                return ((string)(this["ConditionItem_Text"]));
            }
            set {
                this["ConditionItem_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConditionValue_ItemDefinedTypes {
            get {
                return ((string)(this["ConditionValue_ItemDefinedTypes"]));
            }
            set {
                this["ConditionValue_ItemDefinedTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GYOUSHA_CD {
            get {
                return ((string)(this["GYOUSHA_CD"]));
            }
            set {
                this["GYOUSHA_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GYOUSHA_NAME_RYAKU {
            get {
                return ((string)(this["GYOUSHA_NAME_RYAKU"]));
            }
            set {
                this["GYOUSHA_NAME_RYAKU"] = value;
            }
        }
    }
}
