SELECT DISTINCT N'業者マスタ' AS NAME FROM M_GYOUSHA WHERE (SEIKYUU_KYOTEN_CD IN /*KYOTEN_CD*/('') OR SHIHARAI_KYOTEN_CD IN /*KYOTEN_CD*/('')) AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'現場マスタ' AS NAME FROM M_GENBA WHERE (SEIKYUU_KYOTEN_CD IN /*KYOTEN_CD*/('') OR SHIHARAI_KYOTEN_CD IN /*KYOTEN_CD*/('')) AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'引合取引先マスタ' AS NAME
	FROM M_HIKIAI_TORIHIKISAKI AS HT
		LEFT JOIN M_HIKIAI_TORIHIKISAKI_SHIHARAI AS HT_SHI
		ON HT.TORIHIKISAKI_CD = HT_SHI.TORIHIKISAKI_CD
		LEFT JOIN M_HIKIAI_TORIHIKISAKI_SEIKYUU AS HT_SEI
		ON HT.TORIHIKISAKI_CD = HT_SEI.TORIHIKISAKI_CD
	WHERE 
		HT.DELETE_FLG = 'False'
		AND (HT_SEI.SEIKYUU_KYOTEN_CD IN /*KYOTEN_CD*/('') 
			OR HT_SHI.SHIHARAI_KYOTEN_CD IN /*KYOTEN_CD*/(''))
UNION
SELECT DISTINCT N'引合業者マスタ' AS NAME FROM M_HIKIAI_GYOUSHA WHERE (SEIKYUU_KYOTEN_CD IN /*KYOTEN_CD*/('') OR SHIHARAI_KYOTEN_CD IN /*KYOTEN_CD*/('')) AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'引合現場マスタ' AS NAME FROM M_HIKIAI_GENBA WHERE (SEIKYUU_KYOTEN_CD IN /*KYOTEN_CD*/('') OR SHIHARAI_KYOTEN_CD IN /*KYOTEN_CD*/('')) AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'コース名マスタ' AS NAME FROM M_COURSE_NAME WHERE KYOTEN_CD IN /*KYOTEN_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'システム設定マスタ' AS NAME FROM M_SYS_INFO 
WHERE 
	(SEIKYUU_KYOTEN_CD IN /*KYOTEN_CD*/('') 
	OR SHIHARAI_KYOTEN_CD IN /*KYOTEN_CD*/('')
	OR GYOUSHA_SEIKYUU_KYOTEN_CD  IN /*KYOTEN_CD*/('')
	OR GYOUSHA_SHIHARAI_KYOTEN_CD  IN /*KYOTEN_CD*/('')
	OR GENBA_SEIKYUU_KYOTEN_CD  IN /*KYOTEN_CD*/('')
	OR GENBA_SHIHARAI_KYOTEN_CD  IN /*KYOTEN_CD*/('')
	OR MITSUMORI_INJI_KYOTEN_CD1  IN /*KYOTEN_CD*/('')
	OR MITSUMORI_INJI_KYOTEN_CD2  IN /*KYOTEN_CD*/(''))