SELECT * FROM dbo.M_KYOTEN
WHERE 
/*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
 DELETE_FLG = 0
-- ELSE
 1 = 1
/*END*/
/*IF !data.KYOTEN_CD.IsNull*/AND KYOTEN_CD = /*data.KYOTEN_CD.Value*//*END*/
/*IF data.KYOTEN_NAME != null*/AND KYOTEN_NAME = /*data.KYOTEN_NAME*//*END*/
/*IF data.KYOTEN_NAME_RYAKU != null*/AND KYOTEN_NAME_RYAKU = /*data.KYOTEN_NAME_RYAKU*//*END*/
/*IF data.KYOTEN_FURIGANA != null*/AND KYOTEN_FURIGANA = /*data.KYOTEN_FURIGANA*//*END*/
/*IF data.KYOTEN_POST != null*/AND KYOTEN_POST = /*data.KYOTEN_POST*//*END*/
/*IF !data.KYOTEN_TODOUFUKEN_CD.IsNull*/AND KYOTEN_TODOUFUKEN_CD = /*data.KYOTEN_TODOUFUKEN_CD.Value*//*END*/
/*IF data.KYOTEN_ADDRESS1 != null*/AND KYOTEN_ADDRESS1 = /*data.KYOTEN_ADDRESS1*//*END*/
/*IF data.KYOTEN_ADDRESS2 != null*/AND KYOTEN_ADDRESS2 = /*data.KYOTEN_ADDRESS2*//*END*/
/*IF data.KYOTEN_TEL != null*/AND KYOTEN_TEL = /*data.KYOTEN_TEL*//*END*/
/*IF data.KYOTEN_FAX != null*/AND KYOTEN_FAX = /*data.KYOTEN_FAX*//*END*/
/*IF data.KYOTEN_DAIHYOU != null*/AND KYOTEN_DAIHYOU = /*data.KYOTEN_DAIHYOU*//*END*/
/*IF data.KYOTEN_BIKOU != null*/AND KYOTEN_BIKOU = /*data.KYOTEN_BIKOU*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
