UPDATE M_CHIIKIBETSU_KYOKA_MEIGARA
SET TSUMIKAE = /*data.TSUMIKAE*/
/*BEGIN*/WHERE
 /*IF !data.KYOKA_KBN.IsNull*/KYOKA_KBN = /*data.KYOKA_KBN.Value*//*END*/
 /*IF data.GYOUSHA_CD != null*/AND GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/
 /*IF data.GENBA_CD != null*/AND GENBA_CD = /*data.GENBA_CD*//*END*/
 /*IF data.CHIIKI_CD != null*/AND CHIIKI_CD = /*data.CHIIKI_CD*//*END*/
/*IF !data.TOKUBETSU_KANRI_KBN.IsNull*/ AND TOKUBETSU_KANRI_KBN = /*data.TOKUBETSU_KANRI_KBN*//*END*/
/*IF !data.HOUKOKUSHO_BUNRUI_CD.IsNull*/ AND HOUKOKUSHO_BUNRUI_CD = /*data.HOUKOKUSHO_BUNRUI_CD*//*END*/
/*END*/
