SELECT 
    GENBA.GENBA_CD as GENBA_CD
    ,GENBA.GENBA_NAME_RYAKU as GENBA_NAME_RYAKU
	,GENBA.GYOUSHA_CD
	,GYOUSHA.GYOUSHA_NAME_RYAKU
	,GENBA.TORIHIKISAKI_CD
	,TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU
FROM 
    dbo.M_GENBA GENBA
	LEFT JOIN M_GYOUSHA GYOUSHA ON GYOUSHA.GYOUSHA_CD = GENBA.GYOUSHA_CD
	LEFT JOIN M_TORIHIKISAKI TORIHIKISAKI ON TORIHIKISAKI.TORIHIKISAKI_CD = GENBA.TORIHIKISAKI_CD
WHERE GENBA.GYOUSHA_CD = /*data.GYOUSHA_CD*/''
  AND GENBA.GENBA_CD = /*data.GENBA_CD*/''
  AND GENBA.DELETE_FLG = 0