--îÑè„
SELECT
    KON.SYS_ID
    ,KON.DENPYOU_KBN_CD
    --,'' AS TORIHIKISAKI_CD
    --,'' AS GYOUSHA_CD
    --,'' AS GENBA_CD
    ,ISNULL(KON.HINMEI_CD,'') AS HINMEI_CD
    ,KON.DENSHU_KBN_CD
    ,KON.UNIT_CD
    ,ISNULL(KON.UNPAN_GYOUSHA_CD,'') AS UNPAN_GYOUSHA_CD
    ,ISNULL(KON.NIOROSHI_GYOUSHA_CD,'') AS NIOROSHI_GYOUSHA_CD
    ,ISNULL(KON.NIOROSHI_GENBA_CD,'') AS NIOROSHI_GENBA_CD
    ,KON.TANKA
    ,KON.BIKOU
    ,KON.TEKIYOU_BEGIN
    ,KON.TEKIYOU_END
    ,KON.CREATE_USER
    ,KON.CREATE_DATE
    ,KON.CREATE_PC
    ,KON.UPDATE_USER
    ,KON.UPDATE_DATE
    ,KON.UPDATE_PC
    ,KON.DELETE_FLG
    ,KON.TIME_STAMP
    ,ISNULL(GEN.GENBA_NAME_RYAKU,N'') AS NIOROSHI_GENBA_RYAKU
    ,ISNULL(GYOU.GYOUSHA_NAME_RYAKU,N'') AS UNPAN_GYOUSHA_RYAKU
    ,ISNULL(DENS.DENSHU_KBN_NAME_RYAKU,N'') AS DENSHU_KBN_RYAKU
    ,ISNULL(HIN.HINMEI_NAME_RYAKU,N'') AS HINMEI_NAME_RYAKU
    ,ISNULL(UNI.UNIT_NAME_RYAKU,N'') AS UNIT_NAME_RYAKU
    ,ISNULL(GYOUSHA.GYOUSHA_NAME_RYAKU,N'') AS NIOROSHI_GYOUSHA_RYAKU
    ,ISNULL(GEN.GENBA_NAME_RYAKU,N'') AS GENBA_NAME_RYAKU
FROM
    dbo.M_KIHON_HINMEI_TANKA KON
    LEFT JOIN dbo.M_GYOUSHA GYOU ON GYOU.GYOUSHA_CD = KON.UNPAN_GYOUSHA_CD
    LEFT JOIN dbo.M_GYOUSHA GYOUSHA ON GYOUSHA.GYOUSHA_CD = KON.NIOROSHI_GYOUSHA_CD
    LEFT JOIN dbo.M_DENSHU_KBN DENS ON DENS.DENSHU_KBN_CD = KON.DENSHU_KBN_CD
    LEFT JOIN dbo.M_HINMEI HIN ON HIN.HINMEI_CD = KON.HINMEI_CD
    LEFT JOIN dbo.M_UNIT UNI ON UNI.UNIT_CD = KON.UNIT_CD
    LEFT JOIN dbo.M_GENBA GEN ON GEN.GYOUSHA_CD = KON.NIOROSHI_GYOUSHA_CD AND GEN.GENBA_CD = KON.NIOROSHI_GENBA_CD
WHERE
--îÑè„Ç™ëŒè€
	(KON.DENPYOU_KBN_CD = 1)
	--/*IF data.TORIHIKISAKI_CD != null*/AND KON.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/''/*END*/
	--/*IF data.GYOUSHA_CD != null*/AND KON.GYOUSHA_CD = /*data.GYOUSHA_CD*/''/*END*/
	--/*IF data.GENBA_CD != null*/AND KON.GENBA_CD = /*data.GENBA_CD*/''/*END*/
	/*IF data.HINMEI_CD != null*/AND KON.HINMEI_CD LIKE '%' +  /*data.HINMEI_CD*/ + '%'/*END*/
	/*IF !data.DENSHU_KBN_CD.IsNull */AND KON.DENSHU_KBN_CD = /*data.DENSHU_KBN_CD*/0 /*END*/
	/*IF !data.UNIT_CD.IsNull */AND KON.UNIT_CD =/*data.UNIT_CD*/0 /*END*/
	/*IF data.UNPAN_GYOUSHA_CD != null*/AND KON.UNPAN_GYOUSHA_CD LIKE '%' +  /*data.UNPAN_GYOUSHA_CD*/ + '%'/*END*/
	/*IF data.NIOROSHI_GYOUSHA_CD != null*/AND KON.NIOROSHI_GYOUSHA_CD LIKE '%' +  /*data.NIOROSHI_GYOUSHA_CD*/ + '%'/*END*/
	/*IF data.NIOROSHI_GENBA_CD != null*/AND KON.NIOROSHI_GENBA_CD LIKE '%' +  /*data.NIOROSHI_GENBA_CD*/ + '%'/*END*/
	/*IF data.UNPAN_GYOUSHA_CD != null*/AND KON.UNPAN_GYOUSHA_CD LIKE '%' +  /*data.UNPAN_GYOUSHA_CD*/ + '%'/*END*/
	/*IF !data.TEKIYOU_BEGIN.IsNull*/ AND KON.TEKIYOU_BEGIN LIKE '%' +  /*data.TEKIYOU_BEGIN.Value*/ + '%'/*END*/
	/*IF !data.TEKIYOU_END.IsNull*/AND KON.TEKIYOU_END LIKE '%' +  /*data.TEKIYOU_END.Value*/ + '%'/*END*/
	/*IF data.CREATE_USER != null*/AND KON.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
	/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar,KON.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
	/*IF data.UPDATE_USER != null*/AND KON.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
	/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar,KON.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
	/*IF !deletechuFlg*/AND KON.DELETE_FLG = 0/*END*/
	/*IF tekiyounaiFlg || deletechuFlg || tekiyougaiFlg*/AND (1 = 0/*END*/
	/*IF tekiyounaiFlg*/OR (((KON.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= KON.TEKIYOU_END) or (KON.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and KON.TEKIYOU_END IS NULL) or (KON.TEKIYOU_BEGIN IS NULL and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= KON.TEKIYOU_END) or (KON.TEKIYOU_BEGIN IS NULL and KON.TEKIYOU_END IS NULL)) and KON.DELETE_FLG = 0)/*END*/
	/*IF deletechuFlg*/OR KON.DELETE_FLG = /*deletechuFlg*/0/*END*/
	/*IF tekiyougaiFlg*/OR ((KON.TEKIYOU_BEGIN > CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) or CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) > KON.TEKIYOU_END) and KON.DELETE_FLG = 0)/*END*/
	/*IF tekiyounaiFlg || deletechuFlg || tekiyougaiFlg*/ )/*END*/
	/*IF syuruishiteiFlg*/AND HIN.SHURUI_CD =  /*syurui*/ /*END*/
ORDER BY KON.DENSHU_KBN_CD, KON.HINMEI_CD, KON.UNIT_CD, KON.UNPAN_GYOUSHA_CD, KON.NIOROSHI_GYOUSHA_CD, KON.NIOROSHI_GENBA_CD, KON.TEKIYOU_BEGIN
