SELECT
    KON.*
    ,ISNULL(GEN.GENBA_NAME_RYAKU,N'') AS NIOROSHI_GENBA_RYAKU
    ,ISNULL(GYOU.GYOUSHA_NAME_RYAKU,N'') AS UNPAN_GYOUSHA_RYAKU
    ,ISNULL(DENS.DENSHU_KBN_NAME_RYAKU,N'') AS DENSHU_KBN_RYAKU
    ,ISNULL(HIN.HINMEI_NAME_RYAKU,N'') AS HINMEI_NAME_RYAKU
    ,ISNULL(UNI.UNIT_NAME_RYAKU,N'') AS UNIT_NAME_RYAKU
    ,ISNULL(GYOUSHA.GYOUSHA_NAME_RYAKU,N'') AS NIOROSHI_GYOUSHA_RYAKU
FROM
    dbo.M_KOBETSU_HINMEI_TANKA KON
    LEFT JOIN dbo.M_GYOUSHA GYOU ON GYOU.GYOUSHA_CD = KON.UNPAN_GYOUSHA_CD
    LEFT JOIN dbo.M_GYOUSHA GYOUSHA ON GYOUSHA.GYOUSHA_CD = KON.NIOROSHI_GYOUSHA_CD
    LEFT JOIN dbo.M_DENSHU_KBN DENS ON DENS.DENSHU_KBN_CD = KON.DENSHU_KBN_CD
    LEFT JOIN dbo.M_HINMEI HIN ON HIN.HINMEI_CD = KON.HINMEI_CD
    LEFT JOIN dbo.M_UNIT UNI ON UNI.UNIT_CD = KON.UNIT_CD
    LEFT JOIN dbo.M_GENBA GEN ON GEN.GYOUSHA_CD = KON.NIOROSHI_GYOUSHA_CD AND GEN.GENBA_CD = KON.NIOROSHI_GENBA_CD
WHERE KON.DENPYOU_KBN_CD =/*data.DENPYOU_KBN_CD*/0
  AND KON.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/''
  AND KON.GYOUSHA_CD = /*data.GYOUSHA_CD*/''
  AND KON.GENBA_CD = /*data.GENBA_CD*/''
  AND KON.DELETE_FLG = 0
ORDER BY KON.DENSHU_KBN_CD, KON.HINMEI_CD, KON.UNIT_CD, KON.UNPAN_GYOUSHA_CD, KON.NIOROSHI_GYOUSHA_CD, KON.NIOROSHI_GENBA_CD, KON.TEKIYOU_BEGIN
