SELECT
	 GENBA.GENBA_CD as NIOROSHI_GENBA_CD
    ,GENBA.GENBA_NAME_RYAKU as NIOROSHI_GENBA_RYAKU
	,GENBA.GYOUSHA_CD as NIOROSHI_GYOUSHA_CD
    ,GYOUSHA.GYOUSHA_NAME_RYAKU as NIOROSHI_GYOUSHA_RYAKU
FROM
    dbo.M_GENBA GENBA
	LEFT JOIN dbo.M_GYOUSHA GYOUSHA ON GENBA.GYOUSHA_CD = GYOUSHA.GYOUSHA_CD
WHERE GENBA.GYOUSHA_CD = /*data.GYOUSHA_CD*/''
  AND GENBA.GENBA_CD = /*data.GENBA_CD*/''
  AND ((GYOUSHA.UNPAN_JUTAKUSHA_KAISHA_KBN = 1 AND GENBA.TSUMIKAEHOKAN_KBN = 1)
       OR
       ((GYOUSHA.SHOBUN_NIOROSHI_GYOUSHA_KBN = 1 AND (GENBA.SHOBUN_NIOROSHI_GENBA_KBN = 1 OR GENBA.SAISHUU_SHOBUNJOU_KBN = 1))))
  AND GENBA.DELETE_FLG = 0
  AND GYOUSHA.DELETE_FLG = 0
