SELECT 
    TORI.TORIHIKISAKI_CD as TORIHIKISAKI_CD
    ,TORI.TORIHIKISAKI_NAME_RYAKU as TORIHIKISAKI_NAME_RYAKU
FROM 
    dbo.M_TORIHIKISAKI TORI 
WHERE TORI.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/''
  AND TORI.DELETE_FLG = 0