SELECT  M_GTH.*
FROM
M_GENBA_TEIKI_HINMEI AS M_GTH
WHERE
M_GTH.GYOUSHA_CD = /*data.GYOUSHA_CD*/
AND M_GTH.GENBA_CD = /*data.GENBA_CD*/
AND M_GTH.HINMEI_CD = /*data.HINMEI_CD*/
AND M_GTH.UNIT_CD = /*data.UNIT_CD*/