SELECT 
 US1.SYSTEM_ID
,US1.SEQ
,US1.COURSE_KUMIKOMI_CD
,COURSE_KUMIKOMI_NAME = 
CASE 
WHEN US1.COURSE_NAME_CD IS NULL THEN ' '
ELSE '済'
END
,(SELECT TH1.TEIKI_HAISHA_NUMBER
	FROM T_TEIKI_HAISHA_ENTRY TH1
		INNER JOIN T_TEIKI_HAISHA_DETAIL TH2
	            ON  TH1.SYSTEM_ID = TH2.SYSTEM_ID
	  AND TH1.SEQ = TH2.SEQ
	WHERE TH2.UKETSUKE_NUMBER = US1.UKETSUKE_NUMBER
	    AND TH1.DELETE_FLG = 0 ) AS TEIKI_HAISHA_NUMBER
,(SELECT TH1.TEIKI_HAISHA_NUMBER
	FROM T_TEIKI_HAISHA_ENTRY TH1
		INNER JOIN T_TEIKI_HAISHA_DETAIL TH2
				ON  TH1.SYSTEM_ID = TH2.SYSTEM_ID
	  AND TH1.SEQ = TH2.SEQ
	WHERE TH2.UKETSUKE_NUMBER = US1.UKETSUKE_NUMBER 
	    AND TH1.DELETE_FLG = 0) AS TEIKI_HAISHA_NUMBER_BEFORE
,US1.COURSE_NAME_CD
,US1.COURSE_NAME_CD AS COURSE_NAME_CD_BEFORE
,(SELECT CN.COURSE_NAME_RYAKU
	FROM M_COURSE_NAME CN
	WHERE US1.COURSE_NAME_CD = CN.COURSE_NAME_CD) AS COURSE_NAME
,US1.UKETSUKE_NUMBER
,US1.SAGYOU_DATE
,US1.SAGYOU_DATE AS SAGYOU_DATE_OLD
,US1.GYOUSHA_CD
,US1.GYOUSHA_NAME
,US1.GENBA_CD
,US1.GENBA_NAME
,US1.SHARYOU_CD
,US1.SHARYOU_NAME
,US1.SHASHU_CD
,US1.SHASHU_NAME
,US1.UNTENSHA_CD
,US1.UNTENSHA_NAME
,1 AS ENTITY_KBN
,US1.CREATE_DATE
,cast (0 as bit) as KUMIAI_SUMI
,cast (0 as bit) as MOBILE_RENKEI
FROM T_UKETSUKE_SS_ENTRY US1
WHERE US1.DELETE_FLG = 0
AND US1.HAISHA_JOKYO_CD < 3
AND US1.COURSE_KUMIKOMI_CD = '2'
/*IF data.KUMIKOMI_STATUS == 1*/AND US1.COURSE_NAME_CD IS NULL/*END*/
/*IF data.KUMIKOMI_STATUS == 2*/AND US1.COURSE_NAME_CD IS NOT NULL/*END*/
/*IF data.KYOTEN_CD != null*/AND US1.KYOTEN_CD = CONVERT(smallint, /*data.KYOTEN_CD*/'')/*END*/
/*IF data.SAGYOU_DATE_BEGIN != null*/AND (US1.SAGYOU_DATE >= /*data.SAGYOU_DATE_BEGIN*/ OR US1.SAGYOU_DATE_BEGIN >= /*data.SAGYOU_DATE_BEGIN*/)/*END*/
/*IF data.SAGYOU_DATE_END != null*/AND (US1.SAGYOU_DATE <= /*data.SAGYOU_DATE_END*/ OR US1.SAGYOU_DATE <= /*data.SAGYOU_DATE_END*/)/*END*/
ORDER BY CREATE_DATE