SELECT TTHE.TEIKI_HAISHA_NUMBER, TTHE.COURSE_NAME_CD, MCN.COURSE_NAME_RYAKU
FROM T_TEIKI_HAISHA_ENTRY TTHE
LEFT JOIN M_COURSE_NAME MCN
ON TTHE.COURSE_NAME_CD = MCN.COURSE_NAME_CD
WHERE
TTHE.DELETE_FLG = 0
/*IF data.SAGYOU_DATE != null && data.SAGYOU_DATE != ''*/
AND convert(varchar(10),TTHE.SAGYOU_DATE,111) = convert(varchar(10),convert(datetime,/*data.SAGYOU_DATE*/),111)
/*END*/
/*IF data.TEIKI_HAISHA_NUMBER != null && data.TEIKI_HAISHA_NUMBER != ''*/
AND TTHE.TEIKI_HAISHA_NUMBER = /*data.TEIKI_HAISHA_NUMBER*/
/*END*/
/*IF data.COURSE_NAME_CD != null && data.COURSE_NAME_CD != ''*/
AND TTHE.COURSE_NAME_CD = /*data.COURSE_NAME_CD*/
/*END*/
/*IF data.KYOTEN_CD != null && data.KYOTEN_CD != ''*/
AND MCN.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/