SELECT 
T_USSD.*
FROM
T_UKETSUKE_SS_DETAIL T_USSD
INNER JOIN T_UKETSUKE_SS_ENTRY T_USSE
ON T_USSD.SYSTEM_ID = T_USSE.SYSTEM_ID
AND T_USSD.SEQ = T_USSE.SEQ
WHERE
T_USSD.SYSTEM_ID = /*data.SYSTEM_ID*/
AND T_USSE.DELETE_FLG = 0
ORDER BY 
T_USSD.ROW_NO