SELECT 
T_USKD.*
FROM
T_UKETSUKE_SK_DETAIL AS T_USKD
INNER JOIN T_UKETSUKE_SK_ENTRY AS T_USKE
ON T_USKD.SYSTEM_ID = T_USKE.SYSTEM_ID
AND T_USKD.SEQ = T_USKE.SEQ
WHERE
T_USKD.SYSTEM_ID = /*data.SYSTEM_ID*/
AND T_USKE.DELETE_FLG = 0
ORDER BY 
T_USKD.ROW_NO