SELECT
	HIN.*
FROM 
	dbo.M_HINMEI HIN
		INNER JOIN dbo.M_DENSHU_KBN DEN ON DEN.DENSHU_KBN_CD = HIN.DENSHU_KBN_CD
WHERE
	HIN.HINMEI_CD = /*data.HINMEI_CD*/''
	AND (
	HIN.DENSHU_KBN_CD = CONVERT (SMALLINT, '1')
	OR HIN.DENSHU_KBN_CD = CONVERT (SMALLINT, '3')
	OR HIN.DENSHU_KBN_CD = CONVERT (SMALLINT, '9')
	)
ORDER BY HIN.HINMEI_CD