SELECT
    GYOUSHA.GYOUSHA_CD as UNPAN_GYOUSHA_CD
    ,GYOUSHA.GYOUSHA_NAME_RYAKU as UNPAN_GYOUSHA_RYAKU
FROM
    dbo.M_GYOUSHA GYOUSHA
WHERE GYOUSHA.GYOUSHA_CD = /*data.GYOUSHA_CD*/''
  AND GYOUSHA.UNPAN_JUTAKUSHA_KAISHA_KBN = 1
