SELECT 
M_GYOUSHA.GYOUSHA_CD, 
M_GYOUSHA.GYOUSHA_NAME_RYAKU, 
M_GYOUSHA.GYOUSHA_FURIGANA,
M_GYOUSHA.GYOUSHA_POST,  
M_TODOUFUKEN.TODOUFUKEN_NAME_RYAKU, 
M_GYOUSHA.GYOUSHA_ADDRESS1, 
M_GYOUSHA.GYOUSHA_TEL 
FROM M_GYOUSHA 
LEFT JOIN M_TODOUFUKEN ON M_GYOUSHA.GYOUSHA_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD 
AND ((M_TODOUFUKEN.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= M_TODOUFUKEN.TEKIYOU_END) or (M_TODOUFUKEN.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and M_TODOUFUKEN.TEKIYOU_END IS NULL) or (M_TODOUFUKEN.TEKIYOU_BEGIN IS NULL and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= M_TODOUFUKEN.TEKIYOU_END) or (M_TODOUFUKEN.TEKIYOU_BEGIN IS NULL and M_TODOUFUKEN.TEKIYOU_END IS NULL))
AND M_TODOUFUKEN.DELETE_FLG = 0
WHERE
M_GYOUSHA.GYOUSHA_CD = /*data.gyoushaCd*/