SELECT
  -- 廃棄物区分CD
  PT_ENTRY.HAIKI_KBN_CD,
  CASE PT_ENTRY.HAIKI_KBN_CD WHEN 1 THEN '直行' WHEN 2 THEN '建廃' WHEN 3 THEN '積替' ELSE '' END AS HAIKI_KBN_NAME ,

  -- 一次マニフェスト区分
  CASE PT_ENTRY.FIRST_MANIFEST_KBN WHEN 'false' THEN 1 WHEN 'true' THEN 2 END AS FIRST_MANIFEST_KBN,
  CASE PT_ENTRY.FIRST_MANIFEST_KBN WHEN 'false' THEN '一次' WHEN 'true' THEN '二次' ELSE '' END AS FIRST_MANIFEST_KBN_NAME,

  -- 拠点CD
  PT_ENTRY.KYOTEN_CD,
  ISNULL(M_KYOTEN.KYOTEN_NAME_RYAKU,'') AS KYOTEN_NAME,

  -- 取引先CD
  PT_ENTRY.TORIHIKISAKI_CD,
  ISNULL(M_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU,'') AS TORIHIKISAKI_NAME,

  -- 交付年月日
  CONVERT(varchar(10), PT_ENTRY.KOUFU_DATE, 111) AS KOUFU_DATE,

  -- 交付番号区分
  PT_ENTRY.KOUFU_KBN,

  -- 交付番号 
  PT_ENTRY.MANIFEST_ID,

  -- 整理番号 
  PT_ENTRY.SEIRI_ID,

  -- 交付担当者 
  PT_ENTRY.KOUFU_TANTOUSHA,

  -- 交付担当者所属 
  PT_ENTRY.KOUFU_TANTOUSHA_SHOZOKU,

  -- 排出事業者CD 
  PT_ENTRY.HST_GYOUSHA_CD,

  -- 排出事業者名称
  PT_ENTRY.HST_GYOUSHA_NAME,

  -- 排出事業者郵便番号 
  PT_ENTRY.HST_GYOUSHA_POST,

  -- 排出事業者電話番号 
  PT_ENTRY.HST_GYOUSHA_TEL,

  -- 排出事業者住所  
  PT_ENTRY.HST_GYOUSHA_ADDRESS,

  -- 排出事業場CD 
  PT_ENTRY.HST_GENBA_CD,

  -- 排出事業場名称 
  PT_ENTRY.HST_GENBA_NAME,

  -- 排出事業場郵便番号 
  PT_ENTRY.HST_GENBA_POST,

  -- 排出事業場電話番号  
  PT_ENTRY.HST_GENBA_TEL,

  -- 排出事業場住所 
  PT_ENTRY.HST_GENBA_ADDRESS,

  -- 備考 
  PT_ENTRY.BIKOU,

  -- 実績数量 
  PT_ENTRY.HAIKI_SUU,

  -- 実績単位CD 
  PT_ENTRY.HAIKI_UNIT_CD,

  -- 最終処分の場所（予定）区分 
  PT_ENTRY.LAST_SBN_YOTEI_KBN,

  -- 最終処分の場所（予定）業者CD 
  PT_ENTRY.LAST_SBN_YOTEI_GYOUSHA_CD,

  -- 最終処分の場所（予定）現場CD 
  PT_ENTRY.LAST_SBN_YOTEI_GENBA_CD,

  -- 最終処分の場所（予定）現場名称
  PT_ENTRY.LAST_SBN_YOTEI_GENBA_NAME,

  -- 最終処分の場所（予定）郵便番号
  PT_ENTRY.LAST_SBN_YOTEI_GENBA_POST,

  -- 最終処分の場所（予定）電話番号  
  PT_ENTRY.LAST_SBN_YOTEI_GENBA_TEL,

  -- 最終処分の場所（予定）住所 
  PT_ENTRY.LAST_SBN_YOTEI_GENBA_ADDRESS,

  -- 処分受託者CD 
  PT_ENTRY.SBN_GYOUSHA_CD,

  -- 処分受託者名称 
  PT_ENTRY.SBN_GYOUSHA_NAME,

  -- 処分受託者郵便番号
  PT_ENTRY.SBN_GYOUSHA_POST,

  -- 処分受託者電話番号
  PT_ENTRY.SBN_GYOUSHA_TEL,

  -- 処分受託者住所 
  PT_ENTRY.SBN_GYOUSHA_ADDRESS,

  -- 処分の受領者CD
  PT_ENTRY.SBN_JYURYOUSHA_CD,

  -- 処分の受領者名称
  PT_ENTRY.SBN_JYURYOUSHA_NAME,

  -- 処分の受領担当者CD
  PT_ENTRY.SBN_JYURYOU_TANTOU_CD,

  -- 処分の受領担当者名
  PT_ENTRY.SBN_JYURYOU_TANTOU_NAME,

  -- 処分受領日
  CONVERT(varchar(10), PT_ENTRY.SBN_JYURYOU_DATE, 111) AS SBN_JYURYOU_DATE,

  -- 処分の受託者CD  
  PT_ENTRY.SBN_JYUTAKUSHA_CD,

  -- 処分の受託者名称 
  PT_ENTRY.SBN_JYUTAKUSHA_NAME,

  -- 処分担当者CD 
  PT_ENTRY.SBN_TANTOU_CD,

  -- 処分担当者名 
  PT_ENTRY.SBN_TANTOU_NAME,

  -- 照合確認B1票
  CONVERT(varchar(10), PT_ENTRY.CHECK_B1, 111) AS CHECK_B1,

  -- 照合確認B2票
  CONVERT(varchar(10), PT_ENTRY.CHECK_B2, 111) AS CHECK_B2,

  -- 照合確認B4票
  CONVERT(varchar(10), PT_ENTRY.CHECK_B4, 111) AS CHECK_B4,

  -- 照合確認B6票
  CONVERT(varchar(10), PT_ENTRY.CHECK_B6, 111) AS CHECK_B6,

  -- 照合確認D票
  CONVERT(varchar(10), PT_ENTRY.CHECK_D, 111) AS CHECK_D,

  -- 照合確認E票
  CONVERT(varchar(10), PT_ENTRY.CHECK_E, 111) AS CHECK_E,


  --運搬区間
  PT_UPN.UPN_ROUTE_NO,

  --運搬受託者CD
  PT_UPN.UPN_GYOUSHA_CD,

  --運搬受託者名称
  PT_UPN.UPN_GYOUSHA_NAME,

  --運搬受託者郵便番号
  PT_UPN.UPN_GYOUSHA_POST,

  --運搬受託者電話番号
  PT_UPN.UPN_GYOUSHA_TEL,

  --運搬受託者住所
  PT_UPN.UPN_GYOUSHA_ADDRESS,

  --運搬方法CD
  PT_UPN.UPN_HOUHOU_CD,
  ISNULL(M_UNPAN_HOUHOU.UNPAN_HOUHOU_NAME_RYAKU,'') AS UNPAN_HOUHOU_NAME,

  --車種CD
  PT_UPN.SHASHU_CD,
  ISNULL(M_SHASHU.SHASHU_NAME_RYAKU,'') AS SHASHU_NAME,

  --車輌CD
  PT_UPN.SHARYOU_CD,
  ISNULL(M_SHARYOU.SHARYOU_NAME_RYAKU,'') AS SHARYOU_NAME,

  -- 積替保管有無
  PT_UPN.TMH_KBN,
  CASE PT_UPN.TMH_KBN WHEN 1 THEN '有' WHEN 2 THEN '無' ELSE '' END AS TMH_KBN_NAME,

  --運搬先区分
  PT_UPN.UPN_SAKI_KBN,
  CASE PT_UPN.UPN_SAKI_KBN WHEN 1 THEN '処分施設' WHEN 2 THEN '積替保管' ELSE '' END AS UPN_SAKI_KBN_NAME,

  --運搬先の事業者CD
  PT_UPN.UPN_SAKI_GYOUSHA_CD,

  --運搬先の事業場CD
  PT_UPN.UPN_SAKI_GENBA_CD,

  --運搬先の事業場名称
  PT_UPN.UPN_SAKI_GENBA_NAME,

  --運搬先の事業場郵便番号
  PT_UPN.UPN_SAKI_GENBA_POST,

  --運搬先の事業場電話番号
  PT_UPN.UPN_SAKI_GENBA_TEL,

  --運搬先の事業場住所
  PT_UPN.UPN_SAKI_GENBA_ADDRESS,

  --運搬の受託者CD
  PT_UPN.UPN_JYUTAKUSHA_CD,

  --運搬の受託者名称
  PT_UPN.UPN_JYUTAKUSHA_NAME,

  --運転者CD
  PT_UPN.UNTENSHA_CD,

  --運転者名
  PT_UPN.UNTENSHA_NAME,

  --運搬終了年月日
  CONVERT(varchar(10), PT_UPN.UPN_END_DATE, 111) AS UPN_END_DATE,


  --廃棄物種類CD 
  PT_DETAIL.HAIKI_SHURUI_CD,
  ISNULL(M_HAIKI_SHURUI.HAIKI_SHURUI_NAME_RYAKU,'') AS HAIKI_SHURUI_NAME,

  --廃棄物名称CD 
  PT_DETAIL.HAIKI_NAME_CD,
  ISNULL(M_HAIKI_NAME.HAIKI_NAME_RYAKU,'') AS HAIKI_NAME,

  --荷姿CD
  PT_DETAIL.NISUGATA_CD,
  ISNULL(M_NISUGATA.NISUGATA_NAME_RYAKU,'') AS NISUGATA_NAME,

  --数量
  PT_DETAIL.HAIKI_SUU,

  --単位CD 
  PT_DETAIL.HAIKI_UNIT_CD,
  ISNULL(M_UNIT.UNIT_NAME_RYAKU,'') AS UNIT_NAME,

  --処分方法CD
  PT_DETAIL.SBN_HOUHOU_CD,
  ISNULL(M_SHOBUN_HOUHOU.SHOBUN_HOUHOU_NAME_RYAKU,'') AS SHOBUN_HOUHOU_NAME,

  --処分終了日
  CONVERT(varchar(10), PT_DETAIL.SBN_END_DATE, 111) AS SBN_END_DATE,

  --最終処分終了日
  CONVERT(varchar(10), PT_DETAIL.LAST_SBN_END_DATE, 111) AS LAST_SBN_END_DATE,

  --最終処分業者CD
  PT_DETAIL.LAST_SBN_GYOUSHA_CD,
  LAST_GY.GYOUSHA_NAME_RYAKU,
  --最終処分現場CD
  PT_DETAIL.LAST_SBN_GENBA_CD,
  LAST_GB.GENBA_NAME_RYAKU, 

  --積替保管
  PT_ENTRY.TMH_GYOUSHA_CD, 
  PT_ENTRY.TMH_GYOUSHA_NAME, 
  PT_ENTRY.TMH_GENBA_CD, 
  PT_ENTRY.TMH_GENBA_NAME, 
  PT_ENTRY.TMH_GENBA_POST, 
  PT_ENTRY.TMH_GENBA_TEL, 
  PT_ENTRY.TMH_GENBA_ADDRESS 

  FROM T_MANIFEST_PT_ENTRY PT_ENTRY 
  LEFT OUTER JOIN M_KYOTEN
    ON PT_ENTRY.KYOTEN_CD = M_KYOTEN.KYOTEN_CD
   AND M_KYOTEN.DELETE_FLG = 'false'
   AND ( M_KYOTEN.TEKIYOU_BEGIN < GETDATE() OR M_KYOTEN.TEKIYOU_BEGIN IS NULL )
   AND ( M_KYOTEN.TEKIYOU_END > GETDATE() OR M_KYOTEN.TEKIYOU_END IS NULL )
  LEFT OUTER JOIN M_TORIHIKISAKI 
    ON PT_ENTRY.TORIHIKISAKI_CD = M_TORIHIKISAKI.TORIHIKISAKI_CD 
   AND M_TORIHIKISAKI.DELETE_FLG = 'false'
   AND ( M_TORIHIKISAKI.TEKIYOU_BEGIN < GETDATE() OR M_TORIHIKISAKI.TEKIYOU_BEGIN IS NULL )
   AND ( M_TORIHIKISAKI.TEKIYOU_END > GETDATE() OR M_TORIHIKISAKI.TEKIYOU_END IS NULL )

  LEFT OUTER JOIN T_MANIFEST_PT_UPN PT_UPN 
    ON PT_ENTRY.SYSTEM_ID = PT_UPN.SYSTEM_ID
   AND PT_ENTRY.SEQ = PT_UPN.SEQ
  LEFT OUTER JOIN M_UNPAN_HOUHOU 
    ON PT_UPN.UPN_HOUHOU_CD = M_UNPAN_HOUHOU.UNPAN_HOUHOU_CD
   AND M_UNPAN_HOUHOU.DELETE_FLG = 'false'
   AND ( M_UNPAN_HOUHOU.TEKIYOU_BEGIN < GETDATE() OR M_UNPAN_HOUHOU.TEKIYOU_BEGIN IS NULL )
   AND ( M_UNPAN_HOUHOU.TEKIYOU_END  > GETDATE() OR M_UNPAN_HOUHOU.TEKIYOU_END IS NULL )
  LEFT OUTER JOIN M_SHASHU
    ON PT_UPN.SHASHU_CD = M_SHASHU.SHASHU_CD 
   AND M_SHASHU.DELETE_FLG = 'false'
   AND ( M_SHASHU.TEKIYOU_BEGIN < GETDATE() OR M_SHASHU.TEKIYOU_BEGIN IS NULL )
   AND ( M_SHASHU.TEKIYOU_END > GETDATE() OR M_SHASHU.TEKIYOU_END IS NULL )
  LEFT OUTER JOIN M_SHARYOU
    ON PT_UPN.UPN_GYOUSHA_CD = M_SHARYOU.GYOUSHA_CD 
   AND PT_UPN.SHARYOU_CD = M_SHARYOU.SHARYOU_CD 
   AND M_SHARYOU.DELETE_FLG = 'false'
   AND ( M_SHARYOU.TEKIYOU_BEGIN < GETDATE() OR M_SHARYOU.TEKIYOU_BEGIN IS NULL )
   AND ( M_SHARYOU.TEKIYOU_END > GETDATE() OR M_SHARYOU.TEKIYOU_END IS NULL )

  LEFT OUTER JOIN T_MANIFEST_PT_DETAIL PT_DETAIL 
    ON PT_ENTRY.SYSTEM_ID = PT_DETAIL.SYSTEM_ID
   AND PT_ENTRY.SEQ = PT_DETAIL.SEQ
  LEFT OUTER JOIN M_HAIKI_SHURUI WITH(NOLOCK) 
    ON PT_ENTRY.HAIKI_KBN_CD = M_HAIKI_SHURUI.HAIKI_KBN_CD 
   AND PT_DETAIL.HAIKI_SHURUI_CD = M_HAIKI_SHURUI.HAIKI_SHURUI_CD 
   AND M_HAIKI_SHURUI.DELETE_FLG = 'False' 
   AND ( M_HAIKI_SHURUI.TEKIYOU_BEGIN < GETDATE() OR M_HAIKI_SHURUI.TEKIYOU_BEGIN IS NULL )
   AND ( M_HAIKI_SHURUI.TEKIYOU_END > GETDATE() OR M_HAIKI_SHURUI.TEKIYOU_END IS NULL )
  LEFT OUTER JOIN M_HAIKI_NAME WITH(NOLOCK) 
    ON PT_DETAIL.HAIKI_NAME_CD = M_HAIKI_NAME.HAIKI_NAME_CD 
   AND M_HAIKI_NAME.DELETE_FLG = 'False' 
   AND ( M_HAIKI_NAME.TEKIYOU_BEGIN < GETDATE() OR M_HAIKI_NAME.TEKIYOU_BEGIN IS NULL )
   AND ( M_HAIKI_NAME.TEKIYOU_END > GETDATE() OR M_HAIKI_NAME.TEKIYOU_END IS NULL )
  LEFT OUTER JOIN M_NISUGATA WITH(NOLOCK) 
    ON PT_DETAIL.NISUGATA_CD = M_NISUGATA.NISUGATA_CD 
   AND M_NISUGATA.DELETE_FLG = 'False' 
   AND ( M_NISUGATA.TEKIYOU_BEGIN < GETDATE() OR M_NISUGATA.TEKIYOU_BEGIN IS NULL )
   AND ( M_NISUGATA.TEKIYOU_END > GETDATE() OR M_NISUGATA.TEKIYOU_END IS NULL )
  LEFT OUTER JOIN M_UNIT WITH(NOLOCK) 
    ON PT_DETAIL.HAIKI_UNIT_CD = M_UNIT.UNIT_CD 
   AND M_UNIT.DELETE_FLG = 'False' 
   AND ( M_UNIT.TEKIYOU_BEGIN < GETDATE() OR M_UNIT.TEKIYOU_BEGIN IS NULL )
   AND ( M_UNIT.TEKIYOU_END > GETDATE() OR M_UNIT.TEKIYOU_END IS NULL )
  LEFT OUTER JOIN M_SHOBUN_HOUHOU WITH(NOLOCK) 
    ON PT_DETAIL.SBN_HOUHOU_CD = M_SHOBUN_HOUHOU.SHOBUN_HOUHOU_CD 
   AND M_SHOBUN_HOUHOU.DELETE_FLG = 'False' 
   AND ( M_SHOBUN_HOUHOU.TEKIYOU_BEGIN < GETDATE() OR M_SHOBUN_HOUHOU.TEKIYOU_BEGIN IS NULL )
   AND ( M_SHOBUN_HOUHOU.TEKIYOU_END > GETDATE() OR M_SHOBUN_HOUHOU.TEKIYOU_END IS NULL )
  LEFT OUTER JOIN M_GYOUSHA AS LAST_GY WITH(NOLOCK) 
    ON PT_DETAIL.LAST_SBN_GYOUSHA_CD = LAST_GY.GYOUSHA_CD 
  LEFT OUTER JOIN M_GENBA AS LAST_GB WITH(NOLOCK) 
    ON PT_DETAIL.LAST_SBN_GYOUSHA_CD = LAST_GB.GYOUSHA_CD 
	AND PT_DETAIL.LAST_SBN_GENBA_CD = LAST_GB.GENBA_CD 
 WHERE PT_ENTRY.DELETE_FLG = 'false'
   AND PT_ENTRY.SYSTEM_ID = /*data.systemId*/
