SELECT
	TMLZ.YEAR,
	TMLZ.MONTH,
	TMLZ.GOUKEI_ZAIKO_RYOU,
	TMLZ.GOUKEI_KINGAKU
FROM
	T_MONTHLY_LOCK_ZAIKO TMLZ
WHERE
	TMLZ.DELETE_FLG = 0
	AND TMLZ.GYOUSHA_CD = /*data.GYOUSHA_CD*/'000001'
	AND TMLZ.GENBA_CD = /*data.GENBA_CD*/'000001'
	AND TMLZ.ZAIKO_HINMEI_CD = /*data.ZAIKO_HINMEI_CD*/'000001'
ORDER BY TMLZ.YEAR, TMLZ.MONTH DESC