--売上・支払どちらかの伝票が発生していなくてもデータは作られるのでどちらしかない場合はありえないが念のためUINION
SELECT
	*
FROM (
	SELECT
		*
	FROM (
		SELECT
			CONVERT(DATETIME, STR(YEAR) + '/' + STR(MONTH) + '/1', 111) AS SHIME_DATE,
			T_MONTHLY_LOCK_UR.TORIHIKISAKI_CD,
			T_MONTHLY_LOCK_UR.YEAR,
			T_MONTHLY_LOCK_UR.MONTH,
			T_MONTHLY_LOCK_UR.DELETE_FLG
		FROM
			T_MONTHLY_LOCK_UR
	) TMLU
	WHERE
		DELETE_FLG = 0
		AND	TORIHIKISAKI_CD = /*TORIHIKISAKI_CD*/'000001'
		AND TMLU.SHIME_DATE < CONVERT(DATETIME, /*SHIME_DATE*/null, 111)
	UNION ALL
	SELECT
		*
	FROM (
		SELECT
			CONVERT(DATETIME, STR(YEAR) + '/' + STR(MONTH) + '/1', 111) AS SHIME_DATE,
			T_MONTHLY_LOCK_SH.TORIHIKISAKI_CD,
			T_MONTHLY_LOCK_SH.YEAR,
			T_MONTHLY_LOCK_SH.MONTH,
			T_MONTHLY_LOCK_SH.DELETE_FLG
		FROM
			T_MONTHLY_LOCK_SH
	) TMLU
	WHERE
		DELETE_FLG = 0
		AND	TORIHIKISAKI_CD = /*TORIHIKISAKI_CD*/'000001'
		AND TMLU.SHIME_DATE < CONVERT(DATETIME, /*SHIME_DATE*/null, 111)
) MONTHLY_LOCK
ORDER BY MONTHLY_LOCK.SHIME_DATE DESC