SELECT
ENT.SYSTEM_ID,
ENT.SEQ,
/*IF DENPYO_SHURUI == 2*/ENT.UKEIRE_NUMBER AS DENPYONO,/*END*/
/*IF DENPYO_SHURUI == 3*/ENT.SHUKKA_NUMBER AS DENPYONO,/*END*/
/*IF DENPYO_SHURUI == 4*/ENT.UR_SH_NUMBER AS DENPYONO,/*END*/
ENT.DENPYOU_DATE,
ENT.SHIHARAI_DATE,
ENT.TORIHIKISAKI_CD,
ENT.GYOUSHA_CD,
ENT.GENBA_CD,
/*IF DENPYO_SHURUI != 2*/ENT.SHIHARAI_AMOUNT_TOTAL AS SHIHARAI_KINGAKU_TOTAL,/*END*/
/*IF DENPYO_SHURUI == 2*/ENT.SHIHARAI_KINGAKU_TOTAL,/*END*/
ENT.SHIHARAI_TAX_SOTO,
ENT.SHIHARAI_TAX_UCHI,
ENT.SHIHARAI_TAX_SOTO_TOTAL,
ENT.SHIHARAI_TAX_UCHI_TOTAL,
ENT.HINMEI_SHIHARAI_KINGAKU_TOTAL,
ENT.HINMEI_SHIHARAI_TAX_SOTO_TOTAL,
ENT.HINMEI_SHIHARAI_TAX_UCHI_TOTAL,
ENT.SHIHARAI_ZEI_KEISAN_KBN_CD,
ENT.SHIHARAI_ZEI_KBN_CD,
ENT.SHIHARAI_SHOUHIZEI_RATE,

--DET.SYSTEM_ID,
--DET.SEQ,
DET.DETAIL_SYSTEM_ID,
/*IF DENPYO_SHURUI == 2*/DET.UKEIRE_NUMBER,/*END*/
/*IF DENPYO_SHURUI == 3*/DET.SHUKKA_NUMBER,/*END*/
/*IF DENPYO_SHURUI == 4*/DET.UR_SH_NUMBER,/*END*/
DET.DENPYOU_KBN_CD,
DET.HINMEI_CD,
--DET.HINMEI_NAME,
DET.SUURYOU,
DET.UNIT_CD,
DET.KINGAKU,
DET.TAX_SOTO,
DET.TAX_UCHI,
DET.HINMEI_KINGAKU,
DET.HINMEI_TAX_SOTO,
DET.HINMEI_TAX_UCHI,
DET.HINMEI_ZEI_KBN_CD,
DET.MEISAI_BIKOU,
DET.TANKA,
DET.ROW_NO,

M_GYOUSHA.SHIHARAI_KYOTEN_PRINT_KBN AS GY_SHIHARAI_KYOTEN_PRINT_KBN,
M_GYOUSHA.SHIHARAI_KYOTEN_CD AS GY_SHIHARAI_KYOTEN_CD,
M_GYOUSHA.SHIHARAI_SOUFU_NAME1 AS GY_SHIHARAI_SOUFU_NAME1,
M_GYOUSHA.SHIHARAI_SOUFU_NAME2 AS GY_SHIHARAI_SOUFU_NAME2,
M_GYOUSHA.SHIHARAI_SOUFU_KEISHOU1 AS GY_SHIHARAI_SOUFU_KEISHOU1,
M_GYOUSHA.SHIHARAI_SOUFU_KEISHOU2 AS GY_SHIHARAI_SOUFU_KEISHOU2,
M_GYOUSHA.SHIHARAI_SOUFU_POST AS GY_SHIHARAI_SOUFU_POST,
M_GYOUSHA.SHIHARAI_SOUFU_ADDRESS1 AS GY_SHIHARAI_SOUFU_ADDRESS1,
M_GYOUSHA.SHIHARAI_SOUFU_ADDRESS2 AS GY_SHIHARAI_SOUFU_ADDRESS2,
M_GYOUSHA.SHIHARAI_SOUFU_BUSHO AS GY_SHIHARAI_SOUFU_BUSHO,
M_GYOUSHA.SHIHARAI_SOUFU_TANTOU AS GY_SHIHARAI_SOUFU_TANTOU,
M_GYOUSHA.SHIHARAI_SOUFU_TEL AS GY_SHIHARAI_SOUFU_TEL,
M_GYOUSHA.SHIHARAI_SOUFU_FAX AS GY_SHIHARAI_SOUFU_FAX,
M_GYOUSHA.GYOUSHA_NAME1,
M_GYOUSHA.GYOUSHA_NAME2,

M_GYOUSHA_KYOTEN.KYOTEN_NAME AS GY_KYOTEN_NAME,
M_GYOUSHA_KYOTEN.KYOTEN_DAIHYOU AS GY_KYOTEN_DAIHYOU,
M_GYOUSHA_KYOTEN.KYOTEN_POST AS GY_KYOTEN_POST,
M_GYOUSHA_KYOTEN.KYOTEN_ADDRESS1 AS GY_KYOTEN_ADDRESS1,
M_GYOUSHA_KYOTEN.KYOTEN_ADDRESS2 AS GY_KYOTEN_ADDRESS2,
M_GYOUSHA_KYOTEN.KYOTEN_TEL AS GY_KYOTEN_TEL,
M_GYOUSHA_KYOTEN.KYOTEN_FAX AS GY_KYOTEN_FAX,

M_GENBA.GENBA_CD,
M_GENBA.SHIHARAI_KYOTEN_PRINT_KBN AS GE_SHIHARAI_KYOTEN_PRINT_KBN,
M_GENBA.SHIHARAI_KYOTEN_CD AS GE_SHIHARAI_KYOTEN_CD,
M_GENBA.SHIHARAI_SOUFU_NAME1 AS GE_SHIHARAI_SOUFU_NAME1,
M_GENBA.SHIHARAI_SOUFU_NAME2 AS GE_SHIHARAI_SOUFU_NAME2,
M_GENBA.SHIHARAI_SOUFU_KEISHOU1 AS GE_SHIHARAI_SOUFU_KEISHOU1,
M_GENBA.SHIHARAI_SOUFU_KEISHOU2 AS GE_SHIHARAI_SOUFU_KEISHOU2,
M_GENBA.SHIHARAI_SOUFU_POST AS GE_SHIHARAI_SOUFU_POST,
M_GENBA.SHIHARAI_SOUFU_ADDRESS1 AS GE_SHIHARAI_SOUFU_ADDRESS1,
M_GENBA.SHIHARAI_SOUFU_ADDRESS2 AS GE_SHIHARAI_SOUFU_ADDRESS2,
M_GENBA.SHIHARAI_SOUFU_BUSHO AS GE_SHIHARAI_SOUFU_BUSHO,
M_GENBA.SHIHARAI_SOUFU_TANTOU AS GE_SHIHARAI_SOUFU_TANTOU,
M_GENBA.SHIHARAI_SOUFU_TEL AS GE_SHIHARAI_SOUFU_TEL,
M_GENBA.SHIHARAI_SOUFU_FAX AS GE_SHIHARAI_SOUFU_FAX,
M_GENBA.GENBA_NAME1,
M_GENBA.GENBA_NAME2,

M_GENBA_KYOTEN.KYOTEN_NAME AS GE_KYOTEN_NAME,
M_GENBA_KYOTEN.KYOTEN_DAIHYOU AS GE_KYOTEN_DAIHYOU,
M_GENBA_KYOTEN.KYOTEN_POST AS GE_KYOTEN_POST,
M_GENBA_KYOTEN.KYOTEN_ADDRESS1 AS GE_KYOTEN_ADDRESS1,
M_GENBA_KYOTEN.KYOTEN_ADDRESS2 AS GE_KYOTEN_ADDRESS2,
M_GENBA_KYOTEN.KYOTEN_TEL AS GE_KYOTEN_TEL,
M_GENBA_KYOTEN.KYOTEN_FAX AS GE_KYOTEN_FAX,

M_UNIT.UNIT_NAME,

M_KYOTEN.KYOTEN_NAME,
M_KYOTEN.KYOTEN_DAIHYOU,
M_KYOTEN.KYOTEN_POST,
M_KYOTEN.KYOTEN_ADDRESS1,
M_KYOTEN.KYOTEN_ADDRESS2,
M_KYOTEN.KYOTEN_TEL,
M_KYOTEN.KYOTEN_FAX,

M_T.SHIHARAI_SOUFU_NAME1,
M_T.SHIHARAI_SOUFU_NAME2,
M_T.SHIHARAI_SOUFU_KEISHOU1,
M_T.SHIHARAI_SOUFU_KEISHOU2,
M_T.SHIHARAI_SOUFU_POST,
M_T.SHIHARAI_SOUFU_ADDRESS1,
M_T.SHIHARAI_SOUFU_ADDRESS2,
M_T.SHIHARAI_KYOTEN_PRINT_KBN,
M_T.SHIHARAI_KYOTEN_CD,
M_T.SHIHARAI_SOUFU_BUSHO,
M_T.SHIHARAI_SOUFU_TANTOU,
M_T.SHIHARAI_SOUFU_TEL,
M_T.SHIHARAI_SOUFU_FAX,
M_T.SHOSHIKI_KBN,

M_TORIHIKISAKI_KYOTEN.KYOTEN_NAME AS TR_KYOTEN_NAME,
M_TORIHIKISAKI_KYOTEN.KYOTEN_DAIHYOU AS TR_KYOTEN_DAIHYOU,
M_TORIHIKISAKI_KYOTEN.KYOTEN_POST AS TR_KYOTEN_POST,
M_TORIHIKISAKI_KYOTEN.KYOTEN_ADDRESS1 AS TR_KYOTEN_ADDRESS1,
M_TORIHIKISAKI_KYOTEN.KYOTEN_ADDRESS2 AS TR_KYOTEN_ADDRESS2,
M_TORIHIKISAKI_KYOTEN.KYOTEN_TEL AS TR_KYOTEN_TEL,
M_TORIHIKISAKI_KYOTEN.KYOTEN_FAX AS TR_KYOTEN_FAX,

M_C.CORP_NAME,
M_C.CORP_DAIHYOU,

M_HINMEI.HINMEI_NAME

FROM
/*IF DENPYO_SHURUI == 2*/T_UKEIRE_ENTRY ENT INNER JOIN T_UKEIRE_DETAIL DET /*END*/
/*IF DENPYO_SHURUI == 3*/T_SHUKKA_ENTRY ENT INNER JOIN T_SHUKKA_DETAIL DET /*END*/
/*IF DENPYO_SHURUI == 4*/T_UR_SH_ENTRY ENT INNER JOIN T_UR_SH_DETAIL DET /*END*/
ON ENT.SYSTEM_ID = DET.SYSTEM_ID 
AND ENT.SEQ = DET.SEQ 
AND DET.DENPYOU_KBN_CD = '2'
LEFT OUTER JOIN M_GYOUSHA
ON ENT.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD 
LEFT OUTER JOIN M_KYOTEN AS M_GYOUSHA_KYOTEN
ON M_GYOUSHA.SHIHARAI_KYOTEN_CD = M_GYOUSHA_KYOTEN.KYOTEN_CD
LEFT OUTER JOIN M_GENBA
ON ENT.GYOUSHA_CD = M_GENBA.GYOUSHA_CD 
AND ENT.GENBA_CD = M_GENBA.GENBA_CD
LEFT OUTER JOIN M_KYOTEN AS M_GENBA_KYOTEN
ON M_GENBA.SHIHARAI_KYOTEN_CD = M_GENBA_KYOTEN.KYOTEN_CD 
LEFT OUTER JOIN M_UNIT
ON DET.UNIT_CD = M_UNIT.UNIT_CD 
LEFT OUTER JOIN M_KYOTEN
ON M_KYOTEN.KYOTEN_CD = ENT.KYOTEN_CD
LEFT JOIN M_TORIHIKISAKI_SHIHARAI M_T
ON M_T.TORIHIKISAKI_CD = /*SHIHARAI_CD*/
LEFT OUTER JOIN M_KYOTEN AS M_TORIHIKISAKI_KYOTEN
ON ISNULL(M_T.SHIHARAI_KYOTEN_CD,'00') = M_TORIHIKISAKI_KYOTEN.KYOTEN_CD
LEFT JOIN M_CORP_INFO M_C
ON M_C.SYS_ID = 0
LEFT JOIN M_HINMEI
ON M_HINMEI.HINMEI_CD = DET.HINMEI_CD
WHERE
ENT.TORIHIKISAKI_CD = /*SHIHARAI_CD*/
/*IF SHIHARAISHIMEBI_FROM != null && SHIHARAISHIMEBI_FROM != ''*/
AND CONVERT(DateTime,/*SHIHARAISHIMEBI_FROM*/nul, 111) <= ENT.DENPYOU_DATE/*END*/
AND ENT.DENPYOU_DATE <= CONVERT(DateTime,/*SHIHARAISHIMEBI_TO*/null, 111)
AND ENT.KAKUTEI_KBN = '1' 
AND ENT.SHIHARAI_TORIHIKI_KBN_CD = '2' 
AND ENT.DELETE_FLG = 0
/*IF DENPYO_SHURUI == 2 || DENPYO_SHURUI == 3*/
AND ENT.TAIRYUU_KBN = 0
/*END*/
/*IF DENPYO_SHURUI == 3*/
AND (ENT.KENSHU_MUST_KBN != 1 OR ENT.KENSHU_MUST_KBN IS NULL)
UNION ALL (
SELECT
ENT.SYSTEM_ID,
ENT.SEQ,
ENT.SHUKKA_NUMBER AS DENPYONO,
ENT.DENPYOU_DATE,
ENT.KENSHU_SHIHARAI_DATE AS SHIHARAI_DATE,
ENT.TORIHIKISAKI_CD,
ENT.GYOUSHA_CD,
ENT.GENBA_CD,
ENT.KENSHU_SHIHARAI_AMOUNT_TOTAL AS SHIHARAI_KINGAKU_TOTAL,
ENT.KENSHU_SHIHARAI_TAX_SOTO AS SHIHARAI_TAX_SOTO,
ENT.KENSHU_SHIHARAI_TAX_UCHI AS SHIHARAI_TAX_UCHI,
ENT.KENSHU_SHIHARAI_TAX_SOTO_TOTAL AS SHIHARAI_TAX_SOTO_TOTAL,
ENT.KENSHU_SHIHARAI_TAX_UCHI_TOTAL AS SHIHARAI_TAX_UCHI_TOTAL,
ENT.KENSHU_HINMEI_SHIHARAI_KINGAKU_TOTAL AS HINMEI_SHIHARAI_KINGAKU_TOTAL,
ENT.KENSHU_HINMEI_SHIHARAI_TAX_SOTO_TOTAL AS HINMEI_SHIHARAI_TAX_SOTO_TOTAL,
ENT.KENSHU_HINMEI_SHIHARAI_TAX_UCHI_TOTAL AS HINMEI_SHIHARAI_TAX_UCHI_TOTAL,
ENT.SHIHARAI_ZEI_KEISAN_KBN_CD,
ENT.SHIHARAI_ZEI_KBN_CD,
ISNULL(ENT.KENSHU_SHIHARAI_SHOUHIZEI_RATE, 0) AS SHIHARAI_SHOUHIZEI_RATE,

DET.DETAIL_SYSTEM_ID,
DET.SHUKKA_NUMBER,
T_K_D.DENPYOU_KBN_CD,
T_K_D.HINMEI_CD,
T_K_D.SUURYOU,
T_K_D.UNIT_CD,
T_K_D.KINGAKU,
T_K_D.TAX_SOTO,
T_K_D.TAX_UCHI,
T_K_D.HINMEI_KINGAKU,
T_K_D.HINMEI_TAX_SOTO,
T_K_D.HINMEI_TAX_UCHI,
T_K_D.HINMEI_ZEI_KBN_CD,
DET.MEISAI_BIKOU,
T_K_D.TANKA,
T_K_D.ROW_NO,

M_GYOUSHA.SHIHARAI_KYOTEN_PRINT_KBN AS GY_SHIHARAI_KYOTEN_PRINT_KBN,
M_GYOUSHA.SHIHARAI_KYOTEN_CD AS GY_SHIHARAI_KYOTEN_CD,
M_GYOUSHA.SHIHARAI_SOUFU_NAME1 AS GY_SHIHARAI_SOUFU_NAME1,
M_GYOUSHA.SHIHARAI_SOUFU_NAME2 AS GY_SHIHARAI_SOUFU_NAME2,
M_GYOUSHA.SHIHARAI_SOUFU_KEISHOU1 AS GY_SHIHARAI_SOUFU_KEISHOU1,
M_GYOUSHA.SHIHARAI_SOUFU_KEISHOU2 AS GY_SHIHARAI_SOUFU_KEISHOU2,
M_GYOUSHA.SHIHARAI_SOUFU_POST AS GY_SHIHARAI_SOUFU_POST,
M_GYOUSHA.SHIHARAI_SOUFU_ADDRESS1 AS GY_SHIHARAI_SOUFU_ADDRESS1,
M_GYOUSHA.SHIHARAI_SOUFU_ADDRESS2 AS GY_SHIHARAI_SOUFU_ADDRESS2,
M_GYOUSHA.SHIHARAI_SOUFU_BUSHO AS GY_SHIHARAI_SOUFU_BUSHO,
M_GYOUSHA.SHIHARAI_SOUFU_TANTOU AS GY_SHIHARAI_SOUFU_TANTOU,
M_GYOUSHA.SHIHARAI_SOUFU_TEL AS GY_SHIHARAI_SOUFU_TEL,
M_GYOUSHA.SHIHARAI_SOUFU_FAX AS GY_SHIHARAI_SOUFU_FAX,
M_GYOUSHA.GYOUSHA_NAME1,
M_GYOUSHA.GYOUSHA_NAME2,

M_GYOUSHA_KYOTEN.KYOTEN_NAME AS GY_KYOTEN_NAME,
M_GYOUSHA_KYOTEN.KYOTEN_DAIHYOU AS GY_KYOTEN_DAIHYOU,
M_GYOUSHA_KYOTEN.KYOTEN_POST AS GY_KYOTEN_POST,
M_GYOUSHA_KYOTEN.KYOTEN_ADDRESS1 AS GY_KYOTEN_ADDRESS1,
M_GYOUSHA_KYOTEN.KYOTEN_ADDRESS2 AS GY_KYOTEN_ADDRESS2,
M_GYOUSHA_KYOTEN.KYOTEN_TEL AS GY_KYOTEN_TEL,
M_GYOUSHA_KYOTEN.KYOTEN_FAX AS GY_KYOTEN_FAX,

M_GENBA.GENBA_CD,
M_GENBA.SHIHARAI_KYOTEN_PRINT_KBN AS GE_SHIHARAI_KYOTEN_PRINT_KBN,
M_GENBA.SHIHARAI_KYOTEN_CD AS GE_SHIHARAI_KYOTEN_CD,
M_GENBA.SHIHARAI_SOUFU_NAME1 AS GE_SHIHARAI_SOUFU_NAME1,
M_GENBA.SHIHARAI_SOUFU_NAME2 AS GE_SHIHARAI_SOUFU_NAME2,
M_GENBA.SHIHARAI_SOUFU_KEISHOU1 AS GE_SHIHARAI_SOUFU_KEISHOU1,
M_GENBA.SHIHARAI_SOUFU_KEISHOU2 AS GE_SHIHARAI_SOUFU_KEISHOU2,
M_GENBA.SHIHARAI_SOUFU_POST AS GE_SHIHARAI_SOUFU_POST,
M_GENBA.SHIHARAI_SOUFU_ADDRESS1 AS GE_SHIHARAI_SOUFU_ADDRESS1,
M_GENBA.SHIHARAI_SOUFU_ADDRESS2 AS GE_SHIHARAI_SOUFU_ADDRESS2,
M_GENBA.SHIHARAI_SOUFU_BUSHO AS GE_SHIHARAI_SOUFU_BUSHO,
M_GENBA.SHIHARAI_SOUFU_TANTOU AS GE_SHIHARAI_SOUFU_TANTOU,
M_GENBA.SHIHARAI_SOUFU_TEL AS GE_SHIHARAI_SOUFU_TEL,
M_GENBA.SHIHARAI_SOUFU_FAX AS GE_SHIHARAI_SOUFU_FAX,
M_GENBA.GENBA_NAME1,
M_GENBA.GENBA_NAME2,

M_GENBA_KYOTEN.KYOTEN_NAME AS GE_KYOTEN_NAME,
M_GENBA_KYOTEN.KYOTEN_DAIHYOU AS GE_KYOTEN_DAIHYOU,
M_GENBA_KYOTEN.KYOTEN_POST AS GE_KYOTEN_POST,
M_GENBA_KYOTEN.KYOTEN_ADDRESS1 AS GE_KYOTEN_ADDRESS1,
M_GENBA_KYOTEN.KYOTEN_ADDRESS2 AS GE_KYOTEN_ADDRESS2,
M_GENBA_KYOTEN.KYOTEN_TEL AS GE_KYOTEN_TEL,
M_GENBA_KYOTEN.KYOTEN_FAX AS GE_KYOTEN_FAX,

M_UNIT.UNIT_NAME,

M_KYOTEN.KYOTEN_NAME,
M_KYOTEN.KYOTEN_DAIHYOU,
M_KYOTEN.KYOTEN_POST,
M_KYOTEN.KYOTEN_ADDRESS1,
M_KYOTEN.KYOTEN_ADDRESS2,
M_KYOTEN.KYOTEN_TEL,
M_KYOTEN.KYOTEN_FAX,

M_T.SHIHARAI_SOUFU_NAME1,
M_T.SHIHARAI_SOUFU_NAME2,
M_T.SHIHARAI_SOUFU_KEISHOU1,
M_T.SHIHARAI_SOUFU_KEISHOU2,
M_T.SHIHARAI_SOUFU_POST,
M_T.SHIHARAI_SOUFU_ADDRESS1,
M_T.SHIHARAI_SOUFU_ADDRESS2,
M_T.SHIHARAI_KYOTEN_PRINT_KBN,
M_T.SHIHARAI_KYOTEN_CD,
M_T.SHIHARAI_SOUFU_BUSHO,
M_T.SHIHARAI_SOUFU_TANTOU,
M_T.SHIHARAI_SOUFU_TEL,
M_T.SHIHARAI_SOUFU_FAX,
M_T.SHOSHIKI_KBN,

M_TORIHIKISAKI_KYOTEN.KYOTEN_NAME AS TR_KYOTEN_NAME,
M_TORIHIKISAKI_KYOTEN.KYOTEN_DAIHYOU AS TR_KYOTEN_DAIHYOU,
M_TORIHIKISAKI_KYOTEN.KYOTEN_POST AS TR_KYOTEN_POST,
M_TORIHIKISAKI_KYOTEN.KYOTEN_ADDRESS1 AS TR_KYOTEN_ADDRESS1,
M_TORIHIKISAKI_KYOTEN.KYOTEN_ADDRESS2 AS TR_KYOTEN_ADDRESS2,
M_TORIHIKISAKI_KYOTEN.KYOTEN_TEL AS TR_KYOTEN_TEL,
M_TORIHIKISAKI_KYOTEN.KYOTEN_FAX AS TR_KYOTEN_FAX,

M_C.CORP_NAME,
M_C.CORP_DAIHYOU,

M_HINMEI.HINMEI_NAME

FROM
T_SHUKKA_ENTRY ENT INNER JOIN T_SHUKKA_DETAIL DET
ON ENT.SYSTEM_ID = DET.SYSTEM_ID 
AND ENT.SEQ = DET.SEQ 
LEFT JOIN T_KENSHU_DETAIL T_K_D
ON DET.SYSTEM_ID = T_K_D.SYSTEM_ID
AND DET.SEQ = T_K_D.SEQ
AND DET.DETAIL_SYSTEM_ID = T_K_D.DETAIL_SYSTEM_ID
AND DET.ROW_NO = T_K_D.ROW_NO
LEFT OUTER JOIN M_GYOUSHA
ON ENT.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD 
LEFT OUTER JOIN M_KYOTEN AS M_GYOUSHA_KYOTEN
ON M_GYOUSHA.SHIHARAI_KYOTEN_CD = M_GYOUSHA_KYOTEN.KYOTEN_CD
LEFT OUTER JOIN M_GENBA
ON ENT.GYOUSHA_CD = M_GENBA.GYOUSHA_CD 
AND ENT.GENBA_CD = M_GENBA.GENBA_CD
LEFT OUTER JOIN M_KYOTEN AS M_GENBA_KYOTEN
ON M_GENBA.SHIHARAI_KYOTEN_CD = M_GENBA_KYOTEN.KYOTEN_CD 
LEFT OUTER JOIN M_UNIT
ON T_K_D.UNIT_CD = M_UNIT.UNIT_CD 
LEFT OUTER JOIN M_KYOTEN
ON M_KYOTEN.KYOTEN_CD = ENT.KYOTEN_CD
LEFT JOIN M_TORIHIKISAKI_SHIHARAI M_T
ON M_T.TORIHIKISAKI_CD = /*SHIHARAI_CD*/
LEFT OUTER JOIN M_KYOTEN AS M_TORIHIKISAKI_KYOTEN
ON ISNULL(M_T.SHIHARAI_KYOTEN_CD,'00') = M_TORIHIKISAKI_KYOTEN.KYOTEN_CD
LEFT JOIN M_CORP_INFO M_C
ON M_C.SYS_ID = 0
LEFT JOIN M_HINMEI
ON M_HINMEI.HINMEI_CD = T_K_D.HINMEI_CD
WHERE
ENT.TORIHIKISAKI_CD = /*SHIHARAI_CD*/
/*IF SHIHARAISHIMEBI_FROM != null && SHIHARAISHIMEBI_FROM != ''*/
AND CONVERT(DateTime,/*SHIHARAISHIMEBI_FROM*/nul, 111) <= ENT.DENPYOU_DATE/*END*/
AND ENT.DENPYOU_DATE <= CONVERT(DateTime,/*SHIHARAISHIMEBI_TO*/null, 111)
AND ENT.KAKUTEI_KBN = '1' 
AND ENT.SHIHARAI_TORIHIKI_KBN_CD = '2' 
AND ENT.DELETE_FLG = 0
AND ENT.TAIRYUU_KBN = 0
AND ENT.KENSHU_MUST_KBN = 1
)
/*END*/
ORDER BY ENT.SYSTEM_ID,ENT.GYOUSHA_CD,ENT.GENBA_CD ASC