SELECT
	TMLS.ZANDAKA,
	TMAS.ZANDAKA AS CHOUSEI_ZANDAKA
FROM
	T_MONTHLY_LOCK_SH TMLS
	LEFT JOIN T_MONTHLY_ADJUST_SH TMAS
		ON TMLS.TORIHIKISAKI_CD = TMAS.TORIHIKISAKI_CD
		AND TMLS.YEAR = TMAS.YEAR
		AND TMLS.MONTH = TMAS.MONTH
		AND TMLS.SEQ = TMAS.SEQ
		AND TMAS.DELETE_FLG = 0
WHERE
	TMLS.DELETE_FLG = 0
	AND TMLS.TORIHIKISAKI_CD = /*TORIHIKISAKI_CD*/'000001'
	AND TMLS.YEAR = /*YEAR*/2015
	AND TMLS.MONTH = /*MONTH*/1