SELECT
	TMLU.ZANDAKA,
	TMAU.ZANDAKA AS CHOUSEI_ZANDAKA
FROM
	T_MONTHLY_LOCK_UR TMLU
	LEFT JOIN T_MONTHLY_ADJUST_UR TMAU
		ON TMLU.TORIHIKISAKI_CD = TMAU.TORIHIKISAKI_CD
		AND TMLU.YEAR = TMAU.YEAR
		AND TMLU.MONTH = TMAU.MONTH
		AND TMLU.SEQ = TMAU.SEQ
		AND TMAU.DELETE_FLG = 0
WHERE
	TMLU.DELETE_FLG = 0
	AND TMLU.TORIHIKISAKI_CD = /*TORIHIKISAKI_CD*/'000001'
	AND TMLU.YEAR = /*YEAR*/2015
	AND TMLU.MONTH = /*MONTH*/1