SELECT *
FROM (
  SELECT
      ROW_NUMBER() OVER(PARTITION BY MLS.TORIHIKISAKI_CD ORDER BY MLS.YEAR DESC, MLS.MONTH DESC) AS ROW_NO,
      MLS.TORIHIKISAKI_CD,
      MLS.PREVIOUS_MONTH_BALANCE,
      MLS.SHIME_UTIZEI_GAKU,
      MLS.SHIME_SOTOZEI_GAKU,
      ISNULL (MAS.ADJUST_TAX, 0) AS ADJUST_TAX,
      MLS.YEAR,
      MLS.MONTH,
      ISNULL (MAS.ZANDAKA, MLS.ZANDAKA) AS SASHIHIKI_URIAGE_ZANDAKA
  FROM
      T_MONTHLY_LOCK_SH AS MLS
      LEFT JOIN
          T_MONTHLY_ADJUST_SH AS MAS
      ON  MLS.TORIHIKISAKI_CD = MAS.TORIHIKISAKI_CD
      AND MLS.YEAR = MAS.YEAR
      AND MLS.MONTH = MAS.MONTH
      AND MLS.SEQ = MAS.SEQ
      LEFT JOIN
          M_TORIHIKISAKI_SHIHARAI AS MTS
      ON  MLS.TORIHIKISAKI_CD = MTS.TORIHIKISAKI_CD
  WHERE
      MLS.DELETE_FLG = 0
     AND (MLS.YEAR = /*year*/2014
     AND MLS.MONTH < /*month*/12
      OR MLS.YEAR < /*year*/2014)
  /*IF startCD != null && startCD != ''*/AND MLS.TORIHIKISAKI_CD >= /*startCD*/'700001'/*END*/
  /*IF endCD != null && endCD != ''*/AND MLS.TORIHIKISAKI_CD <= /*endCD*/'700001'/*END*/
  AND (
          MAS.DELETE_FLG = 0
      OR  MAS.DELETE_FLG IS NULL
      )
  AND MTS.TORIHIKI_KBN_CD = 2
  /*IF shimebi != null && shimebi != ''*/
  AND ( MTS.SHIMEBI1 = /*shimebi*/0
     OR MTS.SHIMEBI2 = /*shimebi*/0
     OR MTS.SHIMEBI3 = /*shimebi*/0
  )
  /*END*/
)DATA
WHERE DATA.ROW_NO = 1
ORDER BY DATA.TORIHIKISAKI_CD