SELECT * FROM dbo.M_SHARYOU
WHERE 
/*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
 DELETE_FLG = 0
-- ELSE
 1 = 1
/*END*/
/*IF data.GYOUSHA_CD != null*/AND GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/
/*IF data.SHARYOU_CD != null*/AND SHARYOU_CD = /*data.SHARYOU_CD*//*END*/
/*IF data.SHARYOU_NAME != null*/AND SHARYOU_NAME = /*data.SHARYOU_NAME*//*END*/
/*IF data.SHARYOU_NAME_RYAKU != null*/AND SHARYOU_NAME_RYAKU = /*data.SHARYOU_NAME_RYAKU*//*END*/
/*IF data.SHASYU_CD != null*/AND SHASYU_CD = /*data.SHASYU_CD*//*END*/
/*IF data.SHAIN_CD != null*/AND SHAIN_CD = /*data.SHAIN_CD*//*END*/
/*IF !data.SAIDAI_SEKISAI.IsNull*/AND SAIDAI_SEKISAI = /*data.SAIDAI_SEKISAI.Value*//*END*/
/*IF !data.KUUSHA_JYURYO.IsNull*/AND KUUSHA_JYURYO = /*data.KUUSHA_JYURYO.Value*//*END*/
/*IF data.SHARYOU_BIKOU != null*/AND SHARYOU_BIKOU = /*data.SHARYOU_BIKOU*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
