SELECT M_SHARYOU.GYOUSHA_CD, M_GYOUSHA.GYOUSHA_NAME_RYAKU, M_SHARYOU.SHARYOU_CD, M_SHARYOU.SHARYOU_NAME_RYAKU  
FROM dbo.M_SHARYOU AS M_SHARYOU
LEFT JOIN dbo.M_GYOUSHA AS M_GYOUSHA ON M_SHARYOU.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD 
AND M_GYOUSHA.DELETE_FLG = 0
WHERE 
M_SHARYOU.DELETE_FLG = 0
/*IF data.GYOUSHA_CD != null*/AND M_SHARYOU.GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/
/*IF data.SHARYOU_CD != null*/AND M_SHARYOU.SHARYOU_CD = /*data.SHARYOU_CD*//*END*/
/*IF data.SHARYOU_NAME != null*/AND M_SHARYOU.SHARYOU_NAME = /*data.SHARYOU_NAME*//*END*/
/*IF data.SHARYOU_NAME_RYAKU != null*/AND M_SHARYOU.SHARYOU_NAME_RYAKU = /*data.SHARYOU_NAME_RYAKU*//*END*/
/*IF data.SHASYU_CD != null*/AND M_SHARYOU.SHASYU_CD = /*data.SHASYU_CD*//*END*/
/*IF data.SHAIN_CD != null*/AND M_SHARYOU.SHAIN_CD = /*data.SHAIN_CD*//*END*/
/*IF !data.SAIDAI_SEKISAI.IsNull*/AND M_SHARYOU.SAIDAI_SEKISAI = /*data.SAIDAI_SEKISAI.Value*//*END*/
/*IF !data.KUUSHA_JYURYO.IsNull*/AND M_SHARYOU.KUUSHA_JYURYO = /*data.KUUSHA_JYURYO.Value*//*END*/
/*IF data.SHARYOU_BIKOU != null*/AND M_SHARYOU.SHARYOU_BIKOU = /*data.SHARYOU_BIKOU*//*END*/
/*IF data.CREATE_USER != null*/AND M_SHARYOU.CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND M_SHARYOU.CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND M_SHARYOU.CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND M_SHARYOU.UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND M_SHARYOU.UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND M_SHARYOU.UPDATE_PC = /*data.UPDATE_PC*//*END*/
