SELECT
MCS.DELETE_FLG,
MCS.CONTENA_SHURUI_CD,
MCS.CONTENA_SHURUI_NAME,
MCS.CONTENA_SHURUI_NAME_RYAKU,
MCS.CONTENA_SHURUI_FURIGANA,
MCS.CONTENA_SHURUI_BIKOU,
MCS.TEKIYOU_BEGIN,
MCS.TEKIYOU_END,
MCS.CREATE_USER,
MCS.CREATE_DATE,
MCS.CREATE_PC,
MCS.UPDATE_USER,
MCS.UPDATE_DATE,
MCS.UPDATE_PC
FROM 
dbo.M_CONTENA_SHURUI MCS
/*BEGIN*/WHERE
/*IF data.CONTENA_SHURUI_CD != null*/CAST(MCS.CONTENA_SHURUI_CD AS varchar(3)) LIKE '%' + CAST(/*data.CONTENA_SHURUI_CD*/0 AS varchar(3)) + '%'/*END*/
/*IF data.CONTENA_SHURUI_NAME != null && data.CONTENA_SHURUI_NAME != ''*/AND MCS.CONTENA_SHURUI_NAME LIKE '%' +  /*data.CONTENA_SHURUI_NAME*/ + '%'/*END*/
/*IF data.CONTENA_SHURUI_NAME_RYAKU != null && data.CONTENA_SHURUI_NAME_RYAKU != ''*/AND MCS.CONTENA_SHURUI_NAME_RYAKU LIKE '%' +  /*data.CONTENA_SHURUI_NAME_RYAKU*/ + '%'/*END*/
/*IF data.CONTENA_SHURUI_BIKOU != null && data.CONTENA_SHURUI_BIKOU != ''*/AND MCS.CONTENA_SHURUI_BIKOU LIKE '%' +  /*data.CONTENA_SHURUI_BIKOU*/ + '%'/*END*/
/*IF !data.TEKIYOU_BEGIN.IsNull*/AND MCS.TEKIYOU_BEGIN LIKE '%' +  /*data.TEKIYOU_BEGIN.Value*/ + '%'/*END*/
/*IF !data.TEKIYOU_END.IsNull*/AND MCS.TEKIYOU_END LIKE '%' +  /*data.TEKIYOU_END.Value*/ + '%'/*END*/
/*IF data.CREATE_USER != null && data.CREATE_USER != ''*/AND MCS.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, MCS.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
/*IF data.UPDATE_USER != null && data.UPDATE_USER != ''*/AND MCS.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, MCS.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*IF data.SEARCH_TEKIYOU_BEGIN != null*/AND CONVERT(nvarchar, MCS.TEKIYOU_BEGIN, 120) LIKE '%' +  /*data.SEARCH_TEKIYOU_BEGIN*/ + '%'/*END*/
/*IF data.SEARCH_TEKIYOU_END != null*/AND CONVERT(nvarchar, MCS.TEKIYOU_END, 120) LIKE '%' +  /*data.SEARCH_TEKIYOU_END*/ + '%'/*END*/
/*END*/
ORDER BY MCS.CONTENA_SHURUI_CD
