SELECT DISTINCT N'取引先マスタ' AS NAME  FROM M_TORIHIKISAKI WHERE EIGYOU_TANTOU_BUSHO_CD IN /*BUSHO_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'業者マスタ' AS NAME  FROM M_GYOUSHA WHERE EIGYOU_TANTOU_BUSHO_CD IN /*BUSHO_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'現場マスタ' AS NAME  FROM M_GENBA WHERE EIGYOU_TANTOU_BUSHO_CD IN /*BUSHO_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'引合取引先マスタ' AS NAME  FROM M_HIKIAI_TORIHIKISAKI WHERE EIGYOU_TANTOU_BUSHO_CD IN /*BUSHO_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'引合業者マスタ' AS NAME  FROM M_HIKIAI_GYOUSHA WHERE EIGYOU_TANTOU_BUSHO_CD IN /*BUSHO_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'引合現場マスタ' AS NAME  FROM M_HIKIAI_GENBA WHERE EIGYOU_TANTOU_BUSHO_CD IN /*BUSHO_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'社員マスタ' AS NAME FROM M_SHAIN WHERE BUSHO_CD IN /*BUSHO_CD*/('') AND DELETE_FLG = 'False'
