SELECT
COUNT(*)
FROM
T_SEISAN_DENPYOU
/*BEGIN*/WHERE
/*IF !deletechuFlg*/DELETE_FLG = 0/*END*/
/*IF data.SHIHARAISHIMEBI_TO != null && data.SHIHARAISHIMEBI_TO != ""*/
 AND CONVERT(DATETIME, SEISAN_DATE,111) > CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_TO*/null,111)/*END*/
 AND TORIHIKISAKI_CD = /*data.SHIHARAI_CD*/
/*END*/