SELECT T_SEISAN_DENPYOU.SEISAN_NUMBER
FROM   T_SEISAN_DENPYOU
       LEFT JOIN T_SEISAN_DENPYOU_INXS
              ON T_SEISAN_DENPYOU_INXS.SEISAN_NUMBER = T_SEISAN_DENPYOU.SEISAN_NUMBER
       LEFT JOIN M_TORIHIKISAKI_SHIHARAI
              ON T_SEISAN_DENPYOU.TORIHIKISAKI_CD = M_TORIHIKISAKI_SHIHARAI.TORIHIKISAKI_CD
WHERE  T_SEISAN_DENPYOU.DELETE_FLG = 0
       AND M_TORIHIKISAKI_SHIHARAI.INXS_SHIHARAI_KBN = 1
       AND T_SEISAN_DENPYOU_INXS.UPLOAD_STATUS IN ( 2, 5 ) 
	   AND T_SEISAN_DENPYOU.SEISAN_NUMBER =  /*seisanNumber*/