SELECT
	/*IF data.DENPYO_SHURUI == 2*/ENT.UKEIRE_NUMBER AS DENPYOU_NUMBER, /*END*/
	/*IF data.DENPYO_SHURUI == 3*/ENT.SHUKKA_NUMBER AS DENPYOU_NUMBER, /*END*/
	/*IF data.DENPYO_SHURUI == 4*/ENT.UR_SH_NUMBER AS DENPYOU_NUMBER, /*END*/
	ENT.DENPYOU_DATE, 
	/*IF data.DENPYO_SHURUI != 3*/
		ENT.SHIHARAI_DATE AS SEISAN_SHIMEBI,
	/*END*/
	/*IF data.DENPYO_SHURUI == 3*/
	CASE WHEN ENT.KENSHU_MUST_KBN = 1
	THEN
		ENT.KENSHU_SHIHARAI_DATE
	ELSE
		ENT.SHIHARAI_DATE
	END
	AS SEISAN_SHIMEBI,
	/*END*/
	ENT.SHIHARAI_ZEI_KEISAN_KBN_CD,
	ENT.GYOUSHA_NAME, 
	ENT.GENBA_NAME, 
	/*IF data.DENPYO_SHURUI == 2*/
	(ISNULL(ENT.SHIHARAI_KINGAKU_TOTAL, 0) + ISNULL(ENT.HINMEI_SHIHARAI_KINGAKU_TOTAL, 0)) AS KINGAKU
	/*END*/
	/*IF data.DENPYO_SHURUI == 3*/
	CASE WHEN ENT.KENSHU_MUST_KBN = 1
	THEN
		(ISNULL(ENT.KENSHU_SHIHARAI_AMOUNT_TOTAL, 0) + ISNULL(ENT.KENSHU_HINMEI_SHIHARAI_KINGAKU_TOTAL, 0))
	ELSE
		(ISNULL(ENT.SHIHARAI_AMOUNT_TOTAL, 0) + ISNULL(ENT.HINMEI_SHIHARAI_KINGAKU_TOTAL, 0))
	END
	AS KINGAKU
	/*END*/
	/*IF data.DENPYO_SHURUI == 4*/
	(ISNULL(ENT.SHIHARAI_AMOUNT_TOTAL, 0) + ISNULL(ENT.HINMEI_SHIHARAI_KINGAKU_TOTAL, 0)) AS KINGAKU
	/*END*/
	,ISNULL(HIN_COUNT.HIN_SOTO,0) AS HINMEI_SOTO_ZEI_COUNT
	,ISNULL(HIN_COUNT.HIN_NASI,0) AS HINMEI_NASI_ZEI_COUNT
	,ENT.SHIHARAI_ZEI_KBN_CD
FROM
    /*IF data.DENPYO_SHURUI == 2*/T_UKEIRE_ENTRY AS ENT/*END*/
    /*IF data.DENPYO_SHURUI == 3*/T_SHUKKA_ENTRY AS ENT/*END*/
    /*IF data.DENPYO_SHURUI == 4*/T_UR_SH_ENTRY AS ENT/*END*/
LEFT JOIN
	(
		SELECT 
			COUNT_TABLE.SYSTEM_ID, COUNT(COUNT_TABLE.SOTO) AS HIN_SOTO, COUNT(COUNT_TABLE.NASI) AS HIN_NASI
		FROM (
			SELECT
				E.SYSTEM_ID,
				CASE WHEN HINMEI_ZEI_KBN_CD = 1 THEN COUNT(HINMEI_ZEI_KBN_CD) END AS SOTO,
				CASE WHEN HINMEI_ZEI_KBN_CD is null THEN COUNT(HINMEI_ZEI_KBN_CD) END AS NASI
			FROM
				/*IF data.DENPYO_SHURUI == 2*/T_UKEIRE_ENTRY E INNER JOIN T_UKEIRE_DETAIL D/*END*/
				/*IF data.DENPYO_SHURUI == 3*/T_SHUKKA_ENTRY E INNER JOIN T_SHUKKA_DETAIL D/*END*/
				/*IF data.DENPYO_SHURUI == 4*/T_UR_SH_ENTRY E INNER JOIN T_UR_SH_DETAIL D/*END*/
			ON E.SYSTEM_ID = D.SYSTEM_ID
				AND E.SEQ = D.SEQ 
				/*IF data.KYOTEN_CD != 99*/AND E.KYOTEN_CD = /*data.KYOTEN_CD*//*END*/ 		
				AND E.SHIHARAI_TORIHIKI_KBN_CD = 2 
				AND E.KAKUTEI_KBN = 1 
				/*IF data.DENPYO_SHURUI == 2 || data.DENPYO_SHURUI == 3*/
				AND E.TAIRYUU_KBN = 0
				/*END*/
				AND D.DENPYOU_KBN_CD = 2
				/*IF !deletechuFlg*/AND E.DELETE_FLG = 0/*END*/
				/*IF data.SHIHARAI_CD != null && data.SHIHARAI_CD != ""*/AND E.TORIHIKISAKI_CD = /*data.SHIHARAI_CD*//*END*/ 
				/*IF data.SHIHARAISHIMEBI_FROM != null && data.SHIHARAISHIMEBI_FROM != ""*/
					AND CONVERT(DATETIME, E.SHIHARAI_DATE,111) >= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_FROM*/null,111)
				/*END*/
				/*IF data.SHIHARAISHIMEBI_TO != null && data.SHIHARAISHIMEBI_TO != ""*/
					AND CONVERT(DATETIME, E.SHIHARAI_DATE,111) <= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_TO*/null,111)
				/*END*/
			/*IF data.DENPYO_SHURUI == 3*/
			WHERE (E.KENSHU_MUST_KBN != 1 OR E.KENSHU_MUST_KBN IS NULL)
			/*END*/
				GROUP BY E.SYSTEM_ID,HINMEI_ZEI_KBN_CD
			/*IF data.DENPYO_SHURUI == 3*/
			UNION ALL (
				SELECT
					E.SYSTEM_ID,
					CASE WHEN KD.HINMEI_ZEI_KBN_CD = 1 THEN COUNT(KD.HINMEI_ZEI_KBN_CD) END AS SOTO,
					CASE WHEN KD.HINMEI_ZEI_KBN_CD is null THEN COUNT(KD.HINMEI_ZEI_KBN_CD) END AS NASI
				FROM
					T_SHUKKA_ENTRY E INNER JOIN T_SHUKKA_DETAIL D
				ON E.SYSTEM_ID = D.SYSTEM_ID
					AND E.SEQ = D.SEQ 
					/*IF data.KYOTEN_CD != 99*/AND E.KYOTEN_CD = /*data.KYOTEN_CD*//*END*/ 		
					AND E.SHIHARAI_TORIHIKI_KBN_CD = 2 
					AND E.KAKUTEI_KBN = 1 
					AND E.TAIRYUU_KBN = 0
					AND D.DENPYOU_KBN_CD = 2
					/*IF !deletechuFlg*/AND E.DELETE_FLG = 0/*END*/
					/*IF data.SHIHARAI_CD != null && data.SHIHARAI_CD != ""*/AND E.TORIHIKISAKI_CD = /*data.SHIHARAI_CD*//*END*/ 
				LEFT JOIN T_KENSHU_DETAIL KD
				ON KD.SYSTEM_ID = D.SYSTEM_ID 
					AND KD.SEQ = D.SEQ 
					AND KD.DETAIL_SYSTEM_ID = D.DETAIL_SYSTEM_ID
					AND KD.ROW_NO = D.ROW_NO
					AND KD.DENPYOU_KBN_CD = 2
				WHERE E.KENSHU_MUST_KBN = 1
					/*IF data.SHIHARAISHIMEBI_FROM != null && data.SHIHARAISHIMEBI_FROM != ""*/
						AND CONVERT(DATETIME, E.KENSHU_SHIHARAI_DATE,111) >= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_FROM*/null,111)
					/*END*/
					/*IF data.SHIHARAISHIMEBI_TO != null && data.SHIHARAISHIMEBI_TO != ""*/
						AND CONVERT(DATETIME, E.KENSHU_SHIHARAI_DATE,111) <= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_TO*/null,111)
					/*END*/
				GROUP BY E.SYSTEM_ID, KD.HINMEI_ZEI_KBN_CD
			)
			/*END*/
		) AS COUNT_TABLE
		GROUP BY COUNT_TABLE.SYSTEM_ID
	) AS HIN_COUNT
	ON ENT.SYSTEM_ID = HIN_COUNT.SYSTEM_ID
WHERE
	(EXISTS
		(
		SELECT
			DISTINCT E.SYSTEM_ID
		FROM
			/*IF data.DENPYO_SHURUI == 2*/T_UKEIRE_ENTRY E INNER JOIN T_UKEIRE_DETAIL D/*END*/
			/*IF data.DENPYO_SHURUI == 3*/T_SHUKKA_ENTRY E INNER JOIN T_SHUKKA_DETAIL D/*END*/
			/*IF data.DENPYO_SHURUI == 4*/T_UR_SH_ENTRY E INNER JOIN T_UR_SH_DETAIL D/*END*/
		ON E.SYSTEM_ID = D.SYSTEM_ID
			AND E.SEQ = D.SEQ 
	        /*IF data.KYOTEN_CD != 99*/AND E.KYOTEN_CD = /*data.KYOTEN_CD*//*END*/ 		
			AND E.SHIHARAI_TORIHIKI_KBN_CD = 2 
			AND E.KAKUTEI_KBN = 1 
			/*IF data.DENPYO_SHURUI == 2 || data.DENPYO_SHURUI == 3*/
			AND E.TAIRYUU_KBN = 0
			/*END*/
			AND D.DENPYOU_KBN_CD = 2
			/*IF !deletechuFlg*/AND E.DELETE_FLG = 0/*END*/
			/*IF data.SHIHARAI_CD != null && data.SHIHARAI_CD != ""*/AND E.TORIHIKISAKI_CD = /*data.SHIHARAI_CD*//*END*/ 
			/*IF data.SHIHARAISHIMEBI_FROM != null && data.SHIHARAISHIMEBI_FROM != ""*/
				AND CONVERT(DATETIME, E.SHIHARAI_DATE,111) >= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_FROM*/null,111)
			/*END*/
			/*IF data.SHIHARAISHIMEBI_TO != null && data.SHIHARAISHIMEBI_TO != ""*/
				AND CONVERT(DATETIME, E.SHIHARAI_DATE,111) <= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_TO*/null,111)
			/*END*/
		WHERE ENT.SYSTEM_ID = E.SYSTEM_ID
		/*IF data.DENPYO_SHURUI == 3*/
		AND (E.KENSHU_MUST_KBN != 1 OR E.KENSHU_MUST_KBN IS NULL)
		UNION ALL (
			SELECT
				DISTINCT E.SYSTEM_ID
			FROM
				T_SHUKKA_ENTRY E INNER JOIN T_SHUKKA_DETAIL D
			ON E.SYSTEM_ID = D.SYSTEM_ID
				AND E.SEQ = D.SEQ 
				/*IF data.KYOTEN_CD != 99*/AND E.KYOTEN_CD = /*data.KYOTEN_CD*//*END*/ 		
				AND E.SHIHARAI_TORIHIKI_KBN_CD = 2 
				AND E.KAKUTEI_KBN = 1 
				AND E.TAIRYUU_KBN = 0
				AND D.DENPYOU_KBN_CD = 2
				/*IF !deletechuFlg*/AND E.DELETE_FLG = 0/*END*/
				/*IF data.SHIHARAI_CD != null && data.SHIHARAI_CD != ""*/AND E.TORIHIKISAKI_CD = /*data.SHIHARAI_CD*//*END*/ 
			LEFT JOIN T_KENSHU_DETAIL KD
			ON KD.SYSTEM_ID = D.SYSTEM_ID 
				AND KD.SEQ = D.SEQ 
				AND KD.DETAIL_SYSTEM_ID = D.DETAIL_SYSTEM_ID
				AND KD.ROW_NO = D.ROW_NO
				AND KD.DENPYOU_KBN_CD = 2
			WHERE ENT.SYSTEM_ID = E.SYSTEM_ID
				AND E.KENSHU_MUST_KBN = 1
				/*IF data.SHIHARAISHIMEBI_FROM != null && data.SHIHARAISHIMEBI_FROM != ""*/
				  AND CONVERT(DATETIME, E.KENSHU_SHIHARAI_DATE,111) >= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_FROM*/null,111)
				/*END*/
			   /*IF data.SHIHARAISHIMEBI_TO != null && data.SHIHARAISHIMEBI_TO != ""*/
				  AND CONVERT(DATETIME, E.KENSHU_SHIHARAI_DATE,111) <= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_TO*/null,111)
				/*END*/
		)
		/*END*/
		)
	)
	AND (NOT EXISTS
		(
		SELECT
			ENT.SYSTEM_ID, ENT.SEQ
		FROM              
			T_SEISAN_DETAIL SEID
		WHERE
			ENT.SYSTEM_ID = SEID.DENPYOU_SYSTEM_ID
			AND ENT.SEQ = SEID.DENPYOU_SEQ
			/*IF data.DENPYO_SHURUI == 2*/AND SEID.DENPYOU_SHURUI_CD = '1'/*END*/
			/*IF data.DENPYO_SHURUI == 3*/AND SEID.DENPYOU_SHURUI_CD = '2'/*END*/
			/*IF data.DENPYO_SHURUI == 4*/AND SEID.DENPYOU_SHURUI_CD = '3'/*END*/
			AND SEID.DELETE_FLG = 0
		)
		)
	/*IF !deletechuFlg*/AND ENT.DELETE_FLG = 0/*END*/
