SELECT
	TE.SHUKKIN_NUMBER AS DENPYOU_NUMBER, 
	TE.DENPYOU_DATE, 
	'' AS SHIHARAI_ZEI_KEISAN_KBN_CD,
	NULL AS SEISAN_SHIMEBI, 
	NULL AS GYOUSHA_NAME, 
	NULL AS GENBA_NAME, 
	(ISNULL(TE.SHUKKIN_AMOUNT_TOTAL, 0) + ISNULL(TE.CHOUSEI_AMOUNT_TOTAL, 0)) AS KINGAKU,
	0 AS HINMEI_SOTO_ZEI_COUNT,
	0 AS HINMEI_NASI_ZEI_COUNT,
	0 AS SHIHARAI_ZEI_KBN_CD
FROM
	T_SHUKKIN_ENTRY TE
WHERE
TE.DELETE_FLG = 0
/*IF data.KYOTEN_CD != 99*/
AND TE.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/ 		
/*IF data.SHIHARAI_CD != null && data.SHIHARAI_CD != ""*/
AND TE.TORIHIKISAKI_CD = /*data.SHIHARAI_CD*/
/*END*/ 
/*IF data.SHIHARAISHIMEBI_FROM != null && data.SHIHARAISHIMEBI_FROM != ""*/
AND CONVERT(DATETIME, TE.DENPYOU_DATE,111) >= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_FROM*/null,111)
/*END*/ 
/*IF data.SHIHARAISHIMEBI_TO != null && data.SHIHARAISHIMEBI_TO != ""*/
AND CONVERT(DATETIME, TE.DENPYOU_DATE,111) <= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_TO*/,111)
/*END*/ 
AND (NOT EXISTS
	(
	SELECT 1
	FROM              
	    T_SEISAN_DETAIL SEID
	WHERE
	    TE.SYSTEM_ID = SEID.DENPYOU_SYSTEM_ID
	    AND TE.SEQ = SEID.DENPYOU_SEQ
	    AND SEID.DENPYOU_SHURUI_CD = 20
	    AND SEID.DELETE_FLG = 0
	)
	)

ORDER BY 
	TE.DENPYOU_DATE,
	TE.SHUKKIN_NUMBER
		