SELECT SD.SEISAN_NUMBER
FROM T_SEISAN_DENPYOU AS SD
LEFT JOIN T_SHIME_JIKKOU_RIREKI AS SJR
ON SD.SHIME_JIKKOU_NO = SJR.SHIME_JIKKOU_NO
WHERE
SD.DELETE_FLG = 0
AND SD.TORIHIKISAKI_CD = /*data.SHIHARAI_CD*/
AND SJR.DENPYOU_SHURUI = /*data.DENPYOU_SHURUI_CD*/
AND SJR.SHORI_KBN = '2'
AND SJR.KYOTEN_CD = /*data.KYOTEN_CD*/
AND SJR.SHIMEBI = /*data.SHIMEBI*/
/*IF data.SHIHARAISHIMEBI_FROM != null*/
AND SJR.HIDUKE_HANI_BEGIN = /*data.SHIHARAISHIMEBI_FROM*/
AND SJR.HIDUKE_HANI_END = /*data.SHIHARAISHIMEBI_TO*/
--ELSE
AND SJR.HIDUKE_HANI_BEGIN IS NULL
AND SJR.HIDUKE_HANI_END = /*data.SHIHARAISHIMEBI_TO*/
/*END*/