SELECT
SHIHARAI_MONTH,
SHIHARAI_DAY,
ISNULL(SHIHARAI_BETSU_KBN, 0) AS SHIHARAI_BETSU_KBN,
ISNULL(SHIHARAI_BETSU_NICHIGO, 0) AS SHIHARAI_BETSU_NICHIGO
FROM
M_TORIHIKISAKI_SHIHARAI
/*BEGIN*/WHERE
/*IF data.TORIHIKISAKI_CD != null */
TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*//*END*/
/*END*/