SELECT
MST.TORIHIKISAKI_CD AS SHIHARAI_CD,
MST.TORIHIKISAKI_NAME_RYAKU AS SHIHARAI_NAME,
TS.SHIMEBI1 AS SHIMEBI1,
TS.SHIMEBI2 AS SHIMEBI2,
TS.SHIMEBI3 AS SHIMEBI3,
MST.TORIHIKISAKI_ADDRESS1 AS ADDRESS1,
MST.TORIHIKISAKI_ADDRESS2 AS ADDRESS2,
MST.TORIHIKISAKI_TEL AS TEL,
MST.TORIHIKISAKI_FAX AS FAX
FROM
M_TORIHIKISAKI MST
LEFT OUTER JOIN M_TORIHIKISAKI_SHIHARAI TS ON MST.TORIHIKISAKI_CD = TS.TORIHIKISAKI_CD
LEFT JOIN (
     SELECT UKEIRE.TORIHIKISAKI_CD
     FROM T_UKEIRE_ENTRY UKEIRE
     WHERE NOT EXISTS(
              SELECT 1 FROM T_SEISAN_DETAIL DETAIL
              WHERE DETAIL.DENPYOU_SHURUI_CD = 1         
              AND DETAIL.DENPYOU_SYSTEM_ID = UKEIRE.SYSTEM_ID         
              AND DETAIL.DENPYOU_SEQ = UKEIRE.SEQ       
              AND DETAIL.DELETE_FLG = 0)     
           AND UKEIRE.DELETE_FLG = 0
     UNION
     SELECT SHUKKA.TORIHIKISAKI_CD FROM T_SHUKKA_ENTRY SHUKKA
     WHERE NOT EXISTS(
              SELECT 1 FROM T_SEISAN_DETAIL DETAIL
              WHERE DETAIL.DENPYOU_SHURUI_CD = 1
              AND DETAIL.DENPYOU_SYSTEM_ID = SHUKKA.SYSTEM_ID
              AND DETAIL.DENPYOU_SEQ = SHUKKA.SEQ
              AND DETAIL.DELETE_FLG = 0)
           AND SHUKKA.DELETE_FLG = 0
     UNION
     SELECT URSH.TORIHIKISAKI_CD FROM T_UR_SH_ENTRY URSH
     WHERE NOT EXISTS(
              SELECT 1 FROM T_SEISAN_DETAIL DETAIL
              WHERE DETAIL.DENPYOU_SHURUI_CD = 1
              AND DETAIL.DENPYOU_SYSTEM_ID = URSH.SYSTEM_ID
              AND DETAIL.DENPYOU_SEQ = URSH.SEQ
              AND DETAIL.DELETE_FLG = 0)
           AND URSH.DELETE_FLG = 0) AS DENPYOU 
ON DENPYOU.TORIHIKISAKI_CD = MST.TORIHIKISAKI_CD 
LEFT JOIN T_SEISAN_DENPYOU 
ON MST.TORIHIKISAKI_CD = T_SEISAN_DENPYOU.TORIHIKISAKI_CD 
AND T_SEISAN_DENPYOU.DELETE_FLG = 0 
AND SEISAN_NUMBER = (select max(SEISAN_NUMBER) from T_SEISAN_DENPYOU tmp where tmp.TORIHIKISAKI_CD = MST.TORIHIKISAKI_CD) 
WHERE
/*IF data.SHIHARAISHIMEBI_TO == null*/
((((MST.TEKIYOU_BEGIN <= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_FROM*/, 120) AND CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_FROM*/, 120) <= MST.TEKIYOU_END) 
    OR (MST.TEKIYOU_BEGIN <= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_FROM*/, 120) AND MST.TEKIYOU_END IS NULL) 
    OR (MST.TEKIYOU_BEGIN IS NULL AND CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_FROM*/, 120) <= MST.TEKIYOU_END) 
    OR (MST.TEKIYOU_BEGIN IS NULL AND MST.TEKIYOU_END IS NULL)) AND MST.DELETE_FLG = 0)
  OR DENPYOU.TORIHIKISAKI_CD IS NOT NULL    
  OR T_SEISAN_DENPYOU.KONKAI_SEISAN_GAKU != 0    
  OR (T_SEISAN_DENPYOU.KONKAI_SEISAN_GAKU IS NOT NULL AND TS.KAISHI_KAIKAKE_ZANDAKA != 0))
-- ELSE
(
    (
        (
            (
                CONVERT(DATETIME ,/*data.SHIHARAISHIMEBI_FROM*/,120) <= MST.TEKIYOU_BEGIN
            AND MST.TEKIYOU_BEGIN <= CONVERT(DATETIME ,/*data.SHIHARAISHIMEBI_TO*/,120)
            )
        OR  (
                MST.TEKIYOU_END IS NOT NULL
            AND CONVERT(DATETIME ,/*data.SHIHARAISHIMEBI_FROM*/,120) <= MST.TEKIYOU_BEGIN
            AND MST.TEKIYOU_BEGIN <= CONVERT(DATETIME ,/*data.SHIHARAISHIMEBI_TO*/,120)
            )
        )
    OR  (
            (
                MST.TEKIYOU_BEGIN <= CONVERT(DATETIME ,/*data.SHIHARAISHIMEBI_FROM*/,120)
            AND CONVERT(DATETIME ,/*data.SHIHARAISHIMEBI_FROM*/,120) <= MST.TEKIYOU_END
            )
        OR  (
                MST.TEKIYOU_BEGIN <= CONVERT(DATETIME ,/*data.SHIHARAISHIMEBI_FROM*/,120)
            AND MST.TEKIYOU_END IS NULL
            )
        OR  (
                MST.TEKIYOU_BEGIN IS NULL
            AND CONVERT(DATETIME ,/*data.SHIHARAISHIMEBI_FROM*/,120) <= MST.TEKIYOU_END
            )
        OR  (
                MST.TEKIYOU_BEGIN IS NULL
            AND MST.TEKIYOU_END IS NULL
            )
        )
    OR  (
            (
                MST.TEKIYOU_BEGIN <= CONVERT(DATETIME ,/*data.SHIHARAISHIMEBI_TO*/,120)
            AND CONVERT(DATETIME ,/*data.SHIHARAISHIMEBI_TO*/,120) <= MST.TEKIYOU_END
            )
        OR  (
                MST.TEKIYOU_BEGIN <= CONVERT(DATETIME ,/*data.SHIHARAISHIMEBI_TO*/,120)
            AND MST.TEKIYOU_END IS NULL
            )
        OR  (
                MST.TEKIYOU_BEGIN IS NULL
            AND CONVERT(DATETIME ,/*data.SHIHARAISHIMEBI_TO*/,120) <= MST.TEKIYOU_END
            )
        OR  (
                MST.TEKIYOU_BEGIN IS NULL AND MST.TEKIYOU_END IS NULL
            )
        )
    )
AND MST.DELETE_FLG = 0
)
/*END*/

/*IF data.SHIHARAI_CD != null && data.SHIHARAI_CD != ''*/
AND MST.TORIHIKISAKI_CD = /*data.SHIHARAI_CD*/
/*END*/
/*IF data.KYOTEN_CD != 99*/ AND (MST.TORIHIKISAKI_KYOTEN_CD = 99 or MST.TORIHIKISAKI_KYOTEN_CD = /*data.KYOTEN_CD*/) /*END*/
/*IF data.SHIMEBI != null */ 
 AND ( TS.SHIMEBI1 = /*data.SHIMEBI*/ 
 OR TS.SHIMEBI2 = /*data.SHIMEBI*/ 
 OR TS.SHIMEBI3 = /*data.SHIMEBI*/ ) /*END*/
ORDER BY MST.TORIHIKISAKI_CD