SELECT
M_T.TORIHIKISAKI_CD,
M_T.SHOSHIKI_KBN,
M_T.SHOSHIKI_MEISAI_KBN,
M_T.SHOSHIKI_GENBA_KBN,
M_T.SHIHARAI_KEITAI_KBN,
M_T.SHUKKIN_MEISAI_KBN,
M_T.YOUSHI_KBN,
M_T.KAISHI_KAIKAKE_ZANDAKA,
M_T.TAX_HASUU_CD,
M_T.SHIHARAI_SOUFU_NAME1,
M_T.SHIHARAI_SOUFU_NAME2,
M_T.SHIHARAI_SOUFU_KEISHOU1,
M_T.SHIHARAI_SOUFU_KEISHOU2,
M_T.SHIHARAI_SOUFU_POST,
M_T.SHIHARAI_SOUFU_ADDRESS1,
M_T.SHIHARAI_SOUFU_ADDRESS2,
M_T.SHIHARAI_KYOTEN_PRINT_KBN,
M_T.SHIHARAI_KYOTEN_CD,
M_T.SHIHARAI_SOUFU_BUSHO,
M_T.SHIHARAI_SOUFU_TANTOU,
M_T.SHIHARAI_SOUFU_TEL,
M_T.SHIHARAI_SOUFU_FAX,

M_K.KYOTEN_NAME AS SEIKYUU_KYOTEN_NAME,
M_K.KYOTEN_DAIHYOU AS SEIKYUU_KYOTEN_DAIHYOU,
M_K.KYOTEN_POST AS SEIKYUU_KYOTEN_POST,
M_K.KYOTEN_ADDRESS1 AS SEIKYUU_KYOTEN_ADDRESS1,
M_K.KYOTEN_ADDRESS2 AS SEIKYUU_KYOTEN_ADDRESS2,
M_K.KYOTEN_TEL AS SEIKYUU_KYOTEN_TEL,
M_K.KYOTEN_FAX AS SEIKYUU_KYOTEN_FAX

FROM
M_TORIHIKISAKI_SHIHARAI M_T
LEFT OUTER JOIN M_KYOTEN M_K
ON ISNULL(M_T.SHIHARAI_KYOTEN_CD,'00') = M_K.KYOTEN_CD

WHERE
TORIHIKISAKI_CD = /*data.SHIHARAI_CD*/