UPDATE T_SEISAN_DENPYOU SET DELETE_FLG = /*deleteFlg*/ WHERE SEISAN_NUMBER = /*seisanNumber*/ 

UPDATE T_SEISAN_DENPYOU_KAGAMI SET DELETE_FLG = /*deleteFlg*/ WHERE SEISAN_NUMBER = /*seisanNumber*/ 

UPDATE T_SEISAN_DETAIL SET DELETE_FLG = /*deleteFlg*/ WHERE SEISAN_NUMBER = /*seisanNumber*/ 
