SELECT
SMSR.SYSTEM_ID,
SMSR.RENKEI_FLG,
SMSR.DELETE_FLG,
SMSR.MOBILE_PHONE_NUMBER,
SMSR.RECEIVER_NAME,
SMSR.BIKOU,
SMSR.UPDATE_USER,
SMSR.UPDATE_DATE,
SMSR.UPDATE_PC,
SMSR.CREATE_USER,
SMSR.CREATE_DATE,
SMSR.CREATE_PC,
SMSR.TIME_STAMP
FROM 
dbo.M_SMS_RECEIVER SMSR
/*BEGIN*/WHERE
/*IF data.MOBILE_PHONE_NUMBER != null && data.MOBILE_PHONE_NUMBER != ''*/AND SMSR.MOBILE_PHONE_NUMBER LIKE '%' + /*data.MOBILE_PHONE_NUMBER*/ + '%'/*END*/
/*IF data.CREATE_USER != null*/AND SMSR.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, SMSR.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
/*IF data.UPDATE_USER != null*/AND SMSR.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, SMSR.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/

/*IF !deletechuFlg */AND SMSR.DELETE_FLG = 0/*END*/
/*END*/

ORDER BY SMSR.MOBILE_PHONE_NUMBER
