SELECT
	MOP.SYSTEM_ID AS SYSTEM_ID_MOP,
	MOP.SEQ AS SEQ_MOP,
	MOP.OUTPUT_KBN,
	MOP.PATTERN_NAME,
	MOP.DELETE_FLG,
	CAST(MOP.TIME_STAMP AS int) AS TIME_STAMP_MOP,
	MOPK.SYSTEM_ID AS SYSTEM_ID_MOPK,
	MOPK.SEQ AS SEQ_MOPK,
	MOPK.SHAIN_CD,
	CAST(MOPK.TIME_STAMP AS int) AS TIME_STAMP_MOPK,
	ISNULL(MOPK.DEFAULT_KBN,'FALSE') AS DEFAULT_KBN,
	MOPK.DISP_NUMBER
FROM
	M_OUTPUT_PATTERN_HIMO MOP
	LEFT OUTER JOIN
	(
	SELECT
		SYSTEM_ID,
		SEQ,
		SHAIN_CD,
		TIME_STAMP,
		DEFAULT_KBN,
		DISP_NUMBER,
		DELETE_FLG
	FROM
		M_OUTPUT_PATTERN_KOBETSU_HIMO
	WHERE
		SHAIN_CD = /*data.Shain_Cd*/null
		AND DELETE_FLG = 0
	) AS MOPK
	ON  MOP.SYSTEM_ID = MOPK.SYSTEM_ID
/*BEGIN*/
WHERE
	/*IF !deletechuFlg*/ MOP.DELETE_FLG = 0/*END*/
	/*IF data.Patern_Name != null && data.Patern_Name != ''*/
	AND (MOP.PATTERN_NAME LIKE '%' + /*data.Patern_Name*/ + '%'
		 or MOPK.DELETE_FLG = 0)/*END*/
/*END*/
ORDER BY 
	MOP.PATTERN_NAME, MOPK.DISP_NUMBER