//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shougun.Core.PaperManifest.HenkyakuIchiran.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string SET_MANIFESUTO {
            get {
                return ((string)(this["SET_MANIFESUTO"]));
            }
            set {
                this["SET_MANIFESUTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string SET_HIDSUKE {
            get {
                return ((string)(this["SET_HIDSUKE"]));
            }
            set {
                this["SET_HIDSUKE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string SET_HENCYAKU {
            get {
                return ((string)(this["SET_HENCYAKU"]));
            }
            set {
                this["SET_HENCYAKU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HIDUKE_TO {
            get {
                return ((string)(this["SET_HIDUKE_TO"]));
            }
            set {
                this["SET_HIDUKE_TO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HIDUKE_FROM {
            get {
                return ((string)(this["SET_HIDUKE_FROM"]));
            }
            set {
                this["SET_HIDUKE_FROM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HAISHUTSUJIGYOUSYA_CD {
            get {
                return ((string)(this["SET_HAISHUTSUJIGYOUSYA_CD"]));
            }
            set {
                this["SET_HAISHUTSUJIGYOUSYA_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_KOUFUBANNGO {
            get {
                return ((string)(this["SET_KOUFUBANNGO"]));
            }
            set {
                this["SET_KOUFUBANNGO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string SET_HITSUKEIKATSU {
            get {
                return ((string)(this["SET_HITSUKEIKATSU"]));
            }
            set {
                this["SET_HITSUKEIKATSU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HAISHUTSUJIGYOUSYAJOU_CD {
            get {
                return ((string)(this["SET_HAISHUTSUJIGYOUSYAJOU_CD"]));
            }
            set {
                this["SET_HAISHUTSUJIGYOUSYAJOU_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HAISHUTSUJIGYOUSYAJOU_NAME {
            get {
                return ((string)(this["SET_HAISHUTSUJIGYOUSYAJOU_NAME"]));
            }
            set {
                this["SET_HAISHUTSUJIGYOUSYAJOU_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HENSOUSAKI_TORIHIKISAKI_CD {
            get {
                return ((string)(this["SET_HENSOUSAKI_TORIHIKISAKI_CD"]));
            }
            set {
                this["SET_HENSOUSAKI_TORIHIKISAKI_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HENSOUSAKI_TORIHIKISAKI_NAME {
            get {
                return ((string)(this["SET_HENSOUSAKI_TORIHIKISAKI_NAME"]));
            }
            set {
                this["SET_HENSOUSAKI_TORIHIKISAKI_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HENSOUSAKI_GYOUSYA_CD {
            get {
                return ((string)(this["SET_HENSOUSAKI_GYOUSYA_CD"]));
            }
            set {
                this["SET_HENSOUSAKI_GYOUSYA_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HENSOUSAKI_GYOUSYA_NAME {
            get {
                return ((string)(this["SET_HENSOUSAKI_GYOUSYA_NAME"]));
            }
            set {
                this["SET_HENSOUSAKI_GYOUSYA_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HENSOUSAKI_GENBA_CD {
            get {
                return ((string)(this["SET_HENSOUSAKI_GENBA_CD"]));
            }
            set {
                this["SET_HENSOUSAKI_GENBA_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HENSOUSAKI_GENBA_NAME {
            get {
                return ((string)(this["SET_HENSOUSAKI_GENBA_NAME"]));
            }
            set {
                this["SET_HENSOUSAKI_GENBA_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HAISHUTSUJIGYOUSYA_NAME {
            get {
                return ((string)(this["SET_HAISHUTSUJIGYOUSYA_NAME"]));
            }
            set {
                this["SET_HAISHUTSUJIGYOUSYA_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_IKATSU_NYURYOKU {
            get {
                return ((string)(this["SET_IKATSU_NYURYOKU"]));
            }
            set {
                this["SET_IKATSU_NYURYOKU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_BARCODE_KBN {
            get {
                return ((string)(this["SET_BARCODE_KBN"]));
            }
            set {
                this["SET_BARCODE_KBN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HENKYAKUBI {
            get {
                return ((string)(this["SET_HENKYAKUBI"]));
            }
            set {
                this["SET_HENKYAKUBI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_KOUFUBANGO_HYOU {
            get {
                return ((string)(this["SET_KOUFUBANGO_HYOU"]));
            }
            set {
                this["SET_KOUFUBANGO_HYOU"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_RENZOKU_KBN
        {
            get
            {
                return ((string)(this["SET_RENZOKU_KBN"]));
            }
            set
            {
                this["SET_RENZOKU_KBN"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HYOU_A
        {
            get
            {
                return ((string)(this["HYOU_A"]));
            }
            set
            {
                this["HYOU_A"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HYOU_B1
        {
            get
            {
                return ((string)(this["HYOU_B1"]));
            }
            set
            {
                this["HYOU_B1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HYOU_B2
        {
            get
            {
                return ((string)(this["HYOU_B2"]));
            }
            set
            {
                this["HYOU_B2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HYOU_B4
        {
            get
            {
                return ((string)(this["HYOU_B4"]));
            }
            set
            {
                this["HYOU_B4"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HYOU_B6
        {
            get
            {
                return ((string)(this["HYOU_B6"]));
            }
            set
            {
                this["HYOU_B6"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HYOU_C1
        {
            get
            {
                return ((string)(this["HYOU_C1"]));
            }
            set
            {
                this["HYOU_C1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HYOU_C2
        {
            get
            {
                return ((string)(this["HYOU_C2"]));
            }
            set
            {
                this["HYOU_C2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HYOU_D
        {
            get
            {
                return ((string)(this["HYOU_D"]));
            }
            set
            {
                this["HYOU_D"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HYOU_E
        {
            get
            {
                return ((string)(this["HYOU_E"]));
            }
            set
            {
                this["HYOU_E"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_SBN_GYOUSHA_CD
        {
            get
            {
                return ((string)(this["SET_SBN_GYOUSHA_CD"]));
            }
            set
            {
                this["SET_SBN_GYOUSHA_CD"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_SBN_GYOUSHA_NAME
        {
            get
            {
                return ((string)(this["SET_SBN_GYOUSHA_NAME"]));
            }
            set
            {
                this["SET_SBN_GYOUSHA_NAME"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_SBN_GENBA_CD
        {
            get
            {
                return ((string)(this["SET_SBN_GENBA_CD"]));
            }
            set
            {
                this["SET_SBN_GENBA_CD"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_SBN_GENBA_NAME
        {
            get
            {
                return ((string)(this["SET_SBN_GENBA_NAME"]));
            }
            set
            {
                this["SET_SBN_GENBA_NAME"] = value;
            }
        }
    }
}
