SELECT 
    '運賃' AS '伝票',
    DENPYOU_NUMBER AS '伝票番号',
    CONVERT(varchar(10),DENPYOU_DATE,120) AS '伝票日付',
    '' AS '取引先',
	UNPAN_GYOUSHA_NAME AS '業者',
    '' AS '現場',
	SYSTEM_ID AS HIDDEN_SYSTEM_ID,
	RENKEI_NUMBER AS HIDDEN_UKETSUKE_NUMBER,
    DENSHU_KBN_CD AS HIDDEN_RENKEI_DENSHU_KBN_CD,
    9 AS HIDDEN_DENPYOU_KBN
FROM T_UNCHIN_ENTRY
WHERE DELETE_FLG = 0
/*IF !data.KYOTEN_CD.IsNull*/
AND KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/
/*IF !data.KYOTEN_CD.IsNull*/
AND KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/
/*IF !data.DENPYOU_DATE_FROM.IsNull*/
AND CONVERT(varchar(10),DENPYOU_DATE,120) >= /*data.DENPYOU_DATE_FROM*/
/*END*/
/*IF !data.DENPYOU_DATE_TO.IsNull*/
AND CONVERT(varchar(10),DENPYOU_DATE,120) <= /*data.DENPYOU_DATE_TO*/
/*END*/
/*IF data.DENPYOU_NO != null*/
AND DENPYOU_NUMBER = /*data.DENPYOU_NO*/
/*END*/
/*IF data.GYOUSHA_CD != null*/
AND UNPAN_GYOUSHA_CD = /*data.GYOUSHA_CD*/
/*END*/
ORDER BY DENPYOU_DATE,DENPYOU_NUMBER