SELECT 
    'マニフェスト' AS '伝票',
    MANIFEST_ID AS '伝票番号',
    CONVERT(varchar(10),KOUFU_DATE,120) AS '伝票日付',
	MT.TORIHIKISAKI_NAME_RYAKU AS '取引先',
	HST_GYOUSHA_NAME AS '業者',
	HST_GENBA_NAME AS '現場',
	HAIKI_KBN_CD AS HIDDEN_HAIKI_KBN_CD,
	SYSTEM_ID AS HIDDEN_SYSTEM_ID,
	'' AS HIDDEN_UKETSUKE_NUMBER,
	RENKEI_DENSHU_KBN_CD AS HIDDEN_RENKEI_DENSHU_KBN_CD,
    RENKEI_SYSTEM_ID AS HIDDEN_RENKEI_SYSTEM_ID,
    8 AS HIDDEN_DENPYOU_KBN
FROM T_MANIFEST_ENTRY TME
LEFT JOIN M_TORIHIKISAKI MT
ON TME.TORIHIKISAKI_CD = MT.TORIHIKISAKI_CD
WHERE TME.DELETE_FLG = 0
/*IF !data.KYOTEN_CD.IsNull*/
AND KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/
/*IF !data.DENPYOU_DATE_FROM.IsNull*/
AND CONVERT(varchar(10),KOUFU_DATE,120) >= /*data.DENPYOU_DATE_FROM*/
/*END*/
/*IF !data.DENPYOU_DATE_TO.IsNull*/
AND CONVERT(varchar(10),KOUFU_DATE,120) <= /*data.DENPYOU_DATE_TO*/
/*END*/
/*IF data.DENPYOU_NO != null*/
AND MANIFEST_ID = /*data.DENPYOU_NO*/
/*END*/
/*IF data.TORIHIKISAKI_CD != null*/
AND TME.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/
/*END*/
/*IF data.GYOUSHA_CD != null*/
AND HST_GYOUSHA_CD = /*data.GYOUSHA_CD*/
/*END*/
/*IF data.GENBA_CD != null*/
AND HST_GENBA_CD = /*data.GENBA_CD*/
/*END*/
ORDER BY KOUFU_DATE,MANIFEST_ID