-- 売上/支払入力
SELECT 
   DENPYOU_TYPE AS '伝票'
  ,DENPYOU_NUMBER AS '伝票番号'
  ,DENPYOU_DATE AS '伝票日付'
  ,TORIHIKISAKI_NAME AS '取引先'
  ,GYOUSHA_NAME AS '業者'
  ,GENBA_NAME AS '現場'
  ,SYSTEM_ID AS HIDDEN_SYSTEM_ID
  ,HAIKI_KBN_CD AS HIDDEN_HAIKI_KBN_CD
FROM(
    -- マニフェスト
    SELECT 
      'マニフェスト' AS DENPYOU_TYPE
     ,8 AS DENPYOU_TYPE_KBN
     ,TME.MANIFEST_ID AS DENPYOU_NUMBER
     ,TME.KOUFU_DATE AS DENPYOU_DATE
     ,MT.TORIHIKISAKI_NAME_RYAKU AS TORIHIKISAKI_NAME
     ,TME.HST_GYOUSHA_NAME AS GYOUSHA_NAME
     ,TME.HST_GENBA_NAME AS GENBA_NAME
      ,TME.SYSTEM_ID
      ,TME.HAIKI_KBN_CD
    FROM T_MANIFEST_ENTRY TME
	LEFT JOIN M_TORIHIKISAKI MT ON MT.TORIHIKISAKI_CD = TME.TORIHIKISAKI_CD
    WHERE TME.RENKEI_DENSHU_KBN_CD = 3
      AND TME.RENKEI_SYSTEM_ID = /*data.SYSTEM_ID*/
      AND TME.DELETE_FLG = 0
      /*IF !data.MANI_FLG*/
      AND 1 = 0
      /*END*/

    UNION

    -- 運賃
    SELECT
      '運賃' AS DENPYOU_TYPE
     ,9 AS DENPYOU_TYPE_KBN
     ,CONVERT(VARCHAR,DENPYOU_NUMBER) AS DENPYOU_NUMBER
     ,DENPYOU_DATE AS DENPYOU_DATE
     ,'' AS TORIHIKISAKI_NAME
     ,UNPAN_GYOUSHA_NAME AS GYOUSHA_NAME
     ,'' AS GENBA_NAME
      ,SYSTEM_ID
      ,'' AS HAIKI_KBN_CD
    FROM T_UNCHIN_ENTRY
    WHERE RENKEI_NUMBER = /*data.RENKEI_NUMBER*/
      AND DENSHU_KBN_CD = 3
      AND DELETE_FLG = 0
      /*IF !data.UNCHIN_FLG*/
      AND 1 = 0
      /*END*/

    UNION

    -- 受付
    --  収集受付
    SELECT
      '収集受付' AS DENPYOU_TYPE
     ,1 AS DENPYOU_TYPE_KBN
     ,CONVERT(VARCHAR,UKETSUKE_NUMBER) AS DENPYOU_NUMBER
     ,SAGYOU_DATE AS DENPYOU_DATE
     ,TORIHIKISAKI_NAME
     ,GYOUSHA_NAME
     ,GENBA_NAME
      ,SYSTEM_ID
      ,'' AS HAIKI_KBN_CD
    FROM T_UKETSUKE_SS_ENTRY
    WHERE UKETSUKE_NUMBER = /*data.UKETSUKE_NUMBER*/
      AND DELETE_FLG = 0
      /*IF !data.UKETSUKE_FLG*/
      AND 1 = 0
      /*END*/

    UNION

    --  出荷受付
    SELECT
      '出荷受付' AS DENPYOU_TYPE
     ,2 AS DENPYOU_TYPE_KBN
     ,CONVERT(VARCHAR,UKETSUKE_NUMBER) AS DENPYOU_NUMBER
     ,SAGYOU_DATE AS DENPYOU_DATE
     ,TORIHIKISAKI_NAME
     ,GYOUSHA_NAME
     ,GENBA_NAME
      ,SYSTEM_ID
      ,'' AS HAIKI_KBN_CD
    FROM T_UKETSUKE_SK_ENTRY
    WHERE UKETSUKE_NUMBER = /*data.UKETSUKE_NUMBER*/
      AND DELETE_FLG = 0
      /*IF !data.UKETSUKE_FLG*/
      AND 1 = 0
      /*END*/

    UNION

    --  持込受付
    SELECT
      '持込受付' AS DENPYOU_TYPE
     ,3 AS DENPYOU_TYPE_KBN
     ,CONVERT(VARCHAR,UKETSUKE_NUMBER) AS DENPYOU_NUMBER
     ,SAGYOU_DATE AS DENPYOU_DATE
     ,TORIHIKISAKI_NAME
     ,GYOUSHA_NAME
     ,GENBA_NAME
      ,SYSTEM_ID
      ,'' AS HAIKI_KBN_CD
    FROM T_UKETSUKE_MK_ENTRY
    WHERE UKETSUKE_NUMBER = /*data.UKETSUKE_NUMBER*/
      AND DELETE_FLG = 0
      /*IF !data.UKETSUKE_FLG*/
      AND 1 = 0
      /*END*/
) AS A
ORDER BY DENPYOU_TYPE_KBN,DENPYOU_DATE,DENPYOU_NUMBER