-- 代納
SELECT 
   DENPYOU_TYPE AS '伝票'
  ,DENPYOU_NUMBER AS '伝票番号'
  ,DENPYOU_DATE AS '伝票日付'
  ,TORIHIKISAKI_NAME AS '取引先'
  ,GYOUSHA_NAME AS '業者'
  ,GENBA_NAME AS '現場'
  ,SYSTEM_ID AS HIDDEN_SYSTEM_ID
  ,HAIKI_KBN_CD AS HIDDEN_HAIKI_KBN_CD
FROM(
	-- 運賃
	SELECT 
	  '運賃' AS DENPYOU_TYPE
	  ,9 AS DENPYOU_TYPE_KBN
	 ,DENPYOU_NUMBER AS DENPYOU_NUMBER
	 ,DENPYOU_DATE
	 ,'' AS TORIHIKISAKI_NAME
	 ,UNPAN_GYOUSHA_NAME AS GYOUSHA_NAME
	 ,'' AS GENBA_NAME
	 ,SYSTEM_ID
	 ,'' AS HAIKI_KBN_CD
	FROM T_UNCHIN_ENTRY
	WHERE RENKEI_NUMBER = /*data.RENKEI_NUMBER*/
	  AND DENSHU_KBN_CD = 170
	  AND DELETE_FLG = 0
      /*IF !data.UNCHIN_FLG*/
      AND 1 = 0
      /*END*/
) AS A
ORDER BY DENPYOU_TYPE_KBN,DENPYOU_DATE,DENPYOU_NUMBER