-- 検索対象伝票で5.代納が選択された場合
SELECT 
   DENPYOU_TYPE1 AS '伝票'
  ,DENPYOU_NUMBER1 AS '伝票番号'
  ,DENPYOU_DATE1 AS '伝票日付'
  ,TORIHIKISAKI_NAME1 AS '取引先'
  ,GYOUSHA_NAME1 AS '業者'
  ,GENBA_NAME1 AS '現場'
  ,DENPYOU_TYPE2 AS '伝票'
  ,DENPYOU_NUMBER2 AS '伝票番号'
  ,DENPYOU_DATE2 AS '伝票日付'
  ,TORIHIKISAKI_NAME2 AS '取引先'
  ,GYOUSHA_NAME2 AS '業者'
  ,GENBA_NAME2 AS '現場'
  ,DENPYOU_TYPE_KBN AS HIDDEN_DENPYOU_TYPE
  ,DENPYOU_TYPE1 AS HIDDEN_DENPYOU_KBN
  ,DENPYOU_NUMBER1  AS HIDDEN_DENPYOU_NO
  ,DENPYOU_DATE1 AS HIDDEN_DENPYOU_DATE
  ,TORIHIKISAKI_NAME1 AS HIDDEN_TORIHIKISAKI_NAME
  ,GYOUSHA_NAME1 AS HIDDEN_GYOUSHA_NAME
  ,GENBA_NAME1 AS HIDDEN_GENBA_NAME
  ,SYSTEM_ID1 AS HIDDEN_SYSTEM_ID
  ,SYSTEM_ID2 AS HIDDEN_SYSTEM_ID_R
  ,'' AS HIDDEN_HAIKI_KBN_CD
  ,'' AS HIDDEN_HAIKI_KBN_CD_R
FROM(
SELECT 
       '代納' AS DENPYOU_TYPE1
      ,URSH.UR_SH_NUMBER  AS DENPYOU_NUMBER1
      ,URSH.DENPYOU_DATE AS DENPYOU_DATE1
      ,URSH.TORIHIKISAKI_NAME AS TORIHIKISAKI_NAME1
      ,URSH.GYOUSHA_NAME AS GYOUSHA_NAME1
      ,URSH.GENBA_NAME AS GENBA_NAME1
      ,URSH.SYSTEM_ID AS SYSTEM_ID1
	  ,10 AS DENPYOU_TYPE_KBN
      ,'運賃' AS DENPYOU_TYPE2
      ,UNCHIN.DENPYOU_NUMBER AS DENPYOU_NUMBER2
      ,UNCHIN.DENPYOU_DATE AS DENPYOU_DATE2
      ,'' AS TORIHIKISAKI_NAME2
      ,UNCHIN.UNPAN_GYOUSHA_NAME AS GYOUSHA_NAME2
      ,'' AS GENBA_NAME2
      ,UNCHIN.SYSTEM_ID AS SYSTEM_ID2
 FROM 
     T_UR_SH_ENTRY URSH
LEFT JOIN T_UNCHIN_ENTRY UNCHIN
       ON UNCHIN.RENKEI_NUMBER = URSH.UR_SH_NUMBER
      AND UNCHIN.DELETE_FLG = 0
      AND UNCHIN.DENSHU_KBN_CD = 170
LEFT JOIN T_UR_SH_DETAIL DETAIL
       ON URSH.SYSTEM_ID = DETAIL.SYSTEM_ID
      AND URSH.SEQ = DETAIL.SEQ
      AND DETAIL.DENPYOU_KBN_CD = 1
WHERE 
URSH.DELETE_FLG = 0
AND ISNULL(URSH.DAINOU_FLG, 0) = 1
AND DETAIL.DENPYOU_KBN_CD = 1
AND (
     (/*data.RENKEI_KBN*/ = 1) 
  OR (/*data.RENKEI_KBN*/ = 2 AND UNCHIN.SYSTEM_ID IS NOT NULL) 
  OR (/*data.RENKEI_KBN*/ = 3 AND UNCHIN.SYSTEM_ID IS NULL)
  )
/*IF !data.KYOTEN_CD.IsNull*/
AND URSH.KYOTEN_CD = /*data.KYOTEN_CD*/
/*END*/
/*IF !data.DENPYOU_DATE_FROM.IsNull*/
AND CONVERT(varchar(10), URSH.DENPYOU_DATE,120) >= /*data.DENPYOU_DATE_FROM*/
/*END*/
/*IF !data.DENPYOU_DATE_TO.IsNull*/
AND CONVERT(varchar(10), URSH.DENPYOU_DATE,120) <= /*data.DENPYOU_DATE_TO*/
/*END*/
/*IF data.DENPYOU_NO != null*/
AND URSH.UR_SH_NUMBER = /*data.DENPYOU_NO*/
/*END*/
/*IF data.TORIHIKISAKI_CD != null*/
AND URSH.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/
/*END*/
/*IF data.GYOUSHA_CD != null*/
AND URSH.GYOUSHA_CD = /*data.GYOUSHA_CD*/
/*END*/
/*IF data.GYOUSHA_CD != null*/
AND URSH.GENBA_CD = /*data.GYOUSHA_CD*/
/*END*/
) AS A
ORDER BY DENPYOU_TYPE_KBN,DENPYOU_DATE1,DENPYOU_NUMBER1