SELECT
    CHI.CHIIKI_CD
    ,CHI.CHIIKI_NAME
    ,CHI.CHIIKI_NAME_RYAKU
    ,CHI.CHIIKI_FURIGANA
	,CHI.GOV_OR_MAY_NAME
	,RIGHT('00' + CONVERT(varchar, CHI.TODOUFUKEN_CD), 2) TODOUFUKEN_CD
	,TOD.TODOUFUKEN_NAME_RYAKU
    ,CHI.CHIIKI_BIKOU
    ,CHI.CREATE_USER
    ,CHI.CREATE_DATE
    ,CHI.UPDATE_USER
    ,CHI.UPDATE_DATE
    ,CHI.DELETE_FLG
	,CHI.TIME_STAMP
FROM 
    dbo.M_CHIIKI CHI
		LEFT JOIN dbo.M_TODOUFUKEN TOD ON TOD.TODOUFUKEN_CD = CHI.TODOUFUKEN_CD
/*BEGIN*/WHERE
 /*IF data.CHIIKI_CD != null*/
 CHI.CHIIKI_CD LIKE '%' + /*data.CHIIKI_CD*/'000001' + '%'
 /*END*/
 /*IF data.CHIIKI_NAME != null*/AND CHI.CHIIKI_NAME LIKE '%' +  /*data.CHIIKI_NAME*/ + '%'/*END*/
 /*IF data.CHIIKI_NAME_RYAKU != null*/AND CHI.CHIIKI_NAME_RYAKU LIKE '%' +  /*data.CHIIKI_NAME_RYAKU*/ + '%'/*END*/
 /*IF data.CHIIKI_FURIGANA != null*/AND CHI.CHIIKI_FURIGANA LIKE '%' +  /*data.CHIIKI_FURIGANA*/ + '%'/*END*/
 /*IF data.CHIIKI_BIKOU != null*/AND CHI.CHIIKI_BIKOU LIKE '%' +  /*data.CHIIKI_BIKOU*/ + '%'/*END*/
 /*IF data.CREATE_USER != null*/AND CHI.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, CHI.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null*/AND CHI.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, CHI.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
 /*IF !data.TODOUFUKEN_CD.IsNull*/AND CONVERT(nvarchar, CHI.TODOUFUKEN_CD) LIKE '%' + CONVERT(nvarchar,/*data.TODOUFUKEN_CD.Value*/) + '%'/*END*/
 /*IF !deletechuFlg*/AND CHI.DELETE_FLG = /*deletechuFlg*/0/*END*/
/*END*/
ORDER BY CHI.CHIIKI_CD
