--電子担当者検索
SELECT TANTOUSHA_CD,TANTOUSHA_NAME,EDI_MEMBER_ID,TANTOUSHA_KBN 
FROM M_DENSHI_TANTOUSHA 
WHERE DELETE_FLG = 0
/*IF data.EDI_MEMBER_ID != null &&  data.EDI_MEMBER_ID !='' */AND EDI_MEMBER_ID = /*data.EDI_MEMBER_ID*//*END*/
/*IF data.TANTOUSHA_KBN != null &&  data.TANTOUSHA_KBN !='' */AND TANTOUSHA_KBN = /*data.TANTOUSHA_KBN*//*END*/
/*IF data.TANTOUSHA_CD != null &&  data.TANTOUSHA_CD !='' */AND TANTOUSHA_CD = /*data.TANTOUSHA_CD*//*END*/
/*IF data.TANTOUSHA_NAME != null &&  data.TANTOUSHA_NAME !='' */AND TANTOUSHA_NAME = /*data.TANTOUSHA_NAME*//*END*/