SELECT UNIT_CD AS CD,UNIT_NAME_RYAKU AS NAME,UNIT_NAME 
FROM M_UNIT 
WHERE DELETE_FLG = 0 AND DENSHI_USE_KBN = 1 
/*IF data.UNIT_CD != null &&  data.UNIT_CD !='' */AND UNIT_CD = /*data.UNIT_CD*//*END*/