SELECT SHOBUN_HOUHOU_CD AS CD,SHOBUN_HOUHOU_NAME_RYAKU AS NAME,SHOBUN_HOUHOU_NAME 
FROM M_SHOBUN_HOUHOU 
WHERE
/*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
DELETE_FLG = 0
-- ELSE
1 = 1
/*END*/
AND DENSHI_USE_KBN = 1 
/*IF data.SHOBUN_HOUHOU_CD != null &&  data.SHOBUN_HOUHOU_CD !='' */AND SHOBUN_HOUHOU_CD = /*data.SHOBUN_HOUHOU_CD*//*END*/