SELECT TBL.KANSANSHIKI,TBL.KANSANCHI
FROM (SELECT KANSANSHIKI,KANSANCHI 
        FROM M_MANIFEST_KANSAN MMK INNER JOIN M_DENSHI_HAIKI_SHURUI MDHS 
                ON MMK.HOUKOKUSHO_BUNRUI_CD = MDHS.HOUKOKUSHO_BUNRUI_CD 
        WHERE MMK.DELETE_FLG = 0  
        AND MDHS.HAIKI_SHURUI_CD = /*data.HAIKI_SHURUI_CD*//*END*/
        AND MMK.HAIKI_NAME_CD = /*data.HAIKI_NAME_CD*//*END*/
        AND MMK.UNIT_CD = /*data.UNIT_CD*//*END*/
        AND MMK.NISUGATA_CD = /*data.NISUGATA_CD*//*END*/ 
        ) TBL 