SELECT YUUGAI_BUSSHITSU_CD,YUUGAI_BUSSHITSU_NAME
FROM M_DENSHI_YUUGAI_BUSSHITSU 
WHERE DELETE_FLG = 0 
/*IF data.YUUGAI_BUSSHITSU_CD != null &&  data.YUUGAI_BUSSHITSU_CD !='' */AND YUUGAI_BUSSHITSU_CD = /*data.YUUGAI_BUSSHITSU_CD*//*END*/