--電子事業者検索
SELECT  M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID,
		M_DENSHI_JIGYOUSHA.GYOUSHA_CD,
		M_DENSHI_JIGYOUSHA.JIGYOUSHA_NAME,
		M_DENSHI_JIGYOUSHA.JIGYOUSHA_POST, 
		M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS1 AS TODOFUKEN_NAME, 
		(M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS2+
		 M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS3+
		 M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS4) AS DISP_JIGYOUSHA_ADDRESS,
		M_DENSHI_JIGYOUSHA.JIGYOUSHA_TEL,
		M_DENSHI_JIGYOUSHA.JIGYOUSHA_FAX,
		M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS1,
		M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS2,
		M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS3,
		M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS4,
		M_DENSHI_JIGYOUSHA.HST_KBN, 
		M_DENSHI_JIGYOUSHA.UPN_KBN,
		M_DENSHI_JIGYOUSHA.SBN_KBN,
		M_DENSHI_JIGYOUSHA.HOUKOKU_HUYOU_KBN,
		(M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS1+
		 M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS2+
		 M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS3+
		 M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS4) AS JIGYOUSHA_ADDRESS
FROM M_DENSHI_JIGYOUSHA 
LEFT JOIN M_GYOUSHA 
ON M_GYOUSHA.GYOUSHA_CD = M_DENSHI_JIGYOUSHA.GYOUSHA_CD 
WHERE M_DENSHI_JIGYOUSHA.GYOUSHA_CD IS NOT NULL AND M_DENSHI_JIGYOUSHA.GYOUSHA_CD != ''
/*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
AND M_GYOUSHA.DELETE_FLG = 0
/*END*/
/*IF data.GYOUSHA_CD != null &&  data.GYOUSHA_CD !='' */ AND M_DENSHI_JIGYOUSHA.GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/
/*IF data.EDI_MEMBER_ID != null &&  data.EDI_MEMBER_ID !='' */ AND M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID = /*data.EDI_MEMBER_ID*//*END*/
/*IF data.JIGYOUSHA_KBN_OR != null &&  data.JIGYOUSHA_KBN_OR !='' */ AND (M_DENSHI_JIGYOUSHA.HST_KBN = 1 OR M_DENSHI_JIGYOUSHA.SBN_KBN = 1) /*END*/

/*IF data.JIGYOUSHA_KBN_OR == null ||  data.JIGYOUSHA_KBN_OR == ''*/
	/*BEGIN*/
	AND (
	/*IF data.HST_KBN != null &&  data.HST_KBN !='' */ M_DENSHI_JIGYOUSHA.HST_KBN = 1/*END*/
	/*IF data.UPN_KBN != null &&  data.UPN_KBN !='' */ OR M_DENSHI_JIGYOUSHA.UPN_KBN = 1/*END*/
	/*IF data.SBN_KBN != null &&  data.SBN_KBN !='' */ OR M_DENSHI_JIGYOUSHA.SBN_KBN = 1/*END*/
	)
	/*END*/
/*END*/

/*IF data.HOUKOKU_HUYOU_KBN != null &&  data.HOUKOKU_HUYOU_KBN !='' */ AND M_DENSHI_JIGYOUSHA.HOUKOKU_HUYOU_KBN = 1/*END*/

