SELECT
    GYOUSHA.CHIIKI_CD AS CHIIKI_CD,
    GYOUSHA.GYOUSHA_NAME_RYAKU AS NAME_RYAKU
FROM
    M_GYOUSHA AS GYOUSHA
WHERE NOT EXISTS(
    SELECT MCB.CHIIKI_CD FROM M_CHIIKIBETSU_BUNRUI AS MCB
    WHERE GYOUSHA.CHIIKI_CD = MCB.CHIIKI_CD
    )
    AND GYOUSHA.GYOUSHAKBN_MANI = 1
    AND GYOUSHA.CHIIKI_CD IS NOT NULL
    AND GYOUSHA.CHIIKI_CD != ''
/*IF data.DELETE_FLG == false*/
    AND GYOUSHA.DELETE_FLG = 0
/*END*/
GROUP BY
    GYOUSHA.CHIIKI_CD,
    GYOUSHA.GYOUSHA_NAME_RYAKU