SELECT
    GYOUSHA.CHIIKI_CD AS CHIIKI_CD,
    GYOUSHA.GYOUSHU_CD AS GYOUSHU_CD,
    GYOUSHA.GYOUSHA_NAME_RYAKU AS NAME_RYAKU
FROM
    M_GYOUSHA AS GYOUSHA
INNER JOIN M_CHIIKIBETSU_GYOUSHU AS MCG
    ON GYOUSHA.CHIIKI_CD = MCG.CHIIKI_CD
    AND GYOUSHA.GYOUSHU_CD = MCG.GYOUSHU_CD
    AND GYOUSHA.GYOUSHAKBN_MANI = 1
    AND (MCG.HOUKOKU_GYOUSHU_CD IS NULL OR MCG.HOUKOKU_GYOUSHU_CD = '')
/*IF data.DELETE_FLG == false*/
WHERE GYOUSHA.DELETE_FLG = 0
/*END*/

UNION

SELECT
     GYOUSHA.CHIIKI_CD AS CHIIKI_CD,
     GYOUSHA.GYOUSHU_CD AS GYOUSHU_CD,
     GYOUSHA.GYOUSHA_NAME_RYAKU AS NAME_RYAKU
FROM
    M_GYOUSHA AS GYOUSHA
WHERE NOT EXISTS (
    SELECT MCG.CHIIKI_CD FROM M_CHIIKIBETSU_GYOUSHU AS MCG
    WHERE GYOUSHA.CHIIKI_CD = MCG.CHIIKI_CD
    )
    AND GYOUSHA.GYOUSHAKBN_MANI = 1
    AND GYOUSHA.CHIIKI_CD IS NOT NULL
    AND GYOUSHA.CHIIKI_CD != ''
/*IF data.DELETE_FLG == false*/
    AND GYOUSHA.DELETE_FLG = 0
/*END*/
GROUP BY
    GYOUSHA.CHIIKI_CD,
    GYOUSHA.GYOUSHU_CD,
    GYOUSHA.GYOUSHA_NAME_RYAKU

UNION

SELECT
    GENBA.CHIIKI_CD AS CHIIKI_CD,
    GENBA.GYOUSHU_CD AS GYOUSHU_CD,
    GYOUSHA.GYOUSHA_NAME_RYAKU + '、' + GENBA.GENBA_NAME_RYAKU AS NAME_RYAKU
FROM
    M_GENBA AS GENBA
INNER JOIN M_GYOUSHA AS GYOUSHA
    ON GYOUSHA.GYOUSHA_CD = GENBA.GYOUSHA_CD
    AND GYOUSHA.GYOUSHAKBN_MANI = 1
INNER JOIN M_CHIIKIBETSU_GYOUSHU AS MCG
    ON MCG.CHIIKI_CD = GENBA.CHIIKI_CD
    AND MCG.GYOUSHU_CD = GENBA.GYOUSHU_CD
WHERE (MCG.HOUKOKU_GYOUSHU_CD IS NULL OR MCG.HOUKOKU_GYOUSHU_CD = '')
/*IF data.DELETE_FLG == false*/
    AND GYOUSHA.DELETE_FLG = 0
    AND GENBA.DELETE_FLG = 0
/*END*/
GROUP BY
    GENBA.CHIIKI_CD,
    GENBA.GYOUSHU_CD,
    GYOUSHA.GYOUSHA_NAME_RYAKU,
    GENBA.GENBA_NAME_RYAKU

UNION

SELECT
     GENBA.CHIIKI_CD AS CHIIKI_CD,
     GENBA.GYOUSHU_CD AS GYOUSHU_CD,
     GYOUSHA.GYOUSHA_NAME_RYAKU + '、' + GENBA.GENBA_NAME_RYAKU AS NAME_RYAKU
FROM
    M_GENBA AS GENBA
INNER JOIN M_GYOUSHA AS GYOUSHA
    ON GYOUSHA.GYOUSHA_CD = GENBA.GYOUSHA_CD
    AND GYOUSHA.GYOUSHAKBN_MANI = 1
INNER JOIN M_CHIIKIBETSU_GYOUSHU AS MCG
    ON NOT EXISTS (
        SELECT MCG.CHIIKI_CD FROM M_CHIIKIBETSU_GYOUSHU AS MCG
        WHERE GENBA.CHIIKI_CD = MCG.CHIIKI_CD
        )
WHERE (MCG.HOUKOKU_GYOUSHU_CD IS NULL OR MCG.HOUKOKU_GYOUSHU_CD = '')
    AND GENBA.CHIIKI_CD IS NOT NULL
    AND GENBA.CHIIKI_CD != ''
/*IF data.DELETE_FLG == false*/
    AND GYOUSHA.DELETE_FLG = 0
    AND GENBA.DELETE_FLG = 0
/*END*/
GROUP BY
    GENBA.CHIIKI_CD,
    GENBA.GYOUSHU_CD,
    GYOUSHA.GYOUSHA_NAME_RYAKU,
    GENBA.GENBA_NAME_RYAKU