SELECT
    CHIIKIBETSUKYOKA.KYOKA_KBN,
    CHIIKIBETSUKYOKA.GYOUSHA_CD,
    CHIIKIBETSUKYOKA.GENBA_CD,
    CHIIKIBETSUKYOKA.CHIIKI_CD,
    CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO
FROM
    M_CHIIKIBETSU_KYOKA AS CHIIKIBETSUKYOKA
INNER JOIN
    M_GYOUSHA AS GYOUSHA
    ON GYOUSHA.GYOUSHA_CD = CHIIKIBETSUKYOKA.GYOUSHA_CD
    AND GYOUSHA.GYOUSHAKBN_MANI = 1
    AND GYOUSHA.HAISHUTSU_NIZUMI_GYOUSHA_KBN = 1
WHERE (CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO IS NULL
        OR CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO = '')

UNION

SELECT
    CHIIKIBETSUKYOKA.KYOKA_KBN,
    CHIIKIBETSUKYOKA.GYOUSHA_CD,
    CHIIKIBETSUKYOKA.GENBA_CD,
    CHIIKIBETSUKYOKA.CHIIKI_CD,
    CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO
FROM
    M_CHIIKIBETSU_KYOKA AS CHIIKIBETSUKYOKA
INNER JOIN
    M_GYOUSHA AS GYOUSHA
    ON GYOUSHA.GYOUSHA_CD = CHIIKIBETSUKYOKA.GYOUSHA_CD
    AND GYOUSHA.GYOUSHAKBN_MANI = 1
INNER JOIN
    M_GENBA AS GENBA
    ON GENBA.GYOUSHA_CD = CHIIKIBETSUKYOKA.GYOUSHA_CD
    AND GENBA.GENBA_CD = CHIIKIBETSUKYOKA.GENBA_CD
    AND GENBA.HAISHUTSU_NIZUMI_GENBA_KBN = 1
WHERE
    CHIIKIBETSUKYOKA.KYOKA_KBN = 1
    AND (CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO IS NULL
        OR CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO = '')

UNION

SELECT
    CHIIKIBETSUKYOKA.KYOKA_KBN,
    CHIIKIBETSUKYOKA.GYOUSHA_CD,
    CHIIKIBETSUKYOKA.GENBA_CD,
    CHIIKIBETSUKYOKA.CHIIKI_CD,
    CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO
FROM
    M_CHIIKIBETSU_KYOKA AS CHIIKIBETSUKYOKA
INNER JOIN
    M_GYOUSHA AS GYOUSHA
    ON GYOUSHA.GYOUSHA_CD = CHIIKIBETSUKYOKA.GYOUSHA_CD
    AND GYOUSHA.GYOUSHAKBN_MANI = 1
    AND GYOUSHA.SHOBUN_NIOROSHI_GYOUSHA_KBN = 1
WHERE
    CHIIKIBETSUKYOKA.KYOKA_KBN = 1
    AND (CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO IS NULL
        OR CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO = '')

UNION

SELECT
    CHIIKIBETSUKYOKA.KYOKA_KBN,
    CHIIKIBETSUKYOKA.GYOUSHA_CD,
    CHIIKIBETSUKYOKA.GENBA_CD,
    CHIIKIBETSUKYOKA.CHIIKI_CD,
    CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO
FROM
    M_CHIIKIBETSU_KYOKA AS CHIIKIBETSUKYOKA
INNER JOIN
    M_GYOUSHA AS GYOUSHA
    ON GYOUSHA.GYOUSHA_CD = CHIIKIBETSUKYOKA.GYOUSHA_CD
    AND GYOUSHA.GYOUSHAKBN_MANI = 1
INNER JOIN
    M_GENBA AS GENBA
    ON GENBA.GYOUSHA_CD = CHIIKIBETSUKYOKA.GYOUSHA_CD
    AND GENBA.GENBA_CD = CHIIKIBETSUKYOKA.GENBA_CD
    AND GENBA.SHOBUN_NIOROSHI_GENBA_KBN = 1
WHERE
    CHIIKIBETSUKYOKA.KYOKA_KBN = 1
    AND (CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO IS NULL
        OR CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO = '')

UNION

SELECT
    CHIIKIBETSUKYOKA.KYOKA_KBN,
    CHIIKIBETSUKYOKA.GYOUSHA_CD,
    CHIIKIBETSUKYOKA.GENBA_CD,
    CHIIKIBETSUKYOKA.CHIIKI_CD,
    CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO
FROM
    M_CHIIKIBETSU_KYOKA AS CHIIKIBETSUKYOKA
INNER JOIN
    M_GYOUSHA AS GYOUSHA
    ON GYOUSHA.GYOUSHA_CD = CHIIKIBETSUKYOKA.GYOUSHA_CD
    AND GYOUSHA.GYOUSHAKBN_MANI = 1
INNER JOIN
    M_GENBA AS GENBA
    ON GENBA.GYOUSHA_CD = CHIIKIBETSUKYOKA.GYOUSHA_CD
    AND GENBA.GENBA_CD = CHIIKIBETSUKYOKA.GENBA_CD
    AND GENBA.SHOBUN_NIOROSHI_GENBA_KBN = 1
WHERE
    CHIIKIBETSUKYOKA.KYOKA_KBN = 2
    AND (CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO IS NULL
        OR CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO = '')

UNION

SELECT
    CHIIKIBETSUKYOKA.KYOKA_KBN,
    CHIIKIBETSUKYOKA.GYOUSHA_CD,
    CHIIKIBETSUKYOKA.GENBA_CD,
    CHIIKIBETSUKYOKA.CHIIKI_CD,
    CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO
FROM
    M_CHIIKIBETSU_KYOKA AS CHIIKIBETSUKYOKA
INNER JOIN
    M_GYOUSHA AS GYOUSHA
    ON GYOUSHA.GYOUSHA_CD = CHIIKIBETSUKYOKA.GYOUSHA_CD
    AND GYOUSHA.GYOUSHAKBN_MANI = 1
INNER JOIN
    M_GENBA AS GENBA
    ON GENBA.GYOUSHA_CD = CHIIKIBETSUKYOKA.GYOUSHA_CD
    AND GENBA.GENBA_CD = CHIIKIBETSUKYOKA.GENBA_CD
    AND GENBA.SAISHUU_SHOBUNJOU_KBN = 1
WHERE
    CHIIKIBETSUKYOKA.KYOKA_KBN = 3
    AND (CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO IS NULL
        OR CHIIKIBETSUKYOKA.FUTSUU_KYOKA_NO = '')