SELECT
    GYOUSHA.CHIIKI_CD AS CHIIKI_CD,
    GYOUSHA.GYOUSHA_NAME_RYAKU AS NAME_RYAKU
FROM
    M_GYOUSHA AS GYOUSHA
WHERE NOT EXISTS (
    SELECT MCS.CHIIKI_CD FROM M_CHIIKIBETSU_SHISETSU AS MCS
    WHERE GYOUSHA.CHIIKI_CD = MCS.CHIIKI_CD
    )
    AND GYOUSHA.GYOUSHAKBN_MANI = 1
    AND GYOUSHA.CHIIKI_CD IS NOT NULL
    AND GYOUSHA.CHIIKI_CD != ''
/*IF data.DELETE_FLG == false*/
    AND GYOUSHA.DELETE_FLG = 0
/*END*/
GROUP BY
    GYOUSHA.CHIIKI_CD,
    GYOUSHA.GYOUSHA_NAME_RYAKU

UNION

SELECT
    GENBA.CHIIKI_CD AS CHIIKI_CD,
    GYOUSHA.GYOUSHA_NAME_RYAKU + '、' + GENBA.GENBA_NAME_RYAKU AS NAME_RYAKU
FROM
    M_GYOUSHA AS GYOUSHA,
    M_GENBA AS GENBA
WHERE NOT EXISTS(
    SELECT MCS.CHIIKI_CD FROM M_CHIIKIBETSU_SHISETSU AS MCS
    WHERE GENBA.CHIIKI_CD = MCS.CHIIKI_CD
    )
    AND GENBA.GYOUSHA_CD = GYOUSHA.GYOUSHA_CD
    AND GENBA.CHIIKI_CD IS NOT NULL
    AND GENBA.CHIIKI_CD != ''
    AND GYOUSHA.GYOUSHAKBN_MANI = 1
/*IF data.DELETE_FLG == false*/
    AND GYOUSHA.DELETE_FLG = 0
    AND GENBA.DELETE_FLG = 0
/*END*/
GROUP BY
    GENBA.CHIIKI_CD,
    GYOUSHA.GYOUSHA_NAME_RYAKU,
    GENBA.GENBA_NAME_RYAKU