SELECT
    DENSHIJIGYOUJOU.EDI_MEMBER_ID,
    DENSHIJIGYOUJOU.JIGYOUJOU_CD,
    DENSHIJIGYOUJOU.JIGYOUJOU_NAME
FROM
    M_DENSHI_JIGYOUJOU AS DENSHIJIGYOUJOU
	LEFT JOIN M_GENBA GENBA
		  ON DENSHIJIGYOUJOU.GYOUSHA_CD = GENBA.GYOUSHA_CD
		 AND DENSHIJIGYOUJOU.GENBA_CD = GENBA.GENBA_CD
		 AND GENBA.DELETE_FLG = 0
		LEFT JOIN M_CHIIKI CHIIKI
		  ON GENBA.CHIIKI_CD = CHIIKI.CHIIKI_CD
		 AND CHIIKI.DELETE_FLG = 0
		LEFT JOIN M_TODOUFUKEN TODOUFUKEN
		  ON CHIIKI.TODOUFUKEN_CD = TODOUFUKEN.TODOUFUKEN_CD
		 AND TODOUFUKEN.DELETE_FLG = 0
WHERE 1= 1
  AND DENSHIJIGYOUJOU.GYOUSHA_CD IS NOT NULL AND DENSHIJIGYOUJOU.GYOUSHA_CD != '' 
  AND DENSHIJIGYOUJOU.GENBA_CD IS NOT NULL AND DENSHIJIGYOUJOU.GENBA_CD != '' 
  AND ISNULL(DENSHIJIGYOUJOU.JIGYOUJOU_ADDRESS1, '') != ISNULL(TODOUFUKEN.TODOUFUKEN_NAME, '')