SELECT
DISTINCT TME.SYSTEM_ID,
'' AS LATEST_SEQ,
'' AS KANRI_ID
FROM
    T_MANIFEST_ENTRY AS TME
WHERE
TME.DELETE_FLG = 0
AND TME.HAIKI_KBN_CD = /*data.S_HAIKI_KBN*/0
AND TME.SYSTEM_ID = /*data.S_SYSTEM_ID*/''
