SELECT
DISTINCT DMT.KANRI_ID AS KANRI_ID,
DMT.LATEST_SEQ AS LATEST_SEQ,
'' AS SYSTEM_ID
FROM DT_MF_TOC DMT
LEFT JOIN DT_R18_EX DTR18EX
ON DMT.KANRI_ID = DTR18EX.KANRI_ID
WHERE
DMT.KANRI_ID = /*data.S_SYSTEM_ID*/''
OR DTR18EX.SYSTEM_ID = /*data.S_SYSTEM_ID*/''