//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItakuKeiyakushoIchiran.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ItakuKeiyakushoIchiran.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   処分契約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ITAKU_KEIYAKU_SHURUI_1 {
            get {
                return ResourceManager.GetString("ITAKU_KEIYAKU_SHURUI_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   収・運契約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ITAKU_KEIYAKU_SHURUI_2 {
            get {
                return ResourceManager.GetString("ITAKU_KEIYAKU_SHURUI_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   収・運/処分契約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ITAKU_KEIYAKU_SHURUI_3 {
            get {
                return ResourceManager.GetString("ITAKU_KEIYAKU_SHURUI_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ITAKU_KEIYAKU_STATUS_1 {
            get {
                return ResourceManager.GetString("ITAKU_KEIYAKU_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ITAKU_KEIYAKU_STATUS_2 {
            get {
                return ResourceManager.GetString("ITAKU_KEIYAKU_STATUS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返送 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ITAKU_KEIYAKU_STATUS_3 {
            get {
                return ResourceManager.GetString("ITAKU_KEIYAKU_STATUS_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ITAKU_KEIYAKU_STATUS_4 {
            get {
                return ResourceManager.GetString("ITAKU_KEIYAKU_STATUS_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解約済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ITAKU_KEIYAKU_STATUS_5 {
            get {
                return ResourceManager.GetString("ITAKU_KEIYAKU_STATUS_5", resourceCulture);
            }
        }
    }
}
