WITH SYS_PREV
AS
(
	SELECT (SELECT FIELD_VALUE FROM M_SYS_PREV_VALUE WHERE GAMEN_ID = /*gamenId*/ AND FIELD_NAME = 'BANK_CD')  AS BANK_CD
	,(SELECT FIELD_VALUE FROM M_SYS_PREV_VALUE WHERE GAMEN_ID = /*gamenId*/ AND FIELD_NAME = 'BANK_SHITEN_CD') AS BANK_SHITEN_CD 
	,(SELECT FIELD_VALUE FROM M_SYS_PREV_VALUE WHERE GAMEN_ID = /*gamenId*/ AND FIELD_NAME = 'KOUZA_NO') AS KOUZA_NO 
	,(SELECT FIELD_VALUE FROM M_SYS_PREV_VALUE WHERE GAMEN_ID = /*gamenId*/ AND FIELD_NAME = 'KOUZA_SHURUI') AS KOUZA_SHURUI 
)
SELECT 
CAST(1 AS SMALLINT) AS DATA_KBN
,BANK.BANK_CD
,BANK.BANK_NAME
,BANK.BANK_NAME_RYAKU
,BANK.BANK_FURIGANA
,BANK.RENKEI_CD AS BANK_RENKEI_CD
,BANK_SHITEN.BANK_SHITEN_CD
,BANK_SHITEN.BANK_SHITEN_NAME
,BANK_SHITEN.BANK_SHIETN_NAME_RYAKU AS BANK_SHITEN_NAME_RYAKU
,BANK_SHITEN.BANK_SHITEN_FURIGANA
,BANK_SHITEN.KOUZA_SHURUI
,BANK_SHITEN.KOUZA_NO
,BANK_SHITEN.KOUZA_NAME
,BANK_SHITEN.RENKEI_CD AS BANK_SHITEN_RENKEI_CD
FROM SYS_PREV AS E
LEFT JOIN M_BANK AS BANK ON BANK.BANK_CD = E.BANK_CD
LEFT JOIN M_BANK_SHITEN AS BANK_SHITEN ON BANK_SHITEN.BANK_CD = E.BANK_CD
	AND BANK_SHITEN.BANK_SHITEN_CD = E.BANK_SHITEN_CD
	AND BANK_SHITEN.KOUZA_SHURUI = E.KOUZA_SHURUI
	AND BANK_SHITEN.KOUZA_NO = E.KOUZA_NO

UNION ALL
SELECT 
CAST(2 AS SMALLINT) AS DATA_KBN
,BANK.BANK_CD
,BANK.BANK_NAME
,BANK.BANK_NAME_RYAKU
,BANK.BANK_FURIGANA
,BANK.RENKEI_CD AS BANK_RENKEI_CD
,BANK_SHITEN.BANK_SHITEN_CD
,BANK_SHITEN.BANK_SHITEN_NAME
,BANK_SHITEN.BANK_SHIETN_NAME_RYAKU AS BANK_SHITEN_NAME_RYAKU
,BANK_SHITEN.BANK_SHITEN_FURIGANA
,BANK_SHITEN.KOUZA_SHURUI
,BANK_SHITEN.KOUZA_NO
,BANK_SHITEN.KOUZA_NAME
,BANK_SHITEN.RENKEI_CD AS BANK_SHITEN_RENKEI_CD
FROM M_CORP_INFO AS E
LEFT JOIN M_BANK AS BANK ON BANK.BANK_CD = E.BANK_CD
LEFT JOIN M_BANK_SHITEN AS BANK_SHITEN ON BANK_SHITEN.BANK_CD = E.BANK_CD
	AND BANK_SHITEN.BANK_SHITEN_CD = E.BANK_SHITEN_CD
	AND BANK_SHITEN.KOUZA_SHURUI = E.KOUZA_SHURUI
	AND BANK_SHITEN.KOUZA_NO = E.KOUZA_NO
WHERE E.SYS_ID = 0

ORDER BY DATA_KBN ASC