SELECT
CORP.FURIKOMI_IRAIJIN_CD
,E.DENPYOU_DATE
,E.SHUKKIN_NUMBER
,E.SYSTEM_ID
,E.SEQ
,E.TORIHIKISAKI_CD
,T.TORIHIKISAKI_NAME_RYAKU AS TORIHIKISAKI_NAME 
,TS.FURI_KOMI_MOTO_NAME
,ISNULL(E.SHUKKIN_AMOUNT_TOTAL, 0) + ISNULL(E.CHOUSEI_AMOUNT_TOTAL, 0) AS SHUKKIN_KINGAKU
,ISNULL(D.FURIKOMI_KINGAKU, 0) AS FURIKOMI_KINGAKU 
,CASE WHEN D.SYSTEM_ID IS NULL THEN CAST(0 AS BIT) ELSE CAST(1 AS BIT) END AS FURIKOMI_FLG
,BANK.BANK_CD
,BANK.BANK_NAME_RYAKU AS BANK_NAME
,BANK.BANK_FURIGANA
,BANK.RENKEI_CD AS BANK_RENKEI_CD
,BANK_SHITEN.BANK_SHITEN_CD
,BANK_SHITEN.BANK_SHIETN_NAME_RYAKU AS BANK_SHITEN_NAME
,BANK_SHITEN.BANK_SHITEN_FURIGANA
,BANK_SHITEN.KOUZA_SHURUI
,BANK_SHITEN.KOUZA_NO
,BANK_SHITEN.KOUZA_NAME
,BANK_SHITEN.RENKEI_CD AS BANK_SHITEN_RENKEI_CD
,E.FURIKOMI_BANK_CD
,E.FURIKOMI_BANK_NAME
,E.FURIKOMI_BANK_SHITEN_CD
,E.FURIKOMI_BANK_SHITEN_NAME
,E.FURIKOMI_KOUZA_SHURUI_CD
,E.FURIKOMI_KOUZA_SHURUI_NAME
,E.FURIKOMI_KOUZA_NO
,E.FURIKOMI_KOUZA_NAME
,E.TIME_STAMP
FROM T_SHUKKIN_ENTRY AS E
LEFT JOIN 
(
	SELECT 
	D.SYSTEM_ID
	,D.SEQ
	,SUM(ISNULL(D.KINGAKU,0)) AS FURIKOMI_KINGAKU
	FROM T_SHUKKIN_DETAIL AS D
	WHERE D.NYUUSHUKKIN_KBN_CD = 2
	GROUP BY D.SYSTEM_ID ,D.SEQ
) AS D ON E.SYSTEM_ID = D.SYSTEM_ID AND E.SEQ = D.SEQ 
LEFT JOIN M_TORIHIKISAKI AS T ON T.TORIHIKISAKI_CD = E.TORIHIKISAKI_CD
LEFT JOIN M_TORIHIKISAKI_SHIHARAI AS TS ON TS.TORIHIKISAKI_CD = E.TORIHIKISAKI_CD
LEFT JOIN M_BANK AS BANK ON BANK.BANK_CD = E.BANK_CD
LEFT JOIN M_BANK_SHITEN AS BANK_SHITEN ON BANK_SHITEN.BANK_CD = E.BANK_CD
	AND BANK_SHITEN.BANK_SHITEN_CD = E.BANK_SHITEN_CD
	AND BANK_SHITEN.KOUZA_SHURUI = E.KOUZA_SHURUI
	AND BANK_SHITEN.KOUZA_NO = E.KOUZA_NO
LEFT JOIN M_CORP_INFO AS CORP ON CORP. SYS_ID = 0
WHERE E.DELETE_FLG = 0
AND ISNULL(E.FURIKOMI_SHUTSURYOKU_KBN, 0) = 1
/*IF !data.SHUTSURYOKU_JOUKYOU.IsNull && data.SHUTSURYOKU_JOUKYOU.Value == 1*/AND ISNULL(E.BANK_EXPORTED_FLG, 0) = 0/*END*/
/*IF !data.SHUTSURYOKU_JOUKYOU.IsNull && data.SHUTSURYOKU_JOUKYOU.Value == 2*/AND ISNULL(E.BANK_EXPORTED_FLG, 0) = 1/*END*/
/*IF !data.FURIKOMI_DATE.IsNull*/AND E.DENPYOU_DATE = /*data.FURIKOMI_DATE.Value*//*END*/
/*IF data.BANK_CD != null && data.BANK_CD != ''*/AND BANK.BANK_CD = /*data.BANK_CD*//*END*/
/*IF data.BANK_SHITEN_CD != null && data.BANK_SHITEN_CD != ''*/AND BANK_SHITEN.BANK_SHITEN_CD = /*data.BANK_SHITEN_CD*//*END*/
/*IF data.KOUZA_SHURUI != null && data.KOUZA_SHURUI != ''*/AND BANK_SHITEN.KOUZA_SHURUI = /*data.KOUZA_SHURUI*//*END*/
/*IF data.KOUZA_NO != null && data.KOUZA_NO != ''*/AND BANK_SHITEN.KOUZA_NO = /*data.KOUZA_NO*//*END*/
ORDER BY 
E.TORIHIKISAKI_CD
,E.FURIKOMI_BANK_CD
,E.FURIKOMI_BANK_SHITEN_CD
,E.SHUKKIN_NUMBER