SELECT
	1 AS DENSHU_KBN,
	UE.SHIHARAI_DATE AS MEISAI_DATE,
	dbo.M_TORIHIKI_KBN.TORIHIKI_KBN_NAME_RYAKU AS TORIHIKI_KBN,
	UE.UKEIRE_NUMBER AS DENPYOU_NUMBER,
	UE.GYOUSHA_CD AS GYOUSHA_CD,
	UE.GENBA_CD AS GENBA_CD,
	dbo.M_GYOUSHA.GYOUSHA_NAME_RYAKU AS GYOUSHA_NAME,
	dbo.M_GENBA.GENBA_NAME_RYAKU AS GENBA_NAME,
	UD.HINMEI_CD AS HINMEI_CD,
	UE.RECEIPT_NUMBER AS SHIHARAI_NUMBER,
	dbo.M_HINMEI.HINMEI_NAME_RYAKU AS HINMEI_NAME,
	'' AS SUURYOU_UNIT,
	UD.SUURYOU AS SUURYOU,
	dbo.M_UNIT.UNIT_NAME_RYAKU AS UNIT_NAME_RYAKU,
	UD.TANKA AS TANKA,
	(ISNULL(UD.KINGAKU, 0) + ISNULL(UD.HINMEI_KINGAKU, 0)) AS SHIHARAI_KINGAKU,
	(CASE WHEN ISNULL(UD.HINMEI_ZEI_KBN_CD, 0) = 0 THEN 
		(CASE WHEN UE.SHIHARAI_ZEI_KEISAN_KBN_CD = 3 THEN 
			(CASE UE.SHIHARAI_ZEI_KBN_CD WHEN 1 THEN UD.TAX_SOTO WHEN 2 THEN UD.TAX_UCHI ELSE 0 END)
		ELSE
			0 
		END)
	ELSE
		(CASE UD.HINMEI_ZEI_KBN_CD WHEN 1 THEN UD.HINMEI_TAX_SOTO WHEN 2 THEN UD.HINMEI_TAX_UCHI ELSE 0 END)
	END) AS SHOUHIZEI,
	(CASE WHEN ISNULL(UD.HINMEI_ZEI_KBN_CD, 0) = 0 THEN 
		(CASE WHEN UE.SHIHARAI_ZEI_KEISAN_KBN_CD = 3 THEN 
			(CASE WHEN UE.SHIHARAI_ZEI_KBN_CD = 1 THEN UD.TAX_SOTO ELSE 0 END)
		ELSE
			0 
		END)
	ELSE
		(CASE WHEN UD.HINMEI_ZEI_KBN_CD = 1 THEN UD.HINMEI_TAX_SOTO ELSE 0 END)
	END) AS SHOUHI_SOTO_ZEI,
	NULL AS SHUKKIN_KINGAKU,
	NULL AS SASHIHIKI_ZANDAKA,
	UD.MEISAI_BIKOU AS MEISAI_BIKOU,
	UE.TORIHIKISAKI_CD AS TORIHIKISAKI_CD,
	dbo.M_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU AS TORIHIKISAKI_NAME,
	(CASE WHEN UE.SHIHARAI_ZEI_KEISAN_KBN_CD = 1 THEN 
		(CASE UE.SHIHARAI_ZEI_KBN_CD WHEN 1 THEN UE.SHIHARAI_TAX_SOTO WHEN 2 THEN UE.SHIHARAI_TAX_UCHI ELSE 0 END)
	ELSE
		0 
	END) AS DENPYOU_MAI_ZEI,
	(CASE WHEN UE.SHIHARAI_ZEI_KEISAN_KBN_CD = 1 THEN 
		(CASE WHEN UE.SHIHARAI_ZEI_KBN_CD = 1 THEN UE.SHIHARAI_TAX_SOTO ELSE 0 END)
	ELSE
		0 
	END) AS DENPYOU_MAI_SOTO_ZEI,
	UE.SHIHARAI_ZEI_KEISAN_KBN_CD AS ZEI_KEISAN_KBN_CD,
	UE.SHIHARAI_ZEI_KBN_CD AS ZEI_KBN_CD,
	UD.HINMEI_ZEI_KBN_CD AS HINMEI_ZEI_KBN_CD,
	UE.SHIHARAI_SHOUHIZEI_RATE
FROM
	dbo.T_UKEIRE_ENTRY AS UE
LEFT JOIN
	dbo.T_UKEIRE_DETAIL AS UD ON ((UE.SYSTEM_ID = UD.SYSTEM_ID) AND (UE.SEQ = UD.SEQ))
LEFT JOIN
	dbo.M_TORIHIKI_KBN ON UE.SHIHARAI_TORIHIKI_KBN_CD = dbo.M_TORIHIKI_KBN.TORIHIKI_KBN_CD
LEFT JOIN
	dbo.M_GYOUSHA ON UE.GYOUSHA_CD = dbo.M_GYOUSHA.GYOUSHA_CD
LEFT JOIN
	dbo.M_GENBA ON ((dbo.M_GENBA.GYOUSHA_CD = UE.GYOUSHA_CD) AND (dbo.M_GENBA.GENBA_CD = UE.GENBA_CD))
LEFT JOIN
	dbo.M_HINMEI ON UD.HINMEI_CD = dbo.M_HINMEI.HINMEI_CD
LEFT JOIN
	dbo.M_UNIT ON UD.UNIT_CD = dbo.M_UNIT.UNIT_CD
LEFT JOIN
	dbo.M_TORIHIKISAKI ON UE.TORIHIKISAKI_CD = dbo.M_TORIHIKISAKI.TORIHIKISAKI_CD
WHERE
	(UD.DENPYOU_KBN_CD = 2) AND (UE.DELETE_FLG = 0) AND (UE.TAIRYUU_KBN = 0)
/*IF startCD != null*/AND UE.TORIHIKISAKI_CD >= /*startCD*//*END*/
/*IF endCD != null*/AND UE.TORIHIKISAKI_CD <= /*endCD*//*END*/
/*IF densyuKbn == '1' && systemID != null*/AND UE.SYSTEM_ID <> /*systemID*//*END*/
  AND UE.SHIHARAI_TORIHIKI_KBN_CD <> 1
/*IF endDay != null*/AND UE.SHIHARAI_DATE <= /*endDay*//*END*/
  AND NOT EXISTS ( 
    SELECT
      1
    FROM
 	  T_SEISAN_DENPYOU SEIE INNER JOIN T_SEISAN_DETAIL SEID ON SEIE.SEISAN_NUMBER = SEID.SEISAN_NUMBER AND SEID.DELETE_FLG = '0'
 	  /*IF startDay != null*/AND SEIE.SEISAN_DATE <= /*startDay*/ /*END*/
    WHERE
      SEID.DENPYOU_SHURUI_CD = 1
      AND SEID.DENPYOU_SYSTEM_ID = UD.SYSTEM_ID 
      AND SEID.DENPYOU_SEQ = UD.SEQ 
	  AND SEID.DETAIL_SYSTEM_ID = UD.DETAIL_SYSTEM_ID)
UNION ALL (
	SELECT DISTINCT
		2 AS DENSHU_KBN,
		CASE WHEN SE.KENSHU_MUST_KBN = 1
		THEN
			SE.KENSHU_SHIHARAI_DATE
		ELSE
			SE.SHIHARAI_DATE
		END
		AS MEISAI_DATE,
		dbo.M_TORIHIKI_KBN.TORIHIKI_KBN_NAME_RYAKU AS TORIHIKI_KBN,
		SE.SHUKKA_NUMBER AS DENPYOU_NUMBER,
		SE.GYOUSHA_CD AS GYOUSHA_CD,
		SE.GENBA_CD AS GENBA_CD,
		dbo.M_GYOUSHA.GYOUSHA_NAME_RYAKU AS GYOUSHA_NAME,
		dbo.M_GENBA.GENBA_NAME_RYAKU AS GENBA_NAME,
		CASE WHEN SE.KENSHU_MUST_KBN = 1
		THEN
			KD.HINMEI_CD
		ELSE
			SD.HINMEI_CD
		END
		AS HINMEI_CD,
		SE.RECEIPT_NUMBER AS SHIHARAI_NUMBER,
		CASE WHEN SE.KENSHU_MUST_KBN = 1
		THEN
			KHINMEI.HINMEI_NAME_RYAKU
		ELSE
			SHINMEI.HINMEI_NAME_RYAKU
		END
		AS HINMEI_NAME,
		'' AS SUURYOU_UNIT,
		CASE WHEN SE.KENSHU_MUST_KBN = 1
		THEN
			KD.SUURYOU
		ELSE
			SD.SUURYOU
		END
		AS SUURYOU,
		CASE WHEN SE.KENSHU_MUST_KBN = 1
		THEN
			KUNIT.UNIT_NAME_RYAKU
		ELSE
			SUNIT.UNIT_NAME_RYAKU
		END
		AS UNIT_NAME_RYAKU,
		CASE WHEN SE.KENSHU_MUST_KBN = 1
		THEN
			KD.TANKA
		ELSE
			SD.TANKA
		END
		AS TANKA,
		CASE WHEN SE.KENSHU_MUST_KBN = 1
		THEN
			(ISNULL(KD.KINGAKU, 0) + ISNULL(KD.HINMEI_KINGAKU, 0))
		ELSE
			(ISNULL(SD.KINGAKU, 0) + ISNULL(SD.HINMEI_KINGAKU, 0))
		END
		AS SHIHARAI_KINGAKU,
		CASE WHEN SE.KENSHU_MUST_KBN = 1
		THEN
			(CASE WHEN ISNULL(KD.HINMEI_ZEI_KBN_CD, 0) = 0 THEN 
				(CASE WHEN SE.SHIHARAI_ZEI_KEISAN_KBN_CD = 3 THEN 
					(CASE SE.SHIHARAI_ZEI_KBN_CD WHEN 1 THEN KD.TAX_SOTO WHEN 2 THEN KD.TAX_UCHI ELSE 0 END)
				ELSE
					0 
				END)
			ELSE
				(CASE KD.HINMEI_ZEI_KBN_CD WHEN 1 THEN KD.HINMEI_TAX_SOTO WHEN 2 THEN KD.HINMEI_TAX_UCHI ELSE 0 END)
			END)
		ELSE
			(CASE WHEN ISNULL(SD.HINMEI_ZEI_KBN_CD, 0) = 0 THEN 
				(CASE WHEN SE.SHIHARAI_ZEI_KEISAN_KBN_CD = 3 THEN 
					(CASE SE.SHIHARAI_ZEI_KBN_CD WHEN 1 THEN SD.TAX_SOTO WHEN 2 THEN SD.TAX_UCHI ELSE 0 END)
				ELSE
					0 
				END)
			ELSE
				(CASE SD.HINMEI_ZEI_KBN_CD WHEN 1 THEN SD.HINMEI_TAX_SOTO WHEN 2 THEN SD.HINMEI_TAX_UCHI ELSE 0 END)
			END)
		END
		AS SHOUHIZEI,
		CASE WHEN SE.KENSHU_MUST_KBN = 1
		THEN
			(CASE WHEN ISNULL(KD.HINMEI_ZEI_KBN_CD, 0) = 0 THEN 
				(CASE WHEN SE.SHIHARAI_ZEI_KEISAN_KBN_CD = 3 THEN 
					(CASE WHEN SE.SHIHARAI_ZEI_KBN_CD = 1 THEN SD.TAX_SOTO ELSE 0 END)
				ELSE
					0 
				END)
			ELSE
				(CASE WHEN KD.HINMEI_ZEI_KBN_CD = 1 THEN KD.HINMEI_TAX_SOTO ELSE 0 END)
			END)
		ELSE
			(CASE WHEN ISNULL(SD.HINMEI_ZEI_KBN_CD, 0) = 0 THEN 
				(CASE WHEN SE.SHIHARAI_ZEI_KEISAN_KBN_CD = 3 THEN 
					(CASE WHEN SE.SHIHARAI_ZEI_KBN_CD = 1 THEN SD.TAX_SOTO ELSE 0 END)
				ELSE
					0 
				END)
			ELSE
				(CASE WHEN SD.HINMEI_ZEI_KBN_CD = 1 THEN SD.HINMEI_TAX_SOTO ELSE 0 END)
			END)
		END
		AS SHOUHI_SOTO_ZEI,
		NULL AS SHUKKIN_KINGAKU,
		NULL AS SASHIHIKI_ZANDAKA,
		SD.MEISAI_BIKOU AS MEISAI_BIKOU,
		SE.TORIHIKISAKI_CD AS TORIHIKISAKI_CD,
		dbo.M_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU AS TORIHIKISAKI_NAME,
		CASE WHEN SE.KENSHU_MUST_KBN = 1
		THEN
			(CASE WHEN SE.SHIHARAI_ZEI_KEISAN_KBN_CD = 1 THEN 
				(CASE SE.SHIHARAI_ZEI_KBN_CD WHEN 1 THEN SE.KENSHU_SHIHARAI_TAX_SOTO WHEN 2 THEN SE.KENSHU_SHIHARAI_TAX_UCHI ELSE 0 END)
			ELSE
				0 
			END)
		ELSE
			(CASE WHEN SE.SHIHARAI_ZEI_KEISAN_KBN_CD = 1 THEN 
				(CASE SE.SHIHARAI_ZEI_KBN_CD WHEN 1 THEN SE.SHIHARAI_TAX_SOTO WHEN 2 THEN SE.SHIHARAI_TAX_UCHI ELSE 0 END)
			ELSE
				0 
			END)
		END
		AS DENPYOU_MAI_ZEI,
		CASE WHEN SE.KENSHU_MUST_KBN = 1
		THEN
			(CASE WHEN SE.SHIHARAI_ZEI_KEISAN_KBN_CD = 1 THEN 
				(CASE WHEN SE.SHIHARAI_ZEI_KBN_CD = 1 THEN SE.KENSHU_SHIHARAI_TAX_SOTO ELSE 0 END)
			ELSE
				0 
			END)
		ELSE
			(CASE WHEN SE.SHIHARAI_ZEI_KEISAN_KBN_CD = 1 THEN 
				(CASE WHEN SE.SHIHARAI_ZEI_KBN_CD = 1 THEN SE.SHIHARAI_TAX_SOTO ELSE 0 END)
			ELSE
				0 
			END)
		END
		AS DENPYOU_MAI_SOTO_ZEI,
		SE.SHIHARAI_ZEI_KEISAN_KBN_CD AS ZEI_KEISAN_KBN_CD,
		SE.SHIHARAI_ZEI_KBN_CD AS ZEI_KBN_CD,
		SD.HINMEI_ZEI_KBN_CD AS HINMEI_ZEI_KBN_CD,
		SE.SHIHARAI_SHOUHIZEI_RATE
	FROM
		dbo.T_SHUKKA_ENTRY AS SE
	LEFT JOIN
		dbo.T_SHUKKA_DETAIL AS SD ON ((SE.SYSTEM_ID = SD.SYSTEM_ID) AND (SE.SEQ = SD.SEQ))
	LEFT JOIN
		dbo.T_KENSHU_DETAIL AS KD ON ((KD.SYSTEM_ID = SD.SYSTEM_ID) AND (KD.SEQ = SD.SEQ) AND KD.DETAIL_SYSTEM_ID = SD.DETAIL_SYSTEM_ID AND KD.ROW_NO = SD.ROW_NO)
	LEFT JOIN
		dbo.M_TORIHIKI_KBN ON SE.SHIHARAI_TORIHIKI_KBN_CD = dbo.M_TORIHIKI_KBN.TORIHIKI_KBN_CD
	LEFT JOIN
		dbo.M_GYOUSHA ON SE.GYOUSHA_CD = dbo.M_GYOUSHA.GYOUSHA_CD
	LEFT JOIN
		dbo.M_GENBA ON ((dbo.M_GENBA.GYOUSHA_CD = SE.GYOUSHA_CD) AND (dbo.M_GENBA.GENBA_CD = SE.GENBA_CD))
	LEFT JOIN
		dbo.M_HINMEI AS SHINMEI ON SD.HINMEI_CD = SHINMEI.HINMEI_CD
	LEFT JOIN
		dbo.M_UNIT AS SUNIT ON SD.UNIT_CD = SUNIT.UNIT_CD
	LEFT JOIN
		dbo.M_TORIHIKISAKI ON SE.TORIHIKISAKI_CD = dbo.M_TORIHIKISAKI.TORIHIKISAKI_CD
	LEFT JOIN
		dbo.M_HINMEI AS KHINMEI ON SD.HINMEI_CD = KHINMEI.HINMEI_CD
	LEFT JOIN
		dbo.M_UNIT AS KUNIT ON SD.UNIT_CD = KUNIT.UNIT_CD
	WHERE
		(SD.DENPYOU_KBN_CD = 2) AND (SE.DELETE_FLG = 0) AND (SE.TAIRYUU_KBN = 0)
	/*IF startCD != null*/AND SE.TORIHIKISAKI_CD >= /*startCD*//*END*/
	/*IF endCD != null*/AND SE.TORIHIKISAKI_CD <= /*endCD*//*END*/
	/*IF densyuKbn == '2' && systemID != null*/AND SE.SYSTEM_ID <> /*systemID*//*END*/
	AND SE.SHIHARAI_TORIHIKI_KBN_CD <> 1
	/*IF endDay != null*/AND SE.SHIHARAI_DATE <= /*endDay*//*END*/
		AND NOT EXISTS ( 
		    SELECT
		      1
		    FROM
		 	  T_SEISAN_DENPYOU SEIE INNER JOIN T_SEISAN_DETAIL SEID ON SEIE.SEISAN_NUMBER = SEID.SEISAN_NUMBER AND SEID.DELETE_FLG = '0'
		 	  /*IF startDay != null*/AND SEIE.SEISAN_DATE <= /*startDay*/ /*END*/
		    WHERE
		      SEID.DENPYOU_SHURUI_CD = 2
		      AND SEID.DENPYOU_SYSTEM_ID = SD.SYSTEM_ID 
		      AND SEID.DENPYOU_SEQ = SD.SEQ 
			  AND SEID.DETAIL_SYSTEM_ID = SD.DETAIL_SYSTEM_ID)
	)
UNION ALL (
	SELECT
		3 AS DENSHU_KBN,
		U_SE.SHIHARAI_DATE AS MEISAI_DATE,
		dbo.M_TORIHIKI_KBN.TORIHIKI_KBN_NAME_RYAKU AS TORIHIKI_KBN,
		U_SE.UR_SH_NUMBER AS DENPYOU_NUMBER,
		U_SE.GYOUSHA_CD AS GYOUSHA_CD,
		U_SE.GENBA_CD AS GENBA_CD,
		dbo.M_GYOUSHA.GYOUSHA_NAME_RYAKU AS GYOUSHA_NAME,
		dbo.M_GENBA.GENBA_NAME_RYAKU AS GENBA_NAME,
		U_SD.HINMEI_CD AS HINMEI_CD,
		U_SE.RECEIPT_NUMBER AS SHIHARAI_NUMBER,
		dbo.M_HINMEI.HINMEI_NAME_RYAKU AS HINMEI_NAME,
		'' AS SUURYOU_UNIT,
		U_SD.SUURYOU AS SUURYOU,
		dbo.M_UNIT.UNIT_NAME_RYAKU AS UNIT_NAME_RYAKU,
		U_SD.TANKA AS TANKA,
		(ISNULL(U_SD.KINGAKU, 0) + ISNULL(U_SD.HINMEI_KINGAKU, 0)) AS SHIHARAI_KINGAKU,
		(CASE WHEN ISNULL(U_SD.HINMEI_ZEI_KBN_CD, 0) = 0 THEN 
			(CASE WHEN U_SE.SHIHARAI_ZEI_KEISAN_KBN_CD = 3 THEN 
				(CASE U_SE.SHIHARAI_ZEI_KBN_CD WHEN 1 THEN U_SD.TAX_SOTO WHEN 2 THEN U_SD.TAX_UCHI ELSE 0 END)
			ELSE
				0 
			END)
		ELSE
			(CASE U_SD.HINMEI_ZEI_KBN_CD WHEN 1 THEN U_SD.HINMEI_TAX_SOTO WHEN 2 THEN U_SD.HINMEI_TAX_UCHI ELSE 0 END)
		END) AS SHOUHIZEI,
		(CASE WHEN ISNULL(U_SD.HINMEI_ZEI_KBN_CD, 0) = 0 THEN 
			(CASE WHEN U_SE.SHIHARAI_ZEI_KEISAN_KBN_CD = 3 THEN 
				(CASE WHEN U_SE.SHIHARAI_ZEI_KBN_CD = 1 THEN U_SD.TAX_SOTO ELSE 0 END)
			ELSE
				0 
			END)
		ELSE
			(CASE WHEN U_SD.HINMEI_ZEI_KBN_CD = 1 THEN U_SD.HINMEI_TAX_SOTO ELSE 0 END)
		END) AS SHOUHI_SOTO_ZEI,
		NULL AS SHUKKIN_KINGAKU,
		NULL AS SASHIHIKI_ZANDAKA,
		U_SD.MEISAI_BIKOU AS MEISAI_BIKOU,
		U_SE.TORIHIKISAKI_CD AS TORIHIKISAKI_CD,
		dbo.M_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU AS TORIHIKISAKI_NAME,
		(CASE WHEN U_SE.SHIHARAI_ZEI_KEISAN_KBN_CD = 1 THEN 
			(CASE U_SE.SHIHARAI_ZEI_KBN_CD WHEN 1 THEN U_SE.SHIHARAI_TAX_SOTO WHEN 2 THEN U_SE.SHIHARAI_TAX_UCHI ELSE 0 END)
		ELSE
			0 
		END) AS DENPYOU_MAI_ZEI,
		(CASE WHEN U_SE.SHIHARAI_ZEI_KEISAN_KBN_CD = 1 THEN 
			(CASE WHEN U_SE.SHIHARAI_ZEI_KBN_CD = 1 THEN U_SE.SHIHARAI_TAX_SOTO ELSE 0 END)
		ELSE
			0 
		END) AS DENPYOU_MAI_SOTO_ZEI,
		U_SE.SHIHARAI_ZEI_KEISAN_KBN_CD AS ZEI_KEISAN_KBN_CD,
		U_SE.SHIHARAI_ZEI_KBN_CD AS ZEI_KBN_CD,
		U_SD.HINMEI_ZEI_KBN_CD AS HINMEI_ZEI_KBN_CD,
		U_SE.SHIHARAI_SHOUHIZEI_RATE
	FROM
		dbo.T_UR_SH_ENTRY AS U_SE
	LEFT JOIN
		dbo.T_UR_SH_DETAIL AS U_SD ON ((U_SE.SYSTEM_ID = U_SD.SYSTEM_ID) AND (U_SE.SEQ = U_SD.SEQ))
	LEFT JOIN
		dbo.M_TORIHIKI_KBN ON U_SE.SHIHARAI_TORIHIKI_KBN_CD = dbo.M_TORIHIKI_KBN.TORIHIKI_KBN_CD
	LEFT JOIN
		dbo.M_GYOUSHA ON U_SE.GYOUSHA_CD = dbo.M_GYOUSHA.GYOUSHA_CD
	LEFT JOIN
		dbo.M_GENBA ON ((dbo.M_GENBA.GYOUSHA_CD = U_SE.GYOUSHA_CD) AND (dbo.M_GENBA.GENBA_CD = U_SE.GENBA_CD))
	LEFT JOIN
		dbo.M_HINMEI ON U_SD.HINMEI_CD = dbo.M_HINMEI.HINMEI_CD
	LEFT JOIN
		dbo.M_UNIT ON U_SD.UNIT_CD = dbo.M_UNIT.UNIT_CD
	LEFT JOIN
		dbo.M_TORIHIKISAKI ON U_SE.TORIHIKISAKI_CD = dbo.M_TORIHIKISAKI.TORIHIKISAKI_CD
	WHERE
		(U_SD.DENPYOU_KBN_CD = 2) AND (U_SE.DELETE_FLG = 0) 
	/*IF startCD != null*/AND U_SE.TORIHIKISAKI_CD >= /*startCD*//*END*/
	/*IF endCD != null*/AND U_SE.TORIHIKISAKI_CD <= /*endCD*//*END*/
	/*IF densyuKbn == '3' && systemID != null*/AND U_SE.SYSTEM_ID <> /*systemID*//*END*/
	AND U_SE.SHIHARAI_TORIHIKI_KBN_CD <> 1
	/*IF endDay != null*/AND U_SE.SHIHARAI_DATE <= /*endDay*//*END*/
		AND NOT EXISTS ( 
		    SELECT
		      1
		    FROM
		 	  T_SEISAN_DENPYOU SEIE INNER JOIN T_SEISAN_DETAIL SEID ON SEIE.SEISAN_NUMBER = SEID.SEISAN_NUMBER AND SEID.DELETE_FLG = '0'
		 	  /*IF startDay != null*/AND SEIE.SEISAN_DATE <= /*startDay*/ /*END*/
		    WHERE
		      SEID.DENPYOU_SHURUI_CD = 3
		      AND SEID.DENPYOU_SYSTEM_ID = U_SD.SYSTEM_ID 
		      AND SEID.DENPYOU_SEQ = U_SD.SEQ 
			  AND SEID.DETAIL_SYSTEM_ID = U_SD.DETAIL_SYSTEM_ID)
	)
UNION ALL (
	SELECT
		20 AS DENSHU_KBN,
		SHE.DENPYOU_DATE AS MEISAI_DATE,
		'o‹à' AS TORIHIKI_KBN,
		SHE.SHUKKIN_NUMBER AS DENPYOU_NUMBER,
		'' AS GYOUSHA_CD,
		'' AS GENBA_CD,
		'' AS GYOUSHA_NAME,
		'' AS GENBA_NAME,
		'' AS HINMEI_CD,
		NULL AS SHIHARAI_NUMBER,
		dbo.M_NYUUSHUKKIN_KBN.NYUUSHUKKIN_KBN_NAME_RYAKU AS HINMEI_NAME,
		'' AS SUURYOU_UNIT,
		NULL AS SUURYOU,
		'' AS UNIT_NAME_RYAKU,
		NULL AS TANKA,
		NULL AS SHIHARAI_KINGAKU,
		NULL AS SHOUHIZEI,
		NULL AS SHOUHI_SOTO_ZEI,
		ISNULL(SHD.KINGAKU, 0) AS SHUKKIN_KINGAKU,
		NULL AS SASHIHIKI_ZANDAKA,
		SHD.MEISAI_BIKOU AS MEISAI_BIKOU,
		SHE.TORIHIKISAKI_CD AS TORIHIKISAKI_CD,
		dbo.M_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU AS TORIHIKISAKI_NAME,
		NULL AS DENPYOU_MAI_ZEI,
		NULL AS DENPYOU_MAI_SOTO_ZEI,
		NULL AS ZEI_KEISAN_KBN_CD,
		NULL AS ZEI_KBN_CD,
		NULL AS HINMEI_ZEI_KBN_CD,
		0 AS SHIHARAI_SHOUHIZEI_RATE
	FROM
		dbo.T_SHUKKIN_ENTRY AS SHE
	LEFT JOIN
		dbo.T_SHUKKIN_DETAIL AS SHD ON ((SHE.SYSTEM_ID = SHD.SYSTEM_ID) AND (SHE.SEQ = SHD.SEQ))
	LEFT JOIN
		dbo.M_NYUUSHUKKIN_KBN ON SHD.NYUUSHUKKIN_KBN_CD = dbo.M_NYUUSHUKKIN_KBN.NYUUSHUKKIN_KBN_CD
	LEFT JOIN
		dbo.M_TORIHIKISAKI ON SHE.TORIHIKISAKI_CD = dbo.M_TORIHIKISAKI.TORIHIKISAKI_CD
	WHERE (SHE.DELETE_FLG = 0) 
	/*IF startCD != null*/AND SHE.TORIHIKISAKI_CD >= /*startCD*//*END*/
	/*IF endCD != null*/AND SHE.TORIHIKISAKI_CD <= /*endCD*//*END*/
	/*IF endDay != null*/AND SHE.DENPYOU_DATE <= /*endDay*//*END*/
		AND NOT EXISTS ( 
		    SELECT
		      1
		    FROM
		 	  T_SEISAN_DENPYOU SEIE INNER JOIN T_SEISAN_DETAIL SEID ON SEIE.SEISAN_NUMBER = SEID.SEISAN_NUMBER AND SEID.DELETE_FLG = '0'
		 	  /*IF startDay != null*/AND SEIE.SEISAN_DATE <= /*startDay*/ /*END*/
		    WHERE
		      SEID.DENPYOU_SHURUI_CD = 20
		      AND SEID.DENPYOU_SYSTEM_ID = SHD.SYSTEM_ID 
		      AND SEID.DENPYOU_SEQ = SHD.SEQ 
			  AND SEID.DETAIL_SYSTEM_ID = SHD.DETAIL_SYSTEM_ID)
	)
ORDER BY TORIHIKISAKI_CD, SHIHARAI_SHOUHIZEI_RATE, MEISAI_DATE, DENPYOU_NUMBER, DENSHU_KBN
