SELECT * FROM dbo.M_TORIHIKISAKI
WHERE 
((TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= TEKIYOU_END) or (TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and TEKIYOU_END IS NULL) or (TEKIYOU_BEGIN IS NULL and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= TEKIYOU_END) or (TEKIYOU_BEGIN IS NULL and TEKIYOU_END IS NULL))
AND DELETE_FLG = 0 
/*IF startCD != null*/AND TORIHIKISAKI_CD >= /*startCD*//*END*/
/*IF endCD != null*/AND TORIHIKISAKI_CD <= /*endCD*//*END*/
ORDER BY TORIHIKISAKI_CD
