//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shougun.Core.Scale.KeiryouIchiran.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_KYOTEN_CD {
            get {
                return ((string)(this["SET_KYOTEN_CD"]));
            }
            set {
                this["SET_KYOTEN_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HIDUKE_TO {
            get {
                return ((string)(this["SET_HIDUKE_TO"]));
            }
            set {
                this["SET_HIDUKE_TO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HIDUKE_FROM {
            get {
                return ((string)(this["SET_HIDUKE_FROM"]));
            }
            set {
                this["SET_HIDUKE_FROM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_TORIHIKISAKI_CD {
            get {
                return ((string)(this["SET_TORIHIKISAKI_CD"]));
            }
            set {
                this["SET_TORIHIKISAKI_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_GYOUSHA_CD {
            get {
                return ((string)(this["SET_GYOUSHA_CD"]));
            }
            set {
                this["SET_GYOUSHA_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_GENBA_CD {
            get {
                return ((string)(this["SET_GENBA_CD"]));
            }
            set {
                this["SET_GENBA_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_UNPAN_GYOUSHA_CD {
            get {
                return ((string)(this["SET_UNPAN_GYOUSHA_CD"]));
            }
            set {
                this["SET_UNPAN_GYOUSHA_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_KIHON_KEIRYOU_CD {
            get {
                return ((string)(this["SET_KIHON_KEIRYOU_CD"]));
            }
            set {
                this["SET_KIHON_KEIRYOU_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_KEIRYOU_KBN_CD {
            get {
                return ((string)(this["SET_KEIRYOU_KBN_CD"]));
            }
            set {
                this["SET_KEIRYOU_KBN_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_KEIRYOU_JYOUKYOU_CD {
            get {
                return ((string)(this["SET_KEIRYOU_JYOUKYOU_CD"]));
            }
            set {
                this["SET_KEIRYOU_JYOUKYOU_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_SHASHU_CD {
            get {
                return ((string)(this["SET_SHASHU_CD"]));
            }
            set {
                this["SET_SHASHU_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_SHARYOU_CD {
            get {
                return ((string)(this["SET_SHARYOU_CD"]));
            }
            set {
                this["SET_SHARYOU_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tadasigaki {
            get {
                return ((string)(this["tadasigaki"]));
            }
            set {
                this["tadasigaki"] = value;
            }
        }
    }
}
