SELECT DISTINCT MC.COURSE_NAME_CD, MCN.COURSE_NAME_RYAKU
FROM M_COURSE_NAME MCN
INNER JOIN M_COURSE MC
ON MC.COURSE_NAME_CD = MCN.COURSE_NAME_CD
AND MC.DELETE_FLG = 0
LEFT JOIN T_TEIKI_HAISHA_ENTRY TTHE
ON TTHE.COURSE_NAME_CD = MCN.COURSE_NAME_CD
WHERE
MCN.DELETE_FLG = 0
AND TTHE.DELETE_FLG = 0
/*IF data.TEIKI_HAISHA_NUMBER != null && data.TEIKI_HAISHA_NUMBER != ''*/
AND TTHE.TEIKI_HAISHA_NUMBER = /*data.TEIKI_HAISHA_NUMBER*/
/*END*/