SELECT TTHE.TEIKI_HAISHA_NUMBER, TTHE.COURSE_NAME_CD, MCN.COURSE_NAME_RYAKU
/*IF !data.POPFLG*/
, TTHE.SAGYOU_DATE
/*END*/
FROM T_TEIKI_HAISHA_ENTRY TTHE
LEFT JOIN M_COURSE_NAME MCN
ON TTHE.COURSE_NAME_CD = MCN.COURSE_NAME_CD
WHERE
TTHE.DELETE_FLG = 0
/*IF data.TEIKI_HAISHA_NUMBER != null && data.TEIKI_HAISHA_NUMBER != ''*/
AND TTHE.TEIKI_HAISHA_NUMBER = /*data.TEIKI_HAISHA_NUMBER*/
/*END*/
/*IF data.COURSE_NAME_CD != null && data.COURSE_NAME_CD != ''*/
AND TTHE.COURSE_NAME_CD = /*data.COURSE_NAME_CD*/
/*END*/