//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shougun.Core.BusinessManagement.TorihikisakiKakunin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shougun.Core.BusinessManagement.TorihikisakiKakunin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CODE {
            get {
                return ResourceManager.GetString("CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入金先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NYUUKINSAKI {
            get {
                return ResourceManager.GetString("NYUUKINSAKI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入金先CD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NYUUKINSAKI_CD {
            get {
                return ResourceManager.GetString("NYUUKINSAKI_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出金先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SYUKKINSAKI {
            get {
                return ResourceManager.GetString("SYUKKINSAKI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出金先CD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SYUKKINSAKI_CD {
            get {
                return ResourceManager.GetString("SYUKKINSAKI_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取引先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TORIHIKISAKI {
            get {
                return ResourceManager.GetString("TORIHIKISAKI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取引先CD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TORIHIKISAKI_CD {
            get {
                return ResourceManager.GetString("TORIHIKISAKI_CD", resourceCulture);
            }
        }
    }
}
