SELECT
GYOUSHA_CD,
GYOUSHA_NAME_RYAKU,
SHOKUCHI_KBN,
GYOUSHA_POST,
GYOUSHA_ADDRESS1,
GYOUSHA_ADDRESS2,
TANTOUSHA,
GYOUSHA_TEL,
GYOUSHA_KEITAI_TEL
FROM
M_HIKIAI_GYOUSHA
/*BEGIN*/WHERE
/*IF !deletechuFlg*/ DELETE_FLG = 0/*END*/
/*IF data.GYOUSHA_CD != null*/
AND GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/
AND ((TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= TEKIYOU_END) or (TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and TEKIYOU_END IS NULL) or (TEKIYOU_BEGIN IS NULL and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= TEKIYOU_END) or (TEKIYOU_BEGIN IS NULL and TEKIYOU_END IS NULL))
/*END*/
ORDER BY GYOUSHA_CD