SELECT
GENBA_CD,
GENBA_NAME_RYAKU,
SHOKUCHI_KBN,
GENBA_POST,
GENBA_ADDRESS1,
GENBA_ADDRESS2,
TANTOUSHA,
GENBA_TEL,
GENBA_KEITAI_TEL
FROM
M_HIKIAI_GENBA
/*BEGIN*/WHERE
/*IF !deletechuFlg*/ DELETE_FLG = 0/*END*/
/*IF data.GENBA_CD != null*/
AND GENBA_CD = /*data.GENBA_CD*//*END*/
AND GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/
AND ((TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= TEKIYOU_END) or (TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and TEKIYOU_END IS NULL) or (TEKIYOU_BEGIN IS NULL and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= TEKIYOU_END) or (TEKIYOU_BEGIN IS NULL and TEKIYOU_END IS NULL))
/*END*/
