SELECT
KYOTEN_CD,
KYOTEN_NAME_RYAKU
FROM
M_KYOTEN
/*BEGIN*/WHERE
/*IF !deletechuFlg*/ DELETE_FLG = 0/*END*/
/*IF data.KYOTEN_CD != null*/
AND KYOTEN_CD = /*data.KYOTEN_CD*//*END*/
/*END*/
ORDER BY KYOTEN_CD