SELECT 
T_MITSUMORI_DETAIL.SYSTEM_ID,
T_MITSUMORI_DETAIL.SEQ,
T_MITSUMORI_DETAIL.PAGE_SYSTEM_ID,
T_MITSUMORI_DETAIL.DETAIL_SYSTEM_ID, 
T_MITSUMORI_DETAIL.DENPYOU_NUMBER,
T_MITSUMORI_DETAIL.PAGE_NUMBER,
T_MITSUMORI_DETAIL.ROW_NO,
T_MITSUMORI_DETAIL.DENPYOU_KBN_CD, 
T_MITSUMORI_DETAIL.HINMEI_CD,
T_MITSUMORI_DETAIL.HINMEI_NAME,
T_MITSUMORI_DETAIL.NET_JYUURYOU,
T_MITSUMORI_DETAIL.SUURYOU, 
T_MITSUMORI_DETAIL.UNIT_CD,
T_MITSUMORI_DETAIL.TANKA,
T_MITSUMORI_DETAIL.KINGAKU,
T_MITSUMORI_DETAIL.TAX_SOTO,
T_MITSUMORI_DETAIL.TAX_UCHI, 
T_MITSUMORI_DETAIL.HINMEI_ZEI_KBN_CD,
T_MITSUMORI_DETAIL.HINMEI_KINGAKU,
T_MITSUMORI_DETAIL.HINMEI_TAX_SOTO,
T_MITSUMORI_DETAIL.HINMEI_TAX_UCHI, 
T_MITSUMORI_DETAIL.MEISAI_BIKOU,
T_MITSUMORI_DETAIL.MEISAI_TEKIYO,
M_HINMEI.ZEI_KBN_CD, 
M_UNIT.UNIT_NAME,
M_DENPYOU_KBN.DENPYOU_KBN_NAME_RYAKU
FROM T_MITSUMORI_DETAIL 
LEFT JOIN M_UNIT 
    ON T_MITSUMORI_DETAIL.UNIT_CD = M_UNIT.UNIT_CD 
LEFT JOIN M_HINMEI 
    ON T_MITSUMORI_DETAIL.HINMEI_CD = M_HINMEI.HINMEI_CD
LEFT JOIN M_DENPYOU_KBN
    ON T_MITSUMORI_DETAIL.DENPYOU_KBN_CD = M_DENPYOU_KBN.DENPYOU_KBN_CD
WHERE
T_MITSUMORI_DETAIL.DENPYOU_NUMBER = /*data.DENPYOU_NUMBER.Value*/
