SELECT
SHOUHIZEI_RATE
FROM
M_SHOUHIZEI
/*BEGIN*/WHERE
/*IF !deletechuFlg*/ DELETE_FLG = 0/*END*/
AND (TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, /*data*/, 111), 120) and CONVERT(DATETIME, CONVERT(nvarchar,/*data*/, 111), 120) <= TEKIYOU_END)
/*END*/