SELECT
TORIHIKISAKI_CD,
TORIHIKISAKI_NAME_RYAKU,
SHOKUCHI_KBN,
TORIHIKISAKI_POST,
TORIHIKISAKI_ADDRESS1,
TORIHIKISAKI_ADDRESS2,
TANTOUSHA,
TORIHIKISAKI_TEL
FROM
M_TORIHIKISAKI
/*BEGIN*/WHERE
/*IF !deletechuFlg*/ DELETE_FLG = 0/*END*/
/*IF data.TORIHIKISAKI_CD != null*/
AND TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*//*END*/
AND ((TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= TEKIYOU_END) or (TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and TEKIYOU_END IS NULL) or (TEKIYOU_BEGIN IS NULL and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= TEKIYOU_END) or (TEKIYOU_BEGIN IS NULL and TEKIYOU_END IS NULL))
/*END*/
ORDER BY TORIHIKISAKI_CD