SELECT * FROM dbo.T_MITSUMORI_ENTRY
WHERE DELETE_FLG = 0 
/*IF !data.SYSTEM_ID.IsNull*/AND SYSTEM_ID = /*data.SYSTEM_ID.Value*//*END*/
/*IF !data.SEQ.IsNull*/AND SEQ = /*data.SEQ.Value*//*END*/
/*IF !data.KEIRYOU_NUMBER.IsNull*/AND MITSUMORI_NUMBER = /*data.MITSUMORI_NUMBER.Value*//*END*/
ORDER BY SEQ DESC