SELECT S.SHARYOU_CD
--     , S.SHARYOU_NAME
     , S.SHARYOU_NAME_RYAKU
	 , S.SHASYU_CD
	 , SS.SHASHU_NAME_RYAKU
	 , S.GYOUSHA_CD
  FROM M_SHARYOU S
  LEFT JOIN M_SHASHU SS 
    ON SS.SHASHU_CD = S.SHASYU_CD
  LEFT JOIN M_GYOUSHA GS 
    ON GS.GYOUSHA_CD = S.GYOUSHA_CD
 WHERE S.DELETE_FLG = 'false'
   AND GS.DELETE_FLG = 'false'
   AND GS.UNPAN_JUTAKUSHA_KAISHA_KBN = 1
   AND GS.GYOUSHAKBN_MANI = 1
   AND S.SHARYOU_CD = /*data.SHARYOU_CD*/
/*IF data.GYOUSHA_CD != null && data.GYOUSHA_CD != ''*/ AND S.GYOUSHA_CD = /*data.GYOUSHA_CD*/ /*END*/
/*IF data.SHASYU_CD != null && data.SHASYU_CD != ''*/ AND S.SHASYU_CD = /*data.SHASYU_CD*/ /*END*/
/*IF !KOFU_DATE.IsNull*/ 
    AND (((GS.TEKIYOU_BEGIN <= CONVERT(DATETIME, /*KOFU_DATE*/, 120) AND CONVERT(DATETIME, /*KOFU_DATE*/, 120) <= GS.TEKIYOU_END) OR (GS.TEKIYOU_BEGIN <= CONVERT(DATETIME, /*KOFU_DATE*/, 120) AND GS.TEKIYOU_END IS NULL) OR (GS.TEKIYOU_BEGIN IS NULL AND CONVERT(DATETIME, /*KOFU_DATE*/, 120) <= GS.TEKIYOU_END) OR (GS.TEKIYOU_BEGIN IS NULL AND GS.TEKIYOU_END IS NULL)) AND GS.DELETE_FLG <> 1) /*END*/
/*IF KOFU_DATE.IsNull*/ 
    AND (((GS.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) AND CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= GS.TEKIYOU_END) OR (GS.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) AND GS.TEKIYOU_END IS NULL) OR (GS.TEKIYOU_BEGIN IS NULL AND CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= GS.TEKIYOU_END) OR (GS.TEKIYOU_BEGIN IS NULL AND GS.TEKIYOU_END IS NULL)) AND GS.DELETE_FLG <> 1) /*END*/