/* 20140513 ria No.679 伝種区分連携 start*/
SELECT
TKE.DENPYOU_DATE as KOUFU_DATE,
TKE.TORIHIKISAKI_CD as TORIHIKISAKI_CD,
TKE.TORIHIKISAKI_NAME as TORIHIKISAKI_NAME,
TKE.HST_GYOUSHA_CD as HAISYUTU_GYOUSHA_CD,
TKE.HST_GENBA_CD as HAISYUTU_GENBA_CD,
TKE.UNPAN_GYOUSHA_CD as UNPAN_GYOUSHA_CD,
TKE.UNPAN_GYOUSHA_NAME as UNPAN_GYOUSHA_NAME,
TKE.SBN_GYOUSHA_CD as SYOBUN_GYOUSHA_CD,
TKE.SBN_GENBA_CD as UNPAN_GENBA_CD,
TKE.SHASHU_CD as SHASHU_CD,
TKE.SHASHU_NAME as SHASHU_NAME,
TKE.SHARYOU_CD as SHARYOU_CD,
TKE.SHARYOU_NAME as SHARYOU_NAME,
TKE.UNTENSHA_CD as UNTENSHA_CD,
TKE.UNTENSHA_NAME as UNTENSHA_NAME,
TKE.NIOROSHI_GYOUSHA_CD as NIOROSHI_GYOUSHA_CD,
TKE.NIOROSHI_GYOUSHA_NAME as NIOROSHI_GYOUSHA_NAME,
TKE.DENPYOU_DATE as UNPAN_SYURYOU_DATA,
TKE.NIZUMI_GYOUSHA_CD as NIZUMI_GYOUSHA_CD,
TKE.NIZUMI_GYOUSHA_NAME as NIZUMI_GYOUSHA_NAME,
TKE.NIZUMI_GENBA_CD as NIZUMI_GENBA_CD,
TKE.NIZUMI_GENBA_NAME as NIZUMI_GENBA_NAME,
MHS.HAIKI_SHURUI_CD as HAIKI_SHURUI_CD,
MHS.HAIKI_SHURUI_NAME_RYAKU as HAIKI_SHURUI_NAME_RYAKU,
TKE.LAST_SBN_GYOUSHA_CD as LAST_SBN_GYOUSHA_CD,
MG.GYOUSHA_NAME_RYAKU as LAST_SBN_GYOUSHA_NAME,
TKE.LAST_SBN_GENBA_CD as LAST_SBN_GENBA_CD,
MGA.GENBA_NAME_RYAKU as LAST_SBN_GENBA_NAME,
TKE.SYSTEM_ID as SYSTEM_ID,
TKD.DETAIL_SYSTEM_ID as DETAIL_SYSTEM_ID,
TKE.MANIFEST_SHURUI_CD as MANIFEST_SHURUI_CD,
TKE.KIHON_KEIRYOU
FROM 
(SELECT TOP 1 TKE.* FROM T_KEIRYOU_ENTRY TKE
left join T_KEIRYOU_DETAIL TKD ON (TKE.SYSTEM_ID = TKD.SYSTEM_ID AND TKE.SEQ = TKD.SEQ)
WHERE TKE.KEIRYOU_NUMBER = /*data.RENKEI_ID*/0
AND TKE.DELETE_FLG = 0
/*IF data.RENKEI_MEISAI_ID != NULL && data.RENKEI_MEISAI_ID != ''*/
AND TKD.ROW_NO = /*data.RENKEI_MEISAI_ID*/0
/*END*/ )    TKE
left join T_KEIRYOU_DETAIL TKD ON (TKE.SYSTEM_ID = TKD.SYSTEM_ID AND TKE.SEQ = TKD.SEQ)
left join M_HINMEI MH ON (MH.HINMEI_CD = TKD.HINMEI_CD
                       AND MH.DELETE_FLG = 0)
left join M_HAIKI_SHURUI MHS ON (MHS.HAIKI_SHURUI_CD = MH.SP_CHOKKOU_HAIKI_SHURUI_CD
                              AND MHS.HAIKI_KBN_CD = 1
                              AND MHS.DELETE_FLG = 0 )
left join M_GYOUSHA MG ON (MG.GYOUSHA_CD = TKE.LAST_SBN_GYOUSHA_CD)
left join M_GENBA MGA ON (MGA.GYOUSHA_CD = TKE.LAST_SBN_GYOUSHA_CD
                       AND MGA.GENBA_CD = TKE.LAST_SBN_GENBA_CD)
WHERE TKE.KEIRYOU_NUMBER = /*data.RENKEI_ID*/0
AND TKE.DELETE_FLG = 0
/*IF data.RENKEI_MEISAI_ID != NULL && data.RENKEI_MEISAI_ID != ''*/
AND TKD.ROW_NO = /*data.RENKEI_MEISAI_ID*/0
/*END*/
/* 20140513 ria No.679 伝種区分連携 end*/
