/* 20140513 ria No.679 伝種区分連携 start*/
SELECT
TSE.DENPYOU_DATE as KOUFU_DATE,
TSE.TORIHIKISAKI_CD as TORIHIKISAKI_CD,
TSE.TORIHIKISAKI_NAME as TORIHIKISAKI_NAME,
TSE.NIZUMI_GYOUSHA_CD as HAISYUTU_GYOUSHA_CD,
TSE.NIZUMI_GYOUSHA_NAME as GYOUSHA_NAME,
TSE.NIZUMI_GENBA_CD as HAISYUTU_GENBA_CD,
TSE.NIZUMI_GENBA_NAME as GENBA_NAME,
TSE.UNPAN_GYOUSHA_CD as UNPAN_GYOUSHA_CD,
TSE.UNPAN_GYOUSHA_NAME as UNPAN_GYOUSHA_NAME,
TSE.GYOUSHA_CD as SYOBUN_GYOUSHA_CD,
TSE.GYOUSHA_NAME as SYOBUN_GYOUSHA_NAME,
TSE.GENBA_CD as UNPAN_GENBA_CD,
TSE.GENBA_NAME as NIOROSHI_GENBA_NAME,
TSE.SHASHU_CD as SHASHU_CD,
TSE.SHASHU_NAME as SHASHU_NAME,
TSE.SHARYOU_CD as SHARYOU_CD,
TSE.SHARYOU_NAME as SHARYOU_NAME,
TSE.UNTENSHA_CD as UNTENSHA_CD,
TSE.UNTENSHA_NAME as UNTENSHA_NAME,
TSE.GYOUSHA_CD as NIOROSHI_GYOUSHA_CD,
TSE.GYOUSHA_NAME as NIOROSHI_GYOUSHA_NAME,
TSE.DENPYOU_DATE as UNPAN_SYURYOU_DATA,
MHS.HAIKI_SHURUI_CD as HAIKI_SHURUI_CD,
MHS.HAIKI_SHURUI_NAME_RYAKU as HAIKI_SHURUI_NAME_RYAKU,
TSE.SYSTEM_ID as SYSTEM_ID,
TSD.DETAIL_SYSTEM_ID as DETAIL_SYSTEM_ID,
TSE.MANIFEST_SHURUI_CD as MANIFEST_SHURUI_CD
FROM 
(SELECT TOP 1 TSE.* FROM T_SHUKKA_ENTRY TSE
left join T_SHUKKA_DETAIL TSD ON (TSE.SYSTEM_ID = TSD.SYSTEM_ID AND TSE.SEQ = TSD.SEQ)
WHERE TSE.SHUKKA_NUMBER = /*data.RENKEI_ID*/0 
AND TSE.DELETE_FLG = 0
/*IF data.RENKEI_MEISAI_ID != NULL && data.RENKEI_MEISAI_ID != ''*/
AND TSD.ROW_NO = /*data.RENKEI_MEISAI_ID*/0
/*END*/
) TSE
left join T_SHUKKA_DETAIL TSD ON (TSE.SYSTEM_ID = TSD.SYSTEM_ID AND TSE.SEQ = TSD.SEQ)
left join M_HINMEI MH ON (MH.HINMEI_CD = TSD.HINMEI_CD)
left join M_HAIKI_SHURUI MHS ON (MHS.HAIKI_SHURUI_CD = MH.SP_CHOKKOU_HAIKI_SHURUI_CD
                              AND MHS.HAIKI_KBN_CD = 1)
WHERE TSE.SHUKKA_NUMBER = /*data.RENKEI_ID*/0 
AND TSE.DELETE_FLG = 0
/*IF data.RENKEI_MEISAI_ID != NULL && data.RENKEI_MEISAI_ID != ''*/
AND TSD.ROW_NO = /*data.RENKEI_MEISAI_ID*/0
/*END*/
/* 20140513 ria No.679 伝種区分連携 end*/

