/* 20140513 ria No.679 伝種区分連携 start*/
SELECT
TUE.DENPYOU_DATE as KOUFU_DATE,
TUE.TORIHIKISAKI_CD as TORIHIKISAKI_CD,
TUE.TORIHIKISAKI_NAME as TORIHIKISAKI_NAME,
TUE.GYOUSHA_CD as HAISYUTU_GYOUSHA_CD,
TUE.GYOUSHA_NAME as GYOUSHA_NAME,
TUE.GENBA_CD as HAISYUTU_GENBA_CD,
TUE.GENBA_NAME as GENBA_NAME,
TUE.UNPAN_GYOUSHA_CD as UNPAN_GYOUSHA_CD,
TUE.UNPAN_GYOUSHA_NAME as UNPAN_GYOUSHA_NAME,
TUE.NIOROSHI_GYOUSHA_CD as SYOBUN_GYOUSHA_CD,
TUE.NIOROSHI_GYOUSHA_NAME as SYOBUN_GYOUSHA_NAME,
TUE.NIOROSHI_GENBA_CD as UNPAN_GENBA_CD,
TUE.NIOROSHI_GENBA_NAME as NIOROSHI_GENBA_NAME,
TUE.SHASHU_CD as SHASHU_CD,
TUE.SHASHU_NAME as SHASHU_NAME,
TUE.SHARYOU_CD as SHARYOU_CD,
TUE.SHARYOU_NAME as SHARYOU_NAME,
TUE.UNTENSHA_CD as UNTENSHA_CD,
TUE.UNTENSHA_NAME as UNTENSHA_NAME,
TUE.NIOROSHI_GYOUSHA_CD as NIOROSHI_GYOUSHA_CD,
TUE.NIOROSHI_GYOUSHA_NAME as NIOROSHI_GYOUSHA_NAME,
TUE.DENPYOU_DATE as UNPAN_SYURYOU_DATA,
MHS.HAIKI_SHURUI_CD as HAIKI_SHURUI_CD,
MHS.HAIKI_SHURUI_NAME_RYAKU as HAIKI_SHURUI_NAME_RYAKU,
TUE.SYSTEM_ID as SYSTEM_ID,
TUD.DETAIL_SYSTEM_ID as DETAIL_SYSTEM_ID,
TUE.MANIFEST_SHURUI_CD as MANIFEST_SHURUI_CD
FROM 
(SELECT TOP 1 TUE.* FROM T_UKEIRE_ENTRY TUE
 left join T_UKEIRE_DETAIL TUD ON (TUE.SYSTEM_ID = TUD.SYSTEM_ID AND TUE.SEQ = TUD.SEQ) 
 WHERE TUE.UKEIRE_NUMBER =  /*data.RENKEI_ID*/0
 AND TUE.DELETE_FLG = 0 
 /*IF data.RENKEI_MEISAI_ID != NULL && data.RENKEI_MEISAI_ID != ''*/
 AND TUD.ROW_NO = /*data.RENKEI_MEISAI_ID*/0
 /*END*/
 ) TUE
left join T_UKEIRE_DETAIL TUD ON (TUE.SYSTEM_ID = TUD.SYSTEM_ID AND TUE.SEQ = TUD.SEQ)
left join M_HINMEI MH ON (MH.HINMEI_CD = TUD.HINMEI_CD)
left join M_HAIKI_SHURUI MHS ON (MHS.HAIKI_SHURUI_CD = MH.SP_CHOKKOU_HAIKI_SHURUI_CD
                              AND MHS.HAIKI_KBN_CD = 1)
WHERE TUE.UKEIRE_NUMBER =  /*data.RENKEI_ID*/0
AND TUE.DELETE_FLG = 0 
/*IF data.RENKEI_MEISAI_ID != NULL && data.RENKEI_MEISAI_ID != ''*/
AND TUD.ROW_NO = /*data.RENKEI_MEISAI_ID*/0
/*END*/
/* 20140513 ria No.679 伝種区分連携 end*/