select HAIKI_SHURUI_CD,HAIKI_SHURUI_NAME_RYAKU from M_HAIKI_SHURUI
WHERE 
DELETE_FLG = 0
/*IF data.HAIKI_SHURUI_CD != null && data.HAIKI_SHURUI_CD != ''*/
AND HAIKI_SHURUI_CD = /*data.HAIKI_SHURUI_CD*/ /*END*/ 
/*IF data.FROM_HAIKI_SHURUI_CD != null && data.FROM_HAIKI_SHURUI_CD != ''*/
AND HAIKI_SHURUI_CD > /*data.FROM_HAIKI_SHURUI_CD*/ /*END*/ 
/*IF data.TO_HAIKI_SHURUI_CD != null && data.TO_HAIKI_SHURUI_CD != ''*/
AND HAIKI_SHURUI_CD < /*data.TO_HAIKI_SHURUI_CD*/ /*END*/ 
AND HAIKI_KBN_CD = /*data.HAIKI_KBN_CD*/ 