SELECT 
TMPE.SYSTEM_ID,TMPE.SEQ
FROM T_MANIFEST_PT_ENTRY(NOLOCK) TMPE 
left join T_MANIFEST_PT_DETAIL TMPD ON (TMPE.SYSTEM_ID = TMPD.SYSTEM_ID AND TMPE.SEQ = TMPD.SEQ)
WHERE TMPE.DELETE_FLG = 0
AND TMPE.KYOTEN_CD = /*data.KYOTEN*/0 
AND TMPE.HAIKI_KBN_CD = /*data.HAIKI_KBN_CD*/0 
AND TMPE.FIRST_MANIFEST_KBN = /*data.FIRST_MANIFEST_KBN*/0 
AND TMPE.USE_DEFAULT_KBN= 1