SELECT TUSE.SHUKKA_NUMBER,TUSD.ROW_NO 
FROM T_SHUKKA_ENTRY TUSE
left join T_SHUKKA_DETAIL TUSD ON (TUSE.SYSTEM_ID = TUSD.SYSTEM_ID AND TUSE.SEQ = TUSD.SEQ AND TUSD.DETAIL_SYSTEM_ID = /*data.RENKEI_MEISAI_SYSTEM_ID*/)
WHERE TUSE.DELETE_FLG = 0
AND TUSE.SYSTEM_ID =  /*data.RENKEI_SYSTEM_ID*/