SELECT TTHE.TEIKI_JISSEKI_NUMBER,TKD.ROW_NUMBER FROM T_TEIKI_JISSEKI_ENTRY TTHE 
left join T_TEIKI_JISSEKI_DETAIL TKD ON (TTHE.SYSTEM_ID = TKD.SYSTEM_ID AND TTHE.SEQ = TKD.SEQ AND TKD.DETAIL_SYSTEM_ID = /*data.RENKEI_MEISAI_SYSTEM_ID*/)
WHERE TTHE.DELETE_FLG = 0
AND TTHE.SYSTEM_ID =  /*data.RENKEI_SYSTEM_ID*/