SELECT

M_CONTENA.DELETE_FLG,
M_CONTENA.CONTENA_SHURUI_CD,
M_CONTENA_SHURUI.CONTENA_SHURUI_NAME_RYAKU,
M_CONTENA.CONTENA_CD,
M_CONTENA.CONTENA_NAME,
M_CONTENA.CONTENA_NAME_RYAKU,
M_CONTENA.GYOUSHA_CD,
M_GYOUSHA.GYOUSHA_NAME_RYAKU,
M_CONTENA.GENBA_CD,
M_GENBA.GENBA_NAME_RYAKU,
M_CONTENA.KYOTEN_CD,
M_KYOTEN.KYOTEN_NAME_RYAKU,
M_CONTENA.SHARYOU_CD,
M_SHARYOU.SHARYOU_NAME_RYAKU,
M_CONTENA.KOUNYUU_DATE,
M_CONTENA.LAST_SHUUFUKU_DATE,
M_CONTENA.SECCHI_DATE,
CASE
WHEN(CONVERT(nvarchar,M_CONTENA.JOUKYOU_KBN)) IS NOT NULL AND (CONVERT(nvarchar,M_CONTENA.JOUKYOU_KBN)) <>'0'  THEN (CONVERT(nvarchar,M_CONTENA.JOUKYOU_KBN))
ELSE NULL END  AS JOUKYOU_KBN,
M_CONTENA_JOUKYOU.CONTENA_JOUKYOU_NAME_RYAKU,
M_CONTENA.CONTENA_BIKOU,
M_CONTENA.UPDATE_USER,
M_CONTENA.UPDATE_DATE,
M_CONTENA.CREATE_USER,
M_CONTENA.CREATE_DATE,
M_CONTENA.TIME_STAMP

FROM M_CONTENA
LEFT OUTER JOIN M_GENBA
ON M_CONTENA.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
AND M_CONTENA.GENBA_CD = M_GENBA.GENBA_CD
LEFT OUTER JOIN M_KYOTEN
ON M_CONTENA.KYOTEN_CD = M_KYOTEN.KYOTEN_CD
LEFT OUTER JOIN M_SHARYOU
ON M_CONTENA.GYOUSHA_CD = M_SHARYOU.GYOUSHA_CD
AND M_CONTENA.SHARYOU_CD = M_SHARYOU.SHARYOU_CD
LEFT OUTER JOIN M_CONTENA_JOUKYOU
ON M_CONTENA.JOUKYOU_KBN = M_CONTENA_JOUKYOU.CONTENA_JOUKYOU_CD
LEFT OUTER JOIN M_GYOUSHA
ON M_CONTENA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
LEFT OUTER JOIN M_CONTENA_SHURUI
ON M_CONTENA.CONTENA_SHURUI_CD = M_CONTENA_SHURUI.CONTENA_SHURUI_CD

/*BEGIN*/WHERE
/*IF data.CONTENA_SHURUI_CD != null*/M_CONTENA.CONTENA_SHURUI_CD LIKE '%' + /*data.CONTENA_SHURUI_CD*/ + '%'/*END*/
/*IF data.CONTENA_CD != null*/AND M_CONTENA.CONTENA_CD LIKE '%' + /*data.CONTENA_CD*/ + '%'/*END*/
/*END*/

ORDER BY M_CONTENA.CONTENA_SHURUI_CD,M_CONTENA.CONTENA_CD