SELECT

M_CONTENA.DELETE_FLG,
M_CONTENA.CONTENA_SHURUI_CD,
M_CONTENA_SHURUI.CONTENA_SHURUI_NAME_RYAKU,
M_CONTENA.CONTENA_CD,
M_CONTENA.CONTENA_NAME,
M_CONTENA.CONTENA_NAME_RYAKU,
M_CONTENA.GYOUSHA_CD,
M_GYOUSHA.GYOUSHA_NAME_RYAKU,
M_CONTENA.GENBA_CD,
M_GENBA.GENBA_NAME_RYAKU,
M_CONTENA.KYOTEN_CD,
M_KYOTEN.KYOTEN_NAME_RYAKU,
M_CONTENA.SHARYOU_CD,
M_SHARYOU.SHARYOU_NAME_RYAKU,
M_CONTENA.KOUNYUU_DATE,
M_CONTENA.LAST_SHUUFUKU_DATE,
M_CONTENA.SECCHI_DATE,
M_CONTENA.HIKIAGE_DATE,
CASE
WHEN(CONVERT(nvarchar,M_CONTENA.JOUKYOU_KBN)) IS NOT NULL AND (CONVERT(nvarchar,M_CONTENA.JOUKYOU_KBN)) <>'0'  THEN (CONVERT(nvarchar,M_CONTENA.JOUKYOU_KBN))
ELSE NULL END  AS JOUKYOU_KBN,
M_CONTENA_JOUKYOU.CONTENA_JOUKYOU_NAME_RYAKU,
M_CONTENA.CONTENA_BIKOU,
M_CONTENA.UPDATE_USER,
M_CONTENA.UPDATE_DATE,
M_CONTENA.CREATE_USER,
M_CONTENA.CREATE_DATE,
M_CONTENA.TIME_STAMP

FROM M_CONTENA
LEFT OUTER JOIN M_GENBA
ON M_CONTENA.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
AND M_CONTENA.GENBA_CD = M_GENBA.GENBA_CD
LEFT OUTER JOIN M_KYOTEN
ON M_CONTENA.KYOTEN_CD = M_KYOTEN.KYOTEN_CD
LEFT OUTER JOIN M_SHARYOU
ON M_CONTENA.GYOUSHA_CD = M_SHARYOU.GYOUSHA_CD
AND M_CONTENA.SHARYOU_CD = M_SHARYOU.SHARYOU_CD
LEFT OUTER JOIN M_CONTENA_JOUKYOU
ON M_CONTENA.JOUKYOU_KBN = M_CONTENA_JOUKYOU.CONTENA_JOUKYOU_CD
LEFT OUTER JOIN M_GYOUSHA
ON M_CONTENA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
LEFT OUTER JOIN M_CONTENA_SHURUI
ON M_CONTENA.CONTENA_SHURUI_CD = M_CONTENA_SHURUI.CONTENA_SHURUI_CD

/*BEGIN*/WHERE
/*IF data.CONTENA_SHURUI_CD != null*/M_CONTENA.CONTENA_SHURUI_CD LIKE '%' + /*data.CONTENA_SHURUI_CD*/ + '%'/*END*/
/*IF data.CONTENA_CD != null*/AND M_CONTENA.CONTENA_CD LIKE '%' + /*data.CONTENA_CD*/ + '%'/*END*/
/*IF data.CONTENA_NAME != null*/AND M_CONTENA.CONTENA_NAME LIKE '%' +  /*data.CONTENA_NAME*/ + '%'/*END*/
/*IF data.CONTENA_NAME_RYAKU != null*/AND M_CONTENA.CONTENA_NAME_RYAKU LIKE '%' +  /*data.CONTENA_NAME_RYAKU*/ + '%'/*END*/
/*IF data.GYOUSHA_CD != null*/AND M_CONTENA.GYOUSHA_CD LIKE '%' +  /*data.GYOUSHA_CD*/ + '%'/*END*/
/*IF data.GENBA_CD != null*/AND M_CONTENA.GENBA_CD LIKE '%' +  /*data.GENBA_CD*/ + '%'/*END*/
/*IF !data.KYOTEN_CD.IsNull*/AND CONVERT(nvarchar,M_CONTENA.KYOTEN_CD) LIKE '%' + CONVERT(nvarchar,/*data.KYOTEN_CD*/) + '%'/*END*/
/*IF data.SHARYOU_CD != null*/AND M_CONTENA.SHARYOU_CD LIKE '%' +  /*data.SHARYOU_CD*/ + '%'/*END*/
/*IF !data.JOUKYOU_KBN.IsNull*/AND CONVERT(nvarchar,M_CONTENA.JOUKYOU_KBN) LIKE '%' + CONVERT(nvarchar,/*data.JOUKYOU_KBN*/) + '%'/*END*/

/*IF data.CONTENA_SHURUI_NAME_RYAKU != null*/AND M_CONTENA_SHURUI.CONTENA_SHURUI_NAME_RYAKU LIKE '%' +  /*data.CONTENA_SHURUI_NAME_RYAKU*/ + '%'/*END*/
/*IF data.GYOUSHA_NAME_RYAKU != null*/AND M_GYOUSHA.GYOUSHA_NAME_RYAKU LIKE '%' +  /*data.GYOUSHA_NAME_RYAKU*/ + '%'/*END*/
/*IF data.GENBA_NAME_RYAKU != null*/AND M_GENBA.GENBA_NAME_RYAKU LIKE '%' +  /*data.GENBA_NAME_RYAKU*/ + '%'/*END*/
/*IF data.KYOTEN_NAME_RYAKU != null*/AND M_KYOTEN.KYOTEN_NAME_RYAKU LIKE '%' +  /*data.KYOTEN_NAME_RYAKU*/ + '%'/*END*/
/*IF data.SHARYOU_NAME_RYAKU != null*/AND M_SHARYOU.SHARYOU_NAME_RYAKU LIKE '%' +  /*data.SHARYOU_NAME_RYAKU*/ + '%'/*END*/
/*IF data.CONTENA_JOUKYOU_NAME_RYAKU != null*/AND M_CONTENA_JOUKYOU.CONTENA_JOUKYOU_NAME_RYAKU LIKE '%' +  /*data.CONTENA_JOUKYOU_NAME_RYAKU*/ + '%'/*END*/

/*IF data.CONTENA_BIKOU != null*/AND M_CONTENA.CONTENA_BIKOU LIKE '%' +  /*data.CONTENA_BIKOU*/ + '%'/*END*/
/*IF data.CREATE_USER != null*/AND M_CONTENA.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
/*IF data.UPDATE_USER != null*/AND M_CONTENA.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/

/*IF data.SEARCH_KOUNYUU_DATE != null*/AND CONVERT(nvarchar, M_CONTENA.KOUNYUU_DATE, 120) LIKE '%' +  /*data.SEARCH_KOUNYUU_DATE*/ + '%'/*END*/
/*IF data.SEARCH_LAST_SHUUFUKU_DATE != null*/AND CONVERT(nvarchar, M_CONTENA.LAST_SHUUFUKU_DATE, 120) LIKE '%' +  /*data.SEARCH_LAST_SHUUFUKU_DATE*/ + '%'/*END*/
/*IF data.SEARCH_SECCHI_DATE != null*/AND CONVERT(nvarchar, M_CONTENA.SECCHI_DATE, 120) LIKE '%' +  /*data.SEARCH_SECCHI_DATE*/ + '%'/*END*/
/*IF data.SEARCH_HIKIAGE_DATE != null*/AND CONVERT(nvarchar, M_CONTENA.HIKIAGE_DATE, 120) LIKE '%' +  /*data.SEARCH_HIKIAGE_DATE*/ + '%'/*END*/
/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, M_CONTENA.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, M_CONTENA.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/

/*IF !deletechuFlg*/AND M_CONTENA.DELETE_FLG = /*deletechuFlg*/0/*END*/

/*END*/
ORDER BY M_CONTENA.CONTENA_SHURUI_CD,M_CONTENA.CONTENA_CD