SELECT 
    SYS.*
   ,UNI1.UNIT_NAME_RYAKU AS HINMEI_UNIT_NAME
   ,UNI2.UNIT_NAME_RYAKU AS KANSAN_KIHON_UNIT_NAME
   ,UNI3.UNIT_NAME_RYAKU AS KANSAN_UNIT_NAME
   ,UNI4.UNIT_NAME_RYAKU AS MANI_KANSAN_KIHON_UNIT_NAME
   ,UNI5.UNIT_NAME_RYAKU AS MANI_KANSAN_UNIT_NAME
   ,UNI6.UNIT_NAME_RYAKU AS GENBA_KANSAN_UNIT_NAME
   ,ISNULL(NYU1.NYUUSHUKKIN_KBN_NAME_RYAKU,N'') AS SEIKYUU_KAISHUU_HOUHOU_NAME
   ,ISNULL(NYU2.NYUUSHUKKIN_KBN_NAME_RYAKU,N'') AS SHIHARAI_HOUHOU_NAME
   ,ISNULL(NYU3.NYUUSHUKKIN_KBN_NAME_RYAKU,N'') AS NYUUKIN_NYUUSHUKKIN_KBN_NAME
   ,ISNULL(NYU4.NYUUSHUKKIN_KBN_NAME_RYAKU,N'') AS NYUUKIN_IKKATSU_NYUUSHUKKINKIN_KBN_CD_NAME
   ,ISNULL(MAN_SHU.MANIFEST_SHURUI_NAME_RYAKU,N'') AS GENBA_MANIFEST_SHURUI_NAME
   ,ISNULL(MAN_TEH.MANIFEST_TEHAI_NAME_RYAKU,N'') AS GENBA_MANIFEST_TEHAI_NAME
   ,ISNULL(DENSHU.DENSHU_KBN_NAME_RYAKU,N'') AS HINMEI_DENSHU_KBN_NAME
   ,ISNULL(DENPYOU.DENPYOU_KBN_NAME_RYAKU,N'') AS HINMEI_DENPYOU_KBN_NAME
   ,ISNULL(KYO1.KYOTEN_NAME_RYAKU,N'') AS SEIKYUU_KYOTEN_NAME
   ,ISNULL(KYO2.KYOTEN_NAME_RYAKU,N'') AS SHIHARAI_KYOTEN_NAME
   ,ISNULL(KYO3.KYOTEN_NAME_RYAKU,N'') AS GYOUSHA_SEIKYUU_KYOTEN_NAME
   ,ISNULL(KYO4.KYOTEN_NAME_RYAKU,N'') AS GYOUSHA_SHIHARAI_KYOTEN_NAME
   ,ISNULL(KYO5.KYOTEN_NAME_RYAKU,N'') AS GENBA_SEIKYUU_KYOTEN_NAME
   ,ISNULL(KYO6.KYOTEN_NAME_RYAKU,N'') AS GENBA_SHIHARAI_KYOTEN_NAME
   ,ISNULL(KYO7.KYOTEN_NAME_RYAKU,N'') AS MITSUMORI_INJI_KYOTEN_NAME1
   ,ISNULL(KYO8.KYOTEN_NAME_RYAKU,N'') AS MITSUMORI_INJI_KYOTEN_NAME2
   ,ISNULL(GYO.GYOUSHA_NAME_RYAKU,N'') AS UKETSUKE_UPN_GYOUSHA_CD_DEFALUT_NAME
   ,ISNULL(KEI1.KEITAI_KBN_NAME_RYAKU,N'') AS KEIRYOU_UKEIRE_KEITAI_KBN_NAME
   ,ISNULL(KEI2.KEITAI_KBN_NAME_RYAKU,N'') AS KEIRYOU_SHUKKA_KEITAI_KBN_NAME
FROM 
    dbo.M_SYS_INFO SYS
	LEFT JOIN dbo.M_UNIT UNI1 ON UNI1.UNIT_CD = SYS.HINMEI_UNIT_CD
	LEFT JOIN dbo.M_UNIT UNI2 ON UNI2.UNIT_CD = SYS.KANSAN_KIHON_UNIT_CD
	LEFT JOIN dbo.M_UNIT UNI3 ON UNI3.UNIT_CD = SYS.KANSAN_UNIT_CD
	LEFT JOIN dbo.M_UNIT UNI4 ON UNI4.UNIT_CD = SYS.MANI_KANSAN_KIHON_UNIT_CD
	LEFT JOIN dbo.M_UNIT UNI5 ON UNI5.UNIT_CD = SYS.MANI_KANSAN_UNIT_CD
	LEFT JOIN dbo.M_UNIT UNI6 ON UNI6.UNIT_CD = SYS.GENBA_KANSAN_UNIT_CD
	LEFT JOIN dbo.M_NYUUSHUKKIN_KBN NYU1 ON NYU1.NYUUSHUKKIN_KBN_CD = SYS.SEIKYUU_KAISHUU_HOUHOU
	LEFT JOIN dbo.M_NYUUSHUKKIN_KBN NYU2 ON NYU2.NYUUSHUKKIN_KBN_CD = SYS.SHIHARAI_HOUHOU
	LEFT JOIN dbo.M_NYUUSHUKKIN_KBN NYU3 ON NYU3.NYUUSHUKKIN_KBN_CD = SYS.NYUUKIN_NYUUSHUKKIN_KBN_CD
	LEFT JOIN dbo.M_NYUUSHUKKIN_KBN NYU4 ON NYU4.NYUUSHUKKIN_KBN_CD = SYS.NYUUKIN_IKKATSU_NYUUSHUKKINKIN_KBN_CD
	LEFT JOIN dbo.M_MANIFEST_SHURUI MAN_SHU ON MAN_SHU.MANIFEST_SHURUI_CD = SYS.GENBA_MANIFEST_SHURUI_CD
	LEFT JOIN dbo.M_MANIFEST_TEHAI MAN_TEH ON MAN_TEH.MANIFEST_TEHAI_CD = SYS.GENBA_MANIFEST_TEHAI_CD
	LEFT JOIN dbo.M_DENSHU_KBN DENSHU ON DENSHU.DENSHU_KBN_CD = SYS.HINMEI_DENSHU_KBN_CD
	LEFT JOIN dbo.M_DENPYOU_KBN DENPYOU ON DENPYOU.DENPYOU_KBN_CD = SYS.HINMEI_DENPYOU_KBN_CD
	LEFT JOIN dbo.M_KYOTEN KYO1 ON KYO1.KYOTEN_CD = SYS.SEIKYUU_KYOTEN_CD
	LEFT JOIN dbo.M_KYOTEN KYO2 ON KYO2.KYOTEN_CD = SYS.SHIHARAI_KYOTEN_CD
	LEFT JOIN dbo.M_KYOTEN KYO3 ON KYO3.KYOTEN_CD = SYS.GYOUSHA_SEIKYUU_KYOTEN_CD
	LEFT JOIN dbo.M_KYOTEN KYO4 ON KYO4.KYOTEN_CD = SYS.GYOUSHA_SHIHARAI_KYOTEN_CD
	LEFT JOIN dbo.M_KYOTEN KYO5 ON KYO5.KYOTEN_CD = SYS.GENBA_SEIKYUU_KYOTEN_CD
	LEFT JOIN dbo.M_KYOTEN KYO6 ON KYO6.KYOTEN_CD = SYS.GENBA_SHIHARAI_KYOTEN_CD
	LEFT JOIN dbo.M_KYOTEN KYO7 ON KYO7.KYOTEN_CD = SYS.MITSUMORI_INJI_KYOTEN_CD1
	LEFT JOIN dbo.M_KYOTEN KYO8 ON KYO8.KYOTEN_CD = SYS.MITSUMORI_INJI_KYOTEN_CD2
	LEFT JOIN dbo.M_GYOUSHA GYO ON GYO.GYOUSHA_CD = SYS.UKETSUKE_UPN_GYOUSHA_CD_DEFALUT
	LEFT JOIN dbo.M_KEITAI_KBN KEI1 ON KEI1.KEITAI_KBN_CD = SYS.KEIRYOU_UKEIRE_KEITAI_KBN_CD
	LEFT JOIN dbo.M_KEITAI_KBN KEI2 ON KEI2.KEITAI_KBN_CD = SYS.KEIRYOU_SHUKKA_KEITAI_KBN_CD
WHERE
	SYS.SYS_ID = 0
