SELECT * FROM dbo.T_UKEIRE_JISSEKI_DETAIL
WHERE
1 = 1
/*IF !data.DENPYOU_SHURUI.IsNull*/AND DENPYOU_SHURUI = /*data.DENPYOU_SHURUI.Value*//*END*/
/*IF !data.DENPYOU_SYSTEM_ID.IsNull*/AND DENPYOU_SYSTEM_ID = /*data.DENPYOU_SYSTEM_ID.Value*//*END*/
/*IF !data.SEQ.IsNull*/AND SEQ = /*data.SEQ.Value*//*END*/
ORDER BY DETAIL_SEQ