SELECT 
   M_CHIIKI.TODOUFUKEN_CD AS TODOUFUKEN_CD,
   M_TODOUFUKEN.TODOUFUKEN_NAME_RYAKU AS TODOUFUKEN_NAME,
   M_CHIIKI.CHIIKI_NAME_RYAKU
  
FROM M_CHIIKI
  LEFT JOIN M_TODOUFUKEN
    ON M_CHIIKI.TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD
   AND M_TODOUFUKEN.DELETE_FLG = 0

WHERE M_CHIIKI.CHIIKI_CD = /*CHIIKI_CD*/'000000'
  AND M_CHIIKI.DELETE_FLG = 0