SELECT
	MS.SHAIN_CD
	,MS.BUSHO_CD
	,MS.LOGIN_ID
	,MS.PASSWORD
	,MMA.FORM_ID
	,MMA.WINDOW_ID
	,MMA.AUTH_READ
	,MMA.AUTH_ADD
	,MMA.AUTH_EDIT
	,MMA.AUTH_DELETE
FROM
	M_SHAIN MS
	LEFT JOIN M_MENU_AUTH MMA
		ON MS.SHAIN_CD = MMA.SHAIN_CD
		AND MS.BUSHO_CD = MMA.BUSHO_CD
		AND MMA.FORM_ID = 'M188'
		AND MMA.DELETE_FLG = 0
WHERE
	LEN(ISNULL(MS.LOGIN_ID, '')) > 0
	AND MS.DELETE_FLG = 0