//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shougun.Core.Common.DenpyouRenkeiIchiran.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string KINOU_KBN {
            get {
                return ((string)(this["KINOU_KBN"]));
            }
            set {
                this["KINOU_KBN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string DENPYOU_KBN {
            get {
                return ((string)(this["DENPYOU_KBN"]));
            }
            set {
                this["DENPYOU_KBN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DATE_FROM {
            get {
                return ((string)(this["DATE_FROM"]));
            }
            set {
                this["DATE_FROM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DATE_TO {
            get {
                return ((string)(this["DATE_TO"]));
            }
            set {
                this["DATE_TO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DENPYOU_NO {
            get {
                return ((string)(this["DENPYOU_NO"]));
            }
            set {
                this["DENPYOU_NO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TORIHIKISAKI_CD {
            get {
                return ((string)(this["TORIHIKISAKI_CD"]));
            }
            set {
                this["TORIHIKISAKI_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GYOUSHA_CD {
            get {
                return ((string)(this["GYOUSHA_CD"]));
            }
            set {
                this["GYOUSHA_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GENBA_CD {
            get {
                return ((string)(this["GENBA_CD"]));
            }
            set {
                this["GENBA_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string RENKEI_KBN {
            get {
                return ((string)(this["RENKEI_KBN"]));
            }
            set {
                this["RENKEI_KBN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UKETSUKE_FLG {
            get {
                return ((bool)(this["UKETSUKE_FLG"]));
            }
            set {
                this["UKETSUKE_FLG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UKEIRE_FLG {
            get {
                return ((bool)(this["UKEIRE_FLG"]));
            }
            set {
                this["UKEIRE_FLG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SHUKKA_FLG {
            get {
                return ((bool)(this["SHUKKA_FLG"]));
            }
            set {
                this["SHUKKA_FLG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UR_SH_FLG {
            get {
                return ((bool)(this["UR_SH_FLG"]));
            }
            set {
                this["UR_SH_FLG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MANI_FLG {
            get {
                return ((bool)(this["MANI_FLG"]));
            }
            set {
                this["MANI_FLG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UNCHIN_FLG {
            get {
                return ((bool)(this["UNCHIN_FLG"]));
            }
            set {
                this["UNCHIN_FLG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DAINOU_FLG {
            get {
                return ((bool)(this["DAINOU_FLG"]));
            }
            set {
                this["DAINOU_FLG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KYOTEN_CD {
            get {
                return ((string)(this["KYOTEN_CD"]));
            }
            set {
                this["KYOTEN_CD"] = value;
            }
        }
    }
}
