select 
ROW_NUMBER() OVER (ORDER BY SORT_SEISAN_DATE) AS ROW_NUMBER
,inview.GYOUSHA_CD 
,inview.GYOUSHA_NAME_RYAKU
,inview.GENBA_CD
,inview.GENBA_NAME_RYAKU
,inview.SEISAN_DATE
,ISNULL(inview.SEISANGAKU,0) AS SEISANGAKU
,inview.KESHIKOMIGAKU AS KeshikomiGaku
,inview.KESHIKOMIGAKU_TOTAL AS KESHIKOMIGAKU_TOTAL
,inview.MIKESHIKOMIGAKU AS MiKeshikomiGaku
,inview.SEISAN_NUMBER
,inview.KAGAMI_NUMBER
,inview.SYSTEM_ID
,inview.KESHIKOMI_SEQ
,inview.SHUKKIN_NUMBER
,inview.KESHIKOMI_BIKOU
 FROM
 (
 /*IF data.Zandaka == '1'*/
 SELECT
    TNK.SYSTEM_ID AS SYSTEM_ID,
	TNK.KESHIKOMI_SEQ AS KESHIKOMI_SEQ,
	NULL AS GYOUSHA_CD,
	NULL AS GYOUSHA_NAME_RYAKU,
	NULL AS GENBA_CD,
	NULL AS GENBA_NAME_RYAKU,
	'開始残高' AS SEISAN_DATE,
	'1753-01-01 00:00:00.000' AS SORT_SEISAN_DATE,
	MTS.KAISHI_KAIKAKE_ZANDAKA AS SEISANGAKU,
	TNK.KESHIKOMI_GAKU AS KESHIKOMIGAKU,
    TNK2.KESHIKOMI_GAKU_TOTAL AS KESHIKOMIGAKU_TOTAL,
	(MTS.KAISHI_KAIKAKE_ZANDAKA - ISNULL(TNK2.KESHIKOMI_GAKU_TOTAL, 0)) AS MIKESHIKOMIGAKU,
	0 AS SEISAN_NUMBER,
	0 AS KAGAMI_NUMBER,
	TNK.SHUKKIN_NUMBER AS SHUKKIN_NUMBER,
	TNK.KESHIKOMI_BIKOU AS KESHIKOMI_BIKOU
FROM
    M_TORIHIKISAKI_SHIHARAI MTS
LEFT JOIN T_SHUKKIN_KESHIKOMI TNK
       ON MTS.TORIHIKISAKI_CD = TNK.TORIHIKISAKI_CD
	   AND TNK.SEISAN_NUMBER = 0
	   AND TNK.KAGAMI_NUMBER = 0
	   AND TNK.DELETE_FLG = 0 
LEFT JOIN (SELECT
              T_SHUKKIN_KESHIKOMI.SEISAN_NUMBER,
			  T_SHUKKIN_KESHIKOMI.KAGAMI_NUMBER,
			  T_SHUKKIN_KESHIKOMI.TORIHIKISAKI_CD,
			  SUM(T_SHUKKIN_KESHIKOMI.KESHIKOMI_GAKU) AS KESHIKOMI_GAKU_TOTAL
			FROM T_SHUKKIN_KESHIKOMI T_SHUKKIN_KESHIKOMI
			WHERE T_SHUKKIN_KESHIKOMI.DELETE_FLG = 0
			GROUP BY T_SHUKKIN_KESHIKOMI.SEISAN_NUMBER,
			         T_SHUKKIN_KESHIKOMI.KAGAMI_NUMBER,
			         T_SHUKKIN_KESHIKOMI.TORIHIKISAKI_CD) TNK2
	  ON TNK2.SEISAN_NUMBER = 0
	  AND TNK2.KAGAMI_NUMBER = 0
	  AND MTS.TORIHIKISAKI_CD = TNK2.TORIHIKISAKI_CD
WHERE
	1=1
	/*IF data.TORIHIKISAKI_CD != null && data.TORIHIKISAKI_CD != ''*/
	AND MTS.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/
	/*END*/
UNION
/*END*/
SELECT
    TNK.SYSTEM_ID AS SYSTEM_ID,
	TNK.KESHIKOMI_SEQ AS KESHIKOMI_SEQ,
	TSDK.GYOUSHA_CD AS GYOUSHA_CD,
	MGYOUSHA.GYOUSHA_NAME_RYAKU AS GYOUSHA_NAME_RYAKU,
	TSDK.GENBA_CD AS GENBA_CD,
	MGENBA.GENBA_NAME_RYAKU AS GENBA_NAME_RYAKU,
	CONVERT(varchar(10), TSD.SEISAN_DATE, 111) AS SEISAN_DATE,
	TSD.SEISAN_DATE AS SORT_SEISAN_DATE,
	(TSDK.KONKAI_SHIHARAI_GAKU + TSDK.KONKAI_SEI_UTIZEI_GAKU + TSDK.KONKAI_SEI_SOTOZEI_GAKU 
	+ TSDK.KONKAI_DEN_UTIZEI_GAKU + TSDK.KONKAI_DEN_SOTOZEI_GAKU + TSDK.KONKAI_MEI_UTIZEI_GAKU
	+ TSDK.KONKAI_MEI_SOTOZEI_GAKU) AS SEISANGAKU,
	TNK.KESHIKOMI_GAKU AS KESHIKOMIGAKU,
	TNK2.KESHIKOMI_GAKU_TOTAL AS KESHIKOMIGAKU_TOTAL,
	(TSDK.KONKAI_SHIHARAI_GAKU + TSDK.KONKAI_SEI_UTIZEI_GAKU + TSDK.KONKAI_SEI_SOTOZEI_GAKU 
	+ TSDK.KONKAI_DEN_UTIZEI_GAKU + TSDK.KONKAI_DEN_SOTOZEI_GAKU + TSDK.KONKAI_MEI_UTIZEI_GAKU
	+ TSDK.KONKAI_MEI_SOTOZEI_GAKU - ISNULL(TNK2.KESHIKOMI_GAKU_TOTAL, 0)) AS MIKESHIKOMIGAKU,
	TSD.SEISAN_NUMBER AS SEISAN_NUMBER,
	TSDK.KAGAMI_NUMBER AS KAGAMI_NUMBER,
	TNK.SHUKKIN_NUMBER AS SHUKKIN_NUMBER,
	TNK.KESHIKOMI_BIKOU AS KESHIKOMI_BIKOU
FROM
	T_SEISAN_DENPYOU TSD
LEFT JOIN T_SEISAN_DENPYOU_KAGAMI TSDK 
       ON TSDK.SEISAN_NUMBER = TSD.SEISAN_NUMBER 
	   AND TSDK.DELETE_FLG = 0
LEFT JOIN T_SHUKKIN_KESHIKOMI TNK
       ON TNK.SEISAN_NUMBER = TSDK.SEISAN_NUMBER
	   AND TNK.KAGAMI_NUMBER = TSDK.KAGAMI_NUMBER
	   AND TNK.DELETE_FLG = 0
LEFT JOIN M_GYOUSHA MGYOUSHA
       ON MGYOUSHA.GYOUSHA_CD = TSDK.GYOUSHA_CD
LEFT JOIN M_GENBA MGENBA 
       ON MGENBA.GYOUSHA_CD = TSDK.GYOUSHA_CD
	   AND MGENBA.GENBA_CD = TSDK.GENBA_CD
LEFT JOIN (SELECT
              T_SHUKKIN_KESHIKOMI.SEISAN_NUMBER,
			  T_SHUKKIN_KESHIKOMI.KAGAMI_NUMBER,
			  SUM(T_SHUKKIN_KESHIKOMI.KESHIKOMI_GAKU) AS KESHIKOMI_GAKU_TOTAL
			FROM T_SHUKKIN_KESHIKOMI T_SHUKKIN_KESHIKOMI
			WHERE T_SHUKKIN_KESHIKOMI.DELETE_FLG = 0
			GROUP BY T_SHUKKIN_KESHIKOMI.SEISAN_NUMBER,
			         T_SHUKKIN_KESHIKOMI.KAGAMI_NUMBER
		   ) TNK2
	   ON TNK2.SEISAN_NUMBER = TNK.SEISAN_NUMBER
	  AND TNK2.KAGAMI_NUMBER = TNK.KAGAMI_NUMBER
WHERE
    1=1
    /*IF data.TORIHIKISAKI_CD != null && data.TORIHIKISAKI_CD != ''*/
	AND TSD.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/
	/*END*/
	/*IF data.SEISAN_DATE_FROM != null && data.SEISAN_DATE_FROM != ''*/
	AND TSD.SEISAN_DATE >= /*data.SEISAN_DATE_FROM*/
	/*END*/
	/*IF data.SEISAN_DATE_TO != null && data.SEISAN_DATE_TO != ''*/
	AND TSD.SEISAN_DATE <= /*data.SEISAN_DATE_TO*/
	/*END*/
	AND TSD.DELETE_FLG = 0
) inview
 order by ROW_NUMBER, GYOUSHA_CD, GENBA_CD, SHUKKIN_NUMBER
