SELECT
	TORIHIKISAKI_CD PKEY1,
	CAST(NULL AS varchar) PKEY2,
	CAST('2' AS varchar) MENU_CD,
	CAST('1' AS varchar) ITEM_CD,
	CAST('' AS varchar) MENU_NAME,
	CAST('' AS varchar) ITEM_NAME,
	CAST(0 AS bit) CHANGE_FLG,
	TORIHIKISAKI_POST POST,
	TORIHIKISAKI_ADDRESS1 ADDRESS1,
	TORIHIKISAKI_ADDRESS2 ADDRESS2
  FROM M_TORIHIKISAKI
/*BEGIN*/WHERE
 /*IF data.TORIHIKISAKI_POST != null*/
 TORIHIKISAKI_POST LIKE '%' + /*data.TORIHIKISAKI_POST*/'100-0001' + '%'
 /*END*/
 /*IF data.TORIHIKISAKI_ADDRESS1 != null*/AND (TORIHIKISAKI_ADDRESS1 + TORIHIKISAKI_ADDRESS2) LIKE '%' + /*data.TORIHIKISAKI_ADDRESS1*/'èZèä' + '%'/*END*/
/*END*/

UNION ALL

SELECT
	TORIHIKISAKI_CD PKEY1,
	CAST(NULL AS varchar) PKEY2,
	CAST('2' AS varchar) MENU_CD,
	CAST('4' AS varchar) ITEM_CD,
	CAST('' AS varchar) MENU_NAME,
	CAST('' AS varchar) ITEM_NAME,
	CAST(0 AS bit) CHANGE_FLG,
	MANI_HENSOUSAKI_POST POST,
	MANI_HENSOUSAKI_ADDRESS1 ADDRESS1,
	MANI_HENSOUSAKI_ADDRESS2 ADDRESS2
  FROM M_TORIHIKISAKI
/*BEGIN*/WHERE
 /*IF data.MANI_HENSOUSAKI_POST != null*/
 MANI_HENSOUSAKI_POST LIKE '%' + /*data.MANI_HENSOUSAKI_POST*/'100-0001' + '%'
 /*END*/
 /*IF data.MANI_HENSOUSAKI_ADDRESS1 != null*/AND (MANI_HENSOUSAKI_ADDRESS1 + MANI_HENSOUSAKI_ADDRESS2) LIKE '%' + /*data.MANI_HENSOUSAKI_ADDRESS1*/'èZèä' + '%'/*END*/
/*END*/
