SELECT
	NYUUKINSAKI_CD PKEY1,
	CAST(NULL AS varchar) PKEY2,
	CAST('5' AS varchar) MENU_CD,
	CAST('1' AS varchar) ITEM_CD,
	CAST('' AS varchar) MENU_NAME,
	CAST('' AS varchar) ITEM_NAME,
	CAST(0 AS bit) CHANGE_FLG,
	NYUUKINSAKI_POST POST,
	NYUUKINSAKI_ADDRESS1 ADDRESS1,
	NYUUKINSAKI_ADDRESS2 ADDRESS2
  FROM M_NYUUKINSAKI
/*BEGIN*/WHERE
 /*IF data.NYUUKINSAKI_POST != null*/
 NYUUKINSAKI_POST LIKE '%' + /*data.NYUUKINSAKI_POST*/'100-0001' + '%'
 /*END*/
 /*IF data.NYUUKINSAKI_ADDRESS1 != null*/AND (NYUUKINSAKI_ADDRESS1 + NYUUKINSAKI_ADDRESS2) LIKE '%' + /*data.NYUUKINSAKI_ADDRESS1*/'èZèä' + '%'/*END*/
/*END*/
