SELECT
	TORIHIKISAKI_CD PKEY1,
	CAST(NULL AS varchar) PKEY2,
	CAST('2' AS varchar) MENU_CD,
	CAST('3' AS varchar) ITEM_CD,
	CAST('' AS varchar) MENU_NAME,
	CAST('' AS varchar) ITEM_NAME,
	CAST(0 AS bit) CHANGE_FLG,
	SHIHARAI_SOUFU_POST POST,
	SHIHARAI_SOUFU_ADDRESS1 ADDRESS1,
	SHIHARAI_SOUFU_ADDRESS2 ADDRESS2
  FROM M_TORIHIKISAKI_SHIHARAI
/*BEGIN*/WHERE
 /*IF data.SHIHARAI_SOUFU_POST != null*/
 SHIHARAI_SOUFU_POST LIKE '%' + /*data.SHIHARAI_SOUFU_POST*/'100-0001' + '%'
 /*END*/
 /*IF data.SHIHARAI_SOUFU_ADDRESS1 != null*/AND (SHIHARAI_SOUFU_ADDRESS1 + SHIHARAI_SOUFU_ADDRESS2) LIKE '%' + /*data.SHIHARAI_SOUFU_ADDRESS1*/'èZèä' + '%'/*END*/
/*END*/
