SELECT
	CAST(KYOTEN_CD AS varchar) PKEY1,
	CAST(NULL AS varchar) PKEY2,
	CAST('1' AS varchar) MENU_CD,
	CAST('1' AS varchar) ITEM_CD,
	CAST('' AS varchar) MENU_NAME,
	CAST('' AS varchar) ITEM_NAME,
	CAST(0 AS bit) CHANGE_FLG,
	KYOTEN_POST POST,
	KYOTEN_ADDRESS1 ADDRESS1,
	KYOTEN_ADDRESS2 ADDRESS2
  FROM M_KYOTEN
/*BEGIN*/WHERE
 /*IF data.KYOTEN_POST != null*/
 KYOTEN_POST LIKE '%' + /*data.KYOTEN_POST*/'100-0001' + '%'
 /*END*/
 /*IF data.KYOTEN_ADDRESS1 != null*/AND (KYOTEN_ADDRESS1 + KYOTEN_ADDRESS2) LIKE '%' + /*data.KYOTEN_ADDRESS1*/'èZèä' + '%'/*END*/
/*END*/
