SELECT
	TORIHIKISAKI_CD PKEY1,
	CAST(NULL AS varchar) PKEY2,
	CAST('2' AS varchar) MENU_CD,
	CAST('2' AS varchar) ITEM_CD,
	CAST('' AS varchar) MENU_NAME,
	CAST('' AS varchar) ITEM_NAME,
	CAST(0 AS bit) CHANGE_FLG,
	SEIKYUU_SOUFU_POST POST,
	SEIKYUU_SOUFU_ADDRESS1 ADDRESS1,
	SEIKYUU_SOUFU_ADDRESS2 ADDRESS2
  FROM M_TORIHIKISAKI_SEIKYUU
/*BEGIN*/WHERE
 /*IF data.SEIKYUU_SOUFU_POST != null*/
 SEIKYUU_SOUFU_POST LIKE '%' + /*data.SEIKYUU_SOUFU_POST*/'100-0001' + '%'
 /*END*/
 /*IF data.SEIKYUU_SOUFU_ADDRESS1 != null*/AND (SEIKYUU_SOUFU_ADDRESS1 + SEIKYUU_SOUFU_ADDRESS2) LIKE '%' + /*data.SEIKYUU_SOUFU_ADDRESS1*/'èZèä' + '%'/*END*/
/*END*/
