SELECT TOP 1
COUNT(SYSTEM_ID) AS 'COUNT',
SEQ,
TAIRYUU_KBN
FROM
/*IF target == 1*/T_UKEIRE_ENTRY/*END*/
/*IF target == 2*/T_SHUKKA_ENTRY/*END*/
WHERE DELETE_FLG = 0 
/*IF target == 1*/AND UKEIRE_NUMBER = /*number*//*END*/
/*IF target == 2*/AND SHUKKA_NUMBER = /*number*//*END*/
GROUP BY 
SEQ,TAIRYUU_KBN
ORDER BY 
SEQ DESC