SELECT M_GENCHAKU_TIME.GENCHAKU_TIME_CD, M_GENCHAKU_TIME.GENCHAKU_TIME_NAME_RYAKU FROM dbo.M_GENCHAKU_TIME AS M_GENCHAKU_TIME
WHERE DELETE_FLG = 0
/*IF !data.GENCHAKU_TIME_CD.IsNull*/AND GENCHAKU_TIME_CD = /*data.GENCHAKU_TIME_CD.Value*//*END*/
/*IF data.GENCHAKU_TIME_NAME != null*/AND GENCHAKU_TIME_NAME = /*data.GENCHAKU_TIME_NAME*//*END*/
/*IF data.GENCHAKU_TIME_NAME_RYAKU != null*/AND GENCHAKU_TIME_NAME_RYAKU = /*data.GENCHAKU_TIME_NAME_RYAKU*//*END*/
/*IF data.GENCHAKU_TIME_BIKOU != null*/AND GENCHAKU_TIME_BIKOU = /*data.GENCHAKU_TIME_BIKOU*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
