SELECT 
	MCD.REC_ID AS ID
	,MCD.ROW_NO
	,MCD.GYOUSHA_CD
	,MCD.GENBA_CD
	,MG.GENBA_NAME_RYAKU
	,MCD.KIBOU_TIME
	,MCD.ROUND_NO
	,MCD.SAGYOU_TIME_MINUTE
	,MCD.BIKOU
FROM M_COURSE MC
	INNER JOIN M_COURSE_DETAIL MCD 
		ON MC.DAY_CD = MCD.DAY_CD AND MC.COURSE_NAME_CD = MCD.COURSE_NAME_CD
	LEFT JOIN M_GENBA MG 
		ON MCD.GYOUSHA_CD = MG.GYOUSHA_CD AND MCD.GENBA_CD = MG.GENBA_CD
WHERE MC.DELETE_FLG = 0
	AND MC.DAY_CD = /*dayCd*/0
	AND MC.COURSE_NAME_CD = /*courseNameCd*/'000000'
ORDER BY MCD.ROW_NO