SELECT
	NAVI.*
	, CASE
		WHEN NAVI.SAITEKIKA_TAISHO = 1 THEN KYOTEN_C.KYOTEN_CD
		WHEN NAVI.SAITEKIKA_TAISHO = 2 THEN KYOTEN_T.KYOTEN_CD
		ELSE NULL END AS KYOTEN_CD
	, CASE
		WHEN NAVI.SAITEKIKA_TAISHO = 1 THEN KYOTEN_C.KYOTEN_NAME_RYAKU
		WHEN NAVI.SAITEKIKA_TAISHO = 2 THEN KYOTEN_T.KYOTEN_NAME_RYAKU
		ELSE NULL END AS KYOTEN_NAME_RYAKU
	, TEIKI.TEIKI_HAISHA_NUMBER
	, COURSE_NAME.COURSE_NAME_RYAKU
	, UNPAN.GYOUSHA_NAME_RYAKU AS UNPAN_GYOUSHA_NAME_RYAKU
	, UNTEN.SHAIN_NAME_RYAKU AS UNTENSHA_NAME_RYAKU
	, SHASHU.SHASHU_NAME_RYAKU
	, SHARYOU.SHARYOU_NAME_RYAKU
	, SHUPPATSU_GYOUSHA.GYOUSHA_NAME_RYAKU AS SHUPPATSU_GYOUSHA_NAME_RYAKU
	, SHUPPATSU_GENBA.GENBA_NAME_RYAKU AS SHUPPATSU_GENBA_NAME_RYAKU
	, NIOROSHI_GYOUSHA.GYOUSHA_NAME_RYAKU AS NIOROSHI_GYOUSHA_NAME_RYAKU
	, NIOROSHI_GENBA.GENBA_NAME_RYAKU AS NIOROSHI_GENBA_NAME_RYAKU
	, CASE
		WHEN NAVI.SAITEKIKA_TAISHO = 1 THEN COURSE.SAGYOU_BEGIN_HOUR
		WHEN NAVI.SAITEKIKA_TAISHO = 2 THEN TEIKI.SAGYOU_BEGIN_HOUR
		ELSE NULL END AS SAGYOU_BEGIN_HOUR
	, CASE
		WHEN NAVI.SAITEKIKA_TAISHO = 1 THEN COURSE.SAGYOU_BEGIN_MINUTE
		WHEN NAVI.SAITEKIKA_TAISHO = 2 THEN TEIKI.SAGYOU_BEGIN_MINUTE
		ELSE NULL END AS SAGYOU_BEGIN_MINUTE
FROM T_NAVI_DELIVERY NAVI
	LEFT JOIN T_TEIKI_HAISHA_ENTRY TEIKI
		ON NAVI.TEIKI_SYSTEM_ID = TEIKI.SYSTEM_ID AND NAVI.TEIKI_SEQ = TEIKI.SEQ
	LEFT JOIN M_COURSE_NAME COURSE_NAME
		ON NAVI.COURSE_NAME_CD = COURSE_NAME.COURSE_NAME_CD
	LEFT JOIN M_COURSE COURSE
		ON NAVI.DAY_CD = COURSE.DAY_CD AND NAVI.COURSE_NAME_CD = COURSE.COURSE_NAME_CD
	LEFT JOIN M_KYOTEN KYOTEN_T
		ON TEIKI.KYOTEN_CD = KYOTEN_T.KYOTEN_CD
	LEFT JOIN M_KYOTEN KYOTEN_C
		ON COURSE_NAME.KYOTEN_CD = KYOTEN_C.KYOTEN_CD
	LEFT JOIN M_GYOUSHA UNPAN
		ON NAVI.UNPAN_GYOUSHA_CD = UNPAN.GYOUSHA_CD
	LEFT JOIN M_SHAIN UNTEN
		ON NAVI.UNTENSHA_CD = UNTEN.SHAIN_CD
	LEFT JOIN M_SHASHU SHASHU
		ON NAVI.SHASHU_CD = SHASHU.SHASHU_CD
	LEFT JOIN M_SHARYOU SHARYOU
		ON NAVI.UNPAN_GYOUSHA_CD = SHARYOU.GYOUSHA_CD AND NAVI.SHARYOU_CD = SHARYOU.SHARYOU_CD
	LEFT JOIN M_GYOUSHA SHUPPATSU_GYOUSHA
		ON NAVI.SHUPPATSU_GYOUSHA_CD = SHUPPATSU_GYOUSHA.GYOUSHA_CD
	LEFT JOIN M_GENBA SHUPPATSU_GENBA
		ON NAVI.SHUPPATSU_GYOUSHA_CD = SHUPPATSU_GENBA.GYOUSHA_CD AND NAVI.SHUPPATSU_GENBA_CD = SHUPPATSU_GENBA.GENBA_CD
	LEFT JOIN M_GYOUSHA NIOROSHI_GYOUSHA
		ON NAVI.NIOROSHI_GYOUSHA_CD = NIOROSHI_GYOUSHA.GYOUSHA_CD
	LEFT JOIN M_GENBA NIOROSHI_GENBA
		ON NAVI.NIOROSHI_GYOUSHA_CD = NIOROSHI_GENBA.GYOUSHA_CD AND NAVI.NIOROSHI_GENBA_CD = NIOROSHI_GENBA.GENBA_CD
WHERE NAVI.DELETE_FLG = 0
	AND NAVI.SYSTEM_ID = /*systemId*/1