SELECT 
	THD.DETAIL_SYSTEM_ID AS ID
	,THD.ROW_NUMBER AS ROW_NO
	,THD.GYOUSHA_CD
	,THD.GENBA_CD
	,MG.GENBA_NAME_RYAKU
	,THD.KIBOU_TIME
	,THD.ROUND_NO
	,THD.SAGYOU_TIME_MINUTE
	,THD.MEISAI_BIKOU AS BIKOU
FROM T_TEIKI_HAISHA_DETAIL THD
	LEFT JOIN M_GENBA MG
		ON THD.GYOUSHA_CD = MG.GYOUSHA_CD AND THD.GENBA_CD = MG.GENBA_CD
WHERE THD.SYSTEM_ID = /*systemId*/12782
	AND THD.SEQ = /*seq*/4
ORDER BY THD.ROW_NUMBER