SELECT 
    SHOU.SYS_ID,
	(SHOU.SHOUHIZEI_RATE * 100) SHOUHIZEI_RATE,
	SHOU.TEKIYOU_BEGIN,
	SHOU.TEKIYOU_END,
	SHOU.CREATE_USER,
	SHOU.CREATE_DATE,
	SHOU.CREATE_PC,
	SHOU.UPDATE_USER,
	SHOU.UPDATE_DATE,
	SHOU.UPDATE_PC,
	SHOU.DELETE_FLG,
	SHOU.TIME_STAMP
FROM 
    dbo.M_SHOUHIZEI SHOU
/*BEGIN*/WHERE
 /*IF !data.SYS_ID.IsNull */SHOU.SYS_ID = /*data.SYS_ID*/0/*END*/
 /*IF !data.SHOUHIZEI_RATE.IsNull */AND SHOU.SHOUHIZEI_RATE = /*data.SHOUHIZEI_RATE*/0/*END*/
 /*IF data.SEARCH_TEKIYOU_BEGIN != null*/AND CONVERT(nvarchar, SHOU.TEKIYOU_BEGIN, 120) LIKE '%' +  /*data.SEARCH_TEKIYOU_BEGIN*/ + '%'/*END*/
 /*IF data.SEARCH_TEKIYOU_END != null*/AND CONVERT(nvarchar, SHOU.TEKIYOU_END, 120) LIKE '%' +  /*data.SEARCH_TEKIYOU_END*/ + '%'/*END*/
 /*IF data.CREATE_USER != null*/AND SHOU.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, SHOU.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null*/AND SHOU.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, SHOU.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
 /*IF !deletechuFlg*/AND SHOU.DELETE_FLG = 0/*END*/
 /*IF tekiyounaiFlg || deletechuFlg || tekiyougaiFlg*/AND (1 = 0/*END*/
 /*IF tekiyounaiFlg*/OR (((SHOU.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= SHOU.TEKIYOU_END) or (SHOU.TEKIYOU_BEGIN <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) and SHOU.TEKIYOU_END IS NULL) or (SHOU.TEKIYOU_BEGIN IS NULL and CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= SHOU.TEKIYOU_END) or (SHOU.TEKIYOU_BEGIN IS NULL and SHOU.TEKIYOU_END IS NULL)) and SHOU.DELETE_FLG = 0)/*END*/
 /*IF deletechuFlg*/OR SHOU.DELETE_FLG = /*deletechuFlg*/0/*END*/
 /*IF tekiyougaiFlg*/OR ((SHOU.TEKIYOU_BEGIN > CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) or CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) > SHOU.TEKIYOU_END) and SHOU.DELETE_FLG = 0)/*END*/
 /*IF tekiyounaiFlg || deletechuFlg || tekiyougaiFlg*/ )/*END*/
/*END*/
ORDER BY SHOU.SYS_ID
