SELECT
	HIN.*
	,DEN.DENSHU_KBN_NAME_RYAKU
FROM 
	dbo.M_HINMEI HIN
		INNER JOIN dbo.M_DENSHU_KBN DEN ON DEN.DENSHU_KBN_CD = HIN.DENSHU_KBN_CD
WHERE
	HIN.HINMEI_CD = /*data.HINMEI_CD*/''
/*IF !data.DENSHU_KBN_CD.IsNull*/AND (HIN.DENSHU_KBN_CD = /*data.DENSHU_KBN_CD*/1 OR HIN.DENSHU_KBN_CD = 9)/*END*/
AND (HIN.DENPYOU_KBN_CD = /*data.DENPYOU_KBN_CD*/1 OR HIN.DENPYOU_KBN_CD = 9)
AND HIN.DELETE_FLG = 0
ORDER BY HIN.HINMEI_CD