--品名読込ボタン用(支払)
SELECT
	HIN.*
	,DEN.DENSHU_KBN_NAME_RYAKU
	,UNI.UNIT_NAME_RYAKU
FROM 
	dbo.M_HINMEI HIN
		INNER JOIN dbo.M_DENSHU_KBN DEN ON DEN.DENSHU_KBN_CD = HIN.DENSHU_KBN_CD
		LEFT JOIN dbo.M_UNIT UNI ON UNI.UNIT_CD = HIN.UNIT_CD 
WHERE
--支払が対象
(HIN.DENPYOU_KBN_CD = 2 OR HIN.DENPYOU_KBN_CD = 9)
AND HIN.DELETE_FLG = 0
/*IF data.SHURUI_CD != null*/ AND HIN.SHURUI_CD = /*data.SHURUI_CD*/ /*END*/
ORDER BY HIN.HINMEI_CD