SELECT
    KHT.*
    ,ISNULL(HM.HINMEI_NAME_RYAKU,N'') AS HINMEI_NAME_RYAKU
    ,ISNULL(DS.DENSHU_KBN_NAME_RYAKU,N'') AS DENSHU_KBN_NAME_RYAKU
    ,ISNULL(UN.UNIT_NAME_RYAKU,N'') AS UNIT_NAME_RYAKU
    ,ISNULL(GSA.GYOUSHA_NAME_RYAKU,N'') AS UNPAN_GYOUSHA_RYAKU
    ,ISNULL(GS.GYOUSHA_NAME_RYAKU,N'') AS NIOROSHI_GYOUSHA_RYAKU
    ,ISNULL(GB.GENBA_NAME_RYAKU,N'') AS NIOROSHI_GENBA_RYAKU
FROM
    dbo.M_KIHON_HINMEI_TANKA KHT
    LEFT JOIN dbo.M_HINMEI HM ON HM.HINMEI_CD = KHT.HINMEI_CD
    LEFT JOIN dbo.M_DENSHU_KBN DS ON DS.DENSHU_KBN_CD = KHT.DENSHU_KBN_CD
    LEFT JOIN dbo.M_UNIT UN ON UN.UNIT_CD = KHT.UNIT_CD
    LEFT JOIN dbo.M_GYOUSHA GSA ON GSA.GYOUSHA_CD = KHT.UNPAN_GYOUSHA_CD
    LEFT JOIN dbo.M_GYOUSHA GS ON GS.GYOUSHA_CD = KHT.NIOROSHI_GYOUSHA_CD
    LEFT JOIN dbo.M_GENBA GB ON GB.GYOUSHA_CD = KHT.NIOROSHI_GYOUSHA_CD AND GB.GENBA_CD = KHT.NIOROSHI_GENBA_CD
WHERE
	KHT.DENPYOU_KBN_CD =/*data.DENPYOU_KBN_CD*/0
	AND KHT.DELETE_FLG = 0
ORDER BY KHT.DENSHU_KBN_CD, KHT.HINMEI_CD, KHT.UNIT_CD, KHT.UNPAN_GYOUSHA_CD, KHT.NIOROSHI_GYOUSHA_CD, KHT.NIOROSHI_GENBA_CD, KHT.TEKIYOU_BEGIN
