SELECT DISTINCT N'コース明細内訳マスタ' AS NAME FROM M_COURSE_DETAIL_ITEMS WHERE HINMEI_CD IN /*HINMEI_CD*/('')
UNION
SELECT DISTINCT N'在庫比率マスタ' AS NAME FROM M_ZAIKO_HIRITSU WHERE HINMEI_CD IN /*HINMEI_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'個別品名単価マスタ' AS NAME FROM M_KOBETSU_HINMEI_TANKA WHERE HINMEI_CD IN /*HINMEI_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'引合現場単価品名マスタ' AS NAME
FROM
    M_HIKIAI_GENBA_TEIKI_HINMEI 
    INNER JOIN M_HIKIAI_GENBA ON M_HIKIAI_GENBA_TEIKI_HINMEI.HIKIAI_GYOUSHA_USE_FLG = M_HIKIAI_GENBA.HIKIAI_GYOUSHA_USE_FLG  AND M_HIKIAI_GENBA_TEIKI_HINMEI.GYOUSHA_CD = M_HIKIAI_GENBA.GYOUSHA_CD AND M_HIKIAI_GENBA_TEIKI_HINMEI.GENBA_CD = M_HIKIAI_GENBA.GENBA_CD
WHERE
    HINMEI_CD IN /*HINMEI_CD*/('') AND M_HIKIAI_GENBA.DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'引合現場月極品名マスタ' AS NAME
FROM
    M_HIKIAI_GENBA_TSUKI_HINMEI
    INNER JOIN M_HIKIAI_GENBA ON M_HIKIAI_GENBA_TSUKI_HINMEI.HIKIAI_GYOUSHA_USE_FLG = M_HIKIAI_GENBA.HIKIAI_GYOUSHA_USE_FLG  AND M_HIKIAI_GENBA_TSUKI_HINMEI.GYOUSHA_CD = M_HIKIAI_GENBA.GYOUSHA_CD AND M_HIKIAI_GENBA_TSUKI_HINMEI.GENBA_CD = M_HIKIAI_GENBA.GENBA_CD
WHERE
    HINMEI_CD IN /*HINMEI_CD*/('') AND M_HIKIAI_GENBA.DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'仮現場単価品名マスタ' AS NAME
FROM
    M_KARI_GENBA_TEIKI_HINMEI
    INNER JOIN M_KARI_GENBA ON M_KARI_GENBA_TEIKI_HINMEI.GYOUSHA_CD = M_KARI_GENBA.GYOUSHA_CD AND M_KARI_GENBA_TEIKI_HINMEI.GENBA_CD = M_KARI_GENBA.GENBA_CD
WHERE
    HINMEI_CD IN /*HINMEI_CD*/('') AND M_KARI_GENBA.DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'仮現場月極品名マスタ' AS NAME
FROM
    M_KARI_GENBA_TSUKI_HINMEI
    INNER JOIN M_KARI_GENBA ON M_KARI_GENBA_TSUKI_HINMEI.GYOUSHA_CD = M_KARI_GENBA.GYOUSHA_CD AND M_KARI_GENBA_TSUKI_HINMEI.GENBA_CD = M_KARI_GENBA.GENBA_CD
WHERE
    HINMEI_CD IN /*HINMEI_CD*/('') AND M_KARI_GENBA.DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'現場単価品名マスタ' AS NAME
FROM
    M_GENBA_TEIKI_HINMEI
    INNER JOIN M_GENBA ON M_GENBA_TEIKI_HINMEI.GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND M_GENBA_TEIKI_HINMEI.GENBA_CD = M_GENBA.GENBA_CD
WHERE
    HINMEI_CD IN /*HINMEI_CD*/('') AND M_GENBA.DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'現場月極品名マスタ' AS NAME
FROM
    M_GENBA_TSUKI_HINMEI
    INNER JOIN M_GENBA ON M_GENBA_TSUKI_HINMEI.GYOUSHA_CD = M_GENBA.GYOUSHA_CD AND M_GENBA_TSUKI_HINMEI.GENBA_CD = M_GENBA.GENBA_CD
WHERE
    HINMEI_CD IN /*HINMEI_CD*/('') AND M_GENBA.DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'換算マスタ' AS NAME FROM M_KANSAN WHERE HINMEI_CD IN /*HINMEI_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'計量調整マスタ' AS NAME FROM M_KEIRYOU_CHOUSEI WHERE HINMEI_CD IN /*HINMEI_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'基本品名単価マスタ' AS NAME FROM M_KIHON_HINMEI_TANKA WHERE HINMEI_CD IN /*HINMEI_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'個別品名マスタ' AS NAME FROM M_KOBETSU_HINMEI WHERE HINMEI_CD IN /*HINMEI_CD*/('') AND DELETE_FLG = 'False'