SELECT 
    HINMEI.*
	,ISNULL(MJB.JISSEKI_BUNRUI_NAME_RYAKU,N'') AS JISSEKI_BUNRUI_NAME_RYAKU
    ,ISNULL(UNIT.UNIT_NAME_RYAKU,N'') AS UNIT_NAME_RYAKU
    ,ISNULL(DENSHU.DENSHU_KBN_NAME_RYAKU,N'') AS DENSHU_KBN_NAME_RYAKU
    ,ISNULL(DENPYOU.DENPYOU_KBN_NAME,N'') AS DENPYOU_KBN_NAME_RYAKU
    ,ISNULL(SHURUI.SHURUI_NAME_RYAKU,N'') AS SHURUI_NAME_RYAKU
    ,ISNULL(BUNRUI.BUNRUI_NAME_RYAKU,N'') AS BUNRUI_NAME_RYAKU
    ,ISNULL(HOUKOKUSHO.HOUKOKUSHO_BUNRUI_NAME_RYAKU,N'') AS HOUKOKUSHO_BUNRUI_NAME_RYAKU
    ,ISNULL(SHU1.HAIKI_SHURUI_NAME_RYAKU,N'') AS SP_CHOKKOU_HAIKI_SHURUI_NAME
    ,ISNULL(SHU2.HAIKI_SHURUI_NAME_RYAKU,N'') AS SP_TSUMIKAE_HAIKI_SHURUI_NAME
    ,ISNULL(SHU3.HAIKI_SHURUI_NAME_RYAKU,N'') AS KP_HAIKI_SHURUI_NAME
    ,ISNULL(SHU4.HAIKI_SHURUI_NAME,N'') AS DM_HAIKI_SHURUI_NAME
	,ISNULL(HAIKI.HAIKI_NAME_RYAKU,N'') AS HAIKI_MONO_MEISHO_NAME --20250314
	,ISNULL(NISUGATA.NISUGATA_NAME,N'') AS NISUGATA_NAME
	,ISNULL(SHOBUN.SHOBUN_HOUHOU_NAME,N'') AS SHOBUN_HOHO_NAME
	,CONVERT(varchar,N'') AS ZEI_KBN_NAME_RYAKU
FROM 
    dbo.M_HINMEI HINMEI
	LEFT JOIN dbo.M_JISSEKI_BUNRUI MJB ON MJB.JISSEKI_BUNRUI_CD = HINMEI.JISSEKI_BUNRUI_CD
	LEFT JOIN dbo.M_UNIT UNIT ON UNIT.UNIT_CD = HINMEI.UNIT_CD
	LEFT JOIN dbo.M_DENSHU_KBN DENSHU ON DENSHU.DENSHU_KBN_CD = HINMEI.DENSHU_KBN_CD
	LEFT JOIN dbo.M_DENPYOU_KBN DENPYOU ON DENPYOU.DENPYOU_KBN_CD = HINMEI.DENPYOU_KBN_CD
	LEFT JOIN dbo.M_SHURUI SHURUI ON SHURUI.SHURUI_CD = HINMEI.SHURUI_CD
	LEFT JOIN dbo.M_BUNRUI BUNRUI ON BUNRUI.BUNRUI_CD = HINMEI.BUNRUI_CD
	LEFT JOIN dbo.M_HOUKOKUSHO_BUNRUI HOUKOKUSHO ON HOUKOKUSHO.HOUKOKUSHO_BUNRUI_CD = HINMEI.HOUKOKUSHO_BUNRUI_CD
	LEFT JOIN dbo.M_HAIKI_SHURUI SHU1 ON SHU1.HAIKI_KBN_CD = 1 AND SHU1.HAIKI_SHURUI_CD = HINMEI.SP_CHOKKOU_HAIKI_SHURUI_CD
	LEFT JOIN dbo.M_HAIKI_SHURUI SHU2 ON SHU2.HAIKI_KBN_CD = 3 AND SHU2.HAIKI_SHURUI_CD = HINMEI.SP_TSUMIKAE_HAIKI_SHURUI_CD
	LEFT JOIN dbo.M_HAIKI_SHURUI SHU3 ON SHU3.HAIKI_KBN_CD = 2 AND SHU3.HAIKI_SHURUI_CD = HINMEI.KP_HAIKI_SHURUI_CD
	LEFT JOIN dbo.M_DENSHI_HAIKI_SHURUI SHU4 ON SHU4.HAIKI_SHURUI_CD = HINMEI.DM_HAIKI_SHURUI_CD
	LEFT JOIN dbo.M_HAIKI_NAME HAIKI ON HAIKI.HAIKI_NAME_CD = HINMEI.HAIKI_MONO_MEISHO_CD --20250314
	LEFT JOIN dbo.M_NISUGATA NISUGATA ON NISUGATA.NISUGATA_CD = HINMEI.NISUGATA_CD
	LEFT JOIN dbo.M_SHOBUN_HOUHOU SHOBUN ON SHOBUN.SHOBUN_HOUHOU_CD = HINMEI.SHOBUN_HOHO_CD
/*BEGIN*/WHERE
 /*IF data.HINMEI_CD != null*/HINMEI.HINMEI_CD LIKE '%' + /*data.HINMEI_CD*/'000001' + '%'/*END*/
 /*IF data.HINMEI_NAME != null*/AND HINMEI.HINMEI_NAME LIKE '%' +  /*data.HINMEI_NAME*/ + '%'/*END*/
 /*IF data.HINMEI_NAME_RYAKU != null*/AND HINMEI.HINMEI_NAME_RYAKU LIKE '%' +  /*data.HINMEI_NAME_RYAKU*/ + '%'/*END*/
 /*IF data.HINMEI_FURIGANA != null*/AND HINMEI.HINMEI_FURIGANA LIKE '%' +  /*data.HINMEI_FURIGANA*/ + '%'/*END*/
 /*IF !data.UNIT_CD.IsNull*/AND HINMEI.UNIT_CD = /*data.UNIT_CD*//*END*/
 /*IF !data.TC_KOME_KANZANKEISU.IsNull*/AND HINMEI.TC_KOME_KANZANKEISU = /*data.TC_KOME_KANZANKEISU.Value*//*END*/ --20250313
 /*IF !data.DENSHU_KBN_CD.IsNull*/AND HINMEI.DENSHU_KBN_CD = /*data.DENSHU_KBN_CD.Value*//*END*/
 /*IF !data.DENPYOU_KBN_CD.IsNull*/AND HINMEI.DENPYOU_KBN_CD = /*data.DENPYOU_KBN_CD.Value*//*END*/
 /*IF !data.ZEI_KBN_CD.IsNull*/AND HINMEI.ZEI_KBN_CD = /*data.ZEI_KBN_CD.Value*//*END*/
 /*IF data.SHURUI_CD != null*/AND HINMEI.SHURUI_CD LIKE '%' +  /*data.SHURUI_CD*/ + '%'/*END*/
 /*IF data.BUNRUI_CD != null*/AND HINMEI.BUNRUI_CD LIKE '%' +  /*data.BUNRUI_CD*/ + '%'/*END*/
 /*IF data.HOUKOKUSHO_BUNRUI_CD != null*/AND HINMEI.HOUKOKUSHO_BUNRUI_CD LIKE '%' +  /*data.HOUKOKUSHO_BUNRUI_CD*/ + '%'/*END*/
 /*IF data.CREATE_USER != null*/AND HINMEI.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, HINMEI.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null*/AND HINMEI.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, HINMEI.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*END*/
ORDER BY HINMEI.HINMEI_CD