SELECT * FROM dbo.M_SYUKKINSAKI
WHERE 
/*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
 DELETE_FLG = 0
-- ELSE
 1 = 1
/*END*/
/*IF data.SYUKKINSAKI_CD != null*/AND SYUKKINSAKI_CD = /*data.SYUKKINSAKI_CD*//*END*/
/*IF data.SYUKKINSAKI_NAME1 != null*/AND SYUKKINSAKI_NAME1 = /*data.SYUKKINSAKI_NAME1*//*END*/
/*IF data.SYUKKINSAKI_NAME2 != null*/AND SYUKKINSAKI_NAME2 = /*data.SYUKKINSAKI_NAME2*//*END*/
/*IF data.SYUKKINSAKI_NAME_RYAKU != null*/AND SYUKKINSAKI_NAME_RYAKU = /*data.SYUKKINSAKI_NAME_RYAKU*//*END*/
/*IF data.SYUKKINSAKI_FURIGANA != null*/AND SYUKKINSAKI_FURIGANA = /*data.SYUKKINSAKI_FURIGANA*//*END*/
/*IF data.SYUKKINSAKI_TEL != null*/AND SYUKKINSAKI_TEL = /*data.SYUKKINSAKI_TEL*//*END*/
/*IF data.SYUKKINSAKI_FAX != null*/AND SYUKKINSAKI_FAX = /*data.SYUKKINSAKI_FAX*//*END*/
/*IF data.SYUKKINSAKI_POST != null*/AND SYUKKINSAKI_POST = /*data.SYUKKINSAKI_POST*//*END*/
/*IF !data.SYUKKINSAKI_TODOUFUKEN_CD.IsNull*/AND SYUKKINSAKI_TODOUFUKEN_CD = /*data.SYUKKINSAKI_TODOUFUKEN_CD.Value*//*END*/
/*IF data.SYUKKINSAKI_ADDRESS1 != null*/AND SYUKKINSAKI_ADDRESS1 = /*data.SYUKKINSAKI_ADDRESS1*//*END*/
/*IF data.SYUKKINSAKI_ADDRESS2 != null*/AND SYUKKINSAKI_ADDRESS2 = /*data.SYUKKINSAKI_ADDRESS2*//*END*/
/*IF !data.TORIKOMI_KBN.IsNull*/AND TORIKOMI_KBN = /*data.TORIKOMI_KBN.Value*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
