 SELECT 
 T_UKETSUKE_SS_ENTRY.HAISHA_JOKYO_CD
,T_UKETSUKE_SS_ENTRY.EIGYOU_TANTOUSHA_CD
,T_UKETSUKE_SS_ENTRY.EIGYOU_TANTOUSHA_NAME 
,T_UKETSUKE_SS_ENTRY.TORIHIKISAKI_CD
,T_UKETSUKE_SS_ENTRY.TORIHIKISAKI_NAME
,T_UKETSUKE_SS_ENTRY.GYOUSHA_CD
,T_UKETSUKE_SS_ENTRY.GYOUSHA_NAME
,T_UKETSUKE_SS_ENTRY.GENBA_CD
,T_UKETSUKE_SS_ENTRY.GENBA_NAME
,T_UKETSUKE_SS_ENTRY.UNPAN_GYOUSHA_CD
,T_UKETSUKE_SS_ENTRY.UNPAN_GYOUSHA_NAME
,''
,''
,''
,''
,T_UKETSUKE_SS_ENTRY.NIOROSHI_GYOUSHA_CD
,T_UKETSUKE_SS_ENTRY.NIOROSHI_GYOUSHA_NAME
,T_UKETSUKE_SS_ENTRY.NIOROSHI_GENBA_CD
,T_UKETSUKE_SS_ENTRY.NIOROSHI_GENBA_NAME
,T_UKETSUKE_SS_ENTRY.SHARYOU_CD
,T_UKETSUKE_SS_ENTRY.SHARYOU_NAME
,T_UKETSUKE_SS_ENTRY.SHASHU_CD
,T_UKETSUKE_SS_ENTRY.SHASHU_NAME
,T_UKETSUKE_SS_ENTRY.UNTENSHA_CD
,T_UKETSUKE_SS_ENTRY.UNTENSHA_NAME
,T_UKETSUKE_SS_ENTRY.MANIFEST_SHURUI_CD
,M_MANIFEST_SHURUI.MANIFEST_SHURUI_NAME_RYAKU
,T_UKETSUKE_SS_ENTRY.MANIFEST_TEHAI_CD
,M_MANIFEST_TEHAI.MANIFEST_TEHAI_NAME_RYAKU
,T_UKETSUKE_SS_ENTRY.CONTENA_SOUSA_CD
,M_CONTENA_SOUSA.CONTENA_SOUSA_NAME_RYAKU
,T_UKETSUKE_SS_ENTRY.UKETSUKE_BIKOU1
,T_UKETSUKE_SS_ENTRY.UKETSUKE_BIKOU2
,T_UKETSUKE_SS_ENTRY.UKETSUKE_BIKOU3
,'1' AS GENCHAKU_TIME_CD
-- No.2594-->
,T_UKETSUKE_SS_ENTRY.HOJOIN_CD
-- No.2594<-
 FROM T_UKETSUKE_SS_ENTRY
      LEFT JOIN M_MANIFEST_SHURUI
         ON M_MANIFEST_SHURUI.MANIFEST_SHURUI_CD = T_UKETSUKE_SS_ENTRY.MANIFEST_SHURUI_CD
      LEFT JOIN M_MANIFEST_TEHAI
         ON M_MANIFEST_TEHAI.MANIFEST_TEHAI_CD = T_UKETSUKE_SS_ENTRY.MANIFEST_TEHAI_CD
      LEFT JOIN M_CONTENA_SOUSA
         ON M_CONTENA_SOUSA.CONTENA_SOUSA_CD = T_UKETSUKE_SS_ENTRY.CONTENA_SOUSA_CD
 WHERE T_UKETSUKE_SS_ENTRY.UKETSUKE_NUMBER = /*data.UKETSUKE_NUMBER*/
   AND  T_UKETSUKE_SS_ENTRY.DELETE_FLG = 0
 UNION ALL
 SELECT 
 T_UKETSUKE_SK_ENTRY.HAISHA_JOKYO_CD
,T_UKETSUKE_SK_ENTRY.EIGYOU_TANTOUSHA_CD
,T_UKETSUKE_SK_ENTRY.EIGYOU_TANTOUSHA_NAME
,T_UKETSUKE_SK_ENTRY.TORIHIKISAKI_CD
,T_UKETSUKE_SK_ENTRY.TORIHIKISAKI_NAME
,T_UKETSUKE_SK_ENTRY.GYOUSHA_CD
,T_UKETSUKE_SK_ENTRY.GYOUSHA_NAME
,T_UKETSUKE_SK_ENTRY.GENBA_CD
,T_UKETSUKE_SK_ENTRY.GENBA_NAME
,T_UKETSUKE_SK_ENTRY.UNPAN_GYOUSHA_CD
,T_UKETSUKE_SK_ENTRY.UNPAN_GYOUSHA_NAME
,''
,''
,''
,''
,T_UKETSUKE_SK_ENTRY.NIZUMI_GYOUSHA_CD AS NIOROSHI_GYOUSHA_CD
,T_UKETSUKE_SK_ENTRY.NIZUMI_GYOUSHA_NAME AS NIOROSHI_GYOUSHA_NAME
,T_UKETSUKE_SK_ENTRY.NIZUMI_GENBA_CD AS NIOROSHI_GENBA_CD
,T_UKETSUKE_SK_ENTRY.NIZUMI_GENBA_NAME AS NIOROSHI_GENBA_NAME
,T_UKETSUKE_SK_ENTRY.SHARYOU_CD
,T_UKETSUKE_SK_ENTRY.SHARYOU_NAME
,T_UKETSUKE_SK_ENTRY.SHASHU_CD
,T_UKETSUKE_SK_ENTRY.SHASHU_NAME
,T_UKETSUKE_SK_ENTRY.UNTENSHA_CD
,T_UKETSUKE_SK_ENTRY.UNTENSHA_NAME
,T_UKETSUKE_SK_ENTRY.MANIFEST_SHURUI_CD
,M_MANIFEST_SHURUI.MANIFEST_SHURUI_NAME_RYAKU
,T_UKETSUKE_SK_ENTRY.MANIFEST_TEHAI_CD
,M_MANIFEST_TEHAI.MANIFEST_TEHAI_NAME_RYAKU
,''
,''
,T_UKETSUKE_SK_ENTRY.UKETSUKE_BIKOU1
,T_UKETSUKE_SK_ENTRY.UKETSUKE_BIKOU2
,T_UKETSUKE_SK_ENTRY.UKETSUKE_BIKOU3
,'2' AS GENCHAKU_TIME_CD
-- No.2594-->
,T_UKETSUKE_SK_ENTRY.HOJOIN_CD
-- No.2594<--
 FROM T_UKETSUKE_SK_ENTRY
      LEFT JOIN M_MANIFEST_SHURUI
         ON M_MANIFEST_SHURUI.MANIFEST_SHURUI_CD = T_UKETSUKE_SK_ENTRY.MANIFEST_SHURUI_CD
      LEFT JOIN M_MANIFEST_TEHAI
         ON M_MANIFEST_TEHAI.MANIFEST_TEHAI_CD = T_UKETSUKE_SK_ENTRY.MANIFEST_TEHAI_CD
 WHERE T_UKETSUKE_SK_ENTRY.UKETSUKE_NUMBER = /*data.UKETSUKE_NUMBER*/
   AND  T_UKETSUKE_SK_ENTRY.DELETE_FLG = 0
 UNION ALL
 SELECT 
 ''
,T_UKETSUKE_MK_ENTRY.EIGYOU_TANTOUSHA_CD
,T_UKETSUKE_MK_ENTRY.EIGYOU_TANTOUSHA_NAME
,T_UKETSUKE_MK_ENTRY.TORIHIKISAKI_CD
,T_UKETSUKE_MK_ENTRY.TORIHIKISAKI_NAME
,T_UKETSUKE_MK_ENTRY.GYOUSHA_CD
,T_UKETSUKE_MK_ENTRY.GYOUSHA_NAME
,T_UKETSUKE_MK_ENTRY.GENBA_CD
,T_UKETSUKE_MK_ENTRY.GENBA_NAME
,T_UKETSUKE_MK_ENTRY.UNPAN_GYOUSHA_CD
,T_UKETSUKE_MK_ENTRY.UNPAN_GYOUSHA_NAME
,''
,''
,''
,''
,T_UKETSUKE_MK_ENTRY.NIOROSHI_GYOUSHA_CD
,T_UKETSUKE_MK_ENTRY.NIOROSHI_GYOUSHA_NAME
,T_UKETSUKE_MK_ENTRY.NIOROSHI_GENBA_CD
,T_UKETSUKE_MK_ENTRY.NIOROSHI_GENBA_NAME
,T_UKETSUKE_MK_ENTRY.SHARYOU_CD
,T_UKETSUKE_MK_ENTRY.SHARYOU_NAME
,T_UKETSUKE_MK_ENTRY.SHASHU_CD
,T_UKETSUKE_MK_ENTRY.SHASHU_NAME
,''
,''
,''
,''
,''
,''
,''
,''
,T_UKETSUKE_MK_ENTRY.UKETSUKE_BIKOU1
,T_UKETSUKE_MK_ENTRY.UKETSUKE_BIKOU2
,T_UKETSUKE_MK_ENTRY.UKETSUKE_BIKOU3
,'1' AS GENCHAKU_TIME_CD
-- No.2594-->
,''
-- No.2594<--
 FROM T_UKETSUKE_MK_ENTRY
 WHERE T_UKETSUKE_MK_ENTRY.UKETSUKE_NUMBER = /*data.UKETSUKE_NUMBER*/
   AND  T_UKETSUKE_MK_ENTRY.DELETE_FLG = 0