//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DenManiJigyoujyouIchiran.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JIGYOUSHA_KBN_TEXT {
            get {
                return ((string)(this["JIGYOUSHA_KBN_TEXT"]));
            }
            set {
                this["JIGYOUSHA_KBN_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ICHIRAN_ALERT_KENSUU {
            get {
                return ((string)(this["ICHIRAN_ALERT_KENSUU"]));
            }
            set {
                this["ICHIRAN_ALERT_KENSUU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JIGYOUSHA_NAME_TEXT {
            get {
                return ((string)(this["JIGYOUSHA_NAME_TEXT"]));
            }
            set {
                this["JIGYOUSHA_NAME_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JIGYOUJOU_NAME_TEXT {
            get {
                return ((string)(this["JIGYOUJOU_NAME_TEXT"]));
            }
            set {
                this["JIGYOUJOU_NAME_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JIGYOUJOU_ADDRESS_TEXT {
            get {
                return ((string)(this["JIGYOUJOU_ADDRESS_TEXT"]));
            }
            set {
                this["JIGYOUJOU_ADDRESS_TEXT"] = value;
            }
        }
    }
}
