SELECT 
    SHURUI.SHURUI_CD as SHURUI_CD
    ,SHURUI.SHURUI_NAME_RYAKU as SHURUI_NAME_RYAKU
FROM 
    dbo.M_SHURUI SHURUI
/*BEGIN*/WHERE
 /*IF data.SHURUI_CD != null*/ SHURUI.SHURUI_CD LIKE '%' + /*data.SHURUI_CD*/ + '%'/*END*/
 /*END*/