SELECT
	HIN.*
FROM 
	dbo.M_HINMEI HIN
WHERE
	HIN.HINMEI_CD = /*data.HINMEI_CD*/''
/*IF data.SHURUI_CD != null*/AND HIN.SHURUI_CD = /*data.SHURUI_CD*/''/*END*/
AND (HIN.DENPYOU_KBN_CD = /*data.DENPYOU_KBN_CD*/1 OR HIN.DENPYOU_KBN_CD = 9)
AND HIN.DELETE_FLG = 0
ORDER BY HIN.HINMEI_CD