SELECT 
    KAN.*
    ,ISNULL(DEN.DENPYOU_KBN_NAME_RYAKU,N'') AS DENPYOU_KBN_NAME_RYAKU
	,ISNULL(HIN.HINMEI_NAME_RYAKU,N'') AS HINMEI_NAME_RYAKU
	,ISNULL(HIN.SHURUI_CD,N'') AS SHURUI_CD
	,ISNULL(UNI.UNIT_NAME_RYAKU,N'') AS UNIT_NAME_RYAKU
	,KAN.DENPYOU_KBN_CD AS UK_DENPYOU_KBN_CD
	,KAN.HINMEI_CD AS UK_HINMEI_CD
	,KAN.UNIT_CD AS UK_UNIT_CD
FROM 
    dbo.M_HINMEI HIN
	LEFT JOIN dbo.M_KANSAN KAN ON HIN.HINMEI_CD = KAN.HINMEI_CD
	LEFT JOIN dbo.M_DENPYOU_KBN DEN ON DEN.DENPYOU_KBN_CD = KAN.DENPYOU_KBN_CD
	LEFT JOIN dbo.M_UNIT UNI ON UNI.UNIT_CD = KAN.UNIT_CD
WHERE
	KAN.DENPYOU_KBN_CD = /*data.DENPYOU_KBN_CD*/0
	/*IF data.HINMEI_NAME_RYAKU != null && data.HINMEI_HINMEI_NAME_RYAKU != '' */AND HIN.HINMEI_NAME_RYAKU LIKE '%' + /*data.HINMEI_NAME_RYAKU*/ + '%'/*END*/
	/*IF !deletechuFlg*/AND KAN.DELETE_FLG = /*deletechuFlg*/0/*END*/
ORDER BY KAN.HINMEI_CD, KAN.UNIT_CD
