SELECT 
    KAN.*
    ,ISNULL(DEN.DENPYOU_KBN_NAME_RYAKU,N'') AS DENPYOU_KBN_NAME_RYAKU
	,ISNULL(HIN.HINMEI_NAME_RYAKU,N'') AS HINMEI_NAME_RYAKU
	,ISNULL(HIN.SHURUI_CD,N'') AS SHURUI_CD
	,ISNULL(UNI.UNIT_NAME_RYAKU,N'') AS UNIT_NAME_RYAKU
	,KAN.DENPYOU_KBN_CD AS UK_DENPYOU_KBN_CD
	,KAN.HINMEI_CD AS UK_HINMEI_CD
	,KAN.UNIT_CD AS UK_UNIT_CD
FROM 
    dbo.M_KANSAN KAN
	LEFT JOIN dbo.M_DENPYOU_KBN DEN ON DEN.DENPYOU_KBN_CD = KAN.DENPYOU_KBN_CD
	LEFT JOIN dbo.M_HINMEI HIN ON HIN.HINMEI_CD = KAN.HINMEI_CD
	LEFT JOIN dbo.M_UNIT UNI ON UNI.UNIT_CD = KAN.UNIT_CD
WHERE
	KAN.DENPYOU_KBN_CD = /*data.DENPYOU_KBN_CD*/0
	/*IF data.HINMEI_CD != null && data.HINMEI_CD != '' */AND KAN.HINMEI_CD LIKE '%' + /*data.HINMEI_CD*/ + '%'/*END*/
	/*IF !data.UNIT_CD.IsNull */ AND KAN.UNIT_CD = /*data.UNIT_CD*/0/*END*/
	/*IF !data.KANSANSHIKI.IsNull */ AND KAN.KANSANSHIKI = /*data.KANSANSHIKI*/0/*END*/
	/*IF !data.KANSANCHI.IsNull*/AND KAN.KANSANCHI = /*data.KANSANCHI.Value*/0/*END*/ 
	/*IF data.KANSAN_BIKOU != null*/AND KAN.KANSAN_BIKOU LIKE '%' +  /*data.KANSAN_BIKOU*/ + '%'/*END*/
	/*IF data.CREATE_USER != null && data.CREATE_USER != ''*/AND KAN.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
	/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, KAN.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
	/*IF data.UPDATE_USER != null && data.UPDATE_USER != ''*/AND KAN.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
	/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, KAN.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
	/*IF !deletechuFlg*/AND KAN.DELETE_FLG = /*deletechuFlg*/0/*END*/
ORDER BY KAN.HINMEI_CD, KAN.UNIT_CD
