UPDATE dbo.M_KANSAN SET
	DENPYOU_KBN_CD = /*data.DENPYOU_KBN_CD*/0,
	HINMEI_CD = /*data.HINMEI_CD*/'',
	UNIT_CD = /*data.UNIT_CD*/0,
	KANSANSHIKI = /*data.KANSANSHIKI*/0,
	KANSANCHI = /*data.KANSANCHI*/0,
	KANSAN_BIKOU = /*data.KANSAN_BIKOU*/'',
	UPDATE_USER = /*data.UPDATE_USER*/'',
	UPDATE_DATE = CONVERT(DATETIME, /*data.UPDATE_DATE*/null, 120),
	UPDATE_PC = /*data.UPDATE_PC*/'',
	DELETE_FLG = /*data.DELETE_FLG*/0
WHERE DENPYOU_KBN_CD = /*updateKey.DENPYOU_KBN_CD*/0
  AND HINMEI_CD = /*updateKey.HINMEI_CD*/''
  AND UNIT_CD = /*updateKey.UNIT_CD*/0
