-- Viewの登録
CREATE VIEW V_CTICONNECT_DATA
AS
SELECT
    SELECT_TYPE,
    TORIHIKISAKI_CD,
    GYOUSHA_CD,
    GENBA_CD,
    NAME,
    NAME_RYAKU,
    FURIGANA,
    TEL,
    KEITAI_TEL,
    REGISTED_TEL,
    REGISTED_KEITAI_TEL,
    FAX,
    POST,
    TODOUFUKEN,
    ADDRESS
FROM
    (SELECT
        1 AS SELECT_TYPE,
        TORIHIKISAKI_CD,
        '' AS GYOUSHA_CD,
        '' AS GENBA_CD,
        ISNULL(TORIHIKISAKI_NAME1, '') + ISNULL(TORIHIKISAKI_NAME2, '') AS NAME,
        ISNULL(TORIHIKISAKI_NAME_RYAKU, '') AS NAME_RYAKU, 
        ISNULL(TORIHIKISAKI_FURIGANA, '') AS FURIGANA,
        ISNULL(REPLACE(REPLACE(REPLACE(TORIHIKISAKI_TEL, '-', ''), ')', ''), '(', ''), '') AS TEL,
        '' AS KEITAI_TEL,
        ISNULL(TORIHIKISAKI_TEL, '') AS REGISTED_TEL,
        '' AS REGISTED_KEITAI_TEL,
        ISNULL(TORIHIKISAKI_FAX, '') AS FAX, 
        ISNULL(TORIHIKISAKI_POST, '') AS POST,
        ISNULL(M_TODOUFUKEN.TODOUFUKEN_NAME, '') AS TODOUFUKEN,
        ISNULL(TORIHIKISAKI_ADDRESS1, '') + ISNULL(TORIHIKISAKI_ADDRESS2, '') AS ADDRESS
    FROM
        dbo.M_TORIHIKISAKI
        LEFT JOIN dbo.M_TODOUFUKEN
            ON M_TORIHIKISAKI.TORIHIKISAKI_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD

    UNION
    SELECT
        2 AS SELECT_TYPE,
        TORIHIKISAKI_CD,
        GYOUSHA_CD,
        '' AS GENBA_CD,
        ISNULL(GYOUSHA_NAME1, '') + ISNULL(GYOUSHA_NAME2, '') AS NAME,
        ISNULL(GYOUSHA_NAME_RYAKU, '') AS NAME_RYAKU,
        ISNULL(GYOUSHA_FURIGANA, '') AS FURIGANA,
        ISNULL(REPLACE(REPLACE(REPLACE(GYOUSHA_TEL, '-', ''), ')', ''), '(', ''), '') AS TEL,
        ISNULL(REPLACE(REPLACE(REPLACE(GYOUSHA_KEITAI_TEL, '-', ''), ')', ''), '(', ''), '') AS KEITAI_TEL,
        ISNULL(GYOUSHA_TEL, '') AS REGISTED_TEL,
        ISNULL(GYOUSHA_KEITAI_TEL, '') AS REGISTED_KEITAI_TEL,
        ISNULL(GYOUSHA_FAX, '') AS FAX,
        ISNULL(GYOUSHA_POST, '') AS POST,
        ISNULL(M_TODOUFUKEN.TODOUFUKEN_NAME, '') AS TODOUFUKEN,
        ISNULL(GYOUSHA_ADDRESS1, '') + ISNULL(GYOUSHA_ADDRESS2, '') AS ADDRESS
    FROM
        dbo.M_GYOUSHA
        LEFT JOIN dbo.M_TODOUFUKEN
            ON M_GYOUSHA.GYOUSHA_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD

    UNION
    SELECT
        3 AS SELECT_TYPE,
        TORIHIKISAKI_CD,
        GYOUSHA_CD,
        GENBA_CD,
        ISNULL(GENBA_NAME1, '') + ISNULL(GENBA_NAME2, '') AS NAME,
        ISNULL(GENBA_NAME_RYAKU, '') AS NAME_RYAKU,
        ISNULL(GENBA_FURIGANA, '') AS FURIGANA,
        ISNULL(REPLACE(REPLACE(REPLACE(GENBA_TEL, '-', ''), ')', ''), '(', ''), '') AS TEL,
        ISNULL(REPLACE(REPLACE(REPLACE(GENBA_KEITAI_TEL, '-', ''), ')', ''), '(', ''), '') AS KEITAI_TEL,
        ISNULL(GENBA_TEL, '') AS REGISTED_TEL,
        ISNULL(GENBA_KEITAI_TEL, '') AS REGISTED_KEITAI_TEL,
        ISNULL(GENBA_FAX, '') AS FAX,
        ISNULL(GENBA_POST, '') AS POST,
        ISNULL(M_TODOUFUKEN.TODOUFUKEN_NAME, '') AS TODOUFUKEN,
        ISNULL(GENBA_ADDRESS1, '') + ISNULL(GENBA_ADDRESS2, '') AS ADDRESS
    FROM
        dbo.M_GENBA
        LEFT JOIN dbo.M_TODOUFUKEN
            ON M_GENBA.GENBA_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD
    ) AS TOTAL_KOKYAKU_LIST