SELECT DISTINCT N'コースマスタ' AS NAME FROM M_COURSE WHERE UNTENSHA_CD IN /*SHAIN_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'車輛マスタ' AS NAME FROM M_SHARYOU WHERE SHAIN_CD IN /*SHAIN_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'取引先マスタ' AS NAME FROM M_TORIHIKISAKI WHERE EIGYOU_TANTOU_CD IN /*SHAIN_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'業者マスタ' AS NAME FROM M_GYOUSHA WHERE EIGYOU_TANTOU_CD IN /*SHAIN_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'現場マスタ' AS NAME FROM M_GENBA WHERE EIGYOU_TANTOU_CD IN /*SHAIN_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'引合取引先マスタ' AS NAME FROM M_HIKIAI_TORIHIKISAKI WHERE EIGYOU_TANTOU_CD IN /*SHAIN_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'引合業者マスタ' AS NAME FROM M_HIKIAI_GYOUSHA WHERE EIGYOU_TANTOU_CD IN /*SHAIN_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'引合現場マスタ' AS NAME FROM M_HIKIAI_GENBA WHERE EIGYOU_TANTOU_CD IN /*SHAIN_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'申請経路マスタ' AS NAME FROM M_DENSHI_SHINSEI_ROUTE WHERE SHAIN_CD IN /*SHAIN_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'クライアントIDマスタ' AS NAME FROM M_DENSHI_KEIYAKU_CLIENT_ID WHERE SHAIN_CD IN /*SHAIN_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'社内経路入力（電子）マスタ' AS NAME FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO WHERE SHAIN_CD IN /*SHAIN_CD*/('') AND DELETE_FLG = 'False'