SELECT TB.* FROM
(SELECT 
0 AS SEIKYUU_NUMBER,
0 AS KAGAMI_NUMBER,
NULL AS GYOUSHA_CD,
NULL AS GENBA_CD,
'開始残高' AS SEIKYUU_DATE,
'1753-01-01 00:00:00.000' AS SORT_SEIKYUU_DATE,
ISNULL(MTS.KAISHI_URIKAKE_ZANDAKA,0) AS SEIKYUU_KINGAKU,
TNK.KESHIKOMI_GAKU_TOTAL AS KESHIKOMIGAKU_TOTAL,
ISNULL(KAISHI_URIKAKE_ZANDAKA,0) - ISNULL(TNK.KESHIKOMI_GAKU_TOTAL,0) AS MIKESHIKOMI_KINGAKU

FROM M_TORIHIKISAKI_SEIKYUU MTS
LEFT JOIN (SELECT
              T_NYUUKIN_KESHIKOMI.SEIKYUU_NUMBER,
			  T_NYUUKIN_KESHIKOMI.KAGAMI_NUMBER,
			  T_NYUUKIN_KESHIKOMI.TORIHIKISAKI_CD,
			  SUM(T_NYUUKIN_KESHIKOMI.KESHIKOMI_GAKU) AS KESHIKOMI_GAKU_TOTAL
			FROM T_NYUUKIN_KESHIKOMI T_NYUUKIN_KESHIKOMI
			WHERE T_NYUUKIN_KESHIKOMI.DELETE_FLG = 0
			AND T_NYUUKIN_KESHIKOMI.SEIKYUU_NUMBER = 0
			AND T_NYUUKIN_KESHIKOMI.KAGAMI_NUMBER = 0
			GROUP BY T_NYUUKIN_KESHIKOMI.SEIKYUU_NUMBER,
			         T_NYUUKIN_KESHIKOMI.KAGAMI_NUMBER,
			         T_NYUUKIN_KESHIKOMI.TORIHIKISAKI_CD
					 ) TNK
ON MTS.TORIHIKISAKI_CD = TNK.TORIHIKISAKI_CD
WHERE MTS.TORIHIKISAKI_CD = /*torihikisakiCd*/''

UNION ALL

SELECT 
TSDK.SEIKYUU_NUMBER AS SEIKYUU_NUMBER,
TSDK.KAGAMI_NUMBER AS KAGAMI_NUMBER,
TSDK.GYOUSHA_CD AS GYOUSHA_CD,
TSDK.GENBA_CD AS GENBA_CD,
convert(nvarchar(10),TSD.SEIKYUU_DATE,111) AS SEIKYUU_DATE,
TSD.SEIKYUU_DATE AS SORT_SEIKYUU_DATE,
ISNULL(TSDK.KONKAI_URIAGE_GAKU,0)+
ISNULL(TSDK.KONKAI_SEI_UTIZEI_GAKU,0)+
ISNULL(TSDK.KONKAI_SEI_SOTOZEI_GAKU,0)+
ISNULL(TSDK.KONKAI_DEN_UTIZEI_GAKU,0)+
ISNULL(TSDK.KONKAI_DEN_SOTOZEI_GAKU,0)+
ISNULL(TSDK.KONKAI_MEI_UTIZEI_GAKU,0)+
ISNULL(TSDK.KONKAI_MEI_SOTOZEI_GAKU,0) AS SEIKYUU_KINGAKU,
TNK.KESHIKOMI_GAKU_TOTAL AS KESHIKOMIGAKU_TOTAL,
ISNULL(TSDK.KONKAI_URIAGE_GAKU,0)+
ISNULL(TSDK.KONKAI_SEI_UTIZEI_GAKU,0)+
ISNULL(TSDK.KONKAI_SEI_SOTOZEI_GAKU,0)+
ISNULL(TSDK.KONKAI_DEN_UTIZEI_GAKU,0)+
ISNULL(TSDK.KONKAI_DEN_SOTOZEI_GAKU,0)+
ISNULL(TSDK.KONKAI_MEI_UTIZEI_GAKU,0)+
ISNULL(TSDK.KONKAI_MEI_SOTOZEI_GAKU,0)-
ISNULL(TNK.KESHIKOMI_GAKU_TOTAL,0) AS MIKESHIKOMI_KINGAKU

FROM T_SEIKYUU_DENPYOU TSD
INNER JOIN T_SEIKYUU_DENPYOU_KAGAMI TSDK
ON TSD.SEIKYUU_NUMBER = TSDK.SEIKYUU_NUMBER
AND TSDK.DELETE_FLG = 0
LEFT JOIN (SELECT
              T_NYUUKIN_KESHIKOMI.SEIKYUU_NUMBER,
			  T_NYUUKIN_KESHIKOMI.KAGAMI_NUMBER,
			  SUM(T_NYUUKIN_KESHIKOMI.KESHIKOMI_GAKU) AS KESHIKOMI_GAKU_TOTAL
			FROM T_NYUUKIN_KESHIKOMI T_NYUUKIN_KESHIKOMI
			WHERE T_NYUUKIN_KESHIKOMI.DELETE_FLG = 0
			GROUP BY T_NYUUKIN_KESHIKOMI.SEIKYUU_NUMBER,
			         T_NYUUKIN_KESHIKOMI.KAGAMI_NUMBER
		   ) TNK
	   ON TNK.SEIKYUU_NUMBER = TSDK.SEIKYUU_NUMBER
	  AND TNK.KAGAMI_NUMBER = TSDK.KAGAMI_NUMBER
WHERE TSD.TORIHIKISAKI_CD = /*torihikisakiCd*/''
AND TSD.SEIKYUU_DATE <=  /*denpyouDate*/'2016/01/01'
AND TSD.DELETE_FLG = 0
) TB WHERE  TB.MIKESHIKOMI_KINGAKU > 0
ORDER BY TB.SORT_SEIKYUU_DATE,TB.SEIKYUU_NUMBER,TB.GYOUSHA_CD,TB.GENBA_CD