SELECT TORIHIKISAKI.TORIHIKISAKI_CD,
TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU,
NYUUKINSAKI.NYUUKINSAKI_CD,
NYUUKINSAKI.NYUUKINSAKI_NAME_RYAKU
 FROM dbo.M_TORIHIKISAKI TORIHIKISAKI
LEFT JOIN M_TORIHIKISAKI_SEIKYUU TORIHIKISAKI_SEIKYUU ON TORIHIKISAKI.TORIHIKISAKI_CD = TORIHIKISAKI_SEIKYUU.TORIHIKISAKI_CD
LEFT JOIN M_NYUUKINSAKI NYUUKINSAKI  ON TORIHIKISAKI_SEIKYUU.NYUUKINSAKI_CD = NYUUKINSAKI.NYUUKINSAKI_CD
WHERE 
CONVERT(DATE, ISNULL(TORIHIKISAKI.TEKIYOU_BEGIN, DATEADD(day,-1,GETDATE()))) <= CONVERT(DATE, GETDATE()) 
AND CONVERT(DATE, GETDATE()) <= CONVERT(DATE, ISNULL(TORIHIKISAKI.TEKIYOU_END, DATEADD(day,1,GETDATE())))
AND TORIHIKISAKI.DELETE_FLG = 0
AND TORIHIKISAKI_SEIKYUU.TORIHIKI_KBN_CD = 2
/*IF torihikisakiCd != null && torihikisakiCd != ''*/
AND TORIHIKISAKI.TORIHIKISAKI_CD = /*torihikisakiCd*/ 
/*END*/
/*IF furikomiName != null && furikomiName != '' */
AND (TORIHIKISAKI_SEIKYUU.FURIKOMI_NAME1 = /*furikomiName*/''
OR TORIHIKISAKI_SEIKYUU.FURIKOMI_NAME2 = /*furikomiName*/'')
/*END*/
ORDER BY TORIHIKISAKI.TORIHIKISAKI_CD
