using System.Data.SqlTypes;

namespace r_framework.Entity
{
    public class T_HAISHA_WARIATE_DAY : SuperEntity
    {
        public SqlDateTime SAGYOU_DATE { get; set; }
        public string SEARCH_SAGYOU_DATE { get; set; }
        public string GYOUSHA_CD { get; set; }
        public string SHARYOU_CD { get; set; }
        public string UNTENSHA_CD { get; set; }
        public SqlInt32 SEQ { get; set; }
        public SqlInt16 SHUBETSU_KBN_01 { get; set; }
        public SqlInt64 SYSTEM_ID_01 { get; set; }
        public SqlInt64 DENPYOU_NUM_01 { get; set; }
        public SqlInt16 SHUBETSU_KBN_02 { get; set; }
        public SqlInt64 SYSTEM_ID_02 { get; set; }
        public SqlInt64 DENPYOU_NUM_02 { get; set; }
        public SqlInt16 SHUBETSU_KBN_03 { get; set; }
        public SqlInt64 SYSTEM_ID_03 { get; set; }
        public SqlInt64 DENPYOU_NUM_03 { get; set; }
        public SqlInt16 SHUBETSU_KBN_04 { get; set; }
        public SqlInt64 SYSTEM_ID_04 { get; set; }
        public SqlInt64 DENPYOU_NUM_04 { get; set; }
        public SqlInt16 SHUBETSU_KBN_05 { get; set; }
        public SqlInt64 SYSTEM_ID_05 { get; set; }
        public SqlInt64 DENPYOU_NUM_05 { get; set; }
        public SqlInt16 SHUBETSU_KBN_06 { get; set; }
        public SqlInt64 SYSTEM_ID_06 { get; set; }
        public SqlInt64 DENPYOU_NUM_06 { get; set; }
        public SqlInt16 SHUBETSU_KBN_07 { get; set; }
        public SqlInt64 SYSTEM_ID_07 { get; set; }
        public SqlInt64 DENPYOU_NUM_07 { get; set; }
        public SqlInt16 SHUBETSU_KBN_08 { get; set; }
        public SqlInt64 SYSTEM_ID_08 { get; set; }
        public SqlInt64 DENPYOU_NUM_08 { get; set; }
        public SqlInt16 SHUBETSU_KBN_09 { get; set; }
        public SqlInt64 SYSTEM_ID_09 { get; set; }
        public SqlInt64 DENPYOU_NUM_09 { get; set; }
        public SqlInt16 SHUBETSU_KBN_10 { get; set; }
        public SqlInt64 SYSTEM_ID_10 { get; set; }
        public SqlInt64 DENPYOU_NUM_10 { get; set; }
        public SqlInt16 SHUBETSU_KBN_11 { get; set; }
        public SqlInt64 SYSTEM_ID_11 { get; set; }
        public SqlInt64 DENPYOU_NUM_11 { get; set; }
        public SqlInt16 SHUBETSU_KBN_12 { get; set; }
        public SqlInt64 SYSTEM_ID_12 { get; set; }
        public SqlInt64 DENPYOU_NUM_12 { get; set; }
        public SqlInt16 SHUBETSU_KBN_13 { get; set; }
        public SqlInt64 SYSTEM_ID_13 { get; set; }
        public SqlInt64 DENPYOU_NUM_13 { get; set; }
        public SqlInt16 SHUBETSU_KBN_14 { get; set; }
        public SqlInt64 SYSTEM_ID_14 { get; set; }
        public SqlInt64 DENPYOU_NUM_14 { get; set; }
        public SqlInt16 SHUBETSU_KBN_15 { get; set; }
        public SqlInt64 SYSTEM_ID_15 { get; set; }
        public SqlInt64 DENPYOU_NUM_15 { get; set; }
        public SqlInt16 SHUBETSU_KBN_16 { get; set; }
        public SqlInt64 SYSTEM_ID_16 { get; set; }
        public SqlInt64 DENPYOU_NUM_16 { get; set; }
        public SqlInt16 SHUBETSU_KBN_17 { get; set; }
        public SqlInt64 SYSTEM_ID_17 { get; set; }
        public SqlInt64 DENPYOU_NUM_17 { get; set; }
        public SqlInt16 SHUBETSU_KBN_18 { get; set; }
        public SqlInt64 SYSTEM_ID_18 { get; set; }
        public SqlInt64 DENPYOU_NUM_18 { get; set; }
        public SqlInt16 SHUBETSU_KBN_19 { get; set; }
        public SqlInt64 SYSTEM_ID_19 { get; set; }
        public SqlInt64 DENPYOU_NUM_19 { get; set; }
        public SqlInt16 SHUBETSU_KBN_20 { get; set; }
        public SqlInt64 SYSTEM_ID_20 { get; set; }
        public SqlInt64 DENPYOU_NUM_20 { get; set; }
        public SqlInt16 SHUBETSU_KBN_21 { get; set; }
        public SqlInt64 SYSTEM_ID_21 { get; set; }
        public SqlInt64 DENPYOU_NUM_21 { get; set; }
        public SqlInt16 SHUBETSU_KBN_22 { get; set; }
        public SqlInt64 SYSTEM_ID_22 { get; set; }
        public SqlInt64 DENPYOU_NUM_22 { get; set; }
        public SqlInt16 SHUBETSU_KBN_23 { get; set; }
        public SqlInt64 SYSTEM_ID_23 { get; set; }
        public SqlInt64 DENPYOU_NUM_23 { get; set; }
        public SqlInt16 SHUBETSU_KBN_24 { get; set; }
        public SqlInt64 SYSTEM_ID_24 { get; set; }
        public SqlInt64 DENPYOU_NUM_24 { get; set; }
        public SqlInt16 SHUBETSU_KBN_25 { get; set; }
        public SqlInt64 SYSTEM_ID_25 { get; set; }
        public SqlInt64 DENPYOU_NUM_25 { get; set; }
        public SqlInt16 SHUBETSU_KBN_26 { get; set; }
        public SqlInt64 SYSTEM_ID_26 { get; set; }
        public SqlInt64 DENPYOU_NUM_26 { get; set; }
        public SqlInt16 SHUBETSU_KBN_27 { get; set; }
        public SqlInt64 SYSTEM_ID_27 { get; set; }
        public SqlInt64 DENPYOU_NUM_27 { get; set; }
        public SqlInt16 SHUBETSU_KBN_28 { get; set; }
        public SqlInt64 SYSTEM_ID_28 { get; set; }
        public SqlInt64 DENPYOU_NUM_28 { get; set; }
        public SqlInt16 SHUBETSU_KBN_29 { get; set; }
        public SqlInt64 SYSTEM_ID_29 { get; set; }
        public SqlInt64 DENPYOU_NUM_29 { get; set; }
        public SqlInt16 SHUBETSU_KBN_30 { get; set; }
        public SqlInt64 SYSTEM_ID_30 { get; set; }
        public SqlInt64 DENPYOU_NUM_30 { get; set; }
        public SqlBoolean DELETE_FLG { get; set; }
        //Start Sontt
        public SqlInt32 ROW_NUM { get; set; }
        public SqlBoolean KARADENPYOU_FLG_01 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_02 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_03 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_04 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_05 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_06 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_07 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_08 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_09 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_10 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_11 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_12 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_13 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_14 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_15 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_16 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_17 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_18 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_19 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_20 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_21 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_22 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_23 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_24 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_25 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_26 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_27 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_28 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_29 { get; set; }
        public SqlBoolean KARADENPYOU_FLG_30 { get; set; }
        public string SHASHU_CD { get; set; }

        //End Sontt
    }
}