using System.Data.SqlTypes;

namespace r_framework.Entity
{
    public class T_MOBILE_SYOGUN_DATA_INSERT : SuperEntity
    {
        public SqlInt64 SEQ_NO { get; set; }
        public SqlInt64 EDABAN { get; set; }
        public SqlInt64 NODE_EDABAN { get; set; }
        public SqlInt16 KYOTEN_CD { get; set; }
        public string SHASHU_CD { get; set; }
        public string SHASHU_NAME { get; set; }
        public string SHARYOU_CD { get; set; }
        public string SHARYOU_NAME { get; set; }
        public string UNTENSHA_NAME { get; set; }
        public SqlDateTime HAISHA_SAGYOU_DATE { get; set; }
        public string SEARCH_HAISHA_SAGYOU_DATE { get; set; }
        public SqlInt32 HAISHA_DENPYOU_NO { get; set; }
        public string HAISHA_UNTENSHA_CD { get; set; }
        public string HAISHA_COURSE_NAME_CD { get; set; }
        public SqlInt32 HAISHA_KBN { get; set; }
        public SqlDateTime HAISHA_TORIKOMI_DATE { get; set; }
        public string SEARCH_HAISHA_TORIKOMI_DATE { get; set; }
        public string HAISHA_TORIKOMI_FILENAME { get; set; }
        public SqlBoolean HAISHA_CONTENA_FLG { get; set; }
        public SqlInt32 SHUKKO_NO { get; set; }
        public SqlDateTime SHUKKO_CREATEDATE { get; set; }
        public string SEARCH_SHUKKO_CREATEDATE { get; set; }
        public SqlDateTime SHUKKO_UPDATEDATE { get; set; }
        public string SEARCH_SHUKKO_UPDATEDATE { get; set; }
        public SqlInt32 SHUKKO_UPDATECNT { get; set; }
        public SqlDateTime SHUKKO_SHUKKODATE { get; set; }
        public string SEARCH_SHUKKO_SHUKKODATE { get; set; }
        public string SHUKKO_GYOUSHACD { get; set; }
        public string SHUKKO_SHARYOUCD { get; set; }
        public string SHUKKO_TENKI { get; set; }
        public SqlDecimal SHUKKO_METER { get; set; }
        public SqlInt32 KIKO_NO { get; set; }
        public SqlDateTime KIKO_CREATEDATE { get; set; }
        public string SEARCH_KIKO_CREATEDATE { get; set; }
        public SqlDateTime KIKO_UPDATEDATE { get; set; }
        public string SEARCH_KIKO_UPDATEDATE { get; set; }
        public SqlInt32 KIKO_UPDATECNT { get; set; }
        public SqlDateTime KIKO_KIKODATE { get; set; }
        public string SEARCH_KIKO_KIKODATE { get; set; }
        public SqlDecimal KIKO_METER { get; set; }
        public SqlDateTime GENBA_JISSEKI_CREATEDATE { get; set; }
        public string SEARCH_GENBA_JISSEKI_CREATEDATE { get; set; }
        public SqlDateTime GENBA_JISSEKI_UPDATEDATE { get; set; }
        public string SEARCH_GENBA_JISSEKI_UPDATEDATE { get; set; }
        public SqlInt32 GENBA_JISSEKI_UPDATECNT { get; set; }
        public SqlDateTime GENBA_JISSEKI_SHUUSHUUTIME { get; set; }
        public string SEARCH_GENBA_JISSEKI_SHUUSHUUTIME { get; set; }
        public SqlInt32 GENBA_JISSEKI_NO { get; set; }
        public string GENBA_JISSEKI_GYOUSHACD { get; set; }
        public string GENBA_JISSEKI_GENBACD { get; set; }
        public SqlBoolean GENBA_JISSEKI_ADDGENBAFLG { get; set; }
        public SqlInt32 GENBA_JISSEKI_SHUKKONO { get; set; }
        public SqlBoolean GENBA_JISSEKI_JYOGAIFLG { get; set; }
        public SqlDateTime GENBA_DETAIL_CREATEDATE { get; set; }
        public string SEARCH_GENBA_DETAIL_CREATEDATE { get; set; }
        public SqlDateTime GENBA_DETAIL_UPDATEDATE { get; set; }
        public string SEARCH_GENBA_DETAIL_UPDATEDATE { get; set; }
        public SqlInt32 GENBA_DETAIL_UPDATECNT { get; set; }
        public SqlInt32 GENBA_DETAIL_NO { get; set; }
        public string GENBA_DETAIL_HINMEICD { get; set; }
        public SqlDecimal GENBA_DETAIL_SUURYO1 { get; set; }
        public SqlInt16 GENBA_DETAIL_UNIT_CD1 { get; set; }
        public SqlDecimal GENBA_DETAIL_SUURYO2 { get; set; }
        public SqlInt16 GENBA_DETAIL_UNIT_CD2 { get; set; }
        public SqlBoolean GENBA_DETAIL_ADDHINMEIFLG { get; set; }
        public SqlInt16 GENBA_DETAIL_MANIKBN { get; set; }
        public SqlInt64 GENBA_DETAIL_MANINO { get; set; }
        public SqlInt32 GENBA_DETAIL_HANNYUUNO { get; set; }
        public SqlInt32 GENBA_DETAIL_GENBA_NO { get; set; }
        public SqlInt32 HANNYUU_NO { get; set; }
        public SqlDateTime HANNYUU_CREATEDATE { get; set; }
        public string SEARCH_HANNYUU_CREATEDATE { get; set; }
        public SqlDateTime HANNYUU_UPDATEDATE { get; set; }
        public string SEARCH_HANNYUU_UPDATEDATE { get; set; }
        public SqlInt32 HANNYUU_UPDATECNT { get; set; }
        public SqlDateTime HANNYUU_HANNYUUDATE { get; set; }
        public string SEARCH_HANNYUU_HANNYUUDATE { get; set; }
        public string HANNYUU_GYOUSHACD { get; set; }
        public string HANNYUU_GENBACD { get; set; }
        public SqlDecimal HANNYUU_RYO { get; set; }
        public string CONTENA_NO { get; set; }
        public SqlDateTime CONTENA_CREATEDATE { get; set; }
        public string SEARCH_CONTENA_CREATEDATE { get; set; }
        public SqlDateTime CONTENA_UPDATEDATE { get; set; }
        public string SEARCH_CONTENA_UPDATEDATE { get; set; }
        public SqlInt32 CONTENA_UPDATECNT { get; set; }
        public SqlInt32 CONTENA_GENBA_NO { get; set; }
        public SqlDateTime CONTENA_IDOUDATE { get; set; }
        public string SEARCH_CONTENA_IDOUDATE { get; set; }
        public SqlInt16 CONTENA_KYOTEN_CD { get; set; }
        public SqlInt32 CONTENA_IDOU_KBN { get; set; }
        public string CONTENA_SHURUI_CD { get; set; }
        public string CONTENA_CD { get; set; }
        public SqlBoolean JISSEKI_REGIST_FLG { get; set; }
        public SqlBoolean DELETE_FLG { get; set; }
    }
}