SELECT 
	TSD.SEIKYUU_NUMBER
	,ISNULL(TSD_INXS.UPLOAD_STATUS,1) AS UPLOAD_STATUS
	,ISNULL(TSD_INXS.DOWNLOAD_STATUS,1) AS DOWNLOAD_STATUS
	,TSD.TIME_STAMP
FROM T_SEIKYUU_DENPYOU TSD
	LEFT JOIN T_SEIKYUU_DENPYOU_INXS TSD_INXS
            ON TSD_INXS.SEIKYUU_NUMBER = TSD.SEIKYUU_NUMBER
WHERE 
	TSD.SEIKYUU_NUMBER IN /*SeikyuuNumbers*/()
	AND TSD.DELETE_FLG = 0