SELECT 
	CONVERT(nvarchar, M_GENBA.CREATE_DATE, 111)
	, M_GENBA.GYOUSHA_CD
	, M_GYOUSHA.GYOUSHA_NAME_RYAKU
	, M_GENBA.GENBA_CD 
	, M_GENBA.GENBA_NAME_RYAKU 
	, M_GENBA.GENBA_FURIGANA 
	, M_GENBA.GENBA_ADDRESS1 
	, M_GENBA.GENBA_TEL 
	, M_SHAIN.SHAIN_NAME_RYAKU
FROM
	M_GENBA 
	INNER JOIN M_GYOUSHA
		ON M_GENBA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD 
		AND M_GYOUSHA.DELETE_FLG = 0
	LEFT JOIN M_SHAIN
		ON M_GENBA.EIGYOU_TANTOU_CD = M_SHAIN.SHAIN_CD
		AND M_SHAIN.DELETE_FLG = 0
WHERE
	M_GENBA.DELETE_FLG = 0
	/*IF data.gyoushaCd != null && data.gyoushaCd != ''*/
		AND M_GENBA.GYOUSHA_CD = /*data.gyoushaCd*/
	/*END*/
	/*IF data.eigyouTantoushaCd != null && data.eigyouTantoushaCd != ''*/
		AND M_GENBA.EIGYOU_TANTOU_CD = /*data.eigyouTantoushaCd*/
	/*END*/