SELECT
	CONVERT(nvarchar, M_HIKIAI_GENBA.CREATE_DATE, 111)
	, M_HIKIAI_GENBA.GYOUSHA_CD
	, M_GYOUSHA.GYOUSHA_NAME_RYAKU
	, M_HIKIAI_GENBA.GENBA_CD
	, M_HIKIAI_GENBA.GENBA_NAME_RYAKU
	, M_HIKIAI_GENBA.GENBA_FURIGANA
	, M_HIKIAI_GENBA.GENBA_ADDRESS1
	, M_HIKIAI_GENBA.GENBA_TEL
	, M_SHAIN.SHAIN_NAME_RYAKU
	, CASE  WHEN ISNULL(TDSE_1.SYSTEM_ID, '') = '' AND ISNULL(TDSE_2.SYSTEM_ID, '') = '' THEN ''
	  ELSE '申請中' END AS SHINSEI_JOUKYOU
FROM 
	M_HIKIAI_GENBA 
	INNER JOIN (
		SELECT
			MGY.*
			,HGY.GYOUSHA_CD AS GYOUSHA_CD_BEFORE
		FROM
			M_GYOUSHA MGY
			LEFT JOIN M_HIKIAI_GYOUSHA HGY
				ON MGY.GYOUSHA_CD = HGY.GYOUSHA_CD_AFTER
	) M_GYOUSHA
		ON M_HIKIAI_GENBA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD AND M_GYOUSHA.DELETE_FLG = 0
	LEFT JOIN M_SHAIN
		ON M_HIKIAI_GENBA.EIGYOU_TANTOU_CD = M_SHAIN.SHAIN_CD
		AND M_SHAIN.DELETE_FLG = 0

	--元から既存業者だった業者CDを使用した引合現場申請データ検索
	LEFT JOIN (
		SELECT
			DS.SYSTEM_ID
			,DS.GYOUSHA_CD
			,DS.HIKIAI_GENBA_CD
		FROM
			T_DENSHI_SHINSEI_ENTRY DS
			INNER JOIN T_DENSHI_SHINSEI_STATUS SS
				ON DS.SYSTEM_ID = SS.SYSTEM_ID
				AND DS.SEQ = SS.SEQ
				AND SS.DELETE_FLG = 0
		WHERE
			DS.DELETE_FLG = 0
			AND DS.SHINSEI_MASTER_KBN = 7
			AND (SS.SHINSEI_STATUS_CD = 1 OR SS.SHINSEI_STATUS_CD = 2 OR SS.SHINSEI_STATUS_CD = 5)
	) TDSE_1
		ON 	TDSE_1.GYOUSHA_CD = M_HIKIAI_GENBA.GYOUSHA_CD
		AND TDSE_1.HIKIAI_GENBA_CD = M_HIKIAI_GENBA.GENBA_CD

	--引合業者から本登録されて既存業者に変わった引合業者CDを使用した引合現場申請データ検索
	LEFT JOIN (
		SELECT
			DS.SYSTEM_ID
			,DS.HIKIAI_GYOUSHA_CD
			,DS.HIKIAI_GENBA_CD
		FROM
			T_DENSHI_SHINSEI_ENTRY DS
			INNER JOIN T_DENSHI_SHINSEI_STATUS SS
				ON DS.SYSTEM_ID = SS.SYSTEM_ID
				AND DS.SEQ = SS.SEQ
				AND SS.DELETE_FLG = 0
		WHERE
			DS.DELETE_FLG = 0
			AND DS.SHINSEI_MASTER_KBN = 6
			AND (SS.SHINSEI_STATUS_CD = 1 OR SS.SHINSEI_STATUS_CD = 2 OR SS.SHINSEI_STATUS_CD = 5)
	) TDSE_2
		ON TDSE_2.HIKIAI_GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD_BEFORE
		AND TDSE_2.HIKIAI_GENBA_CD = M_HIKIAI_GENBA.GENBA_CD
WHERE
	M_HIKIAI_GENBA.DELETE_FLG = 0 AND ISNULL(M_HIKIAI_GENBA.HIKIAI_GYOUSHA_USE_FLG, 0) = 0
	/*IF data.gyoushaCd != null && data.gyoushaCd != ''*/
		AND M_HIKIAI_GENBA.GYOUSHA_CD = /*data.gyoushaCd*/
	/*END*/
	/*IF data.eigyouTantoushaCd != null && data.eigyouTantoushaCd != ''*/
		AND M_HIKIAI_GENBA.EIGYOU_TANTOU_CD = /*data.eigyouTantoushaCd*/
	/*END*/