SELECT
	CONVERT(nvarchar, M_HIKIAI_GENBA.CREATE_DATE, 111)
	, M_HIKIAI_GENBA.GYOUSHA_CD
	, M_HIKIAI_GYOUSHA.GYOUSHA_NAME_RYAKU
	, M_HIKIAI_GENBA.GENBA_CD
	, M_HIKIAI_GENBA.GENBA_NAME_RYAKU
	, M_HIKIAI_GENBA.GENBA_FURIGANA
	, M_HIKIAI_GENBA.GENBA_ADDRESS1
	, M_HIKIAI_GENBA.GENBA_TEL
	, M_SHAIN.SHAIN_NAME_RYAKU
	, CASE ISNULL(TDSE.HIKIAI_GENBA_CD,'') WHEN '' THEN '' ELSE '申請中' END AS SHINSEI_JOUKYOU
FROM 
	M_HIKIAI_GENBA
	INNER JOIN M_HIKIAI_GYOUSHA
		ON M_HIKIAI_GENBA.GYOUSHA_CD = M_HIKIAI_GYOUSHA.GYOUSHA_CD
		AND M_HIKIAI_GYOUSHA.DELETE_FLG = 0 
	LEFT JOIN M_SHAIN
		ON M_HIKIAI_GENBA.EIGYOU_TANTOU_CD = M_SHAIN.SHAIN_CD
		AND M_SHAIN.DELETE_FLG = 0
	LEFT JOIN (
		 SELECT
			DS.HIKIAI_GYOUSHA_CD
			,DS.HIKIAI_GENBA_CD
		FROM
			T_DENSHI_SHINSEI_ENTRY DS
			INNER JOIN T_DENSHI_SHINSEI_STATUS SS
				ON DS.SYSTEM_ID = SS.SYSTEM_ID
				AND DS.SEQ = SS.SEQ
				AND SS.DELETE_FLG = 0
		WHERE
			DS.DELETE_FLG = 0
			AND DS.SHINSEI_MASTER_KBN = 6
			AND (SS.SHINSEI_STATUS_CD = 1 OR SS.SHINSEI_STATUS_CD = 2 OR SS.SHINSEI_STATUS_CD = 5)
	) TDSE
		ON TDSE.HIKIAI_GYOUSHA_CD = M_HIKIAI_GENBA.GYOUSHA_CD
		AND TDSE.HIKIAI_GENBA_CD = M_HIKIAI_GENBA.GENBA_CD
WHERE
	M_HIKIAI_GENBA.DELETE_FLG = 0 AND M_HIKIAI_GENBA.HIKIAI_GYOUSHA_USE_FLG = 1
	/*IF data.gyoushaCd != null && data.gyoushaCd != ''*/
		AND M_HIKIAI_GENBA.GYOUSHA_CD = /*data.gyoushaCd*/
	/*END*/
	/*IF data.eigyouTantoushaCd != null && data.eigyouTantoushaCd != ''*/
		AND M_HIKIAI_GENBA.EIGYOU_TANTOU_CD = /*data.eigyouTantoushaCd*/
	/*END*/