SELECT 
	CONVERT(nvarchar, M_TORIHIKISAKI.CREATE_DATE, 111),
	M_TORIHIKISAKI.TORIHIKISAKI_CD, 
	M_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU, 
	M_TORIHIKISAKI.TORIHIKISAKI_FURIGANA, 
	M_TORIHIKISAKI.TORIHIKISAKI_ADDRESS1, 
	M_TORIHIKISAKI.TORIHIKISAKI_TEL,
	M_SHAIN.SHAIN_NAME
FROM
	M_TORIHIKISAKI 
	LEFT JOIN M_SHAIN
		ON M_TORIHIKISAKI.EIGYOU_TANTOU_CD = M_SHAIN.SHAIN_CD
		AND M_SHAIN.DELETE_FLG = 0
WHERE
	M_TORIHIKISAKI.DELETE_FLG = 0
	/*IF data.eigyouTantoushaCd != null && data.eigyouTantoushaCd != ''*/
		AND M_TORIHIKISAKI.EIGYOU_TANTOU_CD = /*data.eigyouTantoushaCd*/
	/*END*/