SELECT
	M_DENSHI_JIGYOUJOU.*,
	M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS1 + M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS2 + M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS3 + M_DENSHI_JIGYOUJOU.JIGYOUJOU_ADDRESS4 AS JIGYOUJOU_ADDRESS,
	M_DENSHI_JIGYOUSHA.JIGYOUSHA_NAME
  FROM M_DENSHI_JIGYOUJOU
	INNER JOIN M_DENSHI_JIGYOUSHA ON M_DENSHI_JIGYOUJOU.EDI_MEMBER_ID = M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID
 WHERE M_DENSHI_JIGYOUJOU.GYOUSHA_CD IS NULL OR M_DENSHI_JIGYOUJOU.GYOUSHA_CD = ''
    OR M_DENSHI_JIGYOUJOU.GENBA_CD IS NULL OR M_DENSHI_JIGYOUJOU.GENBA_CD = ''