SELECT
MCJ.DELETE_FLG,
MCJ.CONTENA_JOUKYOU_CD,
MCJ.CONTENA_JOUKYOU_NAME,
MCJ.CONTENA_JOUKYOU_NAME_RYAKU,
MCJ.CONTENA_JOUKYOU_BIKOU,
MCJ.UPDATE_USER,
MCJ.UPDATE_DATE,
MCJ.UPDATE_PC,
MCJ.CREATE_USER,
MCJ.CREATE_DATE,
MCJ.CREATE_PC,
MCJ.TIME_STAMP

FROM 
dbo.M_CONTENA_JOUKYOU MCJ
/*BEGIN*/WHERE
/*IF !data.CONTENA_JOUKYOU_CD.IsNull*/AND MCJ.CONTENA_JOUKYOU_CD = /*data.CONTENA_JOUKYOU_CD*/ /*END*/
/*IF data.CONTENA_JOUKYOU_NAME != null*/AND MCJ.CONTENA_JOUKYOU_NAME LIKE '%' +  /*data.CONTENA_JOUKYOU_NAME*/ + '%'/*END*/
/*IF data.CONTENA_JOUKYOU_NAME_RYAKU != null*/AND MCJ.CONTENA_JOUKYOU_NAME_RYAKU LIKE '%' +  /*data.CONTENA_JOUKYOU_NAME_RYAKU*/ + '%'/*END*/
/*IF data.CONTENA_JOUKYOU_BIKOU != null*/AND MCJ.CONTENA_JOUKYOU_BIKOU LIKE '%' +  /*data.CONTENA_JOUKYOU_BIKOU*/ + '%'/*END*/
/*IF data.CREATE_USER != null*/AND MCJ.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, MCJ.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
/*IF data.UPDATE_USER != null*/AND MCJ.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, MCJ.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*IF !deletechuFlg*/AND MCJ.DELETE_FLG = /*deletechuFlg*/0/*END*/
/*END*/
ORDER BY MCJ.CONTENA_JOUKYOU_CD
