SELECT 
	TOKBN.*,
	ISNULL(TOKBN.TORIHIKI_KBN_NAME, N'') AS TORIHIKI_KBN_NAME
FROM 
    dbo.M_TORIHIKI_KBN TOKBN
/*BEGIN*/WHERE
	/*IF data.TORIHIKI_KBN_BIKOU != null*/ TOKBN.TORIHIKI_KBN_BIKOU LIKE '%' + /*data.TORIHIKI_KBN_BIKOU*/ + '%'/*END*/
	/*IF !data.TORIHIKI_KBN_CD.IsNull*/ AND CAST (TOKBN.TORIHIKI_KBN_CD AS VARCHAR(5)) LIKE '%' + CAST(/*data.TORIHIKI_KBN_CD*/0 AS VARCHAR(5)) + '%'/*END*/
	/*IF data.TORIHIKI_KBN_NAME != null*/ AND TOKBN.TORIHIKI_KBN_NAME LIKE '%' + /*data.TORIHIKI_KBN_NAME*/ + '%'/*END*/
	/*IF data.TORIHIKI_KBN_NAME_RYAKU != null*/ AND TOKBN.TORIHIKI_KBN_NAME_RYAKU LIKE '%' + /*data.TORIHIKI_KBN_NAME_RYAKU*/ + '%'/*END*/
	/*IF data.UPDATE_USER != null*/AND TOKBN.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
	/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, TOKBN.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
	/*IF data.CREATE_USER != null*/AND TOKBN.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
	/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, TOKBN.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
	/*IF !deletechuFlg*/AND TOKBN.DELETE_FLG = 0/*END*/
/*END*/
ORDER BY
	TOKBN.TORIHIKI_KBN_CD
