SELECT 
    TOKBN.*
    ,ISNULL(TOKBN.TORIHIKI_KBN_NAME,N'')AS TORIHIKI_KBN_NAME
FROM 
    dbo.M_TORIHIKI_KBN TOKBN
/*BEGIN*/WHERE
	/*IF data.TORIHIKI_KBN_BIKOU != null*/ TOKBN.TORIHIKI_KBN_BIKOU LIKE '%' + /*data.TORIHIKI_KBN_BIKOU*/ + '%'/*END*/
	/*IF !data.TORIHIKI_KBN_CD.IsNull*/ AND CAST (TOKBN.TORIHIKI_KBN_CD AS VARCHAR(5)) LIKE '%' + CAST(/*data.TORIHIKI_KBN_CD*/0 AS VARCHAR(5)) + '%'/*END*/
	/*IF data.TORIHIKI_KBN_NAME != null*/ AND TOKBN.TORIHIKI_KBN_NAME LIKE '%' + /*data.TORIHIKI_KBN_NAME*/ + '%'/*END*/
	/*IF data.TORIHIKI_KBN_NAME_RYAKU != null*/ AND TOKBN.TORIHIKI_KBN_NAME_RYAKU LIKE '%' + /*data.TORIHIKI_KBN_NAME_RYAKU*/ + '%'/*END*/
	/*IF !deletechuFlg*/AND TOKBN.DELETE_FLG = 0/*END*/
/*END*/
ORDER BY
    TOKBN.TORIHIKI_KBN_CD