SELECT
    MCS.CONTENA_SHURUI_CD,
    MCS.CONTENA_SHURUI_NAME_RYAKU,
	'' AS CONTENA_CD,
    '' AS CONTENA_NAME_RYAKU,
	MCS.SHOYUU_DAISUU
FROM
    M_CONTENA_SHURUI MCS
WHERE
    MCS.DELETE_FLG = 0
    /*IF data.CONTENA_SHURUI_CD != null*/and MCS.CONTENA_SHURUI_CD = /*data.CONTENA_SHURUI_CD*/ /*END*/