SELECT
    MCS.CONTENA_SHURUI_CD,
    MCS.CONTENA_SHURUI_NAME_RYAKU,
    MC.CONTENA_CD,
    MC.CONTENA_NAME_RYAKU,
    1 AS SHOYUU_DAISUU
FROM
    M_CONTENA_SHURUI MCS
    INNER JOIN
        M_CONTENA MC
    ON  MCS.CONTENA_SHURUI_CD = MC.CONTENA_SHURUI_CD
    AND MC.DELETE_FLG = 0
WHERE
    MCS.DELETE_FLG = 0
	/*IF data.CONTENA_SHURUI_CD != null*/and MCS.CONTENA_SHURUI_CD = /*data.CONTENA_SHURUI_CD*/ /*END*/
	/*IF data.CONTENA_CD != null*/and MC.CONTENA_CD = /*data.CONTENA_CD*/ /*END*/