//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyaryoSentaku.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ParamIn_GyosyaCode {
            get {
                return ((string)(this["ParamIn_GyosyaCode"]));
            }
            set {
                this["ParamIn_GyosyaCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ParamIn_CarCode {
            get {
                return ((string)(this["ParamIn_CarCode"]));
            }
            set {
                this["ParamIn_CarCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ParamIn_CarKind {
            get {
                return ((string)(this["ParamIn_CarKind"]));
            }
            set {
                this["ParamIn_CarKind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ParamIn_UntenshaCode {
            get {
                return ((string)(this["ParamIn_UntenshaCode"]));
            }
            set {
                this["ParamIn_UntenshaCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string paramIn_TekiyouFlg {
            get {
                return ((string)(this["paramIn_TekiyouFlg"]));
            }
            set {
                this["paramIn_TekiyouFlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string paramIn_GyoushaTekiyouFlg {
            get {
                return ((string)(this["paramIn_GyoushaTekiyouFlg"]));
            }
            set {
                this["paramIn_GyoushaTekiyouFlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string paramIn_GyoushaKbn {
            get {
                return ((string)(this["paramIn_GyoushaKbn"]));
            }
            set {
                this["paramIn_GyoushaKbn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ParamIn_ClosedDate {
            get {
                return ((string)(this["ParamIn_ClosedDate"]));
            }
            set {
                this["ParamIn_ClosedDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string paramIn_UnpanGyousyaKbn {
            get {
                return ((string)(this["paramIn_UnpanGyousyaKbn"]));
            }
            set {
                this["paramIn_UnpanGyousyaKbn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string paramIn_ManiKbn {
            get {
                return ((string)(this["paramIn_ManiKbn"]));
            }
            set {
                this["paramIn_ManiKbn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string paramIn_SharyouFlg {
            get {
                return ((string)(this["paramIn_SharyouFlg"]));
            }
            set {
                this["paramIn_SharyouFlg"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string paramIn_NaviKbn
        {
            get
            {
                return ((string)(this["paramIn_NaviKbn"]));
            }
            set
            {
                this["paramIn_NaviKbn"] = value;
            }
        }
    }
}
