SELECT
MCS.DELETE_FLG,
MCS.CONTENA_SHURUI_CD,
MCS.CONTENA_SHURUI_NAME,
MCS.CONTENA_SHURUI_NAME_RYAKU,
MCS.CONTENA_SHURUI_FURIGANA,
MCS.CONTENA_SHURUI_BIKOU,
MCS.SHOYUU_DAISUU,
MCS.UPDATE_USER,
MCS.UPDATE_DATE,
MCS.CREATE_USER,
MCS.CREATE_DATE,
MCS.CREATE_PC,
MCS.UPDATE_PC,
MCS.TIME_STAMP
FROM
dbo.M_CONTENA_SHURUI MCS
/*BEGIN*/WHERE
/*IF data.CONTENA_SHURUI_CD != null*/CAST(MCS.CONTENA_SHURUI_CD AS varchar(3)) LIKE '%' + CAST(/*data.CONTENA_SHURUI_CD*/0 AS varchar(3)) + '%'/*END*/
/*IF data.CONTENA_SHURUI_NAME != null*/AND MCS.CONTENA_SHURUI_NAME LIKE '%' +  /*data.CONTENA_SHURUI_NAME*/ + '%'/*END*/
/*IF data.CONTENA_SHURUI_NAME_RYAKU != null*/AND MCS.CONTENA_SHURUI_NAME_RYAKU LIKE '%' +  /*data.CONTENA_SHURUI_NAME_RYAKU*/ + '%'/*END*/
/*IF data.CONTENA_SHURUI_FURIGANA != null*/AND MCS.CONTENA_SHURUI_FURIGANA LIKE '%' +  /*data.CONTENA_SHURUI_FURIGANA*/ + '%'/*END*/
/*IF data.CONTENA_SHURUI_BIKOU != null*/AND MCS.CONTENA_SHURUI_BIKOU LIKE '%' +  /*data.CONTENA_SHURUI_BIKOU*/ + '%'/*END*/
/*IF data.CREATE_USER != null*/AND MCS.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, MCS.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
/*IF data.UPDATE_USER != null*/AND MCS.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, MCS.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*IF !deletechuFlg*/AND MCS.DELETE_FLG = /*deletechuFlg*/0/*END*/
/*END*/
ORDER BY MCS.CONTENA_SHURUI_CD
