SELECT
TUJE.DENPYOU_SHURUI                         AS DENPYOU_SHURUI
,TUJE.DENPYOU_SYSTEM_ID                     AS DENPYOU_SYSTEM_ID
,TUJE.SEQ                                   AS SEQ
,TUJE.SAGYOU_DATE							AS SAGYOU_DATE
,TUJE.SAGYOU_TIME							AS SAGYOU_TIME
,TUJE.SAGYOUSHA_CD							AS SAGYOUSHA_CD
,ISNULL(TUJE.SAGYOUSHA_NAME, '')			AS SAGYOUSHA_NAME
,TUJE.SAGYOU_BIKOU							AS SAGYOU_BIKOU
,ISNULL(TUJD.DENPYOU_SYSTEM_ID, 0)          AS DETAIL_DENPYOU_SYSTEM_ID
,ISNULL(TUJD.DETAIL_SEQ, 0)                 AS DETAIL_SEQ
,ISNULL(TUJD.HINMEI_CD, '')                 AS HINMEI_CD
,MHIN.HINMEI_NAME_RYAKU                     AS HINMEI_NAME_RYAKU
,TUJD.SUURYOU_WARIAI                        AS SUURYOU_WARIAI
FROM T_UKEIRE_JISSEKI_ENTRY AS TUJE
LEFT JOIN T_UKEIRE_JISSEKI_DETAIL AS TUJD
ON TUJE.DENPYOU_SHURUI = TUJD.DENPYOU_SHURUI
AND TUJE.DENPYOU_SYSTEM_ID = TUJD.DENPYOU_SYSTEM_ID
AND TUJE.SEQ = TUJD.SEQ
LEFT JOIN M_HINMEI AS MHIN
ON MHIN.HINMEI_CD = TUJD.HINMEI_CD
AND MHIN.DELETE_FLG = 0
WHERE 
TUJE.DENPYOU_SHURUI = 1
AND TUJE.DENPYOU_SYSTEM_ID = /*keiryouNum*/
AND TUJE.DELETE_FLG = 0 
