SELECT
 TKE.KEIRYOU_NUMBER                         AS KEIRYOU_NUMBER
,TKE.SYSTEM_ID                              AS SYSTEM_ID
,TKE.SEQ                                    AS SEQ
,ISNULL(TKD.DETAIL_SYSTEM_ID, 0)            AS DETAIL_SYSTEM_ID
,TKE.KYOTEN_CD                              AS KYOTEN_CD
,TKE.DENPYOU_DATE                           AS DENPYOU_DATE
,TKE.TORIHIKISAKI_CD                        AS TORIHIKISAKI_CD
,TKE.GYOUSHA_CD                             AS GYOUSHA_CD
,TKE.GENBA_CD                               AS GENBA_CD
,TKE.UNPAN_GYOUSHA_CD                       AS UNPAN_GYOUSHA_CD
,TKE.NIOROSHI_GYOUSHA_CD                    AS NIOROSHI_GYOUSHA_CD
,TKE.NIOROSHI_GENBA_CD                      AS NIOROSHI_GENBA_CD
,TKE.EIGYOU_TANTOUSHA_CD                    AS EIGYOU_TANTOUSHA_CD
,TKE.NYUURYOKU_TANTOUSHA_CD                 AS NYUURYOKU_TANTOUSHA_CD
,TKE.SHARYOU_CD                             AS SHARYOU_CD
,TKE.SHASHU_CD                              AS SHASHU_CD
,TKE.UNTENSHA_CD                            AS UNTENSHA_CD
,TKE.KEITAI_KBN_CD                          AS KEITAI_KBN_CD
,TKE.MANIFEST_SHURUI_CD                     AS MANIFEST_SHURUI_CD
,TKE.MANIFEST_TEHAI_CD                      AS MANIFEST_TEHAI_CD
,TKE.DENPYOU_BIKOU                          AS DENPYOU_BIKOU
,TKE.TAIRYUU_BIKOU                          AS TAIRYUU_BIKOU
,MTSEI.TORIHIKI_KBN_CD                      AS SEIKYUU_TORIHIKI_KBN_CD
,MTSEI.SHIMEBI1                             AS SEIKYUU_SHIMEBI1
,MTSEI.SHIMEBI2                             AS SEIKYUU_SHIMEBI2
,MTSEI.SHIMEBI3                             AS SEIKYUU_SHIMEBI3
,MTSIH.TORIHIKI_KBN_CD                      AS SHIHARAI_TORIHIKI_KBN_CD
,MTSIH.SHIMEBI1                             AS SHIHARAI_SHIMEBI1
,MTSIH.SHIMEBI2                             AS SHIHARAI_SHIMEBI2
,MTSIH.SHIMEBI3                             AS SHIHARAI_SHIMEBI3
,ISNULL(MKYO.KYOTEN_NAME_RYAKU, '')         AS KYOTEN_NAME_RYAKU
,CASE WHEN ISNULL(TKE.TORIHIKISAKI_NAME, '') = ''  
    THEN 
        CASE WHEN ISNULL(MTOR.TORIHIKISAKI_NAME_RYAKU, '') = ''
            THEN '' ELSE MTOR.TORIHIKISAKI_NAME_RYAKU END
    ELSE TKE.TORIHIKISAKI_NAME END          AS TORIHIKISAKI_NAME_RYAKU
,CASE WHEN MTOR.SHOKUCHI_KBN = 1
    THEN '1' ELSE '0' END                   AS TORIHIKISAKI_SHOKUCHI_KBN
,CASE WHEN ISNULL(TKE.GYOUSHA_NAME, '') = ''  
    THEN 
        CASE WHEN ISNULL(MGYO.GYOUSHA_NAME_RYAKU, '') = ''
            THEN '' ELSE MGYO.GYOUSHA_NAME_RYAKU END
    ELSE TKE.GYOUSHA_NAME END               AS GYOUSHA_NAME_RYAKU
,CASE WHEN MGYO.SHOKUCHI_KBN = 1
    THEN '1' ELSE '0' END                   AS GYOUSHA_SHOKUCHI_KBN
,CASE WHEN ISNULL(TKE.GENBA_NAME, '') = ''  
    THEN 
        CASE WHEN ISNULL(MGEN.GENBA_NAME_RYAKU, '') = ''
            THEN '' ELSE MGEN.GENBA_NAME_RYAKU END
    ELSE TKE.GENBA_NAME END                 AS GENBA_NAME_RYAKU
,CASE WHEN MGEN.SHOKUCHI_KBN = 1
    THEN '1' ELSE '0' END                   AS GENBA_SHOKUCHI_KBN
,ISNULL(UNPAN_GYOUSHA_NAME,
 ISNULL(MUPGYO.GYOUSHA_NAME_RYAKU, ''))     AS UNPAN_GYOUSHA_NAME_RYAKU
,CASE WHEN MUPGYO.SHOKUCHI_KBN = 1
    THEN '1' ELSE '0' END                   AS UNPAN_GYOUSHA_SHOKUCHI_KBN
,ISNULL(NIOROSHI_GYOUSHA_NAME,
 ISNULL(MNIGYO.GYOUSHA_NAME_RYAKU, ''))     AS NIOROSHI_GYOUSHA_NAME_RYAKU
,CASE WHEN MNIGYO.SHOKUCHI_KBN = 1
    THEN '1' ELSE '0' END                   AS NIOROSHI_GYOUSHA_SHOKUCHI_KBN
,ISNULL(NIOROSHI_GENBA_NAME,
 ISNULL(MNIGEN.GENBA_NAME_RYAKU, ''))       AS NIOROSHI_GENBA_NAME_RYAKU
,CASE WHEN MNIGEN.SHOKUCHI_KBN = 1
    THEN '1' ELSE '0' END                   AS NIOROSHI_GENBA_SHOKUCHI_KBN
,ISNULL(MEITAN.SHAIN_NAME_RYAKU, '')        AS EIGYOU_TANTOUSHA_NAME_RYAKU
,ISNULL(MNRTAN.SHAIN_NAME_RYAKU, '')        AS NYUURYOKU_TANTOUSHA_NAME_RYAKU
,CASE WHEN ISNULL(MSHARY.SHARYOU_NAME_RYAKU, '') = ''  
    THEN 
        CASE WHEN ISNULL(TKE.SHARYOU_NAME, '') = ''
            THEN '' ELSE TKE.SHARYOU_NAME END
    ELSE MSHARY.SHARYOU_NAME_RYAKU END      AS SHARYOU_NAME_RYAKU
,ISNULL(MSHASH.SHASHU_NAME_RYAKU, '')       AS SHASHU_NAME_RYAKU
,ISNULL(MUNTEN.SHAIN_NAME_RYAKU, '')        AS UNTENSHA_NAME_RYAKU
,ISNULL(MKK.KEITAI_KBN_NAME_RYAKU, '')      AS KEITAI_KBN_NAME_RYAKU
,ISNULL(MMS.MANIFEST_SHURUI_NAME_RYAKU, '') AS MANIFEST_SHURUI_NAME_RYAKU
,ISNULL(MMT.MANIFEST_TEHAI_NAME_RYAKU, '')  AS MANIFEST_TEHAI_NAME_RYAKU
,ISNULL(TKD.ROW_NO, 0)                      AS DETAIL_ROW_NO
,TKD.STACK_JYUURYOU                         AS DETAIL_STACK_JYUURYOU
,TKD.EMPTY_JYUURYOU                         AS DETAIL_EMPTY_JYUURYOU
,TKD.CHOUSEI_JYUURYOU                       AS DETAIL_CHOUSEI_JYUURYOU
,TKD.CHOUSEI_PERCENT                        AS DETAIL_CHOUSEI_PERCENT
,ISNULL(TKD.YOUKI_CD, '')                   AS DETAIL_YOUKI_CD
,TKD.YOUKI_SUURYOU                          AS DETAIL_YOUKI_SUURYOU
,TKD.YOUKI_JYUURYOU                         AS DETAIL_YOUKI_JYUURYOU
,TKD.DENPYOU_KBN_CD                         AS DETAIL_DENPYOU_KBN_CD
,ISNULL(TKD.HINMEI_CD, '')                  AS DETAIL_HINMEI_CD
,TKD.NET_JYUURYOU                           AS DETAIL_NET_JYUURYOU
,TKD.HINMEI_NAME                            AS DETAIL_HINMEI_NAME
,TKD.SUURYOU                                AS DETAIL_SUURYOU
,TKD.UNIT_CD                                AS DETAIL_UNIT_CD
,TKD.TANKA                                  AS DETAIL_TANKA
,TKD.KINGAKU                                AS DETAIL_KINGAKU
,TKD.MEISAI_BIKOU                           AS MEISAI_BIKOU
,ISNULL(MYOK.YOUKI_NAME_RYAKU, '')          AS DETAIL_YOUKI_NAME_RYAKU
,ISNULL(MDEN.DENPYOU_KBN_NAME_RYAKU, '')    AS DETAIL_DENPYOU_KBN_NAME_RYAKU
,ISNULL(MUNI.UNIT_NAME_RYAKU, '')           AS DETAIL_UNIT_NAME_RYAKU
,TKD.HINMEI_ZEI_KBN_CD                      AS DETAIL_HINMEI_ZEI_KBN_CD
,TKD.HINMEI_KINGAKU                         AS DETAIL_HINMEI_KINGAKU

FROM T_KEIRYOU_ENTRY AS TKE

LEFT JOIN T_KEIRYOU_DETAIL AS TKD
ON TKE.KEIRYOU_NUMBER = TKD.KEIRYOU_NUMBER
AND TKE.SYSTEM_ID = TKD.SYSTEM_ID
AND TKE.SEQ = TKD.SEQ

LEFT JOIN M_KYOTEN AS MKYO
ON MKYO.KYOTEN_CD = TKE.KYOTEN_CD
AND MKYO.DELETE_FLG = 0
LEFT JOIN M_TORIHIKISAKI AS MTOR
ON MTOR.TORIHIKISAKI_CD = TKE.TORIHIKISAKI_CD
AND MTOR.DELETE_FLG = 0
AND (MTOR.TEKIYOU_BEGIN IS NULL
    OR (MTOR.TEKIYOU_BEGIN IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MTOR.TEKIYOU_BEGIN, 111), 120) <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))
AND (MTOR.TEKIYOU_END IS NULL
    OR (MTOR.TEKIYOU_END IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MTOR.TEKIYOU_END, 111), 120) >= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))

LEFT JOIN M_TORIHIKISAKI_SEIKYUU AS MTSEI
ON MTSEI.TORIHIKISAKI_CD = MTOR.TORIHIKISAKI_CD

LEFT JOIN M_TORIHIKISAKI_SHIHARAI AS MTSIH
ON MTSIH.TORIHIKISAKI_CD = MTOR.TORIHIKISAKI_CD

LEFT JOIN M_GYOUSHA AS MGYO
ON MGYO.GYOUSHA_CD = TKE.GYOUSHA_CD
AND MGYO.DELETE_FLG = 0
AND (MGYO.TEKIYOU_BEGIN IS NULL
    OR (MGYO.TEKIYOU_BEGIN IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MGYO.TEKIYOU_BEGIN, 111), 120) <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))
AND (MGYO.TEKIYOU_END IS NULL
    OR (MGYO.TEKIYOU_END IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MGYO.TEKIYOU_END, 111), 120) >= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))

LEFT JOIN M_GENBA AS MGEN
ON MGEN.GYOUSHA_CD = TKE.GYOUSHA_CD
AND MGEN.GENBA_CD = TKE.GENBA_CD
AND MGEN.DELETE_FLG = 0
AND (MGEN.TEKIYOU_BEGIN IS NULL
    OR (MGEN.TEKIYOU_BEGIN IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MGEN.TEKIYOU_BEGIN, 111), 120) <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))
AND (MGEN.TEKIYOU_END IS NULL
    OR (MGEN.TEKIYOU_END IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MGEN.TEKIYOU_END, 111), 120) >= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))

/* 運搬業者 */
LEFT JOIN M_GYOUSHA AS MUPGYO
ON MUPGYO.GYOUSHA_CD = TKE.UNPAN_GYOUSHA_CD
AND MUPGYO.DELETE_FLG = 0
AND (MUPGYO.TEKIYOU_BEGIN IS NULL
    OR (MUPGYO.TEKIYOU_BEGIN IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MUPGYO.TEKIYOU_BEGIN, 111), 120) <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))
AND (MUPGYO.TEKIYOU_END IS NULL
    OR (MUPGYO.TEKIYOU_END IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MUPGYO.TEKIYOU_END, 111), 120) >= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))

LEFT JOIN M_GYOUSHA AS MNIGYO
ON MNIGYO.GYOUSHA_CD = TKE.NIOROSHI_GYOUSHA_CD
AND MNIGYO.DELETE_FLG = 0
AND (MNIGYO.TEKIYOU_BEGIN IS NULL
    OR (MNIGYO.TEKIYOU_BEGIN IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MNIGYO.TEKIYOU_BEGIN, 111), 120) <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))
AND (MNIGYO.TEKIYOU_END IS NULL
    OR (MNIGYO.TEKIYOU_END IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MNIGYO.TEKIYOU_END, 111), 120) >= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))

LEFT JOIN M_GENBA AS MNIGEN
ON MNIGEN.GYOUSHA_CD = TKE.NIOROSHI_GYOUSHA_CD
AND MNIGEN.GENBA_CD = TKE.NIOROSHI_GENBA_CD
AND MNIGEN.DELETE_FLG = 0
AND (MNIGEN.TEKIYOU_BEGIN IS NULL
    OR (MNIGEN.TEKIYOU_BEGIN IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MNIGEN.TEKIYOU_BEGIN, 111), 120) <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))
AND (MNIGEN.TEKIYOU_END IS NULL
    OR (MNIGEN.TEKIYOU_END IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MNIGEN.TEKIYOU_END, 111), 120) >= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))

LEFT JOIN M_SHAIN AS MEITAN
ON MEITAN.SHAIN_CD = TKE.EIGYOU_TANTOUSHA_CD
AND MEITAN.DELETE_FLG = 0

/* 入力担当者 */
LEFT JOIN M_SHAIN AS MNRTAN
ON MNRTAN.SHAIN_CD = TKE.NYUURYOKU_TANTOUSHA_CD
AND MNRTAN.DELETE_FLG = 0

LEFT JOIN M_SHARYOU AS MSHARY
ON MSHARY.GYOUSHA_CD = TKE.UNPAN_GYOUSHA_CD
AND MSHARY.SHARYOU_CD = TKE.SHARYOU_CD
AND MSHARY.DELETE_FLG = 0

LEFT JOIN M_SHASHU AS MSHASH
ON MSHASH.SHASHU_CD = TKE.SHASHU_CD
AND MSHASH.DELETE_FLG = 0

/* 運転者 */
LEFT JOIN M_SHAIN AS MUNTEN
ON MUNTEN.SHAIN_CD = TKE.UNTENSHA_CD
AND MUNTEN.DELETE_FLG = 0

/* 形態区分 */
LEFT JOIN M_KEITAI_KBN AS MKK
ON MKK.KEITAI_KBN_CD = TKE.KEITAI_KBN_CD
AND MKK.DELETE_FLG = 0

/* マニフェスト種類CD */
LEFT JOIN M_MANIFEST_SHURUI AS MMS
ON MMS.MANIFEST_SHURUI_CD = TKE.MANIFEST_SHURUI_CD
AND MMS.DELETE_FLG = 0

/* マニフェスト手配CD */
LEFT JOIN M_MANIFEST_TEHAI AS MMT
ON MMT.MANIFEST_TEHAI_CD = TKE.MANIFEST_TEHAI_CD
AND MMT.DELETE_FLG = 0

/* 容器CD */
LEFT JOIN M_YOUKI AS MYOK
ON MYOK.YOUKI_CD = TKD.YOUKI_CD
AND MYOK.DELETE_FLG = 0

LEFT JOIN M_HINMEI AS MHIN
ON MHIN.HINMEI_CD = TKD.HINMEI_CD
AND MHIN.DELETE_FLG = 0

LEFT JOIN M_DENPYOU_KBN AS MDEN
ON MDEN.DENPYOU_KBN_CD = TKD.DENPYOU_KBN_CD
AND MDEN.DELETE_FLG = 0

LEFT JOIN M_UNIT AS MUNI
ON MUNI.UNIT_CD = TKD.UNIT_CD
AND MUNI.DELETE_FLG = 0

WHERE TKE.KEIRYOU_NUMBER = /*keiryouNum*/
AND TKE.DELETE_FLG = 0 
AND TKE.KIHON_KEIRYOU = 1
