SELECT
 TUKE.UKETSUKE_NUMBER                       AS UKETSUKE_NUMBER
,TUKE.SYSTEM_ID                             AS SYSTEM_ID
,TUKE.SEQ                                   AS SEQ
,ISNULL(TUKD.DETAIL_SYSTEM_ID, 0)           AS DETAIL_SYSTEM_ID
,TUKE.KYOTEN_CD                             AS KYOTEN_CD
,TUKE.TORIHIKISAKI_CD                       AS TORIHIKISAKI_CD
,TUKE.GYOUSHA_CD                            AS GYOUSHA_CD
,TUKE.GENBA_CD                              AS GENBA_CD
,TUKE.UNPAN_GYOUSHA_CD                      AS UNPAN_GYOUSHA_CD
,TUKE.NIOROSHI_GYOUSHA_CD                   AS NIOROSHI_GYOUSHA_CD
,TUKE.NIOROSHI_GENBA_CD                     AS NIOROSHI_GENBA_CD
,TUKE.EIGYOU_TANTOUSHA_CD                   AS EIGYOU_TANTOUSHA_CD
,TUKE.SHARYOU_CD                            AS SHARYOU_CD
,TUKE.SHASHU_CD                             AS SHASHU_CD
,''                                         AS UNTENSHA_CD
,''                                         AS CONTENA_SOUSA_CD
,TUKE.MANIFEST_SHURUI_CD                    AS MANIFEST_SHURUI_CD
,TUKE.MANIFEST_TEHAI_CD                     AS MANIFEST_TEHAI_CD
,TUKE.SAGYOU_DATE                           AS SAGYOU_DATE
,MTSEI.TORIHIKI_KBN_CD                      AS SEIKYUU_TORIHIKI_KBN_CD
,MTSEI.SHIMEBI1                             AS SEIKYUU_SHIMEBI1
,MTSEI.SHIMEBI2                             AS SEIKYUU_SHIMEBI2
,MTSEI.SHIMEBI3                             AS SEIKYUU_SHIMEBI3
,MTSIH.TORIHIKI_KBN_CD                      AS SHIHARAI_TORIHIKI_KBN_CD
,MTSIH.SHIMEBI1                             AS SHIHARAI_SHIMEBI1
,MTSIH.SHIMEBI2                             AS SHIHARAI_SHIMEBI2
,MTSIH.SHIMEBI3                             AS SHIHARAI_SHIMEBI3
,ISNULL(MKYO.KYOTEN_NAME_RYAKU, '')         AS KYOTEN_NAME_RYAKU
--,CASE WHEN ISNULL(TUKE.TORIHIKISAKI_NAME, '') = ''  
--    THEN 
--        CASE WHEN ISNULL(MTOR.TORIHIKISAKI_NAME_RYAKU, '') = ''
--            THEN '' ELSE MTOR.TORIHIKISAKI_NAME_RYAKU END
--    ELSE TUKE.TORIHIKISAKI_NAME END         AS TORIHIKISAKI_NAME_RYAKU
,ISNULL(TUKE.TORIHIKISAKI_NAME, '') AS TORIHIKISAKI_NAME_RYAKU
,CASE WHEN MTOR.SHOKUCHI_KBN = 1
    THEN '1' ELSE '0' END                   AS TORIHIKISAKI_SHOKUCHI_KBN
--,CASE WHEN ISNULL(TUKE.GYOUSHA_NAME, '') = ''  
--    THEN 
--        CASE WHEN ISNULL(MGYO.GYOUSHA_NAME_RYAKU, '') = ''
--            THEN '' ELSE MGYO.GYOUSHA_NAME_RYAKU END
--    ELSE TUKE.GYOUSHA_NAME END              AS GYOUSHA_NAME_RYAKU
,ISNULL(TUKE.GYOUSHA_NAME, '') AS GYOUSHA_NAME_RYAKU
,CASE WHEN MGYO.SHOKUCHI_KBN = 1
    THEN '1' ELSE '0' END                   AS GYOUSHA_SHOKUCHI_KBN
--,CASE WHEN ISNULL(TUKE.GENBA_NAME, '') = ''  
--    THEN 
--        CASE WHEN ISNULL(MGEN.GENBA_NAME_RYAKU, '') = ''
--            THEN '' ELSE MGEN.GENBA_NAME_RYAKU END
--    ELSE TUKE.GENBA_NAME END                AS GENBA_NAME_RYAKU
,ISNULL(TUKE.GENBA_NAME, '') AS GENBA_NAME_RYAKU
,CASE WHEN MGEN.SHOKUCHI_KBN = 1
    THEN '1' ELSE '0' END                   AS GENBA_SHOKUCHI_KBN
--,ISNULL(MUPGYO.GYOUSHA_NAME_RYAKU, '')      AS UNPAN_GYOUSHA_NAME_RYAKU
,ISNULL(TUKE.UNPAN_GYOUSHA_NAME, '')      AS UNPAN_GYOUSHA_NAME_RYAKU
,CASE WHEN MUPGYO.SHOKUCHI_KBN = 1
    THEN '1' ELSE '0' END                   AS UNPAN_GYOUSHA_SHOKUCHI_KBN
--,ISNULL(MNIGYO.GYOUSHA_NAME_RYAKU, '')      AS NIOROSHI_GYOUSHA_NAME_RYAKU
,ISNULL(TUKE.NIOROSHI_GYOUSHA_NAME, '')      AS NIOROSHI_GYOUSHA_NAME_RYAKU
,CASE WHEN MNIGYO.SHOKUCHI_KBN = 1
    THEN '1' ELSE '0' END                   AS NIOROSHI_GYOUSHA_SHOKUCHI_KBN
--,ISNULL(MNIGEN.GENBA_NAME_RYAKU, '')        AS NIOROSHI_GENBA_NAME_RYAKU
,ISNULL(TUKE.NIOROSHI_GENBA_NAME, '')        AS NIOROSHI_GENBA_NAME_RYAKU
,CASE WHEN MNIGEN.SHOKUCHI_KBN = 1
    THEN '1' ELSE '0' END                   AS NIOROSHI_GENBA_SHOKUCHI_KBN
,ISNULL(MSHAI.SHAIN_NAME_RYAKU, '')         AS EIGYOU_TANTOUSHA_NAME_RYAKU
,CASE WHEN ISNULL(MSHAR.SHARYOU_NAME_RYAKU, '') = ''  
    THEN 
        CASE WHEN ISNULL(TUKE.SHARYOU_NAME, '') = ''
            THEN '' ELSE TUKE.SHARYOU_NAME END
    ELSE MSHAR.SHARYOU_NAME_RYAKU END       AS SHARYOU_NAME_RYAKU
,ISNULL(MSHAS.SHASHU_NAME_RYAKU, '')        AS SHASHU_NAME_RYAKU
,''                                         AS UNTENSHA_NAME_RYAKU
,ISNULL(MMS.MANIFEST_SHURUI_NAME_RYAKU, '') AS MANIFEST_SHURUI_NAME_RYAKU
,ISNULL(MMT.MANIFEST_TEHAI_NAME_RYAKU, '')  AS MANIFEST_TEHAI_NAME_RYAKU
,ISNULL(TUKD.ROW_NO, 0)                     AS DETAIL_ROW_NO
,ISNULL(TUKD.HINMEI_CD, '')                 AS DETAIL_HINMEI_CD
,TUKD.DENPYOU_KBN_CD                        AS DETAIL_DENPYOU_KBN_CD
,TUKD.SUURYOU                               AS DETAIL_SUURYOU
,TUKD.UNIT_CD                               AS DETAIL_UNIT_CD
,TUKD.TANKA                                 AS DETAIL_TANKA
,TUKD.KINGAKU                               AS DETAIL_KINGAKU
,ISNULL(TUKD.MEISAI_BIKOU, '')              AS DETAIL_MEISAI_BIKOU
,CASE WHEN ISNULL(MHK1.HINMEI_CD, '') != '' THEN MHK1.SEIKYUU_HINMEI_NAME
      WHEN ISNULL(MHK2.HINMEI_CD, '') != '' THEN MHK2.SEIKYUU_HINMEI_NAME
	  ELSE MHIN.HINMEI_NAME
	  END AS DETAIL_HINMEI_NAME_RYAKU
--,ISNULL(MHIN.HINMEI_NAME_RYAKU, '')         AS DETAIL_HINMEI_NAME_RYAKU
,MHIN.ZEI_KBN_CD                            AS DETAIL_HINMEI_ZEI_KBN_CD
,ISNULL(MDEN.DENPYOU_KBN_NAME_RYAKU, '')    AS DETAIL_DENPYOU_KBN_NAME_RYAKU
,ISNULL(MUNI.UNIT_NAME_RYAKU, '')           AS DETAIL_UNIT_NAME_RYAKU
,''											AS CONTENA_SOUSA_CD
,''											AS CONTENA_JOUKYOU_NAME_RYAKU
,ISNULL(TUKE.YOYAKU_JOKYO_CD, 1)            AS YOYAKU_JOKYO_CD

FROM T_UKETSUKE_MK_ENTRY AS TUKE

LEFT JOIN T_UKETSUKE_MK_DETAIL AS TUKD
ON TUKE.UKETSUKE_NUMBER = TUKD.UKETSUKE_NUMBER
AND TUKE.SYSTEM_ID = TUKD.SYSTEM_ID
AND TUKE.SEQ = TUKD.SEQ

LEFT JOIN M_KYOTEN AS MKYO
ON MKYO.KYOTEN_CD = TUKE.KYOTEN_CD
AND MKYO.DELETE_FLG = 0

LEFT JOIN M_TORIHIKISAKI AS MTOR
ON MTOR.TORIHIKISAKI_CD = TUKE.TORIHIKISAKI_CD
AND MTOR.DELETE_FLG = 0
AND (MTOR.TEKIYOU_BEGIN IS NULL
    OR (MTOR.TEKIYOU_BEGIN IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MTOR.TEKIYOU_BEGIN, 111), 120) <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))
AND (MTOR.TEKIYOU_END IS NULL
    OR (MTOR.TEKIYOU_END IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MTOR.TEKIYOU_END, 111), 120) >= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))

LEFT JOIN M_TORIHIKISAKI_SEIKYUU AS MTSEI
ON MTSEI.TORIHIKISAKI_CD = MTOR.TORIHIKISAKI_CD

LEFT JOIN M_TORIHIKISAKI_SHIHARAI AS MTSIH
ON MTSIH.TORIHIKISAKI_CD = MTOR.TORIHIKISAKI_CD

LEFT JOIN M_GYOUSHA AS MGYO
ON MGYO.GYOUSHA_CD = TUKE.GYOUSHA_CD
AND MGYO.DELETE_FLG = 0
AND (MGYO.TEKIYOU_BEGIN IS NULL
    OR (MGYO.TEKIYOU_BEGIN IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MGYO.TEKIYOU_BEGIN, 111), 120) <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))
AND (MGYO.TEKIYOU_END IS NULL
    OR (MGYO.TEKIYOU_END IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MGYO.TEKIYOU_END, 111), 120) >= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))

LEFT JOIN M_GENBA AS MGEN
ON MGEN.GYOUSHA_CD = TUKE.GYOUSHA_CD
AND MGEN.GENBA_CD = TUKE.GENBA_CD
AND MGEN.DELETE_FLG = 0
AND (MGEN.TEKIYOU_BEGIN IS NULL
    OR (MGEN.TEKIYOU_BEGIN IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MGEN.TEKIYOU_BEGIN, 111), 120) <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))
AND (MGEN.TEKIYOU_END IS NULL
    OR (MGEN.TEKIYOU_END IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MGEN.TEKIYOU_END, 111), 120) >= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))

/* 運搬業者 */
LEFT JOIN M_GYOUSHA AS MUPGYO
ON MUPGYO.GYOUSHA_CD = TUKE.UNPAN_GYOUSHA_CD
AND MUPGYO.DELETE_FLG = 0
AND (MUPGYO.TEKIYOU_BEGIN IS NULL
    OR (MUPGYO.TEKIYOU_BEGIN IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MUPGYO.TEKIYOU_BEGIN, 111), 120) <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))
AND (MUPGYO.TEKIYOU_END IS NULL
    OR (MUPGYO.TEKIYOU_END IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MUPGYO.TEKIYOU_END, 111), 120) >= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))

LEFT JOIN M_GYOUSHA AS MNIGYO
ON MNIGYO.GYOUSHA_CD = TUKE.NIOROSHI_GYOUSHA_CD
AND MNIGYO.DELETE_FLG = 0
AND (MNIGYO.TEKIYOU_BEGIN IS NULL
    OR (MNIGYO.TEKIYOU_BEGIN IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MNIGYO.TEKIYOU_BEGIN, 111), 120) <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))
AND (MNIGYO.TEKIYOU_END IS NULL
    OR (MNIGYO.TEKIYOU_END IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MNIGYO.TEKIYOU_END, 111), 120) >= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))

LEFT JOIN M_GENBA AS MNIGEN
ON MNIGEN.GYOUSHA_CD = TUKE.NIOROSHI_GYOUSHA_CD
AND MNIGEN.GENBA_CD = TUKE.NIOROSHI_GENBA_CD
AND MNIGEN.DELETE_FLG = 0
AND (MNIGEN.TEKIYOU_BEGIN IS NULL
    OR (MNIGEN.TEKIYOU_BEGIN IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MNIGEN.TEKIYOU_BEGIN, 111), 120) <= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))
AND (MNIGEN.TEKIYOU_END IS NULL
    OR (MNIGEN.TEKIYOU_END IS NOT NULL AND CONVERT(DATETIME, CONVERT(nvarchar, MNIGEN.TEKIYOU_END, 111), 120) >= CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120)))

LEFT JOIN M_SHAIN AS MSHAI
ON MSHAI.SHAIN_CD = TUKE.EIGYOU_TANTOUSHA_CD

LEFT JOIN M_SHARYOU AS MSHAR
ON MSHAR.GYOUSHA_CD = TUKE.UNPAN_GYOUSHA_CD
AND MSHAR.SHARYOU_CD = TUKE.SHARYOU_CD
AND MSHAR.DELETE_FLG = 0

LEFT JOIN M_SHASHU AS MSHAS
ON MSHAS.SHASHU_CD = TUKE.SHASHU_CD

/* マニフェスト種類CD */
LEFT JOIN M_MANIFEST_SHURUI AS MMS
ON MMS.MANIFEST_SHURUI_CD = TUKE.MANIFEST_SHURUI_CD
AND MMS.DELETE_FLG = 0

/* マニフェスト手配CD */
LEFT JOIN M_MANIFEST_TEHAI AS MMT
ON MMT.MANIFEST_TEHAI_CD = TUKE.MANIFEST_TEHAI_CD
AND MMT.DELETE_FLG = 0

LEFT JOIN M_HINMEI AS MHIN
ON MHIN.HINMEI_CD = TUKD.HINMEI_CD

LEFT JOIN M_KOBETSU_HINMEI AS MHK1
ON MHK1.GYOUSHA_CD = TUKE.GYOUSHA_CD
AND MHK1.GENBA_CD = TUKE.GENBA_CD
AND MHK1.HINMEI_CD = TUKD.HINMEI_CD
AND MHK1.DELETE_FLG = 0

LEFT JOIN M_KOBETSU_HINMEI AS MHK2
ON MHK2.GYOUSHA_CD = TUKE.GYOUSHA_CD
AND MHK2.GENBA_CD = ''
AND MHK2.HINMEI_CD = TUKD.HINMEI_CD
AND MHK2.DELETE_FLG = 0

LEFT JOIN M_DENPYOU_KBN AS MDEN
ON MDEN.DENPYOU_KBN_CD = TUKD.DENPYOU_KBN_CD
AND MDEN.DELETE_FLG = 0

LEFT JOIN M_UNIT AS MUNI
ON MUNI.UNIT_CD = TUKD.UNIT_CD

WHERE TUKE.UKETSUKE_NUMBER = /*uketsukeNum*/
AND TUKE.DELETE_FLG = 0
ORDER BY TUKE.SYSTEM_ID,TUKE.SEQ,TUKD.ROW_NO
