SELECT
  MZHI.ZAIKO_HINMEI_CD,
  MZHI.ZAIKO_HINMEI_NAME,
  MZHI.ZAIKO_HIRITSU,
  MZH.ZAIKO_TANKA
FROM
  (
  SELECT
    DENSHU_KBN_CD,
    HINMEI_CD,
    ZAIKO_HINMEI_CD,
    ZAIKO_HINMEI_NAME,
    ZAIKO_HIRITSU
  FROM
    M_ZAIKO_HIRITSU
  WHERE
    DELETE_FLG = 0
  ) MZHI
LEFT OUTER JOIN
  (
  SELECT
    ZAIKO_HINMEI_CD,
    ZAIKO_TANKA
  FROM
    M_ZAIKO_HINMEI
  WHERE
    DELETE_FLG = 0
  ) MZH
ON
  MZHI.ZAIKO_HINMEI_CD = MZH.ZAIKO_HINMEI_CD
WHERE
  MZHI.DENSHU_KBN_CD = /*data.DENSHU_KBN_CD*/'' AND
  MZHI.HINMEI_CD = /*data.HINMEI_CD*/''