SELECT
	MCN.COURSE_NAME_RYAKU
	,MCD.REC_ID
	,MCD.ROUND_NO
	,MCD.GYOUSHA_CD
	,MGY.GYOUSHA_NAME_RYAKU
	,MCD.GENBA_CD
	,MGB.GENBA_NAME_RYAKU
	,MCD.BIKOU AS MEISAI_BIKOU
-- 	追加分START
	,MCD.ROW_NO
-- 	追加分END
	,MCD.KIBOU_TIME
	,MCD.SAGYOU_TIME_MINUTE
FROM M_COURSE_DETAIL MCD
	INNER JOIN M_COURSE_NAME MCN
		ON MCN.COURSE_NAME_CD = MCD.COURSE_NAME_CD
		/*IF data.KyotenCd != null && data.KyotenCd != ''*/
		AND (MCN.KYOTEN_CD = /*data.KyotenCd*/ OR MCN.KYOTEN_CD = 99)
		/*END*/
        AND MCN.DELETE_FLG = 0
	INNER JOIN M_COURSE MC
		ON MC.DAY_CD = MCD.DAY_CD
        AND MC.COURSE_NAME_CD = MCD.COURSE_NAME_CD
        AND MC.DELETE_FLG = 0
	LEFT JOIN M_GYOUSHA MGY
		ON MGY.GYOUSHA_CD = MCD.GYOUSHA_CD
	LEFT JOIN M_GENBA MGB
		ON MGB.GYOUSHA_CD = MCD.GYOUSHA_CD
        AND MGB.GENBA_CD = MCD.GENBA_CD
WHERE 
	MCD.COURSE_NAME_CD = /*data.CourseNameCd*/
/*IF data.DayCd != 0*/
	AND MCD.DAY_CD = /*data.DayCd*/ 
/*END*/ORDER BY
	MCD.ROW_NO