SELECT
	MC4.DAY_CD
	,MC4.COURSE_NAME_CD
	,MC4.REC_ID
	,MC4.REC_SEQ
	,MC4.HINMEI_CD
	,MC4.UNIT_CD
	,MC4.KANSANCHI
	,MC4.KANSAN_UNIT_CD
	,MC4.KEIYAKU_KBN
	,MC4.KEIJYOU_KBN
	,MC4.DENPYOU_KBN_CD
	,MC4.KANSAN_UNIT_MOBILE_OUTPUT_FLG
	,MC4.INPUT_KBN
	,MC4.NIOROSHI_NO AS NIOROSHI_NUMBER
	,MC4.ANBUN_FLG
	,MC4.TEKIYOU_BEGIN
	,MC4.TEKIYOU_END
FROM
	M_COURSE_DETAIL_ITEMS MC4
	LEFT JOIN M_COURSE_DETAIL AS MCD ON MC4.DAY_CD = MCD.DAY_CD AND MC4.COURSE_NAME_CD = MCD.COURSE_NAME_CD AND MC4.REC_ID = MCD.REC_ID
WHERE
--	MC4.DAY_CD = 1
--	AND MC4.COURSE_NAME_CD = '000011'
	MC4.COURSE_NAME_CD = /*data.CourseNameCd*/
	AND ((MC4.TEKIYOU_BEGIN <= /*data.SagyouDate*/ AND /*data.SagyouDate*/ <= MC4.TEKIYOU_END)
	OR (MC4.TEKIYOU_BEGIN <= /*data.SagyouDate*/ AND MC4.TEKIYOU_END IS NULL))
/*IF data.DayCd != 0*/
	AND MC4.DAY_CD = /*data.DayCd*/
/*END*/
	/*IF data.RecId != 0*/
	AND MCD.REC_ID = /*data.RecId*/
	/*END*/