SELECT            
	M_COURSE_NAME.COURSE_NAME_CD, 
	M_COURSE_NAME.COURSE_NAME_RYAKU, 
	M_COURSE_NAME.KYOTEN_CD, 
    M_KYOTEN.KYOTEN_NAME_RYAKU, 
	M_COURSE.SHASHU_CD,
	M_SHASHU.SHASHU_NAME_RYAKU,
	M_COURSE.SHARYOU_CD,
	M_SHARYOU.SHARYOU_NAME_RYAKU,
	M_COURSE.UNTENSHA_CD,
	M_SHAIN.SHAIN_NAME_RYAKU AS UNTENSHA_NAME_RYAKU,
	M_COURSE.UNPAN_GYOUSHA_CD,
	M_GYOUSHA.GYOUSHA_NAME_RYAKU AS UNPAN_GYOUSHA_NAME_RYAKU,
	M_COURSE.SAGYOU_BEGIN_HOUR,
	M_COURSE.SAGYOU_BEGIN_MINUTE,
	M_COURSE.SAGYOU_END_HOUR,
	M_COURSE.SAGYOU_END_MINUTE,
	M_COURSE.SHUPPATSU_GYOUSHA_CD,
	M_COURSE.SHUPPATSU_GENBA_CD
FROM              
	M_COURSE_NAME
	INNER JOIN M_COURSE ON M_COURSE.COURSE_NAME_CD = M_COURSE_NAME.COURSE_NAME_CD
	LEFT OUTER JOIN M_KYOTEN ON M_COURSE_NAME.KYOTEN_CD = M_KYOTEN.KYOTEN_CD
	LEFT JOIN M_SHASHU ON M_SHASHU.SHASHU_CD = M_COURSE.SHASHU_CD
	LEFT JOIN M_SHARYOU ON M_SHARYOU.GYOUSHA_CD = M_COURSE.UNPAN_GYOUSHA_CD AND M_SHARYOU.SHARYOU_CD = M_COURSE.SHARYOU_CD
	LEFT JOIN M_SHAIN ON M_SHAIN.SHAIN_CD = M_COURSE.UNTENSHA_CD
	LEFT JOIN M_GYOUSHA	ON M_GYOUSHA.GYOUSHA_CD = M_COURSE.UNPAN_GYOUSHA_CD
WHERE
	M_COURSE_NAME.DELETE_FLG = 0
/*IF data.DayCd != 0*/
    AND M_COURSE.DAY_CD = /*data.DayCd*/
/*END*/
	AND M_COURSE.DELETE_FLG = 0
	AND M_COURSE_NAME.COURSE_NAME_CD = M_COURSE.COURSE_NAME_CD
	/*IF data.CourseNameCd != null && data.CourseNameCd != ''*/
	AND M_COURSE.COURSE_NAME_CD = /*data.CourseNameCd*/
	/*END*/
	/*IF data.KyotenCd != null && data.KyotenCd != ''*/
	AND (M_COURSE_NAME.KYOTEN_CD = /*data.KyotenCd*/ OR M_COURSE_NAME.KYOTEN_CD = 99)
	/*END*/
