SELECT 
	TTHS.*
	,MH.HINMEI_NAME_RYAKU
	,MU.UNIT_NAME_RYAKU
FROM
	T_TEIKI_HAISHA_SHOUSAI TTHS
	LEFT JOIN M_HINMEI MH
		ON TTHS.HINMEI_CD = MH.HINMEI_CD
	LEFT JOIN M_UNIT MU
		ON TTHS.UNIT_CD = MU.UNIT_CD
WHERE
	TTHS.SYSTEM_ID = /*data.SystemId*/
	AND TTHS.SEQ = /*data.Seq*/
	AND TTHS.DETAIL_SYSTEM_ID = /*data.DetailSystemId*/
ORDER BY
	TTHS.HINMEI_CD, TTHS.ROW_NUMBER