SELECT
	MC1.DAY_CD
	,MC1.COURSE_NAME_CD
	,MC0.COURSE_NAME_RYAKU
	,MC0.KYOTEN_CD
	,MKT.KYOTEN_NAME_RYAKU
	,MC1.COURSE_BIKOU
	,CONVERT(datetime,/*data.SagyouDate*/) AS SAGYOU_DATE
	,MC1.SHASHU_CD
	,MSH.SHASHU_NAME_RYAKU
	,MC1.SHARYOU_CD
	,MSR.SHARYOU_NAME_RYAKU
	,MC1.UNTENSHA_CD
	,MUN.SHAIN_NAME_RYAKU AS UNTENSHA_NAME_RYAKU
	,MC1.UNPAN_GYOUSHA_CD
	,MG.GYOUSHA_NAME_RYAKU AS UNPAN_GYOUSHA_NAME
FROM
	M_COURSE MC1
	INNER JOIN M_COURSE_NAME MC0
		ON MC0.COURSE_NAME_CD = MC1.COURSE_NAME_CD
		/*IF data.KyotenCd != 99 */
		AND MC0.KYOTEN_CD = /*data.KyotenCd*/
		/*END*/
		AND MC0.DELETE_FLG = 0
	LEFT JOIN T_TEIKI_HAISHA_ENTRY TH1
		ON TH1.COURSE_NAME_CD = MC1.COURSE_NAME_CD
		AND TH1.SAGYOU_DATE = /*data.SagyouDate*/
		/*IF data.KyotenCd != 99 */
		AND TH1.KYOTEN_CD = /*data.KyotenCd*/
		/*END*/
		AND TH1.DELETE_FLG = 0
	LEFT JOIN M_KYOTEN MKT
		ON MKT.KYOTEN_CD = MC0.KYOTEN_CD
	LEFT JOIN M_SHARYOU MSR
		ON MSR.GYOUSHA_CD = MC1.UNPAN_GYOUSHA_CD
		AND MSR.SHARYOU_CD = MC1.SHARYOU_CD
	LEFT JOIN M_SHASHU MSH
		ON MSH.SHASHU_CD = MC1.SHASHU_CD
	LEFT JOIN M_SHAIN MUN
		ON MUN.SHAIN_CD = MC1.UNTENSHA_CD
	LEFT JOIN M_GYOUSHA MG
		ON MG.GYOUSHA_CD = MC1.UNPAN_GYOUSHA_CD
WHERE
	MC1.DELETE_FLG = 0
/*IF data.DayCd != 0*/
    /*IF data.DayCd == 1*/
	AND MC0.MONDAY = 1
    /*END*/
    /*IF data.DayCd == 2*/
	AND MC0.TUESDAY = 1
    /*END*/
    /*IF data.DayCd == 3*/
	AND MC0.WEDNESDAY = 1
    /*END*/
    /*IF data.DayCd == 4*/
	AND MC0.THURSDAY = 1
    /*END*/
    /*IF data.DayCd == 5*/
	AND MC0.FRIDAY = 1
    /*END*/
    /*IF data.DayCd == 6*/
	AND MC0.SATURDAY = 1
    /*END*/
    /*IF data.DayCd == 7*/
	AND MC0.SUNDAY = 1
    /*END*/
	AND MC1.DAY_CD = /*data.DayCd*/
/*END*/
	/*IF data.KyotenCd != 99 */
	AND MC0.KYOTEN_CD = /*data.KyotenCd*/
	/*END*/
	AND TH1.COURSE_NAME_CD IS null
ORDER BY SAGYOU_DATE,COURSE_NAME_CD