SELECT * FROM dbo.M_CHIIKIBETSU_SHOBUN
WHERE DELETE_FLG = 0
/*IF data.CHIIKI_CD != null*/AND CHIIKI_CD = /*data.CHIIKI_CD*//*END*/
/*IF data.SHOBUN_HOUHOU_CD != null*/AND SHOBUN_HOUHOU_CD = /*data.SHOBUN_HOUHOU_CD*//*END*/
/*IF data.HOUKOKU_SHOBUN_HOUHOU_CD != null*/AND HOUKOKU_SHOBUN_HOUHOU_CD = /*data.HOUKOKU_SHOBUN_HOUHOU_CD*//*END*/
/*IF data.HOUKOKU_SHOBUN_HOUHOU_NAME != null*/AND HOUKOKU_SHOBUN_HOUHOU_NAME = /*data.HOUKOKU_SHOBUN_HOUHOU_NAME*//*END*/
/*IF data.SHOBUN_MOKUTEKI_CD != null*/AND SHOBUN_MOKUTEKI_CD = /*data.SHOBUN_MOKUTEKI_CD*//*END*/
/*IF data.CHIIKIBETSU_SHOBUN_BIKOU != null*/AND CHIIKIBETSU_SHOBUN_BIKOU = /*data.CHIIKIBETSU_SHOBUN_BIKOU*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
