SELECT
	RESULT.CONTENA_SHURUI_CD AS CONTENA_SHURUI_CD,
	RESULT.CONTENA_SET_KBN AS CONTENA_SET_KBN,
	ISNULL(RESULT.DAISUU_CNT, 0) AS DAISUU_CNT
FROM
	T_CONTENA_RESULT AS RESULT
	LEFT JOIN T_UKEIRE_ENTRY AS UKEIRE
	ON RESULT.DENSHU_KBN_CD = 1
	AND RESULT.SYSTEM_ID = UKEIRE.SYSTEM_ID
	AND RESULT.SEQ = UKEIRE.SEQ
	AND UKEIRE.DELETE_FLG = 0
	LEFT JOIN T_UR_SH_ENTRY AS UR_SH
	ON RESULT.DENSHU_KBN_CD = 3
	AND RESULT.SYSTEM_ID = UR_SH.SYSTEM_ID
	AND RESULT.SEQ = UR_SH.SEQ
	AND UR_SH.DELETE_FLG = 0
WHERE
	RESULT.DELETE_FLG = 0
	/*IF data.contenaChuruiCdStart != null*/ AND RESULT.CONTENA_SHURUI_CD >= /*data.contenaChuruiCdStart*/ /*END*/
	/*IF data.contenaChuruiCdEnd != null*/ AND RESULT.CONTENA_SHURUI_CD <= /*data.contenaChuruiCdEnd*/ /*END*/
	/*IF !data.kijunbi.IsNull */
	AND (UKEIRE.DENPYOU_DATE <= /*data.kijunbi.Date*/ OR UR_SH.DENPYOU_DATE <= /*data.kijunbi.Date*/)
	/*END*/

UNION ALL (
	SELECT
		RESERVE.CONTENA_SHURUI_CD AS CONTENA_SHURUI_CD,
		RESERVE.CONTENA_SET_KBN AS CONTENA_SET_KBN,
		ISNULL(RESERVE.DAISUU_CNT, 0) AS DAISUU_CNT
	FROM
		T_CONTENA_RESERVE AS RESERVE
		LEFT JOIN T_UKETSUKE_SS_ENTRY UKETSUKE
		ON RESERVE.SYSTEM_ID = UKETSUKE.SYSTEM_ID
		AND RESERVE.SEQ = UKETSUKE.SEQ
		AND UKETSUKE.DELETE_FLG = 0
	WHERE
		RESERVE.DELETE_FLG = 0
		AND CALC_DAISUU_FLG = 1
		/*IF data.contenaChuruiCdStart != null*/ AND RESERVE.CONTENA_SHURUI_CD >= /*data.contenaChuruiCdStart*/ /*END*/
		/*IF data.contenaChuruiCdEnd != null*/ AND RESERVE.CONTENA_SHURUI_CD <= /*data.contenaChuruiCdEnd*/ /*END*/
		/*IF !data.kijunbi.IsNull */
		AND UKETSUKE.SAGYOU_DATE <= /*data.kijunbi.Date*/
		/*END*/
		AND UKETSUKE.HAISHA_JOKYO_CD != 4
		/*IF data.juchuHaishaHukumu == null || data.juchuHaishaHukumu == '2'*/
		AND UKETSUKE.HAISHA_JOKYO_CD NOT IN (1, 2)
		/*END*/
)