SELECT 
    BUN.*
FROM 
    dbo.M_GENBAMEMO_BUNRUI BUN
/*BEGIN*/WHERE
/*IF data.GENBAMEMO_BUNRUI_CD != null && data.GENBAMEMO_BUNRUI_CD != '' */ BUN.GENBAMEMO_BUNRUI_CD LIKE '%' + /*data.GENBAMEMO_BUNRUI_CD*/ + '%'/*END*/
 /*IF data.GENBAMEMO_BUNRUI_NAME != null && data.GENBAMEMO_BUNRUI_NAME != ''*/AND BUN.GENBAMEMO_BUNRUI_NAME LIKE '%' +  /*data.GENBAMEMO_BUNRUI_NAME*/ + '%'/*END*/
 /*IF data.GENBAMEMO_BUNRUI_NAME_RYAKU != null && data.GENBAMEMO_BUNRUI_NAME_RYAKU != ''*/AND BUN.GENBAMEMO_BUNRUI_NAME_RYAKU LIKE '%' +  /*data.GENBAMEMO_BUNRUI_NAME_RYAKU*/ + '%'/*END*/
 /*IF data.GENBAMEMO_BUNRUI_FURIGANA != null && data.GENBAMEMO_BUNRUI_FURIGANA != ''*/AND BUN.GENBAMEMO_BUNRUI_FURIGANA LIKE '%' +  /*data.GENBAMEMO_BUNRUI_FURIGANA*/ + '%'/*END*/
 /*IF data.CREATE_USER != null && data.CREATE_USER != ''*/AND BUN.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, BUN.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null && data.UPDATE_USER != ''*/AND BUN.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, BUN.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*END*/
ORDER BY BUN.GENBAMEMO_BUNRUI_CD
