SELECT ISNULL(MIN(GE.GENBA_CD),1) GENBA_CD
FROM 
	(
		SELECT (CONVERT(INT, GENBA_CD) + 1) GENBA_CD FROM M_GENBA WHERE GYOUSHA_CD = /*gyoushaCd*/ AND ISNUMERIC(GENBA_CD)=1 
	) GE
WHERE GE.GENBA_CD NOT IN (
		SELECT (CONVERT(INT, GENBA_CD) + 0) GENBA_CD FROM M_GENBA WHERE GYOUSHA_CD = /*gyoushaCd*/ AND ISNUMERIC(GENBA_CD)=1
	)