SELECT 
    GEN.GENBA_CD AS GENBA_CD
	,GEN.HIKIAI_GYOUSHA_USE_FLG AS HIKIAI_GYOUSHA_USE_FLG
    ,ISNULL(GEN.GENBA_NAME1,N'') AS GENBA_NAME1
    ,ISNULL(GEN.GENBA_ADDRESS1,N'') AS GENBA_ADDRESS1
    ,ISNULL(GEN.GENBA_NAME2,N'') AS GENBA_NAME2
    ,ISNULL(GEN.GENBA_ADDRESS2,N'') AS GENBA_ADDRESS2
FROM 
    dbo.M_HIKIAI_GENBA GEN
WHERE GEN.GYOUSHA_CD = /*data.GYOUSHA_CD*/'000001'
  /*IF !data.TORIHIKI_JOUKYOU.IsNull && data.TORIHIKI_JOUKYOU.Value == 2*/AND GEN.TORIHIKI_JOUKYOU = 2/*END*/
  AND GEN.DELETE_FLG = 0
ORDER BY GEN.GENBA_CD
