SELECT T_CARRY_ON_REQUEST_UKETSUKE_MK_INXS.UKETSUKE_SYSTEM_ID AS UKETSUKE_SYSTEM_ID
	, T_CARRY_ON_REQUEST_INXS.[STATUS] AS REQUEST_STATUS
	, PREFERENCE_DATE.PREFERENCE_DATE AS CONFIRM_DATE
	, T_CARRY_ON_REQUEST_INXS.IS_UPDATE_SHOUGUN_SAGYOU_DATE
FROM T_CARRY_ON_REQUEST_UKETSUKE_MK_INXS
INNER JOIN T_CARRY_ON_REQUEST_INXS ON T_CARRY_ON_REQUEST_INXS.SYSTEM_ID = T_CARRY_ON_REQUEST_UKETSUKE_MK_INXS.REQUEST_SYSTEM_ID AND T_CARRY_ON_REQUEST_INXS.DELETE_FLG = 0
LEFT JOIN T_CARRY_ON_REQUEST_PREFERENCE_DATE_INXS PREFERENCE_DATE ON PREFERENCE_DATE.SYSTEM_ID = T_CARRY_ON_REQUEST_INXS.SYSTEM_ID 
								AND PREFERENCE_DATE.SEQ = T_CARRY_ON_REQUEST_INXS.SEQ AND PREFERENCE_DATE.[ROW_NUMBER] = 10
WHERE T_CARRY_ON_REQUEST_UKETSUKE_MK_INXS.UKETSUKE_SYSTEM_ID =  /*data.SystemID*/