SELECT  T_UMKD.*
		, M_DENPYOU_KBN.DENPYOU_KBN_NAME_RYAKU
		, M_UNIT.UNIT_NAME_RYAKU
FROM	T_UKETSUKE_MK_DETAIL AS T_UMKD 
LEFT OUTER JOIN M_UNIT 
             ON T_UMKD.UNIT_CD = M_UNIT.UNIT_CD 
LEFT OUTER JOIN M_DENPYOU_KBN 
             ON T_UMKD.DENPYOU_KBN_CD = M_DENPYOU_KBN.DENPYOU_KBN_CD 
			AND M_DENPYOU_KBN.DELETE_FLG = 0
WHERE T_UMKD.UKETSUKE_NUMBER = /*data.UketsukeNumber*/
  AND T_UMKD.SYSTEM_ID = /*data.SystemID*/
  AND T_UMKD.SEQ = /*data.SEQ*/
ORDER BY T_UMKD.ROW_NO