SELECT * FROM dbo.S_NUMBER_YEAR
WHERE DELETE_FLG = 0
/*IF !data.NUMBERED_YEAR.IsNull*/AND NUMBERED_YEAR = /*data.NUMBERED_YEAR.Value*//*END*/
/*IF !data.DENSHU_KBN_CD.IsNull*/AND DENSHU_KBN_CD = /*data.DENSHU_KBN_CD.Value*//*END*/
/*IF !data.KYOTEN_CD.IsNull*/AND KYOTEN_CD = /*data.KYOTEN_CD.Value*//*END*/