SELECT * FROM dbo.M_SHASHU
WHERE 
/*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
 DELETE_FLG = 0
-- ELSE
 1 = 1
/*END*/
/*IF data.SHASHU_CD != null*/AND SHASHU_CD = /*data.SHASHU_CD*//*END*/
/*IF data.SHASHU_NAME != null*/AND SHASHU_NAME = /*data.SHASHU_NAME*//*END*/
/*IF data.SHASHU_NAME_RYAKU != null*/AND SHASHU_NAME_RYAKU = /*data.SHASHU_NAME_RYAKU*//*END*/
/*IF data.SHASHU_FURIGANA != null*/AND SHASHU_FURIGANA = /*data.SHASHU_FURIGANA*//*END*/
/*IF data.SHASHU_BIKOU != null*/AND SHASHU_BIKOU = /*data.SHASHU_BIKOU*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
