SELECT  TOP(1) 
	    M_GENBA_TEIKI_HINMEI.UNIT_CD, 
		M_GENBA_TEIKI_HINMEI.MONDAY, 
		M_GENBA_TEIKI_HINMEI.TUESDAY, 
		M_GENBA_TEIKI_HINMEI.WEDNESDAY, 
		M_GENBA_TEIKI_HINMEI.THURSDAY, 
		M_GENBA_TEIKI_HINMEI.FRIDAY, 
		M_GENBA_TEIKI_HINMEI.SATURDAY, 
		M_GENBA_TEIKI_HINMEI.SUNDAY, 
		M_GENBA_TEIKI_HINMEI.KANSAN_UNIT_CD, 
		M_GENBA_TEIKI_HINMEI.KANSANCHI,
        M_GENBA_TEIKI_HINMEI.DENPYOU_KBN_CD,
        M_GENBA_TEIKI_HINMEI.KEIYAKU_KBN,
		M_GENBA_TEIKI_HINMEI.KEIJYOU_KBN,
		M_GENBA_TEIKI_HINMEI.KANSAN_UNIT_MOBILE_OUTPUT_FLG,
		M_GENBA_TEIKI_HINMEI.ANBUN_FLG
FROM   M_GENBA_TEIKI_HINMEI
/*IF gyoushaCD != null*/WHERE M_GENBA_TEIKI_HINMEI.GYOUSHA_CD = /*gyoushaCD*//*END*/	
/*IF genbaCD != null*/AND M_GENBA_TEIKI_HINMEI.GENBA_CD = /*genbaCD*//*END*/	
/*IF hinmeiCd != null*/AND M_GENBA_TEIKI_HINMEI.HINMEI_CD = /*hinmeiCd*//*END*/	
/*IF denpyouKbnCd != null && denpyouKbnCd != 0 */ AND M_GENBA_TEIKI_HINMEI.DENPYOU_KBN_CD = /*denpyouKbnCd*/ /*END*/

ORDER BY M_GENBA_TEIKI_HINMEI.GYOUSHA_CD, M_GENBA_TEIKI_HINMEI.GENBA_CD, ROW_NO