SELECT  TOP(1) 
	    M_GENBA_TEIKI_HINMEI.UNIT_CD, 
		M_GENBA_TEIKI_HINMEI.MONDAY, 
		M_GENBA_TEIKI_HINMEI.TUESDAY, 
		M_GENBA_TEIKI_HINMEI.WEDNESDAY, 
		M_GENBA_TEIKI_HINMEI.THURSDAY, 
		M_GENBA_TEIKI_HINMEI.FRIDAY, 
		M_GENBA_TEIKI_HINMEI.SATURDAY, 
		M_GENBA_TEIKI_HINMEI.SUNDAY, 
		M_GENBA_TEIKI_HINMEI.KANSAN_UNIT_CD, 
		M_GENBA_TEIKI_HINMEI.KANSANCHI,
        M_GENBA_TEIKI_HINMEI.DENPYOU_KBN_CD,
        M_GENBA_TEIKI_HINMEI.KEIYAKU_KBN,
        M_GENBA_TEIKI_HINMEI.KEIJYOU_KBN,
        M_GENBA_TEIKI_HINMEI.TSUKI_HINMEI_CD,
		M_GENBA_TEIKI_HINMEI.KANSAN_UNIT_MOBILE_OUTPUT_FLG,
		M_GENBA_TEIKI_HINMEI.ANBUN_FLG
FROM   M_GENBA_TEIKI_HINMEI
/*IF data.GYOUSHA_CD != null*/WHERE M_GENBA_TEIKI_HINMEI.GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/	
/*IF data.GENBA_CD != null*/AND M_GENBA_TEIKI_HINMEI.GENBA_CD = /*data.GENBA_CD*//*END*/	
/*IF data.HINMEI_CD != null*/AND M_GENBA_TEIKI_HINMEI.HINMEI_CD = /*data.HINMEI_CD*//*END*/	
/*IF data.DENPYOU_KBN_CD != null*/ AND M_GENBA_TEIKI_HINMEI.DENPYOU_KBN_CD = /*data.DENPYOU_KBN_CD*//*END*/
/*IF data.UNIT_CD != null*/AND M_GENBA_TEIKI_HINMEI.UNIT_CD = /*data.UNIT_CD*//*END*/

ORDER BY M_GENBA_TEIKI_HINMEI.GYOUSHA_CD, M_GENBA_TEIKI_HINMEI.GENBA_CD, ROW_NO