SELECT * FROM dbo.M_GENNYOURITSU
WHERE DELETE_FLG = 0
/*IF data.HOUKOKUSHO_BUNRUI_CD != null*/AND HOUKOKUSHO_BUNRUI_CD = /*data.HOUKOKUSHO_BUNRUI_CD*//*END*/
/*IF data.HAIKI_NAME_CD != null*/AND HAIKI_NAME_CD = /*data.HAIKI_NAME_CD*//*END*/
/*IF data.SHOBUN_HOUHOU_CD != null*/AND SHOBUN_HOUHOU_CD = /*data.SHOBUN_HOUHOU_CD*//*END*/
/*IF !data.GENNYOURITSU.IsNull*/AND GENNYOURITSU = /*data.GENNYOURITSU.Value*//*END*/
/*IF data.GENNYOURITSU_BIKOU != null*/AND GENNYOURITSU_BIKOU = /*data.GENNYOURITSU_BIKOU*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
