--SELECT * FROM S_LIST_COLUMN_SELECT, S_LIST_COLUMN_SELECT_DETAIL
--WHERE
--WINDOW_ID = /*windowID*/1
--AND DETAIL_KBN = /*detailKbn*/1
--AND DISP_KBN = 1

SELECT
S_LIST_COLUMN_SELECT.WINDOW_ID,
S_LIST_COLUMN_SELECT.KOUMOKU_ID,
S_LIST_COLUMN_SELECT.KOUMOKU_RONRI_NAME,
S_LIST_COLUMN_SELECT.OUTPUT_FORMAT,
S_LIST_COLUMN_SELECT.OUTPUT_ALIGN,
S_LIST_COLUMN_SELECT_DETAIL.BUTSURI_NAME,
S_LIST_COLUMN_SELECT_DETAIL.TABLE_NAME,
S_LIST_COLUMN_SELECT_DETAIL.DATA_TYPE
FROM S_LIST_COLUMN_SELECT, S_LIST_COLUMN_SELECT_DETAIL
WHERE
(S_LIST_COLUMN_SELECT.WINDOW_ID = /*windowID*/1 AND S_LIST_COLUMN_SELECT_DETAIL.WINDOW_ID = /*windowID*/1 ) AND
S_LIST_COLUMN_SELECT_DETAIL.KOUMOKU_ID = S_LIST_COLUMN_SELECT.KOUMOKU_ID AND
DETAIL_KBN = /*detailKbn*/1 AND DISP_KBN = 1
