SELECT 
    CHI.*
    ,ISNULL(HOB.HOUKOKUSHO_BUNRUI_NAME_RYAKU,N'') AS HOUKOKUSHO_BUNRUI_NAME_RYAKU
FROM 
    dbo.M_CHIIKIBETSU_BUNRUI CHI
	LEFT JOIN dbo.M_HOUKOKUSHO_BUNRUI HOB ON HOB.HOUKOKUSHO_BUNRUI_CD = CHI.HOUKOKUSHO_BUNRUI_CD
WHERE CHI.CHIIKI_CD = /*data.CHIIKI_CD*/'000001'
ORDER BY CHI.CHIIKI_CD, CHI.HOUKOKUSHO_BUNRUI_CD
