SELECT 
    CHI.*
    ,ISNULL(HOB.HOUKOKUSHO_BUNRUI_NAME_RYAKU,N'') AS HOUKOKUSHO_BUNRUI_NAME_RYAKU
FROM 
    dbo.M_CHIIKIBETSU_BUNRUI CHI
	LEFT JOIN dbo.M_HOUKOKUSHO_BUNRUI HOB ON HOB.HOUKOKUSHO_BUNRUI_CD = CHI.HOUKOKUSHO_BUNRUI_CD
WHERE CHI.CHIIKI_CD = /*data.CHIIKI_CD*/'000001'
  /*IF data.HOUKOKUSHO_BUNRUI_CD != null*/AND CHI.HOUKOKUSHO_BUNRUI_CD LIKE '%' +  /*data.HOUKOKUSHO_BUNRUI_CD*/ + '%'/*END*/
  /*IF data.HOUKOKU_BUNRUI_CD != null*/AND CHI.HOUKOKU_BUNRUI_CD LIKE '%' +  /*data.HOUKOKU_BUNRUI_CD*/ + '%'/*END*/
  /*IF data.HOUKOKU_BUNRUI_NAME != null*/AND CHI.HOUKOKU_BUNRUI_NAME LIKE '%' +  /*data.HOUKOKU_BUNRUI_NAME*/ + '%'/*END*/
  /*IF data.UPDATE_USER != null*/AND CHI.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
  /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, CHI.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
  /*IF data.CREATE_USER != null*/AND CHI.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
  /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, CHI.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
  /*IF !deletechuFlg*/AND CHI.DELETE_FLG = /*deletechuFlg*/0/*END*/
ORDER BY CHI.CHIIKI_CD, CHI.HOUKOKUSHO_BUNRUI_CD
