SELECT 
    CHI.*
    ,ISNULL(HOB.HOUKOKUSHO_BUNRUI_NAME_RYAKU,N'') AS HOUKOKUSHO_BUNRUI_NAME_RYAKU
FROM 
    dbo.M_CHIIKIBETSU_BUNRUI CHI
	LEFT JOIN dbo.M_HOUKOKUSHO_BUNRUI HOB ON HOB.HOUKOKUSHO_BUNRUI_CD = CHI.HOUKOKUSHO_BUNRUI_CD
WHERE 1 <> 1