//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shougun.Core.Billing.Seikyuichiran.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_KYOTEN_CD {
            get {
                return ((string)(this["SET_KYOTEN_CD"]));
            }
            set {
                this["SET_KYOTEN_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_KYOTEN_NAME_RYAKU {
            get {
                return ((string)(this["SET_KYOTEN_NAME_RYAKU"]));
            }
            set {
                this["SET_KYOTEN_NAME_RYAKU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HIDUKE_FROM {
            get {
                return ((string)(this["SET_HIDUKE_FROM"]));
            }
            set {
                this["SET_HIDUKE_FROM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_HIDUKE_TO {
            get {
                return ((string)(this["SET_HIDUKE_TO"]));
            }
            set {
                this["SET_HIDUKE_TO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SET_TORIHIKISAKI_CD {
            get {
                return ((string)(this["SET_TORIHIKISAKI_CD"]));
            }
            set {
                this["SET_TORIHIKISAKI_CD"] = value;
            }
        }
    }
}
