SELECT 
 M_DENSHI_JIGYOUSHA.EDI_MEMBER_ID , 
 M_DENSHI_JIGYOUSHA.JIGYOUSHA_NAME , 
 M_DENSHI_JIGYOUSHA.JIGYOUSHA_POST , 
 M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS1 TODOFUKEN_NAME , 
 ISNULL(M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS2,N'') + ISNULL(M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS3, N'') JIGYOUSHA_ADDRESS , 
 M_DENSHI_JIGYOUSHA.JIGYOUSHA_TEL , 
 M_DENSHI_JIGYOUSHA.GYOUSHA_CD , 
 M_GYOUSHA.GYOUSHA_NAME_RYAKU , 

 M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS1 , 
 M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS2 , 
 M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS3 , 
 M_DENSHI_JIGYOUSHA.JIGYOUSHA_ADDRESS4 , 
 M_GYOUSHA.GYOUSHA_NAME1 , 
 M_GYOUSHA.GYOUSHA_NAME2 , 
 M_GYOUSHA.GYOUSHA_ADDRESS1 , 
 M_GYOUSHA.GYOUSHA_ADDRESS2
 
 FROM M_DENSHI_JIGYOUSHA
 LEFT JOIN M_GYOUSHA ON M_DENSHI_JIGYOUSHA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD

