SELECT 
M_HIKIAI_TORIHIKISAKI.TORIHIKISAKI_CD, 
M_HIKIAI_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU, 
M_HIKIAI_TORIHIKISAKI.TORIHIKISAKI_FURIGANA, 
M_HIKIAI_TORIHIKISAKI.TORIHIKISAKI_POST, 
M_TODOUFUKEN.TODOUFUKEN_NAME_RYAKU, 
M_HIKIAI_TORIHIKISAKI.TORIHIKISAKI_ADDRESS1, 
M_HIKIAI_TORIHIKISAKI.TORIHIKISAKI_TEL, 
'1' AS TORIHIKISAKI_HIKIAI_FLG 

FROM M_HIKIAI_TORIHIKISAKI 
LEFT JOIN M_HIKIAI_GYOUSHA ON M_HIKIAI_GYOUSHA.TORIHIKISAKI_CD = M_HIKIAI_TORIHIKISAKI.TORIHIKISAKI_CD 
LEFT JOIN M_TODOUFUKEN ON M_HIKIAI_TORIHIKISAKI.TORIHIKISAKI_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD 
AND M_TODOUFUKEN.DELETE_FLG = 0
