SELECT 
M_NYUUKINSAKI.NYUUKINSAKI_CD, 
M_NYUUKINSAKI.NYUUKINSAKI_NAME_RYAKU, 
M_NYUUKINSAKI.NYUUKINSAKI_FURIGANA, 
M_NYUUKINSAKI.NYUUKINSAKI_POST, 
M_TODOUFUKEN.TODOUFUKEN_NAME_RYAKU, 
M_NYUUKINSAKI.NYUUKINSAKI_ADDRESS1, 
M_NYUUKINSAKI.NYUUKINSAKI_TEL 
FROM M_NYUUKINSAKI 
LEFT JOIN M_TODOUFUKEN ON M_NYUUKINSAKI.NYUUKINSAKI_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD 
AND M_TODOUFUKEN.DELETE_FLG = 0