SELECT 
M_SYUKKINSAKI.SYUKKINSAKI_CD, 
M_SYUKKINSAKI.SYUKKINSAKI_NAME_RYAKU, 
M_SYUKKINSAKI.SYUKKINSAKI_FURIGANA, 
M_SYUKKINSAKI.SYUKKINSAKI_POST, 
M_TODOUFUKEN.TODOUFUKEN_NAME_RYAKU, 
M_SYUKKINSAKI.SYUKKINSAKI_ADDRESS1, 
M_SYUKKINSAKI.SYUKKINSAKI_TEL 
FROM M_SYUKKINSAKI 
LEFT JOIN M_TODOUFUKEN ON M_SYUKKINSAKI.SYUKKINSAKI_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD 
AND M_TODOUFUKEN.DELETE_FLG = 0