SELECT 
M_TORIHIKISAKI.TORIHIKISAKI_CD, 
M_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU, 
M_TODOUFUKEN.TODOUFUKEN_NAME_RYAKU, 
M_TORIHIKISAKI.TORIHIKISAKI_ADDRESS1, 
M_TORIHIKISAKI.TORIHIKISAKI_FURIGANA, 
M_TORIHIKISAKI.TORIHIKISAKI_POST, 
M_TORIHIKISAKI.TORIHIKISAKI_TEL,
M_TORIHIKISAKI.TORIHIKISAKI_NAME1,
M_TORIHIKISAKI.TORIHIKISAKI_NAME2,
M_TORIHIKISAKI.TORIHIKISAKI_ADDRESS2 
FROM M_TORIHIKISAKI 
LEFT JOIN M_TODOUFUKEN ON M_TORIHIKISAKI.TORIHIKISAKI_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD 
AND M_TODOUFUKEN.DELETE_FLG = 0
