SELECT HAIKI_SHURUI_CD,HAIKI_SHURUI_NAME
FROM M_DENSHI_HAIKI_SHURUI WITH(NOLOCK) 
WHERE 1 = 1
/*IF data.HAIKI_SHURUI_CD != null &&  data.HAIKI_SHURUI_CD !='' */AND HAIKI_SHURUI_CD = /*data.HAIKI_SHURUI_CD*//*END*/