SELECT  R18EX.SYSTEM_ID AS SYSTEM_ID,
        R18EX.SEQ AS SEQ,
        '電子' AS HAIKI_KBN_NAME,
        CONVERT(datetime,DT_R18.HIKIWATASHI_DATE,120) AS KOUFU_DATE,	--交付日付
        DT_R18.MANIFEST_ID AS MANIFEST_ID,								--交付番号
        DT_R18.HAIKI_SUU AS HAIKI_SUU,
        DT_R18.HAIKI_DAI_CODE + DT_R18.HAIKI_CHU_CODE + DT_R18.HAIKI_SHO_CODE AS HAIKI_SHURUI_CD ,--電子廃棄物種類
        (SELECT TOP 1 HAIKI_NAME_CD FROM M_DENSHI_HAIKI_NAME WHERE HAIKI_NAME = DT_R18.HAIKI_NAME ) AS HAIKI_NAME_CD ,--電子廃棄物名称CD
        (SELECT CASE WHEN TBL.KANSANSHIKI=0 THEN DT_R18.HAIKI_SUU*TBL.KANSANCHI
            ELSE DT_R18.HAIKI_SUU/TBL.KANSANCHI END 
            FROM (SELECT KANSANSHIKI,KANSANCHI 
        FROM M_MANIFEST_KANSAN
        WHERE  HOUKOKUSHO_BUNRUI_CD = MDHS.HOUKOKUSHO_BUNRUI_CD
        AND HAIKI_NAME_CD = (SELECT TOP 1 HAIKI_NAME_CD FROM M_DENSHI_HAIKI_NAME WHERE HAIKI_NAME = DT_R18.HAIKI_NAME )
        AND UNIT_CD = DT_R18.HAIKI_UNIT_CODE
        AND NISUGATA_CD = DT_R18.NISUGATA_CODE) TBL) AS KANSAN_SUU,			--換算後数量
        DT_R18.KANRI_ID AS KANRI_ID,										--管理番号
        DMTC.LATEST_SEQ AS LATEST_SEQ										--最後のSEQ			
        
FROM 	DT_R18 INNER JOIN (SELECT KANRI_ID,LATEST_SEQ FROM DT_MF_TOC) DMTC ON DMTC.KANRI_ID  = DT_R18.KANRI_ID 
        AND DMTC.LATEST_SEQ = DT_R18.SEQ 
        LEFT JOIN M_DENSHI_HAIKI_SHURUI MDHS ON MDHS.HAIKI_SHURUI_CD = DT_R18.HAIKI_DAI_CODE + DT_R18.HAIKI_CHU_CODE + DT_R18.HAIKI_SHO_CODE
        LEFT JOIN M_UNIT MU ON MU.UNIT_CD = DT_R18.HAIKI_UNIT_CODE
        LEFT JOIN DT_R18_EX R18EX ON R18EX.KANRI_ID = DT_R18.KANRI_ID AND R18EX.SEQ = DT_R18.SEQ AND R18EX.DELETE_FLG = 0
        LEFT JOIN T_MANIFEST_RELATION TMR ON TMR.FIRST_SYSTEM_ID = R18EX.SYSTEM_ID AND TMR.DELETE_FLG = 0 
WHERE DMTC.KANRI_ID  = DT_R18.KANRI_ID 
      AND DMTC.LATEST_SEQ = DT_R18.SEQ 
      AND DT_R18.KANRI_ID = /*data.KANRI_ID*/