SELECT
	ISNULL(CONVERT(NVARCHAR, MD.LAST_SBN_END_DATE, 112), '') AS LAST_SBN_END_DATE
	, ISNULL(GENBA.GENBA_NAME1, '')
		+ ISNULL(GENBA.GENBA_NAME2, '')
		+ ISNULL(TODOUFUKEN.TODOUFUKEN_NAME, '')
		+ ISNULL(GENBA.GENBA_ADDRESS1, '')
		+ ISNULL(GENBA.GENBA_ADDRESS2, '')
	AS LAST_SBN_JIGYOUJOU_NAME_AND_ADDRESS
FROM
	T_MANIFEST_ENTRY AS ME WITH(NOLOCK)
	INNER JOIN T_MANIFEST_DETAIL AS MD WITH(NOLOCK)
		ON ME.SYSTEM_ID = MD.SYSTEM_ID
		AND ME.SEQ = MD.SEQ
	INNER JOIN M_GENBA AS GENBA WITH(NOLOCK)
		ON MD.LAST_SBN_GYOUSHA_CD = GENBA.GYOUSHA_CD
		AND MD.LAST_SBN_GENBA_CD = GENBA.GENBA_CD
	LEFT JOIN M_TODOUFUKEN AS TODOUFUKEN WITH(NOLOCK)
	ON GENBA.GENBA_TODOUFUKEN_CD = TODOUFUKEN.TODOUFUKEN_CD
WHERE
	ME.DELETE_FLG = 0
	/*IF data.SECOND_SYSTEM_ID != null*/
		AND ME.SYSTEM_ID = /*data.SECOND_SYSTEM_ID*/
	/*END*/