--最終処分終了報告状況の取得（FLG：0（なし）1（報告済）2（報告中））
--混廃なし
SELECT R18EX.SYSTEM_ID, R18EX.SEQ, R18EX.KANRI_ID,
CASE WHEN R18.KANRI_ID IS NOT NULL THEN 1 
ELSE 
    CASE WHEN LATEST_QUE_INFO.KANRI_ID IS NOT NULL AND LATEST_QUE_INFO.STATUS_FLAG = 7 THEN 3
       WHEN LATEST_QUE_INFO.KANRI_ID IS NOT NULL THEN 2
  ELSE
    CASE WHEN QUE_INFO.KANRI_ID IS NOT NULL THEN 2 
    ELSE 
      CASE WHEN LAST_SBN_SUSPEND.KANRI_ID IS NOT NULL THEN 3
      ELSE 0 
      END
    END
  END
END AS FLG
FROM DT_R18_EX R18EX 
INNER JOIN (SELECT KANRI_ID,KIND,LATEST_SEQ FROM DT_MF_TOC WHERE STATUS_FLAG <> 9 AND (KIND <> '5' OR KIND IS NULL)) DT_MF_TOC
ON R18EX.KANRI_ID = DT_MF_TOC.KANRI_ID
LEFT JOIN 
  (SELECT DT_R18.KANRI_ID FROM DT_R18
  INNER JOIN DT_MF_TOC ON ((DT_R18.KANRI_ID = DT_MF_TOC.KANRI_ID) AND (DT_R18.SEQ = DT_MF_TOC.LATEST_SEQ))
  WHERE LAST_SBN_ENDREP_FLAG = 1) AS R18 
ON R18EX.KANRI_ID = R18.KANRI_ID
LEFT JOIN (SELECT KANRI_ID,SEQ,STATUS_FLAG FROM QUE_INFO WHERE FUNCTION_ID = 2000 AND STATUS_FLAG IN (0,1,2,7)) LATEST_QUE_INFO
ON R18EX.KANRI_ID = LATEST_QUE_INFO.KANRI_ID
AND DT_MF_TOC.LATEST_SEQ = LATEST_QUE_INFO.SEQ
LEFT JOIN (SELECT KANRI_ID FROM QUE_INFO WHERE FUNCTION_ID = 2000 AND STATUS_FLAG IN (0,1,7)) QUE_INFO
ON R18EX.KANRI_ID = QUE_INFO.KANRI_ID
LEFT JOIN
  (SELECT KANRI_ID FROM T_LAST_SBN_SUSPEND 
  INNER JOIN (SELECT FIRST_SYSTEM_ID,NEXT_SYSTEM_ID FROM T_MANIFEST_RELATION WHERE DELETE_FLG = 0) MANIFEST_RELATION
  ON T_LAST_SBN_SUSPEND.SYSTEM_ID = MANIFEST_RELATION.NEXT_SYSTEM_ID
  INNER JOIN (SELECT KANRI_ID,SYSTEM_ID FROM DT_R18_EX WHERE DELETE_FLG = 0) R18EX
  ON MANIFEST_RELATION.FIRST_SYSTEM_ID = R18EX.SYSTEM_ID
  WHERE T_LAST_SBN_SUSPEND.DELETE_FLG = 0) LAST_SBN_SUSPEND
ON R18EX.KANRI_ID = LAST_SBN_SUSPEND.KANRI_ID
WHERE R18EX.DELETE_FLG = 0 
AND R18EX.SYSTEM_ID = /*SYSTEM_ID*/

UNION

--混廃あり
SELECT R18EX.SYSTEM_ID, R18EX.SEQ, R18EX.KANRI_ID,
CASE WHEN R18.KANRI_ID IS NOT NULL THEN 1 
ELSE 
  CASE WHEN LATEST_QUE_INFO.KANRI_ID IS NOT NULL AND LATEST_QUE_INFO.STATUS_FLAG = 7 THEN 3
       WHEN LATEST_QUE_INFO.KANRI_ID IS NOT NULL THEN 2
  ELSE
    CASE WHEN QUE_INFO.KANRI_ID IS NOT NULL THEN 2 
    ELSE 
      CASE WHEN LAST_SBN_SUSPEND.KANRI_ID IS NOT NULL THEN 3
      ELSE 0 
      END
    END
  END
END AS FLG
FROM DT_R18_MIX R18EX 
INNER JOIN (SELECT KANRI_ID,KIND,LATEST_SEQ FROM DT_MF_TOC WHERE STATUS_FLAG <> 9 AND (KIND <> '5' OR KIND IS NULL)) DT_MF_TOC
ON R18EX.KANRI_ID = DT_MF_TOC.KANRI_ID
LEFT JOIN 
  (SELECT DT_R18.KANRI_ID FROM DT_R18
  INNER JOIN DT_MF_TOC ON ((DT_R18.KANRI_ID = DT_MF_TOC.KANRI_ID) AND (DT_R18.SEQ = DT_MF_TOC.LATEST_SEQ))
  WHERE LAST_SBN_ENDREP_FLAG = 1) AS R18 
ON R18EX.KANRI_ID = R18.KANRI_ID
LEFT JOIN (SELECT KANRI_ID,SEQ,STATUS_FLAG  FROM QUE_INFO WHERE FUNCTION_ID = 2000) LATEST_QUE_INFO
ON R18EX.KANRI_ID = LATEST_QUE_INFO.KANRI_ID
AND DT_MF_TOC.LATEST_SEQ = LATEST_QUE_INFO.SEQ
LEFT JOIN (SELECT KANRI_ID FROM QUE_INFO WHERE FUNCTION_ID = 2000 AND (STATUS_FLAG = 0 OR STATUS_FLAG = 1)) QUE_INFO
ON R18EX.KANRI_ID = QUE_INFO.KANRI_ID
LEFT JOIN
  (SELECT KANRI_ID FROM T_LAST_SBN_SUSPEND 
  INNER JOIN (SELECT FIRST_SYSTEM_ID,NEXT_SYSTEM_ID FROM T_MANIFEST_RELATION WHERE DELETE_FLG = 0) MANIFEST_RELATION
  ON T_LAST_SBN_SUSPEND.SYSTEM_ID = MANIFEST_RELATION.NEXT_SYSTEM_ID
  INNER JOIN (SELECT KANRI_ID,SYSTEM_ID,DETAIL_SYSTEM_ID FROM DT_R18_MIX WHERE DELETE_FLG = 0) R18EX
  ON MANIFEST_RELATION.FIRST_SYSTEM_ID = R18EX.DETAIL_SYSTEM_ID
  WHERE T_LAST_SBN_SUSPEND.DELETE_FLG = 0) LAST_SBN_SUSPEND
ON R18EX.KANRI_ID = LAST_SBN_SUSPEND.KANRI_ID
WHERE R18EX.DELETE_FLG = 0 
AND R18EX.DETAIL_SYSTEM_ID = /*SYSTEM_ID*/