SELECT QI.KANRI_ID
  FROM QUE_INFO QI
 INNER JOIN M_SYS_INFO MSI ON MSI.SYS_ID = 0
 WHERE QI.STATUS_FLAG IN (8, 9)
   AND QI.UPDATE_TS >= CONVERT(DATETIME, GETDATE() - ISNULL(MSI.MANIFEST_TUUCHI_BEGIN, 0), 120)
   AND QI.UPDATE_TS <= CONVERT(DATETIME, GETDATE() - ISNULL(MSI.MANIFEST_TUUCHI_END, 0), 120)