SELECT DISTINCT N'業者マスタ' AS NAME FROM M_GYOUSHA WHERE TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/'' AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'個別品名単価マスタ' AS NAME FROM M_KOBETSU_HINMEI_TANKA WHERE TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/'' AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'現場マスタ' AS NAME
FROM M_GENBA
WHERE DELETE_FLG = 'False'
AND ((TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/'')
OR((MANI_HENSOUSAKI_TORIHIKISAKI_CD_A = /*data.TORIHIKISAKI_CD*/'')
OR (MANI_HENSOUSAKI_TORIHIKISAKI_CD_B1 = /*data.TORIHIKISAKI_CD*/'')
OR (MANI_HENSOUSAKI_TORIHIKISAKI_CD_B2 = /*data.TORIHIKISAKI_CD*/'')
OR (MANI_HENSOUSAKI_TORIHIKISAKI_CD_B4 = /*data.TORIHIKISAKI_CD*/'')
OR (MANI_HENSOUSAKI_TORIHIKISAKI_CD_B6 = /*data.TORIHIKISAKI_CD*/'')
OR (MANI_HENSOUSAKI_TORIHIKISAKI_CD_C1 = /*data.TORIHIKISAKI_CD*/'')
OR (MANI_HENSOUSAKI_TORIHIKISAKI_CD_C2 = /*data.TORIHIKISAKI_CD*/'')
OR (MANI_HENSOUSAKI_TORIHIKISAKI_CD_D = /*data.TORIHIKISAKI_CD*/'')
OR (MANI_HENSOUSAKI_TORIHIKISAKI_CD_E = /*data.TORIHIKISAKI_CD*/'')))
GROUP BY GYOUSHA_CD, GENBA_CD