SELECT 
    NYU.*
FROM 
    dbo.M_NYUUKINSAKI NYU
/*BEGIN*/WHERE
 /*IF data.NYUUKINSAKI_CD != null*/
 NYU.NYUUKINSAKI_CD = /*data.NYUUKINSAKI_CD*/'000001'
 /*END*/
/*END*/
ORDER BY NYU.NYUUKINSAKI_CD
