SELECT 
    SYU.*
FROM 
    dbo.M_SYUKKINSAKI SYU
/*BEGIN*/WHERE
 /*IF data.SYUKKINSAKI_CD != null*/
 SYU.SYUKKINSAKI_CD = /*data.SYUKKINSAKI_CD*/'000001'
 /*END*/
/*END*/
ORDER BY SYU.SYUKKINSAKI_CD
