UPDATE M_SYUKKINSAKI
SET
 SYUKKINSAKI_NAME1 = /*data.SYUKKINSAKI_NAME1*/
,SYUKKINSAKI_NAME2 = /*data.SYUKKINSAKI_NAME2*/
,SYUKKINSAKI_NAME_RYAKU = /*data.SYUKKINSAKI_NAME_RYAKU*/
,SYUKKINSAKI_FURIGANA = /*data.SYUKKINSAKI_FURIGANA*/
,SYUKKINSAKI_TEL = /*data.SYUKKINSAKI_TEL*/
,SYUKKINSAKI_FAX = /*data.SYUKKINSAKI_FAX*/
,SYUKKINSAKI_POST = /*data.SYUKKINSAKI_POST*/
,SYUKKINSAKI_TODOUFUKEN_CD = /*data.SYUKKINSAKI_TODOUFUKEN_CD*/
,SYUKKINSAKI_ADDRESS1 = /*data.SYUKKINSAKI_ADDRESS1*/
,SYUKKINSAKI_ADDRESS2 = /*data.SYUKKINSAKI_ADDRESS2*/
,UPDATE_USER = /*data.UPDATE_USER*/
,UPDATE_DATE = /*data.UPDATE_DATE*/
,UPDATE_PC = /*data.UPDATE_PC*/
,DELETE_FLG = /*data.DELETE_FLG*/
/*BEGIN*/WHERE
 /*IF data.SYUKKINSAKI_CD != null*/
 SYUKKINSAKI_CD = /*data.SYUKKINSAKI_CD*/
 /*END*/
/*END*/
