SELECT
    MTS.TORIHIKISAKI_CD AS TORIHIKISAKI_CD,
    MT.TORIHIKISAKI_NAME_RYAKU AS TORIHIKISAKI_NAME_RYAKU,
	'' AS GYOUSHA_CD,
	'' AS GYOUSHA_NAME_RYAKU,
	'' AS GENBA_CD,
	'' AS GENBA_NAME_RYAKU,
    MT.EIGYOU_TANTOU_CD AS EIGYOUSHA_CD,
    MS.SHAIN_NAME_RYAKU AS SHAIN_NAME_RYAKU,
    '' AS SHUKKIN_YOTEI_BI,
    MTS.KAISHI_KAIKAKE_ZANDAKA AS SEISAN_GAKU,
    ISNULL(TNK.KESHIKOMI_GAKU, 0) AS SHUKKIN_GAKU,
    MTS.KAISHI_KAIKAKE_ZANDAKA - ISNULL(TNK.KESHIKOMI_GAKU, 0) AS MISHUKKIN_GAKU,
    MTS.SHIMEBI1 AS SHIMEBI,
    '開始残高' AS SEISAN_DATE,
    MTS.SHIHARAI_HOUHOU AS SHIHARAI_HOUHOU,
    MNK.NYUUSHUKKIN_KBN_NAME_RYAKU AS NYUUSHUKKIN_KBN_NAME_RYAKU,
    ISNULL(TNK.SEISAN_NUMBER, 0) AS SEISAN_NUMBER,
    ISNULL(TNK.KAGAMI_NUMBER, 0) AS KAGAMI_NUMBER,
    MT.TORIHIKISAKI_FURIGANA AS TORIHIKISAKI_FURIGANA,
    MS.SHAIN_FURIGANA AS SHAIN_FURIGANA
FROM M_TORIHIKISAKI_SHIHARAI AS MTS
LEFT JOIN (
    SELECT
        TORIHIKISAKI_CD,
        SEISAN_NUMBER,
		KAGAMI_NUMBER,
        SUM(KESHIKOMI_GAKU) AS KESHIKOMI_GAKU
    FROM T_SHUKKIN_KESHIKOMI
    WHERE SEISAN_NUMBER = 0 AND DELETE_FLG = 0
    GROUP BY TORIHIKISAKI_CD, SEISAN_NUMBER, KAGAMI_NUMBER
) AS TNK
    ON MTS.TORIHIKISAKI_CD = TNK.TORIHIKISAKI_CD AND TNK.SEISAN_NUMBER = 0 AND TNK.KAGAMI_NUMBER = 0
LEFT JOIN M_TORIHIKISAKI AS MT
    ON MT.TORIHIKISAKI_CD = MTS.TORIHIKISAKI_CD
LEFT JOIN M_SHAIN AS MS
    ON MS.SHAIN_CD = MT.EIGYOU_TANTOU_CD
LEFT JOIN M_NYUUSHUKKIN_KBN AS MNK
    ON MNK.NYUUSHUKKIN_KBN_CD = MTS.SHIHARAI_HOUHOU
WHERE MTS.KAISHI_KAIKAKE_ZANDAKA - ISNULL(TNK.KESHIKOMI_GAKU, 0) <> 0
/*IF dto.KyotenCd != null && dto.KyotenCd != 99*/AND MT.TORIHIKISAKI_KYOTEN_CD = /*dto.KyotenCd*/99/*END*/
/*IF dto.EigyoushaCdFrom != null && dto.EigyoushaCdFrom != ''*/AND MT.EIGYOU_TANTOU_CD >= /*dto.EigyoushaCdFrom*/''/*END*/
/*IF dto.EigyoushaCdTo != null && dto.EigyoushaCdTo != ''*/AND MT.EIGYOU_TANTOU_CD <= /*dto.EigyoushaCdTo*/''/*END*/
/*IF dto.TorihikisakiCdFrom != null && dto.TorihikisakiCdFrom != ''*/AND MTS.TORIHIKISAKI_CD >= /*dto.TorihikisakiCdFrom*/''/*END*/
/*IF dto.TorihikisakiCdTo != null && dto.TorihikisakiCdTo != ''*/AND MTS.TORIHIKISAKI_CD <= /*dto.TorihikisakiCdTo*/''/*END*/

UNION ALL

SELECT
    TSD.TORIHIKISAKI_CD,
    MT.TORIHIKISAKI_NAME_RYAKU,
	TSDK.GYOUSHA_CD,
	MGYOUSHA.GYOUSHA_NAME_RYAKU,
	TSDK.GENBA_CD,
	MGENBA.GENBA_NAME_RYAKU,
    MT.EIGYOU_TANTOU_CD AS EIGYOUSHA_CD,
    MS.SHAIN_NAME_RYAKU,
    CONVERT(varchar, TSD.SHUKKIN_YOTEI_BI, 111) AS SHUKKIN_YOTEI_BI,
    ISNULL(TSDK.KONKAI_SHIHARAI_GAKU, 0) + ISNULL(TSDK.KONKAI_SEI_UTIZEI_GAKU, 0) + ISNULL(TSDK.KONKAI_SEI_SOTOZEI_GAKU, 0) + ISNULL(TSDK.KONKAI_DEN_UTIZEI_GAKU, 0) + ISNULL(TSDK.KONKAI_DEN_SOTOZEI_GAKU, 0) + ISNULL(TSDK.KONKAI_MEI_UTIZEI_GAKU, 0) + ISNULL(TSDK.KONKAI_MEI_SOTOZEI_GAKU, 0) AS SEISAN_GAKU,
    ISNULL(TNK.SHUKKIN_GAKU, 0) AS SHUKKIN_GAKU,
    (ISNULL(TSDK.KONKAI_SHIHARAI_GAKU, 0) + ISNULL(TSDK.KONKAI_SEI_UTIZEI_GAKU, 0) + ISNULL(TSDK.KONKAI_SEI_SOTOZEI_GAKU, 0) + ISNULL(TSDK.KONKAI_DEN_UTIZEI_GAKU, 0) + ISNULL(TSDK.KONKAI_DEN_SOTOZEI_GAKU, 0) + ISNULL(TSDK.KONKAI_MEI_UTIZEI_GAKU, 0) + ISNULL(TSDK.KONKAI_MEI_SOTOZEI_GAKU, 0)) - ISNULL(TNK.SHUKKIN_GAKU, 0) AS MISHUKKIN_GAKU,
    TSD.SHIMEBI,
    CONVERT(varchar, TSD.SEISAN_DATE, 111) AS SEISAN_DATE,
    MTS.SHIHARAI_HOUHOU,
    MNK.NYUUSHUKKIN_KBN_NAME_RYAKU,
    TSD.SEISAN_NUMBER AS SEISAN_NUMBER,
    TSDK.KAGAMI_NUMBER AS KAGAMI_NUMBER,
    MT.TORIHIKISAKI_FURIGANA AS TORIHIKISAKI_FURIGANA,
    MS.SHAIN_FURIGANA AS SHAIN_FURIGANA
FROM T_SEISAN_DENPYOU AS TSD
JOIN T_SEISAN_DENPYOU_KAGAMI TSDK
    ON TSDK.SEISAN_NUMBER = TSD.SEISAN_NUMBER
	AND TSDK.DELETE_FLG = 0
LEFT JOIN M_GYOUSHA AS MGYOUSHA
    ON MGYOUSHA.GYOUSHA_CD = TSDK.GYOUSHA_CD
LEFT JOIN M_GENBA AS MGENBA
    ON MGENBA.GYOUSHA_CD = TSDK.GYOUSHA_CD
	AND MGENBA.GENBA_CD = TSDK.GENBA_CD
LEFT JOIN (SELECT
             TNK.SEISAN_NUMBER,
	         TNK.KAGAMI_NUMBER,
             SUM(TNK.KESHIKOMI_GAKU) AS SHUKKIN_GAKU
           FROM T_SHUKKIN_KESHIKOMI AS TNK
           WHERE TNK.DELETE_FLG = 0
           GROUP BY TNK.SEISAN_NUMBER, KAGAMI_NUMBER
		   ) TNK
    ON TSDK.SEISAN_NUMBER = TNK.SEISAN_NUMBER
	AND TSDK.KAGAMI_NUMBER = TNK.KAGAMI_NUMBER
JOIN M_TORIHIKISAKI AS MT
    ON MT.TORIHIKISAKI_CD = TSD.TORIHIKISAKI_CD
JOIN M_TORIHIKISAKI_SHIHARAI AS MTS
    ON MTS.TORIHIKISAKI_CD = MT.TORIHIKISAKI_CD
LEFT JOIN M_SHAIN AS MS
    ON MS.SHAIN_CD = MT.EIGYOU_TANTOU_CD
LEFT JOIN M_NYUUSHUKKIN_KBN AS MNK
    ON MNK.NYUUSHUKKIN_KBN_CD = MTS.SHIHARAI_HOUHOU
WHERE TSD.DELETE_FLG = 0
/*IF dto.KyotenCd != null && dto.KyotenCd != 99*/AND TSD.KYOTEN_CD = /*dto.KyotenCd*/99/*END*/
/*IF dto.EigyoushaCdFrom != null && dto.EigyoushaCdFrom != ''*/AND MT.EIGYOU_TANTOU_CD >= /*dto.EigyoushaCdFrom*/''/*END*/
/*IF dto.EigyoushaCdTo != null && dto.EigyoushaCdTo != ''*/AND MT.EIGYOU_TANTOU_CD <= /*dto.EigyoushaCdTo*/''/*END*/
/*IF dto.TorihikisakiCdFrom != null && dto.TorihikisakiCdFrom != ''*/AND TSD.TORIHIKISAKI_CD >= /*dto.TorihikisakiCdFrom*/''/*END*/
/*IF dto.TorihikisakiCdTo != null && dto.TorihikisakiCdTo != ''*/AND TSD.TORIHIKISAKI_CD <= /*dto.TorihikisakiCdTo*/''/*END*/
AND (ISNULL(TSDK.KONKAI_SHIHARAI_GAKU, 0) + ISNULL(TSDK.KONKAI_SEI_UTIZEI_GAKU, 0) + ISNULL(TSDK.KONKAI_SEI_SOTOZEI_GAKU, 0) + ISNULL(TSDK.KONKAI_DEN_UTIZEI_GAKU, 0) + ISNULL(TSDK.KONKAI_DEN_SOTOZEI_GAKU, 0) + ISNULL(TSDK.KONKAI_MEI_UTIZEI_GAKU, 0) + ISNULL(TSDK.KONKAI_MEI_SOTOZEI_GAKU, 0)) - ISNULL(TNK.SHUKKIN_GAKU, 0) <> 0
AND CONVERT(varchar, TSD.SHUKKIN_YOTEI_BI, 111) <= CONVERT(varchar, GETDATE(), 111)

/*IF dto.Sort2 == 1*/
ORDER BY TORIHIKISAKI_CD, GYOUSHA_CD, GENBA_CD, EIGYOUSHA_CD, SEISAN_NUMBER
/*END*/
/*IF dto.Sort2 == 2*/
ORDER BY TORIHIKISAKI_FURIGANA, TORIHIKISAKI_CD, GYOUSHA_CD, GENBA_CD, EIGYOUSHA_CD, SEISAN_NUMBER
/*END*/