SELECT
	M_HIKIAI_TORIHIKISAKI.TORIHIKISAKI_CD AS HIKIAI_TORIHIKISAKI_CD,
	NULL AS TORIHIKISAKI_CD,
	M_HIKIAI_TORIHIKISAKI.TORIHIKISAKI_CD AS DISP_TORIHIKISAKI_CD,
	M_HIKIAI_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU AS TORIHIKISAKI_NAME,
	NULL AS HIKIAI_GYOUSHA_CD,
	NULL AS GYOUSHA_CD,
	NULL AS DISP_GYOUSHA_CD,
	NULL AS GYOUSHA_NAME,
	NULL AS HIKIAI_GENBA_CD,
	NULL AS GENBA_CD,
	NULL AS DISP_GENBA_CD,
	NULL AS GENBA_NAME,
	NULL AS HIKIAI_GYOUSHA_USE_FLG
FROM
	M_HIKIAI_TORIHIKISAKI
WHERE
	1 = 1
	/*IF !dto.KyotenCd.ISNULL && dto.KyotenCd != 99*/
		AND M_HIKIAI_TORIHIKISAKI.TORIHIKISAKI_KYOTEN_CD = /*dto.KyotenCd*/
	/*END*/

UNION ALL (
SELECT
	NULL AS HIKIAI_TORIHIKISAKI_CD,
	NULL AS TORIHIKISAKI_CD,
	NULL AS DISP_TORIHIKISAKI_CD,
	NULL AS TORIHIKISAKI_NAME,
	M_HIKIAI_GYOUSHA.GYOUSHA_CD AS HIKIAI_GYOUSHA_CD,
	NULL AS GYOUSHA_CD,
	M_HIKIAI_GYOUSHA.GYOUSHA_CD AS DISP_GYOUSHA_CD,
	M_HIKIAI_GYOUSHA.GYOUSHA_NAME_RYAKU AS GYOUSHA_NAME,
	NULL AS HIKIAI_GENBA_CD,
	NULL AS GENBA_CD,
	NULL AS DISP_GENBA_CD,
	NULL AS GENBA_NAME,
	NULL AS HIKIAI_GYOUSHA_USE_FLG
FROM
	M_HIKIAI_GYOUSHA
WHERE
	1 = 1
	/*IF !dto.KyotenCd.ISNULL && dto.KyotenCd != 99*/
		AND M_HIKIAI_GYOUSHA.KYOTEN_CD = /*dto.KyotenCd*/
	/*END*/
)

UNION ALL (
SELECT
	NULL AS HIKIAI_TORIHIKISAKI_CD,
	NULL AS TORIHIKISAKI_CD,
	NULL AS DISP_TORIHIKISAKI_CD,
	NULL AS TORIHIKISAKI_NAME,
	CASE
		WHEN M_HIKIAI_GENBA.HIKIAI_GYOUSHA_USE_FLG = 1 THEN M_HIKIAI_GENBA.GYOUSHA_CD
		ELSE NULL
	END AS HIKIAI_GYOUSHA_CD,
	CASE
		WHEN M_HIKIAI_GENBA.HIKIAI_GYOUSHA_USE_FLG = 0 THEN M_HIKIAI_GENBA.GYOUSHA_CD
		ELSE NULL
	END AS GYOUSHA_CD,
	M_HIKIAI_GENBA.GYOUSHA_CD AS DISP_GYOUSHA_CD,
	CASE
		WHEN M_HIKIAI_GENBA.HIKIAI_GYOUSHA_USE_FLG = 0 THEN M_GYOUSHA.GYOUSHA_NAME_RYAKU
		ELSE M_HIKIAI_GYOUSHA.GYOUSHA_NAME_RYAKU
	END AS GYOUSHA_NAME,
	M_HIKIAI_GENBA.GENBA_CD AS HIKIAI_GENBA_CD,
	NULL AS GENBA_CD,
	M_HIKIAI_GENBA.GENBA_CD AS DISP_GENBA_CD,
	M_HIKIAI_GENBA.GENBA_NAME_RYAKU AS GENBA_NAME,
	M_HIKIAI_GENBA.HIKIAI_GYOUSHA_USE_FLG
FROM 
	M_HIKIAI_GENBA 
	LEFT JOIN M_HIKIAI_GYOUSHA
		ON M_HIKIAI_GENBA.GYOUSHA_CD = M_HIKIAI_GYOUSHA.GYOUSHA_CD
	LEFT JOIN M_GYOUSHA 
		ON M_HIKIAI_GENBA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD
WHERE
	1 = 1
	/*IF !dto.KyotenCd.ISNULL && dto.KyotenCd != 99*/
		AND M_HIKIAI_GENBA.KYOTEN_CD = /*dto.KyotenCd*/
	/*END*/
)

ORDER BY DISP_GYOUSHA_CD, DISP_GENBA_CD