SELECT
    TDSE.SYSTEM_ID,
    TDSE.SEQ,
    TDSE.SHINSEI_NUMBER,
    TDSE.SHINSEI_DATE,
    MDSN.NAIYOU_NAME,
    SHINSEISHA.SHAIN_NAME_RYAKU,
    TDSE.HIKIAI_TORIHIKISAKI_CD,
    CASE
        WHEN MHT.TORIHIKISAKI_CD_AFTER IS NOT NULL THEN MHT.TORIHIKISAKI_CD_AFTER
        ELSE TDSE.TORIHIKISAKI_CD
    END TORIHIKISAKI_CD,
    CASE
        WHEN MT.TORIHIKISAKI_NAME_RYAKU IS NOT NULL THEN MT.TORIHIKISAKI_NAME_RYAKU
        WHEN MHT.TORIHIKISAKI_CD_AFTER IS NOT NULL THEN (SELECT TORIHIKISAKI_NAME_RYAKU FROM M_TORIHIKISAKI WHERE TORIHIKISAKI_CD = MHT.TORIHIKISAKI_CD_AFTER)
        ELSE MHT.TORIHIKISAKI_NAME_RYAKU
    END TORIHIKISAKI_NAME,
    TDSE.HIKIAI_GYOUSHA_CD,
    CASE
        WHEN MHGY.GYOUSHA_CD_AFTER IS NOT NULL THEN MHGY.GYOUSHA_CD_AFTER
        ELSE TDSE.GYOUSHA_CD
    END GYOUSHA_CD,
    CASE
        WHEN MGY.GYOUSHA_NAME_RYAKU IS NOT NULL THEN MGY.GYOUSHA_NAME_RYAKU
        WHEN MHGY.GYOUSHA_CD_AFTER IS NOT NULL THEN (SELECT GYOUSHA_NAME_RYAKU FROM M_GYOUSHA WHERE GYOUSHA_CD = MHGY.GYOUSHA_CD_AFTER)
        ELSE MHGY.GYOUSHA_NAME_RYAKU
    END GYOUSHA_NAME,
    TDSE.HIKIAI_GENBA_CD,
    TDSE.GENBA_CD,
    CASE
        WHEN MGE.GENBA_NAME_RYAKU IS NOT NULL THEN MGE.GENBA_NAME_RYAKU
        ELSE TDSE.GENBA_NAME_RYAKU
    END GENBA_NAME,
    TDSS.SHINSEI_STATUS,
    CONVERT(varchar, (SELECT COUNT(*) FROM T_DENSHI_SHINSEI_DETAIL JOIN T_DENSHI_SHINSEI_DETAIL_ACTION ON T_DENSHI_SHINSEI_DETAIL.DETAIL_SYSTEM_ID = T_DENSHI_SHINSEI_DETAIL_ACTION.DETAIL_SYSTEM_ID AND T_DENSHI_SHINSEI_DETAIL_ACTION.DELETE_FLG = 0 WHERE T_DENSHI_SHINSEI_DETAIL.SYSTEM_ID = TDSE.SYSTEM_ID AND T_DENSHI_SHINSEI_DETAIL.SEQ = TDSE.SEQ)) + '/' + CONVERT(varchar, (SELECT COUNT(*) FROM T_DENSHI_SHINSEI_DETAIL WHERE SYSTEM_ID = TDSE.SYSTEM_ID AND SEQ = TDSE.SEQ)) AS PROGRESS,
    SHINSEI_MASTER_KBN,
	HIKIAI_GYOUSHA_USE_FLG
FROM
    (
		--à¯çáåªèÍà»äO
		SELECT
			SE.*
			,'' AS GENBA_NAME_RYAKU
			,'' AS HIKIAI_GYOUSHA_USE_FLG
		FROM
			T_DENSHI_SHINSEI_ENTRY SE
		WHERE
			SE.SHINSEI_MASTER_KBN NOT IN (6,7)
		UNION ALL
		--à¯çáåªèÍ(ä˘ë∂ã∆é“)
		SELECT
			SE.*
			,HGE.GENBA_NAME_RYAKU
			,HGE.HIKIAI_GYOUSHA_USE_FLG
		FROM
			T_DENSHI_SHINSEI_ENTRY SE
			INNER JOIN M_HIKIAI_GENBA HGE
				ON SE.SHINSEI_MASTER_KBN = 7
				AND SE.GYOUSHA_CD = HGE.GYOUSHA_CD
				AND SE.HIKIAI_GENBA_CD = HGE.GENBA_CD
				AND HGE.HIKIAI_GYOUSHA_USE_FLG = 0
		UNION ALL
		--à¯çáåªèÍ(ñ{ìoò^ëO à¯çáã∆é“)
		SELECT
			SE.*
			,HGE.GENBA_NAME_RYAKU
			,HGE.HIKIAI_GYOUSHA_USE_FLG
		FROM
			T_DENSHI_SHINSEI_ENTRY SE
			INNER JOIN M_HIKIAI_GYOUSHA HG
				ON SE.HIKIAI_GYOUSHA_CD = HG.GYOUSHA_CD
				AND SE.SHINSEI_MASTER_KBN = 6
				AND (HG.GYOUSHA_CD_AFTER IS NULL OR HG.GYOUSHA_CD_AFTER = '')
			INNER JOIN M_HIKIAI_GENBA HGE
				ON SE.HIKIAI_GYOUSHA_CD = HGE.GYOUSHA_CD
				AND SE.HIKIAI_GENBA_CD = HGE.GENBA_CD
				AND HGE.HIKIAI_GYOUSHA_USE_FLG = 1
		UNION ALL
		--à¯çáåªèÍ(ñ{ìoò^å„ à¯çáã∆é“)
		SELECT
			SE.*
			,HGE.GENBA_NAME_RYAKU
			,HGE.HIKIAI_GYOUSHA_USE_FLG
		FROM
			T_DENSHI_SHINSEI_ENTRY SE
			INNER JOIN M_HIKIAI_GYOUSHA HG
				ON SE.HIKIAI_GYOUSHA_CD = HG.GYOUSHA_CD
				AND SE.SHINSEI_MASTER_KBN = 6
				AND (HG.GYOUSHA_CD_AFTER IS NOT NULL AND HG.GYOUSHA_CD_AFTER <> '')
			INNER JOIN M_HIKIAI_GENBA HGE
				ON HG.GYOUSHA_CD_AFTER = HGE.GYOUSHA_CD
				AND SE.HIKIAI_GENBA_CD = HGE.GENBA_CD
				AND HGE.HIKIAI_GYOUSHA_USE_FLG = 0
	) AS TDSE
    INNER JOIN
        (
            SELECT DISTINCT
                TDSD.SYSTEM_ID,
                TDSD.SEQ,
                TDSD.SHINSEI_NUMBER
            FROM
                T_DENSHI_SHINSEI_DETAIL AS TDSD
                LEFT JOIN
                    T_DENSHI_SHINSEI_DETAIL_ACTION AS TDSDA
                ON  TDSD.DETAIL_SYSTEM_ID = TDSDA.DETAIL_SYSTEM_ID
                AND TDSDA.DELETE_FLG = 0
        ) AS TDSD
    ON  TDSE.SYSTEM_ID = TDSD.SYSTEM_ID
    AND TDSE.SEQ = TDSD.SEQ
    LEFT JOIN
        T_DENSHI_SHINSEI_STATUS AS TDSS
    ON TDSE.SYSTEM_ID = TDSS.SYSTEM_ID
    AND TDSE.SEQ = TDSS.SEQ
    AND TDSS.DELETE_FLG = 0
    LEFT JOIN
        M_DENSHI_SHINSEI_NAIYOU AS MDSN
    ON  TDSE.NAIYOU_CD = MDSN.NAIYOU_CD
    LEFT JOIN
        M_TORIHIKISAKI AS MT
    ON  TDSE.TORIHIKISAKI_CD = MT.TORIHIKISAKI_CD
    LEFT JOIN
        M_GYOUSHA AS MGY
    ON  TDSE.GYOUSHA_CD = MGY.GYOUSHA_CD
    LEFT JOIN
        M_GENBA AS MGE
    ON  TDSE.GYOUSHA_CD = MGE.GYOUSHA_CD
    AND TDSE.GENBA_CD = MGE.GENBA_CD
    LEFT JOIN
        M_HIKIAI_TORIHIKISAKI AS MHT
    ON  TDSE.HIKIAI_TORIHIKISAKI_CD = MHT.TORIHIKISAKI_CD
    LEFT JOIN
        M_HIKIAI_GYOUSHA AS MHGY
    ON  TDSE.HIKIAI_GYOUSHA_CD = MHGY.GYOUSHA_CD
    LEFT JOIN
        M_SHAIN AS SHINSEISHA
    ON  TDSE.SHINSEISHA_CD = SHINSEISHA.SHAIN_CD
WHERE
    TDSE.DELETE_FLG = 0
/*IF dto.ShainCd != null && dto.ShainCd != ''*/
    AND TDSE.SHINSEISHA_CD = /*dto.ShainCd*/'000001'
/*END*/
    AND TDSS.SHINSEI_STATUS_CD = /*dto.ShinseiStatus*/0
/*IF !dto.ShinseiDateFrom.IsNull*/
    AND TDSE.SHINSEI_DATE >= CONVERT(datetime, /*dto.ShinseiDateFrom*/'2014/01/01')
/*END*/
/*IF !dto.ShinseiDateTo.IsNull*/
    AND TDSE.SHINSEI_DATE <= CONVERT(datetime, /*dto.ShinseiDateTo*/'2014/12/31')
/*END*/
/*IF dto.KyotenCd != null && dto.KyotenCd != '' && dto.KyotenCd != '99'*/
    AND TDSE.KYOTEN_CD = CONVERT(int, /*dto.KyotenCd*/0)
/*END*/
