SELECT
    CHI.CHIIKI_CD,
	CHI.CHIIKI_NAME
FROM
    dbo.M_CHIIKI CHI
/*BEGIN*/WHERE
    /*IF data.CHIIKI_NAME != null*/CHI.CHIIKI_NAME LIKE '%' +  /*data.CHIIKI_NAME*/ + '%'/*END*/
/*END*/
AND(CHI.DELETE_FLG = 0)
ORDER BY CHI.CHIIKI_CD