SELECT * FROM dbo.M_HIKIAI_GENBA
WHERE 
DELETE_FLG = 0
/*IF data.GYOUSHA_CD != null*/AND GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/
/*IF data.GENBA_CD != null*/AND GENBA_CD = /*data.GENBA_CD*//*END*/
/*IF data.TORIHIKISAKI_CD != null*/AND TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*//*END*/
/*IF !data.KYOTEN_CD.IsNull*/AND KYOTEN_CD = /*data.KYOTEN_CD.Value*//*END*/
/*IF data.GENBA_NAME1 != null*/AND GENBA_NAME1 = /*data.GENBA_NAME1*//*END*/
/*IF data.GENBA_NAME2 != null*/AND GENBA_NAME2 = /*data.GENBA_NAME2*//*END*/
/*IF data.GENBA_NAME_RYAKU != null*/AND GENBA_NAME_RYAKU = /*data.GENBA_NAME_RYAKU*//*END*/
/*IF data.GENBA_FURIGANA != null*/AND GENBA_FURIGANA = /*data.GENBA_FURIGANA*//*END*/
/*IF data.GENBA_TEL != null*/AND GENBA_TEL = /*data.GENBA_TEL*//*END*/
/*IF data.GENBA_FAX != null*/AND GENBA_FAX = /*data.GENBA_FAX*//*END*/
/*IF data.GENBA_KEITAI_TEL != null*/AND GENBA_KEITAI_TEL = /*data.GENBA_KEITAI_TEL*//*END*/
/*IF data.GENBA_KEISHOU1 != null*/AND GENBA_KEISHOU1 = /*data.GENBA_KEISHOU1*//*END*/
/*IF data.GENBA_KEISHOU2 != null*/AND GENBA_KEISHOU2 = /*data.GENBA_KEISHOU2*//*END*/
/*IF data.EIGYOU_TANTOU_BUSHO_CD != null*/AND EIGYOU_TANTOU_BUSHO_CD = /*data.EIGYOU_TANTOU_BUSHO_CD*//*END*/
/*IF data.EIGYOU_TANTOU_CD != null*/AND EIGYOU_TANTOU_CD = /*data.EIGYOU_TANTOU_CD*//*END*/
/*IF data.GENBA_POST != null*/AND GENBA_POST = /*data.GENBA_POST*//*END*/
/*IF !data.GENBA_TODOUFUKEN_CD.IsNull*/AND GENBA_TODOUFUKEN_CD = /*data.GENBA_TODOUFUKEN_CD.Value*//*END*/
/*IF data.GENBA_ADDRESS1 != null*/AND GENBA_ADDRESS1 = /*data.GENBA_ADDRESS1*//*END*/
/*IF data.GENBA_ADDRESS2 != null*/AND GENBA_ADDRESS2 = /*data.GENBA_ADDRESS2*//*END*/
/*IF !data.TORIHIKI_JOUKYOU.IsNull*/AND TORIHIKI_JOUKYOU = /*data.TORIHIKI_JOUKYOU.Value*//*END*/
/*IF data.CHUUSHI_RIYUU1 != null*/AND CHUUSHI_RIYUU1 = /*data.CHUUSHI_RIYUU1*//*END*/
/*IF data.CHUUSHI_RIYUU2 != null*/AND CHUUSHI_RIYUU2 = /*data.CHUUSHI_RIYUU2*//*END*/
/*IF data.BUSHO != null*/AND BUSHO = /*data.BUSHO*//*END*/
/*IF data.TANTOUSHA != null*/AND TANTOUSHA = /*data.TANTOUSHA*//*END*/
/*IF data.KOUFU_TANTOUSHA != null*/AND KOUFU_TANTOUSHA = /*data.KOUFU_TANTOUSHA*//*END*/
/*IF data.SHUUKEI_ITEM_CD != null*/AND SHUUKEI_ITEM_CD = /*data.SHUUKEI_ITEM_CD*//*END*/
/*IF data.GYOUSHU_CD != null*/AND GYOUSHU_CD = /*data.GYOUSHU_CD*//*END*/
/*IF data.CHIIKI_CD != null*/AND CHIIKI_CD = /*data.CHIIKI_CD*//*END*/
/*IF data.BIKOU1 != null*/AND BIKOU1 = /*data.BIKOU1*//*END*/
/*IF data.BIKOU2 != null*/AND BIKOU2 = /*data.BIKOU2*//*END*/
/*IF data.BIKOU3 != null*/AND BIKOU3 = /*data.BIKOU3*//*END*/
/*IF data.BIKOU4 != null*/AND BIKOU4 = /*data.BIKOU4*//*END*/
/*IF data.SEIKYUU_SOUFU_NAME1 != null*/AND SEIKYUU_SOUFU_NAME1 = /*data.SEIKYUU_SOUFU_NAME1*//*END*/
/*IF data.SEIKYUU_SOUFU_NAME2 != null*/AND SEIKYUU_SOUFU_NAME2 = /*data.SEIKYUU_SOUFU_NAME2*//*END*/
/*IF data.SEIKYUU_SOUFU_KEISHOU1 != null*/AND SEIKYUU_SOUFU_KEISHOU1 = /*data.SEIKYUU_SOUFU_KEISHOU1*//*END*/
/*IF data.SEIKYUU_SOUFU_KEISHOU2 != null*/AND SEIKYUU_SOUFU_KEISHOU2 = /*data.SEIKYUU_SOUFU_KEISHOU2*//*END*/
/*IF data.SEIKYUU_SOUFU_POST != null*/AND SEIKYUU_SOUFU_POST = /*data.SEIKYUU_SOUFU_POST*//*END*/
/*IF data.SEIKYUU_SOUFU_ADDRESS1 != null*/AND SEIKYUU_SOUFU_ADDRESS1 = /*data.SEIKYUU_SOUFU_ADDRESS1*//*END*/
/*IF data.SEIKYUU_SOUFU_ADDRESS2 != null*/AND SEIKYUU_SOUFU_ADDRESS2 = /*data.SEIKYUU_SOUFU_ADDRESS2*//*END*/
/*IF data.SEIKYUU_SOUFU_BUSHO != null*/AND SEIKYUU_SOUFU_BUSHO = /*data.SEIKYUU_SOUFU_BUSHO*//*END*/
/*IF data.SEIKYUU_SOUFU_TANTOU != null*/AND SEIKYUU_SOUFU_TANTOU = /*data.SEIKYUU_SOUFU_TANTOU*//*END*/
/*IF data.SEIKYUU_SOUFU_TEL != null*/AND SEIKYUU_SOUFU_TEL = /*data.SEIKYUU_SOUFU_TEL*//*END*/
/*IF data.SEIKYUU_SOUFU_FAX != null*/AND SEIKYUU_SOUFU_FAX = /*data.SEIKYUU_SOUFU_FAX*//*END*/
/*IF data.SEIKYUU_TANTOU != null*/AND SEIKYUU_TANTOU = /*data.SEIKYUU_TANTOU*//*END*/
/*IF !data.SEIKYUU_DAIHYOU_PRINT_KBN.IsNull*/AND SEIKYUU_DAIHYOU_PRINT_KBN = /*data.SEIKYUU_DAIHYOU_PRINT_KBN.Value*//*END*/
/*IF data.SHIHARAI_SOUFU_NAME1 != null*/AND SHIHARAI_SOUFU_NAME1 = /*data.SHIHARAI_SOUFU_NAME1*//*END*/
/*IF data.SHIHARAI_SOUFU_NAME2 != null*/AND SHIHARAI_SOUFU_NAME2 = /*data.SHIHARAI_SOUFU_NAME2*//*END*/
/*IF data.SHIHARAI_SOUFU_KEISHOU1 != null*/AND SHIHARAI_SOUFU_KEISHOU1 = /*data.SHIHARAI_SOUFU_KEISHOU1*//*END*/
/*IF data.SHIHARAI_SOUFU_KEISHOU2 != null*/AND SHIHARAI_SOUFU_KEISHOU2 = /*data.SHIHARAI_SOUFU_KEISHOU2*//*END*/
/*IF data.SHIHARAI_SOUFU_POST != null*/AND SHIHARAI_SOUFU_POST = /*data.SHIHARAI_SOUFU_POST*//*END*/
/*IF data.SHIHARAI_SOUFU_ADDRESS1 != null*/AND SHIHARAI_SOUFU_ADDRESS1 = /*data.SHIHARAI_SOUFU_ADDRESS1*//*END*/
/*IF data.SHIHARAI_SOUFU_ADDRESS2 != null*/AND SHIHARAI_SOUFU_ADDRESS2 = /*data.SHIHARAI_SOUFU_ADDRESS2*//*END*/
/*IF data.SHIHARAI_SOUFU_BUSHO != null*/AND SHIHARAI_SOUFU_BUSHO = /*data.SHIHARAI_SOUFU_BUSHO*//*END*/
/*IF data.SHIHARAI_SOUFU_TANTOU != null*/AND SHIHARAI_SOUFU_TANTOU = /*data.SHIHARAI_SOUFU_TANTOU*//*END*/
/*IF data.SHIHARAI_SOUFU_TEL != null*/AND SHIHARAI_SOUFU_TEL = /*data.SHIHARAI_SOUFU_TEL*//*END*/
/*IF data.SHIHARAI_SOUFU_FAX != null*/AND SHIHARAI_SOUFU_FAX = /*data.SHIHARAI_SOUFU_FAX*//*END*/
/*IF !data.JISHA_KBN.IsNull*/ AND JISHA_KBN = /*data.JISHA_KBN*//*END*/
/*IF !data.HAISHUTSU_NIZUMI_GENBA_KBN.IsNull*/ AND HAISHUTSU_NIZUMI_GENBA_KBN = /*data.HAISHUTSU_NIZUMI_GENBA_KBN*//*END*/
/*IF !data.TSUMIKAEHOKAN_KBN.IsNull*/ AND TSUMIKAEHOKAN_KBN = /*data.TSUMIKAEHOKAN_KBN*//*END*/
/*IF !data.SHOBUN_NIOROSHI_GENBA_KBN.IsNull*/ AND SHOBUN_NIOROSHI_GENBA_KBN = /*data.SHOBUN_NIOROSHI_GENBA_KBN*//*END*/
/*IF !data.SAISHUU_SHOBUNJOU_KBN.IsNull*/ AND SAISHUU_SHOBUNJOU_KBN = /*data.SAISHUU_SHOBUNJOU_KBN*//*END*/
/*IF !data.MANI_HENSOUSAKI_KBN.IsNull*/ AND MANI_HENSOUSAKI_KBN = /*data.MANI_HENSOUSAKI_KBN*//*END*/
/*IF !data.MANIFEST_SHURUI_CD.IsNull*/AND MANIFEST_SHURUI_CD = /*data.MANIFEST_SHURUI_CD.Value*//*END*/
/*IF !data.MANIFEST_TEHAI_CD.IsNull*/AND MANIFEST_TEHAI_CD = /*data.MANIFEST_TEHAI_CD.Value*//*END*/
/*IF data.SHOBUNSAKI_NO != null*/AND SHOBUNSAKI_NO = /*data.SHOBUNSAKI_NO*//*END*/
/*IF !data.SHOKUCHI_KBN.IsNull*/ AND SHOKUCHI_KBN = /*data.SHOKUCHI_KBN*//*END*/
/*IF !data.DEN_MANI_SHOUKAI_KBN.IsNull*/ AND DEN_MANI_SHOUKAI_KBN = /*data.DEN_MANI_SHOUKAI_KBN*//*END*/
/*IF !data.ITAKU_KEIYAKU_USE_KBN.IsNull*/AND ITAKU_KEIYAKU_USE_KBN = /*data.ITAKU_KEIYAKU_USE_KBN.Value*//*END*/
/*IF data.MANI_HENSOUSAKI_NAME1 != null*/AND MANI_HENSOUSAKI_NAME1 = /*data.MANI_HENSOUSAKI_NAME1*//*END*/
/*IF data.MANI_HENSOUSAKI_NAME2 != null*/AND MANI_HENSOUSAKI_NAME2 = /*data.MANI_HENSOUSAKI_NAME2*//*END*/
/*IF data.MANI_HENSOUSAKI_KEISHOU1 != null*/AND MANI_HENSOUSAKI_KEISHOU1 = /*data.MANI_HENSOUSAKI_KEISHOU1*//*END*/
/*IF data.MANI_HENSOUSAKI_KEISHOU2 != null*/AND MANI_HENSOUSAKI_KEISHOU2 = /*data.MANI_HENSOUSAKI_KEISHOU2*//*END*/
/*IF data.MANI_HENSOUSAKI_POST != null*/AND MANI_HENSOUSAKI_POST = /*data.MANI_HENSOUSAKI_POST*//*END*/
/*IF data.MANI_HENSOUSAKI_ADDRESS1 != null*/AND MANI_HENSOUSAKI_ADDRESS1 = /*data.MANI_HENSOUSAKI_ADDRESS1*//*END*/
/*IF data.MANI_HENSOUSAKI_ADDRESS2 != null*/AND MANI_HENSOUSAKI_ADDRESS2 = /*data.MANI_HENSOUSAKI_ADDRESS2*//*END*/
/*IF data.MANI_HENSOUSAKI_BUSHO != null*/AND MANI_HENSOUSAKI_BUSHO = /*data.MANI_HENSOUSAKI_BUSHO*//*END*/
/*IF data.MANI_HENSOUSAKI_TANTOU != null*/AND MANI_HENSOUSAKI_TANTOU = /*data.MANI_HENSOUSAKI_TANTOU*//*END*/
/*IF !data.TEKIYOU_BEGIN.IsNull*/AND TEKIYOU_BEGIN = /*data.TEKIYOU_BEGIN.Value*//*END*/
/*IF !data.TEKIYOU_END.IsNull*/AND TEKIYOU_END = /*data.TEKIYOU_END.Value*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
/*IF data.UNTENSHA_SHIJI_JIKOU1 != null*/AND UNTENSHA_SHIJI_JIKOU1 = /*data.UNTENSHA_SHIJI_JIKOU1*//*END*/
/*IF data.UNTENSHA_SHIJI_JIKOU2 != null*/AND UNTENSHA_SHIJI_JIKOU2 = /*data.UNTENSHA_SHIJI_JIKOU2*//*END*/
/*IF data.UNTENSHA_SHIJI_JIKOU3 != null*/AND UNTENSHA_SHIJI_JIKOU3 = /*data.UNTENSHA_SHIJI_JIKOU3*//*END*/
/*IF data.HAKKOUSAKI_CD != null*/AND HAKKOUSAKI_CD = /*data.HAKKOUSAKI_CD*//*END*/
