SELECT 
 ISNULL(MIN(GE.GENBA_CD), 1) GENBA_CD
FROM 
 (
  SELECT (GENBA_CD + 1) GENBA_CD FROM M_HIKIAI_GENBA WHERE GYOUSHA_CD = /*gyoushaCd*/ AND ISNUMERIC(GENBA_CD) = 1 AND HIKIAI_GYOUSHA_USE_FLG = /*hikiaiFlg*/
 ) GE
WHERE GE.GENBA_CD NOT IN
 (
  SELECT (GENBA_CD + 0) GENBA_CD FROM M_HIKIAI_GENBA WHERE GYOUSHA_CD = /*gyoushaCd*/ AND ISNUMERIC(GENBA_CD) = 1 AND HIKIAI_GYOUSHA_USE_FLG = /*hikiaiFlg*/
 )