SELECT
    BU.BUSHO_CD AS BUSHO_CD,
    BU.BUSHO_NAME_RYAKU AS BUSHO_NAME,
	SHA.SHAIN_CD AS SHAIN_CD,
	SHA.SHAIN_NAME_RYAKU AS SHAIN_NAME
FROM
    dbo.M_SHAIN SHA
LEFT JOIN
    dbo.M_BUSHO BU ON SHA.BUSHO_CD = BU.BUSHO_CD
/*BEGIN*/WHERE
    /*IF data.SHAIN_CD != null*/SHA.SHAIN_CD = /*data.SHAIN_CD*/'000001'/*END*/
    /*IF data.BUSHO_CD != null*/AND SHA.BUSHO_CD = /*data.BUSHO_CD*/'001'/*END*/
/*END*/
AND SHA.EIGYOU_TANTOU_KBN = 1
AND(BU.DELETE_FLG = 0)
AND(SHA.DELETE_FLG = 0)
ORDER BY BU.BUSHO_CD,SHA.SHAIN_CD
