UPDATE T_MITSUMORI_ENTRY 
SET GENBA_CD = /*newGENBA_CD*/0
, HIKIAI_GENBA_FLG = 0
WHERE 
 GYOUSHA_CD = /*oldGYOUSHA_CD*/0
 AND GENBA_CD =  /*oldGENBA_CD*/0
 AND HIKIAI_GYOUSHA_FLG = 0
 AND HIKIAI_GENBA_FLG = 1
