SELECT 
 TORIHIKISAKI_KYOTEN_CD,
 TORIHIKISAKI_CD,
 TORIHIKISAKI_NAME1,
 TORIHIKISAKI_NAME2,
 TEKIYOU_BEGIN,
 TEKIYOU_END 
FROM dbo.M_HIKIAI_TORIHIKISAKI
WHERE 
DELETE_FLG = 0
/*IF data.TORIHIKISAKI_CD != null*/AND TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*//*END*/
/*IF !data.TORIHIKISAKI_KYOTEN_CD.IsNull*/AND TORIHIKISAKI_KYOTEN_CD = /*data.TORIHIKISAKI_KYOTEN_CD.Value*//*END*/
/*IF data.TORIHIKISAKI_NAME1 != null*/AND TORIHIKISAKI_NAME1 = /*data.TORIHIKISAKI_NAME1*//*END*/
/*IF data.TORIHIKISAKI_NAME2 != null*/AND TORIHIKISAKI_NAME2 = /*data.TORIHIKISAKI_NAME2*//*END*/
/*IF data.TORIHIKISAKI_NAME_RYAKU != null*/AND TORIHIKISAKI_NAME_RYAKU = /*data.TORIHIKISAKI_NAME_RYAKU*//*END*/
/*IF data.TORIHIKISAKI_FURIGANA != null*/AND TORIHIKISAKI_FURIGANA = /*data.TORIHIKISAKI_FURIGANA*//*END*/
/*IF data.TORIHIKISAKI_TEL != null*/AND TORIHIKISAKI_TEL = /*data.TORIHIKISAKI_TEL*//*END*/
/*IF data.TORIHIKISAKI_FAX != null*/AND TORIHIKISAKI_FAX = /*data.TORIHIKISAKI_FAX*//*END*/
/*IF data.EIGYOU_TANTOU_BUSHO_CD != null*/AND EIGYOU_TANTOU_BUSHO_CD = /*data.EIGYOU_TANTOU_BUSHO_CD*//*END*/
/*IF data.EIGYOU_TANTOU_CD != null*/AND EIGYOU_TANTOU_CD = /*data.EIGYOU_TANTOU_CD*//*END*/
/*IF data.TORIHIKISAKI_POST != null*/AND TORIHIKISAKI_POST = /*data.TORIHIKISAKI_POST*//*END*/
/*IF !data.TORIHIKISAKI_TODOUFUKEN_CD.IsNull*/AND TORIHIKISAKI_TODOUFUKEN_CD = /*data.TORIHIKISAKI_TODOUFUKEN_CD.Value*//*END*/
/*IF data.TORIHIKISAKI_ADDRESS1 != null*/AND TORIHIKISAKI_ADDRESS1 = /*data.TORIHIKISAKI_ADDRESS1*//*END*/
/*IF data.TORIHIKISAKI_ADDRESS2 != null*/AND TORIHIKISAKI_ADDRESS2 = /*data.TORIHIKISAKI_ADDRESS2*//*END*/
/*IF !data.TORIHIKI_JOUKYOU.IsNull*/AND TORIHIKI_JOUKYOU = /*data.TORIHIKI_JOUKYOU.Value*//*END*/
/*IF data.CHUUSHI_RIYUU1 != null*/AND CHUUSHI_RIYUU1 = /*data.CHUUSHI_RIYUU1*//*END*/
/*IF data.CHUUSHI_RIYUU2 != null*/AND CHUUSHI_RIYUU2 = /*data.CHUUSHI_RIYUU2*//*END*/
/*IF data.BUSHO != null*/AND BUSHO = /*data.BUSHO*//*END*/
/*IF data.TANTOUSHA != null*/AND TANTOUSHA = /*data.TANTOUSHA*//*END*/
/*IF data.SHUUKEI_ITEM_CD != null*/AND SHUUKEI_ITEM_CD = /*data.SHUUKEI_ITEM_CD*//*END*/
/*IF data.GYOUSHU_CD != null*/AND GYOUSHU_CD = /*data.GYOUSHU_CD*//*END*/
/*IF data.BIKOU1 != null*/AND BIKOU1 = /*data.BIKOU1*//*END*/
/*IF data.BIKOU2 != null*/AND BIKOU2 = /*data.BIKOU2*//*END*/
/*IF data.BIKOU3 != null*/AND BIKOU3 = /*data.BIKOU3*//*END*/
/*IF data.BIKOU4 != null*/AND BIKOU4 = /*data.BIKOU4*//*END*/
/*IF !data.NYUUKINSAKI_KBN.IsNull*/AND NYUUKINSAKI_KBN = /*data.NYUUKINSAKI_KBN.Value*//*END*/
/*IF !data.MANI_HENSOUSAKI_KBN.IsNull*/ AND MANI_HENSOUSAKI_KBN = /*data.MANI_HENSOUSAKI_KBN*//*END*/
/*IF !data.SHOKUCHI_KBN.IsNull*/ AND SHOKUCHI_KBN = /*data.SHOKUCHI_KBN*//*END*/
/*IF !data.TEKIYOU_BEGIN.IsNull*/AND TEKIYOU_BEGIN = /*data.TEKIYOU_BEGIN.Value*//*END*/
/*IF !data.TEKIYOU_END.IsNull*/AND TEKIYOU_END = /*data.TEKIYOU_END.Value*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
