SELECT ISNULL(MIN(GY.GYOUSHA_CD),1) GYOUSHA_CD
FROM 
	(
		SELECT (GYOUSHA_CD+1) GYOUSHA_CD FROM M_HIKIAI_GYOUSHA WHERE ISNUMERIC(GYOUSHA_CD)=1 
	) GY
WHERE GY.GYOUSHA_CD NOT IN (
		SELECT (GYOUSHA_CD+0) GYOUSHA_CD FROM M_HIKIAI_GYOUSHA WHERE ISNUMERIC(GYOUSHA_CD)=1
	)