SELECT * FROM dbo.M_DENSHI_JIGYOUJOU
/*BEGIN*/WHERE 
/*IF data.EDI_MEMBER_ID != null*/AND EDI_MEMBER_ID = /*data.EDI_MEMBER_ID*//*END*/
/*IF data.JIGYOUJOU_CD != null*/AND JIGYOUJOU_CD = /*data.JIGYOUJOU_CD*//*END*/
/*IF data.JWNET_JIGYOUJOU_CD != null*/AND JWNET_JIGYOUJOU_CD = /*data.JWNET_JIGYOUJOU_CD*//*END*/
/*IF !data.JIGYOUSHA_KBN.IsNull*/AND JIGYOUSHA_KBN = /*data.JIGYOUSHA_NAME*//*END*/
/*IF !data.JIGYOUJOU_KBN.IsNull*/AND JIGYOUJOU_KBN = /*data.JIGYOUSHA_POST*//*END*/
/*IF data.JIGYOUJOU_NAME != null*/AND JIGYOUJOU_NAME = /*data.JIGYOUSHA_ADDRESS1*//*END*/
/*IF data.JIGYOUJOU_POST != null*/AND JIGYOUJOU_POST = /*data.JIGYOUSHA_ADDRESS2*//*END*/
/*IF data.JIGYOUJOU_ADDRESS1 != null*/AND JIGYOUJOU_ADDRESS1 = /*data.JIGYOUSHA_ADDRESS3*//*END*/
/*IF data.JIGYOUJOU_ADDRESS2 != null*/AND JIGYOUJOU_ADDRESS2 = /*data.JIGYOUSHA_ADDRESS4*//*END*/
/*IF data.JIGYOUJOU_ADDRESS3 != null*/AND JIGYOUJOU_ADDRESS3 = /*data.JIGYOUSHA_TEL*//*END*/
/*IF data.JIGYOUJOU_ADDRESS4 != null*/AND JIGYOUJOU_ADDRESS4 = /*data.JIGYOUSHA_FAX*//*END*/
/*IF data.JIGYOUJOU_TEL != null*/AND JIGYOUJOU_TEL = /*data.HST_KBN*//*END*/
/*IF data.GYOUSHA_CD != null*/AND GYOUSHA_CD = /*data.UPN_KBN*//*END*/
/*IF data.GENBA_CD != null*/AND GENBA_CD = /*data.SBN_KBN*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.HOUKOKU_HUYOU_KBN*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.GYOUSHA_CD*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_USER*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.CREATE_DATE*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_USER*//*END*/
/*IF data.TIME_STAMP != null*/AND TIME_STAMP = /*data.UPDATE_DATE*//*END*/
/*END*/