SELECT
DENPYOU.TORIHIKISAKI_CD --請求先CD
,TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU --請求先名
,CASE DENPYOU.SEIKYUU_KEITAI_KBN
    WHEN 1 THEN NULL 
    ELSE DENPYOU.ZENKAI_KURIKOSI_GAKU
 END AS ZENKAI_KURIKOSI_GAKU --前回請求額
,CASE DENPYOU.SEIKYUU_KEITAI_KBN
    WHEN 1 THEN NULL
    ELSE DENPYOU.KONKAI_NYUUKIN_GAKU
 END AS KONKAI_NYUUKIN_GAKU --入金額
,CASE DENPYOU.SEIKYUU_KEITAI_KBN
    WHEN 1 THEN NULL
    ELSE DENPYOU.KONKAI_CHOUSEI_GAKU
 END AS KONKAI_CHOUSEI_GAKU --調整額
--ZENKAI_KURIKOSI_GAKU（前回繰越額）－KONKAI_NYUUKIN_GAKU（今回入金額）－KONKAI_CHOUSEI_GAKU（今回調整額）
,CASE DENPYOU.SEIKYUU_KEITAI_KBN 
    WHEN 1 THEN NULL
    ELSE (ISNULL(DENPYOU.ZENKAI_KURIKOSI_GAKU,0) 
	    - ISNULL(DENPYOU.KONKAI_NYUUKIN_GAKU,0) 
	    - ISNULL(DENPYOU.KONKAI_CHOUSEI_GAKU,0))
 END AS KURIKOSHI_GAKU --繰越額
,DENPYOU.SHIMEBI --締日
,DENPYOU.KONKAI_URIAGE_GAKU --今回取引額(税抜）
--　KONKAI_SEI_UTIZEI_GAKU（今回請内税額）＋KONKAI_SEI_SOTOZEI_GAKU（今回請外税額）
--　＋KONKAI_DEN_UTIZEI_GAKU（今回伝内税額）＋KONKAI_DEN_SOTOZEI_GAKU（今回伝外税額）
--  ＋KONKAI_MEI_UTIZEI_GAKU（今回明内税額）＋KONKAI_MEI_SOTOZEI_GAKU（今回明外税額）
,(ISNULL(DENPYOU.KONKAI_SEI_UTIZEI_GAKU,0) 
	+ ISNULL(DENPYOU.KONKAI_SEI_SOTOZEI_GAKU,0)  
	+ ISNULL(DENPYOU.KONKAI_DEN_UTIZEI_GAKU,0)  
	+ ISNULL(DENPYOU.KONKAI_DEN_SOTOZEI_GAKU,0)  
	+ ISNULL(DENPYOU.KONKAI_MEI_UTIZEI_GAKU,0) 
	+ ISNULL(DENPYOU.KONKAI_MEI_SOTOZEI_GAKU,0))AS SHOUHIZEI --消費税
,CASE DENPYOU.SEIKYUU_KEITAI_KBN
    WHEN 1 THEN (ISNULL(KONKAI_URIAGE_GAKU,0) 
        + ISNULL(KONKAI_SEI_UTIZEI_GAKU,0) 
        + ISNULL (KONKAI_SEI_SOTOZEI_GAKU,0) 
        + ISNULL(KONKAI_DEN_UTIZEI_GAKU,0) 
        + ISNULL(KONKAI_DEN_SOTOZEI_GAKU,0) 
        + ISNULL(KONKAI_MEI_UTIZEI_GAKU,0) 
        + ISNULL(KONKAI_MEI_SOTOZEI_GAKU,0))
    ELSE DENPYOU.KONKAI_SEIKYU_GAKU --今回御請求額
 END AS KONKAI_SEIKYU_GAKU
,DENPYOU.NYUUKIN_YOTEI_BI --入金予定日
,DENPYOU.SEIKYUU_DATE --請求年月日
,DENPYOU.SEIKYUU_KEITAI_KBN
FROM 
T_SEIKYUU_DENPYOU AS DENPYOU
INNER JOIN M_TORIHIKISAKI AS TORIHIKISAKI ON TORIHIKISAKI.TORIHIKISAKI_CD = DENPYOU.TORIHIKISAKI_CD 
WHERE DENPYOU.DELETE_FLG = 0
/*IF !data.HIDUKE_FROM.IsNull*/ AND DENPYOU.SEIKYUU_DATE >= /*data.HIDUKE_FROM*//*END*/
/*IF !data.HIDUKE_TO.IsNull*/ AND DENPYOU.SEIKYUU_DATE <= /*data.HIDUKE_TO*//*END*/
/*IF data.TORIHIKISAKI_CD_FROM !='' */ AND DENPYOU.TORIHIKISAKI_CD >= /*data.TORIHIKISAKI_CD_FROM*//*END*/
/*IF data.TORIHIKISAKI_CD_TO !='' */ AND DENPYOU.TORIHIKISAKI_CD <= /*data.TORIHIKISAKI_CD_TO*//*END*/
/*IF !data.KYOTEN_CD.IsNull*/ AND (DENPYOU.KYOTEN_CD = /*data.KYOTEN_CD*/ OR /*data.KYOTEN_CD*/ = 99) /*END*/
/*IF !data.TORIHIKISAKI_SORT.IsNull && data.TORIHIKISAKI_SORT == '1'*/ ORDER BY TORIHIKISAKI.TORIHIKISAKI_FURIGANA, DENPYOU.TORIHIKISAKI_CD, DENPYOU.SEIKYUU_DATE ASC /*END*/
/*IF !data.TORIHIKISAKI_SORT.IsNull && data.TORIHIKISAKI_SORT == '2'*/ ORDER BY DENPYOU.TORIHIKISAKI_CD ASC /*END*/

