SELECT 
M_GENBA.GYOUSHA_CD, 
M_GYOUSHA.GYOUSHA_NAME_RYAKU, 
M_GENBA.GENBA_CD, 
M_GENBA.GENBA_NAME_RYAKU, 
M_GENBA.GENBA_FURIGANA, 
M_GENBA.GENBA_POST, 
M_GENBA.GENBA_ADDRESS1, 
M_GENBA.GENBA_TEL, 
M_GYOUSHA.SHOBUN_NIOROSHI_GYOUSHA_KBN, 
M_GENBA.SHOBUN_NIOROSHI_GENBA_KBN, 
M_GENBA.SAISHUU_SHOBUNJOU_KBN, 
M_GENBA.HAISHUTSU_NIZUMI_GENBA_KBN, 
M_GENBA.TSUMIKAEHOKAN_KBN 
FROM M_GENBA 
LEFT JOIN dbo.M_GYOUSHA AS M_GYOUSHA ON M_GENBA.GYOUSHA_CD = M_GYOUSHA.GYOUSHA_CD 

