//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipCodeHoshu.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LIST_POST3_TEXT {
            get {
                return ((string)(this["LIST_POST3_TEXT"]));
            }
            set {
                this["LIST_POST3_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LIST_POST7_TEXT {
            get {
                return ((string)(this["LIST_POST7_TEXT"]));
            }
            set {
                this["LIST_POST7_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KOBETSU_POST7_OLD_TEXT {
            get {
                return ((string)(this["KOBETSU_POST7_OLD_TEXT"]));
            }
            set {
                this["KOBETSU_POST7_OLD_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KOBETSU_SIKUCHOUSON_OLD_TEXT {
            get {
                return ((string)(this["KOBETSU_SIKUCHOUSON_OLD_TEXT"]));
            }
            set {
                this["KOBETSU_SIKUCHOUSON_OLD_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KOBETSU_POST7_NEW_TEXT {
            get {
                return ((string)(this["KOBETSU_POST7_NEW_TEXT"]));
            }
            set {
                this["KOBETSU_POST7_NEW_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KOBETSU_SIKUCHOUSON_NEW_TEXT {
            get {
                return ((string)(this["KOBETSU_SIKUCHOUSON_NEW_TEXT"]));
            }
            set {
                this["KOBETSU_SIKUCHOUSON_NEW_TEXT"] = value;
            }
        }
    }
}
