SELECT
    (CASE
        WHEN SMS.SYSTEM_ID IS NOT NULL THEN 'ëóêMçœ'
        ELSE 'ñ¢ëóêM'
        END)
FROM T_UKETSUKE_SK_ENTRY SK
LEFT JOIN T_SMS SMS
ON SK.UKETSUKE_NUMBER = SMS.DENPYOU_NUMBER
WHERE SK.UKETSUKE_NUMBER = /*uketsukeNumber*/