SELECT  T_USKD.*
		, M_DENPYOU_KBN.DENPYOU_KBN_NAME_RYAKU
		, M_UNIT.UNIT_NAME_RYAKU
FROM    T_UKETSUKE_SK_DETAIL AS T_USKD LEFT OUTER JOIN
		M_UNIT ON T_USKD.UNIT_CD = M_UNIT.UNIT_CD LEFT OUTER JOIN
		M_DENPYOU_KBN ON T_USKD.DENPYOU_KBN_CD = M_DENPYOU_KBN.DENPYOU_KBN_CD AND M_DENPYOU_KBN.DELETE_FLG = 0
WHERE	T_USKD.SYSTEM_ID = /*data.SystemID*/
AND		T_USKD.SEQ = /*data.SEQ*/
ORDER BY T_USKD.ROW_NO