//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shougun.Core.SalesPayment.UriageShiharaiNyuuryoku.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DenpyouCtrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DenpyouCtrl"]));
            }
            set {
                this["DenpyouCtrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DetailCtrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DetailCtrl"]));
            }
            set {
                this["DetailCtrl"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>KYOTEN_CD:拠点CD:True:0</string>\r\n  <string>NYUURYOKU_TANTOUSHA_CD:入力担当者:Tru" +
            "e:1</string>\r\n  <string>ENTRY_NUMBER:売上/支払番号:True:5</string>\r\n  <string>RENBAN:年" +
            "連番/日連番:True:6</string>\r\n  <string>KAKUTEI_KBN:確定区分:True:7</string>\r\n  <string>U" +
            "KETSUKE_NUMBER:受付番号:True:8</string>\r\n  " +
            "<string>DENPYOU_DATE:伝票日付:True:10</string>\r\n  <string>URIAGE_DATE:売上日付:Tru" +
            "e:11</string>\r\n  <string>SHIHARAI_DATE:支払日付:True:12</string>\r\n  <string>GYOUSHA_" +
            "CD:業者CD:True:13</string>\r\n  <string>GYOUSHA_NAME_RYAKU:業者名:True:14</string>\r\n  <" +
            "string>GENBA_CD:現場CD:True:15</string>\r\n  <string>GENBA_NAME_RYAKU:現場名:True:16</s" +
            "tring>\r\n  <string>TORIHIKISAKI_CD:取引先CD:True:17</string>\r\n  <string>TORIHIKISAKI" +
            "_NAME_RYAKU:取引先名:True:18</string>\r\n  <string>NIZUMI_GYOUSHA_CD:荷積業者CD:True:19</s" +
            "tring>\r\n  <string>NIZUMI_GYOUSHA_NAME:荷積業者名:True:20</string>\r\n  <string>NIZUMI_G" +
            "ENBA_CD:荷積現場CD:True:21</string>\r\n  <string>NIZUMI_GENBA_NAME:荷積現場名:True:22</stri" +
            "ng>\r\n  <string>NIOROSHI_GYOUSHA_CD:荷降業者CD:True:23</string>\r\n  <string>NIOROSHI_G" +
            "YOUSHA_NAME:荷降業者名:True:24</string>\r\n  <string>NIOROSHI_GENBA_CD:荷降現場CD:True:25</" +
            "string>\r\n  <string>NIOROSHI_GENBA_NAME:荷降現場名:True:26</string>\r\n  <string>UNPAN_G" +
            "YOUSHA_CD:運搬業者CD:True:27</string>\r\n  <string>UNPAN_GYOUSHA_NAME:運搬業者名:True:28</s" +
            "tring>\r\n  <string>SHASHU_CD:車種CD:True:29</string>\r\n  <string>SHARYOU_CD:車輌CD:Tru" +
            "e:31</string>\r\n  <string>SHARYOU_NAME_RYAKU:車輌名:True:32</string>\r\n  <string>UNTE" +
            "NSHA_CD:運転者CD:True:33</string>\r\n  <string>NINZUU_CNT:人数:True:35</string>\r\n  <str" +
            "ing>KEITAI_KBN_CD:形態区分CD:True:36</string>\r\n  <string>MANIFEST_SHURUI_CD:マニ種類CD:T" +
            "rue:38</string>\r\n  <string>MANIFEST_TEHAI_CD:マニ手配CD:True:40</string>\r\n  <string>" +
            "EIGYOU_TANTOUSHA_CD:営業担当者CD:True:42</string>\r\n  <string>DENPYOU_BIKOU:伝票備考:True:" +
            "44</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ApDenpyouCtrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ApDenpyouCtrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>HINMEI_CD:品名CD:True:3</string>
  <string>HINMEI_NAME:品名:True:4</string>
  <string>SUURYOU:数量:True:7</string>
  <string>UNIT_CD:単位CD:True:8</string>
  <string>TANKA:単価:True:10</string>
  <string>KINGAKU:金額:True:11</string>
  <string>MANIFEST_ID:ﾏﾆﾌｪｽﾄ番号:True:13</string>
  <string>MEISAI_BIKOU:備考:True:14</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ApDetailCtrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ApDetailCtrl"]));
            }
        }
    }
}
