SELECT 
M_GYOUSHA.TORIHIKISAKI_CD, 
M_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU, 
M_GYOUSHA.GYOUSHA_CD, 
M_GYOUSHA.GYOUSHA_NAME_RYAKU, 
M_GYOUSHA.GYOUSHA_FURIGANA,
M_GYOUSHA.GYOUSHA_POST,  
M_GYOUSHA.GYOUSHA_ADDRESS1, 
M_GYOUSHA.GYOUSHA_TEL,
M_GYOUSHA.GYOUSHA_NAME1,
M_GYOUSHA.GYOUSHA_NAME2,
M_GYOUSHA.GYOUSHA_ADDRESS2,
M_TORIHIKISAKI.TORIHIKISAKI_NAME1,
M_TORIHIKISAKI.TORIHIKISAKI_NAME2,
M_TORIHIKISAKI.TORIHIKISAKI_ADDRESS1,
M_TORIHIKISAKI.TORIHIKISAKI_ADDRESS2 

FROM M_GYOUSHA 
LEFT JOIN M_TORIHIKISAKI ON M_GYOUSHA.TORIHIKISAKI_CD = M_TORIHIKISAKI.TORIHIKISAKI_CD 