SELECT
    M_GYOUSHA.TORIHIKISAKI_CD
   ,M_GYOUSHA.GYOUSHA_CD AS GYOUSHA_CD
   ,M_GYOUSHA.GYOUSHA_NAME_RYAKU AS GYOUSHAKBN_SHUKKA
   ,'' AS GENBA_CD
FROM M_GYOUSHA
WHERE 
  /*IF selectType == 2*/
    M_GYOUSHA.GYOUSHA_CD = /*gyousha*/
  -- ELSE
    ISNULL(REPLACE(REPLACE(REPLACE(M_GYOUSHA.GYOUSHA_TEL, '-', ''), ')', ''), '(', ''), '') LIKE '%' + /*tel*/ + '%' OR ISNULL(REPLACE(REPLACE(REPLACE(M_GYOUSHA.GYOUSHA_KEITAI_TEL, '-', ''), ')', ''), '(', ''), '') LIKE '%' + /*tel*/ + '%'
  /*END*/
ORDER BY GYOUSHA_CD  ASC
