/*SELECT * FROM T_XXXX where XXXX_NO = /*data.XXXX_NO*/

 入金入力　T_NYUUKIN_ENTRY
 入金明細  T_NYUUKIN_DETAIL */


/*伝票種類（1.入金）時の検索*/
SELECT T_NYUUKIN_ENTRY.KYOTEN_CD,					
       T_NYUUKIN_ENTRY.BUMON_CD,						
	   T_NYUUKIN_ENTRY.NYUUKIN_NUMBER,					
	   T_NYUUKIN_ENTRY.DENPYOU_DATE,					
	   T_NYUUKIN_ENTRY.TORIHIKISAKI_CD,					
       T_NYUUKIN_ENTRY.NYUUKINSAKI_CD,
	   T_NYUUKIN_ENTRY.BANK_CD,
	   T_NYUUKIN_ENTRY.BANK_SHITEN_CD,					
	   T_NYUUKIN_ENTRY.KOUZA_SHURUI,				
	   T_NYUUKIN_ENTRY.KOUZA_NO,				
	   T_NYUUKIN_ENTRY.KOUZA_NAME,					
	   T_NYUUKIN_ENTRY.EIGYOU_TANTOUSHA_CD,					
	   T_NYUUKIN_ENTRY.KARIUKEKIN,				
	   T_NYUUKIN_ENTRY.DENPYOU_BIKOU,					
	   T_NYUUKIN_ENTRY.NYUUKIN_AMOUNT_TOTAL,					
	   T_NYUUKIN_ENTRY.CHOUSEI_AMOUNT_TOTAL,					
	   T_NYUUKIN_ENTRY.KARIUKEKIN_WARIATE_TOTAL,			
	   T_NYUUKIN_ENTRY.CHOUSEI_DENPYOU_KBN,				
	   T_NYUUKIN_DETAIL.SYSTEM_ID,					
	   T_NYUUKIN_DETAIL.ROW_NUMBER,			
	   T_NYUUKIN_DETAIL.NYUUSHUKKIN_KBN_CD,
	   T_NYUUKIN_DETAIL.KINGAKU,					
	   T_NYUUKIN_DETAIL.MEISAI_BIKOU,					
	   M_KYOTEN.KYOTEN_NAME_RYAKU,			
	   M_BUMON.BUMON_NAME_RYAKU,			
	   M_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU,	
	   M_BANK.BANK_NAME_RYAKU,
	   M_BANK_SHITEN.BANK_SHIETN_NAME_RYAKU,					
	   M_SHAIN.SHAIN_NAME_RYAKU,					
	   M_NYUUSHUKKIN_KBN.NYUUSHUKKIN_KBN_NAME_RYAKU,	
	   M_NYUUKINSAKI.NYUUKINSAKI_NAME_RYAKU			

FROM T_NYUUKIN_ENTRY,
	 T_NYUUKIN_DETAIL
	 LEFT JOIN M_KYOTEN ON M_KYOTEN.KYOTEN_CD = T_NYUUKIN_ENTRY.KYOTEN_CD
	 LEFT JOIN M_BUMON ON M_BUMON.BUMON_CD = T_NYUUKIN_ENTRY.BUMON_CD
	 LEFT JOIN M_TORIHIKISAKI ON M_TORIHIKISAKI.TORIHIKISAKI_CD = T_NYUUKIN_ENTRY.TORIHIKISAKI_CD
	 LEFT JOIN M_BANK ON M_BANK.BANK_CD = T_NYUUKIN_ENTRY.BANK_CD
	 LEFT JOIN M_BANK_SHITEN ON (M_BANK_SHITEN.BANK_CD = T_NYUUKIN_ENTRY.BANK_CD AND
								M_BANK_SHITEN.BANK_SHITEN_CD = T_NYUUKIN_ENTRY.BANK_SHITEN_CD)
	 LEFT JOIN M_SHAIN ON M_SHAIN.SHAIN_CD = T_NYUUKIN_ENTRY.EIGYOU_TANTOUSHA_CD
	 LEFT JOIN M_NYUUSHUKKIN_KBN ON M_NYUUSHUKKIN_KBN.NYUUSHUKKIN_KBN_CD = T_NYUUKIN_DETAIL.NYUUSHUKKIN_KBN_CD
	 LEFT JOIN M_NYUUKINSAKI ON M_NYUUKINSAKI.NYUUKINSAKI_CD = T_NYUUKIN_ENTRY.NYUUKINSAKI_CD
WHERE T_NYUUKIN_ENTRY.DELETE_FLG = 0 AND
	  T_NYUUKIN_ENTRY.TIME_STAMP = 2013/08/26 AND 
	  T_NYUUKIN_ENTRY.TIME_STAMP = 2013/08/28 AND
	  T_NYUUKIN_ENTRY.SYSTEM_ID = T_NYUUKIN_DETAIL.SYSTEM_ID AND
	  T_NYUUKIN_ENTRY.SEQ = T_NYUUKIN_DETAIL.SEQ;
	  /*T_NYUUKIN_ENTRY.KYOTEN_CD = '画面の拠点CD' AND
	  /*T_NYUUKIN_ENTRY.BUMON_CD = '画面の部門CD';
	  /*T_NYUUKIN_ENTRY.DENPYOU_DATE = '' AND /*伝票日付* FROM*/
	  /*T_NYUUKIN_ENTRY.DENPYOU_DATE = '' AND /*伝票日付* TO*/
