SELECT 
 DENPYOU.KAKUTEI_KBN,
 DENPYOU.KAKUTEI_KBN AS PRE_KAKUTEI_KBN,
 DENPYOU.DENPYOU_KBN_NAME,
 DENPYOU.DENPYOU_SHURUI,
 DENPYOU.DENPYOU_NUMBER,
 DENPYOU.DENPYOU_DATE,
 DENPYOU.TORIHIKISAKI_CD,
 DENPYOU.TORIHIKISAKI_NAME,
 DENPYOU.GYOUSHA_CD,
 DENPYOU.GYOUSHA_NAME,
 DENPYOU.GENBA_CD,
 DENPYOU.GENBA_NAME,
 DENPYOU.URIAGE_KINGAKU_TOTAL,
 DENPYOU.SHIHARAI_KINGAKU_TOTAL,
 DENPYOU.EIGYOU_TANTOUSHA_NAME,
 DENPYOU.CREATE_DATE,
 DENPYOU.DENPYOU_SHURUI_CD,
 DENPYOU.SYSTEM_ID,
 DENPYOU.SEQ,
 DENPYOU.KYOTEN_CD,
 DENPYOU.DENPYOU_KBN
FROM
 (
  -- 受入
  SELECT 
   CASE E.KAKUTEI_KBN
    WHEN 1 THEN 1
    ELSE 0
   END AS KAKUTEI_KBN,
   CASE D.DENPYOU_KBN
    WHEN 1 THEN N'売上'
    WHEN 2 THEN N'支払'
    WHEN 3 THEN N'混合'
    ELSE ''
   END AS DENPYOU_KBN_NAME,
   N'受入' AS DENPYOU_SHURUI,
   E.UKEIRE_NUMBER AS DENPYOU_NUMBER,
   E.DENPYOU_DATE,
   E.TORIHIKISAKI_CD,
   E.TORIHIKISAKI_NAME,
   E.GYOUSHA_CD,
   E.GYOUSHA_NAME,
   E.GENBA_CD,
   E.GENBA_NAME,
   E.URIAGE_KINGAKU_TOTAL + E.HINMEI_URIAGE_KINGAKU_TOTAL AS URIAGE_KINGAKU_TOTAL,
   E.SHIHARAI_KINGAKU_TOTAL + E.HINMEI_SHIHARAI_KINGAKU_TOTAL AS SHIHARAI_KINGAKU_TOTAL,
   E.EIGYOU_TANTOUSHA_NAME,
   E.CREATE_DATE,
   1 AS DENPYOU_SHURUI_CD,
   E.SYSTEM_ID,
   E.SEQ,
   E.KYOTEN_CD,
   D.DENPYOU_KBN
  FROM 
   T_UKEIRE_ENTRY AS E
  INNER JOIN 
  (SELECT DISTINCT SYSTEM_ID,SEQ, SUM(ISNULL(DENPYOU_KBN_CD,0)) OVER (PARTITION BY SYSTEM_ID,SEQ) AS DENPYOU_KBN
   FROM T_UKEIRE_DETAIL 
   GROUP BY SYSTEM_ID,SEQ, DENPYOU_KBN_CD) AS D
  ON E.SYSTEM_ID = D.SYSTEM_ID
  AND E.SEQ = D.SEQ
  WHERE 
   DELETE_FLG = 0
   AND TAIRYUU_KBN = 0
   AND ((D.DENPYOU_KBN=1 AND E.URIAGE_TORIHIKI_KBN_CD=2)
   OR (D.DENPYOU_KBN=2 AND E.SHIHARAI_TORIHIKI_KBN_CD=2)
   OR (D.DENPYOU_KBN=3 AND E.URIAGE_TORIHIKI_KBN_CD=2 AND E.SHIHARAI_TORIHIKI_KBN_CD=2))
   AND NOT EXISTS (
    SELECT 1 FROM T_SEIKYUU_DENPYOU AS SEIE
    INNER JOIN
        T_SEIKYUU_DETAIL SEIDE ON SEIE.SEIKYUU_NUMBER = SEIDE.SEIKYUU_NUMBER AND SEIDE.DELETE_FLG = '0'
    LEFT JOIN 
        T_UKEIRE_DETAIL UD ON UD.SYSTEM_ID = E.SYSTEM_ID AND UD.SEQ = E.SEQ
    WHERE
        SEIDE.DENPYOU_SHURUI_CD = 1
        AND SEIDE.DENPYOU_SYSTEM_ID = UD.SYSTEM_ID 
        AND SEIDE.DENPYOU_SEQ = UD.SEQ 
        AND SEIDE.DETAIL_SYSTEM_ID = UD.DETAIL_SYSTEM_ID
        AND SEIE.DELETE_FLG = '0'
   )
   AND NOT EXISTS (
    SELECT 1 FROM T_SEISAN_DENPYOU AS SEIE
    INNER JOIN
        T_SEISAN_DETAIL SEIDE ON SEIE.SEISAN_NUMBER = SEIDE.SEISAN_NUMBER AND SEIDE.DELETE_FLG = '0'
    LEFT JOIN 
        T_UKEIRE_DETAIL UD ON UD.SYSTEM_ID = E.SYSTEM_ID AND UD.SEQ = E.SEQ
    WHERE
        SEIDE.DENPYOU_SHURUI_CD = 1
        AND SEIDE.DENPYOU_SYSTEM_ID = UD.SYSTEM_ID 
        AND SEIDE.DENPYOU_SEQ = UD.SEQ 
        AND SEIDE.DETAIL_SYSTEM_ID = UD.DETAIL_SYSTEM_ID
        AND SEIE.DELETE_FLG = '0'
   )
  UNION ALL
  -- 出荷
  SELECT 
   CASE E.KAKUTEI_KBN
    WHEN 1 THEN 1
    ELSE 0
   END AS KAKUTEI_KBN,
   CASE D.DENPYOU_KBN
    WHEN 1 THEN N'売上'
    WHEN 2 THEN N'支払'
    WHEN 3 THEN N'混合'
    ELSE ''
   END AS DENPYOU_KBN_NAME,
   N'出荷' AS DENPYOU_SHURUI,
   E.SHUKKA_NUMBER AS DENPYOU_NUMBER,
   E.DENPYOU_DATE,
   E.TORIHIKISAKI_CD,
   E.TORIHIKISAKI_NAME,
   E.GYOUSHA_CD,
   E.GYOUSHA_NAME,
   E.GENBA_CD,
   E.GENBA_NAME,
   E.URIAGE_AMOUNT_TOTAL + E.HINMEI_URIAGE_KINGAKU_TOTAL AS URIAGE_KINGAKU_TOTAL,
   E.SHIHARAI_AMOUNT_TOTAL + E.HINMEI_SHIHARAI_KINGAKU_TOTAL AS SHIHARAI_KINGAKU_TOTAL,
   E.EIGYOU_TANTOUSHA_NAME,
   E.CREATE_DATE,
   2 AS DENPYOU_SHURUI_CD,
   E.SYSTEM_ID,
   E.SEQ,
   E.KYOTEN_CD,
   D.DENPYOU_KBN
  FROM 
   T_SHUKKA_ENTRY AS E
  INNER JOIN 
  (SELECT DISTINCT SYSTEM_ID,SEQ, SUM(ISNULL(DENPYOU_KBN_CD,0)) OVER (PARTITION BY SYSTEM_ID,SEQ) AS DENPYOU_KBN
   FROM T_SHUKKA_DETAIL 
   GROUP BY SYSTEM_ID,SEQ, DENPYOU_KBN_CD) AS D
  ON E.SYSTEM_ID = D.SYSTEM_ID
  AND E.SEQ = D.SEQ
  WHERE 
   E.DELETE_FLG = 0
   AND E.TAIRYUU_KBN = 0
   AND ((D.DENPYOU_KBN=1 AND E.URIAGE_TORIHIKI_KBN_CD=2)
   OR (D.DENPYOU_KBN=2 AND E.SHIHARAI_TORIHIKI_KBN_CD=2)
   OR (D.DENPYOU_KBN=3 AND E.URIAGE_TORIHIKI_KBN_CD=2 AND E.SHIHARAI_TORIHIKI_KBN_CD=2))
   AND NOT EXISTS (
    SELECT 1 FROM T_SEIKYUU_DENPYOU AS SEIE
    INNER JOIN
        T_SEIKYUU_DETAIL SEIDE ON SEIE.SEIKYUU_NUMBER = SEIDE.SEIKYUU_NUMBER AND SEIDE.DELETE_FLG = '0'
    LEFT JOIN 
        T_SHUKKA_DETAIL SD ON SD.SYSTEM_ID = E.SYSTEM_ID AND SD.SEQ = E.SEQ
    WHERE
        SEIDE.DENPYOU_SHURUI_CD = 2
        AND SEIDE.DENPYOU_SYSTEM_ID = SD.SYSTEM_ID 
        AND SEIDE.DENPYOU_SEQ = SD.SEQ 
        AND SEIDE.DETAIL_SYSTEM_ID = SD.DETAIL_SYSTEM_ID
        AND SEIE.DELETE_FLG = '0'
   )
   AND NOT EXISTS (
    SELECT 1 FROM T_SEISAN_DENPYOU AS SEIE
    INNER JOIN
        T_SEISAN_DETAIL SEIDE ON SEIE.SEISAN_NUMBER = SEIDE.SEISAN_NUMBER AND SEIDE.DELETE_FLG = '0'
    LEFT JOIN 
        T_SHUKKA_DETAIL SD ON SD.SYSTEM_ID = E.SYSTEM_ID AND SD.SEQ = E.SEQ
    WHERE
        SEIDE.DENPYOU_SHURUI_CD = 2
        AND SEIDE.DENPYOU_SYSTEM_ID = SD.SYSTEM_ID 
        AND SEIDE.DENPYOU_SEQ = SD.SEQ 
        AND SEIDE.DETAIL_SYSTEM_ID = SD.DETAIL_SYSTEM_ID
        AND SEIE.DELETE_FLG = '0'
   )
  UNION ALL
  --売上/支払
  SELECT 
   CASE E.KAKUTEI_KBN
    WHEN 1 THEN 1
    ELSE 0
   END AS KAKUTEI_KBN,
   CASE D.DENPYOU_KBN
    WHEN 1 THEN N'売上'
    WHEN 2 THEN N'支払'
    WHEN 3 THEN N'混合'
    ELSE ''
   END AS DENPYOU_KBN_NAME,
   N'売上/支払' AS DENPYOU_SHURUI,
   E.UR_SH_NUMBER AS DENPYOU_NUMBER,
   E.DENPYOU_DATE,
   E.TORIHIKISAKI_CD,
   E.TORIHIKISAKI_NAME,
   E.GYOUSHA_CD,
   E.GYOUSHA_NAME,
   E.GENBA_CD,
   E.GENBA_NAME,
   E.URIAGE_AMOUNT_TOTAL + E.HINMEI_URIAGE_KINGAKU_TOTAL AS URIAGE_KINGAKU_TOTAL,
   E.SHIHARAI_AMOUNT_TOTAL + E.HINMEI_SHIHARAI_KINGAKU_TOTAL AS SHIHARAI_KINGAKU_TOTAL,
   E.EIGYOU_TANTOUSHA_NAME,
   E.CREATE_DATE,
   3 AS DENPYOU_SHURUI_CD,
   E.SYSTEM_ID,
   E.SEQ,
   E.KYOTEN_CD,
   D.DENPYOU_KBN
  FROM 
   T_UR_SH_ENTRY AS E
  INNER JOIN 
  (SELECT DISTINCT SYSTEM_ID,SEQ, SUM(ISNULL(DENPYOU_KBN_CD,0)) OVER (PARTITION BY SYSTEM_ID,SEQ) AS DENPYOU_KBN
   FROM T_UR_SH_DETAIL 
   GROUP BY SYSTEM_ID,SEQ, DENPYOU_KBN_CD) AS D
  ON E.SYSTEM_ID = D.SYSTEM_ID
  AND E.SEQ = D.SEQ
  WHERE 
   DELETE_FLG = 0
   /*IF data.DenpyouShuruiUrSh && !data.DenpyouShuruiDainou*/
     AND ISNULL(DAINOU_FLG, 0) = 0
   /*END*/
   /*IF !data.DenpyouShuruiUrSh && data.DenpyouShuruiDainou*/
     AND ISNULL(DAINOU_FLG, 0) = 1
   /*END*/
   AND ((D.DENPYOU_KBN=1 AND E.URIAGE_TORIHIKI_KBN_CD=2)
   OR (D.DENPYOU_KBN=2 AND E.SHIHARAI_TORIHIKI_KBN_CD=2)
   OR (D.DENPYOU_KBN=3 AND E.URIAGE_TORIHIKI_KBN_CD=2 AND E.SHIHARAI_TORIHIKI_KBN_CD=2))
   AND NOT EXISTS (
    SELECT 1 FROM T_SEIKYUU_DENPYOU AS SEIE
    INNER JOIN
        T_SEIKYUU_DETAIL SEIDE ON SEIE.SEIKYUU_NUMBER = SEIDE.SEIKYUU_NUMBER AND SEIDE.DELETE_FLG = '0'
    LEFT JOIN 
        T_UR_SH_DETAIL USD ON USD.SYSTEM_ID = E.SYSTEM_ID AND USD.SEQ = E.SEQ
    WHERE
        SEIDE.DENPYOU_SHURUI_CD = 3
        AND SEIDE.DENPYOU_SYSTEM_ID = USD.SYSTEM_ID 
        AND SEIDE.DENPYOU_SEQ = USD.SEQ 
        AND SEIDE.DETAIL_SYSTEM_ID = USD.DETAIL_SYSTEM_ID
        AND SEIE.DELETE_FLG = '0'
   )
   AND NOT EXISTS (
    SELECT 1 FROM T_SEISAN_DENPYOU AS SEIE
    INNER JOIN
        T_SEISAN_DETAIL SEIDE ON SEIE.SEISAN_NUMBER = SEIDE.SEISAN_NUMBER AND SEIDE.DELETE_FLG = '0'
    LEFT JOIN 
        T_UR_SH_DETAIL USD ON USD.SYSTEM_ID = E.SYSTEM_ID AND USD.SEQ = E.SEQ
    WHERE
        SEIDE.DENPYOU_SHURUI_CD = 3
        AND SEIDE.DENPYOU_SYSTEM_ID = USD.SYSTEM_ID 
        AND SEIDE.DENPYOU_SEQ = USD.SEQ 
        AND SEIDE.DETAIL_SYSTEM_ID = USD.DETAIL_SYSTEM_ID
        AND SEIE.DELETE_FLG = '0'
   )
 ) AS DENPYOU
/*BEGIN*/
WHERE
   /*IF !data.KyotenCD.IsNull && data.KyotenCD.Value != 99*/
   DENPYOU.KYOTEN_CD = /*data.KyotenCD*/1
   /*END*/
   /*IF !data.KakuteiKbn.IsNull && data.KakuteiKbn.Value == 1*/
   AND DENPYOU.KAKUTEI_KBN = 1
   /*END*/
   /*IF !data.KakuteiKbn.IsNull && data.KakuteiKbn.Value == 2*/
   AND DENPYOU.KAKUTEI_KBN = 0
   /*END*/
   /*IF !data.DenpyouKbn.IsNull*/
   AND DENPYOU.DENPYOU_KBN = /*data.DenpyouKbn*/1
   /*END*/
   /*IF data.DenpyouShuruiUkeire || data.DenpyouShuruiShukka || data.DenpyouShuruiUrSh || data.DenpyouShuruiDainou*/
   AND (
   /*END*/
      /*BEGIN*/
      /*IF data.DenpyouShuruiUkeire*/
      DENPYOU.DENPYOU_SHURUI_CD = 1
      /*END*/
      /*IF data.DenpyouShuruiShukka*/
      OR DENPYOU.DENPYOU_SHURUI_CD = 2
      /*END*/
      /*IF data.DenpyouShuruiUrSh || data.DenpyouShuruiDainou*/
      OR DENPYOU.DENPYOU_SHURUI_CD = 3
      /*END*/
      /*END*/
   /*IF data.DenpyouShuruiUkeire || data.DenpyouShuruiShukka || data.DenpyouShuruiUrSh || data.DenpyouShuruiDainou*/
   )
   /*END*/
   /*IF !data.DateKbn.IsNull && data.DateKbn.Value == 1*/
      /*IF data.DateFrom != null*/AND CONVERT(VARCHAR, DENPYOU.DENPYOU_DATE, 111) >= /*data.DateFrom*/'2014-01-01'/*END*/
      /*IF data.DateTo != null*/AND CONVERT(VARCHAR, DENPYOU.DENPYOU_DATE, 111) <= /*data.DateTo*/'2014-01-01' /*END*/
   /*END*/
   /*IF !data.DateKbn.IsNull && data.DateKbn.Value == 2*/
      /*IF data.DateFrom != null*/AND CONVERT(VARCHAR, DENPYOU.CREATE_DATE, 111) >= /*data.DateFrom*/'2014-01-01'/*END*/
      /*IF data.DateTo != null*/AND CONVERT(VARCHAR, DENPYOU.CREATE_DATE, 111) <= /*data.DateTo*/'2014-01-01' /*END*/
   /*END*/
/*END*/

