SELECT
SHE.TORIHIKISAKI_CD   AS TORIHIKISAKI_CD,
SHE.TORIHIKISAKI_NAME AS TORIHIKISAKI_NAME,
SHE.KYOTEN_CD         AS KYOTEN_CD,
SHE.SYSTEM_ID         AS SYSTEM_ID,
SHE.SEQ               AS SEQ,
SHD.DETAIL_SYSTEM_ID  AS DETAIL_SYSTEM_ID,
SHD.ROW_NO            AS ROW_NO,
SHE.SHUKKA_NUMBER     AS DENPYOU_NUMBER,
SHE.DENPYOU_DATE      AS DENPYOU_DATE,
SHE.URIAGE_DATE       AS URIAGE_DATE,
SHE.SHIHARAI_DATE     AS SHIHARAI_DATE,
SHE.URIAGE_ZEI_KEISAN_KBN_CD,
SHE.URIAGE_ZEI_KBN_CD,
SHE.SHIHARAI_ZEI_KEISAN_KBN_CD,
SHE.SHIHARAI_ZEI_KBN_CD,
SHD.HINMEI_ZEI_KBN_CD
FROM
T_SHUKKA_ENTRY SHE RIGHT OUTER JOIN T_SHUKKA_DETAIL SHD
ON SHE.SYSTEM_ID = SHD.SYSTEM_ID AND SHE.SEQ = SHD.SEQ
/*BEGIN*/WHERE
/*IF !deletechuFlg*/SHE.DELETE_FLG = 0/*END*/
/*IF data.KYOTEN_CD != 99*/
 AND SHE.KYOTEN_CD = /*data.KYOTEN_CD*//*END*/
/*IF data.URIAGE_SHIHARAI_KBN == 1*/
 AND SHE.URIAGE_TORIHIKI_KBN_CD = 2
-- ELSE AND SHE.SHIHARAI_TORIHIKI_KBN_CD = 2/*END*/
 AND SHE.KAKUTEI_KBN = 1
 AND SHD.DENPYOU_KBN_CD = /*data.URIAGE_SHIHARAI_KBN*/
/*IF data.URIAGE_SHIHARAI_KBN == 1*/
 /*IF data.SEIKYUSHIMEBI_FROM != null && data.SEIKYUSHIMEBI_FROM != ""*/
 AND CONVERT(DATETIME, SHE.URIAGE_DATE,111) >= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_FROM*/null,111)
 AND CONVERT(DATETIME, SHE.URIAGE_DATE,111) <= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_TO*/null,111)
 -- ELSE AND CONVERT(DATETIME, SHE.URIAGE_DATE,111) <= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_TO*/null,111)/*END*/
 AND SHE.TORIHIKISAKI_CD = /*data.SEIKYU_CD*/
-- ELSE
 /*IF data.SHIHARAISHIMEBI_FROM != null && data.SHIHARAISHIMEBI_FROM != ""*/
 AND CONVERT(DATETIME, SHE.SHIHARAI_DATE,111) >= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_FROM*/null,111)
 AND CONVERT(DATETIME, SHE.SHIHARAI_DATE,111) <= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_TO*/null,111)
 -- ELSE AND CONVERT(DATETIME, SHE.SHIHARAI_DATE,111) <= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_TO*/null,111)/*END*/
 AND SHE.TORIHIKISAKI_CD = /*data.SHIHARAI_CD*/
/*END*/
/*IF data.DENPYOU_BANGOU != 0*/ AND SHE.SHUKKA_NUMBER = /*data.DENPYOU_BANGOU*//*END*/
AND (SHE.KENSHU_MUST_KBN != 1 OR SHE.KENSHU_MUST_KBN IS NULL)
AND NOT EXISTS (
	SELECT
		1
	FROM
		/*IF data.URIAGE_SHIHARAI_KBN == 1*/
		T_SEIKYUU_DENPYOU AS SEIE
        INNER JOIN T_SEIKYUU_DETAIL SEIDE 
			ON SEIE.SEIKYUU_NUMBER = SEIDE.SEIKYUU_NUMBER AND SEIDE.DELETE_FLG = 0
		-- ELSE
		T_SEISAN_DENPYOU AS SEIE
		INNER JOIN T_SEISAN_DETAIL SEIDE
			ON SEIE.SEISAN_NUMBER = SEIDE.SEISAN_NUMBER AND SEIDE.DELETE_FLG = 0
		/*END*/
	WHERE
		SEIDE.DENPYOU_SHURUI_CD = 2
        AND SEIDE.DENPYOU_SYSTEM_ID = SHD.SYSTEM_ID 
        AND SEIDE.DENPYOU_SEQ = SHD.SEQ 
        AND SEIDE.DETAIL_SYSTEM_ID = SHD.DETAIL_SYSTEM_ID
		/*IF data.SAISHIME_FLG && data.SAISHIME_NUMBER_LIST.Count > 0*/
			/*IF data.URIAGE_SHIHARAI_KBN == 1*/
				AND SEIDE.SEIKYUU_NUMBER NOT IN /*data.SAISHIME_NUMBER_LIST*/(0)
			 -- ELSE
				 AND SEIDE.SEISAN_NUMBER NOT IN /*data.SAISHIME_NUMBER_LIST*/(0)
			/*END*/
		 /*END*/
)
/*END*/

UNION ALL (
	SELECT
	SHE.TORIHIKISAKI_CD   AS TORIHIKISAKI_CD,
	SHE.TORIHIKISAKI_NAME AS TORIHIKISAKI_NAME,
	SHE.KYOTEN_CD         AS KYOTEN_CD,
	SHE.SYSTEM_ID         AS SYSTEM_ID,
	SHE.SEQ               AS SEQ,
	SHD.DETAIL_SYSTEM_ID  AS DETAIL_SYSTEM_ID,
	SHD.ROW_NO            AS ROW_NO,
	SHE.SHUKKA_NUMBER     AS DENPYOU_NUMBER,
	SHE.KENSHU_DATE      AS DENPYOU_DATE,
	SHE.URIAGE_DATE      AS URIAGE_DATE,
	SHE.SHIHARAI_DATE    AS SHIHARAI_DATE,
	SHE.URIAGE_ZEI_KEISAN_KBN_CD,
	SHE.URIAGE_ZEI_KBN_CD,
	SHE.SHIHARAI_ZEI_KEISAN_KBN_CD,
	SHE.SHIHARAI_ZEI_KBN_CD,
	KED.HINMEI_ZEI_KBN_CD
	FROM
	T_SHUKKA_ENTRY SHE RIGHT OUTER JOIN T_SHUKKA_DETAIL SHD
	ON SHE.SYSTEM_ID = SHD.SYSTEM_ID AND SHE.SEQ = SHD.SEQ
	LEFT JOIN T_KENSHU_DETAIL KED
	ON SHD.SYSTEM_ID = KED.SYSTEM_ID
	AND SHD.SEQ = KED.SEQ
	AND SHD.DETAIL_SYSTEM_ID = KED.DETAIL_SYSTEM_ID
	AND SHD.ROW_NO = KED.ROW_NO
	/*BEGIN*/WHERE
	/*IF !deletechuFlg*/SHE.DELETE_FLG = 0/*END*/
	/*IF data.KYOTEN_CD != 99*/
	 AND SHE.KYOTEN_CD = /*data.KYOTEN_CD*//*END*/
	/*IF data.URIAGE_SHIHARAI_KBN == 1*/
	 AND SHE.URIAGE_TORIHIKI_KBN_CD = 2
	-- ELSE AND SHE.SHIHARAI_TORIHIKI_KBN_CD = 2/*END*/
	 AND SHE.KAKUTEI_KBN = 1
	 AND KED.DENPYOU_KBN_CD = /*data.URIAGE_SHIHARAI_KBN*/
	/*IF data.URIAGE_SHIHARAI_KBN == 1*/
	 /*IF data.SEIKYUSHIMEBI_FROM != null && data.SEIKYUSHIMEBI_FROM != ""*/
	 AND CONVERT(DATETIME, SHE.KENSHU_URIAGE_DATE,111) >= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_FROM*/null,111)
	 AND CONVERT(DATETIME, SHE.KENSHU_URIAGE_DATE,111) <= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_TO*/null,111)
	 -- ELSE AND CONVERT(DATETIME, SHE.KENSHU_URIAGE_DATE,111) <= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_TO*/null,111)/*END*/
	 AND SHE.TORIHIKISAKI_CD = /*data.SEIKYU_CD*/
	-- ELSE
	 /*IF data.SHIHARAISHIMEBI_FROM != null && data.SHIHARAISHIMEBI_FROM != ""*/
	 AND CONVERT(DATETIME, SHE.KENSHU_SHIHARAI_DATE,111) >= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_FROM*/null,111)
	 AND CONVERT(DATETIME, SHE.KENSHU_SHIHARAI_DATE,111) <= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_TO*/null,111)
	 -- ELSE AND CONVERT(DATETIME, SHE.KENSHU_SHIHARAI_DATE,111) <= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_TO*/null,111)/*END*/
	 AND SHE.TORIHIKISAKI_CD = /*data.SHIHARAI_CD*/
	/*END*/
	/*IF data.DENPYOU_BANGOU != 0*/ AND SHE.SHUKKA_NUMBER = /*data.DENPYOU_BANGOU*//*END*/
	AND SHE.KENSHU_MUST_KBN = 1
	AND NOT EXISTS (
		SELECT
			1
		FROM
			/*IF data.URIAGE_SHIHARAI_KBN == 1*/
			T_SEIKYUU_DENPYOU AS SEIE
            INNER JOIN T_SEIKYUU_DETAIL SEIDE
				ON SEIE.SEIKYUU_NUMBER = SEIDE.SEIKYUU_NUMBER AND SEIDE.DELETE_FLG = 0
			-- ELSE
			T_SEISAN_DENPYOU AS SEIE
			INNER JOIN T_SEISAN_DETAIL SEIDE
				ON SEIE.SEISAN_NUMBER = SEIDE.SEISAN_NUMBER AND SEIDE.DELETE_FLG = 0
			/*END*/
		WHERE
			SEIDE.DENPYOU_SHURUI_CD = 2
            AND SEIDE.DENPYOU_SYSTEM_ID = SHD.SYSTEM_ID 
            AND SEIDE.DENPYOU_SEQ = SHD.SEQ 
            AND SEIDE.DETAIL_SYSTEM_ID = SHD.DETAIL_SYSTEM_ID
			/*IF data.SAISHIME_FLG && data.SAISHIME_NUMBER_LIST.Count > 0*/
				/*IF data.URIAGE_SHIHARAI_KBN == 1*/
					AND SEIDE.SEIKYUU_NUMBER NOT IN /*data.SAISHIME_NUMBER_LIST*/(0)
				 -- ELSE
					 AND SEIDE.SEISAN_NUMBER NOT IN /*data.SAISHIME_NUMBER_LIST*/(0)
				/*END*/
			/*END*/
	)
	/*END*/
)