SELECT
UKE.TORIHIKISAKI_CD   AS TORIHIKISAKI_CD,
UKE.TORIHIKISAKI_NAME AS TORIHIKISAKI_NAME,
UKE.KYOTEN_CD         AS KYOTEN_CD,
UKE.SYSTEM_ID         AS SYSTEM_ID,
UKE.SEQ               AS SEQ,
UKD.DETAIL_SYSTEM_ID  AS DETAIL_SYSTEM_ID,
UKD.ROW_NO            AS ROW_NO,
UKE.UKEIRE_NUMBER     AS DENPYOU_NUMBER,
UKE.DENPYOU_DATE      AS DENPYOU_DATE,
UKE.URIAGE_DATE       AS URIAGE_DATE,
UKE.SHIHARAI_DATE     AS SHIHARAI_DATE,
UKE.URIAGE_ZEI_KEISAN_KBN_CD,
UKE.URIAGE_ZEI_KBN_CD,
UKE.SHIHARAI_ZEI_KEISAN_KBN_CD,
UKE.SHIHARAI_ZEI_KBN_CD,
UKD.HINMEI_ZEI_KBN_CD
FROM
T_UKEIRE_ENTRY UKE RIGHT OUTER JOIN T_UKEIRE_DETAIL UKD
ON UKE.SYSTEM_ID = UKD.SYSTEM_ID AND UKE.SEQ = UKD.SEQ
/*BEGIN*/WHERE
/*IF !deletechuFlg*/UKE.DELETE_FLG = 0/*END*/
/*IF data.KYOTEN_CD != 99*/
 AND UKE.KYOTEN_CD = /*data.KYOTEN_CD*//*END*/
/*IF data.URIAGE_SHIHARAI_KBN == 1*/
 AND UKE.URIAGE_TORIHIKI_KBN_CD = 2
-- ELSE AND UKE.SHIHARAI_TORIHIKI_KBN_CD = 2/*END*/
 AND UKE.KAKUTEI_KBN = 1
 AND UKD.DENPYOU_KBN_CD = /*data.URIAGE_SHIHARAI_KBN*/
/*IF data.URIAGE_SHIHARAI_KBN == 1*/
 /*IF data.SEIKYUSHIMEBI_FROM != null && data.SEIKYUSHIMEBI_FROM != ""*/
 AND CONVERT(DATETIME, UKE.URIAGE_DATE,111) >= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_FROM*/null,111)
 AND CONVERT(DATETIME, UKE.URIAGE_DATE,111) <= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_TO*/null,111)
 -- ELSE AND CONVERT(DATETIME, UKE.URIAGE_DATE,111) <= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_TO*/null,111)/*END*/
 AND UKE.TORIHIKISAKI_CD = /*data.SEIKYU_CD*/
-- ELSE
 /*IF data.SHIHARAISHIMEBI_FROM != null && data.SHIHARAISHIMEBI_FROM != ""*/
 AND CONVERT(DATETIME, UKE.SHIHARAI_DATE,111) >= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_FROM*/null,111)
 AND CONVERT(DATETIME, UKE.SHIHARAI_DATE,111) <= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_TO*/null,111)
 -- ELSE AND CONVERT(DATETIME, UKE.SHIHARAI_DATE,111) <= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_TO*/null,111)/*END*/
 AND UKE.TORIHIKISAKI_CD = /*data.SHIHARAI_CD*/
/*END*/
/*IF data.DENPYOU_BANGOU != 0*/ AND UKE.UKEIRE_NUMBER = /*data.DENPYOU_BANGOU*//*END*/
AND NOT EXISTS (
	SELECT
		1 
	FROM
		/*IF data.URIAGE_SHIHARAI_KBN == 1*/
		T_SEIKYUU_DENPYOU AS SEIE
        INNER JOIN T_SEIKYUU_DETAIL SEIDE
			ON SEIE.SEIKYUU_NUMBER = SEIDE.SEIKYUU_NUMBER AND SEIDE.DELETE_FLG = 0
		-- ELSE
		T_SEISAN_DENPYOU AS SEIE
		INNER JOIN T_SEISAN_DETAIL SEIDE
			ON SEIE.SEISAN_NUMBER = SEIDE.SEISAN_NUMBER AND SEIDE.DELETE_FLG = 0
		/*END*/
	WHERE
		SEIDE.DENPYOU_SHURUI_CD = 1
        AND SEIDE.DENPYOU_SYSTEM_ID = UKD.SYSTEM_ID 
        AND SEIDE.DENPYOU_SEQ = UKD.SEQ 
        AND SEIDE.DETAIL_SYSTEM_ID = UKD.DETAIL_SYSTEM_ID
		 /*IF data.SAISHIME_FLG && data.SAISHIME_NUMBER_LIST.Count > 0*/
			/*IF data.URIAGE_SHIHARAI_KBN == 1*/
				AND SEIDE.SEIKYUU_NUMBER NOT IN /*data.SAISHIME_NUMBER_LIST*/(0)
			 -- ELSE
				 AND SEIDE.SEISAN_NUMBER NOT IN /*data.SAISHIME_NUMBER_LIST*/(0)
			/*END*/
		 /*END*/
)
/*END*/