SELECT
SHD.SYSTEM_ID AS SYSTEM_ID,
SHD.SEQ AS SEQ,
SHD.DETAIL_SYSTEM_ID AS DETAIL_SYSTEM_ID,
SHD.ROW_NUMBER AS ROW_NO,
SHE.SHUKKIN_NUMBER AS DENPYOU_NUMBER,
SHE.DENPYOU_DATE AS DENPYOU_DATE,
SHE.KYOTEN_CD AS KYOTEN_CD
FROM
T_SHUKKIN_ENTRY SHE RIGHT OUTER JOIN T_SHUKKIN_DETAIL SHD
ON SHE.SYSTEM_ID = SHD.SYSTEM_ID AND SHE.SEQ = SHD.SEQ
/*BEGIN*/WHERE
/*IF !deletechuFlg*/SHE.DELETE_FLG = 0/*END*/
/*IF data.KYOTEN_CD != 99*/
 AND SHE.KYOTEN_CD = /*data.KYOTEN_CD*//*END*/
/*IF data.SHIHARAISHIMEBI_FROM != null && data.SHIHARAISHIMEBI_FROM != ""*/
 AND CONVERT(DATETIME, SHE.DENPYOU_DATE,111) >= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_FROM*/null,111)
 AND CONVERT(DATETIME, SHE.DENPYOU_DATE,111) <= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_TO*/null,111)
  -- ELSE  AND CONVERT(DATETIME, SHE.DENPYOU_DATE,111) <= CONVERT(DATETIME, /*data.SHIHARAISHIMEBI_TO*/null,111)/*END*/
 AND SHE.TORIHIKISAKI_CD = /*data.SHIHARAI_CD*/
/*END*/