SELECT
	KIHON.SYSTEM_ID
FROM M_ITAKU_KEIYAKU_KIHON AS KIHON
/*IF data.GENBA_CD != null*/
LEFT JOIN M_ITAKU_KEIYAKU_KIHON_HST_GENBA AS HST_GENBA
ON KIHON.SYSTEM_ID = HST_GENBA.SYSTEM_ID
/*END*/
/*IF data.HINMEI_CD != null*/
INNER JOIN M_ITAKU_KEIYAKU_BETSU1_HST AS HOUKOKU
ON KIHON.SYSTEM_ID = HOUKOKU.SYSTEM_ID
INNER JOIN (SELECT
               H.HINMEI_CD,
               S1.HOUKOKUSHO_BUNRUI_CD AS BUNRUI_CD1,
               S2.HOUKOKUSHO_BUNRUI_CD AS BUNRUI_CD2,
               S3.HOUKOKUSHO_BUNRUI_CD AS BUNRUI_CD3,
               S4.HOUKOKUSHO_BUNRUI_CD AS BUNRUI_CD4
            FROM M_HINMEI H
            LEFT JOIN M_HAIKI_SHURUI S1
				ON H.SP_CHOKKOU_HAIKI_SHURUI_CD = S1.HAIKI_SHURUI_CD
				AND S1.HAIKI_KBN_CD = 1
            LEFT JOIN M_HAIKI_SHURUI S2
				ON H.SP_TSUMIKAE_HAIKI_SHURUI_CD = S2.HAIKI_SHURUI_CD
				AND S2.HAIKI_KBN_CD = 3
            LEFT JOIN M_HAIKI_SHURUI S3
				ON H.KP_HAIKI_SHURUI_CD = S3.HAIKI_SHURUI_CD
				AND S3.HAIKI_KBN_CD = 2
            LEFT JOIN M_DENSHI_HAIKI_SHURUI S4
				ON H.DM_HAIKI_SHURUI_CD = S4.HAIKI_SHURUI_CD
            WHERE H.HINMEI_CD = /*data.HINMEI_CD*/) AS H
ON (HOUKOKU.HOUKOKUSHO_BUNRUI_CD = H.BUNRUI_CD1 
   OR HOUKOKU.HOUKOKUSHO_BUNRUI_CD = H.BUNRUI_CD2
   OR HOUKOKU.HOUKOKUSHO_BUNRUI_CD = H.BUNRUI_CD3 
   OR HOUKOKU.HOUKOKUSHO_BUNRUI_CD = H.BUNRUI_CD4)
/*END*/
/*IF data.HAIKI_SHURUI_CD != null*/
INNER JOIN M_ITAKU_KEIYAKU_BETSU1_HST AS HOUKOKU
ON KIHON.SYSTEM_ID = HOUKOKU.SYSTEM_ID
INNER JOIN (SELECT
               S.HOUKOKUSHO_BUNRUI_CD
            FROM 
			/*IF data.HAIKI_KBN_CD != 4*/
			M_HAIKI_SHURUI S
			--ELSE
			M_DENSHI_HAIKI_SHURUI S
			/*END*/
            WHERE S.HAIKI_SHURUI_CD = /*data.HAIKI_SHURUI_CD*/
              /*IF data.HAIKI_KBN_CD != 4*/AND S.HAIKI_KBN_CD = /*data.HAIKI_KBN_CD*//*END*/) AS S
ON (HOUKOKU.HOUKOKUSHO_BUNRUI_CD = S.HOUKOKUSHO_BUNRUI_CD)
/*END*/
WHERE 
KIHON.DELETE_FLG = 0
/*IF data.GYOUSHA_CD != null*/
AND KIHON.HAISHUTSU_JIGYOUSHA_CD = /*data.GYOUSHA_CD*/
/*END*/
/*IF data.GENBA_CD != null*/
	/*IF data.GENBA_CD != ''*/
	AND (KIHON.HAISHUTSU_JIGYOUJOU_CD = /*data.GENBA_CD*/
		 OR HST_GENBA.HAISHUTSU_JIGYOUJOU_CD = /*data.GENBA_CD*/
		 OR (ISNULL(KIHON.HAISHUTSU_JIGYOUJOU_CD,'') = ''
		     AND NOT EXISTS (SELECT 1 
							 FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA T1
							 WHERE
							 T1.SYSTEM_ID = KIHON.SYSTEM_ID
							 AND ISNULL(T1.HAISHUTSU_JIGYOUJOU_CD,'') <> '')))
	--ELSE
	AND ISNULL(KIHON.HAISHUTSU_JIGYOUJOU_CD,'') = ''
	AND NOT EXISTS (SELECT 1 
					FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA T1
					WHERE
					T1.SYSTEM_ID = KIHON.SYSTEM_ID
					AND ISNULL(T1.HAISHUTSU_JIGYOUJOU_CD,'') <> '')
	/*END*/
/*END*/
/*IF !data.SAGYOU_DATE.IsNull*/
-- 更新種別：自動更新の場合、「有効期限From～自動更新終了日」を有効期間内とする。
-- 更新種別：単発の場合、「有効期限From～有効期限To」を有効期間内とする。
AND ( (KIHON.YUUKOU_BEGIN <= /*data.SAGYOU_DATE*/ OR KIHON.YUUKOU_BEGIN IS NULL)

-- 更新種別：単発
AND ( KIHON.KOUSHIN_SHUBETSU != 1 AND (KIHON.YUUKOU_END IS NULL OR KIHON.YUUKOU_END >= /*data.SAGYOU_DATE*/)

-- 更新種別：自動
OR ( KIHON.KOUSHIN_SHUBETSU = 1 AND (KIHON.KOUSHIN_END_DATE IS NULL OR KIHON.KOUSHIN_END_DATE >= /*data.SAGYOU_DATE*/) ) ) )
/*END*/