SELECT
NYE.TORIHIKISAKI_CD      AS TORIHIKISAKI_CD,
NYE.KYOTEN_CD            AS KYOTEN_CD,
NYE.SYSTEM_ID            AS SYSTEM_ID,
NYE.SEQ                  AS SEQ,
NYD.DETAIL_SYSTEM_ID     AS DETAIL_SYSTEM_ID,
NYD.ROW_NUMBER           AS ROW_NO,
NYE.NYUUKIN_NUMBER       AS DENPYOU_NUMBER,
NYE.DENPYOU_DATE         AS DENPYOU_DATE,
ISNULL(NYD.KINGAKU,0)    AS GOUKEIGAKU
FROM
T_NYUUKIN_ENTRY NYE RIGHT OUTER JOIN T_NYUUKIN_DETAIL NYD
ON NYE.SYSTEM_ID = NYD.SYSTEM_ID AND NYE.SEQ = NYD.SEQ
/*BEGIN*/WHERE
/*IF !deletechuFlg*/NYE.DELETE_FLG = 0/*END*/
/*IF data.KYOTEN_CD != 99*/
 AND NYE.KYOTEN_CD = /*data.KYOTEN_CD*//*END*/
/*IF data.SEIKYUSHIMEBI_FROM != null && data.SEIKYUSHIMEBI_FROM != ""*/
 AND CONVERT(DATETIME, NYE.DENPYOU_DATE,111) >= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_FROM*/null,111)
 AND CONVERT(DATETIME, NYE.DENPYOU_DATE,111) <= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_TO*/null,111)
 -- ELSE AND CONVERT(DATETIME, NYE.DENPYOU_DATE,111) <= CONVERT(DATETIME, /*data.SEIKYUSHIMEBI_TO*/null,111)/*END*/
 AND NYE.TORIHIKISAKI_CD = /*data.SEIKYU_CD*/
 /*IF data.DENPYOU_BANGOU != 0*/ AND NYE.NYUUKIN_NUMBER = /*data.DENPYOU_BANGOU*//*END*/
 AND NOT EXISTS (
    SELECT
        1 
    FROM
        T_SEIKYUU_DENPYOU AS SEIE
        INNER JOIN T_SEIKYUU_DETAIL SEIDE
        ON SEIE.SEIKYUU_NUMBER = SEIDE.SEIKYUU_NUMBER AND SEIDE.DELETE_FLG = 0
    WHERE
        SEIDE.DENPYOU_SHURUI_CD = 10
        AND SEIDE.DENPYOU_SYSTEM_ID = NYD.SYSTEM_ID 
        AND SEIDE.DENPYOU_SEQ = NYD.SEQ 
        AND SEIDE.DETAIL_SYSTEM_ID = NYD.DETAIL_SYSTEM_ID
		/*IF data.SAISHIME_FLG && data.SAISHIME_NUMBER_LIST.Count > 0*/
		AND SEIDE.SEIKYUU_NUMBER NOT IN /*data.SAISHIME_NUMBER_LIST*/(0)
		/*END*/
		)
/*END*/