SELECT DISTINCT
    TOC.KANRI_ID,
    TOC.LATEST_SEQ,
    '' MANIFEST_ID,
    MIX.LAST_SBN_END_DATE AS LAST_SBN_END_DATE,
    R19EX.UPNSAKI_GENBA_CD AS LAST_SBN_GENBA_CD,
    R19.UPNSAKI_JOU_NAME AS GENBA_NAME1,
    R19.UPNSAKI_JOU_POST AS GENBA_POST,
    R19.UPNSAKI_JOU_TEL AS GENBA_TEL,
    '' AS TODOUFUKEN_NAME,
    '' AS CHIIKI_NAME,
    '' AS SHIKUCHOUSON_NAME,
    ISNULL(R19.UPNSAKI_JOU_ADDRESS1, '') + ISNULL(R19.UPNSAKI_JOU_ADDRESS2, '') + ISNULL(R19.UPNSAKI_JOU_ADDRESS3, '') + ISNULL(R19.UPNSAKI_JOU_ADDRESS4, '') AS GENBA_ADDRESS1,
    '' AS GENBA_ADDRESS2,
    CAST(0 AS bigint) AS SYSTEM_ID,
    CAST(0 AS bigint) AS DETAIL_SYSTEM_ID,
    CAST(0 AS numeric) AS REC_SEQ,
    TOC.UPDATE_TS,
    TOC.STATUS_FLAG,
    TOC.STATUS_DETAIL,
    TOC.APPROVAL_SEQ,
    CAST(MIX.SBN_ENDREP_KBN AS int) AS SBN_ENDREP_KBN,
    CAST(1 AS bit) AS KONGOU_KBN
FROM
    DT_MF_TOC AS TOC
    INNER JOIN DT_R18_MIX AS MIX
        ON TOC.KANRI_ID = MIX.KANRI_ID
        AND MIX.DELETE_FLG = 0
    INNER JOIN DT_R18 AS R18
        ON TOC.KANRI_ID = R18.KANRI_ID
        AND TOC.LATEST_SEQ = R18.SEQ
    LEFT JOIN DT_R19 AS R19
        ON R18.KANRI_ID = R19.KANRI_ID
        AND R18.SEQ = R19.SEQ
        AND R18.UPN_ROUTE_CNT = R19.UPN_ROUTE_NO
    LEFT JOIN DT_R19_EX AS R19EX
        ON R19.KANRI_ID = R19EX.KANRI_ID
        AND R19.UPN_ROUTE_NO = R19EX.UPN_ROUTE_NO
        AND R19EX.DELETE_FLG = 0
WHERE
    MIX.SBN_ENDREP_KBN = 2
    /*IF data != null */ AND TOC.KANRI_ID IN /*data*/('1','2')/*END*/