SELECT
    MANI_MAIN.KANRI_ID AS KANRI_ID, --管理番号
    MANI_MAIN.LATEST_SEQ AS LATEST_SEQ,  --最新SEQ
    MANI_REL_OWN.NEXT_SYSTEM_ID AS SYSTEM_ID,
    MANI_MAIN.UPDATE_TS,
    MANI_MAIN.STATUS_FLAG, -- 状態フラグ
    MANI_MAIN.STATUS_DETAIL, -- 状態詳細フラグ
    MANI_MAIN.APPROVAL_SEQ -- 修正/取消中SEQ
FROM 
    (
        SELECT
            FIRST_SYSTEM_ID, NEXT_SYSTEM_ID
        FROM
            T_MANIFEST_RELATION 
        WHERE
            NEXT_SYSTEM_ID = /*data.MANIFEST_SYSTEM_ID*/
            AND NEXT_HAIKI_KBN_CD = /*data.NEXT_HAIKI_KBN_CD*/
            AND DELETE_FLG = 0
            AND FIRST_HAIKI_KBN_CD = 4
    ) MANI_REL_OWN --自身のマニフェスト紐付情報
INNER JOIN 
    (
        SELECT
            TOC.KANRI_ID,
            TOC.LATEST_SEQ,
            TOC.APPROVAL_SEQ,
            TOC.STATUS_FLAG,
            TOC.STATUS_DETAIL,
            TOC.UPDATE_TS,
            CASE WHEN R18M.DETAIL_SYSTEM_ID IS NOT NULL THEN R18M.DETAIL_SYSTEM_ID ELSE R18E.SYSTEM_ID END SYSTEM_ID
        FROM
            DT_MF_TOC TOC
            INNER JOIN DT_R18 R18 ON TOC.KANRI_ID = R18.KANRI_ID AND TOC.LATEST_SEQ = R18.SEQ
            LEFT JOIN DT_R18_EX R18E ON R18.KANRI_ID = R18E.KANRI_ID AND R18E.DELETE_FLG = 0
            LEFT JOIN DT_R18_MIX R18M ON R18E.SYSTEM_ID = R18M.SYSTEM_ID AND R18M.DELETE_FLG = 0
        WHERE
            R18.LAST_SBN_ENDREP_FLAG = '1'
            AND TOC.STATUS_FLAG IN (3, 4)
    ) MANI_MAIN -- R18 マニフェスト情報・目次情報
ON MANI_REL_OWN.FIRST_SYSTEM_ID = MANI_MAIN.SYSTEM_ID

INNER JOIN (SELECT FIRST_SYSTEM_ID, NEXT_HAIKI_KBN_CD, NEXT_SYSTEM_ID FROM T_MANIFEST_RELATION WHERE FIRST_HAIKI_KBN_CD = 4 AND DELETE_FLG = 0) MANI_FIRST --マニフェスト紐付（２次）
ON MANI_FIRST.FIRST_SYSTEM_ID = MANI_MAIN.SYSTEM_ID

LEFT JOIN (SELECT SYSTEM_ID FROM T_LAST_SBN_SUSPEND WHERE SYSTEM_ID IS NULL AND DELETE_FLG = 0) SBN_SUS --最終処分保留
ON MANI_FIRST.NEXT_SYSTEM_ID = SBN_SUS.SYSTEM_ID