SELECT
    REL.FIRST_SYSTEM_ID AS SYSTEM_ID
FROM
    T_MANIFEST_RELATION AS REL WITH(NOLOCK)
    INNER JOIN (
        SELECT
            CASE WHEN R18MIX.DETAIL_SYSTEM_ID IS NOT NULL
                THEN R18MIX.DETAIL_SYSTEM_ID
                ELSE R18EX.SYSTEM_ID
            END AS SYSTEM_ID
        FROM
            DT_MF_TOC AS TOC WITH (NOLOCK)
            INNER JOIN DT_R18 AS R18 WITH (NOLOCK)
                ON TOC.KANRI_ID = R18.KANRI_ID
                AND TOC.LATEST_SEQ = R18.SEQ
            INNER JOIN DT_R18_EX AS R18EX WITH(NOLOCK)
                ON R18.KANRI_ID = R18EX.KANRI_ID
                AND R18EX.DELETE_FLG = 0
            LEFT JOIN DT_R18_MIX AS R18MIX WITH(NOLOCK)
                ON R18EX.KANRI_ID = R18MIX.KANRI_ID
                AND R18MIX.DELETE_FLG = 0
        WHERE
            ISNULL(TOC.KIND, 0) <> 5
            AND R18.LAST_SBN_ENDREP_FLAG = 1
    ) AS FIRST_MANI
    ON REL.FIRST_SYSTEM_ID = FIRST_MANI.SYSTEM_ID
WHERE
    REL.FIRST_HAIKI_KBN_CD = 4
    AND REL.DELETE_FLG = 0
    /*IF nextHaikiKbnCd == 4*/
        AND REL.NEXT_HAIKI_KBN_CD = 4
    /*END*/
    /*IF nextHaikiKbnCd != 4*/
        AND REL.NEXT_HAIKI_KBN_CD <> 4
    /*END*/
    AND REL.NEXT_SYSTEM_ID = /*nextSysId*/0