-- このクエリを修正した場合は、 \01_共通\BusinessCommon\Sql\GetSyuuryouBiKeikokuData.sql も同様の修正を行うこと

-- 運搬
SELECT
    TME.SYSTEM_ID,
    TME.SEQ
FROM
    T_MANIFEST_ENTRY TME
    LEFT JOIN
        T_MANIFEST_UPN TMU
    ON  TME.SYSTEM_ID = TMU.SYSTEM_ID
    AND TME.SEQ = TMU.SEQ
WHERE
    TME.DELETE_FLG = 0
AND TME.KOUFU_DATE + /*data.Mani_UNPAN_DAYS*/0 < CONVERT (DATETIME, CONVERT (nvarchar, GETDATE (), 111), 120)
AND ISNULL (TMU.UPN_END_DATE, '') = ''
AND /*data.Mani_UNPAN_DAYS*/0 > 0
AND (TMU.UPN_GYOUSHA_CD IS NOT NULL AND TMU.UPN_GYOUSHA_CD <> '')
AND (TMU.UPN_END_DATE IS NULL OR TMU.UPN_END_DATE = '')

UNION

-- 処分
SELECT
    TME.SYSTEM_ID,
    TME.SEQ
FROM
    T_MANIFEST_ENTRY AS TME
    LEFT JOIN
        T_MANIFEST_DETAIL AS TMAD
    ON  TME.SYSTEM_ID = TMAD.SYSTEM_ID
    AND TME.SEQ = TMAD.SEQ
    AND TME.DELETE_FLG = 0
WHERE
    TME.KOUFU_DATE + /*data.Mani_SBN_DAYS*/0 < CONVERT (DATETIME, CONVERT (NVARCHAR, GETDATE (), 111), 120)
AND ISNULL (TMAD.SBN_END_DATE, '') = ''
AND TME.DELETE_FLG = 0
AND /*data.Mani_SBN_DAYS*/0 > 0
AND (((TME.HAIKI_KBN_CD = 1 OR  TME.HAIKI_KBN_CD = 3) AND TMAD.HAIKI_SHURUI_CD < '7000') OR (TME.HAIKI_KBN_CD = 2 AND TMAD.HAIKI_SHURUI_CD < '2100'))



UNION

-- 特管処分
SELECT
    TME.SYSTEM_ID,
    TME.SEQ
FROM
    T_MANIFEST_ENTRY AS TME
    LEFT JOIN
        T_MANIFEST_DETAIL AS TMAD
    ON  TME.SYSTEM_ID = TMAD.SYSTEM_ID
    AND TME.SEQ = TMAD.SEQ
    AND TME.DELETE_FLG = 0
WHERE
    TME.KOUFU_DATE + /*data.Mani_TOK_SBN_DAYS*/0 < CONVERT (DATETIME, CONVERT (NVARCHAR, GETDATE (), 111), 120)
AND ISNULL (TMAD.SBN_END_DATE, '') = ''
AND TME.DELETE_FLG = 0
AND /*data.Mani_TOK_SBN_DAYS*/0 > 0
AND (((TME.HAIKI_KBN_CD = 1 OR  TME.HAIKI_KBN_CD = 3) AND TMAD.HAIKI_SHURUI_CD >= '7000') OR (TME.HAIKI_KBN_CD = 2 AND TMAD.HAIKI_SHURUI_CD >= '2100'))

UNION

-- 最終処分
SELECT
    TME.SYSTEM_ID,
    TME.SEQ
FROM
    T_MANIFEST_ENTRY TME
LEFT JOIN
    T_MANIFEST_DETAIL TMD
ON  TME.SYSTEM_ID = TMD.SYSTEM_ID
AND TME.SEQ = TMD.SEQ
WHERE
    TME.DELETE_FLG = 0
AND (TME.KOUFU_DATE + /*data.Mani_LAST_SBN_DAYS*/0) < CONVERT (DATETIME, CONVERT (nvarchar, GETDATE (), 111), 120)
AND ISNULL (TMD.LAST_SBN_END_DATE, '') = ''
AND /*data.Mani_LAST_SBN_DAYS*/0 > 0
