SELECT
 TOP 1 SEIKYUU_DATE
FROM
 T_SEIKYUU_DENPYOU
WHERE
 SEIKYUU_DATE >= /*checkdate*/ AND KYOTEN_CD IN (/*kyotencd*/,'99') AND
 TORIHIKISAKI_CD = /*torihikisakicd*/ AND
 DELETE_FLG = 0
ORDER BY
 SEIKYUU_DATE DESC
