SELECT
 TOP 1 SEISAN_DATE
FROM
 T_SEISAN_DENPYOU
WHERE
 SEISAN_DATE >= /*checkdate*/ AND KYOTEN_CD IN (/*kyotencd*/,'99') AND
 TORIHIKISAKI_CD = /*torihikisakicd*/ AND
 DELETE_FLG = 0
ORDER BY
 SEISAN_DATE DESC
