SELECT
	TMLU.TORIHIKISAKI_CD
	,TMLU.YEAR
	,TMLU.MONTH
	,'売上' AS KUBUN
FROM
	T_MONTHLY_LOCK_UR TMLU
WHERE
	TMLU.DELETE_FLG = 0
	/*IF !data.YEAR.IsNull*/ AND TMLU.YEAR >= /*data.YEAR*/2015 /*END*/

UNION ALL

SELECT
	TMLS.TORIHIKISAKI_CD
	,TMLS.YEAR
	,TMLS.MONTH
	,'支払' AS KUBUN
FROM
	T_MONTHLY_LOCK_SH TMLS
WHERE
	TMLS.DELETE_FLG = 0
	/*IF !data.YEAR.IsNull*/ AND TMLS.YEAR >= /*data.YEAR*/2015 /*END*/

UNION ALL

SELECT
	'' AS TORIHIKISAKI_CD
	,TMLZ.YEAR
	,TMLZ.MONTH
	,'在庫' AS KUBUN
FROM
	T_MONTHLY_LOCK_ZAIKO TMLZ
WHERE
	TMLZ.DELETE_FLG = 0
	/*IF !data.YEAR.IsNull*/ AND TMLZ.YEAR >= /*data.YEAR*/2015 /*END*/