--売上・支払どちらかの伝票が発生していなくてもデータは作られるのでどちらしかない場合はありえないが念のためUINION
SELECT
	*
FROM
(
	SELECT
		YEAR, MONTH
	FROM
		T_MONTHLY_LOCK_UR
	WHERE
		DELETE_FLG = 0
	UNION ALL
	SELECT
		YEAR, MONTH
	FROM
		T_MONTHLY_LOCK_SH
	WHERE
		DELETE_FLG = 0
) MONTHLY_LOCK
ORDER BY MONTHLY_LOCK.YEAR DESC, MONTHLY_LOCK.MONTH DESC