SELECT M_GYOUSHA.GYOUSHA_CD
     , ISNULL(M_GYOUSHA.GYOUSHA_NAME1,'') + ISNULL(M_GYOUSHA.GYOUSHA_NAME2,'') AS GYOUSHA_NAME
     , ISNULL(M_GYOUSHA.GYOUSHA_NAME1,'') AS GYOUSHA_NAME1
     , ISNULL(M_GYOUSHA.GYOUSHA_NAME2,'') AS GYOUSHA_NAME2
     , M_GYOUSHA.GYOUSHA_NAME_RYAKU
	 , M_GYOUSHA.GYOUSHA_FURIGANA
	 , M_GYOUSHA.GYOUSHA_POST
	 , M_TODOUFUKEN.TODOUFUKEN_NAME
--	 , M_TODOUFUKEN.TODOUFUKEN_NAME_RYAKU
	 , ISNULL(M_TODOUFUKEN.TODOUFUKEN_NAME,'') + ISNULL(M_GYOUSHA.GYOUSHA_ADDRESS1,'') + ISNULL(M_GYOUSHA.GYOUSHA_ADDRESS2,'') AS GYOUSHA_ADDRESS
	 , M_GYOUSHA.GYOUSHA_TEL 
     ,M_GYOUSHA.TEKIYOU_BEGIN
     ,M_GYOUSHA.TEKIYOU_END
  FROM M_GYOUSHA 
  LEFT JOIN M_TODOUFUKEN 
    ON M_GYOUSHA.GYOUSHA_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD 
	   AND M_TODOUFUKEN.DELETE_FLG = 'false'
 WHERE 
/*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
 M_GYOUSHA.DELETE_FLG = 'false'
-- ELSE
 1 = 1
/*END*/
/*IF data.GYOUSHA_CD != null && data.GYOUSHA_CD != ''*/ AND M_GYOUSHA.GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/
/*IF data.GYOUSHAKBN_MANI != null && data.GYOUSHAKBN_MANI != ''*/ AND M_GYOUSHA.GYOUSHAKBN_MANI = /*data.GYOUSHAKBN_MANI*//*END*/
/*IF data.HAISHUTSU_NIZUMI_GYOUSHA_KBN != null && data.HAISHUTSU_NIZUMI_GYOUSHA_KBN != ''*/ AND M_GYOUSHA.HAISHUTSU_NIZUMI_GYOUSHA_KBN = /*data.HAISHUTSU_NIZUMI_GYOUSHA_KBN*//*END*/
/*IF data.SHOBUN_NIOROSHI_GYOUSHA_KBN != null && data.SHOBUN_NIOROSHI_GYOUSHA_KBN != ''*/ AND M_GYOUSHA.SHOBUN_NIOROSHI_GYOUSHA_KBN = /*data.SHOBUN_NIOROSHI_GYOUSHA_KBN*//*END*/
/*IF data.UNPAN_JUTAKUSHA_KAISHA_KBN != null && data.UNPAN_JUTAKUSHA_KAISHA_KBN != ''*/ AND M_GYOUSHA.UNPAN_JUTAKUSHA_KAISHA_KBN = /*data.UNPAN_JUTAKUSHA_KAISHA_KBN*//*END*/

/*IF (data.TSUMIKAEHOKAN_KBN != null && data.TSUMIKAEHOKAN_KBN != '') || (data.SAISHUU_SHOBUNJOU_KBN != null && data.SAISHUU_SHOBUNJOU_KBN != '')*/
 AND EXISTS ( SELECT * FROM M_GENBA 
    WHERE M_GYOUSHA.GYOUSHA_CD = M_GENBA.GYOUSHA_CD 
     /*IF data.TSUMIKAEHOKAN_KBN != null && data.TSUMIKAEHOKAN_KBN != ''*/
     AND  M_GENBA.TSUMIKAEHOKAN_KBN = /*data.TSUMIKAEHOKAN_KBN*/
	 /*END*/
     /*IF data.SAISHUU_SHOBUNJOU_KBN != null && data.SAISHUU_SHOBUNJOU_KBN != ''*/
     AND  M_GENBA.SAISHUU_SHOBUNJOU_KBN = /*data.SAISHUU_SHOBUNJOU_KBN*/
	 /*END*/
   ) 
/*END*/
