SELECT TME.SYSTEM_ID,
       TME.SEQ, 
	   TMD.LAST_SBN_GYOUSHA_CD,
	   MG.GYOUSHA_NAME1 + MG.GYOUSHA_NAME2 AS GYOUSHA_NAME,
	   TMD.LAST_SBN_GENBA_CD,
	   MGA.GENBA_NAME1 + MGA.GENBA_NAME2 AS GENBA_NAME
 FROM T_MANIFEST_ENTRY AS TME WITH(NOLOCK)
 INNER JOIN T_MANIFEST_DETAIL AS TMD WITH(NOLOCK)
     ON TME.SYSTEM_ID = TMD.SYSTEM_ID 
    AND TME.SEQ = TMD.SEQ
LEFT OUTER JOIN M_GYOUSHA AS MG WITH(NOLOCK)
ON TMD.LAST_SBN_GYOUSHA_CD = MG.GYOUSHA_CD
AND MG.DELETE_FLG = 'false'
AND (MG.TEKIYOU_BEGIN < GETDATE() OR MG.TEKIYOU_BEGIN IS NULL )
AND (MG.TEKIYOU_END   > GETDATE() OR MG.TEKIYOU_END   IS NULL )
LEFT OUTER JOIN M_GENBA AS MGA WITH(NOLOCK) 
ON TMD.LAST_SBN_GYOUSHA_CD = MGA.GYOUSHA_CD 
AND TMD.LAST_SBN_GENBA_CD = MGA.GENBA_CD
AND MGA.DELETE_FLG = 'false'
AND (MGA.TEKIYOU_BEGIN < GETDATE() OR MGA.TEKIYOU_BEGIN IS NULL )
AND (MGA.TEKIYOU_END   > GETDATE() OR MGA.TEKIYOU_END   IS NULL )
WHERE 
TME.DELETE_FLG = 'false'
AND TME.HAIKI_KBN_CD = /*data.HAIKI_KBN_CD*/ 
 /*IF data.SYSTEM_ID != null && data.SYSTEM_ID != ''*/ AND TMD.DETAIL_SYSTEM_ID = /*data.SYSTEM_ID*//*END*/
/*IF data.MANIFEST_ID != null && data.MANIFEST_ID != ''*/ AND TME.MANIFEST_ID = /*data.MANIFEST_ID*//*END*/