SELECT MHS.HAIKI_KBN_CD
     , MHS.HAIKI_SHURUI_CD
     , MMK.HAIKI_NAME_CD
     , MMK.UNIT_CD
     , MMK.NISUGATA_CD
     , MMK.KANSANSHIKI
     , MMK.KANSANCHI
     , CASE MMK.KANSANSHIKI 
            WHEN 0 THEN CAST(/*data.HAIKI_SUU*/ AS NUMERIC(14,5)) * MMK.KANSANCHI 
            WHEN 1 THEN CAST(/*data.HAIKI_SUU*/ AS NUMERIC(14,5)) / MMK.KANSANCHI 
            ELSE 0 
       END AS KANSAN_CHI

  FROM M_HAIKI_SHURUI AS MHS

 INNER JOIN M_MANIFEST_KANSAN AS MMK 
    ON MHS.HOUKOKUSHO_BUNRUI_CD = MMK.HOUKOKUSHO_BUNRUI_CD 
   AND MMK.DELETE_FLG = 'false'
   AND MMK.HAIKI_NAME_CD = /*data.HAIKI_NAME_CD*/
   AND MMK.UNIT_CD = /*data.UNIT_CD*/
   AND MMK.NISUGATA_CD = /*data.NISUGATA_CD*/

 WHERE MHS.DELETE_FLG = 'false'
   AND MHS.HAIKI_KBN_CD = /*data.HAIKI_KBN_CD*/
   AND MHS.HAIKI_SHURUI_CD = /*data.HAIKI_SHURUI_CD*/
