SELECT M_SHAIN.SHAIN_CD
     , M_SHAIN.SHAIN_NAME
--     , M_SHAIN.SHAIN_NAME_RYAKU
  FROM M_SHAIN
 INNER JOIN M_SHOBUN_TANTOUSHA
    ON M_SHAIN.SHAIN_CD = M_SHOBUN_TANTOUSHA.SHAIN_CD 
   AND M_SHOBUN_TANTOUSHA.DELETE_FLG = 'false'
 WHERE M_SHAIN.DELETE_FLG = 'false'
   AND M_SHAIN.SHOBUN_TANTOU_KBN = 'true'
   AND M_SHAIN.SHAIN_CD = /*data.SHAIN_CD*/