SELECT TMDP.SYSTEM_ID
     , TMDP.SEQ
     , TMDP.REC_NO
     , TMDP.HAIKI_SHURUI_CD
     , TMDP.HAIKI_SHURUI_NAME
     , TMDP.HAIKI_SUURYOU
     , TMDP.PRT_FLG
  FROM T_MANIFEST_PT_DETAIL_PRT TMDP
--  left join T_MANIFEST_ENTRY TME 
--    on TME.SYSTEM_ID=TMDP.SYSTEM_ID 
--   AND TME.SEQ=TMDP.SEQ
-- WHERE TME.DELETE_FLG = 0
 WHERE TMDP.SYSTEM_ID = /*data.SYSTEM_ID*/ 
   AND TMDP.SEQ =  /*data.SEQ*/