SELECT TMDP.SYSTEM_ID
     , TMDP.SEQ
     , TMDP.REC_NO
     , TMDP.HAIKI_SHURUI_CD
     , TMDP.HAIKI_SHURUI_NAME
     , TMDP.HAIKI_SUURYOU
     , TMDP.PRT_FLG
  FROM T_MANIFEST_ENTRY TME WITH(NOLOCK) 
 INNER JOIN T_MANIFEST_DETAIL_PRT TMDP WITH(NOLOCK)
    ON TME.SYSTEM_ID = TMDP.SYSTEM_ID 
   AND TME.SEQ = TMDP.SEQ
   AND TME.DELETE_FLG = 'false'
 WHERE TMDP.SYSTEM_ID = /*data.SYSTEM_ID*/ 
   AND TMDP.SEQ =  /*data.SEQ*/