SELECT TMPD.SYSTEM_ID
     , TMPD.SEQ
--     , TMPD.DETAIL_SYSTEM_ID
     , NULL AS DETAIL_SYSTEM_ID
--     , CAST(TMPD.TIME_STAMP AS int) AS TIME_STAMP
     , NULL AS TIME_STAMP

	 --廃棄物種類CD
     , TMPD.HAIKI_SHURUI_CD

	 --廃棄物種類名
     , MHS.HAIKI_SHURUI_NAME_RYAKU AS HAIKI_SHURUI_NAME
     --, MHS.HAIKI_SHURUI_NAME

	 --廃棄物の名称CD
     , TMPD.HAIKI_NAME_CD
     
	 --廃棄物の名称名
     , MHN.HAIKI_NAME_RYAKU AS HAIKI_NAME
     --, MHN.HAIKI_NAME

	 --荷姿CD
	 , TMPD.NISUGATA_CD

	 --荷姿名
     , MN.NISUGATA_NAME

	 --割合
     , TMPD.WARIAI

	 --数量
     , TMPD.HAIKI_SUU

	 --単位CD
     , TMPD.HAIKI_UNIT_CD

	 --単位名
     , MU.UNIT_NAME

	 --換算後数量
     , TMPD.KANSAN_SUU

	 --減容後数量
     , TMPD.GENNYOU_SUU

	 --処分方法CD
     , TMPD.SBN_HOUHOU_CD

	 --処分方法名
     , MSH.SHOBUN_HOUHOU_NAME_RYAKU AS SHOBUN_HOUHOU_NAME
     --, MSH.SHOBUN_HOUHOU_NAME

	 --処分終了日
     , TMPD.SBN_END_DATE

	 --最終処分終了日
     , TMPD.LAST_SBN_END_DATE AS LAST_SBN_END_DATE

	 --最終処分業者CD
     , TMPD.LAST_SBN_GYOUSHA_CD AS LAST_SBN_GYOUSHA_CD

	 --最終処分業者名
     --, MG.GYOUSHA_NAME_RYAKU AS GYOUSHA_NAME_RYAKU
     , MG.GYOUSHA_NAME1 + MG.GYOUSHA_NAME2 AS GYOUSHA_NAME

	 --最終処分場所CD
     , TMPD.LAST_SBN_GENBA_CD AS LAST_SBN_GENBA_CD

	 --最終処分場所名
     --, MGA.GENBA_NAME_RYAKU AS GENBA_NAME_RYAKU
     , MGA.GENBA_NAME1 + MGA.GENBA_NAME2 AS GENBA_NAME

	 --二次マニ交付番号
	 , '' AS NEXT_SYSTEM_ID

  FROM T_MANIFEST_PT_ENTRY AS TMPE WITH(NOLOCK)
 INNER JOIN T_MANIFEST_PT_DETAIL AS TMPD WITH(NOLOCK)
    ON TMPE.SYSTEM_ID = TMPD.SYSTEM_ID 
   AND TMPE.SEQ = TMPD.SEQ
  LEFT OUTER JOIN M_HAIKI_SHURUI AS MHS WITH(NOLOCK)
    ON TMPE.HAIKI_KBN_CD = MHS.HAIKI_KBN_CD 
   AND TMPD.HAIKI_SHURUI_CD = MHS.HAIKI_SHURUI_CD
  LEFT OUTER JOIN M_HAIKI_NAME AS MHN WITH(NOLOCK)
    ON TMPD.HAIKI_NAME_CD = MHN.HAIKI_NAME_CD
  LEFT OUTER JOIN M_NISUGATA AS MN WITH(NOLOCK)
    ON TMPD.NISUGATA_CD = MN.NISUGATA_CD
  LEFT OUTER JOIN M_UNIT AS MU WITH(NOLOCK)
    ON TMPD.HAIKI_UNIT_CD = MU.UNIT_CD
  LEFT OUTER JOIN M_SHOBUN_HOUHOU AS MSH WITH(NOLOCK)
    ON TMPD.SBN_HOUHOU_CD = MSH.SHOBUN_HOUHOU_CD
  LEFT OUTER JOIN M_GYOUSHA AS MG WITH(NOLOCK)
    ON TMPD.LAST_SBN_GYOUSHA_CD = MG.GYOUSHA_CD
  LEFT OUTER JOIN M_GENBA AS MGA WITH(NOLOCK) 
    ON TMPD.LAST_SBN_GYOUSHA_CD = MGA.GYOUSHA_CD 
   AND TMPD.LAST_SBN_GENBA_CD = MGA.GENBA_CD

-- WHERE TMPE.DELETE_FLG = 'false'
 WHERE TMPE.SYSTEM_ID = /*data.SYSTEM_ID*/ 
   AND TMPE.SEQ =  /*data.SEQ*/
-- DETAIL_SYSTEM_IDやTIME_STAMPがnullであるため並び順を指定しないとキー順に並ばない可能性がある
ORDER BY
    TMPD.SYSTEM_ID, TMPD.SEQ, TMPD.DETAIL_SYSTEM_ID