SELECT TMD.LAST_SBN_END_DATE
 FROM T_MANIFEST_ENTRY AS TME WITH(NOLOCK)
 INNER JOIN T_MANIFEST_DETAIL AS TMD WITH(NOLOCK)
     ON TME.SYSTEM_ID = TMD.SYSTEM_ID 
   AND TME.SEQ = TMD.SEQ
   WHERE  TME.DELETE_FLG = 'false'
AND TME.HAIKI_KBN_CD = /*data.HAIKI_KBN_CD*/ 
 /*IF data.SYSTEM_ID != null && data.SYSTEM_ID != ''*/ AND TMD.DETAIL_SYSTEM_ID = /*data.SYSTEM_ID*//*END*/
/*IF data.MANIFEST_ID != null && data.MANIFEST_ID != ''*/ AND TME.MANIFEST_ID = /*data.MANIFEST_ID*//*END*/