SELECT HAIKI_SHURUI_CD
     , HAIKI_SHURUI_NAME 
     , HAIKI_SHURUI_NAME_RYAKU 
  FROM M_HAIKI_SHURUI
 WHERE DELETE_FLG = 'false'
   AND HAIKI_KBN_CD = /*data.HAIKI_KBN_CD*/ 
/*IF data.HAIKI_SHURUI_CD != null && data.HAIKI_SHURUI_CD != ''*/ AND HAIKI_SHURUI_CD = /*data.HAIKI_SHURUI_CD*/ /*END*/ 
/*IF data.FROM_HAIKI_SHURUI_CD != null && data.FROM_HAIKI_SHURUI_CD != ''*/ AND HAIKI_SHURUI_CD > /*data.FROM_HAIKI_SHURUI_CD*/ /*END*/ 
/*IF data.TO_HAIKI_SHURUI_CD != null && data.TO_HAIKI_SHURUI_CD != ''*/ AND HAIKI_SHURUI_CD < /*data.TO_HAIKI_SHURUI_CD*/ /*END*/ 