-- SYSTEMIDからR18_EXの情報を取得する
SELECT
    EX_AND_MIX.*
FROM
    (
        SELECT
            EX.*,
            CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL
                THEN MIX.DETAIL_SYSTEM_ID
                ELSE EX.SYSTEM_ID
            END AS RELATION_SYSTEM_ID
        FROM
            DT_R18_EX AS EX WITH(NOLOCK)
            LEFT JOIN DT_R18_MIX AS MIX WITH(NOLOCK) ON EX.KANRI_ID = MIX.KANRI_ID AND MIX.DELETE_FLG = 0
        WHERE
            EX.DELETE_FLG = 0
    ) AS EX_AND_MIX
WHERE
    EX_AND_MIX.RELATION_SYSTEM_ID = /*SYSTEM_ID*/0
    AND EX_AND_MIX.DELETE_FLG = 0