--No.001:業者CD
SELECT M_GYOUSHA.GYOUSHA_CD
--No.002:現場CD
     , M_GENBA.GENBA_CD
--排出事業者区分
--     , M_GYOUSHA.HAISHUTSU_JIGYOUSHA_KBN
--運搬受託者区分
--     , M_GYOUSHA.UNPAN_JUTAKUSHA_KBN
--処分受託者区分
--     , M_GYOUSHA.SHOBUN_JUTAKUSHA_KBN

	 , ISNULL(M_GENBA.GENBA_NAME1,'') + ISNULL(M_GENBA.GENBA_NAME2,'') AS GENBA_NAME
	 , ISNULL(M_GENBA.GENBA_NAME1,'') AS GENBA_NAME1
	 , ISNULL(M_GENBA.GENBA_NAME2,'') AS GENBA_NAME2
--No.007:現場略称名
     , M_GENBA.GENBA_NAME_RYAKU
--No.009:現場TEL
     , M_GENBA.GENBA_TEL
--No.016:現場郵便番号
     , M_GENBA.GENBA_POST
--No.018:現場住所1
--     , M_GENBA.GENBA_ADDRESS1 
--No.019:現場住所2
--     , M_GENBA.GENBA_ADDRESS2 
	 , M_TODOUFUKEN.TODOUFUKEN_NAME
     , ISNULL(M_TODOUFUKEN.TODOUFUKEN_NAME,'') + ISNULL(M_GENBA.GENBA_ADDRESS1,'') + ISNULL(M_GENBA.GENBA_ADDRESS2,'') AS GENBA_ADDRESS
--No.062:排出事業場/荷積現場区分
     , M_GENBA.HAISHUTSU_NIZUMI_GENBA_KBN
--No.063:積替保管区分
     , M_GENBA.TSUMIKAEHOKAN_KBN
--No.064:処分事業場/荷降現場区分
     , M_GENBA.SHOBUN_NIOROSHI_GENBA_KBN
--No.065:最終処分場区分
     , M_GENBA.SAISHUU_SHOBUNJOU_KBN
--No.070:処分先No
     , M_GENBA.SHOBUNSAKI_NO
     ,M_GENBA.TEKIYOU_BEGIN
     ,M_GENBA.TEKIYOU_END
  FROM M_GYOUSHA
 INNER JOIN M_GENBA 
    ON M_GYOUSHA.GYOUSHA_CD = M_GENBA.GYOUSHA_CD
   /*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
   AND M_GENBA.DELETE_FLG = 'false'
   /*END*/
  LEFT JOIN M_TODOUFUKEN 
    ON M_GENBA.GENBA_TODOUFUKEN_CD = M_TODOUFUKEN.TODOUFUKEN_CD 
   /*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
   AND M_TODOUFUKEN.DELETE_FLG = 'false'
   /*END*/
 WHERE 
/*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
 M_GYOUSHA.DELETE_FLG = 'false'
-- ELSE
 1 = 1
/*END*/
/*IF data.GYOUSHA_CD != null && data.GYOUSHA_CD != ''*/ AND M_GYOUSHA.GYOUSHA_CD = /*data.GYOUSHA_CD*//*END*/
/*IF data.GENBA_CD != null && data.GENBA_CD != ''*/ AND M_GENBA.GENBA_CD = /*data.GENBA_CD*//*END*/
/*IF data.GYOUSHAKBN_MANI != null && data.GYOUSHAKBN_MANI != ''*/ AND M_GYOUSHA.GYOUSHAKBN_MANI = /*data.GYOUSHAKBN_MANI*//*END*/
/*IF data.HAISHUTSU_NIZUMI_GYOUSHA_KBN != null && data.HAISHUTSU_NIZUMI_GYOUSHA_KBN != ''*/ AND M_GYOUSHA.HAISHUTSU_NIZUMI_GYOUSHA_KBN = /*data.HAISHUTSU_NIZUMI_GYOUSHA_KBN*//*END*/
/*IF data.SHOBUN_NIOROSHI_GYOUSHA_KBN != null && data.SHOBUN_NIOROSHI_GYOUSHA_KBN != ''*/ AND M_GYOUSHA.SHOBUN_NIOROSHI_GYOUSHA_KBN = /*data.SHOBUN_NIOROSHI_GYOUSHA_KBN*//*END*/
/*IF data.HAISHUTSU_NIZUMI_GENBA_KBN != null && data.HAISHUTSU_NIZUMI_GENBA_KBN != ''*/ AND M_GENBA.HAISHUTSU_NIZUMI_GENBA_KBN = /*data.HAISHUTSU_NIZUMI_GENBA_KBN*//*END*/
/*IF data.SAISHUU_SHOBUNJOU_KBN != null && data.SAISHUU_SHOBUNJOU_KBN != ''*/ AND M_GENBA.SAISHUU_SHOBUNJOU_KBN = /*data.SAISHUU_SHOBUNJOU_KBN*//*END*/
/*IF data.SHOBUN_NIOROSHI_GENBA_KBN != null && data.SHOBUN_NIOROSHI_GENBA_KBN != ''*/ AND M_GENBA.SHOBUN_NIOROSHI_GENBA_KBN = /*data.SHOBUN_NIOROSHI_GENBA_KBN*//*END*/
/*IF data.TSUMIKAEHOKAN_KBN != null && data.TSUMIKAEHOKAN_KBN != ''*/ AND M_GENBA.TSUMIKAEHOKAN_KBN = /*data.TSUMIKAEHOKAN_KBN*//*END*/
