SELECT
	ET.SYSTEM_ID
	,ET.SEQ
	,ET.KYOTEN_CD
	,KY.KYOTEN_NAME_RYAKU
	,ET.SHINSEI_NUMBER
	,ET.SHINSEI_DATE
	,ET.SHINSEISHA_CD
	,SH.SHAIN_NAME_RYAKU
	,ET.JYUYOUDO_CD
	,JU.JYUYOUDO_NAME
	,ET.NAIYOU_CD
	,NA.NAIYOU_NAME
	,DSS.SHINSEI_STATUS
	,ET.DENSHI_SHINSEI_ROUTE_CD
	,RN.DENSHI_SHINSEI_ROUTE_NAME
	,ET.SHINSEISHA_COMMENT
	,ET.MITSUMORI_TENPU
	,
	CASE
		WHEN HT.TORIHIKISAKI_CD_AFTER IS NOT NULL THEN NULL
		ELSE ET.HIKIAI_TORIHIKISAKI_CD
	END AS HIKIAI_TORIHIKISAKI_CD
	,
	CASE
		WHEN HT.TORIHIKISAKI_CD_AFTER IS NOT NULL THEN NULL
		ELSE HT.TORIHIKISAKI_NAME_RYAKU
	END AS HIKIAI_TORIHIKISAKI_NAME
	,
	CASE
		WHEN HGY.GYOUSHA_CD_AFTER IS NOT NULL THEN NULL
		ELSE ET.HIKIAI_GYOUSHA_CD
	END AS HIKIAI_GYOUSHA_CD
	,
	CASE
		WHEN HGY.GYOUSHA_CD_AFTER IS NOT NULL THEN NULL
		ELSE HGY.GYOUSHA_NAME_RYAKU
	END AS HIKIAI_GYOUSHA_NAME
	,ET.HIKIAI_GENBA_CD
	,ET.GENBA_NAME_RYAKU AS HIKIAI_GENBA_NAME
	,
	CASE
		WHEN HT.TORIHIKISAKI_CD_AFTER IS NOT NULL THEN HT.TORIHIKISAKI_CD_AFTER
		ELSE ET.TORIHIKISAKI_CD
	END AS TORIHIKISAKI_CD
	,
	CASE
		WHEN HT.TORIHIKISAKI_CD_AFTER IS NOT NULL THEN (SELECT TORIHIKISAKI_NAME_RYAKU FROM M_TORIHIKISAKI WHERE TORIHIKISAKI_CD = HT.TORIHIKISAKI_CD_AFTER)
		ELSE TR.TORIHIKISAKI_NAME_RYAKU
	END AS TORIHIKISAKI_NAME
	,
	CASE
		WHEN HGY.GYOUSHA_CD_AFTER IS NOT NULL THEN HGY.GYOUSHA_CD_AFTER
		ELSE ET.GYOUSHA_CD
	END AS GYOUSHA_CD
	,
	CASE
		WHEN HGY.GYOUSHA_CD_AFTER IS NOT NULL THEN (SELECT GYOUSHA_NAME_RYAKU FROM M_GYOUSHA WHERE GYOUSHA_CD = HGY.GYOUSHA_CD_AFTER)
		ELSE GY.GYOUSHA_NAME_RYAKU
	END AS GYOUSHA_NAME
	,ET.GENBA_CD
	,GE.GENBA_NAME_RYAKU AS GENBA_NAME
	,DSS.UPDATE_NUM
	,DSS.SHINSEI_STATUS_CD
	,DSS.CREATE_USER AS STATUS_CREATE_USER
	,DSS.CREATE_DATE AS STATUS_CREATE_DATE
	,DSS.CREATE_PC AS STATUS_CREATE_PC
	,DSS.TIME_STAMP AS STATUS_TIME_STAMP
FROM
	(
		--引合現場以外
		SELECT
			SE.*
			,'' AS GENBA_NAME_RYAKU
		FROM
			T_DENSHI_SHINSEI_ENTRY SE
		WHERE
			SE.SHINSEI_MASTER_KBN NOT IN (6,7)
		UNION ALL
		--引合現場(既存業者)
		SELECT
			SE.*
			,HGE.GENBA_NAME_RYAKU
		FROM
			T_DENSHI_SHINSEI_ENTRY SE
			INNER JOIN M_HIKIAI_GENBA HGE
				ON SE.SHINSEI_MASTER_KBN = 7
				AND SE.GYOUSHA_CD = HGE.GYOUSHA_CD
				AND SE.HIKIAI_GENBA_CD = HGE.GENBA_CD
				AND HGE.HIKIAI_GYOUSHA_USE_FLG = 0
		UNION ALL
		--引合現場(本登録前 引合業者)
		SELECT
			SE.*
			,HGE.GENBA_NAME_RYAKU
		FROM
			T_DENSHI_SHINSEI_ENTRY SE
			INNER JOIN M_HIKIAI_GYOUSHA HG
				ON SE.HIKIAI_GYOUSHA_CD = HG.GYOUSHA_CD
				AND SE.SHINSEI_MASTER_KBN = 6
				AND (HG.GYOUSHA_CD_AFTER IS NULL OR HG.GYOUSHA_CD_AFTER = '')
			INNER JOIN M_HIKIAI_GENBA HGE
				ON SE.HIKIAI_GYOUSHA_CD = HGE.GYOUSHA_CD
				AND SE.HIKIAI_GENBA_CD = HGE.GENBA_CD
				AND HGE.HIKIAI_GYOUSHA_USE_FLG = 1
		UNION ALL
		--引合現場(本登録後 引合業者)
		SELECT
			SE.*
			,HGE.GENBA_NAME_RYAKU
		FROM
			T_DENSHI_SHINSEI_ENTRY SE
			INNER JOIN M_HIKIAI_GYOUSHA HG
				ON SE.HIKIAI_GYOUSHA_CD = HG.GYOUSHA_CD
				AND SE.SHINSEI_MASTER_KBN = 6
				AND (HG.GYOUSHA_CD_AFTER IS NOT NULL AND HG.GYOUSHA_CD_AFTER <> '')
			INNER JOIN M_HIKIAI_GENBA HGE
				ON HG.GYOUSHA_CD_AFTER = HGE.GYOUSHA_CD
				AND SE.HIKIAI_GENBA_CD = HGE.GENBA_CD
				AND HGE.HIKIAI_GYOUSHA_USE_FLG = 0
	) ET
	LEFT JOIN T_DENSHI_SHINSEI_STATUS DSS
		ON DSS.SYSTEM_ID = ET.SYSTEM_ID
		AND DSS.SEQ = ET.SEQ
		AND DSS.DELETE_FLG = 0
	LEFT JOIN M_KYOTEN KY
		ON KY.KYOTEN_CD = ET.KYOTEN_CD
	LEFT JOIN M_SHAIN SH
		ON SH.SHAIN_CD = ET.SHINSEISHA_CD
	LEFT JOIN M_DENSHI_SHINSEI_JYUYOUDO JU
		ON JU.JYUYOUDO_CD = ET.JYUYOUDO_CD
	LEFT JOIN M_DENSHI_SHINSEI_NAIYOU NA
		ON NA.NAIYOU_CD = ET.NAIYOU_CD
	LEFT JOIN M_DENSHI_SHINSEI_ROUTE_NAME RN
		ON RN.DENSHI_SHINSEI_ROUTE_CD = ET.DENSHI_SHINSEI_ROUTE_CD
	LEFT JOIN M_HIKIAI_TORIHIKISAKI HT
		ON HT.TORIHIKISAKI_CD = ET.HIKIAI_TORIHIKISAKI_CD
	LEFT JOIN M_HIKIAI_GYOUSHA HGY
		ON HGY.GYOUSHA_CD = ET.HIKIAI_GYOUSHA_CD
	LEFT JOIN M_TORIHIKISAKI TR
		ON TR.TORIHIKISAKI_CD = ET.TORIHIKISAKI_CD
	LEFT JOIN M_GYOUSHA GY
		ON GY.GYOUSHA_CD = ET.GYOUSHA_CD
	LEFT JOIN M_GENBA GE
		ON GE.GYOUSHA_CD = ET.GYOUSHA_CD
		AND GE.GENBA_CD = ET.GENBA_CD
/*BEGIN*/
WHERE
	/*IF data.SYSTEM_ID != null*/ ET.SYSTEM_ID = /*data.SYSTEM_ID*/1 /*END*/
	/*IF data.SEQ != null*/ AND ET.SEQ = /*data.SEQ*/1 /*END*/
/*END*/