SELECT
 MSR.SHARYOU_CD,
 MSR.SHARYOU_NAME_RYAKU, 
 MSR.SHASYU_CD, 
 MSS.SHASHU_NAME_RYAKU,
 MSR.GYOUSHA_CD,
 GS.GYOUSHA_NAME_RYAKU
FROM
 M_SHARYOU MSR
 LEFT JOIN M_SHASHU MSS
 ON MSR.SHASYU_CD = MSS.SHASHU_CD
 LEFT JOIN M_GYOUSHA GS
 ON MSR.GYOUSHA_CD = GS.GYOUSHA_CD
WHERE
MSR.DELETE_FLG = 'False'
/*IF data.GYOUSHA_CD != null*/AND MSR.GYOUSHA_CD LIKE '%' + /*data.GYOUSHA_CD*/ + '%'/*END*/
/*IF data.GYOUSHA_NAME_RYAKU != null*/ AND GS.GYOUSHA_NAME_RYAKU LIKE '%' + /*data.GYOUSHA_NAME_RYAKU*/ + '%'/*END*/
/*IF data.SHARYOU_CD != null*/AND MSR.SHARYOU_CD LIKE '%' + /*data.SHARYOU_CD*/ + '%'/*END*/
/*IF data.SHARYOU_NAME_RYAKU != null*/AND MSR.SHARYOU_NAME_RYAKU LIKE '%' + /*data.SHARYOU_NAME_RYAKU*/ + '%'/*END*/
/*IF data.SHASYU_CD != null*/AND MSR.SHASYU_CD LIKE '%' + /*data.SHASYU_CD*/ + '%'/*END*/
/*IF data.SHASHU_NAME_RYAKU != null*/AND MSS.SHASHU_NAME_RYAKU LIKE '%' + /*data.SHASHU_NAME_RYAKU*/ + '%'/*END*/
ORDER BY       
 MSR.SHARYOU_CD, MSR.SHASYU_CD
