SELECT 
	CLOSED_DATE,
	BIKOU,
	TIME_STAMP
FROM 
	M_WORK_CLOSED_SHARYOU
where
	M_WORK_CLOSED_SHARYOU.GYOUSHA_CD = /*gyoushaCd*/
	AND
	M_WORK_CLOSED_SHARYOU.SHARYOU_CD = /*sharyouCd*/
	AND 
	CONVERT(CHAR(7), CLOSED_DATE, 111) = /*searchDate*/