SELECT *
FROM T_TEIKI_HAISHA_ENTRY
where
	UNPAN_GYOUSHA_CD = /*data.UNPAN_GYOUSHA_CD*/
	AND SHARYOU_CD = /*data.SHARYOU_CD*/
	AND CONVERT(CHAR(7), SAGYOU_DATE, 120) = CONVERT(CHAR(7), /*data.SAGYOU_DATE*/, 120)
	AND DELETE_FLG = 0