SELECT *
FROM T_UR_SH_ENTRY
where
	UNPAN_GYOUSHA_CD = /*data.UNPAN_GYOUSHA_CD*/
	AND SHARYOU_CD = /*data.SHARYOU_CD*/
	AND CONVERT(CHAR(7), DENPYOU_DATE, 120) = CONVERT(CHAR(7), /*data.DENPYOU_DATE*/, 120)
	AND DELETE_FLG = 0