SELECT
	DT_R18.MANIFEST_ID
   ,CASE WHEN ISDATE(DT_R18.HIKIWATASHI_DATE) = 0 THEN NULL ELSE CONVERT(DATETIME, DT_R18.HIKIWATASHI_DATE) END AS HIKIWATASHI_DATE
   ,MAX(DT_R19.UPN_ROUTE_NO) AS UPN_ROUTE_NO
   ,DT_R18.HST_SHA_EDI_MEMBER_ID
   ,DT_R18.HST_SHA_NAME
   ,DT_R18.HST_JOU_NAME
   ,M_DENSHI_HAIKI_SHURUI.HAIKI_SHURUI_NAME AS HAIKI_SHURUI_NAME
   ,(ISNULL(DT_R18.HAIKI_DAI_CODE, '') + ISNULL(DT_R18.HAIKI_CHU_CODE, '') + ISNULL(DT_R18.HAIKI_SHO_CODE, '')) AS HAIKI_SHURUI_CD
   ,DT_R18.HAIKI_NAME
   /*IF data.MANIFEST_REPORT_SUU_KBN == 1*/,DT_R18.HAIKI_KAKUTEI_SUU AS REPORT_SUU/*END*/
   /*IF data.MANIFEST_REPORT_SUU_KBN == 2*/,DT_R18.HAIKI_SUU AS REPORT_SUU/*END*/
   /*IF data.MANIFEST_REPORT_SUU_KBN == 3*/,DT_R19.UPN_SUU AS REPORT_SUU/*END*/
   /*IF data.MANIFEST_REPORT_SUU_KBN == 4*/,DT_R18.RECEPT_SUU AS REPORT_SUU/*END*/
   ,M_UNIT.UNIT_NAME_RYAKU AS REPORT_UNIT_NAME
   ,CASE WHEN ISDATE(DT_R18.SBN_END_DATE) <> 0 THEN CONVERT(DATETIME, DT_R18.SBN_END_DATE) END AS SBN_END_DATE
   ,CASE WHEN DT_R18_MIX_RELATION.DENOMINATOR IS NOT NULL THEN CAST(DT_R18_MIX_RELATION.NUMERATOR AS NVARCHAR) + '/' + (CAST(DT_R18_MIX_RELATION.DENOMINATOR AS NVARCHAR)) END AS RELATION_NUM
   ,CASE WHEN DT_R18_MIX_COMPLETE.DENOMINATOR IS NOT NULL THEN CAST(DT_R18_MIX_COMPLETE.NUMERATOR AS NVARCHAR) + '/' + (CAST(DT_R18_MIX_COMPLETE.DENOMINATOR AS NVARCHAR)) END AS COMPLETE_NUM
   ,(CASE DT_R18.UPN_ENDREP_FLAG WHEN 1 THEN 1 ELSE 0 END ) AS UPN_ENDREP_FLAG
   ,(CASE DT_R18.SBN_ENDREP_FLAG WHEN 1 THEN 1 ELSE 0 END ) AS SBN_ENDREP_FLAG
   ,(CASE DT_R18.LAST_SBN_ENDREP_FLAG WHEN 1 THEN 1 ELSE 0 END ) AS LAST_SBN_ENDREP_FLAG
   ,DT_R18_EX.SYSTEM_ID
   ,DT_MF_TOC.KANRI_ID
   ,DT_MF_TOC.LATEST_SEQ
FROM
	DT_R18
INNER JOIN
	DT_MF_TOC ON
	((DT_R18.KANRI_ID = DT_MF_TOC.KANRI_ID) AND (DT_R18.SEQ = DT_MF_TOC.LATEST_SEQ))
LEFT JOIN
	(SELECT * FROM DT_R18_EX WHERE DELETE_FLG = 0) AS DT_R18_EX ON
	DT_R18.KANRI_ID = DT_R18_EX.KANRI_ID
LEFT JOIN
	DT_R19 ON
	((DT_R18.KANRI_ID = DT_R19.KANRI_ID) AND (DT_R18.SEQ = DT_R19.SEQ))
LEFT JOIN
	(SELECT * FROM DT_R19_EX WHERE DELETE_FLG = 0) AS DT_R19_EX ON
	((DT_R18_EX.SYSTEM_ID = DT_R19_EX.SYSTEM_ID)
		AND (DT_R18_EX.SEQ = DT_R19_EX.SEQ)
		AND (DT_R18_EX.KANRI_ID = DT_R19_EX.KANRI_ID)
		AND (DT_R19.UPN_ROUTE_NO = DT_R19_EX.UPN_ROUTE_NO))
LEFT JOIN
	(SELECT * FROM DT_R18_MIX WHERE DELETE_FLG = 0) AS DT_R18_MIX ON
	((DT_R18_EX.KANRI_ID = DT_R18_MIX.KANRI_ID) AND (DT_R18_EX.SYSTEM_ID = DT_R18_MIX.SYSTEM_ID))
LEFT JOIN
	(SELECT * FROM M_DENSHI_HAIKI_SHURUI) AS M_DENSHI_HAIKI_SHURUI ON
	(ISNULL(DT_R18.HAIKI_DAI_CODE, '') + ISNULL(DT_R18.HAIKI_CHU_CODE, '') + ISNULL(DT_R18.HAIKI_SHO_CODE, '')) = M_DENSHI_HAIKI_SHURUI.HAIKI_SHURUI_CD
LEFT JOIN M_GYOUSHA AS HST_GYOUSHA
	ON DT_R18_EX.HST_GYOUSHA_CD = HST_GYOUSHA.GYOUSHA_CD
/*IF data.MANIFEST_REPORT_SUU_KBN == 1*/
LEFT JOIN M_UNIT
    ON M_UNIT.UNIT_CD = DT_R18.HAIKI_KAKUTEI_UNIT_CODE
/*END*/
/*IF data.MANIFEST_REPORT_SUU_KBN == 2*/
LEFT JOIN M_UNIT
    ON M_UNIT.UNIT_CD = DT_R18.HAIKI_UNIT_CODE
/*END*/
/*IF data.MANIFEST_REPORT_SUU_KBN == 3*/
LEFT JOIN M_UNIT
    ON M_UNIT.UNIT_CD = DT_R19.UPN_UNIT_CODE
/*END*/
/*IF data.MANIFEST_REPORT_SUU_KBN == 4*/
LEFT JOIN M_UNIT
    ON M_UNIT.UNIT_CD = DT_R18.RECEPT_UNIT_CODE
/*END*/
LEFT JOIN (
		SELECT
			MIX1.SYSTEM_ID
		   ,MIX1.KANRI_ID
		   ,ISNULL(MIX2.RELATION_NUM, 0) AS NUMERATOR
		   ,COUNT(MIX1.SYSTEM_ID) AS DENOMINATOR
		FROM
			DT_R18_MIX AS MIX1
		LEFT JOIN (
				SELECT
					SYSTEM_ID
				   ,KANRI_ID
				   ,COUNT(SYSTEM_ID) AS RELATION_NUM
				FROM
					DT_R18_MIX
				INNER JOIN
					(SELECT * FROM T_MANIFEST_RELATION WHERE ((DELETE_FLG = 0) AND (FIRST_HAIKI_KBN_CD = 4))) AS T_MANIFEST_RELATION ON
					DT_R18_MIX.DETAIL_SYSTEM_ID = T_MANIFEST_RELATION.FIRST_SYSTEM_ID
				WHERE
					((DT_R18_MIX.DELETE_FLG = 0) AND (DT_R18_MIX.SBN_ENDREP_KBN = 1))
				GROUP BY
					SYSTEM_ID, KANRI_ID
			) AS MIX2 ON
			((MIX1.SYSTEM_ID = MIX2.SYSTEM_ID) AND (MIX1.KANRI_ID = MIX2.KANRI_ID))
		WHERE
			((MIX1.DELETE_FLG = 0) AND (MIX1.SBN_ENDREP_KBN = 1))
		GROUP BY
			MIX1.SYSTEM_ID
		   ,MIX1.KANRI_ID
		   ,MIX2.RELATION_NUM
	) AS DT_R18_MIX_RELATION ON
	((DT_R18_MIX.SYSTEM_ID = DT_R18_MIX_RELATION.SYSTEM_ID) AND (DT_R18_MIX.KANRI_ID = DT_R18_MIX_RELATION.KANRI_ID))
LEFT JOIN (
		SELECT
			MIX1.SYSTEM_ID
		   ,MIX1.KANRI_ID
		   ,ISNULL(MIX2.COMPLETE_NUM, 0) AS NUMERATOR
		   ,COUNT(MIX1.SYSTEM_ID) AS DENOMINATOR
		FROM
			DT_R18_MIX AS MIX1
		LEFT JOIN (
				SELECT
					DT_R18_MIX.SYSTEM_ID
				   ,DT_R18_MIX.KANRI_ID
				   ,COUNT(DT_R18_MIX.SYSTEM_ID) AS COMPLETE_NUM
				FROM
					DT_R18_MIX
				LEFT JOIN
					( SELECT * FROM T_MANIFEST_RELATION WHERE ((DELETE_FLG = 0) AND (FIRST_HAIKI_KBN_CD = 4))) AS T_MANIFEST_RELATION ON
					DT_R18_MIX.DETAIL_SYSTEM_ID = T_MANIFEST_RELATION.FIRST_SYSTEM_ID
				LEFT JOIN (
						SELECT
							MD.SYSTEM_ID, MD.DETAIL_SYSTEM_ID
						FROM
							T_MANIFEST_DETAIL AS MD
						INNER JOIN
							T_MANIFEST_ENTRY AS ME ON
							((MD.SYSTEM_ID = ME.SYSTEM_ID) AND (MD.SEQ = ME.SEQ))
						LEFT JOIN (
								SELECT SYSTEM_ID, SEQ FROM T_MANIFEST_DETAIL
								WHERE ((LAST_SBN_END_DATE IS NULL) OR (LAST_SBN_GYOUSHA_CD IS NULL) OR (LAST_SBN_GENBA_CD IS NULL))
								GROUP BY SYSTEM_ID ,SEQ
							) AS MD_EX ON
							((MD.SYSTEM_ID = MD_EX.SYSTEM_ID) AND (MD.SEQ = MD_EX.SEQ))
						WHERE
							((ME.DELETE_FLG = 0) AND (MD_EX.SYSTEM_ID IS NULL))
						GROUP BY
							MD.SYSTEM_ID, MD.DETAIL_SYSTEM_ID
					) AS T_PAPER_MANIFEST ON
					T_MANIFEST_RELATION.NEXT_SYSTEM_ID = T_PAPER_MANIFEST.DETAIL_SYSTEM_ID
				LEFT JOIN (
						SELECT
							DT_R18_EX.SYSTEM_ID
						   ,DT_R13.KANRI_ID
						FROM
							DT_R18_EX
						INNER JOIN
							DT_R13 ON
							DT_R13.KANRI_ID = DT_R18_EX.KANRI_ID
						LEFT JOIN (
								SELECT KANRI_ID FROM DT_R13
								WHERE ((LAST_SBN_END_DATE IS NULL) OR (LAST_SBN_JOU_NAME IS NULL))
								GROUP BY KANRI_ID
							) AS R13_EX ON
							DT_R13.KANRI_ID = R13_EX.KANRI_ID
						WHERE
							(R13_EX.KANRI_ID IS NULL)
						GROUP BY
							DT_R18_EX.SYSTEM_ID
						   ,DT_R13.KANRI_ID
					) AS T_ELEC_MANIFEST ON
					T_MANIFEST_RELATION.NEXT_SYSTEM_ID = T_ELEC_MANIFEST.SYSTEM_ID
				WHERE
					(DT_R18_MIX.DELETE_FLG = 0)
					AND (
						(DT_R18_MIX.SBN_ENDREP_KBN = 2)
						OR ((T_MANIFEST_RELATION.FIRST_SYSTEM_ID IS NOT NULL) AND
						   ((CASE WHEN NEXT_HAIKI_KBN_CD = 4 THEN T_ELEC_MANIFEST.SYSTEM_ID ELSE T_PAPER_MANIFEST.SYSTEM_ID END) IS NOT NULL))
					)
				GROUP BY
					DT_R18_MIX.SYSTEM_ID
				   ,DT_R18_MIX.KANRI_ID
			) AS MIX2 ON
			((MIX1.SYSTEM_ID = MIX2.SYSTEM_ID) AND (MIX1.KANRI_ID = MIX2.KANRI_ID))
		WHERE
			MIX1.DELETE_FLG = 0
		GROUP BY
			MIX1.SYSTEM_ID
		   ,MIX1.KANRI_ID
		   ,MIX2.COMPLETE_NUM
	) AS DT_R18_MIX_COMPLETE ON
	((DT_R18_MIX.SYSTEM_ID = DT_R18_MIX_COMPLETE.SYSTEM_ID) AND (DT_R18_MIX.KANRI_ID = DT_R18_MIX_COMPLETE.KANRI_ID))
WHERE
    (DT_MF_TOC.KIND = 4 OR DT_MF_TOC.KIND = 5 OR DT_MF_TOC.KIND IS NULL)
	AND (DT_MF_TOC.STATUS_FLAG = 4)
    AND (ISNULL(DT_R18.FIRST_MANIFEST_FLAG, '') = '' OR ISNULL(HST_GYOUSHA.JISHA_KBN, 0) = 0)
	AND ((M_DENSHI_HAIKI_SHURUI.KONGOU_KBN = 1) OR (ISNULL(M_DENSHI_HAIKI_SHURUI.KONGOU_KBN, 0) = 0 AND DT_R18_MIX.SYSTEM_ID IS NOT NULL))
	AND (DT_R18_EX.SYSTEM_ID IS NOT NULL)
/*IF data.DATE_KBN == '1'*/AND ((CASE WHEN ISDATE(DT_R18.HIKIWATASHI_DATE) = 0 THEN NULL ELSE CONVERT(DATETIME, CONVERT(NVARCHAR, DT_R18.HIKIWATASHI_DATE, 111), 120) END) >= /*data.DATE_FROM*/ AND (CASE WHEN ISDATE(DT_R18.HIKIWATASHI_DATE) = 0 THEN NULL ELSE CONVERT(DATETIME, CONVERT(NVARCHAR, DT_R18.HIKIWATASHI_DATE, 111), 120) END) <= /*data.DATE_TO*/)/*END*/
/*IF data.DATE_KBN == '2'*/AND ((CASE WHEN ISDATE(DT_R19.UPN_END_DATE) = 0 THEN NULL ELSE CONVERT(DATETIME, CONVERT(NVARCHAR, DT_R19.UPN_END_DATE, 111), 120) END) >= /*data.DATE_FROM*/ AND (CASE WHEN ISDATE(DT_R19.UPN_END_DATE) = 0 THEN NULL ELSE CONVERT(DATETIME, CONVERT(NVARCHAR, DT_R19.UPN_END_DATE, 111), 120) END) <= /*data.DATE_TO*/)/*END*/
/*IF data.DATE_KBN == '3'*/AND ((CASE WHEN ISDATE(DT_R18.SBN_END_DATE) = 0 THEN NULL ELSE CONVERT(DATETIME, CONVERT(NVARCHAR, DT_R18.SBN_END_DATE, 111), 120) END) >= /*data.DATE_FROM*/ AND (CASE WHEN ISDATE(DT_R18.SBN_END_DATE) = 0 THEN NULL ELSE CONVERT(DATETIME, CONVERT(NVARCHAR, DT_R18.SBN_END_DATE, 111), 120) END) <= /*data.DATE_TO*/)/*END*/
/*IF data.DATE_KBN == '4'*/AND ((CASE WHEN ISDATE(DT_R18.LAST_SBN_END_DATE) = 0 THEN NULL ELSE CONVERT(DATETIME, CONVERT(NVARCHAR, DT_R18.LAST_SBN_END_DATE, 111), 120) END) >= /*data.DATE_FROM*/ AND (CASE WHEN ISDATE(DT_R18.LAST_SBN_END_DATE) = 0 THEN NULL ELSE CONVERT(DATETIME, CONVERT(NVARCHAR, DT_R18.LAST_SBN_END_DATE, 111), 120) END) <= /*data.DATE_TO*/)/*END*/
/*IF data.RELATION_SHOW_KBN == '1'*/AND (DT_R18_MIX_RELATION.NUMERATOR = DT_R18_MIX_RELATION.DENOMINATOR)/*END*/
/*IF data.RELATION_SHOW_KBN == '2'*/AND ((DT_R18_MIX_RELATION.NUMERATOR <> DT_R18_MIX_RELATION.DENOMINATOR) OR (DT_R18_MIX_RELATION.DENOMINATOR IS NULL))/*END*/
/*IF data.NEXT_SHOW_KBN == '1'*/AND (DT_R18_MIX_COMPLETE.NUMERATOR = DT_R18_MIX_COMPLETE.DENOMINATOR)/*END*/
/*IF data.NEXT_SHOW_KBN == '2'*/AND ((DT_R18_MIX_COMPLETE.NUMERATOR <> DT_R18_MIX_COMPLETE.DENOMINATOR) OR (DT_R18_MIX_COMPLETE.DENOMINATOR IS NULL))/*END*/
/*IF data.HST_GYOUSHA_CD != null*/AND DT_R18_EX.HST_GYOUSHA_CD = /*data.HST_GYOUSHA_CD*//*END*/
/*IF data.HST_GENBA_CD != null*/AND DT_R18_EX.HST_GENBA_CD = /*data.HST_GENBA_CD*//*END*/
/*IF data.SBN_GYOUSHA_CD != null*/AND DT_R18_EX.SBN_GYOUSHA_CD = /*data.SBN_GYOUSHA_CD*//*END*/
/*IF data.UPN_SAKI_GENBA_CD != null*/AND DT_R19_EX.UPNSAKI_GENBA_CD = /*data.UPN_SAKI_GENBA_CD*//*END*/
/*IF data.UPN_JYUTAKUSHA_CD != null*/AND DT_R19_EX.UPN_GYOUSHA_CD = /*data.UPN_JYUTAKUSHA_CD*//*END*/
/*IF data.HOUKOKUSHO_BUNRUI_CD != null*/AND M_DENSHI_HAIKI_SHURUI.HOUKOKUSHO_BUNRUI_CD = /*data.HOUKOKUSHO_BUNRUI_CD*//*END*/
/*IF data.DENSHI_HAIKI_SHURUI_CD != null*/AND (ISNULL(DT_R18.HAIKI_DAI_CODE, '') + ISNULL(DT_R18.HAIKI_CHU_CODE, '') + ISNULL(DT_R18.HAIKI_SHO_CODE, '')) = /*data.DENSHI_HAIKI_SHURUI_CD*//*END*/
/*IF data.MANIFEST_ID_FROM != null*/AND DT_R18.MANIFEST_ID >= /*data.MANIFEST_ID_FROM*//*END*/
/*IF data.MANIFEST_ID_TO != null*/AND DT_R18.MANIFEST_ID <= /*data.MANIFEST_ID_TO*//*END*/
GROUP BY
	DT_R18.MANIFEST_ID
   ,DT_R18.HIKIWATASHI_DATE
   ,DT_R18.HST_SHA_EDI_MEMBER_ID
   ,DT_R18.HST_SHA_NAME
   ,DT_R18.HST_JOU_NAME
   ,M_DENSHI_HAIKI_SHURUI.HAIKI_SHURUI_NAME
   ,DT_R18.HAIKI_DAI_CODE
   ,DT_R18.HAIKI_CHU_CODE
   ,DT_R18.HAIKI_SHO_CODE
   ,DT_R18.HAIKI_SAI_CODE
   ,DT_R18.HAIKI_NAME
   /*IF data.MANIFEST_REPORT_SUU_KBN == 1*/,DT_R18.HAIKI_KAKUTEI_SUU/*END*/
   /*IF data.MANIFEST_REPORT_SUU_KBN == 2*/,DT_R18.HAIKI_SUU/*END*/
   /*IF data.MANIFEST_REPORT_SUU_KBN == 3*/,DT_R19.UPN_SUU/*END*/
   /*IF data.MANIFEST_REPORT_SUU_KBN == 4*/,DT_R18.RECEPT_SUU/*END*/
   ,M_UNIT.UNIT_NAME_RYAKU
   ,DT_R18.SBN_END_DATE
   ,DT_R18_MIX_RELATION.NUMERATOR
   ,DT_R18_MIX_RELATION.DENOMINATOR
   ,DT_R18_MIX_COMPLETE.NUMERATOR
   ,DT_R18_MIX_COMPLETE.DENOMINATOR
   ,DT_R18.UPN_ENDREP_FLAG
   ,DT_R18.SBN_ENDREP_FLAG
   ,DT_R18.LAST_SBN_ENDREP_FLAG
   ,DT_R18_EX.SYSTEM_ID
   ,DT_MF_TOC.KANRI_ID
   ,DT_MF_TOC.LATEST_SEQ
ORDER BY
	DT_R18.MANIFEST_ID
   ,DT_R18.HIKIWATASHI_DATE