SELECT
     ISNULL(KON.HINMEI_CD,'') AS MEISAI_HINMEI_CD
	,ISNULL(HIN.HINMEI_NAME_RYAKU,'') AS HINMEI_NAME_RYAKU	
	,ISNULL(UNI.UNIT_NAME_RYAKU,'') AS UNIT_NAME_RYAKU	
	,KON.TANKA AS UTSUTSU_TANKA	
	,'' AS XIN_TANKA
	,ISNULL(HIN.SHURUI_CD,'') AS MEISAI_SHURUI_CD
	,ISNULL(MSHR.SHURUI_NAME_RYAKU,'') AS MEISAI_SHURUI_NAME_RYAKU
	,ISNULL(HIN.BUNRUI_CD,'') AS MEISAI_BUNRUI_CD
	,ISNULL(MBUR.BUNRUI_NAME_RYAKU,'') AS MEISAI_BUNRUI_NAME_RYAKU
    ,DENS.DENSHU_KBN_NAME_RYAKU AS DENSHU_KBN_RYAKU
    ,ISNULL(KON.TORIHIKISAKI_CD,'') AS MEISAI_TORIHIKISAKI_CD
	,ISNULL(MTORI.TORIHIKISAKI_NAME_RYAKU,'') AS MEISAI_TORIHIKISAKI_NAME_RYAKU
    ,ISNULL(KON.GYOUSHA_CD,'') AS MEISAI_GYOUSHA_CD
	,ISNULL(MGYOU.GYOUSHA_NAME_RYAKU,'') AS MEISAI_GYOUSHA_NAME_RYAKU
    ,ISNULL(KON.GENBA_CD,'') AS MEISAI_GENBA_CD
	,ISNULL(MGEN.GENBA_NAME_RYAKU,'') AS MEISAI_GENBA_NAME_RYAKU    
    ,ISNULL(KON.UNPAN_GYOUSHA_CD,'') AS MEISAI_UNPAN_GYOUSHA_CD
	,ISNULL(GYOU.GYOUSHA_NAME_RYAKU,'') AS MEISAI_UNPAN_GYOUSHA_RYAKU
    ,ISNULL(KON.NIOROSHI_GYOUSHA_CD,'') AS MEISAI_NIOROSHI_GYOUSHA_CD
	,ISNULL(GYOUSHA.GYOUSHA_NAME_RYAKU,'') AS MEISAI_NIOROSHI_GYOUSHA_RYAKU
    ,ISNULL(KON.NIOROSHI_GENBA_CD,'') AS MEISAI_NIOROSHI_GENBA_CD
	,ISNULL(GEN.GENBA_NAME_RYAKU,'') AS MEISAI_NIOROSHI_GENBA_RYAKU  
    ,KON.BIKOU AS MEISAI_BIKOU
    ,KON.TEKIYOU_BEGIN AS TEKIYOU_BEGIN
	,'' AS XIN_TEKIYOU_BEGIN
    ,KON.TEKIYOU_END AS TEKIYOU_END
	,KON.SYS_ID
	,ISNULL(KON.UNIT_CD,'') AS MEISAI_UNIT_CD
	,KON.DENSHU_KBN_CD AS DENSHU_KBN_CD
FROM
    dbo.M_KOBETSU_HINMEI_TANKA KON	
	LEFT JOIN dbo.M_TORIHIKISAKI MTORI ON MTORI.TORIHIKISAKI_CD = KON.TORIHIKISAKI_CD
	LEFT JOIN dbo.M_GYOUSHA MGYOU ON MGYOU.GYOUSHA_CD = KON.GYOUSHA_CD 
	LEFT JOIN dbo.M_GENBA MGEN ON MGEN.GYOUSHA_CD = KON.GYOUSHA_CD AND MGEN.GENBA_CD = KON.GENBA_CD
    LEFT JOIN dbo.M_GYOUSHA GYOU ON GYOU.GYOUSHA_CD = KON.UNPAN_GYOUSHA_CD
    LEFT JOIN dbo.M_GYOUSHA GYOUSHA ON GYOUSHA.GYOUSHA_CD = KON.NIOROSHI_GYOUSHA_CD
    LEFT JOIN dbo.M_DENSHU_KBN DENS ON DENS.DENSHU_KBN_CD = KON.DENSHU_KBN_CD
    LEFT JOIN dbo.M_HINMEI HIN ON HIN.HINMEI_CD = KON.HINMEI_CD
    LEFT JOIN dbo.M_UNIT UNI ON UNI.UNIT_CD = KON.UNIT_CD
    LEFT JOIN dbo.M_GENBA GEN ON GEN.GYOUSHA_CD = KON.NIOROSHI_GYOUSHA_CD AND GEN.GENBA_CD = KON.NIOROSHI_GENBA_CD
	LEFT JOIN dbo.M_SHURUI MSHR ON MSHR.SHURUI_CD = HIN.SHURUI_CD
	LEFT JOIN dbo.M_BUNRUI MBUR ON MBUR.BUNRUI_CD = HIN.BUNRUI_CD
WHERE
	KON.DENPYOU_KBN_CD =/*data.DENPYOU_KBN_CD.Value*/
	/*IF data.TORIHIKISAKI_CD != null && data.TORIHIKISAKI_CD != ''*/AND KON.TORIHIKISAKI_CD = /*data.TORIHIKISAKI_CD*/''/*END*/
	/*IF data.GYOUSHA_CD != null && data.GYOUSHA_CD != ''*/AND KON.GYOUSHA_CD = /*data.GYOUSHA_CD*/''/*END*/
	/*IF data.GENBA_CD != null && data.GENBA_CD != ''*/AND KON.GENBA_CD = /*data.GENBA_CD*/''/*END*/
	/*IF data.HINMEI_CD != null && data.HINMEI_CD != ''*/AND KON.HINMEI_CD LIKE '%' +  /*data.HINMEI_CD*/ + '%'/*END*/
	/*IF !data.UNIT_CD.IsNull*/AND KON.UNIT_CD = /*data.UNIT_CD.Value*/ /*END*/
	/*IF data.UNPAN_GYOUSHA_CD != null && data.UNPAN_GYOUSHA_CD != ''*/AND KON.UNPAN_GYOUSHA_CD LIKE '%' +  /*data.UNPAN_GYOUSHA_CD*/ + '%'/*END*/
	/*IF data.NIOROSHI_GYOUSHA_CD != null && data.NIOROSHI_GYOUSHA_CD != ''*/AND KON.NIOROSHI_GYOUSHA_CD LIKE '%' +  /*data.NIOROSHI_GYOUSHA_CD*/ + '%'/*END*/
	/*IF data.NIOROSHI_GENBA_CD != null && data.NIOROSHI_GENBA_CD != ''*/AND KON.NIOROSHI_GENBA_CD LIKE '%' +  /*data.NIOROSHI_GENBA_CD*/ + '%'/*END*/
	/*IF data.SHURUI_CD != null && data.SHURUI_CD != ''*/AND MSHR.SHURUI_CD LIKE '%' +  /*data.SHURUI_CD*/ + '%'/*END*/
	/*IF data.BUNRUI_CD != null && data.BUNRUI_CD != ''*/AND MBUR.BUNRUI_CD LIKE '%' +  /*data.BUNRUI_CD*/ + '%'/*END*/
	/*IF !data.TANK_FROM.IsNull*/AND KON.TANKA >= /*data.TANK_FROM.Value*/0/*END*/
	/*IF !data.TANK_TO.IsNull*/AND KON.TANKA <= /*data.TANK_TO.Value*/0/*END*/

	/*IF !data.TANK_TEKIYOU_BEGIN_START.IsNull && !data.TANK_TEKIYOU_BEGIN_END.IsNull*/
	AND CONVERT(DATETIME, KON.TEKIYOU_BEGIN, 111) >=  CONVERT(DATETIME, /*data.TANK_TEKIYOU_BEGIN_START*/'', 111)	
    AND CONVERT(DATETIME, KON.TEKIYOU_BEGIN, 111) <=  CONVERT(DATETIME, /*data.TANK_TEKIYOU_BEGIN_END*/'', 111)
	/*END*/

	/*IF !data.TANK_TEKIYOU_END_START.IsNull && !data.TANK_TEKIYOU_END_END.IsNull*/
	AND CONVERT(DATETIME, KON.TEKIYOU_END, 111) >=  CONVERT(DATETIME, /*data.TANK_TEKIYOU_END_START*/'', 111)
    AND CONVERT(DATETIME, KON.TEKIYOU_END, 111) <=  CONVERT(DATETIME, /*data.TANK_TEKIYOU_END_END*/'', 111)
	/*END*/

	/*IF !data.TANK_TEKIYOU_BEGIN_START.IsNull && data.TANK_TEKIYOU_BEGIN_END.IsNull*/
	AND CONVERT(DATETIME, KON.TEKIYOU_BEGIN, 111) >=  CONVERT(DATETIME, /*data.TANK_TEKIYOU_BEGIN_START*/'', 111)	
    /*END*/

	/*IF data.TANK_TEKIYOU_BEGIN_START.IsNull && !data.TANK_TEKIYOU_BEGIN_END.IsNull*/	
    AND CONVERT(DATETIME, KON.TEKIYOU_BEGIN, 111) <=  CONVERT(DATETIME, /*data.TANK_TEKIYOU_BEGIN_END*/'', 111)
	/*END*/

	/*IF data.TANK_TEKIYOU_END_START.IsNull && !data.TANK_TEKIYOU_END_END.IsNull*/
	AND CONVERT(DATETIME, KON.TEKIYOU_END, 111) <=  CONVERT(DATETIME, /*data.TANK_TEKIYOU_END_END*/'', 111)
	/*END*/

	/*IF !data.TANK_TEKIYOU_END_START.IsNull && data.TANK_TEKIYOU_END_END.IsNull*/
    AND CONVERT(DATETIME, KON.TEKIYOU_END, 111) >=  CONVERT(DATETIME, /*data.TANK_TEKIYOU_END_START*/'', 111)
	/*END*/
	AND ((CONVERT(DATETIME, CONVERT(nvarchar, GETDATE(), 111), 120) <= KON.TEKIYOU_END) OR KON.TEKIYOU_END IS NULL)
	AND KON.DELETE_FLG = 0
ORDER BY KON.HINMEI_CD, KON.UNIT_CD, KON.TORIHIKISAKI_CD, KON.GYOUSHA_CD, KON.GENBA_CD, KON.DENSHU_KBN_CD, KON.TEKIYOU_BEGIN, KON.TEKIYOU_END

