SELECT
    SYS_ID
   ,KON.TEKIYOU_BEGIN AS TEKIYOU_BEGIN	
   ,KON.TEKIYOU_END AS TEKIYOU_END
FROM
    dbo.M_KOBETSU_HINMEI_TANKA KON	
WHERE
    KON.DENPYOU_KBN_CD = /*data.DENPYOU_KBN_CD.Value*/
    AND KON.HINMEI_CD =/*data.HINMEI_CD*/
	AND KON.UNIT_CD =/*data.UNIT_CD*/
	AND KON.DENSHU_KBN_CD =/*data.DENSHU_KBN_CD.Value*/
	AND KON.UNPAN_GYOUSHA_CD =/*data.UNPAN_GYOUSHA_CD*/
	AND KON.NIOROSHI_GYOUSHA_CD =/*data.NIOROSHI_GYOUSHA_CD*/
	AND KON.NIOROSHI_GENBA_CD =/*data.NIOROSHI_GENBA_CD*/
	AND KON.TORIHIKISAKI_CD =/*data.TORIHIKISAKI_CD*/
	AND KON.GYOUSHA_CD =/*data.GYOUSHA_CD*/
	AND KON.GENBA_CD =/*data.GENBA_CD*/
	AND KON.DELETE_FLG = 0
ORDER BY
    KON.TEKIYOU_BEGIN