SELECT 
    TDFK.*
FROM 
    dbo.M_TODOUFUKEN TDFK
/*BEGIN*/WHERE
 /*IF !data.TODOUFUKEN_CD.IsNull */CAST(TDFK.TODOUFUKEN_CD AS VARCHAR(5)) LIKE '%' + CAST(/*data.TODOUFUKEN_CD*/0 AS VARCHAR(5)) + '%'/*END*/
 /*IF data.TODOUFUKEN_NAME != null*/AND TDFK.TODOUFUKEN_NAME LIKE '%' +  /*data.TODOUFUKEN_NAME*/ + '%'/*END*/
 /*IF data.TODOUFUKEN_NAME_RYAKU != null*/AND TDFK.TODOUFUKEN_NAME_RYAKU LIKE '%' +  /*data.TODOUFUKEN_NAME_RYAKU*/ + '%'/*END*/
 /*IF data.TODOUFUKEN_NAME_FURIGANA != null*/AND TDFK.TODOUFUKEN_NAME_FURIGANA LIKE '%' +  /*data.TODOUFUKEN_NAME_FURIGANA*/ + '%'/*END*/
 /*IF data.TODOUFUKEN_BIKOU != null*/AND TDFK.TODOUFUKEN_BIKOU LIKE '%' +  /*data.TODOUFUKEN_BIKOU*/ + '%'/*END*/
 /*IF data.CREATE_USER != null*/AND TDFK.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, TDFK.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
 /*IF data.UPDATE_USER != null*/AND TDFK.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
 /*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, TDFK.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*END*/
ORDER BY TDFK.TODOUFUKEN_CD
