SELECT DISTINCT
     TME.SYSTEM_ID AS SYSTEM_ID
    ,TME.SEQ AS SEQ
    ,TMD.DETAIL_SYSTEM_ID AS DETAIL_SYSTEM_ID
    ,TME.MANIFEST_ID AS MANIFEST_ID
    ,NULL AS KANRI_ID
    ,NULL AS DEN_SEQ
	,TME.HAIKI_KBN_CD AS HAIKI_KBN_CD
	,TMD.HAIKI_SHURUI_CD AS HAIKI_SHURUI_CD
	,MHS.HAIKI_SHURUI_NAME AS HAIKI_SHURUI_NAME
	,TME.HST_GYOUSHA_CD AS HST_GYOUSHA_CD
	,TME.HST_GENBA_CD AS HST_GENBA_CD
	,TMU.UPN_SAKI_GYOUSHA_CD AS SBN_GYOUSHA_CD
	,TMU.UPN_SAKI_GENBA_CD AS SBN_GENBA_CD
	,TMD.SBN_HOUHOU_CD AS SBN_HOUHOU_CD
	,TMU.UPN_SAKI_KBN AS UPN_SAKI_KBN
	,TMD.KANSAN_SUU AS KANSAN_SUU
	,TMD.GENNYOU_SUU AS GENNYOU_SUU
	/*IF data.GYOUSHA_KBN.Value == 1 && data.SAI_ITAKU_KBN.Value == 1*/
	    ,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN 1
		    WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 THEN 1
			ELSE 0 END AS ITAKU_KBN
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN NEXT_TMU.UPN_SAKI_GYOUSHA_CD
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 THEN NEXT_DTR19EX.UPNSAKI_GYOUSHA_CD
			ELSE NULL END AS ITAKUSAKI_CD
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN NEXT_TMU.UPN_SAKI_GENBA_CD
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 THEN NEXT_DTR19EX.UPNSAKI_GENBA_CD
			ELSE NULL END AS ITAKU_GENBA_CD
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN NEXT_ITAMGA.JISHA_KBN
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 THEN NEXT_DEN_ITAMGA.JISHA_KBN
			ELSE NULL END AS ITAKU_JISHA_KBN
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN NEXT_TMU.UPN_SAKI_GENBA_NAME
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 THEN NEXT_DEN_ITAMGA.GENBA_NAME1 + NEXT_DEN_ITAMGA.GENBA_NAME2
			ELSE NULL END AS ITAKUSAKI_NAME
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN NEXT_TMU.UPN_SAKI_GENBA_ADDRESS
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 THEN 
			/*IF data.ADDRESS_KBN.Value == 1*/
				NEXT_DEN_ITAMT.TODOUFUKEN_NAME + NEXT_DEN_ITAMGA.GENBA_ADDRESS1 + NEXT_DEN_ITAMGA.GENBA_ADDRESS2 
			/*END*/
			/*IF data.ADDRESS_KBN.Value == 2*/
				NEXT_DEN_ITAMGA.GENBA_ADDRESS1 + NEXT_DEN_ITAMGA.GENBA_ADDRESS2
			/*END*/
			/*IF data.ADDRESS_KBN.Value == 3*/
				NEXT_DEN_ITAMT.TODOUFUKEN_NAME + NEXT_DEN_ITAMGA.GENBA_ADDRESS1 
			/*END*/
			ELSE NULL END AS ITAKUSAKI_ADDRESS
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN NEXT_ITAMGA.CHIIKI_CD
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 THEN NEXT_DEN_ITAMGA.CHIIKI_CD
			ELSE NULL END AS ITAKUSAKI_CHIIKI_CD
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN
				--二次マニが紙マニフェストの場合
				CASE WHEN NEXT_TME.HAIKI_KBN_CD = 2 THEN
					CASE WHEN NEXT_TMD.HAIKI_SHURUI_CD BETWEEN '0000' AND '2099' THEN NEXT_MCK.FUTSUU_KYOKA_NO 
					ELSE NEXT_MCK.TOKUBETSU_KYOKA_NO
					END
				ELSE
					CASE WHEN NEXT_TMD.HAIKI_SHURUI_CD BETWEEN '0000' AND '6999' THEN NEXT_MCK.FUTSUU_KYOKA_NO 
					ELSE NEXT_MCK.TOKUBETSU_KYOKA_NO
					END
				END
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 THEN 
				--二次マニが電子マニフェストの場合
				CASE WHEN (NEXT_DTR18.HAIKI_DAI_CODE + NEXT_DTR18.HAIKI_CHU_CODE + NEXT_DTR18.HAIKI_SHO_CODE) BETWEEN '0000' AND '6999' THEN NEXT_DEN_MCK.FUTSUU_KYOKA_NO
					ELSE NEXT_DEN_MCK.TOKUBETSU_KYOKA_NO
					END
			ELSE NULL END AS ITAKUSAKI_KYOKA_NO
	/*END*/
	/*IF data.GYOUSHA_KBN.Value == 1 && data.SAI_ITAKU_KBN.Value == 2*/
	    ,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 AND NEXT_ITAMGA.JISHA_KBN = 0 THEN 1
		    WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_ITAMGA.JISHA_KBN = 0 THEN 1
			ELSE 0 END AS ITAKU_KBN
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 AND NEXT_ITAMGA.JISHA_KBN = 0 THEN NEXT_TMU.UPN_SAKI_GYOUSHA_CD
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_ITAMGA.JISHA_KBN = 0 THEN NEXT_DTR19EX.UPNSAKI_GYOUSHA_CD
			ELSE NULL END AS ITAKUSAKI_CD
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 AND NEXT_ITAMGA.JISHA_KBN = 0 THEN NEXT_TMU.UPN_SAKI_GENBA_CD
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_ITAMGA.JISHA_KBN = 0 THEN NEXT_DTR19EX.UPNSAKI_GENBA_CD
			ELSE NULL END AS ITAKU_GENBA_CD
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 AND NEXT_ITAMGA.JISHA_KBN = 0 THEN NEXT_ITAMGA.JISHA_KBN
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_ITAMGA.JISHA_KBN = 0THEN NEXT_DEN_ITAMGA.JISHA_KBN
			ELSE NULL END AS ITAKU_JISHA_KBN
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 AND NEXT_ITAMGA.JISHA_KBN = 0 THEN NEXT_TMU.UPN_SAKI_GENBA_NAME
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_ITAMGA.JISHA_KBN = 0 THEN NEXT_DEN_ITAMGA.GENBA_NAME1 + NEXT_DEN_ITAMGA.GENBA_NAME2
			ELSE NULL END AS ITAKUSAKI_NAME
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 AND NEXT_ITAMGA.JISHA_KBN = 0 THEN NEXT_TMU.UPN_SAKI_GENBA_ADDRESS
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_ITAMGA.JISHA_KBN = 0 THEN 
			/*IF data.ADDRESS_KBN.Value == 1*/
				NEXT_DEN_ITAMT.TODOUFUKEN_NAME + NEXT_DEN_ITAMGA.GENBA_ADDRESS1 + NEXT_DEN_ITAMGA.GENBA_ADDRESS2 
			/*END*/
			/*IF data.ADDRESS_KBN.Value == 2*/
				NEXT_DEN_ITAMGA.GENBA_ADDRESS1 + NEXT_DEN_ITAMGA.GENBA_ADDRESS2
			/*END*/
			/*IF data.ADDRESS_KBN.Value == 3*/
				NEXT_DEN_ITAMT.TODOUFUKEN_NAME + NEXT_DEN_ITAMGA.GENBA_ADDRESS1 
			/*END*/
			ELSE NULL END AS ITAKUSAKI_ADDRESS
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 AND NEXT_ITAMGA.JISHA_KBN = 0 THEN NEXT_ITAMGA.CHIIKI_CD
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_ITAMGA.JISHA_KBN = 0 THEN NEXT_DEN_ITAMGA.CHIIKI_CD
			ELSE NULL END AS ITAKUSAKI_CHIIKI_CD
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN
				--二次マニが紙マニフェストの場合
				CASE WHEN NEXT_TME.HAIKI_KBN_CD = 2 THEN
					CASE WHEN NEXT_TMD.HAIKI_SHURUI_CD BETWEEN '0000' AND '2099' THEN NEXT_MCK.FUTSUU_KYOKA_NO 
					ELSE NEXT_MCK.TOKUBETSU_KYOKA_NO
					END
				ELSE
					CASE WHEN NEXT_TMD.HAIKI_SHURUI_CD BETWEEN '0000' AND '6999' THEN NEXT_MCK.FUTSUU_KYOKA_NO 
					ELSE NEXT_MCK.TOKUBETSU_KYOKA_NO
					END
				END
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_ITAMGA.JISHA_KBN = 0 THEN
				--二次マニが電子マニフェストの場合
				CASE WHEN (NEXT_DTR18.HAIKI_DAI_CODE + NEXT_DTR18.HAIKI_CHU_CODE + NEXT_DTR18.HAIKI_SHO_CODE) BETWEEN '0000' AND '6999' THEN NEXT_DEN_MCK.FUTSUU_KYOKA_NO
					ELSE NEXT_DEN_MCK.TOKUBETSU_KYOKA_NO
					END
			ELSE NULL END AS ITAKUSAKI_KYOKA_NO
	/*END*/
	/*IF data.GYOUSHA_KBN.Value != 1*/
	,0 AS ITAKU_KBN
	,NULL AS ITAKUSAKI_CD
	,NULL AS ITAKU_GENBA_CD
	,NULL AS ITAKU_JISHA_KBN
	,NULL AS ITAKUSAKI_NAME
	,NULL AS ITAKUSAKI_ADDRESS
	,NULL AS ITAKUSAKI_CHIIKI_CD
	,NULL AS ITAKUSAKI_KYOKA_NO
	/*END*/
	
	,MCB.HOUKOKU_BUNRUI_CD AS HOUKOKUSHO_BUNRUI_CD
	,MCB.HOUKOKU_BUNRUI_NAME AS HOUKOKUSHO_BUNRUI_NAME
	/*IF data.TOKUBETSU_KANRI_KBN.Value == 1*/
		,HSTMCK.FUTSUU_KYOKA_NO AS SAIITAKU_KYOKA_NO
		,CASE WHEN HSTMCK.FUTSUU_KYOKA_NO IS NOT NULL THEN '再委託' ELSE NULL END AS JYUTAKU_KBN 
	/*END*/
	/*IF data.TOKUBETSU_KANRI_KBN.Value == 2*/
		,HSTMCK.TOKUBETSU_KYOKA_NO AS SAIITAKU_KYOKA_NO
		,CASE WHEN HSTMCK.TOKUBETSU_KYOKA_NO IS NOT NULL THEN '再委託' ELSE NULL END AS JYUTAKU_KBN 
	/*END*/
	,HSTMGS.GYOUSHA_NAME1 + HSTMGS.GYOUSHA_NAME2 AS HST_GYOUSHA_NAME
	/*IF data.ADDRESS_KBN.Value == 1*/
		,HSTMGSMT.TODOUFUKEN_NAME + HSTMGS.GYOUSHA_ADDRESS1 + HSTMGS.GYOUSHA_ADDRESS2 AS HST_GYOUSHA_ADDRESS
	/*END*/
	/*IF data.ADDRESS_KBN.Value == 2*/
		,HSTMGS.GYOUSHA_ADDRESS1 + HSTMGS.GYOUSHA_ADDRESS2 AS HST_GYOUSHA_ADDRESS
	/*END*/
	/*IF data.ADDRESS_KBN.Value == 3*/
		,HSTMGSMT.TODOUFUKEN_NAME + HSTMGS.GYOUSHA_ADDRESS1 AS HST_GYOUSHA_ADDRESS
	/*END*/
	,HSTMGA.GENBA_NAME1 + HSTMGA.GENBA_NAME2 AS HST_GENBA_NAME
	/*IF data.ADDRESS_KBN.Value == 1*/
		,HSTMGAMT.TODOUFUKEN_NAME + HSTMGA.GENBA_ADDRESS1 + HSTMGA.GENBA_ADDRESS2 AS HST_GENBA_ADDRESS
	/*END*/
	/*IF data.ADDRESS_KBN.Value == 2*/
		,HSTMGA.GENBA_ADDRESS1 + HSTMGA.GENBA_ADDRESS2 AS HST_GENBA_ADDRESS
	/*END*/
	/*IF data.ADDRESS_KBN.Value == 3*/
		,HSTMGAMT.TODOUFUKEN_NAME + HSTMGA.GENBA_ADDRESS1 AS HST_GENBA_ADDRESS
	/*END*/
	,HSTMGA.CHIIKI_CD AS HST_GENBA_CHIIKI_CD
	,MU.UNIT_NAME AS JYUTAKU_UNIT_NAME
	,MCH.HOUKOKU_SHOBUN_HOUHOU_CD AS SHOBUN_HOUHOU_CD
	,MCH.HOUKOKU_SHOBUN_HOUHOU_NAME AS SHOBUN_HOUHOU_NAME
	,SBNMGS.GYOUSHA_NAME1 + SBNMGS.GYOUSHA_NAME2 AS SBN_GYOUSHA_NAME
	/*IF data.ADDRESS_KBN.Value == 1*/
		,SBNMGSMT.TODOUFUKEN_NAME + SBNMGS.GYOUSHA_ADDRESS1 + SBNMGS.GYOUSHA_ADDRESS2 AS SBN_GYOUSHA_ADDRESS
	/*END*/
	/*IF data.ADDRESS_KBN.Value == 2*/
		,SBNMGS.GYOUSHA_ADDRESS1 + SBNMGS.GYOUSHA_ADDRESS2 AS SBN_GYOUSHA_ADDRESS
	/*END*/
	/*IF data.ADDRESS_KBN.Value == 3*/
		,SBNMGSMT.TODOUFUKEN_NAME + SBNMGS.GYOUSHA_ADDRESS1 AS SBN_GYOUSHA_ADDRESS
	/*END*/
    ,TMUMGA.GENBA_NAME1 + TMUMGA.GENBA_NAME2 AS SBN_GENBA_NAME
    /*IF data.ADDRESS_KBN.Value == 1*/
		,TMUMT.TODOUFUKEN_NAME + TMUMGA.GENBA_ADDRESS1 + TMUMGA.GENBA_ADDRESS2 
	/*END*/
	/*IF data.ADDRESS_KBN.Value == 2*/
		,TMUMGA.GENBA_ADDRESS1 + TMUMGA.GENBA_ADDRESS2 
	/*END*/
	/*IF data.ADDRESS_KBN.Value == 3*/
		,TMUMT.TODOUFUKEN_NAME + TMUMGA.GENBA_ADDRESS1 
	/*END*/
	AS SBN_GENBA_ADDRESS
	,TMUMGA.CHIIKI_CD AS SBN_GENBA_CHIIKI_CD
	,HSTMGA.CHIIKI_CD AS HST_JOU_CHIIKI_CD
	,HSTMGA.GENBA_TODOUFUKEN_CD AS HST_JOU_TODOUFUKEN_CD
	,CASE WHEN HSTMGA.CHIIKI_CD = /*data.TEISHUTSU_CHIIKI_CD*/0 THEN 1 ELSE 2 END AS HST_KEN_KBN
    
FROM 
	T_MANIFEST_ENTRY TME

	INNER JOIN T_MANIFEST_DETAIL TMD ON TMD.SYSTEM_ID = TME.SYSTEM_ID AND TMD.SEQ = TME.SEQ
	LEFT JOIN (SELECT TMU1.* FROM T_MANIFEST_ENTRY TME1 INNER JOIN T_MANIFEST_UPN TMU1 ON TMU1.SYSTEM_ID = TME1.SYSTEM_ID AND TMU1.SEQ = TME1.SEQ AND TMU1.UPN_ROUTE_NO = 1 WHERE (TME1.HAIKI_KBN_CD = 1 OR TME1.HAIKI_KBN_CD =2) AND TME1.DELETE_FLG =0 AND TME1.SEQ = (SELECT MAX(SEQ) FROM T_MANIFEST_ENTRY WHERE SYSTEM_ID = TME1.SYSTEM_ID)
	           UNION
	           SELECT TMU2.* FROM T_MANIFEST_ENTRY TME2 INNER JOIN T_MANIFEST_UPN TMU2 ON TMU2.SYSTEM_ID = TME2.SYSTEM_ID AND TMU2.SEQ = TME2.SEQ AND TME2.HAIKI_KBN_CD = 3  AND TMU2.UPN_ROUTE_NO = (
	                                                                              SELECT MIN(UPN_ROUTE_NO) FROM T_MANIFEST_UPN WHERE TME2.SYSTEM_ID = SYSTEM_ID AND SEQ = TME2.SEQ AND TME2.HAIKI_KBN_CD = 3 AND UPN_SAKI_KBN = 1) AND TME2.DELETE_FLG = 0) TMU ON TMU.SYSTEM_ID = TME.SYSTEM_ID AND TMU.SEQ = TME.SEQ
	LEFT JOIN M_GENBA HSTMGA ON HSTMGA.GENBA_CD = TME.HST_GENBA_CD AND HSTMGA.GYOUSHA_CD = TME.HST_GYOUSHA_CD
	LEFT JOIN M_GENBA TMUMGA ON TMUMGA.GYOUSHA_CD = TMU.UPN_SAKI_GYOUSHA_CD AND TMUMGA.GENBA_CD = TMU.UPN_SAKI_GENBA_CD
	--LEFT JOIN M_GENBA ITAMGA ON ITAMGA.GENBA_CD = TMU.UPN_SAKI_GYOUSHA_CD AND ITAMGA.GYOUSHA_CD = TMU.UPN_SAKI_GENBA_CD
	--LEFT JOIN M_CHIIKIBETSU_KYOKA SBNMCK ON SBNMCK.GYOUSHA_CD = TMU.UPN_SAKI_GYOUSHA_CD AND SBNMCK.GENBA_CD = TMU.UPN_SAKI_GENBA_CD

	LEFT JOIN T_MANIFEST_RELATION TMR ON  TMR.FIRST_SYSTEM_ID = TMD.DETAIL_SYSTEM_ID AND TMR.FIRST_HAIKI_KBN_CD = TME.HAIKI_KBN_CD AND TMR.DELETE_FLG = 0
	LEFT JOIN ( SELECT
					MENTRY.*, MDETAIL.DETAIL_SYSTEM_ID
				FROM
					T_MANIFEST_ENTRY AS MENTRY
					INNER JOIN T_MANIFEST_DETAIL AS MDETAIL 
						ON MDETAIL.SYSTEM_ID = MENTRY.SYSTEM_ID
						AND MENTRY.SEQ = MDETAIL.SEQ
				) AS NEXT_TME ON NEXT_TME.DETAIL_SYSTEM_ID = TMR.NEXT_SYSTEM_ID AND NEXT_TME.SEQ = (SELECT MAX(SEQ) FROM T_MANIFEST_ENTRY WHERE SYSTEM_ID = NEXT_TME.SYSTEM_ID) AND NEXT_TME.DELETE_FLG = 0 AND TMR.NEXT_HAIKI_KBN_CD != 4
	LEFT JOIN T_MANIFEST_DETAIL NEXT_TMD ON NEXT_TME.SYSTEM_ID = NEXT_TMD.SYSTEM_ID AND NEXT_TME.SEQ = NEXT_TMD.SEQ AND NEXT_TMD.DETAIL_SYSTEM_ID = (SELECT MIN(DETAIL_SYSTEM_ID) FROM T_MANIFEST_DETAIL WHERE SYSTEM_ID = NEXT_TMD.SYSTEM_ID AND SEQ = NEXT_TMD.SEQ)
	LEFT JOIN (SELECT TMU1.* FROM T_MANIFEST_ENTRY TME1 INNER JOIN T_MANIFEST_UPN TMU1 ON TMU1.SYSTEM_ID = TME1.SYSTEM_ID AND TMU1.SEQ = TME1.SEQ AND TMU1.UPN_ROUTE_NO = 1 WHERE (TME1.HAIKI_KBN_CD = 1 OR TME1.HAIKI_KBN_CD =2) AND TME1.DELETE_FLG =0 AND TME1.SEQ = (SELECT MAX(SEQ) FROM T_MANIFEST_ENTRY WHERE SYSTEM_ID = TME1.SYSTEM_ID)
	           UNION
	           SELECT TMU2.* FROM T_MANIFEST_ENTRY TME2 INNER JOIN T_MANIFEST_UPN TMU2 ON TMU2.SYSTEM_ID = TME2.SYSTEM_ID AND TMU2.SEQ = TME2.SEQ AND TME2.HAIKI_KBN_CD = 3  AND TMU2.UPN_ROUTE_NO = (
	                                                                              SELECT MIN(UPN_ROUTE_NO) FROM T_MANIFEST_UPN WHERE TME2.SYSTEM_ID = SYSTEM_ID AND SEQ = TME2.SEQ AND TME2.HAIKI_KBN_CD = 3 AND UPN_SAKI_KBN = 1) AND TME2.DELETE_FLG = 0 ) NEXT_TMU ON NEXT_TMU.SYSTEM_ID = NEXT_TME.SYSTEM_ID AND NEXT_TMU.SEQ = NEXT_TME.SEQ AND TMR.NEXT_HAIKI_KBN_CD != 4
	LEFT JOIN M_GENBA NEXT_ITAMGA ON NEXT_ITAMGA.GYOUSHA_CD = NEXT_TMU.UPN_SAKI_GYOUSHA_CD AND NEXT_ITAMGA.GENBA_CD = NEXT_TMU.UPN_SAKI_GENBA_CD AND TMR.NEXT_HAIKI_KBN_CD != 4
	LEFT JOIN M_CHIIKIBETSU_KYOKA NEXT_MCK ON NEXT_MCK.GYOUSHA_CD = NEXT_TMU.UPN_SAKI_GYOUSHA_CD AND NEXT_MCK.GENBA_CD = NEXT_TMU.UPN_SAKI_GENBA_CD AND TMR.NEXT_HAIKI_KBN_CD != 4 AND NEXT_MCK.KYOKA_KBN = 3 AND NEXT_MCK.CHIIKI_CD = NEXT_ITAMGA.CHIIKI_CD

	LEFT JOIN DT_R18_EX NEXT_DTR18EX ON NEXT_DTR18EX.SYSTEM_ID = TMR.NEXT_SYSTEM_ID AND NEXT_DTR18EX.DELETE_FLG = 0 AND TMR.NEXT_HAIKI_KBN_CD = 4
	LEFT JOIN DT_MF_TOC NEXT_TOC ON NEXT_TOC.KANRI_ID = NEXT_DTR18EX.KANRI_ID
	LEFT JOIN DT_R18 NEXT_DTR18 ON NEXT_TOC.KANRI_ID = NEXT_DTR18.KANRI_ID AND NEXT_TOC.LATEST_SEQ = NEXT_DTR18.SEQ
	LEFT JOIN DT_R19_EX NEXT_DTR19EX ON NEXT_DTR19EX.SYSTEM_ID = TMR.NEXT_SYSTEM_ID AND NEXT_DTR19EX.DELETE_FLG = 0 AND TMR.NEXT_HAIKI_KBN_CD = 4
	LEFT JOIN DT_R19 NEXT_DTR19 ON NEXT_DTR19.KANRI_ID = NEXT_DTR19EX.KANRI_ID AND NEXT_DTR19.SEQ = NEXT_DTR19EX.SEQ AND TMR.NEXT_HAIKI_KBN_CD = 4
	LEFT JOIN M_GENBA NEXT_DEN_ITAMGA ON NEXT_DEN_ITAMGA.GYOUSHA_CD = NEXT_DTR19EX.UPNSAKI_GYOUSHA_CD AND NEXT_DEN_ITAMGA.GENBA_CD = NEXT_DTR19EX.UPNSAKI_GENBA_CD AND TMR.NEXT_HAIKI_KBN_CD = 4
	LEFT JOIN M_CHIIKIBETSU_KYOKA NEXT_DEN_MCK ON NEXT_DEN_MCK.GYOUSHA_CD = NEXT_DTR19EX.UPNSAKI_GYOUSHA_CD AND NEXT_DEN_MCK.GENBA_CD = NEXT_DTR19EX.UPNSAKI_GENBA_CD AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_MCK.KYOKA_KBN = 3 AND NEXT_DEN_MCK.CHIIKI_CD = NEXT_DEN_ITAMGA.CHIIKI_CD

	LEFT JOIN M_CHIIKI NEXT_DEN_ITAMC ON NEXT_DEN_ITAMC.CHIIKI_CD = NEXT_DEN_ITAMGA.CHIIKI_CD AND TMR.NEXT_HAIKI_KBN_CD = 4
	LEFT JOIN M_TODOUFUKEN NEXT_DEN_ITAMT ON NEXT_DEN_ITAMT.TODOUFUKEN_CD = NEXT_DEN_ITAMC.TODOUFUKEN_CD AND TMR.NEXT_HAIKI_KBN_CD = 4 
	LEFT JOIN M_GYOUSHA HSTMGS ON HSTMGS.GYOUSHA_CD = TME.HST_GYOUSHA_CD
	LEFT JOIN M_CHIIKI HSTMGSMCK ON HSTMGSMCK.CHIIKI_CD = HSTMGS.CHIIKI_CD
	LEFT JOIN M_TODOUFUKEN HSTMGSMT ON HSTMGSMT.TODOUFUKEN_CD = HSTMGSMCK.TODOUFUKEN_CD
	LEFT JOIN M_CHIIKI HSTMGAMCK ON HSTMGAMCK.CHIIKI_CD = HSTMGA.CHIIKI_CD
	LEFT JOIN M_TODOUFUKEN HSTMGAMT ON HSTMGAMT.TODOUFUKEN_CD = HSTMGAMCK.TODOUFUKEN_CD
	LEFT JOIN M_GYOUSHA SBNMGS ON SBNMGS.GYOUSHA_CD = TMU.UPN_SAKI_GYOUSHA_CD
	LEFT JOIN M_CHIIKI SBNMGSMCK ON SBNMGSMCK.CHIIKI_CD = SBNMGS.CHIIKI_CD
	LEFT JOIN M_TODOUFUKEN SBNMGSMT ON SBNMGSMT.TODOUFUKEN_CD = SBNMGSMCK.TODOUFUKEN_CD
	LEFT JOIN M_CHIIKI TMUMC ON TMUMC.CHIIKI_CD = TMUMGA.CHIIKI_CD
	LEFT JOIN M_TODOUFUKEN TMUMT ON TMUMT.TODOUFUKEN_CD = TMUMC.TODOUFUKEN_CD
	LEFT JOIN M_HAIKI_SHURUI MHS ON MHS.HAIKI_KBN_CD = TME.HAIKI_KBN_CD AND MHS.HAIKI_SHURUI_CD = TMD.HAIKI_SHURUI_CD
	LEFT JOIN M_CHIIKIBETSU_BUNRUI MCB ON MCB.CHIIKI_CD = /*data.TEISHUTSU_CHIIKI_CD*/0 AND MCB.HOUKOKUSHO_BUNRUI_CD = MHS.HOUKOKUSHO_BUNRUI_CD 
	LEFT JOIN M_CHIIKIBETSU_KYOKA HSTMCK ON HSTMCK.GYOUSHA_CD = TME.HST_GYOUSHA_CD AND HSTMCK.GENBA_CD = TME.HST_GENBA_CD
	/*IF data.GYOUSHA_KBN.Value == 1*/
		AND HSTMCK.KYOKA_KBN =2 AND HSTMCK.CHIIKI_CD = /*data.TEISHUTSU_CHIIKI_CD*/0
	/*END*/
	/*IF data.GYOUSHA_KBN.Value == 2*/
		AND HSTMCK.KYOKA_KBN =3 AND HSTMCK.CHIIKI_CD = /*data.TEISHUTSU_CHIIKI_CD*/0
	/*END*/
	LEFT JOIN M_UNIT MU ON MU.UNIT_CD = (SELECT MANI_KANSAN_KIHON_UNIT_CD FROM M_SYS_INFO) 
	LEFT JOIN M_CHIIKIBETSU_SHOBUN MCH ON MCH.SHOBUN_HOUHOU_CD = TMD.SBN_HOUHOU_CD AND MCH.CHIIKI_CD = /*data.TEISHUTSU_CHIIKI_CD*/0

WHERE TME.DELETE_FLG = 0
	/*IF data.GYOUSHA_KBN.Value == 1*/
	  /*IF data.JIGYOUJOU_KBN.Value == 1*/
	    AND TMD.SBN_END_DATE IS NOT NULL
		AND (TMD.SBN_END_DATE <= CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_END.Value*/20140901, 111), 120) AND CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_BEGIN.Value*/20100901, 111), 120) <= TMD.SBN_END_DATE)
		AND TME.FIRST_MANIFEST_KBN = 0
		AND TMU.UPN_SAKI_GYOUSHA_CD = /*data.HOUKOKU_GYOUSHA_CD*/0
		AND TMU.UPN_SAKI_GENBA_CD = /*data.HOUKOKU_GENBA_CD*/0
		/*IF data.KEN_KBN.Value == 1*/
			AND HSTMGA.CHIIKI_CD = TMUMGA.CHIIKI_CD
		/*END*/
		/*IF data.KEN_KBN.Value == 2*/
			AND HSTMGA.CHIIKI_CD != TMUMGA.CHIIKI_CD
		/*END*/
	  /*END*/
	  /*IF data.JIGYOUJOU_KBN.Value == 2*/
	    AND TMD.SBN_END_DATE IS NOT NULL
	    AND TME.FIRST_MANIFEST_KBN = 1
		AND (TMD.SBN_END_DATE <= CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_END.Value*/20140901, 111), 120) AND CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_BEGIN.Value*/20100901, 111), 120) <= TMD.SBN_END_DATE)
		AND TMR.NEXT_SYSTEM_ID IS NOT NULL
		AND TMU.UPN_SAKI_GYOUSHA_CD = /*data.HOUKOKU_GYOUSHA_CD*/0
		AND TMU.UPN_SAKI_GENBA_CD = /*data.HOUKOKU_GENBA_CD*/0
        /*IF data.KEN_KBN.Value == 1*/
		AND HSTMGA.CHIIKI_CD = TMUMGA.CHIIKI_CD
		/*END*/
		/*IF data.KEN_KBN.Value == 2*/
		AND HSTMGA.CHIIKI_CD != TMUMGA.CHIIKI_CD
		/*END*/
	  /*END*/
	/*END*/

	/*IF data.GYOUSHA_KBN.Value == 2*/
	  /*IF data.JIGYOUJOU_KBN.Value == 1*/
		AND (TMD.SBN_END_DATE <= CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_END.Value*/20140901, 111), 120) AND CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_BEGIN.Value*/20100901, 111), 120) <= TMD.SBN_END_DATE)
		AND TMD.SBN_END_DATE IS NOT NULL
		AND TME.FIRST_MANIFEST_KBN = 1
		AND TMU.UPN_SAKI_GYOUSHA_CD = /*data.HOUKOKU_GYOUSHA_CD*/0
		AND TMU.UPN_SAKI_GENBA_CD = /*data.HOUKOKU_GENBA_CD*/0
		/*IF data.KEN_KBN.Value == 1*/
			AND HSTMGA.CHIIKI_CD = TMUMGA.CHIIKI_CD
		/*END*/
		/*IF data.KEN_KBN.Value == 2*/
			AND HSTMGA.CHIIKI_CD != TMUMGA.CHIIKI_CD
		/*END*/
	  /*END*/

	  /*IF data.JIGYOUJOU_KBN.Value == 2*/
		AND (TMD.LAST_SBN_END_DATE <= CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_END.Value*/20140901, 111), 120) AND CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_BEGIN.Value*/20100901, 111), 120) <= TMD.LAST_SBN_END_DATE)
		AND TMD.LAST_SBN_END_DATE IS NOT NULL
		AND TME.FIRST_MANIFEST_KBN = 1
		AND TMD.LAST_SBN_GYOUSHA_CD = /*data.HOUKOKU_GYOUSHA_CD*/0
		AND TMD.LAST_SBN_GENBA_CD = /*data.HOUKOKU_GENBA_CD*/0
		/*IF data.KEN_KBN.Value == 1*/
			AND HSTMGA.CHIIKI_CD = TMUMGA.CHIIKI_CD
		/*END*/
		/*IF data.KEN_KBN.Value == 2*/
			AND HSTMGA.CHIIKI_CD != TMUMGA.CHIIKI_CD
		/*END*/
      /*END*/
	/*END*/
	/*IF data.TOKUBETSU_KANRI_KBN.Value == 1*/
	AND (
	(TME.HAIKI_KBN_CD != 2 AND TMD.HAIKI_SHURUI_CD BETWEEN '0000' AND '6999') OR 
	(TME.HAIKI_KBN_CD = 2 AND TMD.HAIKI_SHURUI_CD BETWEEN '0000' AND '2099')
	)
	/*END*/

	/*IF data.TOKUBETSU_KANRI_KBN.Value == 2*/
	AND (
	(TME.HAIKI_KBN_CD != 2 AND TMD.HAIKI_SHURUI_CD BETWEEN '7000' AND '9999') OR 
	(TME.HAIKI_KBN_CD = 2 AND TMD.HAIKI_SHURUI_CD BETWEEN '2100' AND '9999')
	)
	/*END*/
/*IF data.DENMANI_KBN.Value == 1*/
UNION

SELECT DISTINCT
     NULL AS SYSTEM_ID
    ,NULL AS SEQ
    ,DTR18.SYSTEM_ID AS DETAIL_SYSTEM_ID
    ,DTR18.MANIFEST_ID AS MANIFEST_ID
    ,DTR18.KANRI_ID AS KANRI_ID
    ,DTR18.SEQ AS DEN_SEQ
	,'4' AS HAIKI_KBN_CD
	,DTR18.HAIKI_DAI_CODE + DTR18.HAIKI_CHU_CODE + DTR18.HAIKI_SHO_CODE AS HAIKI_SHURUI_CD
	,DTR18.HAIKI_SHURUI_NAME AS HAIKI_SHURUI_NAME
	,DTR18.HST_GYOUSHA_CD AS HST_GYOUSHA_CD
	,DTR18.HST_GENBA_CD AS HST_GENBA_CD
	,DTR18.SBN_GYOUSHA_CD AS SBN_GYOUSHA_CD
	,DTR18.SBN_GENBA_CD AS SBN_GENBA_CD
	,DTR18.SBN_HOUHOU_CD AS SBN_HOUHOU_CD
	,DTR19.UPNSAKI_JOU_KBN AS UPN_SAKI_KBN
	,DTR18.KANSAN_SUU AS KANSAN_SUU
	,DTR18.GENNYOU_SUU AS GENNYOU_SUU
	/*IF data.GYOUSHA_KBN.Value == 1 && data.SAI_ITAKU_KBN.Value == 1*/
	    ,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN 1
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 THEN 1
			ELSE 0 END AS ITAKU_KBN
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN NEXT_TMU.UPN_SAKI_GYOUSHA_CD
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 THEN NEXT_DTR19EX.UPNSAKI_GYOUSHA_CD
			ELSE NULL END AS ITAKUSAKI_CD
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN NEXT_TMU.UPN_SAKI_GENBA_CD
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 THEN NEXT_DTR19EX.UPNSAKI_GENBA_CD
			ELSE NULL END AS ITAKU_GENBA_CD
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN NEXT_ITAMGA.JISHA_KBN
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 THEN NEXT_DEN_ITAMGA.JISHA_KBN
			ELSE NULL END AS ITAKU_JISHA_KBN
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN NEXT_TMU.UPN_SAKI_GENBA_NAME
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 THEN NEXT_DEN_ITAMGA.GENBA_NAME1 + NEXT_DEN_ITAMGA.GENBA_NAME2
			ELSE NULL END AS ITAKUSAKI_NAME
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN NEXT_TMU.UPN_SAKI_GENBA_ADDRESS
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 THEN 
			/*IF data.ADDRESS_KBN.Value == 1*/
				NEXT_DEN_ITAMT.TODOUFUKEN_NAME + NEXT_DEN_ITAMGA.GENBA_ADDRESS1 + NEXT_DEN_ITAMGA.GENBA_ADDRESS2 
			/*END*/
			/*IF data.ADDRESS_KBN.Value == 2*/
				NEXT_DEN_ITAMGA.GENBA_ADDRESS1 + NEXT_DEN_ITAMGA.GENBA_ADDRESS2
			/*END*/
			/*IF data.ADDRESS_KBN.Value == 3*/
				NEXT_DEN_ITAMT.TODOUFUKEN_NAME + NEXT_DEN_ITAMGA.GENBA_ADDRESS1 
			/*END*/
			ELSE NULL END AS ITAKUSAKI_ADDRESS
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN NEXT_ITAMGA.CHIIKI_CD
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 THEN NEXT_DEN_ITAMGA.CHIIKI_CD
			ELSE NULL END AS ITAKUSAKI_CHIIKI_CD
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN
				--二次マニが紙マニフェストの場合
				CASE WHEN NEXT_TME.HAIKI_KBN_CD = 2 THEN
					CASE WHEN NEXT_TMD.HAIKI_SHURUI_CD BETWEEN '0000' AND '2099' THEN NEXT_MCK.FUTSUU_KYOKA_NO 
					ELSE NEXT_MCK.TOKUBETSU_KYOKA_NO
					END
				ELSE
					CASE WHEN NEXT_TMD.HAIKI_SHURUI_CD BETWEEN '0000' AND '6999' THEN NEXT_MCK.FUTSUU_KYOKA_NO 
					ELSE NEXT_MCK.TOKUBETSU_KYOKA_NO
					END
				END
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 THEN 
				--二次マニが電子マニフェストの場合
				CASE WHEN (NEXT_DTR18.HAIKI_DAI_CODE + NEXT_DTR18.HAIKI_CHU_CODE + NEXT_DTR18.HAIKI_SHO_CODE) BETWEEN '0000' AND '6999' THEN NEXT_DEN_MCK.FUTSUU_KYOKA_NO
					ELSE NEXT_DEN_MCK.TOKUBETSU_KYOKA_NO
					END
			ELSE NULL END AS ITAKUSAKI_KYOKA_NO
	/*END*/
	/*IF data.GYOUSHA_KBN.Value == 1 && data.SAI_ITAKU_KBN.Value == 2*/
	    ,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 AND NEXT_ITAMGA.JISHA_KBN = 0 THEN 1
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_ITAMGA.JISHA_KBN = 0 THEN 1
			ELSE 0 END AS ITAKU_KBN
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 AND NEXT_ITAMGA.JISHA_KBN = 0 THEN NEXT_TMU.UPN_SAKI_GYOUSHA_CD
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_ITAMGA.JISHA_KBN = 0 THEN NEXT_DTR19EX.UPNSAKI_GYOUSHA_CD
			ELSE NULL END AS ITAKUSAKI_CD
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 AND NEXT_ITAMGA.JISHA_KBN = 0 THEN NEXT_TMU.UPN_SAKI_GENBA_CD
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_ITAMGA.JISHA_KBN = 0 THEN NEXT_DTR19EX.UPNSAKI_GENBA_CD
			ELSE NULL END AS ITAKU_GENBA_CD
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 AND NEXT_ITAMGA.JISHA_KBN = 0 THEN NEXT_ITAMGA.JISHA_KBN
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_ITAMGA.JISHA_KBN = 0THEN NEXT_DEN_ITAMGA.JISHA_KBN
			ELSE NULL END AS ITAKU_JISHA_KBN
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 AND NEXT_ITAMGA.JISHA_KBN = 0 THEN NEXT_TMU.UPN_SAKI_GENBA_NAME
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_ITAMGA.JISHA_KBN = 0 THEN NEXT_DEN_ITAMGA.GENBA_NAME1 + NEXT_DEN_ITAMGA.GENBA_NAME2
			ELSE NULL END AS ITAKUSAKI_NAME
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 AND NEXT_ITAMGA.JISHA_KBN = 0 THEN NEXT_TMU.UPN_SAKI_GENBA_ADDRESS
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_ITAMGA.JISHA_KBN = 0 THEN 
			/*IF data.ADDRESS_KBN.Value == 1*/
				NEXT_DEN_ITAMT.TODOUFUKEN_NAME + NEXT_DEN_ITAMGA.GENBA_ADDRESS1 + NEXT_DEN_ITAMGA.GENBA_ADDRESS2 
			/*END*/
			/*IF data.ADDRESS_KBN.Value == 2*/
				NEXT_DEN_ITAMGA.GENBA_ADDRESS1 + NEXT_DEN_ITAMGA.GENBA_ADDRESS2
			/*END*/
			/*IF data.ADDRESS_KBN.Value == 3*/
				NEXT_DEN_ITAMT.TODOUFUKEN_NAME + NEXT_DEN_ITAMGA.GENBA_ADDRESS1 
			/*END*/
			ELSE NULL END AS ITAKUSAKI_ADDRESS
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 AND NEXT_ITAMGA.JISHA_KBN = 0 THEN NEXT_ITAMGA.CHIIKI_CD
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_ITAMGA.JISHA_KBN = 0 THEN NEXT_DEN_ITAMGA.CHIIKI_CD
			ELSE NULL END AS ITAKUSAKI_CHIIKI_CD
		,CASE WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD != 4 THEN
				--二次マニが紙マニフェストの場合
				CASE WHEN NEXT_TME.HAIKI_KBN_CD = 2 THEN
					CASE WHEN NEXT_TMD.HAIKI_SHURUI_CD BETWEEN '0000' AND '2099' THEN NEXT_MCK.FUTSUU_KYOKA_NO 
					ELSE NEXT_MCK.TOKUBETSU_KYOKA_NO
					END
				ELSE
					CASE WHEN NEXT_TMD.HAIKI_SHURUI_CD BETWEEN '0000' AND '6999' THEN NEXT_MCK.FUTSUU_KYOKA_NO 
					ELSE NEXT_MCK.TOKUBETSU_KYOKA_NO
					END
				END
			WHEN TMR.NEXT_SYSTEM_ID IS NOT NULL AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_ITAMGA.JISHA_KBN = 0 THEN 
				--二次マニが電子マニフェストの場合
				CASE WHEN (NEXT_DTR18.HAIKI_DAI_CODE + NEXT_DTR18.HAIKI_CHU_CODE + NEXT_DTR18.HAIKI_SHO_CODE) BETWEEN '0000' AND '6999' THEN NEXT_DEN_MCK.FUTSUU_KYOKA_NO
					ELSE NEXT_DEN_MCK.TOKUBETSU_KYOKA_NO
					END
			ELSE NULL END AS ITAKUSAKI_KYOKA_NO
	/*END*/
	/*IF data.GYOUSHA_KBN.Value != 1*/
	    ,0 AS ITAKU_KBN
		,NULL AS ITAKUSAKI_CD
		,NULL AS ITAKU_GENBA_CD
		,NULL AS ITAKU_JISHA_KBN
		,NULL AS ITAKUSAKI_NAME
		,NULL AS ITAKUSAKI_ADDRESS
		,NULL AS ITAKUSAKI_CHIIKI_CD
		,NULL AS ITAKUSAKI_KYOKA_NO
	/*END*/
	
	,MCB.HOUKOKU_BUNRUI_CD AS HOUKOKUSHO_BUNRUI_CD	
	,MCB.HOUKOKU_BUNRUI_NAME AS HOUKOKUSHO_BUNRUI_NAME
	/*IF data.TOKUBETSU_KANRI_KBN.Value == 1*/
		,MCK.FUTSUU_KYOKA_NO AS SAIITAKU_KYOKA_NO
		,CASE WHEN MCK.FUTSUU_KYOKA_NO IS NOT NULL THEN '再委託' ELSE NULL END AS JYUTAKU_KBN 	/*END*/
	/*IF data.TOKUBETSU_KANRI_KBN.Value == 2*/
		,MCK.TOKUBETSU_KYOKA_NO AS SAIITAKU_KYOKA_NO
		,CASE WHEN MCK.TOKUBETSU_KYOKA_NO IS NOT NULL THEN '再委託' ELSE NULL END AS JYUTAKU_KBN 	/*END*/
	,HSTMGS.GYOUSHA_NAME1 + HSTMGS.GYOUSHA_NAME2 AS HST_GYOUSHA_NAME
	/*IF data.ADDRESS_KBN.Value == 1*/
		,HSTMGSMT.TODOUFUKEN_NAME + HSTMGS.GYOUSHA_ADDRESS1 + HSTMGS.GYOUSHA_ADDRESS2 AS HST_GYOUSHA_ADDRESS
	/*END*/
	/*IF data.ADDRESS_KBN.Value == 2*/
		,HSTMGS.GYOUSHA_ADDRESS1 + HSTMGS.GYOUSHA_ADDRESS2 AS HST_GYOUSHA_ADDRESS
	/*END*/
	/*IF data.ADDRESS_KBN.Value == 3*/
		,HSTMGSMT.TODOUFUKEN_NAME + HSTMGS.GYOUSHA_ADDRESS1 AS HST_GYOUSHA_ADDRESS
	/*END*/
	
	,HSTMGA.GENBA_NAME1 + HSTMGA.GENBA_NAME2 AS HST_GENBA_NAME
	/*IF data.ADDRESS_KBN.Value == 1*/
		,HSTMGAMT.TODOUFUKEN_NAME + HSTMGA.GENBA_ADDRESS1 + HSTMGA.GENBA_ADDRESS2 AS HST_GENBA_ADDRESS
	/*END*/
	/*IF data.ADDRESS_KBN.Value == 2*/
		,HSTMGA.GENBA_ADDRESS1 + HSTMGA.GENBA_ADDRESS2 AS HST_GENBA_ADDRESS
	/*END*/
	/*IF data.ADDRESS_KBN.Value == 3*/
		,HSTMGAMT.TODOUFUKEN_NAME + HSTMGA.GENBA_ADDRESS1 AS HST_GENBA_ADDRESS
	/*END*/
	,HSTMGA.CHIIKI_CD AS HST_GENBA_CHIIKI_CD
	,MU.UNIT_NAME AS JYUTAKU_UNIT_NAME
	,MCH.HOUKOKU_SHOBUN_HOUHOU_CD AS SHOBUN_HOUHOU_CD
	,MCH.HOUKOKU_SHOBUN_HOUHOU_NAME AS SHOBUN_HOUHOU_NAME
	,SBNMGS.GYOUSHA_NAME1 + SBNMGS.GYOUSHA_NAME2 AS SBN_GYOUSHA_NAME
	/*IF data.ADDRESS_KBN.Value == 1*/
		,SBNMGSMT.TODOUFUKEN_NAME + SBNMGS.GYOUSHA_ADDRESS1 + SBNMGS.GYOUSHA_ADDRESS2 AS SBN_GYOUSHA_ADDRESS
	/*END*/
	/*IF data.ADDRESS_KBN.Value == 2*/
		,SBNMGS.GYOUSHA_ADDRESS1 + SBNMGS.GYOUSHA_ADDRESS2 AS SBN_GYOUSHA_ADDRESS
	/*END*/
	/*IF data.ADDRESS_KBN.Value == 3*/
		,SBNMGSMT.TODOUFUKEN_NAME + SBNMGS.GYOUSHA_ADDRESS1 AS SBN_GYOUSHA_ADDRESS
	/*END*/
	,TMUMGA.GENBA_NAME1 + TMUMGA.GENBA_NAME2 AS SBN_GENBA_NAME
	/*IF data.ADDRESS_KBN.Value == 1*/
		,TMUMT.TODOUFUKEN_NAME + TMUMGA.GENBA_ADDRESS1 + TMUMGA.GENBA_ADDRESS2 
	/*END*/
	/*IF data.ADDRESS_KBN.Value == 2*/
		,TMUMGA.GENBA_ADDRESS1 + TMUMGA.GENBA_ADDRESS2 
	/*END*/
	/*IF data.ADDRESS_KBN.Value == 3*/
		,TMUMT.TODOUFUKEN_NAME + TMUMGA.GENBA_ADDRESS1 
	/*END*/
	AS SBN_GENBA_ADDRESS
	,TMUMGA.CHIIKI_CD AS SBN_GENBA_CHIIKI_CD
	,HSTMGA.CHIIKI_CD AS HST_JOU_CHIIKI_CD
	,HSTMGA.GENBA_TODOUFUKEN_CD AS HST_JOU_TODOUFUKEN_CD
	,CASE WHEN HSTMGA.CHIIKI_CD = /*data.TEISHUTSU_CHIIKI_CD*/0 THEN 1
		ELSE 2 END AS HST_KEN_KBN

FROM 
    DT_MF_TOC DMT
    INNER JOIN (
            SELECT
                R18.KANRI_ID
                ,R18.SEQ
                ,R18.MANIFEST_ID
                ,R18.MANIFEST_KBN
                ,R18.SBN_END_DATE
                ,R18.FIRST_MANIFEST_FLAG
                ,EX.HST_GYOUSHA_CD
                ,EX.HST_GENBA_CD
                ,EX.SBN_GYOUSHA_CD
                ,EX.SBN_GENBA_CD
                ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.DETAIL_SYSTEM_ID ELSE EX.SYSTEM_ID END) AS SYSTEM_ID
                ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.SBN_HOUHOU_CD ELSE EX.SBN_HOUHOU_CD END) AS SBN_HOUHOU_CD
                ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.KANSAN_SUU ELSE EX.KANSAN_SUU END) AS KANSAN_SUU
                ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.GENNYOU_SUU ELSE EX.GENNYOU_SUU END) AS GENNYOU_SUU
                ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.HAIKI_DAI_CODE ELSE R18.HAIKI_DAI_CODE END) AS HAIKI_DAI_CODE
                ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.HAIKI_CHU_CODE ELSE R18.HAIKI_CHU_CODE END) AS HAIKI_CHU_CODE
                ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.HAIKI_SHO_CODE ELSE R18.HAIKI_SHO_CODE END) AS HAIKI_SHO_CODE
                ,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX.SBN_ENDREP_KBN ELSE R18.SBN_ENDREP_KBN END) AS SBN_ENDREP_KBN
				,(CASE WHEN MIX.DETAIL_SYSTEM_ID IS NOT NULL THEN MIX_HAIKI_SHURUI.HAIKI_SHURUI_NAME ELSE R18.HAIKI_SHURUI END) AS HAIKI_SHURUI_NAME
            FROM DT_R18 AS R18
            LEFT JOIN DT_R18_EX AS EX
            ON R18.KANRI_ID = EX.KANRI_ID AND EX.DELETE_FLG = 0
            LEFT JOIN DT_R18_MIX AS MIX
            ON EX.SYSTEM_ID = MIX.SYSTEM_ID AND MIX.DELETE_FLG = 0
			LEFT JOIN M_DENSHI_HAIKI_SHURUI AS MIX_HAIKI_SHURUI
            ON (MIX.HAIKI_DAI_CODE + MIX.HAIKI_CHU_CODE + MIX.HAIKI_SHO_CODE) = MIX_HAIKI_SHURUI.HAIKI_SHURUI_CD
        ) DTR18
        ON DMT.KANRI_ID = DTR18.KANRI_ID AND DMT.LATEST_SEQ = DTR18.SEQ
    LEFT JOIN DT_R19 DTR19 ON DTR19.KANRI_ID = DTR18.KANRI_ID AND DTR19.SEQ = DTR18.SEQ AND DTR19.UPN_ROUTE_NO = (SELECT MAX(UPN_ROUTE_NO) FROM DT_R19 WHERE KANRI_ID = DTR19.KANRI_ID AND SEQ = DTR19.SEQ)
	LEFT JOIN DT_R19_EX DTR19EX ON DTR19EX.KANRI_ID = DTR19.KANRI_ID AND DTR19EX.UPN_ROUTE_NO = DTR19.UPN_ROUTE_NO AND DTR19EX.DELETE_FLG = 0
	LEFT JOIN DT_R13 DTR13 ON DTR13.KANRI_ID = DTR18.KANRI_ID AND DTR13.SEQ = DTR18.SEQ
	LEFT JOIN DT_R13_EX DTR13EX ON DTR13EX.KANRI_ID = DTR13.KANRI_ID AND DTR13EX.REC_SEQ = DTR13.REC_SEQ AND DTR13EX.DELETE_FLG = 0
	LEFT JOIN M_GENBA HSTMGA ON HSTMGA.GENBA_CD = DTR18.HST_GENBA_CD AND HSTMGA.GYOUSHA_CD = DTR18.HST_GYOUSHA_CD
	LEFT JOIN M_GENBA SBNMGA ON SBNMGA.GYOUSHA_CD = DTR18.SBN_GYOUSHA_CD AND SBNMGA.GENBA_CD = DTR18.SBN_GENBA_CD

	LEFT JOIN T_MANIFEST_RELATION TMR ON  TMR.FIRST_SYSTEM_ID = DTR18.SYSTEM_ID AND TMR.FIRST_HAIKI_KBN_CD =4 AND TMR.DELETE_FLG = 0
	LEFT JOIN ( SELECT
					MENTRY.*, MDETAIL.DETAIL_SYSTEM_ID
				FROM
					T_MANIFEST_ENTRY AS MENTRY
					INNER JOIN T_MANIFEST_DETAIL AS MDETAIL 
						ON MDETAIL.SYSTEM_ID = MENTRY.SYSTEM_ID
						AND MENTRY.SEQ = MDETAIL.SEQ
				) AS NEXT_TME ON NEXT_TME.DETAIL_SYSTEM_ID = TMR.NEXT_SYSTEM_ID AND NEXT_TME.DELETE_FLG = 0 AND TMR.NEXT_HAIKI_KBN_CD != 4
	LEFT JOIN T_MANIFEST_DETAIL NEXT_TMD ON NEXT_TME.SYSTEM_ID = NEXT_TMD.SYSTEM_ID AND NEXT_TME.SEQ = NEXT_TMD.SEQ AND NEXT_TMD.DETAIL_SYSTEM_ID = (SELECT MIN(DETAIL_SYSTEM_ID) FROM T_MANIFEST_DETAIL WHERE SYSTEM_ID = NEXT_TMD.SYSTEM_ID AND SEQ = NEXT_TMD.SEQ)
	LEFT JOIN (SELECT TMU1.* FROM T_MANIFEST_ENTRY TME1 INNER JOIN T_MANIFEST_UPN TMU1 ON TMU1.SYSTEM_ID = TME1.SYSTEM_ID AND TMU1.SEQ = TME1.SEQ AND TMU1.UPN_ROUTE_NO = 1 WHERE (TME1.HAIKI_KBN_CD = 1 OR TME1.HAIKI_KBN_CD = 2) AND TME1.DELETE_FLG =0 AND TME1.SEQ = (SELECT MAX(SEQ) FROM T_MANIFEST_ENTRY WHERE SYSTEM_ID = TME1.SYSTEM_ID)
	           UNION
	           SELECT TMU2.* FROM T_MANIFEST_ENTRY TME2 INNER JOIN T_MANIFEST_UPN TMU2 ON TMU2.SYSTEM_ID = TME2.SYSTEM_ID AND TMU2.SEQ = TME2.SEQ AND TME2.HAIKI_KBN_CD = 3  AND TMU2.UPN_ROUTE_NO = (
	                                                                              SELECT MIN(UPN_ROUTE_NO) FROM T_MANIFEST_UPN WHERE TME2.SYSTEM_ID = SYSTEM_ID AND SEQ = TME2.SEQ AND TME2.HAIKI_KBN_CD = 3 AND UPN_SAKI_KBN = 1) AND TME2.DELETE_FLG = 0 ) NEXT_TMU ON NEXT_TMU.SYSTEM_ID = NEXT_TME.SYSTEM_ID AND NEXT_TMU.SEQ = NEXT_TME.SEQ AND TMR.NEXT_HAIKI_KBN_CD != 4
	LEFT JOIN M_GENBA NEXT_ITAMGA ON NEXT_ITAMGA.GYOUSHA_CD = NEXT_TMU.UPN_SAKI_GYOUSHA_CD AND NEXT_ITAMGA.GENBA_CD = NEXT_TMU.UPN_SAKI_GENBA_CD AND TMR.NEXT_HAIKI_KBN_CD != 4
	LEFT JOIN M_CHIIKIBETSU_KYOKA NEXT_MCK ON NEXT_MCK.GYOUSHA_CD = NEXT_TMU.UPN_SAKI_GYOUSHA_CD AND NEXT_MCK.GENBA_CD = NEXT_TMU.UPN_SAKI_GENBA_CD AND TMR.NEXT_HAIKI_KBN_CD != 4 AND NEXT_MCK.KYOKA_KBN = 3 AND NEXT_MCK.CHIIKI_CD = NEXT_ITAMGA.CHIIKI_CD

	LEFT JOIN DT_R18_EX NEXT_DTR18EX ON NEXT_DTR18EX.SYSTEM_ID = TMR.NEXT_SYSTEM_ID AND NEXT_DTR18EX.DELETE_FLG = 0 AND TMR.NEXT_HAIKI_KBN_CD = 4
	LEFT JOIN DT_MF_TOC NEXT_TOC ON NEXT_TOC.KANRI_ID = NEXT_DTR18EX.KANRI_ID
	LEFT JOIN DT_R18 NEXT_DTR18 ON NEXT_TOC.KANRI_ID = NEXT_DTR18.KANRI_ID AND NEXT_TOC.LATEST_SEQ = NEXT_DTR18.SEQ
	LEFT JOIN DT_R19_EX NEXT_DTR19EX ON NEXT_DTR19EX.SYSTEM_ID = TMR.NEXT_SYSTEM_ID AND NEXT_DTR19EX.DELETE_FLG = 0 AND TMR.NEXT_HAIKI_KBN_CD = 4
	LEFT JOIN DT_R19 NEXT_DTR19 ON NEXT_DTR19.KANRI_ID = NEXT_DTR19EX.KANRI_ID AND NEXT_DTR19.SEQ = NEXT_DTR19EX.SEQ AND TMR.NEXT_HAIKI_KBN_CD = 4
	LEFT JOIN M_GENBA NEXT_DEN_ITAMGA ON NEXT_DEN_ITAMGA.GYOUSHA_CD = NEXT_DTR19EX.UPNSAKI_GYOUSHA_CD AND NEXT_DEN_ITAMGA.GENBA_CD = NEXT_DTR19EX.UPNSAKI_GENBA_CD AND TMR.NEXT_HAIKI_KBN_CD = 4
	LEFT JOIN M_CHIIKIBETSU_KYOKA NEXT_DEN_MCK ON NEXT_DEN_MCK.GYOUSHA_CD = NEXT_DTR19EX.UPNSAKI_GYOUSHA_CD AND NEXT_DEN_MCK.GENBA_CD = NEXT_DTR19EX.UPNSAKI_GENBA_CD AND TMR.NEXT_HAIKI_KBN_CD = 4 AND NEXT_DEN_MCK.KYOKA_KBN = 3 AND NEXT_DEN_MCK.CHIIKI_CD = NEXT_DEN_ITAMGA.CHIIKI_CD

	LEFT JOIN M_CHIIKI NEXT_DEN_ITAMC ON NEXT_DEN_ITAMC.CHIIKI_CD = NEXT_DEN_ITAMGA.CHIIKI_CD AND TMR.NEXT_HAIKI_KBN_CD = 4
	LEFT JOIN M_TODOUFUKEN NEXT_DEN_ITAMT ON NEXT_DEN_ITAMT.TODOUFUKEN_CD = NEXT_DEN_ITAMC.TODOUFUKEN_CD AND TMR.NEXT_HAIKI_KBN_CD = 4 
	LEFT JOIN M_DENSHI_HAIKI_SHURUI MDHS ON MDHS.HAIKI_SHURUI_CD = (DTR18.HAIKI_DAI_CODE + DTR18.HAIKI_CHU_CODE + DTR18.HAIKI_SHO_CODE)
	LEFT JOIN M_CHIIKIBETSU_BUNRUI MCB ON MCB.CHIIKI_CD = /*data.TEISHUTSU_CHIIKI_CD*/0 AND MCB.HOUKOKUSHO_BUNRUI_CD = MDHS.HOUKOKUSHO_BUNRUI_CD
	LEFT JOIN M_CHIIKIBETSU_KYOKA MCK ON MCK.GYOUSHA_CD = DTR18.HST_GYOUSHA_CD AND MCK.GENBA_CD = DTR18.HST_GENBA_CD
	/*IF data.GYOUSHA_KBN.Value == 1*/
	  AND MCK.KYOKA_KBN =2 AND MCK.CHIIKI_CD = /*data.TEISHUTSU_CHIIKI_CD*/0
    /*END*/
    /*IF data.GYOUSHA_KBN.Value == 2*/
	  AND MCK.KYOKA_KBN =3 AND MCK.CHIIKI_CD = /*data.TEISHUTSU_CHIIKI_CD*/0
    /*END*/
    LEFT JOIN M_GYOUSHA HSTMGS ON HSTMGS.GYOUSHA_CD = DTR18.HST_GYOUSHA_CD
    LEFT JOIN M_CHIIKI HSTMGSMCK ON HSTMGSMCK.CHIIKI_CD = HSTMGS.CHIIKI_CD
    LEFT JOIN M_TODOUFUKEN HSTMGSMT ON HSTMGSMT.TODOUFUKEN_CD = HSTMGSMCK.TODOUFUKEN_CD
    
	LEFT JOIN M_CHIIKI HSTMGAMCK ON HSTMGAMCK.CHIIKI_CD = HSTMGA.CHIIKI_CD
	LEFT JOIN M_TODOUFUKEN HSTMGAMT ON HSTMGAMT.TODOUFUKEN_CD = HSTMGAMCK.TODOUFUKEN_CD
	
	LEFT JOIN M_UNIT MU ON MU.UNIT_CD = (SELECT MANI_KANSAN_KIHON_UNIT_CD FROM M_SYS_INFO)  
    LEFT JOIN M_CHIIKIBETSU_SHOBUN MCH ON MCH.SHOBUN_HOUHOU_CD = DTR18.SBN_HOUHOU_CD AND MCH.CHIIKI_CD = /*data.TEISHUTSU_CHIIKI_CD*/0
    
    LEFT JOIN M_GYOUSHA SBNMGS ON SBNMGS.GYOUSHA_CD = DTR18.SBN_GYOUSHA_CD
    LEFT JOIN M_CHIIKI SBNMGSMCK ON SBNMGSMCK.CHIIKI_CD = SBNMGS.CHIIKI_CD
    LEFT JOIN M_TODOUFUKEN SBNMGSMT ON SBNMGSMT.TODOUFUKEN_CD = SBNMGSMCK.TODOUFUKEN_CD
    
    LEFT JOIN M_GENBA TMUMGA ON TMUMGA.GYOUSHA_CD = DTR18.SBN_GYOUSHA_CD AND TMUMGA.GENBA_CD = DTR18.SBN_GENBA_CD
    LEFT JOIN M_CHIIKI TMUMC ON TMUMC.CHIIKI_CD = TMUMGA.CHIIKI_CD
    LEFT JOIN M_TODOUFUKEN TMUMT ON TMUMT.TODOUFUKEN_CD = TMUMC.TODOUFUKEN_CD

WHERE 1=1

	/*IF data.GYOUSHA_KBN.Value == 1*/
	  /*IF data.JIGYOUJOU_KBN.Value == 1*/
	    AND DTR18.SBN_END_DATE IS NOT NULL
		AND (DTR18.SBN_END_DATE <= CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_END.Value*/20140901, 111), 120) AND CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_BEGIN.Value*/20100901, 111), 120) <= DTR18.SBN_END_DATE)
		AND DTR18.MANIFEST_KBN = 2
		AND (ISNULL(DTR18.FIRST_MANIFEST_FLAG,'') = '' OR ISNULL(HSTMGS.JISHA_KBN, 0) = 0)
		AND DTR18.SBN_GYOUSHA_CD = /*data.HOUKOKU_GYOUSHA_CD*/0
		AND DTR18.SBN_GENBA_CD = /*data.HOUKOKU_GENBA_CD*/0
		/*IF data.KEN_KBN.Value == 1*/
			AND HSTMGA.CHIIKI_CD = SBNMGA.CHIIKI_CD
		/*END*/
		/*IF data.KEN_KBN.Value == 2*/
			AND HSTMGA.CHIIKI_CD != SBNMGA.CHIIKI_CD
		/*END*/
	  /*END*/
	  /*IF data.JIGYOUJOU_KBN.Value == 2*/
		AND DTR18.MANIFEST_KBN = 2
	    AND ((
		     DTR13.LAST_SBN_END_DATE IS NOT NULL
			 AND DTR18.SBN_ENDREP_KBN=1
		     AND (ISNULL(DTR18.FIRST_MANIFEST_FLAG,'') = '' OR ISNULL(HSTMGS.JISHA_KBN, 0) = 0)
		     AND (DTR13.LAST_SBN_END_DATE <= CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_END.Value*/20140901, 111), 120) AND CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_BEGIN.Value*/20100901, 111), 120) <= DTR13.LAST_SBN_END_DATE)
			 AND TMR.NEXT_SYSTEM_ID IS NOT NULL
			 AND DTR13EX.LAST_SBN_GYOUSHA_CD = /*data.HOUKOKU_GYOUSHA_CD*/0
		     AND DTR13EX.LAST_SBN_GENBA_CD = /*data.HOUKOKU_GENBA_CD*/0)
		   OR (
		     DTR18.SBN_END_DATE IS NOT NULL
			 AND DTR18.SBN_ENDREP_KBN=2
		     AND (ISNULL(DTR18.FIRST_MANIFEST_FLAG,'') <> '' AND ISNULL(HSTMGS.JISHA_KBN, 0) = 1)
		     AND (DTR18.SBN_END_DATE <= CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_END.Value*/20140901, 111), 120) AND CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_BEGIN.Value*/20100901, 111), 120) <= DTR18.SBN_END_DATE)
		     AND TMR.NEXT_SYSTEM_ID IS NULL
			 AND DTR18.SBN_GYOUSHA_CD = /*data.HOUKOKU_GYOUSHA_CD*/0
		     AND DTR18.SBN_GENBA_CD = /*data.HOUKOKU_GENBA_CD*/0
            ))
        /*IF data.KEN_KBN.Value == 1*/
			AND HSTMGA.CHIIKI_CD = TMUMGA.CHIIKI_CD
		/*END*/
		/*IF data.KEN_KBN.Value == 2*/
			AND HSTMGA.CHIIKI_CD != TMUMGA.CHIIKI_CD
		/*END*/
	  /*END*/
	/*END*/

	/*IF data.GYOUSHA_KBN.Value == 2*/
		/*IF data.JIGYOUJOU_KBN.Value == 1*/
        AND DTR18.SBN_ENDREP_KBN = 2
		AND (DTR18.SBN_END_DATE <= CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_END.Value*/20140901, 111), 120) AND CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_BEGIN.Value*/20100901, 111), 120) <= DTR18.SBN_END_DATE)
		AND DTR18.SBN_END_DATE IS NOT NULL
		AND DTR18.MANIFEST_KBN = 2
		AND (ISNULL(DTR18.FIRST_MANIFEST_FLAG,'') <> '' AND ISNULL(HSTMGS.JISHA_KBN, 0) = 1)
		AND DTR18.SBN_GYOUSHA_CD = /*data.HOUKOKU_GYOUSHA_CD*/0
		AND DTR18.SBN_GENBA_CD = /*data.HOUKOKU_GENBA_CD*/0
		/*IF data.KEN_KBN.Value == 1*/
			AND HSTMGA.CHIIKI_CD = TMUMGA.CHIIKI_CD
		/*END*/
		/*IF data.KEN_KBN.Value == 2*/
			AND HSTMGA.CHIIKI_CD != TMUMGA.CHIIKI_CD
		/*END*/
	  /*END*/

	  /*IF data.JIGYOUJOU_KBN.Value == 2*/
	    AND 
		DTR18.SBN_ENDREP_KBN=2
		AND DTR18.SBN_END_DATE IS NOT NULL
		AND (DTR18.SBN_END_DATE <= CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_END.Value*/20140901, 111), 120) AND CONVERT(DATETIME, CONVERT(NVARCHAR, /*data.DATE_BEGIN.Value*/20100901, 111), 120) <= DTR18.SBN_END_DATE)
		AND DTR18.SBN_GYOUSHA_CD = /*data.HOUKOKU_GYOUSHA_CD*/0
		AND DTR18.SBN_GENBA_CD = /*data.HOUKOKU_GENBA_CD*/0
		AND DTR18.MANIFEST_KBN = 2
		/*IF data.KEN_KBN.Value == 1*/
			AND HSTMGA.CHIIKI_CD = TMUMGA.CHIIKI_CD
		/*END*/
		/*IF data.KEN_KBN.Value == 2*/
			AND HSTMGA.CHIIKI_CD != TMUMGA.CHIIKI_CD
		/*END*/
      /*END*/
	/*END*/
	/*IF data.TOKUBETSU_KANRI_KBN.Value == 1*/
	AND (DTR18.HAIKI_DAI_CODE + DTR18.HAIKI_CHU_CODE + DTR18.HAIKI_SHO_CODE) BETWEEN '0000' AND '6999'
	/*END*/

	/*IF data.TOKUBETSU_KANRI_KBN.Value == 2*/
	AND (DTR18.HAIKI_DAI_CODE + DTR18.HAIKI_CHU_CODE + DTR18.HAIKI_SHO_CODE) BETWEEN '7000' AND '9999'
	/*END*/
/*END*/
ORDER BY SYSTEM_ID, SEQ, KANRI_ID, DEN_SEQ