SELECT 
      CAST(0 AS BIT) AS HENKOU_FLG
    , M_TORIHIKISAKI.TORIHIKISAKI_CD
	, M_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU AS TORIHIKISAKI_NAME1
	, ISNULL(TODO.TODOUFUKEN_NAME,'') + ISNULL(M_TORIHIKISAKI.TORIHIKISAKI_ADDRESS1,'') + ISNULL(M_TORIHIKISAKI.TORIHIKISAKI_ADDRESS2,'') AS TORIHIKISAKI_ADDRESS1
	, M_TORIHIKISAKI.TORIHIKISAKI_TEL
	, M_TORIHIKISAKI.EIGYOU_TANTOU_BUSHO_CD
	, M_BUSHO.BUSHO_NAME_RYAKU
	, M_TORIHIKISAKI.EIGYOU_TANTOU_CD
	, M_SHAIN.SHAIN_NAME_RYAKU
	, M_TORIHIKISAKI.EIGYOU_TANTOU_BUSHO_CD EIGYOU_TANTOU_BUSHO_CD_AFTER
	, M_BUSHO.BUSHO_NAME_RYAKU BUSHO_NAME_RYAKU_AFTER
	, M_TORIHIKISAKI.EIGYOU_TANTOU_CD EIGYOU_TANTOU_CD_AFTER
	, M_SHAIN.SHAIN_NAME_RYAKU SHAIN_NAME_RYAKU_AFTER
	, M_TORIHIKISAKI.EIGYOU_TANTOU_CD EIGYOU_TANTOU_CD_AFTER_OLD
FROM M_TORIHIKISAKI
INNER JOIN M_BUSHO
ON M_TORIHIKISAKI.EIGYOU_TANTOU_BUSHO_CD = M_BUSHO.BUSHO_CD
INNER JOIN M_SHAIN
ON M_TORIHIKISAKI.EIGYOU_TANTOU_CD = M_SHAIN.SHAIN_CD
INNER JOIN M_EIGYOU_TANTOUSHA
ON M_TORIHIKISAKI.EIGYOU_TANTOU_CD = M_EIGYOU_TANTOUSHA.SHAIN_CD
LEFT JOIN M_TODOUFUKEN TODO
ON TODO.TODOUFUKEN_CD = M_TORIHIKISAKI.TORIHIKISAKI_TODOUFUKEN_CD

WHERE M_TORIHIKISAKI.DELETE_FLG = 0
AND M_BUSHO.DELETE_FLG = 0
AND M_BUSHO.DELETE_FLG = 0
AND M_SHAIN.EIGYOU_TANTOU_KBN = 1
/*IF data.EigyouTantouBushoCd != null && data.EigyouTantouBushoCd != ''*/
AND M_TORIHIKISAKI.EIGYOU_TANTOU_BUSHO_CD = /*data.EigyouTantouBushoCd*/
/*END*/
/*IF data.EigyouTantouCd != null && data.EigyouTantouCd != ''*/
AND M_TORIHIKISAKI.EIGYOU_TANTOU_CD = /*data.EigyouTantouCd*/
/*END*/
/*IF data.ToriCd != null && data.ToriCd != ''*/
AND M_TORIHIKISAKI.TORIHIKISAKI_CD LIKE '%' + /*data.ToriCd*/ + '%'
/*END*/
/*IF data.ToriName != null && data.ToriName != ''*/
AND M_TORIHIKISAKI.TORIHIKISAKI_NAME_RYAKU LIKE '%' + /*data.ToriName*/ + '%'
/*END*/
/*IF data.Address != null && data.Address != ''*/
AND (ISNULL(TODO.TODOUFUKEN_NAME,'') + ISNULL(M_TORIHIKISAKI.TORIHIKISAKI_ADDRESS1,'') + ISNULL(M_TORIHIKISAKI.TORIHIKISAKI_ADDRESS1,'')) LIKE '%' + /*data.Address*/ + '%'
/*END*/
/*IF data.Tel != null && data.Tel != ''*/
AND M_TORIHIKISAKI.TORIHIKISAKI_TEL LIKE '%' + /*data.Tel*/ + '%'
/*END*/
/*IF data.BushoCdBf != null && data.BushoCdBf != ''*/
AND M_TORIHIKISAKI.EIGYOU_TANTOU_BUSHO_CD LIKE '%' + /*data.BushoCdBf*/ + '%'
/*END*/
/*IF data.BushoNameBf != null && data.BushoNameBf != ''*/
AND M_BUSHO.BUSHO_NAME_RYAKU LIKE '%' + /*data.BushoNameBf*/ + '%'
/*END*/
/*IF data.TantoushaCdBf != null && data.TantoushaCdBf != ''*/
AND M_TORIHIKISAKI.EIGYOU_TANTOU_CD LIKE '%' + /*data.TantoushaCdBf*/ + '%'
/*END*/
ORDER BY M_TORIHIKISAKI.TORIHIKISAKI_CD