SELECT
    NYUUKIN_NUMBER
FROM T_NYUUKIN_SUM_ENTRY
WHERE NYUUKIN_NUMBER = (
    SELECT MAX(TNSE.NYUUKIN_NUMBER) 
    FROM T_NYUUKIN_SUM_ENTRY TNSE
    LEFT JOIN T_NYUUKIN_ENTRY TNE
    ON TNE.NYUUKIN_SUM_SYSTEM_ID = TNSE.SYSTEM_ID
    AND TNE.SEQ = TNSE.SEQ
    WHERE TNSE.DELETE_FLG = 0
    AND (TNE.TOK_INPUT_KBN IS NULL
        OR TNE.TOK_INPUT_KBN = 1)
    /*IF kyotenCd != ''*/AND (TNSE.KYOTEN_CD = /*kyotenCd*/ OR /*kyotenCd*/ = 99)/*END*/
    /*IF nyuukinNumber != ''*/ AND TNSE.NYUUKIN_NUMBER < /*nyuukinNumber*/0/*END*/)
AND DELETE_FLG = 0