SELECT
    *
FROM
    T_SEIKYUU_DETAIL
    LEFT JOIN
        T_NYUUKIN_KESHIKOMI
    ON  T_SEIKYUU_DETAIL.DENPYOU_NUMBER = T_NYUUKIN_KESHIKOMI.NYUUKIN_NUMBER
    AND T_NYUUKIN_KESHIKOMI.DELETE_FLG = 0
WHERE
    T_SEIKYUU_DETAIL.DENPYOU_SHURUI_CD = 10
AND T_SEIKYUU_DETAIL.DELETE_FLG = 0
AND T_NYUUKIN_KESHIKOMI.SEIKYUU_NUMBER IS NULL
AND T_SEIKYUU_DETAIL.SEIKYUU_NUMBER = /*seikyuuNumber*/0