SELECT
TUSKE.NIZUMI_DATE,
TUSKE.TORIHIKISAKI_CD,
TUSKE.TORIHIKISAKI_NAME,
TUSKE.GYOUSHA_CD,
TUSKE.GYOUSHA_NAME,
TUSKE.GENBA_CD,
TUSKE.GENBA_NAME,
TUSKE.UNPAN_GYOUSHA_CD,
TUSKE.UNPAN_GYOUSHA_NAME,
TUSKE.SHASHU_CD,
TUSKE.SHASHU_NAME,
TUSKE.SHARYOU_CD,
TUSKE.SHARYOU_NAME,
TUSKE.NIZUMI_GENBA_CD,
TUSKE.NIZUMI_GENBA_NAME,
TUSKE.NIZUMI_GYOUSHA_CD,
TUSKE.NIZUMI_GYOUSHA_NAME,
TUSKE.UNTENSHA_CD,
TUSKE.UNTENSHA_NAME,
TUSKE.SAGYOU_DATE,
MHS.HAIKI_SHURUI_CD,
MHS.HAIKI_SHURUI_NAME_RYAKU,
GB.TSUMIKAEHOKAN_KBN,
GB.SHOBUN_NIOROSHI_GENBA_KBN,
TUSKE.SYSTEM_ID,
TUSKD.DETAIL_SYSTEM_ID,
TUSKE.MANIFEST_SHURUI_CD
FROM (SELECT TOP 1 TUSKE.* FROM  T_UKETSUKE_SK_ENTRY TUSKE 
left join T_UKETSUKE_SK_DETAIL TUSKD ON (TUSKE.SYSTEM_ID = TUSKD.SYSTEM_ID AND TUSKE.SEQ = TUSKD.SEQ)
WHERE TUSKE.UKETSUKE_NUMBER = /*data.RENKEI_NO*/0						
AND TUSKE.DELETE_FLG = 0				
/*IF data.RENKEI_GYO_NO != NULL && data.RENKEI_GYO_NO !=''*/
 AND TUSKD.ROW_NO         = /*data.RENKEI_GYO_NO*/0
/*END*/	) TUSKE
left join T_UKETSUKE_SK_DETAIL TUSKD ON (TUSKE.SYSTEM_ID = TUSKD.SYSTEM_ID AND TUSKE.SEQ = TUSKD.SEQ)
left join M_HINMEI MH ON (MH.HINMEI_CD = TUSKD.HINMEI_CD)
left join M_HAIKI_SHURUI MHS ON (MHS.HAIKI_SHURUI_CD = MH.SP_TSUMIKAE_HAIKI_SHURUI_CD
							  AND MHS.HAIKI_KBN_CD = 3)
left join M_GENBA GB ON (TUSKE.GYOUSHA_CD = GB.GYOUSHA_CD
					 AND TUSKE.GENBA_CD = GB.GENBA_CD)
WHERE TUSKE.UKETSUKE_NUMBER = /*data.RENKEI_NO*/0			
AND TUSKE.DELETE_FLG = 0				
/*IF data.RENKEI_GYO_NO != NULL && data.RENKEI_GYO_NO !=''*/
 AND TUSKD.ROW_NO         = /*data.RENKEI_GYO_NO*/0
/*END*/	