SELECT 
TSE.DENPYOU_DATE AS KOHU_DATE,
TSE.TORIHIKISAKI_CD,
TSE.TORIHIKISAKI_NAME,
TSE.GYOUSHA_CD,
TSE.GYOUSHA_NAME,
TSE.UNPAN_GYOUSHA_CD,
TSE.UNPAN_GYOUSHA_NAME,
TSE.SHASHU_CD,
TSE.SHASHU_NAME,
TSE.SHARYOU_CD,
TSE.SHARYOU_NAME,
TSE.NIZUMI_GYOUSHA_CD ,
TSE.NIZUMI_GYOUSHA_NAME,
TSE.NIZUMI_GENBA_CD,
TSE.NIZUMI_GENBA_NAME,
TSE.UNTENSHA_CD,
TSE.UNTENSHA_NAME,
TSE.DENPYOU_DATE AS UNBAN_DATE,
MHS.HAIKI_SHURUI_CD,
MHS.HAIKI_SHURUI_NAME_RYAKU,
GB.TSUMIKAEHOKAN_KBN,
GB.SHOBUN_NIOROSHI_GENBA_KBN,
TSE.GENBA_CD,
TSE.GENBA_NAME,
TSE.SYSTEM_ID,
TSD.DETAIL_SYSTEM_ID,
TSE.MANIFEST_SHURUI_CD
FROM (SELECT TOP 1 TSE.* FROM  T_SHUKKA_ENTRY TSE 
left join T_SHUKKA_DETAIL TSD ON (TSE.SYSTEM_ID = TSD.SYSTEM_ID AND TSE.SEQ = TSD.SEQ)
WHERE TSE.SHUKKA_NUMBER = /*data.RENKEI_NO*/0 							
AND TSE.DELETE_FLG = 0				
/*IF data.RENKEI_GYO_NO != NULL && data.RENKEI_GYO_NO !=''*/
 AND TSD.ROW_NO = /*data.RENKEI_GYO_NO*/0
/*END*/	) TSE
left join T_SHUKKA_DETAIL TSD ON (TSE.SYSTEM_ID = TSD.SYSTEM_ID AND TSE.SEQ = TSD.SEQ)
left join M_HINMEI MH ON (MH.HINMEI_CD = TSD.HINMEI_CD)
left join M_HAIKI_SHURUI MHS ON (MHS.HAIKI_SHURUI_CD = MH.SP_TSUMIKAE_HAIKI_SHURUI_CD
							  AND MHS.HAIKI_KBN_CD = 3)
left join M_GENBA GB ON (TSE.GYOUSHA_CD = GB.GYOUSHA_CD
					 AND TSE.GENBA_CD = GB.GENBA_CD)
WHERE TSE.SHUKKA_NUMBER = /*data.RENKEI_NO*/0 			
AND TSE.DELETE_FLG = 0				
/*IF data.RENKEI_GYO_NO != NULL && data.RENKEI_GYO_NO !=''*/
 AND TSD.ROW_NO = /*data.RENKEI_GYO_NO*/0
/*END*/	