SELECT
TKE.DENPYOU_DATE AS KOHU_DATE,
TKE.TORIHIKISAKI_CD,
TKE.TORIHIKISAKI_NAME,
TKE.GYOUSHA_CD,
TKE.GYOUSHA_NAME,
TKE.GENBA_CD,
TKE.GENBA_NAME,
TKE.UNPAN_GYOUSHA_CD,
TKE.UNPAN_GYOUSHA_NAME,
TKE.SHASHU_CD,
TKE.SHASHU_NAME,
TKE.SHARYOU_CD,
TKE.SHARYOU_NAME,
TKE.NIOROSHI_GENBA_CD,
TKE.NIOROSHI_GENBA_NAME,
TKE.NIOROSHI_GYOUSHA_CD,
TKE.NIOROSHI_GYOUSHA_NAME,
TKE.UNTENSHA_CD,
TKE.UNTENSHA_NAME,
TKE.DENPYOU_DATE AS UNBAN_DATE,
TKE.NIZUMI_GYOUSHA_CD,
TKE.NIZUMI_GYOUSHA_NAME,
TKE.NIZUMI_GENBA_CD,
TKE.NIZUMI_GENBA_NAME,
MHS.HAIKI_SHURUI_CD,
MHS.HAIKI_SHURUI_NAME_RYAKU,
GB.TSUMIKAEHOKAN_KBN,
GB.SHOBUN_NIOROSHI_GENBA_KBN,
TKE.SYSTEM_ID,
TKD.DETAIL_SYSTEM_ID,
TKE.MANIFEST_SHURUI_CD,
TKE.HST_GYOUSHA_CD as HAISYUTU_GYOUSHA_CD,
TKE.HST_GENBA_CD as HAISYUTU_GENBA_CD,
TKE.SBN_GYOUSHA_CD as SYOBUN_GYOUSHA_CD,
TKE.SBN_GENBA_CD as UNPAN_GENBA_CD,
TKE.LAST_SBN_GYOUSHA_CD as LAST_SBN_GYOUSHA_CD,
MG.GYOUSHA_NAME_RYAKU as LAST_SBN_GYOUSHA_NAME,
TKE.LAST_SBN_GENBA_CD as LAST_SBN_GENBA_CD,
MGA.GENBA_NAME_RYAKU as LAST_SBN_GENBA_NAME,
TKE.KIHON_KEIRYOU
FROM (SELECT TOP 1 TKE.* FROM  T_KEIRYOU_ENTRY TKE 
left join T_KEIRYOU_DETAIL TKD ON (TKE.SYSTEM_ID = TKD.SYSTEM_ID AND TKE.SEQ = TKD.SEQ)
WHERE TKE.KEIRYOU_NUMBER = /*data.RENKEI_NO*/0						
AND TKE.DELETE_FLG = 0				
/*IF data.RENKEI_GYO_NO != NULL && data.RENKEI_GYO_NO !=''*/
 AND TKD.ROW_NO = /*data.RENKEI_GYO_NO*/0
/*END*/) TKE
left join T_KEIRYOU_DETAIL TKD ON (TKE.SYSTEM_ID = TKD.SYSTEM_ID AND TKE.SEQ = TKD.SEQ)
left join M_HINMEI MH ON (MH.HINMEI_CD = TKD.HINMEI_CD 
					   AND MH.DELETE_FLG = 0) 
left join M_HAIKI_SHURUI MHS ON (MHS.HAIKI_SHURUI_CD = MH.SP_TSUMIKAE_HAIKI_SHURUI_CD
							  AND MHS.HAIKI_KBN_CD = 3        
                              AND MHS.DELETE_FLG = 0)
left join M_GYOUSHA MG ON (MG.GYOUSHA_CD = TKE.LAST_SBN_GYOUSHA_CD)
left join M_GENBA MGA ON (MGA.GYOUSHA_CD = TKE.LAST_SBN_GYOUSHA_CD
                       AND MGA.GENBA_CD = TKE.LAST_SBN_GENBA_CD)
left join M_GENBA GB ON (
						/*IF data.RENKEI_MANI_FLG == 2*/
						TKE.GYOUSHA_CD = GB.GYOUSHA_CD
						 AND TKE.GENBA_CD = GB.GENBA_CD
						 /*END*/
						 /*IF data.RENKEI_MANI_FLG == 1*/
						 TKE.NIOROSHI_GYOUSHA_CD = GB.GYOUSHA_CD
						 AND TKE.NIOROSHI_GENBA_CD = GB.GENBA_CD
						 /*END*/
						 AND GB.DELETE_FLG = 0 							
						 AND (GB.TEKIYOU_BEGIN <= SYSDATETIME() OR GB.TEKIYOU_BEGIN IS NULL)							
						 AND (GB.TEKIYOU_END >= SYSDATETIME() OR GB.TEKIYOU_END IS NULL))

WHERE TKE.KEIRYOU_NUMBER = /*data.RENKEI_NO*/0		
AND TKE.DELETE_FLG = 0				
/*IF data.RENKEI_GYO_NO != NULL && data.RENKEI_GYO_NO !=''*/
 AND TKD.ROW_NO = /*data.RENKEI_GYO_NO*/0
/*END*/	