SELECT 
TUMKE.SAGYOU_DATE AS KOHU_DATE,
TUMKE.TORIHIKISAKI_CD,
TUMKE.TORIHIKISAKI_NAME,
TUMKE.GYOUSHA_CD,
TUMKE.GYOUSHA_NAME,
TUMKE.GENBA_CD,
TUMKE.GENBA_NAME,
TUMKE.UNPAN_GYOUSHA_CD,
TUMKE.UNPAN_GYOUSHA_NAME,
TUMKE.SHASHU_CD,
TUMKE.SHASHU_NAME,
TUMKE.SHARYOU_CD,
TUMKE.SHARYOU_NAME,
TUMKE.NIOROSHI_GENBA_CD,
TUMKE.NIOROSHI_GENBA_NAME,
TUMKE.NIOROSHI_GYOUSHA_CD,
TUMKE.NIOROSHI_GYOUSHA_NAME,
TUMKE.SAGYOU_DATE AS UNBAN_DATE,
MHS.HAIKI_SHURUI_CD,
MHS.HAIKI_SHURUI_NAME_RYAKU,
GB.TSUMIKAEHOKAN_KBN,
GB.SHOBUN_NIOROSHI_GENBA_KBN,
TUMKE.SYSTEM_ID,
TUMKD.DETAIL_SYSTEM_ID,
TUMKE.MANIFEST_SHURUI_CD AS MANIFEST_SHURUI_CD
FROM (SELECT TOP 1 TUMKE.* FROM  T_UKETSUKE_MK_ENTRY TUMKE 
left join T_UKETSUKE_MK_DETAIL TUMKD ON (TUMKE.SYSTEM_ID = TUMKD.SYSTEM_ID AND TUMKE.SEQ = TUMKD.SEQ)
WHERE TUMKE.UKETSUKE_NUMBER = /*data.RENKEI_NO*/0							
AND TUMKE.DELETE_FLG = 0
/*IF data.RENKEI_GYO_NO != NULL && data.RENKEI_GYO_NO !=''*/
 AND TUMKD.ROW_NO          = /*data.RENKEI_GYO_NO*/0
/*END*/	) TUMKE
left join T_UKETSUKE_MK_DETAIL TUMKD ON (TUMKE.SYSTEM_ID = TUMKD.SYSTEM_ID AND TUMKE.SEQ = TUMKD.SEQ)
left join M_HINMEI MH ON (MH.HINMEI_CD = TUMKD.HINMEI_CD)
left join M_HAIKI_SHURUI MHS ON (MHS.HAIKI_SHURUI_CD = MH.SP_TSUMIKAE_HAIKI_SHURUI_CD
							  AND MHS.HAIKI_KBN_CD = 3)
left join M_GENBA GB ON (TUMKE.NIOROSHI_GYOUSHA_CD = GB.GYOUSHA_CD
					 AND TUMKE.NIOROSHI_GENBA_CD = GB.GENBA_CD)

WHERE TUMKE.UKETSUKE_NUMBER = /*data.RENKEI_NO*/0			
AND TUMKE.DELETE_FLG = 0
/*IF data.RENKEI_GYO_NO != NULL && data.RENKEI_GYO_NO !=''*/
 AND TUMKD.ROW_NO          = /*data.RENKEI_GYO_NO*/0
/*END*/	