SELECT
TKE.DENPYOU_DATE AS KOHU_DATE,
TKE.TORIHIKISAKI_CD,
TKE.TORIHIKISAKI_NAME,
TKE.GYOUSHA_CD,
TKE.GYOUSHA_NAME,
TKE.GENBA_CD,
TKE.GENBA_NAME,
TKE.UNPAN_GYOUSHA_CD,
TKE.UNPAN_GYOUSHA_NAME,
TKE.SHASHU_CD,
TKE.SHASHU_NAME,
TKE.SHARYOU_CD,
TKE.SHARYOU_NAME,
TKE.NIOROSHI_GENBA_CD,
TKE.NIOROSHI_GENBA_NAME,
TKE.NIOROSHI_GYOUSHA_CD,
TKE.NIOROSHI_GYOUSHA_NAME,
TKE.UNTENSHA_CD,
TKE.UNTENSHA_NAME,
TKE.DENPYOU_DATE AS UNBAN_DATE,
TKE.NIZUMI_GYOUSHA_CD,
TKE.NIZUMI_GYOUSHA_NAME,
TKE.NIZUMI_GENBA_CD,
TKE.NIZUMI_GENBA_NAME,
MHS.HAIKI_SHURUI_CD,
MHS.HAIKI_SHURUI_NAME_RYAKU,
GB.TSUMIKAEHOKAN_KBN,
GB.SHOBUN_NIOROSHI_GENBA_KBN,
TKE.SYSTEM_ID,
UJD.DETAIL_SYSTEM_ID as DETAIL_SYSTEM_ID,
TKE.MANIFEST_SHURUI_CD,
TKE.HST_GYOUSHA_CD as HAISYUTU_GYOUSHA_CD,
TKE.HST_GENBA_CD as HAISYUTU_GENBA_CD,
TKE.SBN_GYOUSHA_CD as SYOBUN_GYOUSHA_CD,
TKE.SBN_GENBA_CD as UNPAN_GENBA_CD,
TKE.LAST_SBN_GYOUSHA_CD as LAST_SBN_GYOUSHA_CD,
MG.GYOUSHA_NAME_RYAKU as LAST_SBN_GYOUSHA_NAME,
TKE.LAST_SBN_GENBA_CD as LAST_SBN_GENBA_CD,
MGA.GENBA_NAME_RYAKU as LAST_SBN_GENBA_NAME,
TKE.KIHON_KEIRYOU,
ISNULL(TKE.NET_TOTAL,0) AS NET_TOTAL,
ISNULL(UJD.SUURYOU_WARIAI,0) AS SUURYOU_WARIAI,
M_UNIT.UNIT_NAME
FROM (SELECT TOP 1 TKE.*, UJE.SEQ AS UJE_SEQ, UJD.DETAIL_SEQ AS UJD_DETAIL_SEQ, 3 AS UNIT_CD FROM T_KEIRYOU_ENTRY TKE
left join T_UKEIRE_JISSEKI_ENTRY UJE ON (TKE.SYSTEM_ID = UJE.DENPYOU_SYSTEM_ID AND UJE.DENPYOU_SHURUI = 1 AND UJE.DELETE_FLG = 0)
left join T_UKEIRE_JISSEKI_DETAIL UJD ON (UJE.DENPYOU_SHURUI = UJD.DENPYOU_SHURUI AND UJE.DENPYOU_SYSTEM_ID = UJD.DENPYOU_SYSTEM_ID AND UJE.SEQ = UJD.SEQ)
WHERE TKE.KEIRYOU_NUMBER = /*data.RENKEI_NO*/0						
AND TKE.DELETE_FLG = 0				
/*IF data.RENKEI_GYO_NO != NULL && data.RENKEI_GYO_NO !=''*/
 AND UJD.DETAIL_SEQ = /*data.RENKEI_GYO_NO*/0
/*END*/) TKE
left join T_UKEIRE_JISSEKI_DETAIL UJD ON (TKE.SYSTEM_ID = UJD.DENPYOU_SYSTEM_ID AND TKE.UJE_SEQ = UJD.SEQ AND UJD.DENPYOU_SHURUI = 1)
left join M_HINMEI MH ON (MH.HINMEI_CD = UJD.HINMEI_CD 
					   AND MH.DELETE_FLG = 0) 
left join M_HAIKI_SHURUI MHS ON (MHS.HAIKI_SHURUI_CD = MH.SP_TSUMIKAE_HAIKI_SHURUI_CD
							  AND MHS.HAIKI_KBN_CD = 3        
                              AND MHS.DELETE_FLG = 0)
left join M_GYOUSHA MG ON (MG.GYOUSHA_CD = TKE.LAST_SBN_GYOUSHA_CD)
left join M_GENBA MGA ON (MGA.GYOUSHA_CD = TKE.LAST_SBN_GYOUSHA_CD
                       AND MGA.GENBA_CD = TKE.LAST_SBN_GENBA_CD)
left join M_GENBA GB ON (
						/*IF data.RENKEI_MANI_FLG == 2*/
						TKE.GYOUSHA_CD = GB.GYOUSHA_CD
						 AND TKE.GENBA_CD = GB.GENBA_CD
						 /*END*/
						 /*IF data.RENKEI_MANI_FLG == 1*/
						 TKE.NIOROSHI_GYOUSHA_CD = GB.GYOUSHA_CD
						 AND TKE.NIOROSHI_GENBA_CD = GB.GENBA_CD
						 /*END*/
						 AND GB.DELETE_FLG = 0 							
						 AND (GB.TEKIYOU_BEGIN <= SYSDATETIME() OR GB.TEKIYOU_BEGIN IS NULL)							
						 AND (GB.TEKIYOU_END >= SYSDATETIME() OR GB.TEKIYOU_END IS NULL))
left join M_UNIT ON TKE.UNIT_CD = M_UNIT.UNIT_CD
WHERE TKE.KEIRYOU_NUMBER = /*data.RENKEI_NO*/0		
AND TKE.DELETE_FLG = 0				
/*IF data.RENKEI_GYO_NO != NULL && data.RENKEI_GYO_NO !=''*/
 AND UJD.DETAIL_SEQ = /*data.RENKEI_GYO_NO*/0
/*END*/	
/*IF (data.RENKEI_GYO_NO == NULL || data.RENKEI_GYO_NO == '') && data.CHK_MODE_KBN == 1 */
AND UJD.SUURYOU_WARIAI IS NOT NULL
/*END*/