SELECT 
TMKSH.SYSTEM_ID
,TMKSH.SEQ
,TMKSH.REC_NO
,TMKSH.SHOBUN_HOUHOU_CD
,TMKSH.SHOBUN_HOUHOU_NAME
FROM T_MANIFEST_KP_SBN_HOUHOU TMKSH
WHERE TMKSH.SYSTEM_ID = /*data.SYSTEM_ID*/ AND TMKSH.SEQ =  /*data.SEQ*/