SELECT * FROM dbo.M_ITAKU_KEIYAKU_KIHON
WHERE 
/*IF data.ISNOT_NEED_DELETE_FLG.IsNull || data.ISNOT_NEED_DELETE_FLG.IsFalse*/
 DELETE_FLG = 0
-- ELSE
 1 = 1
/*END*/
/*IF data.SYSTEM_ID != null*/AND SYSTEM_ID = /*data.SYSTEM_ID*//*END*/
/*IF data.ITAKU_KEIYAKU_NO != null*/AND ITAKU_KEIYAKU_NO = /*data.ITAKU_KEIYAKU_NO*//*END*/
/*IF !data.ITAKU_KEIYAKU_SHURUI.IsNull*/AND ITAKU_KEIYAKU_SHURUI = /*data.ITAKU_KEIYAKU_SHURUI.Value*//*END*/
/*IF !data.ITAKU_KEIYAKU_STATUS.IsNull*/AND ITAKU_KEIYAKU_STATUS = /*data.ITAKU_KEIYAKU_STATUS.Value*//*END*/
/*IF data.HAISHUTSU_JIGYOUSHA_CD != null*/AND HAISHUTSU_JIGYOUSHA_CD = /*data.HAISHUTSU_JIGYOUSHA_CD*//*END*/
/*IF data.ITAKU_KEIYAKU_FILE_PATH != null*/AND ITAKU_KEIYAKU_FILE_PATH = /*data.ITAKU_KEIYAKU_FILE_PATH*//*END*/
/*IF !data.KOUSHIN_SHUBETSU.IsNull*/AND KOUSHIN_SHUBETSU = /*data.KOUSHIN_SHUBETSU.Value*//*END*/
/*IF !data.KOUSHIN_END_DATE.IsNull*/AND KOUSHIN_END_DATE = /*data.KOUSHIN_END_DATE.Value*//*END*/
/*IF !data.YUUKOU_BEGIN.IsNull*/AND YUUKOU_BEGIN = /*data.YUUKOU_BEGIN.Value*//*END*/
/*IF !data.YUUKOU_END.IsNull*/AND YUUKOU_END = /*data.YUUKOU_END.Value*//*END*/
/*IF data.SHIHARAI_HOUHOU != null*/AND SHIHARAI_HOUHOU = /*data.SHIHARAI_HOUHOU*//*END*/
/*IF !data.KEIYAKUSHO_CREATE_DATE.IsNull*/AND KEIYAKUSHO_CREATE_DATE = /*data.KEIYAKUSHO_CREATE_DATE.Value*//*END*/
/*IF !data.KEIYAKUSHO_SEND_DATE.IsNull*/AND KEIYAKUSHO_SEND_DATE = /*data.KEIYAKUSHO_SEND_DATE.Value*//*END*/
/*IF !data.KEIYAKUSHO_RETURN_DATE.IsNull*/AND KEIYAKUSHO_RETURN_DATE = /*data.KEIYAKUSHO_RETURN_DATE.Value*//*END*/
/*IF !data.KEIYAKUSHO_END_DATE.IsNull*/AND KEIYAKUSHO_END_DATE = /*data.KEIYAKUSHO_END_DATE.Value*//*END*/
/*IF data.BIKOU1 != null*/AND BIKOU1 = /*data.BIKOU1*//*END*/
/*IF data.BIKOU2 != null*/AND BIKOU2 = /*data.BIKOU2*//*END*/
/*IF !data.ITAKU_KEIYAKU_CHECK.IsNull*/ AND ITAKU_KEIYAKU_CHECK = /*data.ITAKU_KEIYAKU_CHECK*//*END*/
/*IF data.CREATE_USER != null*/AND CREATE_USER = /*data.CREATE_USER*//*END*/
/*IF !data.CREATE_DATE.IsNull*/AND CREATE_DATE = /*data.CREATE_DATE.Value*//*END*/
/*IF data.CREATE_PC != null*/AND CREATE_PC = /*data.CREATE_PC*//*END*/
/*IF data.UPDATE_USER != null*/AND UPDATE_USER = /*data.UPDATE_USER*//*END*/
/*IF !data.UPDATE_DATE.IsNull*/AND UPDATE_DATE = /*data.UPDATE_DATE.Value*//*END*/
/*IF data.UPDATE_PC != null*/AND UPDATE_PC = /*data.UPDATE_PC*//*END*/
