SELECT 
TSE.GYOUSHA_CD,
TSE.GYOUSHA_NAME
FROM 
T_SHUKKA_ENTRY AS TSE 
WHERE 
TSE.DELETE_FLG = 0 
AND TSE.TAIRYUU_KBN = 0 
AND DENPYOU_DATE BETWEEN /*dateFrom*/0 AND /*dateTo*/0
AND TSE.SHARYOU_NAME = /*sharyouName*/0
/*IF !kyotenCd.IsNull*/
AND KYOTEN_CD = /*kyotenCd*/
/*END*/
GROUP BY
TSE.GYOUSHA_CD,
TSE.GYOUSHA_NAME
ORDER BY TSE.GYOUSHA_CD