SELECT DISTINCT LLS.* FROM T_LOGI_LINK_STATUS LLS
LEFT JOIN T_LOGI_DELIVERY_DETAIL LDD on LDD.SYSTEM_ID = LLS.SYSTEM_ID and LDD.DELETE_FLG = 0
WHERE LDD.DENPYOU_ATTR = 2
and LDD.REF_DENPYOU_NO = /*uketsukeNum*/0
and LLS.LINK_STATUS <> 3
and LLS.DELETE_FLG = 0